### ISSUE TITLE
Mageworx Search Autocomplete not working

### ISSUE THREAD

**Issue by ChintanKaneriya** [Smile-SA/elasticsuite#1001]
Hello everyone,

I am using Magento 2.1.7 and this website is using customtheme.

I have installed below extension:
https://www.mageworx.com/magento-2-search-atocomplete-free.html

but it seems that it is not working in front end
### Preconditions

Version: Magento CE 2.1.7
Os: Windows 10

Extension Ver: v2.1.2

### Theme and Extension layout files

here is my customtheme's layout file

app/design/frontend/My_Vendor/My_Theme/Magento_Theme/layout/default.xml

`<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
  <body>
    <referenceBlock name="logo">
      <arguments>
        <argument name="logo_file" xsi:type="string">images/my_logo.png</argument>
        <argument name="logo_img_width" xsi:type="number">300</argument>
        <argument name="logo_img_height" xsi:type="number">300</argument>
      </arguments>
    </referenceBlock>
       
    <referenceContainer name="page.wrapper">
      <container name="top_custom_links_wrapper" htmlClass="topbar clearfix" htmlTag="div" before="-">
        <block class="Magento\Framework\View\Element\Template" name="top_custom_links" template="Magento_Theme::html/top_links.phtml" />
      </container>
      <container name="header_after_toplinks_wrapper"  after="top_custom_links_wrapper">
        <block class="Magento\Framework\View\Element\Template" name="header_after_toplinks" template="Magento_Theme::html/custom_header.phtml" >
          <block class="Magento\Theme\Block\Html\Header\Logo" name="logo">
            <arguments>
              <argument name="logo_img_width" xsi:type="number">270</argument>
              <argument name="logo_img_height" xsi:type="number">84</argument>
            </arguments>
          </block>
          <block class="Magento\Framework\View\Element\Template" name="top.search" as="topSearch" template="Magento_Search::form.mini.phtml" />
        </block>
      </container>
    </referenceContainer>
    
        
    
	  
	<move element="minicart" destination="header_after_toplinks"/>
    <referenceContainer name="header.panel" remove="true"/>
    <referenceContainer name="header-wrapper" remove="true"/>
    
    
    
    <move element="breadcrumbs" destination="main.content" before="-" />
    <referenceContainer name="footer" remove="true"/>
    <referenceContainer name="footer-container">
      <block class="Magento\Theme\Block\Html\Footer" name="footer_block" template="html/footer.phtml">
        <block class="Magento\Newsletter\Block\Subscribe" name="custom_subscribe" template="subscribe_footer.phtml" />
        
        
        
      </block>
    </referenceContainer>
  </body>
</page>
`

here is extension's layout file:

`
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <head>
        <css src="MageWorx_SearchSuiteAutocomplete::css/searchsuiteautocomplete.css"/>
    </head>
    <body>
        <referenceBlock name="top.search">
            <block class="MageWorx\SearchSuiteAutocomplete\Block\Autocomplete" name="mageworx-wrapper" template="MageWorx_SearchSuiteAutocomplete::autocomplete.phtml" />
        </referenceBlock>
    </body>
</page>
`

### Expected result

 i think that i have to change the class for block "top.search" in theme's layout file but not sure about it 

### Actual result

search is not showing any result in front end

**Comment by romainruaud** [comment]
Hello @ChintanKaneriya 

I did not dig into the Mageworx extension source code, but it's likely unprobable that you can have both this one and Elasticsuite on your website.

If you change the "top.search" block to use the ElasticSuite one, there is no point on keeping Mageworx extension since it would never get called.

That being said, supporting third party paid extension is not part of our community support commitment. You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards

**Comment by ChintanKaneriya** [comment]
Thank You @romainruaud and I am sorry for inconvenience. I am new to the git hub so I don't know about community's rules.

**Comment by Topor68** [comment]
how did you fix the error? @ChintanKaneriya
