### ISSUE TITLE
Attribute with Custom Source Model and Layered Navigation

### ISSUE THREAD

**Issue by mcyrulik** [Smile-SA/elasticsuite#1004]
### Preconditions

Magento Version : 2.2.4

ElasticSuite Version : 2.5.12

Environment : Developer and production

Third party modules : Several, but the one at odds here is uNirgy Dropship Vendor

### Steps to reproduce

1. Create a product attribute with a custom source model
2. Add that attribute to the Layered Nav (Filterable with results)
3. Reindex

### Expected result

1. Attribute shows up in the layered navigation.

### Actual result

1. Attribute does not show up in layered nav.

I have reported this before, and as it's a custom source model, it was determined that this was an issue with the custom source model.

I know that the source model works with the layered navigation. If we change the Search Appliance back to Mysql and re-index, the attribute shows up. This would lead me to believe that Elasticsuite is accessing the source model in a way that the source model does not like. 

I understand that this is my issue to fix, but my client really would like us to figure this out. I am willing to customize/extend the Elasticsuite code to get our custom source model to show up. 

What I am hoping for is a little help in determining where in the ElasticSuite code the options for the Layered nav are generated so that I could work backwards to figure out what about the source model would need to be adjusted make ElasticSuite pick up these options appropriately.

**Comment by romainruaud** [comment]
Hello @mcyrulik and thank you for giving our module a try.

Could you please post a screenshot of : 

- how is your attribute configured in the Back-Office
- how it looks like in the `eav_attribute` and `catalog_eav_attribute` table ?

Regards

**Comment by romainruaud** [comment]
Closed due to being inactive / not answered for more than 1 month.

Regards
