### ISSUE TITLE
Demo shop: search and pages with products not accessible

### ISSUE THREAD

**Issue by simonrl** [Smile-SA/elasticsuite#1008]
In the demo shop linked in the Readme, the search functionality does not work. CMS pages and category pages without a product listing are accessible. Search result pages and category pages with a product listing throw an exception.

### Steps to reproduce
1. Go to demo store
2. Enter a search term and press enter
3. OR navigate to a 2nd level category page such as this one: http://demo.magento-elastic-suite.io/index.php/women/tops-women/hoodies-and-sweatshirts-women.html

### Expected result
1. the search result page shows
2. OR the category page shows

### Actual result
1. The Magento error page is shown, with a message such as:
There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: 1167320596154

**Comment by romainruaud** [comment]
Hello @simonrl 

You are right, there was a system issue on the demo server.

I just fixed it, should work normally now.

Thank you for pointing it to me,

Regards

**Comment by KAB8609** [comment]
Looks like the demo store is down again.

See screenshot.
![screen shot 2018-07-20 at 3 33 29 pm](https://user-images.githubusercontent.com/993468/43021685-89d9013e-8c32-11e8-889b-12ba824843a6.png)
