### ISSUE TITLE
How to allow "-" to be searchable?

### ISSUE THREAD

**Issue by pankajpragma** [Smile-SA/elasticsuite#1011]
Hi,

For example a product name "Anti-Phospho-TGFBR1 (S165) Polyclonal Antibody".

It doesn't appear in the search results when I search for "TGFBR1" but if I rename the product name by replacing "-" with space "Anti Phospho TGFBR1 (S165) Polyclonal Antibody", then it appears in the results.

However, I can't remove the "-" from all products because they make sense with the product name or SKU.

Is there any way to let elastic search ignore "-" while indexing and searching?

**Comment by afoucret** [comment]
Should be fixed by PR #1022

**Comment by simonrl** [comment]
Hi,

any idea how I implement only the changes from https://github.com/Smile-SA/elasticsuite/pull/1022 without updating to the latest version?

I tried defining the analyzers with new params in my own `elasticsuite_analysis.xml` file in a new module, but get the error message that multiple nodes have been found for `/analysis/analyzers/analyzer[@name='standard' and @language='default']/filters/filter`

Thanks

**Comment by rbayet** [comment]
Hi @simonrl,

Could you open a new issue with your question, all the while referencing this one ?
Posting in an issue closed for months is a recipe for us to miss your comment/question, due to over-abundance of github notifications from third party repositories.

Regards,
