### ISSUE TITLE
Module Elasticsuite_Catalog InstallSchema

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/elasticsuite#102]
There is a useless constructor in Smile\ElasticsuiteCatalog\Setup\InstallSchema class :

    /**
     * InstallSchema constructor.
     *
     * @param \Magento\Eav\Setup\EavSetup $eavSetup The EAV Setup
     */
    public function __construct(EavSetup $eavSetup)
    {
        $this->eavSetup = $eavSetup;
    }

The constructor initiate a never used var and causes errors when installing magento with elasticsuite.

**Comment by romainruaud** [comment]
@AymericJoubert we will fix this really soon.

Could you please detail the error which is occuring ? I do not think I have already faced it.

Regards,
