### ISSUE TITLE
How to include flat table(sku,componentName,casNumber)?

### ISSUE THREAD

**Issue by sivajik34** [Smile-SA/elasticsuite#1023]
I want to search with 2 things for example.
1.ComponentName 2. CASNUMBER
these 2 things not existed as Product attributes.
we have flat table with 3 columns(sku,componentName,casNumber).

so user should be able to search with above 2 fields?
In which file i can include this flat table?

**Comment by romainruaud** [comment]
Hello @sivajik34 

Did you read the dev docs ? 

The part about **DataSources** is the one that will cover your needs : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#data-sources

Regards
