### ISSUE TITLE
Add attribute code to Category -> Display Settings in Admin Panel

### ISSUE THREAD

**Issue by adamrandazzo** [Smile-SA/elasticsuite#1026]
Hi All -

I have a use case where I need to add the attribute code to the `Catalog -> Category -> Display Settings -> Layered Navigation Filters` area (see screenshot). If someone can point me in the right direction where I can find this code, I would appreciate it. If others find it useful, I can certainly create a PR.

![djr73ixxoacyvqd](https://user-images.githubusercontent.com/8340768/43720636-a95f68d4-995e-11e8-97eb-f3698b4d7e47.jpg)

Thank you

**Comment by romainruaud** [comment]
Hello @adamrandazzo 

Attributes that are shown here are just attributes which are set to "Use in Layered Navigation : Yes" when you access an attribute configuration screen via **Stores > Attributes > Product** 

Regards

**Comment by adamrandazzo** [comment]
Hi @romainruaud - I understand which attributes show up there. However, I need to actually see the attribute_code, not just the attribute name in the display. 

For example, we have several distinct "Size" attributes for our store because there are so many different product lines. For those, we need to see the code, like `hook_size`, `bracket_size`, etc. I am just looking on how to add the actual code there for attributes that are displayed.

Thanks

**Comment by romainruaud** [comment]
Oh ok,

well then you might want to hookup on the UI component which is here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/view/adminhtml/ui_component/category_form.xml#L34

and his data provider which is here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php#L95

Regards

**Comment by adamrandazzo** [comment]
That is what I was looking for! thank you!
