### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by kinexvikas** [Smile-SA/elasticsuite#1027]
Hi, I am getting errors during elasticsuite setup on Magento Cloud EE. 

### Preconditions

Magento Version : 2.2.4 EE Cloud

ElasticSuite Version :2.5

Environment : Production

Third party modules : No

### Steps to reproduce

1. Steps given in https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall
2. After this getting error **_"There is no such adapter: elasticsuite"_** when i click on front-end categories.
3.  bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker
4. bin/magento setup:upgrade
5.  After issuing above commands getting error **_"No alive nodes found in your cluster"_**

### Expected result

1. Elastic suite should be installed properly
 

### Actual result

1.  There is no such adapter: elasticsuite"

2. Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

Please look into this.

Thank You

**Comment by kinexvikas** [comment]
Hi @romainruaud 

I tried with Elastic Search 2.4 with Elastic Suite 2.5  only.

**Comment by romainruaud** [comment]
@kinexvikas I am speaking about this deprecated method : https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#deprecated-solution--by-using-a-module-embedding-the-configuration

**Comment by romainruaud** [comment]
@kinexvikas how did you create these two files ? You have to create them under app/code/MyNameSpace/Mymodule as you would do for a new magento module.

**Comment by kinexvikas** [comment]
@romainruaud I did this in the same way as we do in creating new module.

**Comment by romainruaud** [comment]
Hmm ok I think I foud it. Variable name was mis-typed on the Wiki.

Please try to add this variable to your project : 

`CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__SERVERS=elasticsearch.internal`

instead of CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__ES_HOSTS which was indeed wrong.

**Comment by romainruaud** [comment]
I found that you just have to add the variable at the end of the `.magento.app.yaml` file which is easier to do : 

```yaml
variables:
  env:
    CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__SERVERS: 'elasticsearch.internal'
```

**Comment by kinexvikas** [comment]
@romainruaud It's working now. Thank You!

**Comment by kinexvikas** [comment]
Hi @romainruaud 
There are different elastic search hosts for integration and staging environments like elasticsearch.internal for integration and localhost for staging and production environments.  How can we configure environment specific these hosts in .magento.app.yaml file ?  
Thank You!
