### ISSUE TITLE
No products in categories since Smile suite uninstall

### ISSUE THREAD

**Issue by adamrandazzo** [Smile-SA/elasticsuite#1029]
I was testing the extensions on my dev site and unfortunately I don't believe the extension is going to work for us. 

- Magento 2.2.4 + B2B
- The modules were installed / uninstalled via composer.
- I also had the B2B module installed for the shared catalog
- I followed the uninstall directions in the README and cleaned up the database - there were no issues with it.
- I have cleared generated/ all caches, recompiled di, etc.
- I am not seeing any errors, the products simply do not show

Best,

Adam

**Comment by romainruaud** [comment]
Hello @adamrandazzo 

You probably have also to check which search engine is set now that Elasticsuite is uninstalled : via **Stores > Configuration > Catalog > Catalog Search > Engine**.

It should be set back to MySQL full text or standard Magento Elasticsearch.

Please ensure it's properly set, then trigger a full reindex via `bin/magento index:reindex`.

Regards
