### ISSUE TITLE
Not detect enablePhoneticSearch correctly

### ISSUE THREAD

**Issue by tua** [Smile-SA/elasticsuite#1031]
When disable Phonetic at backend, $this->enablePhoneticSearch is false instead of null. Correct me if anything i missed. Thanks.
 
https://github.com/Smile-SA/elasticsuite/blob/9decad3ca084adc574900867b4a374e98ef35140/src/module-elasticsuite-core/Search/Request/ContainerConfiguration/RelevanceConfig.php#L145

**Comment by romainruaud** [comment]
You are right,

I pushed PR #1040 to fix this one.

Thank you for reporting it

**Comment by afoucret** [comment]
PR #1040 have been merged and will be part of the next bugfix release.
