### ISSUE TITLE
Question: difference between expansion and synonyms in Thesaurus

### ISSUE THREAD

**Issue by simonrl** [Smile-SA/elasticsuite#1032]
Hi,

first, thanks for this extension.

Also sorry if my question is documented somewhere.

I searched the docs, for example here: https://github.com/Smile-SA/elasticsuite/wiki/ThesaurusAdministration and here: https://www.elastic.co/guide/en/elasticsearch/guide/current/synonyms-expand-or-contract.html, and still could not find an answer:

What is the difference if I create a "Synonyms"-Thesaurus vs. a "Expansion"-Thesaurus in the Magento backend?

The configuration possibilities seem to be about the same.

Also, the query outlined in the Elasticsuite docs linked above doesn't show - in my opinion - how these types are handled differently: the words are replaced by the synonyms, and are in an equal manner replaced by the expansion.

It would be nice to get an answer or further links to read.

Thanks!

**Comment by romainruaud** [comment]
Hello @simonrl 

Please refer to the User Guide which is a bit more detailed than the project wiki, the part about thesaurus begins on page 11 : https://github.com/Smile-SA/elasticsuite/blob/master/doc/static/User%20Guide-ElasticSuite%20for%20Magento%202-v2.5.pdf

Regards
