### ISSUE TITLE
Product Attribute Admin Sort Not Working With Options that have "

### ISSUE THREAD

**Issue by mdroidian** [Smile-SA/elasticsuite#1037]
If a Product Attribute has Options with quotes in them (IE - 3", 2-1/2") then Admin Sort does not work.

I've tested this on our Magento installation, as well as a separate default Luma.
Same issue applies on Category or Search with same product results.

I've re-indexed, cleared cache, and double-checked the db 'facet_sort_order' is indeed '_manual'

### Preconditions

Magento Version : 2.2.3 EE

ElasticSuite Version : 2.5.10
Elasticsearch Version : 2.4.6

Environment : Developer

Third party modules :

### Steps to reproduce

1. Create Product Attribute, Dropdown

2. Storefront Properties
Use in Layered Navigation -> Filterable(with results)
Use In Search Results Layered Navigation -> Yes
Facet sort order -> Admin sort

3. Add options
5, 1/32", 1/16", 1/4", 1/2", 1", T40, Universal, 1', 2', 2-1/2'

4. Add attribute to products.

5. Search or View Category with said products/attribute.

### Expected result

1. Sort Order is same as Admin

### Actual result

1. Sort Order seems random.  Does not follow sort order in admin/db.
Screenshots show what looks like 'Count', but with multiple tests it has varied.
![sc2](https://user-images.githubusercontent.com/3792666/44171848-a1832600-a098-11e8-99d1-0d35389616aa.JPG)
![sc1](https://user-images.githubusercontent.com/3792666/44171849-a1832600-a098-11e8-88d1-cfbb69fd2784.JPG)

sc1.jpg (backend)
sc2.jpg (frontend)

**Comment by romainruaud** [comment]
Confirmed. I reproduce this one on latest Elasticsuite.

Attributes without any quotes in option values are still sorted properly when using "Admin Sort".

Will dig more into this one.

Thank you for reporting it.

**Comment by afoucret** [comment]
PR #1039 have been merged and will be part of the next bugfix release.
