### ISSUE TITLE
How to: Remove display of Facet Attribute when all products have same option. 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1042]
### Preconditions
Facet Navigation has products which only contain products of 1 value 

Magento Version : 2.2.5 

ElasticSuite Version : Latest

Environment : Either 

### Steps to reproduce

1. Install Elastic Suite
2. Create layered navigation attribute
3. Assign the same option value of this attribute to all products of a category 

### Expected result

1. When only 1 option is available for a given attribute remove it from the display.

### Actual result
See "Shop by Size" and "Shop by Material", there are 25 products in the category and they all have the same value. 
<img width="690" alt="screen shot 2018-08-21 at 5 13 02 pm" src="https://user-images.githubusercontent.com/7387019/44431900-7c455a80-a565-11e8-84f8-7a23660c572f.png">

As you can see this attribute displays, while it can be removed by editing the category settings directly in the admin of this specific category is this the assumed best approach to solve this?

**Comment by romainruaud** [comment]
Hello @duffner 

yes, you are right, actually the best way to prevent such an attribute from being displayed is to force-hide it directly in the category.

Maybe we could deal with it by the code to also hide such attributes automatically (if they have only one filter with a value equals to the amount of product currently matched).

Regards

**Comment by duffner** [comment]
@romainruaud, thank you for the update.  I believe this should be configurable on the attribute level as a boolean maybe that indicates if facet percentage is 100% of one option then it should be removed.  

I believe Magento handles this differently but poorly. In early versions of Magento 2 if you have a category of 50 products and you have an attribute of "Shop by Color" and 25 have the "Black" option value assigned and 25 are empty Magento will remove this option. In this case "Shop by Color" would still be applicable as there are technically two options for color "Black" and "False".  I'm not sure if Magento changed this behavior in later versions but it's something to watch out for. 

Thanks for the quite response - Robert

**Comment by afoucret** [comment]
Hi @duffner,

PR #1051 should improve the facets selection mechanism in a way that should fix this issue.
We plan to release it as part of the upcoming next major release 2.6.0.

BR,
