### ISSUE TITLE
rangeslider.js 404 error?

### ISSUE THREAD

**Issue by ctaulborg** [Smile-SA/elasticsuite#1062]
When loading a product listings page, a JS 404 error is being thrown for 'https://someclient.com/static/frontend/someclient/someclient-theme/en_US/rangeSlider.js.  Attempting to completely remove the extension and reinstalling doesn't seem to help.

### Preconditions

Magento Version : Magento CE 2.2.5

ElasticSuite Version : 2.6.0

Environment : Production

Third party modules : 
Amasty_Base
Amasty_CommonRules
Amasty_Conditions
Amasty_Feed
Amasty_Groupcat
Amasty_Number
Amasty_Payrestriction
Amazon_Core
Amazon_Login
Amazon_Payment
Apptrian_FacebookPixel
Bss_ExportColumn
Bss_Reindex
Cminds_MultiUserAccounts
Codisto_Connect
Dotdigitalgroup_Email
Ebizmarts_MailChimp
Klarna_Core
Klarna_Kp
Klarna_Ordermanagement
LiveChat_LiveChat
MageMojo_Cron
MageWorx_HtmlSitemap
MageWorx_SeoAll
MageWorx_SeoBase
MageWorx_SeoBreadcrumbs
MageWorx_SeoCrossLinks
MageWorx_SeoExtended
MageWorx_SeoMarkup
MageWorx_SeoRedirects
MageWorx_SeoUrls
MageWorx_SeoXTemplates
MageWorx_XmlSitemap
Magebees_Urlrewrite
Magefan_Blog
OlegKoval_RegenerateUrlRewrites
ParadoxLabs_Authnetcim
ParadoxLabs_TokenBase
SafeMage_Extensions
SafeMage_UrlOptimization
Shopial_Facebook
Temando_Shipping
Unirgy_RapidFlow
Unirgy_RapidFlowPro
Unirgy_SimpleLicense
Unirgy_SimpleUp
WeltPixel_Backend
WeltPixel_GoogleTagManager
Yotpo_Yotpo

### Steps to reproduce

php bin/magento maintenance:enable
php bin/magento module:disable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker
composer remove smile/elasticsuite
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
php bin/magento cache:clean
php bin/magento cache:flush

composer clearcache
composer require smile/elasticsuite
php bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
php bin/magento cache:clean
php bin/magento cache:flush

php bin/magento index:reindex catalogsearch_fulltext
php bin/magento index:reindex elasticsuite_categories_fulltext
php bin/magento index:reindex elasticsuite_thesaurus

php bin/magento maintenance:disable

### Expected result

JS error should be resolved with newest version.

### Actual result

404 still occurs on rangeSlider.js.

**Comment by afoucret** [comment]
The problem seems to be in your theme and you will need to find and remove occurences of 'rangeSlider' in it.

The original file is shipped with Smile_ElasticsuiteCatalog so it's not a big surprise to see the file missing when you remove the extension.

IMHO, not an ElasticSuite issue but an issue in the theme.
