### ISSUE TITLE
Wrong products in category

### ISSUE THREAD

**Issue by Tjitse-E** [Smile-SA/elasticsuite#1067]
Hi,

I'm facing a problem with Elasticsuite/Elastic; some of the deeper categories have the wrong products. I'm using:

- Magento 2.2.5
- PHP 7.1
- smile/elasticsuite 2.6.1
- Elastic 5.6.10

The problem on the frontend:
![elektromotor_accessoires_-_rubberbootshop_nl-2-2](https://user-images.githubusercontent.com/14849044/45301501-65b17400-b511-11e8-8253-40f696a9a91b.png)

The number of products is 617, according to the product count on the frontend. However, when I check the backend and the database, there are only 64 products in this particular category. 

![elektromotor_accessoires__id__677____categories___inventory___catalog___magento_admin](https://user-images.githubusercontent.com/14849044/45299481-0d2ba800-b50c-11e8-89e4-e3eaeacd7b86.png)

I'm not sure if the problem is related to elasticsuite, but it is definitely related to elastic. If I disable Elasticsuite and reindex Magento the issue is fixed.

What I've tried so far:
- Resetting and reindexing the indexes
- Removing the Magento 2 elastic indices and rebuilding them.

After following the request with xdebug, I it seems that the request done by Elasticsuite is correct, but that the wrong products are returned by Elastic.

![evaluate_en_504_gateway_time-out](https://user-images.githubusercontent.com/14849044/45301350-11a68f80-b511-11e8-9c25-9f070af62e72.png)

What's the best way to further investigate this issue?

**Comment by Tjitse-E** [comment]
I've found out that if I query elastic directly for products with category id = 677, elastic returns the correct result. So there must be a bug somewhere in the elasticsuite query.

**Comment by Tjitse-E** [comment]
Ok we've solved this problem. It turned out that our client was using a third party import module that changed the category value of `in_anchor` to false. Changing all the `in_anchor` values to true solved the problem.

**Comment by romainruaud** [comment]
Glad to see you managed to fix it.

And yes, by design, with Elasticsuite, all categories are set to `is_anchor=1` but of course, this can be dismantled by third party modules as it's the case on your instance.

Regards
