### ISSUE TITLE
Sku's With Dashes Not WOrking

### ISSUE THREAD

**Issue by JerrodDavenport** [Smile-SA/elasticsuite#1071]
We have several SKU's with dashes in them "-".  When searching for any sku with a dash, the search results is always empty.

### Preconditions

Magento Version : Version 2.1.9 EE

ElasticSuite Version : 2.6

Environment : Production 

Third party modules :

### Steps to reproduce

1. Simply search for a SKU with a dash in it.  Ex.  AA-100MM
2.
3.

### Expected result

1. I would expect the search to find products with dashes in them.

### Actual result

1.  Empty Page

**Comment by afoucret** [comment]
Hi @JerrodDavenport, 

I am not able to reproduce your issue.
Are you sure you are using ElasticSuite 2.6.x (seems to me strange because it should not be compatible with Magento 2.1.x) ?

BR,

**Comment by romainruaud** [comment]
Closed for being inactive / not answered for way too long (22 days).
