### ISSUE TITLE
Products disappear from category after update products' attributes

### ISSUE THREAD

**Issue by asprada** [Smile-SA/elasticsuite#1075]
I use Magento 2 EE (v2.2.5) with multiple websites (1 website and store view for 1 country). Each country has about 600 products with own price in local currency. After updating lots of products' attributes (by csv import or attribute repository) I discovered that during elasticsearch reindexation process (scheduled in cron_schedule table every 1 minute) products disappearing from each category for couple of seconds. After reindexation everything back to normal. I use the latest version of module but I encountered the same issue in elasticsuite version 2.5.13.

### Preconditions

Magento Version : 2.2.5 EE

ElasticSuite Version : 2.6.1

ElasticSearch Version: 5.6.7

Environment : Production mode

Third party modules : Fastly

### Steps to reproduce

1. Create min. 2 websites with 1 store view each.
2. Create some categories in each store view.
3. Add to each store view more than 500 products and assign those to categories.
4. Make sure that magento cron running properly and new items are appearing in cron_schedule table.
5. Change attribute value for all products in each store view (use e.g. magento default csv data importer: System > Data Transfer > Import)
6. During reindexation proces keep refreshing one of your category and wait for the issue I mentioned.

### Actual result

1. Products disappear for a while in the category.
![image 1](https://user-images.githubusercontent.com/6390698/45426733-59f2b880-b69d-11e8-9089-af363eeb6a76.png)

**Comment by atolodas** [comment]
Confirm. After migration from 1.9 same problem.

**Comment by romainruaud** [comment]
Hello @asprada 

Did you investigate more ? I'm wondering especially about the Magento CSV import, maybe it's doing something wrong like flushing the category/product table or something like this during the process, prior to rebuilding it after.

Could you give a try to your use case with a legacy Magento without elasticsuite and check if you are having the same issue ? 

Regards

**Comment by romainruaud** [comment]
Closed for being stale for way too long.
