### ISSUE TITLE
config / env settings

### ISSUE THREAD

**Issue by julienanquetil** [Smile-SA/elasticsuite#1080]
With the new command of Magento (app:config:dump) the elastic search configuration is dumped in "config.php"

for me it make more sens to have it on "env.php" because the elastic config (ip, port...) is more related to the environment (prod / pre prod...) ?

perhaps I'am wrong ?
Thanks
### Preconditions

Magento Version : 2.2.5

ElasticSuite Version : 2.6.1

Environment : Dev & prod

Third party modules : not related

**Comment by romainruaud** [comment]
@julienanquetil 

For me it would be the case if you use the ``--lock-env`` (for Magento >2.2.4) parameter.

See : https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-config-mgmt-set.html

Have you a more detailed scenario about what you are trying to achieve ?

Regards

**Comment by julienanquetil** [comment]
Thanks that's right !!!.

My goal is to have the same "config" from dev to prod except serveur IP so everything related to env into env.php and other in config.php.
I miss the "lock-env" parameter, so with this one everything is fine on my side.
Thanks

**Comment by romainruaud** [comment]
No problem, this part of Magento is quite obscure and is often refactorised by them (the lock-env did appear in 2.2.4 ...).

I close this ticket since you said that everything is fine on your side now :)
