### ISSUE TITLE
Flipping Attribute Set on the product edit page also enables the product toggle

### ISSUE THREAD

**Issue by qgor** [Smile-SA/elasticsuite#1081]
Not sure is this a bug or is it intended when changing the Attribute Set, it also toggles the Product Enable flag to active when managing the product using the Product Edit page in back office.

I can not replicate this behaviour on the instances that do not have this extension installed.

### Preconditions

Environment is hosted on Magento Cloud 

Magento Version : Cloud 2.2.5

ElasticSuite Version : 2.6.1

Environment : production

Third party modules :

        'PHPCuong_Faq' => 1,
        'Plumrocket_Base' => 1,
        'Plumrocket_Amp' => 1,
        'Plumrocket_SizeChart' => 1,
        'Smile_ElasticsuiteCore' => 1,
        'Smile_ElasticsuiteCatalog' => 1,
        'Smile_ElasticsuiteCatalogRule' => 1,
        'Smile_ElasticsuiteCms' => 1,
        'Smile_ElasticsuiteCatalogOptimizer' => 1,
        'Smile_ElasticsuiteSharedCatalog' => 1,
        'Smile_ElasticsuiteSwatches' => 1,
        'Smile_ElasticsuiteThesaurus' => 1,
        'Smile_ElasticsuiteTracker' => 1,
        'Smile_ElasticsuiteVirtualCategory' => 1,
        'Ves_All' => 1,
        'Ves_ImageSlider' => 1,
        'Ves_Megamenu' => 1,
        'Ves_Setup' => 1,

### Steps to reproduce

1. Log into admin back office; 
2. Select a product from Catalog, Product in the Product Listing that's has Attribute Set to "Default" and Enable Product to "Disabled"; 
3. Make an update to the Attribute Set, for example "General"; 
4. Enable Product flag is initially "No" changes to "Yes" after the loading shield is lifted. 

### Expected result

1. Enable Product flag remains unchanged

### Actual result

1. Enable Product flag is initially "No" changes to "Yes".
2. If initially "Yes" it remains "Yes", which is fine. 

![product-attribute-set-1](https://user-images.githubusercontent.com/1244739/45558410-d86e6800-b80d-11e8-9c94-f15962ed0382.png)

![product-attribute-set-2](https://user-images.githubusercontent.com/1244739/45558423-df957600-b80d-11e8-99c6-d3a9a64d14ff.png)

**Comment by romainruaud** [comment]
Hello @qgor 

This bug is not related to Elasticsuite : we do not have anything plugged on the product edit page.

Please submit your issue on the Magento Github directly.

Regards
