### ISSUE TITLE
Catalog Search indexer and ElasticSuite Category Indexing indexer process unknown error:

### ISSUE THREAD

**Issue by arjunkoid** [Smile-SA/elasticsuite#1087]
When run the bin/magento indexer:reindex command got following issue
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}

### Preconditions

Magento Version :2.2.3

ElasticSuite Version : ^2.4

Environment : production

Third party modules :

### Steps to reproduce

1. Go to magento CLI
2. Run php bin/magento indexer: reindex
3. Gives error on terminal

### Expected result

Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
ElasticSuite Category index has been rebuilt successfully in 00:00:00

### Actual result

1. [Screenshot, logs]
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:08
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:01
![image](https://user-images.githubusercontent.com/1737615/45816558-e91e5280-bcd3-11e8-8a08-138f385be3d2.png)

**Comment by romainruaud** [comment]
It looks like an issue related to the Elasticsearch version. With `elasticsuite ^2.4` you have probably migrated to latest 2.6 version without noticing. 

Please give me the output of the following commands : 

`` composer info | grep elastic ``

`` curl http://localhost:9200 ``

**Comment by romainruaud** [comment]
I close this issue for being inactive/unanswered for 2 weeks.

As I said, you probably have to migrate to Elasticsearch 6.x if you are actually using latest version of Elasticsuite.

Regards

**Comment by edward-simpson** [comment]
I too am having this issue, versions:

elasticsearch/elasticsearch       v5.3.2      PHP Client for Elasticsearch
magento/module-elasticsearch 100.2.5    N/A
smile/elasticsuite                        2.6.2      Magento 2 merchandising and search engine built on ElasticSearch 
smile/module-elasticsuite-cms-search              2.2.0              Smile Elasticsuite - Cms Pages Search Module for Smile Elasticsuite.

**Comment by r0umi** [comment]
Hello,
I've got the same issue too.

**Preconditions :** 
Magento Version :2.2.6
ElasticSuite Version : 2.6.4
ElasticSearch Version : 5.3.2

**Steps to reproduce : **
Go to magento CLI
Run php bin/magento indexer: reindex
Gives error on terminal

**Expected result : **
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:01
Product Flat Data index has been rebuilt successfully in 00:00:03
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:02
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:03
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
Warehouse index has been rebuilt successfully in 00:00:01
ElasticSuite Category Index has been rebuilt successfully in 00:00:00
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00

**Actual result : **
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:01
Product Flat Data index has been rebuilt successfully in 00:00:03
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:02
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:03
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
Warehouse index has been rebuilt successfully in 00:00:01
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00

 **composer info | grep elastic :** 
elasticsearch/elasticsearch           v5.3.2             PHP Client for Elasticsearch
magento/module-elasticsearch    100.2.5            N/A
smile/elasticsuite                            2.6.4              Magento 2 merchandising and search engine built on ElasticSearch

**curl elasticsearch.internal:9200 :** 
{
  "name" : "XcCSCAf",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "_8WfXM3mSw2-vs4el0ftvw",
  "version" : {
    "number" : "5.2.2",
    "build_hash" : "f27a4de",
    "build_date" : "2018-07-06T08:50:44.258Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by rbayet** [comment]
Hi @edward-simpson,

Could you also give me the version of your ElasticSearch ?

Regards,

**Comment by r0umi** [comment]
Hello,

He's got the same version : v5.3.2 according to his last comment.

Regards, Romain

**Comment by rbayet** [comment]
> Hello,
> 
> He's got the same version : v5.3.2 according to his last comment.
> 
> Regards, Romain

Hello @r0umi, v5.3.2 is the version of its ElasticSearch PHP client (elasticsearch/elasticsearch).
I updated my comment to clarify that I'm interested in the ElasticSearch **server** version.

Regards,

**Comment by romainruaud** [comment]
I close this one for being inactive / stalled for too long.

Please open a new issue with all needed details if you are still encountering the problem.

Regards

**Comment by mlaurel** [comment]
I'm having this same issue, along with another error with ElasticSuite (but I won't get into that now).  When I do the following commands...

```
composer info | grep elastic && curl http://localhost:9200
```

I get this...

```
elasticsearch/elasticsearch                       v5.3.2             PHP Client for Elasticsearch
magento/module-elasticsearch                      100.2.5            N/A
smile/elasticsuite                                2.6.3              Magento 2 merchandising and search engine built on ElasticSearch

{
  "name" : "Man-Beast",
  "cluster_name" : "elasticsearch_mikelaurel",
  "cluster_uuid" : "-jUZpvotSmydDBjGMbodog",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```

As I mentioned above, when I do a full reIndex, I get errors on the following indexes:

```
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
```
```
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```
