### ISSUE TITLE
Missing required argument $values

### ISSUE THREAD

**Issue by TandyCorp** [Smile-SA/elasticsuite#1088]
when cron is running the following entry keeps apearing in the system log...
main.CRITICAL: Missing required argument $values of Smile\ElasticsuiteCore\Search\Request\Query\Terms. [] []
### Preconditions

Magento Version : Magento Open Source 2.2.6

ElasticSuite Version : 2.6.1

Environment : Default Mode

Third party modules : M2e Pro.

**Comment by TandyCorp** [comment]
To be honest I just gave up and ignore it as I couldn't find any information anywhere that explains whet the error message means, so I had no way of investigating further.

**Comment by romainruaud** [comment]
I'll close this one for now since tracking indexes will be refactored in later version, feel free to open another issue if you are still facing issues.

Best regards

**Comment by speller** [comment]
I had this issue on my local installation when I didn't run `setup:di:compile` after upgrading the module.
