### ISSUE TITLE
Thesaurus: Synonyms with special german chars doesn't seemed to be resolved

### ISSUE THREAD

**Issue by dyron** [Smile-SA/elasticsuite#1089]
### Preconditions

Magento Version : 2.2.5

ElasticSuite Version : 2.5.13 on Production, 2.6. on Developer

Environment : Both Production and Developer

### Steps to reproduce

1. Create the required synonyms:
![bildschirmfoto 2018-09-24 um 13 06 10](https://user-images.githubusercontent.com/116693/45949045-a5d92200-bffa-11e8-949f-7fcc28e57172.png)

2. Create the ElasticSuite Thesaurus Index:
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:31

### Expected result

1. Both search results should show about the same products, different in product sorting.

### Actual result

1. Go to https://www.eurofer.de/eurofer-portal/catalogsearch/result/?q=sto%C3%9Fgriff, but it has only one result for "türgriff"

**Comment by dyron** [comment]
I'd like to add that the ES module analysis-icu is already active.

**Comment by romainruaud** [comment]
Fixed by #1136 and embedded in latest **2.6.2** release.
