### ISSUE TITLE
Optimizers: "store view" field is displayed twice

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1091]
When you edit an optimizer, the "store view" field is displayed twice.

### Preconditions
http://demo.magento-elastic-suite.io/
ElasticSuite Version : latest (2.6.1)
Third party modules : No

### Steps to reproduce
Edit an optimizer

### Actual result
The "store view" field is displayed below "Enable Optimizer" AND displayed in the top bar above "Enable Optimizer"
![capture d ecran 2018-09-25 a 16 14 05](https://user-images.githubusercontent.com/20048184/46020343-769be100-c0de-11e8-8fe8-4ae9c3726d2d.png)

### Expected result
I think we should see the "store view" field below "Enable Optimizer".
The other one is confusing.

**Comment by romainruaud** [comment]
You are right, imho this is actually not relevant to have a store switcher on optimizer edit page.

Regards

**Comment by romainruaud** [comment]
Associated PR have been merged and will be part of the next minor release scheduled for next week.

Thank you for reporting it.

Regards
