### ISSUE TITLE
Optimizer: category preview is not working

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1092]
When I edit an optimizer, the category preview is not displayed.

### Preconditions
http://demo.magento-elastic-suite.io
Magento Version : Open Source 2.2.5
ElasticSuite Version : 2.6.1
Third party modules : No
My browser is Chrome 69 for Mac

### Steps to reproduce
1. Edit an optimiser (for example "boost sur les produits soldés" or "test-run-aufou")
2. In the "Preview" block, select "Category Product View"
3. Select a category
4. Click "Preview"

### Expected result
A preview of the category should be displayed

### Actual result
Nothing happens: no error message... no preview... nothing.

![capture d ecran 2018-09-25 a 16 25 19](https://user-images.githubusercontent.com/20048184/46020858-9e3f7900-c0df-11e8-8476-52acf64dc85f.png)

An idea: When I look at the AJAX request, the response of the server is {"base_products":[],"optimized_products":[],"size":0}

**Comment by romainruaud** [comment]
Fixed. Probably as a side effect of fixing the optimizer appliance via #1108 

Regards
