### ISSUE TITLE
Optimizer: not working ?

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1093]
I enabled an optimizer that applies a +1000% boost on all products with a price lower than 30€, and the optimizer is not applied on front.

I don't know why... what did I do wrong ?

### Preconditions
http://demo.magento-elastic-suite.io
Magento Version : Open Source 2.2.5
ElasticSuite Version : 2.6.1
Third party modules : No

### Steps to reproduce
I enabled the optimizer "test-run-aufou".
I disabled the "manual sort" on all the products of the category "tees men".

### Expected result
All products below $30 should be displayed first

### Actual result
When I look at the category
http://demo.magento-elastic-suite.io/index.php/men/tops-men/tees-men.html
The price of the two first products is $39 -> the boost is not working.

**Comment by jsterling** [comment]
I'm seeing the same; the 'preview' is fine but the optimizer is not applied to a category view. 

### Preconditions
Magento Version : Open Source 2.2.6
ElasticSuite Version : 2.6.1

###Steps to reproduce
Set Optimizer for category and search to add 1000 weighting to 'In Stock' products

###Expected result
In stock products should be displayed first

Actual result
No change to sort order

**Comment by romainruaud** [comment]
Associated PR have been merged and will be part of the next minor release scheduled for next week.

Thank you for reporting it.

Regards
