### ISSUE TITLE
Optimizer: Base table or view not found

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1095]
### Preconditions

Magento Version : 2.2.5 CE

ElasticSuite Version : 2.6.1

Environment : Developer

### Steps to reproduce

1. Create an optimizer and save

### Expected result

1. Optimizer should save successfully 

### Actual result

1. Could not save the optimizer: SQLSTATE[42S02]: Base table or view not found: 1146 Table '[DB_NAME].smile_elasticsuite_optimizer_limitation' doesn't exist, query was: DELETE FROM `smile_elasticsuite_optimizer_limitation` WHERE (optimizer_id = 2)

Our table names are prefixed.

**Comment by romainruaud** [comment]
Well, seems like we are using somewhere a direct access to this table (without a proper `getTable()` call to deal with prefixes I guess) on the latest version of Elasticsuite.

We should be able to provide a fix on this one quickly.

Regards

**Comment by romainruaud** [comment]
Associated PR have been merged and will be part of the next minor release scheduled for next week.

Thank you for reporting it.

Regards
