### ISSUE TITLE
categoryLayerFactory for block / Objectmanager?

### ISSUE THREAD

**Issue by jsterling** [Smile-SA/elasticsuite#1097]
I'm trying to show an ElasticSuite category in a block (via Objectmanager). 

`$category->getProductCollection()` works to get the products but they do not match the order as set in admin (some manual sort, some auto). 

I note from the FAQ I can do

```
$collection = $this->_categoryLayerFactory
                    ->create()
                    ->getProductCollection();
$collection->addCategoryFilter($category);
```

However categoryLayerFactory remains a mystery; I can't see this referenced in any other code (Smile or Magento) to be able to inject via ObjectManager. Any pointers?

**Comment by romainruaud** [comment]
Hello,

the proper way to instantiate a collection and filter it should be : 

```php
/** @var \Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory $collectionFactory **/

// $collection will be an Elasticsuite one, since it's defined in Elasticsuite DI that the fulltext collection is now an Elasticsuite one.

$collection = $collectionFactory->create();
$collection->addCategoryFilter($category);
```
