### ISSUE TITLE
Change display mode in category config page not working.

### ISSUE THREAD

**Issue by jideacto** [Smile-SA/elasticsuite#1098]
Change display mode in category config page not working.
### Preconditions
Magento Version : 2.2.5 CE
ElasticSuite Version : 2.6.1
Environment : Developer

### Steps to reproduce
1. Go to edit category
2. Section Display Settings -> Layered Navigation Filters
3. Ex. change display mode and save

### Expected result

1. Save and show filter always displayed

### Actual result

1. Error after save -> Invalid Form Key. Please refresh the page.

**Comment by romainruaud** [comment]
Closed for being not reproduced and inactive/unanswered for 2 weeks.

Feel free to reopen if you have more insights.

Regards
