### ISSUE TITLE
Products not Shown in Category pages after start using Redis

### ISSUE THREAD

**Issue by Alizeinalzadeh** [Smile-SA/elasticsuite#1101]
We were using elasticsearch and everything was fine, after we start using Redis for cache, the products aren't available in category pages.  
We tried to disable elasticsearch and the products backed and were available in page. 

### Preconditions
Magento Version : 2.2.2 open source

ElasticSuite Version : 2.5.9

Environment : tested on both developer and production mode

Third party modules : codazon fastest theme

### Steps to reproduce
1. Probably there is some incompatibility with redis 

### Expected result
1. The Products of a category should shown in category pages. 

### Actual result
1. no products shown in category pages and the error is "we could found any product  ... "

**Comment by Alizeinalzadeh** [comment]
and also i update elasticsuite to 2.6.1 version and still have the issue and i categery pages i got: We can't find products matching the selection.

**Comment by romainruaud** [comment]
Hello @Alizeinalzadeh 

We use Elasticsuite + Redis as cache backend on many projects at Smile already, and did never face a such issue.

Which kind of Full Page Cache are you using ? Built-in Magento pagecache or Varnish integrated ?

Regards

**Comment by Alizeinalzadeh** [comment]
> Hello @Alizeinalzadeh
> 
> We use Elasticsuite + Redis as cache backend on many projects at Smile already, and did never face a such issue.
> 
> Which kind of Full Page Cache are you using ? Built-in Magento pagecache or Varnish integrated ?
> 
> Regards

Hi @romainruaud  
We don't use Varnish at all. We use Redis for magento 2 default cache, sessions and page cache, i can give you the config we use if you need them. 
I've tried to disable the elasticsuite modules and the problem solved, but then I've enabled elasticsuite and , disabled the Redis but I've got the error again.

**Comment by romainruaud** [comment]
If you are toggling enable/disable Elasticsuite, you have to process a full reindex each time you enable Elasticsuite (and set it as default search engine). Are you processing a full reindex each time ?

Regards

**Comment by Alizeinalzadeh** [comment]
> If you are toggling enable/disable Elasticsuite, you have to process a full reindex each time you enable Elasticsuite (and set it as default search engine). Are you processing a full reindex each time ?
> 
> Regards

Yes I process a full reindex and got no errors during reindexing.

**Comment by bfound2016** [comment]
What we'd like to know, is there a more explicit way to debug this either on Magento side of Elasticsearch side?

**Comment by atolodas** [comment]
Confir, same problem Redis+Elasticsuite +Multistore

**Comment by romainruaud** [comment]
As we are not actually able to reproduce this problem, please give us details if you are able to reproduce it on a raw Magento installation, without any custom theme.

I strongly suspect this is rather related to a third party extension than to Elasticsuite.

Regards

**Comment by romainruaud** [comment]
Closed for being not updated for more than 10 days.

Regards

**Comment by Alizeinalzadeh** [comment]
> Closed for being not updated for more than 10 days.
> 
> Regards

The problem solved just today, 
we add --page-cache-redis-compress-data=1 to redis configuration and now the products shown in category pages.

**Comment by Alizeinalzadeh** [comment]
> Confir, same problem Redis+Elasticsuite +Multistore

adding --page-cache-redis-compress-data=1 to redis config worked for me.
