### ISSUE TITLE
[Facet Search] Doesn't work on IE because of unsupported includes()

### ISSUE THREAD

**Issue by mborkowski** [Smile-SA/elasticsuite#1102]
Facet search won't work on IE because of unsupported array search method `includes()`. Console throws an error and nothing happens, facet items are not filtered.

### Preconditions

Custom theme, based on theme-blank

Magento Version :
2.2.5

ElasticSuite Version :
2.4
(looking at the code of 2.6.x it will also be there) 

Environment :
Default/Developer

Third party modules :
Plenty of them but for sure not related
### Steps to reproduce

1. Open IE (any, let's say IE11) 😸 
2. Go to category page where filters search input can be found
3. Type something

### Expected result

Facet items are filtered by the query provided

### Actual result

Nothing happens, console throws an error of unsupported `includes()` for an array

The problem is in https://github.com/Smile-SA/elasticsuite/blob/2.6.x/src/module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js script where you can find `includes()` method used twice (lines 125 and 131). I'd suggest to use `indexOf` to test the query, which is also simple and will work also on older browsers.

**Comment by romainruaud** [comment]
Hello @mborkowski 

Thank you for reporting this one.

Would you mind creating a PR to fix this since you have already identified the issue and the proper workaround ?

Regards

**Comment by romainruaud** [comment]
Associated PR was merged, and will be part of the next minor release. 

Thank you for pointing this issue, and thank you again for contributing a resolution !

Best regards
