### ISSUE TITLE
Removing extension break search

### ISSUE THREAD

**Issue by Kamik** [Smile-SA/elasticsuite#1114]
Magento Version : 2.2.6
After uinstall extension is magento search breaks (uninstalled as from wiki)

url - catalogsearch/result/?q=XXXX

`1 exception(s):
Exception #0 (InvalidArgumentException): Invalid filter type

Exception #0 (InvalidArgumentException): Invalid filter type
#0 /var/www/clients/client4/web26/web/vendor/magento/framework/Search/Request/Cleaner.php(113): Magento\Framework\Search\Request\Cleaner->cleanFilter('visibility_filt...')
#1 /var/www/clients/client4/web26/web/vendor/magento/framework/Search/Request/Cleaner.php(212): Magento\Framework\Search\Request\Cleaner->cleanQuery('visibility')
#2 /var/www/clients/client4/web26/web/vendor/magento/framework/Search/Request/Cleaner.php(92): Magento\Framework\Search\Request\Cleaner->processQueryReference(Array)
#3 /var/www/clients/client4/web26/web/vendor/magento/framework/Search/Request/Cleaner.php(57): Magento\Framework\Search\Request\Cleaner->cleanQuery('quick_search_co...')
#4 /var/www/clients/client4/web26/web/vendor/magento/framework/Search/Request/Builder.php(142): Magento\Framework\Search\Request\Cleaner->clean(Array)
......
`

**Comment by romainruaud** [comment]
Hello @Kamik 

Did you try to clean the DI and purge the generated directory after uninstalling ?

**Comment by Kamik** [comment]
mean you
rm -rf var/generation/*
rm -rf var/di/*
?
yes

**Comment by romainruaud** [comment]
If you are using Magento 2.2.6 it's rather /generated

**Comment by Kamik** [comment]
yes. no changes

**Comment by Kamik** [comment]
i have dumped $filter in vendor\magento\framework\Search\Request\Cleaner.php in function cleanFilter
with var_dump($filter);

dump on error:
`array(2) {
    [0] => string(10)
    "termFilter" [1] => string(10)
    "termFilter"
}
array(4) {
    ["name"] => array(2) {
        [0] => string(17)
        "visibility_filter" [1] => string(17)
        "visibility_filter"
    }["field"] => array(2) {
        [0] => string(10)
        "visibility" [1] => string(10)
        "visibility"
    }["value"] => array(3) {
        [0] => array(2) {
            [0] => string(1)
            "3" [1] => string(1)
            "4"
        }[1] => array(2) {
            [0] => string(1)
            "3" [1] => string(1)
            "4"
        }["is_bind"] => bool(true)
    }["type"] => array(2) {
        [0] => string(10)
        "termFilter" [1] => string(10)
        "termFilter"
    }
}`
also type 'termFilter' throw exception

**Comment by Kamik** [comment]
var_dump($filter['type']);
`
array(2) {
    [0] => string(10)
    "termFilter" [1] => string(10)
    "termFilter"
}
`
var_dump(FilterInterface::TYPE_TERM);
`string(10)
"termFilter"`

**Comment by Kamik** [comment]
ok. i solved it. resave attribute "visibility" in admin backend.

**Comment by mtkumar82** [comment]
I have the same problem. I resaved category_ids and visibility attributes from magento2 backend.
Steps:-
1) Login to Admin.
2) Store->attributes->product.
3) Search category_ids and save it.
4) Than search visibility and resave it.
