### ISSUE TITLE
php bin/magento setup:static-content:deploy ( gives an errors )

### ISSUE THREAD

**Issue by tukker01** [Smile-SA/elasticsuite#1120]
Preconditions
Magento Version : 2.2.6

ElasticSuite Version : ElasticSuite 2.6.x

Environment : Ubuntu 16.04.3 LTS

php bin/magento setup:static-content:deploy gives the understage result

Compilation from source: /var/www/html/vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @autocomplete-item__border is undefined in file /var/www/html/var/view_preprocessed/pub/static/frontend/Solwin/shoptica/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 32, column 38
30|                     border-bottom: 0;
31|                 }
32|                 .lib-css(border-top, @autocomplete-item__border);
33|                 cursor: default;
34|                 margin: 0;
35|                 padding: @indent__xs @indent__xl @indent__xs @indent__s;

  [Magento\Framework\Exception\FileSystemException]
  Cannot read contents from file "/var/www/html/pub/static/frontend/Solwin/shoptica/en_US/css/styles-m.css" Warning!file_get_contents(/var/www/html/pub/stati
  c/frontend/Solwin/shoptica/en_US/css/styles-m.css): failed to open stream: No such file or directory

this has to do with our template, the developer of the template indicates that it is a problem ElasticSuite problem.

This is his anwser:
(The issue is in your custom module Smile_ElasticsuiteCore which you have installed from the GIT.

This is not Shoptica theme related issue.

I have found the line in which this issue occurs. 

https://github.com/Smile-SA/elasticsuite/blob/e6d5af51e09f78d550579fc018c7245c59e0c7b8/src/module-elasticsuite-core/view/frontend/web/css/source/_module.less#L32

You should contact to the Smile support person. Because they have developed it and they know it better.
)

**Comment by sezio** [comment]
Hello, 

I also have this issue, have you any solution ?

Thanks

**Comment by romainruaud** [comment]
Yes, the workaround described by @sezio should do the trick.

Just to end the discussion : The `@autocomplete-*` variables are defined into the Luma theme, but also in the Blank theme. 

So your theme should still have these custom variables since they come from the blank theme.

Anyone doing a theme from scratch and not inheriting the blank theme, or removing custom variable from it, is doing wrong.
