### ISSUE TITLE
2.6.0 Compatibility fix for Magento 2.3.0[beta12]

### ISSUE THREAD

**Issue by spanxcom** [Smile-SA/elasticsuite#1121]
https://github.com/Smile-SA/elasticsuite/blob/a1310b429beafb7a1466c98fc47695141aaa5c84/src/module-elasticsuite-core/Indexer/GenericIndexerHandler.php#L156

Playing around with figuring out how much work it'll take us to upgrade to 2.3 beginning of next year and got this error message when installing 2.6.0 with Magento 2.3.0[beta12]

`PHP Fatal error:  Declaration of Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler::isAvailable() must be compatible with Magento\Framework\Indexer\SaveHandler\IndexerInterface::isAvailable($dimensions = Array) `

Fixed by changing L156 referenced above to:
`public function isAvailable($dimensions = [])`

**Comment by romainruaud** [comment]
Hello @spanxcom 

would you mind proposing a PR for this one, since you've already found the resolution ?

Regards

**Comment by romainruaud** [comment]
So, seems like you did not have time to contribute :(

I fixed it by myself via PR #1143 that has been merged in 2.6.x branch. Will be part of next minor release. If you can't wait, please use 2.6.x branch from now.

Regards
