### ISSUE TITLE
Category Layered Navigation Filter Display Mode doesn't work on anchored product list pages

### ISSUE THREAD

**Issue by giraclion** [Smile-SA/elasticsuite#1122]
### Preconditions
When hiding Layered Navigation Filters via Display Mode in Admin Panel Category Edit Page, those filters will be hidden only if you access category explicitly by its full URL: https://www.site.com/clothing/woman/dresses (the Dresses category is third level category). But if you access category by its anchored filter:  https://www.site.com/clothing/woman?cat=CATEGORY_ID, all filters will be displayed, regardless of Display Mode setting for that CATEGORY_ID. After thorough debugging it tuned out that on explicit category page ESSuite loads filters based on that category settings, but when loading anchored category via ?cat=CATEGORY_ID, ESSuite loads parent category filters settings

- Magento Version : EE (Commerce Edition) v2.2.5
- ElasticSuite Version : v2.6.1
- Environment: Production Environment

### Steps to reproduce
1. Go to Magento -> Admin Panel -> Catalog -> Categories
1. Edit 3rd level category and set Display Mode = "Always Hidden" for any Layered Navigation Filter
1. Click Save
1. Go to Frontend and access category (product list page) via URL like https://www.site.com/clothing/woman?cat=CATEGORY_ID (anchored/category filtered URL)

### Expected result
Hidden Layered Navigation Filter is not be displayed

### Actual result
Hidden Layered Navigation Filter is still displayed

**Comment by romainruaud** [comment]
Hello @giraclion 

Accessing a category the way you do it, with `clothing/woman?cat=ID` is not the legacy way Magento is doing it : by filtering on a specific category, you should be redirected to this category with his full URL.

How do you achieve accessing categories like this ? Is it due to custom code of your own ?

Regards

**Comment by giraclion** [comment]
Hi @romainruaud ,

This is a native anchor category link we are getting when using "Category" filter rendered by ElasticSuite for sub-sub categories. 

To fix that problem we added this DI change to our "Main" module:
```
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <!-- Direct links to category in layered navigation -->
    <type name="Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category">
        <arguments>
            <argument name="useUrlRewrites" xsi:type="boolean">true</argument>
        </arguments>
    </type>
</config>
```

Not sure if this is related to Magento 2.2.5 which we are currently using.

**Comment by romainruaud** [comment]
@giraclion 

Look on our demo platform, which is up-to-date with latest Elasticsuite 2.6.2 : 

http://demo.magento-elastic-suite.io/index.php/men/tops-men.html

The category filter is not displaying children category links with `?cat=XX` but rather just using the legacy category URL to access.

Please provide us a list of any third-party modules you are using, if any.

**Comment by giraclion** [comment]
@romainruaud We have `?cat=XX` on search results page: http://demo.magento-elastic-suite.io/catalogsearch/result/?q=Tank

We added some custom code to style the filers differently, but we did not touch the core Smile ES logic

**Comment by romainruaud** [comment]
Hello, so : 

- on search results page, it's normal to navigate through category filter with `cat=XX`
- the category layered navigation filters customization **is not applied** when browsing through search results pages : for now, it's non-implemented here, we are considering adding it later.

- on catalog pages (standard category pages, eg. when you browse them directly via the navigation menu), you should not see the `cat=XX` for the category filter, rather the full category URL
- category layered navigation filters customization **are applied** here.


So, is your initial issue concerning a category that you **access** through the navigation menu or direct url ? Or is it concerning a category you **filter** on, on the search result page ?

**Comment by sergiirepin** [comment]
Hey @romainruaud any updates for this:

> the category layered navigation filters customization is not applied when browsing through search results pages : for now, it's non-implemented here, we are considering adding it later.

?

Also, Looks like it isn't possible to customize Navigation Filters for Root Category?
