### ISSUE TITLE
Hebrew Synonyms do not work

### ISSUE THREAD

**Issue by giraclion** [Smile-SA/elasticsuite#1123]
### Preconditions
When settings up Hebrew synonyms and attempting to search in Hebrew on frontend using those synonyms - search doesn't provide any results. When using English only synonyms, all works as expected.

- Magento Version: Commerce Edition v2.2.5
- ElasticSuite Version: v2.6.1
- ElasticSearch Version: AWS ElasticSearch v5.5
- Environment: Production

### Steps to reproduce
1. Set synonyms using Hebrew language: `alpha,אלפא,אלפה,שךפיש`
1. Make sure thesaurus indexation is completed
1. Go to Frontend and try to search any of the synonym words

### Expected result
1. You should see relevant products according to any of the synonyms

### Actual result
1. Search results are showing no results for Hebrew words that absent in searchable product attribute values, but exist in synonyms/aliases that can be found in some products

**Comment by romainruaud** [comment]
Hello @giraclion 

I'm wondering how this can be correlated with #1072 

For sure, Elasticsuite does not ship any hebrew analyzers by default. This could probably explain why synonyms in hebrew are not properly handled. 

We'll have a look on this one.

**Comment by giraclion** [comment]
Hi @romainruaud, can this https://github.com/Smile-SA/elasticsuite/issues/1072#issuecomment-426738685 work as a workaround for now?

**Comment by rbayet** [comment]
Hi @giraclion, this particular issue depends on a specific analysis chain which is not declared through XML, so https://github.com/Smile-SA/elasticsuite/issues/1072#issuecomment-426738685 would not apply.
The problem has been identified and is more a a code related encoding issue than related to language analysis/support.

That is not to say that https://github.com/Smile-SA/elasticsuite/issues/1072#issuecomment-426738685 could be helpful in a broader sense if you have additional relevance/search issues.

Regards,
Richard.

**Comment by romainruaud** [comment]
Fixed by #1136 and embedded in latest 2.6.2 release.
