### ISSUE TITLE
M2.2.6 & ES2.6 | Missing Autocomplete Template

### ISSUE THREAD

**Issue by Streetec** [Smile-SA/elasticsuite#1124]
### Preconditions
Magento Version : 2.2.6 CE
ElasticSuite Version : 2.6
Environment : Production

Third party modules : MGS FrontEnd Builder 
(https://www.magesolution.com/mgs-frontend-builder-theme-for-magento2.html)

### Steps to reproduce

1. Install MGS FrontEnd Builder
2. Install ElasticSuite
3. Use the search and wait for the autocompete box

### Expected result

1. Autocomplete pops up with links to products / categories and all that usual stuff

### Actual result

1. Autocomplete pops up with kinda a missing template, nothing is clickable, no css
![missingtemplate](https://user-images.githubusercontent.com/25366828/46720891-0199e100-cc72-11e8-8de8-e007c16ef1f2.JPG)

**Comment by romainruaud** [comment]
Hello @Streetec 

Most probably due to your custom theme...

Are you able to check for XHR requests on your page to lookup where it's trying to download the template from ?

Regards

**Comment by Streetec** [comment]
Yea I've thought about it. But when i remove the whole Magento_Search folder within the custom theme and add the Smile Search to the header.xml it gets even wierder. The search gets a width of 100% within the container and theres isnt even the autocomplete with the missing template anymore.

I've checked for XHR but there was nothing wrong. Every request was passed with a status code of 200

**Comment by Streetec** [comment]
I've played a bit with the ElasticSuite and the custom theme and it seems like it is kinda working now.
Except that i get an error on the `form-mini.js` on line 193:83 wich is the following:

` if (this.titleRenderers && this.titleRenderers[type]) {
                title = $('<dt role="listbox" class="autocomplete-list-title title-' + type + '">' + this.titleRenderers[type].render(data) + '</dt>');
                } else if (this.options.templates && this.options.templates[type].title) {
                title = $('<dt role="listbox" class="autocomplete-list-title title-' + type + '">' + this.options.templates[type].title + '</dt>');
            }`

**Comment by romainruaud** [comment]
which error are you facing on this line ?

**Comment by Streetec** [comment]
> which error are you facing on this line ?

It is: `form-mini.js:193 Uncaught TypeError: Cannot read property 'title' of undefined`

**Comment by romainruaud** [comment]
Ok so probably `this.options.templates[type]` is undefined.

Are you able to log what is actually in the `this.options.templates` variable ?

Can you check if your theme is having any references to `top.search` or `topSearch` block in his layout ?

**Comment by Streetec** [comment]
This report can be closed and marked as solved. After adding the missing referenceBlock with all the arguments the search works as intended.

    <referenceBlock name="top.search">
            <arguments>
                <argument name="rendererList" xsi:type="array">
                    <item name="product" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Products</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
                    </item>
                    <item name="category" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Categories</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
                    </item>
                    <item name="product_attribute" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Attributes</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>

**Comment by romainruaud** [comment]
Glad to hear it :)
