### ISSUE TITLE
How can I define a custom index analyzer?

### ISSUE THREAD

**Issue by lovemeblender** [Smile-SA/elasticsuite#1126]
It is clear from the documentation that you can add a custom query analyzer [like this](https://github.com/Smile-SA/elasticsuite/wiki/Indexing#custom-analysis--filtering-of-fields). I didn't find the index equivalent to `defaultSearchAnalyzer` though.  

How can I define a custom index analyzer per ES field?

### Preconditions

Magento Version : 2.2

ElasticSuite Version : 2.6

**Comment by romainruaud** [comment]
Hello @lovemeblender 

Look how it's done for the SKU : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L44

And the "reference" analyzer declared here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/etc/elasticsuite_analysis.xml#L187

**Comment by lovemeblender** [comment]
Thanks @romainruaud. However this is the query analyzer isn't it? I was wondering how I can do the same for the indexed fields.

**Comment by lovemeblender** [comment]
A bit of update: @romainruaud you were right that this is the `index analyzer`, however this leaves us without a `query analyzer`. Any idea how to define one? Thanks.

**Comment by lovemeblender** [comment]
I think I got it. If you define as `defaultSearchAnalyzer` an analyzer called `default` then it automagically uses `default_search` as the query analyzer!
