### ISSUE TITLE
Array string issue

### ISSUE THREAD

**Issue by coresh** [Smile-SA/elasticsuite#1128]
After proper installation, indexing and deploying the extension provided with the issue (any category-view page):
![screenshot-20181011172004-1920x1053](https://user-images.githubusercontent.com/9606476/46826963-ef5d9700-cd86-11e8-9d9e-698196c0b617.png)

### Preconditions

Magento Version: 2.2.6

ElasticSuite Version :
![screenshot-20181011184913-1920x1080](https://user-images.githubusercontent.com/9606476/46826981-f97f9580-cd86-11e8-9a75-21dfbb5bc1ca.png)

Environment : developer

Third party modules :

List of enabled modules:
Aheadworks_Coupongenerator
Aheadworks_Followupemail2
Aheadworks_Popup
Amasty_Base
Auctane_Api
Magefan_Community
Faonni_Breadcrumbs
KiwiCommerce_AdminActivity
KiwiCommerce_LoginAsCustomer
Lof_AjaxScroll
Lof_All
MSP_Common
MSP_DevTools
MageWorx_SeoAll
MageWorx_HtmlSitemap
MageWorx_SeoBase
MageWorx_SeoBreadcrumbs
MageWorx_SeoCrossLinks
MageWorx_SeoExtended
MageWorx_SeoMarkup
MageWorx_SeoRedirects
MageWorx_SeoUrls
MageWorx_SeoXTemplates
Magefan_Blog
Aheadworks_Autorelated
Aheadworks_Helpdesk
Amasty_ShippingTableRates
Amazon_Core
Ebizmarts_Mandrill
KiwiCommerce_CronScheduler
MagePal_GmailSmtpApp
Amazon_Login
Amasty_CommonRules
Klarna_Core
Amazon_Payment
Cadence_Fbpixel
Cadence_Pinterest
Amasty_Shiprules
Faonni_ReCaptcha
Smile_ElasticsuiteCore
MageWorx_XmlSitemap
Klarna_Ordermanagement
Aitoc_PreOrders
Aheadworks_RewardPoints
Aheadworks_Giftcard
Klarna_Kp
Ebizmarts_MailChimp
ParadoxLabs_TokenBase
ParadoxLabs_Authnetcim
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteCms
Comwrap_ElasticsuiteBlog
Smile_ElasticsuiteVirtualCategory
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteTracker
Smile_ElasticsuiteRating
Solwin_Productreview
SplashLab_CorsRequests
Vertex_Tax
Ves_All
Ves_Megamenu
Ves_Setup
WeltPixel_Backend
WeltPixel_GoogleTagManager

### Steps to reproduce

1. Direct after properly indexing and flushing caches, deploying (familiar)
2. By opening any categories
3.

### Expected result

1. Expected opening the category page without issues
without smile-related extensions with luma theme -> everything ok.

### Actual result

1. [Screenshot, logs]

Provided patch -> fixed issue:

https://github.com/Smile-SA/elasticsuite/pull/1127

but the result after applying the patch:

![screenshot-20181011185933-1920x1053](https://user-images.githubusercontent.com/9606476/46827397-09e44000-cd88-11e8-9b8d-2b0b15d17cda.png)

**Comment by romainruaud** [comment]
Hello,

please use `composer info | grep smile` and give us the output of this command to check exact elasticsuite version.

Also, please give us details about ElasticSearch version (5.x or 6.x ?)

**Comment by coresh** [comment]
Hello:

```
>  /usr/bin/composer info | grep smile                                                                                                                                                                                                                  [git::new_theme_v001|] 
smile/elasticsuite                                2.6.1     Magento 2 merchandising and search engine built on ElasticSearch 
smile/module-elasticsuite-cms-search              2.1.4     Smile Elasticsuite - Cms Pages Search Module for Smile Elasticsuite.
smile/module-elasticsuite-rating                  2.1.5     Smile ElasticSuite - Rating search module.
```

**Comment by coresh** [comment]
```
>  /usr/bin/composer --version                                                                                                                                                                                                                          [git::new_theme_v001|] 
Composer version 1.7.2 2018-08-16 16:57:12
```

**Comment by coresh** [comment]
```
>  rpm -qa | \grep --color=auto elastics                                                                                                                                                                                                                [git::new_theme_v001|] 
elasticsearch-5.6.11-1.noarch
```

**Comment by coresh** [comment]
```
>  composer info | grep elas                                                                                                                                                                                                                            [git::new_theme_v001|] 
Running 1.7.2 (2018-08-16 16:57:12) with PHP 7.1.18 on Linux / 4.18.9-200.fc28.x86_64
elasticsearch/elasticsearch                       v5.3.2    PHP Client for Elasticsearch
smile/elasticsuite                                2.6.1     Magento 2 merchandising and search engine built on ElasticSearch 
smile/module-elasticsuite-cms-search              2.1.4     Smile Elasticsuite - Cms Pages Search Module for Smile Elasticsuite.
smile/module-elasticsuite-rating                  2.1.5     Smile ElasticSuite - Rating search module.

```

**Comment by coresh** [comment]
```
MariaDB [m2_0003]> SELECT * FROM setup_module WHERE module LIKE '%lasti%';
+------------------------------------+----------------+--------------+
| module                             | schema_version | data_version |
+------------------------------------+----------------+--------------+
| Comwrap_ElasticsuiteBlog           | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteCatalog          | 1.5.0          | 1.5.0        |
| Smile_ElasticsuiteCatalogOptimizer | 1.1.0          | 1.1.0        |
| Smile_ElasticsuiteCatalogRule      | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteCms              | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteCore             | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteRating           | 1.2.0          | 1.2.0        |
| Smile_ElasticsuiteSwatches         | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteThesaurus        | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteTracker          | 1.2.0          | 1.2.0        |
| Smile_ElasticsuiteVirtualCategory  | 1.3.0          | 1.3.0        |
+------------------------------------+----------------+--------------+
11 rows in set (0.00 sec)

MariaDB [m2_0003]>

```

**Comment by romainruaud** [comment]
Hello,

I highly suspect you have some third party module which is interfering with Layered Navigation, since this issue does not exist on a raw Elasticsuite install.

As I explained on your PR, this is not a suitable way to fix it. Aggregations on `attribute_set_id` and `indexed_attributes` should always be here, so there is actually no point on testing them or to ignore them.

You have a third party module which is actually breaking something on layered navigation, or search.

Since providing support for third-party modules integration is out of the scope of our Open Source support provided here on Github, you can contact me directly by email at romain.ruaud@smile.fr if you are interested in commercial support.

Best regards

**Comment by coresh** [comment]
Hello, Romain: I will check related to third-party modules
Thank you.
