### ISSUE TITLE
Kill autocomplete queries "on the fly"

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#113]
When the user is typing, we should kill the Ajax queries on the fly.

If I type "hoodie", there will be all this Ajax queries : 

"ho", "hoo", "hood", "hoodi", "hoodie".

Sometimes their results not appear in the right order, dependant of the time the Ajax results come to the browser : I can see the proper "hoodie" results, and just after they are replaced by non-pertinent results from the query "hoo".

We should kill the previous Ajax queries (or minimum ignoring them) each times the customer types a new letter.

We should also kill them when he presses backspace or even enter.

**Comment by afoucret** [comment]
PR have been merged.
