### ISSUE TITLE
Label in the configuration

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1135]
### Preconditions
Magento Version : 2.2.5
ElasticSuite Version : latest
Environment : http://demo.magento-elastic-suite.io/

### Steps to reproduce
Open the menu Store > Product Attribute
Choose an attribute
Open the tab "StoreFront Properties"

### Actual result
Below 2 fields, a label is displayed
 "Can be used only with catalog input type Dropdown, Multiple Select and Price."

![capture d ecran 2018-10-15 a 16 53 12](https://user-images.githubusercontent.com/20048184/46958765-dad91180-d09a-11e8-9d70-d4acd1778e7b.png)

### Expected result
The feature is also working with attributes type "Text Field" -> it should be displayed in the label

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor release.

Thank you for pointing it !

Regards
