### ISSUE TITLE
ES 2.6.2 & Magento 2.2.6 | Error in Category Admin page

### ISSUE THREAD

**Issue by Streetec** [Smile-SA/elasticsuite#1145]
### Preconditions
Magento Version : 2.2.6
ElasticSuite Version : 2.6.2
Environment : Production

### Steps to reproduce
1. Upgrade ES vom 2.6.1 to 2.6.2
2. Reindex everything
3. Open Category page with products in it

### Expected result
1. Category gets loaded and shows the products inside the category

### Actual result
1. Spinner appears and spins forever
2. Chrome DevTools show an error on `product-sorter.js:119`
3. `Uncaught TypeError: Cannot read property 'map' of undefined`

**Comment by rbayet** [comment]
Could not reproduce on 2.2.6 CE fresh install with Luma sample data / ElasticSearch 5.6.12

**Comment by Streetec** [comment]
After I disabled the VirtualCatalog module the error is not longer present. Not sure how to reproduce...

**Comment by smuzza** [comment]
@Streetec i also get this error on 2.6.1.

What version of elastic search are you using?

**Comment by romainruaud** [comment]
Closed for being stalled/inactive for too long, and not reproduce by our side.

Feel free to open a new issue if still encountering the problem.

Regards
