### ISSUE TITLE
Cant save Category in large environment (Big Post)

### ISSUE THREAD

**Issue by wouter-toppershops** [Smile-SA/elasticsuite#1153]
### Preconditions

Magento Version : 2.2.6 and 2.3

ElasticSuite Version : 2.6.x-dev

Environment : Developer

Third party modules :

### Steps to reproduce

1. have a lot of categories with attributes. 
2. try to save them
3. get error of invalid form key. but its actually an other error.  he isnt actually submitting the the form. its posting to `/admin/catalog/category/validate/` with alot of post entities [https://pastebin.com/XTjx9dAR]
4. i believe the error is in the php setting `max_input_vars` but increasing those values doesnt seem to be an option in my opinion. 

### Expected result

1. save the category.
2. post the form without all the `facet_config[][]` entities if they havent changed. (i dont think its nessecary to make such a big post for every time the category needs to be changed)

### Actual result

1. Post Request: https://pastebin.com/XTjx9dAR
2. 
![screenshot from 2018-10-25 09-28-58](https://user-images.githubusercontent.com/40226924/47483503-b7039180-d839-11e8-9f74-bd651e2d8fb9.png)
![screenshot from 2018-10-25 09-29-16](https://user-images.githubusercontent.com/40226924/47483509-bcf97280-d839-11e8-8e70-e2db3cd1380f.png)
![screenshot from 2018-10-25 09-29-43](https://user-images.githubusercontent.com/40226924/47483518-c1be2680-d839-11e8-8d9d-a4817c0f7ae5.png)
![screenshot from 2018-10-25 09-38-56](https://user-images.githubusercontent.com/40226924/47483571-def2f500-d839-11e8-8c21-467482b9aea6.png)

**Comment by wouter-toppershops** [comment]
@Swahjak you got more details to fill in the blancs?

**Comment by Swahjak** [comment]
The post data suggests that all attribute's that are filterable are displayed while only certain attributes affect the category. Since this is still a (relatively) small catalog I could see this "issue" increase in the future. Maybe only loading the relevant attributes could solve this problem. Maybe filtering the 'Use Default value' on post could reduce the post size as well, since this would be the most common case.

**Comment by romainruaud** [comment]
Hello @Swahjak 

Yes, displaying only "relevant" attributes (attributes matching at least one product in the category, or attribute that have been customized for this category previously) is definitely something we were considering for this feature : better UX imho, and shall also fix this issue.

We'll have a look on this one,

Thank you for using our module and for having reported this.

Regards

**Comment by romainruaud** [comment]
Fixed by PR #1164 that will be part of next minor release.
