### ISSUE TITLE
How to remove request filters?

### ISSUE THREAD

**Issue by shochdoerfer** [Smile-SA/elasticsuite#1158]
I needed to remove one of the defined request filters. I tried to create a custom `elasticsuite_search_request.xml` file in my own module and remove the filter there. Unfortunately that did not work. Is there any way to remove or customize filters of pre-defined requests?

**Comment by romainruaud** [comment]
Hello @shochdoerfer 

You can create a custom `elasticsuite_search_request.xml` file and define a dummy filter that has the same key of one of the existing filter.

Your dummy implementation should just return nothing.

Let me know if it works.

**Comment by shochdoerfer** [comment]
Will give it a try. Currently I used the DI preferences to achieve the same but that really feels like a bad idea  :P

**Comment by shochdoerfer** [comment]
Works fine. Thank you.
