### ISSUE TITLE
Different search results are not consistent with Synonymns

### ISSUE THREAD

**Issue by vivekjha25** [Smile-SA/elasticsuite#1160]
### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : 2.5.12

Environment : Production

Third party modules :

### Steps to reproduce

1. Check Terms configured for Name in theasaurus . Eg: Instant Pot - Insta pot, instapot
2. Searching using the terms and names gives different results
3. Insta/instant pot are not confirgured as terms for any other Name

### Expected result

1. insta pot and instapot  should give same results

### Actual result

1.insta pot and instapot - gives different results.

**Comment by romainruaud** [comment]
Hmm... We raised this topic internally at Smile also.

Our proposal for getting it fixed was #1147 

Could you give a try to this commit on your instance and give me more details ?

**Comment by romainruaud** [comment]
@vivekjha25 any update ?
