### ISSUE TITLE
With ElasticSearch coming as standard in Magento 2.3, what is the future for this project?

### ISSUE THREAD

**Issue by woutersamaey** [Smile-SA/elasticsuite#1162]
With ElasticSearch coming as standard in Magento 2.3, what is the future for this project?

Can you share anything on this?

**Comment by woutersamaey** [comment]
@romainruaud, this sounds really good. Does this mean that upgrading to 2.3 will be (fairly) painless with regards to Elastic Search? I imagine we would simply disable Magento's own modules and keep Elastic Suite turned on, or do you think more will be involved?

**Comment by romainruaud** [comment]
In fact you do not have to disable any Magento legacy module : Elasticsuite is shipped as a Search Engine implementation, being respectful of Magento standards.

On your Back-Office you will be able to choose a search engine between MySQL Fulltext (legacy), Elasticsearch (legacy implementation of Elasticsearch 2.x), Elasticsearch 5.x (legacy), and Smile Elasticsuite.

Regards

**Comment by woutersamaey** [comment]
Superb, thanks!
