### ISSUE TITLE
InventoryData Not indexing Correctly when using Scheduled Indexer on EE 2.2.3

### ISSUE THREAD

**Issue by cft-mike** [Smile-SA/elasticsuite#1163]
InventoryData Not indexing Correctly when using Scheduled Indexer on EE 2.2.3

Magento Version : 2.2.3 EE

ElasticSuite Version : 2.5.9

Environment : Production

1. Indexers on schedule
2. Update an out of stock product to in stock (is_in_stock = 0 -> is_in_stock = 1)
3. Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\InventoryData::loadInventoryData($storeId, $productIds) returns old inventory data , so elastic datasource has incorrect values.

### Expected result
1. Index Current inventory data

### Actual result
1. Loads previous value from cataloginventory_stock_status, before cataloginventory_stock completes.

**Disclaimer:  i have not been able to test this on  a clean Magento install **

Here's my rabbit hole I've been down.

- I verified that the product ids have been added to cataloginventory_stock_cl  & catalogsearch_fulltext_cl 

- Which i then followed to: Smile\ElasticsuiteCatalog\Plugin\Indexer\Stock\ReindexProductsAfterStockUpdate

-  Then  I followed the $this->processFullTextIndex to Smile\ElasticsuiteCatalog\Plugin\Indexer\AbstractIndexerPlugin which i see skips the catalogSearch indexer if set to on schedule  

if (!$fullTextIndexer->isScheduled()) {
            if (!empty($processIds)) {
                $fullTextIndexer->reindexList($processIds);
            }
      }

- So from here i looked at the loadinventorydata function in Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource and saw that it is using the table 'cataloginventory_stock_status'. So i logged the results of this query and noticed that it was getting the stock status of product before cataloginventory_stock_status was reindexed.

**Comment by romainruaud** [comment]
Hello @cft-mike 

Thank you for submitting it.

We'll have a look on this one.

Regards

**Comment by cft-mike** [comment]
Thank you for looking into this.
I've found that our indexers appear to be in the incorrect order for some reason (TBD).
catalogsearch_fulltext is coming before cataloginventory_stock 
I've noticed magento added CatalogInventory to the  CatalogSearch module Sequence,
I'm expecting that to resolve my issue, i will test tomorrow.

**Comment by romainruaud** [comment]
Considering this one resolved since it was probably specific to your project/environment 

Feel free to open a new issue if still encountering the problem.
