### ISSUE TITLE
Searching Numerical SKU without spellchecking (Only Exact matches)

### ISSUE THREAD

**Issue by HannesJa** [Smile-SA/elasticsuite#1166]
First of all, Amazing how you employ the potential of the elasticsearch engine! Not even fair to compare between Magento's out of the box functionality with yours. Wonderful.

### Preconditions

Magento 2.1.9 (edit: Commerce Cloud Edition)
Smile Elasticsuite 2.3.11
Elasticsearch: 2.4

Search by Numerical SKU e.g. 9789525557992. This gives correct, exact results if the match is actually found. The problem is that the same product is found even with SKU 9789525157992.

Our webstore sells currently only books, so the SKU is also the ISBN in our case. We have set the ISBN to be searchable, but not spellchecked. The SKU was tried to be not used in spellcheck, but then the search did not find any results even with previously correct matching SKUs. So the SKU is now used in spellcheck again, so it is included in the search. However we would need it to be only exact matches. If someone searches a book by the ISBN (SKU), and no results is found, the customer should not be redirected to a product with different, albeit similar, product.

Environment : Both Developer and Production

Third party modules : Mirasvit Autocomplete (Only for showing results in autocomplete, not affecting the search functionality)

I have read through the open issues, and the closest I could find was this:
https://github.com/Smile-SA/elasticsuite/issues/412

However, adding the SKU to be used in the spellchecking gave the results that were mentioned above.

Is this something that is "fixed" in later Elasticsuite versions? If we upgrade our Magento instance to a 2.2.X later on, we could also employ a later version of Smile Elasticsuite along.

**Comment by romainruaud** [comment]
Hello,

first of all, thank you for the support you are showing to our module. I'm always happy to see people happy when using it. So many thanks !

You are right, you are actually using a slightly outdated version of Elasticsuite, which is not considered by our Open Source support commitment anymore. But yes, versions 2.4.0 and 2.5.2 have been embedding improvements for SKU search, so if you are updating your Magento instance, you'd definitely give a try to latest Elasticsuite versions to improve your search relevance.

Do not hesitate to give me more details,

Best regards

**Comment by romainruaud** [comment]
I close this one, since it has been answered.

Regards
