### ISSUE TITLE
errror install magento 2.2.6

### ISSUE THREAD

**Issue by tfmlink** [Smile-SA/elasticsuite#1181]
### Preconditions

Magento Version :

ElasticSuite Version :

Environment :

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

Installing data... {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}

**Comment by rikwillems** [comment]
@tfmlink you need to install both phonetic and icu analysers.
https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-phonetic.html
https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html

**Comment by romainruaud** [comment]
@rikwillems  is right, thank you for answering.

@tfmlink please refer to the manual : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x#installing-required-plugins
