### ISSUE TITLE
The search fields in the layered navigation do not work with cyrillisch characters

### ISSUE THREAD

**Issue by themoonwatcher** [Smile-SA/elasticsuite#1184]
I'm using 2.4 of Smile_ElasticsuiteCatalog on Magento CE 2.2.6

### Steps to reproduce
1. Type cyrillic text in search field for attribute options in the layered navigation.

### Expected result
1. Filter the options of the attribute.

### Actual result
1. Nothing happens.

### My sollution
In `attribute-filter.js` file there is a line like
`            .replace(/[^\w\-]+/g, '')       // Remove all non-word chars`
that removes cyrillic characters. If that line is commented, the search works fine;

**Comment by romainruaud** [comment]
Maybe @androshchuk you can be better than us to deal with this one.

Let us know if you have any knowledge about something that could be able to "filter all non-word characters except cyrillic".

Vanilla PHP would be the better, we do not plan to being forced to add third-party extensions to deal with this.

Regards

**Comment by romainruaud** [comment]
Fixed by PR #1471
