### ISSUE TITLE
 Products List Preview and Sorting does not update and wear random products

### ISSUE THREAD

**Issue by philsouza2016** [Smile-SA/elasticsuite#1188]
Products List Preview and Sorting does not update and wear random products even after being removed from the category.

Preconditions
Magento Version : Version 2.2.6 Open Source

ElasticSuite Version : ElasticSuite 2.6

Third party modules :

Steps to reproduce

When I changed the developer magento mode to production random products appeared in some categories. After returning to the developer mode again some sites returned to normal however in some categories, even removed the products insist on appearing in the positioning and only disappear asking to hide them ...

Actual result
See screenshot.
![products-sort-error](https://user-images.githubusercontent.com/21315154/48614744-23277000-e976-11e8-9ee3-08540e322f71.png)

**Comment by rbayet** [comment]
Hello @philsouza2016,

Did you encounter the problem on a classic category or on a virtual category, or both ?

Regards,

**Comment by rbayet** [comment]
So far, I have not been able to reproduce this issue.

The only way to get close to that is to : 
- have indexers in "Update by schedule"
- having crons disabled
- removing products assigned to *standard* category and simply saving the category

If the crons are not run, the category is not reindexed and 
- the removed products are still indexed as assigned to the category in ElasticSearch
- and so they are visible in front and in the Products List Preview and Sorting panel

**But** 
1. those are not "random" products
2. being in production or developer mode has not impact

**Comment by romainruaud** [comment]
Closed for being not-reproduced by our side and inactive for more than one month.

Feel free to open a new issue with expected details if you are still encountering this one.

Regards
