### ISSUE TITLE
(2.3.x) Magento_Search/form-mini not found

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/elasticsuite#1195]
Issue #1186 pointed to some web JS file relocations that occured in Magento 2.2.x and have been forward ported to Magento 2.3.x.
The PR #1190 merged on the 2.6.x branch makes sure that the code is compliant with the BC approach of the 2.2.x line.
The forward port of the JS files relocations in 2.3.x is no longer BC, though.

### Preconditions

Magento Version : CE 2.3.0-beta32 + sample data

ElasticSuite Version : 2.6.x branch (which includes PR #1190)

Environment : developer

Third party modules : N/A

### Steps to reproduce

1. Load the homepage

### Expected result

1. No JS loading error

### Actual result

1. /pub/static/version1542817982/frontend/Magento/luma/en_US/Magento_Search/form-mini.js in 404

**Comment by rbayet** [comment]
@romainruaud Merging 2.6.x on master is required before fixing / merging this one (or a conflict will occur).

**Comment by romainruaud** [comment]
Ok, I merged 2.6.x into master
