### ISSUE TITLE
Feature Request: Filter by in_stock and text-sub-filter

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#120]
Something Elasticsuite and most magento sites are missing:
Filter by is_in_stock (and/or sort by is_in_stock). 

Example Code: https://github.com/tzyganu/magento2-stock-filter

In IT many warranty and software/service components sit at stock level 0 and cloud up the catalog until you need to find the items. Prioritzation of is_sin_stock or stock >0 objects or filtering of these objects would be highly desirable!

I believe based on the sample code and existing code in Elasticsuite - this would be very easy to implement!
example: https://www.amazon.com/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=usb+drive 

Secondly : Breadcrumb text sub-filter. 

Say if I search on USB drives , get a large response, then wish to sub-filter the results on 4gb or other value without using attributes, I could type into a filter on the left to add a sub-filter with breadcrumbs without having to add the keyword to the main query causing inefficiency! 

Or if I start out with a category based view, and wish to refine the results on a text input or two, I could input a sub-filter on the results and preferabbly continue to sub-filter with more text in breadcrumb fashion!

Search for -> USB drive -> 4gb -> some other keyword not in facet -> 3rd filter.

These two search methods would bring Elasticsuite up to and beyond all other magento based Search methods and bring it up to industry standards!

Example:
http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&N=100007960&IsNodeId=1&srchInDesc=pack&hisInDesc=4gb%2C%20white&page=1&bop=And&ActiveSearchResult=True&PageSize=36&order=BESTMATCH

**Comment by romainruaud** [comment]
Hello @southerncomputer and thank you for submitting RFCs !

I split them in two different issues #124 and #125 which would be easier for us to prioritize on roadmap.

Therefore I am closing this one. Do not hesitate to propose other features, we are always happy to see people using this module and asking for new features.

Regards,
