### ISSUE TITLE
Support for composer elasticsearch 6.x

### ISSUE THREAD

**Issue by denissdubinin** [Smile-SA/elasticsuite#1201]
In composer.json file version ~5.1 of elasticsearch/elasticsearch is required. Which means supported versions are 5.1.0 - 5.1.9. So package cannot be installed using composer for the project that use ES 6.x.

Magento Version :
2.2.6

ElasticSuite Version :
2.6.3

Environment :
Developer

### Steps to reproduce

1. Open CLI
2. Do `composer require smile/elasticsuite ^2.6.0`

### Expected result

1. Package is installed

### Actual result

1. http://prntscr.com/lnhu0c

**Comment by rbayet** [comment]
Hello @denissdubinin,

I reckon you are using a Magento Open Source (CE) version ?
As it is not possible to install/require ~6.0 version of elasticsearch/elasticsearch on EE 2.2.6 due to conflicting requirements with the native EE magento/module-elasticsearch module.

Regards,
Richard.

**Comment by rbayet** [comment]
I'll leave this issue opened. The docs https://github.com/Smile-SA/elasticsuite/wiki puts forward compatibility with ES 6.x (see https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x), so it's only logical that composer requirements reflect that.

**Even if** it means that on a EE version, native magento/module-elasticsearch module will prevent installing elasticsearch/elasticsearch 6.0

**Comment by rbayet** [comment]
Closing as Elasticsuite does not need the 6.x elasticsearch PHP client to run correctly with a 6.x server, hence the dependency to the 5.x client as it stands today.
In that context, the risk that CE and EE users run different versions of the elasticsearch PHP client is not worth taking.

The docs should probably clearly states that the Elasticsuite composer requirements are self-sufficient, whether you install an ES 5.x or an ES 6.x server.
