### ISSUE TITLE
php Undefined store_id error on tracker log indexing

### ISSUE THREAD

**Issue by vanpoppel** [Smile-SA/elasticsuite#1212]
Magento Version : 2.2.7
ElasticSuite Version : 2.6.3 and ElasticSuiteCMS 2.2.1
Environment : Production
Third party modules : a lot.

### Steps to reproduce
1. Have lines like this in elasticsuite_tracker_log_event: 
`INSERT INTO `elasticsuite_tracker_log_event` (`event_id`, `date`, `data`)
VALUES ('ce6ef8485edc507a6b3efcd95848a652', '2018-07-19 11:43:56', '{\"image\":\"h.png\"}');`
2. Enable cron
3. Check cron logs

### Expected result
1. An exception is logged in stead of running into a PHP error.

### Actual result
`[2018-11-30 20:25:13] report.CRITICAL: Notice: Undefined index: store_id in /path/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/SessionIndex.php on line 81 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: store_id in /path/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/SessionIndex.php on line 81 at /path/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

### Additional comment
I have been trying to find out how a log event can be registered without a store id, and couldn't find the cause. It could be a process that was stuck, a php error, or something else. This can be caused by many things. That's another issue i guess.

**Comment by romainruaud** [comment]
Hello @vanpoppel 

thanks for submitting this one.

I agree, it's strange that events are generated without any store Id, and we'll have to dig more to find where it can be the case.

But it should be easy to fix this one actually by discarding events that do not have any store.

Thanks

**Comment by romainruaud** [comment]
Fixed by #1269 that will be part of next minor release.

Regards.
