### ISSUE TITLE
Release (tag) for Magento 2.2.7 support

### ISSUE THREAD

**Issue by kweij** [Smile-SA/elasticsuite#1217]
A fix has been applied for a change that happened in the latest Magento 2.2.7 release: https://github.com/Smile-SA/elasticsuite/issues/1195

This fix is scheduled to release with a 2.7 branch that seems to require Magento ^2.3, however this fix also needs to become available for Magento 2.2.7. So I suppose a 2.6.4 reelase should be created to continue support for Magento 2.2.7, because currently it's broken.

**Comment by kweij** [comment]
Ah, I see this is in progress: https://github.com/Smile-SA/elasticsuite/projects/33

**Comment by romainruaud** [comment]
Yes, we plan to release this one tomorrow, to be completely transparent. It will be a double release of Elasticsuite 2.6.4 and Elasticsuite 2.7.0.

Regards
