### ISSUE TITLE
magento 2.2.7 - Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by robert-schmidt** [Smile-SA/elasticsuite#1220]
### Preconditions

php 7.1, litespeed, mariadb latest, redis for sessions stoare, litemage for page cache

Magento Version : 2.2.7, CE

ElasticSuite Version : 2.6.4

Environment : Production

Third party modules : nothing relevant

### Steps to reproduce

Just upgraded to magento 2.2.7 and I started to get these error warnings in /var/report/:

`{"0":"Warning: Cannot modify header information - headers already sent by (output started at \\/public_html\/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php:114) in \\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php on line 148","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'Cannot modify h...', '\\/publ...', 148, Array)\n#1 \\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php(148): setcookie('X-Magento-Vary', '4717374a13c36f3...', 1544173948, '\/', '', true, true)\n#2 \\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php(101): Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager->setCookie('X-Magento-Vary', '4717374a13c36f3...', Array)\n#3 \\/public_html\/vendor\/magento\/framework\/App\/Response\/Http.php(108): Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager->setSensitiveCookie('X-Magento-Vary', '4717374a13c36f3...', Object(Magento\\Framework\\Stdlib\\Cookie\\SensitiveCookieMetadata))\n#4 \\/public_html\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(37): Magento\\Framework\\App\\Response\\Http->sendVary()\n#5 \\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/Response\/HttpPlugin.php(25): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendVary()\n#6 \\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\PageCache\\Model\\App\\Response\\HttpPlugin->beforeSendResponse(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#7 \\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#8 \\/public_html\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(117): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins('sendResponse', Array, Array)\n#9 \\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse()\n#10 \\/public_html\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#11 {main}","url":"\/elasticsuite\/tracker\/hit\/image\/h.png?page[store_id]=1&page[type][identifier]=catalog_category_view&page[type][label]=Catalog%20Category&page[category][id]=53&page[category][label]=Noutati&page[category][path]=1%2F2%2F53&page[product_list][page_count]=1&page[product_list][product_count]=169&page[product_list][current_page]=1&page[product_list][sort_order]=position&page[product_list][sort_direction]=asc&page[product_list][display_mode]=grid&session[uid]=5704ea78-4bff-4f7f-1efe-4f22818a84a1&session[vid]=5704ea78-4bff-4f7f-1efe-4f22818a84a1&page[site]=www.domain.com&page[url]=%2Fnoutati.html&page[title]=Nout%C4%83%C5%A3i%IDENTIFIER&page[referrer][domain]=www.domain.com&page[referrer][page]=%2F&page[resolution][x]=360&page[resolution][y]=720","script_name":"\/pub\/index.php"}`

### Expected result

No error warnings.

### Actual result

Error warnings as mentioned above.

**Comment by rbayet** [comment]
Hello @robert-schmidt,

I tested on a vanilla CE 2.2.7 + luma in production mode with a doc_root on pub, with FPC enabled (either the built-in or Varnish), and did not get that kind of errors when being logged for instance, which triggers setting the X-Magento-Vary cookie in the native `\Magento\PageCache\Model\App\Response\HttpPlugin` plugin.

Nothing odd strikes me in the code HTTP response plugin of the litemage for page cache, but I have never used that module.

Can you confirm that if you de-activate litemage for page cache, those errors disappear ?

Regards,

**Comment by romainruaud** [comment]
Closed for being inactive/stalled during one month.

Feel free to open a new issues with the needed details if still encountering this one.

Regards

**Comment by bhargavmehta** [comment]
Getting the same error
{"0":"Warning: Cannot modify header information - headers already sent by (output started at \/srv\/public_html\/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php:114) in \/srv\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php on line 148","1":"#0 [internal function]: Magento\\Framework\\App\\ErrorHandler->handler(2, 'Cannot modify h...', '\/srv\/public_htm...', 148, Array)\n#1 \/srv\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php(148): setcookie('wp_customerId', '', 1, '\/', 'www.cabletiesun...', false, false)\n#2 \/srv\/public_html\/vendor\/magento\/framework\/Stdlib\/Cookie\/PhpCookieManager.php(301): Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager->setCookie('wp_customerId', '', Array)\n#3 \/srv\/public_html\/app\/code\/WeltPixel\/GoogleTagManager\/Model\/CookieManager.php(92): Magento\\Framework\\Stdlib\\Cookie\\PhpCookieManager->deleteCookie('wp_customerId', Object(Magento\\Framework\\Stdlib\\Cookie\\PublicCookieMetadata))\n#4 \/srv\/public_html\/app\/code\/WeltPixel\/GoogleTagManager\/Plugin\/CookieManagement.php(44): WeltPixel\\GoogleTagManager\\Model\\CookieManager->setGtmCookies()\n#5 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): WeltPixel\\GoogleTagManager\\Plugin\\CookieManagement->afterDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/srv\/public_html\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(69): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#7 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/srv\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/srv\/public_html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#10 \/srv\/public_html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#11 \/srv\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#12 \/srv\/public_html\/pub\/index.php(38): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#13 {main}","url":"\/elasticsuite\/tracker\/hit\/image\/h.png?page[store_id]=1&page[type][identifier]=catalog_product_view&page[type][label]=Catalog%20Product%20View%20(Any)&page[category][id]=9&page[category][label]=Cable%20Ties&page[category][path]=1%2F2%2F9&page[product][id]=256&page[product][label]=Light%20Heavy%20Duty%20120lb%20Cable%20Ties&page[product][sku]=Light%20Heavy%20Duty%20120lb%20&session[uid]=3f6a8f6d-23a0-7d22-1901-4d57416fbcbd&session[vid]=54da28dd-d160-d647-9808-92148b4fa28b&page[site]=www.cabletiesunlimited.com&page[url]=%2Fcable-ties%2Flight-heavy-duty-120lb-cable-ties.html&page[title]=Light%20and%20Heavy%20Duty%20Nylon%206%20Cable%20Ties&page[referrer][domain]=www.cabletiesunlimited.com&page[referrer][page]=%2Fcable-ties.html&page[resolution][x]=1920&page[resolution][y]=1080","script_name":"\/index.php"}

**Comment by oviliz** [comment]
@robert-schmidt , are you using ElasticSuite?
https://github.com/Smile-SA/elasticsuite

**Comment by oviliz** [comment]
@romainruaud , does this offer enough additional information to reopen this issue?
https://sentry.io/share/issue/4ec640e27fe245fface0f691781ce848/
