### ISSUE TITLE
configurable products attributes not showing in layered navigation

### ISSUE THREAD

**Issue by badev-ajay** [Smile-SA/elasticsuite#1227]
Hi Team,

I have a lot of configurable products and configurable attribute is size attribute.   Size attribute is indexed in ElasticServer as but is not showing in layered navigation.

Example: Size Attribute is a global attribute only child products is selectable of configurable products. if i see in the database configure product size field has blank but its child product have size value
 

### Preconditions

Magento Version : Magento 2.2.6

ElasticSuite Version : 2.6

Environment : Developer

Third party modules : No

### Steps to reproduce

1.
2.
3.

### Expected result

1. its common configurable product attribute should come in layered navigation 

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
First question here : is your "Size" attribute set to be use in layered navigation ? https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration

**Comment by badev-ajay** [comment]
Hi Team ,

I am sharing screenshots 

![image](https://user-images.githubusercontent.com/42803285/49782896-f4ff3b00-fd3d-11e8-948c-a0763b6bb05b.png)

![image](https://user-images.githubusercontent.com/42803285/49782909-fe88a300-fd3d-11e8-9ade-c69f79762664.png)

![image](https://user-images.githubusercontent.com/42803285/49782919-06484780-fd3e-11e8-87b5-20abc8d11843.png)

![image](https://user-images.githubusercontent.com/42803285/49782933-14966380-fd3e-11e8-8e90-2987dbe8b76e.png)

**Comment by badev-ajay** [comment]
Hi Team, I think the issue was in the product. now it resolved please close this ticket.
