### ISSUE TITLE
Categories & Products Missing result collection 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1230]
### Preconditions (*)

1. Migrated store from 1.9.0.1 to 2.3.0 
2. Magento version 2.3.0
3. ElasticSuite  "version": "2.7.0",
4. Multiple Categories Created, with Sub Categories, previously set to "is_anchor" in Magento 1
5. Parent Category has 215 products, approx 145 active
 
### Steps to reproduce (*)

1. Migrate Data from Magento 1 to Magento 2 (w/o settings) on Vanilla Magento Install 
2. Configure ElasticSuite 
3. Reindex Data including ElasticSuite 

### Expected result (*)

1.  Click on parent category on front-end 
2. See 145 products in the collection 

### Actual result (*)

1. See 2 products in the collection 
<img width="1364" alt="screen shot 2018-12-11 at 9 46 45 am" src="https://user-images.githubusercontent.com/7387019/49812507-39351000-fd2b-11e8-8de2-7ce2495b612e.png">

Child Categories categories are also missing products, do you have any thoughts? 

If I disable elastic suite, and reindex data, and click on the top level category expected products are visible. 

ElasticSuite disabled
<img width="1462" alt="screen shot 2018-12-11 at 9 46 39 am" src="https://user-images.githubusercontent.com/7387019/49812490-2faba800-fd2b-11e8-82d0-2c982a13f091.png">

I'm struggling to know if this is a Migration issue, however, with stock Magento it works as expected. 

As this is a development environment I can share any data necessary to help debug.  
Thanks. 

******EDIT******
After attaching the screenshots, I noticed that it appears there are categories missing from the layered navigation entirely.   Maybe that's important. Also posted to incorrect Repository! Whoops.

**Comment by duffner** [comment]
Hmm looks interesting, catalog size is 19,000 visible simple products.  

No complex products

**Comment by duffner** [comment]
I applied the commit as a patch and it works as expected!  Thanks for the hint @rbayet

**Comment by rbayet** [comment]
Hello @duffner,

You're welcome.
Closing this issue as we've just released 2.7.1 which embeds the fix for #1223 

Regards,
