### ISSUE TITLE
[Question] Query text matching a product from a comma separated string attribute value

### ISSUE THREAD

**Issue by liamjtoohey** [Smile-SA/elasticsuite#1232]
Query text matching product from comma separated string attribute value
-----------

Hi!

First of all, forgive me, I am new to elasticsuite! I have a question in regards to query text matching a product from a comma separated string attribute value. I was wondering how this would work?

Example below (`alternative_items` being the product attribute containing comma separated string): 

**Example product**
- Product SKU: `SKU01`
- `alternative_items` value: `SKU02,SKU03,SKU04`

The use case would be "customer searches for 'SKU03'. The product with `SKU03` is of course returned, but we also want to return product matching `SKU01` - as `SKU03` is an alternative item for this".

If I were to set this attribute as used in search with a reasonable weight, would I get `SKU01` returned when searching for `SKU03`? If not, what kind of customisation is required?

Magento Version : EE `2.2.3`

ElasticSuite Version : `2.6.4`

Environment : Production

**Comment by liamjtoohey** [comment]
@rbayet Thanks a lot for the info! This information is really useful. Will give this a test with my actual SKU format.

**Comment by romainruaud** [comment]
@liamjtoohey can we close this one ?

**Comment by liamjtoohey** [comment]
@rbayet Thanks again for this information, I've since decided to add a new data source to copy the list of alternative products skus the indexed sku field (as mentioned above).

I was just wondering, how can I ensure the data for the `alternative_items ` attribute exists in `$indexData`? I fear that loading this attribute value within my `addData` function for each product would be inefficient.

**Comment by liamjtoohey** [comment]
Ignore the above, found the relevant (and super useful) docs here: https://github.com/Smile-SA/elasticsuite/wiki/Indexing#dynamic-fields-provider

@romainruaud Happy for this one to be closed, thanks again!
