### ISSUE TITLE
How to Create Nested Objects

### ISSUE THREAD

**Issue by truelogicapp** [Smile-SA/elasticsuite#1233]
@romainruaud 

I would like to Create Nested Objects like category and price for my Attributes without define in elasticsuite_indices.xml 

Is it possible to create Nested Objects mapping into code?

### Preconditions
Magento Version : 2.1.3

ElasticSuite Version : 2.4.6

Environment : Production

Third party modules : No

### Steps to reproduce
```
<field name="category.category_id" type="integer" nestedPath="category" />
                <field name="category.position" type="integer" nestedPath="category" />
                <field name="category.is_parent" type="boolean" nestedPath="category" />
                <field name="category.name" type="string" nestedPath="category">
                    <isSearchable>1</isSearchable>
                    <isUsedInSpellcheck>1</isUsedInSpellcheck>
                    <isFilterable>0</isFilterable>
                </field>
```
how to achieve the above Nested Objects without define in XML?

**Comment by romainruaud** [comment]
I'm afraid that a mapping will be mandatory if you created nested objects.

But mapping can be done either via XML, or via the datasource, see https://github.com/Smile-SA/elasticsuite/wiki/Indexing#dynamic-fields-provider

As stated in the documentation, if your field is "static" and will have always the same name, it's easier to add it with an XML config file. If it's something which is more dynamic, you'll probably want to define a `DynamicFieldProvider` attached to your datasource.

Regards

**Comment by truelogicapp** [comment]
Hi Romain,

Thanks for your reply.

But there is no example how to define nested objects using DynamicFieldProvider
interface

I am facing issue creating nested objects using this. We are able to
create each attribute configuration (defined via the Magento's Back-Office)
into an array but nested objects having error. Can you guide or give an
example of same.

Kind Regards
Raman

**Comment by romainruaud** [comment]
I've never tried by myself but according to how it's done for the attributes : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php#L204

And how the Field class is defined : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Index/Mapping/Field.php#L77

You should be able to create your nested fields with the FieldFactory, just by using the proper nestedPath.

Regards

**Comment by romainruaud** [comment]
I close this once since I answered.

Regards
