### ISSUE TITLE
Search Suggestion doesnt work

### ISSUE THREAD

**Issue by wouter-toppershops** [Smile-SA/elasticsuite#1234]
### Preconditions

Magento Version : 2.3

ElasticSuite Version : 2.7.1

Environment : DEVELOP

Third party modules :

### Steps to reproduce

1. search in bar, and wait for search suggestion
2.
3.

### Expected result

1. error on the suggestion controller (https://pastebin.com/DTBfZwj9), our custom attribute does not have a `type` => `termBucket` but its `0` => `termBucket` caused by `Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\AttributeAggregation:65` there is no `type` key set.

### Actual result

1. 
![screenshot from 2018-12-13 13-16-07](https://user-images.githubusercontent.com/40226924/49939436-22ceb600-fedd-11e8-8fc2-ce0b628449ac.png)

**Comment by wouter-toppershops** [comment]
See https://github.com/Smile-SA/elasticsuite/pull/1235

**Comment by rbayet** [comment]
Confirmed on M2 2.3.x and 2.7.x / developer mode

**Comment by wouter-toppershops** [comment]
See New Pull: https://github.com/Smile-SA/elasticsuite/pull/1237

**Comment by rbayet** [comment]
Hello @wouter-toppershops,

I've seen it, thanks !

Regards
