### ISSUE TITLE
Update Uninstall Docs

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1240]
Please update uninstall docs https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall

### Preconditions

Magento Version : 2.2.5 CE

ElasticSuite Version : 2.6.3

Environment : Developer

### Steps to reproduce

1. Install ElasticSuite
2. Try uninstalling using the details here https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall

### Expected result

1. Everything should be removed from the database without error

### Actual result

1. It seems some tables are not removed, such as `smile_elasticsuite_optimizer_limitation`
2. Received error about `smile_elasticsuite_optimizer_search_container` not existing. This might not be a valid issue as I had to run the uninstall several times and this table may have been deleted the first time around.

**Comment by romainruaud** [comment]
Point 1 was correct, I added it to the wiki.

I did not reproduce point 2, most probably irrelevant since you suspect you already deleted the table.

Regards
