### ISSUE TITLE
catalog_product index does not exist yet

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Smile-SA/elasticsuite#1249]
Don't know why.

This is a fresh install of elasticsuite on an existing Magento site.
Wanting to improve the speed of search as its too slow.

Magento 2.2.5
composer require smile/elasticsuite ~2.6.0

```
curl http://localhost:9200/_cat/indices?v
```
Does not show a magento2_default_catalog_product* entry.

There are lots of products, how can I have it create the index?
Reindex all works but same problem.

```
 bin/magento index:status
+---------------------------------+--------+-----------+-----------------+------------------+
| Title                           | Status | Update On | Schedule Status | Schedule Updated |
+---------------------------------+--------+-----------+-----------------+------------------+
| Catalog Product Rule            | Ready  | Save      |                 |                  |
| Catalog Rule Product            | Ready  | Save      |                 |                  |
| Catalog Search                  | Ready  | Save      |                 |                  |
| Category Products               | Ready  | Save      |                 |                  |
| Customer Grid                   | Ready  | Save      |                 |                  |
| Design Config Grid              | Ready  | Save      |                 |                  |
| ElasticSuite Category Indexing  | Ready  | Save      |                 |                  |
| ElasticSuite Thesaurus Indexing | Ready  | Save      |                 |                  |
| Product Categories              | Ready  | Save      |                 |                  |
| Product EAV                     | Ready  | Save      |                 |                  |
| Product Price                   | Ready  | Save      |                 |                  |
| Stock                           | Ready  | Save      |                 |                  |
+---------------------------------+--------+-----------+-----------------+------------------+
```

**Comment by romainruaud** [comment]
Hello @LiamKarlMitchell 

If you are installing Elasticsuite on top of an existing Magento2 website, you'll have to check if Elasticsuite is properly set as search engine in the Back Office (Stores > Configuration > Catalog > Catalog Search).

An old value can exist in case the config has been already saved previously.

Can you check this and give us more details ? 

Regards

**Comment by romainruaud** [comment]
@LiamKarlMitchell any update on this one ?

**Comment by romainruaud** [comment]
I close this one for being stalled / inactive for too long.

Feel free to open a new issue if you are still encountering a problem.

Regards

**Comment by pushpendra07** [comment]
Hello @romainruaud, 

It's showing same issue when search.

`Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed.`
