### ISSUE TITLE
RFC : Additional fulltext filter

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#125]
submitted by @southerncomputer in #120 

> Secondly : Breadcrumb text sub-filter.
> 
> Say if I search on USB drives , get a large response, then wish to sub-filter the results on 4gb or other value without using attributes, I could type into a filter on the left to add a sub-filter with breadcrumbs without having to add the keyword to the main query causing inefficiency!
> 
> Or if I start out with a category based view, and wish to refine the results on a text input or two, I could input a sub-filter on the results and preferabbly continue to sub-filter with more text in breadcrumb fashion!
> 
> Search for -> USB drive -> 4gb -> some other keyword not in facet -> 3rd filter.
> 
> These two search methods would bring Elasticsuite up to and beyond all other magento based Search methods and bring it up to industry standards!
> 
> Example:
> http://www.newegg.com/Product/ProductList.aspx?Submit=ENE&N=100007960&IsNodeId=1&srchInDesc=pack&hisInDesc=4gb%2C%20white&page=1&bop=And&ActiveSearchResult=True&PageSize=36&order=BESTMATCH

**Comment by afoucret** [comment]
Not sure if we want to add this feature.
I found it confusing as a matter of use UX.
Plus, I do not consider it as being core feature. Maybe a plugin can do the job.

I would prefer some kind of semantic query parsing which should be able to tokenize the query issued by the customer into semantic chunks.

If many users are voting this one up maybe I can change my mind on this.
