### ISSUE TITLE
Bundle product with fixed price is in-correct in autocomplete

### ISSUE THREAD

**Issue by ibeschastnaya** [Smile-SA/elasticsuite#1250]
We noticed the same issue as described here: https://github.com/Smile-SA/elasticsuite/issues/1182

### Preconditions
Create bundle product with fixed price.

Magento Version : EE 2.2.6

ElasticSuite Version :  "2.6.4",

Environment : Magento Cloud in production mode

Third party modules :

### Steps to reproduce
Open storefront.
Enter query to the search field to search for your bundle with fixed price
Pay attention to the price of the Bundle in quick search drop-down.

### Expected result
 Fixed price should be shown.

### Actual result
Price range is shown.
![image](https://user-images.githubusercontent.com/10774035/50833538-1f064600-135a-11e9-9ce4-76e977e87993.png)

This issue probably related to the fact that for product query for Autocomplete doesn't have price_type, so products rendered with range instead of fixed price.

**Comment by rbayet** [comment]
Fixed by 
- #1281 for M2 2.2.x
- #1282 for M2 2.3.x
