### ISSUE TITLE
Unable to install Elasticsuite on Magento Cloud

### ISSUE THREAD

**Issue by jfgalano** [Smile-SA/elasticsuite#1251]
### Preconditions

Magento Version : MAgento Cloud Commerce 2.2.5

ElasticSuite Version : 2.6.0

Environment : production

Third party modules :

### Steps to reproduce

1. update the services.yaml file
2. try to deploy
3. fail to compile

### Expected result

1. elasticsuite installed

### Actual result

1. fail on compile with error on these lines:
configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic

**Comment by ibeschastnaya** [comment]
We had the same issue that related to default ElasticSuite settings that look to localhost, so we need to  update config.php to look on Cloud Elasticsearch instance:
`'catalog' => [
                'search' => [
                    'elasticsearch_server_hostname' => 'elasticsearch.internal',
                    'elasticsearch_server_port' => '9200',
                    'elasticsearch5_server_hostname' => 'elasticsearch.internal',
                    'elasticsearch5_server_port' => '9200'
                ]
            ],
            'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'elasticsearch.internal:9200',
                    'enable_https_mode' => '0',
                    'enable_http_auth' => '0',
                    'http_auth_user' => '',
                    'http_auth_pwd' => '',
                    'scheme' => 'http'
                ]
            ]`

**Comment by djenvert** [comment]
Have you read the documentation? 

https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall

**Comment by jfgalano** [comment]
Yes of course, but the compile command fails on these line:
configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic

**Comment by romainruaud** [comment]
@jfgalano I don't understand your last comment.

Could you post a detailed error log so we can investigate further ?

Regards

**Comment by romainruaud** [comment]
@jfgalano please append an update to this issue otherwise we'll have to close it for being inactive for too long.

regards
