### ISSUE TITLE
RequestMapper incorrectly extracts filters from search criteria

### ISSUE THREAD

**Issue by grandpalacko** [Smile-SA/elasticsuite#1253]
### Preconditions
Magento Version: Magento Community Edition 2.3.0
ElasticSuite Version: 2.7.2
Environment: Developer

### Steps to reproduce
1. Create a Search API request with price filter (from and to condition types)

```
/rest/V1/search?
searchCriteria[filterGroups][1][filters][0][field]=price.price&
searchCriteria[filterGroups][1][filters][0][value]=50&
searchCriteria[filterGroups][1][filters][0][conditionType]=from&
searchCriteria[filterGroups][2][filters][0][field]=price.price&
searchCriteria[filterGroups][2][filters][0][value]=100&
searchCriteria[filterGroups][2][filters][0][conditionType]=to&
searchCriteria[requestName]=catalog_view_container
```

### Expected result
1. Items in the results set will have a price between 50 and 100

### Actual result
1. The `from` filter is ignored, items will have a price between 0 and 100

**Comment by romainruaud** [comment]
Confirmed (both the bug, and the associated fix).

Thank you for spotting this one and for contributing the solution.

Regards !

**Comment by romainruaud** [comment]
Closed by merging the associated PR.

Will be part of next 2.7.3 minor release.

Regards
