### ISSUE TITLE
eav_attribute_options sort_oder not respected

### ISSUE THREAD

**Issue by shochdoerfer** [Smile-SA/elasticsuite#1256]
### Preconditions
Magento Version : 2.2.7
ElasticSuite Version : 2.6.4
Environment : Developer

Elasticsuite does not respect the sort_order defined in eav_attribute_options when populating the attributes in the resulting document. The attributes (ids & values) will always be sorted by id.

**Comment by romainruaud** [comment]
Hello @shochdoerfer 

what do you mean by "in the resulting document" ? You mean the document inside the Elasticsearch index ? 

What's your goal with having the options sorted propely inside the document ? Are you querying the Elasticsearch index directly ?

Regards

**Comment by romainruaud** [comment]
Main problem for me is that sorting data during indexing could impact index performances.

Do you have some metrics with/without your fix ?

Also, you are kinda hacking the system by using a fulltext search index as a data store :/

**Comment by shochdoerfer** [comment]
In the current demo we have a few thousand products in the database and a lot of store views that expose part of the product catalog. The indexing did not get much slower, it is not really noticeable. If I am not mistaken, you are using caching anyways, maybe there's a option to cache that information as well.

Not sure if we are hacking the system, we don't only use it for search ;) It kind of acts as data store for the frontend, keeping the data in an optimized form. Search is just the icing on the cake.

**Comment by romainruaud** [comment]
we do not plan to fix this actually, since we consider it a very specific need.

Considering you found a workaround, I close this one.

Best regards
