### ISSUE TITLE
Strange behaviour when search by SKU formed like: A0123456

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#1257]
I have a problem with the search for some SKU codes formed by a letter and a series of numbers.
These products are simple products associated with grouped or configurable products.

The strange thing is that by looking for example for: C53208 are correctly found products that have inside them a product associated with SKU C53208, but at the same time many other products that have the letter C in the title.

on the other hand, looking only for the numeric part, the results only include the fathers products and exclude all the other products (the operation is perfect).

you can check the operation here:

https://www.brignoliarmi.it/catalogsearch/result/?q=C53208
https://www.brignoliarmi.it/catalogsearch/result/?q=53208

Magento Version : 2.2.6
ElasticSuite Version : 2.6.2
Environment : Production

**Comment by CRYX2** [comment]
sorry, does anyone have an idea if I can fix or if I have to change some settings?

**Comment by rbayet** [comment]
Hello @CRYX2,

Do you have other examples on your site ?
Because the two links you provided seem to contradict the following : 

> The strange thing is that by looking for example for: C53208 are correctly found products that have inside them a product associated with SKU C53208, but at the same time many other products that have the letter C in the title.
> 
https://www.brignoliarmi.it/catalogsearch/result/?q=C53208 to me only shows products with exactly a product of SKU C53208 in them (2 products out of 2) and no other with only the C letter.

> on the other hand, looking only for the numeric part, the results only include the fathers products and exclude all the other products (the operation is perfect).
And https://www.brignoliarmi.it/catalogsearch/result/?q=53208 only displays a single product which does NOT reference 53208 (at least in the visible information available on the product page).

Regards,
Richard.

**Comment by CRYX2** [comment]
> Hello @CRYX2,
> 
> Do you have other examples on your site ?
> Because the two links you provided seem to contradict the following :
> 
> > The strange thing is that by looking for example for: C53208 are correctly found products that have inside them a product associated with SKU C53208, but at the same time many other products that have the letter C in the title.
> 
> https://www.brignoliarmi.it/catalogsearch/result/?q=C53208 to me only shows products with exactly a product of SKU C53208 in them (2 products out of 2) and no other with only the C letter.
> 
> > on the other hand, looking only for the numeric part, the results only include the fathers products and exclude all the other products (the operation is perfect).
> > And https://www.brignoliarmi.it/catalogsearch/result/?q=53208 only displays a single product which does NOT reference 53208 (at least in the visible information available on the product page).
> 
> Regards,
> Richard.

Hello, I've solved by creating a custom elasticsuite_analysis.xml file, this is the content:

`<analysis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_analysis.xsd">
    <filters>
        <filter name="word_delimiter" type="word_delimiter" language="default">
            <generate_word_parts>true</generate_word_parts>
            <catenate_words>true</catenate_words>
            <catenate_numbers>true</catenate_numbers>
            <catenate_all>true</catenate_all>
            <split_on_case_change>true</split_on_case_change>
            <split_on_numerics>false</split_on_numerics>
            <preserve_original>true</preserve_original>
        </filter>
        <filter name="reference_word_delimiter" type="word_delimiter" language="default">
            <generate_word_parts>false</generate_word_parts>
            <catenate_words>false</catenate_words>
            <catenate_numbers>false</catenate_numbers>
            <catenate_all>false</catenate_all>
            <split_on_case_change>true</split_on_case_change>
            <split_on_numerics>false</split_on_numerics>
        </filter>
    </filters>
</analysis>`

**Comment by rbayet** [comment]
Hi, @CRYX2 

That's good news !

Looking at the SKU mapping in 2.7.x, and considering your initial request, my first hunch was indeed to fix the `reference_word_delimiter` filter of the `reference` analyzer to disable `split_on_numerics` and/or re-enable `preserve_original`.

The last changes on SKU search indeed went towards allowing "partial SKU search" (see  #810), which a `split_on_numerics = true` helps, but obviously is not what you expected.
Be aware that the changes you introduced in `reference_word_delimiter` should disable that "partial SKU search" from now on and those same changes in `word_delimiter` would also disable that "partial SKU search" if a SKU is mentioned in another indexed field (for instance a product description).
This may or may not be an acceptable consequence for you.

For future references (and for an internal request that has been submitted to me), can you clarify your use cases / desired (and obviously obtained) behaviours ?
If the user searches for an alphanumeric SKU starting with a letter then
- and the product is available in the store then
- - [ ] only find that product and redirect to the product page
- - [ ] find that product and others that have a similar SKU
- - - [ ] preferably those with the same SKU prefix (which could be difficult in your case)
- - - [ ] those with a simular SKU
- and the product is not available then
- - [ ] find others that have a similar SKU
- - - [ ] preferably those with the same SKU prefix (which could be difficult in your case)
- - - [ ] those with a simular SKU

Regards,
Richard

**Comment by romainruaud** [comment]
This one looks stalled and might have been already solved (writing custom analysis is the good thing to do)

I'm closing it, since now everything you need to know about SKU is explained on the wiki : https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuBasics

Best regards
