### ISSUE TITLE
Spellchecker / Fuzzy queries refactoring.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#1266]
There are functional holes in the spellchecking / fuzzy query building.

 - termVectors query is run against 'spelling' field, so only against 'is_used_in_spellcheck' fields.

 - if no results, a fuzzy query is built on 'spelling', and on all 'is_used_in_spellcheck' fields (having a weight > 1).

=> can cause 0 results for a query that should have some (value can exist on a field which is not 'used_in_spellcheck').

**Comment by southerncomputer** [comment]
any progress on this?

**Comment by romainruaud** [comment]
At some point, we also used "search" meta-field for term vectors : https://github.com/Smile-SA/elasticsuite/pull/532/commits/13fb6f91557d35b749df2fde1ebbd4089e0b35f3
