### ISSUE TITLE
Unknown filter type [phonetic] for [phonetic]

### ISSUE THREAD

**Issue by ravichand2689** [Smile-SA/elasticsuite#1267]

**Comment by romainruaud** [comment]
Closed.

Please respect the issue template and fill all needed details.

Most probable answer to your problem is : you are missing the phonetic plugin for ES. please refer to the documentation : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x#installing-required-plugins

**Comment by ananth-iyer** [comment]
In case anyone trying to install **elasticsearch plugins** on **Ubuntu server**, use below commands:

> /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
> /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-phonetic

or
Search the tool in your Linux server using below command:
> locate elasticsearch-plugin

then install [Smile-SA/elasticsuite](https://github.com/Smile-SA/elasticsuite) extension on your Magento 2 root
