### ISSUE TITLE
Autocomplete not rendering products properly in M2.3.0

### ISSUE THREAD

**Issue by qbo-tech** [Smile-SA/elasticsuite#1285]
Autocomplete is finding products but not rendering products properly in M2.3.0 after fresh Install.

![image](https://user-images.githubusercontent.com/22456214/51818126-46826b80-2293-11e9-9c9e-3ee4d3191355.png)

Autocomplete block is rendering default Luma only (form-mini.js) instead of Smile's form-mini.js :
pub/static/frontend/Magento/luma/es_MX/Magento_Search/js/form-mini.js 

![image](https://user-images.githubusercontent.com/22456214/51818266-dc1dfb00-2293-11e9-9d53-4ca771f4e70e.png)

(phtml module files load, however requite-js config seems like not updating the quickSearch component with the new form-mini.js)

### Preconditions

Magento Version : 2.3.0

ElasticSuite Version : 2.7.4 / master

Environment : PHP 7.2.14. Docker 18.06,  ES 5, Magento Default mode, Default Luma Theme

Third party modules : None

### Steps to reproduce

1. Install Magento 2.3.0 with Sample Data
2. Install Elastic Suite via composer
3. Configure Elasticsearch & Backoffice settings
4. Reindex

### Expected result

1. Autocomplete shoud show product images & prices as in demo screenshots.

### Actual result

1. Products shown as terms (in-line text, no images, no title)

**Comment by romainruaud** [comment]
It seems that it's actually loading the "wrong" `form-mini.js` file and using the legacy one instead of the Elasticsuite one.

Did you override the theme prior to install Elasticsuite ? 

Especially this file : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml

You might have your own `form.mini.phtml` which was already customized prior to Elasticsuite installation.

Regards

**Comment by qbo-tech** [comment]
Thanks for your reply @romainruaud .

Well this is a default installation with no modifications on the theme at all. 

Actually the file module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml is being rendered, I double checked.

The problem seems to be more RequireJs related, since the quickSearch component -defined in the require-config.js file-  called in the template you mentionded, loads the default form-mini.js instead of yours. So thats why I think is requireJs related.

Has this particular feature been tested with M2.3.0 ?

Any other suggestions to check with ?

**Comment by qbo-tech** [comment]
Well it seems like the issue appears only on **Magento default mode**. Switching to developer mode fixed the issue.

**Comment by romainruaud** [comment]
Most probably something related to the global requirejs-config.json file not being rebuilded after your first ElasticSuite install.

May I close this one ?

**Comment by maxq** [comment]
I have the same issue, how do we fix this?
Custom theme must be overwriting the file
