### ISSUE TITLE
401 (Unauthorized) error when accessing the relevance configuration

### ISSUE THREAD

**Issue by haelbichalex** [Smile-SA/elasticsuite#1286]
### Preconditions

MacOS Mojave, Docker 

Magento Version : 2.3.0 EE

ElasticSuite Version : 2.7.4

Environment : developer

### Steps to reproduce

1. Backend --> Elasticsuite --> Search Relevance --> Relevance Configuration
2. Click on one of the option containers

### Expected result

1. No errors

### Actual result

1. I get an 401 Unauthorized error in console when accessing following url 
```
admin/smile_elasticsuite/search_request_relevanceconfig/state/key/7cb02d9d6bf6a828aff5ab536f1156228937c6f6de428229aa2a36b2a2cd100a/?isAjax=true&container=relevance_fulltext_base_settings&value=1&form_key=U1c0tjWXgIRVFoDo
```

Not sure if this is a problem with my setup, because it also occurs on our staging environment where there is also a basic authorization alert displaying when opening the configuration container.

**Comment by romainruaud** [comment]
Actually I do not reproduce this issue. 

Are you still facing it ? Which ACLs are associated to your admin account ?

Regards

**Comment by romainruaud** [comment]
@haelbichalex any update ?

**Comment by haelbichalex** [comment]
Hi @romainruaud. The issue is still there, but we think it's because of our varnish password protection. I'll close this issue for now, as I installed your module on another Magento 2 instance and couldn't reproduce this. 
I'll let you know when I found a solution 👍

**Comment by kamzata** [comment]
I got the same error. Did you solve?
