### ISSUE TITLE
Dev Question: index related_skus and make sure the products are visible 

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1288]
We have product relations where product A1, A2 have different spare parts via B, C, D.

Now I want to create a virtual category which contains only A1, A2 if any spare parts are assigned, AND those spare parts are enabled.

Where can I inject custom code to index just condition and how would A1 be updated if the part B, C or D becomes disabled (or enabled)?

**Comment by romainruaud** [comment]
How are modelized relationships between your products ? 

If they are standard magento relationships for composite products (configurable, bundle, grouped...etc) they should be already indexed properly via the chilren_ids.

If it's not like this, you could probably take some inspiration about how it's done here : 

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L46

We fetch the children products (if any), and then via the `filterCompositeProducts` we are able to discard any configurable product that is having all of his childs disabled.

That's not exactly what you are planning to do, but it can be a good starting point.

regards

**Comment by amenk** [comment]
Thanks for the answer, not it's related products, but I think it is a great starting point.
