### ISSUE TITLE
Cookie Messages on Login Page not cleared when ElasticSuite Tracker is active

### ISSUE THREAD

**Issue by DanieliMi** [Smile-SA/elasticsuite#1291]
### Preconditions

Full elasticsuite installed
Catalog is protected by login

Magento Version : 2.2.6
ElasticSuite Version : 2.64
Environment : Developer or Production
Third party modules : Quite some :-)

### Steps to reproduce

1. Login to the shop with a wrong password
2. Flash messages 'You did not sign in correctly or your account is temporarily disabled.' is shown
3. Login with right password
4. On the start page, still the message is shown, which should not

not 100% reproducible in Chrome, but in Firefox quite well

### Expected result

1. Flash message should appear only once

### Actual result
Logged in page with 
![selection_239](https://user-images.githubusercontent.com/31039652/51998758-8a56ba00-24b9-11e9-8cb2-ced299338cdd.png)

### Debugging

First we inserted some debug code - the cookie is removed properly

![selection_234](https://user-images.githubusercontent.com/31039652/51998545-2af8aa00-24b9-11e9-9c4c-6a523732cfce.png)

as you can see 
![selection_233](https://user-images.githubusercontent.com/31039652/51998519-20d6ab80-24b9-11e9-9541-75b3e0868c37.png)

We think it is caused by the fact that the tracker's h.png is loaded BEFORE messages.js kicks in, and thus sends the cookies to the server. Then in the next request, Magento sends this cookie message again.

![developer tools - sata shop - http --shop sata com magento weide imi local-dealer_de_de-_232](https://user-images.githubusercontent.com/31039652/51998631-4bc0ff80-24b9-11e9-9d5a-8c335fd83f3a.png)

For now we disable the tracker, but it would be great if this could be fixed.

**Comment by rbayet** [comment]
Confirmed on EE 2.2.6 with a basic "Private Sales" website restriction applied  :

![ee226_website_restriction](https://user-images.githubusercontent.com/2353374/53650288-7e8b1e80-3c44-11e9-9fd3-e7de484458a4.png)

![ee226_private_sales_postlogin](https://user-images.githubusercontent.com/2353374/53650377-b1351700-3c44-11e9-9872-a949fa3f1181.png)

**Comment by southerncomputer** [comment]
I have modified tracking,js to be called by config.phtml and variables.phtml using requirejs - which should be how the js is called with domReady! to delay it from being called too early. I'd suggest it is implemented this way anyhow! Magento 2.3.1 does some erratic behavior with javascript load/execute order as you are seeing!

**Comment by romainruaud** [comment]
@southerncomputer can you publish your patch as a PR ?

**Comment by southerncomputer** [comment]
unfortunately, it is still having this problem of being caught by Private site restrictions and getting a 302 to customer/account/login/ . I had to whitelist the url for now otherwise you get wonky page loads within page-loads which amplified by javascript actions cause double event-firing and the login referer script redirects to hit.php.. etc. It must be the way tracking.js is calling hit that is messing with everything, i'm guessing it is not using xhr/xmlhttprequest/jsonp method to bypass the security frontend modules!

**Comment by romainruaud** [comment]
I close, this issue is too old. Regards
