### ISSUE TITLE
Dev-Question: Reuse the product search in an own function

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1295]
We have a custom autocomplete where we want to utilize the elasticsearch product search.

In our own constructor we inject:

        \Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider $collectionProvider,

And get the product collection like this:

        $productCollection = $this->collectionProvider->getProductCollection();

Now the following happens: The Catalog visibility is used, even we inject the Autocomplete provider.

When debugging this with a breakpoint in 

    \Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider::__construct

I saw that the $collectionProcessors are not injected, despite being present in vendor/smile/elasticsuite/src/module-elasticsuite-catalog/etc/frontend/di.xml:129

    <type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider" shared="true">
        <arguments>
            <argument name="collection" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection</argument>
            <argument name="collectionProcessors" xsi:type="array">
                <item name="filters" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Filter</item>
                <item name="attributeSelect" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\AttributeSelector</item>
                <item name="attributeAggregations" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\AttributeAggregation</item>
            </argument>
        </arguments>
    </type>

Versions:

    smile/elasticsuite                                2.6.4                  
    magento/product-community-edition                 2.2.6                  

*Our ref: 41689*

**Comment by romainruaud** [comment]
How are you building your custom autocomplete ? 

If it's an API call, please note that the collection processors are injected only in **frontend** DI, meaning they are not injected in other areas (adminhtml, webapi_rest, webapi_soap).

Regards

**Comment by amenk** [comment]
Yes it is an API ...

**Comment by amenk** [comment]
Was able to solve it by copy & paste

in my global di.xml



    

    <virtualType name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection" type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">quick_search_container</argument>
        </arguments>
    </virtualType>

    <type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider" shared="true">
        <arguments>
            <argument name="collection" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection</argument>
            <argument name="collectionProcessors" xsi:type="array">
                <item name="filters" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Filter</item>
                <item name="attributeSelect" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\AttributeSelector</item>
                <item name="attributeAggregations" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\AttributeAggregation</item>
            </argument>
        </arguments>
    </type>

Wondering if there is a nicer way ...

Thanks anyways!

**Comment by romainruaud** [comment]
The nicer way would be that we do this copy inside etc/di/webapi_rest/di.xml file of Elasticsuite directly :) 

But since there is no autocomplete endpoint in the legacy Magento 2 API, we did put this only on the `frontend` DI. 

We'll have a look at this one for next minor release I guess.

Regards

**Comment by romainruaud** [comment]
Closed as being answered.

In any cases, we won't add this DI into the webapi_rest since on a legacy Magento+Elasticsuite install you are not supposed to have webapi_rest endpoint for autocomplete.

If people want to build it by themselves, they'll have to add the DI as you did, so it' non-blocking for people to build on top of Elasticsuite.

Regards
