### ISSUE TITLE
Dev-Question: Filter only by SKU in Autocomplete Query

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1297]
For a while I am trying now to only filter by SKU in autocomplete

My requirement is to search for partially typed SKUs.

So i have 123456 (a Yoga Whatever) in the catalog and want to find it by typing 123

This works:

        /** @var \Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider */
        protected $collectionProvider;
        $productCollection = $this->collectionProvider->getProductCollection();

        $productCollection->setSearchQuery($sku);

But it will also match in other fields, so I can search for "Yoga" as well.

So i tried to add

        $productCollection->addFieldToFilter('sku', ['like' => '%'. $sku . '%']);

But now the autocomplete - partial match functionality is lost. I can only find the article by typing 123456.

I also tried to construct a TERM query with option "field" but that also seems to loose the autocomplete functionality.

Do you have some pointer into the right direction?

*Our ref: 41689*

**Comment by romainruaud** [comment]
Did you give a try to your `like` workaround without the `%` ? Or maybe the `fulltext` filter operator.

I did not test it, but the filter is transformed into an Elasticsearch query here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Search/Request/Query/Filter/QueryBuilder.php

From what I can see, `%` is not needed.

Regards

**Comment by amenk** [comment]
So you mean a like, but without "%" ?

**Comment by amenk** [comment]
Will try...

**Comment by romainruaud** [comment]
any update on this one ?

**Comment by amenk** [comment]
Did not work I think. I currently went with

        $sku = (string) (int) $sku; // quickfix, disallow non-number numbers, see #41689
        $productCollection->setSearchQuery($sku);

**Comment by romainruaud** [comment]
Ok, I close this one since it has been answered.

**Comment by amenk** [comment]
please reopen .. quickfix does not help, if you have enter a number that is also part of the product name

**Comment by amenk** [comment]
This works when sending to elasticsearch, but I have no clue how to construct such a wildcard query using the smilesa elastic module:

	{
	  "size": 25,
	  "sort": [
	    {
	      "_score": {
		"order": "desc"
	      }
	    },
	    {
	      "entity_id": {
		"order": "desc",
		"missing": "_first",
		"unmapped_type": "keyword"
	      }
	    }
	  ],
	  "from": 0,
	  "query": {
	    "bool": {
	      "filter": {
		"bool": {
		  "must": [
		    {
		      "wildcard": {
		        "sku": "100*"
		      }
		    },
		    {
		      "term": {
		        "stock.is_in_stock": {
		          "value": true,
		          "boost": 1
		        }
		      }
		    },
		    {
		      "terms": {
		        "visibility": [
		          3,
		          4
		        ],
		        "boost": 1
		      }
		    }
		  ],
		  "must_not": [],
		  "should": [],
		  "boost": 1
		}
	      },
	      "boost": 1
	    }
	  }
	}
