### ISSUE TITLE
Elasticsearch 7 support & Elasticsearch 5 deprecation

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#1303]
Elasticsearch 5.x will be EOL on March 11.

Since we support ES 6, it's not a major issue, and customers will be able to upgrade smoothly.

We'll have to implement ES 7 support, and flag ES 5 as deprecated, and to be removed on a later version.

In parallel, maybe we should contribute ES 6 support to Magento legacy Elasticsearch implementation to ensure their framework will allow installing the Elasticsearch client v6.

**Comment by woutersamaey** [comment]
Are there many breaking changes for 7.x?

**Comment by romainruaud** [comment]
@woutersamaey not that much, there is some things to be taken into account. 

In fact I decided to put this on pause until elasticsearch releases their official PHP client, which was a bit delayed. Since it's available now, we'll be able to get back to this topic.

Anyway, such a change will be for ElasticSuite 2.9 (next major version) so that anybody still on Elasticsearch 5 will be able to stay on ElasticSuite 2.8 until they migrate.

Regards

**Comment by romainruaud** [comment]
done with #1773
