### ISSUE TITLE
Tracking pixel slowing down load of all pages

### ISSUE THREAD

**Issue by Shimon2** [Smile-SA/elasticsuite#1304]
The tracking pixel is now slowing down the load of all product pages.  It was not a problem until recently.  Now it add 1.5 to 5 seconds on the page load

How can I disable it

### Preconditions
Magento 2.2.2

Magento Version : 2.2.2

ElasticSuite Version :

Environment : Production

Third party modules :

### Steps to reproduce

1. Go to a product page using tools.pingdom to see load time of all components of page
2. Load time of page is 3.5 seconds
3. Load time of " https://t.smile.eu/h.png?magento2"  is 1.5 seconds

### Expected result

1. Load time of page until recently was about 2 seconds

### Actual result

1. load time of page is 3.5 seconds

**Comment by romainruaud** [comment]
@Shimon2 

Tracking pixel to external Smile domain has been removed a long time ago. 

We totally agree that it was not a glorious idea, but we needed to be able to know who was using our module so ... 

We gracefully accepted to put out our eyes and removed it in version 2.5.9 .

I deduce that you are using a Elasticsuite version <2.5.9 which is therefore way outdated. You should upgrade to a more recent version to get rid of the tracking pixel, but also to benefits many new features that you are actually missing :)

Regards
