### ISSUE TITLE
The model "Based on attribute value" accepts decimal attributes, but not integer

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/elasticsuite#1307]
Thanx first for your wonderful Suite and job !

I have tried the brand new model "Based on attribute value". I have noticed this : you can configure attribute targeting attributes with "decimal validation" but you can't target attributes with "integer validation" (validate digit option).

Could you please add this use case ?

Thanx again !

Magento Version : Magento commerce 2.2.5
ElasticSuite Version : 2.6.3
Environment : Dev & Prod modes

Regards
![2019-02-18_133005](https://user-images.githubusercontent.com/47741932/52951167-53b9e400-3381-11e9-9feb-a38b6373954b.jpg)

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor releases 2.6.7 & 2.7.5
