### ISSUE TITLE
[ENHANCEMENT] Optimizer : do not propose "preview" for not selected request types

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/elasticsuite#1309]
Hi !
When editing Optimizer configuration, you can select **request types** : Catalog Product Search AND/OR Category Product View.

It should not be possible (given that it is not relevant) to preview a request type that has not been selected in the configuration above. In other words, if Catalog Product Search is **not** a selected request type, then it is not previewable.

Regards

![2019-02-18-14_05_02](https://user-images.githubusercontent.com/47741932/52953008-8c0ff100-3386-11e9-848e-11dfaa5dd242.png)

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor releases 2.6.7 & 2.7.5
