### ISSUE TITLE
[Enhancement] Display attribute name with attribute Magento code

### ISSUE THREAD

**Issue by FredRaym** [Smile-SA/elasticsuite#1311]
Hi,

On large catalogs, it happens that we use several times the same name for different attributes (that refer to different attribute sets for example). Then, it is difficult to select the right attribute in Rule condition list (cf. capture)

I propose to display attribute code either next to the attribute name, or in a tooltip. For example : **<attribute name> [<attribute code>]**

Regards

![2019-02-18_155853](https://user-images.githubusercontent.com/47741932/52959283-21ff4800-3396-11e9-8c4b-b92bd72d9949.png)

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor releases 2.6.7 & 2.7.5
