### ISSUE TITLE
Excluding a short word (like "red") from being considered a stopword

### ISSUE THREAD

**Issue by lewisje** [Smile-SA/elasticsuite#1319]
### Preconditions

Magento Version : CE 2.2.7

ElasticSuite Version : 2.6.6

Environment : Production

Third party modules :

* Adfab_Gdpr
* Amasty_Base
* Amasty_CommonRules
* Amasty_Conditions
* Amasty_ShippingArea
* Amasty_Shiprestriction
* Amasty_Xnotif
* Anowave_Package
* Anowave_Sort
* Apptrian_FacebookPixel
* Apptrian_ImageOptimizer
* Apptrian_Minify
* Bss_CustomProductAttributeExport
* CompactCode_FixProductBreadcrumbs
* CustomerParadigm_OrderComments
* Dotdigitalgroup_Email
* Drc_Soldout
* Flancer32_Minify
* Fooman_EmailAttachments
* Fooman_GoogleAnalyticsPlus
* Fooman_PrintOrderPdf
* Fooman_SameOrderInvoiceNumber
* GalacticLabs_DisableCompareProducts
* Hackaton_EAVCleaner
* Ho_Templatehints
* Igorludgero_WarmCache
* Infortis_Base
* Infortis_Brands
* Infortis_Cgen
* Infortis_Dataporter
* Infortis_Infortis
* Infortis_Ultimo
* Infortis_UltraMegamenu
* Infortis_UltraSlideshow
* Itoris_Core
* Itoris_ProductGrid
* Klarna_Core
* Klarna_Kp
* Klarna_Ordermanagement
* Mageplaza_Gdpr
* Mageplaza_GoogleAnalytics
* Mageplaza_Seo
* Mirasvit_Profiler
* ParadoxLabs_Authnetcim
* ParadoxLabs_TokenBase
* ShipWorks_Module
* Swissup_RefinedUrl
* Tnegeli_M2CliTools
* Unirgy_Giftcert
* Unirgy_SimpleLicense
* Unirgy_SimpleUp
* WebdesignStudenten_Adminemails
* WebdesignStudenten_Backorder
* WebdesignStudenten_Htmlsitemap
* Webspeaks_Notification
* Yireo_CheckoutTester2

### Steps to reproduce

1. Search for the term `red` in the store's search bar (in a store with many products that are red, have "red" in their names or descriptions, or have words like "colored" in searchable attributes).

### Expected result

1. Results are returned that are relevant for `red`.

### Actual result

1. All available products are returned, even those that are not relevant for `red`.

**Comment by rbayet** [comment]
Hello @lewisje,

Could you give us more information about your catalog and your expectations ?
For instance, what is your catalog size : only visible products in search and total size - for instance including not visible simple products assigned to a configurable production ?

What is the percentage of products that have the term `red` (and only `red`, not `colored`) in those two groups ?

Have you already tried to tweak the cutoff frequency ?

Regards,

**Comment by lewisje** [comment]
Sorry, the real problem was a native Magento setting: I just realized that I had set the minimum search query to be 4 characters long, and when I lowered it, the search worked as expected.
