### ISSUE TITLE
JS errors and non working search with enabled ublock origin

### ISSUE THREAD

**Issue by Wohlie** [Smile-SA/elasticsuite#1321]
Hi,

i use chrome with enabled ublock origin as adblocker with this configuration:
![ublock](https://user-images.githubusercontent.com/329240/53151258-058c2700-35b3-11e9-9d32-fa42d2dab70c.png)

In this case is get js errors, because the js file `...Smile_ElasticsuiteTracker/js/tracking.js` is blocked:
![jserrors](https://user-images.githubusercontent.com/329240/53151519-bbf00c00-35b3-11e9-90d5-cbf2a8c34373.png)

The bigger problem is, also the search function is not working in case of the js errors.

Fix:
Add a try catch to all `smileTracker` calls.

**Comment by rbayet** [comment]
Hello @Wohlie,

Can you provide the version of Magento2 and ElasticSuite you are using (I know it might not relevant, but still) and on which Chrome version/platform you are using ?

On M2 2.3.0, I can reproduce the first issue with ublock origin installed in Chromium 65 on Ubuntu **but** the autocomplete search is not blocked.
Can you detail that additional error ?

Regards,

**Comment by romainruaud** [comment]
Fixed by associated PR, will be part of next minor releases 2.6.7 & 2.7.5
