### ISSUE TITLE
PHP Fatal error:  Cannot use Smile\\ElasticsuiteCore\\Model\\Search\\Request\\RelevanceConfig\\Structure\\Element\\Section\\Visibility as Visibility because the name is already in use in /var/www/web/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/Structure/Element/Section.php on line 19

### ISSUE THREAD

**Issue by metamasterplay** [Smile-SA/elasticsuite#134]
Environment:
- Magento 2.1.1 in production mode
- PHP 7.0.11
- Elasticsuite 2.2.x-dev installed with composer.

Steps to  reproduce:
- Go to Backend > Smile ElasticSuite > Search relevancy

Expected result:
- Access Search relevancy menu entry
What happens:

- Apache2 throws a 500 error. Investigating the apache2 log shows this error:
` PHP Fatal error:  Cannot use Smile\\ElasticsuiteCore\\Model\\Search\\Request\\RelevanceConfig\\Structure\\Element\\Section\\Visibility as Visibility because the name is already in use in /var/www/web/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/Structure/Element/Section.php on line 19`

Possible fix:
- Remove `use Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Section\Visibility;` in `smile/elasticsuite/src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/Structure/Element/Section.php` as it's already declared.

**Comment by Nielex** [comment]
I've the same issue

Mage2 2.1.1 in dev mode
php 7.0.11
Elasticsuite 2.2.x-alpha2

**Comment by Nielex** [comment]
Maybe better solution to use a alias for Visibility in this file?

`smile/elasticsuite/src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/Structure/Element/Section.php`

buy changing `use Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Section\Visibility` to `use Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Section\Visibility as Vis;` (or whatever allias) and changing the revenrance in the rest of this file

**Comment by romainruaud** [comment]
did you test it @Nielex ? Since I am not able to reproduce the issue for now, I cannot be sure this can really fix it.

**Comment by metamasterplay** [comment]
I think the problem comes from a conflict with another non-standard composer package which uses the same class name. So maybe aliasing it is the better solution.

I'll try to investigate the other modules installed to see if I can find the culprit.

**Comment by romainruaud** [comment]
There is a PR here : https://github.com/Smile-SA/elasticsuite/pull/136

I cannot reproduce the issue so I am not able to ensure it will fix it. Feel free to test it if needed.

**Comment by southerncomputer** [comment]
What does your /etc/php.d/10-opcache.ini look like? Improper settings may confuse opcache with similar named files?

Here is mine:
zend_extension=opcache.so
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 12
opcache.max_accelerated_files = 90000
opcache.max_wasted_percentage = 5
opcache.use_cwd = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 120
opcache.file_update_protection = 2
opcache.revalidate_path = 1
;opcache.save_comments = 1
;opcache.load_comments = 1
opcache.fast_shutdown = 1
opcache.enable_file_override = 1
opcache.optimization_level = 0xffffffff
opcache.inherited_hack = 1
opcache.blacklist_filename=/etc/php.d/opcache-default.blacklist
opcache.max_file_size = 0
opcache.consistency_checks = 0
opcache.force_restart_timeout = 60
opcache.error_log = ""
opcache.log_verbosity_level = 1
opcache.preferred_memory_model = ""
opcache.protect_memory = 0

**Comment by romainruaud** [comment]
@Nielex and @metamasterplay can you check with the opcode configuration provided by @southerncomputer ? 

So we will be able to know if it is an opcode issue instead of an elasticsuite one.

**Comment by metamasterplay** [comment]
This is my phpinfo output regarding opcache:
```
Directive	Local Value	Master Value
opcache.blacklist_filename	no value	no value
opcache.consistency_checks	0	0
opcache.dups_fix	Off	Off
opcache.enable	On	On
opcache.enable_cli	Off	Off
opcache.enable_file_override	Off	Off
opcache.error_log	no value	no value
opcache.fast_shutdown	0	0
opcache.file_cache	no value	no value
opcache.file_cache_consistency_checks	1	1
opcache.file_cache_only	0	0
opcache.file_update_protection	2	2
opcache.force_restart_timeout	180	180
opcache.huge_code_pages	Off	Off
opcache.inherited_hack	On	On
opcache.interned_strings_buffer	4	4
opcache.lockfile_path	/tmp	/tmp
opcache.log_verbosity_level	1	1
opcache.max_accelerated_files	2000	2000
opcache.max_file_size	0	0
opcache.max_wasted_percentage	5	5
opcache.memory_consumption	64	64
opcache.optimization_level	0x7FFFBFFF	0x7FFFBFFF
opcache.preferred_memory_model	no value	no value
opcache.protect_memory	0	0
opcache.restrict_api	no value	no value
opcache.revalidate_freq	2	2
opcache.revalidate_path	Off	Off
opcache.save_comments	1	1
opcache.use_cwd	On	On
opcache.validate_timestamps	On	On
```
It's the standard configuration packaged in ppa:ondrej/php repository for Ubuntu 16.04.1
Changing opcache.enable_file_override to 1 seems to have fixed the issue for me.

**Comment by afoucret** [comment]
PR #136 seems to fix it.

The opcache config may be a good solution if it does not works (It was unknown to me. Thx @southerncomputer)
