### ISSUE TITLE
How to save "manual sort order" in category programmatically?

### ISSUE THREAD

**Issue by Emanuel-23** [Smile-SA/elasticsuite#1348]
I would like to set and save "manual sort order"s for some specific categories in a Magento 2.2 Shop *programmatically*. What is the best and easiest way to achieve this?

**Additional context**
We have some categories, that differ from the default categories in Magento 2 and show some kind of ranking for a range of products. Until now, we have set our custom order ranking by saving our custom positions to Magentos default category position attribute. As far is I know, this does not work when using ElasticSuite and in order to avoid confusion, you even disabled the Position column in Magentos backend ([#344](https://github.com/Smile-SA/elasticsuite/issues/344#issuecomment-286697672)).

Magento Version : 2.2.7 Magento CE
ElasticSuite Version : 2.6.0
Environment : developer mode

**Comment by romainruaud** [comment]
Probably the good entry point should be here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-virtual-category/Model/ResourceModel/Category/Product/Position.php#L119

You'll have to previously set the products on the category via `setSortedProducts()` and `setBlacklistedProducts()`
