### ISSUE TITLE
swatches.css load in catalogsearch_result_index

### ISSUE THREAD

**Issue by jeroenkosse** [Smile-SA/elasticsuite#1349]
In the catalogsearch_result_index from the module-elasticsuite-swatches source there is a head tag to add the <css src="Magento_Swatches::css/swatches.css"/>. This files is not longer existing in the Magento 2.3 version and should be removed from this xml to prevent errors when trying to add the swatches.css to the layout.

### Preconditions
We use nginx with php7.

Magento Version : CE 2.3

ElasticSuite Version : 2.7.4

Environment : Production

Third party modules : No

### Steps to reproduce
1. Enable all elasticsuite modules
2. Load a page
3. Check the error log for the error

### Expected result
1. No errors in the log for fetching the swatches.css that is missing from the filesystem

### Actual result
1. Error message with Unable to get content  for Magento_Swatches/css/swatches.min.css

**Comment by rbayet** [comment]
Fixed by #1359
