### ISSUE TITLE
Layered Navigation does not show within Advanced Search

### ISSUE THREAD

**Issue by harrigo** [Smile-SA/elasticsuite#1351]
I have no layered navigation showing within my advanced search results making for a very poor experience within advanced search.

### Preconditions
Magento Version : 2.2.7
ElasticSuite Version : ^2.6.0
Environment : Developer / Production

### Steps to reproduce
1. Navigate to advanced search on site
2. Search for a product

### Expected result

1. List of products shown with layered navigation to refine search

### Actual result

1. Blank sidebar shown without a layered navigation

**Comment by romainruaud** [comment]
Hello,

there is no layered navigation on the legacy Magento2 Advanced Search.

We did not add it either on Elasticsuite and will not introduce this.

However, you could achieve it by yourself easily with some custom development.

Regards
