### ISSUE TITLE
Virtual category rule with "is one of" option

### ISSUE THREAD

**Issue by chombe** [Smile-SA/elasticsuite#1353]
Hi there. 
If someone can help me please.

I'm using latest 2.7.5 Smile elasticsuite with 2.3.0 magento version.
Is ElasticSuite able to create virtual category rule with "is one of" option?
Currently, if i want to create virtual category rule which takes more then one product i need to use multiple contains options like this:

![image](https://user-images.githubusercontent.com/2380250/54591482-9deabf80-4a2a-11e9-9aca-bd68a295c907.png)

So, for rule with lots of products this could be quite unsuitable.
Is there a way to implement rule like when creating catalog rule:

![image](https://user-images.githubusercontent.com/2380250/54591687-08036480-4a2b-11e9-9bf7-2859f6ee0ede.png)

I'm probably missing something so any help would be great.

**Comment by romainruaud** [comment]
@chombe there is no point on using virtual categories to map a list of SKUS.

To be honest, I'm thinking about removing it.

If you wanna build a category based on a list of products, just use the legacy grid, it's made for this.

For any other attributes, the "is one of" operator is available for multiple options based attributes.

Regards

**Comment by chombe** [comment]
@romainruaud  thanks for answer.

For "legacy grid" you mean Magento products grid? 
![image](https://user-images.githubusercontent.com/2380250/54596718-882ec780-4a35-11e9-85a1-9bd7495f099a.png)

If so, then this category wouldn't be virtual.
We are thinking using this virtual category rule for a marketing purpose. 
This virtual category rule is so cool feature because category is not assigned to a product.
If you go on product edit form page, there is no category tied to a product (if product is affected with virtual category rule)
