### ISSUE TITLE
Problem with layered navigation - Custom backend model - Always visible configuration

### ISSUE THREAD

**Issue by EstebanSerfe** [Smile-SA/elasticsuite#1357]
We have an attribute (varchar) that has a custom backend model (which was added on DI)
If we go to a category and select the option "Always visible" for that value there is an error when navigating the view.

### Preconditions
Magento Version : CE 2.2.6
ElasticSuite Version : 2.6.7
Environment : Developer
Third party modules :

### Steps to reproduce
1. Add an attribute (varchar) wich has a model to validate (no transformations)
2. Set attribute as searchable and visible on layered navigation
3. Add the backend model to the backend model listing on the di.xml of the module. https://github.com/Smile-SA/elasticsuite/issues/943#issuecomment-395771677
4. Go to a category > Display options > attribute > Always Visible
5. Enter to the category view on the frontend

### Expected result
1. See the attribute on the layered navigation with it's possible options on the layered navigation.

### Actual result
<code>
1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $name of Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term.

Exception #0 (BadMethodCallException): Missing required argument $name of Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term.
#0 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime('Smile\\Elasticsu...', Array, Array)
#1 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments('Smile\\Elasticsu...', Array, Array)
#2 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Smile\\Elasticsu...', Array)
#3 /var/www/html/generated/code/Smile/ElasticsuiteCore/Search/Request/Aggregation/Bucket/TermFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('\\Smile\\Elastics...', Array)
#4 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Aggregation/AggregationFactory.php(57): Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\TermFactory->create(Array)
#5 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Aggregation/AggregationBuilder.php(121): Smile\ElasticsuiteCore\Search\Request\Aggregation\AggregationFactory->create('termBucket', Array)
#6 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Aggregation/AggregationBuilder.php(78): Smile\ElasticsuiteCore\Search\Request\Aggregation\AggregationBuilder->buildAggregation(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), Array, 'outside_diamete...', Array)
#7 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Builder.php(157): Smile\ElasticsuiteCore\Search\Request\Aggregation\AggregationBuilder->buildAggregations(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), Array, Array)
#8 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(540): Smile\ElasticsuiteCore\Search\Request\Builder->create(1, 'catalog_view_co...', 0, 10, NULL, Array, Array, Array, Array)
#9 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(435): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->prepareRequest()
#10 /var/www/html/vendor/magento/framework/Data/Collection/AbstractDb.php(340): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFiltersBefore()
#11 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(472): Magento\Framework\Data\Collection\AbstractDb->_renderFilters()
#12 /var/www/html/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(909): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFilters()
#13 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(777): Magento\Eav\Model\Entity\Collection\AbstractCollection->load(false, false)
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product\Collection->load(false, false)
#15 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): TriangleMFG\ProductAttributes\Model\ResourceModel\Product\Collection\Interceptor->___callParent('load', Array)
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): TriangleMFG\ProductAttributes\Model\ResourceModel\Product\Collection\Interceptor->Magento\Framework\Interception\{closure}()
#17 /var/www/html/generated/code/TriangleMFG/ProductAttributes/Model/ResourceModel/Product/Collection/Interceptor.php(403): TriangleMFG\ProductAttributes\Model\ResourceModel\Product\Collection\Interceptor->___callPlugins('load', Array, Array)
#18 /var/www/html/vendor/magento/module-review/Observer/CatalogBlockProductCollectionBeforeToHtmlObserver.php(38): TriangleMFG\ProductAttributes\Model\ResourceModel\Product\Collection\Interceptor->load()
#19 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\Review\Observer\CatalogBlockProductCollectionBeforeToHtmlObserver->execute(Object(Magento\Framework\Event\Observer))
#20 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\Review\Observer\CatalogBlockProductCollectionBeforeToHtmlObserver), Object(Magento\Framework\Event\Observer))
#21 /var/www/html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#22 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('catalog_block_p...', Array)
#23 /var/www/html/vendor/magento/module-catalog/Block/Product/ListProduct.php(471): Magento\Framework\Event\Manager\Proxy->dispatch('catalog_block_p...', Array)
#24 /var/www/html/vendor/magento/module-catalog/Block/Product/ListProduct.php(116): Magento\Catalog\Block\Product\ListProduct->initializeProductCollection()
#25 /var/www/html/vendor/magento/module-catalog/Block/Product/ListProduct.php(187): Magento\Catalog\Block\Product\ListProduct->_getProductCollection()
#26 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(666): Magento\Catalog\Block\Product\ListProduct->_beforeToHtml()
#27 /var/www/html/generated/code/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(882): Magento\Framework\View\Element\AbstractBlock->toHtml()
#28 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Catalog\Block\Product\ListProduct\Interceptor->toHtml()
#29 /var/www/html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('category.produc...')
#30 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('category.produc...')
#31 /var/www/html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('category.produc...')
#32 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('category.produc...', true)
#33 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement('category.produc...', true)
#34 /var/www/html/vendor/magento/module-catalog/Block/Category/View.php(100): Magento\Framework\View\Element\AbstractBlock->getChildHtml('product_list')
#35 /var/www/html/vendor/magento/module-catalog/view/frontend/templates/category/products.phtml(18): Magento\Catalog\Block\Category\View->getProductListHtml()
#36 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/v...')
#37 /var/www/html/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Category\View), '/var/www/html/v...', Array)
.......
</code>

For what I've been able to debug, there problem is that the attribute is added to the facet but without a name or field inside their configuration.

**Comment by romainruaud** [comment]
Hello @EstebanSerfe 

for commodity of reproducing your bug, can you provide : 

- the exact backend model of your attribute (even if it's only for validation)
- what's exactly on the `catalog_eav_attribute` and `eav_attribute` for this specific attribute

And some details about the attributes : is it a select or a multiselect ? things like this.

Regards

**Comment by EstebanSerfe** [comment]
Hi @romainruaud:
One of the validation model has:
```
namespace Sample\ProductAttributes\Model\Entity\Attribute\Backend;

use Helper\Data as Attributes;

class UpToTwelve extends \Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend
{
    public function validate($object)
    {
        $attrCode = $this->getAttribute()->getAttributeCode();
        $label = $this->getAttribute()->getStoreLabel();
        $value = $object->getData($attrCode);
        if (!$this->isPositiveOrZero($value)) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('Please enter a number 0 or greater in the "%1" field.', $label)
            );
        }
        if (!$this->decimalPlaces($value, 12)) {
            throw new \Magento\Framework\Exception\LocalizedException(
                __('"%1" field error. Please enter a number up to twelve decimal places.', $label)
            );
        }
        $this->validateIsNotNull($object);
        return true;
    }
}
```

The backtrace has issues on the bearing_width attribute which has the following configuration:
**eav_attribute**
```
INSERT INTO `eav_attribute` (`attribute_id`, `entity_type_id`, `attribute_code`, `attribute_model`, `backend_model`, `backend_type`, `backend_table`, `frontend_model`, `frontend_input`, `frontend_label`, `frontend_class`, `source_model`, `is_required`, `is_user_defined`, `default_value`, `is_unique`, `note`) VALUES(154, 4, 'bearing_width', NULL, 'Sample\\ProductAttributes\\Model\\Entity\\Attribute\\Backend\\Validate\\UpToTwelve', 'varchar', NULL, 'Sample\\ProductAttributes\\Model\\Entity\\Attribute\\Frontend\\MetersValue', 'text', 'Bearing Width', 'validate-number validate-zero-or-greater', NULL, 0, 0, NULL, 0, 'Enter bearing width in meters')
```
**catalog_eav_attribute**
```
INSERT INTO `catalog_eav_attribute` (`attribute_id`, `frontend_input_renderer`, `is_global`, `is_visible`, `is_searchable`, `is_filterable`, `is_comparable`, `is_visible_on_front`, `is_html_allowed_on_front`, `is_used_for_price_rules`, `is_filterable_in_search`, `used_in_product_listing`, `used_for_sort_by`, `apply_to`, `is_visible_in_advanced_search`, `position`, `is_wysiwyg_enabled`, `is_used_for_promo_rules`, `is_required_in_admin_store`, `is_used_in_grid`, `is_visible_in_grid`, `is_filterable_in_grid`, `search_weight`, `additional_data`, `is_displayed_in_autocomplete`, `is_used_in_spellcheck`, `facet_min_coverage_rate`, `facet_max_size`, `facet_sort_order`, `display_pattern`, `display_precision`) VALUES
(154, NULL, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 1, NULL, 0, 1, 90, 10, '_count', NULL, 0);
```

I've added the following into the module di.xml:
```
<type name="Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\AttributeData">
        <arguments>
            <argument name="indexedBackendModels" xsi:type="array">
                <item name="UpToTwelve" xsi:type="string">\Sample\ProductAttributes\Model\Entity\Attribute\Backend\Validate\UpToTwelve.php</item>
            </argument>
        </arguments>
    </type>
```

If I leave the setting in "auto" and set facet on 0, the attribute appears. Only when the "always visible" option is activated is when this happens.

Let me know if you need more information.

**Comment by romainruaud** [comment]
Quick update : I reproduced the same attribute as yours.

For now, what I can clearly see is that the attribute is not added to the Elasticsearch index mapping, and no value is indexed at all in any products, most probably explaining the issue you are encountering.

I'll investigate more.

**Comment by romainruaud** [comment]
So, I did re-create the same attribute as yours, only difference is that I did set a frontend_model which equals to `null` since I do not have your frontend model.

Result in a category is the following, so no problem for me : 

![Sélection_678](https://user-images.githubusercontent.com/15340849/56301335-e4216480-6137-11e9-84b3-ae2b20357bee.png)

Are you sure you cleaned up the cache and processed a full reindex after adding this attribute and setting data to it ? 

Does your products have any value for this attribute ? 

As additional debug information, can you provide : 

- the mapping of your ElasticSearch index 
- content of some documents to see how data is stored insided them

Regards
