### ISSUE TITLE
i have download smile elasticsuite where should i place.inside app/code folder or vendor folder.by which name should i place

### ISSUE THREAD

**Issue by LavanyaCS** [Smile-SA/elasticsuite#1358]
### Preconditions

Magento Version :2.3

ElasticSuite Version :2.7

Environment :Developer

Third party modules :Yes

### Steps to reproduce

1.If i have added in app/code showing error called alive cluster is not found
2.i want to know to configure inside the magento 2.3 where should place by which format
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Please refer to the documentation : https://github.com/Smile-SA/elasticsuite/wiki
