### ISSUE TITLE
Category product collection empty if I put container div.sidebar.main before main in 2columns-left.xml

### ISSUE THREAD

**Issue by spanatiy** [Smile-SA/elasticsuite#1370]
I tried to load div.sidebar.main container before main container  in custom theme but got an issue.

Magento 2.3
Php-fpm 7.1
Percona 5.7

Magento Version : CE
ElasticSuite Version : elasticsearch 6.2.4

Environment : Developer

Third party modules :
Smile_ElasticsuiteAdminNotification
Smile_ElasticsuiteCore
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteTracker
Smile_ElasticsuiteVirtualCategory
### Steps to reproduce
1. Edit vendor/magento/module-theme/view/frontend/page_layout/2columns-left.xml
2. Change <container name="div.sidebar.main" htmlTag="div" htmlClass="sidebar sidebar-main" **before="main"**>
3. Check any category with products.

### Expected result

1. Products should be in collection and be visible on page.

### Actual result

1. Instead of products I get notice  We can't find products matching the selection.

I tried to backtrace issue and found that collection becomes empty in ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php 
after  public function getFacetedData($field) execution.

**Comment by david-fuehr** [comment]
I experienced the same issue. All categories are empty after upgrade to:
* `smile_elasticsuite: 2.8.0` on
* Magento Commerce 2.3.1 with
* PHP 7.2
* Elasticsearch 6.6

In our theme I found:
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <!-- ... -->
        <move element="div.sidebar.main" destination="columns" before="main"/>
    </body>
</page>
```

After deleting this line (and flushing `layout full_page block_html`) the products reappeared in the categories.

**Comment by davidhiendl** [comment]
We also experience this issue with several test env's and customized themes that move the sidebar. Reverting the change or switching to the base theme for testing purposes resolves the issue.

**Comment by jajajaime** [comment]
I am experiencing the same issue with moving the layered nav section, or even just changing the category layout to 1column.

**Comment by david-fuehr** [comment]
This seems a related issue: https://github.com/Smile-SA/elasticsuite/issues/1404. We experienced empty categories after moving the filters around in categories (as described above) and on the search result page.
In both cases we could work around this issue by tweaking the `layout.xml`

**Comment by romainruaud** [comment]
This is already stated in our FAQ here : 

https://github.com/Smile-SA/elasticsuite/wiki/FAQ#i-have-problems-with-the-pagination--sorting

And link to a veeeeery ooold Magento 2 legacy bug : 

https://github.com/magento/magento2/issues/7253
