### ISSUE TITLE
Text based swatches returning incorrect results in layered navigation

### ISSUE THREAD

**Issue by JamesAllwood** [Smile-SA/elasticsuite#1371]
When using a text based swatch in the layered navigation, if a store contains values that all start with the same value followed by a space, selecting one of them, selects all of them, and the parameter in the URL only contains the first section.

For example, if I'm listing shoes, and have the values `13` and `13 Child` available in my text swatch, clicking on the `13 Child` in the layered navigation, also selects `13`, and the results are incorrect.

Based on tests, this seems to be limited to text swatches only

### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.76

Environment : Production mode

Third party modules : None

### Steps to reproduce

1. Create new text based attribute, and populate with the values `13` and `13 Child`. Set the attribute to be available in the layered navigation
2. Assign attribute to attribute set
3. Create a new product and assign value `13`
4. Create a second new product and assign value `13 Child` (ensure both products are assigned to the same category
5. Visit the category on the frontend and filter for the value `13 Child`

### Expected result

1. I see just the product that has been assigned  the `13 Child` attribute value

### Actual result

1. Both the `13` and `13 Child` attributes are selected
2. The parameter in the URL reflects only the value `13` rather than `13+Child`
3. The results show only the product that has the `13` value assigned to it, and not the `13 Child` value

Before filter is applied:

![image](https://user-images.githubusercontent.com/5270957/55474724-d03f1400-5609-11e9-94ac-a1ec9118929f.png)

After filter for `13 Child` is applied:

![image](https://user-images.githubusercontent.com/5270957/55474672-ab4aa100-5609-11e9-8b87-57c1b94414b3.png)

**Comment by romainruaud** [comment]
Confirmed.

We'll try to address this one on next 2.7 minor.

Regards

**Comment by romainruaud** [comment]
Closed by associated PR, will be part of 2.6.9 and 2.7.7

Thank you for reporting it
