### ISSUE TITLE
Forgot of some operators for multiselect attribute for virtual category

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/elasticsuite#1372]
### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.7.6

Environment : Dev/Prod

### Steps to reproduce

1. Have a product attribute multiselect
2. Check the operators for this attribute when creating/editing a virtual category (is one of/is not one of)
3. Check the operators for cart rules (is one of/is not one of/contains/does not contain)

### Expected result
1. have the same operators for the multiselect attribute

### Actual result
1. Don't have the same operators

Use Case:
A product attribute multiselect with values: A, B, C, D, E
Some products with values on this attribute: A,B or B,C or E,D or A,D,E etc ....
We want to show on the virtual category products with value containing for example A.

I test by adding operators on my development environment and it seems to work.
Related issue: #298

Regards

**Comment by romainruaud** [comment]
This one has been answered outside of this Github am I right ?

What's the next steps ?

**Comment by rbayet** [comment]
@romainruaud awaiting for PierreLeMaguer that everything is working as expected.
I haven't be able to reproduce. We can close the issue and re-open it later if need be.
