### ISSUE TITLE
Layered Navigation Filters not displaying on top-level category

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1378]
### Preconditions

Magento Version : 2.3.0

ElasticSuite Version : 2.7.6 

Environment : Production

 
Third party modules :
ElasticSearch

### Steps to reproduce

1. Have Child of Root Level Category
2. Look at Layered Navigation Options
3. 

### Expected result

1.  I should be able to select what attributes to display on the category 

### Actual result

![screencapture-dev-gibuys-admin_fbxw54-catalog-category-edit-key-3adee78e93abae0d6782f2330d373f75e2fa48e3d04d482d9864703b9ec73e75-id-7-2019-04-12-10_16_41](https://user-images.githubusercontent.com/7387019/56048272-bf2e8b00-5d0c-11e9-8576-42846d3a2a97.png)

Do you have any ideas about what may be causing this issue?

**Comment by romainruaud** [comment]
I'm nearly sure it's due to a mistake of mine : https://github.com/Smile-SA/elasticsuite/blob/2.7.x/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php#L121

Should be `>= 2` and not `>2`.

I guess you have the issue on first level of categories only ?

Regards

**Comment by duffner** [comment]
@romainruad, yes it’s only with that level and your reference makes sense! I was just hoping this wasn’t expected behavior.  Thanks for looking.  Do you know what version the fix will be available?

**Comment by romainruaud** [comment]
next minor version since I pushed the PR #1379 that fix this issue.

Sorry for the inconvenience it caused.

Regards

**Comment by romainruaud** [comment]
PR merged so I close the issue

**Comment by duffner** [comment]
@romainruaud, let me know once this is available via composer and I'll test for you.
