### ISSUE TITLE
Virtual Category

### ISSUE THREAD

**Issue by TexnikTexnolog** [Smile-SA/elasticsuite#1387]
Good day.
I have a problem with the Virtual Category.
I want to add to the Virtual Category a few SKU http://prntscr.com/nfrp0w  http://prntscr.com/nfs676 
It looks like this “3M-BR-500142-1100, OB-50P13-L-XS” Is this possible?
Here you can download the video, how I eat do it
https://fex.net/s/zobsbay

**Comment by romainruaud** [comment]
As I previously said : what's the point in creating a virtual category based on a list of SKUS ? 

If you plan to map some products into a category directly, you should used the legacy grid to assign them.

Regards

**Comment by TexnikTexnolog** [comment]
I create a temporary category  for shares for 2-3 days.
And add (and then delete) the desired product in the virtual category by
listing the SKU is very convenient.
And I saw there the opportunity. I just can not understand why the
functionality does not work.
So far did so http://prntscr.com/nfusss
and thought like that you can http://prntscr.com/nfuuk2

------

Я создаю временную категорию и под категорию для акций на 2-3 дня.
И добавить (а потом удалить) нужный товар в виртуальную категорию
перечислив SKU очень удобно.
И видел там такую возможность. Просто не могу понять почему функционал не
работает.
Пока сделал так http://prntscr.com/nfusss
а думал вот так можно http://prntscr.com/nfuuk2

вт, 23 апр. 2019 г. в 18:33, Romain Ruaud <notifications@github.com>:

**Comment by romainruaud** [comment]
PR #1394 is fixing this behavior by allowing rule with several SKUs to work properly.
