### ISSUE TITLE
DataProvider still is MySQL

### ISSUE THREAD

**Issue by ddattee** [Smile-SA/elasticsuite#14]
I think that the module is still missing a DataProvider.
Indeed in `/module-elasticsuite-catalog/etc/di.xml` is it normal that the `DataProviderFactory` still point to the MySQL one ?

```
<type name="Magento\Framework\Search\Dynamic\DataProviderFactory">
    <arguments>
        <argument name="dataProviders" xsi:type="array">
            <item name="elasticsuite" xsi:type="string">Magento\CatalogSearch\Model\Adapter\Mysql\Dynamic\DataProvider</item>
        </argument>
    </arguments>
</type>
```

**Comment by afoucret** [comment]
Think this one is not relevant anymore.
Feel free to reopen if needed.
