### ISSUE TITLE
Indexer handler is not available: elasticsuite

### ISSUE THREAD

**Issue by faisalirfan361** [Smile-SA/elasticsuite#1403]
I have recently updated to magento 2.3.1 and I updated elasticsearch suite too: 
I am running elastic search on same instance (this is a dev machine). I get following error:

> Catalog Product Rule index has been rebuilt successfully in 00:00:00
> Catalog Search indexer process unknown error:
> Indexer handler is not available: elasticsuite
> ElasticSuite Category Indexing indexer process unknown error:
> No alive nodes found in your cluster
> ElasticSuite Thesaurus Indexing indexer process unknown error:
> No alive nodes found in your cluster

 output for php bin/magento config:show | grep elasticsuite

> smile_elasticsuite_catalogsearch_settings/catalogsearch/redirect_if_one_result - 1
> smile_elasticsuite_catalogsearch_settings/catalogsearch/expanded_facets - 0
> smile_elasticsuite_tracker/general/enabled - 0
> smile_elasticsuite_tracker/session/visit_cookie_name - STUID
> smile_elasticsuite_tracker/session/visit_cookie_lifetime - 3600
> smile_elasticsuite_tracker/session/visitor_cookie_name - STVID
> smile_elasticsuite_tracker/session/visitor_cookie_lifetime - 365
> smile_elasticsuite_tracker/anonymization/enabled - 0
> smile_elasticsuite_core_base_settings/es_client/servers - localhost:9200
> smile_elasticsuite_core_base_settings/es_client/enable_https_mode - false
> smile_elasticsuite_core_base_settings/es_client/enable_http_auth - false
> smile_elasticsuite_core_base_settings/es_client/http_auth_user - 
> smile_elasticsuite_core_base_settings/es_client/http_auth_pwd - 

and output for composer info | grep elasticsearch

> elasticsearch/elasticsearch                                       v6.1.0    PHP Client for Elasticsearch
> magento/module-elasticsearch                                      100.3.1   N/A
> magento/module-elasticsearch-6                                    100.3.0   N/A
> magento/module-inventory-elasticsearch                            1.0.0     N/A

any suggestions please?

**Comment by romainruaud** [comment]
What's the output of `curl localhost:9200` ?

**Comment by faisalirfan361** [comment]
here is the curl output:

> curl -XGET http://localhost:9200
> {
>   "name" : "CGKFIbm",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "GEfl_Dj3SY-zv0e49GVoNQ",
>   "version" : {
>     "number" : "6.7.2",
>     "build_flavor" : "default",
>     "build_type" : "deb",
>     "build_hash" : "56c6e48",
>     "build_date" : "2019-04-29T09:05:50.290371Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.7.0",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }
> 

thanks

**Comment by marvinhinz** [comment]
We have the same problem. 

`# curl localhost:9200
{
  "name" : "h_9UxPW",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "rqGb0OWoQFOPrx_mBxf5aA",
  "version" : {
    "number" : "6.8.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "65b6179",
    "build_date" : "2019-05-15T20:06:13.172855Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
`

Also when saving a product the following error appears in var/exception.log:

`[2019-06-11 12:47:20] main.CRITICAL: Der Lagerartikel konnte nicht gespeichert werden. Bitte versuchen Sie es erneut. {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): Der Lagerartikel konnte nicht gespeichert werden. Bitte versuchen Sie es erneut. at magento/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): Keine verknüpften Bestände gefunden at magento/vendor/magento/module-inventory-sales/Model/GetStockBySalesChannel.php:55)"} []
`

**Comment by Ketika** [comment]
Hi there,

Any solution for this issue? I am also facing the same in my Magento commerce cloud project. Please suggest.

**Comment by simonrl** [comment]
Problem for me was that I had removed the Multi Source Inventory from my shop. The modules need to be enabled.

**Comment by romainruaud** [comment]
Closed for being stalled/inactive for too long, and probably too specific
