### ISSUE TITLE
advanced search broken for 2.8.x

### ISSUE THREAD

**Issue by CristinaNicoleta** [Smile-SA/elasticsuite#1404]
### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.0

Environment : prod

### Steps to reproduce

1. Go to advanced search page from demo: http://demo.magento-elastic-suite.io/index.php/catalogsearch/advanced/
2. Search for "bag" or any other product listed
3. The link build for the search is: http://demo.magento-elastic-suite.io/index.php/catalogsearch/advanced/result/?name=bag&sku=&description=&short_description=&price%5Bfrom%5D=&price%5Bto%5D=

### Expected result

1. A text with the number of results and the listing of the products

### Actual result

1. Just the first text, which say "4 items were found using the following search criteria"
2. The actual list of products is missing: "We can't find products matching the selection." Picture attached. 
![elasticsuite](https://user-images.githubusercontent.com/11942965/57522322-108d6280-732b-11e9-81db-14afcd449359.png)

3. The issue seems to come from this method: `\Magento\Catalog\Block\Product\ListProduct::_getProductCollection`
If I comment the first check and initialize a new collection, the list of products it is loaded.
`protected function _getProductCollection()`
    `{`
        `//if ($this->_productCollection === null) {`
            `$this->_productCollection = $this->initializeProductCollection();`
        `//}`

        `return $this->_productCollection;`
    `}`
4. This happens only for ElasticSuite 2.8.0. For 2.7.7 it works just fine.

I reproduced it on my local machine, also.

Thank you!

**Comment by interequipment** [comment]
I'm having same issue on ElasticSuite 2.8.0 (Magento 2.3.1)

**Comment by romainruaud** [comment]
@androshchuk can you work on this issue please ?

**Comment by david-fuehr** [comment]
This is probably related to https://github.com/Smile-SA/elasticsuite/issues/1370. After moving the filter block to the top, we experienced empty search results. A workaround that worked for us is (regarding `catalogsearch_result_index.xml`):
```xml
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
    <body>
        <move element="catalogsearch.leftnav" destination="additional" before="-" />
    </body>
</page>
```

**Comment by romainruaud** [comment]
Fixed in associated PR.
