### ISSUE TITLE
Output order

### ISSUE THREAD

**Issue by TexnikTexnolog** [Smile-SA/elasticsuite#1407]
** Output order **
Good day.
Day after day I have been thinking about the order of withdrawal of goods in the catalog.
I want on the site in categories to raise up a popular product.
So that the best-selling product is from the top

Ex:
sku FT-ACP do first
sku VD-FSO-NEO-H to make the second
sku LV-GS-1 make third
If there is a promotional price to put above the first

But this product is very, very much.
I cannot do it through the "Products List Preview and Sorting" as I have a booster written that the product for which there is a promotional price is above all.

Did this: http://prntscr.com/nqv8hu
But in this case, all the goods rise up and sorted according to their id.
Is it possible to output like this: http://prntscr.com/nqvaa3

**Comment by TexnikTexnolog** [comment]
Еще очень актуально

**Comment by romainruaud** [comment]
I'm not sure about how we can solve the initial issue. 

But to be completely aware of what is happening on this one, @TexnikTexnolog I see that you seem to be more comfortable with russian language, can you explain your issue in russian so that  @androshchuk will be able to qualify it and rephrase in proper english.

Once we'll have full understanding of what you are trying to achieve, I should be able to give you a more complete answer.

Regards

**Comment by romainruaud** [comment]
Ok, thanks to @androshchuk I'm now aware of what you are trying to achieve.

If I'm correct, what you want is : "if I create a boost based on a list of SKUs, the boost should apply and respect the order of addition of these products in the boost".

It's not possible to achieve such a thing with optimizers. This is not what they are inteded to do.

Optimizers are used to apply a **scoring**, not a **sorting** : each product matched by an optimizer will have the same score inside a category. And when products have the same score, they get sorted (secondary) by their entity_id.

If you plan to set positions 1,2,3 for a given category, please use our drag-and-drop merchandiser (manual product sorting) directly on this category : https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#manual-product-sorting-in-categories

Best regards

**Comment by TexnikTexnolog** [comment]
If you plan to set positions 1,2,3 for a given category, please use our drag-and-drop merchandiser (manual product sorting) directly on this category : https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#manual-product-sorting-in-categories

Ок. А как в таком случаи массово поднять товар выше чем тот что я выбрал в категории?
На пример поместить весть товар на который есть скидка в самый верх всех категорий?
