### ISSUE TITLE
Virtual category rest api conditions

### ISSUE THREAD

**Issue by a-t-s** [Smile-SA/elasticsuite#1408]
Well, first of all: Thank you for working on the https://github.com/Smile-SA/elasticsuite/issues/1298 enhancement! Very cool.
Unfortunately I cannot get the conditions to work.
A PUT to {{base_url}}/rest/V1/categories/279
`{
    "category": {
    	"id": 279,
        "custom_attributes": [
            {
                "attribute_code": "is_virtual_category",
                "value": "1"
            },
            {
                "attribute_code": "virtual_rule",
                "value": {
                    "condition": {
                        "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine",
                        "conditions": [
                            {
                                "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Product",
                                "operator": "()",
                                "attribute_name": "department",
                                "value": [
                                    "Men"
                                ]
                            },
                            {
                                "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Product",
                                "operator": "==",
                                "attribute_name": "new",
                                "value": true
                            }
                        ],
                        "aggregator_type": "all",
                        "operator": null,
                        "value": "1"
                    }
                }
            }
        ]
    }
}`
Leads to a response:
...
`        {
            "attribute_code": "virtual_rule",
            "value": {
                "condition": {
                    "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine",
                    "aggregator_type": "all",
                    "operator": null,
                    "value": true
                }
            }
        },`
...
Same thing if I try to PUT it as a extension attribute
`{
    "category": {
        "id": 280,
        "custom_attributes": [
            {
                "attribute_code": "is_virtual_category",
                "value": "1"
            }
        ],
        "extension_attributes": {
            "virtual_rule": {
                "condition": {
                    "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine",
                    "conditions": [
                        {
                            "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Product",
                            "operator": "()",
                            "attribute_name": "department",
                            "value": [
                                "Women"
                            ]
                        },
                        {
                            "condition_type": "Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Product",
                            "operator": "==",
                            "attribute_name": "new",
                            "value": true
                        }
                    ],
                    "aggregator_type": "all",
                    "operator": null,
                    "value": "1"
                }
            }
        }
    }
}`
Looking briefly into the issue it seems like vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Category/Attribute/VirtualRule/SaveHandler.php:67 `$rule->loadPost($attributeData);`
expects a "conditions" key in vendor/magento/module-rule/Model/AbstractModel.php:341 and vendor/magento/module-rule/Model/AbstractModel.php:318
where the outer object is written with a "condition" (singular) key.
On the other hand you put all the singular spelled getters and setters in place so I am not quite sure if I got confused.

**Comment by romainruaud** [comment]
@androshchuk can you check this one ?

Regards

**Comment by romainruaud** [comment]
Fixed by #1470
