### ISSUE TITLE
Elasticsearch prefix

### ISSUE THREAD

**Issue by fnash** [Smile-SA/elasticsuite#1409]
Hi,

Is there a way to add a prefix in the host configuration?

I took a look at the code and it does not seem to be possible for the moment because of this line https://github.com/Smile-SA/elasticsuite/blob/2.6.x/src/module-elasticsuite-core/Client/ClientBuilder.php#L103 that forces an array configuration and not the connection string.

Do you confirm?

Configuring a prefix is possible since 2014 refering to this: https://github.com/elastic/elasticsearch-php/issues/60#issuecomment-39125000

Do you have an idea on how to make it possible?

Thanks

**Comment by davidwindell** [comment]
We need this too as our dev ES serfver runs multiple M2 sites. With core Magento you can specify an index prefix. 

Did you get anywhere this @fnash?

**Comment by davidwindell** [comment]
Would the `Indices alias name` option https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings do the trick instead?

**Comment by romainruaud** [comment]
yes, your indices will be named according to this alias.

So if you have several sites running on a single ES node (which I do not recommend), ensure to have an unique alias for each of them.

Regards

**Comment by davidwindell** [comment]
I think this issue can be closed now, thanks @romainruaud
