### ISSUE TITLE
Elastic Suite 2.8.0 setup:upgrade 

### ISSUE THREAD

**Issue by artmediastudio** [Smile-SA/elasticsuite#1410]
### Preconditions

Magento Version : 2.3.0

ElasticSuite Version :2,8.0

Environment :Developer

Third party modules :

### Steps to reproduce

1. bin/magento setup:upgrade

### Actual result

Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [9]. This limit can be set by changing the [index.max_shingle_diff] index level setting."}],"type":"illegal_argument_exception","reason":"In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [9]. This limit can be set by changing the [index.max_shingle_diff] index level setting."},"status":400}
root@odino:/home/ftp/artmediastudio/www/artmediastudio.it/magento/2.0/magento# php magento deploy:mode:show
Could not open input file: magento
root@odino:/home/ftp/artmediastudio/www/artmediastudio.it/magento/2.0/magento# php bin/magento deploy:mode:show
Current application mode: developer. (Note: Environment variables may override this value.)

**Comment by romainruaud** [comment]
Which exact version of ElasticSearch are you using ?

**Comment by artmediastudio** [comment]
Thanks for answer
7.1.0

**Comment by romainruaud** [comment]
Ok that's what I was afraid of.

It's not supported actually. Please use ElasticSearch 6.8
