### ISSUE TITLE
ElasticSearch Logging Event Indexer Issue 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#1412]
ElasticSearch logging tasks seem to never complete, which causes old indices to not to be removed, and this inflates quickly in size which causes the CPU/RAM usage increasing drastically. 

### Preconditions

Magento Version : 2.3.1 CE (Community Edition) 

ElasticSuite Version : 2.7.x 

Environment : Production

Third party modules : ElasticSuite and FindCanary Infusionsoft integration 

### Steps to reproduce

1. Production Site with Traffic 
2. Enable Logging Event feature from ElasticSuite
3. elasticsuite_index_log_event triggers

### Expected result

1. elasticsuite_index_log_event completes successfully 

### Actual result

1. [Screenshot, logs]
elasticsuite_index_log_event fails to finish, due to extensive CPU ultilization 

Screen Shot of Log Graphs Once Index Log Event is enabled. 
![witsend_elasticsearch](https://user-images.githubusercontent.com/7387019/58220673-6b34a000-7cd5-11e9-8d0c-380001a95c90.png)

Overall, Magento's cron system isn't the best, but it would be nice to see this feature work without so much CPU usage.

**Comment by rbayet** [comment]
Hello @duffner,

How many events are left unprocessed in the queue ?

How heavy is the traffic on your site / how many events in average do you get per day ?
You can have a rough idea with the following queries 
```
select DATE(date) as day, count(*) as nb_events from elasticsuite_tracker_log_event group by day order by day asc;
```
and
```
select AVG(nb_events) from (select DATE(date) as day, count(*) as nb_events from elasticsuite_tracker_log_event group by day order by day asc) avg_events;
```

The `elasticsuite_index_log_event` cronjob treats up to 10K events per execution. It's not configurable, but you can use the DI to tweak the value for `$chunkSize` of `\Smile\ElasticsuiteTracker\Cron\IndexLogEvent` :
```
namespace Smile\ElasticsuiteTracker\Cron;

/**
 * Cron task used to index tracker log event.
 *
 * [...]
 */
class IndexLogEvent
{
   [...]
    /**
     * @var integer
     */
    private $chunkSize;

    /**
     * Constructor.
     *
     * @param \Smile\ElasticsuiteTracker\Api\EventQueueInterface   $eventQueue   Pending events queue.
     * @param \Smile\ElasticsuiteTracker\Api\SessionIndexInterface $eventIndex   Event index.
     * @param \Smile\ElasticsuiteTracker\Api\EventIndexInterface   $sessionIndex Session index.
     * @param integer                                              $chunkSize    Size of the chunk of events to index.
     */
    public function __construct(
        \Smile\ElasticsuiteTracker\Api\EventQueueInterface $eventQueue,
        \Smile\ElasticsuiteTracker\Api\EventIndexInterface $eventIndex,
        \Smile\ElasticsuiteTracker\Api\SessionIndexInterface $sessionIndex,
        $chunkSize = 10000
    ) {
        $this->eventQueue   = $eventQueue;
        $this->eventIndex   = $eventIndex;
        $this->sessionIndex = $sessionIndex;
        $this->chunkSize    = $chunkSize;
    }
```

But all in all, it might be simply a sizing or architecture issue on your ElasticSearch instance.
How many nodes are you using ? What is they typology ?
Are they located on (a) dedicated server(s) ?
When the cron executes, do its have any impact on the availability of the catalog / search on the site ?

If that is the case, and if you have very heavy traffic on the site, an option would be to dedicate some nodes to only hold the tracker data (event and session documents) by using ElasticSearch document routing options.

Regards,

PS : what is the role/purpose of FindCanary Infusionsoft ?
