### ISSUE TITLE
When a certain attribute is use_in_search=no, autocomplete search crashes (normal search works)

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1417]
### Preconditions

We have a color_2 attribute which is use_in_search=no

Magento Version : 2.2.8
ElasticSuite Version : [dev-fix-866-discount-for-configurables](https://github.com/iMi-digital/elasticsuite/tree/fix-866-discount-for-configurables), based on develop-2.6.x

Environment : Developer or Production

Third party modules : yes. some

### Steps to reproduce
1. Use the quick search (type a word)

### Expected result
1. Return results

### Workaround

Set the field to use_in_search=yes

### Actual result

2. 500er server error appears
```1 exception(s):
Exception #0 (BadMethodCallException): Missing required argument $name of Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term.

Exception #0 (BadMethodCallException): Missing required argument $name of Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term.
<pre>#1 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59]
#2 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#3 Magento\Framework\ObjectManager\ObjectManager->create() called at [generated/code/Smile/ElasticsuiteCore/Search/Request/Aggregation/Bucket/TermFactory.php:43]
#4 Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\TermFactory->create() called at [vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Aggregation/AggregationFactory.php:57]
```

**Comment by romainruaud** [comment]
Ooops, looks like this issue was missed by everyone.

Sorry about that @amenk 

Is it still up-to-date ? Any other informations that you can provide us since this issue was happening ?

**Comment by amenk** [comment]
It's still on our backlog but not prioritised. We can try to reproduce it again, have to check back with the customer.

**Comment by romainruaud** [comment]
Is this still accurate @amenk  ?

**Comment by amenk** [comment]
The issue is not relevant for us anymore due to other changes,
Can be closed if you like.
