### ISSUE TITLE
error in optimizer

### ISSUE THREAD

**Issue by androshchuk** [Smile-SA/elasticsuite#1418]
### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.0

Environment : dev

### Steps to reproduce

1. Go to page Elasticsuite Optimizer page
2. Click button "Add new Optimizer"
3. Click button "Preview" without choosing Request type

### Expected result

See optimization results

### Actual result

I got 500 error http://joxi.net/Drl9allhVe76dm

**Comment by romainruaud** [comment]
Fixed by associated PR.
