### ISSUE TITLE
Virtual category rule - "is not one of" condition not working

### ISSUE THREAD

**Issue by alexayg** [Smile-SA/elasticsuite#1420]
### Preconditions

Magento Version : Magento CE 2.2.5
ElasticSuite Version : 2.5
Elasticsearch version : 5.6.10
Magento Environment : dev

### Steps to reproduce

1. Create a new virtual category
2. Select a "Virtual Category Root" for it
3. Under "Virtual rule" add the following condition: "Category **is not one of** category_ids_list"

### Expected result

1. The virtual category page should not display the products from the "category_ids_list" categories.

### Actual result
1. The virtual category page is displaying all the products from the "Virtual Category Root" categories.

**Comment by romainruaud** [comment]
Hello @alexayg 

ElasticSuite 2.5 is quite old now, and I'm afraid that we cannot continue supporting it as part of our Open Source support commitment here on github.

That being said, thank you for reporting this bug, we'll try to reproduce it on most recent release and to bring a fix for this one if this is still accurate.

@androshchuk can you try to reproduce this issue on 2.8 version of ElasticSuite, and if still occuring, work on a fix ?

Regards

**Comment by romainruaud** [comment]
Fixed by associated PR
