### ISSUE TITLE
Slack Support

### ISSUE THREAD

**Issue by sivasdescalzo** [Smile-SA/elasticsuite#1422]
I am trying to connect my Slack with https://github.com/Smile-SA/elasticsuite repo in order to get notifications everytime there is a release, but it seems GitHub Slack APP needs some permissions to the repo to do that.

Cloud you please install GitHub Slack APP in your repo in order to be able to connect Slack with your repo?
Many thx!

**Comment by romainruaud** [comment]
sorry @sivasdescalzo but this is not something we plan to do. 

If you wanna stay in touch with new releases, use the Github star & watch tools.

Regards
