### ISSUE TITLE
Returns 0 result if page size is false in collection

### ISSUE THREAD

**Issue by kirkmadera** [Smile-SA/elasticsuite#1428]
The smile class `\Smile\ElasticsuiteCore\Search\Request\Builder::create` does not work with pageSize = false appropriately in my opinion.

### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8

Environment : developer mode

Third party modules : N/A

### Steps to reproduce

1. Do not set page size in layout for product list page
2. View product list page

### Expected result

1. All products displayed with no limit

### Actual result

1. No products displayed

### Notes
The protected variable $_pageSize of a Magento collection defaults to false. There is a note above this in `\Magento\Framework\Data\Collection` that reads "if page size is false, then we works with all items".

    /**
     * Pager page size
     *
     * if page size is false, then we works with all items
     *
     * @var int|false
     */
    protected $_pageSize = false;

The smile class `\Smile\ElasticsuiteCore\Search\Request\Builder::create` does not work with pageSize = false appropriately in my opinion. (I just debugged for two days to find this).

If $size is false, it should behave more like Magento intended and return all results. 

"All" results is sort of relative because ElasticSearch forces a limit and has a default limit of 10,000 for index.max_result_window (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html). This seems like a reasonable max for returning "all" records in Magento.

`\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareRequest` also has a line of code that does not explicitly consider $size as false which would need to be addressed.

I have a fix for this and will submit it shortly.

**Comment by kirkmadera** [comment]
See https://github.com/Smile-SA/elasticsuite/pull/1429

**Comment by romainruaud** [comment]
I close this one for reasons explained in the PR.

If I missed something, please create a new issue with a scenario explaining why things are not working as expected.

Regards
