### ISSUE TITLE
ElasticSuite takes me to Product Page automatically when I want to view search results.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Smile-SA/elasticsuite#1432]
When searching for "942" which is in a products SKU, I am taken instantly to a product with "942" in the name. E.g. ".472 x 942 Something".

- Is ElasticSuite able to show the search page with all matches rather than goto a product page? (Unless there really is only 1 product matching the search criteria?)

When using Keyword search on admin back end there are 77 records found.
Front end takes me to 1 product only.

Ok I edited the ResultPlugin.php so it does not redirect, and I can see the frontend results only have 1 product.
```php
if ($productCollection->getCurPage() === 1 && $productCollection->getSize() === 1 && 1==0) {
```

**Additional context**
Magento 2.3
ElasticSearch 6.4.5

**Comment by rbayet** [comment]
Hello @LiamKarlMitchell,

Yes redirecting to the product page when there is only one search result is an Elasticsuite feature.
You can disable/enable in admin in "Stores > Configuration > Elasticsuite > Catalog Search > Redirect to product page if only one result".

> When using Keyword search on admin back end there are 77 records found.
Be careful: the M2 admin backend search is **not** powered by Elasticsuite.

Regards
