### ISSUE TITLE
No products shown with 1-column Layout

### ISSUE THREAD

**Issue by tieroom** [Smile-SA/elasticsuite#1433]
### Preconditions
Magento Version :2.3.1 on PHP 7.2
ElasticSuite Version : 2.8.0
Environment :Developer

### Steps to reproduce
1. Find a category with active products
2. Set Design > Layout to 2 columns with left bar
3. Refresh cache
4. View products on frontend
5. Set Design > Layout to 1 column
6. Refresh cache
7. View products on frontend

### Expected result
1. Products are listed in both step 4 and 7

### Actual result
1. Products are listed in step 4 (2 columns with left bar) but not in step 7 (1 column)

**Comment by stoutik** [comment]
I have the some problem.
Magento Version : 2.3.1
ElasticSuite Version : 2.8.0

**Comment by romainruaud** [comment]
This one might be due to the position of the `toolbar` block in the layout.

@androshchuk can you investigate on this one ?

Regards

**Comment by romainruaud** [comment]
@tieroom @stoutik can you check again this one against ElasticSuite 2.8.1 ? 

It appears to be fixed (probably as a side effect of https://github.com/Smile-SA/elasticsuite/commit/5d9733a8d0eadf49b8ec9e3dee48a58e2678b335 or https://github.com/Smile-SA/elasticsuite/commit/9ce50b98de7fac6b7dc078926c201dd916efa42c )

**Comment by stoutik** [comment]
@romainruaud 
I just made an ElasticSuite update to 2.8.1, all works well, thank you very much.

**Comment by romainruaud** [comment]
Good to know ! thank you @androshchuk for pointing me this one.

I close if it's resolved !
