### ISSUE TITLE
Magento 2 B2B QuickOrder " index does not exist yet. Make sure everything is reindexed."

### ISSUE THREAD

**Issue by NathMorgan** [Smile-SA/elasticsuite#1434]
Magento 2.3.1 B2B QuickOrder page on Product Suggest Ajax fails with a 500 error ` Index does not exist yet. Make sure everything is reindexed.` with {$indexIdentifier} being null

### Preconditions

Magento Version : Magento 2.3.1 EE

ElasticSuite Version : 2.8.0

Environment : Developer & Production (Effects both)

Third party modules : N/A

### Steps to reproduce

1. Enable B2B features within Magento 2.3.1 EE
2. Browse to the quickorder page
3. Start typing in the fields

### Expected result
1. Products returned if found or nothing returned if no products found

### Actual result

1. Exception is thrown with the error ` index does not exist yet. Make sure everything is reindexed.` with `{$indexIdentifier}` being null

After investigating myself I have found that this module (https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog) fixes the blank index issues we have been having however the module is two years old and is currently not supported on the version of PHP Magento 2.3.1 uses (7.2) see PR here: https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog/pull/2

Is this above module still okay to use?

**Comment by romainruaud** [comment]
I fixed the shared catalog module, including Magento 2.3.1 compatibility.

Please use latest version (1.1.0) of the shared catalog module if you are on Magento 2.3.x (or the 2.3.x-dev branch).

Please note you also have to use this module to enable Quick Order to work with Elasticsuite : https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order

Regards
