### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by volanar** [Smile-SA/elasticsuite#1435]
[logs.txt](https://github.com/Smile-SA/elasticsuite/files/3310612/logs.txt)
https://github.com/Smile-SA/elasticsuite/issues/897
I have the same mistake and it did not help. Magento2.3.1, elasticsuite 2.8.0. Are there other fixes available?
Uncaught TypeError: Cannot read property 'map' of undefined
at UiClass.onProductListLoad (product-sorter.js:212)
at fire (jquery.js:3232)
at Object.fireWith [as resolveWith] (jquery.js:3362)
at done (jquery.js:9840)
at XMLHttpRequest.callback (jquery.js:10311)

**Comment by southerncomputer** [comment]
I've found that magento 2.3.1 has janky requirejs/amd issues.. I've had to add 'domReady!' to many javascript require functions and have to even patch  phtml files with <scripts> to get them to fire consistently in-order as they had been doing in 2.1.17~.. Not a fun upgrade so far!

**Comment by romainruaud** [comment]
I close this one for being poorly documented/explained.

Please next time, take the time to give us more details about the version of components and how to reproduce the bug.

Thank you
