### ISSUE TITLE
Set EavAttribute Fields in Setup

### ISSUE THREAD

**Issue by davidsiemers** [Smile-SA/elasticsuite#1438]
Hello,

I'm currently trying to set ElasticSuite's EavAttribute fields when running an installer script for a module. In this module, I'm creating a custom product attribute. Unfortunately, trying to set ElasticSuite fields such as facet_min_coverage_rate or facet_sort_order don't seem to work. For reference, here's a snippet from the install method in the InstallData script:

`
$eavSetup = $this->eavSetupFactory->create();
        $eavSetup->addAttribute(
            \Magento\Catalog\Model\Product::ENTITY,
            'myattribute',
            [
                'group' => 'General',
                'type' => 'text',
                'label' => 'My Attribute',
                'input' => 'multiselect',
                'source' => 'Vendor\MyAttribute\Model\Attribute\Source\Aircraft',
                'frontend' => '',
                'backend' => 'Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend',
                'required' => false,
                'sort_order' => 50,
                'global' => \Magento\Eav\Model\Entity\Attribute\ScopedAttributeInterface::SCOPE_GLOBAL,
                'is_html_allowed_on_front' => true,
                'is_visible_on_front' => false,
                'used_in_product_listing' => false,
                'searchable' => true,
                'filterable' => true,
                'is_visible_in_advanced_search' => true,
                'is_filterable_in_search' => true,
                'facet_min_coverage_rate' => 2,
                'facet_sort_order' => '_term',
            ]
        );
`

I'm thinking this is due to the custom columns created for the ElasticSuite module not being known to the EavSetupFactory. Would I have to modify that class to get this to work? Or would it be better to modify the field in the InstallSchema script of my module(after checking if ElasticSuite's columns exist, of course). Or perhaps there's a better approach?

Any insight on this would be wildly helpful.

Thanks!

**Comment by romainruaud** [comment]
@davidsiemers maybe we should flush the DDL cache after adding the colum (I thought it was automatic), or maybe there is another cache to flush related to attribute Data.

As a workaround, you can do like this after creating the attribute :  https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Setup/CatalogSetup.php#L285

**Comment by davidsiemers** [comment]
Thank you! I will look into doing that :).

**Comment by romainruaud** [comment]
I close since this has been answered and (probably ?) resolved.

Regards
