### ISSUE TITLE
Autocomplete auto learning

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/elasticsuite#1439]
Hello Romain,

I was reading ticket #1413 and you said about a near refactoring of autocomplete functionnality.

Do you have any roadmap or an estimation on when the refactor should be available ?

Thank you !
Aymeric

**Comment by romainruaud** [comment]
Hello @AymericJoubert 

for now, this one is a low priority, in fact we'd more likely tend to build an autocomplete which is based on "popular" search terms (by popular I mean the terms that are mostly used for a slipping period of time).

Regards

**Comment by romainruaud** [comment]
I'm closing this since the question has been answered.

Regards
