### ISSUE TITLE
After upgrade to magento 2.3.2 site broken

### ISSUE THREAD

**Issue by a970032** [Smile-SA/elasticsuite#1442]
### Preconditions

Magento Version : magento 2.3.2

ElasticSuite Version :2.8.0

Environment :Developer

Third party modules :

### Steps to reproduce

1. composer require "magento/magento-cloud-metapackage":"2.3.2" --no-update
2. bin/magento setup:upgrade
3. 500 error Fatal Error: 'Class 'Magento\CatalogInventory\Model\Plugin\Layer' not found' in '/var/www/vhosts/default/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php' on line 25

### Expected result

1. can normally go to home page

### Actual result

```
<error>
<messages>
<error>
<data_item>
<code>500</code>
<message>
<![CDATA[
Fatal Error: 'Class 'Magento\CatalogInventory\Model\Plugin\Layer' not found' in '/var/www/vhosts/default/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php' on line 25
]]>
</message>
<trace>
<![CDATA[ Trace is not available. ]]>
</trace>
</data_item>
</error>
</messages>
</error>
```

![image](https://user-images.githubusercontent.com/18587853/60150241-669a6480-980a-11e9-9f56-7d60c2335ed1.png)

**Comment by sweikenb** [comment]
Same here, as it seems they removed the Layer-plugin entirely from the source:

https://github.com/magento/magento2/tree/2.3.2/app/code/Magento/CatalogInventory/Model/Plugin

**Comment by sweikenb** [comment]
A quick fix for this is to disable the plugin, this would have other consequences regarding the displaying of the stock status, but at least the site isn't down:

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <!--
    Temporary Quick-Fix to prevent the site to be down:
    https://github.com/Smile-SA/elasticsuite/issues/1442
    -->
    <type name="Magento\Catalog\Model\Layer">
        <plugin name="addStockStatusOnPrepareFrontCollection"
                type="Smile\ElasticsuiteCatalog\Plugin\LayerPlugin"
                disabled="true"/>
    </type>
</config>
```

**Comment by NathMorgan** [comment]
Created PR that should fix this issue https://github.com/Smile-SA/elasticsuite/pull/1444

**Comment by Quazz** [comment]
Layered navigation will still be entirely broken even if you do this.

Looks like this commit is what removed the layer plugin and changed the logic:

https://github.com/magento/magento2/commit/9ab466d8569ea556cb01393989579c3aac53d9a3#diff-2ad66624cecd33a368d784f2be936f48

**Comment by southerncomputer** [comment]
https://github.com/Smile-SA/elasticsuite/issues/1445#issuecomment-505971767 see this thread

**Comment by romainruaud** [comment]
Thank you @NathMorgan for your PR.

as far as I can see, it could do the trick. I did not test it by myself however.

@androshchuk can you have a look on this issue and associated PR ?

Regards

**Comment by kleestb** [comment]
Unfortunately #1448 did not work for us and we desperately need to have a working version. When can we expect a fix?

**Comment by tratta** [comment]
@kleestb did you try to restore the layer plugin ?
https://github.com/Smile-SA/elasticsuite/issues/1445

**Comment by kirmorozov** [comment]
It's weird, that Magento fellows allowed removal of the code without any prior notice, as pert of minor release.

**Comment by hanhpv** [comment]
Same issue

**Comment by southerncomputer** [comment]
What is the issue you are getting after applying the patch?

**Comment by nopenopenope** [comment]
Same issue on Vanilla Magento 2.3.2, ES 6.1.8 and Module 2.8.0

**Comment by southerncomputer** [comment]
did you apply this patch and the #1444 patch as well?!

**Comment by nopenopenope** [comment]
Hi @southerncomputer, I'll apply the patch and revert further changes that I made in order to solve this. I'll let you know quickly.

**Comment by nopenopenope** [comment]
@southerncomputer after reindexing (as I said, fresh install, Data Migration has been done, tho):

```
1 exception(s):
Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed.
```

**Comment by southerncomputer** [comment]
did you get this error after doing bin/magento indexer:reindex ?

**Comment by nopenopenope** [comment]
Yes, exactly. I made some calls to ES to check for active indicies and found only those. The numbers look to small. There are ~6k Products in the DB currently.

```
 www-data@local:~/magento2$ curl -X GET "elasticsearch:9200/_cat/indices?v"
health status index                                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   magento2_product_1_v1                             qBm5TNDLQzi5gTPM-SPxkA   5   1       2932            0      3.4mb          3.4mb
green  open   magento2_default_catalog_category_20190706_140456 ajZESosKRCi4okyFUPbR7A   1   0        680            0        1mb            1mb
green  open   magento2_default_thesaurus_20190706_140458        OWeLSlbSTsqx_DFRreE4Yg   1   0          0            0       261b           261b
```

**Comment by southerncomputer** [comment]
It sounds like your product indexing is crashing/getting stuck! Might turn on var/log/debug.log and tail it while its doing indexing!
on my dev box it is showing
```
green  open   magento2_default_catalog_product_20190706_050716  zsB-28XjRfWbMzG6NfXN8g   1   0   12301172            0     12.4gb         12.4gb
```

I know elasticsuite builds indexes with a temp name and then renames it as it completes successfully!

**Comment by nopenopenope** [comment]
Thanks for that hint with the Magento ElasticSearch Engine, that actually was an issue of not setting the Source to ElasticSearch.

**Comment by romainruaud** [comment]
Good to know !

I'll work on this one this week.

But for me, the plugin can be removed, since the Stock management is now done with a search context filter : 

https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Product/Search/Request/Container/Filter/Stock.php

**Comment by romainruaud** [comment]
Fixed by PR #1461

**Comment by marvinhinz** [comment]
Thanks! Could create a new release with this merge?

**Comment by skazhikadyadya** [comment]
> A quick fix for this is to disable the plugin, this would have other consequences regarding the displaying of the stock status, but at least the site isn't down:
> 
> ```
> <?xml version="1.0"?>
> <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>         xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
>     
>     <type name="Magento\Catalog\Model\Layer">
>         <plugin name="addStockStatusOnPrepareFrontCollection"
>                 type="Smile\ElasticsuiteCatalog\Plugin\LayerPlugin"
>                 disabled="true"/>
>     </type>
> </config>
> ```

Hi, excuse me, how i can implement that XML? Thanks.

**Comment by skazhikadyadya** [comment]
Some problem.

```
[mirkada@shop public_html]$ bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker
PHP Fatal error:  Class 'Magento\CatalogInventory\Model\Plugin\Layer' not found in /home/mirkada/web/shop.mirkada.com/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 25
```
Latest M2. How I can quickly fix that? Thanks.

**Comment by humanwere** [comment]
@skazhikadyadya I fix like this;

```
$ composer remove smile/elasticsuite 
$ composer require smile/elasticsuite 2.8.x-dev
```

**Comment by roman204** [comment]
there is also a version 3.0 now
```
$ composer remove smile/elasticsuite 
$ composer require smile/elasticsuite:^3.0
```

**Comment by romainruaud** [comment]
@roman204 as far as I know there is no 3.0 version.

Where did you find it ?

**Comment by roman204** [comment]
![image](https://user-images.githubusercontent.com/584168/65756330-2f8f6400-e115-11e9-8a21-d66f5c7faeda.png)

**Comment by romainruaud** [comment]
It's elasticsuite here... not magesuite...

**Comment by roman204** [comment]
oh thanks.. wrong issue
