### ISSUE TITLE
ElasticSuite incompatible with Amasty Groupcat and MageWorx Customer Prices modules.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Smile-SA/elasticsuite#1443]
When Elastic Suite is enabled some other modules we have stop working properly.
Elastic Suite is nice so we want to keep using it, but also want to use the other modules to control product visibility per customer and custom prices per customer. (It's b2b).

Is there a guide or a recommendation on how I can adapt existing modules to work with this new way of searching?

They do things to the search results and have a search_request.xml of their own or use "Plugins" in the etc/di.xml

Things such as Viewing a category, Searching do not work with the below error.

Module 1: Amasty Groupcat
```
1 exception(s):
Exception #0 (LogicException): Field amasty_groupcat_entity_id does not exists in mapping

Exception #0 (LogicException): Field amasty_groupcat_entity_id does not exists in mapping
#0 /var/www/vhosts/magento/staging/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Filter/QueryBuilder.php(97): Smile\ElasticsuiteCore\Index\Mapping->getField('amasty_groupcat...')
#1 /var/www/vhosts/magento/staging/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Builder.php(105): Smile\ElasticsuiteCore\Search\Request\Query\Filter\QueryBuilder->create(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), Array)
#2 /var/www/vhosts/magento/staging/generated/code/Smile/ElasticsuiteCore/Search/Request/Query/Builder/Interceptor.php(37): Smile\ElasticsuiteCore\Search\Request\Query\Builder->createFilterQuery(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), Array)
#3 /var/www/vhosts/magento/staging/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Builder.php(89): Smile\ElasticsuiteCore\Search\Request\Query\Builder\Interceptor->createFilterQuery(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), Array)
#4 /var/www/vhosts/magento/staging/vendor/magento/framework/Interception/Interceptor.php(58): Smile\ElasticsuiteCore\Search\Request\Query\Builder->createQuery(Object(Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration), NULL, Array, 1)
#5 /var/www/vhosts/magento/staging/vendor/magento/framework/Interception/Interceptor.php(138): Smile\ElasticsuiteCore\Search\Request\Query\Builder\Interceptor->___callParent('createQuery', Array)
```

Module 2: MageWorx_CustomerPrices
I have actually disabled this for now whilst figuring out the first.

```
1054 - Unknown column 'cat_index.position' in 'field list'
```

I was hoping this would be something I can quickly fix to add a Mapping and pull this data through, but if not should I be in touch with the modules developers to get them to make it compatible?

Thanks.

**Comment by Quazz** [comment]
https://github.com/Smile-SA/elasticsuite/wiki/Indexing#mappings

**Comment by LiamKarlMitchell** [comment]
Thanks for the link to the mappings info seems that would be the way to go to fix the first one.

Turns out that we actually did not need the features that were broken in the other modules in this circumstance and was able to safely bypass their functionality. Yay~

Amasty/Groupcat/Plugin/Catalog/Model/Layer.php
Made line 57 of beforePrepareProductCollection return null; to disable this.

MageWorx
Plugin/Layer/Category/ApplyCustomerPricesToCollection.php
Commented Line 152
//'cat_index_position' => 'cat_index.position',

Because cat_index is not used when we enable Elastic Suite it seems and the position comes from Elastic Suite anyway.

Of course Ideally this work around would be done with the appropriate over-ride maybe an around plugin.

Worked in my circumstance so thought I would post the outcome in-case someone else stumbles on the same scenario in the future Shrugs.

**Comment by choussamaster** [comment]
This is the solution to keep Amasy/Groupcat product filter work with ElasticSuite
Override the plugin with a preference

di.xml

` <preference for="Amasty\Groupcat\Plugin\Catalog\Model\Layer"
                type="MyStore\MyStoreCatalog\Plugin\Override\Amasty\Layer"></preference>`

app/code/YourPackageX/YourModuleX/Plugin/Override/Amasty/Layer.php

`<?php

namespace YourPackageX\YourModuleX\Plugin\Override\Amasty;

use Amasty\Groupcat\Helper\Data;
use Amasty\Groupcat\Model\ProductRuleProvider;
use Magento\Framework\Registry;
use Magento\Search\Model\EngineResolver;

class Layer extends \Amasty\Groupcat\Plugin\Catalog\Model\Layer
{

    /**
     * @var ProductRuleProvider
     */
    private $ruleProvider;

    /**
     * @var Data
     */
    private $helper;

    /**
     * @var Registry
     */
    private $coreRegistry;

    /**
     * @var EngineResolver
     */
    private $searchEngineResolver;

    public function __construct(
        ProductRuleProvider $ruleProvider,
        Data $helper,
        Registry $coreRegistry,
        EngineResolver $searchEngineResolver
    ) {
        $this->ruleProvider = $ruleProvider;
        $this->helper = $helper;
        $this->coreRegistry = $coreRegistry;
        $this->searchEngineResolver = $searchEngineResolver;
    }

    /**
     * Prepare Product Collection for layred Navigation.
     * Add restricted product filter to search engine.
     * In search_request.xml added filter for amasty_groupcat_entity_id
     *
     * Overrided due to ElasticSuite conflict
     * @param \Magento\Catalog\Model\Layer                            $subject
     * @param \Magento\Catalog\Model\ResourceModel\Product\Collection $collection
     *
     * @return array|null
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function beforePrepareProductCollection($subject, $collection)
    {
        if (!$this->helper->isModuleEnabled() || $this->coreRegistry->registry('amasty_ignore_product_filter')) {
            return null;
        }

        $collection->setFlag('groupcat_filter_applied', 1);
        $productIds = $this->ruleProvider->getRestrictedProductIds();

        if ($productIds) {
            // add filter to product fulltext search | catalog product collection
            if ($this->searchEngineResolver->getCurrentSearchEngine() === EngineResolver::CATALOG_SEARCH_MYSQL_ENGINE) {
                $collection->addFieldToFilter('amasty_groupcat_mysql_entity_id', ['nin' => $productIds]);
            } elseif($this->searchEngineResolver->getCurrentSearchEngine() == 'elasticsuite') {
                $collection->addFieldToFilter('entity_id', ['nin' => $productIds]);
            } else {
                $collection->addFieldToFilter('amasty_groupcat_elastic_entity_id', $productIds);
            }

            return [$collection];
        }

        return null;
    }

}
`
