### ISSUE TITLE
Problem with count products in category with diffrent filters.

### ISSUE THREAD

**Issue by pawcioma** [Smile-SA/elasticsuite#1446]
**Is your question related to a problem? Please describe.**
Problem with count products in category with diffrent filters. When I used some filters from layer navigation numbers of products in category ignore this filters. Only filter "q"(search query) working ok. 

Ex :
When I used search form I got results. Layer navigation have some filters for example "availability ", "category". I see availability got: 24h - 50 products; 48h 50 products and "category 1" 70 products; "category 2' 30 products. When I choose availabilty 24h numbers of products in category stay the same 70 and 30. Sum of number products in categories  should be 50.

**Additional context**
Do you have some idea what I have wrong or I can fix it?

**Comment by romainruaud** [comment]
> Sum of number products in categories should be 50.

Not exactly... In fact, *Max number of products in any categories should be >=50*, but the total sum of all categories can be >50 because a product can belong to several categories.

That being said, please kindly give us more details :

- Magento Version
- Elasticsuite Version
- list of third party modules
- how is your "availability" attribute created ? is it a swatch attribute ?

Regards

**Comment by pawcioma** [comment]
Magento Version: 2.2.5
ElasticSuite Version: 2.6.6
how is your "availability" attribute created ? is it a swatch attribute ?: Availability is EAV attribute(int), but problem is with any attribute.
List of third party modules:
https://themeforest.net/item/fastest-magento-2-themes-magento-212-magento-19-multipurpose-responsive-theme-10-design/16178989
 - Plugin to Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\Category:afterGetUrl

**Comment by pawcioma** [comment]
> Not exactly... In fact, _Max number of products in any categories should be >=50_, but the total sum of all categories can be >50 because a product can belong to several categories.

You have right but when I have selected availability filter in layer navigation, category have number of products equel sum of products in category. When I choose category and select availability number of products is defferent then I saw before I choose category in layernavigaiton.

**Comment by pawcioma** [comment]
I found reason. Problem is with `Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category`. I overwrite configuration from `vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/etc/frontend/di.xml` and I set
`<virtualType name="categoryFilterUsingRewrite" type="Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category">
        <arguments>
            <argument name="useUrlRewrites" xsi:type="boolean">true</argument>
        </arguments>
    </virtualType>`
and number of products in layer navigation for category now is correct. 
I question is what can broken if I change  `Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category` to `Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category` ?

**Comment by pawcioma** [comment]
I testing it and looks like virtual category stop working. Listing is empty. How Can I fix it ? Count products in filter works fine with "Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category" but virtual category stop working. When I used "Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category" number of products in filter working wrong.

**Comment by pawcioma** [comment]
I fixed it myself. If it was fixed in some version send me which version

**Comment by romainruaud** [comment]
So this issue can be closed @pawcioma  ?
