### ISSUE TITLE
Index takes too long to finish after installing & configuring module

### ISSUE THREAD

**Issue by barbarosselimbuyukelci** [Smile-SA/elasticsuite#1447]
As you can see below it takes too long to finish index process. 

### Preconditions
198K products, over 10 extra searchable attributes.

Magento Version : 2.3.1

ElasticSuite Version :

Environment : Development mode

Third party modules : Ethan Yehuda's Cronjob Manager Module and our own payment module.

### Actual result
# php bin/magento indexer:reindex catalog_product_attribute
Product EAV index has been rebuilt successfully in 00:46:02

 # php bin/magento indexer:reindex catalogsearch_fulltext
Catalog Search index has been rebuilt successfully in 00:56:50

**Comment by southerncomputer** [comment]
Must be slow machine you are on. I can do 1Million products with 1000 searchable attributes in same time!

**Comment by romainruaud** [comment]
Can you describe more what "too long" means ?

A timing itself show nothing, as stated by @southerncomputer it also strongly depends of the hardware you are running with.

If it's on a production server with 32Go of RAM for MySQL and the same for ES, yes I'd tend to say it's a bit slow.

Please give us more details.

**Comment by barbarosselimbuyukelci** [comment]
Well, as you can see it tooks 46 minutes. 
Server is really strong, brand new i9 16 core processors, 128 gb ram, nvme ssds. IDK why it took so long.

**Comment by southerncomputer** [comment]
dude product eav index is magento only! Has nothing to do with ElasticSuite!

**Comment by romainruaud** [comment]
@barbarosselimbuyukelci 

did you give a try to the legacy Elasticsearch indexing ? the one provided by Magento. I'm curious to see the difference between their version and the ElasticSuite one.

I see that you are still on Developer mode also, you should probably try in production mode.

Also, hardware is fine but are the MySQL and Elasticsearch configuration fine-tuned ? 

Where are theses components ? Do they have their own server, or is everyone on the same server ? 

Regards
