### ISSUE TITLE
Notice: Undefined index: stock

### ISSUE THREAD

**Issue by robjstanley** [Smile-SA/elasticsuite#145]
Causing ajax requests on admin category product view to spin forever.

Notice: Undefined index: stock in smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview/Item.php on line 103

**Comment by romainruaud** [comment]
Hello @robjstanley and thank you for submitting an issue.

We'll provide a fix soon.

Just to know about it, are your store configured to "Manage Stock : false" or something like this in the Magento configuration ?

**Comment by robjstanley** [comment]
Manage Stock is currently set to Yes.

**Comment by romainruaud** [comment]
Did you process a full reindex ?

**Comment by robjstanley** [comment]
I have processed a full reindex, issue remains.

**Comment by romainruaud** [comment]
Fixed by PR #146 

Merged into master, 2.2.x and 2.3.x.

Will be part of the next minor release 2.2.2.

Thank you again for submitting the issue !

Best regards,
