### ISSUE TITLE
After upgrading to 2.3.2 admin is not working

### ISSUE THREAD

**Issue by leonhelmus** [Smile-SA/elasticsuite#1451]
When trying to go to the admin login page we get an error report.

### Preconditions

We get the message:
`{"0":"Class Smile\\ElasticsuiteAdminNotification\\Observer\\PredispatchAdminActionControllerObserver does not exist","1"`

Magento Version : Magento EE

ElasticSuite Version : 2.8.0

Environment : production

### Expected result

1. i want to see a login page.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
For now, I'm not able to reproduce this one.

Did you proceed with compiling after upgrading your Magento instance ?

Regards

**Comment by TimPietrusky** [comment]
I had the same problem and "solved" it by running `bin/magento setup:di:compile`!
