### ISSUE TITLE
Call to undefined method Search\Request::getType when making a search request with WeltPixel AutoComplete.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Smile-SA/elasticsuite#1453]
### Preconditions
Magento Version : Magento 2.3.0 Community Edition.
ElasticSuite Version : 2.9.x-dev
Environment : Developer on Ubuntu server served with Nginx.
Third party modules :
```
Alekseon_CleanRunningJobs
Amasty_Base
Amasty_Groupcat
Amasty_ProductAttachment
Amasty_ProductAttachmentApi
Amazon_Core
Amazon_Login
Amazon_Payment
BitExpert_ForceCustomerLogin
FireGento_FastSimpleImport
Infortis_Base
Infortis_Brands
Infortis_Cgen
Infortis_Dataporter
Infortis_Infortis
Infortis_Ultimo
Infortis_UltraMegamenu
Infortis_UltraSlideshow
Klarna_Core
Klarna_Kp
Klarna_Ordermanagement
Mageants_CustomMenu
Magecomp_Savecartpro
Mageplaza_Core
Mageplaza_LoginAsCustomer
Mageplaza_Smtp
MageWorx_CustomerPrices
MSP_ReCaptcha
MSP_TwoFactorAuth
Smile_ElasticsuiteAdminNotification
Smile_ElasticsuiteAnalytics
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCore
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteTracker
Smile_ElasticsuiteVirtualCategory
Temando_Shipping
Triotech_ModifyNavigationMenu
Ulmod_CategoryViewMode
Ulmod_Core
Vertex_Tax
Webkul_Helpdesk
WeltPixel_Backend
WeltPixel_SearchAutoComplete
```

### Steps to reproduce
1. It was working just fine a week ago so I know that elastic suite module was working with the weltpixel ajax auto complete.
2. Ran a composer install for Mageplaza_Smtp maybe that did some kind of upgrade of elastic suite modules?
3. Now it does not work anymore.
4. Tried rebuilding, clearing caches, deleting static and generated/code directories etc still not happening.

This is by Ajax request not Rest API but may still be related?

Exception:
```
Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Search\Request::getType() in vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php:104
Stack trace:
#0 vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php(82): Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter-&gt;doSearch(Object(Magento\Framework\Search\Request))
#1 vendor/magento/module-search/Model/SearchEngine.php(42): Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter-&gt;query(Object(Magento\Framework\Search\Request))
#2 vendor/magento/framework/Search/Search.php(72): Magento\Search\Model\SearchEngine-&gt;search(Object(Magento\Framework\Search\Request))
#3 app/code/WeltPixel/SearchAutoComplete/Model/Autocomplete/SearchDataProvider.php(267): Magento\ in vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Adapter.php on line 104
```

Any thoughts to repair this?
Kind regards,

**Comment by romainruaud** [comment]
Hello @ChintanKaneriya

I did not dig into the Weltpixel extension source code (and I cannot, since it's not open source), but it's likely unprobable that you can have both this one and Elasticsuite on your website.

Especially considering their extension is providing the same thing as the Elasticsuite autocomplete box.

That being said, supporting third party paid extension is not part of our community support commitment. You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards

**Comment by LiamKarlMitchell** [comment]
I understand this is not something Smile-SA would fix (at least without commercial support).
Just an update on compatibility with WeltPixel for the next guy who has this issue with their Pearl theme/extensions :)

You need to disable these modules to use Smile-SA Elastic Search.
WeltPixel_AdvanceCategorySorting
WeltPixel_LayeredNavigation
WeltPixel_SearchAutoComplete

But then the ajax lazy load scrolling feature from WeltPixel does not work maybe it comes from AdvanceCategorySorting.
Maybe there is some line of code that can be commented out in that module but I have not looked yet.

The Search Autocomplete/bar has CSS over-written in the Theme, which needs to be reverted to allow Smile's one to work properly, the autocomplete words are showing for me now but are not clickable/interactable.

There are other search types though which might work I'll have to play around with it.
![image](https://user-images.githubusercontent.com/1968109/88868230-b34d3c00-d263-11ea-8fe7-aec90d38a539.png)
