### ISSUE TITLE
catalog_product index does not exist yet. Make sure everything is reindexed.

### ISSUE THREAD

**Issue by vitalidadatski** [Smile-SA/elasticsuite#1456]
Hello. I have an exception when i try to use catalogsearch functionality.

Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed.
<pre>#1 Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration->getIndex() called at [vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/ContainerConfiguration.php:94]

Magento version - 2.3.1 EE
smile/elasticsuite": "^2.8

magento in:rei
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:05
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:00
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00

**Comment by romainruaud** [comment]
Hello @vitalidadatski 

I'm afraid that we'll need more details.

Where does this message appear ? 

If you are using ElasticSuite on top of a previously existing Magento instance, please ensure that ElasticSuite is set as default search engine on the configuration : **Stores > Configuration > Catalog > Catalog Search > Search Engine**.

This parameter should be set to Smile ElasticSuite.
