### ISSUE TITLE
"/var/www/html/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid

### ISSUE THREAD

**Issue by kleestb** [Smile-SA/elasticsuite#1457]
**Description**
It's not possible to create or edit a cms page.

**Reproduce**

install Magento 2.3.1
set deployment mode to developer
install magesuite 2.0.3
install and activate creativeshop theme
clear cache and open the backend
go to Content -> Elements -> Pages -> Add New Page or edit a existing one
Expected
The cms page editor should be opened.

**Actual**
An error is displayed.

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/html/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 9

Verify the XML and try again.

Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/html/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 9

Verify the XML and try again.
<pre>#1 Magento\Ui\Config\Reader->read() called at [vendor/magento/module-ui/Config/Data.php:102]
#2 Magento\Ui\Config\Data->initData() called at [vendor/magento/module-ui/Config/Data.php:136]
#3 Magento\Ui\Config\Data->get('cms_page_form') called at [vendor/magento/framework/View/Layout/Reader/UiComponent.php:100]
#4 Magento\Framework\View\Layout\Reader\UiComponent->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea72731000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7270c000000001904b426#) called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#5 Magento\Framework\View\Layout\ReaderPool->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7270c000000001904b426#) called at [vendor/magento/framework/View/Layout/Reader/Container.php:89]
#6 Magento\Framework\View\Layout\Reader\Container->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7270c000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7273d000000001904b426#) called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#7 Magento\Framework\View\Layout\ReaderPool->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7273d000000001904b426#) called at [vendor/magento/framework/View/Page/Config/Reader/Body.php:68]
#8 Magento\Framework\View\Page\Config\Reader\Body->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7273d000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7271e000000001904b426#) called at [vendor/magento/framework/View/Layout/ReaderPool.php:105]
#9 Magento\Framework\View\Layout\ReaderPool->interpret(&Magento\Framework\View\Layout\Reader\Context#000000003ea724eb000000001904b426#, &Magento\Framework\View\Layout\Element#000000003ea7271e000000001904b426#) called at [vendor/magento/framework/View/Layout.php:325]
#10 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:89]
#11 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#12 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:55]
#13 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#14 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:253]
#15 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:875]
#16 Magento\Framework\View\Layout->getBlock('menu') called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:414]
#17 Magento\Framework\View\Layout\Interceptor->getBlock('menu') called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#18 Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Cms::cms...') called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#19 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Cms::cms...') called at [vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php:60]
#20 Magento\Cms\Controller\Adminhtml\Page\Edit->_initAction() called at [vendor/magento/module-cms/Controller/Adminhtml/Page/Edit.php:93]
#21 Magento\Cms\Controller\Adminhtml\Page\Edit->execute() called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php:24]
#22 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#23 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#24 Magento\Backend\App\AbstractAction->dispatch(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#27 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(&Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor#000000003ea724f3000000001904b426#, &Closure#000000003ea724db000000001904b426#, &Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#), NULL) called at [generated/code/Magento/Cms/Controller/Adminhtml/Page/Edit/Interceptor.php:39]
#30 Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/App/FrontController.php:159]
#31 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#, &Magento\Cms\Controller\Adminhtml\Page\Edit\Interceptor#000000003ea724f3000000001904b426#) called at [vendor/magento/framework/App/FrontController.php:99]
#32 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#33 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#34 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#35 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#), array(array('default_store_se...', 'page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'))) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#36 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#000000003ea72197000000001904b426#) called at [vendor/magento/framework/App/Http.php:136]
#37 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#38 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#39 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000003ea721dd000000001904b426#) called at [index.php:46]
</pre>

**Comment by romainruaud** [comment]
Hello,

this is not related to ElasticSuite at all.

Please submit your issue on the "magesuite" repository.

Regards
