### ISSUE TITLE
No product found when using "Show all" on product list

### ISSUE THREAD

**Issue by FlinthDevs** [Smile-SA/elasticsuite#1458]
Using the "Show all" feature on products lists returns no result.

### Preconditions

Magento Version : 2.3.1 CE
ElasticSuite Version : 2.8.0
Environment : Developper

### Steps to reproduce

1. Enable "Allow all products per page" option in admin
2. Go on a product list page (category view or fulltext search)
3. Select "All" in "Show X per page" select

### Expected result
1. All products are listed

### Actual result
1. No products are found and the message "We can't find products matching the selection." displayed.

**Comment by rbayet** [comment]
Fixed by https://github.com/Smile-SA/elasticsuite/pull/1431

**Comment by rbayet** [comment]
See also #1428

**Comment by romainruaud** [comment]
Fixed by associated PR #1460
