### ISSUE TITLE
"Only discounted products" shows products with a price per group of customer

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1462]
### Preconditions
J'ai eu ce problème sur Magento Commerce 2.3.1 avec Elastic Suite.
je peux fournir un accès à cette plateforme si besoin( par message privé)

### Steps to reproduce
* Sur un produit X, définir un prix plus bas valable uniquement pour un groupe de client Y.
* Créer une catégorie virtuelle avec la règle "only discounted products"
* En front, aller sur cette catégorie virtuelle : cette catégorie va afficher le produit X, même si on est un client anonyme qui ne fait pas partie du groupe de client Y.

On se retrouve dans une situation qui n'est pas désirée: on est dans une catégorie censée afficher des produits en promo et on affiche un produit qui n'a pas de promo.

**Comment by PierrickOlivier** [comment]
Je vois que j'ai le même problème dans les règles de boost: une règle de boost sur "only discounted products" boost aussi les produits avec un prix par groupe de client.

**Comment by romainruaud** [comment]
Fixed by #2401 

I forgot to close this old issue :)
