### ISSUE TITLE
404 errors on the demo website

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1463]
Le site de démo http://demo.magento-elastic-suite.io est un peu "cassé":
* La catégorie "Women" n'est pas à côté de "Men". Elle n'a plus ses sous-catégories.
* Quand on clique sur "Women" et qu'on essaye d'aller sur une sous-catégorie, on a une erreur 404
* Idem sur la catégorie "Sale" et "What's new", il y a des erreurs 404 sur les sous-catégories

Ces erreurs 404 partout, ça donne l'impression que le site ne fonctionne pas bien...

**Comment by romainruaud** [comment]
Fixed
