### ISSUE TITLE
Missing "position" column when assigning products to category

### ISSUE THREAD

**Issue by qsolutions-pl** [Smile-SA/elasticsuite#1464]
### Preconditions

Magento Version : 2.3.x

ElasticSuite Version : 2.8.0

Environment : both Developer & Production mode

Third party modules : none

### Steps to reproduce

1. Enable module
2. Go to category page in backend, assign products to it
3. Try to assign custom product position

### Expected result

1. Visible column "Position" when setting up product order

### Actual result

1. [Screenshot, logs] No position column
![image](https://user-images.githubusercontent.com/4256191/60907724-886c0080-a27a-11e9-890b-0f1408a550b1.png)

**Comment by romainruaud** [comment]
@qsolutions-pl this is by design. We removed the column since users can manage product position by using the Visual Merchandiser (drag and drop tool) that is provided by Elasticsuite.

Regards

**Comment by qsolutions-pl** [comment]
@romainruaud ok I do get that, but it is impossible or very hard to manage large database with over 50k products. Maybe consider position parameter to be configurable somewhere?
