### ISSUE TITLE
tracking_log_session index does not exist yet. Make sure everything is reindexed

### ISSUE THREAD

**Issue by kevinvuillemin** [Smile-SA/elasticsuite#1465]
Hello,

Very nice,

All done without an error in analytics : 
tracking_log_session index does not exist yet. Make sure everything is reindexed.
tracking_log_event index does not exist yet. Make sure everything is reindexed.

My products and categories are indexed.

An idea ? 

Magento version - 2.3.2
smile/elasticsuite": "^2.8

![Sélection_082](https://user-images.githubusercontent.com/12586404/61022298-ea4e7680-a3f0-11e9-9ac4-e4d8ff790242.png)

**Comment by romainruaud** [comment]
Hello @kevinvuillemin 

there is a cronjob indexing periodically the tracker data. So on a cold start, it's normal to have nothing.

What you should check now is : 

- when you browse the frontend of your website, you should see data coming in the table `elasticsuite_tracker_log_event`

- your crontab has to be set up properly so that data will be sent from this table and indexed into ES periodically.

regards

**Comment by kevinvuillemin** [comment]
Thanks a lot, I thought it was with command: indexer:reindex.

It works very well, thank you

**Comment by cconway24** [comment]
I am seeing this same error so I looked in the elasticsuite_tracker_log_event table and it's empty. Where should I look next as to why data isn't being populated?

**Comment by amenk** [comment]
Is tracking maybe disabled for your shop?

Stores -> Configuration -> Tracking -> Global -> Enabled -> Yes

But I made bad experience with the tracking...

**Comment by DevRiffs** [comment]
I have same issue now. Same error, elasticsuite_tracker_log_event is empty, tracking is enabled. What else should I check to make it work?

**Comment by rbayet** [comment]
Hello @cconway24, @DevRiffs,

If tracking is enabled and you still are not getting any data into the table `elasticsuite_tracker_log_event` **and** not tracker indices in Elasticsearch (*tracking_log_event* and *tracking_log_session* indices), check that the JS tracker is correctly loaded on your front pages (see below).

If you have *tracking_log_event* and *tracking_log_session* indices in your Elasticsearch but still getting that error, please open a new issue.

**Checking the JS tracker is loaded**

You should images requests to `elasticsuite/tracker/hit/image/h.png` such as this one in your Firefox/Chrome/browser network console : 
```
https://your.domain.tld/elasticsuite/tracker/hit/image/h.png?page[store_id]=1&page[cms][identifier]=home&page[cms][title]=Home Page&page[type][identifier]=cms_index_index&page[type][label]=CMS Home Page&session[uid]=e6a3f8ce-0c80-9400-7c4e-a625c3f83168&session[vid]=a12041a3-77b4-8881-b301-0f4bd7e1f94d&page[site]=ee235p2.lxc&page[url]=/&page[title]=Home Page&page[resolution][x]=1920&page[resolution][y]=1032
```

If you're not seeing this, then a third party module is messing with the layout instruction of Smile\ElasticsuiteTracker

If you're seeing those, but the HTTP response code is not 200, please investigate what may cause the issue on your infrastructure.

Regards,

**Comment by edenofjinx** [comment]
@rbayet everything seems like it works but still get that the indexes do not exist yet.
![Screenshot from 2021-01-28 14-14-45](https://user-images.githubusercontent.com/23340692/106137607-98f10e00-6173-11eb-802f-7f64ba90fafd.png)

**Comment by kiber** [comment]
I had the same issue and the solution was enabling Tracking and running **elasticsuite_index_log_event** cronjob

**Comment by felixsebastiany** [comment]
Try:

> bin/magento indexer:reset && bin/magento indexer:reindex && bin/magento cron:install && bin/magento cron:run
