### ISSUE TITLE
"search by SKU" in the Merchandiser

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1467]
In the menu "Search term", when you click "Merchandisier", a screen is displayed to sort products by drag & drop.

In this screen it is not possible to search for a product by SKU.

This search is available on the category page, but is not available in the search term. It would be nice to add it because in the search result page we frequently have many products displayed.

(this feature has been suggested by Decathlon users)

**Comment by romainruaud** [comment]
@androshchuk I think you may have a try on this one

**Comment by romainruaud** [comment]
I forgot to close this one but it have been implemented, thank you !

**Comment by androshchuk** [comment]
@romainruaud You're welcome! :)
