### ISSUE TITLE
Товар в самиый вверх с помощью "Optimizers List" не смотря на "Manual Sort" 

### ISSUE THREAD

**Issue by TexnikTexnolog** [Smile-SA/elasticsuite#1472]
Доброго времени суток.
Я закрепил товар в категориях с помощью "Manual Sort"  http://prntscr.com/og464i 
И товар в категория находится с верху в том порядке что и нужно.
Но у меня возникает потребность поднимать товар на который есть скидка в самый верх категории (над тем товаром что я выставил с помощью  "Manual Sort" )
Акционный товар я поднимал вверх в "Optimizers List" http://prntscr.com/og49dd 
Но в таком случаи товар поднятый с помощью "Optimizers List" становится ниже товара выставленного с помощью "Manual Sort"
Как я могу поднять товар в самый вверх каталога с помощью "Optimizers List" ?

**Comment by androshchuk** [comment]
Доброго времени суток. 
Спасибо за Ваш вопрос.
Мы не планируем вводить такую функцию в ElasticSuite. Продукты с "Manual Sort" всегда будут иметь приоритет над продуктами, которые подпадают под оптимизаторы. Так было задумано и, вероятно, не изменится в ближайшее время. Вы можете самостоятельно изменить это поведение переопределив методы Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareSortOrders или Smile\ElasticsuiteCatalog\Plugin\LayerPlugin::setSortParams .

С уважением, команда Elasticsuite
