### ISSUE TITLE
Search optimizer not working on 2.8.1

### ISSUE THREAD

**Issue by Jurhillebrink** [Smile-SA/elasticsuite#1473]
The search optimizer doesn't work anymore after upgrading elasticsuite to 2.8.1

### Preconditions

It is not working on Magento 2.3.2 with 2.8.1 and not working on magento 2.3.1 with 2.8.1. When I downgrade Elasticsuite to 2.8.0 on Magento 2.3., the search optimizer works properly.

Magento Version : CE

ElasticSuite Version : 2.8.1

Environment : Developer mode

Third party modules : =

### Steps to reproduce

1. Install Magento 2.3.1 or 2.3.2 with Elasticsuite 2.8.1 and sample data
2. Create search optimizer, set 'model' to 'constant', set 'request type' to 'Category Product View', set 'apply to' 'all categories', set 'boost value' to '200', set 'rule conditions' to 'Color is one of Red', set 'category preview' to 'men'.
3. Click on 'Preview'

### Expected result

1. Products are boosted:
![image](https://user-images.githubusercontent.com/14016931/61464070-ef25a400-a975-11e9-85c4-9f3100230b8a.png)

### Actual result

1. Products are not boosted: 
![image](https://user-images.githubusercontent.com/14016931/61464189-24ca8d00-a976-11e9-998b-07c3d054e26d.png)

**Comment by romainruaud** [comment]
@androshchuk can you try to reproduce this one against both described versions ?

Regards

**Comment by romainruaud** [comment]
Fixed by PR #1480
