### ISSUE TITLE
Getting Error in exception log in Magento 2: Call to a member function getValues() on null at /vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/SessionIndex.php:69)"} []: 

### ISSUE THREAD

**Issue by Renu05** [Smile-SA/elasticsuite#1477]
SmileSuite throwing an error Call to a member function getValues() on null at 
 /vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/SessionIndex.php:69)"} []

### Preconditions
Our site is configured in Magento cloud. we have configured Redis ,Elasticsearch
We are using Smilesuite and found that whenever we refresh the product listing page we are getting an error in exception log stating that 
**report.CRITICAL: Error when running a cron job {"exception":"[object] (RuntimeException(code: 0): Error when running a cron job at vendor/magento/module-cron/Observer/ProcessCronQueueObserver.php:327, Error(code: 0): Call to a member function getValues() on null at vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/SessionIndex.php:69)"} []**

Magento Version :2.3. 1(EE)

ElasticSuite Version :2.8.0
ElasticSearch : 6.5.4

Environment : Production Mode

Third party modules : Amasty ,Aheadworks

### Steps to reproduce

1.Configured the smilesuite extension vesion 2.8.0 , Redis 3.0 and elasticsearch 6.5.4
2. Refresh the product listing page and check the exception log 
3. Error found Call to a member function getValues() on null at /vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/SessionIndex.php:69)"} []

### Expected Result 
smilesuite should work without an error.

**Comment by romainruaud** [comment]
Fixed by PR #1491
