### ISSUE TITLE
Behavior of category suggest

### ISSUE THREAD

**Issue by berwa** [Smile-SA/elasticsuite#1478]
In one of our projects we encountered a very strange behavior regarding the category-suggest: it only seems to work properly if the category's name was once searched for.

### Preconditions
Magento Version : Commerce 2.2.9
ElasticSuite Version : 2.6.9
Environment : all modes
Third party modules : none (reproduced on plain installation: only Magento, sample-data and Elasticsuite)
important: no searches submitted yet (no entries in table search_query)

### Steps to reproduce
(plain Magento-installation with sample-data)
Start typing "sweatshir" into search-bar 

### Expected result
Suggest for existing category "Hoodies & Sweatshirts" should be displayed

### Actual result
No category-suggest is displayed
(it will be displayed if "sweatshirt" was typed-in completely, or if a search for "sweatshirt" was submitted before)

**Comment by romainruaud** [comment]
It's by design, see my answer here : https://github.com/Smile-SA/elasticsuite/issues/1413

I consider this issue as a duplicate
