### ISSUE TITLE
Add ignore_above: 256 on untouched in mapping

### ISSUE THREAD

**Issue by Fdec** [Smile-SA/elasticsuite#1479]
Hi

On untouched field in the mapping, there is not automatically "ignore_above: 256", saw with @rbayet .

Magento 2.3.1
Elasticsuite 2.8.1
Elasticsearch 6.5.4

**Comment by romainruaud** [comment]
@androshchuk can you handle this one ?

Probably a good location to investigate is on : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Index/Mapping/Field.php#L357

**Comment by rbayet** [comment]
Fixed by PR #1487
