### ISSUE TITLE
Contacting elasticsuite to elastic cloud

### ISSUE THREAD

**Issue by timovanhilst** [Smile-SA/elasticsuite#1482]
Hello!

I'm new to Elasticsearch/Elasticsuite.
And I'm trying to figure out how to use Elasticsuite in combination with hosting Elasticsearch at Elastic cloud (elastic.co).

I searched on the internet for a guide/tutorial but I can't find much about it.

Can someone help me?
it is greatly appreciated! :)

**Comment by jsterling** [comment]
Very little setup is required. Once you've created a deployment in Elastic Cloud, in Magento admin go to:

Store > Configuration > ElasticSuite > Base Settings

- Servers List: use 'Copy Endpoint URL' in your ElasticCloud dashboard to get the URL. You may need to remove the https:// prefix
- Use HTTPS = Yes
- Enable basic HTTP Authentication = Yes
- Basic HTTP Authentication User = elastic
- Password: Given by Elastic Cloud

**Comment by romainruaud** [comment]
Thanks @jsterling for answering this one, I could not have done better :)

 @timovanhilst is ok for you ? May I close ?

**Comment by timovanhilst** [comment]
I'm sorry I didn't respond.
I can make a conection with the Elastic cloud but I get the following error

{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[tiebreaker-000000002][172.17.0.30:19700][indices:admin/create]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}

**Comment by jsterling** [comment]
You need to enable the analysis-icu and analysis-phonetic under 'Elasticsearch plugins and settings' when managing your Elastic Cloud deployment.

**Comment by timovanhilst** [comment]
It was a bit of a hassle to find out where these settings can be found.
Thanks for the help!

Go to your deployment -> Edit page -> Manage plugins and settings. 
Enable analysis-icu & analysis-phonetic

**Comment by emogerov** [comment]
I still get the same error even though in Elastic Cloud both plugins are enabled
