### ISSUE TITLE
How to show short_description in autocomplete results?

### ISSUE THREAD

**Issue by aario** [Smile-SA/elasticsuite#1484]
**Is your question related to a problem? Please describe.**
How to show short_description in autocomplete results? It's not a filterable attribute though.

**Additional context**
The Show in Autocomplete option doesn't appear for this attribute in Admin Panel> Product Attributes> Edit> Store Front Properties

**Comment by romainruaud** [comment]
Duplicate of #953 

Also see https://github.com/Smile-SA/elasticsuite/issues/1416 for a detailed answer.

Regards
