### ISSUE TITLE
Stock Status boost Optimizer not working properly

### ISSUE THREAD

**Issue by george1604** [Smile-SA/elasticsuite#1490]
I tried to set up an Optimizer as described in this post: https://github.com/Smile-SA/elasticsuite/issues/704. The problem is that the in-stock products are distributed on pages (2 in-stock products are on top of the first page, another 3 products are on top of the second page and so on). Is this normal or am I missing something?

### Preconditions
Magento Version : 2.2.7
ElasticSuite Version : 2.6.5
Environment : development, production
Third party modules : no

### Steps to reproduce
1. Create an Optimizer for In stock products with boost 1000 (similar as https://github.com/Smile-SA/elasticsuite/issues/704#issuecomment-359784903)
2. Go to the category page. (I have a category with 27 products, 6 in stock, 21 out of stock)

### Expected result
1. All in-stock products are on the first page.

### Actual result

1. In-stock products are distributed between the 3 pages of the category.
After some debugging, I figured out that Elasticsuite query returns the products in the correct order. Then, Magento is doing smth strange. When "loading" the collection, a MySQL query runs "SELECT ...  WHERE entity_id IN (all ids from elasticsearch in correct order) **LIMIT 10**". Why does Magento do the pagination here?
2. Another strange thing is that the implementation provided in this response (https://github.com/Smile-SA/elasticsuite/issues/704#issue-290826172) is working for me, but only on the category page. In search result page it's not.

**Comment by romainruaud** [comment]
The `LIMIT 10` usually comes from the pagination toolbar of Magento. Do you have any configuration related to this ? 

Maybe you should try to trace back if there is a call to `setPageSize` on the collection and find out who is applying this.

regards
