### ISSUE TITLE
Imported configurable products not visible in search or layered nav

### ISSUE THREAD

**Issue by tieroom** [Smile-SA/elasticsuite#1492]
### Preconditions
Magento Version : 2.3.1 on PHP 7.2
ElasticSuite Version : 2.8.0
Environment : Developer

### Steps to reproduce
1. Using the standard magento product import, import a configurable product including its simple children. Have them all added to categories and visibility of all set to "catalog,search".
2. Reindex and clear cache
3. Try finding the imported products in layered navigation or search

### Expected result
1. Both the simple and the configurable products should be found in search and found in the categories they were assigned through the layered navigation.

### Actual result
1. Only the simple products are found in search and layered nav. The configurable can only be found by visiting its URL directly.

After some debug it seems like Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Action\Full:addIsVisibleInStoreFilter() only grabs products that are added to the root category and for some reason newly imported configurable products are not added to root.

Note that old configurable products that were migrated from M1 work as expected. This only applies to new products imported to M2.

Before I go on somehow forcing root categories on these configurables, I want to check if this is anything you have seen before or that should be handled differently by the extension.

**Comment by androshchuk** [comment]
Hello, tieroom. Thank you for your report. Сan you give me your import file?

Regards

**Comment by tieroom** [comment]
So you've got two files here. new_products_for_import.csv adds to file to the admin and new_products_translation_for_import.csv adds it for a specific store front.

These obviously include a lot of specific stuff for our store. I'm going to try scale it down to a single file that can be imported on a vanilla magento and see if the issue can be reproduced there. But, in the meantime, if you can say anything just from these files, I'm all ears.

[product_import_csv_files.zip](https://github.com/Smile-SA/elasticsuite/files/3451458/product_import_csv_files.zip)

**Comment by tieroom** [comment]
Turns out the reason was not to do with the root category. It was simply because of a custom attribute (barcode) which was not being populated for the configurables. Once I set this to a random value the configurables also got indexed. I'm gonna guess this is a magento core issue rather than a smile issue. Feel free to reopen if you feel differently and want more details.
