### ISSUE TITLE
Magento 2.3.2, ES 2.8.0 Error: "Please upgrade your database"

### ISSUE THREAD

**Issue by satellite1** [Smile-SA/elasticsuite#1496]
Fresh virgin install of Magento 2.3.2 OSE
PHP 7.2.19
MySQL 5.7.25
Developer Mode
Note: Everything working until adding:
composer require smile/elasticsuite ~2.8.0

sudo php bin/magento setup:upgrade
sudo php bin/magento setup:di:compile
etc..

![image](https://user-images.githubusercontent.com/16124737/62418502-e3093a00-b637-11e9-9901-702f26eb62f2.png)

My educated experienced guess would be an incomplete install/upgrade. Possibly because during upgrade it flags looking for active cluster? 

Then throws error in browser. Even multiple attempts to upgrade yield same:

`{"0":"Please upgrade your database: Run \"bin\/magento setup:upgrade\" from the Magento root directory.\nThe following modules are outdated:\nSmile_ElasticsuiteCatalog data: current version - none, required version - 1.5.1\nSmile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0\nSmile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0\nSmile_ElasticsuiteTracker data: current version - none, required version - 1.2.0\nSmile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1\nSmile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0\nSmile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1\nSmile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.4.1","1":"<pre>#1 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000006d9edf7b0000000026972ec7#) called at [vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php:73]\n#2 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(&Magento\\Framework\\App\\FrontController\\Interceptor#000000006d9edfec0000000026972ec7#, &Closure#000000006d9ede630000000026972ec7#, &Magento\\Framework\\App\\Request\\Http#000000006d9edf7b0000000026972ec7#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#3 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(&Magento\\Framework\\App\\Request\\Http#000000006d9edf7b0000000026972ec7#) called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#4 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', array(&Magento\\Framework\\App\\Request\\Http#000000006d9edf7b0000000026972ec7#), array(array('page_cache_from_...', 'storeCookieValid...', 'install', 'configHash'), array('front-controller...'), 'requestPreproces...')) called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:26]\n#5 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(&Magento\\Framework\\App\\Request\\Http#000000006d9edf7b0000000026972ec7#) called at [vendor\/magento\/framework\/App\/Http.php:137]\n#6 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:261]\n#7 Magento\\Framework\\App\\Bootstrap->run(&Magento\\Framework\\App\\Http\\Interceptor#000000006d9edf9e0000000026972ec7#) called at [index.php:39]\n<\/pre>","url":"\/","script_name":"\/index.php"}`

**Comment by satellite1** [comment]
@romainruaud 

Hello,

The ESS should not be enabled nor looking for a local ES install just to install the module. Magento 2.3.2 still sets search to MySQL as default. In my architecture, the design is to have the Elasticsearch server on a separate instance. 

Thanks for the reply.

Regards,

**Comment by romainruaud** [comment]
ElasticSuite sets himself as default when installing the module. So you must have an Elasticsearch server running somewhere.

It can be on a separate instance but in this case you have to properly set it into the configuration :  https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-already-installed-

**Comment by satellite1** [comment]
@romainruaud 

That's a catch 22 for many. You can't configure ES if the server is crashed, because the ES failed to install, and of course not too many end users will want to or have the experience to CLI install.  

My suggestion, [if possible] is not to set ES as default on install. Let the end user enable and configure the module first, because not everyone will have port 9200 open, and not everyone is going to have ES properly installed or want to have installed on local server. 

I kind of figured this was the issue after troubleshooting it, and your reply confirmed it. Thanks. 

S1
