### ISSUE TITLE
Swatches attributes not displayed with Manual Sort

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#1497]
### Preconditions

Magento Version : 2.3.x

ElasticSuite Version : 2.8.x

Environment : dev and/or prod

Third party modules : none

### Steps to reproduce

1. Create a *visual swatch attribute* with some values and attached visuals (like `color` attribute)
2. Set it to be filterable in search and in layered navigation
2. Set the *Facet Sort Order* to *Admin Sort*
3. Reindex if needed, go to a frontend category where this attribute should be displayed in layered navigation filters

### Expected result

1. The filter should be displayed with all attributes values

### Actual result

1. No values are displayed for this filter

It's only happening with "Admin sort" option for the "Facet Sort order". Other modes are fine.

When fixing this one, beware to not cause a regression on precedent #1371

**Comment by androshchuk** [comment]
Hello, @romainruaud . I fixed this https://github.com/Smile-SA/elasticsuite/pull/1499 and did a little refactoring.

Regards

**Comment by rbayet** [comment]
Fixed by PR #1499
