### ISSUE TITLE
Group attribute values in facets

### ISSUE THREAD

**Issue by royandre** [Smile-SA/elasticsuite#1498]
When filtering on typically colors or sizes, there often exists hundreds of attribute values (e.g "Dark Red", "Blood Red", "Rose Red", "Red'ish" and what not), and so we need to group attribute values like this over to another attribute typically called "color_filter", which only has "Red", "Blue", etc. and where all the red variants are mapped to the "Red".

Then, the "color_filter" attribute is the one to be used as facet/filter attribute, while the "color" attribute with the hundreds of options is kept away from the facet/filter.

We have made a "Filter Mapping" module for this for M1, and we have used the Amasty Improved Navigation's "Group Mapping" function for this for M2, however with the introduction of Elastic Search we are kicking out Amasty Improved Navigation all-together, and then need a replacement for it.

We can develop this functionality and add as a PR here or separate module (TBD) - we just want to check if anyone else has done this already or is up for it?

**Comment by JeroenVanLeusden** [comment]
Major bump. We're definitely interested in this feature.

**Comment by Melleschepers** [comment]
Also very interested in this feature.

**Comment by romainruaud** [comment]
That's quite an old issue but I'm curious to see if you did built it by yourself @royandre ?

If that's the case I'll be glad to review a PR
