### ISSUE TITLE
Sorting doesn't work on multistore non-default storefront

### ISSUE THREAD

**Issue by wmwnuk** [Smile-SA/elasticsuite#1500]
### Preconditions

Magento Version : 2.3.0 Community Edition / Open-Source Edition

ElasticSuite Version : 2.8.0

Environment : Developer and Production mode

Third party modules : 
Infortis_Infortis
Infortis_Brands
Infortis_Cgen
Infortis_Dataporter
Infortis_Base
Infortis_UltraSlideshow
Infortis_UltraMegamenu
Infortis_Ultimo

(I've listed only modules affecting layered navigation / search page since disclosing full list of modules / customizations might be a security risk since stores we speak about are live + most of the modules have to do with promotions, orders, customer service and checkout, design or frontend optimization)

### Steps to reproduce

1. Set up ElasticSuite on a Magento 2 store with more than one store view.
2. Add some attributes to sort (set them as used for sorting).
3. Clear cache and run full reindex.

### Expected result

1. On all store views sorting should be working properly, as well as pagination (actually I mean product_list_limit parameter).

### Actual result

1. On default store view everything works fine, although on the second store view no sorting option selected from toolbar does work, also some categories appear empty (but it's hard to tell the actual rule here, but I believe it has to do with number of products being lower than one page, so 32 by default).
2. This is default store view using ElasticSuite: https://www.stressnomore.co.uk
3. This is the second store view with faulty sorting: https://www.kegel8.co.uk (page size problem is already fixed not-really-clean way, since these are production stores, so categories cannot be left empty just to show it doesn't work).

There are some modifications to sorting, but these only modify param coming from url (price_asc => order by price, set direction to ASC, so the collection itself receives expected parameters: attribute_code and sort direction), but also it was tested with all these custom modules disabled and the effect is the same. Non-default store view is experiencing problems described. The sort order data seems to be absent in queries sent to ElasticSearch.

**Comment by rbayet** [comment]
Hello @androshchuk,

Can you try to first reproduce the issue on a multi-store CE 2.3.0 edition with Elasticsuite version 2.8.0, with classic and virtual categories ?
If confirmed, see what happens in with 2.8.x-dev ?

Regards,

**Comment by rbayet** [comment]
Hello @wmwnuk,

Sorry I was not able to reproduce the behavior you described on a fresh Luma CE 2.3.0 with Elasticsuite 2.8.0 and two store views and an additional attribute used for sorting (I used the SKU).

I'm not sure the tweak you made to have a single GET variable to have both sort order and sort direction is the culprit, but it's a good starting point.
If that's not the source of the problem, then disabling one by one your third party modules related to search / layered navigation is the way to go.

If you can reproduce the behavior on a local install, try to debug to see if you go through `\Smile\ElasticsuiteCatalog\Plugin\LayerPlugin` ?

Regards,

**Comment by romainruaud** [comment]
@wmwnuk did you manage to fix it by yourself ?

**Comment by drinkingsouls** [comment]
@rbayet 
A slightly unrelated question - how did you get sort by newest to work with ElasticSearch? I can see on the demo site kegel8.co.uk that products can be ordered by newest in the category.
Thank you.
