### ISSUE TITLE
M1 vs M2 Module - Virtual Attributes and Rule Conditions

### ISSUE THREAD

**Issue by jesse-thomas** [Smile-SA/elasticsuite#1502]
In the M1 version of this module there was...
- A Virtual Attribute feature to allow product attributes to be based on Smile or other catalog rule conditions. It was very powerful, for example to add an In Stock or On sale filter to search results or even a catalog rule. 
- A Catalog rule condition for "Only new products" which we used for a New Products virtual category. 

I don't see those options in the M2 version, are there any plans to add them? Or is there a feature in M2 that makes them obsolete?

To say your modules are awesome would be an understatement, you set the bar very high for others wanting to develop an Elastic module. Thanks for all your hard work! 

Thanks!

**Comment by jesse-thomas** [comment]
Just found pr #595 and it worked for creating the "only new products" condition.

**Comment by romainruaud** [comment]
@jesse-thomas can you contact me directly by mail about this topic ? via romain.ruaud@smile.fr

Thank you !

**Comment by jesse-thomas** [comment]
I sent you two emails, you might have responded. I am on a few mailing lists and could have deleted the email. I'd be happy to send another if you have time to respond?
thanks!

**Comment by jesse-thomas** [comment]
I'm still interested in a solution to the in stock filter.
