### ISSUE TITLE
How to add custom attributes?

### ISSUE THREAD

**Issue by leonardovilarinho** [Smile-SA/elasticsuite#1504]
Hi,

I'm new to Magento 2 and Elastic, I was wondering if in this module I can put custom attributes in Elastic. I installed the module, and saw that in Elastic not all attributes of categories and products appear.

For example, in the categories does not appear the image link. Products do not show data about Magento custom options.

Can I add new attributes to Elastic? Can anyone tell me the way to do this?

**Comment by androshchuk** [comment]
Hi, @leonardovilarinho 

Please read ElasticSuite wiki https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration and don't forget to reindex.

Regards

**Comment by romainruaud** [comment]
@leonardovilarinho is the provided answer enough for you ? 

Do you need more informations ?

**Comment by leonardovilarinho** [comment]
@romainruaud  I tried, with most attributes gone right. But now I have problems trying to index images, when the product has more than one image only the main image is indexed in Elastic.

I would like to index all product images in an array, Magento has the media_gallery attribute that stores all product photos, even if you change the attribute settings the media_gallery tutorial does not appear in Elastic.

In other search solutions like Algolia, indexing media_gallery works, only in Elastic that I can't.

**Comment by romainruaud** [comment]
I close this one since the level of customization you want to achieve cannot be covered as part of our Open Source support policy here, despite being completely achievable.

If you want us to provide more support on this one, you can contact us by mail at romain.ruaud@smile.fr to purchase professional support services which will allow us to provide you more coaching or development workforce to achieve your needs.

Regards

**Comment by glenelkinsdev** [comment]
> https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration

yes my backend model is Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

![image](https://github.com/Smile-SA/elasticsuite/assets/99587729/a8916a02-034e-4cce-9d1d-efcf0af1b7c9)
