### ISSUE TITLE
Elasticsearch displays categories from different storeview

### ISSUE THREAD

**Issue by perrivdb** [Smile-SA/elasticsuite#1505]
Elasticsearch displays categories in search results that are not enabled in the current storeview. Clicking on the result directs you to a 404 page.

Any idea where this is going wrong?

**Comment by androshchuk** [comment]
Hello, @perrivdb 

You have not provided enough information about the issue. 
If I understood correctly the problem is that the disabled category (like Watches) disappears from the top menu but does not disappear from the left menu (subcategories)
http://joxi.ru/Dr8OK11fo0XM7A

This seems to be a problem for magento2, not our module. I was checking on clean magento2 without elasticsuite.

Can you check it on a clean magento2? Or please provide us with more details about the problem.

Regards

**Comment by rbayet** [comment]
Hi @perrivdb,

As requested by @androshchuk, please provide the usual context informations  
- preconditions (Magento2 version, Elasticsuite version, environment, third party modules used, ...)
- steps to reproduce

Regards,

**Comment by perrivdb** [comment]
Hi!

Apoligies for the delayed response. I'll make my situation a bit more clear:

**Magento Version :** 2.3.2 CE
**ElasticSuite Version :** 2.8.0
**Environment :** Issue is present in both developer as production mode
**Third party modules :** 
_"ebizmarts/mailchimp-lib": "^3.0",
"tig/buckaroo": "^1.10",
"honl/magento2-nl-nl": "^1.1",
"fooman/pdfcustomiser-m2": "^8.2"
Amasty_Base
Amasty_GoogleMap
Iksanika_Productmanage
MageArray_CustomOptions_

### Steps to reproduce
1. Have a magento 2.3 multistore, where each store has its own set of (unique) categories
2. Open frontend of a store and search for a category that is only present in a different store

### Expected result
1. Search result should be empty

### Actual result
1. Elasticsuite lists the category in the search results. Clicking on it results in a 404 page because the current store does not have the listed category active.
<img width="513" alt="Screen Shot 2019-08-27 at 14 34 34" src="https://user-images.githubusercontent.com/27292635/63771683-e6f74780-c8d7-11e9-8219-b896ef7669d2.png">

<img width="1300" alt="Screen Shot 2019-08-27 at 14 34 42" src="https://user-images.githubusercontent.com/27292635/63771682-e6f74780-c8d7-11e9-8a3a-6e8b17baf40b.png">

**Comment by romainruaud** [comment]
Ok so if I understand correctly, we are showing disabled categories in the autocomplete box.

@androshchuk @serg6854 can you check by reproducing the scenario from @perrivdb with the two different store views, and a different category tree per store view ?

Regards

**Comment by perrivdb** [comment]
Thanks for the fix!
