### ISSUE TITLE
How to search by category url?

### ISSUE THREAD

**Issue by leonardovilarinho** [Smile-SA/elasticsuite#1507]
I am trying to do a search by the URL of a category, with product the same query works. But with category the return is empty.

For example, I have the category "pecas", as in print below:

![Category](https://image.prntscr.com/image/yvc7FXBVQYyFW-WPI4aNZA.png)

The category url is represented by the url_path attribute, so I try to search by term (because I want to search for an exact string). But the return is empty:

![Category result](https://image.prntscr.com/image/IhicfjltSUiqpjUYiwqN1Q.png)

I do not know how to test more, I tried with the attribute `url_key` of the product and it worked, only in the category I can not search. Can anyone help me solve this?

**Comment by rbayet** [comment]
Hi @leonardovilarinho,

Can you provide us the version of Magento 2 and Elasticsuite versions you are using ?
Can you also show us screenshots related to "with product the same query works" ?

Finally, which kind of search are you trying to perform ? And with what goal in the context of the module ? To tweak the autocomplete category search ?

Anyway, with a `term` query, you're looking for an exact match, which cannot work for a `text` field which is analyzed : on the product index, we have dedicated `attribute.untouched` subfields (un-analyzed `keyword`) for the layer navigation purpose.
If you use a `query_string` query, you should get matches, but not necessarily only those that you are looking for.

Regards,

**Comment by leonardovilarinho** [comment]
Hello,

My goal is to find the product or category from the URL.

For example, going to `site.com/product-a` Elastic would have to return me the product with url_key equal to `product-a`.

When accessing `site.com/category-a` Elastic should return me to the category with url_path equal to `category-a`.

But as you can see in the prints, I can't search the category by `url_path` attribute.

I have a category with `url_oath` equal to `pecas`, but when I look for Elastic it doesn't return me.


An example of how I get a product by URL:
![Product](https://image.prntscr.com/image/d2mIK7wiScOaqgfDSQd8_A.png)


Now here is the category index, I have the category with url `pecas`:
![Category](https://image.prntscr.com/image/BgyeKaOURbGeu-fWYjvZbg.png)

But when trying to get her Elastic returns nothing to me:
![Not found](https://image.prntscr.com/image/iv5itMY_R0SbSpcNdItqHg.png)


I think it may be some mapping that the module does in Elastic that does not allow the search by category URL.

**Comment by romainruaud** [comment]
Please provide a copy of your index mapping @leonardovilarinho so that we could investigate a bit more.

Regards
