### ISSUE TITLE
Search error 

### ISSUE THREAD

**Issue by vishne0** [Smile-SA/elasticsuite#1511]
When we try to  search using  keywords for example  JBL and press enter  we get t he  desired  result, however  when we try to searc for  say audio we see the products in suggetion but if  we press enter it just shows us blank page and shows  no products
### Preconditions

Magento Version : CE - 2.3.2

ElasticSuite Version :6.0.1

Environment : PRODUCTION

Third party modules :

### Steps to reproduce

1. Search for a keyword for example Audio
2. Press Enter
3. Shows blank page 

### Expected result

1. Should show product listing matching  the  keywords.

### Actual result

1. [Screenshot, logs]
main.INFO: curl -XPOST 'http://localhost:9200/magento2_default_catalog_category/category/_search?pretty=true' -d '{"size":3,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"audio","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"audio","fields":["search^1","search.whitespace^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"audioquest","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"audioquest","fields":["search^1","search.whitespace^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"audio solutions","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"audio solutions","fields":["search^1","search.shingle^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"audio analogue","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"audio analogue","fields":["search^1","search.shingle^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}}}' [] []

![image](https://user-images.githubusercontent.com/24691857/63414025-9a63c600-c418-11e9-9992-4a99349a1410.png)

**Comment by rbayet** [comment]
Hello @vishne0,

What's that thing on the left on your screenshot ?
Is this a redesigned version of the category layer filter or a custom navigation menu ?

Considering your [previous issue](https://github.com/Smile-SA/elasticsuite/issues/1508), I would suggest looking into any third party module which has its own version of `view/frontend/layout/catalog_category_view_type_layered.xml` or `view/frontend/layout/catalogsearch_result_index.xml` and try to disable the module to see if the behavior persists.

Regards,

**Comment by vishne0** [comment]
its not coming through any plugin , these are the categories we have  created from backend.

**Comment by rbayet** [comment]
@vishne0 so is this the category layer filter ?
That is to say the links leads to `/catalogsearch/result/index/?q=[search query]&cat=[category id]` ?

Can you provide the answer (from cerebro for instance) of your raw query ?

Regards,

**Comment by vishne0** [comment]
As you suggested I have looked for the files and below are the results. It doenst look like that there is any third  party module being  used 
/vendor/magento/module-layered-navigation/view/frontend/layout/catalog_category_view_type_layered.xml
/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalog_category_view_type_layered.xml
/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/view/frontend/layout/catalog_category_view_type_layered.xml
/vendor/magento/module-layered-navigation/view/frontend/layout/catalog_category_view_type_layered.xml
/app/code/Magento/LayeredNavigation/view/frontend/layout/catalog_category_view_type_layered.xml
However below are few seems  using third party module 
/app/code/Mageants/AskForPrice/view/frontend/layout/catalogsearch_result_index.xml
/app/design/frontend/Artisticbird/art/Magento_Theme/layout/catalogsearch_result_index.xml
/app/design/frontend/Artisticbird/studio22/Magento_Theme/layout/catalogsearch_result_index.xml
/app/design/frontend/Artisticbird/studio22mobile/Magento_Theme/layout/catalogsearch_result_index.xml
/vendor/magento/module-advanced-search/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-catalog-search/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-directory/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-layered-navigation/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-msrp/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-swatches/view/frontend/layout/catalogsearch_result_index.xml
/vendor/magento/module-wishlist/view/frontend/layout/catalogsearch_result_index.xml
/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml
/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/view/frontend/layout/catalogsearch_result_index.xml
/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/view/frontend/layout/catalogsearch_result_index.xml
This might be an issue ?

**Comment by vishne0** [comment]
catalogsearch/result/?q=audio this what the search url is

**Comment by rbayet** [comment]
> > That is to say the links leads to `/catalogsearch/result/index/?q=[search query]&cat=[category id]` ?

> catalogsearch/result/?q=audio this what the search url is  which shows blank pages

Actually I was speaking about the links under the left column blue menu with category names.

> **However below are few seems  using third party module** 
> - /app/code/Mageants/AskForPrice/view/frontend/layout/catalogsearch_result_index.xml
> - /app/design/frontend/Artisticbird/art/Magento_Theme/layout/catalogsearch_result_index.xml
> - /app/design/frontend/Artisticbird/studio22/Magento_Theme/layout/catalogsearch_result_index.xml
> - /app/design/frontend/Artisticbird/studio22mobile/Magento_Theme/layout/catalogsearch_result_index.xml

Yes, those module and themes layout files might alter the behavior of the search page by altering the specificites of `vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml` considering they will be loaded **after**.
I would advise disabling one after another those module/themes for confirmation.

Regards,

**Comment by rbayet** [comment]
Hello @vishne0,

An additional question : you provided the version of the ElasticSearch server (6.0.1), but which version of `smile/elasticsuite` are you using ?
(`composer show smile/elasticsuite | grep -i versions` or looking into your composer.lock).

Regards,

**Comment by vishne0** [comment]
> Hello @vishne0,
> 
> An additional question : you provided the version of the ElasticSearch server (6.0.1), but which version of `smile/elasticsuite` are you using ?
> (`composer show smile/elasticsuite | grep -i versions` or looking into your composer.lock).
> 
> Regards,

Using 2.8.1

**Comment by vishne0** [comment]
so is this a bug?

**Comment by rbayet** [comment]
@vishne0 No, so far, I haven't been able to reproduce your problem either on 2.8.1 or the latest 2.8.2 release.
I would advise iterating on your theme(s) and module(s) layout files to identify something messing with the layer or the results block as they are configured by `smile/elasticsuite` layout files.

Regards,

**Comment by romainruaud** [comment]
@vishne0 since your issue cannot be reproduced on a raw Magento + ElasticSuite instance, and considering the amount of third party extensions you are having that are altering the search result pages, it's most likely an incompatibility between these extensions and Elasticsuite.

That being said, supporting third party extensions is not part of our community support commitment. You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards
