### ISSUE TITLE
Internal error with GraphQL in magento 2.3.2

### ISSUE THREAD

**Issue by JulienPradet** [Smile-SA/elasticsuite#1513]
Hi!

I'm running into an issue when I try to run a GraphQL query on my new Magento 2.3.2 install. I'm pretty new to GraphQL in general, so I had trouble identifying the root issue. But I'm opening this issue in case you had any clue about what's happening. I'd be happy to help dig further with a few pointers.

### Preconditions
Magento Version : 2.3.2
ElasticSuite Version : 2.8.1
Environment : developer and production 

Third party modules :
* Venia sample data
* smile/module-elasticsuite-cms-search 2.2.3

### Steps to reproduce

1. Install a magento from scratch
2. Add the sample data
3. Send the introspection query to GraphQL

<details>
<summary>Introspection query as curl</summary>
<pre>curl 'http://magento232.local/graphql' -H 'accept: */*' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36' -H 'content-type: application/json' --data-binary '{"operationName":"IntrospectionQuery","variables":{},"query":"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  fields(includeDeprecated: true) {\n    name\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"}' --compressed</pre>
</details>

### Expected result

No errors and the data describing the GraphQL schema.

### Actual result

An error is sent back :

```json
{
	"errors": [{
		"debugMessage": "Config element \"SmileElasticsuiteVirtualCategoryDataVirtualRuleInterface\" is not declared in GraphQL schema",
		"message": "Internal server error",
		"category": "internal",
		"locations": [{
			"line": 12,
			"column": 5
		}],
		"path": ["__schema", "types"]
	}]
}
```

It seems to be related to `Smile\ElasticsuiteVirtualCategory\Api\Data\VirtualRuleInterface` and the fact that VirtualRules are added to the `Magento\Catalog\Api\Data\CategoryInterface` but I couldn't really pin point how to disable it in GraphQL.

Thanks for your help and this great lib :)

**Comment by real34** [comment]
FYI, I can reproduce this issue in 1.8.2 too.

**Comment by real34** [comment]
The issue has been caused by the `virtualCategoryType` locator added as part of https://github.com/Smile-SA/elasticsuite/commit/dfb44ab896c803b2be1f0a17a5e8f6a9a5dbf5f8#diff-dc986573a1fa5d60b8f78f8bfd32a32eR121 (in 2.7.7).

I guess that GraphQL is trying to find a matching type definition when building its schema.

I will try to dig into the GraphQL stack to see if I can suggest a PR, but I don't know it very well so if someone else wants to give a hand: feel free to do so! :smile:
