### ISSUE TITLE
ElasticSuite Category Indexing indexer process unknown error

### ISSUE THREAD

**Issue by jasonmchugh** [Smile-SA/elasticsuite#1519]
Hi,
I upgraded Magento 2.1.8 to 2.2.9.
Did all the setup:upgrade and everything seem normal and working.
But now everytime I reindex I got the same error:
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}

I tried to change the versions to :
elasticsearch/elasticsearch v5.5.0
smile/elasticsuite 2.6.9 
And now it's 
elasticsearch/elasticsearch v6.7.2
smile/elasticsuite 2.6.9 

I'm on Centos 7.6 v 80.0.24
Magento Version : CE 2.2.9
ElasticSuite Version :2.6.9 
Environment : Developer

### Steps to reproduce
1. On every command php bin/magento indexer:reindex
2. I received:
Design Config Grid index has been rebuilt successfully in 00:00:05
Customer Grid index has been rebuilt successfully in 00:01:15
Category Products index has been rebuilt successfully in 00:00:30
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:13
Product EAV index has been rebuilt successfully in 00:00:14
Stock index has been rebuilt successfully in 00:00:08
Product Price index has been rebuilt successfully in 00:00:10
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:42
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:04
3.If i  composer info | grep elastic:
elasticsearch/elasticsearch    v6.7.2    PHP Client for Elasticsearch
smile/elasticsuite   2.6.9     Magento 2 merchandising and search engine built
4. service elasticsearch status:
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-08-28 11:38:50 EDT; 2h 3min ago
     Docs: http://www.elastic.co
  Process: 73487 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 73490 (java)
   CGroup: /system.slice/elasticsearch.service
           └─73490 /bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -X...

Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.index.mapper.MapperServic...49)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.cluster.metadata.MetaData...57)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.cluster.metadata.MetaData...30)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.cluster.service.InternalC...80)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.cluster.service.InternalC...84)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.common.util.concurrent.Pr...31)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at org.elasticsearch.common.util.concurrent.Pr...94)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at java.util.concurrent.ThreadPoolExecutor.run...49)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at java.util.concurrent.ThreadPoolExecutor$Wor...24)
Aug 28 13:42:20 serveur.groupejacobus.com elasticsearch[73490]: at java.lang.Thread.run(Thread.java:748)
Hint: Some lines were ellipsized, use -l to show in full.

Can you help please!!??

**Comment by romainruaud** [comment]
Your Elasticsearch server (not the PHP connector, the server by itself) seems to be still on Elasticsearch 2 when you should have at least an Elasticsearch 5. 

What's the output of `curl localhost:9200` ?

Regards

**Comment by jasonmchugh** [comment]
Hi,
the output is:
{
  "name" : "Kid Nova",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "2cb62E2ZTxGC0ztrcEJTzA",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by romainruaud** [comment]
Okay so you are using an Elasticsearch 2.4.6 which is **not supported** by ElasticSuite 2.6.9

You have to upgrade the Elasticsearch component.

Regards

**Comment by jasonmchugh** [comment]
Thank you Romain, I just want to know what is the best way to do it.
I still have a live Magento using the Elasticsearch, is it possible to update Elasticsearch 2 to Elasticsearch 5 and keeping both site Working on the same server?
Is it better to use the migration tool (https://github.com/elastic/elasticsearch-migration/tree/2.x) or simply install a new one (https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html)?
Thanks!

**Comment by romainruaud** [comment]
I never used the migration tool but from what I can read it seems to be useful in your case.

If your other Magento is using ElasticSuite, you have to ensure he is also using a proper version to deal with Elasticsearch 5. 

Regards
