### ISSUE TITLE
Broken Magento instance produce multiple ES indexes when crons runs

### ISSUE THREAD

**Issue by jburel-clever-age** [Smile-SA/elasticsuite#1520]
Hi,

### Preconditions
Magento Version : EE 2.3.2
ElasticSuite Version : ~2.8.0
Environment : Production

### Steps to reproduce
Your instance must be broken, you can delete some compilated files for example

1. Remove statics files into pub/static/* or generated/*
2. Try an access to the frontend url: an error must be shown (important!)
3. Add Magento cron in system crontab (setup:cron:run and cron:run) every minute, or you can try to run these crons manually

### Expected result
1. Nothing...

### Actual result
1. A catalog_product index is created on ES each time that the Magento crons runs (every minute in my case) :

![image](https://user-images.githubusercontent.com/29145920/63927062-432fa800-ca4d-11e9-8501-955c0c36a68d.png)

Do you have any idea on how to fix that?

Thanks for your help :)

**Comment by romainruaud** [comment]
Might be related with #1086 and the PR #1516 .

Could you check the fix given in the PR for your problem and let us know if it's better ? 

Regards

**Comment by jburel-clever-age** [comment]
Hi @romainruaud,
I'll try it today or next week, I'm not able to test it right now :(
Thanks for this update!

**Comment by romainruaud** [comment]
@jburel-clever-age any news ?
