### ISSUE TITLE
Unable to Edit a Category With Admin Role Restrictions

### ISSUE THREAD

**Issue by paulpartington-cti** [Smile-SA/elasticsuite#1521]
When an admin user that has a role that limits the scope to a particular website attempts to edit a category, an error is shown - `catalog_product index does not exist yet. Make sure everything is reindexed.`

### Preconditions
Magento Version : Magento EE 2.3.0

ElasticSuite Version : 2.8.0

Environment : Production

Third party modules : None that affect search

### Steps to reproduce
1. Create two websites and assign a different root category to each of them
2. Create an administrator role with full permissions but limited to the second website
3. Assign an administrator to the new role
4. Try to edit a category

### Expected result
1. The administrator should only be able to see the category tree associated to their role scope
2. The administrators should be able to edit a category

### Actual result
1. The administrator can see the category tree correctly
2. An error is shown on the category page - `catalog_product index does not exist yet. Make sure everything is reindexed. `

If the administrator role is assigned to the default website, it works as expected.

**Comment by romainruaud** [comment]
@androshchuk can you try reproducing this one please ?

The fix might be then hard to provide, there is probably somewhere in the code a call to `getStores()` or `getStore()` which is getting intercepted by the `Magento\AdminGws` module and that is removing the unauthorized stores for the current admin user.

**Comment by romainruaud** [comment]
@serg6854 please try to reproduce this one with Dima

**Comment by romainruaud** [comment]
@paulpartington-cti can you post a screenshot of your store configuration ? The screen where all the websites and associated store views are listed.

**Comment by romainruaud** [comment]
I close for being never answered, please reopen a new issue with more details if still facing it.
