### ISSUE TITLE
Category product list view empty

### ISSUE THREAD

**Issue by wearetelescopic** [Smile-SA/elasticsuite#1529]
I'm on Magento 2.2.8 with elasticsearch 6.6

The module installed all fine and the search itself seems to work.
However when I go to a category product view page (which also should containt a layered filter navigation) I now get no results. 
I disabled all other thrid party modules, reindexed, cleared cache - nothing works.

I don't really know how to debug this either, how can i see if a category in the elastic search index has products? It looks ok in the admin panel, when I go to a category, i see the full list list products.

but on the front end, [storeview]/[category] just says 'no results', e.g. /en/fabrics

Any ideas where I could have gone wrong or how to debug this?

Thanks!

**Comment by romainruaud** [comment]
First point is, obviously, to check if you have products associated to this category.

Of course also, ensure these products have the value "Catalog" or "Catalog, Search" for the "Visibility" attribute.

If that's not the case, please check that you do not have a layout customization which is changing blocks order, especially the Toolbar like described here : https://github.com/Smile-SA/elasticsuite/wiki/FAQ#i-have-problems-with-the-pagination--sorting
