### ISSUE TITLE
Optimizer preview: 500 error

### ISSUE THREAD

**Issue by androshchuk** [Smile-SA/elasticsuite#1533]
### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.2

Environment : dev

Third party modules : none

### Steps to reproduce

1. Create a new optimizer of constant model, active, available on request type "Category Product View"
2. Input a sensible boost value (for instance 20 %)
3. In the Category Product View fieldset, change "Apply to" to "Selected categories"
4. In Apply to categories select the "Gear" category.
5. In the preview, select Category Product View and select category "Collections".
6. Click "Preview"

### Expected result

Display the boosted product list

### Actual result

500 error. 
1 exception(s):
Exception #0 (LogicException): Field category does not exists in mapping

Exception #0 (LogicException): Field category does not exists in mapping
<pre>#1 Smile\ElasticsuiteCore\Search\Request\Query\Filter\QueryBuilder->create() called at [vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Builder.php:105]
#2 Smile\ElasticsuiteCore\Search\Request\Query\Builder->createFilterQuery() called at [generated/code/Smile/ElasticsuiteCore/Search/Request/Query/Builder/Interceptor.php:37]
#3 Smile\ElasticsuiteCore\Search\Request\Query\Builder\Interceptor->createFilterQuery() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/CategoryQuery.php:81]
#4 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview\CategoryQuery->getCategorySearchQuery() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/RequestBuilder.php:126]
#5 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview\RequestBuilder->getSearchRequestParams() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/ResultsBuilder.php:63]
#6 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview\ResultsBuilder->getPreviewResults() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php:213]
#7 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview->getPreviewResults() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php:148]
#8 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview->getBaseResults() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php:112]
#9 Smile\ElasticsuiteCatalogOptimizer\Model\Optimizer\Preview->getData() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Controller/Adminhtml/Optimizer/Preview.php:93]
#10 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview->execute() called at [generated/code/Smile/ElasticsuiteCatalogOptimizer/Controller/Adminhtml/Optimizer/Preview/Interceptor.php:24]
#11 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#12 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:231]
#13 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#14 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#15 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#16 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#17 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->___callPlugins() called at [generated/code/Smile/ElasticsuiteCatalogOptimizer/Controller/Adminhtml/Optimizer/Preview/Interceptor.php:39]
#19 Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]
#20 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]
#21 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#22 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#25 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:136]
#26 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#27 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#28 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:26]
#30 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:258]
#31 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre>

This happens only  with a category "Collections"

**Comment by romainruaud** [comment]
@serg6854 please have a look on this one with @androshchuk
