### ISSUE TITLE
Filtering Product collection on custom indexed data

### ISSUE THREAD

**Issue by LittleBigDev** [Smile-SA/elasticsuite#1535]
Hello,

I am using the Amasty "[Product Labels](https://marketplace.magento.com/amasty-label.html)" third party module, adding some tags or ribbons above product images based on conditions (like conditions used for your virtual categories).

The goal is to add a custom layered navigation filter, based on external data (not a product attribute). This external data (Product/Label relations) is stored in specific tables and specific index.

I was able to aggregate and add the Product/Label relations into catalog_product ES index via a custom dataSource (I tried multiple structures : imploded label ids, label ids array, "label" nested property...).
Datasource config :
```xml
    <index identifier="catalog_product">
        <type name="product">
            <datasources>
                <datasource name="labels">Vendor\Module\Model\Product\Indexer\Fulltext\Datasource\LabelData</datasource>
            </datasources>
            <mapping>
                <field name="label.label" type="integer" nestedPath="label"/>
            </mapping>
        </type>
    </index>
```
In ES index, mapping under `mappings.product.properties` is :
```json
          "label": {
            "type": "nested",
            "properties": {
              "label": {
                "type": "integer"
              }
            }
          }
```
(this is the last mapping I tried).

I also created and injected a new Filter Type into `\Magento\Catalog\Model\Layer\FilterList::getFilters` with a Plugin. This custom filter type (`Vendor\Module\Model\Layer\Filter\Label`) is supposed to implement `apply()` method, to add new filter(s) into layer's product collection.

This is where I'm stuck. I tried something like this (simplified code) :
```php
    public function apply(RequestInterface $request)
    {
        $labelId = (int)$request->getParam('label');
        $this->getLayer()->getProductCollection()
            ->addFieldToFilter('label', $labelId)
        ;

        $this->getLayer()->getState()->addFilter(
            $this->_createItem('Vente Privée', $labelId)
        );
    
         return $this;
    }
```
Sadly, as soon as I choose a Label filter value on frontend (either category view or search result page) I'm getting an Exception : "Field label does not exists in mapping".
This "label" field is checked against `\Smile\ElasticsuiteCore\Index\Mapping::$fields`. I was not able to find how `Mapping::$fields` is populated. I supposed it was merged configuration data from all `elasticsuite_indices.xml` files, but my mapped `label` custom property is missing.

Obviously, I'm not mastering this topic. I'm pretty sure I'm not stating everything you need to help me. I'm also pretty sure I'm not asking the good questions, but I hope some Elasticsuite expert will get it, and will be able to help me !

Thanks by advance !

**Comment by LittleBigDev** [comment]
Hello @romainruaud, 
Thank you for your answer.

The problem is that when building filter block or when applying the filter, some dependencies rely on an attribute model (Swatches renderer for instance). But the given "field to filter" ('label') is not a product attribute. When these dependencies try to use `\Magento\Catalog\Model\Layer\FilterFilterInterface::getAttributeModel()` result, it gives an error and blank display (because result is `null`).
I was able to fix the issue for filter blocks creation (injecting a custom block class in the filters pool) but not for the `apply()` part ; I had to dig kinda deeply, and came to conclusion that I would have to customize and/or override too many dependencies for an elegant solution.

So here I came asking for advice.

**Comment by romainruaud** [comment]
Hi @LittleBigDev 

Hi @davidsiemers

I'm afraid we can't go further than what we can provide as part of our (free) open source support here.

If you feel the need to customize more the extension to fit your project needs, we can provide you commercial support as part of our support policy. If this is something you are interested in, please send us an email directly at romain.ruaud@smile.fr

Best regards

**Comment by andrewsurrey** [comment]
@LittleBigDev did you ever find a sensible solution?

**Comment by LittleBigDev** [comment]
Hello @andrewsurrey ,
It's been a while and I can't remember.
But I know myself good enough to be sure about one thing : if I had found any solution, I would have shared it here.
So, I think we decided to not index external data, and filter our lists another way (somehow).
