### ISSUE TITLE
Is flat catalog still recommended when using Smile elasticsuite and Magento 2.3?

### ISSUE THREAD

**Issue by Tjitse-E** [Smile-SA/elasticsuite#1539]
**Is your question related to a problem? Please describe.**
What is the recommended setting for flat catalog in Magento 2.3.x + Smile Elasticsuite? Magento said in their devdocs that it is no longer best practice to enable flat catalog, due to native elasticsearch. Is the same valid for elasticsuite?

**Additional context**
More info about Magento's statement [here](https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html)

![Using a Flat Catalog | Magento Open Source 2 3 User Guide 2019-09-11 10-44-04](https://user-images.githubusercontent.com/14849044/64682059-1635b900-d481-11e9-9ab9-bee9b2138ac3.png)

**Comment by southerncomputer** [comment]
to piggyback - what about eav indexer? is this required for elasticsuite?
![image](https://user-images.githubusercontent.com/6178967/64690097-9ba77200-d45d-11e9-9f20-db0584deb20c.png)

**Comment by romainruaud** [comment]
@Tjitse-E I would say that we have no special recommendations about using or not the flat catalog. Zero parts of ElasticSuite is assuming that the flat catalog is active or not, so feel free to follow the Magento recommendation and to stop using it.

@southerncomputer  I'd say that EAV indexer is probably not necessary to have Elasticsuite running properly : the data built by this index is used to draw the layered navigation filters, which is done by retrieving data from the Elasticsearch index when you are using ElasticSuite.
