### ISSUE TITLE
Optimizer/Rule conditions > Invalid security or form key. Please refresh the page.

### ISSUE THREAD

**Issue by ivanvart** [Smile-SA/elasticsuite#1541]
Creating new optimizer settings in the seccition "Apply to products" any options that you select get the messages "Invalid security or form key. Please refresh the page."

### Preconditions

Magento Version : 2.3.2

ElasticSuite Version : from composer   "branch-alias" : { "dev-master" : "2.9.x-dev"  }

Environment : Developer 

Third party modules :

### Steps to reproduce

1. Go Optimizer
2. Add New
3. Try to select any option in the section Apply to products

### Expected result

1. dont get error

### Actual result

1. [Screenshot, logs]

**Comment by androshchuk** [comment]
Hello, @ivanvart 
Unfortunately, I couldn't reproduce the bug.
Please provide more information (steps to reproduce, screenshots and logs)

Regards

**Comment by fbkaasa** [comment]
Unfortunately we see this bug in one of our environments as well. As soon as you try and add attributes from the drop-down list you are thrown to the dashboard with the error message "Invalid security or form key. Please refresh the page."
