### ISSUE TITLE
Layered Navigation Filterable Attributes and Optimiser

### ISSUE THREAD

**Issue by nuzil** [Smile-SA/elasticsuite#1544]
## Problem
We have Optimiser rule that uses one of attributes as criteria to put some product on top on category view page. 
Then Admin set this attribute to "Use in Layered Navigation: NO". 
Reindex everything

Products are not anymore displayed on a category page on a frontend and also user see an error on Category Edit page in the backend

Problem is caused by this attribute is not indexed anymore, but Optimiser is still trying to load it from there

## Preferred Solution
Attribute even with "Use in Layered Navigation: NO" have to be possible to use in Optimiser rules.

**Comment by romainruaud** [comment]
> Attribute even with "Use in Layered Navigation: NO" have to be possible to use in Optimiser rules.

It's possible actually. It's a bit hacky, but setting such attributes as "is used for promo rules : yes" allow to use them in optimizers.

Probably we could add another boolean flag that is dedicated to enable/disable an attribute for being used by optimizers.

**Comment by romainruaud** [comment]
I close this one since I answered the question, even if it's a bit hacky approach to do this.
