### ISSUE TITLE
Product sorter (and optimizer ?) preview : product is not correctly re-ordered

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/elasticsuite#1546]
On a category affected by an optimizer, with several products already positioned at the first 3 slots and 2 of them blacklisted, an initially "automatically" sorted product which is manually sorted is not re-positioned at its original position when it is switch back to "automatic sort".

### Preconditions

Magento Version : CE 2.3.2

ElasticSuite Version : 2.8-x (reproduced on http://demo.magento-elastic-suite.io)

Environment : Developer and Production 

Third party modules : N/A

### Steps to reproduce

1. On a Luma demo site with Elasticsuite, create and enable an optimizer with the following characteristics : Request Type=ALL, All search terms, All categories, Boost value=20%, Apply to Products = If ALL those conditions are TRUE : Attribute Set is Bag
2. Make sure this is the only enabled optimizer
3. In admin, go to the category "Gear"
4. Notice that bags are the first listed products
5. If needed, clear any product position or blacklist status and save the category
6. Switch successively on "Manual Sort" for the first 3 products (it should be "Push It Messenger Bag", "Overnight Duffle", "Driven Backpack") so they are manually sorted but without changing their actual position
7. Blacklist the 1st and the 3rd product, save the category
8. When the preview is reloaded, switch on "Manual Sort" the 12th product (last one on the second row). Its position is in 4th place.
9. Switch back that product to "Automatic Sort". It receives its original 12th position.
10. Switch again that product to "Manual Sort" and position it as the 2nd product.
11. Switch back that product to "Automatic Sort"

### Expected result

1. The product should be repositioned as before on its original position, in 12th place.

### Actual result

1. The product is flagged as having "Automatic Sort" but is not repositioned, staying at the 2nd position in the preview list.

![no_repositioning](https://user-images.githubusercontent.com/2353374/65332346-cd87a980-dbbe-11e9-9fa2-6f05b1ba5b59.png)

**Additional information:** 
- so far, I was not able to reproduce the issue when no optimizers are enabled
- the issue seems to be purely related to the preview list re-ordering : when the category is saved with the "Automatically Sorted" at that invalid position, the product is correctly position at its native location when the category edit form / preview list is refreshed.

**Comment by romainruaud** [comment]
@rbayet does this issue still exists ?
