### ISSUE TITLE
product filter for in stock out of stock

### ISSUE THREAD

**Issue by Nightcrowe** [Smile-SA/elasticsuite#1549]
Hello 
maybe this issue already been adressed ( But i do not find it)
Is it possible to filter products as in stock out of stock using any easy way using elasticsuite?

**Comment by romainruaud** [comment]
Hello @Nightcrowe 

do you mean this : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L354

?
