### ISSUE TITLE
'Unable to save Stock Item' error while creating new products.

### ISSUE THREAD

**Issue by apurv-anand** [Smile-SA/elasticsuite#155]
'Unable to save Stock Item' error while creating new products.

Environment: 
M2.1.1
ES: 2.2.1
Ubuntu / Apache / MySQL

Steps:
- Install new Magento 2.1.1 server.
- Create few products (optional) - the products get created.
- Install ES 2.1.1 
- Enable all modules.
- Login to Magento and create new product.

Current: Products cannot be created. Error: 'Unable to save Stock Item' 
Expected: None of the core functionality should be affected by the module. Products should get created.

**Comment by afoucret** [comment]
This one is related to #156.
Once the search engine will be configured correctly everything will be OK.
