### ISSUE TITLE
Can an extension create custom pages that display search results for specific queries?

### ISSUE THREAD

**Issue by volanar** [Smile-SA/elasticsuite#1551]
Can an extension create custom pages that display search results for specific queries? Or does elastic suite not have this feature?
For example, you can create a page ‘Samsung blue mobile phones’. It will look like a regular catalogue page. But product list will return search results by query ‘Samsung blue mobile phones’.

**Comment by romainruaud** [comment]
@volanar you can achieve this with the virtual categories : https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories

Regards
