### ISSUE TITLE
bug in rendex elasticsuite_categories_fulltext 

### ISSUE THREAD

**Issue by capm4** [Smile-SA/elasticsuite#1553]
When is reindex elasticsuite_categories_fulltext for multi store.
There is bug  when create index in elasticsearch.
Because  wrong quary builds to databases.
vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Category/Indexer/Fulltext/Action/Full.php 
method addIsVisibleInStoreFilter  
http://joxi.ru/Q2K1G96cL1pBkr.jpg
So if you have rootCategoryId = 2 
query will be 'e.path LIKE ?', "1/2%"
but if your root Category for next store will be like 264
category from other store will go to select http://joxi.ru/KAxJNlwHZg07Lm.jpg 

I fix this add method addIsVisibleInStoreFilter to select  close '/' after rootCategoryId
$select->where('e.path LIKE ?', "1/{$rootCategoryId}/%");

I didn't test how it works in new elastisuit version/
### Preconditions

Magento Version : 2.2.6

ElasticSuite Version : 2.6.4

Environment :prod

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Seems to be still the case on recent ElasticSuite versions.

@androshchuk @serg6854 can you handle this one ?

regards

**Comment by androshchuk** [comment]
Hello, @capm4.
Thank you for your issue.
Problem was indeed present and we fixed it thanking you.

Regards
