### ISSUE TITLE
Indices duplicates

### ISSUE THREAD

**Issue by yrudiuk** [Smile-SA/elasticsuite#1554]
Elasticsuite creates indices duplicates if not able to load data from the existing index. This causes CPU load, high memory usage and as the result 503 errors.

### Preconditions
Magento Version : 2.2.7 Commerce
ElasticSuite Version : 2.6.4
Environment : production

### Steps to reproduce
Issue happens when elasticsuite can't read data from the elasticsearch index in any way

**Comment by romainruaud** [comment]
@yrudiuk I'm sorry but your issue is no qualified enough.

Can you propose a more detailed scenario so that we'd be able to reproduce this anomaly ?

Best regards
