### ISSUE TITLE
'GenericIndexerHandler could not be converted to string' error while full reindexing.

### ISSUE THREAD

**Issue by apurv-anand** [Smile-SA/elasticsuite#156]
'GenericIndexerHandler could not be converted to string' error while full reindexing.

Error:
Catalog Search indexer process unknown error:
Recoverable Error: Object of class Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler could not be converted to string in /opt/bitnami/apps/magento/htdocs/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandlerFactory.php on line 83

Steps:
-Install M2.1.1
-Install ES 2.2.1
-Install ElasticSearch on remove server: http://<server>/elasticsearch (AWS Bitnami distribution).
-Configure Base Settings: ES Server List: http://<server>/elasticsearch

-Run Reindex: bin/magento index:reindex catalogsearch_fulltext

Current: Throws error: Catalog Search indexer process unknown error:
Recoverable Error: Object of class Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler could not be converted to string in /opt/bitnami/apps/magento/htdocs/vendor/magento/module-catalog-search/Model/Indexer/IndexerHandlerFactory.php on line 83

Expected: Should not throw error and index/reindex the data.

**Comment by afoucret** [comment]
Regarding to the information you sent us by email, your setup is not supported by the module.

ES can be installed on it's own server but:

- The URL should not contains any additional path (/elasticsearch in your setup)
- The authentification is not supported. You should use AWS VPC instead to secure your cluster.

Then your pattern `List: http:///elasticsearch` is not compliant with the required pattern (eg : `es-node1.fqdn:9200, es-node2.fqdn:9200`)

At last bitnami images may not provide required plugin (phonetic).

Here is a documentation about the best way to install the ES Server : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig and how to configure the module https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall
