### ISSUE TITLE
Category links in autocomplete are incorrect due to storeview

### ISSUE THREAD

**Issue by Quazz** [Smile-SA/elasticsuite#1560]
### Preconditions

Magento Version : CE 2.3.2

ElasticSuite Version : 2.8

Environment : Production

Third party modules : Too many to list, though the problem seems unrelated. The problem only occurs for autocomplete. Everything else works normally.

### Steps to reproduce

1. Enable categories autocomplete
2. Go to categories and switch to a storeview
3. Change the name of a child category (Root -> 1st Parent -> 1st Child -> 1st Grandchild) for that storeview only (url_key still same as others)
4. Save the category, reindex, etc
5. Try and search for the Grandchild in the storeview
6. Note that the Child part of the url is incorrect

### Expected result

1. The link to the category works properly

### Actual result

1. The generated URL is incorrect and leads to a 404 page.

This seems to be a bit all over the place, sometimes parts of the url are correct, other times those parts are wrong too.

**Comment by Quazz** [comment]
Thank you for looking into this!

I'll try to implement!

**Comment by romainruaud** [comment]
@Quazz any insights ?

**Comment by Quazz** [comment]
@romainruaud Magento fixed the incorrect storing on their end, thanks to your issue submissions I believe.

https://github.com/magento/magento2/commit/5a9265806c97ecdac7f87728a6fb93b4d59161ba

Though this of course doesn't fix the already stored incorrect values.

**Comment by Quazz** [comment]
Actually, upon testing, it doesn't appear to store the correct url_path still. Ugh.

Perhaps the url can be built using url_key instead?

**Comment by Quazz** [comment]
@romainruaud It seems even for default storeview the values are sometimes incorrectly stored...

**Comment by Quazz** [comment]
> @Quazz any insights ?

In the end, I decided to delete the url_path values for categories; they aren't used in Magento 2.3 anywhere.

I used following query: 

`DELETE FROM catalog_category_entity_varchar WHERE attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'url_path' AND entity_type_id = 3);`

In case someone is looking to do the same.
