### ISSUE TITLE
Filters in custom page with custom layer doens't respect product collection

### ISSUE THREAD

**Issue by sedax90** [Smile-SA/elasticsuite#1562]
I've created a custom controller with a custom layer following this guide:
https://webkul.com/blog/how-to-create-layered-navigation-on-custom-page-in-magento-2/

I've added to my frontend/di.xml some modifications following elasticsuite-catalog module:

```
<type name="Dexanet\Dealer\Block\Navigation">
        <arguments>
            <argument name="filterList" xsi:type="object">categoryFilterList</argument>
        </arguments>
    </type>

   <type name="Dexanet\Dealer\Model\Layer">
        <arguments>
            <argument name="context" xsi:type="object">Magento\CatalogSearch\Model\Layer\Category\Context</argument>
            <argument name="productCollectionFactory" xsi:type="object">Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory</argument>
        </arguments>
    </type>

    <type name="Dexanet\Dealer\Model\Layer">
        <plugin name="createSortOrdersOnPrepareFrontCollection" type="Smile\ElasticsuiteCatalog\Plugin\LayerPlugin"/>
    </type>
```

The page now show correct products besed on the filtered collection defined in layer but products count and filters are wrong.
Do I still have to include something?

**Comment by ionpan** [comment]
+1

**Comment by tschirmer** [comment]
The Collection provider is replaced with a virtual type:
"Magento\Catalog\Model\Layer\Search\ItemCollectionProvider"

This won't act normally, 

It should be loading:
"\Magento\Catalog\Model\Layer\Category\ItemCollectionProvider" when no search options are enabled for that category. I'm having the same problem, but I haven't solved this yet, it'll need a pull request and a module update.

**Comment by Birjitsinh** [comment]
I have same issue in magento 2.3 custom product collection

`<virtualType name="MagentoCoders\Vendor\Model\ResourceModel\Vendor\ProductCollection" type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">vendor_search_container</argument>
        </arguments>
    </virtualType>
    <virtualType name="MagentoCoders\Vendor\Model\ResourceModel\Vendor\ProductCollectionFactory" type="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">MagentoCoders\Vendor\Model\ResourceModel\Vendor\ProductCollection</argument>
        </arguments>
    </virtualType>
    <virtualType name="MagentoCoders\Vendor\Model\Layer\ItemCollectionProvider" type="Magento\CatalogSearch\Model\Layer\Search\ItemCollectionProvider">
        <arguments>
            <argument name="collectionFactory" xsi:type="object">MagentoCoders\Vendor\Model\ResourceModel\Vendor\ProductCollectionFactory</argument>
        </arguments>
    </virtualType>
    <virtualType name="MagentoCoders\Vendor\Model\Layer\Context" type="Magento\Catalog\Model\Layer\Context">
        <arguments>
            <argument name="collectionProvider" xsi:type="object">MagentoCoders\Vendor\Model\Layer\ItemCollectionProvider</argument>
            <argument name="stateKey" xsi:type="object">Magento\CatalogSearch\Model\Layer\Search\StateKey</argument>
            <argument name="collectionFilter" xsi:type="object">Magento\Catalog\Model\Layer\Search\CollectionFilter</argument>
        </arguments>
    </virtualType>
    <virtualType name="MagentoCoders\Vendor\Model\Layer" type="Magento\Catalog\Model\Layer\Search">
        <arguments>
            <argument name="context" xsi:type="object">MagentoCoders\Vendor\Model\Layer\Context</argument>
        </arguments>
    </virtualType>
    <type name="Magento\Catalog\Model\Layer\Resolver">
        <arguments>
            <argument name="layersPool" xsi:type="array">
                <item name="vendor" xsi:type="string">MagentoCoders\Vendor\Model\Layer</item>
            </argument>
        </arguments>
    </type>
    <type name="Magento\Catalog\Model\Layer">
        <plugin name="addVendorFilter" type="MagentoCoders\Vendor\Plugin\Model\LayerPlugin"/>
    </type>`

**Comment by romainruaud** [comment]
Too specific issue and too old, I close.

Regards
