### ISSUE TITLE
When to re-index?

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#1563]
Hi, during the developments process I often change files `elasticsuite_analysis.xml` and `elasticsuite_indices.xml`. Is it required to reindex the Magento after doing so or cleaning cache is enough?

**Comment by rbayet** [comment]
Hello @madonzy,

Sorry about the delay.
Performing a full reindex after a change to `elasticsuite_indices.xml` is required for your changes to be taken into account as it is not possible to update the mapping of a live index.

Considering `elasticsuite_analysis.xml`, you can change *some* settings of a live index, but if you alter the analyzers, which are used both at indexing and search time, then it is a good rule of thumb to also perform a full reindex so your search results are coherent / in par with how you expect your content to have been indexed.

Best regards,

**Comment by romainruaud** [comment]
Closing since answered
