### ISSUE TITLE
Smile_ElasticsuiteAnalytics missing in documentations module enable list

### ISSUE THREAD

**Issue by robin31** [Smile-SA/elasticsuite#1565]
In the documentation page https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall there is a command to enable the Elasticsuite modules. This command is missing the new Smile_ElasticsuiteAnalytics module. As a result the new Search Usage dashboard is missing.

### Preconditions
Install the latest elasticsuite 2.8.x in an already installed Magento 2.3.x environment.

Magento Version : CE & EE

ElasticSuite Version : 2.8.x

Environment : developer & production

Third party modules : None

### Steps to reproduce
1. Install Magento 2.3.x
2. follow https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

### Expected result
1. Smile_ElasticsuiteAnalytics (search dashboard) is working

### Actual result
1. Search Usage dashboard / Smile_ElasticsuiteAnalytics is not enabled

### Issue
The command `bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker` is missing the new `Smile_ElasticsuiteAnalytics`

**Comment by romainruaud** [comment]
Hi @robin31 , you are right.

I updated the wiki page, thank you for noticing this ! 

Regards
