### ISSUE TITLE
If a disabled part with a subset of a search term of an enabled product - search will fail?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#1573]
Say i have a disabled product - out of stock named HEW-W1A52A .. 
and another product named HEW-W1A52A#BGJ - enabled and in stock.

both with mfgpartno of W1A52A#BGJ (searchable).

Elasticsuite will not get a direct hit on search term W1A52A until I delete or rename the disabled part from my catalog. Once i fix the disabled product, one hit matching occurs again..

Any thoughts on why this might be happening? (where in the code that might check for enabled product that could affect elasticsuite search?

**Comment by rbayet** [comment]
Hello @southerncomputer,

I don't see a reason why the disabled product will by its mere lack of presence in the Elasticsearch index but presence in your catalog prevent you from getting hits on the other enabled and in stock product.
Especially if there are no links between the two products.

> Elasticsuite will not get a direct hit on search term W1A52A until I delete or rename the disabled part from my catalog. Once i fix the disabled product, one hit matching occurs again..

Can you clarify the situations (all of them) when you get hits and when you don't ?

Regards,

**Comment by southerncomputer** [comment]
Well I believe the disabled product was in elasticsuite index..

When I say direct hit I mean the option to redirect to product on single match. This fails when the disabled product and enabled product are both present.

Which makes me wonder what happens when a disabled product and enabled product both hit on a search - is the disabled product considered still valid for search in elasticsuite or in magento code itself.

If i changed the disabled part's sku and mfgpartno and the indexer updates elasticsuite, the problem goes away!

**Comment by rbayet** [comment]
> Well I believe the disabled product was in elasticsuite index..
> 
> When I say direct hit I mean the option to redirect to product on single match. This fails when the disabled product and enabled product are both present.
> 

Ah, ok, it makes more sense now.
So when the redirect DOES NOT happen, how many search results are displayed in the search results page ? 
One or two ?

> Which makes me wonder what happens when a disabled product and enabled product both hit on a search - is the disabled product considered still valid for search in elasticsuite or in magento code itself.
> 
Well it all depends on your definition of disabled.
For you is it only out of stock ? And do you show out of stock products in the catalog ?

Regards,

**Comment by southerncomputer** [comment]
So when the redirect DOES NOT happen, how many search results are displayed in the search results page ?
One or two ? It falls back to a spellchecked search that returns more than 1 listing.. not exactly what a customer expects when they put in perfect match part number (SKU)..

My definition of disabled is catalog_product_entity_int.STATUS=2 - which is stored in index of elasticsuite - this product may be out of stock but we show out of stock products anyway. 

But I wonder if it is a combination of status=2 in magento? 

Does elasticsuite and/or Magento_catalog filter OUT on status=2?

`| attribute_id | entity_type_id | attribute_code | attribute_model | backend_model | backend_type | backend_table | frontend_model | frontend_input | frontend_label | frontend_class | source_model                                          | is_required | is_user_defined | default_value | is_unique | note | etilize_attribute_id |
+--------------+----------------+----------------+-----------------+---------------+--------------+---------------+----------------+----------------+----------------+----------------+-------------------------------------------------------+-------------+-----------------+---------------+-----------+------+----------------------+
|           97 |              4 | status         | NULL            | NULL          | int          | NULL          | NULL           | select         | Enable Product | NULL           | Magento\Catalog\Model\Product\Attribute\Source\Status |           0 |               0 | 1             |         0 | NULL |                 NULL |
`

**Comment by rbayet** [comment]
Disabled products are not indexed in Elasticsuite.

They are filtered out at indexing time when they are absent of the 'catalog_category_product_index' table, see `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Action\Full::getSearchableProducts` and `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Action\Full::getCategoryProductIndexTable`.

Out of stock products are always indexed in Elasticsuite.
But Elasticsuite respects and apply the `Stores > Configuration > Catalog > Inventory > Display Out of Stock Products` settings.
It is done by `\Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\Stock`, while `\Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\VisibleInSearch` filters out products according to their visibility.

So, true, there is no query time filtering out of products indexed into Elasticsuite with status=2 because that should not happen in the first place.
I haven't also tested what happens if one circumvents the Magento API and manage to switch in the MySQL DB only the product status to 2 while the product is still present in ES.

By the way, which version of Magento 2 and Elasticsuite are we talking about ?

Regards,

**Comment by southerncomputer** [comment]
But what happens when status=2 disabled on mysql db and status=1 in elasticsuite?

does the mview partial indexer then delete the part from elasticsuite?

I'm using 2.3.2 with 2.8 elasticsuite ..

**Comment by rbayet** [comment]
Hello @southerncomputer,

Yes, it status is changed to 2 in the DB, the mview indexer gets notified, that's the native behavior, see vendor/magento/module-catalog-search/etc/mview.xml : 
```
<view id="catalogsearch_fulltext" class="\Magento\CatalogSearch\Model\Indexer\Mview\Action" group="indexer">
        <subscriptions>
            <table name="catalog_product_entity" entity_column="entity_id" />
            <table name="catalog_product_entity_int" entity_column="entity_id" />
            [...]
        </subscriptions>
    </view>
```

So the product is reindexed, and Elasticsuite deletes the pre-existing documents before reindexing, 

See \Magento\CatalogSearch\Model\Indexer\Fulltext :
```
   /**
     * Execute materialization on ids entities
     *
     * @param int[] $entityIds
     * @return void
     * @throws \InvalidArgumentException
     */
    public function execute($entityIds)
    {
        foreach ($this->dimensionProvider->getIterator() as $dimension) {
            $this->executeByDimensions($dimension, new \ArrayIterator($entityIds));
        }
    }

    /**
     * @inheritdoc
     *
     * @throws \InvalidArgumentException
     */
    public function executeByDimensions(array $dimensions, \Traversable $entityIds = null)
    {
        if (count($dimensions) > 1 || !isset($dimensions[StoreDimensionProvider::DIMENSION_NAME])) {
            [...]
        }
        $storeId = $dimensions[StoreDimensionProvider::DIMENSION_NAME]->getValue();
        $saveHandler = $this->indexerHandlerFactory->create([
            'data' => $this->data
        ]);

        if (null === $entityIds) {
            [...]
        } else {
            // internal implementation works only with array
            $entityIds = iterator_to_array($entityIds);
            $productIds = array_unique(
                array_merge($entityIds, $this->fulltextResource->getRelationsByChild($entityIds))
            );
            if ($saveHandler->isAvailable($dimensions)) {
                $saveHandler->deleteIndex($dimensions, new \ArrayIterator($productIds));
                $saveHandler->saveIndex($dimensions, $this->fullAction->rebuildStoreIndex($storeId, $productIds));
            }
        }
    }
```

and \Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler :
```
    /**
     * {@inheritDoc}
     */
    public function deleteIndex($dimensions, \Traversable $documents)
    {
        foreach ($dimensions as $dimension) {
            $storeId   = $dimension->getValue();

            if ($this->indexOperation->indexExists($this->indexName, $storeId)) {
                $index     = [...]
                $type      = [...]
                $batchSize = [...]

                foreach ($this->batch->getItems($documents, $batchSize) as $batchDocuments) {
                    $bulk = $this->indexOperation->createBulk()->deleteDocuments($index, $type, $batchDocuments);
                    $this->indexOperation->executeBulk($bulk);
                }

                $this->indexOperation->refreshIndex($index);
            }
        }

        return $this;
    }
```

Regards,

**Comment by southerncomputer** [comment]
yeah will all cron indexers ran - and up to date. I have a status=2 (disabled) in mysql DB and status=1 in elasticsuite index.. That is odd! I will have to run tests to see why they are in a disconnect!

**Comment by rbayet** [comment]
If none of the indexers are locked and you know the crons run correctly without error (and your indexers are indeed in "Update by Schedule") then look under the hood to see what happens when you manually change a status directly in DB : 
- are the changelog table correctly updated ?
- are those DB triggers still there ?

Good hunting.

**Comment by romainruaud** [comment]
@southerncomputer did you figure out what was happening ?
