### ISSUE TITLE
Attribute with ID: "virtual_rule" does not exist

### ISSUE THREAD

**Issue by rbostan** [Smile-SA/elasticsuite#1575]
### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : ~2.6.0

Environment : Production

Third party modules :

### Steps to reproduce

1. Install extension
2. run setup:upgrade

### Expected result

1. Working normally

### Actual result

1. Attribute with ID: "virtual_rule" does not exist

**Comment by androshchuk** [comment]
Hello @rbostan 
I checked this issue with Magento 2.2.3 CE and ElasticSuite ~2.6.0 (I checked with 2.6.0 and 2.6.9)
Everything is fine for me. 
setup:upgrade was executed without errors and attribute "virtual_rule" was created in the database.

Could you give me more information about your steps to reproduce the issue.

Regards

**Comment by rbostan** [comment]
Hello,
I tried many times with different combinations with (production-developer mode, upgraded magento to 2.2.8) no chance.

Usual way, i've run `composer require smile/elasticsuite ~2.6.0` without errors.
But when i tried to run `setup:upgrade`still giving `Attribute with ID: "virtual_rule" does not exist` at `Module 'Smile_ElasticsuiteVirtualCategory':
Upgrading data..`step

**Comment by rbostan** [comment]
Upss, my bad. There was some old records about this module in setup_module table. deleted these entries and tried reinstall, everything worked fine. closing.
