### ISSUE TITLE
Backend virtual category slow loading

### ISSUE THREAD

**Issue by masb74** [Smile-SA/elasticsuite#1576]
In Magento 2.3.2 I created some virtual category, now it takes a long time to load the category in backend if I need to open and modify. Is there a cache to activate?

**Comment by rbayet** [comment]
Hello @masb74,

How many products do appear in the merchandiser preview screen ?
How many products in total would you say are targeted by your virtual rule ?

Regards,

**Comment by masb74** [comment]
hello @rbayet it depends by the category, but we have about 150/200 products each virtual category. I  created about 50 virtual categories, but I need to create other 150 more. It seems that the module send an ajax call that takes 20 minutes to be completed
thanks a lot

**Comment by rbayet** [comment]
OK, by "some", I thought you meant "a few" :)

If your existing virtual categories are arranged into a tree (children of each other) and you do plan to add 150 more such virtual categories, I'd like to warn you about the implication and performance issues that might appear.
Please refer to this recent [comment of mine](https://github.com/Smile-SA/elasticsuite/issues/1561#issuecomment-543085410) in another issue, and [Romain's detailled explanation](https://github.com/Smile-SA/elasticsuite/issues/1244#issuecomment-460552991).

That being said, 20 minutes for the (I'm just taking a guess) the visual merchandiser to generate its preview, that's a bit steep unless your categories are indeed arranged in a subtree, that your rules use categories conditions, and your Elasticsearch server a bit underperforming ...

Could you confirm the incriminated ajax URL ?
Have your tried profiling or APM tools to determine where most of the 20 minutes is spent (by that I mean in PHP or MySQL or waiting for Elasticsearch) ?

Regards
