### ISSUE TITLE
How sorting products in categories is working ?

### ISSUE THREAD

**Issue by vahir2016** [Smile-SA/elasticsuite#1579]
Bonjour, 

Je travaille sur un projet qui va charger une collection de produits à partir d'une catégorie et on a remarqué que le tri disponible dans l'admin n'était pas appliqué. 
J'ai donc appliqué sur la collection le tri tel qu'il devrait être dans l'admin mais je m'y prends peut être de la mauvaise façon ? 

J'ai vu que la fonctionnalité native de tri par position avait été remplacée par votre module.

La position provenant de la table "catalog_category_product" ne semble plus être mise à jour à partir du drag and drop. J'ai aussi remarqué qu'il fallait que je réindex pour que la position soit transmise dans la table "catalog_category_product_index".

J'ai aussi remarqué la présence d'une table "smile_virtualcategory_catalog_category_product_position" qui semble contenir aussi la position.

Pouvez-vous m'expliquer un peu plus dans le détail le fonctionnement ? 

Voici ce qui a été fait :

```
 public function getLoadedProductCollectionByCategoryId($categoryId, $rand = false)
    {
        $category = $this->categoryFactory->create()->load($categoryId);
        $collection = $this->_productCollectionFactory->create();
        $collection->addAttributeToSelect('*');
        $collection->addCategoryFilter($category);
        $collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
        $collection->addAttributeToFilter(
            'status',
            \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED
        );

        if ($rand) {
            $collection->getSelect()->order('rand()');
        } else {
            $categorySortBy = $category->getDefaultSortBy() ?: $this->_catalogConfig->getProductListDefaultSortBy(
                $this->_storeManager->getStore()->getId()
            );

            switch ($categorySortBy) {
                case 'name' :
                    $collection->setOrder($categorySortBy, 'ASC');
                    break;
                case 'position' :
                    $collection->setOrder($categorySortBy, 'DESC');
                    break;
                case null:
                    break;
                default:
                    $collection->setOrder($categorySortBy);
            }
        }

        return $collection;
    }
```
Merci d'avance, 

Bonne journée,

Cordialement Valentin.

---

Hello,

I am working on a project that will load a collection of products from one category and we noticed that the sorting available in the admin was not applied.
So I applied on the collection the sort as it should be in the admin but I take it can be the wrong way?

I saw that the native feature of sorting by position had been replaced by your module.

The position from the "catalog_category_product" table no longer appears to be updated from the drag and drop. I also noticed that I had to reindex for the position to be passed to the "catalog_category_product_index" table.

I also noticed the presence of a table "smile_virtualcategory_catalog_category_product_position" which also seems to contain the position.

Can you explain to me a little more in detail the operation?

Thank you in advance,

Have a good day,

Sincerely Valentin.

**Comment by rbayet** [comment]
Hello @vahir2016,

**I / How to sort by category position a Elasticsuite fulltext collection**

Elasticsuite indexes a product's category relation and position in the following form in the index ;
```
"category":[
   {
      "category_id":2,
      "is_virtual":"false"
   },
   {
      "category_id":3,
      "is_parent":true,
      "is_virtual":"false",
      "name":"Gear"
   },
   {
      "category_id":4,
      "is_parent":true,
      "is_virtual":"false",
      "position":2,
      "name":"Bags"
   }
]
```
=> the product is visible in categories 2 (root), 3/Gear and 4/`Gear>Bags` with a manual position (2) on that last category.
When on that category, to sort by position, the request contains a sort instruction "sort by category.position where category.category_id = 4".

This sort instruction is built with the help of the `\Smile\ElasticsuiteCatalog\Plugin\LayerPlugin` plugin : 
```
    private function setSortParams(
        \Magento\Catalog\Model\Layer $layer,
        \Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection $collection
    ) {
        $searchQuery = $this->queryFactory->get();

        if (!$searchQuery->getQueryText() && $layer->getCurrentCategory()) {
            $categoryId = $layer->getCurrentCategory()->getId();
            $sortFilter = ['category.category_id' => $categoryId];
            $collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);
```
(see \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::addSortFilterParameters).

This ties in with the following lines of `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareSortOrders` method (executed right before sending the request) :  
```
        foreach ($this->_orders as $attribute => $direction) {
            $sortParams = ['direction' => $direction];
            $sortField  = $this->mapFieldName($attribute);

            if ($useProductuctLimitation && isset($this->_productLimitationFilters['sortParams'][$attribute])) {
                $sortField  = $this->_productLimitationFilters['sortParams'][$attribute]['sortField'];
                $sortParams = array_merge($sortParams, $this->_productLimitationFilters['sortParams'][$attribute]);
          } [...]
          $sortOrders[$sortField] = $sortParams;
```

**Conclusion** try adding the following before your switch/case.
```
            $sortFilter = ['category.category_id' => $categoryId];
            $collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);
```

**II / Where are the product positions actually used by Elasticsuite ?**

As long as `smile/module-elasticsuite-virtual-category` is **enabled**, you benefit from the virtual categories feature **and** our "drag and drop" visual merchandiser (which works on both standard and virtual categories).
Products positions (and blacklist status) are then indeed **no longer written to `catalog_category_product`** but in the (ill-named) dedicated table **`smile_virtualcategory_catalog_category_product_position`.**

If `smile/module-elasticsuite-virtual-category` is **enabled**
At indexing time, the resource model `Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` provides products category data (category / product association **and** products position) by relying on that storage table to `\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData`.

If `smile/module-elasticsuite-virtual-category` is **disabled**, `\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData` used its default resource model `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData` which loads the products positions from the default category/product index table (see `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\CategoryData::getCategoryProductSelect`).

Hopes this clarifies thing.

Regards,

**Comment by vahir2016** [comment]
Hello, 

Thanks you a lot for the answer. Unfortunately I have to deal with urgent tickets on my project but I will check for your answer as soon as possible.

**Comment by ivankristic** [comment]
Hey @rbayet 

thank you for this explanation, it helped a lot during debugging.

Could you please kindly provide the same for before indexing, ie flow of request when is sent to elastic during indexing, in relation to products positions.

We have a problem where we have few virtual categories seemingly identical (by comparing data in db). And we get **three** different kind of product positioning - valid one and two invalid.
After reading this and debugging, it turned out we actually get only get **two** positioning - valid - per position and **invalid - per entity id**
We had unfortunate bloody coincidence that made it look like there was 3.

Anyhow, we spent 3 days on this already, and really could use a guiding hand.
Also, smne might find it helpful, just like we did find this.

Thanks.
BR
