### ISSUE TITLE
Layout Categories facettes 

### ISSUE THREAD

**Issue by FlorentGuilbard** [Smile-SA/elasticsuite#158]
Hi, 
I found something strange on the categories level 2 ou 3. 
The categories facettes are very confusing because they use multiple select. It disturbs the user
Can you change the layout for all the categories level ? 
Thank you very much.

**Comment by afoucret** [comment]
PR #165 will fix this one.

**Comment by afoucret** [comment]
PR #165 is merged.
Will be part of 2.3.0 release.
