### ISSUE TITLE
Have the elasticsuite tracker hit return the empty HTTP/200 response to the client, asynchronously performing the recording of the hit, to improve performance

### ISSUE THREAD

**Issue by dufrygrant** [Smile-SA/elasticsuite#1580]
We are currently using the Elasticsuite product on a Magento 2.2.x site.

Each page is performing a hit to the h.png file (in reality, the tracker URL), but this ordinarily takes ~1.5 seconds to return the empty HTTP/200 response to the user.

Can this in future be refactored to return the HTTP/200 response to the user 'early' (ie not synchronously waiting for the recording of the hit with ElasticSearch to return successfully, unless the product is in some sort of debug mode to deliberately force the current behaviour)?

The issue is that the user's browser is needing to wait for the infrastructure backend when it does not need to (ie no meaningful data is being provided back to the client).

Example hit:
https://bengaluru.websitename.com/en/elasticsuite/tracker/hit/image/h.png?page[store_id]=92&page[type][identifier]=brandboutique_brand_index&page[type][label]=&page[product_list][page_count]=1&page[product_list][product_count]=6&page[product_list][current_page]=1&page[product_list][sort_order]=position&page[product_list][sort_direction]=asc&page[product_list][display_mode]=grid&session[uid]=xxxxxxx-31b8-9b4f-f08e-b54438ca63a1&session[vid]=xxxxxx-1802-0398-e5b3-d82be00ca14c&page[site]=bengaluru.websitename.com&page[url]=%2Fen%2Fbrands%2Fbacardi&page[title]=Bacardi%20%7C%20Duty%20Free%20Bengaluru%20Airport%20Shops&page[referrer][domain]=bengaluru.websitename.com&page[referrer][page]=%2Fen%2Fbrands%2Fabsolut&page[resolution][x]=1920&page[resolution][y]=1160

**Comment by southerncomputer** [comment]
might be your backend is congested.. I'm only seeing avg 80ms response!

![image](https://user-images.githubusercontent.com/6178967/67024520-8c59bb00-f0d2-11e9-9723-5ad9ac99732f.png)

**Comment by rbayet** [comment]
Hello @dufrygrant,

@southerncomputer points something I thought about yesterday : are your crons running correctly ?

There may be a situation where the events are stacking into the dedicated DB `elasticsuite_tracker_log_event` table without being flushed regularly into the Elasticsearch dedicated indices.

Regards,

**Comment by dufrygrant** [comment]
Which one would be doing the flushing, specifically?

Neither the elasticsuite_categories_fulltext or the elasticsuite_thesaurus cron jobs (both of which are running) flush the table in question, it seems (both run, no size change).

(That table's currently 3.8Gb in size in one of our divisions)

**Comment by romainruaud** [comment]
This cronjob should empty the table regularly : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-tracker/etc/crontab.xml#L20

But can you please give us the detailed version of ElasticSuite you are using ?

**Comment by dufrygrant** [comment]
(Sorry for the deleted message; I'm running that now and will let you know)

**Comment by southerncomputer** [comment]
one thing you can do is wrap the sendtag calling function in a delay setTimeout to push it back after pageload to make it appear less blocking..

` setTimeout( function(){ smileTracker.sendTag();},10000);
`
