### ISSUE TITLE
Hide Magento Default Product List on Category Pages

### ISSUE THREAD

**Issue by KholdenSP** [Smile-SA/elasticsuite#1587]
**Is your feature request related to a problem? Please describe.**
In the sorting of Magento product on a particular category, the product list is shown both from Smile and Magento Default. The SORTING appears to be controlled by Smile. This creates confusion when some may go in and attempt to sort by the Magento Default list. 

**Describe the solution you'd like**
Hide the Magento sorting list, only showing Smile's sort list. Also having the option to view the images or a simple text list of product to help collapse the view. 

**Describe alternatives you've considered**
Simply advising others on which list to use, but the top one is somewhat useless from Sorting. 

**Additional context**
![image](https://user-images.githubusercontent.com/53538134/67026903-84435080-f0bd-11e9-9885-b48553b12598.png)

**Comment by rbayet** [comment]
Hello @KholdenSP,

Such a visual merchandiser (the upper part of your screenshot) is not supposed to show up when using Magento 2 + Elasticsuite.
The module takes care of hiding the "Position" column of the native Products grid/dynamic rows component which we keep visible for the purpose of letting the merchant add/remove products (for non-virtual categories).

Here what it is supposed to look like :
![category_edit_merchandiser](https://user-images.githubusercontent.com/2353374/67157567-12257280-f32e-11e9-9b48-8d9afd0f1169.png)

I would say this might be a weird bug or a collision with a third party extension/module.
Could you fill out a standard Issue/Bug report and provide us with the details of your installation ?

Regards,
