### ISSUE TITLE
Request for Better Optimizer Configuration Options

### ISSUE THREAD

**Issue by KholdenSP** [Smile-SA/elasticsuite#1592]
**Is your feature request related to a problem? Please describe.**
This is a feature request to be able to work more efficiently against several search terms that need optimizers. It's difficult to have to create several optimizers for a single search term or set of search terms.

**Describe the solution you'd like**
Offer either a "Duplicate Optimizer" option to avoid selecting multiple settings that are the same for each optimizer, or an advanced Boost formula to work within a specific term or set of terms.

ie, 
Boost "100" where Attribute is X
**AND** Boost "-50" where Attribute is Y

Perhaps something like the mockup below?

No other alternatives considered. 

![image](https://user-images.githubusercontent.com/53538134/67502909-88321e00-f63b-11e9-8eb0-ac660ec23f20.png)

**Comment by romainruaud** [comment]
Hi @KholdenSP 

Technically speaking, it would not be easy to have several rules with different weights inside an unique optimizer.

But having a button "Duplicate Optimizer" could be a quick-win.

**Comment by romainruaud** [comment]
The "Duplicate Optimizer" has been implemented in 2.9.0

I don't think we'll go further on this topic.

Regards
