### ISSUE TITLE
Indexes doesn't delete

### ISSUE THREAD

**Issue by capm4** [Smile-SA/elasticsuite#1606]
Old indexes doesn't delete
--
### Preconditions

As we no. When full reindex start for catalogsearch_fulltext. Elastic stay to listing old index, and create new. When new index is created elastic begin to listing new and delete old. But while new index is create and some problem happened and we got exeption, indexer that was created doesn't delete. So if you have huge number with product , and have to do reindex once 1-2 week, after 3-4 month you will have many unused index.  
I thing there must be some cron job that will clean old index.

Magento Version :
2.2.6

ElasticSuite Version :
2.4.0

Environment :
Developer and Production

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by rbayet** [comment]
Hello @capm4,

I don't think it's a good idea to add a cronjob that would in essence validate inaction towards indexing or architecture problems by removing traces of the errors.
I understand that having extra unused and opened indices might put a load on the architecture and accelerate/aggravate the situation.

I would favour a "warning" cronjob that would periodically scan for indices without an alias (hence inactive) and a name indicative of a creation in the past (so as not to warn about a new index being created).
Not automatically removing those indices, it would possibly let clues in place for a sysadmin to investigate.

I'll let @romainruaud voice his opinion, but feel free to push us a PR anyway.

Regards,

**Comment by romainruaud** [comment]
I do agree, but I'm not sure such a warning signal should be put inside the Magento Back-Office : people reading it might not be able to proceed proper actions.

Maybe we could add a screen into the Back-Office, something like "Indices status" listing all the "managed by ElasticSuite" indices with status : 

- used
- rebuilding
- ghost index (in case of failure during previous indexing)

And a button to allow deleting ghost indices from the Back Office.

**Comment by romainruaud** [comment]
@androshchuk can you try to work on this new feature under support of @rbayet ? 

It will be a new Back-Office screen, with a proper menu entry. 

This should display a list of actually existing Elasticsearch indices.

For each index, we should be able to display : 

- index name
- alias
- number of documents
- index size
- (and if possible, to be able to expand the index mapping, this one is a nice to have).
- Index state (see below for details).
- and a Delete button but only for "Ghost" indices.

Each index can have several states : 

- **Live** if the index is actually used by the application (if it has an alias, it's supposed to be live)
- **Rebuilding** if the index does not have any alias (and the index process is flagged as running), it's probably that the index is being rebuilt.
- **Ghost** if the index does not have any alias but a more recent index is live (according to the fact they are horodated), or maybe if the index has no alias and is horodated far away (more than 2 days ?) in the past.

The Delete button must show a confirmation and a warning message to the user. We also have to ensure that this does not open a door to delete indices that are not "ghosts".

Regards

**Comment by romainruaud** [comment]
I'd like this feature to be put into the ElasticsuiteCore module, and you'll might have to add some methods (Eg : to get all indices) to this class : https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-core/Client/Client.php

Let's go :)

**Comment by vpashovski** [comment]
Hi, can you please make sure that the button for deleting ghost indices from the Back Office is deleting only indices used from current Magento instance - maybe comparing with indices prefix.
We had module with similar functionality that deleted all indices on the elastic server that affected other sites.
Thanks :)

**Comment by romainruaud** [comment]
yes @vpashovski it's done like this :)

I'll review and merge this feature probably next week.

Regards

**Comment by southerncomputer** [comment]
@romainruaud  you may need to add an unlock index, say if disk space gets too low,elasticsearch will prevent an index from deletion by locking it! Took me a few hours to work that not-so-obvious issue out!

**Comment by romainruaud** [comment]
This feature has been added into master branch and is scheduled for next release 2.9.0
