### ISSUE TITLE
What is the best optimisation for lots of synonyms

### ISSUE THREAD

**Issue by jaybouvet** [Smile-SA/elasticsuite#1610]
Hi !

We're having a lot of issue with ElasticSuite on Magento Cloud 2.3.3. For some reason ElasticSearch keeps crashing, which is currently being investigated by Magento's team.

We know that we have a lot of synonyms on the website, and I wondering if this isn't the root cause of the issue.

We have 80 thesaurus, all synonyms. Each thesaurus is for a different term : "Fridge", "Oven", "Drier", "Dishwasher", and so one.
For each thesaurus, we have a lot of synoyms per thesaurus, but just has one term. Sometimes over 100 synonyms.

What would be the best way to organize all this data ?

Here's a screenshot, to make all this clearer
<img width="1666" alt="Capture d’écran 2019-11-06 à 13 18 18" src="https://user-images.githubusercontent.com/50889866/68326025-a74b9980-0098-11ea-8705-eebf335505e4.png">

Thanks !

**Comment by rbayet** [comment]
Hello @jaybouvet,

Looking at your screenshot, I have a question : have those synonyms lists been established by observing visitor data and confirming that each term didn't in fact returned any data ?
Or are those synonyms lists a sort of "migrated data" from another platform/search engine configuration ?

Not that I want to avoid answering the initial question, but to me, at least some of those synonyms are redundant with the fuzzy search/spellchecking ability of Elasticsuite and/or the phonetic search.
To me, for instance, at least half of your "cuisson" synonyms are in the boundary of the phonetic search.
A synonym should be the last resort for the variation of a misspelled term, when adjusting the fuzziness did not provide adequate results or generated too many noise.
For instance, having a synonym "frigo" for "réfrigérateur" is perfectly valid.

Regards,

**Comment by jaybouvet** [comment]
Hi @rbayet 

Thanks for the quick reply. I think our customer brought that from another search engine, but I do not think that it has been established from observing behaviors.

About fuzziness, maybe it's because I had bad experience with other search engine before, but I feel like it is less efficient than using synonyms, mostly on long strings, with multiple words.

I'll have a talk with our customer to have him use that functionnality instead.

Thanks !

**Comment by rbayet** [comment]
Hello @jaybouvet,

I'll post tomorrow a cerebro screenshot of some [REST analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) calls on an french index to show you how to rule out unnecessary synonyms based on phonetic search and/or stemming.

Regards,

**Comment by jaybouvet** [comment]
Perfect ! We'll wait for this.

Could you enlighten me on the difference between having multiple thesaurus with synonymes and having 1 thesaurus with multiple terms ? Which would be the best, if we remove all the fuzziness and phonetic issues ?

Thanks !

**Comment by rbayet** [comment]
Hello @jaybouvet,

**Fuzziness and edit distance**

Let's tackle first what can be covered by the [fuzzy search](https://github.com/Smile-SA/elasticsuite/wiki/FulltextSearchEngineBasicConfiguration#fuzziness-configuration) which, when enabled, will allow for a certain amounts of edit (or "letters change").
Our configuration in admin for the "fuzziness value" will allow for 1, 2 or AUTO. AUTO means : a certain number of edits [according to the word length](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness).
The doc says : 
```
0..2
     Must match exactly
3..5
     One edit allowed
>5
     Two edits allowed
```
So any word between 3 and 5 letters long will be allowed one edit. Any word longer than 5 letters will be allowed 2 edits.
About those edits : 
> When querying text or keyword fields, fuzziness is interpreted as a Levenshtein Edit Distance — the number of one character changes that need to be made to one string to make it the same as another string.
A character edit can be : a character added or removed
A character swap (a "p" for a "b") is one edit.
Two characters changing positions is two edits.

You can perform tests on https://planetcalc.com/1721/ 
![image](https://user-images.githubusercontent.com/2353374/68393446-5e651500-016c-11ea-8f52-c4cf91bc11ed.png)
with your long list of synonyms for réfrigérateur
réfrigérateur,eéfrigérateur,éfrigérateur,frigérateur,frigidaire,frigo,frigos,rédrigérateur,réfeigérateur,réffrigérateur,réfigérateur,réfrgérateur,réfrgiérateur,réfriérateur,réfrigéarteur,réfrigéeateur,réfrigéeateur.

You will see that, if we exclude the obvious (frigo,frigos,frigidaire), there is not a *single* réfrigérateur variation that has an edit distance bigger than 2.

**ACTUAL fuzziness and edit distance**
I simplified things a bit just above : when the fuzziness is enabled in a query, we actually target fields with our `whitespace` analyzer.
By default those fields will be  
- name.whitespace
- sku.whitespace
- spelling.whitespace (the `spelling` fields contains the data of all attributes with `is_used_in_spellcheck = 1`)

So to be 100% accurate, you should actually use for instance a tool like [cerebro](https://github.com/lmenezes/cerebro) to use the [analyze API endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) and look what a word looks like with the whitespace analyzer before trying to guess/compute the edit distance : 
![image](https://user-images.githubusercontent.com/2353374/68396149-5b205800-0171-11ea-8355-164175f1d9ee.png)

With the whitespace analyzer : 
- the case is gone
- accents are gone

This reduces differences / edits in the first place.

**Phonetic matching**
Requests made when the spellchecking is enabled also have a phonetic matching component : they will either cover or complement edit distance matching : 
![image](https://user-images.githubusercontent.com/2353374/68398594-4ba30e00-0175-11ea-8f48-edd610ac1b58.png)

Some words will generate two phonetic tokens : 
![image](https://user-images.githubusercontent.com/2353374/68398770-8c9b2280-0175-11ea-8205-709de399840a.png)

**When fuzziness/phonetic matching is not needed in the first place**
I didn't see any in your screenshot, but obviously, neither the fuzzy/phonetic search will be needed, nor synonyms if words share a common "root" according to the [stemmer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html) defined in our `standard` analyzer (for the `spelling` field).

![image](https://user-images.githubusercontent.com/2353374/68400525-7cd10d80-0178-11ea-853f-71851179684b.png)
Those four words share the same root, hence, according to the `standard`, they are all present in the index even if only one of them is there.

Warning : all stemmers have language depended rules, of course. The `french` stemmer, for instance will sadly consider that `frigo` and `frigos` are different word.

**Conclusion** 
Do not add synonyms for word that can generate the same or almost the same matches when fuzzy search/phonetic matching is enabled.
You can use our **Search Usage dashboard** (requires the tracker to be enabled) to identify spellchecked requests and those without any results.

I'll forward your specific question about thesaurus organization.

Regards,

**Comment by jaybouvet** [comment]
Hi @rbayet ,

Thank you very much for this complete answer !
We'll use the fuzziness instead of all the synonyms we have now.

I'll wait for your answer about thesaurus organization.

Thank you,

**Comment by rbayet** [comment]
Hello @jaybouvet,

There will not be any much difference at indexing time between having a thesaurus for each "theme" or having fewer thesaurus with different "themes" regrouped, due to the structure of the tables and the SQL queries performed to get all synonyms and all expansions at the same time.

You would only hit a performance threshold if you had like several thousands thesaurus, half of them synonyms, the other half being expansion and a significat amount being disabled (because the `smile_elasticsuite_thesaurus` lacks an index on its `type` and `is_active` columns).
By then, you might have had to tweak the `group_concat_max_len` MySQL setting because the two queries (the one getting all synonyms, the other getting all expansions) use `GROUP_CONCAT()`.

**Conclusion:** Your ongoing stability problems are more probably related to [this issue](https://github.com/Smile-SA/elasticsuite/issues/1613) which is caused by what we see as invalid index settings enforced by the ECE Tools.
There is a discussion with the Magento Cloud team about that.

Regards,

**Comment by jaybouvet** [comment]
Thank you for your answer ! We'll monitor the issue you provided.
