### ISSUE TITLE
Add conflict to magento/module-elasticsearch

### ISSUE THREAD

**Issue by jwundrak** [Smile-SA/elasticsuite#1611]
We have some troubles with the stock on virtual-categories and the reindexing. After Debugging, the main issue is `\Magento\Framework\Indexer\Config\DependencyInfoProvider`.

We remove the M2-ES dependency in composer.json with:

~~~
    "replace": {
      "magento/module-elasticsearch": "*"
    }
~~~

and it works.

Can you add please a conflict to this module? Thanks

Magento Version : 2.2.7(-EE)
ElasticSuite Version : 2.6.9

**Comment by romainruaud** [comment]
@jwundrak can you please describe the main issue and a detailed scenario of your debug ?

Regards

**Comment by jwundrak** [comment]
@romainruaud Sure.
We have a virtual category. If we change a product, that is in this virtual category, to out of stock and `qty=0`, the product is still in this category (show out-of-Stock disabled). Reindex manual "catalogsearch_fulltext" helps and the product is not in the virtual category.
Set Stock to 8 and to "in stock" also not includes the product in the virtual category until i do a manual reindex.

Debugging with stock-Index and Catalog-Search-Index "On Save":
The ES-Modul of Magento adds the `catalogsearch_fulltext` to the dependencies (`$indexerData['dependencies']`) in e.g. `\Magento\Framework\Indexer\Config\DependencyInfoProvider::getIndexerIdsToRunAfter`, so `\Smile\ElasticsuiteCatalog\Plugin\Indexer\Stock\ReindexProductsAfterStockUpdate` is never execute.

Ok, I can disable the ES of Magento, but I think it is easier, to remove the dependency.

**Comment by jwundrak** [comment]
There was an other problem. Sorry for bug report. It is not related to any conflict
