### ISSUE TITLE
Filter order in categories (BO) not saved correctly

### ISSUE THREAD

**Issue by ubarenroom** [Smile-SA/elasticsuite#1612]
When I don't touch to the filter in categories BO, order is lost.

### Preconditions

Magento Version : EE 2.3.1

ElasticSuite Version :2.8

Environment :Developer and Production mode

Third party modules :

### Steps to reproduce

1. In Bo Categories, open tab "Display Settings" change order of many attributes and save
2. After the save go to Display settings and check order
3. Save the category without any changes
4. after save check order.

### Expected result

1.the order cannot change if we don't touch to filter order

### Actual result

1. In the table the position is set to 1 when we don't touch to filter position

**Comment by rbayet** [comment]
OK, I managed to reproduce it on your environment.

Under some circumstances, **one of them** being re-saving the category without opening the "Display Settings" tabs again, the `facet_config[x][position]` POST variables for the N pinned attributes are all set to 1.
So of course, those attributes are still pinned so above all the others non-pinned attributes, but their relative position is now probably based on the attribute id.
I also had some issues where the drag'n'drop would not want to work correctly, throwing JS errors everywhere, but that could be circumstantial.

Will try to reproduce on a Luma.

**Comment by rbayet** [comment]
Reproduced locally on a 2.8.x Luma.

**Comment by rbayet** [comment]
This is a pure JS/UI component problem.

From a situation where configured order can be observed in front : 
- the data in the table is valid (as expected)
- the SQL query is valid so the DataProvider has accurate value for the "position" column
- the `facet_config_order[X]` hidden inputs which representsthe hidden "position" input hold accurate values

But if no change occurred on the dynamic rows, at submission/validate AJAX calls the `facet_config[X][position]` values for the pinned attributes are all at 1.

**Comment by rbayet** [comment]
Can also reproduce it on a CE 2.2.7 / ES 2.6.9.

**Comment by rbayet** [comment]
OK, found the source of the problem.

The listens function `onPinChange` (for each "record") is called on initialization at a moment where the parent component (the dynamic rows) probably doesn't have its `elems()` ready yet, hence `this.parentComponent().getPinnedRecords().length` always equals 0 and already pinned elements get assigned the "1" position.

(web/js/category/filter-config/record.js)
```
        onPinChange : function() {
            if (this.data() && this.data().is_pinned !== undefined) {
                this.isPinned(this.data().is_pinned);
                if (this.isPinned()) {
                    this.position = this.parentComponent().getPinnedRecords().length + 1;
                }
                this.parentComponent().sort(this.position, this);
            }
        },
 ```
and (web/js/category/filter-config/dynamic-rows.js)
```
        getPinnedRecords : function() {
            return this.elems().filter(
                function(elem) { return elem.isPinned() === true }
            ).sort(function(recordA, recordB) {
                return recordA.position - recordB.position;
            });
        }
```
