### ISSUE TITLE
Issues with optimizers "Based on attribute value"

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#1619]
I tried to used the optimizer "Based on attribute value", new feature in ES 2.6.3, and I faced several issues. Maybe some of them are bugs ?

### Preconditions
Magento Version : 2.3.2
ElasticSuite Version : 2.8
Environment : public demo http://demo.magento-elastic-suite.io/

### 1. Configuration of the attribute

When I create an optimizer "based on attribute value" the only attributes I can select (attributes displayed in the list) are attributes with the following config:
- "Type" = "Price"
- "Use in search Results Layered Navigation" = "Yes"

The fact that it's mandatory to display the attribute as a filter is an issue. For example it prevent the merchant to create a boost based on the margin, because we don't want to display the margin as a filter.

And also it seems a bit strange to force to display the attribute as a filter on "search result page" but not on "category page". On a business point of view, the boost per attribute value is useful on both pages, I don't see a reason to do a difference between them.

### 2. Preview of the boost

On the demo platform http://demo.magento-elastic-suite.io/ I tried to create a boost based on the "price" of the product, "scale function = linear", "boost multiply = 1", but in the "preview" window, nothing changed in the search results.
![image](https://user-images.githubusercontent.com/20048184/68844411-07aa8e80-06ca-11ea-9050-c0d32ce193d8.png)

With "square root", I also have the same result.
And with "Logarithmic" the score is changed to the value 0 for all products.

### 3. What is the formula ?

This last one is not an issue, it's a question for ElasticSuite documentation: I would be interested to have some explanations about the formula used to calculate the score.
For example with a "linear" boost, multiplicator 1, do we do a simple multiplication of the score by the value of the attribute ? (in that case it would be very important to have no "zero" value)

**Comment by rbayet** [comment]
Hello @PierrickOlivier,

### 1. Configuration of the attribute

There is no requirement for an attribute to be used as filter (whether in catalog or in search results) : any attribute that has "Use for Promo Rule Conditions : Yes" can also be used.
For instance, on the demo, I have set "Use for Promo Rule Conditions : Yes" for the "cost" attribute, and it is no available in the boost's select : 
![image](https://user-images.githubusercontent.com/2353374/68958388-504a7080-07cc-11ea-89b1-ecf2d7552215.png)

> The fact that it's mandatory to display the attribute as a filter is an issue. For example it prevent the merchant to create a boost based on the margin, because we don't want to display the margin as a filter.

Granted, but as this is not the case, this is a non-issue.

> And also it seems a bit strange to force to display the attribute as a filter on "search result page" but not on "category page". On a business point of view, the boost per attribute value is useful on both pages, I don't see a reason to do a difference between them

You lost me there.
Where the boost can be applied is not determined by the fact that the attribute is filterable in search or catalog. It only depends on the "Request Type" optimiser setting : 
![image](https://user-images.githubusercontent.com/2353374/68958541-9b648380-07cc-11ea-9ed3-5004543cf0a8.png)

2. Preview of the boost
I can confirm the issue. I'll get back to you on this point and your third shortly.

Regards,

**Comment by romainruaud** [comment]
@androshchuk can you have a look on this one ?

**Comment by adamkarnowka** [comment]
Hi, so basically you removed "price" from the dropdown :)

Are there any plans to support nested fields in future? Having price (final price) as optimizer, as well as stock qty would be huge feature business wise. Pushing high/low stock products to top/bottom for example seems like common need to major merchants. 

If there are no plans - how would you suggest to implement it? I thought about creating new decimal attributes for qty and price and populate values on product save, but that seems little dirty to me - maybe there is a better way?

Kind regards,
Adam

**Comment by minhnd55** [comment]
Hi all,

Thanks for posting this issue. I ran into the same problem today when my website need to implement a function to boost product's score by it's price.

Can you guys please look into this issue again and find a fix to make optimizer work on nested attribute value? Or an instruction on how to implement it would be nice also.

Appreciate anything can help to move forward.

@adamkarnowka have you found any solution? I also think about creating new decimal attributes for price (for each customer type). Can let me know if you have implemented this and if it works?

Thanks,
Minh

**Comment by adamkarnowka** [comment]
> @adamkarnowka have you found any solution? I also think about creating new decimal attributes for price (for each customer type). Can let me know if you have implemented this and if it works?

Hello, I have worked-around this by creating new indexed field, where current price is added as `double` - created `elasticsuite_indices.xml` with:

```xml
<indices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_ElasticsuiteCore:etc/elasticsuite_indices.xsd">
    <index identifier="catalog_product" defaultSearchType="product">
        <type name="product" idFieldName="entity_id">
            <datasources>
                <datasource name="current_price">Namespace\Module\Model\Product\Indexer\Fulltext\Datasource\CurrentPriceData</datasource>
            </datasources>
            <mapping>
                <field name="current_price" type="double" />
            </mapping>
        </type>
    </index>
</indices>
```

And in class:

```php
<?php

namespace Namespace\Module\Model\Product\Indexer\Fulltext\Datasource;

class CurrentPriceData implements \Smile\ElasticsuiteCore\Api\Index\DatasourceInterface
{
    public const CURRENT_PRICE_ATTRIBUTE_CODE = 'current_price';

    /**
     * @var \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\PriceData
     */
    private $resourceModel;

    /**
     * CurrentPriceData constructor.
     * @param \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\PriceData $resourceModel
     */
    public function __construct(\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\PriceData $resourceModel)
    {
        $this->resourceModel = $resourceModel;
    }

    /**
     * @param int $storeId
     * @param array $indexData
     * @return array
     */
    public function addData($storeId, array $indexData)
    {
        $priceData = $this->resourceModel->loadPriceData($storeId, array_keys($indexData));

        foreach ($priceData as $priceDataRow) {
            $productId     = (int) $priceDataRow['entity_id'];

            $indexData[$productId][self::CURRENT_PRICE_ATTRIBUTE_CODE] = [$priceDataRow['min_price']];
            
            if (!isset($indexData[$productId]['indexed_attributes'])) {
                $indexData[$productId]['indexed_attributes'] = [self::CURRENT_PRICE_ATTRIBUTE_CODE];
            } elseif (!in_array(self::CURRENT_PRICE_ATTRIBUTE_CODE, $indexData[$productId]['indexed_attributes'])) {
                $indexData[$productId]['indexed_attributes'][] = self::CURRENT_PRICE_ATTRIBUTE_CODE;
            }
        }

        return $indexData;
    }
}
```

So while reindexing, I am saving price in index. Note: attribute must be created in Magento (so you can use it in booster) but you don't have to save values in it (in Magento DB). This works for me as long as indexes are synced- but for 99% of time order of products is correct. Hope it helps :)
