### ISSUE TITLE
"Special Price" Not available in Virtual Category Rules

### ISSUE THREAD

**Issue by metamasterplay** [Smile-SA/elasticsuite#162]
Hi,
I'm wondering how I can achieve having a Virtual Category with the discounted products. One way to do so is to create a rule where special_price>0. This method actually works in Magento catalog rules and cart rules, but I can't find the attribute special_price in the list.

I'm using Magento 2.1.1 with ElasticSuite 2.2.2

**Comment by afoucret** [comment]
Sorry for the delay but I wanted to take the time to make a good response on this one.

Since we rely on the search engine to compute rules, only indexed attributes are usable in the rule engine :

* searchable attributes
* filterable attributes (search or catalog)

So making the special_price attributes searchable and reindexing the engine should do the job.

But, imho, I should not do this. Indeed having a not empty special_price attribute is not a good way to have all discounted products into a rule since because other rules can apply at the same time :

* Special price can be higher than price and not be applied

* Special price can application can be limited by date range

* Catalog rules

* Tier pricing can be leveaged by customer group

Instead we have already indexed a special field into the engine : is_discounted which live in the price nested object. This field combines all this parameters to determine if the product is discounted or not in a consistent way.

Our next step (not done yet) will be to have this field exposed in the rule engine. At the same time we will add the following computed rules :

* As image

* Is in stock

This is expected to be available in our next major release (2.3.0).

Let me now if you are ok with this response and if we can close this issue.

**Comment by afoucret** [comment]
@metamasterplay : since I have no feedback from you, I close this one.

**Comment by afoucret** [comment]
FYI, the new special attributes I was talking about (is_discount, is_in_stock and has_image) are visible in the PR #181 and will be available in 2.3.0. Following options are available in the rule management : 

* Only discounted products
* Only products with image
* Only in stock products

BR,

**Comment by metamasterplay** [comment]
Sorry for the delayed answer I wasn't able to test these changes. I just tested them now  with version 2.3.x and i get a blank screen when using **Only discounted products** in the virtual category. Apache2 error log shows:
`PHP Fatal error:  Uncaught Error: Call to a member function getConditions() on array in /var/www/web/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Block/Product/Conditions.php:145
Stack trace:
#0 /var/www/web/var/view_preprocessed/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/view/adminhtml/templates/product/conditions.phtml(1): Smile\\ElasticsuiteCatalogRule\\Block\\Product\\Conditions->getInputHtml()
#1 /var/www/web/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/web/va...')
#2 /var/www/web/vendor/magento/framework/View/Element/Template.php(255): Magento\\Framework\\View\\TemplateEngine\\Php->render(Object(Smile\\ElasticsuiteCatalogRule\\Block\\Product\\Conditions), '/var/www/web/va...', Array)
#3 /var/www/web/vendor/magento/framework/View/Element/Template.php(279): Magento\\Framework\\View\\Element\\Template->fetchView('/var/www/web/va...')
#4 /var/www/web/vendor/magento/module-backend/Block/Template.php(104): Magento\\Framework\\View\\Element\\Template->_toHtml()
#5 /var/www/w in /var/www/web/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Block/Product/Conditions.php on line 145, referer: https://e-motion.ma/backend/catalog/category/edit/id/62/`

Magento 2 Exception log:
`Next Zend_Db_Statement_Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'web.elasticsuite_categories_fulltext_cl' doesn't exist, query was: UPDATE `catalog_category_entity` SET `attribute_set_id` = ?, `parent_id` = ?, `path` = ?, `level` = ?, `children_count` = ? WHERE (entity_id = '62') in /var/www/web/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php:235
Stack trace:
#0 /var/www/web/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/web/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('UPDATE `catalog...', Array)
#4 /var/www/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(459): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE `catalog...', Array)
#5 /var/www/web/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(514): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('UPDATE `catalog...', Array)
#6 /var/www/web/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(635): Magento\Framework\DB\Adapter\Pdo\Mysql->query('UPDATE `catalog...', Array)
#7 /var/www/web/vendor/magento/framework/EntityManager/Db/UpdateRow.php(82): Zend_Db_Adapter_Abstract->update('catalog_categor...', Array, '(entity_id = '6...')
#8 /var/www/web/vendor/magento/framework/EntityManager/Operation/Update/UpdateMain.php(57): Magento\Framework\EntityManager\Db\UpdateRow->execute('Magento\\Catalog...', Array)
#9 /var/www/web/vendor/magento/framework/EntityManager/Operation/Update.php(105): Magento\Framework\EntityManager\Operation\Update\UpdateMain->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#10 /var/www/web/vendor/magento/framework/EntityManager/EntityManager.php(87): Magento\Framework\EntityManager\Operation\Update->execute(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#11 /var/www/web/vendor/magento/module-catalog/Model/ResourceModel/Category.php(1025): Magento\Framework\EntityManager\EntityManager->save(Object(Magento\Catalog\Model\Category\Interceptor))
#12 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Catalog\Model\ResourceModel\Category->save(Object(Magento\Catalog\Model\Category\Interceptor))
#13 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Model\ResourceModel\Category\Interceptor->___callParent('save', Array)
#14 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Array, 'smile_elasticsu...')
#15 /var/www/web/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php(91): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Category\Interceptor))
#16 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(67): Smile\ElasticsuiteVirtualCategory\Plugin\Catalog\Category\SaveProductsPositions->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Category\Interceptor))
#17 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Array, 'catalogsearchFu...')
#18 /var/www/web/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php(43): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Catalog\Model\Category\Interceptor))
#19 /var/www/web/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Category.php(29): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Category->addCommitCallback(Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Category\Interceptor))
#20 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Category->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Category\Interceptor))
#21 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'save', Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Array, 'clean_cache')
#22 /var/www/web/vendor/magento/framework/App/Cache/FlushCacheByTags.php(60): Magento\Catalog\Model\ResourceModel\Category\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Category\Interceptor))
#23 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave(Object(Magento\Catalog\Model\ResourceModel\Category\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Category\Interceptor))
#24 /var/www/web/var/generation/Magento/Catalog/Model/ResourceModel/Category/Interceptor.php(364): Magento\Catalog\Model\ResourceModel\Category\Interceptor->___callPlugins('save', Array, Array)
#25 /var/www/web/vendor/magento/framework/Model/AbstractModel.php(631): Magento\Catalog\Model\ResourceModel\Category\Interceptor->save(Object(Magento\Catalog\Model\Category\Interceptor))
#26 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Model\AbstractModel->save()
#27 /var/www/web/var/generation/Magento/Catalog/Model/Category/Interceptor.php(39): Magento\Catalog\Model\Category\Interceptor->___callPlugins('save', Array, Array)
#28 /var/www/web/vendor/magento/module-catalog/Controller/Adminhtml/Category/Save.php(203): Magento\Catalog\Model\Category\Interceptor->save()
#29 /var/www/web/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Adminhtml\Category\Save->execute()
#30 /var/www/web/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->___callParent('dispatch', Array)
#33 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor), Array, 'adminAuthentica...')
#34 /var/www/web/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor), Array, 'adminMassaction...')
#37 /var/www/web/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#38 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/web/var/generation/Magento/Catalog/Controller/Adminhtml/Category/Save/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->___callPlugins('dispatch', Array, Array)
#40 /var/www/web/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Adminhtml\Category\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#42 /var/www/web/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#43 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#44 /var/www/web/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /var/www/web/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#46 /var/www/web/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#47 /var/www/web/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /var/www/web/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#49 /var/www/web/index.php(49): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#50 {main} [] []`

I checked my database and table **elasticsuite_categories_fulltext_cl** indeed doesn't exist. I also checked the InstallSchema.php and there doesn't seem to any table created with that name.
