### ISSUE TITLE
Multi word search

### ISSUE THREAD

**Issue by tudro** [Smile-SA/elasticsuite#1620]
Hello,

When i have a multi word search, eg. `lorem ipsum`, i don't get first the products that contain in the name this `lorem ipsum`. Instead, it seems that it return all products that either contain `lorem` or `ipsum`.

Ex :
Here is a list of products: https://dev.magazinuldepietre.ro/pietre-semipretioase/hematit.html?forma=Sfera As you can see, there are products that contain the words `hematit` and `sfere`

Here is the search for `hematit sfere` https://dev.magazinuldepietre.ro/catalogsearch/result/?q=hematit+sfere You can see none of those products are listed.

Probably i'm doing some bad configuration somewhere, but i can figure it out. The only attribute set to be searchable is the name.

Thank you

**Comment by rbayet** [comment]
Hello @tudro,

Have you changed the relevance configuration for "[Minimum Should Match](https://github.com/Smile-SA/elasticsuite/wiki/FulltextSearchEngineBasicConfiguration#fulltext-base-settings)" ?

If it's still at 100% then the other possible issues would be 
- your "hematit sfere" products not being visible both in catalog and search (due to the "Visibility" attribute)
- maybe something problematic in your mapping / index where romanian would not be supported correctly
- and/or an issue with our "term vectors" pre-analysis query 
- or the custom development/extension in charge of your infinite scroll messing with the search query sort orders or search results

In that order, could you :
- check the "Minimum Should Match" setting value ?
- tell me if you also enabled Spellchecking ("Is Used in Spellcheck") on the "name" attribute ?
- give me version of the `elasticsearch/elasticsearch` module ('composer info elasticsearch/elasticsearch | grep -i version`) and which version of M2 and Elasticsuite you are using ?

Regards,

**Comment by tudro** [comment]
Hello @rbayet ,

Thank you for the help.

- `Minimum should match` is at 100%
- The `hematit sfere` products are all with `visibility=catalog, search`
- i tried with spellchecking disabled for name and i got the same result
- elasticsearch module v5.4.0, magento v2.3.0, elasticsuite 2.8.0

I will try and check the infinite scroll, too.

Thank you

**Comment by rbayet** [comment]
Hello @tudro,

Thanks for the heads up.
You can leave spellchecking enabled for name : all attributes with "Used in Spellcheck = Yes" are used in our analysis pre-request to determine which kind of search request to perform (exact match, with fuzziness, with fuzziness but boosting the rare exact matches, etc).
So if name is your only indexed product attribute, it should be left with "Used in Spellcheck = Yes" (don't forget to reindex).

Could you post your Elasticsearch product index [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) and [settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-settings.html) ?
You can retrieve them with curl or with the help of the chrome [head extension](https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm/) or using [cerebro](https://github.com/lmenezes/cerebro).

You can also enable the [debug mode](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#elasticsearch-client) which will log Elasticsearch requests (warning: both the fulltext search and catalog navigation related requests) in `system.log` and check that fulltext search requests actually use `_score` as first sort parameter.

Regards,

**Comment by tudro** [comment]
Hi @rbayet ,

I have reenabled spellcheck and reindexed.

Here are the mapping and the settings:
[mapping.txt](https://github.com/Smile-SA/elasticsuite/files/3851032/mapping.txt)
[settings.txt](https://github.com/Smile-SA/elasticsuite/files/3851033/settings.txt)

Here are the 2 logs for `sort`:
```
[2019-11-15 10:30:45] main.INFO: curl -XGET 'http://localhost:9200/magento_dev_default_catalog_product/product/_search?pretty=true' -d '{"size":5,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"filter":{"bool":{"must":[{"terms":{"visibility":[3,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"search_query","score_mode":"none","query":{"bool":{"must":[{"term":{"search_query.query_id":{"value":931,"boost":1}}},{"term":{"search_query.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}}],"must_not":[],"should":[],"boost":1}},"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}}}' [] []
```
and
```
[2019-11-15 10:30:47] main.INFO: curl -XGET 'http://localhost:9200/magento_dev_default_catalog_category/category/_search?pretty=true' -d '{"size":3,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}}}' [] []
```

Thank you

**Comment by rbayet** [comment]
@tud

> 
> Here are the 2 logs for `sort`:
> 
> ```
> [2019-11-15 10:30:45] main.INFO: curl -XGET 'http://localhost:9200/magento_dev_default_catalog_product/product/_search?pretty=true' -d '{"size":5,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"filter":{"bool":{"must":[{"terms":{"visibility":[3,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"search_query","score_mode":"none","query":{"bool":{"must":[{"term":{"search_query.query_id":{"value":931,"boost":1}}},{"term":{"search_query.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}}],"must_not":[],"should":[],"boost":1}},"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","name^5","sku^6","search.shingle^0","name.shingle^0","sku.shingle^0","name.sortable^0","sku.sortable^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}}}' [] []
> ```
> 
> and
> 
> ```
> [2019-11-15 10:30:47] main.INFO: curl -XGET 'http://localhost:9200/magento_dev_default_catalog_category/category/_search?pretty=true' -d '{"size":3,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"hematit sfere","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"hematit sfere","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 6 mm","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"must":{"multi_match":{"query":"Hematit sfere 4 mm","fields":["search^1","search.shingle^0"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}}}' [] []
> ```
> 
> Thank you

Do you confirm those 2 requests are those showing up in the logs when you're performing a "hematit sfere" search ?

Regards,

**Comment by tudro** [comment]
@rbayet Yes.

**Comment by rbayet** [comment]
Hello @tudro,

There is something weird about your queries, it looks like you have synonyms (from the Thesaurus) that have been applied but : 
- I don't see any synonyms declared in your `*_thesaurus_* ` indices settings 
- the boost for each possible synonym (`Hematit sfere 6 mm`, `Hematit sfere 6 mm`) is set to 1, instead of being lower than than

```
      "must": {
        "bool": {
          "must": [],
          "must_not": [],
          "should": [
            {
              "bool": {
                "filter": {
                  "multi_match": {
                    "query": "hematit sfere",
                    [...]
                  }
                },
                "must": {
                  "multi_match": {
                    "query": "hematit sfere",
                    [...]
                  }
                },
                "boost": 1
              }
            },
            {
              "bool": {
                "filter": {
                  "multi_match": {
                    "query": "Hematit sfere 6 mm",
                    [...]
                  }
                },
                "must": {
                  "multi_match": {
                    "query": "Hematit sfere 6 mm",
                    [...]
                  }
                },
                "boost": 1
              }
            },
            {
              "bool": {
                "filter": {
                  "multi_match": {
                    "query": "Hematit sfere 4 mm",
                    [...]
                },
                "must": {
                  "multi_match": {
                    "query": "Hematit sfere 4 mm",
                    [...]
                  }
                },
                "boost": 1
              }
            }
          ],
```

Could you check that you have indeed a **Synonyms** thesaurus configured in your admin interface for that store (menu Elasticsuite > Thesaurus) with the terms "hematit sfere,Hematit sfere 6 mm,Hematit sfere 4 mm" ? And tell me if its status is indeed "Active" ?

Could you also check the following settings in Elasticsuite > Search Relevance ? : 
- Thesaurus Configuration > Synonyms Configuration > Synonyms Weight Divider
- Thesaurus Configuration > Query Expansions Configuration > Concepts Weight Divider
- Relevance Configuration > Phrase Match Configuration > Enable Boost on Phrase Match
- Relevance Configuration > Phrase Match Configuration > Phrase Match Boost Value

Long story short : 
- your synonyms should show up in the indices settings but they don't :|
- by default the boost for each synonym should be 0.1 but you may have changed the value for Thesaurus Configuration > Synonyms Configuration > Synonyms Weight Divider
- the phrase matching query components are applied but with a boost of 0, so Relevance Configuration > Phrase Match Configuration > Enable Boost on Phrase Match is likely set to "No"

I would advise to : 
- avoid multi words synonyms like "hematit sfere,Hematit sfere 6 mm,Hematit sfere 4 mm" because multi-words generally generate a lot of noise and sometimes wonky results because the tokenisers go all over the place
- if you want to in general boost products like https://dev.magazinuldepietre.ro/pietre-semipretioase/hematit/hematit-sfere-fatetate-12-mm.html whatever the search query, the best course of action is to use a search optimizer (Elasticsuite > Optimizers)
- if you want to specifically put a few products at the top when searching "hematit sfere", please use the [search terms merchandiser](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#manual-product-sorting-in-search-results) 
- keep a value > 1 for Thesaurus Configuration > Synonyms Configuration > Synonyms Weight Divider (and Thesaurus Configuration > Query Expansions Configuration > Concepts Weight Divider)
- re-set Relevance Configuration > Phrase Match Configuration > Enable Boost on Phrase Match to Yes

What the phrase match boost is boosting products where your several search terms are located next to each other, for instance in the name of the product : 
- the `name` attribute is the only searchable attribute 
- **but** we also index a product's categories name
- hence, when your query is expanded from "hematit sfere" to "hematit sfere" OR "Hematit sfere 6 mm" OR "Hematit sfere 4 mm" (due to your synonym) it might words party in the products' name and/or in the products categories name.

(It looks like) we no longer provide a settings available in the admin interface to decide if fulltext search should use a product's categories name, so if after all those recommendations you still encounter issue, I will indicate where to change that in the configuration files.

Regards,

**Comment by tudro** [comment]
Hello @rbayet ,

Thank you very much for your time and detailed explanations.

There is nothing in Elasticsuite > Thesaurus:
![image](https://user-images.githubusercontent.com/11506738/68945404-01dfa680-07b9-11ea-994f-11caab141309.png)

- Thesaurus Configuration > Synonyms Configuration > Synonyms Weight Divider
![image](https://user-images.githubusercontent.com/11506738/68945472-250a5600-07b9-11ea-8ec2-1282f1243094.png)

- Thesaurus Configuration > Query Expansions Configuration > Concepts Weight Divider
![image](https://user-images.githubusercontent.com/11506738/68945484-2d629100-07b9-11ea-9692-2642930cbde9.png)

- Relevance Configuration > Phrase Match Configuration > Enable Boost on Phrase Match
- Relevance Configuration > Phrase Match Configuration > Phrase Match Boost Value
This was set to `no`. I enabled it, reindex, no difference. This is how it is now:
![image](https://user-images.githubusercontent.com/11506738/68945676-95b17280-07b9-11ea-928e-8c865a6696ac.png)

Thank you

**Comment by rbayet** [comment]
Hello @tudro,

This is weird, especially the thesaurus/synonym situation.
Do you have native synonyms entered in the Marketing > Search synonyms ?
Do you have any third party extension or custom module which is supposed to enhance the fulltext search or provide an alternative synonym related feature ?

I can also see that your product list is not working correctly when the sort order and direction are changed :
- sorting by price desc does not work : https://dev.magazinuldepietre.ro/catalogsearch/result/index/?product_list_dir=desc&product_list_order=price&q=hematit+sfere 
- neither does sorting by name ascending : https://dev.magazinuldepietre.ro/catalogsearch/result/index/?product_list_order=name&q=hematit+sfere

As your Elasticsearch requests seemed to be (almost) OK with the default sort order/direction, I would be tempted to point to a problem with a third party module or maybe the theme (even though your toolbar block seems to be quite standard).
As this is a dev instance, I would recommend disabling the FPC just in case ...

Regards,

**Comment by tudro** [comment]
Hello @rbayet 

This is in marketing:
![image](https://user-images.githubusercontent.com/11506738/68952880-5d199500-07c9-11ea-8934-f978e19faf03.png)

I haven't installed any module that deals with search, unless this is hidden from the base functionality of the module. This is the list of my modules:
[modules.txt](https://github.com/Smile-SA/elasticsuite/files/3852040/modules.txt)

I didn't even notice that the sort is not working. This `dev` instance is just a copy of the [prod one](https://www.magazinuldepietre.ro/pietre-semipretioase.html). The only difference is that `prod` search is on elasticsearch (same bad results) and `dev` is on `elasticsuite`.

I have disabled FPC. 

How can i disable elasticsuite to check if the sort? At least i can figure out if it's from something else and make another copy of the `prod`.

Any tips on what to look for in the theme? For modules i assume just take them one by one and disable them, right?

Thank you

**Comment by tudro** [comment]
@rbayet Yup, it's from the theme. I switch to `luma` and now everything is ok. So the only question that remains is the one if you have any idea what to look for in this theme.

Thank you

**Comment by rbayet** [comment]
@tudro I would look first for any layout instruction or template override which would conflict with the ones in Smile_ElasticsuiteCatalog (vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalogsearch_result_index.xml and vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalog_category_view_type_layered.xml) for 
- catalog.leftnav (custom template)
- catalogsearch.navigation.renderer (block change)

Failing that, conflict or changes (for instance, block change/rewrites) for 
- search.result (Magento_CatalogSearch)
- search_result_list (Magento_CatalogSearch)
- product_list_toolbar (Magento_CatalogSearch)
- catalogsearch.leftnav, catalogsearch.navigation.state and catalogsearch.navigation.renderer (Magento_LayeredNavigation)

Regards,

**Comment by tudro** [comment]
@rbayet Thank you very much for your time and help.
