### ISSUE TITLE
after installing smile ElasticSuite switching back to mysql searchengine exceptions

### ISSUE THREAD

**Issue by isabelcelima** [Smile-SA/elasticsuite#1622]
After installing elasticsuite and when i switch back to mysql searchengine the category page shows the following error:
1 exception(s):
Exception #0 (LogicException): Index provider not configured
Exception #0 (LogicException): Index provider not configured
#0 /var/www/html/lorenzotessuti/vendor/magento/framework/Search/Adapter/Mysql/Adapter.php(78): Magento\Framework\Search\Adapter\Mysql\Mapper->buildQuery(Object(Smile\ElasticsuiteCore\Search\Request))
#1 /var/www/html/lorenzotessuti/vendor/magento/module-search/Model/SearchEngine.php(42): Magento\Framework\Search\Adapter\Mysql\Adapter->query(Object(Smile\ElasticsuiteCore\Search\Request))
#2 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(626): Magento\Search\Model\SearchEngine->search(Object(Smile\ElasticsuiteCore\Search\Request))
#3 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(194): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->loadProductCounts()
#4 /var/www/html/lorenzotessuti/generated/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(24): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->getSize()
#5 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/RelevantFilterList.php(69): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getSize()
#6 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/RelevantFilterList.php(37): Smile\ElasticsuiteCatalog\Model\Layer\RelevantFilterList->getCoverageRates(Object(Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor))
#7 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(186): Smile\ElasticsuiteCatalog\Model\Layer\RelevantFilterList->getRelevantFilters(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Array)
#8 /var/www/html/lorenzotessuti/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php(174): Smile\ElasticsuiteCatalog\Block\Navigation->addFacets()
#9 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Element/AbstractBlock.php(272): Smile\ElasticsuiteCatalog\Block\Navigation->_prepareLayout()
#10 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Layout/Generator/Block.php(150): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor))
#11 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#12 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Layout.php(343): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#13 /var/www/html/lorenzotessuti/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#14 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#15 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#16 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#17 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Page/Config.php(208): Magento\Framework\View\Layout\Builder->build()
#18 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Page/Config.php(544): Magento\Framework\View\Page\Config->build()
#19 /var/www/html/lorenzotessuti/vendor/magento/framework/View/Page/Config.php(502): Magento\Framework\View\Page\Config->getElementAttribute('body', 'class')
#20 /var/www/html/lorenzotessuti/vendor/magento/module-catalog/Controller/Category/View.php(202): Magento\Framework\View\Page\Config->addBodyClass('page-products')
#21 /var/www/html/lorenzotessuti/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(24): Magento\Catalog\Controller\Category\View->execute()
#22 /var/www/html/lorenzotessuti/vendor/magento/framework/App/Action/Action.php(107): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#23 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', Array)
#25 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/lorenzotessuti/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(39): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', Array, Array)
#27 /var/www/html/lorenzotessuti/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Category\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#29 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#30 /var/www/html/lorenzotessuti/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /var/www/html/lorenzotessuti/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#33 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#34 /var/www/html/lorenzotessuti/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/html/lorenzotessuti/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#36 /var/www/html/lorenzotessuti/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/html/lorenzotessuti/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#38 /var/www/html/lorenzotessuti/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#39 /var/www/html/lorenzotessuti/index.php(54): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#40 {main}
Magento Version : Magento CE ver. 2.2.6

ElasticSuite Version : 6.5.4

Environment : Developer

**Comment by romainruaud** [comment]
@isabelcelima you cannot switch back to an other search engine once ElasticSuite is installed. 

It's a "whole package". If you want to go back to MySQL you'll have to completely remove ElasticSuite.

Regards

**Comment by ericmorand** [comment]
@romainruaud and nothing seems wrong with that? Is this bug or a feature?
