### ISSUE TITLE
Elasticsearch Version

### ISSUE THREAD

**Issue by rafallmmw** [Smile-SA/elasticsuite#1628]
Hello,

I upgrade to Magento 2.3.3 and of course I will use the newest smile i.e. 2.8.3.
However which elasticsearch version should i use ? 6 or 7 ?
On the https://github.com/Smile-SA/elasticsuite i see very useful table which shows me information: which smile version is for which magento version.

It would be really cool if there is such table for mapping between: smile version and elastic search version. Currently this information I see somewhere under https://github.com/Smile-SA/elasticsuite/releases

I found there "We began our journey for the Elasticsearch 7". However it doesn't sound like official announcement :)
Therefore my question: However which elasticsearch version should i use ? 6 or 7 ?

Thank you in advance for help

regards
Rafal

**Comment by romainruaud** [comment]
Hi @rafallmmw 

You are right, Elasticsearch 7 is not supported yet.

You can use the latest Elasticsearch 6 instead.

regards
