### ISSUE TITLE
Only default (admin) values are being indexed

### ISSUE THREAD

**Issue by NORDCOMPCZ** [Smile-SA/elasticsuite#1630]
On multi-store environment the translated values for multiselect attributes are being ignored.

### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.0

Environment : Developer

Third party modules :

### Steps to reproduce

1. Create an multi-select attribute
2. Add translated values to this attribute (typically colours would pass this)
3. Index data

### Expected result

1. Translated values should be indexed
2. Translated values (taken from index) should be displayed in layered navigation/filter on category page 

### Actual result

1. Admin (default) values are indexed
2. Admin (default) values are displayed in filter

**Comment by romainruaud** [comment]
@androshchuk can you try to reproduce this issue ?

**Comment by romainruaud** [comment]
Sorry Dima, I took it finally.

I cannot reproduce, clearly visible here : 

http://demo.magento-elastic-suite.io/index.php/men/tops-men.html

You have all the color translated in french on the french store view, so does some values of the "Material" attribute (Cotton/Coton, Fleece/Polaire, Leather/Cuir).

Can you please give us more details ? Did you do a full reindex after translating the attributes values ?

**Comment by NORDCOMPCZ** [comment]
@romainruaud thanks a lot for your prompt reply. Yes, I've tested lots of possible solutions and full reindex was the first one. Is there any special setting required?
We have colours named without any special characters as admin value (typically `weiss` or `gruen`) and correctly under specific language (here `weiß` or `grün`). Nevertheless only the admin-values are indexed and displayed as labels on frontend (`weiss` instead of `weiß`).
