### ISSUE TITLE
Unknown TokenFilter type [phonetic] for [phonetic]

### ISSUE THREAD

**Issue by rafaelstz** [Smile-SA/elasticsuite#1631]
### Preconditions
PHP 7.1
Magento Version : 2.3.2

ElasticSuite Version : 2.8.3

Environment : developer

### Steps to reproduce
1. Install via composer
2. Try to run `bin/magento setup:upgrade`

### Expected result

1. Run without issues

### Actual result
1. I received this message below.

```
{"error":{"root_cause":[{"type":"index_creation_exception","reason":"failed to create index"}],"type":"illegal_argument_exception","reason":"Unknown TokenFilter type [phonetic] for [phonetic]"},"status":400}
```

![Screenshot 2019-11-27 11 12 16](https://user-images.githubusercontent.com/610598/69730635-329fd400-1107-11ea-95e7-928179884e2f.png)

**Comment by romainruaud** [comment]
You need to install `analysis-phonetic` and `analysis-icu` plugins as decribed here : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x#installing-required-plugins

Regards
