### ISSUE TITLE
Fatal error: Class 'Magento\CatalogInventory\Model\Plugin\Layer' on module-elasticsuite-catalog/Plugin/LayerPlugin.php

### ISSUE THREAD

**Issue by amarroni** [Smile-SA/elasticsuite#1633]
Trying to install module on a fresh magento 2.3.3 via magesuite. After changed to the creative theme throw this error.
Reviwing the error line 24 plugin signature is using a no exist magento class
### Preconditions

Magento Version :
CE 2.3.3

ElasticSuite Version :
2.7.0

Environment :
Developer

Third party modules :
Magesuite

### Steps to reproduce

1. error display trying to access to homege
2.
3.

### Expected result

1. show homepage

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/5198527/70204922-0e448880-1701-11ea-8ea4-bb535c6faf02.png)

**Comment by Quazz** [comment]
Magento 2.3.X should install ElasticSuite 2.8

**Comment by amarroni** [comment]
@Quazz thanks you so much for your update. I just fallowing the documentation. Doc. said if you are running 2.3.x should use ^2.7.0.

Let me check

**Comment by romainruaud** [comment]
yes @amarroni please upgrade to Elasticsuite 2.8.0

In any cases, we do not provide support for MageSuite.

Regards
