### ISSUE TITLE
"Only discounted products" fail for configurable products if all children have same discount

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#1634]
Magento Version : 2.3.2
ElasticSuite Version : 2.8.2
Environment : Production

### Steps to reproduce
1. Create a discount rule for a set of simple products all releated to a single configurable parent
2. Create a new virtual category with a virtual rule: "Only discounted products"
3. Reindex all

### Expected result
1. Category should show configurable products discounted

### Actual result
1. Nothing is displayed

I think the problem is releated to:
Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData\PriceConfigurable

The two methods returns $priceData['min_price'] and $priceData['max_price'] but Magento doens't change those values in the main table catalog_product_index_price:

![Schermata del 2019-12-09 12-24-46](https://user-images.githubusercontent.com/5001801/70432195-fbbeac00-1a7e-11ea-93b9-13849ca8847b.png)

**Comment by CRYX2** [comment]
someone has an idea?

**Comment by romainruaud** [comment]
Hello @CRYX2 

you are right, since we rely on price index data coming from `catalog_product_index_price`, we can't do better if Magento is unable to properly compute this data.

Maybe you can open an issue directly on the Magento bug tracker for this one.

Regards
