### ISSUE TITLE
Category pagination issue if 100,000+ products

### ISSUE THREAD

**Issue by zjevik** [Smile-SA/elasticsuite#1637]
### Preconditions

I use this docker container: fballiano/magento2-apache-php on Ubuntu 18.04.3 LTS
Magento CE 2.3.3 + Catalog_pagination_issue_on_Elasticsearch_6_composer-2019-10-11-08-07-41.patch applied
ElasticSearch 6.8.5
MySql 5.7

Magento Version: CE 2.3.3

ElasticSuite Version: 6.8.5

Environment : Default (although I discovered the bug in Production mode but didn't test it with clean install)

Third party modules : None

### Steps to reproduce

1. Install Magento 2.3.3 + elasticsuite 2.8.3
2. import https://github.com/zjevik/elasticsuite/blob/master/import.csv
3. run reindex

### Expected result

1. http://localhost/parts.html?p=11112 should display 100000 - 100008 products.

### Actual result

1. The page displays "We can't find products matching the selection." while http://localhost/parts.html?p=11111 works fine.

<img width="1294" alt="Screen Shot 2019-12-09 at 12 19 30 PM" src="https://user-images.githubusercontent.com/7343686/70457540-53104c80-1a7e-11ea-9267-1303d0453836.png">
<img width="1293" alt="Screen Shot 2019-12-09 at 12 19 40 PM" src="https://user-images.githubusercontent.com/7343686/70457541-53104c80-1a7e-11ea-9b30-60e90c79fbb9.png">

**Comment by androshchuk** [comment]
Hello @zjevik

I think a problem in https://github.com/Smile-SA/elasticsuite/blob/12f25cc840f16953c095475969207f3dde46af33/src/module-elasticsuite-core/etc/di.xml#L462 and\or https://github.com/Smile-SA/elasticsuite/blob/12f25cc840f16953c095475969207f3dde46af33/src/module-elasticsuite-core/Helper/IndexSettings.php#L41

Also, need to be changed index.max_result_window to more 100000 in your elasticseach server https://discuss.elastic.co/t/paginating-result-set-greater-than-10000-with-aggregations-possible-options/119673/6

Regards

**Comment by zjevik** [comment]
Wow, thank you so much! Changing the `index.max_result_window` variable solve the issue. I never checked the ES logs...
I have 600,000+ products in a category and while I don't expect anyone will be browsing through it the issue was that once you changed "Sort By" then even the first page didn't show up.
