### ISSUE TITLE
Install guidelines

### ISSUE THREAD

**Issue by zap263** [Smile-SA/elasticsuite#1638]
Hi..
Sorry its a bit of a newbie question and i've only started dabbling with SSH and customizing my Magento store myself.

Can someone please provide a guideline or point me to a tutorial that explains how to install this.

Many thanks!

**Comment by zjevik** [comment]
This repository has an amazing wiki page. Did you check it?
https://github.com/Smile-SA/elasticsuite/wiki

**Comment by romainruaud** [comment]
@zjevik said it all !

Please reopen an issue if you are still facing problem while following our wiki.

Regards
