### ISSUE TITLE
Category active filter does not respect store

### ISSUE THREAD

**Issue by simonrl** [Smile-SA/elasticsuite#1641]
It seems that categories that are disabled on a global level are not added to store view indexes.

### Preconditions

Magento Version : 2.1.14

ElasticSuite Version : ^2.3.0

Environment : occurs developer & production mode

Third party modules : not relevant here

### Steps to reproduce

1. set category to "is_active=0" in global scope
2. enable the said category in store view scope
3. rebuild `elasticsuite_categories_fulltext`

### Expected result

1. Using Kibana, the category should be found in the store view's index

### Actual result

1. The category is not part of the index

### Possible solution
I know that I'm using an outdated version, but the error also seems to be present in the latest version.
If you look here: https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/ResourceModel/Category/Indexer/Fulltext/Action/Full.php#L70, the method `addIsActiveFilter()` doesn't seem to take the store id into account. A category that is disabled in admin scope won't occur in any index.

It seems to be fixed by changing line #69 from:
`$categoryCollection = $this->categoryCollectionFactory->create()`
...to:
`$categoryCollection = $this->categoryCollectionFactory->create()->setStoreId($storeId);`

After reindexing, I can see that the category is part of the index of the store view(s) it's enabled for.

Thanks
Simon

**Comment by romainruaud** [comment]
Thank you @simonrl for reporting this.

Can you provide a PR containing your fix ?

Regards

**Comment by simonrl** [comment]
Hi,

sure.
Should I create an PR for each branch 2.3.x onwards up to the current one? Or which branches do you prefer?

Regards

**Comment by romainruaud** [comment]
We wont probably release anything more for branches <2.6.x since they are out of scope from our Open Source support here.

regards

**Comment by simonrl** [comment]
Hi @romainruaud 

please include my PRs in the next releases if they're ok.

https://github.com/Smile-SA/elasticsuite/pull/1697
https://github.com/Smile-SA/elasticsuite/pull/1696
https://github.com/Smile-SA/elasticsuite/pull/1695

Thanks
Simon
