### ISSUE TITLE
4th level Category links in autocomplete

### ISSUE THREAD

**Issue by test4295** [Smile-SA/elasticsuite#1643]
Preconditions
Magento Version : CE 2.3.2
ElasticSuite Version : 2.8.3

**Steps to reproduce**
1 Try to create 4th level category
![Screenshot_2](https://user-images.githubusercontent.com/5907520/70973219-3ce03d00-20cb-11ea-9654-7be08d8c74e9.png)

2 Search 4th level category(jacket)
![Screenshot_1](https://user-images.githubusercontent.com/5907520/70973163-1cb07e00-20cb-11ea-9f43-da5c318ab25b.png)

3 Getting parent(3rd level) category URL in Jackets-Sub(all 4th level) category URL and other levels category URLs are getting proper and working fine.
![Screenshot_3](https://user-images.githubusercontent.com/5907520/70973226-42d61e00-20cb-11ea-8102-e5d5ea3b651b.png)

**Expected result**
1 The link for the category with all levels works properly

**Actual result**
1 Getting the wrong 4th level category URL.

**Comment by androshchuk** [comment]
Hello, @test4295.
Thanks for the good catch!

Please don't close the issue.
We'll discuss it later and add a solution to new versions of the module.

Regards

**Comment by rbayet** [comment]
Fixed by #1646 in 2.8.4
