### ISSUE TITLE
Optimizers List для All Store Views

### ISSUE THREAD

**Issue by TexnikTexnolog** [Smile-SA/elasticsuite#1644]
Может ли ElasticSuite создавать Optimizers List http://prntscr.com/qchsgj для не только для выбранного Store Views (к примеру RU или UA) а сразу для всего All Store Views так как в карточке товара http://prntscr.com/qchtaw ?

**Comment by androshchuk** [comment]
@TexnikTexnolog здравствуйте. 

К сожалению сейчас в ElasticSuite нет такой возможности.

С уважением.

**Comment by TexnikTexnolog** [comment]
спасибо
