### ISSUE TITLE
jQuery UI slider Touch & Drag/Drop support on Mobile devices

### ISSUE THREAD

**Issue by minhluan259** [Smile-SA/elasticsuite#1648]
On the touch screen, instead of registering a touch as picking up a handle and a drag as dragging the handle across the slider, it just slides the whole webpage to the side of the screen. 
It does work if you tap the handle and then tap the location on the slider where you want the handle to end up.
Could you please implement this library?
http://touchpunch.furf.com/
http://touchpunch.furf.com/content.php?/slider/range-slider

**Comment by quisse** [comment]
Duplicate as in #1701 #1578 #879.

**Comment by romainruaud** [comment]
Fixed by #2138
