### ISSUE TITLE
Catalog Search indexer and ElasticSuite Category Indexing indexer process unknown error:

### ISSUE THREAD

**Issue by mlaurel** [Smile-SA/elasticsuite#1652]
I'm having a similar issue as #1087  

I'm running Magento Version: 2.2.6

When I reindex with `bin/magento indexer:reindex` command, I get the following 2 issues...

```
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
```
```
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```

When I run the following commands...

```
composer info | grep elastic && curl http://localhost:9200
```

I get this...

```
elasticsearch/elasticsearch                       v5.3.2             PHP Client for Elasticsearch
magento/module-elasticsearch                      100.2.5            N/A
smile/elasticsuite                                2.6.3              Magento 2 merchandising and search engine built on ElasticSearch

{
  "name" : "Man-Beast",
  "cluster_name" : "elasticsearch_mikelaurel",
  "cluster_uuid" : "-jUZpvotSmydDBjGMbodog",
  "version" : {
    "number" : "2.4.6",
    "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
    "build_timestamp" : "2017-07-18T12:17:44Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by mlaurel** [comment]
Some additional info... which the previous #1087 mentions, when I mistakenly ran `brew upgrade`  I believe
my previously working  elasticsuite ^2.4  was upgraded to the latest 2.6 version.  How can I fix this?

**Comment by androshchuk** [comment]
Hello @mlaurel 

ElasticSuite ^ 2.6 supports ElasticSearch 6.x, so use it. Many things have been fixed in this version. 
Also, ElasticSuite ^ 2.6 is not compatible with ElasticSearch 2.x.

For a detailed instruction "tutorial" please refer to the official Smile_Elasticsuite documentary to get everything correct https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x

Regards

**Comment by romainruaud** [comment]
Hello @mlaurel 

@androshchuk is right, you are using an outdated version of Elasticsearch (2.4). You have to update it to at least 5, but upgrading to Elasticsearch 6 would be the best option for you.

Regards
