### ISSUE TITLE
Filter catalog products by attribute does not update layered navigation filters as well

### ISSUE THREAD

**Issue by ionpan** [Smile-SA/elasticsuite#1653]
I need to filter the products collection by attribute. I tracked down the layered navigation collection and found out that it uses an instance of Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection. By adding a filter to it (addAttributeToFilter) I was able to filter the catalog's products successfully. However, I came upon an inconsistency in the layered navigation filters. The options count do not take into consideration the attribute filter I apply to the collection and they refer to the catalog as if there was never a filter in the first place. As a result, I get greater count numbers than what the user sees on the catalog and even options for products that are not visible due to the manual filter I apply. I have seen this issue happening without the ElasticSuite installed, but since ElasticSuite overrides the default collection class (Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection) maybe you can pinpoint something that I am missing in this story.

**Comment by romainruaud** [comment]
Hello @ionpan 

You should not use `addAttributeToFilter` because it's adding an SQL based filter.

you'd rather got with `addFieldToFilter` which will be mapped into a properly tailored Elasticsearch filter.

Regards

**Comment by ionpan** [comment]
Thank you for your reply. I got lost regarding the naming schema of the attributes on ElasticSearch. It turns out Magento adds several prefixes to the attribute codes based on the type of the attribute (for instance on mine it adds "option_text_attribute_code") before it sends the products batch to Elastic. That got me confused. I actually added the filters to the filters attribute of the collection and it worked.

**Comment by romainruaud** [comment]
You should not worry about the naming, since the engine will map it properly under the hood after (add the option_ if needed, etc...).

Regards

**Comment by ionpan** [comment]
As a matter of fact, it didn't. I looked it up using ElasticSearch Head on my browser to find said attribute and filter it this way. Anyway, the thing is it worked beautifully after this, filtering both the collection's items and the filters' options counts.

**Comment by romainruaud** [comment]
Great, may we close this issue ?

**Comment by ionpan** [comment]
All well and thank you for your time.
