### ISSUE TITLE
Number of expanded facets is always > 0 

### ISSUE THREAD

**Issue by NORDCOMPCZ** [Smile-SA/elasticsuite#1656]
Acoording to settings, there is a possibility to set number of facets that are initially opened. In case you want all of them kept closed (set 0 in administration), this setting is not respected.

### Preconditions

Magento Version : 2.3.1

ElasticSuite Version : 2.8.0

Environment : doesn't matter

Third party modules :

### Steps to reproduce

1. Set number of initially opened facets to 0
2. Clear caches

### Expected result

1. None of the present facets should be opened 

### Actual result

1. At least one (the first) is opened

**Comment by NORDCOMPCZ** [comment]
Possible fix:

in `src/module-elasticsuite-catalog/Block/Navigation.php`, L:119
replace
`$activeFilters    = range(0, min(count($displayedFilters), $expandedFacets) - 1);`
with
`
$activeFilters    = [];
            if ($expandedFacets > 0) {
                $activeFilters    = range(0, min(count($displayedFilters), $expandedFacets) - 1);
            }
`

**Comment by romainruaud** [comment]
Hello @NORDCOMPCZ 

can you provide a PR with your fix for this one ?

Regards
