### ISSUE TITLE
Override class collection

### ISSUE THREAD

**Issue by ionpan** [Smile-SA/elasticsuite#1658]
I was having the same issue with issue #1079 and I think I hit rock bottom. What I am trying to do is restrict the users to several products based on user and product attributes (fairly custom requirements) and I am trying to override the Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareRequest() in order to add my custom filters. I believe this is not possible using a plugin as the method is private and I see no observers being called in the process.
My frontend di.xml looks like this:
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection" type="Vendor\Module\Model\ResourceModel\Product\Fulltext\Collection" />
</config>`

Keep in mind that Vendor\Module\Model\ResourceModel\Product\Fulltext\Collection extends Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection and I have copied all private attributes and methods that cannot be inherited only adding a few lines of code in prepareRequest().

**Comment by rbayet** [comment]
Hello @ionpan,

As you do not describe sufficiently what you want to do in the first place (applying some specific query filters ?), I can't help you there.

So I'll consider that your current question (this issue) is that you have trouble overriding the Elasticsuite fulltext collection with the DI.

The declaration you posted is not enough and is probably not needed at all if you try the following : 

From :
```
    <preference for="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection"
                type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection" />
```
to
```
    <preference for="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection"
                type="[your collection] />
```

From 
```
    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory"
                 type="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection</argument>
        </arguments>
    </virtualType>

    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollection"
                 type="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">quick_search_container</argument>
        </arguments>
    </virtualType>
```
to 
```
    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory"
                 type="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">[your collection]</argument>
        </arguments>
    </virtualType>

    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollection"
                 type="[your collection]">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">quick_search_container</argument>
        </arguments>
    </virtualType>
```

Of course, **make sure that Vendor\Module depends on Smile\ElasticsuiteCatalog** to be sure that modules and DI are loaded in the correct order (check your app/etc/config.php).

Regards,

**Comment by ionpan** [comment]
Thank for your reply @rbayet. I already have
`<module name="Magento_Catalog" />`
`<module name="Magento_CatalogSearch" />`
`<module name="Smile_ElasticsuiteCatalog" />`
in my module.xml. It doesn't seem to work though.

**Comment by rbayet** [comment]
@ionpan Have you applied the changes in your DI I indicated ?

Regards,

**Comment by ionpan** [comment]
Yes

**Comment by rbayet** [comment]
I'll have a look tomorrow to see if I forgot a declaration.

**Comment by rbayet** [comment]
@iopan Nope, totally works on my side.

Here are the 4 declarations that you need.
**1: preference for "Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection"**
```
    <preference for="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection"
                type="CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext\Collection" />
```

**2: changing the instanceName argument of Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory**
```
    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory"
                 type="Magento\Catalog\Model\ResourceModel\Product\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext\Collection</argument>
        </arguments>
    </virtualType>
```
or simply 
```
    <type name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory">
        <arguments>
            <argument name="instanceName" xsi:type="string">CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext\Collection</argument>
        </arguments>
    </type>
```

**3. and 4. changing the concrete type of virtual Types Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollection and Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection (for autocomplete)**
```
    <virtualType name="Magento\CatalogSearch\Model\ResourceModel\Fulltext\SearchCollection"
                 type="CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">quick_search_container</argument>
        </arguments>
    </virtualType>

    <virtualType name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection"
                 type="CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">catalog_product_autocomplete</argument>
        </arguments>
    </virtualType>
```

Those declarations in the frontent/di.xml of a module with the following module.xml declaration 
```
    <module name="CompanyName_ModuleName" setup_version="1.0.0">
        <sequence>
            <module name="Magento_Catalog" />
            <module name="Smile_ElasticsuiteCatalog" />
            <module name="Smile_ElasticsuiteVirtualCategory" />
        </sequence>
    </module>
```
is enough for Elasticsuite using my collection instead, which basically just overrides getSize and setOrder : 
```
namespace CompanyName\ModuleName\Model\ResourceModel\Product\Fulltext;

use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection as ElasticsuiteCollection;

class Collection extends ElasticsuiteCollection
{
    /**
     * {@inheritDoc}
     */
    public function getSize()
    {
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/override.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info('--- OVERRIDE ---');
        $logger->info(__METHOD__);

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder($attribute, $dir = self::SORT_ORDER_DESC)
    {
        $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/override.log');
        $logger = new \Zend\Log\Logger();
        $logger->addWriter($writer);
        $logger->info('--- OVERRIDE ---');
        $logger->info(__METHOD__);

        return parent::setOrder($attribute, $dir);
    }
}
```

Works both in developer and production mode, in (grand a bit old) EE 2.3.0 + Elasticsuite 2.8.x-dev.

Please note that my CompanyName\ModuleName module is in app/code and not a vendorized module.

Regards,

**Comment by ionpan** [comment]
@rbayet The only thing missing from my module.xml was `<module name="Smile_ElasticsuiteVirtualCategory" />` but it didn't make any difference. The module is enabled and some of its functionality can be seen at the moment. CompanyName\ModuleName is indeed in app/code and not a vendor module. I am in developer mode at the moment, Magento 2.3.3 Open Source. ElasticSuite version is `"smile/elasticsuite": "^2.8"` from my composer.json and recently updated. And I follow the same paradigm as you for class inheritance. I am sorry to tell you that it still doesn't work.

**Comment by ionpan** [comment]
The thing is, when I add your instructions in my di.xml, it no longer executes the code I deliberately put in the vendor collection. Keep in mind, my di.xml is in the frontend folder as I need this functionality to be available only for the customers.

**Comment by rbayet** [comment]
The declarations I copy/pasted are indeed in the frontend/di.xml of the module.

**Comment by rbayet** [comment]
I've just tested the declarations in a lighter module on a Luma 2.3.3 Open Source, with the module in app/code. With or without the MSI modules. Production and developer modes.
I removed the unnecessary depends on Smile\ElasticsuiteVirtualCategory (it was required for the original module's plugins).

See the mockup enclosed
[OverridingFulltextCollection.tar.gz](https://github.com/Smile-SA/elasticsuite/files/4045811/OverridingFulltextCollection.tar.gz)
Test it and a fresh install without any third party module and you will see it works as intended.
If it does not work as expected on your project, it may be related to conflicting DI declarations in other vendor or custom modules.

**Anyway, whether or not this works as expected, don't go that road of extending the collection**.
If you want to add custom filters to the Elasticsearch queries, either all the time or only in frontend, look instead at the **elasticsearch_search_request.xml file** and implement a new request/filters/filter node.
You will be able to inject whatever object you need in your \Smile\ElasticsuiteCore\Api\Search\Request\Container\FilterInterface implementing class and apply whatever filter you want according to the context (based on the App Area).
If you use the FPC (the default or any kind), don't forget to make sure your cache varies according to your frontend users contraints, etc by playing with \Magento\Framework\App\Http\Context.

Regards,

**Comment by ionpan** [comment]
I will try on a clean installation just to be sure. It seems it took me a lot more time to do what I wanted than I initially intended, so I might as well look around that elasticsearch_search_request.xml file you mentioned. Thank you for your time either way, it's good to know this well made module has such excellent support.

**Comment by ionpan** [comment]
@rbayet I just wanted to let you know that it I managed to use the elasticsuite_search_request.xml file and inject my filters there. I also set some values to the http context that helped me group my users tand cache their pages accordingly. It all worked beautifully. Again, thanks for your advice and time, keep up the good work!

**Comment by emrahuyanik** [comment]
`
<virtualType name="elasticsearchCategoryCollection" type="Nayax\LayeredNavigation\Model\ResourceModel\Fulltext\Collection">
        <arguments>
            <argument name="searchRequestName" xsi:type="string">catalog_view_container</argument>
            <argument name="searchCriteriaResolverFactory" xsi:type="object">elasticsearchSearchCriteriaResolverFactory</argument>
            <argument name="searchResultApplierFactory" xsi:type="object">elasticsearchSearchResultApplier\Factory</argument>
            <argument name="totalRecordsResolverFactory" xsi:type="object">elasticsearchTotalRecordsResolver\Factory</argument>
            <argument name="defaultFilterStrategyApplyChecker" xsi:type="object">Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\DefaultFilterStrategyApplyChecker</argument>
        </arguments>
    </virtualType>
`

**Comment by mibesoft** [comment]
@emrahuyanik it's working for me on magento CE 2.4.2-p1
