### ISSUE TITLE
Attributes that allow for a Min and Max value for use with a slider

### ISSUE THREAD

**Issue by ifking80** [Smile-SA/elasticsuite#1671]
Hello,

When I intially looked into this module a couple of months ago I thought it had the ability to create an attribute for a product where we can set a min and max value for an example "Frequency Range" that would have a min value of 1Ghz and a max value of 10Ghz.

Then on the front end by means of a slider if you set it to 3Ghz this item would still show up because 3 Ghz falls in the range of 1-10.

If this module is capable of this would you be able to provide some documentation and if not is it something that could be implemented?

Thanks,
Ifking

**Comment by rbayet** [comment]
Hello @ifking80,

That's weird, I'm pretty sure we had that question before and that I had answered it.
Then maybe it was this very issue and I answered it _in my head_. Oh well...

This behaviour is not available _out of the box_, but you could write a custom layered navigation filter that achieves it
- either by relying on a custom attribute type that allows for a min/max (but I imagine it would be store in a serialized form, so maybe not the easiest way)
- or by relying on on two attributes

On the Elasticsearch side, you could rely on either 
- a [complex field](https://github.com/Smile-SA/elasticsuite/wiki/Indexing#complex-field-types) containing both min and max values (`frequency.min` and `frequency.max`)
- two simple fields (`frequency_min` and `frequency_max`)

Then of course the fun starts.
You could probably rely on [implemented aggregation types](https://github.com/Smile-SA/elasticsuite/wiki/Querying#facets) and create your own layer filter model (look into [src/module-elasticsuite-catalog/etc/frontend/di.xml](https://github.com/Smile-SA/elasticsuite/blob/371736f31dea5af4ee9c1e5315989eb12b4093bb/src/module-elasticsuite-catalog/etc/frontend/di.xml#L61)).

But in terms of UX, it's a bit complicated : if you use a terms aggregation with a metric extracting the smallest frequency.min value and another aggregation (or the same) to extract the higher frequency.max values, you only managed to get the bounds.
It does not mean that any value in between those bounds is valid : for instance if you have a bunch of products with the range 1-3 and another bunch with range 6-10, your min will be 1 and your max will be 10.
But any value on your slider between 3.something and 5.something is **_invalid_** ie there are no products there.

So you should probably look first for a field structure in Elasticsearch and an aggregation/metrics/pipeline type that allows you to easily build an histogram of "valid values" (in the example above, that would be [1, 2, 3, 6, 7, 8, 9, 10]) and have a version of our price/decimal slider that "snaps" to valid values.

Regards,
