### ISSUE TITLE
Search results in dropdown correct - result page no results

### ISSUE THREAD

**Issue by alicedfisheye** [Smile-SA/elasticsuite#1679]
Search results in search bar dropdown are correct with custom product attributes - when searched, no results on the result page. 

It seems to only occur on custom attributes with the 'Catalogue Input Type for Store Owner' of text area.  

### Preconditions

Magento Version : Magento ver. 2.3.3 EE

ElasticSuite Version : 2.8.3

Environment : Occurs on Developer and Production

Third party modules :

Magento_AdminAnalytics
Magento_Store
Magento_Directory
Magento_Theme
Magento_Eav
Magento_AdvancedPricingImportExport
Magento_Rule
Magento_Customer
Magento_Backend
Magento_Amqp
Magento_AmqpStore
Magento_Config
Magento_User
Magento_Authorization
Magento_AdminNotification
Magento_Indexer
Magento_AuthorizenetGraphQl
Magento_Variable
Magento_Cms
Magento_Backup
Magento_Catalog
Magento_Quote
Magento_SalesSequence
Magento_Payment
Magento_CatalogInventory
Magento_BraintreeGraphQl
Magento_Bundle
Magento_GraphQl
Magento_BundleImportExport
Magento_BundleImportExportStaging
Magento_Sales
Magento_RequisitionList
Magento_Search
Magento_Checkout
Magento_CacheInvalidate
Magento_CatalogUrlRewrite
Magento_AuthorizenetAcceptjs
Magento_AdvancedCatalog
Magento_MediaStorage
Magento_EavGraphQl
Magento_CatalogImportExport
Magento_CatalogImportExportStaging
Magento_CardinalCommerce
Magento_CatalogInventoryGraphQl
Magento_Msrp
Magento_CatalogPageBuilderAnalytics
Magento_CatalogPageBuilderAnalyticsStaging
Magento_CatalogRule
Magento_Widget
Magento_ConfigurableProduct
Magento_SalesRule
Magento_CustomerCustomAttributes
Magento_Downloadable
Magento_GiftCard
Magento_Captcha
Magento_StoreGraphQl
Magento_Wishlist
Magento_CustomerSegment
Magento_AuthorizenetCardinal
Magento_Ui
Magento_CheckoutAddressSearch
Magento_Security
Magento_CheckoutAgreements
Magento_CheckoutAgreementsGraphQl
Magento_Staging
Magento_ScalableOms
Magento_CmsGraphQl
Magento_CmsPageBuilderAnalytics
Magento_CmsPageBuilderAnalyticsStaging
Magento_CmsStaging
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_Company
Magento_Integration
Magento_CompanyGraphQl
Magento_CompanyPayment
Magento_Analytics
Magento_ConfigurableImportExport
Magento_AdvancedCheckout
Magento_ProductAlert
Magento_CatalogGraphQl
Magento_ConfigurableProductSales
Magento_Reports
Magento_ConfigurableRequisitionList
Magento_CatalogSearch
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_CustomAttributeManagement
Magento_AdvancedRule
Magento_CustomerBalance
Magento_CustomerBalanceGraphQl
Magento_VersionsCms
Magento_CustomerFinance
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_CatalogWidget
Magento_DataMigrationTool
Magento_Deploy
Magento_Developer
Magento_AdvancedSearch
Magento_DirectoryGraphQl
Magento_TargetRule
Magento_DownloadableGraphQl
Magento_Tax
Magento_Vault
Magento_BundleGraphQl
Magento_Elasticsearch
Magento_Elasticsearch6
Magento_WebsiteRestriction
Magento_Email
Magento_EncryptionKey
Magento_Enterprise
Magento_Weee
Magento_GiftCardAccount
Magento_QuoteGraphQl
Magento_GiftCardGraphQl
Magento_GiftCardImportExport
Magento_NegotiableQuote
Magento_GiftCardRequisitionList
Magento_CatalogPermissions
Magento_GiftRegistry
Magento_GiftMessage
Magento_GiftMessageStaging
Magento_UrlRewrite
Magento_GiftWrapping
Magento_GiftWrappingStaging
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_GoogleOptimizer
Magento_GoogleOptimizerStaging
Magento_GoogleShoppingAds
Magento_PageCache
Magento_UrlRewriteGraphQl
Magento_GraphQlCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_GroupedProductStaging
Magento_GroupedRequisitionList
Magento_SharedCatalog
Magento_ImportExport
Magento_CatalogStaging
Magento_InstantPurchase
Magento_CheckoutAddressSearchNegotiableQuote
Magento_Invitation
Magento_LayeredNavigation
Magento_LayeredNavigationStaging
Magento_Logging
Magento_CatalogEvent
Magento_MessageQueue
Magento_CatalogRuleConfigurable
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_MsrpStaging
Magento_MultipleWishlist
Magento_MysqlMq
Magento_BundleNegotiableQuote
Magento_NegotiableQuoteSharedCatalog
Magento_Newsletter
Magento_OfflinePayments
Magento_OfflineShipping
Magento_Banner
Magento_PageBuilder
Magento_GoogleTagManager
Magento_AdminGws
Magento_PaymentStaging
Magento_Paypal
Magento_PaypalCaptcha
Magento_PaypalGraphQl
MSP_ReCaptcha
Magento_Persistent
Magento_PersistentHistory
Magento_PricePermissions
Magento_ConfigurableProductStaging
Magento_ProductVideo
Magento_ProductVideoStaging
Magento_PromotionPermissions
Magento_QuickOrder
Magento_BannerPageBuilderAnalytics
Magento_GiftCardAccountGraphQl
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_Reminder
Magento_CatalogStagingPageBuilder
Magento_RequireJs
Magento_BundleRequisitionList
Magento_ResourceConnections
Magento_Review
Magento_ReviewStaging
Magento_Reward
Magento_RewardGraphQl
Magento_SalesRuleStaging
Magento_Rma
Magento_RmaGraphQl
Magento_RmaStaging
Magento_Robots
Magento_Rss
Magento_AdvancedSalesRule
Magento_ConfigurableNegotiableQuote
Magento_SalesArchive
Magento_SalesGraphQl
Magento_CatalogRuleStaging
Magento_RewardStaging
Magento_BannerCustomerSegment
Magento_SampleData
Magento_ScalableCheckout
Magento_ScalableInventory
Magento_BundleSharedCatalog
Magento_ScheduledImportExport
Magento_ConfigurableSharedCatalog
Magento_SearchStaging
Magento_CompanyCredit
Magento_GiftCardSharedCatalog
Magento_Shipping
Magento_Sitemap
Magento_CheckoutStaging
Magento_StagingPageBuilder
Magento_GiftCardNegotiableQuote
Magento_ConfigurableProductGraphQl
Magento_Support
Magento_Webapi
Magento_SwaggerWebapi
Magento_SwatchesGraphQl
Magento_DownloadableStaging
Magento_CatalogInventoryStaging
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_B2b
Magento_ThemeGraphQl
Magento_Tinymce3
Magento_Tinymce3Banner
Magento_Translation
Magento_CheckoutAddressSearchGiftRegistry
Magento_CatalogUrlRewriteStaging
Magento_CatalogUrlRewriteGraphQl
Magento_AsynchronousOperations
Magento_ElasticsearchCatalogPermissions
Magento_Braintree
Magento_VaultGraphQl
Magento_BannerPageBuilder
Magento_VisualMerchandiser
Magento_Swagger
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_GroupedSharedCatalog
Magento_GiftCardStaging
Magento_WeeeGraphQl
Magento_WeeeStaging
Magento_PageBuilderAnalytics
Magento_BundleStaging
Magento_WishlistGraphQl
AgrilineProducts_Captcha
AgrilineProducts_Catalog
AgrilineProducts_CatalogPricing
AgrilineProducts_Company
Fisheye_Base
AgrilineProducts_Tractors
AgrilineProducts_CustomerExport
AgrilineProducts_GroupedProduct
Fisheye_Menu
Fisheye_PageBuilder
AgrilineProducts_PriceImport
AgrilineProducts_RestApiLog
WeProvide_EnquireJs
Fisheye_Theme
AgrilineProducts_TractorProductGeneration
Fisheye_Catalog
AgrilineProducts_TractorSearch
MageWorx_SeoAll
AgrilineProducts_CustomStockStatus
Craftyclicks_Ukpostcodelookup
FireGento_FastSimpleImport
EthanYehuda_CronjobManager
CtiDigital_Configurator
Fisheye_AdvancedRedirects
Fisheye_CompanyHttpContext
AgrilineProducts_Menu
Fisheye_Basket
Fisheye_BasketDeliveryUpsell
Fisheye_BasketPreview
AgrilineProducts_SubCategories
Fisheye_Checkout
Fisheye_B2b
Fisheye_CustomerAccount
Fisheye_SimpleModal
Fisheye_Newsletter
Fisheye_ExpressCheckout
Fisheye_ExpressCheckoutPaypal
Fisheye_Lazyload
AgrilineProducts_CurrencySwitcherContext
Smile_ElasticsuiteCore
AgrilineProducts_PageBuilder
Fisheye_ProductAlert
Fisheye_DeliveryReturnsInfo
Fisheye_SortBy
ShipperHQ_Shipper
AgrilineProducts_Theme
Fisheye_UrlRewriteCustomiser
Fisheye_UrlRewriteOptimiser
Fooman_EmailAttachments
Fooman_PrintOrderPdf
Fooman_SameOrderInvoiceNumber
Iazel_RegenProductUrl
Magento_PaypalReCaptcha
MageWorx_HtmlSitemap
MageWorx_Info
MageWorx_XmlSitemap
MageWorx_SeoBase
MageWorx_SeoBreadcrumbs
MageWorx_SeoCategoryGrid
MageWorx_SeoCrossLinks
MageWorx_SeoExtended
MageWorx_SeoMarkup
MageWorx_SeoRedirects
MageWorx_SeoReports
MageWorx_SeoUrls
MageWorx_SeoXTemplates
AgrilineProducts_TractorSitemap
Mageplaza_Core
Mageplaza_Smtp
ShipperHQ_Common
ShipperHQ_Logger
ShipperHQ_Option
Smile_ElasticsuiteCatalog
Fisheye_Search
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Fisheye_CoreConfig
Smile_ElasticsuiteQuickOrder
Smile_ElasticsuiteSharedCatalog
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteAnalytics
Swissup_Checkout
Swissup_Core
Swissup_Taxvat
AgrilineProducts_TractorProductSeoLanding
Xtento_XtCore
Xtento_StockImport
Xtento_TrackingImport
Xtento_OrderExport
Yireo_Whoops
Yotpo_Yotpo

### Steps to reproduce

1. Search products with by custom attribute value with the 'Catalogue Input Type for Store Owner' of textarea.
2. View results on dropdown - which are correct.
3. Click to search and browse results page. No Results. 

### Expected result

1. When you search by custom attribute if there are matching results in the dropdown. The results page should match or include more. 

### Actual result

1. Search products with by custom attribute value with the 'Catalogue Input Type for Store Owner' of textarea.
2. View results on dropdown - which are correct.
3. Click to search and browse results page. No Results.

**Comment by alicedfisheye** [comment]
After further review, it would seem adding any custom attribute within the admin no matter the type it does not render a results page without adding the code found in this github issue. 

https://github.com/Smile-SA/elasticsuite/issues/517#issuecomment-326593204

**Comment by androshchuk** [comment]
Hello @alicedfisheye 
I also did some research. I can change attribute configuration via Admin panel and set "Used in spellcheck" to "Yes" http://joxi.ru/p273811TWxjkJ2
It works for me.

Regards
