### ISSUE TITLE
Wrong count in layered navigation when using custom collection

### ISSUE THREAD

**Issue by anthonyherve** [Smile-SA/elasticsuite#1682]
### Preconditions
Magento Version : EE 2.3.3

ElasticSuite Version : 2.8.3

Environment : Developer

Third party modules : 
- smile/module-elasticsuite-cms-search
- smile/module-elasticsuite-shared-catalog
- Amasty / GDPR
- FME / Productattachments

### Steps to reproduce

I want to pre filter collection by adding some addAttributeToFilter to collection. I try for example to edit method beforePrepareProductCollection in Plugin/LayerPlugin.php.
`public function beforePrepareProductCollection(
        \Magento\Catalog\Model\Layer $layer,
        \Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection $collection
    ) {
        $collection->setPageSize(10)->setCurPage(1);
        //$collection->addFieldToFilter('sku', ['like' => '001109%']);
        $collection->addFieldToFilter('sku', ['eq' => '00110970149']);
        //$collection->addFieldToFilter('c_062', ['neq' => NULL]);
        $this->setSortParams($layer, $collection);
    }`

I have tried different ways to filter. With help of issue https://github.com/Smile-SA/elasticsuite/issues/1653, I use addFieldToFilter instead of addAttributeToFilter and it works well for  following filter:
$collection->addFieldToFilter('sku', ['eq' => '00110970149']);

But with $collection->addFieldToFilter('sku', ['like' => '001109%']);, I have no result and same thing with last one ($collection->addFieldToFilter('c_062', ['neq' => NULL]);).
For the last one, I have checked into my table catalog_product_entity_varchar (my attribute c_062 is varchar type) and I have one line which is not null.

I think I'm not far from my goal.

Can you please help me?

Thank you in advance.

Regards,
Anthony

**Comment by anthonyherve** [comment]
I add my goal is to do a OR filter like this:
`$collection->addFieldToFilter(
            ['c_062', 'c_063'], 
            [
                ['neq' => NULL],
                ['neq' => NULL]
            ]
        );`

But I have following error:
`1 exception(s):
Exception #0 (Exception): Warning: Illegal offset type in isset or empty in /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php on line 614

Exception #0 (Exception): Warning: Illegal offset type in isset or empty in /var/www/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php on line 614
<pre>#1 Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->mapFieldName() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php:242]
#2 Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->addFieldToFilter() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:74]
#3 Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->beforePrepareProductCollection() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#4 Magento\Catalog\Model\Layer\Category\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Catalog\Model\Layer\Category\Interceptor->___callPlugins() called at [generated/code/Magento/Catalog/Model/Layer/Category/Interceptor.php:26]
#6 Magento\Catalog\Model\Layer\Category\Interceptor->prepareProductCollection() called at [vendor/magento/module-catalog/Model/Layer.php:147]
#7 Magento\Catalog\Model\Layer->getProductCollection() called at [vendor/magento/module-catalog/Block/Product/ListProduct.php:470]
#8 Magento\Catalog\Block\Product\ListProduct->initializeProductCollection() called at [vendor/magento/module-catalog/Block/Product/ListProduct.php:116]
#9 Magento\Catalog\Block\Product\ListProduct->_getProductCollection() called at [vendor/magento/module-catalog/Block/Product/ListProduct.php:188]
#10 Magento\Catalog\Block\Product\ListProduct->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1096]
#11 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1101]
#12 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:671]
#13 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:557]
#14 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:533]
#15 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#16 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#17 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#18 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#19 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#20 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#21 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#22 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#25 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#26 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#28 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#31 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:585]
#32 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:535]
#33 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:488]
#34 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:954]
#35 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#36 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#37 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#38 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:52]
#39 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#40 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#41 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#42 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#43 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#44 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:26]
#45 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:141]
#46 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#47 Magento\Framework\App\Http\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#48 Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#49 Magento\Framework\App\Http\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:26]
#50 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#51 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>`

A simple neq does not work.
I tri also a "$collection->addFieldToFilter('c_062', ['like' => '%ebb5e6e6e38a071451e481a84bfe0b5b28b5d5c7_00175110100_C_062%']);" and it works well.

I don't really understand which filters work and which one does not work.

Thank you for your help.

Regards,
Anthony

**Comment by romainruaud** [comment]
Hello Anthony,

we won't be able to provide you more support here as part of our Open Source support (free) policy since you are trying to achieve complex customisation on top of our extension.

Shall you be interested in more support from us as part of our Commercial support (paid) policy, feel free to reach me directly by email at romain.ruaud@smile.fr

Best regards
