### ISSUE TITLE
smile_elasticsuite/search_request_relevanceconfig/index/ goes nowhere

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1683]
### Preconditions

Magento Version : 2.3.3 CE

ElasticSuite Version : 2.8.3

Environment : developer

Third party modules : none

### Steps to reproduce

1. Click on [admin menu] > ElasticSuite > Search Engine > Search Relevance
2. Page redirects to dashboard with `Invalid security or form key. Please refresh the page.` error. 

### Expected result

1. If this is still a valid menu item, it should go to the relevant admin page or be removed.

### Actual result

1. Page redirects to dashboard with `Invalid security or form key. Please refresh the page.` error. No other menu items have this issue.

**Comment by romainruaud** [comment]
Hello @refueledinc 

This screen is still existing, actually I'm able to access it on our demo environment (I cannot disclose access to the admin however).

Can you give us more details about your admin ACLs configuration ? It might be related to it.

Regards

**Comment by refueledinc** [comment]
I have full admin access. I did `c:c` and `c:f`, logged in/out and it did not help. No other menu items with EleasticSuite or core have this issue.

**Comment by refueledinc** [comment]
Ok, I have found the issue.

I completely forgot https://github.com/redchamps/clean-admin-menu is installed on the instance and seems to be causing the issue. I'll file a bug report.
