### ISSUE TITLE
We can't find products matching the selection few minutes after reindexation

### ISSUE THREAD

**Issue by tkuter-pl** [Smile-SA/elasticsuite#1684]
We made a shop using Magento 2 EE and we are experiencing problems with category pages in the frontend. Few minutes after daily full reindexation (bin/magento indexer:reindex) products are disappearing in categories.

We are getting following message: We can't find products matching the selection.

Problem is not appearing everyday, but there was a time, when we get it in three days, one by one.
After making next reindexation (catalogsearch_fulltext) products are appearing again.

### Preconditions

Magento Version : 2.3.1 EE

ElasticSuite Version : 2.7.2

Environment : production
ElasticSearch: 5.6.16

Third party modules :
- mageplaza/module-smtp

### Steps to reproduce

1. Make full reindex
2. Wait about 7 minutes
3. No product is listed in categories

### Expected result

1. Products are always listed in the categories

### Actual result

1. I attached two log files in [logs.zip](https://github.com/Smile-SA/elasticsuite/files/4128068/logs.zip): on 2020-01-24 there was no issues, today (2020-01-29) problems started at 06:47:48 - failed to execute query

**Comment by rbayet** [comment]
Hello @tkuter-pl,

In the logs, Elasticsearch is complaining about the mapping below the category structure, but I don't see why.
Could you provide us the mapping of your catalog product indices (or just magento2_en_catalog_product)
- right after a full reindex (when the problem is not occuring yet) ?
- right after the problem starts occuring ?

Regards,

**Comment by tkuter-pl** [comment]
Hi @rbayet 

Here is the mapping configuration:
[magento2_en_catalog_product.mapping.json.zip](https://github.com/Smile-SA/elasticsuite/files/4135326/magento2_en_catalog_product.mapping.json.zip)

This is correct mapping when everything is fine.

I don't have the mapping right after the problem starts occurring.
I will attach it here when problem will occur again.

We upgraded our ElasticSearch to version 6.8.6 yesterday and we didn't have problems yesterday.

Regards,

**Comment by rbayet** [comment]
Indeed @tkuter-pl that mapping looks fine.

> I will attach it here when problem will occur again.
Perfect.

**Comment by tkuter-pl** [comment]
@rbayet We have encountered this problem again and this time we were able to get invalid mappings.
It looks very strage.

I enclosed following list files:
```
-rw-r--r-- 1 tkuter tkuter 7187 mar  6 17:16 magento2_en_catalog_product.mapping.2020-03-06T17:16:01.json
-rw-r--r-- 1 tkuter tkuter 7187 mar  6 17:18 magento2_en_catalog_product.mapping.2020-03-06T17:18:01.json
-rw-r--r-- 1 tkuter tkuter 6138 mar  6 17:20 magento2_en_catalog_product.mapping.2020-03-06T17:20:01.json
-rw-r--r-- 1 tkuter tkuter 6457 mar  6 17:22 magento2_en_catalog_product.mapping.2020-03-06T17:22:01.json
-rw-r--r-- 1 tkuter tkuter 6572 mar  6 17:24 magento2_en_catalog_product.mapping.2020-03-06T17:24:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:26 magento2_en_catalog_product.mapping.2020-03-06T17:26:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:28 magento2_en_catalog_product.mapping.2020-03-06T17:28:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:30 magento2_en_catalog_product.mapping.2020-03-06T17:30:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:32 magento2_en_catalog_product.mapping.2020-03-06T17:32:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:34 magento2_en_catalog_product.mapping.2020-03-06T17:34:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:36 magento2_en_catalog_product.mapping.2020-03-06T17:36:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:38 magento2_en_catalog_product.mapping.2020-03-06T17:38:01.json
-rw-r--r-- 1 tkuter tkuter 6328 mar  6 17:40 magento2_en_catalog_product.mapping.2020-03-06T17:40:01.json
```
As you can see there are some files with different size after the failure.
Valid size is 7187 bytes.

In next few minutes mapping was changing.

This time problem was fixed after two reindexes.

Could you help me to investigate those files?

At first I can see that index was changed from ```magento2_en_catalog_product_20200306_054400``` to ```magento2_en_catalog_product_20200306_040653```.
I cannot say why and how this happened.

When you try to compare ```magento2_en_catalog_product.mapping.2020-03-06T17:16:01.json``` with ```magento2_en_catalog_product.mapping.2020-03-06T17:26:01.json``` you will see that attributes are not mapped in right way - almost all were switched to different types.

[mapping.zip](https://github.com/Smile-SA/elasticsuite/files/4299434/mapping.zip)

**Comment by romainruaud** [comment]
Hi @tkuter-pl 

what's the situation on this one ?

Regards
