### ISSUE TITLE
Search box: Suggestions are showing even when user enter 3 spaces.

### ISSUE THREAD

**Issue by nandigowda** [Smile-SA/elasticsuite#1686]
### Preconditions

We have over 20 Categories and 40 products
Elasticsearch version = 6.8.6
Elasticsuite module setting on admin

Magento Version : 2.3.3 CE

ElasticSuite Version :

Environment : 2.8.3

Third party modules :
Vnecoms_Core
Vnecoms_Sms
Vnecoms_SmsKsaSms
Ced_SmsaShipping

### Steps to reproduce

1. Enter 3 spaces in search bar.
2. It will show some product list for blank spaces also

### Expected result

1. It should trim the actual keywords enter in the search box

### Actual result

1. [Screenshot, logs]
![space suggestion](https://user-images.githubusercontent.com/58467827/73644031-9cee6b00-469a-11ea-8830-8adee97d69df.png)

**Comment by romainruaud** [comment]
Acknowledge, this can be reproduced on demo env : http://demo.magento-elastic-suite.io/
