### ISSUE TITLE
Global facet management

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1687]
I can't seem to find a way to manage facets at a global level. Is this possible?

I see there is category level management under `Display`. However a few issue:

1. We have over 500 categories, we want all of them to have the same settings. Setting this per category is tedious. IE sort and display mode
2. How do you manage facets on the search page?

It would seem there should be a global setting for all facets and then the category management would override the global if there is a specific condition that needs to be met for the category.

**Comment by romainruaud** [comment]
Hi @refueledinc 

Settings can be set at a global level on each attribute as described here : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration

This will be applied everywhere on your store (categories and search page). If you define customization for a particular category, this will override the global settings for this category only.

Does it answer to your question ?

Regards

**Comment by refueledinc** [comment]
@romainruaud thanks for the help

Yes, I saw this but how might I set the Display Mode at a global level? For example, we want some attributes to show in expanded mode all the time, while others should not show the options until expanded by the user. It would also be nice to set the expanded facet on the attribute. For example, some attributes should only collapse after 5 options, while others collapse after 3. This is a config option, but it really should be on the attribute for more flexibility.

**Comment by romainruaud** [comment]
What do you mean by "should only collapse after 5 options" ? If you set a "Facet max Size" to 5, only the first 5 values of the attribute will be shown in the filter, and a "Show more" button will be displayed.

Or you are speaking only about the number of "expanded" filters on the search result page ?

**Comment by refueledinc** [comment]
Ok, after reading the doc page it makes more sense. The attribute has helper text of "Max number of values returned by a facet query." so I wrongly assumed this meant a maximum of X values would be returned (not hidden by show more)

**Comment by romainruaud** [comment]
Great, may we close this ?
