### ISSUE TITLE
Swatches attribute edit options

### ISSUE THREAD

**Issue by ziiljuks** [Smile-SA/elasticsuite#1692]
### Preconditions
Existing atribute with multiple options.

Magento Version : 2.3.3
ElasticSuite Version : 2.8.4
Environment : Developer and Production

### Steps to reproduce
1. Open swatch attribute edit

### Expected result
1. See existing options

### Actual result
![Screenshot from 2020-02-05 12-40-33](https://user-images.githubusercontent.com/423835/73834976-53765b00-4815-11ea-8445-fe06f44d3951.png)

There are no js errors.
When I comment out setTemplate from module-elasticsuite-catalog/view/adminhtml/layout/catalog_product_attribute_edit.xml, then it show default magento block but it works.

**Comment by rbayet** [comment]
Hello @ziiljuks,

I cannot reproduce your issue on a 2.3.4 (CE or EE) in production mode.

With version of Magento 2 2.3.3 are you using ? The CE/OpenSource or the EE/Commerce version ?
Do you see the issue in developer or production mode ?
Was the attribute created manually or through a setup ?

Regards,

**Comment by rbayet** [comment]
Helo @ziiljuks,

I cannot reproduce your issue on a 2.3.3 (CE or EE) either.
What is weird on your screenshot is that :

- the "**Storefront Properties**" tab is missing
- the "**Use Product Image for Swatch if Possible**" field is visible while it is only supposed to be shown when the catalog input type is set on "**Visual Swatch**", not "**Text Swatch**".

I might be wrong, but I'd blame either invalid attribute creation through setup, or a third party extension collision.

Regards,
