### ISSUE TITLE
Category pagination with page selected and 'show all' shows empty result

### ISSUE THREAD

**Issue by lcampanella-wh** [Smile-SA/elasticsuite#1693]
### Preconditions
PHP 7.2
Magento 2.3.3 Enterprise (developer mode)
Magento patch applied: Catalog pagination issue on Elasticsearch 6.x patch for Magento 2.3.3 
ElasticSuite Version: 2.8.4
Elasticsearch 6.5.4

Third party modules : none

### Steps to reproduce

1. Add some products to a category to use pagination in the frontend
2. Refresh indexes
3. Access category in the frontend
4. Change to any page (3 for instance) on product listing
5. Click in "All" in dropdown to show all products
6. Url should look like: <base_url>/category.html?p=3&product_list_limit=all

### Expected result

All products for given category should be shown

### Actual result

No products are found, screen with this text is shown:
We can't find products matching the selection.

This was tested on a newly created Magento instance, no other 3rd party code is present besides ElasticSuite.

Thanks.

**Comment by rbayet** [comment]
Hello @lcampanella-wh, 

Concerning
> Magento patch applied: Catalog pagination issue on Elasticsearch 6.x patch for Magento 2.3.3

Are your referring to 

- https://support.magento.com/hc/en-us/articles/360035142371-Catalog-pagination-doesn-t-work-when-Elasticsearch-6-x-is-used 
- https://github.com/magento/magento2/issues/25378

Have you installed this patch before moving to Elasticsuite ?
Or had you already a pagination issue with Elasticsuite and decided to apply this patch ?

Regards,

**Comment by tina-trenkner** [comment]
Hi there, 

Bug is evident on the ElasticSuite demo store. I can replicate @lcampanella-wh 's exact steps to replicate the issue on the demo store. 

PRECONDITIONS:
Whatever is used on the demo store. I have also seen this on builds with M2 Open Source 2.3.2, 2.3.4; ElasticSuite ~2.8.0; ^2.8

STEPS TO REPRODUCE:
1. Visit http://demo.magento-elastic-suite.io/index.php/women/tops-women.html
2. Click on page 2 on Women's Tops category page
3. On the product qty to show on page dropdown, choose "All"
4. URL appears as http://demo.magento-elastic-suite.io/index.php/women/tops-women.html?p=2&product_list_limit=all

EXPECTED RESULT:
User should be able to see all products in the category

ACTUAL RESULT: 
No products are found, screen with this text is shown:
We can't find products matching the selection.
<img width="1332" alt="Screen Shot 2020-04-06 at 6 13 29 AM" src="https://user-images.githubusercontent.com/17261934/78506469-ca0be680-77cd-11ea-81be-836c824d40c1.png">

Please investigate? Thanks

**Comment by mautz-et-tong** [comment]
Please reopen as this is still present on 2.8.x

**Comment by gaiterjones** [comment]
I think this is a Magento bug fixed in 2.4.0. See https://github.com/magento/magento2/pull/28015

**Comment by rbayet** [comment]
Fixed by #1993 along with #1986
