### ISSUE TITLE
Content Type Parameter - elasticsearch server 6.x

### ISSUE THREAD

**Issue by jalung** [Smile-SA/elasticsuite#1700]
Perusing the logs, all the curl request are without the Content Type argument. The question is whether the module is working properly, since the elastic server requires it.
### Preconditions

Reference
`https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests`
> In earlier releases of Elasticsearch, the content-type was optional, and if it was missing or not recognised, then the server would sniff the content and make an educated guess regarding the content-type. That will no longer happen in Elasticsearch 6.0 - every incoming request needs to have the correct content-type for the body it contains.

> This ability to enforce strict content-type checking has existed since Elasticsearch 5.3 via the http.content_type.required configuration setting. In 5.x it is optional, and defaults to false, in Elasticsearch 6.0, that setting defaults to true, and there is no way to disable it. 

> If you regularly use curl or another command line tool to send data into Elasticsearch, you’ll need to add the Content-Type header to any request that contains a body. For curl, that means adding -H'Content-Type: application/json' to the command line of any request that has a JSON body

Magento Version :2.3.4

ElasticSuite Version :2.8.4

Environment :default

Third party modules :Dss-html-sitemap

### Steps to reproduce

1.Turn on debug in module and read the logs
2.
3.

### Expected result

1. To see in the logs:
`curl -XPOST 'http://localhost:9200/magento2_electronics/product/_search?pretty=true' -H'Content-Type: application/json' -d ...
`

### Actual result

1. [Screenshot, logs]
`curl -XPOST 'http://localhost:9200/magento2_electronics/product/_search?pretty=true'  -d ...
`

**Comment by romainruaud** [comment]
Hi,

connection to the elasticsearch server is handled by the official elasticsearch php client : https://github.com/elastic/elasticsearch-php

The client is also dumping the *example* curl requests into the log files.

I'm pretty sure the official client is handling this properly.

Regards
