### ISSUE TITLE
Price slider doesn't drag in mobile

### ISSUE THREAD

**Issue by test4295** [Smile-SA/elasticsuite#1701]
Preconditions
Magento Version : CE 2.3.2
ElasticSuite Version : 2.8.3

Expected result
1 Range slider moves in all view like desktop

Actual result
1 Range slider doesn't work in mobile

**Comment by rbayet** [comment]
The range slider does work in mobile, please see my [comment](https://github.com/Smile-SA/elasticsuite/issues/1578#issuecomment-543098658) in #1578

Regards,
