### ISSUE TITLE
Numeric properties are not validated by the tracker and can cause ES to crash

### ISSUE THREAD

**Issue by palviggi-flagbit** [Smile-SA/elasticsuite#1702]
Using invalid values for the numeric properties of the tracker, Elastic Search will fail when processing the index because they can't be interpreted correctly. Eventually the constant exceptions can cause an OOM.
The store was hit by a burp suite scan and ended with this problem.
It is related to PR #975. I fixed it by removing the data for the day and adding an event processor that converts all the properties marked as numbers in elasticsuite_indices.xml.

### Preconditions

Tracker is enabled

Magento Version : 2.3.3 CE

ElasticSearch Version: 5.6.12

ElasticSuite Version : 2.8.3

Environment : Production

Third party modules : not related

### Steps to reproduce

1. visit on the site this url "/elasticsuite/tracker/hit/image/h.png?page[store_id]=2&page[type][identifier]=catalog_category_view&page[type][label]=Catalog%20Category&page[category][id]=507&page[category][label]=My%20Category&page[category][path]=1%2F175%2F507&page[product_list][page_count]=65&page[product_list][product_count]=645&page[product_list][current_page]=1&page[product_list][sort_order]=topseller&page[product_list][sort_direction]=asc&page[product_list][display_mode]=list&session[uid]=5550-1ba5-186a-8c8bed9dd257&session[vid]=7fd0-57d1-3e69-fd7525c4ee45&page[site]=www.example.com&page[url]=%2Fmy-category&page[title]=My%20Category&page[referrer][domain]=www.example.com&page[referrer][page]=%2Fmy-category&page[resolution][x]=128055835307'%20or%20'3426'%3d'3426&page[resolution][y]=984"  (labels and uid were changed). note the page.resolution.x value
2. in the database, the invalid string will be saved 

### Expected result

1. Everything works normally

### Actual result

1. this appears constantly on the ES logs.
```
[DEBUG][o.e.a.b.TransportShardBulkAction] [3RmGevj] [magento2-prod_example_tracking_log_event_20200124][0] failed to execute bulk item (index) BulkShardRequest [[magento2-prod_example_tracking_log_event_20200124][0]] containing [1792] requests
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [page.resolution.x]
[... trace]
Caused by: java.lang.NumberFormatException: For input string: "128055835307' or '3426'='3426"
```

**Comment by southerncomputer** [comment]
I had keys get into my table with value INF , which caused the deleteevents function to go crazy until i added a column INF to the table (hack), not sure how those values got into the tracker tables but it jammed up debug.log etc with tons of huge queries failing!

**Comment by rbayet** [comment]
Hi @southerncomputer,

Could you create a separate issue for that one so I can address it properly if need be ?

Regards,
