### ISSUE TITLE
Wrong virtual type declaration

### ISSUE THREAD

**Issue by thomas-kl1** [Smile-SA/elasticsuite#1713]
Following virtual type shouldn't extend Magento\Config\Model\Config\Structure\Data but Magento\Framework\Config\Data\Scoped

```
    <virtualType name="Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data" type="Magento\Config\Model\Config\Structure\Data">
        <arguments>
            <argument name="reader" xsi:type="object">Smile\ElasticsuiteCore\Search\Request\RelevanceConfig\Structure\Reader</argument>
            <argument name="cacheId" xsi:type="string">smile_elasticsuite_relevance_configuration_structure</argument>
        </arguments>
    </virtualType>
```

Indeed Magento\Config\Model\Config\Structure\Data is concrete implementation for magento system config.
Please use the generic one: Magento\Framework\Config\Data\Scoped

**Comment by romainruaud** [comment]
Hi @thomas-kl1 

Probably the generic one did not exist when we wrote this part of ElasticSuite (it was written a long time ago).

Can you propose a PR for this fix ? 

Regards

**Comment by rbayet** [comment]
Hello @thomas-kl1,

Actually, I don't see the reasoning behind this issue.

`Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data` is not the only class extending Magento\Config ones.
A good portion of the RelevanceConfig related code piggybacks on Magento\Config.
So why singling out `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data` ?

Regards,

**Comment by thomas-kl1** [comment]
What are the other class extending Magento\Config\Model\Config\Structure\Data?

**Comment by rbayet** [comment]
> What are the other class extending Magento\Config\Model\Config\Structure\Data?

That's not quite what I said when I said 

> `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data` is not the only class extending Magento\Config ones.

My point is **besides** `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data` extending `Magento\Config\Model\Config\Structure\Data`, we also have, **also through virtualType** : 
- `Smile\ElasticsuiteCore\Search\Request\RelevanceConfig\Structure\Reader` extending `Magento\Config\Model\Config\S`tructure\Reader`
- `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure` extending `Magento\Config\Model\Config\Structure`
- `Smile\ElasticsuiteCore\Controller\Adminhtml\Search\Request\RelevanceConfig\SectionChecker` extending `Magento\Config\Controller\Adminhtml\System\ConfigSectionChecker`
- `Smile\ElasticsuiteCore\Block\Adminhtml\Search\Request\RelevanceConfig\Form\FieldFactory` extending `Magento\Config\Block\System\Config\Form\Field\Factory`
- `Smile\ElasticsuiteCore\Block\Adminhtml\Search\Request\RelevanceConfig\Tabs` extending `Magento\Config\Block\System\Config\Tabs`
- `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Iterator\Group` extending `Magento\Config\Model\Config\Structure\Element\Iterator\Group`
- `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Iterator\Tab` extending `Magento\Config\Model\Config\Structure\Element\Iterator\Tab`
- `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Tab` extending `Magento\Config\Model\Config\Structure\Element\Tab`
- `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Element\Iterator\Section` extending `Magento\Config\Model\Config\Structure\Element\Iterator\Section`
- `relevanceDependencyMapper` extending `Magento\Config\Model\Config\Structure\Element\Dependency\Mapper\Proxy`

So what is the exact reason for wanting to change the parent class of `Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data` ?
Is there an issue that we are not aware of ?

Regards,

**Comment by thomas-kl1** [comment]
I forgot the following part: <virtualType name="Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure" type="Magento\Config\Model\Config\Structure" shared="false">...</...>

I don't understand why the relevance config is not in store settings, but it's my personal opinion and has nothing to do here. My bad.

**Comment by rbayet** [comment]
Hi @thomas-kl1,

I guess the initial idea was to have the custom scope path `default / container / store ` instead of  `default / website / store` and having to push into that the notion of dynamic containers (initially the autocomplete specific container did not exist).
There are modules which dynamically create series of system config fields, so the module could probably have gone that way, but I guess this was both an aesthetic oriented design choice and related to the need of a custom, clean UX.

Don't worry, we don't have any problem with people voicing their opinion in a civilized manner :)

Regards,

**Comment by thomas-kl1** [comment]
Last point, I had an issue on a project where there were some third party modules with plugins on the Magento\Config\Model\Config\Structure\Data class, and it throws exception with the Smile\ElasticsuiteCore\Model\Search\Request\RelevanceConfig\Structure\Data. But I've fixed the module which actually had the "real issue".
