### ISSUE TITLE
Magento cloud build in staging env is failing because of the module

### ISSUE THREAD

**Issue by archanab20** [Smile-SA/elasticsuite#1714]
Magento cloud build in staging env is failing because of the module.This is working as expected in Integration environment . 

### Preconditions

We are using Smile elastic suite as our search engine .
We have configured it as per the document mentioned here : https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall

We have followed all the steps and is working fine on our all 3 integration environments .
When we are pushing the code to staging environment the deployment is failing .

Magento Version :EE

ElasticSuite Version : 2.8

Environment : production.

Third party modules :
Vertex_Tax
WeltPixel_Backend
WeltPixel_Quickview
Yotpo_Yotpo
Tawk_Widget
Temando_Shipping
IWD_All
IWD_Opc
MageClass_ClickAndCollect
Magecomp_Extrafee
Mageplaza_Core
Mageplaza_Blog
Mageplaza_AjaxLayer
Mageplaza_LayeredNavigation
Mageplaza_Search
Mageplaza_SocialLogin
Magestore_Bannerslider
Smile_ElasticsuiteCore
Smartwave_Megamenu
Smartwave_Porto
Smartwave_Core
Smartwave_Dailydeals
Smartwave_Filterproducts
Smartwave_Socialfeeds
### Steps to reproduce

1.While pushing the code from cloud integration environment to staging . 
2.
3.

### Expected result

1. build should complete successfully . 

### Actual result

1. And var/log/install_upgrade.log:

Module 'Preface_ShowSubCategory':
Module 'Preface_SmsIntegration':
Module 'Preface_StaticContent':
Module 'Preface_TicketManager':
Module 'Preface_TicketEmail':
Module 'Smartwave_Core':
Module 'Smartwave_Dailydeals':
Module 'Smartwave_Filterproducts':
Module 'Preface_MegaMenu':
Module 'Smartwave_Porto':
Module 'Smartwave_Socialfeeds':
Module 'Smile_ElasticsuiteAdminNotification':
Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

So it looks like it cannot connect to ElasticSearch. However I can:
fmr5km4b3vwiy_stg@i-0c416ee3a8a042d41:~/var/log$ curl localhost:9200/_cat/nodes?v
ip          heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
192.168.6.6           32          85   1    0.07    0.11     0.09 mdi       *      46p6hka
192.168.5.5           40          86   2    0.10    0.13     0.10 mdi       -      P2uK5fn
192.168.7.7           29          85   1    0.07    0.11     0.09 mdi       -      ZGHrc4l

Elastic server is working as expected .

**Comment by UgoTurner** [comment]
Did you update your `env.php` ? Look at this issue : https://github.com/Smile-SA/elasticsuite/issues/1002

**Comment by archanab20** [comment]
@UgoTurner  This is for community edition . Is there any way for cloud edition to work on staging environment similarly .

**Comment by rbayet** [comment]
Hello @ryanisn,

If you followed https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#ensure-proper-configuration-for-elasticsuite-host, please check that your Elasticsearch server instance for the staging environment is indeed available at **elasticsearch.internal**.

There might have been naming convention changes that do not know about yet.

Regards,

**Comment by rbayet** [comment]
Bumping this because I some managed to reference someone else instead of @archanab20 in my comment above :/
