### ISSUE TITLE
ElasticSuite Layered Navigation not rendering on front end.

### ISSUE THREAD

**Issue by stephenLigo** [Smile-SA/elasticsuite#1715]
### Preconditions

Cent OS 7
PHP 7.3

Magento Version : 2.3.4

ElasticSuite Version : 2.8.4

Environment : Developer

Third party modules : Codazon Infiniti Template with Ajax Layered Navigation

### Steps to reproduce

1. Install and set up Elastic Search 6+
2. Install and set up Elastic Suite 2.8.4
3. Check connection, upgrade, clear cache and configure modules

### Expected result

1. Left hand Layered Navigation configured as expected

### Actual result

1. [Screenshot, logs] No layered navigation with any filters. Tried disabling template layered nav/magento layered nav and MagePlaza layered nav (Disabled)

No errors or warnings in dev panel.

**Comment by rbayet** [comment]
Hello @stephenLigo,

I'd go with disabling the "Codazon Infiniti Template with Ajax Layered Navigation" (if you haven't already done it) module and check what happens.

Long story short: Elasticsuite provides its own layered navigation. Codazon Infiniti Template with Ajax Layered Navigation, by the look of its name, probably does too, maybe by extending the native one, but more probably by replacing the native blocks, as ElasticsuiteCatalog does.

There are probable collisions in terms of layout : a module A can perfectly replace module B's blocks without any errors or warnings.

Regards,

**Comment by radub** [comment]
> I also have issues displaying attributes in the frontend layered navigation. I have an attribute which I want to use. I'm using M2.4.4 with the luma theme with small customisations in terms of styling (css and js). I have removed smile/elasticsuite and the attribute **is displayed**. When I install smile/elasticsuite, the attribute is no longer displayed. Below are the attribute specifications from the data patch:
> 
> ```
> [
>     'type' => 'int',
>     'label' => 'Is Quick Ship',
>     'input' => 'boolean',
>     'source' => Boolean::class,
>     'required' => false,
>     'sort_order' => '13',
>     'global' => ScopedAttributeInterface::SCOPE_GLOBAL,
>     'default' => '1',
>     'visible' => true,
>     'user_defined' => true,
>     'searchable' => false,
>     'filterable' => false,
>     'comparable' => false,
>     'visible_on_front' => false,
>     'unique' => false,
>     'group' => 'General',
>     'used_in_product_listing' => false,
>     'is_used_in_grid' => true,
>     'is_visible_in_grid' => false,
>     'is_filterable_in_grid' => true
> ]
> ```
> 
> Any thoughts?

Fur future reference:
This is actually expected as ElasticSuite renders the Layered Navigation Attributes based on relevance (enough values for the attribute). Also rendering can be forced by setting the Always Display on the attribute in the Design Settings on each category.
