### ISSUE TITLE
Composer install Error

### ISSUE THREAD

**Issue by mariusik88** [Smile-SA/elasticsuite#1719]
### Preconditions

PHP 7.3 

Magento Version : 2.3.4

ElasticSuite Version : 2.8.x

Environment : Default mode

### Steps to reproduce

omposer require smile/elasticsuite ~2.8.0
./composer.json has been updated

Fatal error: Uncaught TypeError: Return value of Magento\InventoryComposerInstaller\Plugin_composer_tmp1::initModuleDeployment() must be an instance of Magento\InventoryComposerInstaller\void, none returned in phar:///opt/cpanel/composer/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code:69
Stack trace:
#0 [internal function]: Magento\InventoryComposerInstaller\Plugin_composer_tmp1->initModuleDeployment(Object(Composer\Script\Event))
#1 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#2 phar:///opt/cpanel/composer/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///opt/cpanel/composer/bin/composer/src/Composer/Installer.php(205): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-update-cmd', true)
#4 phar:///opt/cpanel/composer/bin/composer/src/Composer/Command/RequireCommand.php(20 in phar:///opt/cpanel/composer/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code on line 69

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by rbayet** [comment]
Hello @mariusik88,

I don't have any issue with composer 1.9 and PHP 7.2.24.

I would go for a general PHP compatibility issue, nothing specific to Elasticsuite, considering where the error is thrown.
I know that 
> [Magento recommends using PHP 7.3](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php)

But give it a shot to downgrade to the latest PHP 7.2...
If you google that error, you will find that error in many different contexts.

Regards

**Comment by romainruaud** [comment]
Our Travis instance is running daily Elasticsuite install from scratch, for all Magento 2.3.x versions on PHP 7.2 and 7.3, and there is no issue on Composer.

As previously said, you might have an issue related to using a too old Composer version (not supporting PHP 7.3) or something like this.

Since it's not related to Elasticsuite, I close.

regards
