### ISSUE TITLE
Singular / plural in price fork

### ISSUE THREAD

**Issue by axelmo-smile** [Smile-SA/elasticsuite#1721]
### Preconditions

Magento Version : 2.2.11

ElasticSuite Version : 2.6.10

Environment : pre-production

### Steps to reproduce

1. Choose a category
2. Play with the price fork to have only one product 

### Expected result

1. In French we should have "1 produit" (singular)

### Actual result

1. We have "1 produits" (plural)

![wording orthographe pluriel](https://user-images.githubusercontent.com/61463570/75253543-0287d000-57df-11ea-8df6-d8494abf1620.JPG)

I can give you an access (private message) if you want.

**Comment by rbayet** [comment]
Hello @axelmo-smile,

I was going to brush it off saying that as Magento2 still does not offer a singular/plural aware i18n/10n mechanism and actually in its own templates, usually does not make the distinction, we chose not to.

Problem is, at least in 2.3.4, it's not easy anymore to find such an example.
So I guess we could do what is done in the mini-cart :
![Sélection_865](https://user-images.githubusercontent.com/2353374/76000507-1977a200-5f04-11ea-9a32-2e479da701c4.png)
![Sélection_866](https://user-images.githubusercontent.com/2353374/76000514-1c729280-5f04-11ea-8c3d-8ed15420e700.png)

... and introduce a messageTemplates.displayOne properties in our `src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js`.

Unfortunately, the 2.6.10 was probably our last Elasticsuite release for M2 2.2.x, considering it's near EOL (I'll confirm with @romainruaud).
If so, you would probably have to backport the changes yourself. :|

Regards,

**Comment by romainruaud** [comment]
We will not backport this since it's a non-blocker / very minor issue.

Magento 2.2 is EOL so we will only backport security / breaking issues.

Regards

**Comment by axelmo-smile** [comment]
Hello ! 

Thanks for your feedback.
