### ISSUE TITLE
How come my elasticsearch doc count is greater than number of items?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#1729]
**Is your question related to a problem? Please describe.**
A clear and concise description of what the problem is. 

green  open   magento2_default_catalog_category_20200223_092135 3IGpQ8UtSXelH960P0dvww   2   0        751          209        1mb            1mb
green  open   magento2_default_catalog_product_20200223_131509  OiV-Udx3SUSgn_CZnie7sA   2   0   12984806       211172    108.1gb        108.1gb

mysql> select count(*) from catalog_product_entity;
+----------+
| count(*) |
+----------+
|  3048938 |
+----------+
1 row in set (0.56 sec)

All simple products no children/parent relationships..

Just curious how the doc count is far greater than number of products?

**Additional context**
Add any other context or screenshots about your question here.

**Comment by rbayet** [comment]
Hello @southerncomputer,

The document count contains also documents which are created for [nested fields ](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/nested.html)

For the product index that will be :

- **category** properties (categories where the product is attached/visible/positioned/blacklisted)
- **price** properties (one entry per customer group)
- **search_query** properties (search queries for which the product is positioned/blacklisted)

See [this example in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/nested.html#_limits_on_nested_mappings_and_objects)
> As described earlier, each nested object is indexed as a separate document under the hood. Continuing with the example above, if we indexed a single document containing 100 user objects, then 101 Lucene documents would be created — one for the parent document, and one for each nested object

Regards,
