### ISSUE TITLE
why there is only title in autocomplte?

### ISSUE THREAD

**Issue by chenghuili** [Smile-SA/elasticsuite#1730]
why there is only title in autocomplte? how to display product image, price and sku ?
<img width="617" alt="Screen Shot 2020-03-01 at 13 56 19" src="https://user-images.githubusercontent.com/14212956/75620491-8fa69c80-5bc4-11ea-9813-751020c59140.png">

**Comment by rbayet** [comment]
As this does not look like a response made only out of search queries (native autocomplete without Elasticsuite), the most likely is that Elasticsuite is not really the one providing the answers.
This might be a custom theme issue or a conflict with a third party module.

I would recommend you to look at the autocomplete ajax response structure on our demo.
If the structure is not the same : it's not Elasticsuite providing the response.
If the structure is the same : this is a theming/javascript conflict.

Regards,
