### ISSUE TITLE
Elasticsearch API call is returning null

### ISSUE THREAD

**Issue by tajveez-73** [Smile-SA/elasticsuite#1732]
Hi,

I am making catalog product API call to URL `http://<website_url>:9200/magento2_default_catalog_product/_search` with post data `{"query":{"bool":{"must":[{"query_string":{"default_field":"_all","query":"white"}}],"must_not":[],"should":[]}},"from":0,"size":100,"sort":[],"aggs":{}}` and i am getting `{
"took": 0,
"timed_out": false,
"_shards": {
"total": 1,
"successful": 1,
"skipped": 0,
"failed": 0
},
"hits": {
"total": 0,
"max_score": null,
"hits": [ ]
}
}` i don't understand whats wrong because i did the same call with simple elasticsearch (before installing elasticsuite) it was returning correct result. now i am getting nothing.

my Magento version: 2.3
Elasticsearch version: 5.6.11
Elasticsuite version: 2.8.0

**Comment by rbayet** [comment]
Hello @tajveez-73,

We disable the `_all` field on all our indices 
![Sélection_863](https://user-images.githubusercontent.com/2353374/75699671-20f33d00-5cb1-11ea-8fdf-66a8e4f398c6.png)
So you need to change your `default_field` query parameter accordingly.

What you could use instead is the `search` default field where all searchable attribute content or entity meta-data is copied to.
`{"query":{"bool":{"must":[{"query_string":{"default_field":"searchl","query":"white"}}],"must_not":[],"should":[]}},"from":0,"size":100,"sort":[],"aggs":{}}`

We also rely on the `spelling` field which contains all the content for searchable attribute / meta-data for which fuzzy search is enabled.

Regards,
