### ISSUE TITLE
{"type":"illegal_argument_exception","reason":"Unknown filter type {phonetic} for {phonetic},"status":400}

### ISSUE THREAD

**Issue by sngraphics1** [Smile-SA/elasticsuite#1735]
Trying to install elasticsuite on AWS instance of Bitnami's certified Magento 2.3 community image in developer mode.

### Steps to reproduce

```
1. $ sudo composer require smile/elasticsuite ~2.8.0
2. $ sudo bin/magento-cli setup:upgrade
```

### Expected result
`1. bin/magento-cli setup:upgrade completes
`
### Actual result
```
Module 'Smile_ElasticsuiteAdminNotification':
Module 'Smile_ElasticsuiteCore':
Module 'Smile_ElasticsuiteCatalog':
Installing data... {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}
bitnami@ip-172-31-32-20:~/apps/magento/htdocs$
```

**Comment by sngraphics1** [comment]
exception.log

```
[2020-03-04 21:46:26] main.CRITICAL: Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.5.1
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.2.0
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.4.1 {"report_id":"53b8bac4bcf62514f550218fdbba753b7ca9840c352288365e1bdc58d97847c8","exception":"[object] (Magento\\Framework\$
```

**Comment by rbayet** [comment]
Hello @sngraphics1,

You're missing Elasticsearch server requirements: [the phonetic and icu plugins](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x#installing-required-plugins).

Regards,

**Comment by TheRealHunzik** [comment]
> Hello @sngraphics1,
> 
> You're missing Elasticsearch server requirements: [the phonetic and icu plugins](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-6.x#installing-required-plugins).
> 
> Regards,


Hello @rbayet 

I have Magento 2.3

Here is My Installed Plugin List

![Screenshot from 2021-03-08 12-52-17](https://user-images.githubusercontent.com/51072292/110291196-758c6f00-800d-11eb-8548-d5ad912cf7e0.png)

Here is My Elastic Search

![Screenshot from 2021-03-08 12-55-21](https://user-images.githubusercontent.com/51072292/110291302-981e8800-800d-11eb-9c96-d3d59e4f81cb.png)


And When i Re index I am still getting this issue

![Screenshot from 2021-03-08 12-53-52](https://user-images.githubusercontent.com/51072292/110291414-bab0a100-800d-11eb-817c-183e32ed3247.png)



Please Guide me

**Comment by ramindas** [comment]
Hi,

This works for me, thanks Ali

cd /usr/share/elasticsearch
bin/elasticsearch-plugin install analysis-phonetic
bin/elasticsearch-plugin install analysis-icu
sudo service elasticsearch restart

Thanks, Raminda

**Comment by gvasilakiss** [comment]
> Hi,
> 
> This works for me, thanks Ali
> 
> cd /usr/share/elasticsearch bin/elasticsearch-plugin install analysis-phonetic bin/elasticsearch-plugin install analysis-icu sudo service elasticsearch restart
> 
> Thanks, Raminda

Saved me!

**Comment by sharathkvdckap** [comment]
> Hi,
> 
> This works for me, thanks Ali
> 
> cd /usr/share/elasticsearch bin/elasticsearch-plugin install analysis-phonetic bin/elasticsearch-plugin install analysis-icu sudo service elasticsearch restart
> 
> Thanks, Raminda

Saved me..!!!! Thank you
