### ISSUE TITLE
Update the wiki to present the "Based on attribute value" search optimizer

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/elasticsuite#1740]
**Is your feature request related to a problem? Please describe.**
The wiki [describes the "**Model**" property](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers) of search optimizer with 

> The model to use for scoring. Actually only Constant model can be chosen. Additional models will come in future versions.

But the "Based on attribute value" has been existing for a while now.
![Model selection](https://user-images.githubusercontent.com/2353374/76005799-d02b5080-5f0b-11ea-9b48-2c0c1d98b484.png)

**Describe the solution you'd like**
Update the [wiki page](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers) of search optimizers to describe the "Based on attribute value" optimizers and the extra parameters they provide, etc.

**Comment by romainruaud** [comment]
done
