### ISSUE TITLE
Manual sort order being removed

### ISSUE THREAD

**Issue by jarcorreia** [Smile-SA/elasticsuite#1750]
**Is your question related to a problem? Please describe.**
Magento 2.3.1 Commerce
Elasticsuite 2.8.1

We have a client of ours which states that many times the products in categories are losing the manual sorting they gave to them, but can't pin point when it happens precisely. I performed a lot of tests on this and I can't seem to reproduce the issue.

- Do you have any knowledge of products in categories losing it's manual sort order?

**Comment by thampe** [comment]
Hi,

there are serveral PRs that could fix the issue: 

* #1543
* #1632

As far as I know none of them are merged.

**Comment by jarcorreia** [comment]
We weren't yet able to replicate this issue in a consistent way.

I'm closing this down until we find how to replicate time and time again.

**Comment by jarcorreia** [comment]
Thank you @thampe for your help.
