### ISSUE TITLE
Getting error illegal_argument_exception while installing on Magento 2.3

### ISSUE THREAD

**Issue by tajveez-73** [Smile-SA/elasticsuite#1751]
Hi, 

While installing elasticsuite on my Magento I get following error when i run Magento's setup:upgrade command:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [0] for setting [index.max_result_window] must be >= 1"}],"type":"illegal_argument_exception","reason":"Failed to parse value [0] for setting [index.max_result_window] must be >= 1"},"status":400}`

Magento v2.3
Elasticsearch v5.6.11
Elasticsuite v2.8.5

**Comment by androshchuk** [comment]
Hello @tajveez-73 

It seems we have a problem with the installation sequence of modules.
Do you have Magento_ConfigurableSampleData in your instance?
Please provide a list of all modules.

You can fix it now:
1. Set config manually:
`bin/magento config:set smile_elasticsuite_core_base_settings/indices_settings/number_of_shards 1`
2. Run Magento's setup:upgrade:
`bin/magento setup:upgrade`

Regards

**Comment by tajveez-73** [comment]
Hello @androshchuk 

Here's list of modules
`Magento_AdminAnalytics
Magento_Store
Magento_AdvancedPricingImportExport
Magento_Directory
Magento_Amqp
Magento_AmqpStore
Magento_Config
Magento_Theme
Magento_Backend
Magento_Variable
Magento_Eav
Magento_Customer
Magento_AuthorizenetGraphQl
Magento_Search
Magento_Backup
Magento_AdminNotification
Magento_BraintreeGraphQl
Magento_Indexer
Magento_Authorization
Magento_BundleImportExport
Magento_CacheInvalidate
Magento_Cms
Magento_Catalog
Magento_Quote
Magento_Security
Magento_GraphQl
Magento_CatalogImportExport
Magento_Rule
Magento_CatalogInventory
Magento_CatalogRule
Magento_Msrp
Magento_CatalogSearch
Magento_CatalogUrlRewrite
Magento_StoreGraphQl
Magento_Widget
Magento_SalesSequence
Magento_Payment
Magento_CheckoutAgreementsGraphQl
Magento_Sales
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_User
Magento_Checkout
Magento_ConfigurableProduct
Magento_EavGraphQl
Magento_ConfigurableProductSales
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_CurrencySymbol
Magento_Captcha
Magento_Integration
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_Deploy
Magento_Developer
Magento_Dhl
Magento_AsynchronousOperations
Magento_DirectoryGraphQl
Magento_Downloadable
Magento_CatalogGraphQl
Magento_ImportExport
Magento_CardinalCommerce
Magento_BundleGraphQl
Magento_AdvancedSearch
Magento_Elasticsearch
Magento_Email
Magento_EncryptionKey
Magento_Fedex
Magento_GiftMessage
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GoogleShoppingAds
Magento_UrlRewriteGraphQl
Magento_PageCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Magento_Bundle
Magento_InstantPurchase
Magento_Analytics
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogSearch
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductAdminUi
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryImportExport
Magento_InventoryCache
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationAdminUi
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryProductAlert
Magento_InventoryRequisitionList
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventoryExportStock
Magento_InventorySalesAdminUi
Magento_CatalogInventoryGraphQl
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_Shipping
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySourceSelectionApi
Magento_LayeredNavigation
Magento_Marketplace
Magento_MediaStorage
Magento_MessageQueue
Magento_ConfigurableImportExport
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_Multishipping
Magento_MysqlMq
Magento_NewRelicReporting
Magento_Newsletter
Magento_OfflinePayments
Magento_SalesRule
Magento_GraphQlCache
Magento_Authorizenet
Magento_Vault
Magento_Paypal
Magento_QuoteGraphQl
Magento_PaypalCaptcha
Magento_Persistent
Magento_ProductAlert
Magento_ProductVideo
Magento_AuthorizenetAcceptjs
Magento_QuoteAnalytics
Magento_PaypalGraphQl
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_Reports
Magento_RequireJs
Magento_Review
Magento_ReviewAnalytics
Magento_Robots
Magento_Rss
Magento_AuthorizenetCardinal
Magento_CheckoutAgreements
Magento_SalesAnalytics
Magento_SalesGraphQl
Magento_SalesInventory
Magento_OfflineShipping
Magento_Braintree
Magento_UrlRewrite
Magento_Elasticsearch6
Magento_CustomerAnalytics
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_InventoryShippingAdminUi
Magento_Signifyd
Magento_Sitemap
Magento_InventoryGraphQl
Magento_ConfigurableProductGraphQl
Magento_Webapi
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_DownloadableGraphQl
Magento_ThemeGraphQl
Magento_Tinymce3
Magento_Translation
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogUrlRewriteGraphQl
Magento_CatalogAnalytics
Magento_Usps
Magento_CatalogRuleConfigurable
MSP_ReCaptcha
Magento_VaultGraphQl
Magento_Version
Magento_Swagger
Magento_WebapiAsync
Magento_WebapiSecurity
Magento_Weee
Magento_WeeeGraphQl
Magento_CatalogWidget
Magento_Wishlist
Magento_WishlistAnalytics
Magento_WishlistGraphQl
Amazon_Core
Amazon_Login
Amazon_Payment
Bss_AjaxCart
CollectionProduct_CollectionType
Craftyclicks_Ukpostcodelookup
Divante_VsbridgeIndexerCore
Divante_VsbridgeIndexerCms
Divante_VsbridgeIndexerCatalog
Divante_VsbridgeIndexerReview
Divante_VsbridgeIndexerTax
Dotdigitalgroup_Email
Ebizmarts_MandrillSmtp
Ebizmarts_SagePaySuite
Faonni_SalesSequence
Firebear_ImportExport
IWD_All
Iazel_RegenProductUrl
Klarna_Core
Klarna_Ordermanagement
Klarna_Kp
Magento_PaypalReCaptcha
MSP_TwoFactorAuth
Mageplaza_Core
Mageplaza_CronSchedule
Magepow_Categories
Mb_Customizations
Reviewscouk_Reviews
SR_ModifiedSalesOrderGrid
Smile_ElasticsuiteAdminNotification
Smile_ElasticsuiteCore
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteTracker
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteAnalytics
Smile_ElasticsuiteVirtualCategory
Snowdog_CmsApi
Temando_Shipping
Vertex_Tax
Wyomind_Core
Wyomind_DataFeedManager
Yotpo_Yotpo
` 

it had `Magento_SampleData` i disabled it and ran command, now i am getting different error on setup upgrade

`{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_default_catalog_category_], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_default_catalog_category_"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_default_catalog_category_], must not start with '_', '-', or '+'","index_uuid":"_na_","index":"_default_catalog_category_"},"status":400}`

**Comment by androshchuk** [comment]
I think the problem is in the Magento2 setting Elasticsearch Index Prefix or ElasticSuite setting Indices Alias Name. 
Most likely it is empty and you are running a reindex.

**Comment by tajveez-73** [comment]
@androshchuk I have specified Magento2 setting Elasticsearch Index Prefix from the configuration and How to set Elasticsuite Indices Alias name, as the admin configuration are not visible to me because I'm getting this error on setup:upgrade command

**Comment by androshchuk** [comment]
you can do it with via CLI
`bin/magento config:set smile_elasticsuite_core_base_settings/indices_settings/alias magento2`
Also you must set indices_patter
`bin/magento config:set smile_elasticsuite_core_base_settings/indices_settings/indices_pattern {{YYYYMMdd}}_{{HHmmss}}`

**Comment by tajveez-73** [comment]
Thanks, it's working now, except for one thing `magento2_default_catalog_product` index is not being created. all other indexes are being created, I have tried reindexing. but it still isn't coming.

**Comment by androshchuk** [comment]
You probably need to reset some indexers.

Please provide me an output 
`bin/magento indexer:reindex`

**Comment by tajveez-73** [comment]
`Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:00
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:00
Google Product Removal Feed index has been rebuilt successfully in 00:00:00
Google Product Feed index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:01
Vsbridge Cms Block Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Cms Page Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Product Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Category Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Attributes Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Review Indexer index has been rebuilt successfully in 00:00:00
Vsbridge Tax Rule Indexer index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:00
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
ElasticSuite Customer Indexing index has been rebuilt successfully in 00:00:00
`

**Comment by androshchuk** [comment]
It seems that all is well. 

when do you get the error 'magento2_default_catalog_product index is not being created'?

**Comment by tajveez-73** [comment]
when I access `http://localhost:9200/magento2_default_catalog_product` i get `{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"magento2_default_catalog_product","index_uuid":"_na_","index":"magento2_default_catalog_product"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"magento2_default_catalog_product","index_uuid":"_na_","index":"magento2_default_catalog_product"},"status":404}`

It's weird because `magento2_default_catalog_category` is index is present and I can access it.

**Comment by romainruaud** [comment]
@tajveez-73 I see many "VsBridge" module in you logs.

I guess you are using VueStorefront, is it the case ?

**Comment by tajveez-73** [comment]
@romainruaud yes I am. and also the magento's reindexing command doesn't create Elasticsearch's catalog product index, but when saving the product (I have a plugin that reindex product on save) that product is available in `magento2_default_catalog_product` index

**Comment by androshchuk** [comment]
@tajveez-73 we've investigated the issue and it looks like you didn't enable our module before a run 
`bin/magento setup:upgrade`
Please see the documentation:
https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-already-installed-

Regards
