### ISSUE TITLE
BC break for 2.8.5

### ISSUE THREAD

**Issue by quisse** [Smile-SA/elasticsuite#1752]
Magento 2.3.3 compilation breaks when 2.8.5 is installed because of the Magento_CatalogGraphQL dependency (which is introduced in magento 2.3.4). This isn't required in the composer.json

https://github.com/Smile-SA/elasticsuite/blob/02a77e0b38cebdef1dc0177ad99170114da84002/src/module-elasticsuite-catalog/GraphQl/Model/Resolver/Layer/FiltersProvider.php#L18-L19

### Preconditions

Magento Version : 2.3.3

ElasticSuite Version : 2.8.5

Environment : Production

**Comment by romainruaud** [comment]
I agree that it would be supposed to break, but I'm wondering why it's actually not breaking on our Travis build (which features an install and compile) : https://travis-ci.org/github/Smile-SA/elasticsuite/jobs/663975570?utm_medium=notification&utm_source=github_status

**Comment by romainruaud** [comment]
Let me correct myself : "it would be supposed to break" **if you do not have the CatalogGraphQl module**

Did you remove this module ?

**Comment by quisse** [comment]
Hmmm, thought it was newly introduced but it seems not. It is removed from the magento install of the project I'm currently working on.
My apologies for wasting your time.

**Comment by quisse** [comment]
And also thanks for the quick response!
