### ISSUE TITLE
Time out category edit page

### ISSUE THREAD

**Issue by sivasdescalzo** [Smile-SA/elasticsuite#1753]
### Preconditions
Magento Version : Magento Cloud 2.3.4
ElasticSuite Version : 2.8.5
Environment : Production

### Steps to reproduce
1. Going to a Virtual Category in admin, gets time out.
Trace:
…ol called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Platform/
Quote.php (89)
…ol called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Platform/
Quote.php (66)
…As called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Platform/
Quote.php (31)
…d at /app/pklm4qvvunynw/vendor/magento/framework/DB/Select/
ColumnsRenderer.php (56)
…ed at /app/pklm4qvvunynw/vendor/magento/framework/DB/Select/
SelectRenderer.php (71)
…led at /app/pklm4qvvunynw/vendor/magento/framework/DB/Select/
RendererProxy.php (108)
…xy::render called at /app/pklm4qvvunynw/vendor/magento/framework/DB/
Select.php (509)
…at /app/pklm4qvvunynw/vendor/magento/zendframework1/library/Zend/Db/
Select.php (1374)
…called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Adapter/Pdo/
Mysql.php (648)
…called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Adapter/Pdo/
Mysql.php (545)
…called at /app/pklm4qvvunynw/vendor/magento/framework/DB/Adapter/Pdo/
Mysql.php (613)
…lm4qvvunynw/vendor/magento/zendframework1/library/Zend/Db/Adapter/
Abstract.php (828)
…unynw/vendor/magento/module-resource-connections/DB/Adapter/Pdo/
MysqlProxy.php (1300)
…lm4qvvunynw/vendor/magento/framework/EntityManager/Operation/
CheckIfExists.php (78)
…at /app/pklm4qvvunynw/vendor/magento/framework/EntityManager/
EntityManager.php (117)
…p/pklm4qvvunynw/vendor/magento/module-catalog/Model/ResourceModel/
Category.php (1096)
… called at /app/pklm4qvvunynw/vendor/magento/framework/Model/
AbstractModel.php (540)
…dor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/
Rule.php (230)
…dor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/
Rule.php (286)
…dor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/
Rule.php (151)

### Expected result
1. Return category edit page

### Actual result
1. Timeout, it never returns

**Comment by dambrogia** [comment]
Providing more context would be helpful. How many products/categories do you have? What size server are you on? How big is your database? Are you using New Relic? What have you done to profile the request to see where the majority of the latency is occurs?
