### ISSUE TITLE
Stemmer override filter requires either rules or rules_path to be configured

### ISSUE THREAD

**Issue by svencoeck** [Smile-SA/elasticsuite#1757]
We have 4 storeviews for 4 languages (English, Dutch, French and German). Since the update to elasticsuite 2.8.5 the products for the French aren't showing up in the catalog. When trying to reindex the catalog search we are getting this error message:

`
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"stemmer override filter requires either `rules` or `rules_path` to be configured"}],"type":"illegal_argument_exception","reason":"stemmer override filter requires either `rules` or `rules_path` to be configured"},"status":400}
`

### Preconditions

Magento Version : 2.3.2 CE

ElasticSuite Version : 2.8.5

Environment : production 

### Steps to reproduce

1. Install version ElasticSuite 2.8.5
2. Add 4 storeviews for the different languages
3. Reindex

### Expected result

ElasticSuite reindexes all products for all storeviews (languages)

### Actual result

Error message when trying to reindex catalog search and related ElasticSuite indexes.

This issue is related to the changes requested in #1742

**Comment by romainruaud** [comment]
Hi @svencoeck 

Can you precise also the version of your Elasticsearch server ?

Regards

**Comment by svencoeck** [comment]
We are using elasticsearch 5.6.13

**Comment by tufahu** [comment]
I've the same bug with 5.6.16 (also a multi store store site with french and english)

**Comment by romainruaud** [comment]
Yep, confirmed that the `stemmer_override` behavior is different between ES5 and ES6.

**Comment by tufahu** [comment]
thank you for the fast fix & release
