### ISSUE TITLE
filter option no result

### ISSUE THREAD

**Issue by chenghuili** [Smile-SA/elasticsuite#1760]
there are products in category, but when I click filter option, there is no result, and filter title changed to value.
![1585557167580](https://user-images.githubusercontent.com/14212956/77892036-80d70680-72a4-11ea-8840-bf5ac20e0c09.jpg)
![1585557203546](https://user-images.githubusercontent.com/14212956/77892040-82a0ca00-72a4-11ea-901f-7167c16cce66.jpg)

**Comment by chenghuili** [comment]
i've solve it, because of the third party of extension.

**Comment by romainruaud** [comment]
okay, I close then.

Next time don't forger to provide accurate details about how to reproduce the issue.

Regards
