### ISSUE TITLE
Elastic suit Fatal error with Ultimo theme

### ISSUE THREAD

**Issue by enganas07** [Smile-SA/elasticsuite#1763]
When using ultimo theme product slider or any category related with elasticsuit module it show fatal error

### Preconditions
Environment: Centos 7 OS apache web server 
Magento Version : CE
ElasticSuite Version : 2.4
Environment : Production mode
Third party modules :
Aramex_Adminhtml,
--
Aramex_Core,
Aramex_Shipping,
Ced_SmsaShipping,
Emagicone_Bridgeconnector,
Infortis_Infortis,
Infortis_Brands,
Infortis_Cgen,
Infortis_Dataporter,
Infortis_Base,
Infortis_UltraSlideshow,
Daba_Basic,
Aramex_ApiLocationValidator,
Daba_Homecategory,
Infortis_UltraMegamenu,
Magecomp_Deleteorder,
Codesoftic_StockRequest,
Daba_Categorybanner,
Aramex_Shipment,
Dotdigitalgroup_Email,
Mageplaza_Core,
Mageplaza_GoogleRecaptcha,
Mageplaza_Productslider,
Mageplaza_Smtp,
Malkesh_AttributeImage,
Smile_ElasticsuiteCore,
Malkesh_IconAttr,
PCAPredict_Tag,
Prince_Productattach ,
Shopial_Facebook ,
Smile_ElasticsuiteCatalog ,
Smile_ElasticsuiteCatalogRule   ,
Smile_ElasticsuiteCatalogOptimizer   ,
Malkesh_ExcelSearch ,
Smile_ElasticsuiteSwatches ,
Smile_ElasticsuiteThesaurus ,
Smile_ElasticsuiteTracker ,
Smile_ElasticsuiteVirtualCategory   ,
Sts_SmartRoute ,
Daba_Healthcare ,
Vikash_CreateAttribute ,
Vikash_DistributerCompany ,
Vikash_ManufactureCompany ,
Webkul_Odoomagentoconnect ,
Webkul_UvDeskConnector ,

### Expected result
1.The Product list should showing

### Actual result
Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addSortFilterParameters() in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:93 Stack trace: #0 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php(73): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->setSortParams(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor)) #1 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(121): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->beforePrepareProductCollection(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor)) #2 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\Layer\Category\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 93

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Supporting third party paid extension compatibility is not part of our community support commitment. 
Also, ElasticSuite 2.4 is a very old version and not maintained anymore.

You can contact us for commercial support if it is critical for you.

Feel free to send an email to romain.ruaud@smile.fr if you are interested in this kind of commercial support.

Regards
