### ISSUE TITLE
401 (Unauthorized) error when accessing the relevance configuration

### ISSUE THREAD

**Issue by kamzata** [Smile-SA/elasticsuite#1766]
### Preconditions

Magento Version : 2.3.4 CE (Debian 10, self hosted)

ElasticSuite Version : 2.8.5

Environment : developer

### Steps to reproduce

1. Backend --> Elasticsuite --> Search Relevance (or any other option) --> Relevance Configuration (or any other option)
2. Click on one of the option containers

### Expected result

1. No errors

### Actual result

1. I get an 401 Unauthorized error in console when accessing following url `https://example.com/admin/smile_elasticsuite/search_request_relevanceconfig/state/key/8220c52dbe7adc87045b2ace0ec3038315edd94c864ed5d7b4167143550abb72/?isAjax=true&container=relevance_cutoff_frequency_configuration&value=1&form_key=V44Zcnwf0TwFXiUI`
2. ![Schermata 2020-04-06 alle 15 12 28](https://user-images.githubusercontent.com/1103317/78562117-27795500-7819-11ea-9bc7-cfebc88de58b.png)

I think it has been already reported from _haelbichalex_ user here: https://github.com/Smile-SA/elasticsuite/issues/1286

**Comment by romainruaud** [comment]
I cannot reproduce this one.

User who previously reported it said it was due to their Varnish protection.

Since it's working on our demo environment, you'll have to provide more details to us, especially the ACLs which are linked to your admin user.

Regards

**Comment by kamzata** [comment]
> I cannot reproduce this one.
> 
> User who previously reported it said it was due to their Varnish protection.
> 
> Since it's working on our demo environment, you'll have to provide more details to us, especially the ACLs which are linked to your admin user.
> 
> Regards

Sure, and thanks for your reply. I don't have Varnish installed but I have a Nginx reverse proxy in front of Apache web server which serves Magento. Nginx reverse proxy has the Basic Authentication configured. If I remove it,  Elasticsuite don't ask anymore for authentication but the error 401 is still present in the console log.

**Comment by kamzata** [comment]
Any news on this?

**Comment by romainruaud** [comment]
Unfortunately nope, since it's not occuring on our demo environment (which is quite standard), there's not much we can do about it as part of our Open Source support policy.

We could have a look on your environment if you wish to, but that would be on a time&material basis (professional services).

Let me know,

Regards

**Comment by kamzata** [comment]
I think this happen because there's a Varnish or Nginx reverse proxy in front of it. Just installed another Magento instance on another test environment without a reverse proxy and it works fine. Thanks anyway.

**Comment by romainruaud** [comment]
I close since it's resolved / due to custom environment with Varnish.

Regards
