### ISSUE TITLE
Toolbar Sorting is not working properly in Product Listing page

### ISSUE THREAD

**Issue by test4295** [Smile-SA/elasticsuite#1770]
Attribute sorting result in product listing page of magento 2 is not correct. The result, I getting in random for every attribute sort result for price and name etc. 
Suppose I choose to sort using price in ascending , Result will be like this Product 1 price -100, product 2 price 150, product 3 price 50, product 80. After disable elasticsuite module, the result of attribute sort is fine.

**Magento Version** : 2.3.2 Magento CE

**Comment by rikwillems** [comment]
I'm having the same issue on 2.3.4 EE. We noticed it on price sorting and I verified it on name sorting.

**Comment by romainruaud** [comment]
No issue on the demo instance (2.3.4 EE) : http://demo.magento-elastic-suite.io/index.php/men/tops-men/hoodies-and-sweatshirts-men.html?product_list_order=price

Are you using a custom layout where the toolbar block has been moved elswhere than its default location ?
