### ISSUE TITLE
Getting "index_already_exists_exception" 

### ISSUE THREAD

**Issue by tajveez-73** [Smile-SA/elasticsuite#1771]
Hi,

I have created a custom Index of the Customer following instructions in here "Smile-SA/magento2-module-elasticsuite-cms-search", also like here I have created a plugin that reindexes the data after Customer is saved, now everything is working fine on UI, Customer record gets created, its reindex automatically, but when I create a record with Magento's REST API, I get the response.
`Array
(
    [message] => Internal Error. Details are available in Magento log file. Report ID: webapi-5e8deeee4765b
)`

in logs I get the following.

`[2020-04-07 13:30:48] main.CRITICAL: Report ID: webapi-5e8c8088458d6; Message: {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists","index_uuid":"hZZb6uZdRkCuIej15c9yPg","index":"magento2_tunstall_shop_customer_entity_20200407_133048"}],"type":"index_already_exists_exception","reason":"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists","index_uuid":"hZZb6uZdRkCuIej15c9yPg","index":"magento2_tunstall_shop_customer_entity_20200407_133048"},"status":400} {"exception":"[object] (Exception(code: 400): Report ID: webapi-5e8c8088458d6; Message: {\"error\":{\"root_cause\":[{\"type\":\"index_already_exists_exception\",\"reason\":\"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists\",\"index_uuid\":\"hZZb6uZdRkCuIej15c9yPg\",\"index\":\"magento2_tunstall_shop_customer_entity_20200407_133048\"}],\"type\":\"index_already_exists_exception\",\"reason\":\"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists\",\"index_uuid\":\"hZZb6uZdRkCuIej15c9yPg\",\"index\":\"magento2_tunstall_shop_customer_entity_20200407_133048\"},\"status\":400} at /http/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Elasticsearch\\Common\\Exceptions\\BadRequest400Exception(code: 400): {\"error\":{\"root_cause\":[{\"type\":\"index_already_exists_exception\",\"reason\":\"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists\",\"index_uuid\":\"hZZb6uZdRkCuIej15c9yPg\",\"index\":\"magento2_tunstall_shop_customer_entity_20200407_133048\"}],\"type\":\"index_already_exists_exception\",\"reason\":\"index [magento2_tunstall_shop_customer_entity_20200407_133048/hZZb6uZdRkCuIej15c9yPg] already exists\",\"index_uuid\":\"hZZb6uZdRkCuIej15c9yPg\",\"index\":\"magento2_tunstall_shop_customer_entity_20200407_133048\"},\"status\":400} at /http/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:636)"} []`

Is there any possible work around this, so that I don't get errors while calling API.

Regards

**Comment by romainruaud** [comment]
Hi @tajveez-73 

going that deep into customization is not something we can provide you support you for here, as part of our open source policy.

If you are interested in professional services (paid), feel free to contact me directly by mail at romain.ruaud@smile.fr

You probably missed on something with index creation and the alias the index get when it's created.

Regards
