### ISSUE TITLE
if I disabled this module, all products are disappeared in categories.

### ISSUE THREAD

**Issue by chenghuili** [Smile-SA/elasticsuite#1776]
if I disabled this module, all products are disappeared in categories.  I reindexed it and cleared cache.
I'd like to know how to uninstall this extension totally? 
<img width="697" alt="Screen Shot 2020-04-15 at 15 18 46" src="https://user-images.githubusercontent.com/14212956/79309153-710a2400-7f2c-11ea-9758-8e5d0feca8c7.png">

**Comment by romainruaud** [comment]
https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall should cover all steps.

Regards

**Comment by chenghuili** [comment]
of course, I did that, I disabled all smile extension and deleted tables to refer the link, and I also recompile, reindex and cleared cache. but products still couldn't be displayed in categories.

**Comment by romainruaud** [comment]
Well, I'm afraid we cannot provide more support for a Magento instance which is not using Elasticsuite anymore. If you removed all Elasticsuite modules, you are now using a vanilla Magento, which is not something we can provide any help for.

Regards
