### ISSUE TITLE
Searching for name of not visible child of grouped product gives no results

### ISSUE THREAD

**Issue by mveldhuizen** [Smile-SA/elasticsuite#1778]
In release 2.8.3 there has been a fix for the issue #1488. 
In that fix ([commit 707cc6d0927e1382440063dd83d59a56b6e1534e](https://github.com/Smile-SA/elasticsuite/commit/707cc6d0927e1382440063dd83d59a56b6e1534e)) the $forbidenChildrenAttributeCode is changed and name is also included as a forbidden attribute.
As a result when indexing the name of the children is not added to the index for the parent grouped product. This breaks searching for grouped products by the name of a child.

### Preconditions
Magento Version : 2.3.1
ElasticSuite Version : >= 2.8.3
Environment : Production

### Steps to reproduce
1. Create a product Grouped product; example "Product serie 2080"
2. Add a child product; example name "2080-A14", sku "SKU_56789"
Make sure the name of the product is not in the sku.
3. Set child product to not visible individually
4. Reindex

### Expected result
1. When searching for 2080-A14 we expect to see the Product serie 2080 on the result page

### Actual result
1. The product is not found when searching for the name of a child product. 
When we search for the sku we do find the grouped product. As expected.

**Comment by romainruaud** [comment]
That's kinda strange to me why we decided to add the name into the `$forbiddenChildrenAttribute` list.

If you remove it, does it give you the expected result ?

Regards

**Comment by mveldhuizen** [comment]
We also thought it was strange, seems to be no connection to the fixed bug ;-) 

Yes removing name from the array fixes the problem. Search works as expected because the names of all children are appended to the name of parent in the ES index.

**Comment by dyron** [comment]
We ran in this problem, too. Removing the `name` works. Any plans to revert this change?

**Comment by romainruaud** [comment]
`name` can be removed since this commit : 
https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/di.xml#L221

I close.
