### ISSUE TITLE
Undefined index: type_id - Catalog Search indexer

### ISSUE THREAD

**Issue by abude** [Smile-SA/elasticsuite#1780]
Installed Smile-sa elasticSuite for Magento 2.3.3 and when indexing it gives that error.

### Preconditions
Magento Version : 2.3.3
ElasticSuite Version : ~2.8.0
ElasticSearch engine: 6.8.3
Environment : production
Third party modules : all disabled and removed after installing smile

### Steps to reproduce
1. After installing smile, i ran the indexer command Fulltext
2. Disabled all our third-party extensions and removed the Code of them

### Expected result
1. It should index fine

### Actual result
1. give this error:

`Catalog Search indexer process unknown error:
Notice: Undefined index: type_id in /srv/html/src/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData.php on line 64`

If i dump the indexData in that file it looks like this:

`[18458]=>
  array(7) {
    [74]=>
    string(7) "1234566"
    [92]=>
    string(3) "N/A"
    [96]=>
    string(7) "Enabled"
    [122]=>
    string(13) "Taxable Goods"
    [71]=>
    string(4) "test"
    [72]=>
    string(4) "test"
    [73]=>
    string(4) "test"
  }`

**Comment by romainruaud** [comment]
What do you have in the `catalog_product_entity` table for this specific product ?

**Comment by abude** [comment]
Hey @romainruaud ,

Here's the record of that product in the table:

https://www.dropbox.com/s/2vvtgwod9xvku7l/Screenshot%202020-04-17%2017.29.25.png?dl=0

Hope it helps.

**Comment by abude** [comment]
Update:

in `vendor/magento/module-catalog-search/Model/Indexer/Fulltext.php` before `$saveHandled->saveIndex()` added: 

`echo get_class($this-fullAction);`

And it shows: 

`Magento\CatalogSearch\Model\Indexer\Fulltext\Action\Full`

instead of:

`Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Action\Full`

Hope this helps

**Comment by abude** [comment]
This was solved.

After installation, somehow the `catalog/search/engine` was set to mysql instead of elasticsuite.

Changing that to the right value solved the issue.
