### ISSUE TITLE
Folder structure incoherent with composer requirements

### ISSUE THREAD

**Issue by rvitaliy** [Smile-SA/elasticsuite#1789]
When i download this vendor, i see in my vendor folder files like:
```
vendor/smile/elasticsuite/src/module-elasticsuite-admin-notification/composer.json
vendor/smile/elasticsuite/src/module-elasticsuite-analytics/composer.json
etc...
```
Why we need specify this files they are never used and generate only overhead of work and create confusion.
In addition, they cause the final package to weigh more.

Another related question.
this package doesn't exist see https://packagist.org/?query=smile%2Fmodule-elasticsuite-core 
why we do this it's something internal of magento that i can't understand?

```
    "replace": {
        "smile/module-elasticsuite-core": "self.version",
        "smile/module-elasticsuite-admin-notification": "self.version",
        "smile/module-elasticsuite-analytics": "self.version",
        "smile/module-elasticsuite-catalog": "self.version",
        "smile/module-elasticsuite-catalog-optimizer": "self.version",
        "smile/module-elasticsuite-catalog-rule": "self.version",
        "smile/module-elasticsuite-swatches": "self.version",
        "smile/module-elasticsuite-thesaurus": "self.version",
        "smile/module-elasticsuite-tracker": "self.version",
        "smile/module-elasticsuite-virtual-category": "self.version"
    },
```

I'm new in magento community but i really don't understand this approach, can anyone explain?

**Comment by romainruaud** [comment]
It's legacy. We could probably remove these files since we ship all modules bundled together everytime.

But since it's not causing trouble to have it, its low-low-priority for now.

**Comment by romainruaud** [comment]
Done in 2.10.0

**Comment by rvitaliy** [comment]
@romainruaud Hi i see the commit https://github.com/Smile-SA/elasticsuite/commit/ce7061f6ffd5d1cd24f356bbc07b791b9bd2f8a3
i think you can remove `replace` for all `smile/*` vendors from main composer.json
