### ISSUE TITLE
Save to close `*_tracking_log_*` indices?

### ISSUE THREAD

**Issue by tsdtsdtsd** [Smile-SA/elasticsuite#1790]
I started working on a large Magento 2.3.3 installation with elasticsuite 2.8.x. 
We found out that elasticsearch uses a huge amount of file descriptors. I'm guessing this is due to **7000+** tracking indices. 

I would like to know if it is save to de-alias and close those indices (and probably delete them somewhere in the future), keeping only the latest by timestamp. I know that we will lose tracking data, which is not important for us.
The question is, if there could be any problems showing up in the shop(s) or back-office.

**Comment by Quazz** [comment]
You can reduce the amount of days kept (and thus the amount of indices) in the settings; it will clean them up itself.

**Comment by romainruaud** [comment]
@Quazz is right you can configure this in the back-office.

By default we keep 365 days of data, which can be a bit huge on a small server and/or a huge website.

Feel free to reduce the timeframe to fit your needs.

Regards
