### ISSUE TITLE
Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc in product names

### ISSUE THREAD

**Issue by scottbolasevich** [Smile-SA/elasticsuite#1791]
Not Properly Filtering Search Terms for autocomplete. Causing sql error to show when using words like "MAX" or "COUNT" etc
### Preconditions

magento 2.3.4 and elastic search 6+ on nexcess

Magento Version : 2.3.4 

ElasticSuite Version : 6.0

Environment : production

Third party modules : no

### Steps to reproduce

1.https://www.goinggreensolutions.com.au/ 
2. search "eco max"
3. you can see here https://prnt.sc/s8v1k7

### Expected result

1. normal search results
{
"title": "Eco",
"num_results": "242"
},
### Actual result

1. [Screenshot, logs] sql error
https://www.goinggreensolutions.com.au/search/ajax/suggest/?q=eco+max&_=1588277353486
{
"title": "eco max brush' **AND 9307=CAST((CHR(113)||CHR(122)||CHR(118)||CHR(113)||CHR(113))||(SELECT (CASE WHEN (9307=9307) THEN 1 ELSE 0 EN",**
"num_results": "267"
}
https://prnt.sc/s8v1k7

**Comment by scottbolasevich** [comment]
FYI i dont need a test box or anything either. .this problem is all over the internet look at all the sites with this issue.. it must be from a special character in the product title/name or something not being escaped properly 

https://prospecelectronics.com/search/ajax/suggest/?q=prv
http://www.northfalmouthrentals.com/catalogsearch/ajax/suggest/?q=EKGQ
https://noti.nu/catalogsearch/ajax/suggest/?q=car

i mean there are literally hunderds of sites with this problem i can use google like a scanner and just give you a ton of results..  you can see here also effecting there front end https://prnt.sc/s8vai5

so this is likley a wide spread problem on like every installation of elastic search either that or ALOT of people including myself have it misconfigured?? any info here would be great

**Comment by romainruaud** [comment]
@scottbolasevich are you sure this is occuring when using Elasticsuite on Magento 2 ? 

None of the websites you are showing are actually using our extension.

Regards

**Comment by scottbolasevich** [comment]
Hmm maybe i got this ticket in the wrong place so my apologizes.. but we are using Elasticsearch 6.0.x is this not the same thing? i assumed the elasticsuite as the same thing.. now im questioning it

**Comment by romainruaud** [comment]
Elasticsuite is a search extension for Magento 2, that is basically adding a lot of capabilities including the usage of Elasticsearch as the backend search engine.

If the websites your are showing are not using our extension, there is not much we can do for you :)

**Comment by scottbolasevich** [comment]
ya totally understand sorry to clog up the system a deeper search i think i
wanted the bug here  https://github.com/elastic/elasticsearch/issues/56344

thanks for the quick reply thou

Scott
