### ISSUE TITLE
Static content generation issue

### ISSUE THREAD

**Issue by emirajbbd** [Smile-SA/elasticsuite#1793]
While static content generation process run an exception generates

### Preconditions

Magento Version : 2.3.5 EE

ElasticSuite Version : >= 2.9.0

Environment : Production

Third party modules :

### Steps to reproduce

1. Run setup:static-content:deploy

### Expected result

1. Static content generation done

### Actual result
Compilation from source ***/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-indices/view/adminhtml/web/js/jquery.json-viewer.js failed
RuntimeException: Unclosed string at position: 616 in ***/public_html/vendor/tedivm/jshrink/src/JShrink/Minifier.php:479
Stack trace:
#0 ***/public_html/vendor/tedivm/jshrink/src/JShrink/Minifier.php(238): JShrink\Minifier->saveString()
#1 ***/public_html/vendor/tedivm/jshrink/src/JShrink/Minifier.php(147): JShrink\Minifier->loop()
#2 ***/public_html/vendor/tedivm/jshrink/src/JShrink/Minifier.php(115): JShrink\Minifier->minifyDirectToOutput('/**\n * jQuery j...', Array)
#3 ***/public_html/vendor/magento/framework/Code/Minifier/Adapter/Js/JShrink.php(27): JShrink\Minifier::minify('/**\n * jQuery j...')
#4 ***/public_html/vendor/magento/framework/View/Asset/PreProcessor/Minify.php(60): Magento\Framework\Code\Minifier\Adapter\Js\JShrink->minify('/**\n * jQuery j...')
#5 ***/public_html/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Framework\View\Asset\PreProcessor\Minify->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#6 ***/public_html/vendor/magento/framework/View/Asset/Source.php(152): Magento\Framework\View\Asset\PreProcessor\Pool->process(Object(Magento\Framework\View\Asset\PreProcessor\Chain))
#7 ***/public_html/vendor/magento/framework/View/Asset/Source.php(105): Magento\Framework\View\Asset\Source->preProcess(Object(Magento\Framework\View\Asset\File))
#8 ***/public_html/vendor/magento/framework/View/Asset/File.php(158): Magento\Framework\View\Asset\Source->getFile(Object(Magento\Framework\View\Asset\File))
#9 ***/public_html/vendor/magento/framework/App/View/Asset/Publisher.php(74): Magento\Framework\View\Asset\File->getSourceFile()
#10 ***/public_html/vendor/magento/framework/App/View/Asset/Publisher.php(62): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#11 ***/public_html/vendor/magento/module-deploy/Service/DeployStaticFile.php(89): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#12 ***/public_html/vendor/magento/module-deploy/Service/DeployPackage.php(189): Magento\Deploy\Service\DeployStaticFile->deployFile('js/jquery.json-...', Array)
#13 ***/public_html/vendor/magento/module-deploy/Service/DeployPackage.php(133): Magento\Deploy\Service\DeployPackage->processFile(Object(Magento\Deploy\Package\PackageFile), Object(Magento\Deploy\Package\Package))
#14 ***/public_html/vendor/magento/module-deploy/Service/DeployPackage.php(102): Magento\Deploy\Service\DeployPackage->deployEmulated(Object(Magento\Deploy\Package\Package), Array, false)
#15 [internal function]: Magento\Deploy\Service\DeployPackage->Magento\Deploy\Service\{closure}()
#16 ***/public_html/vendor/magento/framework/App/State.php(187): call_user_func_array(Object(Closure), Array)
#17 ***/public_html/vendor/magento/module-deploy/Service/DeployPackage.php(103): Magento\Framework\App\State->emulateAreaCode('adminhtml', Object(Closure))
![2020-05-03_2026](https://user-images.githubusercontent.com/63784/80916956-ba0c0600-8d7d-11ea-8424-ab91f25c7cb2.png)

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
@androshchuk can you look at this one ?

@emirajbbd you are having minification enabled I guess ?

**Comment by androshchuk** [comment]
Hello, @emirajbbd 
This was a problem with the third-party module we used to display the mappings and settings of the indexes. 
Can you check if my fix https://github.com/androshchuk/elasticsuite/commit/4dd5bee732873e4578d2ed1201ff30f5a7ddd60d helped you?

Regards

**Comment by vrielsa** [comment]
> Hello, @emirajbbd
> This was a problem with the third-party module we used to display the mappings and settings of the indexes.
> Can you check if my fix [androshchuk@4dd5bee](https://github.com/androshchuk/elasticsuite/commit/4dd5bee732873e4578d2ed1201ff30f5a7ddd60d) helped you?
> 
> Regards

We had the same issue on a fresh installation of Magento 2.3.5 open source. Your mentioned fix worked for us.

Best wishes
