### ISSUE TITLE
GraphQl query and Virtual categories

### ISSUE THREAD

**Issue by voytech-net** [Smile-SA/elasticsuite#1796]
**Is your question related to a problem? Please describe.**
Hello. I am having trouble getting products by category_id which is a virtual category. I can see products appear in the admin area of category virtual rule settings, but not when calling graphql.

**Additional context**
M2 version: 2.3.3
ES version: 2.8.7

Virtual rule: single rule with one attribute settings
Query:
`{
    products(filter: {category_id: {eq: "3"}}) {
        items {
            name
        }
    }
}`

My result is empty. Is there something special I need to do to enable these? Does virtual category work in GraphQl?

Thank you very much for your answer.

**Comment by romainruaud** [comment]
Hi @voytech-net 

I don't fetch products by category_id the (exactly) the same way as you're doing.

Check it out how we do it through our testing sample here : https://github.com/Smile-SA/elasticsuite/tree/2.9.x/Resources/tests/graphql/category

That being said, are you able to fetch non-virtual categories through your query ?

By my side, I'm not able to reproduce this on my M2 2.3.5 with Elasticsuite 2.9.0 so it might be a bug that only occurs in your particular version.

Regards
