### ISSUE TITLE
Fatal error: Cannot use 'Bool'

### ISSUE THREAD

**Issue by rootindex** [Smile-SA/elasticsuite#18]
Fatal error: Cannot use 'Bool' as class name as it is reserved in {PROJECT}/vendor/smile-sa/elasticsuite/[src/module-elasticsuite-core/Search/Request/Query/Bool.php](../blob/master/src/module-elasticsuite-core/Search/Request/Query/Bool.php) on line 26

I have a feeling this might be specific to Mac and Windows case sensitivity, perhaps renaming the class to Boolean might have a better effect?

[migration70.incompatible.other.classes](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.other.classes)

**Comment by afoucret** [comment]
The PR have been merged into the master code base.
It will be part of the 2.1 release coming soon.

Thx for the contrib.
