### ISSUE TITLE
[2.9] Event Log Index cron error Elasticsearch 7.6

### ISSUE THREAD

**Issue by Quazz** [Smile-SA/elasticsuite#1800]
### Preconditions

Magento Version : CE 2.3.5

ElasticSuite Version : 2.9.0

Environment : Production

### Steps to reproduce

1. Enable and setup cron
2. Trigger event for log for a new index (eg new day)
3. Check cron output

### Expected result

1. Index is created successfully with all info available

### Actual result

1. `{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [codec] for create index"}],"type":"parse_exception","reason":"unknown key [codec] for create index"},"status":400}` cron returns that error and the index is unassigned and incomplete.

**Comment by romainruaud** [comment]
Update : seems to be only occuring when using Elasticsearch 7.x (not specified in original issue).

**Comment by romainruaud** [comment]
PR #1801 should fix this.

To be delivered in 2.9.1
