### ISSUE TITLE
Index per customer group, per store

### ISSUE THREAD

**Issue by killoff** [Smile-SA/elasticsuite#1805]
Is there a way to create indices per customer groups?
So, instead of `magento2_ch_fr_catalog_product_20200511_130916` we create 
(Number of customer groups) x magento2_ch_fr_catalog_product_20200511_130916:
`magento2_0_ch_fr_catalog_product_20200511_130916`
`magento2_1_ch_fr_catalog_product_20200511_130916`
`magento2_2_ch_fr_catalog_product_20200511_130916`

Or somebody can point to the class responsible for creating the indices, where I can implement some plugin and control the way how indices created

**Comment by dambrogia** [comment]
I would recommend using following the stack trace starting at `Magento\Indexer\Console\Command\IndexerReindexCommand::execute` when running the `php bin/magento indexer:reindex catalogsearch_fulltext` command on the CLI.

You'll descend into the logic where it creates _Dimensions_ for the indexes (which seem to be per store view if I recall correctly). As you get further in, you'll wind up in `Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler` where you have the general `save/create/delete` functions for indexes. 

These are called from `\Smile\ElasticsuiteCatalog\Model\Category\Indexer\Fulltext` which is what implements the Magento native indexer and mview interfaces: 
- `\Magento\Framework\Indexer\ActionInterface`
- `\Magento\Framework\Mview\ActionInterface`

**Comment by killoff** [comment]
Actually it is a bad idea and really hard to implement :)
`Smile\ElasticsuiteCore\Helper\IndexSettings` shows that it's not possible or big effort required to intercept this and other related classes.
I was thinking that it's somehow dependent on Magento dimension mode 
`$ bin/magento indexer:show-dimensions-mode` but it's not.

In custom indexers, like Category it is more realistic, thank you @dambrogia
