### ISSUE TITLE
How to display out of stock products only in search dropdown

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1812]
We are using smile elasticsuite version 2.8.0 with magento version 2.3.4.

We have default inventory setting on admin->Catalog->Inventory->Display Out of Stock Products = No
because we do not want to display out of stock products in any listing pages.

But would also be nice to show out of stock in only autocomplete search drop down.

Is there any possibility with extension that we can do some changes and it should possible?

Please let us know your view for same.

Thanks in advance,
David Andersson

**Comment by romainruaud** [comment]
The stock filter is included in the `autocomplete` query definition here : https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml#L35

If you write your own `elasticsuite_search_request.xml` file and define a new `stockFilter` (that will do basically nothing compared to the legacy one) for this query, it should do the trick.

Regards

**Comment by davidandersson1** [comment]
Hello @romainruaud ,

Thanks a lot for your reply.

I tried same like created my new own class same as "Smile\ElasticsuiteCatalog\Model\Product\Search\Request\Container\Filter\Stock" and method isEnabledShowOutOfStock return true and replaced class name in line number 35 as you mentioned above. in order to do local testing I haven't overwrite the "elasticsuite_search_request.xml" file instead directly apply my new class in module's "elasticsuite_search_request.xml" file but it's not working somehow :(

Please let us know if I was wrong above at any point.

Thanks,
David
