### ISSUE TITLE
Alternative to DataSources

### ISSUE THREAD

**Issue by Larke12** [Smile-SA/elasticsuite#1813]
Previously we used a custom datasource to add some aggregated data to the index for each product. How should we do that now that datasources have been deprecated and removed from the elasticsuite_indices.xml file? It appears from commit history it was actually completely removed at one point and is only partially reinstated for the moment.

I did review the [wiki](https://github.com/Smile-SA/elasticsuite/wiki/Indexing#dynamic-fields-provider) that still explains such a process using DataSources, however, if there is a proper alternative to use here any information on it would be much appreciated.

**Comment by romainruaud** [comment]
Sure it's explained in the latest release note : 

```
As explained in 2.8.0 we moved the legacy Datasources declaration from the elasticsuite_indices.xml to the DI. We supported both fashions in 2.8.0 and now we drop the old-fashion support : They have to be injected via the DI into the Smile\ElasticsuiteCore\Api\Index\DataSourceResolverInterface. If you did write custom datasources, you'll have to move their declaration into the DI.
```

And in the old 2.8.0 release note when we deprecated them : 

```
⚠️ We moved the Datasources outside the elasticsuite_indices.xml file. Now they have to be injected via the DI into the Smile\ElasticsuiteCore\Api\Index\DataSourceResolverInterface. For now, we still support datasources defined in the legacy way via the elasticsuite_indices.xml file but this support will be dropped on next major version.
```

I keep your issue open as a reminder to update the wiki.

Regards

**Comment by romainruaud** [comment]
Wiki has been updated : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#data-sources

Regards
