### ISSUE TITLE
Same code base (differenct database) but queries are different

### ISSUE THREAD

**Issue by hkvega01** [Smile-SA/elasticsuite#1814]
I've a two webistes (ee 2.3.4 + smile elasticsuite 2.8.7), one is dev and another one is staging, but now staging is returning wrong products, but dev is fine, see the screenshots. I've created a external script to call the elastic search server, i swap the green part of query (the screenshot) to replace the red query in the external script(staging), the result returns same products as dev website.

Ex :
- i can't figure out why two websites with same code and setting but generating different queries.

**Additional context**
![image](https://user-images.githubusercontent.com/4374758/82175795-7da4e200-9907-11ea-9791-279fd948fd35.png)

Anyone know why the queries generated are different?

**Comment by romainruaud** [comment]
Yep, queries might be different according to the content of the index itself.

We execute a "pre-flight" request through [termVectors](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html) to determine if the searched term is **exact** existing in the index. If that's not the case, we trigger a fuzzy query.
