### ISSUE TITLE
Search ignores numbers in attributes

### ISSUE THREAD

**Issue by hdezela** [Smile-SA/elasticsuite#1815]
We have a site set up at https://qa.volvo.klikealolatam.net/ and are using Elasticsuite. The site has chassis & tag numbers as attributes for products so users are able to find the specific parts for their vehicle.

However, the search is completely ignoring any numbers within the attributes. For example, we have the tag numbers [ACJ743](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ743) and [ACJ948](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ948), which do not share products, if you look at the result set they are exactly the same.

We did some testing and if we search only for the text value of [ACJ](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ) the results are again the same. If we search for a non-existent tag, say [ACJ999](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ999), we get no results, but as long as one tag matches, results are returned for _all_ tags which share the letters, ignoring the number part.

We've tried setting "split_on_numerics" to false but it doesn't seem to affect anything.

**Comment by androshchuk** [comment]
Hello @hdezela 
I have not seen similar problems if used Used in spellcheck = Yes
and set <defaultSearchAnalyzer>reference</defaultSearchAnalyzer> (this can be done by adding to the file elasticsearch_indices.xml) for these attributes. 

Also, you will be limited here by this 
https://github.com/Smile-SA/elasticsuite/wiki/SearchingBySkuBasics#what-does-not-work

Regards

**Comment by rbayet** [comment]
Hello @hdezela,

I see that your examples [ACJ743](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ743) and [ACJ948](https://qa.volvo.klikealolatam.net/catalogsearch/result/?q=ACJ948) know correctly show different products.

Did the original `split_on_numerics=false` finally made a difference or the approach mentioned by @androshchuk paid off ?
Feel free to let us know how you solved your issue.

Regards,

**Comment by hdezela** [comment]
After the latest update the issue seems to be resolved. I don't know exactly what did it though.

**Comment by romainruaud** [comment]
okay, good to know. Don't hesitate to open again with more details if this happens to occur again.

Regards
