### ISSUE TITLE
Price filter or sort by is not working correctly

### ISSUE THREAD

**Issue by bawwwa** [Smile-SA/elasticsuite#1818]
If the price filter is applied we get random product out of the range on the result. 

When sorted by price (low to high or hight to low) we get product out of order.

### Preconditions
PHP: PHP 7.2.29-1+0~20200320.39+debian9~1.gbp513c2e 
Magento Version: 2.3.5-p1 (EE cloud)
ElasticSuite Version :2.9.0

Third party modules :

### Steps to reproduce
1.Sort by price 
2.filter by price

### Expected result
1. product should be sorted by price.
2. product should be within the filter price range

**Comment by androshchuk** [comment]
Hello, @bawwwa 
Unfortunately, I could not reproduce this problem in my environment.

Could you try to reproduce such behavior on our demo site http://demo.magento-elastic-suite.io/index.php/ ?

Regards

**Comment by bawwwa** [comment]
I had to do this;
`DELETE FROM catalog_product_entity_decimal WHERE attribute_id IN (78, 77) and row_id in (SELECT row_id FROM catalog_product_entity c where c.type_id = 'configurable');
DELETE FROM catalog_product_entity_datetime WHERE attribute_id IN (79, 80) and row_id in (SELECT row_id FROM catalog_product_entity c where c.type_id = 'configurable');`

removes special price and price for configurable on catalog_product_entity_decimal and removes sepecial price from and to dates from catalog_product_entity_datetime. That fixed the issue. Nothing wrong with the module! 

Thanks @androshchuk!

**Comment by androshchuk** [comment]
You're welcome!
