### ISSUE TITLE
Table view doesnt exist after install 

### ISSUE THREAD

**Issue by shak18** [Smile-SA/elasticsuite#1819]
I cannot figure out how to install this properly after install with composer my site crashes cause it says it can't find some config tables from the elastic search module it's that a problem with the module or its something I'm doing wrong??

`php -d memory_limit=-1 composer require smile/elasticsuite ~2.8.0`

that's how install the module, do you guys have any idea on this???

**Comment by androshchuk** [comment]
Hello @shak18.

please follow [our instructions](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) for installing the module. 
You may not have complied
`bin/magento setup:upgrade `

Regards

**Comment by shak18** [comment]
i have to run this after propper install, and setup upgrade in order to stop the errors of missing config table:

`n98-magerun2 config:store:set catalog/search/engine elasticsuite
`
