### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'smile_elasticsuite_relevance_config_data' doesn't exist,

### ISSUE THREAD

**Issue by ericzzhou** [Smile-SA/elasticsuite#1820]
### Preconditions

5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.3.17 (cli) (built: Apr 30 2020 11:13:08) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans

Magento Version : Magento CLI 2.3.4

ElasticSuite Version : 6.8

Environment : Developer

Third party modules :

### Steps to reproduce

1. composer install => cannot download
2.down file from https://github.com/Smile-SA/elasticsuite/releases/tag/2.8.7
3. unzip to /app/code/Smile
4. change directory name : 
        Smile/ElasticsuiteAdminNotification
        Smile/ElasticsuiteAdminNotification/
        Smile/ElasticsuiteAnalytics/
        Smile/ElasticsuiteCatalog/
        Smile/ElasticsuiteCatalogOptimizer/
        Smile/ElasticsuiteCatalogRule/
        Smile/ElasticsuiteCore/
        Smile/ElasticsuiteSwatches/
        Smile/ElasticsuiteThesaurus/
        Smile/ElasticsuiteTracker/
        Smile/ElasticsuiteVirtualCategory/
5. php bin/magento setup:upgrade

### Expected result

1. Create some database table, for example “
smile_elasticsuite_relevance_config_data ” or more

### Actual result

1. [Screenshot](https://cooll-cn.oss-cn-hongkong.aliyuncs.com/1.png)

**Comment by androshchuk** [comment]
Hello @ericzzhou.
I can't help you.
The module must be installed using a composer.
Please follow [our instructions](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) for installing the module.

Regards.

**Comment by ericzzhou** [comment]
@androshchuk 
thank you for your reply.

Sorry, i can't installed this module with composer , It always times out.
I'm sure there is no problem with my network。

version : magneto 2.3.4 
command : composer require smile/elasticsuite ^2.7.0

**Comment by ericzzhou** [comment]
> Hello @ericzzhou.
> I can't help you.
> The module must be installed using a composer.
> Please follow [our instructions](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) for installing the module.
> 
> Regards.

@androshchuk
thank you for your reply.

Sorry, i can't installed this module with composer , It always times out.
I'm sure there is no problem with my network。

version : magneto 2.3.4
command : composer require smile/elasticsuite ^2.7.0

**Comment by romainruaud** [comment]
@ericzzhou you have to install the module with composer. This should not time out, if the composer install does not succeed, please open another issue.

Regards
