### ISSUE TITLE
Who can provide me with elasticsuite related mysql table structure

### ISSUE THREAD

**Issue by ericzzhou** [Smile-SA/elasticsuite#1821]
**Is your question related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Who can provide me with elasticsuite related mysql table structure

**Additional context**
Add any other context or screenshots about your question here.

**Comment by romainruaud** [comment]
Hi @ericzzhou 

I'm sorry but we will need more details to be able to answer your question.

Regards
