### ISSUE TITLE
How to configure the autocomplete results template

### ISSUE THREAD

**Issue by shak18** [Smile-SA/elasticsuite#1826]
I have set up and running my elasticsuite and its working as expected in the search part, I have added to my theme's the following subfolders (Smile_ElasticsuiteCore/templates/search) with a form.mini.phtml in order to display correctly the search bar in the website, however, I cannot figure out how to make the search results formatted as in the demos (with products and suggestions separated and with preview images) I'm getting a simple list like this every time:

![preview](https://i.imgur.com/pBJaQ27.png)

What do I need to change to make this work? or what template do I need to add to my custom theme in order to configure this properly?

**Comment by androshchuk** [comment]
Hello @shak18 

You can find more settings in Stores -> Configurations -> Elasticsuite -> Autocomplete

After you changed our form we will not be able to help you. You can install a new magento2 instance with a sample data and Elasticsuite module and check the settings there.

Regards.

**Comment by shak18** [comment]
Even before the change the results always look like that, they never look like this:

![demo](https://i.imgur.com/xfW42rN.png)

and i want to know what do ai have todo for the results to show categorized and with previews

**Comment by rbayet** [comment]
Hello @shak18,

My guess would be that you moved `src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml` along with the layout update `src/module-elasticsuite-core/view/frontend/layout/default.xml` and changed the path of the template.
It may be sufficient, with improper module dependencies, to "re-declare" the block after `src/module-elasticsuite-catalog/view/frontend/layout/default.xml` has updated the `rendererList` argument.

If that is the case, I may be wrong, but I would advise to take inspiration from `vendor/magento/theme-frontend-luma` on how to customize a specific template/JS template without the need to change the template path.

Regards
