### ISSUE TITLE
Main description link => http://magento-elastic-suite.io/ is a 404 page

### ISSUE THREAD

**Issue by FredericMartinez** [Smile-SA/elasticsuite#1828]
Description repository:
> Smile ElasticSuite - Magento 2 merchandising and search engine built on ElasticSearch http://magento-elastic-suite.io/
Goes to a 404 page

![elastic404](https://user-images.githubusercontent.com/13019288/83116624-52bb4a80-a0cc-11ea-86ae-1d25074b3975.png)

**Comment by romainruaud** [comment]
moved to https://elasticsuite.io
