### ISSUE TITLE
Critical error When CatalogInventory_stock_status.website_id <> 0 See: https://github.com/magento/magento2/issues/7090

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#183]
This Category indexer issue is related to checking for website_id when calling for cataloginventory_stock_status table. Magento does not allow per-website Inventory, thus filtering on website_id can product invalid results which can cause critical error in catalog_category display format as below!

See issue as described by magento2 developers:
https://github.com/magento/magento2/issues/7090

2016/10/26 10:40:02 [error] 10606#10606: *259 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addSortFilterParameters() in /home/scw/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:78
Stack trace:
#0 /home/scw/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php(59): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->setSortParams(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor))
#1 /home/scw/public_html/vendor/magento/framework/Interception/Interceptor.php(123): Smile\ElasticsuiteCatalog\Plugin\LayerPlugin->beforePrepareProductCollection(Object(Magento\Catalog\Model\Layer\Category\Interceptor), Object(Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor))
#2 /home/scw/public_html/var/generation/Magento/Catalog/Model/Layer/Category/Interceptor.php(26): Magento\Catalog\Model\Layer\Categ" while reading response header from upstream, client: 72.54.10.246, server: , request: "GET /catalog/category/view/s/a-v-control-panels/id/1047/ HTTP/1.1", upstream: "fastcgi://unix:/run/php.sock:", host: "shop2.scw.com", referrer: "https://shop2.scw.com/"

mysql> select * from catalog_category_entity limit 10;
+-----------+------------------+-----------+---------------------+---------------------+--------------------+----------+-------+----------------+---------------------+
| entity_id | attribute_set_id | parent_id | created_at          | updated_at          | path               | position | level | children_count | etilize_category_id |
+-----------+------------------+-----------+---------------------+---------------------+--------------------+----------+-------+----------------+---------------------+
|         1 |                0 |         0 | 2016-10-21 15:46:39 | 2016-10-22 18:39:39 | 1                  |        0 |     0 |         763658 |                NULL |
|         2 |                3 |         1 | 2016-10-21 15:46:39 | 2016-10-22 18:39:39 | 1/2                |        0 |     1 |              0 |                NULL |
|         3 |                3 |         2 | 2016-10-21 16:40:59 | 2016-10-22 18:01:30 | 1/2/3              |        0 |     2 |              0 |                NULL |
|         4 |                3 |         1 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4                |        1 |     1 |         763657 |                   1 |
|         5 |                3 |         4 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/5              |       15 |     2 |            829 |                   2 |
|         6 |                3 |       200 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/369/198/200/6  |        5 |     5 |           4713 |                4799 |
|         7 |                3 |       200 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/369/198/200/7  |        4 |     5 |            979 |                4800 |
|         8 |                3 |       200 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/369/198/200/8  |        1 |     5 |             31 |                4801 |
|         9 |                3 |       230 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/369/230/9      |        1 |     4 |            130 |                4805 |
|        10 |                3 |       201 | 2016-10-22 18:01:13 | 2016-10-22 18:39:39 | 1/4/369/198/201/10 |        5 |     5 |            617 |                4806 |
+-----------+------------------+-----------+---------------------+---------------------+--------------------+----------+-------+----------------+---------------------+
mysql> select * From store_group;
+----------+------------+--------------------+------------------+------------------+
| group_id | website_id | name               | root_category_id | default_store_id |
+----------+------------+--------------------+------------------+------------------+
|        0 |          0 | Default            |                0 |                0 |
|        1 |          1 | Main Website Store |                4 |                1 |
+----------+------------+--------------------+------------------+------------------+

update store_group set root_category_id=2 where group_id=1; 

Stops this error from happening!

Any thoughts?

**Comment by southerncomputer** [comment]
I have back-ported Elasicsuite 2.1.2 to magento 2.1.2 and this category problem does not manifest!

It appears to do with having too many categories! The Entire Category Filter disappears during searches (fulltext), any direct linking to categories causes above failure, however the categories do show up in auto-complete (however if you click on them they crash as above!) ODD!

I have about 700K products with 600 categories - all indexing appears to have completed multiple times!

**Comment by romainruaud** [comment]
Hello @southerncomputer 

I am not sure to getting it but I will try to help anyway.

For testing purposes I have actually a catalog with 3 millions of products an 6000 categories.

The root category of my store is the "2" : this is a standard Magento install.

I am working with branch 2.3.x for this test and I do not have the issue you describe, even if I am having a huge number of categories.

you are saying that if I want to reproduce this issue, I have to move my category tree under another one (the "4" in your example), and set this category as root category id ?

Also, regarding the big number of categories, are you facing this issue ? https://github.com/magento/magento2/issues/7193

Best regards,

**Comment by southerncomputer** [comment]
public function loadInventoryData($storeId, $productIds)
    {
        $websiteId = $this->getWebsiteId($storeId);
        $stockId   = $this->getStockId($websiteId);
        $select = $this->getConnection()->select()
            ->from(['ciss' => $this->getTable('cataloginventory_stock_status')], ['product_id', 'stock_status', 'qty'])
            ->where('ciss.stock_id = ?', $stockId)
            ->where('ciss.website_id = ?', $this->stockConfiguration->getDefaultScopeId())
            ->where('ciss.product_id IN(?)', $productIds);
        return $this->getConnection()->fetchAll($select);
    }

Suggest removing : ->where('ciss.website_id = ?', $this->stockConfiguration->getDefaultScopeId())

Since this is not possible to be other than 0 !

**Comment by southerncomputer** [comment]
if "IS_ANCHOR"==0 on category -> elasticsearch throws exception
