### ISSUE TITLE
How manual sort work on category level

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1832]
Hello, 

We have enabled manual sort with products on some categories to display that products in top position in frontend but not working.

So I read the document pdf and found that its work with only magento enterprise edition and we are trying with our community version.

We have magento community version 2.3.5 and Elasticsuite version ~2.8.0 according to composer.json file.

So want to confirm that manual sort feature is working with only enterprise edition or its work with community version as well?

I have attached screenshot of pdf documentation.

Can you please share your view for the same.

Thanks,
David Andersson

![Screenshot from 2020-06-02 18-16-13](https://user-images.githubusercontent.com/49389320/83526289-d6799a80-a503-11ea-98ec-846b673f4bfd.png)

**Comment by androshchuk** [comment]
Hello @davidandersson1 
I checked it in my environment:
Magento CE 2.3.5 ("magento/product-community-edition": "2.3.5-p1",)
ElasticSuite: 2.9.0
Manual sorting works well: http://i.imgur.com/0rCSl1w.png

Please provide more information on how this can be reproduced, as well as the exact versions of your modules.

Regards

**Comment by davidandersson1** [comment]
Hi @androshchuk thanks for you reply.

I have upgraded same elastic version as you. Just curious and want to know like its working with only Virtual categories or how?

Thanks,
David

**Comment by androshchuk** [comment]
Hi @davidandersson1 

Do you mean Manual sort?
It works for all categories. And also in search terms (Marketing -> Search Terms -> Merchandiser)

Regards

**Comment by davidandersson1** [comment]
Hi @androshchuk 

Thanks for your reply!  Yes I meant "Manual sort". sorry for not being clear.

However I almost found issue why "Manual Sort" not working because at global setting Catalog->Catalog->Storefront if I change "Product Listing Sort by" as another custom option (like I created one custom attribute and set Yes for "Used for Sorting in Product Listing" at attribute level and "Catalog Input Type for Store Owner" = Text) except "Position" then Manual sort not working in my case. if "Position" is selected on "Product Listing Sort by" then only works.

May I know, Have you tried with custom option on global setting as above? or do you have default setting?

Thanks,
David

**Comment by davidandersson1** [comment]
Hello,

I have installed fresh magento version 2.4.0 with sample data and only Smile elastic suite module version 2.10, nothing else. single store only.

Use Flat Catalog Category = Yes
Use Flat Catalog Product = Yes
All Reindexes with schedule mode.

In Backend, Store->Configuration->Catalog->Catalog->Product Listing Sort by = Product Name
Category edit level-> Default Product Listing Sort By = Position with checked checkbox "Use Config Settings", and enabled Manual sorting for some products but it's not working on frontend.

Really do not getting what's wrong here, Anybody Please help me. here I attached screenshots of configuration.

Thanks in advance,
David Andersson

![Screenshot from 2020-09-16 14-01-43](https://user-images.githubusercontent.com/49389320/93312724-2c5d1e80-f825-11ea-8c20-e946490fac36.png)
![Screenshot from 2020-09-16 14-01-31](https://user-images.githubusercontent.com/49389320/93312731-2d8e4b80-f825-11ea-9135-bb182e1f8b01.png)
![Screenshot from 2020-09-16 13-59-26](https://user-images.githubusercontent.com/49389320/93312736-2ebf7880-f825-11ea-80bf-192c0b24852a.png)
![Screenshot from 2020-09-16 13-59-20](https://user-images.githubusercontent.com/49389320/93312741-30893c00-f825-11ea-8e83-65ff76f33b03.png)
