### ISSUE TITLE
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:53

### ISSUE THREAD

**Issue by AymericBoi** [Smile-SA/elasticsuite#1833]
### Preconditions

Magento Version : 2.3.5

ElasticSuite Version : ~2.8
Elasticsearch Version : 6.5

Environment : Developer

### Steps to reproduce

1. php bin/magento indexer:reset
2. php bin/magento indexer:reindex
3.

### Expected result

1. reindexing all indexes using elasticsearch

### Actual result

1. Error printed on several indexes as Catalog Search, ElasticSuite Category Indexing, ElasticSuite Thesaurus Indexing with the following message :
 indexer process unknown error:
No alive nodes found in your cluster

and catalogsearch_fulltext with the following message : 
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:53
Stack trace:
#0 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(78): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(96): Elasticsearch\Transport->getConnection()
#2 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(258): Elasticsearch\Transport->performRequest('POST', '/_all/_bulk', Array, '{"index":{"_ind...', Array)
#3 /app/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4 /app/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#5 /app/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::Rea in /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 53

Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:53
Stack trace:
#0 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(78): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(96): Elasticsearch\Transport->getConnection()
#2 /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(258): Elasticsearch\Transport->performRequest('POST', '/_all/_bulk', Array, '{"index":{"_ind...', Array)
#3 /app/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#4 /app/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#5 /app/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::Rea in /app/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 53

But when I run curl commands, Elasticsearch looks alive and well. Ex: 
curl -X GET "http://elasticsearch.internal:9200/_all/_settings?pretty"
gives me a list of the indexes with their settings.

Thank you

**Comment by duffner** [comment]
This is just a general issue, not related to ElasticSuite, rather just Elastic itself.  The error you're seeing is just because Elastic is not running, or died for some reason.  Try restarting Elastic and post your results.
