### ISSUE TITLE
Filterable (no results) for specific attribute

### ISSUE THREAD

**Issue by zexperto** [Smile-SA/elasticsuite#1836]
I am not sure if the module support displaying the attribute in the layered navigation with this option 
**Filterable (no results)** ? could you please confirm 

Magento Version CE 2.2.9

**Comment by androshchuk** [comment]
Hello @zexperto 
In your module, the behavior for Filterable (no results) and Filterable (with results) is no different. 
(we do not display options with zero results http://i.imgur.com/aqzSA4h.png (Left - Magento2 with ElasticSuite, right - without ElasticSuite)) 
Also, as in the native Magento2: if the attribute cannot affect the search result, it is not displayed http://i.imgur.com/dEjO1jL.png
This applies to both values (Filterable (no results) and Filterable (with results))

Regards
