### ISSUE TITLE
Child product index even if they are not visible

### ISSUE THREAD

**Issue by AKALuffy** [Smile-SA/elasticsuite#184]
When i run : 

bin/magento index:reindex catalogsearch_fulltext

It work fine but when i try to saw index with :  curl 'localhost:9200/_cat/indices?v'

I can saw that child product is index even if they are supposed to be not visible on website.

After that i try to make a search on my website and each child product show up in my search ...

Do you know how is it possible ?

( when i say child product , it is simple product linked on configurable product )

Kind regards

**Comment by romainruaud** [comment]
Are you sure that the `catalog_category_product` is properly re-indexed ?

Elasticsuite is based on this index values when building the visibility filtering : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Action/Full.php#L89

**Comment by AKALuffy** [comment]
Thanks @romainruaud .

That's my problem :+1:
