### ISSUE TITLE
Product page  URL 404 in virtual category

### ISSUE THREAD

**Issue by christiaanjansen1991** [Smile-SA/elasticsuite#1840]
In a virtual category products are shown correctly and shows correct URL with category parameters:

/category/sub-category/product

After click on product url page gives a 404. 

### Environment
Magento Version : CE 2.3.5
ElasticSuite Version : 2.9.0
Environment : Production

### Steps to reproduce
1. Create virtual category
2. Link products
3. View virtual category
4. Click product URL
5. 404 page loaded

### Expected result
1. Create virtual category
2. Link products
3. View virtual category
4. Click product URL
5. PDP loaded 

### Actual result
1. Create virtual category
2. Link products
3. View virtual category
4. Click product URL
5. 404 page loaded

What I see in the url_rewrite table is that product URL's with category path are missing. Is it possible to generate virtual categories with category path in the PDP?

For example:
**Virtual category**
https://www.ventilatieshop.com/onze-merken/ubbink/
**PDP with 404 status**
https://www.ventilatieshop.com/onze-merken/ubbink/kunststof-dakpan-verbeterde-holle-voor-doorvoer-110-131-dakhelling-25-45-graden-0170033/

In a normal category PDP is loaded correctly.

**Comment by romainruaud** [comment]
This should work since this PR : https://github.com/Smile-SA/elasticsuite/pull/1475

So it might be a bug

@androshchuk can you investigate ?

**Comment by androshchuk** [comment]
Hello @christiaanjansen1991 
Could you provide your Search Engine Optimization Configuration (Stores -> Configuration -> Catalog -> Catalog)?
In particular "Product URL Suffix", "Category URL Suffix" and "Use Categories Path for Product URLs"

Regards

**Comment by christiaanjansen1991** [comment]
Van: Dmytro Androshchuk <notifications@github.com>
Beantwoorden - Aan: Smile-SA/elasticsuite <reply@reply.github.com>
Datum: dinsdag 14 juli 2020 om 14:08
Aan: Smile-SA/elasticsuite <elasticsuite@noreply.github.com>
CC: christiaanjansen1991 <info@ceecommerce.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [Smile-SA/elasticsuite] Product page URL 404 in virtual category (#1840)

 

Hello @christiaanjansen1991
Could you provide your Search Engine Optimization Configuration (Stores -> Configuration -> Catalog -> Catalog)?
In particular "Product URL Suffix", "Category URL Suffix" and "Use Categories Path for Product URLs"

Regards

**Comment by androshchuk** [comment]
Hello @christiaanjansen1991 
I think your config is http://i.imgur.com/O6BO9Q2.png

I made some fixes. Please check it in your environment.

Regards

**Comment by christiaanjansen1991** [comment]
Thanks, works with the fixes. Any idea about the release for this bugifx?
