### ISSUE TITLE
Display the attribute even it has one option for all products

### ISSUE THREAD

**Issue by zexperto** [Smile-SA/elasticsuite#1841]
### Preconditions

Magento Version : Magento CE 2.3, Magento CE 2.2

ElasticSuite Version : Elasticsearch 6.5

Environment : Development 

Third party modules : there are a lot of small custom modules, nothing related to the category search and we can disable them all , and we still have the same issue

### Steps to reproduce

1.  Create Category
2. Create 10 Products
3. Create new attribute , name = Color, dropdown, options = Red/Blue/Black
4. Add the attribute to the attribute set
5. Assign random colors to the 10 products
6. You can see now the Color attribute in the Category with the correct number of products for each option in the layered navigation 
7. Now go back and assign only Black color for the all 10 products
8. Go back to the Category
9. You will see that the attribute is gone from the layered navigation

### Expected result

1. We need to see one Color options  "Black" with 10 as product number

### Actual result

1. the Attribute was gone

**Comment by zexperto** [comment]
I found the solution but I am not sure if this will affect anything in the project , you need to modify the below line in this function  (**_getItemsData**) in this file
**Filename:** \vendor\smile\elasticsuite\src\module-elasticsuite-catalog\Model\Layer\Filter\Attribute.php
Function **_getItemsData**
Line : **if (!empty($this->currentFilterValue) || $minCount < $productCollection->getSize()) {**
New Line: **if (!empty($this->currentFilterValue) || $minCount <=$productCollection->getSize()) {**

**Comment by romainruaud** [comment]
Hi @zexperto 

By design, we consider useless to display a filter that would have no effect on the product list when clicked.

Maybe we could consider making this configurable by the admin. However, this is low-priority for us.

So if you want this to be possible, could you please consider making a PR containing the changes ? This could be either a sitewide configuration, or maybe a per-attribute configuration.

Regards

**Comment by romainruaud** [comment]
@zexperto any update ?

**Comment by zexperto** [comment]
Hello @romainruaud  unfortunately I could not work on it yet

**Comment by romainruaud** [comment]
Should be fixed by #2026 

In this case, if you set this filter to be "always visible" at your category level, you should be able to make it appear.

Can you check this with latest elasticsuite version @zexperto ?

**Comment by zexperto** [comment]
@romainruaud I confirm that it is working now as expected, that's really awesome
Thank you guys all for your efforts
