### ISSUE TITLE
composer installation error magento/module-inventory-sales-api >=1.0.3

### ISSUE THREAD

**Issue by thomasklosinsky** [Smile-SA/elasticsuite#1844]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for smile/elasticsuite ^2.9 -> satisfiable by smile/elasticsuite[2.9.0].
    - smile/elasticsuite 2.9.0 requires magento/module-inventory-sales-api >=1.0.3 -> no matching package found.

Magento v. 2.3.5

**Comment by thomasklosinsky** [comment]
Hi rbayet,
how can check that? I didn't know that is possible...

**Comment by thomasklosinsky** [comment]
This is my composer.json:

{
    "name": "magento/magento2ce",
    "description": "Magento 2 (Open Source)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "php": "~7.1.3||~7.2.0||~7.3.0",
        "ext-bcmath": "*",
        "ext-ctype": "*",
        "ext-curl": "*",
        "ext-dom": "*",
        "ext-gd": "*",
        "ext-hash": "*",
        "ext-iconv": "*",
        "ext-intl": "*",
        "ext-mbstring": "*",
        "ext-openssl": "*",
        "ext-pdo_mysql": "*",
        "ext-simplexml": "*",
        "ext-soap": "*",
        "ext-xsl": "*",
        "ext-zip": "*",
        "lib-libxml": "*",
        "braintree/braintree_php": "3.35.0",
        "colinmollenhour/cache-backend-file": "~1.4.1",
        "colinmollenhour/cache-backend-redis": "1.10.6",
        "colinmollenhour/credis": "1.10.0",
        "colinmollenhour/php-redis-session-abstract": "~1.4.0",
        "composer/composer": "^1.9",
        "elasticsearch/elasticsearch": "~7.7",
        "fishpig/magento2-wordpress-integration": "*",
        "guzzlehttp/guzzle": "^6.3.3",
        "laminas/laminas-captcha": "^2.7.1",
        "laminas/laminas-code": "~3.3.0",
        "laminas/laminas-config": "^2.6.0",
        "laminas/laminas-console": "^2.6.0",
        "laminas/laminas-crypt": "^2.6.0",
        "laminas/laminas-db": "^2.8.2",
        "laminas/laminas-dependency-plugin": "^1.0",
        "laminas/laminas-di": "^2.6.1",
        "laminas/laminas-eventmanager": "^3.0.0",
        "laminas/laminas-feed": "^2.9.0",
        "laminas/laminas-form": "^2.10.0",
        "laminas/laminas-http": "^2.6.0",
        "laminas/laminas-i18n": "^2.7.3",
        "laminas/laminas-json": "^2.6.1",
        "laminas/laminas-log": "^2.9.1",
        "laminas/laminas-mail": "^2.9.0",
        "laminas/laminas-mime": "^2.5.0",
        "laminas/laminas-modulemanager": "^2.7",
        "laminas/laminas-mvc": "~2.7.0",
        "laminas/laminas-serializer": "^2.7.2",
        "laminas/laminas-server": "^2.6.1",
        "laminas/laminas-servicemanager": "^2.7.8",
        "laminas/laminas-session": "^2.7.3",
        "laminas/laminas-soap": "^2.7.0",
        "laminas/laminas-stdlib": "^3.2.1",
        "laminas/laminas-text": "^2.6.0",
        "laminas/laminas-uri": "^2.5.1",
        "laminas/laminas-validator": "^2.6.0",
        "laminas/laminas-view": "~2.11.2",
        "magento/composer": "~1.5.0",
        "magento/data-migration-tool": "2.3.4",
        "magento/magento-composer-installer": ">=0.1.11",
        "magento/zendframework1": "~1.14.2",
        "monolog/monolog": "^1.17",
        "paragonie/sodium_compat": "^1.6",
        "pelago/emogrifier": "^2.0.0",
        "php-amqplib/php-amqplib": "~2.7.0||~2.10.0",
        "phpseclib/mcrypt_compat": "1.0.8",
        "phpseclib/phpseclib": "2.0.*",
        "ramsey/uuid": "~3.8.0",
        "swissup/argento-m2": "^1.17",
        "swissup/module-marketplace": "^1.5",
        "symfony/console": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "symfony/event-dispatcher": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "symfony/process": "~4.1.0||~4.2.0||~4.3.0||~4.4.0",
        "tedivm/jshrink": "~1.3.0",
        "tubalmartin/cssmin": "4.1.1",
        "webonyx/graphql-php": "^0.13.8",
        "wikimedia/less.php": "~1.8.0"
    },
    "require-dev": {
        "allure-framework/allure-phpunit": "~1.2.0",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "friendsofphp/php-cs-fixer": "~2.14.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento-coding-standard": "*",
        "magento/magento2-functional-testing-framework": "~2.6.4",
        "pdepend/pdepend": "2.5.2",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpmd/phpmd": "@stable",
        "phpstan/phpstan": "^0.12.2",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "~3.4.0"
    },
    "suggest": {
        "ext-pcntl": "Need for run processes in parallel mode"
    },
    "replace": {
        "magento/module-marketplace": "100.3.4",
        "magento/module-admin-analytics": "100.3.2",
        "magento/module-admin-notification": "100.3.5",
        "magento/module-advanced-pricing-import-export": "100.3.4",
        "magento/module-amqp": "100.3.4",
        "magento/module-amqp-store": "100.3.1",
        "magento/module-analytics": "100.3.5",
        "magento/module-asynchronous-operations": "100.3.5",
        "magento/module-authorization": "100.3.4",
        "magento/module-authorizenet": "100.3.5",
        "magento/module-authorizenet-acceptjs": "100.3.4",
        "magento/module-authorizenet-cardinal": "100.3.1",
        "magento/module-authorizenet-graph-ql": "100.3.2",
        "magento/module-advanced-search": "100.3.4",
        "magento/module-backend": "101.0.5",
        "magento/module-backup": "100.3.5",
        "magento/module-braintree": "100.3.5",
        "magento/module-braintree-graph-ql": "100.3.2",
        "magento/module-bundle": "100.3.5",
        "magento/module-bundle-graph-ql": "100.3.4",
        "magento/module-bundle-import-export": "100.3.4",
        "magento/module-cache-invalidate": "100.3.4",
        "magento/module-captcha": "100.3.5",
        "magento/module-cardinal-commerce": "100.3.2",
        "magento/module-catalog": "103.0.5",
        "magento/module-catalog-customer-graph-ql": "100.3.0",
        "magento/module-catalog-analytics": "100.3.4",
        "magento/module-catalog-import-export": "101.0.5",
        "magento/module-catalog-inventory": "100.3.5",
        "magento/module-catalog-inventory-graph-ql": "100.3.4",
        "magento/module-catalog-rule": "101.1.5",
        "magento/module-catalog-rule-configurable": "100.3.5",
        "magento/module-catalog-search": "101.0.5",
        "magento/module-catalog-url-rewrite": "100.3.5",
        "magento/module-catalog-widget": "100.3.5",
        "magento/module-checkout": "100.3.5",
        "magento/module-checkout-agreements": "100.3.5",
        "magento/module-checkout-agreements-graph-ql": "100.3.1",
        "magento/module-cms": "103.0.5",
        "magento/module-cms-url-rewrite": "100.3.4",
        "magento/module-config": "101.1.5",
        "magento/module-configurable-import-export": "100.3.4",
        "magento/module-configurable-product": "100.3.5",
        "magento/module-configurable-product-sales": "100.3.4",
        "magento/module-contact": "100.3.5",
        "magento/module-cookie": "100.3.5",
        "magento/module-cron": "100.3.5",
        "magento/module-currency-symbol": "100.3.5",
        "magento/module-customer": "102.0.5",
        "magento/module-customer-analytics": "100.3.4",
        "magento/module-customer-downloadable-graph-ql": "100.3.0",
        "magento/module-customer-import-export": "100.3.5",
        "magento/module-deploy": "100.3.4",
        "magento/module-developer": "100.3.5",
        "magento/module-dhl": "100.3.5",
        "magento/module-directory": "100.3.5",
        "magento/module-directory-graph-ql": "100.3.3",
        "magento/module-downloadable": "100.3.5",
        "magento/module-downloadable-graph-ql": "100.3.4",
        "magento/module-downloadable-import-export": "100.3.5",
        "magento/module-eav": "102.0.5",
        "magento/module-elasticsearch": "100.3.5",
        "magento/module-elasticsearch-6": "100.3.4",
        "magento/module-elasticsearch-7": "100.3.0",
        "magento/module-email": "101.0.5",
        "magento/module-encryption-key": "100.3.5",
        "magento/module-fedex": "100.3.4",
        "magento/module-gift-message": "100.3.4",
        "magento/module-google-adwords": "100.3.5",
        "magento/module-google-analytics": "100.3.4",
        "magento/module-google-optimizer": "100.3.4",
        "magento/module-graph-ql": "100.3.5",
        "magento/module-graph-ql-cache": "100.3.2",
        "magento/module-catalog-graph-ql": "100.3.5",
        "magento/module-catalog-cms-graph-ql": "100.3.0",
        "magento/module-catalog-url-rewrite-graph-ql": "100.3.5",
        "magento/module-configurable-product-graph-ql": "100.3.5",
        "magento/module-customer-graph-ql": "100.3.5",
        "magento/module-eav-graph-ql": "100.3.4",
        "magento/module-swatches-graph-ql": "100.3.5",
        "magento/module-tax-graph-ql": "100.3.4",
        "magento/module-url-rewrite-graph-ql": "100.3.5",
        "magento/module-cms-url-rewrite-graph-ql": "100.3.4",
        "magento/module-weee-graph-ql": "100.3.4",
        "magento/module-cms-graph-ql": "100.3.4",
        "magento/module-grouped-import-export": "100.3.4",
        "magento/module-grouped-product": "100.3.5",
        "magento/module-grouped-catalog-inventory": "100.3.3",
        "magento/module-grouped-product-graph-ql": "100.3.4",
        "magento/module-import-export": "100.3.5",
        "magento/module-indexer": "100.3.5",
        "magento/module-instant-purchase": "100.3.5",
        "magento/module-integration": "100.3.5",
        "magento/module-layered-navigation": "100.3.4",
        "magento/module-media-gallery": "100.3.1",
        "magento/module-media-gallery-api": "100.3.0",
        "magento/module-media-storage": "100.3.5",
        "magento/module-message-queue": "100.3.4",
        "magento/module-msrp": "100.3.5",
        "magento/module-msrp-configurable-product": "100.3.3",
        "magento/module-msrp-grouped-product": "100.3.3",
        "magento/module-multishipping": "100.3.5",
        "magento/module-mysql-mq": "100.3.4",
        "magento/module-new-relic-reporting": "100.3.4",
        "magento/module-newsletter": "100.3.5",
        "magento/module-offline-payments": "100.3.4",
        "magento/module-offline-shipping": "100.3.5",
        "magento/module-page-cache": "100.3.5",
        "magento/module-payment": "100.3.5",
        "magento/module-paypal": "100.3.5",
        "magento/module-paypal-captcha": "100.3.2",
        "magento/module-paypal-graph-ql": "100.3.1",
        "magento/module-persistent": "100.3.5",
        "magento/module-product-alert": "100.3.5",
        "magento/module-product-video": "100.3.5",
        "magento/module-quote": "101.1.5",
        "magento/module-quote-analytics": "100.3.4",
        "magento/module-quote-graph-ql": "100.3.5",
        "magento/module-related-product-graph-ql": "100.3.1",
        "magento/module-release-notification": "100.3.4",
        "magento/module-reports": "100.3.5",
        "magento/module-require-js": "100.3.4",
        "magento/module-review": "100.3.5",
        "magento/module-review-analytics": "100.3.4",
        "magento/module-robots": "101.0.4",
        "magento/module-rss": "100.3.4",
        "magento/module-rule": "100.3.5",
        "magento/module-sales": "102.0.5",
        "magento/module-sales-analytics": "100.3.4",
        "magento/module-sales-graph-ql": "100.3.3",
        "magento/module-sales-inventory": "100.3.4",
        "magento/module-sales-rule": "101.1.5",
        "magento/module-sales-sequence": "100.3.4",
        "magento/module-sample-data": "100.3.4",
        "magento/module-search": "101.0.5",
        "magento/module-security": "100.3.5",
        "magento/module-send-friend": "100.3.4",
        "magento/module-send-friend-graph-ql": "100.3.3",
        "magento/module-shipping": "100.3.5",
        "magento/module-signifyd": "100.3.5",
        "magento/module-sitemap": "100.3.5",
        "magento/module-store": "101.0.5",
        "magento/module-store-graph-ql": "100.3.4",
        "magento/module-swagger": "100.3.5",
        "magento/module-swagger-webapi": "100.3.4",
        "magento/module-swagger-webapi-async": "100.3.4",
        "magento/module-swatches": "100.3.5",
        "magento/module-swatches-layered-navigation": "100.3.4",
        "magento/module-tax": "100.3.5",
        "magento/module-tax-import-export": "100.3.4",
        "magento/module-theme": "101.0.5",
        "magento/module-theme-graph-ql": "100.3.3",
        "magento/module-translation": "100.3.5",
        "magento/module-ui": "101.1.5",
        "magento/module-ups": "100.3.5",
        "magento/module-url-rewrite": "101.1.5",
        "magento/module-user": "101.1.5",
        "magento/module-usps": "100.3.5",
        "magento/module-variable": "100.3.4",
        "magento/module-vault": "101.1.5",
        "magento/module-vault-graph-ql": "100.3.2",
        "magento/module-version": "100.3.4",
        "magento/module-webapi": "100.3.4",
        "magento/module-webapi-async": "100.3.5",
        "magento/module-webapi-security": "100.3.4",
        "magento/module-weee": "100.3.5",
        "magento/module-widget": "101.1.4",
        "magento/module-wishlist": "101.1.5",
        "magento/module-wishlist-graph-ql": "100.3.3",
        "magento/module-wishlist-analytics": "100.3.4",
        "magento/theme-adminhtml-backend": "100.3.5",
        "magento/theme-frontend-blank": "100.3.5",
        "magento/theme-frontend-luma": "100.3.5",
        "magento/language-de_de": "100.3.4",
        "magento/language-en_us": "100.3.4",
        "magento/language-es_es": "100.3.4",
        "magento/language-fr_fr": "100.3.4",
        "magento/language-nl_nl": "100.3.4",
        "magento/language-pt_br": "100.3.4",
        "magento/language-zh_hans_cn": "100.3.4",
        "magento/framework": "102.0.5",
        "magento/framework-amqp": "100.3.5",
        "magento/framework-bulk": "100.3.5",
        "magento/framework-message-queue": "100.3.5",
        "trentrichardson/jquery-timepicker-addon": "1.4.3",
        "components/jquery": "1.11.0",
        "blueimp/jquery-file-upload": "5.6.14",
        "components/jqueryui": "1.10.4",
        "twbs/bootstrap": "3.1.0",
        "tinymce/tinymce": "3.4.7",
        "magento/module-tinymce-3": "100.3.5",
        "magento/module-csp": "100.3.0"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "extra": {
        "component_paths": {
            "trentrichardson/jquery-timepicker-addon": "lib/web/jquery/jquery-ui-timepicker-addon.js",
            "components/jquery": [
                "lib/web/jquery.js",
                "lib/web/jquery/jquery.min.js",
                "lib/web/jquery/jquery-migrate.js"
            ],
            "blueimp/jquery-file-upload": "lib/web/jquery/fileUploader",
            "components/jqueryui": [
                "lib/web/jquery/jquery-ui.js"
            ],
            "twbs/bootstrap": [
                "lib/web/jquery/jquery.tabs.js"
            ],
            "tinymce/tinymce": "lib/web/tiny_mce_4"
        }
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/",
            "Magento\\PhpStan\\": "dev/tests/static/framework/Magento/PhpStan/"
        }
    },
    "version": "2.3.5",
    "minimum-stability": "stable",
    "repositories": {
        "swissuplabs": {
            "type": "composer",
            "url": "https://ci.swissuplabs.com/api/packages.json"
        },
        "data-migration-tool": {
            "type": "git",
            "url": "https://github.com/magento/data-migration-tool"
        }
    }
}

**Comment by rbayet** [comment]
Hello @thomasklosinsky,

Is the content of your vendor/magento directory limited to this ?
```
composer
magento2-functional-testing-framework
magento-coding-standard
magento-composer-installer
zendframework1
``` 

And most Magento modules located in app/code/Magento ?
If so, I can confirm the issue but it's not the correct way to install Magento / Elasticsuite through composer : you will only be able to install Elasticsuite *manually*.

Please refer to https://devdocs.magento.com/guides/v2.3/install-gde/composer.html

**Comment by thomasklosinsky** [comment]
Reinstalled everything with composer only. works... thanks!
