### ISSUE TITLE
VirtualCategorySetup.php::convertSerializedRulesToJson returns Invalid column data type "" on a fresh install

### ISSUE THREAD

**Issue by amelojunior** [Smile-SA/elasticsuite#1847]
vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Setup/VirtualCategorySetup.php  Method convertSerializedRulesToJson returns Invalid column data type "" on a fresh install

### Preconditions

Magento Version : 2.3.5 CE

ElasticSuite Version : 2.9.1

Environment : Developer

Third party modules :

### Steps to reproduce

1. Create a fresh install of elasticsearch

### Expected result
1. Finish the setup:upgrade without errors

### Actual result
1. Module 'Smile_ElasticsuiteVirtualCategory':
Installing data... Upgrading data... Invalid column data type ""

**Comment by rbayet** [comment]
Hello @amelojunior,

What is the typology of your Magento version ? CE (Open Source) or EE (Commerce) ?
Is this a migration project ?

Regards,

**Comment by amelojunior** [comment]
Hi @rbayet 

Its a CE and not is a migration.

thanks!!

**Comment by rbayet** [comment]
Hi @amelojunior,

I was not able to reproduce your issue. By the error message, it seems like the attribute  "virtual_rule" might not have been created previously.

Could you tell us more about your install ?
For instance, you OS and version, your PHP version, type of Database server and version.

Regards,

**Comment by amelojunior** [comment]
@rbayet 

I'm using 
-ubuntu 19.10
-mysql 8
-php7.2

**Comment by rbayet** [comment]
Hello @amelojunior,

I may go out on a limb there, but your mysql version is probably the culprit.
As far as I know, only incoming [Magento 2.4.0 is supposed to be compatible Mysql 8.x](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/mysql.html#mysql-8-changes).

Magento 2.3.x is still [only officially compatible with MySQL 5.6 and 5.7](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#database).

Regards,

**Comment by amelojunior** [comment]
@rbayet 

I downgraded to mysql 5.7 and really solved it, thanks
