### ISSUE TITLE
autocomplete/catalogsearch products not showing

### ISSUE THREAD

**Issue by thomasklosinsky** [Smile-SA/elasticsuite#1848]
Magento v 2.3.5 p1
elasticsuite 2.9.0
elasticsearch 7.7.1
(plugins enabled !)

List of disabled modules:
Smile_ElasticsuiteCatalogGraphQl
Smile_ElasticsuiteIndices

Migrated settings and data from Magento 1 successfully...

Set "Display out of stock products" in Catalog Inventory Configuration...

Followed the instructions in elasticsuite wiki for installation and setup.
Set Catalog search to elasticsuite and disabled suggestions and recommendations - basically for testing purpose.
Indexes rebuilt...
When searching in frontend I can not find any product and there also is no autocomplete.

There are a few products showing in some categories... but not all. 
And the search is also not including categories.

There are 575 documents in catalog_product indice or ES... but there should be about 20k...

![grafik](https://user-images.githubusercontent.com/6616220/84571654-e0698c00-ad94-11ea-99d0-f5fee5cea864.png)

What I also found is that there is no option in Attributes > Product for "Used in autocomplete" as described here:
https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration
This is how the attribute "name" looks like in search config.
![grafik](https://user-images.githubusercontent.com/6616220/84570720-9336eb80-ad8f-11ea-8746-7b0661563091.png)

Seems a little weird, as if something is missing.
Any help appreciated!

**Comment by thomasklosinsky** [comment]
any experiences with incomplete product attributes and not showing products because of that?

How can I debug this?

**Comment by thomasklosinsky** [comment]
{"index":{"_index":"m2_storeview_catalog_product_20200613_172350","_type":"_doc","_id":47614}}
{"entity_id":"47614","attribute_set_id":"4","type_id":"simple","sku":"wesDUEPRE","has_options":false,"required_options":false,"created_at":"2015-04-08 13:46:00","updated_at":"2018-11-06 08:14:03","visibility":"4","price":[{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":0,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":1,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":2,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":3,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":4,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":5,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":6,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":7,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":8,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"},{"price":"775.000000","original_price":"775.000000","is_discount":false,"customer_group_id":9,"tax_class_id":1,"final_price":"775.000000","min_price":"775.000000","max_price":"775.000000"}],"indexed_attributes":["price","name","image","small_image","thumbnail","url_key","url_path","options_container","delivery_time","aw_os_product_position","aw_os_product_text","aw_os_category_position","aw_os_category_text","ean","description","short_description","status","tax_class_id","visibility","manufacturer"],"category":[{"category_id":3,"is_virtual":"false","name":"Root category for Main Website"},{"category_id":20,"is_virtual":"false","name":"Outboard & FX"},{"category_id":168,"is_virtual":"false","name":"500 Series"},{"category_id":741,"is_parent":true,"is_virtual":"false"}],"name":["WesAudio Due-Pre"],"image":["\/d\/s\/dsc_0226_2.jpg"],"small_image":["\/d\/s\/dsc_0226_2.jpg"],"thumbnail":["\/d\/s\/dsc_0226_2.jpg"],"url_key":["wesaudio-due-pre"],"url_path":["wesaudio-due-pre"],"options_container":["container2"],"option_text_options_container":["Block after Info Column"],"delivery_time":["usually 2-3 days, in urgent cases contact us so we can check est. delivery times for you"],"aw_os_product_position":["BR"],"aw_os_product_text":["CUSTOM"],"aw_os_category_position":["BR"],"aw_os_category_text":["CUSTOM"],"ean":["2500009857462"],"description":["<p><span style=\"font-size: 10pt;\"><strong>DUE-PRE<\/strong>&nbsp;<\/span><span style=\"font-size: 10pt;\">- fully discrete mic\/instrument 500 series preamp with two modes of operation.<\/span><\/p>\r\n<p><span style=\"font-size: 10pt;\">Preamp circuit is switchable between to amps: RED and GREEN<\/span><\/p>\r\n<p><span style=\"font-size: 10pt;\">RED mode is a British classic style preamp (1073) and GREEN is an American vintage style preamp (discrete opamp).&nbsp;<\/span><span style=\"font-size: 10pt;\">Both preamps have unique sonic textures known as a best classical sound preamps.<\/span><br \/><span style=\"font-size: 10pt;\">Carnhill transformers are responsibility for matching impedance and de\/symmetrization circuits.&nbsp;<\/span><span style=\"font-size: 10pt;\">Preamp is loaded with two PADs: IN 20dB PAD and OUT 8dB PAD which allows to saturate both preamp and output transformer.<\/span><br \/><span style=\"font-size: 10pt;\">Additionally DUE-PRE has front input XLR Combo socket which can be used in both ways: as a mic input and as a instrumental input.&nbsp;<\/span><span style=\"font-size: 10pt;\">Instrumental input is a high impedance input of which signal feeds input transformer through FET transistor.&nbsp;<\/span><span style=\"font-size: 10pt;\">Module can draw up to 5W of power.<\/span><\/p>"],"short_description":["<p>fully discrete mic\/instrument 500 series preamp with two modes of operation<\/p>"],"status":[1],"option_text_status":["Enabled"],"tax_class_id":[1],"option_text_tax_class_id":["Vollbesteuerte Artikel"],"manufacturer":[1173],"option_text_manufacturer":["WesAudio"],"stock":{"is_in_stock":true,"qty":1}}

this is one of the index documents for ES from the debug.log... seems complete to me.

are only products with stock indexed?
But why are no products shown in autocomplete?

**Comment by thomasklosinsky** [comment]
And the mapping looks like this:

{

    "attribute_set_id": {
        "type": "integer"
    },
    "autocomplete": {
        "type": "text",
        "fields": {
            "shingle": {
                "type": "text",
                "analyzer": "shingle"
            },
            "whitespace": {
                "type": "text",
                "analyzer": "whitespace"
            }
        },
        "analyzer": "standard"
    },
    "aw_os_category_display": {
        "type": "integer"
    },
    "aw_os_category_image": {
        "type": "keyword",
        "ignore_above": 256
    },
    "aw_os_category_position": {
        "type": "integer"
    },
    "aw_os_category_text": {
        "type": "keyword",
        "ignore_above": 256
    },
    "aw_os_product_display": {
        "type": "integer"
    },
    "aw_os_product_image": {
        "type": "keyword",
        "ignore_above": 256
    },
    "aw_os_product_position": {
        "type": "integer"
    },
    "aw_os_product_text": {
        "type": "keyword",
        "ignore_above": 256
    },
    "aw_video": {
        "type": "keyword",
        "ignore_above": 256
    },
    "cable_channels": {
        "type": "integer"
    },
    "cable_color": {
        "type": "integer"
    },
    "cable_diameter": {
        "type": "integer"
    },
    "cable_manufacturer": {
        "type": "integer"
    },
    "cable_plug_manufacturer": {
        "type": "integer"
    },
    "cable_plug_type": {
        "type": "integer"
    },
    "cable_plug_type_2": {
        "type": "integer"
    },
    "category": {
        "type": "nested",
        "properties": {
            "category_id": {
                "type": "integer"
            },
            "is_blacklisted": {
                "type": "boolean"
            },
            "is_parent": {
                "type": "boolean"
            },
            "is_virtual": {
                "type": "boolean"
            },
            "name": {
                "type": "text",
                "copy_to": [
                    "search",
                    "spelling"
                ],
                "analyzer": "standard"
            },
            "position": {
                "type": "integer"
            }
        }
    },
    "children_ids": {
        "type": "integer"
    },
    "color": {
        "type": "integer"
    },
    "configurable_attributes": {
        "type": "keyword"
    },
    "cost": {
        "type": "double"
    },
    "created_at": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "custom_design": {
        "type": "keyword"
    },
    "custom_design_from": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "custom_design_to": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "delivery_time": {
        "type": "keyword",
        "ignore_above": 256
    },
    "description": {
        "type": "keyword",
        "ignore_above": 256
    },
    "ean": {
        "type": "keyword",
        "ignore_above": 256
    },
    "entity_id": {
        "type": "integer"
    },
    "gift_message_available": {
        "type": "boolean"
    },
    "has_options": {
        "type": "boolean"
    },
    "image": {
        "type": "keyword",
        "ignore_above": 256
    },
    "image_label": {
        "type": "keyword",
        "ignore_above": 256
    },
    "indexed_attributes": {
        "type": "keyword"
    },
    "links_purchased_separately": {
        "type": "integer"
    },
    "links_title": {
        "type": "keyword",
        "ignore_above": 256
    },
    "manufacturer": {
        "type": "integer"
    },
    "media_gallery": {
        "type": "keyword",
        "ignore_above": 256
    },
    "meta_description": {
        "type": "keyword",
        "ignore_above": 256
    },
    "meta_keyword": {
        "type": "keyword",
        "ignore_above": 256
    },
    "meta_title": {
        "type": "keyword",
        "ignore_above": 256
    },
    "minimal_price": {
        "type": "double"
    },
    "monitor_field": {
        "type": "integer"
    },
    "name": {
        "type": "text",
        "fields": {
            "shingle": {
                "type": "text",
                "analyzer": "shingle"
            },
            "sortable": {
                "type": "text",
                "analyzer": "sortable",
                "fielddata": true
            },
            "whitespace": {
                "type": "text",
                "analyzer": "whitespace"
            }
        },
        "copy_to": [
            "search",
            "spelling"
        ],
        "analyzer": "standard"
    },
    "news_from_date": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "news_to_date": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "old_id": {
        "type": "integer"
    },
    "option_text_aw_os_category_display": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_aw_os_category_position": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_aw_os_product_display": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_aw_os_product_position": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_channels": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_color": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_diameter": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_manufacturer": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_plug_manufacturer": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_plug_type": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_cable_plug_type_2": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_color": {
        "type": "text",
        "fields": {
            "untouched": {
                "type": "keyword",
                "ignore_above": 256
            }
        },
        "copy_to": [
            "search",
            "spelling"
        ],
        "analyzer": "standard"
    },
    "option_text_custom_design": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_gift_message_available": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_manufacturer": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_monitor_field": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_options_container": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_page_layout": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_price_view": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_shipment_type": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_status": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_tax_class_id": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_visibility": {
        "type": "keyword",
        "ignore_above": 256
    },
    "option_text_wireless_mic_series": {
        "type": "keyword",
        "ignore_above": 256
    },
    "options_container": {
        "type": "keyword"
    },
    "page_layout": {
        "type": "keyword"
    },
    "pixi_tags": {
        "type": "keyword",
        "ignore_above": 256
    },
    "price": {
        "type": "nested",
        "properties": {
            "customer_group_id": {
                "type": "integer"
            },
            "final_price": {
                "type": "double"
            },
            "is_discount": {
                "type": "boolean"
            },
            "max_price": {
                "type": "double"
            },
            "min_price": {
                "type": "double"
            },
            "original_price": {
                "type": "double"
            },
            "price": {
                "type": "double"
            },
            "tax_class_id": {
                "type": "integer"
            }
        }
    },
    "price_type": {
        "type": "integer"
    },
    "price_view": {
        "type": "integer"
    },
    "required_options": {
        "type": "boolean"
    },
    "reviews": {
        "type": "keyword",
        "ignore_above": 256
    },
    "samples_title": {
        "type": "keyword",
        "ignore_above": 256
    },
    "search": {
        "type": "text",
        "fields": {
            "shingle": {
                "type": "text",
                "analyzer": "shingle"
            },
            "whitespace": {
                "type": "text",
                "analyzer": "whitespace"
            }
        },
        "analyzer": "standard"
    },
    "search_query": {
        "type": "nested",
        "properties": {
            "is_blacklisted": {
                "type": "boolean"
            },
            "position": {
                "type": "integer"
            },
            "query_id": {
                "type": "integer"
            }
        }
    },
    "shipment_type": {
        "type": "integer"
    },
    "short_description": {
        "type": "keyword",
        "ignore_above": 256
    },
    "sku": {
        "type": "text",
        "fields": {
            "sortable": {
                "type": "text",
                "analyzer": "sortable",
                "fielddata": true
            },
            "untouched": {
                "type": "keyword",
                "ignore_above": 256
            }
        },
        "copy_to": [
            "search",
            "spelling"
        ],
        "analyzer": "reference"
    },
    "sku_type": {
        "type": "integer"
    },
    "small_image": {
        "type": "keyword",
        "ignore_above": 256
    },
    "small_image_label": {
        "type": "keyword",
        "ignore_above": 256
    },
    "special_from_date": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "special_price": {
        "type": "double"
    },
    "special_to_date": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "spelling": {
        "type": "text",
        "fields": {
            "phonetic": {
                "type": "text",
                "analyzer": "phonetic"
            },
            "shingle": {
                "type": "text",
                "analyzer": "shingle"
            },
            "whitespace": {
                "type": "text",
                "analyzer": "whitespace"
            }
        },
        "analyzer": "standard"
    },
    "status": {
        "type": "integer"
    },
    "stock": {
        "properties": {
            "is_in_stock": {
                "type": "boolean"
            },
            "qty": {
                "type": "integer"
            }
        }
    },
    "tax_class_id": {
        "type": "integer"
    },
    "thumbnail": {
        "type": "keyword",
        "ignore_above": 256
    },
    "thumbnail_label": {
        "type": "keyword",
        "ignore_above": 256
    },
    "type_id": {
        "type": "keyword"
    },
    "updated_at": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd"
    },
    "url_key": {
        "type": "keyword",
        "ignore_above": 256
    },
    "url_path": {
        "type": "keyword",
        "ignore_above": 256
    },
    "visibility": {
        "type": "integer"
    },
    "weight": {
        "type": "text",
        "copy_to": [
            "search",
            "spelling"
        ],
        "analyzer": "standard"
    },
    "weight_type": {
        "type": "integer"
    },
    "wireless_mic_series": {
        "type": "integer"
    }

}


...
Don't know if this helps....

**Comment by thomasklosinsky** [comment]
At least I got the categories working. I resaved all of the 30k products...

But still autocomplete search is not finding anything...

Here's the debug log when searching for an entry:


[2020-06-15 07:43:12] main.DEBUG: Request Body [null] []
[2020-06-15 07:43:12] main.INFO: Request Success: {"method":"HEAD","uri":"http://localhost/das_german_catalog_category","port":9200,"headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.7.0 (Linux 4.15.0-106-generic; PHP 7.2.24-0ubuntu0.18.04.6)"]},"HTTP code":200,"duration":0.002308} []
[2020-06-15 07:43:12] main.DEBUG: Response [[]] []
[2020-06-15 07:43:12] main.INFO: curl -XHEAD 'http://localhost/das_german_catalog_category?pretty=true' [] []
[2020-06-15 07:43:12] main.DEBUG: Response: {"response":[],"method":"HEAD","uri":"http://localhost/das_german_catalog_category","HTTP code":200,"duration":0.002308} []
[2020-06-15 07:43:12] main.DEBUG: Request Body ["{\"size\":3,\"sort\":[{\"_score\":{\"order\":\"desc\"}},{\"entity_id\":{\"order\":\"desc\",\"missing\":\"_first\",\"unmapped_type\":\"keyword\"}}],\"from\":0,\"query\":{\"bool\":{\"must\":{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"bool\":{\"filter\":{\"multi_match\":{\"query\":\"Reddi\",\"fields\":[\"search^1\",\"sku^1\"],\"minimum_should_match\":\"100%\",\"tie_breaker\":1,\"boost\":1,\"type\":\"best_fields\"}},\"must\":{\"multi_match\":{\"query\":\"Reddi\",\"fields\":[\"search^1\",\"search.whitespace^10\"],\"minimum_should_match\":1,\"tie_breaker\":1.0,\"boost\":1,\"type\":\"best_fields\"}},\"boost\":1}},{\"bool\":{\"filter\":{\"multi_match\":{\"query\":\"reddi di\",\"fields\":[\"search^1\",\"sku^1\"],\"minimum_should_match\":\"100%\",\"tie_breaker\":1,\"boost\":1,\"type\":\"best_fields\"}},\"must\":{\"multi_match\":{\"query\":\"reddi di\",\"fields\":[\"search^1\",\"search.shingle^10\"],\"minimum_should_match\":1,\"tie_breaker\":1.0,\"boost\":1,\"type\":\"best_fields\"}},\"boost\":1}},{\"bool\":{\"filter\":{\"multi_match\":{\"query\":\"reddi v2\",\"fields\":[\"search^1\",\"sku^1\"],\"minimum_should_match\":\"100%\",\"tie_breaker\":1,\"boost\":1,\"type\":\"best_fields\"}},\"must\":{\"multi_match\":{\"query\":\"reddi v2\",\"fields\":[\"search^1\",\"search.shingle^10\"],\"minimum_should_match\":1,\"tie_breaker\":1.0,\"boost\":1,\"type\":\"best_fields\"}},\"boost\":1}},{\"bool\":{\"filter\":{\"multi_match\":{\"query\":\"reddio\",\"fields\":[\"search^1\",\"sku^1\"],\"minimum_should_match\":\"100%\",\"tie_breaker\":1,\"boost\":1,\"type\":\"best_fields\"}},\"must\":{\"multi_match\":{\"query\":\"reddio\",\"fields\":[\"search^1\",\"search.whitespace^10\"],\"minimum_should_match\":1,\"tie_breaker\":1.0,\"boost\":1,\"type\":\"best_fields\"}},\"boost\":1}}],\"minimum_should_match\":1,\"boost\":1}},\"boost\":1}},\"track_total_hits\":100000}"] []
[2020-06-15 07:43:12] main.INFO: Request Success: {"method":"POST","uri":"http://localhost/das_german_catalog_category/_search","port":9200,"headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.7.0 (Linux 4.15.0-106-generic; PHP 7.2.24-0ubuntu0.18.04.6)"]},"HTTP code":200,"duration":0.010541} []
[2020-06-15 07:43:12] main.DEBUG: Response [{"took":9,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}}] []
[2020-06-15 07:43:12] main.INFO: curl -XPOST 'http://localhost/das_german_catalog_category/_search?pretty=true' -d '{"size":3,"sort":[{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"bool":{"must":{"bool":{"must":[],"must_not":[],"should":[{"bool":{"filter":{"multi_match":{"query":"Reddi","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields"}},"must":{"multi_match":{"query":"Reddi","fields":["search^1","search.whitespace^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields"}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"reddi di","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields"}},"must":{"multi_match":{"query":"reddi di","fields":["search^1","search.shingle^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields"}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"reddi v2","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields"}},"must":{"multi_match":{"query":"reddi v2","fields":["search^1","search.shingle^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields"}},"boost":1}},{"bool":{"filter":{"multi_match":{"query":"reddio","fields":["search^1","sku^1"],"minimum_should_match":"100%","tie_breaker":1,"boost":1,"type":"best_fields"}},"must":{"multi_match":{"query":"reddio","fields":["search^1","search.whitespace^10"],"minimum_should_match":1,"tie_breaker":1.0,"boost":1,"type":"best_fields"}},"boost":1}}],"minimum_should_match":1,"boost":1}},"boost":1}},"track_total_hits":100000}' [] []
[2020-06-15 07:43:13] main.DEBUG: Response: {"response":{"took":9,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]}},"method":"POST","uri":"http://localhost/das_german_catalog_category/_search","HTTP code":200,"duration":0.010541} []

**Comment by rbayet** [comment]
Hello @thomasklosinsky,

Have you finally manage to identify the cause of your issue ?
Or is it still outstanding ?

Regards,

**Comment by thomasklosinsky** [comment]
Hey,
I didn‘t resolve the issue.
I ended up using another (paid) elasticsearch module which works fine...

**Comment by romainruaud** [comment]
Ok I close then, since it was very specific to your context.

Regards
