### ISSUE TITLE
Issue with "group by" clauses on MySQL 5.7

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#185]
The following query, which is used for retrieving bundle products childrens : 

```
SELECT `main`.`parent_product_id`, `main`.`product_id`, GROUP_CONCAT(DISTINCT super_table.attribute_id SEPARATOR ',') AS `configurable_attributes` FROM `catalog_product_bundle_selection` AS `main`
 LEFT JOIN `catalog_product_super_attribute` AS `super_table` ON super_table.product_id = main.parent_product_id WHERE (main.parent_product_id in (51,52,53)) GROUP BY `main`.`product_id`
```

On MySQL 5.6.28 it produces correct results : 

```
+-------------------+------------+-------------------------+
| parent_product_id | product_id | configurable_attributes |
+-------------------+------------+-------------------------+
|                51 |         21 | NULL                    |
|                51 |         22 | NULL                    |
|                51 |         26 | NULL                    |
|                51 |         29 | NULL                    |
|                51 |         32 | NULL                    |
|                51 |         33 | NULL                    |
|                51 |         34 | NULL                    |
|                51 |         35 | NULL                    |
+-------------------+------------+-------------------------+
```

But on MySQL 5.7.14 it produces the following error : 

```
ERROR 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'magento2.main.parent_product_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

**Comment by kirmorozov** [comment]
I would not expect that its an issue.
Magento has a lot of places with non-aggregation fields in select.
Please setup your mysql in less restrictive mode.

**Comment by romainruaud** [comment]
Hello @kirmorozov and thank you for your answer. The mentioned query is generated by our module, not by Magento's core.

Are you saying that even core parts of Magento would not run properly for such queries ?

Regards,

**Comment by kirmorozov** [comment]
I would put this issue to bottom of priority list, historically mysql was permissive.
Let it be permissive for few more years. 
Just put, and go on
`sql-mode = "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"`

**Comment by romainruaud** [comment]
@kirmorozov I think you make a small mistake : here is the Smile Repository for ElasticSuite module, not the Magento's one :)

But as far as I understand, the official recommendation for Magento on MySQL 5.7 is to turn off the only_full_group_by configuration.

I think we will fix the problematic queries of our module anyway.

**Comment by romainruaud** [comment]
I understood : 

- when executed via Magento the query is OK. Since Magento forces SQL_MODE to empty string : on the ``_connect()`` function of the Adapter : 

```
        $this->_connection->query("SET SQL_MODE=''");
```

- when logged and then ran on the MySQL console directly, it fails, due to the SQL Mode being different.

So this is not a bug, since the application runs the query properly.
