### ISSUE TITLE
Undefined index: name in Autocomplete/Category/ItemFactory.php

### ISSUE THREAD

**Issue by PivitParkour94** [Smile-SA/elasticsuite#1855]
### Preconditions

PHP 7.3

Magento Version : 2.3.5-p1 (Open Source)

ElasticSuite Version : N/A

Environment : Production

Third party modules :

### Steps to reproduce

Found that the following error is being thrown
[DATE] main.CRITICAL: Notice: Undefined index: name in <magento2>/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Autocomplete/Category/ItemFactory.php on line 100
 
### Expected result

Should check for the name key in the array before using it.

### Actual result

Sometimes the name is missing and throws an error.

The error being thrown doesn't seem to effect the functionality, just can become an issue when extra logs are being thrown that aren't needed.

**Comment by androshchuk** [comment]
Hello @PivitParkour94 
I can't reproduce it in my environment.
Could you provide more information when this happens?
Perhaps the problem is deeper.

Regards

**Comment by PivitParkour94** [comment]
That's the issue. Not too sure what's causing it, but somehow the document source is being loaded with the name field missing. We've just noticed the log creeping up with these errors, it most likely is bad data in the database, but verifying an array key is set before using it is a good way to avoid these issues.

We have patched it locally and it would be good to not have to maintain our own patched version, if we're getting this error once, someone somewhere else will also get this error. Just wanting to help make the module more stable.

Would you prefer I make a PR and you can accept/reject it as you see fit? I'd rather not put in the effort if it will just be rejected.

Cheers

**Comment by androshchuk** [comment]
Hello @PivitParkour94 
You can do PR and we'll consider it in the near future.

Regards

**Comment by romainruaud** [comment]
Yes, we should check the array key before using it, for sure. Most probably, we should not return anything from the ItemFactory if name is missing : we would not have anything to display into the autocomplete box.

Most probably, the origin of the bug can be : 

- the `name` attribute for categories is not set to `is_searchable=1` meaning there is nothing in the index. We should ensure that in our Setup files and/or indices XML we enforce category name to be searchable.
- the category _really_ has an empty name : in this case, we get back to step 1 and should not in any case try to display it into the autocomplete box.

@PivitParkour94 you can submit a PR if you want.

regards
