### ISSUE TITLE
failed to parse field [created_at] of type [date] - Failed to parse with all enclosed parsers

### ISSUE THREAD

**Issue by amelojunior** [Smile-SA/elasticsuite#1856]
### Preconditions

Magento Version : 2.3.5-p1 CE
-ubuntu 19.10
-mysql 5.7
-php7.2
-elasticsearch 7.7.1

ElasticSuite Version : 2.9.1

Environment : developer

### Steps to reproduce

bin/magento indexer:reindex catalogsearch_fulltext

### Expected result
index all products

### Actual result

2020-06-18 15:05:35] main.DEBUG: Response [{"took":2393,"errors":true,"items":[{"index":{"_index":"dev_default_catalog_product_20200618_150529","_type":"_doc","_id":"17321","
status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [created_at] of type [date] in document with id '17321'.
Preview of field's value: '0000-00-00 00:00:00'","caused_by":{"type":"illegal_argument_exception","reason":"failed to parse
date field [0000-00-00 00:00:00] with format [yyyy-MM-dd HH:mm:ss||yyyy-MM-dd]","caused_by":{"type":"date_time_parse_exception","reason":"Failed to parse with all enclosed parsers"}}}}},

**Comment by androshchuk** [comment]
Hello @amelojunior 
I can't reproduce it. 
Could you provide more information?

Regards

**Comment by amelojunior** [comment]
@androshchuk 

I identified that our ERP created some products with the attribute created_at = 0000-00-00 00:00:00, 
that was the reason for the problem.
