### ISSUE TITLE
The attribute model is not defined.

### ISSUE THREAD

**Issue by Lach1222** [Smile-SA/elasticsuite#1857]
Magento 2.3.5 p1
elasticsuite 2.9.1
elasticsearch 7.7.1

When you go too ether a category or run a search it results in the following error. We have tried searching our DB for any incorrect attributes models and have also tried disabling layered navigation attributes as mentioned in #1571 
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined.

Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined.
<pre>#1 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute->getJsLayout()
#2 call_user_func_array() called at [vendor/magento/framework/View/TemplateEngine/Php.php:82]
#3 Magento\Framework\View\TemplateEngine\Php->__call() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/attribute.phtml:30]
#4 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#5 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:26]
#9 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#10 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#11 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/Renderer/AbstractRenderer.php:64]
#12 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\AbstractRenderer->render() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:52]
#13 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:37]
#14 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->render() called at [app/code/Codazon/AjaxLayeredNavPro/view/frontend/templates/layer/view.phtml:58]
#15 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#16 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#17 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#18 Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#19 Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php:26]
#20 Magento\Framework\View\TemplateEngine\Php\Interceptor->render() called at [vendor/magento/framework/View/Element/Template.php:271]
#21 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:301]
#22 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1100]
#23 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1104]
#24 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:674]
#25 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:566]
#26 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:542]
#27 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#28 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#29 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#30 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#31 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#32 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#33 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#34 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#35 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#36 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#37 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#38 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#39 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#40 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#41 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#42 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#43 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#44 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#45 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#46 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:963]
#47 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#48 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#49 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#50 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:52]
#51 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#52 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#53 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#54 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#55 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#56 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:26]
#57 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/View.php:221]
#58 Magento\Framework\App\View->renderLayout() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:168]
#59 Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:110]
#60 Magento\CatalogSearch\Controller\Result\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#61 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#62 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php:108]
#63 Smile\ElasticsuiteCatalog\Plugin\CatalogSearch\ResultPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#64 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#65 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:26]
#66 Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#67 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#68 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#69 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#70 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:39]
#71 Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:162]
#72 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:98]
#73 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#74 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#75 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#76 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#77 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:73]
#78 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#79 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#80 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#81 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#82 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#83 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by androshchuk** [comment]
Hello @Lach1222 
I can't reproduce it.
Could you provide more information?

Regards

**Comment by gmalhotra02** [comment]
Any fix for this, I just installed codazone theme and got this error while making any search. I have raised with codazone team though but any help to sort it out.

Error below, on Luma theme search was working fine. 




1 exception(s): Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined. Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined. <pre>#1 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute->getJsLayout() #2 call_user_func_array() called at [vendor/magento/framework/View/TemplateEngine/Php.php:94] #3 Magento\Framework\View\TemplateEngine\Php->__call() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/attribute.phtml:30] #4 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71] #5 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273] #6 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303] #7 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/Renderer/AbstractRenderer.php:64] #8 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\AbstractRenderer->render() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:52] #9 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:37] #10 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->render() called at [app/code/Codazon/AjaxLayeredNavPro/view/frontend/templates/layer/view.phtml:58] #11 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71] #12 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273] #13 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303] #14 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1111] #15 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1115] #16 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:675] #17 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:566] #18 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:542] #19 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #20 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #21 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #22 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #24 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #25 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #26 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #27 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #28 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #29 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #30 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #31 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #32 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #33 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #34 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #35 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #36 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #37 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #38 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #39 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #40 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #41 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #42 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #43 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #44 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #45 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #46 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #47 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594] #48 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544] #49 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149] #50 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497] #51 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140] #52 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:963] #53 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58] #54 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138] #55 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153] #56 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347] #57 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258] #58 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171] #59 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58] #60 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138] #61 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153] #62 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:95] #63 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/View.php:221] #64 Magento\Framework\App\View->renderLayout() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:168] #65 Magento\CatalogSearch\Controller\Result\Index->getNotCacheableResult() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:110] #66 Magento\CatalogSearch\Controller\Result\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58] #67 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138] #68 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php:108] #69 Smile\ElasticsuiteCatalog\Plugin\CatalogSearch\ResultPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135] #70 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51] #71 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135] #72 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153] #73 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:23] #74 Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111] #75 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58] #76 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138] #77 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153] #78 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:32] #79 Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186] #80 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118] #81 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58] #82 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138] #83 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99] #84 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135] #85 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71] #86 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135] #87 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153] #88 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23] #89 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116] #90 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23] #91 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263] #92 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40] </pre>

**Comment by mgwalk** [comment]
try disabling 
'Codazon_AjaxLayeredNavPro' => 0,
/app/etc/config.php
