### ISSUE TITLE
Price declared as 'double', but indexed as string

### ISSUE THREAD

**Issue by killoff** [Smile-SA/elasticsuite#1861]
### Preconditions
No modification made to the module, no extensions that impact Elasticsuite functionality installed.

Magento Version : 2.3.4

ElasticSuite Version : 6.8.8

Environment : Magento in default mode, Ubuntu

### Steps to reproduce
`bin/magento indexer:reindex`

### Expected result
Nested property price.price (.original_price, .final_price etc.) should have float values
```
		"price": [
			{
				"price": 45.5,
				"original_price": 45.5,
				"is_discount": false,
				"customer_group_id": 0,
				"tax_class_id": 0,
				"final_price": 45.5,
				"min_price": 45.5,
				"max_price": 45.5
			},
```

### Actual result
Nested property price.price (.original_price, .final_price etc.) have string values
```
		"price": [
			{
				"price": "45.500000",
				"original_price": "45.500000",
				"is_discount": false,
				"customer_group_id": 0,
				"tax_class_id": 0,
				"final_price": "45.500000",
				"min_price": "45.500000",
				"max_price": "45.500000"
			},
```

As the result, range filter and aggregation on price give unpredictable results.

`POST /index_name/_search`
```
{
    "size": 0,
    "aggs": {
        "price": {
            "nested": {
                "path": "price"
            },
            "aggs": {
                "price": {
                    "range": {
                        "field": "price.price",
                        "ranges": [
                            {
                                "to": 10
                            },
                            {
                                "from": 10,
                                "to": 20
                            },
                            {
                                "from": 20,
                                "to": 30
                            }
                        ]
                    }
                }
            }
        }
    }
}
```

If I add this

` $indexData[$rowId]['price'][0]['price'] = (float)$indexData[$rowId]['price'][0]['price'];`

Everything works as expected.

It seems that Elasticsuite does not perform types-casting on the data being saved to elasticsearch index.

**Comment by androshchuk** [comment]
Hello @killoff 

I agree that the price format does not correspond to the declared type.
It seems that the situation is the same in clear magento2.

I couldn't find "unpredictable results". 
Could you tell me how to reproduce them and also check please, does my PR fix the problem?

Regards

**Comment by killoff** [comment]
Hi @androshchuk 

> Could you tell me how to reproduce them and also check please, does my PR fix the problem?

Thank you for the fix. It DOES fix the issue. 
However, I wouldn't use round(), just type casting to float instead `'original_price'    => (float)$originalPrice`
Or at least round with the higher precision: `'original_price'    => round($originalPrice, 5)`

> I couldn't find "unpredictable results".

I gave an example with aggregation (aggs)
I don't know whether elasticsuite supports price range filter.
The thing is, we don't use all frontend features, only indexers. But we have our custom storefront that operates with es data.
