### ISSUE TITLE
Ajax Filter "Show more" not working on custom "Shop by Manufacturer" Pages

### ISSUE THREAD

**Issue by stb** [Smile-SA/elasticsuite#1863]
Hi!
We are using a custom extension that displays all products of a manufacturer on a dedicated page. There the filters work as expected just when you press "Show more" on a filter the ajax request does not work.

For categories the request looks like this: http://magento.site/de/catalog/navigation_filter/ajax/id/1/?cat=1&filterName=attributecode&_=1593163306420

Right now the request looks like this:
http://magento.site/de/catalog/navigation_filter/ajax/%brand_name%/%attributecode%/%attributeid%/?filterName=attributecode&_=1593165116065

Any ideas how the request should look like when sent from a custom page with an attribute as selector instead of the category?

Extension: Mageplaza_Shopbybrand

Thanks!

**Comment by stb** [comment]
Any ideas?

**Comment by stb** [comment]
Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute.php is creating the link, with the following method.
`
private function getAjaxLoadUrl()
{
    $qsParams = ['filterName' => $this->getFilter()->getRequestVar()];
    $currentCategory = $this->getFilter()->getLayer()->getCurrentCategory();

    if ($currentCategory && $currentCategory->getId() && $currentCategory->getLevel() > 1) {
        $qsParams['cat'] = $currentCategory->getId();
    }

    $urlParams = ['_current' => true, '_query' => $qsParams];

    return $this->_urlBuilder->getUrl('catalog/navigation_filter/ajax', $urlParams);
}

`

**Comment by romainruaud** [comment]
Hello @stb 

Supporting third party paid extension compatibility is not part of our community support commitment.

You can contact us for commercial support if it is critical for you.

Feel free to send an email to elasticsuite@smile.fr if you are interested in this kind of commercial support.

Regards
