### ISSUE TITLE
IndexStatsProvider::sizeFormatted() must be of the type string, null returned

### ISSUE THREAD

**Issue by jocielandrade** [Smile-SA/elasticsuite#1865]
### Preconditions
Magento Version : Magento Cloud 2.3
ElasticSuite Version : 2.9.0
Environment : Developer
Third party modules : None

### Steps to reproduce
1. On Admin, open ELASTICSUITE > System > Indices

### Expected result
1. The system list indices

### Actual result
1. The system shows:

`
Fatal error: Uncaught TypeError: Return value of Smile\ElasticsuiteIndices\Model\IndexStatsProvider::sizeFormatted() must be of the type string, null returned in /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php:170 Stack trace: #0 /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php(126): Smile\ElasticsuiteIndices\Model\IndexStatsProvider->sizeFormatted(NULL) #1 /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/ResourceModel/Index/Collection.php(85): Smile\ElasticsuiteIndices\Model\IndexStatsProvider->indexStats('magento2_mexico...', NULL) #2 /app/vendor/magento/framework/Data/Collection.php(691): Smile\ElasticsuiteIndices\Model\ResourceModel\Index\Collection->loadData(false, false) #3 /app/vendor/magento/framework/Data/Collection.php(333): Magento\Framework\Data\Collection->load() #4 /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/Index/Collection.php(87): Magento\Framework\Data\Collection->getItems() in /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php on line 170
`

**Comment by androshchuk** [comment]
Hello @jocielandrade 
Could you provide your Elasticsearch Server version?

**Comment by jocielandrade** [comment]
Follow:
`
curl elasticsearch.internal:9200
{
  "name" : "ZhWtrg2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "UmjCapzPRi-yuR6JjsObRA",
  "version" : {
    "number" : "6.5.4",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "82a8aa7",
    "build_date" : "2019-01-23T12:07:18.760675Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

`

**Comment by androshchuk** [comment]
I can't reproduce it in my environment.
Can you provide me the output of $indexStats array for the problem index in this line
https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-indices/Model/IndexStatsProvider.php#L125 ?

Regards

**Comment by romainruaud** [comment]
Maybe there is something different on Magento Cloud hosted Elasticsearch server that would make the response being different ?

**Comment by davidandersson1** [comment]
Hello @androshchuk 

We have same issue and we are using magento version 2.3.5 and elastic suite version 2.9.1

As per your above question for output of $indexStats array, in my case its completely empty output of this line
https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-indices/Model/IndexStatsProvider.php#L125

We are using separate elastic server and defined in "Elasticsearch Servers List" like 178.33.4.248:9200

Is there anything else that would help us to sort out the issue.

Can you please provide your view for same.

Thanks,
David

**Comment by androshchuk** [comment]
Hello @davidandersson1 

Unfortunately, I was never able to reproduce this error.
I can only suggest this solution https://github.com/androshchuk/elasticsuite/commit/eb4342364d0cdd132b927761aac12e5053b078be

Regards

**Comment by davidandersson1** [comment]
Hi @androshchuk 

Thanks, it's work with above suggested solution and i can Indices with Index status.

Some index status with EXTERNAL, some with GHOST and some with LIVE.

So what does it means exactly? is it fine if we remove Indices with status "EXTERNAL"?

Can you please provide your view for the same.

Thanks,
David

**Comment by romainruaud** [comment]
Please read the original feature/issue ticket : https://github.com/Smile-SA/elasticsuite/issues/1606

Quick recap : 

- live indices : they are actually used by your website, cannot be deleted (the delete action is not visible/possible)
- external indices : they are not belonging to your website (they have a different alias, or no alias at all, or even not related with Elasticsuite), cannot be deleted (the delete action is not visible/possible)
- ghost indices : indices belonging to your website but that never finished indexing properly, they can be safely deleted through the admin panel.

**Comment by davidandersson1** [comment]
Hi @romainruaud 

Thanks for your reply.

I understand about external indices like we are not able to delete through back office and they are not belonging to website.

But somehow if we have to delete those external indices forcefully then is it good to use below syntax?

curl -XDELETE http://localhost:9200/{Index Title}

Where {Index Title} same as display on back office grid.

Thanks,
David Andersson
