### ISSUE TITLE
Graphql Internal Server Error Get Product Filter By Multiple Category Id

### ISSUE THREAD

**Issue by alexwijanarko** [Smile-SA/elasticsuite#1866]
### Preconditions
Magento Version : Magento EE 2.3.4
ElasticSuite Version : 2.8.4
Environment : Developer
Third party modules : - 

### Steps to reproduce
1. Call {{base_url}}/graphql with query :
```
{
  products(
	search:"test"
	filter: {category_id: {in:["4","5"]}}
  )
  {
	items {
  	id
  	name
  	sku
	}
	total_count
	page_info {
  	page_size
	}
  }
}
```

### Expected result

1. Return data products from category 4 and 5

### Actual result

1. Internal Server Error
2. Log from exception.log :
`report.ERROR: Warning: Illegal offset type in /xxx/vendor/magento/module-catalog/Model/CategoryRepository.php on line 135 {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Warning: Illegal offset type in /xxx/vendor/magento/module-catalog/Model/CategoryRepository.php on line 135 at /xxx/vendor/webonyx/graphql-php/src/Error/Error.php:174, Exception(code: 0): Warning: Illegal offset type in /xxx/vendor/magento/module-catalog/Model/CategoryRepository.php on line 135 at /xxx/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

**Comment by rbayet** [comment]
Also confirmed on a CE 2.3.4.

The graphQL query works on Magento's Elasticsearch 6+ connector.

**Comment by rbayet** [comment]
Also affects Elasticsuite 2.9.x on Magento 2.3.5+
