### ISSUE TITLE
Product shown in parent category

### ISSUE THREAD

**Issue by kerlama** [Smile-SA/elasticsuite#1867]
Hi,
this is possible duplicate but I could not find any solution for this.

Product is shown in parent category because its anchored.

### Preconditions
Magento Version : 2.3.5
ElasticSuite Version : 2.9.1
Environment : production mode

### Steps to reproduce
I have category structure like this:

Category 1
|_ Sub category 1

Product is assigned to Sub Category 1 only. Category 1 is set as anchor, by elastic suite module.

When you go to Category 1 page, product is shown, which should not be the case.

### Expected result
1. Product should not be shown

### Actual result
1. Product is shown on parent

**Comment by androshchuk** [comment]
Hello @kerlama 
This is the default behavior of Magento2
You can check it on clean Magento2 without Elasticsuite.

Regards
