### ISSUE TITLE
[dev question] Get all products of a category programmatically, with ElasticSuite virtual category support

### ISSUE THREAD

**Issue by amenk** [Smile-SA/elasticsuite#1868]
We have a special category on our page where we "just" want to show all products instead of only the first page of products. Also this category does not have any sidebar or toolbar.

In earlier Magento versions we succeeded with 

    class ProductSelector extends \Magento\Catalog\Block\Product\ListProduct {
        protected function _beforeToHtml() {
            $this->getToolbarBlock()->setData('_current_limit', PHP_INT_MAX);
            $this->getToolbarBlock()->setData('_current_grid_order', 'name');
            return parent::_beforeToHtml();
        }
    }

This worked for a while but is not very stable / upgrade safe and manipulating the toolbar block does not seem right.

We so thought it is a good idea to get a the category collection on a lower level:

    private function initializeProductCollection()
    {
        /**
         * @var $category Category
         */
        $category = $this->registry->registry('current_category');
        $collection = $category->getProductCollection();
        $this->collectionFilter->filter($collection, $category);
        $collection->addOrder('name', Collection::SORT_ORDER_ASC);

        return $collection;
    }
}

But this now does not support the ElasticSuite functions of virtual categories. Virtual categories are just empty.

Can you suggest a better way to "simply" get a category-product-list, but without the toolbars limits, supporting elasticsuite?

I already tried

    /** @var \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory */
    protected $fulltextCollectionFactory;

    private function initializeProductCollection()
    {
        /**
         * @var $category Category
         */
        $category = $this->registry->registry('current_category');
        $collection = $this->fulltextCollectionFactory->create();
        $collection->addCategoryFilter($category);
        $collection->addOrder('name', Collection::SORT_ORDER_ASC);

        return $collection;
    }

But this just does not return any products as well.

Any hints are appreciated :)

**Comment by amenk** [comment]
Does anybody have some hint here? I would have asked on StackExchange but I find it very specific to elasticsuite.

**Comment by romainruaud** [comment]
Hello @amenk 

You are right, the ``addCategoryFilter`` would result in applying a filter based only on the `category.category_id` field during the ES query : https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L334

Most probably, if you want to deal with the fact that category can be virtual or not, you should take inspiration on the layer filter from the virtual category module : https://github.com/Smile-SA/elasticsuite/blob/2.9.x/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php

Maybe we could add a plugin on `addCategoryFilter` method inside the VirtualCategory to ensure the same behavior.

Regards

**Comment by amenk** [comment]
Thank you @romainruaud . Not quite sure how the code to fetch the products will look then :) But I will try...

**Comment by amenk** [comment]
This seems to work


	<?php

	use Magento\Catalog\Api\CategoryRepositoryInterface;
	use Magento\Catalog\Block\Product\Context;
	use Magento\Catalog\Model\Category;
	use Magento\Catalog\Model\Layer\Resolver;
	use Magento\Framework\Data\Collection;
	use Magento\Framework\Data\Helper\PostHelper;
	use Magento\Framework\Registry;
	use Magento\Framework\Url\Helper\Data;

	class ProductSelector extends \Magento\Catalog\Block\Product\ListProduct {
	    /** @var Registry */
	    protected $registry;

	    /** @var \Magento\Catalog\Model\Layer\Category\CollectionFilter */
	    protected $collectionFilter;

	    /** @var \Magento\Catalog\Model\Layer\Category */
	    protected $layer;

	    /** @var \Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category */
	    protected $filter;

	    public function __construct(
		Context $context,
		PostHelper $postDataHelper,
		Resolver $layerResolver,
		CategoryRepositoryInterface $categoryRepository,
		Data $urlHelper,
		Registry $registry,
		\Magento\Catalog\Model\Layer\Category\CollectionFilter $collectionFilter,
		\Magento\Catalog\Model\Layer\Category $layer,
		\Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\CategoryFactory $filter,
		array $data = []
	    ) {
		$this->registry = $registry;
		$this->collectionFilter = $collectionFilter;
		$this->layer = $layer;
		$this->filter = $filter;
		parent::__construct($context, $postDataHelper, $layerResolver, $categoryRepository, $urlHelper, $data);
	    }

	    protected function _beforeToHtml() {
		$collection = $this->initializeProductCollection();
		$collection->load(); // we load so beforeToHtml does not load again
		$this->setCollection($collection);
		$this->setToolbarBlockName(null); // just for additional safety

		return parent::_beforeToHtml();
	    }

	    private function initializeProductCollection()
	    {
		/**
		 * @var $category Category
		 */
		$category = $this->registry->registry('current_category');
		$this->layer->setCurrentCategory($category);
		$filter = $this->filter->create(['layer' => $this->layer]);
		$filter->apply($this->getRequest());
		$collection = $this->layer->getProductCollection();

		$collection->addOrder('name', Collection::SORT_ORDER_ASC);

		return $collection;
	    }
	}
