### ISSUE TITLE
Error: Call to a member function getSearchQueriesByChildren() on string in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 71

### ISSUE THREAD

**Issue by Nielex** [Smile-SA/elasticsuite#187]
I get this error when I try to load the result search page.

The function getSearchQueriesByChildren() executes on $currentCategory->getVirtualRule(). In my case $currentCategory->getVirtualRule() is a string like this:

"a:6:{s:4:"type";s:62:"Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Combine";s:9:"attribute";N;s:8:"operator";N;s:5:"value";s:1:"1";s:18:"is_value_processed";N;s:10:"aggregator";s:3:"all";}" 

That explains the error, but is not clear to me if I did something wrong in the config/install of that this is a issue.

**Comment by Nielex** [comment]
I get the same kind of error when I'm opening a category page.

Error: Call to a member function getCategorySearchQuery() on null in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 98.

In this situation is $currentCategory->getVirtualRule() NULL.

**Comment by afoucret** [comment]
Hi @Nielex, did you run the setup:upgrade script, clean all caches and di ?

Did you upgrade from a previous version of ElasticSuite ?

**Comment by Nielex** [comment]
Hi @afoucret,

I did all steps, setup, compile, etc. And I didn't do an upgrade of ElasticSuite, but it isn't a clean Magento shop where I encounter this issues.

When I disable all f me custom modules, its works fine. I think something conflicts whit each other. Don't know what, yet. 

How does get $currentCategory->getVirtualRule() set? That is not really clear to me at the moment.

**Comment by afoucret** [comment]
What version of ElasticSuite are you using ?
Did you proceed to a migration from v.2.0.x to v2.1.x or v.2.2.x ?

**Comment by gewaechshaus** [comment]
Running into the same issue on an Magento 2.1.2 / Ubuntu 16.04 instance... Fresh composer installation.

**Comment by gewaechshaus** [comment]
I manualy cleaned all related stuff in var folder by
     rm -rf view_preprocessed/* generation/* di/* cache/* page_cache/*
and did the same to the static folder...

After that I did a setup:upgrade :di:compile and :static-content:deploy again.
Same result in my case.
https://www.makerdise.com/mechanik.html

**Comment by afoucret** [comment]
Hi @Nielex , Hi @gewaechshaus 

To investigate this bug I will need you to respond the following questions :

* Magento version ?
* ElasticSuite version ?
* Did you upgrade from an ElasticSuite version < 2.2.0 ?
* Are you using flat categories ?
* Are you using a root category that is not with the id 2

That should be enough to begin to see what's wrong

**Comment by gewaechshaus** [comment]
HI @afoucret - and BTW many thanks to you...

- 2.1.2
- 2.2 (stated in composer.json)
- N
- Y
- N

**Comment by afoucret** [comment]
What if you disable flat categories ?
I try to enable it (for other purposes) this afternoon and I had several issues with virtual categories.

**Comment by gewaechshaus** [comment]
Bingo...

**Comment by gewaechshaus** [comment]
There also seems to be an issue with the color attribute... (maybe cause I didn't configure it completly)
https://www.makerdise.com/3d-druck/filament.html
I can only choose between to colors in layered navigation...

**Comment by afoucret** [comment]
At least, now, you can work with this workaround.

We will release a patch to support flat categories in the next release (2.3.x) expected in few weeks and let this issue open until then.

**Comment by gewaechshaus** [comment]
@afoucret - for sure... Thanks for offering such a nice piece of hard work/ clean code!
I am looking forward to the next release, meanwhile I'll study the docu/config.

**Comment by afoucret** [comment]
@gewaechshaus 

Thanks for being so supportive with us and do no hesitate to spread the module (github stars, tweets, ...). The more users we have, the more the module will be relevant.

For the color attribue problem, can you please fill a new issue ? We try to keep subjects separated and tracker as clean as possible

**Comment by gewaechshaus** [comment]
@afoucret - do you have an idea what is causing the limitation on the color attribute in the layered navigation right here:
https://www.makerdise.com/3d-druck/filament.html

I tested all combinations related to this https://github.com/Smile-SA/elasticsuite/wiki/Attribute%20configuration

Maybe some problem with indexation? I will have to install the head plugin...

**Comment by gewaechshaus** [comment]
Sorry, we were both posting at the same moment...

**Comment by Nielex** [comment]
@afoucret ,

sorry for my late response. The flat tables where the issue for me to. They get enabled through xml settings in a custom module.

Is there a possibility in the future that the smile_elasticsuite would be compatible with the flat tables turn on?

**Comment by afoucret** [comment]
Hi @Nielex,

Happy to see, the workaround is OK for you too.

As explained in a previous response we will try to get the module compatible in version 2.3.0 (or maybe release 2.4.0 if it is too difficult). I let this issue open until the module will be compatible with category flat table.

**Comment by Nielex** [comment]
Oh sorry, I missed that response. But good to hear its in the scope. I'll look forward to see that feature and to see the module is getting better and better. I'm loving it already and I'll try to do my best to contribute to it.

**Comment by mantonuk** [comment]
@afoucret tnx
it's duplicate
https://github.com/Smile-SA/elasticsuite/issues/205
excuse me about that

**Comment by romainruaud** [comment]
Just a small update, for me, when activating flat categories, the error is the following : 

```
Exception #0 (Exception): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/magento/src/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 150

Exception #0 (Exception): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/magento/src/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 150

```

To anyone facing this error, the workaround is the same as said before : disabling Flat Categories.

We will try to provide a fix for this one soon.

**Comment by afoucret** [comment]
PR #231 fix this one and has been merged in branch 2.3.x.
Will be available in the 2.3.x release.

**Comment by gloong** [comment]
The fix for this issue is for Magento 2.1.x, what of the fix for Magento 2.0.x?

**Comment by afoucret** [comment]
We do not plan to backport this one on older version since the code (both Magento and ElasticSuite) has evolved a lot since then.

To be less specific, we do not consider Magento 2.0.x is ready for production and we encourage all our client to migrate to Magento > 2.1.x as soon as possible. We only fix security problem for Magento 2.0.

BR,

**Comment by Hesoy** [comment]
Same issue on Mage v2.2.1, flat categories disabled.

**Comment by Mr-Robby** [comment]
@Hesoy Hi, did you find solution to fix this issue?

**Comment by Hesoy** [comment]
@Mr-Robby Hi, yes, check this issue #951

**Comment by mehrdadhosseinzadeh** [comment]
@Nielex can you help me about this problem ?
please see Fatal error: Uncaught Error: Call to a member function getCategorySearchQuery() on null i
