### ISSUE TITLE
Does it Work with ElasticSearch 7.x?

### ISSUE THREAD

**Issue by uandiweb** [Smile-SA/elasticsuite#1870]
I would like to use this great search tool, but at the same time I want to keep using ElasticSearch 7.x.

Thank you

**Comment by androshchuk** [comment]
Hello @uandiweb 
Yes. Our module supports ElasticSearch 7.x since version 2.9.0 https://github.com/Smile-SA/elasticsuite/releases/tag/2.9.0

Regards
