### ISSUE TITLE
smile/elasticsuite version 2.9.0 with Magento 2.3.4

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1874]
Hello,

Can you please let us know, does module version 2.9.0 should work fine with Magento version 2.3.4? because we have magento version 2.3.4 on production so before upgrade the module its really important for us to know about compatibility .

Looking forward to hearing from you!

Thanks,
David Andersson

**Comment by androshchuk** [comment]
Hello @davidandersson1 
If I'm not mistaken - for correct work of our module version 2.9.x is required Magento 2.3.5 

Regards

**Comment by davidandersson1** [comment]
Hi @androshchuk 

Thanks a lot for your feedback.
