### ISSUE TITLE
Layered navigation checkboxes/filters wait a little bit before reloading page.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Smile-SA/elasticsuite#1879]
It is frustrating when the Layered navigation checkboxes the page refreshes constantly but user might be trying to select multiple filter.

**Describe the solution you'd like**
After a slight delay and no user activity (mouse/touch/key input) for some ms, then apply the selected/changed filters?

**Describe alternatives you've considered**
Have considered ajax, but this is not implemented in elasticsuite and this would still be a problem if it was just not as noticable.

I could try to record a video example of this perhaps.

To reproduce the issue, have a drop down layered navigation enabled attribute.
Click on 1 option, then click on another option within a short time.
The page reloads but only the first selected option is selected.
Expecting all selected filters to be applied.

**Comment by duffner** [comment]
@romainruaud, is Ajax in the roadmap for ElasticSuite?

**Comment by barryvdh** [comment]
Maybe you can trigger the loading screen? `jQuery('body').trigger('processStart');`

**Comment by romainruaud** [comment]
2 years old issue -> I close.

Feel free to open a new one if needed.

Regards
