### ISSUE TITLE
Smile_ElasticsuiteIndices module improve index performance?

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1883]
Hello,

We have recently upgraded Magento version 2.3.5 so now we have Elastic suite version 2.9.1 according to composer update.

We have noticed Smile's 2 separate modules fetched "Smile_ElasticsuiteCatalogGraphQl" and "Smile_ElasticsuiteIndices" but at this time we have disabled it.

So we want to know, does both module should improve performance during index time or exactly for which purpose of those modules.

Can you please provide your view for the same.

Thanks,
David Andersson

**Comment by romainruaud** [comment]
Hello,

ElasticSuiteCatalogGraphQl is here to properly plug Elasticsuite with graphQL search and categories query, it also improves a lot performances of these queries. For me there is no need to disable it.

ElasticSuiteIndices is here to help you "managing" (or at least, monitorigin) your Elasticsearch server and indices through the back-office, there is no need to disable this module.

Regards

**Comment by davidandersson1** [comment]
Hi @romainruaud 

Thanks a lot for your view.

**Comment by davidandersson1** [comment]
Hello @romainruaud 

Hope you are doing well.

I have enabled both modules on production server and try to check indices through back office but it will throw error on server's php error log like

[23-Jul-2020 03:01:49 UTC] PHP Fatal error:  Uncaught TypeError: Return value of Smile\ElasticsuiteIndices\Model\IndexStatsProvider::sizeFormatted() must be of the type string, null returned in /../../../store/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php:170
Stack trace:
#0 /../../../store/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php(126): Smile\ElasticsuiteIndices\Model\IndexStatsProvider->sizeFormatted(NULL)
#1 /../../../store/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/ResourceModel/Index/Collection.php(85): Smile\ElasticsuiteIndices\Model\IndexStatsProvider->indexStats('magento2_defaul...', 'magento2_defaul...')
#2 /../../../store/vendor/magento/framework/Data/Collection.php(691): Smile\ElasticsuiteIndices\Model\ResourceModel\Index\Collection->loadData(false, false)
#3 /../../../store/vendor/magento/framework/Data/Collection.php(333): in /../../../store/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatsProvider.php on line 170

After enabled both modules, I had ran all magento core commands like upgrade,compile,static content and cache clear,flush etc..

Is there any particular setting for it?

Can you please help!

Thanks,
David Andersson

**Comment by romainruaud** [comment]
yes this issue is followed in #1865
