### ISSUE TITLE
[Top Priority] Magento 2.4 compatibility

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#1888]
As the title said, this one is top priority.

Target branch for this : master. I'll try to backport it into 2.9 **if possible** but I don't expect everything to be BC.

If you can also adapt the Travis build strategy, that'd be appreciated. Let me know if you're unfamiliar with this.

**Comment by refueledinc** [comment]
@romainruaud do you have an ETA on M2.4 support?

**Comment by romainruaud** [comment]
@refueledinc we hope to release a new major 2.10 version as soon as possible.

In the meantime, if you are starting to use the extension with Magento 2.4 please use dev-master branch, but keep in mind it's considered unstable for now.

Regards

**Comment by romainruaud** [comment]
2.10.0 to be released asap ! :)
