### ISSUE TITLE
install on magento 2.4

### ISSUE THREAD

**Issue by abolfazlayoubi** [Smile-SA/elasticsuite#1897]
### Preconditions

Magento Version :2.4

ElasticSuite Version :2.9

Environment :

Third party modules :

### Actual result

1.Uncaught Error: Class 'Magento\CatalogSearch\Model\ResourceModel\Engine' not found in /home/abolfazl/www/html/magento24/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Engine.php:25

**Comment by abolfazlayoubi** [comment]
change file Smile\ElasticsuiteCatalog\Model\ResourceModel\Engine

change line from in :
use Magento\CatalogSearch\Model\ResourceModel\Engine as MySqlEngine;
to in :
use Magento\Elasticsearch\Model\ResourceModel\Engine as MySqlEngine;

**Comment by romainruaud** [comment]
Hello @abolfazlayoubi , we'll release a new major 2.10.0 version as long as a new branch 2.10.x for Magento 2.4 compatibility, as soon as possible.

If you want to use the module with Magento 2.4 for now, please use the __master__ branch but keep in mind it's considered as an unstable branch for now
