### ISSUE TITLE
autocomplete not showing products

### ISSUE THREAD

**Issue by xkinkade** [Smile-SA/elasticsuite#1910]
I followed the install instructions in the elasticsuite wiki.  I am using Luma theme with sample data.

When I type a word into the search box I do not get any product results. 

### Preconditions

Magento Version : Magento (CE) v 2.3.5 p1

ElasticSuite Version : 2.9.2  elasticsearch 7.7.0

Environment : Developer

Third party modules : base install

### Steps to reproduce

In the search box I type in the word bag

### Expected result

I expect products to show in the suggestions

### Actual result

No products

I was able to fix this by changing

src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml

xml: request name="catalog_product_autocomplete" label="Catalog Product Autocomplete" index="catalog_product" track_total_hits="0" fulltext="true"

track_total_hists from "0" to "true"

revised xml: request name="catalog_product_autocomplete" label="Catalog Product Autocomplete" index="catalog_product" track_total_hits="true" fulltext="true"

I don't know if that is the correct action.

**Comment by Neos2007** [comment]
Same issue for me: Magento 2.4.0 + elsaticsearch  server 7.x (tested with 7.2.1 and 7.7.1)  + elasticSuite 2.10.0.
@xkinkade your solution fixed the problem.
Note:
I also tested with elastic search 6.8.2 and there were no problems with autocomplete.

**Comment by bmelman** [comment]
Had the same issue Magento 2.3.5 elasticsearch 7.8.0 and elasticsuite 2.10.0, @xkinkade 's solution fixed it!

**Comment by romainruaud** [comment]
For me this one is also related with the "pagesize" issue (#1903 #1912 and so on).

The fix in #1914 does also resolve your issue on my local dev environment.

Please upgrade to either 2.10.1 or 2.9.3 (to be released in a couple of minutes) and let us know if this still happens.

Regards
