### ISSUE TITLE
Virtual Category - Get Category Ids by Product

### ISSUE THREAD

**Issue by hofstein** [Smile-SA/elasticsuite#1913]
Hey,

is it possible to get the category ids by product when using only virtual categories?

Regards
Marcus

**Comment by rbayet** [comment]
Hello @hofstein,

**Foreword :** **do _not_ build your entire catalog using virtual categories**, especially if you have a huge category tree and lots of products. This is not what virtual categories are intended for and you will have many performance issues on the Magento2 side and on the Elasticsearch server side.

**About your question**
By definition, we don't know in advance that a product belongs to a virtual category until that query is executed.
So to know whose virtual categories a product belong to, a naïve approach would be to loop on each of your virtual categories, and build/execute that query + a filter for that product id to see if the product is there.
**=> Not the valid approach.**

Fortunately, Elasticsearch provides the [percolation mechanism](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html) which acts in an opposite way to standard search 
- with the default _search mechanisms, you add documents to an index, and you perform _search requests on that index which provides documents (that's the way Elastic works for products)
- with the _percolate mechanisms, you add "queries as documents" to an index, and you perform _percolate requests by providing either documents or document ids (located in another index), the response will be a list of those "queries as documents"

The official document is a bit scarse, so you might have to find [third party content ](https://medium.com/@ajones1_999/understanding-the-elasticsearch-percolator-4e5c15b2dc33) a bit more explanatory and recent than that [very old official post blog](https://www.elastic.co/blog/percolator) about it.

Regards,

**Comment by rbayet** [comment]
@hofstein for implementation, you could look at https://github.com/Smile-SA/magento2-module-elasticsuite-targetrule (Magento2 2.3.x only unfortunately) which replaces the Magento_TargetRule module and 
- replace the target rule conditions engine by the one used for virtual categories and search optimizers
- indexes the target rules and their corresponding search queries into a dedicated index
- uses percolation in the frontend to determine whose target rules a product matches

Regards,
