### ISSUE TITLE
ProductCollection _pageSize is null

### ISSUE THREAD

**Issue by Lukas-G21** [Smile-SA/elasticsuite#1917]
ProductCollection _pageSize is null causing  products grid to show all collection products. Pagination shows correct amount of pages but grid itself shows all products. E.g. _totalRecords is 67. There are 3 pages in the toolbar and each page shows same 67 products.

### Preconditions
Magento Version : 2.3.5 CE
ElasticSuite Version : 2.9.2
Environment : Developer & Production

### Steps to reproduce

1.  Set default page size to 30
2.  Product grid component for category is set to default

### Expected result
1. Product grid should show correct amount of products divided by pages

### Actual result

1. Product grid shows all _totalRecords on each available category page

**Comment by Bashev** [comment]
see #1914 :)

**Comment by Lukas-G21** [comment]
@Bashev Applied #1914 PR as patch. 1st page is still showing all collection products with no limit. Second, thrird pages and so on is showing results not found message with 0 products.

**Comment by Bashev** [comment]
> 
> 
> @Bashev Applied #1914 PR as patch. 1st page is still showing all collection products with no limit. Second, thrird pages and so on is showing results not found message with 0 products.

Thank you for feedback, will check, what i miss to commit. I fix it on production first.

**Comment by Bashev** [comment]
@Lukas-G21 my mistake (of course) it define new function, but not use it... you can check changes again.

**Comment by Lukas-G21** [comment]
@Bashev After last commit pagination works correctly, Thank you for quick replies :)

**Comment by tiberiucontiu** [comment]
I found the very same issue with M2.3.4, Elastic 5.7 and Smile v. 2.8.9
I can see the version is not maintained anymore, but this could be useful for somebody still using this versions.
The quick fix was to downgrade Smile to v. 2.8.8.
We are planing a Magento upgrade to 2.4 and then we will upgrade also Smile to latest version. 

We appreciate your work!

**Comment by romainruaud** [comment]
I consider all of this pagesize issue as critical, and will release a 2.8.10 as well even if this should not be maintained anymore.

I'll have a look on #1914 as well, thank you for providing it @Bashev

**Comment by choleaoum** [comment]
> I consider all of this pagesize issue as critical, and will release a 2.8.10 as well even if this should not be maintained anymore.
> 
> I'll have a look on #1914 as well, thank you for providing it @Bashev

The PR fixes the pagination issue for category searches but with query search its still happening for me. 

Magento 2.4 using Porto Theme

**Comment by romainruaud** [comment]
Fixed in 2.8.10, 2.9.3 and 2.10.1 minor releases
