### ISSUE TITLE
Filter sliders are only click-based on mobile, very raw experience.

### ISSUE THREAD

**Issue by giograf** [Smile-SA/elasticsuite#1919]
For those attributes that use sliders for filtering, user experience on mobile is very poor.
It is impossible to drag thumb(s) along the track.
Thumb is expected to be draggable, but it is not, it seems like it just was not thought through for mobiles.
### Preconditions
Bug can be found in the elasticsuite demo.
I am using my own phone, which is Huawei Mate Pro 20 / Chrome, our customer has the same issue.
http://demo.magento-elastic-suite.io/index.php/women/tops-women/jackets-women.html

### Steps to reproduce
1. Follow the link above on a mobile device.
2. Open product filters.
3. Try to toggle the price filter.

### Expected result

1. I need to be able to press a thumb and move it to the position on track that is relevant to me.
Track should be continuous an effect immediate: https://material.io/components/sliders#usage

### Actual result
1. 
![SVID-20200813-133427-1](https://user-images.githubusercontent.com/15056756/90125967-94729d80-dd6b-11ea-943d-e62862b8011d.gif)

**Comment by romainruaud** [comment]
Fixed by #2138

**Comment by harrigo** [comment]
I'm intermittently getting this issue on mobile. Anyone else experiencing this?
