### ISSUE TITLE
TypeError: getFrontTab() is undefined

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#1923]
After enabling Smile_ElasticsuiteCatalog the attribute edit screen is broken. The console quits with an error message: "Uncaught TypeError: getFrontTab() is undefined" referring to file \vendor\smile\elasticsuite\src\module-elasticsuite-catalog\view\adminhtml\templates\catalog\product\attribute\js.phtml line 238-

### Preconditions

Magento Version : 2.4.0

ElasticSuite Version : 2.10.0

Environment : Developer

Third party modules :

### Steps to reproduce

1. Install modules Smile_ElasticsuiteCore and Smile_ElasticsuiteCatalog
2. Go to shops -> attribute -> product
3. Visit the edit screen of any attribute

### Expected result

1. The edit screen should work as usual

### Actual result

1. Console comes up with the error message "TypeError: getFrontTab() is undefined"
2. Impossible to save attribute changes, the save buttons are unresponsive

**Comment by OvalMedia** [comment]
The error goes away once the module Smile_ElasticsuiteSwatches is enabled as well.

**Comment by romainruaud** [comment]
Well you are not supposed to disable the Smile_ElasticsuiteSwatches module.

So there's not much that can be said about this one I guess.

Would you mind if we close ?

**Comment by OvalMedia** [comment]
I would suggest you make it mandantory (dependent).

**Comment by romainruaud** [comment]
The ElasticsuiteSwatches module is included in the package already. I'm not sure there is much more we can do.

**Comment by romainruaud** [comment]
I close this one, nothing more can be done here I guess.

Regards
