### ISSUE TITLE
quantity_and_stock_status doens't show up in Category layered navigation filter

### ISSUE THREAD

**Issue by maurisource** [Smile-SA/elasticsuite#1924]
I'm trying to have the stock status shown up in the Filter. I cannot figure out how to add "quantity_and_stock_status" default attribute to show up on the frontend Category layered navigation filter.
Here's my config:
![Screen Shot 2020-08-20 at 15 37 15](https://user-images.githubusercontent.com/1178609/90816922-095d4e80-e2fb-11ea-9900-ac0ed435681a.png)

If I create any other drop-down attributes, it shows up in Category layered navigation filter

Can someone please explain why "quantity_and_stock_status" is not supported by this module?

I'm trying to have the stock status shown up in the Filter

**Comment by romainruaud** [comment]
That's not working, this is not a "real" attribute in Magento actually, having it displayed as a layered navigation filter would require more work, since it would imply to create a filter based on the `stock.is_in_stock` field.

Regards
