### ISSUE TITLE
Autocomplete showing product names only

### ISSUE THREAD

**Issue by ivagarfitt** [Smile-SA/elasticsuite#1929]
Magento version: 2.3.5-p2
Elasticsuite version: 2.9.2

Because `track_total_hits` is set to `0` autocomplete not showing product details like images, names, etc.
When this is set to `true` all working fine. 

https://github.com/Smile-SA/elasticsuite/blob/097f17cc94c6af4dda9c684ea8597d4541665326/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml#L33

**Comment by vahonc** [comment]
Hello @ivagarfitt 

I don't think that it's a good idea to set the `track_total_hits` to `true` for autocomplete. Not so long ago, we had an issue linked with this. [Here](https://github.com/Smile-SA/elasticsuite/pull/1914) you could find a solution that might fix your problem or please try to upgrade/re-install ElasticSuite to the last version.

Best regards

**Comment by romainruaud** [comment]
Hi @ivagarfitt ,

@vahonc is right, track_total_hits is not the culprit here, even if it looks like an usual suspect. 

#1914 should be enough to resolve the issue, so please upgrade to 2.9.3 version of Elaticsuite.

Regards
