### ISSUE TITLE
Notice: Trying to access array offset on value of type int - Layer Navigation - Swatches

### ISSUE THREAD

**Issue by tiberiucontiu** [Smile-SA/elasticsuite#1931]
### Preconditions

PHP7.4 & Mysql 8

Magento Version : 2.4.0

ElasticSuite Version: 2.10.0

Environment: Production mode

### Steps to reproduce

1. Configure a product attribute of type "Visual Swatch" 
2. Add labels, one label should start with a space
3. Make the attribute filterable and set it to show up in layer navigation
4. Create products with the values setup on the created attribute
5. Navigate to Catalog Product Listing page 

### Expected result
1.The layer navigation should be shown and work properly

### Actual result

1. In production mode the layer navigation block is not rendered at all
2. In production mode the following row is written in logs: 

==> var/log/system.log <==
[2020-08-27 10:19:01] main.CRITICAL: Notice: Trying to access array offset on value of type int in /var/www/html/releases/62/vendor/smile/elasticsuite/src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php on line 70 [] []

3. In developer mode, the execution is stoped with the following error trace
![image](https://user-images.githubusercontent.com/2530506/91442853-28b82680-e87b-11ea-8385-4941331b6e4a.png)

**Comment by leonhelmus** [comment]
I have the same issue. I solved it by adding this check for now
`
        foreach (array_merge(array_flip($sortingArr), $attributeOptions) as $item) {
           if(is_array($item)) {
            $attributeOptionsSort[$item['id']] = $item;
           }
        }
`

But i don't think this is the most clean solution.

**Comment by vahonc** [comment]
Hi @leonhelmus 
Thanks for your help, I'll check it out.

Best regards

**Comment by hmimthiaz** [comment]
Hi @leonhelmus 

I had the same issue and with your check it was working.

**Comment by justin-spotire** [comment]
> Hi @leonhelmus
> Thanks for your help, I'll check it out.
> 
> Best regards

Hi @vahonc , do you have any update for this bug, I'm facing this issue and hope that we will have update for it soon.

Thanks

**Comment by vahonc** [comment]
Hello @justin-spotire,

Unfortunately, so far I haven't been able to reproduce this test case. Seems previous versions of PHP may have been less strict on such mistakes and silently swallowed the error / notice while 7.4 does not do this anymore. But you can try the solution that was suggested by @leonhelmus and which I a little bit updated on my own, and give us your feedback if it helped you. 
<pre>
foreach (array_merge(array_flip($sortingArr), $attributeOptions) as $item) {
     if(isset($item) && is_array($item)) {
         $attributeOptionsSort[$item['id']] = $item;
     }
 }
</pre>
I will add the official MR a little bit later.

Best regards,

**Comment by leonhelmus** [comment]
@vahonc yes, it probably his something to do with strict typing. I have seen those issues a lot in 2.4.1.

**Comment by sedax90** [comment]
I've the same problem with Magento 2.4.1 and Php 7.4

**Comment by vahonc** [comment]
Hello @sedax90,

Have you tried the solution from my last comment?

Best regards,

**Comment by sedax90** [comment]
@vahonc your solution is working fine, I think we need a patch with this code

**Comment by Igloczek** [comment]
@rbayet do you have some estimate when this fix will be released? Is there something we may help you with?
