### ISSUE TITLE
Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed

### ISSUE THREAD

**Issue by mihaikalif** [Smile-SA/elasticsuite#1936]
### Preconditions

Magento Version : 2.3.5
ElasticSuite Version : 2.9.3
Environment : developer

### Steps to reproduce

0. Made all the installations, enable the modules for elasticsearch

1.  sudo /opt/bitnami/apps/magento/htdocs/bin/magento-cli setup:upgrade  
2.  sudo /opt/bitnami/apps/magento/htdocs/bin/magento-cli setup:di:compile   
3. sudo /opt/bitnami/apps/magento/htdocs/bin/magento-cli  setup:static-content:deploy -f  
4. sudo   /opt/bitnami/apps/magento/htdocs/bin/magento-cli cache:clean   
5.  sudo /opt/bitnami/apps/magento/htdocs/bin/magento-cli cache:flush   
6.  sudo /opt/bitnami/apps/magento/htdocs/bin/magento-cli indexer:reindex
Everything ended up with no errrors.

In the configuration I set up the ElasticSuite under Store> Catalog> Catalog Search
![Capture1](https://user-images.githubusercontent.com/61434922/91786804-19393480-ec11-11ea-88a0-100f017992ae.PNG)

### Expected result
1. to search for the products

### Actual result
![Capture](https://user-images.githubusercontent.com/61434922/91786784-09b9eb80-ec11-11ea-9db5-41740a10380e.PNG)

**Comment by mihaikalif** [comment]
After running the index:reindex I can see there is an error:
Catalog Search indexer process unknown error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbb42nvfc4bvkx.inventory_stock_1' doesn't exist, query was: SELECT `product`.`entity_id` AS `product_id`, `stock_index`.`is_salable` AS `stock_status`, `stock_index`.`quantity` AS `qty` FROM `catalog_product_entity` AS `product`
 INNER JOIN `inventory_stock_1` AS `stock_index` ON product.sku = stock_index.sku WHERE (product.entity_id IN (33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 55, 56, 57, 58, 59, 136, 184, 186, 190, 194, 199, 205, 211, 215, 217, 219, 223, 226, 233, 240, 243, 248, 254, 258, 264, 272, 280, 282, 284, 288, 292, 297, 300, 304, 308, 313, 315, 319, 324, 342, 343, 358, 360, 368, 369, 378, 381, 383, 385, 387, 393, 399, 404, 405, 412, 414, 416, 418, 420, 422, 428, 429, 438, 444, 446, 448, 450, 452, 453, 456, 458, 460, 462, 465, 467, 469, 471, 473, 475, 477, 479, 481, 483, 485, 487, 492, 498, 505, 510, 515, 520, 527, 529, 530, 531, 532, 533, 535, 536, 537, 538, 539, 540, 541, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 577, 578, 579, 584, 585, 587, 588, 589, 591, 592, 594, 595, 596, 597, 598, 599, 612)) GROUP BY `product`.`entity_id`

**Comment by mihaikalif** [comment]
I got the solution for this, you need to create a view table inventory_stock_1 for your catalog in database.

Here is the command you need to run in your DB SQL. Make sure to update 3 things in below query dbusername, localhost, dbname.

CREATE ALGORITHM=UNDEFINED DEFINER=`dbusername`@`localhost` SQL SECURITY INVOKER VIEW `inventory_stock_1`  AS  select distinct `legacy_stock_status`.`product_id` AS `product_id`,`legacy_stock_status`.`website_id` AS `website_id`,`legacy_stock_status`.`stock_id` AS `stock_id`,`legacy_stock_status`.`qty` AS `quantity`,`legacy_stock_status`.`stock_status` AS `is_salable`,`product`.`sku` AS `sku` from (`dbname`.`cataloginventory_stock_status` `legacy_stock_status` join `dbname`.`catalog_product_entity` `product` on((`legacy_stock_status`.`product_id` = `product`.`entity_id`)));

**Comment by mihaikalif** [comment]
Now the only thing is that when I'm searching for a product. I'm getting this image.
![Capture](https://user-images.githubusercontent.com/61434922/91833052-dbf39780-ec4e-11ea-9462-51c5c4827641.PNG)

**Comment by mihaikalif** [comment]
I found the sollution to be related to the customization of the theme that is breaking the way the elasticsearch is functioning. While changing the theme back to luma - elasticsearch suite is functioning properly.

**Comment by mihaikalif** [comment]
I'm not sure how the search form from the personalized theme is not working - I tried with another theme and the response is still similar with the one from the photo. Only the Luma theme brings the products in the list. Any advice is welcome.

**Comment by romainruaud** [comment]
That's a common issue with poorly written custom themes : https://github.com/Smile-SA/elasticsuite/wiki/FAQ#the-autocomplete-box-is-not-showing-up--does-only-display-search-terms

However, we cannot provide support for third-party software here, I close the issue.

Regards
