### ISSUE TITLE
"Fixed Product Taxe" is not used to display the price

### ISSUE THREAD

**Issue by spipu** [Smile-SA/elasticsuite#194]
On the auto complete, and search result, if a product has a "fixed product taxe" attribute, then the displayed price does not take it in account.

For example, if a product has a price of 100€ (included the 20% french taxes) + a DEEE of 5€, it displayed:

- Product Page: 105€ (with DEEE 5€)
- Search Result: 100€

thanks

**Comment by afoucret** [comment]
@romainruaud  : you should be able to use the wee into the product autcomplete data provider.

Don't forget to append the weee amount only if the prices are configured to display it

**Comment by romainruaud** [comment]
Fixed by the PR #207 

Will be part of upcoming 2.3 release.
