### ISSUE TITLE
How can I change the sort programmatically?

### ISSUE THREAD

**Issue by gihovani** [Smile-SA/elasticsuite#1941]
How can I change the sort programmatically?
**I have a customized page and I need the products to be sorted in the same order they were registered?**

**Additional context**
Files:
[di.xml]

`<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Magento\Catalog\Model\Layer">
        <plugin name="gg2_custom_layer_plugin" type="Gg2\Custom\Plugin\Model\Plugin\Model\Layer"/>
    </type>
</config>`

[Gg2\Custom\Plugin\Model\Plugin\Model\Layer.php]

`<?php

namespace Gg2\Custom\Plugin\Model;

use Magento\Framework\App\RequestInterface;
use HenryScheinBrazil\Chaordic\Helper\Data;

class Layer
{
    protected $request;
    protected $helper;

    public function __construct(RequestInterface $request, Data $helper)
    {
        $this->request = $request;
        $this->helper = $helper;
    }
    public function beforePrepareProductCollection(\Magento\Catalog\Model\Layer $subject, $collection)
    {
        if ($this->request->getFullActionName() === 'gg2_custom_page' &&
            $entityIds = $this->helper->getData('entityIds')) {
            $cond = new \Zend_Db_Expr('FIELD(e.entity_id,' . implode(',', $entityIds) . ')');
            $collection->getSelect()->columns(['ranking' => $cond]);
            $collection
                ->distinct(true)
                ->addFieldToFilter('entity_id', ['in' => $entityIds])
                ->setOrder('ranking', 'ASC');

            return [$collection];
        }
        return [$collection];
    }
}`

**Comment by romainruaud** [comment]
https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L204

``setOrder`` should be enouch **if and only if your "ranking" attribute is properly indexed in the engine and set as _sortable_** : if that's a product attribute, just set it to "Is used for Sort By : Yes", if that's not an attribute, you'll have to define a proper mapping for it : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#fields

Regards

**Comment by gihovani** [comment]
but this attribute I am creating dynamically: ""new \Zend_Db_Expr('FIELD(e.entity_id,' . implode(',', $entityIds) . ')')""
how can i do the ordering this way?

**Comment by gihovani** [comment]
> https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L204
> 
> `setOrder` should be enouch **if and only if your "ranking" attribute is properly indexed in the engine and set as _sortable_** : if that's a product attribute, just set it to "Is used for Sort By : Yes", if that's not an attribute, you'll have to define a proper mapping for it : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#fields
> 
> Regards


how can I do to maintain the order of skus in the same order that was passed as a parameter?

**Comment by romainruaud** [comment]
Answer to the initial question has been given.

I close the issue for being more than one year old.

Feel free to open a new one if you are still facing problems.

Regards
