### ISSUE TITLE
Attribute settings causes Elasticsearch to have an internal error an product listing is empty

### ISSUE THREAD

**Issue by pointia** [Smile-SA/elasticsuite#1942]
We had the problem, that if specific product settings are made, the elasticsearch query got an error and the product listing page was empty.

### Preconditions

If you set a type int attribute (Catalog INput Type for Store Owner: Dropdown)  and use the following settings the attribute is not filterable.
![image](https://user-images.githubusercontent.com/1998210/92718457-26b59380-f362-11ea-823a-ee86ce644ed9.png)

We've debugged the elasticsearch query and figured out that, for some reason the "field" in "aggregations" -> attribute -> "terms"  was empty for that attribute. We then had to set the config for "Use in Search" to "No" and reindex the catalog search again to make it work again.

Magento Version : 2.3.5-p2

ElasticSuite Version : 2.9.2 + 2.9.3

Environment : Developer + Production (both)

Third party modules : smile/module-elasticsuite-cms-search (2.2.7)

### Steps to reproduce

1. Create a new dropdown attribute
2. Set the settings as shown above
3. Reindex and navigate into a category where products are available with the attribute you've just created

### Expected result

1. Product listing should appear

### Actual result

1. No products are available

**Comment by romainruaud** [comment]
This one is most probably a cache issue, we can definitely have attributes used for search and filterable. 

@vahonc can you try to establish a reproduction scenario for this one ?

**Comment by dambrogia** [comment]
When changing the following metadata on product attributes, you _can_ invalidate your index. 

![image](https://user-images.githubusercontent.com/6516452/96801715-13fc9880-13bd-11eb-9b62-80ce0021d9a0.png)

My understanding is that these are the 6 pieces of metadata that will cause an attribute to be indexed for a product in elasticsearch. If an attribute is not indexable, then indexable (or visa-versa) I believe that is when you will face empty product listing pages.

 
I found that out through an existing and open issue issue: https://github.com/Smile-SA/elasticsuite/issues/1689

**Comment by pointia** [comment]
Hi, thanks for investigating. 
Since we changed that setting everything works fine and we didn't have the exception again.

**Comment by rbayet** [comment]
Hello @pointia,

Yes, I think the issue is that you encountered occured between saving your attribute and performing the full reindex, contrary to the "Steps to reproduce" you described (hence why @vahonc could not reproduce).

So, it's basically the problem described in #1689 (which seems active, so I'll have a look).

Regards,

**Comment by pointia** [comment]
@rbayet 
Ok, so I think we should close that issue here and continue in #1689.
Thanks for your support.
