### ISSUE TITLE
Wrong `getLastPageNum()` value from collection

### ISSUE THREAD

**Issue by Coosos** [Smile-SA/elasticsuite#1946]
`getLastPageNum` from `vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/amount.phtml` always contains 1 instead of page number.

### Preconditions

Magento Version : EE (I haven't tested on CE)

ElasticSuite Version : 2.9.3

Environment : Developer / Production

### Steps to reproduce
1. Fresh installation with sample data
2. Install ES and configure it
3. Go to category with multiple pages

### Expected result
1. At the top of the page we must have

![image](https://user-images.githubusercontent.com/5632327/93062158-d6e20f80-f674-11ea-9c25-5bb25f8c5cb3.png)

### Actual result

![image](https://user-images.githubusercontent.com/5632327/93062492-4821c280-f675-11ea-8e87-b8022656bff3.png)

**Comment by romainruaud** [comment]
How many items are displayed ? 12 or 50 ? 

I mean, is only the `getLastPageNum()` incorrect, or the whole listing mechanism that gets wrong ?

**Comment by Coosos** [comment]
> How many items are displayed ? 12 or 50 ?

12 per page (default configuration)
 
> I mean, is only the `getLastPageNum()` incorrect, or the whole listing mechanism that gets wrong ?

From what I've seen, it's only in this file (`vendor/magento/module-catalog/view/frontend/templates/product/list/toolbar/amount.phtml`) who contains wrong value. Because in this file (`vendor/magento/module-theme/view/frontend/templates/html/pager.phtml`), `$block->getLastPageNum()` contains good value (5)

According to my analysis, the problem comes from `$this->_pageSize` in `src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php`. 

The call to the collection launches the methods in this order : `_beforeLoad`, `_renderFiltersBefore` and `_afterLoad`
But, in  `_renderFiltersBefore`, `$this->originalPageSize` get value from `$this->_pageSize` which is worth false.

So in `\Magento\Framework\Data\Collection::getLastPageNumber`, `$collectionSize` we get 50 but `$this->_pageSize` contains false. Because of that, so it returns 1.

**Comment by romainruaud** [comment]
Okay so the pagination is working correctly, only the number of pages which is displayed is incorrect.

**Comment by Coosos** [comment]
The problem follows the following MR : https://github.com/Smile-SA/elasticsuite/pull/1862
Patch for pagination : https://github.com/Smile-SA/elasticsuite/pull/1914

**Comment by ajourquin** [comment]
Issue still there in 2.9.3. 
Pagination is working correctly, only the number of pages which is displayed is incorrect.

**Comment by Coosos** [comment]
> Issue still there in 2.9.3.
> Pagination is working correctly, only the number of pages which is displayed is incorrect.
> 
> Fix is to remove line 459 $this->originalPageSize = $this->_pageSize; in module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php

A fix is proposed with this MR : https://github.com/Smile-SA/elasticsuite/pull/1948
We tested it on a project and it fixed the problem 👍
