### ISSUE TITLE
Catalog search index taken much time with magento 2.4+ smile elasticsuite 2.10.0

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1947]
Hello,

Recently we have upgraded magento latest version 2.4.0 with smile elastic suite version 2.10.0.

We have elasticsearch version 7.6.1 and installed locally.

We have around 400k products, before upgrade magento + smile, we have same number of products and that time Catalog search index taken around 30 mins and now with same catalog + both (magento+smile) latest versions taken around 55 to 60 mins to complete the Catalog search index.

So according to latest smile or magento version, we have to do any change on elasticsearch server or is there any changes on backend configuration?

Can you please help!

Thanks,
David Andersson

**Comment by romainruaud** [comment]
Hello @davidandersson1 

Which version of Elasticsuite and Magento were you using before ? 

Are you using MSI now ? before ?

Regards

**Comment by davidandersson1** [comment]
HI @romainruaud,

Thanks for your response.

We were use Elastic suite version "~2.9.0"  and Magento version 2.3.5 and we are not using MSI before or now, actually MSI all modules disabled from started of M2 development. so we are not use MSI from last one year.

Also now we are facing pagination issue on catalog search listing page with magento latest version 2.4.0 with smile elastic suite version 2.10.0. but on category page pagination works fine. only issue at catalog search listing page.

Please let me know if you need any more assistance from my end.

Thanks,
David Andersson

**Comment by romainruaud** [comment]
Please check 2.10.1 version for pagination issues : https://github.com/Smile-SA/elasticsuite/releases/tag/2.10.1

Can you give me more details about MySQL version you use ?

**Comment by davidandersson1** [comment]
Hi @romainruaud,

Thanks for your view.

During weekend, I checked the issue in details and its due to one of customisation event like <event name="catalog_block_product_list_collection">

and with Observer file there is some additional code for catalog category pages and it was affected the pagination on catalog search result listing page. so I resolved it.

However we are using MySQL version 8.0

Thanks,
David

**Comment by davidandersson1** [comment]
@romainruaud  as i update you above pagination is resolved on catalog search result listing page but still search indexer are taking much time, almost double (compare to magento 2.3.5 + smile 2.9 + MySQL 5.7 + PHP 7.2) in magento 2.4 + smile 2.10 + MySQL 8.0 + PHP 7.4 and number of products are same in both magento version.

Really do not have any clue for it.

Someone please help..

Thanks in advance,
David

**Comment by romainruaud** [comment]
I'm curious about something, could you give a try to commenting this block : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/di.xml#L525:L529

It will probably require to clean the cache and compile again.

Maybe the async indexing is causing troubles in your instance.

Did you try lowering also the `batch_indexing_size` here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/config.xml#L33

I'm also curious to see how it does impact your indexing speed.

Regards

**Comment by davidandersson1** [comment]
Hi @romainruaud ,

I tried with suggested your both solutions, after commenting the block in di.xml + change batch as 500, I had run compile command + flush the cache.

and performed the catalog search index, still it's taken same time, around 52 mins which is quite much i guess,

I tried with another way like disabled the all Smile modules and performed the catalog search index and its was completed in only 12 mins. and I think its much good index time within 400k+ products.

**Comment by superdav42** [comment]
> Also now we are facing pagination issue on catalog search listing page with magento latest version 2.4.0 with smile elastic suite version 2.10.0. but on category page pagination works fine. only issue at catalog search listing page.

Are you still having pagination issues on the search results page? After upgrading to M 2.4 pagination seems to be completely disabled showing 1 - 612 of 612 on page one. So it's trying to display all the results on one page which would be slow and sometimes runs out of memory for queries which have many results. I tried updating to M 2.4.1 and elastic suite 2.10.x-dev and it is still happening.

**Comment by davidandersson1** [comment]
@superdav42 I resolved pagination issue on the search result listing page.

Actually it was due to one of custom extension with observer event "catalog_block_product_list_collection".

So I suggest you to disabled all third party and other custom extensions, run required magento core commands and then check same issue.

Hope it will help you.

Thanks,
David Andersson

**Comment by superdav42** [comment]
@davidandersson1 
Thanks, I did have a third part extension observing the `catalog_block_product_list_collection` event. I disabled that listener and it's working correctly now.

**Comment by romainruaud** [comment]
I close, this issue is too old.
