### ISSUE TITLE
Categories page in admin doesn't loaded (spinner all the time).

### ISSUE THREAD

**Issue by Zayander** [Smile-SA/elasticsuite#1949]
### Preconditions

Magento Version : 2.4.0

ElasticSuite Version : 2.10.0

Environment : Production

Third party modules :

### Steps to reproduce

1. Go to the Dash->Catalog->Categories
2.
3.

### Expected result

1. Create a new category

### Actual result

1. Page doesn't loaded 
![image](https://user-images.githubusercontent.com/25375571/93372942-4b77a280-f85d-11ea-8993-e9335241535d.png)
An error in the browser console

```
product-sorter.js:206 Uncaught TypeError: Cannot read property 'map' of undefined
    at UiClass.onProductListLoad (product-sorter.js:206)
    at fire (jquery.js:3238)
    at Object.fireWith [as resolveWith] (jquery.js:3368)
    at done (jquery.js:9846)
    at XMLHttpRequest.callback (jquery.js:10317)
```

If module Smile_ElasticsuiteVirtualCategory disabled an error disappear and I can create a new category.

**Comment by vahonc** [comment]
Hi @Zayander 

As I already mentioned in #1950 I can't reproduce your test case. Please check your configuration of the ElasticSuite module according to the steps described in our Wiki or provide us more details about the configuration of your store.

Best regards

**Comment by webcreative24** [comment]
@romainruaud Hello. Same here. After editing manual sort orders and save category getting same error. how to debug it?

**Comment by vahonc** [comment]
Hello @webcreative24,

First of all, provide details about the configuration of your environment. The initial issue is too old, so I don't think that you use such old components.

Have you checked Magento logs and Console tab of your browser?

p.s. I suggest you create a new issue and give all details that could help us to understand your problem or how we can try to reproduce this.

BR,
Vadym
