### ISSUE TITLE
Smile\ElasticsuiteCore\Search\Request\Query\Filtered given type error  when a new category created.

### ISSUE THREAD

**Issue by Zayander** [Smile-SA/elasticsuite#1950]
### Preconditions

Magento Version :2.4.0

ElasticSuite Version :2.10.0

Environment : production

Third party modules :

### Steps to reproduce

1. Go to the Dash->Catalog->Categories
2. Create a new category and assign a product to this category.
3. Go to the category created

### Expected result

1. Expect to see category with assigned products

### Actual result

1. 
![image](https://user-images.githubusercontent.com/25375571/93380843-774c5580-f868-11ea-87ff-43eadda314d5.png)

An Error Argument 1 passed to Magento\Elasticsearch\Elasticsearch5\SearchAdapter\Mapper::processFilterQuery() must be an instance of Magento\Framework\Search\Request\Query\Filter, instance of Smile\ElasticsuiteCore\Search\Request\Query\Filtered given, called in /var/www/src/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Mapper.php on line 114
Exception in /var/www/src/vendor/magento/module-elasticsearch/Elasticsearch5/SearchAdapter/Mapper.php:185

**Comment by vahonc** [comment]
Hello @Zayander 

For your test case I've been used:
- Magento 2.4.0
- ElasticSuite 2.10.0
- Elasticsearch 6.8.11

Unfortunately, I can't reproduce your problem. I was able to create a new test category without any issues, assign some products to it, and browse category bio in Magento BO and FO.

![m24-test-cat](https://user-images.githubusercontent.com/67791361/93470621-dd81b880-f8fa-11ea-9d22-6db56fe85a00.png)

Could you please clarify more details, for example, which version of Elasticsearch you are using, have you use some specific configuration of your store, etc? 

Also please check your configuration of the ElasticSuite module according to the steps described in our Wiki. Maybe I should try to re-install the ElasticSuite module, clear the Magento cache, run setup-upgrade, and run re-index.

Best regards

**Comment by romainruaud** [comment]
@Zayander if you go through `\Magento\Elasticsearch\Elasticsearch5\SearchAdapter` it's highly likely that you **don't** have Elasticsuite being set as your default Search engine.

Please check it on ``Stores > Configuration > Catalog > Search`` that the search engine is set to Elasticsuite.

Regards
