### ISSUE TITLE
Globally using display modes

### ISSUE THREAD

**Issue by Varulv1997** [Smile-SA/elasticsuite#1953]
Hello there ! I was wondering if there is a way to set attributes' display modes for example to always displayed, but globally, instead of setting it for countless categories.

**Comment by patricksteenks** [comment]
I'm interested in this as well. I have been working on a script to set this per category to "always displayed" but have not succeeded yet.

**Comment by Varulv1997** [comment]
The attributes actually will display if there are any products having them, I gave up on the idea of doing it from the backend and simply added the attributes manually in the frontview.

**Comment by patricksteenks** [comment]
Ok, cool. I have written a cli command which sets the attributes to always display and now it is working. :)
