### ISSUE TITLE
Issue after Magento 2.3.5 to 2.4 upgrade

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#1956]
Hello after upgrade Magento to 2.4, i can see this error on logs:
Validation Failed: 1: id is too long, must be no longer than 512 bytes but was:
Stack trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(317): Elasticsearch\Connections\Co in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 632
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 907;2: id is too long, must be no longer than 512 bytes but was: 782;3: id is too long, must be no longer than 512 bytes but was: 782;4: id is too long, must be no longer than 512 bytes but was: 907;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 907;2: id is too long, must be no longer than 512 bytes but was: 782;3: id is too long, must be no longer than 512 bytes but was: 782;4: id is too long, must be no longer than 512 bytes but was: 907;"},"status":400} in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632

### Preconditions

cron:run

Magento Version :

Magento CE 2.4

ElasticSuite Version :

2.10 last

Environment :

Production

Third party modules :

### Steps to reproduce

1. bin/magento cron:run
2.
3.

### Expected result

1. no error

### Actual result

1. Error:

Stack trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(317): Elasticsearch\Connections\Co in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 632
PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 907;2: id is too long, must be no longer than 512 bytes but was: 782;3: id is too long, must be no longer than 512 bytes but was: 782;4: id is too long, must be no longer than 512 bytes but was: 907;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id is too long, must be no longer than 512 bytes but was: 907;2: id is too long, must be no longer than 512 bytes but was: 782;3: id is too long, must be no longer than 512 bytes but was: 782;4: id is too long, must be no longer than 512 bytes but was: 907;"},"status":400} in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:632

**Comment by romainruaud** [comment]
Can you give us more details, especially what you could find on : 

- the magento /var/log/exception.log
- the magento /var/log/debug.log
- the magento /var/log/system.log
- the elasticsearch log files : /var/log/elasticsearch/elasticsearch.log

Also can you provide us an example of product ids being problematic ?

Regards
