### ISSUE TITLE
Module and layered navigation

### ISSUE THREAD

**Issue by ioannisgz** [Smile-SA/elasticsuite#1957]
Hi. Although I read your wiki page I can't understand if this module loads magento layered navigation though Elasticsearch.
I am talking about magento 2.4 CE and Commerce Edition
Could you please specify?
Thanks

**Comment by romainruaud** [comment]
Yes, layered navigation, search results, and autocomplete box, everything is pulled through Elasticsearch.

Which additional details do you want ?

**Comment by ioannisgz** [comment]
Thank you for your answer... So to install your and test this module all 3rd party modules affected layered and search must be removed , right?

**Comment by romainruaud** [comment]
Correct, it's likely this kind of modules will not behave properly.

Regards
