### ISSUE TITLE
Duplicate Optimizer: Error: Call to a member function format() on bool 

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#1959]
### Preconditions

Magento Version : 2.4.0CE on PHP7.4

ElasticSuite Version : 2.10.1

Environment : Developer

Third party modules : na

### Steps to reproduce

1. Create an Optimizer 
2. Go back to Optimizer grid page 
3. Select "duplicate" for the Optimizer created in Step 1.

### Expected result

1. Should duplicate the optimizer

### Actual result
Error: Call to a member function format() on bool in /vendor/smile/elasticsuite/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Copier.php

**Comment by vahonc** [comment]
Hello @refueledinc,

For your test case I used:
- Magento 2.4.0 EE
- PHP 7.4.8
- ElasticSuite 2.10.1

Unfortunately, I was not able to reproduce your bug, I have successfully duplicate an optimizers item that was created before without any errors.

![magento-optimizers-list](https://user-images.githubusercontent.com/67791361/95091137-be728b80-072e-11eb-9baf-d139d90955f1.png)

Maybe in your case, you use some specific rules for optimizers. Please provide more details about the item which you want to duplicate (details, conditions, screenshots, etc)

Best regards

**Comment by refueledinc** [comment]
@vahonc It looks like it's related to the active to/from date. Since these are not required. I did not set a value. Duplicate fails when there is no value set for them. If I set them, then duplicate, it works.
