### ISSUE TITLE
Impossible to redefine field type for dynamic fields via elasticsuite_indices.xml

### ISSUE THREAD

**Issue by killoff** [Smile-SA/elasticsuite#1962]
**Is your feature request related to a problem? Please describe.**
Generally speaking, client is unable to get full control over fields mapping using just `elasticsuite_indices.xml`. 
This refers to eav attributes of product/category.
For example, '`name`' attribute for category.
The mapping for this field would be always` type="text", analyzer="standard"`
Based on this line https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L134
Even if the client try to change this behaviour by adding, this will not have any effect.
```
    <index identifier="catalog_category">
        <type name="category" idFieldName="entity_id">
            <mapping>
                <field name="name" type="keyword" />
            </mapping>
        </type>
    </index>

```
As the result, varchar attributes in magento do not have an unanalyzed `keyword` field in elasticsearch.
Which makes it impossible to use these fields in aggregations, sorting, or in scripts.

**Describe the solution you'd like**
I would like to have full control of attributes mapping via  `elasticsuite_indices.xml`.
No matter how attributes defined in Magento or which type they have, I would like to have a possibility to 'rewrite' the mapping. 
 
**Describe alternatives you've considered**
An alternative would be: initField() method of `\Smile\ElasticsuiteCatalog\Model\Eav\Indexer\Fulltext\Datasource\AbstractAttributeData` 
 should take into account what is defined in `elasticsuite_indices.xml`.
And if no mapping defined in xml file - behave in default mode, as it's currently doing.

**Additional context**
Smile Elasticsuite is an awesome package, which can be used not only in classic mode.
It has much wider possibilities.
We actually use only backend part of it for sending products/categories to elastic cloud.
Following by the custom frontend implementation.
Thus we need to control the mapping in elasticsearch indicies for our frontend needs

**Comment by romainruaud** [comment]
Well according to this, the XML file should overwrite anything calculated dynamically by the Datasources : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Index/Indices/Config.php#L173

```
            if (isset($fields[$fieldName])) {
                // Field also exists with dynamic providers.
                // We merge the dynamic config and the config coming from configuration file.
                // XML file has precedence.
                $field = $fields[$fieldName]->mergeConfig($fieldConfig['fieldConfig'] ?? []);
            }
```

Or at least, it should have been the case, because I had exactly your need in mind when I wrote this piece of code :) 

It appears that it's not the case according to you, or I'm misunderstanding it.

I got no time to test this actually, but I'll ask @vahonc to have a look at it.

Please provide additional insights if you have some.

Regards

**Comment by romainruaud** [comment]
Okay, after some vacations I realize that I missed the fact that you want to override the *type* of the field, not the rest of the field configuration.

Maybe the piece of code I shown does not merge correctly the "type" and the "analyzer" property of the xml node.

**Comment by romainruaud** [comment]
@killoff can you check if the proposed solution in #2046 is achieving what you need ?

Regards

**Comment by romainruaud** [comment]
@killoff any update ?

**Comment by killoff** [comment]
@romainruaud thanks for the simple solution. It does the thing.
We can close the ticket.

**Comment by romainruaud** [comment]
Great, I merge it and I close.

Thank you
