### ISSUE TITLE
v2.6 Clean Tracking data

### ISSUE THREAD

**Issue by ychadwick** [Smile-SA/elasticsuite#1966]
I cannot figure how to clean the tracking data, the version we are using is 2.6.9  as we have a magento 2.2 version. Unlike later versions, there is no cronjob to clean up the tracking data, and our elastic search indexes were growing alarmingly.

**Comment by romainruaud** [comment]
curl -X DELETE "localhost:9200/my_indice_name?pretty"

You can use patterns like "my_alias_tracking_*".

See https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-delete-index.html

**Comment by ychadwick** [comment]
Thanks for the tip. In the end I made a cron job, similar to that of the later version, and implement it to regularly clean the indexes.
