### ISSUE TITLE
Elastic Cluster from elastic.co

### ISSUE THREAD

**Issue by ubedarab** [Smile-SA/elasticsuite#1968]
One of my project we are using your module,
but we are not want to use elastic.co cluster.

and its good working and connected with curl command and Magento default test connection.
its perfectly working just have problem with your module, 
https://exmapleurl.elastic-cloud.com:9243

so can you please check and update your module to allow this kind of cluster url end point to work with your module so it will be good to continue with your module.

can you check and respond please,

**Comment by rbayet** [comment]
Hello @ubedarab,

I've just managed to connect Magento2 + Elasticsuite to a Elastic Cloud instance while answering #1971 .
And people have managed to do it in the past (see #1482).

Please refer to those issues and/or describe more accurately your issue if correctly configuring Elasticsuite with your Elastic Cloud cluster HTTP authentication credentials does not solve your problem.

Regards,
