### ISSUE TITLE
Third party sorting module

### ISSUE THREAD

**Issue by JoostWan** [Smile-SA/elasticsuite#1970]
Is there any third party sorting module that's working with ElasticSuite for more sorting options? Like best seller etc.

**Comment by vahonc** [comment]
Hello @JoostWan,

As far as I know, we do not use any third-party modules for sorting, only those modules that are included in the ElasticSuite. Using third-party modules is at your own risk and we do not guarantee the correct work of our module or other third-party modules.

You can get more information here:
- https://github.com/Smile-SA/elasticsuite
- https://github.com/Smile-SA/elasticsuite/wiki

Best regards

**Comment by refueledinc** [comment]
@JoostWan - RedChamps is working on a premium module for Bestseller and Newest. We are beta testing it for them. It should be available to everyone soon.

**Comment by refueledinc** [comment]
@JoostWan - RedChamps has released the module here https://redchamps.com/extra-sorting-options-magento-2-extension.html

Please consider showing them some support. They've been very helpful to us. They are very open to feedback and suggestions you may have.

**Comment by JoostWan** [comment]
@refueledinc Thanks, the module is working here!

**Comment by romainruaud** [comment]
Good to see that extensions providers are considering implementing out-of-the-box compatibility with Elasticsuite :)

I close the issue then.

Regards
