### ISSUE TITLE
How to make the subcategory products not visible in main category?

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#1972]
Hello,

We are using magento version 2.3.5 with smile elastic suite version ~2.9.0,

One thing noticed, after installed Smile modules, Category edit level default magento field "Is Anchor" is no longer visible, so if we do not want to display sub category products in main category then how we should achieve it?

Can you please provide information for the same.

Thanks in advance,
David Andersson

**Comment by achatpc** [comment]
I have the same question.

Thank you in advance.

**Comment by romainruaud** [comment]
Hello, you cannot, we do enforce the "is anchor" by design.

The only way to achieve it would be to manually blacklist the children products in the parent category, which could be, if you have plenty of them, not easily doable manually.

Regards
