### ISSUE TITLE
2.4.1 adds the contextinterface argument

### ISSUE THREAD

**Issue by davidtisn** [Smile-SA/elasticsuite#1973]
https://github.com/Smile-SA/elasticsuite/blob/30fc0c43087d093ce5298beaf15e296cb22ce001/src/module-elasticsuite-catalog-graph-ql/Model/Resolver/Products/Query/Search.php#L85

**Comment by Quazz** [comment]
Duplicate of https://github.com/Smile-SA/elasticsuite/issues/1961
