### ISSUE TITLE
Rest Api Categories / Categories Merchandising - Bug?

### ISSUE THREAD

**Issue by ViniciusNaoDivulgue** [Smile-SA/elasticsuite#1977]
Hello friends,

We believe we have found a Bug.
I will describe the scenario, see if you can direct us.

We have a Magento v2.4 running with ElasticSuite.

We do all product registrations via Rest API.
From this moment on we would like to order the position of the products in the category also by API.
This is where the possible bug happens, position changes are made via API, they are saved but have no effect.

### Preconditions

- Magento v2.4 - CE
- ElasticSuite Last Version
- Nginx
- PHP 7.4

### Steps to reproduce

REST API / Categories

[PUT] rest / default / V1 / categories / {category_id} / products

{
     "productLink": {
         "sku": "123456",
         "position": 3, <- Here I define the position
         "category_id": "99",
         "extension_attributes": {}
         }
}

Is there any configuration to disable Categories Merchandising / Drag and Drop?
With this action we want to order the position of our products via API, as without the module installed. (Expected result)
We believe that it does not consider the position field updated by the API.
All others funcionabilitys are very appreciate =]

### Actual result

Just updating position on backend:
Catalog >> Categories >> Products on Category >> Products List Preview and Sorting

Today:
![1](https://user-images.githubusercontent.com/47072232/97623066-e7233380-1a03-11eb-943f-8933c73201ba.png)

Without this feature works by API:
![2](https://user-images.githubusercontent.com/47072232/97623198-133eb480-1a04-11eb-896d-10f81ea4042a.png)

Really Thanks Team!
Here we appreciate your job =]

**Comment by rbayet** [comment]
Hello @ViniciusNaoDivulgue,

Alas, this is not a bug, it's a feature ;)

Elasticsuite does not take into account the native product positions in categories stored in `catalog_category_product` but those in the dedicated table `smile_virtualcategory_catalog_category_product_position` where the "blacklisting" is also stored.
It is explained fully [on this comment](https://github.com/Smile-SA/elasticsuite/issues/1579#issuecomment-545964118).

As explained [in another issue](https://github.com/Smile-SA/elasticsuite/issues/1734#issuecomment-595069519), you could  : 
- either decide to disable the **smile/module-elasticsuite-virtual-category** module : problem solved (but not more virtual categories)
- or decide to re-define the `categories` datasource to have a model pull records from the native table(s)
- or overwrite the REST API entrypoint to write directly to `smile_virtualcategory_catalog_category_product_position` 

Regards,

**Comment by romainruaud** [comment]
We should implement the third solution into the virtual-category module, but to be honest, that's a low-priority for us actually.

I add it into next features roadmap anyway.

**Comment by romainruaud** [comment]
@vahonc can you try to override the legacy Magento API so that when someone is contributing a position, it goes to the proper table ?

As explained it should go into `smile_virtualcategory_catalog_category_product_position` and not into `catalog_category_product`
