### ISSUE TITLE
Virtual Category module suddenly throwing errors

### ISSUE THREAD

**Issue by Quazz** [Smile-SA/elasticsuite#1985]
After updating some packages (not elasticsuite itself) with composer (none of them related to layered navigation), Virtual Category module throws an error: 

For frontend:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class '{"type":"Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1","is_value_processed":null,"aggregator":"all"}' not found in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67`

And for backend:

`main.CRITICAL: Error: Call to a member function getCategorySearchQuery() on string in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php:116`

And for virtual categories on backend:

`main.CRITICAL: Error: Call to a member function loadPost() on string in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/Preview.php:144`

The odd thing is; it was working perfectly fine before. I had this error about two weeks ago, but then after a while of trying to figure it out and debugging, I turned the module back on and it worked normally again. 

Looking through the history of issues; this seems to appear every once in a while, but no real conclusive answer.

### Preconditions

Magento Version : 2.4.0

ElasticSuite Version : 2.10.1

Environment : Production

Third party modules : Loads, none of them impact layered navigation, however (fully handled by elasticsuite)

### Steps to reproduce

No clue how to reproduce, given that it happened out of the blue. 
I do use optimizers on every category which is why I guess all categories go 500 

### Expected result

Category pages load normally

### Actual result

Category page returns error 500 and logs the critical error in system.log

**Comment by Quazz** [comment]
Is there a way to determine what the cause is? 

It seems like ->getVirtualRule() is returning a string when an object is expected.

**Comment by Quazz** [comment]
After commenting out line 116 in Preview.php

I am now manually saving categories that don't have is_virtual attribute, found by query:

`SELECT entity_id FROM catalog_category_entity WHERE NOT EXISTS (SELECT * FROM catalog_category_entity_int WHERE catalog_category_entity_int.entity_id = catalog_category_entity.entity_id AND attribute_id = 343) ORDER BY `catalog_category_entity`.`entity_id` DESC`
(343 being is_virtual attribute_id in my case)

This seems to save the info for those categories. I hope that this resolves it; it's over 100 categories so may take some time.

**Comment by Quazz** [comment]
Manually adding a check to verify if the virtualrule is an object and if not to exectute the ReadHandler seems to resolve it for me. 

`            if (!is_object($virtualRule)) {
                $this->virtualRuleReadHandler->execute($category);
                $virtualRule = $category->getVirtualRule();
            }
`

That said, it seems like this shouldn't be necessary and makes me wonder why it doesn't work out of the box (anymore)

**Comment by romainruaud** [comment]
You are right, the "check if object and call the read handler if it's not" should not be needed since the read handler is _supposed_ to be called every time we load a category.

That's not the first time I see this kind of issue by the way, despite I've never been able to reproduce it by myself.

I think this is really due to the fact that some categories do not have any value for virtual_rule (that's step *1*) and then, for unknown reasons, we don't go through the read handler when loading them (that's step *2*), and we run into failure.

I'm wondering what could cause the read handler not being called when loading a category. However, there's not much I can do myself here, since I'm not able to reproduce it. Maybe your scenario is detailed enough to be reproduced, we'll try to have a look but since this one seems to be very specific to _something unknow_, it's not high priority for now : we never faced it on a Luma/Venia even if the sample data in this case does not have particular `virtual_rule` contributed for all categories.

Regards

**Comment by Quazz** [comment]
Yes, the weird thing is that it was working fine before and then suddenly it wasn't anymore.

I see that the readhandler is supposed to be applied in the ResourceModel. 

@romainruaud 

Preliminary testing, suggests that adding the preference for the ResourceModel into the di.xml might resolve this. 

`<preference for="Magento\Catalog\Model\ResourceModel\Category\Collection" type="Smile\ElasticsuiteVirtualCategory\Model\ResourceModel\VirtualCategory\Collection" />`

**Comment by Quazz** [comment]
Still can't wrap my head around it.

In the ResourceModel/VirtualCategory/Collection the getVirtualRule() definitely returns an object, but then when you navigate to one of the pages it is suddenly just a string?

**Comment by romainruaud** [comment]
Yes unfortunately I came to the same conclusion but never reproduced it.

Maybe something related to caching, or to Varnish fragments for the layered navigation in some edge cases ?

**Comment by Quazz** [comment]
Unfortunately, we don't use Varnish. We use redis for all our caching (seperate instance for session and cache)

And it also happens in the backend on category management page.

**Comment by Quazz** [comment]
Small update: I test if it works primarily on the backend so the frontend is undisturbed.

By modifying Preview.php I can make it load normally. What I noticed today was that Virtual Categories still load fine regardless, but normal ones do not. Interesting data point to say the least.

**Comment by Quazz** [comment]
One thing I have noticed is that the store_id for the rule in the resourcemodel is 0 (of course), but when loading a category in "All store views" it ends up adopting the default storeview for the current category root instead of the admin storeview. 

I can't compare with a working version myself, unfortunately.

**Comment by misthero** [comment]
I have the same issue with es 2.9.6 and magento 2.3.6

**Comment by davidandersson1** [comment]
exact same issue for us with magento version 2.3.5 and elasticsuite version ~2.9.0.

lots of times, same error generated in log/exception.log file.

Is there any solution for this bug?

**Comment by Quazz** [comment]
Soooo, still not sure what the cause is, but after installing https://github.com/creatuity/magento2-interceptors module, I no longer experience this issue. 

Perhaps a bug in Magento core regarding interceptor generation in certain edge cases?

**Comment by Quazz** [comment]
I have since disabled the interceptor module, upgraded to 2.4.2 and Elasticsuite to 2.10.3 and it works without issue again.

**Comment by jtomaszewski** [comment]
We don't use interceptors module. This bug started appearing to us today, after we've upgraded magento from 2.4.1 to 2.4.2 and also a lot of other modules. (So hard to tell, whether it was the magento update, or which module exactly...)

**Comment by refueledinc** [comment]
Has anyone managed to get to the bottom of this?

We've been seeing this error in our logs for months now.

We're on M2.4.2CE and ES2.10.3

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class
'{"type":"Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1",
"is_value_processed":null,"aggregator":"all"}' not found in 
vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67
```

From what we can tell, we're not having any issue from a user perspective, but the error is added to our logs throughout the day.

**Comment by melquchiri-tbd** [comment]
I'm getting the same error here

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class
'{"type":"Smile\\ElasticsuiteVirtualCategory\\Model\\Rule\\Condition\\Combine","attribute":null,"operator":null,"value":"1",
"is_value_processed":null,"aggregator":"all"}' not found in 
vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67
```

**Comment by ankurkinex** [comment]
I am also getting similar issue on Magento 2.4.5 P2

report.CRITICAL: TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, first array member is not a valid class name or object in vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php:76

What is the fix?

**Comment by romainruaud** [comment]
https://github.com/Smile-SA/elasticsuite/pull/2931 this PR should fix this.

Imho your solution @blanioo was not enough, because there are also some strange cases where the virtualRule is here, but not empty, just the "text based" value and not the object.

So I added an authoritative call to the read handler in such cases.

I'm still not able to reproduce this however, it's probably very dependant on other modules in the call stack.

Regards
