### ISSUE TITLE
No results found when visiting the last page and changing 'show how many'

### ISSUE THREAD

**Issue by WebWeave** [Smile-SA/elasticsuite#1986]
### Preconditions

Clean install with Elasticsearch 6.8.11

Magento Version : 2.3.5-p1

ElasticSuite Version : 2.9.3

Environment : Production

Third party modules : Nope, basically clean install.

### Steps to reproduce

1. Open Magento advanced search and search for products that match a product attribute
2. Go to the last page of results
3. Click back any page
4. Up the "how many results" from 10 to 25 for example

### Expected result

1. See the results of the search

### Actual result

![image](https://user-images.githubusercontent.com/17380630/98349132-e9941780-2019-11eb-8669-3624738dd13d.png)

**Comment by rbayet** [comment]
Can't reproduce on 2.4.1 / 2.10.2.
Can reproduce on a 2.3.5-p2 / 2.9.3 both on advanced search, fulltext search and catalog navigation.
I have the feeling it's a native bug in the toolbar (not resetting the p/page parameter on switching page size), to confirm with a native Magento without Elasticsuite.

**Comment by rbayet** [comment]
> 
> Possible link with/duplicate of #1946

Nope, it's more probably a duplicate/similar issue as for #1693

**Comment by rbayet** [comment]
Fixed by #1993
