### ISSUE TITLE
Smile_ElasticsuiteAnalytics depends on Smile_ElasticsuiteCore but it's not declared on module.xml

### ISSUE THREAD

**Issue by ericmorand** [Smile-SA/elasticsuite#1988]
Smile_ElasticsuiteAnalytics depends on Smile_ElasticsuiteCore at least for its admin menu:

```xml
<?xml version="1.0"?>
<!--
/**
 * ElasticSuite Analytics menu configuration
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteAnalytics
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2020 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Backend:etc/menu.xsd">
    <menu>
        <add id="Smile_ElasticsuiteAnalytics::analytics"
             title="Analytics"
             translate="title"
             module="Smile_ElasticsuiteAnalytics"
             sortOrder="30"
             parent="Smile_ElasticsuiteCore::elasticsuite_menu"
             resource="Smile_ElasticsuiteAnalytics::analytics"
         />
        <add id="Smile_ElasticsuiteAnalytics::search_usage"
             title="Search Usage"
             module="Smile_ElasticsuiteCatalogOptimizer"
             sortOrder="30"
             parent="Smile_ElasticsuiteAnalytics::analytics"
             action="smile_elasticsuite_analytics/search/usage"
             resource="Smile_ElasticsuiteAnalytics::search_usage"
         />
    </menu>
</config>
```

But it's not declared as such im module.xml:

```xml
<?xml version="1.0"?>
<!--
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteAnalytics
 * @author    Aurelien FOUCRET <aurelien.foucret@smile.fr>
 * @copyright 2020 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Smile_ElasticsuiteAnalytics" setup_version="0.0.1">
        <sequence>
            <module name="Smile_ElasticsuiteCatalog" />
            <module name="Smile_ElasticsuiteTracker" />
        </sequence>
    </module>
</config>
```

It is then possible to remove the core module while keeping the analytics module, whoch lead to a crash of the admin area:

`Exception #0 (OutOfRangeException): Specified invalid parent id (Smile_ElasticsuiteCore::elasticsuite_menu)`

**Comment by romainruaud** [comment]
`sequence` is definitely **not** something to define hard dependencies between modules, but rather a loading _sequence_, as you can see here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/module.xml#L26

We do have a `sequence` on a Magento Commerce module, but everything is going fine when this module is not here.

So, considering this fact, and the very "uncommon" scenario to reproduce your issue (remove the _core_ module of Elasticsuite, which would of course lead to many other failures), it's unlikely we'll do something for this.

If you feel the need to add the sequence to Smile_ElasticsuiteCore, you can submit a PR and we'll probably merge it but I doubt it's enough to fix your specific scenario. Please bear in mind that adding Smile_ElasticsuiteCatalog and Smile_ElasticsuiteTracker to the sequence should be enough : they do have a sequence on Smile_ElasticsuiteCore themselves.

Regards

**Comment by ericmorand** [comment]
Well, something is wrong anyway. You are right that hard dependencies are not declared in module.xml. But they should be declared in the composer manifest, as per Magento documentation:

https://devdocs.magento.com/guides/v2.4/architecture/archi_perspectives/components/modules/mod_depend.html#hard-dependencies

This dependency being declared nowhere, it is possible to remove the Core module and have the site crash because some other modules (Analytics for example) depend on it.

> remove the core module of Elasticsuite, which would of course lead to many other failures

That's the point. Disabling the core module should _not_ lead to failures. It should not be possible until all dependent modules have been disabled. Try for example to disable Magento_CatalogStaging to see what I'm talking about.
