### ISSUE TITLE
issue with module installation with Magento 2.4 enterprise

### ISSUE THREAD

**Issue by magentoguyspk** [Smile-SA/elasticsuite#1989]
Hello,
we have magento 2.4 site http://172.105.21.242/alias/athens-global-services-sa-aliss/mesa-de-comedo.html
I have tried to install the module by composer , but whenever I try 
after sometimes commmads get killed by itselft  check this https://prnt.sc/vdr5rt
I have also increased server configuration (like increasing RAM) 
but still commnad not sucessfully installed

can you please check and brif me ,how can we sortout this and install the elasticsuite

Many Thanks

**Comment by rbayet** [comment]
Hello @magentoguyspk,

Could you give us more details about your installation ?
Is it a Magento 2.4.0 or 2.4.1 ?
What is the distribution and version of your linux instance/server ?

Have you tried using composer as a non-root user as suggested by the composer warnings ?

Regards,

**Comment by MagentoGuysProjects** [comment]
Hello @rbayet ,

I have added Magento admin details below. Let me know if you need any other details. 
It is Magento 2.4.0 Enterprise edition.
Distribution and version of server : Ubuntu 20.04 LTS
I have tried installing it from the root user. 

**admin URL**
http://172.105.21.242/alias/athens-global-services-sa-aliss/admin/
username : magento
password : Magento@123

**Comment by kipangadevteam** [comment]
Hello @rbayet ,

Can you please share an update.
