### ISSUE TITLE
Sort By Newest

### ISSUE THREAD

**Issue by drinkingsouls** [Smile-SA/elasticsuite#1990]
A question more than an issue here.
Is there any Magento sorting by newest for product grid when using Smile Elasticsuite? As soon as I enable the module and Elasticsearch I can no longer order products by most recent in the grid.
Is there any sort by modules that work with Elasticsearch and Elastucsuite.
Thank you.

**Comment by vleshchyshyn** [comment]
I have a same question: when using Elastucsuite I can no longer sort by newest product. Is there a way to have this working or is there any third-party extension to add this functionality?

**Comment by drinkingsouls** [comment]
I didn't get any further with it. I believe the RedChamps Extra Sorting Options plugin was the only working extension but I have not tried it myself.
https://redchamps.com/extra-sorting-options-magento-2-extension.html

**Comment by drinkingsouls** [comment]
This module is free and seems to work:

https://github.com/amareshtiwari/Advance_Sorting_Magento2

**Comment by romainruaud** [comment]
@drinkingsouls what do you mean by "in the grid" ?

Are you speaking about the product listing page ?

Regards

**Comment by drinkingsouls** [comment]
Yes, the catalogue pages where products are listed. As soon as ElasticSearch is enabled (which is now default) the sort by newest does not order correctly.

This extension partially works but sorts the opposite way, with oldest at the top:
https://github.com/amareshtiwari/Advance_Sorting_Magento2

**Comment by romainruaud** [comment]
Did you give a try to just set the "created_at" attribute as sortable ? This should be enough to sort on creation date.

**Comment by drinkingsouls** [comment]
I did, it made no difference. The only solution I found was the RedChamps Extra Sorting options plugin that worked for this. Though it's other sorting options are very limited.

**Comment by romainruaud** [comment]
Okay, I close this one since you found a workaround.

Regards

**Comment by drinkingsouls** [comment]
It was far from an ideal solution as it is a paid extension. However this is not an issue with this module, sort by newest doesn't work on Magento when using ElasticSearch (which is now the only option). A Magento fix or solution is needed for this long term.
