### ISSUE TITLE
Invalid method  Invalid method Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category::isActive

### ISSUE THREAD

**Issue by sanganagouda1** [Smile-SA/elasticsuite#1998]
### Preconditions

Magento 2.3.5
Windows 10
mysql

Magento Version : CE 2.3.5

ElasticSuite Version : 2.9.0

Environment : Developer

Third party modules : 

### Steps to reproduce

1. Installed the elastic server on windows  refered this document (https://www.elastic.co/guide/en/elasticsearch/reference/current/zip-windows.html)
2. Installed smile elasticsuite module in  magento local (xampp) -composer require smile/elasticsuite ~2.9.0
3. Configured smile elastic suite and elastic server in magento2.3.5

### Expected result

1. Catalog should load as expected

### Actual result

1. [Screenshot, logs]
 Invalid method Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category::isActive
![image](https://user-images.githubusercontent.com/11024606/99510499-2a424800-29ad-11eb-9f58-b62b8f084dc0.png)
![Screenshot (64)](https://user-images.githubusercontent.com/11024606/99510553-3928fa80-29ad-11eb-8647-598f9fbacb7b.png)

**Comment by romainruaud** [comment]
Hi @sanganagouda1 

This seems to be very specific to your project.

Did you find anything else since you submitted this ?

Regards

**Comment by amitmaurya191** [comment]
I'm also getting the slimier issue but it is in different module of elastic search. 

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\Category::isActive

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\Category::isActive
```

![image](https://user-images.githubusercontent.com/59875468/109857023-32827280-7c80-11eb-986c-c00fb29ef382.png)

Help please.

**Comment by wahidnory** [comment]
Heya,

Not to drag this issue out of staleness, but I've recently upgraded a shop from 2.3.4-p2 to 2.4.2 and this came out of nowhere.
If anybody got any tips as to where to look, that'd be great.

If I debug this eventually I'll report back.
