### ISSUE TITLE
Number of Shard/Replica on Magento Cloud

### ISSUE THREAD

**Issue by lucasmilin** [Smile-SA/elasticsuite#2000]
Hi,

For some reasons, indices are created with 3 shards and 0 replicas instead of having 3 shards and 2 replicas  on Magento Cloud.

Do you have any idea what can cause this wrong index configuration?

Thanks!

**Additional context**
Magento Commerce Cloud 2.3.5-p2
Elasticsuite 2.8.2
Elasticsearch 6.5.4

There are also recurring messages in the elasticsearch.log file:
][INFO ][o.e.x.m.e.l.LocalExporter] [-_XXXX] waiting for elected master node [{ixxxxx}

{ml.machine_memory=169007497216, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}] to setup local exporter [default_local] (does it have x-pack installed?)

**Comment by romainruaud** [comment]
This is intended to be configurable through the Back-Office : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings

However, on Magento Cloud, they enforce it through this class of the ECE Tools : https://github.com/magento/ece-tools/blob/develop/src/Config/SearchEngine/ElasticSuite.php

So for me, everything relies in the template file of Magento Cloud, if you set proper values inside it, they will be reported to Elasticsuite configuration.

**Comment by romainruaud** [comment]
That being said, since a Magento Cloud infrastructure is always on 3 nodes, I could advise to proceed with the following configuration : 

- 3 shards
- 2 replicas

But keep in mind the following thing : *you probably don't need 3 shards, especially if you do not have several dozens of Gbs in your indices*.

Most probably, *1 shard / 2 replicas* is enough for most cases.

Regards

**Comment by lucasmilin** [comment]
Thank for your answer @romainruaud!

Let me give more details. We configured Elasticsuite with 3 shards/2 replicas in the .magento.env.yaml:

SEARCH_CONFIGURATION:
            _merge: true
            engine: elasticsuite
        ELASTICSUITE_CONFIGURATION:
            _merge: true
            indices_settings:
                number_of_shards: 3
                number_of_replicas: 2

This configuration works very well most of the time:

green  open   magento2_fr_catalog_product_20201009_104106     xxxxxxxxxxxxxxxxx   3   0    0            0       783b           783b
green  open   magento2_fr_catalog_category_20201007_150650    xxxxxxxxxxxxxxxxx   3   2    402       28      1.9mb        667.1kb
green  open   magento2_en_catalog_product_20201009_062305  xxxxxxxxxxxxxxxxx   3   0    0            0       783b           783b

but sometimes while reindexing, some indices are created with 3 shards/0 replica.

Have you ever heard about this kind of behaviour? I would like to know what can cause an index with 0 replica whereas the settings is 2 replicas.

Regards

**Comment by rbayet** [comment]
Hello @lucasmilin,

> but sometimes while reindexing, some indices are created with 3 shards/0 replica.

This is standard behaviour for Elasticsuite.
New indices are **created at first with a replica value of 0.**
Once the reindexing is complete for a given index, it is "**installed**", which means 
- the index **alias** is swapped from the previous index to that new one
- the replica settings are applied

See \Smile\ElasticsuiteCore\Indexer\GenericIndexerHandler::saveIndex
```
        foreach ($dimensions as $dimension) {
            $storeId   = $dimension->getValue();

            try {
                $index = $this->indexOperation->getIndexByName($this->indexName, $storeId);
            } catch (\Exception $e) {
                $index = $this->indexOperation->createIndex($this->indexName, $storeId);
            }

            [...]
            $this->indexOperation->installIndex($index, $storeId);
            [...]
```
And \Smile\ElasticsuiteCore\Index\IndexOperation::createIndex + \Smile\ElasticsuiteCore\Index\IndexSettings::getCreateIndexSettings
```
    public function getCreateIndexSettings()
    {
        $settings = [
            'requests.cache.enable'            => true,
            'number_of_replicas'               => 0,
            'number_of_shards'                 => $this->helper->getNumberOfShards(),
```
Versus \Smile\ElasticsuiteCore\Index\IndexOperation::installIndex + \Smile\ElasticsuiteCore\Index\IndexSettings::getInstallIndexSettings
```
    public function getInstallIndexSettings()
    {
        $settings = [
            'number_of_replicas'     => $this->helper->getNumberOfReplicas(),
            'refresh_interval'       => self::DIFF_REINDEX_REFRESH_INTERVAL,
```

Having indices with
- a "timestamp" in the past
- no index alias
- a small index size
- 0 document 
- a number of replicas of 0

is usually indicative of a fatal error during reindexing.
We call those indices "ghost indices". A "Indices Stats Dashboard'" was introduced in a later version of Elasticsuite to allow you to remove those useless indices from Magento admin.

Regards,
