### ISSUE TITLE
double class attribute in autocomplete template

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#2008]
Magento Version : 2.4.1

ElasticSuite Version : 2.10.3

Smile_ElasticsuiteCatalog\web\template\autocomplete\product.html

The items listed here have two class attributes set inside template:
class="<%- data.row_class %>" and class="product-item"

**Comment by rbayet** [comment]
@vahonc Could you replicate the fix of https://github.com/Smile-SA/elasticsuite/pull/2022 for branch 2.9.x ?
