### ISSUE TITLE
Bulk index operation failed - failed to parse [children_attributes]

### ISSUE THREAD

**Issue by johnhughes1984** [Smile-SA/elasticsuite#201]
Hi guys

First off great work on this suite, it's a very impressive open source offering.

We've implemented the suite on one of our sites and we noticing issues with bundle products, which means they keep disappearing from categories (and search) on the frontend of the site.

This is an example of the error output (in system.log) that outputs when the catalogsearch_fulltext index is refreshed:

```
[2016-11-14 11:00:22] main.ERROR: Bulk index operation failed 12 times in index magento2_default_catalog_product_20161114_110007 for type product Error (mapper_parsing_exception) : failed to parse [children_attributes] Failed doc ids sample : 5802, 5808, 5810, 5814, 5817, 5818, 5824, 5851, 5859, 5867 [] []
```

The error is in nature similar to the one raised in this ticket: https://github.com/Smile-SA/elasticsuite/issues/81

However it refers to 'children attributes', which as all the product Ids listed as samples in the error are bundle products relates to some kind of issue mapping these.

I've also tried turning making all attributes not searchable / used in layered navigation with no success.

It is also worth noting we have around 100 bundle products on the site and only a certain number at any one time have problems (between 10-30 normally) and it does appear to very intermittent.

If you have any ideas / suggestions or have seen this before It'd be appreciated as it has us scratching our heads at the minute!

If you need any more detail please let me know.

Kind regards

**Comment by afoucret** [comment]
Hi @johnhughes1984,

Very glad to see you appreciate our work on ElasticSuite. We appreciate a lot such supportive feedback.

For you bug, it would help us a lot if you were able to extract the error from the ElasticSearch logs which should be located in `/var/log/elasticsearch`directory. Actually they are more accurate than the Magento log which are only aggregating product ids. By the way the contains the document source indexed ....

**Comment by johnhughes1984** [comment]
Sure no problem, will take a look there now

**Comment by johnhughes1984** [comment]
Hi @afoucret 

Please see log file attached, now I know that exists I'll also have a browse through and see what I can spot.

[elasticsuite.log.txt](https://github.com/Smile-SA/elasticsuite/files/589511/elasticsuite.log.txt)

Many thanks

**Comment by afoucret** [comment]
Hi @johnhughes1984,

Found !!! The patch should be available very soon (let's say tomorrow). It is only matters of having a array_values somewhere it is currently missing.

I will also need to know what version of ElasticSuite you are currently using in order to target the right branch ....

**Comment by johnhughes1984** [comment]
Wow, that was fast! Thanks @afoucret 

We're running the latest (I believe), which is 2.2.2

We're also running Magento CE 2.1.2 if it helps at all.

Many thanks for looking at this so quickly, very much appreciated 👍 💯

**Comment by afoucret** [comment]
Note : Patched proposed in PR #202

**Comment by afoucret** [comment]
You can test

**Comment by afoucret** [comment]
You can test it by using the 2.2.x dev branch.
If everything is OK, it will be part of the next release (2.2.3).

Thx for reporting and by advance for your feedback about the patch.

**Comment by johnhughes1984** [comment]
Excellent, I can confirm it works great (i.e. no more errors when indexing bundle products).

Many, many thanks!
