### ISSUE TITLE
Crashing server if ES not responding.

### ISSUE THREAD

**Issue by alin1918** [Smile-SA/elasticsuite#2011]
### Preconditions

Set in the database 2-3 es servers:
smile_elasticsuite_core_base_settings/es_client/servers --- elasticsearch:9400,elasticsearch:9200,elasticsearch:9500

On first have have a non responding ES server (but active). Can be reproduced by starting a netcat listen on that server:  nc -l 9400 
Try to load a page that is using the elasticsearch.
It will remain in loading until you go and kill the process : "nc -l 9400".

A fix can be done by setting a timeout on the connection. ex vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php : extractOptions
![Screen Shot 2020-12-02 at 10 08 31 PM](https://user-images.githubusercontent.com/792685/100925952-5f8d8080-34eb-11eb-8e38-9ec0564284da.png)

![Screen Shot 2020-12-02 at 10 09 43 PM](https://user-images.githubusercontent.com/792685/100925750-19d0b800-34eb-11eb-93c9-4271516cf07c.png)
or 
vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php : performRequest 
or 
vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php:search
vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php:info
vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php: indexExists ( A fix can be done just with this one, because will mark the two problematic servers as dead and will get a connection on the third one)

![Screen Shot 2020-12-02 at 10 20 25 PM](https://user-images.githubusercontent.com/792685/100926828-b051a900-34ec-11eb-9370-4b586cd74a42.png)

![Screen Shot 2020-12-02 at 10 20 18 PM](https://user-images.githubusercontent.com/792685/100926816-adef4f00-34ec-11eb-8005-9685177d6f42.png)

Magento Version :
Magento EE 2.3.5-p2

ElasticSuite Version :
"smile/elasticsuite": "^2.8"

Environment :
Developer

Third party modules :
A lot.

### Expected result

1. Page should Load

### Actual result

1. [Screenshot, logs]
Page is not loading
![Screen Shot 2020-12-02 at 10 10 53 PM](https://user-images.githubusercontent.com/792685/100925888-4b498380-34eb-11eb-8e05-5308fd89515c.png)

**Comment by romainruaud** [comment]
2 years old issue -> I close.

Feel free to open a new one if needed.

Regards
