### ISSUE TITLE
ElasticSearch Server 7.6.x 

### ISSUE THREAD

**Issue by gaiterjones** [Smile-SA/elasticsuite#2012]
I am working on upgrades to Magento 2.4.1. The Magento system requirements recommend ElasticSearch Server v7.6.x - can you confirm ElasticSuite 2.10.x is compatible with ElasticSearch Server 7.6.x. If not which version is recommended?

**Comment by vahonc** [comment]
Hello @gaiterjones,

In my local environment I use:
- Magento EE ver. 2.4.1
- Elasticsearch 7.9.3
- ElasticSuite 2.10.3

Here's an output 'curl -XGET 'localhost:9200'';
<pre>
{
  "name" : "master",
  "cluster_name" : "m241ee",
  "cluster_uuid" : "N00zhFP3TEm0r2Y6yH6eVQ",
  "version" : {
    "number" : "7.9.3",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "c4138e51121ef06a6404866cddc601906fe5c868",
    "build_date" : "2020-10-16T10:36:16.141335Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
</pre>

And I don't notice any issues with compatibility.

Best regards,

**Comment by romainruaud** [comment]
Yes as @vahonc said, Elasticsuite is compatible with your version of ES.

If you face any bugs or non-compatible things, please open a new issue with details.

regards
