### ISSUE TITLE
how to add custom field in elasticsuite modules

### ISSUE THREAD

**Issue by rajupremkumar** [Smile-SA/elasticsuite#2016]
@romainruaud and what about if I have many values (like tags) I should supply it like csv or maybe array?

_Originally posted by @madonzy in https://github.com/Smile-SA/elasticsuite/issues/517#issuecomment-326267075_

**Comment by romainruaud** [comment]
Hi @rajupremkumar 


Please : 

- respect the issue/question template by giving more details about what you are trying to achieve.
- read the wiki about indexing and especially the *Datasource* part : https://github.com/Smile-SA/elasticsuite/wiki/Indexing

I close your issue, if you don't manage to do it with the wiki details, please open a new one and provide a clear explanation of your use case.
