### ISSUE TITLE
Uninstal elasticsuite

### ISSUE THREAD

**Issue by mihaikalif** [Smile-SA/elasticsuite#2024]
Uninstal for elasticsuite fails

### Preconditions

Magento Version : Magento CE 2.4.0

ElasticSuite Version : 2.10.1

Environment : developer

Third party modules :

### Steps to reproduce

1. followed this link to unistall https://github.com/Smile-SA/elasticsuite/issues/299
2. removed the files from vendor/smile
3. removed the lines for registration configuration autoload_files.php

### Expected result
removed successfully

### Actual result

1. [Screenshot, logs]
Errors appears when trying to flush cache
PHP Warning:  require(/opt/bitnami/apps/magento/htdocs/vendor/composer/../smile/elasticsuite/src/module-elasticsuite-core/registration.php): failed to open stream: No such file or directory in /opt/bitnami/apps/magento/htdocs/vendor/composer/autoload_real.php on line 73
PHP Fatal error:  require(): Failed opening required '/opt/bitnami/apps/magento/htdocs/vendor/composer/../smile/elasticsuite/src/module-elasticsuite-core/registration.php' (include_path='/opt/bitnami/apps/magento/htdocs/vendor/magento/zendframework1/library:.:/opt/bitnami/php/lib/php') in /opt/bitnami/apps/magento/htdocs/vendor/composer/autoload_real.php on line 73

**Comment by mihaikalif** [comment]
Removed the lines referring to smilesuite from:
composer\autoload_psr4.php
\composer\autoload_static.php 
\composer\installed.json 
The error now translates to: 

PHP Fatal error:  Uncaught Error: Class 'Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration\BaseConfig' not found in /opt/bitnami/apps/magento/htdocs/generated/code/Smile/ElasticsuiteCore/Search/Request/ContainerConfiguration/BaseConfig/Proxy.php:7
Stack trace:
#0 /opt/bitnami/apps/magento/htdocs/vendor/composer/ClassLoader.php(444): include()
#1 /opt/bitnami/apps/magento/htdocs/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/opt/bitnami/ap...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smile\\Elasticsu...')
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): spl_autoload_call('Smile\\Elasticsu...')
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Smile\\Elasticsu...', Array)
#5 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ in /opt/bitnami/apps/magento/htdocs/generated/code/Smile/ElasticsuiteCore/Search/Request/ContainerConfiguration/BaseConfig/Proxy.php on line 7

**Comment by vahonc** [comment]
Hello @mihaikalif,

Removing our module manually is not the best solution, but you can easily remove the ElasticSuite module via composer:
`composer remove smile/elasticsuite`

I suggest you this way:
1. Remove the ElasticSuite module via composer
2. Run setup-upgrade, reindex and clean cache commands from Magento CLI
3. Follow this link to unistall #299 to clean up your DB
4. Update an `Search Engine` option in `Stores -> Settings -> Configuration -> Catalog -> Catalog -> Catalog Search` in Magento BO
4. Run again reindex and clean cache commands from Magento CLI

Best regards,

**Comment by mihaikalif** [comment]
rm -rf var/cache/*
 rm -rf var/page_cache/*
 rm -rf var/generation/*
rm -rf generated
 rm -rf pub/static/*

Did the trick and finally I removed successfully the elasticsuite.

**Comment by romainruaud** [comment]
Ok great I close then.

Regards
