### ISSUE TITLE
Graphql import + catalog reindex

### ISSUE THREAD

**Issue by splakhonin** [Smile-SA/elasticsuite#2027]
After bulk import by default Magento elasticsearch index is created (ex magento2_default_catalog_product)
After if you run catalog search reindex you will see an error {type":"invalid_alias_name_exception","reason":"Invalid alias name [magento2_default_catalog_product]}
 
### Preconditions

Magento 2.4.1 Cloud/EE

ElasticSuite Version :
Last  2.10.x

Environment :
Developer

**Comment by romainruaud** [comment]
hi @splakhonin could you please provide more detailed scenario to reproduce this ?

The first step especially is not clear, are you starting with an empty DB and then importing some stuff in it ?

Regards
