### ISSUE TITLE
Fix issue with missing values on swatches attributes filters

### ISSUE THREAD

**Issue by berkneis** [Smile-SA/elasticsuite#2029]
Hello,

I have asked a question on this topic before. #2028 

I don't know how it reacts in other attribute types, however when I experiment with color attribute (visual swatch), there is no value seems with the Filterable (with results) selection in the Use in Layered Navigation option. When I select it as filterable (no results), the filter appears but it doesn't work. Links are not being able to be clicked.

I've reviewed #1360 pull request.
[Related modification](https://github.com/Smile-SA/elasticsuite/pull/1360#issuecomment-585882468) 

### Preconditions

Magento Version : 2.4.1
ElasticSuite Version : 2.10.3 (latest)
Environment : Developer and Production

### Steps to reproduce
1. Add a visual swatch attribute into filter.
2. Set Filterable (with results) selection to Use in Layered Navigation
3. Check your available filters.

### FIX

I fixed the issue overriding this function in "\Smile\ElasticsuiteSwatches\Block\Navigation\Renderer\Swatches\RenderLayered":

```
protected function getFilterOption(array $filterItems, Option $swatchOption)
{
    $resultOption = false;
    $filterItem = $this->getFilterItemById($filterItems, $swatchOption->getValue());
    if ($filterItem && $this->isOptionVisible($filterItem)) {
        $resultOption = $this->getOptionViewData($filterItem, $swatchOption);
    }
    return $resultOption;
}
```
TO
```
protected function getFilterOption(array $filterItems, Option $swatchOption)
{
    $resultOption = false;
    $filterItem = $this->getFilterItemByLabel($filterItems, $swatchOption->getLabel());
    if ($filterItem && $this->isOptionVisible($filterItem)) {
        $resultOption = $this->getOptionViewData($filterItem, $swatchOption);
    }
    return $resultOption;
}
```

**Comment by vahonc** [comment]
Hello @berkneis,

Could you please give more details about the configuration of your particular test case and your attribute, since the "color" attribute is working out-of-the-box? This will help us understand why the problem described by you occurs when the scenario (options, settings) for creating custom attributes differs from the default behavior.

Best regards,

**Comment by berkneis** [comment]
Hello @vahonc ,

Thanks for your answer.

I am using a custom theme. 
When I test with luma theme which is preferred in developer environment, problem appears to be same. I am using multilingual store. 

```
$swatchOption->getValue()
```
When I use as it is shown above, there is no color option appears in the filter. Only the title appears.

For example;
![Screenshot (25)](https://user-images.githubusercontent.com/2790754/103580677-ace67e80-4eeb-11eb-9b62-8bf678880f64.png)


```
$swatchOption->getLabel()
```
When I use as it is shown above I don't have any problem. It appears as it is shown in the picture. 
![Screenshot (26)](https://user-images.githubusercontent.com/2790754/103580993-3302c500-4eec-11eb-8d25-e7185a8aef8b.png)
All the filter settings are like in the picture.

![1](https://user-images.githubusercontent.com/2790754/103580079-95f35c80-4eea-11eb-9e25-909ad68049de.png)
![2](https://user-images.githubusercontent.com/2790754/103580091-9a1f7a00-4eea-11eb-9988-9b1fec9b61c4.png)

**Comment by rbayet** [comment]
Hello @berkneis,

Could you post the exact same two screenshots but *with* the Luma theme and not the custom theme ?
Is it an in-house custom theme or a theme extension ? If the latter, which one ?

Regards,

**Comment by berkneis** [comment]
Hello @rbayet ,

Thank you for answer.

```
$swatchOption->getValue()
```
while using this code;

![Screenshot (35)](https://user-images.githubusercontent.com/2790754/103799590-59e00900-505c-11eb-928a-026ccb0e7c00.png)


```
$swatchOption->getLabel()
```
while using this code;
![Screenshot (34)](https://user-images.githubusercontent.com/2790754/103799644-69f7e880-505c-11eb-934d-93d84e1409f3.png)

If you wish I can set up a demo address.

2- It is not an extension, it is a custom theme.

**Comment by vahonc** [comment]
Hello @berkneis,

Earlier, to test another issue in Magento 2.4.0, I had created my custom attribute "Color Swatch" based on the standard "Color" and I had no problems with displaying it without any additional changes in the code. 

![Screenshot from 2021-01-05 12-47-06](https://user-images.githubusercontent.com/67791361/103889905-da9c1500-50ef-11eb-8fc5-97e341b50f19.png)

Also if you take a look at this: https://github.com/Smile-SA/elasticsuite/blob/5cf565150049899306e81127ecd52b8a9587cdff/src/module-elasticsuite-swatches/Block/Navigation/Renderer/Swatches/RenderLayered.php#L95

you will see that in the ElasticSuite 2.10.3 version originally this line hasn't changed as you described in your preconditions/fix.

So it looks like that on your side were some additional changes, maybe when you tested something. Please try re-install the ElasticSuite 2.10.3 version and check it out again.

Best regards
