### ISSUE TITLE
What is better - relevance rule or optimizer

### ISSUE THREAD

**Issue by Mobecls** [Smile-SA/elasticsuite#2034]
I found that both Relevance rules and Optimizers are doing kind of the same. 

What is the difference in them and what I should be using most?

**Comment by rbayet** [comment]
Hello @Mobecls,

Did you close the issue by mistake or have you found an answer in the meantime ?

Regards,

**Comment by Mobecls** [comment]
No, I actually was comparing Amasty's relevance to Searchsuite Optimizer - so it's not relevant to post it here.

Yet the Relevance feature in Searchsuite is not that obvious - I'm not really sure what's the best configuration here and how does it work - /smile_elasticsuite/search_request_relevanceconfig/index

**Comment by rbayet** [comment]
The relevance settings allows you to tweak how the fulltext search works.
Default settings are usually OK in most cases, but [the wiki page](https://github.com/Smile-SA/elasticsuite/wiki/FulltextSearchEngineBasicConfiguration) gives you more information about those. 

Almost all settings are related to an Elasticsearch feature/behavior, so there is a lot of link to Elasticsearch documentation too.
It can be much more explicit that our wiki page.

Regards,
