### ISSUE TITLE
tracking_log_session index does not exist yet and 

### ISSUE THREAD

**Issue by DevRiffs** [Smile-SA/elasticsuite#2038]
Hello,
I saw same question, but it is closed without answer. I have issue, that there is error "tracking_log_session index does not exist yet and ", elasticsuite_tracker_log_event table empty and not filling when browsing. Tracking is enabled. So at this point not sure what is wrong and what to do.

**Comment by vahonc** [comment]
Hello @DevRiffs,

Firstly, we need more details about your environment and test case. Based on the fact that you pointed out I can only advise you to make sure if the module is really enabled with the command:
`bin/magento module:status Smile_ElasticsuiteTracker`,

also, if needed run these commands: 
<pre>
bin/magento setup:upgrade
bin/magento cache:flush
bin/magento indexer:reindex
</pre>

After that try to search for some products on your website and then check Magento BO -> ElasticSuite -> Analytics -> Search Usage. I also recommend that you check if your cron is configured correctly, since the correct work of the ElasticsuiteTracker  depends on it.

Best regards

**Comment by DevRiffs** [comment]
What is correct cron configuration for elasticsuite? Cron is working, everything else is fine. Is there anything else need to set in cron for elasticsuite ?

**Comment by vahonc** [comment]
As far as I know, ElasticSuite doesn't require any additional or specific settings in cron.

**Comment by jmonrove** [comment]
I am having the same issue in Magento Commerce 2.3.5-p2 with ElasticSuite 2.9

![image](https://user-images.githubusercontent.com/32687858/110833608-7ad9fb80-8251-11eb-965a-05e42461c90c.png)


When I check my Indexes, they're not there
![image](https://user-images.githubusercontent.com/32687858/110833840-b70d5c00-8251-11eb-9558-fbf5e5087875.png)


When I checked my database, I don't see either
tracking_log_session 
tracking_log_event

but you can see

elasticsuite_**tracker**_log_customer_link
elasticsuite_**tracker**_log_event
![image](https://user-images.githubusercontent.com/32687858/110834068-f3d95300-8251-11eb-8a97-4641c9253cd6.png)

**Comment by jmonrove** [comment]
When I perform searches in the front end I do get new records added to 
elasticsuite_tracker_log_event


I do get the h.png image with a 200 status code

![image](https://user-images.githubusercontent.com/32687858/110837898-ab706400-8256-11eb-8d80-ec6783c47dbf.png)

**Comment by romainruaud** [comment]
@DevRiffs and/or @jmonrove  any update on this one ?

As soon as you have Magento cron running, data collected through the tracker should be indexed into Elasticsearch.

When you navigate, you should see data coming into `elasticsuite_tracker_log_event`

And then, when the cron passes, data is indexed into Elasticsearch and removed from this table.

**Comment by jmonrove** [comment]
Hi @romainruaud 

My indices are up to date and cron is running every 5 mins, but the problem remains that
**tracking_log_session** and  **tracking_log_event**
do not exist in my database.

![image](https://user-images.githubusercontent.com/32687858/116428041-66e65b00-a7f9-11eb-9a0b-9a135d126210.png)

**Comment by jmonrove** [comment]
Here's a screenshot of me manually running cron, index reset and reindexing with the status result below, observe no log_session log_event indexes shown.

Any ideas? Thanks!

![image](https://user-images.githubusercontent.com/32687858/116429387-b2e5cf80-a7fa-11eb-9a11-20286a1955dc.png)

**Comment by romainruaud** [comment]
Hi,

what's the output of `curl your-elastic-search-ip:9200/_cat/indices` ?

**Comment by jmonrove** [comment]
This is the response I got from running that command:

`green open magento2_default_catalog_product_20210308_214857  9lThkMvETOilSOlxa2szog 1 0     0 0    208b    208b
green open magento2_default_tracking_log_session_20210318    m3aTyfuNSEeEV1ZfSpFKbw 1 0     3 0   5.8kb   5.8kb
green open magento2_default_tracking_log_event_20210413      tB2J4gKzSCe49hjqbvCCRg 1 0    16 0  25.3kb  25.3kb
green open magento2_default_thesaurus_20210428_151913        e_bMWx0iS2W_lMRU3w2MKA 1 0     0 0    208b    208b
green open magento2_default_tracking_log_session_20210413    f9LqyiuCRoecKTWD1CqmXw 1 0    16 0  10.5kb  10.5kb
green open magento2_default_tracking_log_session_20210311    D6avNPAxRVSR8EYS0wjbXw 1 0    14 0    12kb    12kb
green open magento2_default_tracking_log_event_20210318      m9L_AywVQ9qiIT8gJyqtxQ 1 0     3 0  12.3kb  12.3kb
green open magento2_default_tracking_log_session_20210310    zMCY8O_KTRGAA1E7JNiH8A 1 0     1 0   6.1kb   6.1kb
green open magento2_default_tracking_log_session_20210330    UPVfRMrFROKL895x-c3QuA 1 0     1 0     5kb     5kb
green open magento2_default_tracking_log_event_20210330      m-VId2ISToGkaCzvDkNR9g 1 0     1 0  10.9kb  10.9kb
green open magento2_default_tracking_log_event_20210310      C0qqE007SFGCY2LkMMDomw 1 0     7 0  23.3kb  23.3kb
green open magento2_default_tracking_log_event_20210311      nqw6JfMqQzSU-zJeX8YKRg 1 0    26 0  32.6kb  32.6kb
green open magento2_default_tracking_log_session_20210308    _A7DWV0CQVmS0yhLpsku_g 1 0     1 0   9.6kb   9.6kb
green open magento2_default_tracking_log_session_20210407    KSKPmqiHQ_2FmxinFEOOug 1 0     8 0   7.7kb   7.7kb
green open magento2_default_tracking_log_session_20210309    ap2C8zc2T7KNyRc45WfV1g 1 0     4 0   9.4kb   9.4kb
green open magento2_default_tracking_log_session_20210328    bINmnCseRcyTkAKm5iUQSg 1 0     1 0     5kb     5kb
green open magento2_default_tracking_log_session_20210405    6yfkvBuuQFKUVWJPUVxQvw 1 0     4 0   7.9kb   7.9kb
green open magento2_default_tracking_log_session_20210406    I0grqBUBRt6FPAX8Q1N6Bw 1 0     1 0     5kb     5kb
green open magento2_default_tracking_log_session_20210425    xWdc2VjwRWS_xzF3WQjNzA 1 0     4 0   6.7kb   6.7kb
green open magento2_default_tracking_log_session_20210327    Ucb2ZtDySsKjaR5qau_EBQ 1 0     1 0     5kb     5kb
green open magento2_default_tracking_log_event_20210325      Qx7V3TC_T6y2oDBxGR4hGA 1 0   476 0  99.6kb  99.6kb
green open magento2_default_tracking_log_event_20210425      tOIMiby_TYOBpMU2HMA7eA 1 0     8 0    21kb    21kb
green open magento2_default_tracking_log_event_20210327      bOPCOVXhR4eRlx0UvCOXbg 1 0     1 0  10.9kb  10.9kb
green open magento2_default_catalog_category_20210428_151912 DhqdU3C_SfSFVLuyXRUbng 1 0    54 0 535.7kb 535.7kb
green open magento2_default_tracking_log_session_20210325    ID8HqQ8ER9uOK2LH177eVA 1 0     2 0     6kb     6kb
green open magento2_default_tracking_log_event_20210328      REV-G3AETICYZF6Wc0b9Bw 1 0     1 0  10.9kb  10.9kb
green open magento2_default_tracking_log_event_20210405      0docEJRPSp6lOI6UlylS0A 1 0    32 0  39.4kb  39.4kb
green open magento2_default_catalog_product_20210428_151855  KEMR_myVSVqOjzsb8HNtSA 1 0 11749 0   7.4mb   7.4mb
green open magento2_default_tracking_log_event_20210406      jtGL03gISPSEYZQMd4p9Hg 1 0     1 0  10.9kb  10.9kb
green open magento2_default_tracking_log_event_20210407      dER7tymeSMSeiNh77PyoiQ 1 0     8 0  17.4kb  17.4kb
green open magento2_default_tracking_log_session_20210320    iku3ktq9RkOBp-q24iBKeQ 1 0     1 0     5kb     5kb
green open magento2_default_tracking_log_event_20210308      EMsMqyZ8RE-m58XbPGEPPw 1 0    52 0  46.1kb  46.1kb
green open magento2_default_catalog_product_20210308_214751  N3tVJk9AQcWaioc6gavz4w 1 0     0 0    208b    208b
green open magento2_default_tracking_log_event_20210309      HR-wzJfgSMeyT3evrtr9aw 1 0    51 0  56.6kb  56.6kb
green open magento2_default_tracking_log_event_20210320      07Wvp5afR3S_cd13j-gKNQ 1 0     1 0  10.9kb  10.9kb
green open magento2_default_cms_page_20210428_151913         1mRT4alDQVmdlAp4dJBcUA 1 0     0 0    208b    208b`

**Comment by romainruaud** [comment]
Okay so the tracking session indices are there.

I don't get why Elasticsuite would not be seeing them

**Comment by jmonrove** [comment]
Not sure either, this is running on Magento commerce 2.3.5-p2 with elasticsuite 2.9.0
I'm going to try updating to Magento commerce 2.4.2-p1 with elasticsuite 2.10.0

**Comment by jmonrove** [comment]
I was able to get it working on Magento Comerce 2.4.2, elasticsuite 2.10.0
![image](https://user-images.githubusercontent.com/32687858/117345096-0390a480-ae5b-11eb-8f7c-f6cc3c7ad5e1.png)
![image](https://user-images.githubusercontent.com/32687858/117345253-2d49cb80-ae5b-11eb-84ef-cb57112f995e.png)
