### ISSUE TITLE
Error: Call to undefined method addQueryFilter()

### ISSUE THREAD

**Issue by setrada** [Smile-SA/elasticsuite#2042]
### Preconditions
Magento Version : 2.4.1
ElasticSuite Version : 2.10.3
Environment : Developer and Production
Third party modules : WeltPixel Layered Navigation

### Steps to reproduce
1. Install WeltPixel Layered Navigation Free Version
2. Click on Category Page

### Expected result
1. Showing products of category

### Actual result
Error: Call to undefined method WeltPixel\LayeredNavigation\Model\ResourceModel\Fulltext\Collection\Interceptor::addQueryFilter() in htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php:94 Stack trace: #0 htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(119): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection(Object(Magento\Catalog\Model\Category\Interceptor)) #1 htdocs/vendor/magento/module-layered-navigation/Block/Navigation.php(70): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply(Object(Magento\Framework\App\Request\Http)) #2 htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(287): Magento\LayeredNavigation\Block\Navigation->_prepareLayout() #3 htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(149): Magento\Framework\View\Element\AbstractBlock->setLayout(Object(Magento\Framework\View\Layout\Interceptor)) #4 htdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #5 htdocs/vendor/magento/framework/View/Layout.php(352): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context)) #6 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->generateElements() #7 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('generateElement...', Array) #8 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #9 htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(68): Magento\Framework\View\Layout\Interceptor->___callPlugins('generateElement...', Array, Array) #10 htdocs/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements() #11 htdocs/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks() #12 htdocs/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks() #13 htdocs/vendor/magento/framework/View/Page/Config.php(224): Magento\Framework\View\Layout\Builder->build() #14 htdocs/vendor/magento/framework/View/Page/Config.php(587): Magento\Framework\View\Page\Config->build() #15 htdocs/vendor/magento/framework/View/Page/Config.php(545): Magento\Framework\View\Page\Config->getElementAttribute('body', 'class') #16 htdocs/vendor/magento/module-catalog/Controller/Category/View.php(249): Magento\Framework\View\Page\Config->addBodyClass('page-products') #17 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Category\View->execute() #18 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('execute', Array) #19 htdocs/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}() #20 htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure)) #21 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}() #22 htdocs/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(23): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('execute', Array, Array) #23 htdocs/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Category\View\Interceptor->execute() #24 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #25 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', Array) #26 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #27 htdocs/generated/code/Magento/Catalog/Controller/Category/View/Interceptor.php(32): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', Array, Array) #28 htdocs/vendor/magento/framework/App/FrontController.php(186): Magento\Catalog\Controller\Category\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #29 htdocs/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Catalog\Controller\Category\View\Interceptor)) #30 htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http)) #31 htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array) #32 htdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #33 htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #34 htdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #35 htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http)) #36 htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #37 htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array) #38 htdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #39 htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #40 htdocs/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #41 htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #42 {main}

**Comment by romainruaud** [comment]
Hello @setrada 

Most probably and according to the stacktrace you gave, there is a major incompatibility between your module and Elasticsuite.

It's not that surprising if we consider both modules are working on the same functional parts of the layered navigation.

Since compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do.

However, in such cases, we do provide commercial support to ensure building proper compatibility. If you are interested in such kind of support, send and email to elasticsuite@smile.fr and we'll try to handle your request.

Best regards.
