### ISSUE TITLE
Upgrade from 2.8.8 to 2.10.3 Magento commerce 

### ISSUE THREAD

**Issue by VZeroCool** [Smile-SA/elasticsuite#2045]
We had **Magento commerce(enterprise) 2.3.5-p1** with **Elasticsuit 2.8.8** and **Elasticsearch 6.6** 
All things are working as expected post upgrade of all of three application autocomplete started behaving strange.  
**Magento Commerce - 2.4.1** , **Elasticsuit- 2.10.0** and **Elasticsearch - 7.6**
Search terms,Categories is there but products are missing for autocomplete box.

**Strange Problem:** In local environment if we use Elasticsearch 6.x with latest Elasticsuit 2.10.0 its working as expected. but not with Elasticsearch 7.6.

### Preconditions

Magento Version : 2.4.1 Commerce  (EE) 

ElasticSuite Version : 2.10.03

Environment : Developer or production output is same

Third party modules : Yes having in-house module to customize autocomplete behavior. To include downloadable products.  
https://pastebin.com/hXn3paUM

### Steps to reproduce

1. Upgrade Magento with elasticsearch 
2. Reindex all data
3. Go to frontend and check

### Expected result

1. It should work with Elasticsearch 7.6 as no changes in core module. 

### Actual result

1. Working with latest Elasticsuit and Elasticsearch 6.6 but not with Elasticsearch 7.6

**Comment by romainruaud** [comment]
Hi @VZeroCool 

I've seen that you did customize the Autocomplete Products Dataprovider. We cannot provide support for existing customization that would go in failure following an upgrade of Elasticsuite.

Did you try removing this override ? Is it working with only the legacy class ?

**Comment by VZeroCool** [comment]
Hi @romainruaud 
yeah it's working slightly but in latest version something changed at ProductCollection class. As its not returning productObject. 

In ESuit 2.8.X printing $product was returning complete product object, In 2.10.x it's not.

https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Autocomplete/Product/DataProvider.php#L92

That's why our logic stopped working. I looked for release notes but couldn't find much. 
Can you help out with that if possible !?

Thanks,

**Comment by romainruaud** [comment]
Hi, sorry @VZeroCool but we cannot provide open source (free) support for module customization here.

This repository is intended only to track legacy bugs of the software, which is not appearing to be the case here, since it's due to customizations by your side.

If you are interesting in purchasing some professional support from us, please feel free to write at elasticsuite@smile.fr

Regards
