### ISSUE TITLE
Fatal error: Call to a member function getCategorySearchQuery() on null vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 98

### ISSUE THREAD

**Issue by mantonuk** [Smile-SA/elasticsuite#205]
I got Fatal error on M2.1.2 and "Smile_ES' 2.2.2.
Issue come if '**catalog category flat data**' == enabled. (all ok if has disabled)

smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php
96         $query = $category->getVirtualRule()->getCategorySearchQuery($category);
method on line 98 retrn wrong object.

$category->getVirtualRule()
return
string(61) "Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category" ('catalog category flat data' == enabled)
**instead of **
"Smile\ElasticsuiteVirtualCategory\Model\Rule" **'catalog category flat data' == disabled**)

**Comment by martijnrmediact** [comment]
We are encountering the same issue also when flat categories are disabled.

**Comment by ulftietze** [comment]
Hey,

i can relate this issue too in version 2.2.6 with installed Magento 2.2.6.
I'm looking forward to get some more debug information.

**Comment by ulftietze** [comment]
Hey Guys,

debugged myself into this and found a possible bug/solution.
In my projekt i was extending the Magento\Catalog\Model\Category and replaced it with a <preference .../>

Removing this preference, clearing all caches and generated classes, this works like a charm ^^
