### ISSUE TITLE
Navigation Error - Smile/Elastic Suite

### ISSUE THREAD

**Issue by gmalhotra02** [Smile-SA/elasticsuite#2050]
I implemented Codazon theme infinit on my new magento project and have faced following error, seems like issue with layer navigation and error generated by smile suite, only 3 modules installed Magento 2.4.1 pack + smile suite 2.10.3 + codazon theme.

I have deployed Magento CE 2.4.1, ElasticSuite 2.10.3, elasticsearch version 7.10.2

Issue: If I enable smile modules the css of search box is broken and following error is thrown while applying search. 
Note if from the drop-down I select individual product, it takes me to the product page. However if I perform general search or select category then below error is thrown - this makes me feel that somehow attributes are also broken for layered navigation. 

### Expected result
Search should display products with layered navigation on. 

### Actual result
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined.

Exception #0 (Magento\Framework\Exception\LocalizedException): The attribute model is not defined.
<pre>#1 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Attribute->getJsLayout()
#2 call_user_func_array() called at [vendor/magento/framework/View/TemplateEngine/Php.php:94]
#3 Magento\Framework\View\TemplateEngine\Php->__call() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/templates/layer/filter/attribute.phtml:30]
#4 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#5 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273]
#6 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#7 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/Renderer/AbstractRenderer.php:64]
#8 Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\AbstractRenderer->render() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:52]
#9 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->_toHtml() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation/FilterRenderer.php:37]
#10 Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer->render() called at [app/code/Codazon/AjaxLayeredNavPro/view/frontend/templates/layer/view.phtml:58]
#11 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#12 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:273]
#13 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:303]
#14 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1111]
#15 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1115]
#16 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:675]
#17 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:566]
#18 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:542]
#19 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#20 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#21 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#22 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#23 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#24 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#25 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#26 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#27 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#28 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#29 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#30 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#31 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#32 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#33 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#34 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#35 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#36 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#37 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#38 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#39 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#40 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#41 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#42 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#43 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#44 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#45 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#46 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#47 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:594]
#48 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:544]
#49 Magento\Framework\View\Layout->renderNonCachedElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:149]
#50 Magento\Framework\View\Layout\Interceptor->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:497]
#51 Magento\Framework\View\Layout->renderElement() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:140]
#52 Magento\Framework\View\Layout\Interceptor->renderElement() called at [vendor/magento/framework/View/Layout.php:963]
#53 Magento\Framework\View\Layout->getOutput() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#54 Magento\Framework\View\Layout\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#55 Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#56 Magento\Framework\View\Layout\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:347]
#57 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#58 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#59 Magento\Framework\View\Result\Layout->renderResult() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#60 Magento\Framework\View\Result\Page\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#61 Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#62 Magento\Framework\View\Result\Page\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/View/Result/Page/Interceptor.php:23]
#63 Magento\Framework\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/View.php:221]
#64 Magento\Framework\App\View->renderLayout() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:138]
#65 Magento\CatalogSearch\Controller\Result\Index->getCacheableResult() called at [vendor/magento/module-catalog-search/Controller/Result/Index.php:108]
#66 Magento\CatalogSearch\Controller\Result\Index->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#67 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#68 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/CatalogSearch/ResultPlugin.php:108]
#69 Smile\ElasticsuiteCatalog\Plugin\CatalogSearch\ResultPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#70 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#71 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#72 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#73 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:23]
#74 Magento\CatalogSearch\Controller\Result\Index\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#75 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#76 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#77 Magento\CatalogSearch\Controller\Result\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#78 Magento\CatalogSearch\Controller\Result\Index\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Result/Index/Interceptor.php:32]
#79 Magento\CatalogSearch\Controller\Result\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#80 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#81 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#82 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#83 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#84 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#85 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#86 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#87 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#88 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#89 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#90 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#91 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:40]
</pre>

**Comment by vahonc** [comment]
Hello @gmalhotra02,

Could you please try to switch to the default Magento theme - Luma and check or the problem you mentioned keeps recurring?

Best regards

**Comment by gmalhotra02** [comment]
> Hello @gmalhotra02,
> 
> Could you please try to switch to the default Magento theme - Luma and check or the problem you mentioned keeps recurring?
> 
> Best regards

Yes it is occuring on Luma theme as well now.

**Comment by vahonc** [comment]
Hello,

In the case when you switched to the Luma theme whether this Codazon_AjaxLayeredNavPro module was disabled? If it was enabled try to disable it and check it again.

Best regards

**Comment by gmalhotra02** [comment]
Error is seen after disabling ajax layer navigation pro as well

But somehow rating module has conflict with smile suite it seems, disabling rating module let's search work, there are other issues though e.g. search 

There is one more issue that is observed, e.g. selecting brand doesn't let products be loaded for particular brand... 

All of the above works well by disabling smile suite, I have asked codazon team as well to work on the issue resolution.

**Comment by gmalhotra02** [comment]
Will you be able to help with the module or I will # have only one choice of removing smile suite completely. Codazon team has denied support as it is 3rd party module issue (smile-suite module)

**Comment by romainruaud** [comment]
Hello @gmalhotra02 

It's unlikely that our module and another one working on the same area (layered navigation) will function correctly.

So you are right, you'll have to make a choice, or to resolve the conflicts by yourself (by coding).

I close since we'll not provide such support here as part of our Open Source support policy.

Regards
