### ISSUE TITLE
Product (tiles) missing

### ISSUE THREAD

**Issue by PHProDreamy** [Smile-SA/elasticsuite#2055]
When visiting some product listing pages there are products / product tiles missing. They are also not shown in the source code.

### Preconditions
Magento Version : Magento ver. 2.4.1 - CE

ElasticSuite Version : 2.10.3

Environment : We are developing but using production mode

### Steps to reproduce
1. Make a category with lots of products
2. Go through all the Listing pages
3. See there is something wrong

### Expected result

1. All listing pages should have 12 products, unless there are no more products of course

### Actual result
1. Some pages only have 10 products and they also don't show up in the source code. https://filebin.net/o0ddm3zrt1n0egfq/screencapture-acc-baby-lux-boutique-cybex-html-2021-01-27-09_33_25.png?t=pvwptxrb
When you continue to the next page, in this case page 12, there are 12 products there.

**Comment by vahonc** [comment]
Hello @PHProDreamy,

As I can see from your screenshot you are using a non-default (custom) Magento theme. We do not guarantee the correct operation of our module in such cases. 

If possible, you can switch to the default Magento theme (Luma) and check if the problem you mentioned still exists.

Best regards

**Comment by PHProDreamy** [comment]
Hello.
We have moved our environment to Luma.
The problem can be seen here: https://ibb.co/Qr4qRYK (and online at: https://acc.baby-lux.com/mondo.html?p=27)

The issue is even bigger. See the video for what happens on page 27, 28, 29, 30 and then 26 and 31 work good. https://streamable.com/cr8w7a

For htaccess please please send me a mail.

**Comment by PHProDreamy** [comment]
https://ibb.co/hVbQM3c
https://ibb.co/jZnByPM
https://ibb.co/wy9pYnT
https://ibb.co/VBP7F0C

Here are the screenshots for multiple pages.

**Comment by PHProDreamy** [comment]
https://babylux-acc2-fr.phpro.be/boutique/cybex.html?p=11 another example

**Comment by romainruaud** [comment]
Hi @PHProDreamy 

I'm closing this issue because it's something specific to your project.

We cannot address this as part of our Open Source (free) support policy here. If you need specific project support from our side, please reach us by mail at elasticsuite@smile.fr and we'll find out how we could collaborate on a time & material basis.

Best regards

**Comment by PHProDreamy** [comment]
@romainruaud ; I disagree. This environment is Luma based and has no other modules running than ElasticSuite. I read more issues on github here with similar issues. Furthermore, I have already send 5 mails to get a quote to help us fix this, and I don't get any more replies.
