### ISSUE TITLE
Category Product List Preview and Category front end not showing all products

### ISSUE THREAD

**Issue by MaddocksL** [Smile-SA/elasticsuite#2056]
### Preconditions

Magento Version : 2.4.1

ElasticSuite Version : 2.10.3

Environment : Developer

Third party modules :
Custom module for Grouped Products
Custom module for Category Attributes

### Steps to reproduce

1. Add products to category
2. Reindex and clear cache
2. View "Products in Category"

### Expected result

1. Product List Preview and Sorting shows all enabled products or a "show more" button if too many products to show

### Actual result

1. A limited number of products shown in backend as well as front end
![image](https://user-images.githubusercontent.com/5184589/105983375-92d63100-6090-11eb-8187-ae446e747dc1.png)

**Comment by vahonc** [comment]
Hello @MaddocksL,

Could you try to disable or remove (if it's possible) your third-party modules?

If you use third-party modules that may affect our module, we cannot guarantee the correct work of the ElasticSuite module.

Best regards

**Comment by MaddocksL** [comment]
Hi @vahonc, I've disabled all the custom modules and I'm still having the same issue.

**Comment by romainruaud** [comment]
@MaddocksL what is the "visibility" of the non-displayed products ?

I guess they are simple childrens of configurables, so most probably, even if they are "attached" to this category, they are not displayed in front-office if they do not have at least "Catalog" or "Catalog, Search" set for their visibility.

**Comment by MaddocksL** [comment]
Although you have edited you response I'll give some more information about the products as it may help.

They are all grouped products with varying numbers of simple products assigned to them. I have checked 2 different products from the same category where 1 appears and the other doesn't. The settings for:
- Enable Product
- Quantity
- Advanced Inventory > Manage Stock
- Stock Status
- Visibility

All settings match for both the grouped product as well as the simple products.

**Comment by MaddocksL** [comment]
I have found the cause of the issue.

A custom product attribute, text field - decimal number, that was set to filterable had products which were imported with non-numeric characters (e.g. 18+18).

It seems importing skips any checks that are in place when importing to prevent this from happening. Does that make it a bug or a feature request? 😄

**Comment by romainruaud** [comment]
This might be a bug but it should be posted into Magento's github, not ours :) 

You are right, Elasticsearch is strict on field types, and we build the mapping according to the attribute declaration in magento (integer, string, boolean, etc...).

We cannot add control for each field of each product during reindexing since it would hurt performances a lot.

The only thing we can recommend is to be very cautious when importing product data into Magento.

Regards
