### ISSUE TITLE
Get products from Category in custom block and respect Manual Sort Order

### ISSUE THREAD

**Issue by paugnu** [Smile-SA/elasticsuite#2057]
**Is your question related to a problem? Please describe.**
I've created a custom block in my home page I would like to get 12 products from a specific category. Some products of this category have been ordered manually (by checking the manual sort) in the category visual merchandiser.

However, the collection is not ordered with the manual sorted products first, it just retrieves the products in the default position order (like if none of the product had been manual sorted).

In my block, I've used CategoryRepository class to load and get the product collection sorting by 'position'. 

In the category page, everything looks good (manual sorted products are displayed first). This is my code (I know it's very basic, but I would expect it to work anyway):

	public function getProductCollection()
	{
	    $category = $this->categoryRepository->get($this->getData('category'));
	    $collection = $category->getProductCollection();
	    $collection->addAttributeToSort('position');
	    $collection->setPage(1, 12);
	    return $collection;
	}

- How should I use the category repository to correctly return the products in the expected order (same order as displayed in category).

**Comment by romainruaud** [comment]
Hi Pau, long time no see :) How are things doing in Spain ?

It's unlikely that ``$category->getProductCollection()`` will return an Elasticsuite collection.

I'd give a try to something like this : 

```php
/** Use \Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory as a factory to get a "search engine based" collection **/

$collection = $productCollectionFactory->create():
```

Then, you can refer to Richard's instructions on this previous issue : https://github.com/Smile-SA/elasticsuite/issues/1579#issuecomment-545964118

```php
/** This will manage proper sorting by position **/
$sortFilter = ['category.category_id' => $categoryId];
$collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);

/** This will filter based on your category **/
$collection->addCategoryFilter($category);        
```

**Comment by paugnu** [comment]
Hi @romainruaud !

Yes, long time no see! Things are doing great: I live in la campagne with my wife, dogs and petites poules qui me donnent des oeufs tous les jours :), five minutes walk from my work place. Everything is OK and, as you can see, always on Magento :). I would like to take this opportunity to thank you for the work you do with ElasticSuite: we're using it in one of our big projects, and now I can see how powerful it is (I didn't have the chance to appreciate the work you all do when I was in Bordeaux).

Do you still work in Bordeaux Agency? Same place? Did they finish the bridge? :D 

Back to the issue, there is something I must be doing wrong. I'm using the class you mentioned in my constructor, but the block is not rendering. I'm getting this error:
`Impossible to process constructor argument Parameter #2 [ <required> Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory $productCollectionFactory`

This is the way I'm using it (it's in a widget):
```php
<?php

namespace Brildor\Widgets\Block\Widget;

use Magento\Catalog\Api\CategoryRepositoryInterface;
use Magento\Framework\View\Element\Template\Context;
use Magento\Framework\View\Element\Template;
use Magento\CatalogSearch\Model\ResourceModel\Fulltext\CollectionFactory;

use Magento\Widget\Block\BlockInterface;

class CategoryProductsList extends Template implements BlockInterface
{
    protected $_template = "widget/category_product_list.phtml";
    private CategoryRepositoryInterface $categoryRepository;
    private CollectionFactory $productCollectionFactory;

    public function __construct(
        Context $context,
        CategoryRepositoryInterface $categoryRepository,
        CollectionFactory $productCollectionFactory,
        array $data = []
    )
    {
        $this->productCollectionFactory = $productCollectionFactory;
        $this->categoryRepository = $categoryRepository;
        parent::__construct($context, $data);
    }

    public function getProductCollection()
    {
        $collection = $this->productCollectionFactory->create();

        $sortFilter = ['category.category_id' => $this->getData('category')];
        $collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);

        $category = $this->categoryRepository->get($this->getData('category_id'));
        $collection->addCategoryFilter($category);

        $collection->setPage(1, $this->getData('products_count'));

        return $collection;
    }
}
```
Thanks for your help!

**Comment by patricksteenks** [comment]
I'm wondering about this question as well. I get the same error when using this CollectionFactory in my construct function.

**Comment by patricksteenks** [comment]
Ok, when I use `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory $productCollectionFactory,` in my construct, the sort is working!

**Comment by paugnu** [comment]
Hi @patricksteenks,

Could you please share the code you're using for your block? When I use that class it doesn't work for me (manual sorted products are not sorted, it just takes the default order).

**Comment by patricksteenks** [comment]
Yes, off course!

`<?php
    /**
    * Block for best sold products homepage
    * @category    Keytoe
    * @package     Keytoe_Project
    * @author      Keytoe.nl
    */
    
    namespace Keytoe\Project\Block\Cms\Homepage;

    class Bestverkocht extends \Magento\Framework\View\Element\Template  {

        protected $_categoryFactory;
        protected $categoryRepository;
        protected $_category;
        protected $_productCollectionFactory;
        protected $_productloader;

        public function __construct(
            \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory $productCollectionFactory,
            \Magento\Framework\View\Element\Template\Context $context,
            \Magento\Catalog\Model\CategoryFactory $categoryFactory,
            \Magento\Catalog\Model\ProductFactory $_productloader,
            \Magento\Catalog\Model\CategoryRepository $categoryRepository,
            \Keytoe\Project\Helper\Producthelper $productHelper
        ) {
            $this->_productCollectionFactory = $productCollectionFactory;
            $this->_categoryFactory = $categoryFactory;
            $this->bestverkochtCategoryId = "";
            $this->_productloader = $_productloader;
            $this->categoryRepository = $categoryRepository;
            $this->productHelper = $productHelper;

            parent::__construct($context);
        }
        
        /**
         * Get category object
         *
         * @return \Magento\Catalog\Model\Category
         */
        public function getCategory($categoryId) {
            $this->_category = $this->_categoryFactory->create();
            $this->_category->load($categoryId);

            return $this->_category;
        }

        public function getProductCollection($categoryId, $limit = 1000) {
            $category = $this->getCategory($categoryId);
            $collection = $this->_productCollectionFactory->create();
            $collection->addAttributeToSelect('*');
            $collection->addCategoryFilter($category);
            $collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
            $collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
            $sortFilter = ['category.category_id' => $categoryId];
            $collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);
            $collection->setPageSize($limit);
            $collection->setOrder('position','asc');

            return $collection;
        }
    }
    `
Be sure to run the indexer again after saving your category and cleaning the cache!

**Comment by paugnu** [comment]
Thanks a lot @patricksteenks, it work for me! We can close this.

**Comment by patricksteenks** [comment]
👍

Verstuurd vanaf mijn iPhone

**Comment by phphitesh** [comment]
> Yes, off course!
> 
> `<?php /** * Block for best sold products homepage * @category Keytoe * @Package Keytoe_Project * @author Keytoe.nl */
> 
> ```
> namespace Keytoe\Project\Block\Cms\Homepage;
> 
> class Bestverkocht extends \Magento\Framework\View\Element\Template  {
> 
>     protected $_categoryFactory;
>     protected $categoryRepository;
>     protected $_category;
>     protected $_productCollectionFactory;
>     protected $_productloader;
> 
>     public function __construct(
>         \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory $productCollectionFactory,
>         \Magento\Framework\View\Element\Template\Context $context,
>         \Magento\Catalog\Model\CategoryFactory $categoryFactory,
>         \Magento\Catalog\Model\ProductFactory $_productloader,
>         \Magento\Catalog\Model\CategoryRepository $categoryRepository,
>         \Keytoe\Project\Helper\Producthelper $productHelper
>     ) {
>         $this->_productCollectionFactory = $productCollectionFactory;
>         $this->_categoryFactory = $categoryFactory;
>         $this->bestverkochtCategoryId = "";
>         $this->_productloader = $_productloader;
>         $this->categoryRepository = $categoryRepository;
>         $this->productHelper = $productHelper;
> 
>         parent::__construct($context);
>     }
>     
>     /**
>      * Get category object
>      *
>      * @return \Magento\Catalog\Model\Category
>      */
>     public function getCategory($categoryId) {
>         $this->_category = $this->_categoryFactory->create();
>         $this->_category->load($categoryId);
> 
>         return $this->_category;
>     }
> 
>     public function getProductCollection($categoryId, $limit = 1000) {
>         $category = $this->getCategory($categoryId);
>         $collection = $this->_productCollectionFactory->create();
>         $collection->addAttributeToSelect('*');
>         $collection->addCategoryFilter($category);
>         $collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
>         $collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
>         $sortFilter = ['category.category_id' => $categoryId];
>         $collection->addSortFilterParameters('position', 'category.position', 'category', $sortFilter);
>         $collection->setPageSize($limit);
>         $collection->setOrder('position','asc');
> 
>         return $collection;
>     }
> }
> `
> ```
> 
> Be sure to run the indexer again after saving your category and cleaning the cache!

@patricksteenks , is it possible to filter **positions** if it has **NULL** value in above code.
Actually i have some **blacklisted Product** assigned to category and it's loading with collections and I don't want it.

**Comment by patricksteenks** [comment]
You can always filter a collection on product status? Probably the blacklist products have a different status (not visible perhaps) in Magento, on which you can filter with addFieldToFilter()?
