### ISSUE TITLE
Plans for CSP Support?

### ISSUE THREAD

**Issue by PivitParkour94** [Smile-SA/elasticsuite#2058]
**Is your question related to a problem? Please describe.**
When running Magento 2.3.6 with the Magento_CSP module enabled the external resources break because there is no csp_whitelist.xml defined.

Is this something you are planning on adding support for?

Docs: https://devdocs.magento.com/guides/v2.4/extension-dev-guide/security/content-security-policies.html

**Additional context**
Each module in the suite would need a separate CSP whitelist file depending on the resources.
For example the `smile/module-elasticsuite-analytics` module requires the `www.gstatic.com` host to be whitelisted for displaying the chart in the search usage.

Enabling the CSP module is an all or nothing type thing and requires all the resources to be whitelisted accurately, otherwise it is pointless having it enabled at all.

**Comment by romainruaud** [comment]
Yes that's definitely something we should support.

That being said, I think that the analytics module is the only one that is requiring statics from external domains.

**Comment by PivitParkour94** [comment]
Excellent to hear! Thanks for taking the time! I look forward to the new version.
