### ISSUE TITLE
Method unavailable in new Magento

### ISSUE THREAD

**Issue by Zayander** [Smile-SA/elasticsuite#2059]
A isMasterCatalogAvailable() method unavailable in Magento 2.4.2
### Preconditions

elasticsearch:7.6
php-fpm:7.4
nginx
mysql:8.0  

Magento Version : 2.4.2

ElasticSuite Version : 2.10.3

Environment : developer

Third party modules : not used

### Steps to reproduce

1. Go to the product category page 

### Expected result

1. observe products

### Actual result

1. observe PHP notice
![image](https://user-images.githubusercontent.com/25375571/106282394-323e2400-6249-11eb-87f8-fe07a1c7fd85.png)

The isMasterCatalogAvailable method you've used in your /var/www/revolution/src/vendor/smile/module-elasticsuite-shared-catalog/Plugin/Catalog/Model/ResourceModel/Product/Fulltext/CollectionPlugin.php dos not exists in Magento Version : 2.4.2

Thanks
Aleksandr

**Comment by romainruaud** [comment]
Hi @Zayander 

This issue should be moved here : https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog

**Comment by pusachev** [comment]
HI @romainruaud 

Thank's for answer I will transfer this issue to  https://github.com/Smile-SA/magento2-module-elasticsuite-shared-catalog

Cheers
