### ISSUE TITLE
Filter product collection by custom attribute

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#2060]
Hello,

We are using magento version 2.3.5 with smile elasticsuite module and we have 2 stores.

So whenever "Catalog Search" indexer performed, elsticsuite module created 2 Indices(according to look at Admin->Elasticsuite->System->Indices) for each store view that is fine and understandable.

We have created one custom attribute(sellable) with "Yes/No" type and value assign on second store level.

What I want to achieve is like whenever elastic suite module try to create product indices for second store that time it should filter only products which has set value = "Yes" so frontend showing only those products in category. or is there any other way that we can showing only products in frontend which has sellable=Yes.

Can you please help us how can I achieve it?

Thanks in advance,
David Andersson

**Comment by vahonc** [comment]
Hello @davidandersson1 

You could add a new filter model based on your custom attribute. Here's https://github.com/vahonc/elasticsuite/commit/099e3c397d262ab2f8e9fdb1784b48152ad9fcfc a code that can be useful for understanding the logic of such kind of solution.

Best regards
