### ISSUE TITLE
Pinning Products to Top of Search Results Not Working.

### ISSUE THREAD

**Issue by ganesh-ecsion** [Smile-SA/elasticsuite#2061]
The merchandising functionality for search results doesn't seem to be working. For the search term 'chest freezer' I have an item pinned to the top of search results, but it's not showing on the front end.

### Preconditions

Magento Version : 2.3.3-p1 EE

ElasticSuite Version : 2.8.0

Environment : Developer

Third party modules : Amasty Improved Sorting

### Steps to reproduce

1. Go to Admin dashboard -> marketing -> Search term -> Edit term -> Merchandise . You got a product list that will be returned by this search query.
2. Did manually sort some products and save them.
3. Magento's Back-Office result does not display exactly the same on frontend search page. 

### Expected result

1. Whatever sorting order we have applied to the products for a search term on Back-Office, the Same sorting order should appear on the frontend after search. Working properly for category merchandise sort but not working for search term merchandising.

### Actual result

1. Merchandiser:
![image](https://user-images.githubusercontent.com/33414084/106630056-7d399d80-65a1-11eb-849f-f1db80aefd26.png)

2. Front End Search Results:

![image](https://user-images.githubusercontent.com/33414084/106630082-8296e800-65a1-11eb-9343-2ce4b571d3e7.png)

**Comment by romainruaud** [comment]
HI @ganesh-ecsion 

The pinned products will be displayed on their pinned positions only when using "Relevance" as the sorting in Front-Office, which does not appear to be the case on your screenshot.

So it looks to be normal for me. 

Think about it if you change the Sort By to use "Price", customers will expect to have the lowest price first, not products that have been pinned to the first position.

Can you check it's working as expected when you change "Sort By" to "Relevance" in your front office ?

Regards
