### ISSUE TITLE
Price Slider Tranalation

### ISSUE THREAD

**Issue by gferreyra1** [Smile-SA/elasticsuite#2064]
How can I translate the text showed in the image below ?

![Captura de pantalla 2021-02-07 a las 22 50 23](https://user-images.githubusercontent.com/35316379/107167279-3d0a5e80-6997-11eb-86df-1dd0866d2093.png)

Regards

**Comment by vahonc** [comment]
Hello @gferreyra1,

You can look at the source of this line here: https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Block/Navigation/Renderer/Slider.php#L139

And here's a translation for the US language: https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/i18n/en_US.csv#L7

So you could quite easily change text whatever you want at this CSV file or add translation to any different files with localization like this: `"<%- count %> products","<%- count %> your text"`

Don't forget to clear the cache ;)

Best regards

**Comment by gferreyra1** [comment]
thanks @vahonc I've modified the source and re build the child theme and it worked fine.

Best regards
