### ISSUE TITLE
Merchandiser Manual Sort Issue With New Products

### ISSUE THREAD

**Issue by markloganuk** [Smile-SA/elasticsuite#2065]
Hi

I have an issue with the merchandiser functionality. When we set all products in a category to Manual and we move them to positions that look good, any new products are automatically added to the bottom of the categories.  When we have a category with lots of pages, this is an issue because the new products are beneath everything.

Is there a way to set it so the new products go to the top of the category when you have set it to manual sort? It would be easier for someone to look at the category and identify products that then needed sorting. Having new products go to the bottom is not good for conversion rate.

We're using Magento 2.3.3 Enterprise

Thanks
Mark

**Comment by romainruaud** [comment]
Well that's by design, manually pinned product are supposed to stay at the position that was given to them.

You could implement it as an optimizer rule following this old proposal : https://github.com/Smile-SA/elasticsuite/pull/595#issue-149569496
