### ISSUE TITLE
Search engine randomly switch back to MYSQL

### ISSUE THREAD

**Issue by mustanguy69** [Smile-SA/elasticsuite#2072]
Hello,
Thanks for a really good module !

There is an issue I have and I really cant figure out what's happening !

Sometimes when editing products/category or others action in the admin the search engine is automatically switch back to MYSQL and so the site crash on category pages + search ...

The weird thing is when it happens it look like the indexer are removed from the table "mview_state" ...
Also when it happens the page "Index managment" in the admin is empty.

The only solution to get it back is to flush the cache (sometimes 2 times) and magically it came back

Magento Version : 2.3.3 CE

ElasticSuite Version :~2.8.0

Environment : Production

Error I could catch into exception.log : 

```
main.CRITICAL: elasticsuite_categories_fulltext view does not exist. {"exception":"[object] (InvalidArgumentException(code: 0): elasticsuite_categories_fulltext view does not exist. at /var/www/vhosts/****/htdocs/releases/20210211121420/vendor/magento/framework/Mview/View.php:182)"} []

```
![image](https://user-images.githubusercontent.com/56423123/107755898-5145b700-6d1b-11eb-9cfd-e27cf5f61ad7.png)

And after flushing cache : 

![image](https://user-images.githubusercontent.com/56423123/107756038-80f4bf00-6d1b-11eb-8363-6d538f4c2b78.png)

Any help would be much appreciated ! Thanks :smiley:

**Comment by romainruaud** [comment]
hi @mustanguy69 

it's been some time since you submitted this, did you make any progress on that ?

Regards
