### ISSUE TITLE
Search result issue

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2075]
Hello,

I have issue with search result when using search bar.

All results are showing in one page.

Can be related to Smile module?

Thank you in advance.

**Comment by vahonc** [comment]
Hello @achatpc,

At this moment, according to the description of your problem, we can't suggest you any solution. We need more details about your case, namely the version of the Magento and ElasticSuite (screenshots, logs, etc).

You could try to uninstall/remove, if it's possible, the ElasticSuite module and come back to Elasticsearch7 in the settings Search Engine in Magento BO and check if your problems still occur.

Best regards

**Comment by achatpc** [comment]
Fixed with:

https://magento.stackexchange.com/questions/326814/magento-2-pagination-not-working-on-search-results-porto-theme
