### ISSUE TITLE
Products List Preview and Sorting products are missing.

### ISSUE THREAD

**Issue by nagarajuk12** [Smile-SA/elasticsuite#2077]
### Preconditions

Magento Version : Magento/2.3 (B2B)

ElasticSuite Version : 6.8.0

Environment :  Development.

Third party modules : No

### Steps to reproduce

1. There are 16 products assigned to one category. But in the Products List Preview and Sorting showing only 9 products.

4. All products are simple & configurable with catalog search & assigned to the same category and website.

### Expected result

1. In the products list preview and sorting it should display 16 products.

### Actual result

1. https://prnt.sc/zmfq7u
2. https://prnt.sc/zmfuk7
3. https://drive.google.com/file/d/1Qns8-rfmPAhNuuTgA5WDUAagVyR5-vcu/view

Could you please advise how to fix this issue.

**Comment by KZNcode** [comment]
We're having an issue that may relate to this as well... 

When we do a 'select all' the preview section completely disappears, and there's a serialization error after hitting save...

Selecting each product 1 by 1 works as expected... But as soon as you hit "select all" at any point of the selection process, the same above issue takes place.

**Comment by romainruaud** [comment]
@KZNcode please fill a new issue, this seems to be different than OP's thread.

@KnK123 it looks like you have product without prices, if that's the case, they won't be indexed in the Magento legacy stock index, which may cause them to not appear in frontend (and also not on the BO preview, which reflects exactly the frontend).

What is your configuration about displaying out of stock products in frontend ? If your store is configured to not display them, that can also cause them to not appear in the preview.

Regards

**Comment by KnK123** [comment]
@romainruaud  Thanks for your reply. Actually those are configurable products. Hence price is zero.

**Comment by KnK123** [comment]
@KZNcode @romainruaud Could you please advise how to resolve this issue?

**Comment by rameshre-kensium** [comment]
@romainruaud  Any update on this?

**Comment by kerlama** [comment]
I have the same issue ... latest smile module and magento 2.4.1 and 2.4.2

**Comment by KZNcode** [comment]
> I have the same issue ... latest smile module and magento 2.4.1 and 2.4.2
> 
> EDIT: I changed alias name and did full reindex and all products appeared.

@kerlama tried doing the same; didn't work in our case.

**Comment by KnK123** [comment]
> I have the same issue ... latest smile module and magento 2.4.1 and 2.4.2
> 
> EDIT: I changed alias name and did full reindex and all products appeared.

@kerlama I have tried the same from my end but did not work.

**Comment by KnK123** [comment]
Hi Team,

Can any one help me on this issue please?

Thanks

**Comment by romainruaud** [comment]
Maybe could it be related to #2093 or #2099 ?

**Comment by br1luca** [comment]
Hello,
I have the same issue. Some weeks ago i opened a ticket to report the same problem, currently i cannot fint it.
My Magento version is 2.3.5 and this is the list of Smile modules i'm running on that istance.


| module                              | schema_version | data_version |
| --------  | ------------------- | --------------------- |
| Smile_ElasticsuiteAdminNotification | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteAnalytics         | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteCatalog           | 1.5.1          | 1.5.1        |
| Smile_ElasticsuiteCatalogOptimizer  | 1.2.0          | 1.2.0        |
| Smile_ElasticsuiteCatalogRule       | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteCms               | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteCore              | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteRetailer          | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteSwatches          | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteThesaurus         | 1.0.0          | 1.0.0        |
| Smile_ElasticsuiteTracker           | 1.2.0          | 1.2.0        |
| Smile_ElasticsuiteVirtualCategory   | 1.4.1          | 1.4.1        |
| Smile_Map                           | 1.0.0          | 1.0.0        |
| Smile_Retailer                      | 1.1.0          | 1.1.0        |
| Smile_Seller                        | 1.1.0          | 1.1.0        |
| Smile_StoreLocator                  | 2.0.0          | 2.0.0        |


@thampe I tried your fix from https://github.com/Smile-SA/elasticsuite/pull/2147 but i think don't work.
Could you share some information about the fix, maybe i could help?

**Comment by romainruaud** [comment]
Is this one still relevant ?

**Comment by rameshre-kensium** [comment]
Hi Roman,

No. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
