### ISSUE TITLE
Warning message: Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget.

### ISSUE THREAD

**Issue by adavia** [Smile-SA/elasticsuite#2080]
After installing elasticsuit 2.10.3 i am facing the following warning message in category pages on my Magento 2.4.1 local environment
"Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site."
I am afraid this might cause performance issue.

### Preconditions

Local environment.

Magento Version : Magento Open Source 2.4.1

ElasticSuite Version : 2.10.3

Environment : Developer mode

Third party modules : 
Social Login (Aheadworks)
SMTP (Mageplaza)

### Steps to reproduce

1. Install elasticsuit 2.10.3
2. Setup module. Reindex and flushed cache
3. Navigate to category pages

### Expected result

1. Everything working as expected. No console errors/warnings

### Actual result

1. [Screenshot, logs]
2. Everything is working fine, but the following warning is showing up
![image](https://user-images.githubusercontent.com/2234616/108210663-d35a2500-70f9-11eb-8d0f-085d82f30a54.png)

Not entirely sure but maybe range-slider-widget.js is making use of 'jquery/ui' and causing the warning
![image](https://user-images.githubusercontent.com/2234616/108217700-e670f300-7101-11eb-9cd6-ab1aefacb959.png)

**Comment by vahonc** [comment]
Hello @adavia,

Are you using some custom theme or default Luma theme? If so, could you try switch to the default theme and check it again?

BR,
Vadym

**Comment by Quazz** [comment]
The PR that fixes this is merged and I presume it will be in the next version.

https://github.com/Smile-SA/elasticsuite/pull/1927

**Comment by adavia** [comment]
Thanks @Quazz
