### ISSUE TITLE
Product Query Interface is not found while setup upgrade

### ISSUE THREAD

**Issue by purna12** [Smile-SA/elasticsuite#2086]
sudo php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 81.0 MiBPHP Fatal error:  Interface 'Magento\CatalogGraphQl\Model\Resolver\Products\Query\ProductQueryInterface' not found in /app/code/Smile/ElasticsuiteCatalogGraphQl/Model/Resolver/Products/Query/Search.php on line 34

Fatal error: Interface 'Magento\CatalogGraphQl\Model\Resolver\Products\Query\ProductQueryInterface' not found in /app/code/Smile/ElasticsuiteCatalogGraphQl/Model/Resolver/Products/Query/Search.php on line 34

**Comment by vahonc** [comment]
Hello @purna12,

Could you please provide more details about your environment such as Magento and ElasticSuite versions? Did you additional changes in the code or install some specific third-party modules, etc?

Did you try to clean your cache before compilation or run next command:
`rm -rf var/cache/* var/page_cache/* generated/code/*`

BR,
Vadym
