### ISSUE TITLE
autocomplete isn't working

### ISSUE THREAD

**Issue by dbrzezicki** [Smile-SA/elasticsuite#2087]
Magento: 2.4.1 CE
ElasticSuite: 2.10.3
Theme: Porto

I have a problem with the search because autocomplete isn't working. Any suggestions?

![search](https://user-images.githubusercontent.com/79701354/109304734-f80e7500-783c-11eb-9949-918a8b0c83dc.png)

I did:

In the file :
/app/design/frontend/Smartwave/porto/Magento_CatalogSearch/web/css/source/_module.less

Replace old with new variables:
@autocomplete__background-color
@autocomplete__border
@autocomplete-item__border
@autocomplete-item__hover__color
@autocomplete-item-amount__color

change in: app/design/frontend/Smartwave/porto/Smartwave_Porto/layout/default.xml

                <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Smile_ElasticsuiteCore::search/form.mini.phtml">
                    <arguments>
                        <argument name="rendererList" xsi:type="array">
                            <item name="term" xsi:type="array">
                                <item name="title" xsi:type="string" translate="true">Search terms</item>
                                <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                            </item>
                            <item name="product" xsi:type="array">
                                <item name="title" xsi:type="string" translate="true">Products</item>
                                <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
                            </item>
                            <item name="category" xsi:type="array">
                                <item name="title" xsi:type="string" translate="true">Categories</item>
                                <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
                            </item>
                            <item name="product_attribute" xsi:type="array">
                                <item name="title" xsi:type="string" translate="true">Attributes</item>
                                <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product-attribute</item>
                                <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
                            </item>
                        </argument>
                    </arguments>
                </block>      

copy files from: vendor/smile/elasticsuite/src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml 
to: app/design/frontend/Smartwave/porto/Smile_ElasticsuiteCore/templates/search/form.mini.phtml

bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy
bin/magento c:c
bin/magento c:f
bin/magento index:reindex

**Comment by vahonc** [comment]
Hello @dbrzezicki,

As I can see you're using a custom theme, we couldn't guarantee the correct work of our modules in this case. 

You could try switch to the default theme (Luma) and check if this problem is occurring.

Also, check logs and the output from Console/Dev tools of your browser, maybe you will find some errors which help you to understand where is your problem.

BR,
Vadym
