### ISSUE TITLE
Price slider not friendly in mobile

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2090]
Price slider is not friendly in mobile, drag event is not working in it, need to click it to make chnages

**Comment by romainruaud** [comment]
Duplicate of #1919 but we definitely have to adress this one

**Comment by PixelT** [comment]
Did someone check this drag event on mobile?
It seems that it doesn't work...

**Comment by vahonc** [comment]
Hello @PixelT

Which version of the ES you are using?

Have you checked it on a real website and real mobile? 

Have you clear/flush the cache and rebuild static content on your website?

BR,
Vadym

**Comment by PixelT** [comment]
I was checking it on the newest version - `2.10.5` on blank and luma theme - in both cases, I can't drag on slider - the `jquery.ui.touch-punch.min.js` file is loaded properly.
Yes I was testing on real website/devices.

**Comment by vahonc** [comment]
Hello @PixelT,

We've updated the ES module on our demo site to the latest version and looks like it works as expected, here's an [example](http://demo.magento-elastic-suite.io/index.php/men/tops-men/jackets-men.html).

Maybe there are some devices compatibility or cache issues, I've tested it on an Android device with a Chrome browser.

Could you check how it works on our demo site from your device? 

And also, please provide your test condition, like OS, browser, etc.

BR,
Vadym
