### ISSUE TITLE
"Configuration" type cache not invalidated after saving product attribute

### ISSUE THREAD

**Issue by sky-hub** [Smile-SA/elasticsuite#2101]
### Preconditions

Magento Version : 2.4.2

ElasticSuite Version : 2.10.3

Environment : All

Third party modules : None

### Steps to reproduce

1. Create Magento attribute of backend type decimal (can be any type as long as it can be used as "Filterable"), set "Use in Layered Navigation" to "No"
2. Assign attribute to some attribute set and create products using this attribute
3. Reindex "catalogsearch_fulltext" (I think this can be optional as long as there is an Elastic Search index)
4. Visit category page where products have been assigned. Will trigger logic in `\Smile\ElasticsuiteCore\Index\Indices\Config::getDynamicFields`
5. Go to Magento admin and set "Use in Layered Navigation" to "Yes" for the created attribute
6. Reindex "catalogsearch_fulltext"
7. Visit again category page where products have been assigned. Because the attribute was indexed in ES, it will be returned by the facet data, therefore it will be shown in filters sidebar.
8. Use the created attribute to filter the product collection

### Expected result

1. Category page should be rendered and product listing filtered by the selected attributes

### Actual result

1. Because the filterable attributes are cached and the cache was not refreshed the following error will be thrown `Field {$name} does not exists in mapping` from `\Smile\ElasticsuiteCore\Index\Mapping::getField`

### Solution
1. Use the "save_after" event on attributes (or similar solution) and invalidate the "Configuration" cache.

**Comment by sky-hub** [comment]
PS: I can create a PR with a fix for this issue when it gets validated.

**Comment by sky-hub** [comment]
@romainruaud , can I assume that consider this a legitimate issue and I can create a PR with a fix?

**Comment by romainruaud** [comment]
yes sure, feel free !

**Comment by romainruaud** [comment]
I thought I made an answer on this one previously.

Beware, that's related to https://github.com/Smile-SA/elasticsuite/issues/1689

Cleaning the cache will be enough **if you reindex after**, otherwise, you will have the field in the "PHP Mapping" (Elasticsuite will be aware of the field) but not in the Elasticsearch index, that may also lead to other issues like in #1689.

Changing configuration for an attribute (sortable, filterable, searchable) should also trigger an invalidation of the Catalogsearch index.

**Comment by sky-hub** [comment]
@romainruaud , here is the PR that invalidates "Configuration" cache and FULLTEXT index on attribute save https://github.com/Smile-SA/elasticsuite/pull/2109

Even though there is already an afterSave plugin for the product attribute model I have used the observer to limit this functionality to action performed from admihtml area only. As you mentioned in some comments I think for other areas it would be best for the developers to choose when they want to clear cache or reindex.

If you have any comments let's discuss them and see what can be improved here.

**Comment by sky-hub** [comment]
@romainruaud , upon futher investigation I have discovered that Magento already invalidating the FULLTEXT index in `\Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Attribute::afterSave`, so since that part is covered and I removed it from the PR.

**Comment by sky-hub** [comment]
@romainruaud , final PR for the problem described in this issue and in https://github.com/Smile-SA/elasticsuite/issues/1689 are here: https://github.com/Smile-SA/elasticsuite/pull/2109/commits/e393f4ffdb24253d787474ea1ea36a76f23275bf

The main problem is that when the reindex is performed and the config cache for \Smile\ElasticsuiteCore\Index\Indices\Config::CACHE_ID is not cleared, when changing attribute data, the reindex process will use an outdated configuration from cache.

As I have mentioned in the previous comment Magento already handles index invalidation on attribute change, BUT there is still the discussion about index invalidation when making the attribute "SORTABLE" which I would like your opinion on it.

**Comment by romainruaud** [comment]
I merged your PR. thank you for contributing.

Turns out that the issue appearing in #1689 was due to the cache not being purged.

With your PR, the frontend no longer throw an error when an attribute is set to be sortable.

However, the sorting does not work until the search index is rebuilt, that's why I also added PR #2134 

Regards
