### ISSUE TITLE
Search result not show 

### ISSUE THREAD

**Issue by toyarmys** [Smile-SA/elasticsuite#2102]
When I call getBlockHtml('top.search') in my custom template, it show the search bar as well. But when I started to search, it not show the result as expect. Not show error in console log, though. Please have a look on it. Thanks.

**Comment by vahonc** [comment]
Hello @toyarmys,

Could you please add more details and explain what you want to do, what results are you expected, etc? Also, It will be useful if you added some screenshots for a better understanding of this issue.

BR,
Vadym
