### ISSUE TITLE
Virtual categories for elasticsearch suite 

### ISSUE THREAD

**Issue by ioweb-gr** [Smile-SA/elasticsuite#2105]
- Is ElasticSuite able to build virtual categories based on a specific attribute which differs per website? 

For example I have an attribute `MyAttribute` for which Product X has a value of 

20% in Website 1  and 
40% in Website 2

I create a virtual category for which I would like to show products where MyAttribute is 20%. 

I would expect Product X to show up in Website 1 but not in Website 2. 

Would something like this be possible?

**Comment by romainruaud** [comment]
Hi @ioweb-gr 

that should be working as intended as soon as your attribute is scoped properly.

Elasticsuite will index your product with 20% for website 1 index, and 40% for website 2 index. Even if the virtual category condition is the same for both website, the result shall differ according to product data.

Don't hesitate to let us know if this did work for you.
