### ISSUE TITLE
Too Many Indices with Status as Ghots

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2106]
Magento Version : 2.4.1

I see to many indices mostly with status as GHOST what is this for , please help me with same, screenshot as below

![image](https://user-images.githubusercontent.com/63009790/114292155-24f3b000-9aaa-11eb-9b5e-4ded9f4a09ec.png)

**Comment by romainruaud** [comment]
Ghost indices indicates that the fulltext indexing process did not end well.

You should check in the magento logs (exception.log or system.log) to see if there are any logged errors during re-indexing. Or maybe check also the elasticsearch server logs.

You can safely remove these indices, they are not used by the engine.
