### ISSUE TITLE
Sometime Suddenly "default_catalog_product_*" ES indices size reduced and frontend without products

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#2107]
Sometime elastic product indices size reduced itself and front-end without any products so we lost the sales :(

Magento Version : 2.3.5
ElasticSuite Version : ~2.9.0
Environment : Production
We have 2 store views
We are using separate host for ES server.
We have around 400k products and 650 categories.

According to our catalog, sometime we have "default_catalog_product_" size is 700 MB or sometime 1 GB and suddenly its reduced to some bytes, let's say 650 bytes or 1 or 2 MB. this is happened for us 2 times in last 2 weeks.

If we perform catalog search index then again ES indices size proper and products appear to fronted but its really risky and we are looking for permanent solution of this issue.

Third party modules :  'Amasty_BannersLite' ,'Amasty_Base' ,'Amasty_Conditions' ,'Amasty_CommonTests' ,'Amasty_CommonRules','Amasty_CronScheduleList','Amasty_CrossLinks','Amasty_CustomerLogin','Amasty_Feed','Amasty_Geoip','Amasty_GdprCookie',
'Amasty_Gdpr','Amasty_Mage24Fix','Amasty_Meta','Amasty_ProductAttachment','Amasty_ProductAttachmentApi','Amasty_Promo','Amasty_Rgrid','Amasty_Rma','Amasty_SalesRuleWizard','Amasty_SeoHtmlSitemap','Amasty_SeoToolKit',
'Amasty_SeoSingleUrl','Amasty_SeoRichData','Amasty_ShippingArea','Amasty_ShippingTableRates','Amasty_Shiprestriction','Amasty_ShopbyBase','Amasty_ShopbyBrand','Amasty_ShopbyRoot','Amasty_XmlSitemap'

We noticed, sometimes below error generating in magento exception log and system.log
main.CRITICAL: Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67 

Honestly, We are not aware exactly when and why indices size reduced itself except above error! and do not know the reason behind above exception error.

Can you please help for the same! Please let me know if you need any other assistance from my end!

Thanks,
David Andersson

**Comment by davidandersson1** [comment]
Hello,

Still we are facing below critical error in exception.log

main.CRITICAL: Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67

Can you please suggest fix for this error?

Thanks in advance,
David Andersson

**Comment by Quazz** [comment]
For your first problem, I don't remember exactly, but I seem to recall this being a Magento core bug. 

The second one was a problem I used to struggle with for a long time until one day it was automagically gone.  (though I strongly suspect it has to do with a badly written plugin/interceptor somewhere in your code)

**Comment by davidandersson1** [comment]
Hi @Quazz Thanks a lot for your reply

Regarding my first issue, it was due to less heap size on elasticsearch server, we extended it from 4 GB to 7 GB but now we are not facing the same issue within last 15 days, otherwise every 3-4 days we faced same issue!

Regarding second one, as you suggested plugin/interceptor somewhere in your code, that I understood but any idea where you think Core class plugin responsible for this issue, because at this time, lots of custom + 3rd party modules so ofcourse, lots of plugin use in code so very hard to find out the exact plugin so any guess for core class which stand with plugin and its possible cause of this issue?

**Comment by Quazz** [comment]
> Hi @Quazz Thanks a lot for your reply
> 
> Regarding my first issue, it was due to less heap size on elasticsearch server, we extended it from 4 GB to 7 GB but now we are not facing the same issue within last 15 days, otherwise every 3-4 days we faced same issue!
> 
> Regarding second one, as you suggested plugin/interceptor somewhere in your code, that I understood but any idea where you think Core class plugin responsible for this issue, because at this time, lots of custom + 3rd party modules so ofcourse, lots of plugin use in code so very hard to find out the exact plugin so any guess for core class which stand with plugin and its possible cause of this issue?

I don't believe it was a core plugin that was the issue (given that the module is tested with core Magento and works fine). 

It's really hard to track down a buggy plugin due to their nature, so for the most part it ends up coming down to trial and error which is fairly frustrating. 

You could try https://github.com/creatuity/magento2-interceptors using that. Either the problem magically disappears due to interceptors being generated differently or it will throw an error in your face that might point you in the right direction.  (though I did run into a core Magento 2 plugin that was incorrectly written and caused issues with this module: see https://github.com/creatuity/magento2-interceptors/issues/6 )

**Comment by romainruaud** [comment]
@davidandersson1 any update on this one ?

**Comment by davidandersson1** [comment]
Hi @romainruaud 

Sorry but i do not have any clue for issue main.CRITICAL: Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Helper/Rule.php on line 67

**Comment by romainruaud** [comment]
2 years old issue -> I close.

Feel free to open a new one if needed.

Regards
