### ISSUE TITLE
Connect to external password protected Elastic node on AWS

### ISSUE THREAD

**Issue by Nielex** [Smile-SA/elasticsuite#211]
I'm testing with a external ElasticSearch node on AWS. Now I'm trying to connect to it from Magento2, but the node needs basic password authentication. 

How do I configure my credentials in the Smile Module so I'can use this node?

**Comment by afoucret** [comment]
Currently it is not supported by ElasticSuite.
My advice would be to not use authentication for ES and to rely on the VPC feature of AWS instead in order to secure your cluster.

**Comment by afoucret** [comment]
I don't close the issue since we will implement it sometime.
Additionally, it will allow to handle clusters hosted by Elastic (Elastic Cloud offer).

**Comment by Nielex** [comment]
I could connect to AWS with basic authenthication in the url:

http://user:password@url:port

That works fine. The issue I had, was that the ElasticSearch instance I used was running on ElasticSearch 5. With ElasticSearch 5, I got an error on the handler when I'm running the indexer:

"No handler found for uri [/default_catalog_category_20161121_111244] and method [POST]"

I thought the authentication was trowing this error, but its the ElasticSearch version. SO my conclusion is that ElasticSuite isn't compatible with ElasticSearch 5. Is compatibility with version 5 planned in the future?

**Comment by Nielex** [comment]
@afoucret 

I did a bit of work this afternoon and I think I build the basic password authentication with configurable options in the system config. It works for my Elasticsearch instance. I'll create a pull request if your interested.

**Comment by afoucret** [comment]
Hi @Nielex,

ES 5.x is planned, but we have to work on the module compatibility. One of the most difficult part of the job is to update the ES PHP Client to the 5.x version. While it is not a huge problem for the community edition of Magento, the enterprise one requires a 2.x client. As we want provide support for Magento EE, we will need to find a way. We will have to work with Magento team in order to achieve this.

**Comment by Nielex** [comment]
Hi @afoucret,

Tnx for the update. I'm looking forward to Elastic 5 support. But no hurry, Elastic 2.4 is still working fine for me. And I love this module, it still is getting better and better.

**Comment by afoucret** [comment]
PR #218 have been merged into 2.3.x and master branches.

@Nielex : I refactored the code a little. You can test it again with my modification. If everything goes fine, we will close this issue.

Thx for the contrib.

**Comment by afoucret** [comment]
FYI : will be part of the upcoming 2.3.0 stable release.

**Comment by afoucret** [comment]
@Nielex : any feedback about this one ?

**Comment by Nielex** [comment]
Hi @afoucret,

Sorry for my late response. I didn't had to chance to response earlier. But your refactoring was very nice, I learned a lot from it. And it works fine, so I'm looking forward to next 2.3.0 release to see this implemented.

Tnx for your quick review on my pull request. I'm looking forward to contribute more in the future.

**Comment by afoucret** [comment]
Hi @Nielex,

Glad to see it have worked. Once again thank you for the contrib.
