### ISSUE TITLE
Virtual Category not working when using custom product attribute text field

### ISSUE THREAD

**Issue by trebb0r** [Smile-SA/elasticsuite#2110]
### Preconditions
I'm using Magento Commerce 2.3.5-p2 and using Smile Elastic Suite version 2.9.4 including the latest version of the Shared Catalog and Quick Order module in production mode. Only one website and one store view is available.

### Steps to reproduce
1. Login to backend
2. Go to Stores > Product > Attributes
3. Create a custom Product Attribute or use an existing one with type text field
4. Add Product Attribute to Attribute Set
5. Edit a Product and input a value on the custom Product Attribute
6. Save the Product
7. Go to Products > Categories
8. Select an existing Category
9. Enable Virtual Category
10. Set rule on custom Product Attribute contains the value you input at step 5
11. Wait for preview 

### Expected result
1. The product in step 5 should be previewed.

### Actual result
1. No preview is given, except a warning about multi store view (also when saved anyway, no products are shown on frontend).

Any ideas why this is happening? When I use as custom Product Attribute that has a dropdown or multiselect, the preview works.

**Comment by vahonc** [comment]
Hello @trebb0r,

I've tried to reproduce this issue according to your steps on my local environment with Magento 2.3.5p2 EE and ES 2.9.3.
And I didn't notice any problems with previewing for selected/assigned products.

So I've created a custom Product Attribute with a type Text Field and named it External SKU. The only thing that I did additional to your steps is clear cache after step 6.

Here's what I have after setting up a rule on custom Product Attribute (i.e. External SKU) which contains the value that was inputted at step 5 (i.e. 24-WB02-External).

![Screenshot from 2021-04-15 17-19-33](https://user-images.githubusercontent.com/67791361/114886644-61a80a00-9e10-11eb-89dd-661b34b7b713.png)

As you can see I've success previewing a product which I expected to see.

So try to clear cache and/or do reindex before setting up a rule for your virtual category.

Do not hesitate to contact if there is anything else I can help you

BR,
Vadym

**Comment by StevenGuapaBV** [comment]
Hi Vadym,

When I checked this locally (also M2 2.3.5p2 EE and ES 2.9.3) I encountered the same problem as @trebb0r. I run MySql8, could that be a difference? I noticed while debugging when I added the option 'is one of' '()' tot the string input operator I got the results I expected. While using 'contains' '{}' I never got a result. 

Clearing cache en reindexing did not help while setting up virtual categories. 

With kind regards,
Steven

**Comment by vahonc** [comment]
Hello @StevenGuapaBV,

Could you provide more details about your steps to reproducing if this issue? Also, you could enable logging of ES queries in Stores > Configuration > Elasticsuite > Enable Debug Mode. The queries will be logged into the `system.log` and you can copy/paste these queries here. Perpahs, it could be a mapping issue or some settings of your attributes, so please check your configs.

BR,
Vadym

**Comment by vahonc** [comment]
@trebb0r, @StevenGuapaBV is this issue still relevant for you?
