### ISSUE TITLE
GraphQL pagination not working

### ISSUE THREAD

**Issue by bheptinh** [Smile-SA/elasticsuite#2112]
### Preconditions

Looks like graphql request return empty `items` array when explicitly passed `currentPage` property.
I've created MR (#1965) also you can see more information there and I'm facing with that issue again on latest Magento & ElasticSuite versions

Magento Version : 2.4.2

ElasticSuite Version : 2.10.3

Environment : Developer & Production

Third party modules : none

### Steps to reproduce

1. just make a qraphql request 
```graphql
query {
  products(search: "yoga", currentPage: 1, pageSize: 5) {
    items {
      name
    }
    page_info {
      current_page
      page_size
      total_pages
    }
    total_count
  }
}
```

### Expected result

1. `items` array from response shouldn't be empty

### Actual result

1. empty `items` array

**Comment by deadman619** [comment]
I'm having this issue as well. I get all the items on page 1, but it seems like there's an offset that gets set on every page after 1, which is a problem because the query that forms already has the IDs of the products.
```
SELECT `e`.*, IF(at_status.value_id > 0, at_status.value, at_status_default.value) AS `status`, IF(at_visibility.value_id > 0, at_visibility.value, at_visibility_default.value) AS `visibility` FROM `catalog_product_entity` AS `e`
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1
 INNER JOIN `catalog_product_entity_int` AS `at_status_default` ON (`at_status_default`.`entity_id` = `e`.`entity_id`) AND (`at_status_default`.`attribute_id` = '97') AND `at_status_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '97') AND (`at_status`.`store_id` = 1)
 INNER JOIN `catalog_product_entity_int` AS `at_visibility_default` ON (`at_visibility_default`.`entity_id` = `e`.`entity_id`) AND (`at_visibility_default`.`attribute_id` = '99') AND `at_visibility_default`.`store_id` = 0
 LEFT JOIN `catalog_product_entity_int` AS `at_visibility` ON (`at_visibility`.`entity_id` = `e`.`entity_id`) AND (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 1) WHERE (e.entity_id IN (2016, 2009, 2003)) AND (stock_status_index.stock_status=1) ORDER BY FIELD(e.entity_id,2016,2009,2003)
```

**Comment by romainruaud** [comment]
Well this one is a bit surprising.

I do have some environments where it's working, either page 1 or page 2.

Some others, page 1 is ok, but switching to page 2 gives me empty results.

See, Magento 2.4.1 : 

![image](https://user-images.githubusercontent.com/15340849/115046266-916e1500-9ed7-11eb-8ea6-f8d4afebd7f9.png)
![image](https://user-images.githubusercontent.com/15340849/115046288-959a3280-9ed7-11eb-9bcd-d8e6f6bc4cb8.png)

On a Magento 2.4.2 EE I do have the bug : 

![image](https://user-images.githubusercontent.com/15340849/115046428-b82c4b80-9ed7-11eb-9c0b-cca786d5a768.png)
![image](https://user-images.githubusercontent.com/15340849/115046476-caa68500-9ed7-11eb-97f9-05b95833c276.png)

**Comment by romainruaud** [comment]
`total_pages` seems to be broken, I'll try to investigate

**Comment by romainruaud** [comment]
Okay, I upgraded the environment where it was working (2.4.1) to 2.4.2 and now it has the bug too.

I'll try to find more

**Comment by romainruaud** [comment]
PR #2117 is a WIP fix for this issue.

It's WIP because `total_pages` is still wrong with it, but items are properly returned from pages to pages 
Can you guys test it ?

**Comment by deadman619** [comment]
I tested it out and it works. Thank you.

**Comment by tim-breitenstein-it** [comment]
I have this Bug too.

When will there be a new version which fixes this bug?

**Comment by romainruaud** [comment]
we'll probably release a new version this week containing this fix.

**Comment by romainruaud** [comment]
I close since this was fixed and should be released asap
