### ISSUE TITLE
ElasticSuite works fine, but breaks bin/magento setup:config:set for all variables

### ISSUE THREAD

**Issue by hartstores** [Smile-SA/elasticsuite#2122]
### Preconditions

Magento Cloud Start Edition

Magento Version :
2.4.1

ElasticSuite Version :
2.10.3

Environment :
Production

### Steps to reproduce

1. Install and configure ElasticSuite per this guide https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall
2. ElasticSuite works fine, search works fine in the FrontEnd
3. Try to run bin/magento setup:config:set for any variable (e.g. bin/magento setup:config:set --enable-debug-logging=true)
**Get an error : Unable to connect ElasticSearch server : No alive nodes found in your cluster**

### Expected result

1. No error

### Actual result

1. web@mymagento.0:~$ bin/magento setup:config:set --enable-debug-logging=true
Unable to connect ElasticSearch server : No alive nodes found in your cluster

Note : The issue happens with any config variable, not just --enable-debug-logging.

.magento.app.yaml : 
relationships:
    database: "mysql:mysql"
    redis: "redis:redis"
    **elasticsearch: "elasticsearch:elasticsearch"**

**CONFIG__DEFAULT__SMILE_ELASTICSUITE_CORE_BASE_SETTINGS__ES_CLIENT__SERVERS: 'elasticsearch.internal'**

services.yaml  : 
elasticsearch:
    type: elasticsearch:7.7
    disk: 1024
    configuration:
        plugins:
            - analysis-icu
            - analysis-phonetic

Elastic Search responds correctly : 
web@mymagento.0:~$ curl elasticsearch.internal:9200
{
  "name" : "elasticsearch.0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "N6hOiJ4hT3-Oj9yfUfcXcg",
  "version" : {
    "number" : "7.7.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "253b3a30f2a2b9750d9ac7ff738982fde8a27f6f",
    "build_date" : "2020-06-18T16:09:32.168971Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by hartstores** [comment]
I just discovered something. Adding this to env.php and clearing cache fixes the issue. Except env.php gets overwritten by the Magento Cloud deploy process.

'smile_elasticsuite_core_base_settings' => [
                'es_client' => [
                    'servers' => 'elasticsearch.internal:9200'                ]
            ]
        ]
    ]

**Comment by hartstores** [comment]
Hello @vahonc ,

To summarize, I would add in your documentation that Magento Cloud does not support installing ElasticSuite through code (app/code), as it does not add the necessary parameters in env.php. It only works when installed through composer. 

This is further discussed in this section of the Magento Cloud guide https://devdocs.magento.com/cloud/env/variables-deploy.html#elasticsuite_configuration

"If the ElasticSuite composer package is installed, this is configured automatically."

**Comment by vahonc** [comment]
@rbayet, could you please comment on it?

BR,
Vadym

**Comment by romainruaud** [comment]
Hi @hartstores 

we don't support "app/code" setup, that's why the wiki is only speaking about installing through composer.

If Elasticsuite is installed as an unproper/unsupported manner by a third-party solution, that's their responsibility to fix it.

Regards
