### ISSUE TITLE
Wanted to removed Filter by Category

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2124]
Magento Version - 2.4.2

Issue : Wanted to removed filter by Category that shows all child category of the current category

Details - i have set category attribute as used in layered navigation --> no , still category filter shows on listing page with all child category prepopuated.

Ex: i have category - shirts with Virtual child category like - Red Shirts, Blue Shirts and so on, when i open shirts category listing page i see filter by category with all child category option .

I do not want this filter help with way for this

**Comment by vahonc** [comment]
Hello @ia-gaurav,

Please try to set the `Display Category Filter` setting to `No`, it should help you. You can find this setting here: `STORES -> Configuration -> CATALOG -> Catalog -> Layered Navigation -> Display Category Filter`. 

![04-26-2021 configuration settings stores magento admin](https://user-images.githubusercontent.com/67791361/116051822-abe78180-a681-11eb-88fe-913c5c420705.png)

Also, don't forget to clear cache and run re-index. 

BR,
Vadym

**Comment by romainruaud** [comment]
I close this one, since the answer provided by @vahonc is the proper way to do this.
