### ISSUE TITLE
Catalog search result shows complete list on one page

### ISSUE THREAD

**Issue by tim-breitenstein-it** [Smile-SA/elasticsuite#2125]
The atalog search result page show the complete list on one page instead of a working pagination.

Maybe related to: https://github.com/Smile-SA/elasticsuite/issues/1947#issuecomment-698945544
and this: https://github.com/Smile-SA/elasticsuite/issues/2075 (https://magento.stackexchange.com/questions/326814/magento-2-pagination-not-working-on-search-results-porto-theme)
but the Port theme is not my case.

I found no module which is using `<event name="catalog_block_product_list_collection">`

### Preconditions

PHP v7.4
MySQL v5.7.33
Magento 2 Creativeshop theme v11.2.0 (https://github.com/magesuite/theme-creativeshop)
MageSuite v7.0.0 (https://github.com/magesuite/magesuite)
Index complete and fresh.

Magento Version : 2.4.2

ElasticSuite Version : 2.10.3

Environment : Developer / Production

Third party modules :
- Mageplaza GoogleTagManager
- Mageplaza SEO Extension
- Mageplaza Cron Scheduler
- MageWorx Downlaods
- Wyomind DataFeedManager
- Magefan Blog
- Some custom module (But I don´t think these confuse)

### Steps to reproduce

1. Search for test an press ENTER
2. OR
3. Got to https://www.magento-test-shop.com/catalogsearch/result/?q=test

### Expected result

1. Search result: 1037 products, Page 1 of 87, 12 per page
2. Only 12 products per page with working pagination
3. Normal loading time

### Actual result

1. Search result: 1037 products, Page 1 of 87, 12 per page
2. But all product on one page
3. Loading time very slow

**Comment by vahonc** [comment]
Hello @tim-breitenstein-it,

As I understand you're using a custom theme, in this case, we don't guarantee the correct working ES module. You'll have to resolve the conflicts by yourself (by coding) or contact the support team of this theme.

However, try to change your custom theme to default Luma theme on your test environment and check if the problem still occurs?

For example in my test environment with the fresh M2 EE 2.4.2, default Luma theme and sample data, and ES 2.10.3 all is fine with the results of searching and paggination.

![04-26-2021 search results for hoodie ](https://user-images.githubusercontent.com/67791361/116054928-e0107180-a684-11eb-9736-cf37775455ae.png)

![04-26-2021 search results for hoodie  (1)](https://user-images.githubusercontent.com/67791361/116055272-3382bf80-a685-11eb-8fb3-886f6c46b0f8.png)

BR,
Vadym

**Comment by romainruaud** [comment]
Considering the fact that it's not reproduced in a vanilla magento with elasticsuite (see http://demo.magento-elastic-suite.io/index.php/catalogsearch/result/?q=hoodie ), this is probably due to customizations in your project.

Have you tried contacting the theme authors or the magesuite authors about it ?
