### ISSUE TITLE
Autocomplete - product details page (PDP) instead of search results page after pressing ENTER

### ISSUE THREAD

**Issue by matorg-acc** [Smile-SA/elasticsuite#2126]
Hovering mouse cursor over autocomplete list item (without clicking it) causing redirect to PDP after pressing ENTER.

### Preconditions

Magento Version : 2.3.3-p1 (EE)

ElasticSuite Version : 2.8.11

Environment : Developer and Production

Third party modules : none - vanilla Magento with sample data modules

### Steps to reproduce

1. Search for 'green' and wait for autocomplete results
2. Hover mouse cursor over one of the result item (don't click it)
3. Move mouse cursor off the result list over empty area and click to close autocomplete results.
4. Press ENTER.

### Expected result

1. Search results page.

### Actual result

1. Product details page for the last hovered item in autocomplete results list

**Comment by vahonc** [comment]
Hello @matorg-acc,

Do you use the default Luma theme or some custom theme?

BR,
Vadym

**Comment by matorg-acc** [comment]
Hello @vahonc, I use default Luma theme.

**Comment by vahonc** [comment]
@matorg-acc, according to our support policy, we no longer actively support version 2.8.x. Therefore, for now, this issue has a low priority for us. I tried testing this issue on M2 2.3.4 and ES 2.8.6 and didn't found any problem.

Is there any way to update the version of Magento or ES module in your test environment?

BR,
Vadym

**Comment by matorg-acc** [comment]
@vahonc I cannot update Magento and therefore, based on versions compatibility, I cannot also update ES (Magento <2.3.5 -> ES 2.8.x)

**Comment by vahonc** [comment]
@matorg-acc, yes you're right, I've also reproduced this issue on the environment with Magento 2.4.2 and ES 2.10.3. I'll try to check what we can do with it.

BR,
Vadym
