### ISSUE TITLE
Error during Redeploying environment process. (Urgent)

### ISSUE THREAD

**Issue by eugeneg729** [Smile-SA/elasticsuite#2128]
Hi,

Could you advice me on this. As it's quite urgent.
I am facing this issue when trying to redeploy my project. Please any suggestions in solving this?

Thank you.

Error is below:
----------------

[2021-04-27 03:11:06] ERROR: [1] The command "php ./bin/magento setup:config:set --remote-storage-driver=file -n --ansi --no-interaction" failed. In ConfigSetCommand.php line 151:
Parameter validation failed
------------------
W: In Processor.php line 129:
W:
W: The command "php ./bin/magento setup:config:set --remote-storage-driver=fil
W: e -n --ansi --no-interaction" failed. In ConfigSetCommand.php line 151
W: :
W:
W: Parameter validation failed
------------------
W: In Shell.php line 86:
W:
W: The command "php ./bin/magento setup:config:set --remote-storage-driver=fil
W: e -n --ansi --no-interaction" failed. In ConfigSetCommand.php line 151
W: :
W:
W: Parameter validation failed

---------------

Opening environment
Executing post-deploy hook for application mymagento
[2021-04-27 03:11:27] INFO: Starting scenario(s): scenario/post-deploy.xml (magento/ece-tools version: 2002.1.6, magento/magento2-base version: 2.4.2)
[2021-04-27 03:11:28] ERROR: [201] Post-deploy is skipped because deploy was failed.
W:
W: In Processor.php line 129:
W:
W: Post-deploy is skipped because deploy was failed.
W:
W:
W: In DeployFailed.php line 39:
W:
W: Post-deploy is skipped because deploy was failed.

**Comment by romainruaud** [comment]
Hello @eugeneg729 

Are you sure this is due to Elasticsuite ?

**Comment by eugeneg729** [comment]
Hi,

Yes regarding this 3 modules.

Smile_ElasticsuiteCore
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteSwatches

**Comment by eugeneg729** [comment]
Deployment log.  Any suggestion would be much appreciated.
https://codeshare.io/Gb9k8O

**Comment by romainruaud** [comment]
@eugeneg729 

I can see this error in your deployment log : 

>     W: In Shell.php line 86:
>  W:                                                                                
>   W:   The command "php ./bin/magento setup:config:set --remote-storage-driver=fil  
>  W:   e -n --ansi --no-interaction" failed. In ConfigSetCommand.php line 151  

This has nothing to do with Elasticsuite until proven otherwise.

Regards

**Comment by eugeneg729** [comment]
Hi Romain,

Thanks for your quick response. I will try to update the modules on my end and check again. If issue still persist.
Maybe it's a compatibility issue on Magento cloud end. As I am pushing to Magento Cloud repo.
