### ISSUE TITLE
Problem with Pagination

### ISSUE THREAD

**Issue by tomarSmile** [Smile-SA/elasticsuite#213]
Hi Smile ES Team,

We encountered a problem with a limitation to 20 products per page.
When I have a category with 30 products, only the first 20 products are shown.

On this same category, when I use 9 products per page on grid mode (catalog_frontend_grid_per_page), pagination goes to page 4. But page 4 returns the message "There are no products matching the selection." and the page 3 returns only 2 products.

Thanks by advance for your help,

**Comment by afoucret** [comment]
Hi @tomarSmile,

I tested this on a clean install of Magento (+ sample data) with ElasticSuite installed and was not able to reproduce the bug (if well understood) : 

You can see an example here : http://demo.magento-elastic-suite.io/index.php/men/tops-men.html?p=2&product_list_limit=24

What version of Magento / ElasticSuite are you using ?

Don't you have any toolbar or navigation customization in your project ? By example changing the name of the toolbar block can lead to such bugs ...

**Comment by tomarSmile** [comment]
Hi Aurélien,

We found the problem. We are doing : `<move element="div.sidebar.main" destination="columns" before="-"/>` on the page_layout file : 2columns-left.xml.

Thanks for your help.

Tomar
