### ISSUE TITLE
Using MSI with new Stock and new Sources disappearing configurable product type after reindexing inventory

### ISSUE THREAD

**Issue by meirzaicube** [Smile-SA/elasticsuite#2137]
Using magento MSI with new Stock and new Sources disappearing Configurable Product type only after reindexing inventory, but not with Simple Product and Virtual Product type

### Preconditions
PHP 7.4.16
Magento Version: 2.4.1
ElasticSuite Version: 2.10
Environment: Developer and Production
Third-party modules : _None_

### Steps to reproduce

1. Create 2 new Inventory Source: **Stock A** and **Stock B** 
2. Create 1 new Inventory Stock: **Main Stock** . And Main Website as Sales Channels. Assign both sources above into the Main Stock. 
3. Create 1 configurable product type with associated simple products, assign both sources above on each associated simple products
4.Create 1 simple product and also assign both sources above
5. Make sure all products using sam category
6. Goto the category page, and you will see both products (simple and configurable)
7. Reindexing Inventory by calling `bin/magento indexer:reindex inventory`

![Screenshot from 2021-05-02 08-57-14](https://user-images.githubusercontent.com/66400334/116799544-72e95a00-ab24-11eb-9dd8-96cddafa723e.png)
![Screenshot from 2021-05-02 08-57-26](https://user-images.githubusercontent.com/66400334/116799554-77ae0e00-ab24-11eb-909e-7f4a4d39c0a4.png)

### Expected result
Go to the category page, and you will see both products (simple and configurable)

![Screenshot from 2021-05-02 08-55-18](https://user-images.githubusercontent.com/66400334/116799522-37e72680-ab24-11eb-96d6-e436ecfeeee6.png)

### Actual result
Go to the category page, and you will see only 1 product, which is a simple product. The configurable is missing.
![Screenshot from 2021-05-02 08-53-37](https://user-images.githubusercontent.com/66400334/116799525-3cabda80-ab24-11eb-851e-d7c1290a80f8.png)

### Additional Information
To bring the configurable product type back is doing reindex `bin/magento ind:rei catalogsearch_fulltext` and `bin/magento c:f`

**Comment by meirzaicube** [comment]
Currently, i'm using the patch from Magento https://support.magento.com/hc/en-us/articles/360050636011-MDVA-30977-Magento-patch-missing-products-from-categories-indexing-related , still monitoring.

**Comment by vahonc** [comment]
Hello @meirzaicube,

Did I understand you correctly that the problem you described was before using the patch and now you are monitoring whether this patch helped you?

BR,
Vadym

**Comment by meirzaicube** [comment]
@vahonc Yes, correct

**Comment by vahonc** [comment]
Okay, then we will wait for new updates from you.

BR,
Vadym

**Comment by meirzaicube** [comment]
The patch fixes the bug.
