### ISSUE TITLE
I want to hide count in filters any setting for it

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2139]
I want to hide count in filters any setting for it, there is option in Admin to not show count in layered navigation but it seems not working

**Comment by vahonc** [comment]
Hello @ia-gaurav,

If I understood correctly what you want, you need to set **Display Product Count** to **No** in `STORES -> Configuration -> Catalog -> Layered Navigation -> Display Product Count`.

**Look at my screenshots:**
![magento2-display-product-count-front-after](https://user-images.githubusercontent.com/67791361/118099038-5fb87300-b3dd-11eb-8b0d-fbc036cf1703.png)

![magento2-display-product-count-config](https://user-images.githubusercontent.com/67791361/118099024-5a5b2880-b3dd-11eb-8937-0eec8c4a55d5.png)

![magento2-display-product-count-front-before](https://user-images.githubusercontent.com/67791361/118098997-53ccb100-b3dd-11eb-911f-e7787b2a1dee.png)

Don't forget to clear the cache of Magento!

And if that doesn't solve your problem, please provide more details (screenshots, etc.).

BR,
Vadym

**Comment by ia-gaurav** [comment]
already done, but seems not working  for me 

Magento Verison - 2.4.1
ElasticSuite Version - 7.9.2

Setting SS  - 

![image](https://user-images.githubusercontent.com/63009790/118117227-f5b5c300-b408-11eb-9b8c-4e73f9e219bf.png)

**Comment by ia-gaurav** [comment]
Please ignore I got issue, my theme was rewriting filter output .

**Comment by romainruaud** [comment]
Okay I close then
