### ISSUE TITLE
SHow More After 10th Attribute

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2141]
where can i choose option to show "Show More" option after x number of attributes in filter 

Please note - I want to do this for filter swatches

**Comment by romainruaud** [comment]
That's not possible for swatches unfortunately.

For other attributes, it's the "Facet Max Size" configuration option.

**Comment by vahonc** [comment]
Hello @ia-gaurav,

I agree with @Romain that currently this is not possible for swatches. 

You could read our Wiki about the configuration "Show more" feature for other types of attributes and maybe it will be useful for you.
- [Faceting configuration](https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration)
- [Faceting configuration by category](https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration-by-category)

BR,
Vadym
