### ISSUE TITLE
Move Out of Stock To Last

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2142]
Is there option to move all out of stock products in last

**Comment by romainruaud** [comment]
Hi,

you can just create an optimizer to do this, and apply a positive boost to products that are in stock : https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers

**Comment by ia-gaurav** [comment]
i could get way to do this , can you share screenshot for my test case

**Comment by ia-gaurav** [comment]
@romainruaud  
 i could not get way to do this from optimizer , can you share screenshot for same

**Comment by romainruaud** [comment]
Please refer to the wiki, it's as simple as creating a positive boost and targeting "Only in stock products" in the rule section of the optimizer.

Regards

**Comment by henkvalk** [comment]
Thanks @romainruaud That worked for me

**Comment by ia-gaurav** [comment]
@henkvalk  did it worked for you can u share screenshot for setting

**Comment by ia-gaurav** [comment]
@romainruaud  - it worked for me also but i just noticed that it is confliction it manual sort i used, is there way to remove manual sort in case product goes out of stock

**Comment by romainruaud** [comment]
Actually not. Manual sort has always precedence, so if a product is pinned with manual sort, it will remain at the pinned position.

Regards
