### ISSUE TITLE
Possibility to extend children attributes that are indexed into parent content

### ISSUE THREAD

**Issue by adamkarnowka** [Smile-SA/elasticsuite#2143]
Hi, I can see that for custom attributes and configurable products, when indexed, values of of these attributes are saved for configurable and it's simples:

![image](https://user-images.githubusercontent.com/511845/118801200-08b11300-b8a1-11eb-812c-8dd1219421a9.png)

Having values stored like this messes up our optimizers' behaviour when we want to use attribute saved like this.

I can see that adding attributes to `forbidenChildrenAttributeCode` in  https://github.com/Smile-SA/elasticsuite/blob/ddb32cece156cfa7f84b4c54fea26411e29d315e/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L34

However, since it's private it's very hard to extend it. 
Would you consider making this array configurable via xml or any other way to make more adjustable?

Thanks,
Adam

**Comment by romainruaud** [comment]
Sure, this could be a good improvement.

Are you able to propose a PR for this ?

**Comment by adamkarnowka** [comment]
Sure, just tell me what kind of configuration is preferred by you? I think admin config would be the best approach, because attributes can also be added in admin panel and it would be good to control how they are indexed also within admin panel scope - not needed code changes or deployment?

**Comment by romainruaud** [comment]
Yes if you can propose something that would be configurable per-attribute, it would be definitely the best option.

Let me know !

**Comment by romainruaud** [comment]
This has been done in #2465
