### ISSUE TITLE
Is it possible to add is in stock attibute for filter products ?

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2144]
Hello,

i am trying to add is in stock filter on layered navigation.

But not work.

Can you help me please ? You can sy attribute settings bellow

Thank you in advance.

![image](https://user-images.githubusercontent.com/17496183/119254789-ac0f6a00-bbb8-11eb-991a-7c235976f8f2.png)
![image](https://user-images.githubusercontent.com/17496183/119254797-b598d200-bbb8-11eb-8f8a-db64adfc9d32.png)
![image](https://user-images.githubusercontent.com/17496183/119254805-c77a7500-bbb8-11eb-899d-6a5f1eb5c117.png)
![image](https://user-images.githubusercontent.com/17496183/119254808-cc3f2900-bbb8-11eb-99f6-adfeb26695a2.png)

**Comment by romainruaud** [comment]
Nope that's not possible, cf #1924

**Comment by achatpc** [comment]
Thank you. I think that i have to add new custom attibute for enable this feature.

**Comment by webcreative24** [comment]
@achatpc did you find any solution for that?
