### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by globallydigital** [Smile-SA/elasticsuite#215]
We have installed Elastic Suite onto a Magento 2.1.2 install via Composer as guided within your documentation, however following the install we are seeing the following error in the logs:

No shard available for [org.elasticsearch.action.termvectors.TermVectorsRequest@7c51141e]

What does this error indicate?

**Comment by afoucret** [comment]
Hi @globallydigital,

From what I see this error indicates, that an index is missing. Most probably the thesaurus index.

I realize that the following update was missing in the wiki reindexing section:

```
bin/magento index:reindex catalogsearch_fulltext
```

should now be

```
bin/magento index:reindex catalogsearch_fulltext
bin/magento index:reindex elasticsuite_categories_fulltext
bin/magento index:reindex elasticsuite_thesaurus
```

Can you try to launch this three commands and give me a feedback.
The wiki has already been updated.

**Comment by globallydigital** [comment]
Hi,

We have applied this but are still seeing the same error.

Regard
Paras

**Comment by afoucret** [comment]
Does you magento logs contains any errors triggered during indexing ?
What about your ES logs (/var/log/elasticsearch/*.log) ?

**Comment by afoucret** [comment]
Hi @globallydigital, I did not get any feedback from you on my last aswers. Is the problem solved ? If so, what was the source of the problem ?

**Comment by globallydigital** [comment]
The ES logs (/var/log/elasticsearch/*.log)  have not generated and the Magento 2 exception was not generated but error generated on system.log. Please find attached text files for more information.

**Comment by romainruaud** [comment]
Hello @globallydigital and thank you for providing such feedback.

I would like to know which version of Elasticsearch you are running exactly ? 

Also, both indexing and querying processes are showing the same error : "no shard available".

We will need to know how is configured your Elasticsearch instance : how many nodes and shard, where is it located, do you have a replication strategy ?

Best regards,

**Comment by afoucret** [comment]
I suspect that you have reached the 85% of used space on the disk containing ElasticSearch.
The default config prevent new shards being allocated to a node in this condition (https://www.elastic.co/guide/en/elasticsearch/reference/2.4/disk-allocator.html) : 

> Controls the low watermark for disk usage. It defaults to 85%, meaning ES will not allocate new shards to nodes once they have more than 85% disk used. It can also be set to an absolute byte value (like 500mb) to prevent ES from allocating shards if less than the configured amount of space is available.

Can you check if this limit have been reached ?

As you can see ElasticSuite is reporting some errors in the log :
```
[2016-11-24 06:18:00] main.ERROR: Bulk index operation failed 100 times in index magento2_default_catalog_product_20161124_061559 for type product Error (unavailable_shards_exception) : [magento2_default_catalog_product_20161124_061559][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [magento2_default_catalog_product_20161124_061559] containing [100] requests] Failed doc ids sample : 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3614 [] []
``` 

You can make the reporting more verbose by enabling the debug mode of ES (we strongly advice to not apply this settings in production since every ES queries and responses will be logged causing huge amount of magento logs to be generated).

**Comment by globallydigital** [comment]
This is from the host:

You are currently only consuming 28% of your allocated disk space:

[root@fearlesss-vm0 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        98G  27G  72G  28% /

**Comment by afoucret** [comment]
One simple question : what the result of running the following command in bash on your server : 
```
curl "http://localhost:9200"
```

and

```
curl -XGET "http://localhost:9200/_cluster/health?pretty"
```

The most likely would be that your ElasticSearch cluster is not correctly installed and the issue is not related with ElasticSuite at all.

**Comment by afoucret** [comment]
Hi @globallydigital,

Any feedback ?

**Comment by globallydigital** [comment]
We now have the extension working – thank you for your help.

The issue was with the hosting provider and their setup.

**Comment by afoucret** [comment]
OK. Thank you for your feedback. I was pretty sure it was not related wit ElasticSuite.

**Comment by shiva12121** [comment]
hi i tried install opensmile on visual studio 2010 and win 8.1 64 bit but when i writ this cod : SMILExtract_Release -c has errors that see it :
pleases help me
![66717994-c59cdd00-edeb-11e9-9b6f-d10eb24951f3](https://user-images.githubusercontent.com/48890275/66752344-110fc380-ee9e-11e9-96cc-1ce9c75115bb.png)
