### ISSUE TITLE
Fatal error in admin when editing a category (with fix)

### ISSUE THREAD

**Issue by JonathanBBD** [Smile-SA/elasticsuite#2155]
### Preconditions

Magento Version : 2.3.7
ElasticSuite Version : 2.9.5
Environment : Production
Third party modules : -

### Steps to reproduce
1. Login into the admin
2. Goto Catalog > Category
3. Click a non-root category to see it's details

### Expected result
1. See the category edit form

### Actual result
1. Error with "Trying to access array offset on value of type int"

### Resolve

This issue is already fixed in the 2.10.x branch, see commit [Fixes error using incorrect variable for calculate price ](https://github.com/Smile-SA/elasticsuite/commit/a88b2b0435b91d69e91baa7d92cebb8283c711c4). I merely request to apply this fix in the 2.9.x branch as well.

Thank you.

**Comment by romainruaud** [comment]
@vahonc can you add a PR to 2.9.x branch with this fix ?

**Comment by mamsincl** [comment]
Can we get this merged and tagged, please

**Comment by romainruaud** [comment]
Yes I plan to do some release at the end of the month, this one will be included.

Regards
