### ISSUE TITLE
Product filters - Price Slider - Product out of stock showed in listing with higher price

### ISSUE THREAD

**Issue by br1luca** [Smile-SA/elasticsuite#2158]
The price filter does not apply to out of stock products.

### Preconditions
Magento Version : 
CC

ElasticSuite Version :
2.8.8

Environment :
Production

Third party modules :
No

### Steps to reproduce

1. Have a OUT OF STOCK product (Configurable with all single OUT OF STOCK)
2. Have a Catalog Rule apply to the OUT OF STOCK product
3. Fitler a PLP with that product with a max price lower the product price

### Expected result
1. The product should not be visible

### Actual result
1. The product is visible

**Comment by romainruaud** [comment]
Hi @br1luca 

I'm wondering if the result of Magento catalogrule are accurate in the price index table. We index the raw content of this table in the ES index, meaning that, if the value is incorrect in the table, it will be incorrect for Elasticsearch too.

Are you able to provide more details to your example by giving us the content of ``catalog_product_index_price`` table for this particular product ?

**Comment by br1luca** [comment]
You only need that row?

**Comment by dambrogia** [comment]
Do you have optimizers enabled? When you start adding queries, filters and optimizers it's very easy for the `score` of the result to be exponentially higher. Have you tried debugging this to see what the score is being returned? I would assume this is a configuration or data issue.
