### ISSUE TITLE
Index Identifier is empty when querying GraphQL products query

### ISSUE THREAD

**Issue by rootindex** [Smile-SA/elasticsuite#2159]
When hitting the frontend the correct results get returned however when hitting the GraphQL query the following error message gets returned: 

Internal server error: Index does not exist yet. Make sure everything is reindexed. 

### Preconditions

- Custom docker environment: 
```
        PHP 7.4.19  /  Zend OPcache v7.4.19 
        MARIADB_VERSION=1:10.4.17+maria~focal
        docker.elastic.co/elasticsearch/elasticsearch:7.6.2 
        elastic analysis-icu      7.6.2
        elastic analysis-phonetic 7.6.2

   ```

Magento Version : 2.4.2

ElasticSuite Version : 2.10.4

Environment : Developer + Production (both tested)

Third party modules :
N/A
### Steps to reproduce

1. Hit the GraphQL products query endpoint
```query {
  products(filter: {sku: {eq: "sku1"}}) {
    items {
      name
    }
  }
}

```

### Expected result

1. Receive list of products

### Actual result

1. Received error message 
```{
  "errors": [
    {
      "debugMessage": " index does not exist yet. Make sure everything is reindexed.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "products"
      ]
    }
  ],
  "data": {
    "products": null
  }
}
```
GraphQL: 
```
[2021-06-04 10:51:16] main.WARNING: Request Failure: {"method":"HEAD","uri":"http://elastic/m2_default_","port":9200,"headers":{"Host":["elastic"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.7.0 (Linux 4.19.0-16-amd64; PHP 7.4.19)"]},"HTTP code":404,"duration":0.001987,"error":"null"} []
[2021-06-04 10:51:16] main.WARNING: Response [null] []
[2021-06-04 10:51:16] main.INFO: curl -XHEAD 'http://elastic/m2_default_?pretty=true' [] []
```
Frontend:
```
[2021-06-04 10:37:14] main.INFO: Request Success: {"method":"POST","uri":"http://elastic/m2_default_catalog_product/_search","port":9200,"headers":{"Host":["elastic"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.7.0 (Linux 4.19.0-16-amd64; PHP 7.4.19)"]},"HTTP code":200,"duration":0.006889} []
[2021-06-04 10:37:14] main.INFO: curl -XPOST 'http://elastic/m2_default_catalog_product/_search?pretty=true' -d ' ...

```

**Comment by vahonc** [comment]
Hello @rootindex,

I've tried to reproduce your issue on my test environment with Magento EE 2.4.2 and ES 2.10.4 and everything was fine with the providing by you a GraphQL products query:
 
![Screenshot from 2021-06-07 11-35-32](https://user-images.githubusercontent.com/67791361/120988282-17476780-c787-11eb-866c-c65d4ef13786.png)

As I can see, you're using the custom indices alias name, so first, check your settings in Magento BO according to our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings) and maybe run a full reindex to be sure that everything was indexed.

Also please provide an output of this command: 
`curl http://localhost:9200/_cat/indices?v`

BR,
Vadym

**Comment by rootindex** [comment]
Please find attached the output:

```
www-data@fpm:/app$ curl http://elastic:9200/_cat/indices?v
health status index                                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   m2_default_catalog_product_20210604_094757  QBH6HZAHSbyH0ra9LviLEA   1   0     105771            0      105mb          105mb
green  open   m2_default_thesaurus_20210604_095044        kgIS11BUTi-QowOCup5AnQ   1   0          0            0       283b           283b
green  open   m2_default_catalog_category_20210604_095043 zxTWYuqJSSO_X6mnseb8Fw   1   0        774            0        3mb            3mb
www-data@fpm:/app$ bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:48
Category Products index has been rebuilt successfully in 00:04:51
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:45
Stock index has been rebuilt successfully in 00:00:02
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:04
Catalog Search index has been rebuilt successfully in 00:00:32
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:01
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
www-data@fpm:/app$ curl http://elastic:9200/_cat/indices?v
health status index                                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   m2_default_catalog_category_20210607_100256 6Hw2YTJdS9GVxJaVNyFInA   1   0        774            0        3mb            3mb
green  open   m2_default_thesaurus_20210607_100257        aGIyaKz-TLusIh3iKokZ6g   1   0          0            0       230b           230b
green  open   m2_default_catalog_product_20210607_100222  vRzcC6ZoSUWG56Wl0WfLmQ   1   0     105771            0    186.1mb        186.1mb
```

**Comment by romainruaud** [comment]
It's very strange, it looks like Magento is not able to determine correctly the index name to use, since the "catalog_product" part is not injected into the index name.

Do you have something custom built on top of Elasticsuite ? Third party modules ?

**Comment by rootindex** [comment]
There is nothing custom build on top of it, I've since creating this ticket tried a few things. On development(warden) I managed to get things to work correctly, I took the working database and codebase to the staging environment where I still get the failed index name on graphql endpoint. This leads me to believe this is a php setting or module not being installed.

**Comment by rootindex** [comment]
It looks like baseConfig returns null
```
$this->baseConfig->get($this->containerName . '/' . $param) ?? $default;
```

<img width="1430" alt="Screenshot 2021-06-08 at 19 05 33" src="https://user-images.githubusercontent.com/505211/121228251-d0439a00-c88c-11eb-9d65-1e2edadf6122.png">

**Comment by rootindex** [comment]
Further debugging leads me to the following:

on dev (and frontend) the containerName = 'quick_search_container'
but on staging it the containerName changes to 'graphql_product_search'

**Comment by rootindex** [comment]
This issue seems to be very much related to #1690 , not sure why and how the same code base/database (only configuration changes) can have such a strange effect.

**Comment by rootindex** [comment]
I believe I found the issue, I followed the installation process without error or notice, two modules stays disabled if the project is in production mode. I fixed it by running. 

```
bin/magento module:enabled Smile_ElasticsuiteCatalogGraphQl Smile_ElasticsuiteIndices
```
