### ISSUE TITLE
Do you support ES5?

### ISSUE THREAD

**Issue by LouiseMcMahon** [Smile-SA/elasticsuite#216]
I've been fghing trying to get the module to work only to read #211 which says ES5 is not supported? is that is the case should that not be in your docs?

**Comment by afoucret** [comment]
Hi,

ES 5.x is quite recent so we did'nt not had the time to update doc before early adopters try to install it. It is not fixed [here](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) and  [there](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig).

Thx for the contrib
