### ISSUE TITLE
Child Category to Use parent category custom sorting

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2160]
**Preconditions**
Magento 2.4
A Parent and A child Category

**Steps to reproduce**
Change Ordering of Products in Parent product with custom drag option
Create child virtual category of above parent 

**Expected result**
child category should inherit parent category custom ordering 

**Actual result**
custom ordering is not inherited from parent category

**Comment by romainruaud** [comment]
Sorry but we do not plan to implement this. To be honest, we found out that manual positioning is rarely used, except for very small catalogs, due to the amount of manual work it requires. And on very small catalogs, it's not an issue to merchandise each category without inheritance.

Regards
