### ISSUE TITLE
Cache not cleared when changing a virtual category rule

### ISSUE THREAD

**Issue by bretin** [Smile-SA/elasticsuite#2162]
Prior Magento 2.4.2 and ES 2.10.4, when a change was made on a category rule, it was reflected automatically in front.
Now, we need to do a cache flush in order to have the change visible in front.

It was working fine for us on Magento 2.3.5 p2 and ES 2.9.4

### Preconditions

Magento Version : 2.4.2-p1 EE

ElasticSuite Version : 2.10.3 and 2.10.4

Environment : Dev

Third party modules : N/A

### Steps to reproduce
1. Create a category
2. Set the category as Virtual Category with a rule like: Price < 5$. Let say this is suppose to return 5 products
3. Access the page in front => 5 products are shown (Result OK)
4. Change the category Rule to Price < 10$ and Save. Now we should have 10 products
5. Access the page in front (Make sure you don't have Fastly configured if on a server)
6. The page still show 5 products (Result KO)
7. If you try to do a **cache clear** This does not do anything BUT  if we do a bin/magento cache:flush now it works.

### Expected result
1. When a category rule is saved, the cache "getCategorySearchQuery" should be invalided or deleted (for all storeviews) only for the current category so when accessing the product

### Actual result
1. The category in front is still showing the old rule. Even if we try to sort or change page the results are wrong.
2. If the Admin try to clean each cache individually it does not do anything BUT if we execute the commande ligne bin/magento cache:flush OR click on the orance button "Flush Magento Cache" on tha cache page, this fix the issue.
3. This is not an option because the impact on the website performances are too big.

If we remove the specific cache on the category save, it looks like it works fine but not sure why it is now different...
In file `smile/elasticsuite/src/module-elasticsuite-virtual-category/Observer/ConvertVirtualRuleOnSave.php` function `execute`

```php
$stores = $this->storeRepository->getList();
foreach ($stores as $store) {
            $this->cache->remove(implode('|', ['getCategorySearchQuery', $store->getId(), $entity->getId()]));
            $this->cache->remove(implode('|', ['getSearchQueriesByChildren', $store->getId(), $entity->getId()]));
}
```

Thanks

**Comment by romainruaud** [comment]
Well, the only cache tag which is put in these objects is the Magento's legacy "CATEGORY" tag : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-virtual-category/Helper/Rule.php#L69

```
$this->cache->save($cacheData, $cacheKey, [\Magento\Catalog\Model\Category::CACHE_TAG]);
```

It seems that this cache is not purged anymore by Magento when editing a category ? That would be surprising but I know they can do such things.

@vahonc can you try to reproduce this issue ?

**Comment by vahonc** [comment]
I've been able to reproduce this issue on my test environment with Magento EE ver. 2.4.2 and ES 2.10.4.

And according to the [release notes](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-2.html#catalog) of Magento 2.4.2, it looks like now when we try to Save a category it flushes only the block cache that is related to this category. Previously, Magento flushed the cache for all category blocks.

I'll try to work around it and will add some changes.

BR,
Vadym
