### ISSUE TITLE
Error on reindexing - TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, 

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2165]
I am getting below error 

Catalog Search index process unknown error:
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [magento1_en_catalog_product_20210609_043506] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}],"type":"cluster_block_exception","reason":"index [magento1_en_catalog_product_20210609_043506] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"},"status":429}
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:00

**Comment by ia-gaurav** [comment]
yes doing it solved the issue , but my elasticsearch goes down frequently any way to optimize same

**Comment by vahonc** [comment]
> but my elasticsearch goes down frequently any way to optimize same

For this one we need more details, maybe you have some log entries or smth like this.

BR,
Vadym

**Comment by ia-gaurav** [comment]
can you help me with way to get logs - do i need to enable soemthing for log

**Comment by vahonc** [comment]
I'm not sure that your problem linked directly to our ES module, most probably you have some issue with Elasticsearch and your environment. 

I think that you can start your investigations by exploring `/var/log/elasticsearch/*.log` 

Also, you could check the [official docs](https://www.elastic.co/guide/en/cloud/current/ec-enable-logging-and-monitoring.html) of Elasticsearch.

BR,
Vadym

**Comment by ia-gaurav** [comment]
@vahonc  i am triyng to find issue - meanwhile can u help me what should be indices for better optimization

**Comment by ia-gaurav** [comment]
check below setting - 


![image](https://user-images.githubusercontent.com/63009790/121931970-eefcd180-cd61-11eb-881b-29eaaf0a7474.png)

**Comment by vahonc** [comment]
Hello @ia-gaurav,

I think that smth is wrong with your indexes.

You could try to delete all existing indexes, flush cache and run full re-index .

`$ curl -XDELETE localhost:9200/*`

`$ bin/magento cache:flush`

`$ bin/magento indexer:reindex`

BR,
Vadym
