### ISSUE TITLE
How to add a custom Virtual Category Rule

### ISSUE THREAD

**Issue by jaxtheking** [Smile-SA/elasticsuite#2166]
Hi,
I'm investigating if there's a way to add a custom Virtual Category Rule from my own module. Without going into any detail, I need to add a rule for Recently Added products (hardcoded to 15 days will do if I can't figure out how to use < >).

I see how the module adds its own custom rules in di.xml:
```
<!-- Add the default Elasticsuite Special Attributes. -->
<type name="Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttributesProvider">
    <arguments>
        <argument name="attributes" xsi:type="array">
            <item name="has_image" xsi:type="object">Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\HasImage</item>
            <item name="stock.is_in_stock" xsi:type="object">Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsInStock</item>
            <item name="price.is_discount" xsi:type="object">Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsDiscount</item>
        </argument>
    </arguments>
</type>
```
How would I declare my module's di.xml to add to the list above and not override it fully?
I hope my question makes sense.
Thanks, Luca

**Comment by vahonc** [comment]
Hello @jaxtheking,

You're on the right track, you just need to add a custom rule for the Virtual Category in your own module by declaring it in di.xml as you show in the code from above. Just remove unnecessary items and specify the path to the model where you will implement your custom code. Magento will merge all XML files into one.

BR,
Vadym

**Comment by jaxtheking** [comment]
It sounds easy enough then (last famous words).
@vahonc Thanks for your reply, it's very appreciated.
