### ISSUE TITLE
Search Bar Broken on Codazon Infinit Theme

### ISSUE THREAD

**Issue by hiimkhaled** [Smile-SA/elasticsuite#2168]
As you can see the screenshots, after installing Elasticsuite, the search bar is broken. Everything else is working fantastic, I have been trying this since long time but no luck.

Installed theme is [**Codazon Infinit**](https://themeforest.net/item/infinit-magento-2-magento-1-theme-multipurpose-responsive-theme/22432458)
URL [**mke.com.bd**](https://www.mke.com.bd/)

I am not a hardcore developer, can anyone help me if it can be fixed using custom CSS or any other tricks?

TIA!
![image](https://user-images.githubusercontent.com/30042185/121695118-91138400-caec-11eb-91c4-afe128e87722.png)
![image](https://user-images.githubusercontent.com/30042185/121695280-bc966e80-caec-11eb-8d9f-2a31c280f92e.png)

**Comment by romainruaud** [comment]
Hello @hiimkhaled 

we do not provide such kind of support for third-party extensions as part of our Open Source support policy here on Github.

I close it since we'll not provide any fix. You should ask your agency to fix this.

Best regards
