### ISSUE TITLE
Pagination shows all products of the category on every paginated page

### ISSUE THREAD

**Issue by diybook** [Smile-SA/elasticsuite#2173]
I'm having the same issue like @jimuld in #1912. I've updated to magento 2.4.2 and elasticsuite 2.10.4 and having the same problem he has described in his last post. 

All products of a category are shown on all pages. Collection size is 38 and only 20 products should be shown per page. But all 38 products are listed.

### Preconditions
Magento Version : 2.4.2 CE 
ElasticSuite Version : 2.10.4
Magento Environment : Developer 

Third party modules :
Amasty_GdprCookie
Amasty_Stockstatus
Fooman_PrintOrderPdf
Fooman_EmailAttachments
Mirasvit_Seo
Mirasvit_Core
Mirasvit_SeoSitemap
Mirasvit_SeoFilter
Mirasvit_SeoAutolink
Mirasvit_SeoContent
Mirasvit_SeoMarkup
Mirasvit_SeoToolbar
WeltPixel_Backend
WeltPixel_GoogleTagManager
WeltPixel_OwlCarouselSlider
WeltPixel_LazyLoading
WeltPixel_LazyLoadingOwlCarouselSlider

### Steps to reproduce
Go to category that should be paginated (max. results 20)

### Expected result
1-x pages dependent on result size

### Actual result
1-x pages with all products of the collection e.g.  98 products
![Unbenannt](https://user-images.githubusercontent.com/3702595/122184091-2cf61480-ce8c-11eb-9ea7-512e44783c93.PNG)

**Comment by vahonc** [comment]
Hello @diybook,

Most likely your problem is related to using a custom theme. Can you check it out on a default theme like Luma?

BR,
Vadym

**Comment by diybook** [comment]
Thanks for your answer. I'll check that. What files shall I have a closer look? Layout Files, Template Files or Block Files? The result with pagination is working on the search result page. 

BR, Gerald

**Comment by vahonc** [comment]
Gerald, it's hard to say exactly why you are facing this problem. This can be in templates, layouts, and also in the settings of the theme itself. 

Also, check your catalog display settings in Magento BO:

![configuration-settings-stores-magento-admin](https://user-images.githubusercontent.com/67791361/122213211-655c1980-ceb1-11eb-99f6-db9c76177439.jpg)

Did you use your custom theme before the update? Did you notice this problem then?

**Comment by diybook** [comment]
Hi, the theme is not causing this issue. I've checked it with luma theme. The behaviour is the same. I'll start deactivating 3rd party modules. The theme was the same before the update, so there was no change.

**Comment by vahonc** [comment]
Which Magento version did you upgrade to 2.4.2 from? Did you check your catalog display settings or other settings in Magento BO?

BR,
Vadym

**Comment by diybook** [comment]
I've updated from 2.3.6. But I may have found it finally. There was a bug in the Weltpixel module, or to be more specific in an overwrite of this module. But I have to verify it. Thanks for your help to get on the right track. BR Gerald

**Comment by g-laurenz** [comment]
> I've updated from 2.3.6. But I may have found it finally. There was a bug in the Weltpixel module, or to be more specific in an overwrite of this module. But I have to verify it. Thanks for your help to get on the right track. BR Gerald

Hi, I'm also having an issue with the WeltPixel Extension. Would you kindly teach me how you fixed the issue?
Thank you!

**Comment by sw69** [comment]
> > I've updated from 2.3.6. But I may have found it finally. There was a bug in the Weltpixel module, or to be more specific in an overwrite of this module. But I have to verify it. Thanks for your help to get on the right track. BR Gerald
> 
> Hi, I'm also having an issue with the WeltPixel Extension. Would you kindly teach me how you fixed the issue? Thank you!

Hi, did you find a solution?
