### ISSUE TITLE
es_rejected_execution_exception, status 429

### ISSUE THREAD

**Issue by fritzmg** [Smile-SA/elasticsuite#2174]
After installing MageSuite in a Magento `2.4.2-p1` instance, which also has `smile/elasticsuite` as a dependency, the following error appears when running `indexer:reindex` (or when `cron:run` is executed):

```json
{
    "error": {
        "root_cause": [
            {
                "type": "es_rejected_execution_exception",
                "reason": "rejected execution of coordinating operation [coordinating_and_primary_bytes=95396333, replica_bytes=0, all_bytes=95396333, coordinating_operation_bytes=22949230, max_coordinating_and_primary_bytes=107374182]"
            }
        ],
        "type": "es_rejected_execution_exception",
        "reason": "rejected execution of coordinating operation [coordinating_and_primary_bytes=95396333, replica_bytes=0, all_bytes=95396333, coordinating_operation_bytes=22949230, max_coordinating_and_primary_bytes=107374182]"
    },
    "status": 429
}
```

As I am unfamiliar with the inner workings of Elasticsearch and the Elasticsuite specifically, I am not sure how to fix this problem. Since the error mentions a `429` status: is Elasticsuite somehow sending too many requests to the Elasticsearch server and the Elasticsearch server then refuses this? If yes, is this a typical Elasticsearch server problem? Unfortunately we are not managing the Elasticsearch server ourselves, so we would need some pointers to give to the admins of the server.

**Comment by vahonc** [comment]
Hello @fritzmg,

Most likely your problems are linked to AWS hosting. Could you please provide more details about it? 

It looks like your elasticsearch setup is not able to keep indexing under the current load, [ref](https://discuss.elastic.co/t/in-which-case-elasticsearch-will-return-429/23483)

Please check the settings and limitations of your AWS hosting plan. 

Also, maybe this [article](https://aws.amazon.com/premiumsupport/knowledge-center/resolve-429-error-es/) will be useful for you too.

BR,
Vadym
