### ISSUE TITLE
Elastic suite is not indexing product catalog.

### ISSUE THREAD

**Issue by jnouelccn** [Smile-SA/elasticsuite#2179]
After running the magento reindex command elastic suite it is not indexing/sending the product catalog to the elastic search server. No errors appear during the reindex process (does it pretty fast so maybe it's not iterating the product catalog) and the index is created successfully in the elastic search server but it appears to be empty (208b of size). 

Another problem that we have encountered in some servers after added elastic suite is that the admin page it's completely empty (only returning a 304 http response). But we don't know if this problem is related to the slastic suite.

### Preconditions

This is a STAGING Environment.

Magento Version : EE 2.3.5-p2

ElasticSuite Version : 2.9.0

Environment : developer mode

Third party modules :
Mageplaza_Core
Mageplaza_BannerSlider
Mageplaza_DeleteOrders
Mageplaza_GoogleRecaptcha
Mageplaza_Productslider
Mageplaza_Smtp
Algolia_AlgoliaSearch
Algolia_CustomAlgolia
Eadesigndev_Eacore
Eadesigndev_Pdfgenerator
Ced_FbNative
MSP_ReCaptcha
MGS_Core
MGS_Popup
Omnipro_ProductStructuredData
Tigren_Ajaxsuite
Tigren_Ajaxwishlist
MageWorx_OrdersBase
MageWorx_OrderEditor
[third party modules.txt](https://github.com/Smile-SA/elasticsuite/files/6689604/third.party.modules.txt)

### Steps to reproduce

1. Run bin/magento indexer:reindex or  bin/magento index:reindex catalogsearch_fulltext elasticsuite_categories_fulltext elasticsuite_thesaurus

### Expected result

1. Elastic search indices should be created with product catalog
2. Catalog searh should give results
3. Category navegation should work
![elastic search indices](https://user-images.githubusercontent.com/86262436/122829515-1baa6f00-d2b5-11eb-871a-48492254fb49.PNG)

### Actual result

1. Catalog search does not return products
2. Categories pages does not have products
3. Catalog Product does not have products in elastic search sever

curl -i localhost:9200/_cat/indices returns the following:  

green open stagingjumbo_default_catalog_category_20210607_145813           ght52vQdTtCdXCZWD6OpFQ 1 0 363 0 355.5kb 355.5kb
green open stagingjumbo_default_catalog_product_20210621_050020            3yLOPeTnRgqJ4FMhmt7ZBg 1 0   0 0    208b    208b
green open stagingjumbo_almacen_thesaurus_20210607_145816                  QZzELwpASUS0VM1ZsLUT0A 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_catalog_product_20210621_050023     s8FHGcQ2TZKUGufEOFghQg 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_category_20210607_145814 w3kspZCmSjiY7sTESNaQaw 1 0 363 0 355.5kb 355.5kb
green open stagingjumbo_deliverystoreview_thesaurus_20210607_145816        1VPp4AcIT0qv7JyaHB4rUQ 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_product_20210621_050022  cI0xY8vfRBCjPBBruwIvCA 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_thesaurus_20210607_145816           EK6i0pH2QN2O7bxlvLYTRw 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_catalog_category_20210607_145815    3PiyAYHRTJS4jFjHjmzfhw 1 0   0 0    208b    208b
green open stagingjumbo_almacen_catalog_product_20210621_050023            4jP3_sAeSGmDhkhoNj6ClQ 1 0   0 0    208b    208b
green open stagingjumbo_default_thesaurus_20210607_145815                  jqdw3WPZRLyjNmUnBLWVOg 1 0   0 0    208b    208b
green open stagingjumbo_almacen_catalog_category_20210607_145815           MN1EM8YeQDuR2pc-3Lif5Q 1 0 363 0 355.5kb 355.5kb
[elasti search indeces.txt](https://github.com/Smile-SA/elasticsuite/files/6689603/elasti.search.indeces.txt)

**Comment by vahonc** [comment]
Hello @jnouelccn,

Have you used the ElasticSuite module before, or you just installed it in your environment? Probably something is wrong with the general configuration, please read our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/GettingStarted).

For the indexes issue, try to remove all indexes and run full reindex:

<pre>
$ curl -XDELETE localhost:9200/*
$ bin/magento cache:flush
$ bin/magento indexer:reindex
</pre>

Also, it could be some conflicts with third-party modules, like AlgoliaSearch, Tigren_Ajaxsuite, etc, so try to disable some of them.

As for the empty admin page, please send a screenshot for a better understanding. But it also could be some issue with the configuration of the ES module, check if it was properly enabled or run `$ bin/magento setup:upgrade`.

BR,
Vadym

**Comment by jnouelccn** [comment]
Hello @vahonc 

Thank you for your reply.

We have tested it in development environment.  Now we're testing in Staging environment.

Sorry to inform you that we followed your steps and It did not work.  We also disabled all third party modules reported but it didn't work either. These are the results of bin/magento indexer:reindex:
 
```
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:00
Product Flat Data index has been rebuilt successfully in 00:00:24
Category Flat Data index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:05
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Product EAV index has been rebuilt successfully in 00:00:05
Stock index has been rebuilt successfully in 00:00:01
Inventory index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Product/Target Rule index has been rebuilt successfully in 00:00:00
Target Rule/Product index has been rebuilt successfully in 00:00:00
Catalog Search index has been rebuilt successfully in 00:00:09
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:01
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```

These are the results in the elastic search server (curl -i localhost:9200/_cat/indices):

```
green open stagingjumbo_almacen_catalog_product_20210622_193551            Fl__cSjwT3OWftVYUXWpTg 1 0   0 0    208b    208b
green open stagingjumbo_default_catalog_category_20210622_193556           ghGrcA4JQiumkiJ52n8DEQ 1 0 363 0 355.5kb 355.5kb
green open stagingjumbo_almacen_thesaurus_20210622_193558                  PUBPwSZzQLumxluYdIv2XQ 1 0   0 0    208b    208b
green open stagingjumbo_default_catalog_product_20210622_193546            ZC3866B2QcOHLWW8dNK4Mg 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_catalog_product_20210622_193551     D73ss37xRtCGQBRRJ-6s1Q 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_thesaurus_20210622_193557           pjk6jKKxSNKxfvbARX06SQ 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_product_20210622_193551  0IpsNM7ETKqfzA2wZQuvuQ 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_catalog_category_20210622_193557    0HHjkQ44Qamb4j_cMRjOkA 1 0   0 0    208b    208b
green open stagingjumbo_default_thesaurus_20210622_193557                  s92zElHVRZedd8ZKF9FL_w 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_category_20210622_193556 C9fqydJoRDqlvYg8w2oiqg 1 0 363 0 355.5kb 355.5kb
green open stagingjumbo_almacen_catalog_category_20210622_193557           XVhtLC8gTA-xU5jxky5ixQ 1 0 363 0 355.5kb 355.5kb
green open stagingjumbo_deliverystoreview_thesaurus_20210622_193557        aJFfKsy1Qr-Qqt4y23WBCA 1 0   0 0    208b    208b

```
**About the ADMIN page:**
The admin page is totally empty. No login page or redirection is happening

This is the content(source code) shown in the admin page: 

"<html><head></head><body></body></html>"

It's just blank.

Thank you.

**Comment by vahonc** [comment]
Hello @jnouelccn,

If I correctly understand you, when you try to go to the Magento BO, like `https://localhost/admin` you get an empty page and there's no login form? If it's so, I think that this problem is not linked with our module and you should check Magento logs (system.log and exception.log) for more information.

Also, you could try to re-install the ES module by installing the latest version in order to your version of Magento, for now, it's the 2.9.5 version, maybe it helps to solve your issue with indexes.

<pre>
$ composer remove smile/elasticsuite
$ composer require smile/elasticsuite ~2.9.0
</pre>

Don't forget to clean your environment with the next commands:

<pre>
$ bin/magento setup:upgrade
$ bin/magento cache:flush
$ bin/magento indexer:reindex
</pre>

BR,
Vadym

**Comment by jnouelccn** [comment]
Hello @vahonc 

Thank you for your support.

We proceeded with the suggestions but nothing changed.  Next are the results of indexing:

`green open stagingjumbo_bonostoreviewx_catalog_product_20210625_213927     yKOtCADqS_iYfHTF4JBXyQ 1 0   0 0    208b    208b
green open stagingjumbo_almacen_catalog_product_20210625_213927            OR9l2MPDQn-g5eGNdY3u-A 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_product_20210625_213926  pLrYmbMbT2yGrYOxcGkbVQ 1 0   0 0    208b    208b
green open stagingjumbo_default_catalog_product_20210625_213920            ovjwPnntRJW9xN_3IHPhkg 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_thesaurus_20210625_213936           kiS1FUyiTMqg2JCe2VMZbg 1 0   0 0    208b    208b
green open stagingjumbo_default_catalog_category_20210625_213934           dIl7HdgCTyOAGtEDjyDG8w 1 0 363 0 355.7kb 355.7kb
green open stagingjumbo_almacen_thesaurus_20210625_213937                  tXiT6y27SwWNuswrn3hDIA 1 0   0 0    208b    208b
green open stagingjumbo_bonostoreviewx_catalog_category_20210625_213935    MuNBZh-SRISYE0B2__Tlog 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_catalog_category_20210625_213935 _PzY07fHTfyhX4RdDXG_Vw 1 0 363 0 355.7kb 355.7kb
green open stagingjumbo_default_thesaurus_20210625_213936                  CmuJ8Ap-TQS_wDkK9V0meg 1 0   0 0    208b    208b
green open stagingjumbo_deliverystoreview_thesaurus_20210625_213936        f2J22-A0S1-kg9AYTT_0bQ 1 0   0 0    208b    208b
green open stagingjumbo_almacen_catalog_category_20210625_213936           fGt7bzztTJSKqh73SQ8Swg 1 0 363 0 355.7kb 355.7kb`

**Comment by romainruaud** [comment]
HI @jnouelccn 

All your **catalog_product** indices are empty according to the information you provide : they have a size of 0, and no documents at all inside.

If nothing is triggered in the logs during indexing by magento, maybe there is something in the Elasticsearch log files. Can you check if you have access to them ? They should be somewhere like /var/log/elasticsearch/

**Comment by vahonc** [comment]
Hi @jnouelccn,

Also, check the configuration of your websites, maybe there are some issues with assigned categories and products to these websites or enable/disabling or smth like that, 'cause it's very weird that all your indexes have a size of 0.

BR,
Vadym

**Comment by jnouelccn** [comment]
Thank you @romainruaud  and @vahonc  for the follow up and support.
There are no ElasticSearch logs at the location indicated.

We double check the configuration.  It's ok.  We are proceeding to create a new staging environment based on production environment to test this again.

**Comment by jnouelccn** [comment]
Hello everyone.

We have created a new STAGING Environment and proceded to implement Elastic suite but we are having the same results.  Also, the logs for Elastic are not being generated for some reason.  Please find attached below an image of the Basic Settings where we have enabled Debug mode.

Thank you.
![ELASTICSUITE_DEBUG_MODE](https://user-images.githubusercontent.com/86262436/124964462-0d678d00-dfef-11eb-834e-27b98dfa3b92.png)

**Comment by vahonc** [comment]
Hello @jnouelccn,

What is output of `$ ls -la /var/log/elasticsearch`? You don't have any log records in this place?

If you activate the Debug mode of Elasticsuite all queries will be logged into the `system.log` in Magento logs folder `<magento_root>/var/log`

Did you use local or cloud hosting? Are you sure that Elasticsearch was properly installed and configured in your environment? 

You can check it by this command `$ curl -i localhost:9200`

Finally, you could try checking your issue by changing the `Search Engine` in Magento BO (`STORES -> Configuration -> Catalog -> Catalog Search -> Search Engine`) to `Elasticsearch 7.0+`. 

If you still observe your problem, this means that something is wrong with the configuration of your environment and this does not refer to our module.

BR,
Vadym

**Comment by jnouelccn** [comment]
Hello.

Thank you for the follow up.  It seems the issue has been solved.  I will answer your questions and give you also the solution.

No we did not have any log records in /var/log/elasticsearch.  Since you mentioned that logs will be saved to system.log when  activating Debug mode we went there and found information that pointed us to the right direction.

`[2021-07-12 15:10:16] report.ERROR: Bulk index operation failed 1 times in index staging_default_catalog_product_20210712_151011 for type _doc. Error (mapper_parsing_exception) : failed to parse field [created_at] of type [date] in document with id '125020'. Preview of field's value: '0000-00-00 00:00:00'. Failed doc ids sample : 125020. [] []`

The issue is that the products had the field created_at in the table catalog_product_entity with value '0000-00-00 00:00:00' and with this value indexing was not happening.  We set the value of this field to some date and now it is indexing and it works.

Thank you.

**Comment by jnouelccn** [comment]
Hello.
Now we have another problem.  When we compile Magento (run setup:upgrade and compile) Search tries to find the Elastic Server in locahost:9200 instead of the defined server which is correctly configured in env.php and it shows on Basic Settings in Configuration.
This is really confusing.
Thanks for you help.

**Comment by vahonc** [comment]
@jnouelccn, as I understand you are using a non-default port (8080) for your Elasticsearch instead of a default 9200. I'm not sure if it's a good practice and I don't know why you don't want to use the default port. It looks like you want to find a unicorn ;-)

However, you should be sure that your Elasticsearch is properly installed and configured. For this could you show the output of this command: `$ curl -i localhost:8080` or `$curl -i 10.0.4.227:8080` and also please show your Elasstisearch config: `$ cat /etc/elasticsearch/elasticsearch.yml `. In this file you could try to set bind address for a specific IP (IPv4 or IPv6) and a custom port for HTTP.

BR,
Vadym

**Comment by jnouelccn** [comment]
Hello @vahonc 
Thank you for the follow up and support.

I confirm we are using port 8080.  Also, please know that after compilation of Magento when the error of "no alive nodes" happens when it tries to search using locahost:9200, if I go to BASIC SETTINGS for ElasticSuite in Magento Admin Configuration and just click SAVE then ElastiSuite works again.

Please see requested output of the curl command. 

`ubuntu@ip-10-0-1-75:/var/www/html$ curl -i http://10.0.0.172:8080
HTTP/1.1 200 OK
Date: Wed, 14 Jul 2021 13:09:24 GMT
Server: Apache/2.4.18 (Ubuntu)
content-type: application/json; charset=UTF-8
content-length: 542

{
  "name" : "ip-10-0-0-172",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "N7C3KoIGSc-qs41K1_Vqbg",
  "version" : {
    "number" : "7.12.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "3186837139b9c6b6d23c3200870651f10d3343b7",
    "build_date" : "2021-04-20T20:56:39.040728659Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`
Here's the contents of the elasticsearch.yml file
[elasticsearch.yml.txt](https://github.com/Smile-SA/elasticsuite/files/6816379/elasticsearch.yml.txt)

Thank you.

**Comment by vahonc** [comment]
@jnouelccn, 

The "No alive nodes found in your cluster" error message is usually means that Elasticsearch cannot be joined.

Have a look at your elasticsearch.yml:

<pre>
# ---------------------------------- Network -----------------------------------
#
# By default Elasticsearch is only accessible on localhost. Set a different
# address here to expose this node on the network:
#
network.host: "localhost"
#
# By default Elasticsearch listens for HTTP traffic on the first free port it
# finds starting at 9200. Set a specific HTTP port here:
#
http.port: 9200  
</pre>

As you can see, the default port 9200 is still used, try to change it on your custom port, save a restart Elasticsearch.

BR,
Vadym

**Comment by jnouelccn** [comment]
Hello @vahonc 
Yes, but that YML file is the configuration file in the ElasticSearch Server.  Not on the Magento Server.  FYI.

Changed the port to 8080 and this message appeared after trying to start the service:
`Job for elasticsearch.service failed because the control process exited with error code. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.`

The executed the systemctl status command and this appeared:
`ubuntu@ip-10-0-0-172:~$ systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-07-14 09:46:41 AST; 42s ago
     Docs: https://www.elastic.co
  Process: 14121 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 14121 (code=exited, status=1/FAILURE)

Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]:         at java.base/java.lang.Thread.run(Thread.java:831)
Jul 14 09:46:41 ip-10-0-0-172 systemd-entrypoint[14121]: For complete error details, refer to the log at /var/log/elasticsearch/elasticsearch.log
Jul 14 09:46:41 ip-10-0-0-172 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 09:46:41 ip-10-0-0-172 systemd[1]: Failed to start Elasticsearch.
Jul 14 09:46:41 ip-10-0-0-172 systemd[1]: elasticsearch.service: Unit entered failed state.
Jul 14 09:46:41 ip-10-0-0-172 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
`
Here's the elasticsearch.log file with recent information.
[elasticsearch.log](https://github.com/Smile-SA/elasticsuite/files/6816711/elasticsearch.log)

Thank you.

**Comment by vahonc** [comment]
@jnouelccn, according to elasticsearch.log provided by you it looks like you have a conflict with ports.
<pre>
[2021-07-14T09:46:41,270][ERROR][o.e.b.Bootstrap          ] [ip-10-0-0-172] Exception
org.elasticsearch.http.BindHttpException: Failed to bind to 127.0.0.1:8080
.
.
.
[2021-07-14T09:46:41,293][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [ip-10-0-0-172] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: BindHttpException[Failed to bind to 127.0.0.1:8080]; nested: BindException[Address already in use];
</pre>

Usually, the 8080 port is used by Apache or other WebService, therefore I told you that it's not good practice to use this port. 

Could you explain why you don't want to use the 9200 port?

BR,
Vadym

**Comment by romainruaud** [comment]
@jnouelccn that's very strange what happens after compilation. Can you check the content of your env.php and core_config_data table for settings related to elasticsuite after doing the setup:upgrade and the compilation ?

**Comment by jnouelccn** [comment]
Hello @vahonc and @romainruaud 
Thank you both for your support and follow up on this.

What you indicate could be a conflict of ports has the IP address 127.0.0.1 and the elasticsearch server is located on another server as you can see below in env.php.  Apache is not running on the Elastic Server hence not using port 8080.

Please see env.php with elastic settings in this image:
![envphp_ElasticSettings](https://user-images.githubusercontent.com/86262436/125865129-7fd9485d-1e97-4035-9db4-993e96f608ac.png)

Also, here's core_config_data on the module:
![coreconfigdata_Elastic](https://user-images.githubusercontent.com/86262436/125865206-2459c358-3779-4bbf-8409-774d8d74a3e1.png)

We checked both env.php and core_config_data after compilation and it seems the same information remains.

And one more piece of information we discovered.  If we run "bin/magento cache:clean" after compilation the problem disappears and everything goes back to normal with Elastic working correctly.

**Comment by jnouelccn** [comment]
At the end, the cache:clean solves the issue after compilation.
We managed to implement Elastic.
Thank you all.
