### ISSUE TITLE
PHP Notice during reindex

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#218]
Occured on a test instance after upgrading from 2.2.x to 2.3.x : 

```
Notice: Array to string conversion in /var/www/elasticsuite_int/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 563
ElasticSuite Category Indexing indexer process unknown error:
Notice: Array to string conversion in /var/www/elasticsuite_int/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 563
ElasticSuite Thesaurus Indexing indexer process unknown error:
Notice: Array to string conversion in /var/www/elasticsuite_int/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ClientBuilder.php on line 563
```

This line contains the following : 

```
    private function prependMissingScheme($host)
    {
        if (!filter_var($host, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED)) {
            $host = 'http://' . $host;
        }

        return $host;
    }

```

The module is configured to use ```localhost:9200``` as the host (default configuration).

This one must be investigated.

**Comment by romainruaud** [comment]
Ok,

this was due to the fact I was using ```elasticsearch/elasticsearch v2.2.1```.

It appears that the minimal version to use is ```elasticsearch/elasticsearch v2.2.3```

@afoucret I think this is due to the addition of https://github.com/Smile-SA/elasticsuite/commit/924e01ce0cbcb8932831d19d6939d83fc9533937

We should keep this in mind for users which are still running an old version of elasticsearch client, don't we ?

**Comment by afoucret** [comment]
Nope.
You should update the dependency with something like : `"elaasticsearch/elasticsearch" : "^2.2.3".`.
Composer will update the package for people using older version of `elasticsearch/elasticsearch`.

Waiting for your PR.

**Comment by afoucret** [comment]
PR #220 merged to fix this one.
