### ISSUE TITLE
Grouped product sort by price is not correct.

### ISSUE THREAD

**Issue by ganeshp29** [Smile-SA/elasticsuite#2181]
The grouped product sort by price does not work properly on the product list page. Looks like for grouped products this would be getting the lowest-priced item in the group and that's what it's sorting off of?

This issue was specific to grouped products. 

![image](https://user-images.githubusercontent.com/33414084/123271114-23208100-d51e-11eb-8d3e-da47f275c2e2.png)

### Preconditions

Magento Version : 2.3.3-p1 EE
ElasticSuite Version : 2.8.0
Environment : Developer
Third party modules : Amasty Improved Sorting

### Steps to reproduce

1. sort the product by "Price: low to high" or "Price: high to low" and check the results..

### Expected result

1. We need a grouped product need to be sort as per their grouped price. The grouped product sort by price does not need to rely on their children's product price.
2. Products in the above screenshot are sorted low to high, and the result should be like - 

$1,831.00 
$2,720.81 
$2,750.54 
$3,128.45

### Actual result

1. 
![image](https://user-images.githubusercontent.com/33414084/123271542-92967080-d51e-11eb-90bb-c9d927fabd35.png)

Products in the screenshot are sorted low to high but prices are (in order of screenshot)

1. $2,750.54 
2. $3,128.45
3. $3,128.45
4. $1,831.00 

A possible reason for the issue could be that the prices of the children's products are not being used in the logic for sorting.

**Custom module implemented by Us**

We have created a custom module to fix grouped product sort by price functionality, that creates a **grouped_price** column to store the grouped product price.

Following is the information about how this functionality has been set up.

1. We have Created the "Goed_CatalogProductsSorting" module and added a column called "grouped_price" in the "catalog_product_entity" table using install schema.
1. We have implemented the script which will run manually using the Magento command. It updates all the grouped product prices to the "grouped_price" column. Here is the command that needs to run to update product grouped_price: **php bin/magento goed:update_grouped_products_price**

1. We have  override AddAttributeToSort() function of product collection. This will execute when we sort products by price. It takes the greatest value amongst the grouped_price and min_price and stored in sorting_price which is used in the order clause while sorting ASC or DESC.
1. Also implemented CatalogProductSaveObserver functionality to update product grouped_price on product save.
1. Once everything is done, We have run the following commands for reindexing.

1. **php bin/magento indexer:reindex amasty_sorting_bestseller amasty_sorting_most_viewed**
1. **php bin/magento indexer:reindex catalogsearch_fulltext catalog_product_attribute catalog_product_flat**

The above custom module code implementation working fine if we don't have elastic search implemented on Magento  store. If we will enable the Elastic Suite/search then it's not working properly.

**Comment by vahonc** [comment]
Hi @ganesh-ecsion,

As I can see you are using a third-party module like Amasty Improved Sorting. Could you try to disable it and check it out again?

It could be possible that our module and another one working on the same area (filtration, layered navigation, etc) and it's unlikely that they will function correctly. Also, your problem could be linked to your custom theme if it overrides a default sorting of the Magento.

BR,
Vadym

**Comment by ganesh-ecsion** [comment]
Hi @vahonc,
Thanks for the response,

I have disabled the third-party module Amasty Improved Sorting and checked the grouped product sort by price functionality, But still, it's not working.  
Grouped products are using the lowest priced product in the group for the price sort. We want it to be sort based on whole grouped product price, not depend on the lowest price of product associated with that grouped product.

**Comment by romainruaud** [comment]
Hi @ganesh-ecsion 

Is your "grouped_price" attribute indexed in Elasticsearch ? That's the first thing to do. It should also be "sortable".

Then you'll need to use specifically this field when sorting by price, otherwise the engine will use "price" which might be incorrect in your case if I understand properly.

regards

**Comment by romainruaud** [comment]
Hi @ganesh-ecsion 

Is your "grouped_price" attribute indexed in Elasticsearch ? That's the first thing to do. It should also be "sortable".

Then you'll need to use specifically this field when sorting by price, otherwise the engine will use "price" which might be incorrect in your case if I understand properly.

regards

**Comment by ganeshp29** [comment]
Hi @romainruaud 
The "grouped_price" is not an attribute, It's a custom field that I have created in the "catalog_product_entity" table using install schema.

After opening the link - http://localhost:9200/magento2*/product/_search?pretty, I got the following result. please check the screenshot below -

![image](https://user-images.githubusercontent.com/33414084/123974267-20200780-d9da-11eb-9875-a6368be7f751.png)

Using this link - http://localhost:9200/_all?pretty, I got the following result. Please check screenshot below-

![image](https://user-images.githubusercontent.com/33414084/123974844-9290e780-d9da-11eb-9fda-573c73d57908.png)

I have overridden the "AddAttributeToSort" method using the Plugin concept and set custom sort order(By sorting_price). It is working fine when Elastic Suite is disabled, But after enabling it and use Elastic Search, it does not work properly.

Here is my code.

```
public function aroundAddAttributeToSort(\Magento\Catalog\Model\ResourceModel\Product\Collection $subject, $result, $attribute, $dir)
    {
 
		if ($attribute == 'price') {

			$subject->getSelect()->columns("GREATEST(e.grouped_price, price_index.min_price) AS sorting_price");
			$subject->getSelect()->order("sorting_price {$dir}");
        }
		
        return $result;
    }
```

Could you please check and suggest any solution to fix this issue?

**Comment by romainruaud** [comment]
Hello,

first of all, you have to remain that the workflow when retrieving a product list from the engine is : 

The workflow here is actually the following :

    1 : aggregating all filters (if any) and all sort orders (if any)
    2 : compute this into the Elasticsearch query
    3 : ask Elasticsearch for matching product Ids
    4 : put these product Ids into the SQL query filter
    5 : return the collection

So the sorting must be sent to the ElasticSearch server. Like any other sorting mechanism, the search engine should do this and this cannot be done in SQL (like with `getSelect()->order()`) because the SQL query will alway be filtered with the first page of product Ids matching the query : it would only sort **among** this list of product ids. That's what you are doing with your proposal.

Your field `grouped_price` should be sortable. If that's not an attribute, you have to do this with XML configuration : https://github.com/Smile-SA/elasticsuite/wiki/Indexing#fields

After this, you have to clear the cache and proceed a full reindex.

Then in your plugin, probably just `$subject->setOrder('grouped_price', $direction)` will be enough for the engine to sort appropriately.

**Comment by ganeshp29** [comment]
Hi @romainruaud 

I have followed the workflow you suggested for sort by grouped_price. but it's not working properly. The products not getting sort by the custom field "grouped_price". 

I have implemented it to overridden Toolbar.php using the plugin concept. Please check the following code implementation.

**di.xml**

```
<type name="Magento\Catalog\Block\Product\ProductList\Toolbar">
        <plugin name="goed_custom_block_toolbar" type="Goed\CatalogProductsSorting\Plugin\Catalog\Block\Toolbar" />
</type>
```

**Toolbar.php**

```
<?php
namespace Goed\CatalogProductsSorting\Plugin\Catalog\Block;

class Toolbar
{

    /**
    * Plugin
    *
    * @param \Magento\Catalog\Block\Product\ProductList\Toolbar $subject
    * @param \Closure $proceed
    * @param \Magento\Framework\Data\Collection $collection
    * @return \Magento\Catalog\Block\Product\ProductList\Toolbar
    */
    public function aroundSetCollection(
    \Magento\Catalog\Block\Product\ProductList\Toolbar $subject,
    \Closure $proceed,
    $collection
    ) {
    $currentOrder = $subject->getCurrentOrder();
    $result = $proceed($collection);

    if ($currentOrder) {
        $joinConditions = 'e.entity_id = catalog_product_entity.entity_id';
        $collection->getSelect()->join(
             ['catalog_product_entity'],
             $joinConditions,
             []
            )->columns("catalog_product_entity.grouped_price");

        if ($currentOrder == 'price_desc') {
            $collection->getSelect()->columns("GREATEST(catalog_product_entity.grouped_price, price_index.min_price) AS sorting_price");
            $collection->getSelect()->order('sorting_price', 'desc');
        } elseif ($currentOrder == 'price_asc') {
            $collection->getSelect()->columns("GREATEST(catalog_product_entity.grouped_price, price_index.min_price) AS sorting_price");
            $collection->getSelect()->order('sorting_price', 'asc');
        }
    }

    return $result;
    }

}
```
 
Could you please check and suggest what is wrong with the code. Please help me out to resolve this issue.

**Comment by romainruaud** [comment]
Hi, you did not follow what I've explained in my previous comment. Especially this : 

> So the sorting must be sent to the ElasticSearch server. Like any other sorting mechanism, the search engine should do this and this cannot be done in SQL (like with `getSelect()->order()`) because the SQL query will alway be filtered with the first page of product Ids matching the query : it would only sort **among** this list of product ids. That's what you are doing with your proposal.

And therefore this : 

> Then in your plugin, probably just $subject->setOrder('grouped_price', $direction) will be enough for the engine to sort appropriately.

To summarize : don't use SQL for sorting, let the engine do the job.

I close the issue since it's way too far from just providing Open Source support. If you are interested in dedicated (paid) support through professional services, please send a mail to elasticsuite@smile.fr

Regards
