### ISSUE TITLE
Conflict due to  Categories Merchandising and Behavioral Search optimizations

### ISSUE THREAD

**Issue by vivekcoder007** [Smile-SA/elasticsuite#2183]
**Preconditions**

- Magento 2.4
- Smile Elastic Latest Version

**Steps to reproduce**
1: Use Mannual sorting for Category 
2: Set first 2 products in Mannual sorting - Out of stock
3: Create Optimizer rule to show Red color first

**Expected result**
1: Out of stock products should show as bottom as per optimizer rule

Actual result:
1: Out of stock still shows on top 2 products

**Comment by vahonc** [comment]
Hello @vivekcoder007,

Please refer to our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#creating-an-optimizer), I think that you need to add one more condition to your Optimizer rule like "Only in stock products" to display immediately products that matched your condition (Color is Red) for showing the results on top of your product list.

BR,
Vadym

**Comment by romainruaud** [comment]
@vivekcoder007 this is by design.

Manual products will always take precedence on optimizers, so if you pin an out-of-stock product to the top of the list, the product will remain here (if your store is configured to not hide out-of-stock products).

**Comment by ia-gaurav** [comment]
@romainruaud  can you help me with way for any workaround as if top pinned products are out of stock it looks bad experience

**Comment by vahonc** [comment]
@ia-gaurav could you explain more what exactly you expected in your case.

BR,
Vadym

**Comment by ia-gaurav** [comment]
@vahonc  - i have set few products in top via Categories Merchandising, but i want that if that product goes out of stock they should move to last and follow the optimizer rule.

So i want optimizer should override - Categories Merchandising in case of out of stocks, showing first product out of stock is not good approach

**Comment by vahonc** [comment]
@ia-gaurav,

As said @romainruaud above, "Manual products will always take precedence on optimizers" so for now there no solution from out-the-box and it definitely required some custom development. You could try workaround configuring to hide out-of-stock products on your site or to remove manual sort in case product goes out of stock. As for the last solution, we think it is an interesting idea, and perhaps we will include this feature in future releases of our module.

BR,
Vadym

**Comment by ia-gaurav** [comment]
thanks noted - do can u let me know file responsible for manual sorting so i could check any easy workaround
