### ISSUE TITLE
Hide products from child categories

### ISSUE THREAD

**Issue by gerrits-ecommerce** [Smile-SA/elasticsuite#2190]
Is it possible to only show the products in the currently selected category and not products included only in child categories?

**Comment by romainruaud** [comment]
Nope that's not possible out-of-the-box.

**Comment by gerrits-ecommerce** [comment]
Is there a route to make this possible, either as a planned feature for this project or by modifying the code ourselves?

Would you be interested in accepting a pull request that adds this functionality or do you not believe this functionality to be feasible

**Comment by romainruaud** [comment]
Maybe you can try setting all your categories to `is_anchor=0` instead of `is_anchor=1` which is the legacy default behavior we introduced years ago.

But I doubt this will work "everywhere", eg. I have no clues about how it will behave in a search results context.

Regards

**Comment by mehdichaouch** [comment]
I'm also looking for [this kind of feature](https://github.com/Smile-SA/elasticsuite/issues/2190#issue-934886745) and I'm interested to get more info/tips on how this could be accomplished (if it's possible)?

Regards

**Comment by Viper9x** [comment]
@romainruaud Finally, I've done this feature: Hide products from child categories in the product listing page. I can see many people looking for this feature (some other issues: [#425](https://github.com/Smile-SA/elasticsuite/issues/425), [#1972](https://github.com/Smile-SA/elasticsuite/issues/1972)) and Smile Elasticsuite currently breaks the design from magento core as your reply in issue #425 :

"
Hello,

This is a functional and design choice of our own to ensure a product will be correctly mapped into the Elasticsearch index as belonging to all categories from lower level to the upper. This way, we are able to find all products belonging to a level 1 category (let's say "Men") by searching for "men". We are also able to propose a category filter which will correctly display all products in any category below "Men" when filtering on this category. This also allow us to have virtual categories working properly at any level.
"

Do you want to implement this feature to Smile Elasticsuite and add a category attribute to manage include/exclude products from parent category and implement exclude (if attribute setting is yes) products from parent category in the product listing page? If you happy to go, I'll add a pull request for that.

Here is what I did:
- My case: Hide products from child categories from the parent category, apply for all category. Note, if products are added in both child categories and parent category, they won't be excluded.
- Implement: add an observer for event `catalog_block_product_list_collection`, then implement logic, here is execute() method:
```
public function execute(EventObserver $observer)
    {
        $productCollection = $observer->getEvent()->getCollection();

        /** @var \Magento\Catalog\Model\Category $currentCategory */
        $currentCategory = $this->registry->registry('current_category');
        $childCategoryIds = $currentCategory->getAllChildren(true);
        //Remove current category ID from $childCategoryIds
        unset($childCategoryIds[array_search($currentCategory, $childCategoryIds)]);
        $childCategoryIds = implode(',', $childCategoryIds);

        //Get all products in child categories to exclude
        $childCategoryProductsCollection = clone $productCollection;
        $childCategoryProductsCollection->joinField(
            'category_id',
            'catalog_category_product',
            'category_id',
            'product_id=entity_id',
            null,
            'left'
        )->addAttributeToFilter(
            'category_id',
            ['in' => $childCategoryIds]
        )->getSelect()->group('entity_id')->distinct(true);
        $childCategoryProductIds = $childCategoryProductsCollection->getAllIds();

        //Get all products in current category
        $currentCategoryProductsCollection = clone $productCollection;
        $currentCategoryId = $currentCategory->getId();
        $currentCategoryProductsCollection->joinField(
            'category_id',
            'catalog_category_product',
            'category_id',
            'product_id=entity_id',
            null,
            'left'
        )->addAttributeToFilter(
            'category_id',
            ['in' => $currentCategoryId]
        );
        $currentCategoryProductIds = $currentCategoryProductsCollection->getAllIds();

        //Exclude all products in child categories from current (parent) category
        // but keep products that added in current category.
        $excludeProductsIds = array_diff($childCategoryProductIds, $currentCategoryProductIds);
        $productCollection->addFieldToFilter(
            'entity_id',
            ['nin' => $excludeProductsIds]
        );

        return $this;
    }
```

I didn't have time to test if it breaks virtual category logic or not as I don't use virtual category feature, if you happy to implement this feature, could you confirm this?

**Comment by itm-development** [comment]
@TuVanDev  were you able to solve this?

**Comment by zexperto** [comment]
@TuVanDev were you able to implement this?
