### ISSUE TITLE
Pagination doesn't work on Magento 2.4.2 EE

### ISSUE THREAD

**Issue by TdAmi** [Smile-SA/elasticsuite#2193]
### Preconditions

Wampserver - PHP 7.4.9

Magento Version : 2.4.2 EE - Recently upgrade from 2.3.5-p1 EE

ElasticSearch Version : 7.7.0

ElasticSearch plugins :
`
analysis-icu
analysis-phonetic
`

ElasticSuite Version : 2.10.4

Environment : Developer

Third party modules : /

### Steps to reproduce

1. During navigation on a product listing, page number and items per page are ignored. Pagination is correcly showned but we can also see all products no mater the page size and page number.

### Expected result

1. Showing the correct products on each pages

### Actual result

![2021-07-02 16_52_34-Produits _ Comptoir des pros](https://user-images.githubusercontent.com/68944547/124292979-74e88d00-db56-11eb-80d0-d6c5cd7f1270.png)

Regards

**Comment by vahonc** [comment]
Hello @TdAmi,

Are you using some custom theme?

Could you switch to the default theme (Luma) and check it out again?

BR,
Vadym

**Comment by TdAmi** [comment]
Hi @vahonc,

Yes i'm using a custom theme. I have tried to switch to Luma theme and Blank theme as you said and i'm facing the same issue using them.
The items counter looks wrong too.

![2021-07-05 09_41_51-Produits _ Comptoir des pros](https://user-images.githubusercontent.com/68944547/124436112-f407dc00-dd75-11eb-8218-1274a76e225b.png)

Regards,
Anthony

**Comment by vahonc** [comment]
@TdAmi,

It's strange, previously we have some issues with pagination but they were fixed. You could check how it work on our [demo](http://demo.magento-elastic-suite.io/index.php/men/bottoms-men.html) site.

Have you checked if there no any overrides for this?

Also, please check this setting in Magento BO:

![07-05-2021 configuration settings stores magento admin](https://user-images.githubusercontent.com/67791361/124440185-08060a80-dd83-11eb-8583-89181d998ae6.png)

BR,
Vadym

**Comment by romainruaud** [comment]
Yep, I cannot reproduce it either on our demo site : http://demo.magento-elastic-suite.io/index.php/men/tops-men.html

**Comment by TdAmi** [comment]
@vahonc,

I have checked in our Magento BO, this setting is ok.

We have many overrides but aparently none about this. I have tried to remove some of thems, with no effect.

Maybe it can be due to the use of Magento Commerce and not the open source version ?

**Comment by vahonc** [comment]
I've checked the pagination issue on both my local environments with Magento 2.4.2 CE and EE versions and ES 2.10.4. 

In all cases, I can't reproduce any issue with it. pagination and items counter are worked as expected.

BR,
Vadym

**Comment by rikwillems** [comment]
@TdAmi I'm running into the same issue. I've disabled `Anowave_Ec` module and that fixes the issue. Now I will start  research on what the exact issue is.

**Comment by TdAmi** [comment]
@vahonc @rikwillems Thanks for your replies.

I finally found that disabling `Trustpilot Reviews` module fixes the issue. Trustpilot have released a new version of this module (2.6.560) that solve this issue.

**Comment by vahonc** [comment]
@TdAmi, I'm glad that you found the cause of your problem.

Yes, this is good advice: always check all third-party modules that are installed in your stores and make sure that they are up-to-date.

BR,
Vadym
