### ISSUE TITLE
magento 2.2 catagory product can't dispaly in front-end 

### ISSUE THREAD

**Issue by cha80** [Smile-SA/elasticsuite#2203]
### Preconditions

Magento Version :magento ce 2.2.11

ElasticSuite Version :2.6.10

Environment : developer mode 

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.
![image](https://user-images.githubusercontent.com/56351661/125382885-19759500-e3c9-11eb-8228-a3bd0258c2f0.png)

### Actual result

1. [Screenshot, logs]
We can't find products matching the selection
![image](https://user-images.githubusercontent.com/56351661/125383593-38c0f200-e3ca-11eb-9d2b-d234931a2c37.png)
and now i face this problem
![image](https://user-images.githubusercontent.com/56351661/125427041-d1fccbec-85d8-4933-ac94-c3aaa5550b91.png)

**Comment by vahonc** [comment]
Hello @cha80,

According to your description, it's not really clear which operations caused your issue. So, we need more details, like do you use an early ES module or just installed it, are you faced with this bug the first time, are you noticed this issue in all categories or just in one specific, have you installed some 3rd-party modules, etc.

For this moment I can only suggest you try to do the following things in an attempt to fix it:

- Re-indexing all
- Checking Visibility is set to Catalog & Search for all products
- Checking Status is set to Enabled for all products
- Checking Inventory is greater than 0 and status is set to 'In Stock' for all products
- Checking Website is set to base for all products
- Flushing all Caches
- Switching to the default Luma theme to see if it was a theme bug.

BR,
Vadym

**Comment by cha80** [comment]
and now i solve the previos problem 
and i face the problem like below

![image](https://user-images.githubusercontent.com/56351661/125443897-c0bc864d-258f-4f77-882b-e91161681010.png)

**Comment by vahonc** [comment]
@cha80, I suppose that you are using some custom theme. You could try to switch to the default Luma theme to see if it's a theme bug, but don't forget to flush your cache, re-index all, and re-run `php bin/magento setup:static-content:deploy`

Here's a [similar issue](https://github.com/Smile-SA/elasticsuite/issues/91). Most likely you need to solve the styles conflicts in your custom theme by yourself because we don't provide support for the compatibility of our modules with the custom themes.

BR,
Vadym

**Comment by cha80** [comment]
i use Porto theme   ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月13日(星期二) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Smile-SA/elasticsuite] magento 2.2 catagory product can&#39;t dispaly in front-end  (#2203)

**Comment by romainruaud** [comment]
Hello @cha80 

This topic is already covered in #91 and #1112

Regards

**Comment by cha80** [comment]
a plugin cause this problem when i remove it 
it work fine
