### ISSUE TITLE
Having Issue in save selected attribute values in virtuat category rule

### ISSUE THREAD

**Issue by ds-mukeshsoni** [Smile-SA/elasticsuite#2206]
Hi Support,

I am editing virtual category rule in magento category but when I am selecting attribute in rule like "brand" is one of ... I am able to select multiple values from multiselect field but when I click on save category values are not saved it shows only previous selected attribute options. Also here brand attribute is Dropdown type attribute defined in attribute. This is also not working for multselect type attributes in admin.

### Preconditions
I am using Magento ver. 2.3.3 and Smile_ElasticsuiteVirtualCategory" version is 1.4.1

**Note from @romainruaud : I removed plain-text logins and passwords**

Magento Version : 2.3.3 CE

ElasticSuite Version : ~~2.1.0~~ 2.8.5

Environment : developer mode
The above information provided you is of staging site which is in developer mode.

### Steps to reproduce
1. Create a virtual rule in admin category.
2. Select a attribute in conditions with "is one of" and select more then one values from multiselect and save category.
3. Now edit the category and edit rule in virtual category here when you select more options in multi select it will show you selected but when you save the category all newly added options will not show.

### Expected result
1. When we update attribute options selected in virtual category they should be updated in the selected virtual rule and saved.

### Actual result
editing virtual category rule in magento category but when I am selecting attribute in rule like "brand" is one of ... I am able to select multiple values from multiselect field but when I click on save category values are not saved.

![virtual-category-issue-1](https://user-images.githubusercontent.com/15997176/125909175-d3ef6be1-239c-4241-a6ea-b38287b57b32.png)
![virtual-cat-edit-issue2](https://user-images.githubusercontent.com/15997176/125909183-905a575d-98b5-4e3c-a2fc-8564367e430b.png)

Thanks
Mukesh

**Comment by vahonc** [comment]
Hello @ds-mukeshsoni,

As I can see your project have a lot of customizations and 3rd-party modules (Amasty, etc). Perhaps some of them could be affected on your problem.

I've tried to edit a virtual category rule for the Brands category and the behaviour was strange, sometimes it adds a new option that I selected sometimes not added after saving the category. Maybe it is related to the configuration of this attribute or may be linked to some limitation for options of this attribute, cause as I can see the brand attribute have a lot of options for selection.

So could you provide more details about your Magento instance, especially if you are using any third-party extensions?

Also please provide an extract of the queries that are being sent to ES when you are editing your virtual category. You can get it from the `system.log` file if you activate the Debug mode of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Enable Debug mode`.

BR,
Vadym

**Comment by ds-mukeshsoni** [comment]
Hi Support,

List of third party modules which are used to customization in site are as below:
	'Amasty_BannersLite' => 1,
	'Amasty_Base' => 1,
	'Amasty_Geoip' => 1,
	'Amasty_CheckoutGraphQl' => 1,
	'Amasty_Conditions' => 1,
	'Amasty_CommonTests' => 1,
	'Amasty_CommonRules' => 1,
	'Amasty_CronScheduleList' => 1,
	'Amasty_CrossLinks' => 1,
	'Amasty_Feed' => 1,
	'Amasty_Checkout' => 1,
	'Amasty_GiftCard' => 1,
	'Amasty_Label' => 1,
	'Amasty_MegaMenu' => 1,
	'Amasty_Meta' => 1,
	'Amasty_Mostviewed' => 1,
	'Amasty_Oaction' => 1,
	'Amasty_Ogrid' => 1,
	'Amasty_ProductAttachment' => 1,
	'Amasty_Preorder' => 1,
	'Amasty_Pgrid' => 1,
	'Amasty_Promo' => 1,
	'Amasty_Rgrid' => 1,
	'Amasty_SalesRuleWizard' => 1,
	'Amasty_SeoHtmlSitemap' => 1,
	'Amasty_SeoSingleUrl' => 1,
	'Amasty_SeoRichData' => 1,
	'Amasty_ShippingArea' => 1,
	'Amasty_ShippingTableRates' => 1,
	'Amasty_Shiprestriction' => 1,
	'Amasty_Shiprules' => 1,
	'Amasty_StorePickup' => 1,
	'Amasty_Storelocator' => 1,
	'Amasty_Xlanding' => 1,
	'Amasty_XmlSitemap' => 1,
	'Clearpay_Clearpay' => 1,
	'Cloudways_Mymodule' => 1,
	'Craftyclicks_Clicktoaddress' => 1,
	'Craftyclicks_Ukpostcodelookup' => 1,
	'CtiDigital_AmastyPromoText' => 1,
	'CtiDigital_Backend' => 1,
	'FireGento_FastSimpleImport' => 1,
	'CtiDigital_CustomLandingPage' => 1,
	'CtiDigital_DPDExport' => 1,
	'CtiDigital_DateOfBirthCheck' => 1,
	'CtiDigital_Migration' => 1,
	'CtiDigital_NavatronConfigurator' => 1,
	'CtiDigital_ProductIcons' => 1,
	'CtiDigital_ProductStock' => 1,
	'CtiDigital_QtyStepper' => 1,
	'CtiDigital_ShowProductSaleSizes' => 1,
	'CtiDigital_SizeGuideAttribute' => 1,
	'CtiDigital_Widgets' => 1,
	'CtiDigital_WineAttributes' => 1,
	'Cti_BuildVersion' => 1,
	'Cti_Hotjar' => 1,
	'Ctidigital_Banner' => 1,
	'Ctidigital_CookieNotification' => 1,
	'Ctidigital_GoogleOptimize' => 1,
	'Dhlexpress_Services' => 1,
	'Dotsquares_Allowpdf' => 1,
	'Dotsquares_Amastygrid' => 1,
	'Dotsquares_AutoInvoice' => 1,
	'Dotsquares_Bundleoptionskus' => 1,
	'Dotsquares_CategoryAttribute' => 1,
	'Dotsquares_CategoryWidget' => 1,
	'Dotsquares_Checkoutsummary' => 1,
	'Dotsquares_Contactmessage' => 1,
	'Dotsquares_Custom' => 1,
	'Dotsquares_CustomPageLayout' => 1,
	'Dotsquares_Deliverylocation' => 1,
	'Dotsquares_DisableFrontCheckMoneyOrder' => 1,
	'Smile_ElasticsuiteCore' => 1,
	'Dotsquares_Foodpair' => 1,
	'Dotsquares_Guntrader' => 1,
	'Dotsquares_ImportExport' => 1,
	'Dotsquares_Order' => 1,
	'Dotsquares_Paypalorderreport' => 1,
	'Fooman_EmailAttachments' => 1,
	'Dotsquares_RestrictShippingMethod' => 1,
	'Dotsquares_ShippingStore' => 1,
	'Dotsquares_T2T' => 1,
	'Sivajik34_CustomFee' => 1,
	'MageVision_UpdateOrderEmailAddress' => 1,
	'Dotsquares_Vivinorating' => 1,
	'Ebizmarts_MailChimp' => 1,
	'EthanYehuda_CronjobManager' => 1,
	'Experius_EmailCatcher' => 1,
	'FME_SeoImagesAltTag' => 1,
	'CtiDigital_Configurator' => 1,
	'Fooman_PdfCore' => 1,
	'Fooman_PdfDesign' => 1,
	'Fooman_PrintOrderPdf' => 1,
	'Fooman_PdfCustomiser' => 1,
	'Dotsquares_PdfCustomiser' => 1,
	'Klarna_Core' => 1,
	'Klarna_Ordermanagement' => 1,
	'Klarna_Kp' => 1,
	'Magento_PaypalReCaptcha' => 1,
	'MSP_TwoFactorAuth' => 1,
	'MagePal_GmailSmtpApp' => 1,
	'Dotsquares_UpdateOrderEmailAddress' => 1,
	'Magebees_Attribute' => 1,
	'Magebees_Products' => 1,
	'Magefan_Community' => 1,
	'Magefan_Blog' => 1,
	'Magefan_WysiwygAdvanced' => 1,
	'Mageplaza_Core' => 1,
	'Mageplaza_DeleteOrders' => 1,
	'Mageplaza_ImageOptimizer' => 1,
	'Mageside_CustomShippingPrice' => 1,
	'Magezon_Core' => 1,
	'Magezon_Builder' => 1,
	'Magezon_Newsletter' => 1,
	'Magezon_PageBuilder' => 1,
	'Magezon_PageBuilderIconBox' => 1,
	'Magezon_PageBuilderPageableContainer' => 1,
	'Magezon_PageBuilderPreview' => 1,
	'Mconnectmedia_CmsPageCanonicalUrl' => 1,
	'Mirasvit_Core' => 1,
	'Mirasvit_Dashboard' => 1,
	'Mirasvit_Report' => 1,
	'Mirasvit_ReportBuilder' => 1,
	'Mirasvit_Reports' => 1,
	'Nublue_Navatron' => 1,
	'OlegKoval_RegenerateUrlRewrites' => 1,
	'Reviewscouk_Reviews' => 1,
	'Dotsquares_Untickbillingsameasshipping' => 1,
	'Smile_ElasticsuiteAdminNotification' => 1,
	'Smile_ElasticsuiteCatalog' => 1,
	'Smile_ElasticsuiteCatalogRule' => 1,
	'Smile_ElasticsuiteCatalogOptimizer' => 1,
	'Smile_ElasticsuiteVirtualCategory' => 1,
	'Smile_ElasticsuiteTracker' => 1,
	'Smile_ElasticsuiteSwatches' => 1,
	'Smile_ElasticsuiteThesaurus' => 1,
	'Smile_ElasticsuiteAnalytics' => 1,
	'Dotsquares_Extendvirtualcategoryrule' => 1,
	'WeSupply_Toolbox' => 1,
	'WeltPixel_Backend' => 1,
	'WeltPixel_GoogleTagManager' => 1,

 
The behavior of brand selection in attribute I observed is When we select first option the ajax (https://cadman.projectstatus.co.uk/cadadmin/virtualcategory/category_virtual/preview/ajax/1/store/3/?isAjax=true) for preview will execute and saves the value also when we deselect all previous values and select again the it runs ajax call and saves values when we save category. This strange behavior is not for particular attribute it is same for other options like color etc.

The extract of the queries that are being sent to ES after enabling debug mode I am attaching the logs generated while updating brand option selection and save category.

[debug.log](https://github.com/Smile-SA/elasticsuite/files/6838480/debug.log)
[system.log](https://github.com/Smile-SA/elasticsuite/files/6838483/system.log)

Thanks
Mukesh

**Comment by vahonc** [comment]
@ds-mukeshsoni as I told you before your project has a lot of customizations and 3rd-party modules. Therefore it's hard to say what exactly could cause this issue. 

According to the lists of the 3rd-party modules provided by you, I think that one of them - Dotsquares_Extendvirtualcategoryrule could somehow be affected on this. Could you please try to disable it and check again your issue?

BR,
Vadym

**Comment by ds-mukeshsoni** [comment]
Hi Vadym,

I have tried to disable all customizing extensions including Dotsquares_Extendvirtualcategoryrule but new options added in virtual rule is not saving.
Please suggest if any other thing which can fix this issue.

Thanks
Mukesh

**Comment by muksSoni** [comment]
Hi Vadym,

Have you got the chance to check the issue cause. Please provide some suggestion regarding issue fix for files need to check for this. There is no error in javascript console but preview ajax is running for some attribute options and not working for other options in same attribute. Once this preview ajax is run then changes reflect otherwise not.

Thanks
Mukesh Soni

**Comment by vahonc** [comment]
@muksSoni, I was able to reproduce this bug even on the latest version of ES module, seems that's something that we could miss from the beginning. I'll try to play a workaround on this and investigate this issue deeper.

BR,
Vadym

**Comment by walkwizus** [comment]
Hi !

We have the same issue with Magento 2.4.3-p1 and the latest version of ElasticSuite.

**Comment by romainruaud** [comment]
PR https://github.com/Smile-SA/elasticsuite/pull/2388 fixed this issue.

Regards
