### ISSUE TITLE
Categories displaying wrong products if "Display Category Filter" set to "No"

### ISSUE THREAD

**Issue by braders** [Smile-SA/elasticsuite#2207]
_This is related to https://github.com/Smile-SA/elasticsuite/issues/1925, and possibly a duplicate However, I am opening a new ticket as that ticket is closed, and the problem exists on the latest plugin version._

We were experiencing an issue where each category was displaying the full catalog (i.e. not just the products within that category). Sorting by "Position" moved the products in the category to the top of the list, but products from other categories were still shown.

We found that this was resolved by setting "Display Category Filter" (Config -> Catalog -> Catalog -> Layered Navigation) to "No". We have the category_ids attribute set to now show in layered navigation, and so the layered navigation still does not show categories.

### Preconditions
Magento Commerce Cloud
Magento ver. 2.4.1

ElasticSuite Version :2.10.4

Environment: Observed in both developer and production mode

### Expected result
Categories should show the correct products, regardless of the "Display Category Filter" configuration.

### Actual result
Category pages showed all products, from all categories. Note that search results pages continued to work correctly.

**Comment by vahonc** [comment]
Hello @braders,

We need more details about your environment. Are you using some custom theme or 3rd-party modules that can be affected on your issue?

BR,
Vadym

**Comment by braders** [comment]
Hi Vadym,

Thanks for the quick response. 

We're using a custom theme (built on top of blank), and a number of custom modules. 

We have a number of custom modules, but the two that seem most relevant are Mageplaza_AjaxLayer and Amasty_Xsearch (which provides some optimised UI for the search page and autocomplete).

Thanks,
Bradley

**Comment by vahonc** [comment]
@Bradley, could you try to disable these modules (if it's possible) and check again if your issue is still relevant?

BR,
Vadym
