### ISSUE TITLE
Issue after reindex the indexer

### ISSUE THREAD

**Issue by jucar21** [Smile-SA/elasticsuite#2208]
### Preconditions
Ubuntu 18.04
PHP 7.3
Magento Version : Magento CE 2.3.7
ElasticSuite Version : ~2.9
ElasticSearch Version : 6.6.1
Environment : Development

Magento has been upgraded from 2.2.11 to 2.3.7
### Steps to reproduce
1. service elasticsearch restart
2. php bin/magento indexer:reindex elasticsuite_categories_fulltext

### Expected result
1. successful reindex

### Actual result
1. ElasticSuite Category Indexing indexer process unknown error:
Warning: trim() expects parameter 1 to be string, array given in .../www/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php on line 202

> if ($this->usesSource($attribute)) {
>             $optionTextFieldName = $this->getOptionTextFieldName($attributeCode);
>             $optionTextValues    = $this->getIndexOptionsText($attribute, $storeId, $value);
>             // Filter empty values. Not using array_filter here because it could remove "0" string from values.
> line202->            $optionTextValues    = array_diff(array_map('trim', $optionTextValues), ['', null, false]);
>             $optionTextValues    = array_values($optionTextValues);
>             $values[$optionTextFieldName] = $optionTextValues;
>         }

This issue was not happening under magento 2.2.11 and came up when upgraded, elasticsuite has also been upgraded to latest following the Readme recommendation:

<html>
<body>

Magento >=2.3.5 Opensource (CE) / Commerce (EE) | ElasticSuite 2.9.x : composer require smile/elasticsuite ~2.9.0 | 6.x & 7.x | Yes
-- | -- | -- | --

</body>
</html>

**Comment by jucar21** [comment]
Hi,

I am trying to figure out the attribute that is failing, at the moment I am getting the following printing some information of the attribute that fails:

> attr_id: 117
> attr_name: landing_page
> attr_code: landing_page
> opt_textfield_name: option_text_landing_page
> array(1) {
>   [0]=>
>   array(2) {
>     ["value"]=>
>     string(3) "211"
>     ["label"]=>
>     string(6) "Guides"
>   }
> }

**Comment by vahonc** [comment]
@jucar21, could you provide the configuration (screenshots) of this attribute in Magento BO?

BR,
Vadym

**Comment by jucar21** [comment]
Hi,

I couldn't find how to figure out what attribute is on backend, What I have done is a control before the issue checking if the first option of $optionTextValues is string or array. and if is array just jump it.

That allows me to reindex with no issues, as it jumps that attribute, but I am not sure if that could have any consequence.

Regards

**Comment by benyatesayko** [comment]
@vahonc I've attached an export of the attribute data as I can't view this data category attributes in the admin (or at least AFAI!) [landing_page.csv](https://github.com/Smile-SA/elasticsuite/files/6916607/landing_page.csv)

The output of `$this->getIndexOptionsText($attribute, $storeId, $value)` returns a multidimensional array which as expected would cause an error in `array_diff(array_map('trim', $optionTextValues), ['', null, false])`

![Screenshot from 2021-08-02 13-01-12](https://user-images.githubusercontent.com/52029371/127858934-666fc05d-82a0-409a-8ee0-79aa28df2689.png)

**Comment by benyatesayko** [comment]
Ok, I think I've found the source of the issue, it looks to be data related

The landing_page attribute makes use of a source model, namely Magento\Catalog\Model\Category\Attribute\Source\Page. This class returns a collection cms blocks as opposed to cms pages for the getOptions method. Magento\Eav\Model\Entity\Attribute\Source::getOptionText($value) would normally find the value we're indexing in the below code, and return the array in the expected format for `array_diff(array_map('trim', $optionTextValues), ['', null, false]) `to be able to handle the string.
```
        $options = $this->getAllOptions();
        // Fixed for tax_class_id and custom_design
        if (count($options) > 0) {
            foreach ($options as $option) {
                if (isset($option['value']) && $option['value'] == $value) {
                    return isset($option['label']) ? $option['label'] : $option['value'];
                }
            }
```
In my case, I found that it was searching for an ID of a cms block that doesn't exist, which meant the option value was never found in the code above which meanta multidimensional array would be returned, which itself eventually causes the error in the issue description. I think this may be a migration issue from M1. When I have updated the landing_page attribute for all entries to use a valid cms block ID, the index completes with no issues. @jucar21  I'd be interested to know if this solves the issue for you too (and whether your site was migrated from M1?).

**Comment by vahonc** [comment]
@benyatesayko, good catch! Thank you for your investigation.

BR,
Vadym

**Comment by fritzmg** [comment]
We are having the same issue with the `brands` attribute from _MageSuite_. The `brands` attribute is a `Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend`, but `Smile\ElasticsuiteCatalog\Helper\AbstractAttribute::getIndexOptionsText` will return something like this for this attribute for a given product:

```json
[{"label":"Weingut Sigl","value":"752"}]
```

It does not appear to be related to invalid/missing references, as the referenced brand definitely exists.
