### ISSUE TITLE
Creating the AutoComplete input field using the createBlock-function produces an exception

### ISSUE THREAD

**Issue by t-eichmann** [Smile-SA/elasticsuite#2209]
### Preconditions

We use Magento 2 with a custom theme. 

Magento Version : 2.4.2

ElasticSuite Version : 2.10.5

Environment : both

Third party modules : custom theme, other modules not relevant for this bug

### Steps to reproduce
In one of our template files we want create and render the input field using the createBlock()-function of the layout, like this:
~~~
echo $block->getLayout()
     ->createBlock('Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete')
     ->setData('rendererList', $rendererList)
     ->setTemplate('Smile_ElasticsuiteCore::search/form.mini.phtml')
     ->toHtml();
~~~ 

### Expected result
Instantiate the block and render it
### Actual result
An exception occurs:
~~~
Type Error occurred when creating object: Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete, Argument 4 passed to Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete::__construct() must be of the type array, null
 given, called in /var/www/public/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
~~~

When editing the parameterlist of the constructor of  Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete so that $data has a default value of `[]` (empty array) the instantiation works as it should.

**Comment by romainruaud** [comment]
Hi @t-eichmann 

good catch, can you submit a PR to branch 2.10.x for this one ?

Regards

**Comment by t-eichmann** [comment]
I would like to, but I am new to working with Github and have no clue how to do that.

**Comment by romainruaud** [comment]
Okay, @vahonc can you propose a PR for this one then ? Should be an easy one.

Regards

**Comment by vahonc** [comment]
Ok, I'll take care of it.

BR,
Vadym
