### ISSUE TITLE
Elasticsuite 2.8.5 and higher is not compatible with magento 2.3.1, but it should be according to readme

### ISSUE THREAD

**Issue by bartoszkubicki** [Smile-SA/elasticsuite#2210]
### Preconditions

Magento Version : EE, 2.3.1

ElasticSuite Version : 2.8.5 / 2.8.6 and higher

Environment : dev mode

Third party modules : yes, but it doesn't matter

### Steps to reproduce

1. require specific version of elasticsuite 2.8.5 or higher
2. clear generated and flush cache
3. run setup:di:compile

### Expected result

1. nothing happens it works as stated in https://github.com/Smile-SA/elasticsuite#%EF%B8%8F-magento-versions-compatibility- All 2.8.* versions should be compatible with magento <2.3.5

### Actual result

1. get error on elasticsuite 2.8.5
```
"Source class "\elasticsuiteSearchResultApplier" for "elasticsuiteSearchResultApplierFactory" generation does not exist."
```

or on higher versions 

```
bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 70.0 MiB
Fatal error: Interface 'Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplierInterface' not found in /var/www/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection/SearchResultApplier.php on line 28

```

2. Readme should have correct version matrix.

**Comment by vahonc** [comment]
Hello @bartoszkubicki,

Please be aware of the warning that was added to our [2.8.5 release note](https://github.com/Smile-SA/elasticsuite/releases/tag/2.8.5). 

We had to introduced a `>= Magento 2.3.2` requirement by relying on the native class `\Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier` which does not exist in 2.3.0 and 2.3.1 and generating the following error on earlier versions:
`Source class "\elasticsuiteSearchResultApplier" for "elasticsuiteSearchResultApplierFactory" generation does not exist`.

At the moment, you should either upgrade your Magento versions, if it's possible at least up to Magento 2.3.2, or lock your Elasticsuite version to our previous [2.8.4 release](https://github.com/Smile-SA/elasticsuite/releases/2.8.4). I've checked with Magento 2.3.1 EE and ES 2.8.4 there are no errors during executing the command `$ bin/magento setup:di:compile`.

BR,
Vadym

**Comment by bartoszkubicki** [comment]
Hello @vahonc , I have already checked that and locked version on 2.8.4. It is not always possible to upgrade magento. Version matrix should be extended by adding that information.

**Comment by romainruaud** [comment]
I updated the matrix. Thank you for reporting it. Regards
