### ISSUE TITLE
Reindexation from the Admin UI

### ISSUE THREAD

**Issue by speller** [Smile-SA/elasticsuite#2216]
I've just changed the ElasticSearch host setting in the Stores -> Configuration -> ElasticSuite -> Base settings. And now I need to reindex everything. How can I do that without SSH access?

**Comment by romainruaud** [comment]
You should just clean the cache and go to Index Management, select the "Catalogsearch Fulltext index", the "Elasticsuite categories fulltext" and "Elasticsuite Thesaurus" and choose the "Invalidate" action in the action menu.

This will trigger a reindexing the next time your crontab will run. Of course this requires to have enabled the Magento crontab.

Regards
