### ISSUE TITLE
variable @autocomplete-item__border is undefined

### ISSUE THREAD

**Issue by LouiseMcMahon** [Smile-SA/elasticsuite#222]
elasticsuite 2.2.3

```[2016-11-29 11:13:25] main.CRITICAL: 
Compilation from source: 
frontend/***/***/en_GB/css/styles-l.less
variable @autocomplete-item__border is undefined in file /var/www/html/web/var/view_preprocessed/css/frontend/*****/*****/en_GB/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
28|                 border-bottom: 0;
29|             }
30|             .lib-css(border-top, @autocomplete-item__border);
31|             cursor: default;
32|             margin: 0;
33|             padding: @indent__xs @indent__xl @indent__xs @indent__s; [] [] 
```

is preventing generation of css

**Comment by LouiseMcMahon** [comment]
This is on magneto 2.1.2

**Comment by LouiseMcMahon** [comment]
To fix it i had to add the following to or theme. I would suggest having some fallback if its not defined and documenting that a bit more clearly.

```@autocomplete__background-color: @color-white;
@autocomplete__border: 1px solid @form-element-input__border-color;
@autocomplete-item__border: 1px solid @color-gray90;
@autocomplete-item__hover__color: @color-gray91;
@autocomplete-item-amount__color: @color-gray60;```

**Comment by romainruaud** [comment]
Hello @LouiseMcMahon 

Could you describe how is configured your "Design" ? Which theme do you use ? A custom one from scratch ?

The ```@autocomplete-*``` variables are defined into the Luma theme, but also in the Blank theme. 

If you are derivating one of those 2 themes you are not supposed to face this issue.

Let us know,

Regards

**Comment by LouiseMcMahon** [comment]
Hi @romainruaud its a completely custom one and even it it was based off blank theme we tend to remove unused variables.

**Comment by romainruaud** [comment]
Well... I'm afraid that I don't get it. Theses variables are not unused because they are used by our extension, but also by standard Magento's autocomplete box, so you should not have removed them from the blank theme, don't you ?

**Comment by afoucret** [comment]
Hi @LouiseMcMahon,

As explained by @romainruaud, the variables are present in standard Magento theme.
We can not handle heavy customizations done in custom themes by the users of the module and only ship something that works out of the box on a standard Magento.

Additionally, we can not propose our own default values for variables that are expected to be present, since it would override the values provided by the default theme and future changes in the default theme would not be applied then.

I fear that you will to have to live with this ...

**Comment by EliasKotlyar** [comment]
I have encountered the same bug - custom theme which was forked from a older blank-theme.
I could solve this by creating the file app/design/frontend/<Theme>/base/Magento_CatalogSearch/web/css/source/_module.less and putting the instructions inside.

**Comment by plalgiush** [comment]
> To fix it i had to add the following to or theme. I would suggest having some fallback if its not defined and documenting that a bit more clearly.
> 
> ```
> @autocomplete__border: 1px solid @form-element-input__border-color;
> @autocomplete-item__border: 1px solid @color-gray90;
> @autocomplete-item__hover__color: @color-gray91;
> @autocomplete-item-amount__color: @color-gray60;
> ```

at some points, you may also need to add the line @autocomplete__background-color: @color-white;
