### ISSUE TITLE
index_not_found_exception with multiple Elasticsearch servers

### ISSUE THREAD

**Issue by torhoehn** [Smile-SA/elasticsuite#2226]
### Preconditions

Magento Version : 2.4.2-p1

ElasticSuite Version : 2.10.4

Environment : Production mode

Third party modules :

### Steps to reproduce

1. Have one configured Elasticsearch server in `Elasticsearch Servers List`, e.g. `localhost:9200`
2. Run bin/magento indexer:reindex catalogsearch_fulltext, Index is rebuilt successfully
3. Configure a second Elasticsearch server in `Elasticsearch Servers List`, e.g. `localhost:9200,localhost:9202`

### Expected result

1. Index should be rebuilt successfully

### Actual result

1. Exception will be thrown:
```
Catalog Search index process unknown error:
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [magento2_default_catalog_product_20210805_190512]","resource.type":"index_or_alias","resource.id":"magento2_default_catalog_product_20210805_190512","index_uuid":"_na_","index":"magento2_default_catalog_product_20210805_190512"}],"type":"index_not_found_exception","reason":"no such index [magento2_default_catalog_product_20210805_190512]","resource.type":"index_or_alias","resource.id":"magento2_default_catalog_product_20210805_190512","index_uuid":"_na_","index":"magento2_default_catalog_product_20210805_190512"},"status":404}
```

**Comment by vahonc** [comment]
Hello @torhoehn,

First, check if all is good with your Elasticsearch instances like `curl -i http://localhost:9200/` and `curl -i http://localhost:9202/` and if your Indices settings are properly configured according to this [refer](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#indices-settings).

Also, please show the output you get from `curl -XGET localhost:9200/_cat/indices?v` and `curl -XGET localhost:9202/_cat/indices?v`

And the last, you could enable Debug Mode for the ES queries in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode` and run full re-index again, after that the queries will be logged into the Magento logs (system.log and exception.log ) and you will be able to see if there are any logged errors during re-indexing. Also check the Elasticsearch server logs (`/var/log/elasticsearch/`)

BR,
Vadym
