### ISSUE TITLE
Catalog Search index process unkown error: Warning: array_merge()

### ISSUE THREAD

**Issue by gusdemayo** [Smile-SA/elasticsuite#2242]
### Preconditions

Magento Version : 2.4.1

ElasticSuite Version : 2.10.6

Environment : Development

Third party modules :

### Steps to reproduce

1. php bin/magento indexer:reset catalogsearch_fulltext
2. php bin/magento indexer:reset catalogsearch_fulltext

### Expected result

Reindex of the catalogsearch_fulltext index

### Actual result

Catalog Search index process unkown error:
Warning: array_merge(): Expected parameter 1 to be an array, string given in /app/magento/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php on line 132

**Comment by vahonc** [comment]
Hello @gusdemayo,

I've checked this issue on my test (fresh) Magento 2.4.1 EE and ES 2.10.6 and I didn't notice any problem during reset/reindex of catalogsearch_fulltext index. It looks like there is could be some issue with the data of your store. 

Could you provide more details about your environment and data, maybe check attributes configuration or Magento logs. Any information or details help us to better understand where exactly is this problem and why this error occurs.

BR,
Vadym

**Comment by gusdemayo** [comment]
@vahonc That was my thought as well, as I've been able to run the reindex all the way through on a smaller test environment, the error mostly happens on our staging environment. I've been trying to track down where the data is coming from that's running through the function in AttributeData that throws the error, is it just product attributes in the catalog_product_entity_* tables?

**Comment by romainruaud** [comment]
Yes, that's attribute data. I suggest you add some logging at the failing line, to see which attribute it is, and also what is the problematic value.

Regards

**Comment by gusdemayo** [comment]
I ran a reindex logging which attributes it was failing on, and it looks like all of attributes were product SKUs, and the ones that failed happened to be multiple products that shared the same SKU, does that sound like the cause?

**Comment by romainruaud** [comment]
That's still blurry for me.

Are you having an attribute that is called "sku" and which is storing data in catalog_product_entity_varchar table ?

**Comment by gusdemayo** [comment]
Ok so I think I fixed the data that was causing the issue, but now I get the error "No alive nodes." I already confirmed I have the correct elasticsearch container URL and settings, the version of elasticsearch is 7.6.2, and the version of elasticsuite is 2.10. I can confirm the elasticsearch instance is running, and it can be connected to via the default Magento Elasticsearch module.

**Comment by vahonc** [comment]
@gusdemayo, could you show the output of this command:

 `$ curl http://localhost:9200/_cat/indices?v`

Also, you could enable logging ES queries in:

`Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`
    
and then try to run a full reindex, all queries will be logged into the `system.log`.

BR,
Vadym

**Comment by gusdemayo** [comment]
Making a /_cat/indices request shows a bunch of default_catalog_product indices, most of which are over a gigabyte. I will run a full reindex with debug mode enabled.

**Comment by gusdemayo** [comment]
We actually had debug mode enabled already, so I looked at the logs, and see that it uses the same url all throughout without issue, and then there's suddenly a "Connection Reset By Peer" error followed by a bunch of "No alive nodes" errors. This might be an issue with the timeout/elasticsearch configuration of our host.

**Comment by gusdemayo** [comment]
@vahonc I'm wondering if the size of bulk index API requests could cause the "Connection Reset By Peer" error, is there a setting for changing how many things get indexed at a time?

**Comment by vahonc** [comment]
@gusdemayo, "Connection Reset By Peer" means that something other than the client closed the connection. However, it wasn't Elasticsearch either: Elasticsearch keeps client connections open until the client closes them. This means whatever closed the connection, it must be between the client and Elasticsearch.

I think you should check the configuration of your environment, maybe this configuration is not enough for high performance.

Have you checked logs of the Elasticsearch in `/var/log/elasticsearch/` and Apache (Nginx)?

BR,
Vadym

**Comment by romainruaud** [comment]
Yes, bulk size can matter.

You may try to reduce this parameter : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/config.xml#L33

**Comment by gusdemayo** [comment]
I tried reducing the bulk size by half and it still has the issue. The strange thing is that we're using the same managed hosting provider for the Elasticsearch 7.6 node in our staging environment where we're doing the upgrade as for the elasticsearch 6 node we'd been using before, and we've haven't seemed to have the specific "No alive nodes/Connection reset by peer" error occur there.

**Comment by romainruaud** [comment]
Hi @gusdemayo 

You might have too much "ghost" indices as your comment "Making a /_cat/indices request shows a bunch of default_catalog_product indices, most of which are over a gigabyte" let me suppose.

This might "clog" your Elasticsearch server since each index will take an amount of RAM. That could potentially explain your issues. Probably each time you had an error during the catalog search index, a remanent index was created and left behind.

First of all, you can remove all indices that have no alias. If you have a recent version of Elasticsuite, this is doable through the back-office.

You can also mass delete them with curl if needed. If by mistake you delete the "current" index used by Elasticsuite, you'll have to proceed with a full reindex after.

Regards

**Comment by gusdemayo** [comment]
Yeah, I've cleared out all the old indexes, and this is a new node that was spun up for the update

**Comment by romainruaud** [comment]
Do you have access to the Elasticsearch server logs ?

**Comment by gusdemayo** [comment]
I duplicated the environment I'd been having the issue in docker on my local machine - same MySQL version, Elasticsearch version, PHP, etc. and the reindex ran through without "Connection Reset By Peer," I think the issue is hosting configuration

**Comment by romainruaud** [comment]
Hi @gusdemayo , it seems to be a network/hosting issue according to what you describes. Unfortunately if that's the case there is not that much we can do about this :/ 

Just to clarify (before closing), is the initial issue resolved ? it was due to a data problem by your side ?
