### ISSUE TITLE
Catalog > Categories - Category View fails, showing raw SQL query for large categories

### ISSUE THREAD

**Issue by lbajsarowicz** [Smile-SA/elasticsuite#2250]
### Preconditions (*)
1. Magento 2.4.3
2. MySQL 5.7
3. PHP 7.4.23
4. ElasticSuite 2.10.6
5. Product Catalog with a Category that contains 100k+ SKUs

### Steps to reproduce (*)

1. Open Catalog > Categories
2. Head to the category with 100k+ SKUs

### Expected result (*)

1. I should be able to view Category details, including Products listed in the Category
2. Magento should never display a raw SQL query anywhere on Admin or Storefront (!)    

### Actual result (*)

1. Magento displays raw SQL query with Product IDs for Products in a Category
    ![Screenshot from 2021-09-05 00-44-17](https://user-images.githubusercontent.com/1639941/132109703-4323ae8c-c9a6-41d7-8903-ee01729fd598.png)

**Comment by romainruaud** [comment]
I've seen the issue in Magento2 repo too :) 

I guess it's an elasticsuite problem after all ? Did you trace what was triggering this query ? This looks like a call to `getSize()` somewhere in the code.

Regards

**Comment by vahonc** [comment]
@lbajsarowicz, you need to increase **max_allowed_packet**. For this, access to your Database, run this command:
`SHOW VARIABLES LIKE 'max_allowed_packet';` to check what it's value and then multiple it to 2 or 3 times as your wishes.

To perform it at a global level, you could run the command: `SET GLOBAL max_allowed_packet=xxx`

BR,
Vadym

**Comment by romainruaud** [comment]
@vahonc is right, this should fix the issue. However, I'm still curious about any stack trace we could see for this one. I'm concerned if this is a legacy Magento2 bug or if that's pure Elasticsuite fault. We might optimize something if that's by our side.

@lbajsarowicz if you have any more details, feel free !

**Comment by romainruaud** [comment]
@lbajsarowicz any update on this one ? I'm not sure it's still relevant.
