### ISSUE TITLE
jquery.ui.touch-punch missing shim

### ISSUE THREAD

**Issue by sambolek** [Smile-SA/elasticsuite#2259]
jQuery UI touch punch requires jquery UI to work. However, it seems that we have no shim set for jquery/ui.

### Preconditions

Magento Version : 2.4.3

ElasticSuite Version : 2.10.6

Environment : production

Third party modules : -

### Steps to reproduce

1. Open category page on mobile device or responsive web view (important thing to note is that touch has to be enabled)

### Expected result

1. No errors

### Actual result

1. `Uncaught TypeError: Cannot read properties of undefined (reading 'mouse')`
![Screenshot at Sep 22 11-06-51](https://user-images.githubusercontent.com/5627631/134315669-94f1c4d7-ec11-4c27-8921-ce9e9fd8d26a.png)
![Screenshot at Sep 22 11-07-08](https://user-images.githubusercontent.com/5627631/134315710-99f15ac3-a887-44a3-a22f-2c797e7d4f18.png)

**Comment by sambolek** [comment]
We're using advanced bundling via r.js as per https://www.integer-net.com/magento-2-javascript-bundling-integer-net-2/

For bundles to function properly, it's important that shims are defined if "hidden" dependency exists, like this one, where we're using a function from jquery-ui-mouse inside jquery-ui-touch-punch.

I haven't tried to reproduce on a vanilla instance, but don't think having a shim would hurt.

**Comment by romainruaud** [comment]
Ok that's more clear for me :) 

I'll merge the PR, expect a minor release next week, regards !
