### ISSUE TITLE
After 2.10.7, have some ghost indice. 

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2270]
Hello, after update to 2.10.7 last, i can see some ghost indice?

What can i do with ?

Thank you in advance.

![image](https://user-images.githubusercontent.com/17496183/135507079-ffe9565f-0d0b-461b-a2ef-6062283fd078.png)

**Comment by romainruaud** [comment]
That's not due to 2.10.7, according to the ghost indices creation date, they were created several months ago.

It happens when the reindexing process encounters an error.

You can delete them, directly through the Back-Office in the action column.

Regards

**Comment by achatpc** [comment]
Thank you.
