### ISSUE TITLE
Search SKU with hyphen and dot returns no result

### ISSUE THREAD

**Issue by sfourniero2** [Smile-SA/elasticsuite#2271]
### Preconditions

Magento Version : EE 2.3.4

ElasticSuite Version : 2.8.7
smile/module-elasticsuite-shared-catalog Version 2.8.0

Environment : Developer & Production

### What happens
We have some products with complexes SKUS than contains hyphen and dot, for example : **NOR.0707-60**

When we search with the complete Sku there's no result found. We are getting the 'Your search returned no results.'

When we search with only a part of the sku (with only one special character ex : NOR.0707 or 0707-60), the product is found. 

### Expected result

1. If we type the entire sku with dot and hyphen the product should be found

**Comment by romainruaud** [comment]
I close, this issue is too old, feel free to open a new one if the problem still persists.

However, in the meantime, the algorithm related to SKU based search improved a lot, I'm pretty confident this case would be fixed now.

Regards
