### ISSUE TITLE
Undefined index type_id in AttributeData.php on line 190

### ISSUE THREAD

**Issue by Josch-** [Smile-SA/elasticsuite#2276]
### Preconditions

Magento Version : 2.4.3
ElasticSuite Version : ~2.10.0
ElasticSearch engine: 7.15.0
Environment : developer

### Steps to reproduce

1. Installed elasticsuite
2. ran php bin/magento indexer:reindex

### Expected result

1. A flawless reindex

### Actual result

Error:

**Catalog Search index process error during indexation process:
Notice: Undefined index: type_id in /var/www/vhosts/shop.url/httpdocs/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php on line 190**

Full output

> php bin/magento indexer:reindex
> Design Config Grid index has been rebuilt successfully in 00:00:00
> Customer Grid index has been rebuilt successfully in 00:00:00
> Product Flat Data index has been rebuilt successfully in 00:00:07
> Category Flat Data index has been rebuilt successfully in 00:00:00
> Category Products index has been rebuilt successfully in 00:00:03
> Product Categories index has been rebuilt successfully in 00:00:00
> Catalog Rule Product index has been rebuilt successfully in 00:00:00
> Product EAV index has been rebuilt successfully in 00:00:00
> Stock index has been rebuilt successfully in 00:00:00
> Product Price index has been rebuilt successfully in 00:00:00
> Catalog Product Rule index has been rebuilt successfully in 00:00:00
> Catalog Search index process error during indexation process:
> Notice: Undefined index: type_id in /var/www/vhosts/shop.kedo.de/httpdocs/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php on line 190
> Search Spell-Correction index has been rebuilt successfully in 00:04:43
> Search Score Rules index has been rebuilt successfully in 00:00:00
> ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:03
> ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:01

**Comment by Josch-** [comment]
@romainruaud

Hi,

thanks a lot for your answer.

> `type_id` is a **system field** of Magento.
> This is representing product types : configurable, simple, bundle, etc ...
> If one product does not have this field, it's likely a problem of corrupted data.
> But as @vahonc pointed to me, maybe you are also having an attribute that is called "type_id" ?

I looked at the table "catalog_product_entity" - every product has the type_id "simple". There is no product without a value in the field "type_id".

Second - we don't have an attribute "type_id" in the list of attributes. I sent an extract of the system.log to @vahonc 

This is strange and I hope we'll solve this.

**Comment by romainruaud** [comment]
Okay, can you add some logging at the problematic line and see what is the content of `$productData` ?

Regards

**Comment by Josch-** [comment]
@romainruaud - I don't understand what you mean with "add some logging at the problematic line". How can I do that and in which file? Do you mean the system.log?

Best wishes

**Comment by vahonc** [comment]
Hello @Josch- 

You could add some logging at the problematic line and see what is the content of `$productData` according to your error log:
> Notice: Undefined index: type_id in /var/www/vhosts/shop.kedo.de/httpdocs/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php on line 190

BR,
Vadym

**Comment by romainruaud** [comment]
@Josch- Something like : 

```
$writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
$logger = new \Zend\Log\Logger();
$logger->addWriter($writer);
$logger->info(print_r($productData, true));
```
