### ISSUE TITLE
RFC : AJAX Layered Navigation

### ISSUE THREAD

**Issue by nghelo** [Smile-SA/elasticsuite#228]
Hi,
just an information...It is planned the possibility to enable the layered navigation through AJAX ?

Best regards and many congratulations for your fantastic suite.

**Comment by afoucret** [comment]
Hi @nghelo,

Currently we do not plan to move forward on AJAX loading of the layered navigation.
The only AJAX feature we plan to deliver in the next releases is about facet display (embedded search engine into the facet and show more / less feature).

Actually getting this done is quite hard work and would require us to modify large parts of Magento standard design / theme. We do not want to modify this area in such proportion to keep Magento as upgradable as possible.
There is also SEO considerations that should not be forgotten that requires a lot of work during the design of such a feature.

But, we are open minded and we listen our community. If this request collect a lot of support by the community, we could implement it in the future. We also consider PRs if you want to work on this !!!!

**Comment by romainruaud** [comment]
I obviously +1 Aurélien's answer.

Imho, if we do this feature in the future, it has chances to be an external module for ElasticSuite, and not bundled as default in the "core" suite.

By the way, thank you for submitting this RFC and using our module.

Best regards,

**Comment by dharake** [comment]
Hi there,

Thanks for the fantastic suite of modules. I am having difficulty with one aspect, I already use a 3rd party module for layered navigation which I prefer to keep as it uses AJAX. Is there a way that I can just disable the layered navigation feature? I have tried with no luck so far.

Best Regards

**Comment by webtekindo** [comment]
I also think we should be able to disable the layered navigation if needed.

**Comment by blueflykeelo** [comment]
Anybody figure out how to disable the layered nav in ES? I bought a third party module which is conflicting

**Comment by duffner** [comment]
@afoucret and @romainruaud has any more consideration been made in the development of this feature. While the ability to use multi-select in layered navigation is a nice feature, from a user perspective it's too slow and should be able to be modified by Ajax. In general, high-end sites, ones interested in having improved search and layered navigation also want this feature.  I do agree it should be an add-on module, but I want to know if this is in your roadmap as I have 4 customers asking for it and they all are built using your suite of elastic search modules.

**Comment by duffner** [comment]
@afoucret and @romainruaud Is there any update on this request?

**Comment by afoucret** [comment]
Hi @duffner,

To be honest we have other priorities and the core team will not work on this any time soon.
It could be nice to see some code or additional module to ElasticSuite provided by the community.

**Comment by Zyles** [comment]
If you look at Aheadworks layered navigation they have ajax solved and that is an extension that does not modify your theme.

Refreshing page and moving the browser to the top is problematic with a lot of content so ajax would be a huge benefit.

**Comment by kevinvuillemin** [comment]
Hello, did you find a solution for magento 2.3 ?

**Comment by adrianalin89** [comment]
@afoucret and @romainruaud Is there any news about ajax loading being implemented on this request?

**Comment by natedawg92** [comment]
as @afoucret has confirmed that this is not a priority at the moment I did a little searching to try and find something that achieves this.

I came across https://github.com/acharrex/magento2-extension-ajax-layered-navigation which for the most part worked.

It however didn't work with ElasticSuite filters that are rendered via a knockout template, or with links that were added after this module loaded. with a little tweaking however I managed to get this to work.

see the [PR](https://github.com/acharrex/magento2-extension-ajax-layered-navigation/pull/7) on that repo that I have raised, I would appreciate any code reviews from the community and any other feedback you may have.

**Comment by romainruaud** [comment]
I close, we won't implement such things nowadays since headless Magento is becoming more and more a standard.

Regards

**Comment by kpitn** [comment]
Hi, I just create a module available here : https://github.com/Web200/magento2-elasticsuite-ajax
Actually the module is for testing purpose.
The packagist is not yet available, he can only be install by cloning repository.

If someone can test it and make some returns.

**Comment by Tahuna1** [comment]
> Hi, I just create a module available here : https://github.com/Web200/magento2-elasticsuite-ajax
> Actually the module is for testing purpose.
> The packagist is not yet available, he can only be install by cloning repository.
> 
> If someone can test it and make some returns.

Hi kpitn, 
first its a nice module.
i have made test install and on my installation if you have multiselect filter and you choose the one option its works fine but when you click an second option on the same filter attribute it don´t shows up in 'Activated filters' and also it looks like the filter options and counts on filters are not updated.

**Comment by kpitn** [comment]
Hi  @Tahuna1  sorry there was an error left.
It's fix in the last release.

You can open issue in the module repository, if you have another problem.
