### ISSUE TITLE
First setup:install with elasticsuite fail to fallback to magento elasticsearch parameters + prefix/alias not used

### ISSUE THREAD

**Issue by Teods** [Smile-SA/elasticsuite#2281]
### Preconditions

I currently want to deploy my project on standard server with apache/php/redis/elasticsearch.

The specific part is about elasticsearch, I want to host multiple client on the same instance, so I have X-Pack Security enabled with multiple role/user configured.

Magento Version : 2.4.3

ElasticSuite Version : 2.10.7

Environment : Production

Third party modules :
- yireo/magento2-replace-bundled
- opengento/module-gdpr
- hyva theme
- sample-data

### Steps to reproduce

Before every try, the database is wiped (no tables) and the code is erased with new fetch for git and composer install.

I installed magento 2 with multiple modules included (rgpd etc...) with the elastisearch standard parameters available and everything went fine, the indexes are created with the prefix/alias provided and the user/password provided worked.

`bin/magento setup:install --cleanup-database --db-host=localhost --db-name=client1 --db-user=client1 --db-password=demo --base-url="https://demo" --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.io --admin-user=admin --admin-password=123456 --language=fr_FR --currency=EUR --timezone=Europe/Paris --search-engine=elasticsearch7 --elasticsearch-host=localhost --elasticsearch-index-prefix=demo --elasticsearch-port=9200 --elasticsearch-enable-auth=1 --elasticsearch-username=demo --elasticsearch-password="123456" --cache-backend=redis --cache-backend-redis-server=localhost --cache-backend-redis-port=6301 --cache-backend-redis-db=0 --page-cache=redis --page-cache-redis-server=localhost --page-cache-redis-port=6301 --page-cache-redis-db=1 --session-save=redis --session-save-redis-host=localhost --session-save-redis-port=6301 --session-save-redis-log-level=4 --session-save-redis-db=2 --use-sample-data --use-rewrites=1`

But when I install elasticsuite and do the same, 2 problems arise : 

1. If a chose "elasticsuite" as defautl search-engine, the search-engine is not recognized and the installation fail
2. If I let "elasticsearch7" as default search-engine, the elasticsearch Magento parameters are not used to set (pass/login/alias etc...) and then the installation fail with error : 
`ElasticSuite : Unable to configure connection to Elasticsearch server : {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}`

To finish if I try with elasticsuite parameters (--es-host, --es-pass etc...) the installation process start because these parameters are taken. Unfortunately for me I need multiple index in the same elastic server and no "--es-alias" parameters exist and the indices created at installation contains the default alias "magento2" instead of mine.

I can change if afterward, but if two Magento 2 installation occurred at the exact same time, they will clash.

For me the problem comes from this file https://github.com/romainruaud/elasticsuite/blob/651b325ce6b42f1474f35d9a198d316f8c081c68/src/module-elasticsuite-core/Setup/ConfigOptionsList.php

The line 220 should be https://github.com/romainruaud/elasticsuite/blob/651b325ce6b42f1474f35d9a198d316f8c081c68/src/module-elasticsuite-core/Setup/ConfigOptionsList.php#L220 : 
`if (!$config && (array_key_exists($inputKey, $this->fallbackMapping))) {`
With array_key_exist instead of in_array, the value searched when validating data are the elasticsuite parameter. Or maybe you want to make the magento 2 elastic param the default and fallback on elasticsuite param then some other refactoring are necessary (in getClientOptions function and inside the if L220 to select the key of the array based on the value)

But when I changed that, it was not the only problem. The constructor overload the array "$fallbackMapping" with default empty value and then no matching matrix exist. 
https://github.com/romainruaud/elasticsuite/blob/651b325ce6b42f1474f35d9a198d316f8c081c68/src/module-elasticsuite-core/Setup/ConfigOptionsList.php#L80

### Expected result

1. The installation process should work with default Magento 2 parameters in fallback and take "--es" parameters only if provided.
2. The alias/prefix parameters should be active at "setup:install" and not only by config settings

I tried my best to investigate but cannot known if there was a reason to not implement "alias/prefix" on install script and if the constructor erasing the matrix is normal because you want to implement it another way.

Thanks for your help.

**Comment by romainruaud** [comment]
I updated my PR, I'm testing installing "from zero" with the following command : 

```
bin/magento setup:install --cleanup-database --db-host=localhost --db-name=magento2_test --db-user=root --admin-firstname=admin --admin-lastname=admin --admin-email=admin@admin.io --admin-user=admin --admin-password=magento123456 --language=fr_FR --currency=EUR --timezone=Europe/Paris --search-engine=elasticsuite --elasticsearch-host=elasticsearch7.lxc --elasticsearch-index-prefix=test --elasticsearch-port=9200 --elasticsearch-username=elastic --elasticsearch-password=elastic
```

Can you check also by your side with last PR modifications if that fits better ? 

Regards

**Comment by romainruaud** [comment]
This was released in latest release.

Regards
