### ISSUE TITLE
Same products in each category slider on Home page

### ISSUE THREAD

**Issue by prasad-sankey** [Smile-SA/elasticsuite#2283]
After installing the Elasticsuite extension and all it's required other extensions, I'm getting the issue that on the home page in each category slider I'm getting the same products(Please refer the below image). I cannot understand the root cause for this as in the slider configuration I do have set different categories. This issue only occurred when I installed the elastic suite as before it was working fine.

**Environment Details:**
Magento Version : CE 2.4.2-p2
ElasticSuite Version : 2.10.7
ElasticSearch Version : 7.14.0
Magento Environment : Developer
Custom Theme: Alo theme
Third party modules :
1. Magic Cart
2. Magic Product
3. Magic Menu

### Steps to reproduce
1. Installed Elasticsuite and all required other extensions and enable them.
2. Run the commands of Magento like:
		php bin/magento indexer:reset
		php bin/magento indexer:reindex
		php bin/magento setup:upgrade
		php bin/magento setup:di:compile
		php bin/magento setup:static-content:deploy -f --theme Magento/backend --theme Alothemes/market5
		php bin/magento cache:flush
3. Open the Magento website homepage.

### Expected result
Each category slider should display the products as per the category configured in its setting and not same products for all categories.

### Actual result
Same products under each category slider on the homepage
![image](https://user-images.githubusercontent.com/35484037/136647584-a41afcde-d2d1-4f23-95cd-90b3b6a07d9f.png)

**Comment by prasad-sankey** [comment]
Hi @vahonc, I tried checking the issue with different plugin for the product slider and it is displaying the data correctly. As you said the may be related to the Alo themes's magic product slider.

**Comment by romainruaud** [comment]
Compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do for your issue.

You'll have to ask Alo to provide compatibility with Elasticsuite, or switch to a more compliant widget.

Regards
