### ISSUE TITLE
Search is stopped working on frontend after selecting "Based on attribute value" from model option.

### ISSUE THREAD

**Issue by mgoswamirave** [Smile-SA/elasticsuite#2295]
The elastic suite is working fine but when we create optimizer with "Based on attribute value" from Model option it is stopped working.

### Preconditions

Magento Version : 2.3.7-p2 EE (B2B)

ElasticSuite Version : 2.9.0 

Environment : Production

Third party modules : No

### Steps to reproduce

1. Create a new optimizer. 
2. Set Model  = > Based on attribute value

![image](https://user-images.githubusercontent.com/87437246/137254073-0cbe28ec-704e-4f5c-9079-2a1ca6684b58.png)

3. Select attribute.

![image](https://user-images.githubusercontent.com/87437246/137254310-1c386a22-ee90-4876-ab6b-b05d616c4928.png)

4. Save Optimizer.
5. After selecting "Based on attribute value" from Model search is not working.

![image](https://user-images.githubusercontent.com/87437246/137255448-4f13716b-a2e1-4246-8675-884164dfc679.png)

### Expected result

1. Searching should work relative with attribute value.

**Comment by vahonc** [comment]
Hello @mgoswamirave,

It could be linked to the configuration of your attribute. According to our [Wiki](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Config/Attributes/Collection.php) if you create a New optimizer that uses configuration fieldset as "Based on attribute value" your attribute must be a decimal or integer and not a string.

Could you tell me what kind of data has your attribute?

BR,
Vadym

**Comment by vahonc** [comment]
Hello @mgoswamirave,

Sorry for the long delay. Could you tell me what `Catalog Input Type for Store Owner` you set up in your attribute? It will be more helpful if you provide more detailed settings (screenshots) of your attribute.

BR,
Vadym
