### ISSUE TITLE
Product attribute edition generate a JS error

### ISSUE THREAD

**Issue by mehdichaouch** [Smile-SA/elasticsuite#2296]
### Preconditions

Magento Version :  2.3.6.0 EE (B2B)

ElasticSuite Version : 2.9.8

Environment : Production

Third party modules : No

### Steps to reproduce

1. Log in backend
2. Go to _Store > Attributes Product_
3. Create a new attribute
4. for _Catalog Input Type for Store Owner_ choice _Text Area_
![image](https://user-images.githubusercontent.com/861701/137291332-dae286ac-4d40-4ba6-85cc-de01cf71229b.png)
5. fill all mandatory fields
6. _Save Attribute_
7. Open DevTools in console
8. Re-edit your attribute
9. Error you will get:
![image](https://user-images.githubusercontent.com/861701/137291950-3110d08a-2a46-4be6-9db5-54b82ca99be6.png)
<details>
  <summary>Error code</summary>

```
(index):2673 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at bindAttributeInputType ((index):2673)
    at HTMLDocument.<anonymous> ((index):2899)
    at fire (jquery.js:3238)
    at Object.add [as done] (jquery.js:3297)
    at jQuery.fn.init.jQuery.fn.ready (jquery.js:3548)
    at jQuery.fn.init (jquery.js:2973)
    at new jQuery.fn.init (jquery-migrate.js:241)
    at jQuery (jquery.js:80)
    at (index):2898
    at Object.execCb (require.js:1650)
```
</details>
from here :

![image](https://user-images.githubusercontent.com/861701/137292038-30624489-ccbd-4c58-ab3f-f1c0cf646bc3.png)

10. This error block possibility of editing and saving attribute

### Expected result

1. no error to allow attribute saving correctly

### Solution
This can fix but I don't know if the problem really came from [here](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml#L115)

![image](https://user-images.githubusercontent.com/861701/137293755-6931ae9b-4d9b-4dfe-bee2-8153f1b204ba.png)

**Comment by bmandl** [comment]
> 

Unfortunately, flushing cache did not help. Error pops up as soon as I open attribute settings (edit attribute) -> any attribute. Temorary solution is, to disable Smile modules, make changes to attributes, then enable Smile modules back

**Comment by mehdichaouch** [comment]
@vahonc as I remember wysiwyg is disabled by default, did you activated it for your test?

**Comment by vahonc** [comment]
@mehdichaouch the WYSIWYG editor is enabled by default

![11-30-2021 configuring the editor adobe commerce 24 user guide](https://user-images.githubusercontent.com/67791361/144018710-1bccc36b-d2d8-47a1-b930-2a5005289dfb.png)

So I don't change this setting in my test environments

![11-30-2021 configuration settings stores magento admin](https://user-images.githubusercontent.com/67791361/144018910-23904b2a-3a59-41b7-9b5d-96d1a3c64b1b.png)

Have you changed this setting in your environment?

BR,
Vadym

**Comment by mehdichaouch** [comment]
Oh sorry, my bad about this confusion.

Yes this param is setted to `Disabled by Default` in my store.

![image](https://user-images.githubusercontent.com/861701/144027561-65617c6f-d6d2-48ca-82ea-edb6abd641dd.png)

Merci,

**Comment by romainruaud** [comment]
Okay, so what needs to be done is on this file/line : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/view/adminhtml/templates/catalog/product/attribute/js.phtml#L115

replace

```if($('is_wysiwyg_enabled').value == '0'){``` 
by 
```if($('is_wysiwyg_enabled') && $('is_wysiwyg_enabled').value == '0'){```

**Comment by vahonc** [comment]
@mehdichaouch,

Can you test my PR on your environment?

BR,
Vadym

**Comment by mehdichaouch** [comment]
@romainruaud thank for the fix.
@vahonc I'm not able to test this anymore.

So I let you see if you want to integrate this fix in code.
Thanks
