### ISSUE TITLE
Displaying unrelated products on category page

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2299]
### Preconditions

Magento Version : 2.4.2

ElasticSuite Version : 2.10.6

Environment : Production

### Steps to reproduce

1. Create category "Main"
2. Create subcategory "Main > Main red", virtual category with rules = "Category = Main and Color = red"

### Expected result

1. Main category shows products from Main category

### Actual result

1. Main category shows products from Main category AND any red products

**Comment by Nuranto** [comment]
![Capture d’écran 2021-10-21 à 16 34 42](https://user-images.githubusercontent.com/1633463/138300047-d044ca1b-9f96-40d4-acdb-0be0f5235dc8.png)

Other informations : 
- Magento 2.4.3-p1
- 2 websites, 2 root categories

**Comment by romainruaud** [comment]
From our point of view, there is no issue there. Vadym gave you the proper workaround to achieve your needs.

Then, I close this issue, feel free to open a new one if you are still facing issues on virtual categories.
