### ISSUE TITLE
Search terms - products are not sorting manually on the frontend

### ISSUE THREAD

**Issue by kczaplinska** [Smile-SA/elasticsuite#2305]
### Preconditions
Magento Version : 2.4.2-p2

ElasticSuite Version : 2.10.6

Environment: developer and production mode

Third party modules: our custom modules

### Steps to reproduce
1. Go in Admin Panel to "Marketing -> Search Terms"
2. Add search term.
3. Go to "Merchandiser" tab.
4. Sort some of the products manually.
5. Go to the frontend and type this search term in the search input.

### Expected result
1. The products for that search term should be displayed as we sorted them. The manual sort should be applied.

### Actual result
Manual sort is not applied.
Products are displaying randomly. The product I want to be first is not.

### Additional information
We found out that one line was removed in this PR, which is (probably) causing this issue but it is in magento module - https://github.com/magento/magento2/pull/27263

After adding this line: " $this->addToolbarBlock($collection); " the sorting products by manual sort are working, and for now it is our workaround for that.

**Comment by romainruaud** [comment]
I think @rbayet is investigating this one. I reopen.

**Comment by romainruaud** [comment]
I do not reproduce this one either with the said versions.

We'll need more details to investigate.

Are you using a custom theme ?

**Comment by kczaplinska** [comment]
Hi @romainruaud 
Yes indeed, we are using a custom theme, but the functionality is working on Magento 2.3 but not after upgrading our project to Magento 2.4.2-p2.

**Comment by vahonc** [comment]
Hello @kczaplinska,

Could you provide screenshots from your website (frontend/backend) as I pasted in my [comment](https://github.com/Smile-SA/elasticsuite/issues/2305#issuecomment-947502505)?

Also, maybe after migration, there are some issues that are linked to the database, you should check if all tables and columns are properly created.

BR,
Vadym
