### ISSUE TITLE
Partial Search with custom attribute (parts number)

### ISSUE THREAD

**Issue by pbeckerLx** [Smile-SA/elasticsuite#2317]
Hello everyone,

i'm trying to integrate a partial-search with a custom-attribute (code: search_sku,  text field).
I already set this attribute as searchable and did a  complete reindex.

What i need is, that the quick-search gives back a result, even when i'm just entering 3-4 digits inside the complete search_sku.

Lets say for example the product's search_sku attribute value is "49240457000A" i want this product as a search-result when i'm entering 4045, (4 digits in the middle), but also when i'm entering 4924 or 70000A.

If it would be an SQL-Search it would do it with a wildcard search LIKE %search_string%.

I did find a few possible solutions which are unfortunately not working, for example this one:
https://github.com/Smile-SA/elasticsuite/issues/970

I have to admit that i did just copy & paste, of course with modifyfing the variable-names as far as i understand the code.

My questions:
- Is this with possible and if yes, how can i archive it?
- Is there some kind of tutorial for this available?

Thanks for your help in advance! :)

**Comment by romainruaud** [comment]
Hi @pbeckerLx 

everything is covered in the guide provided by @vahonc and in the #970 comment from @elvinristi 

We cannot engage more time here as this is not part of our Open Source support policy.

If you need more from us, we can provide (paid) support as part of our Commercial support policy. Just write an email to elasticsuite@smile.fr if you are interested.

Regards
