### ISSUE TITLE
Issue with reindex

### ISSUE THREAD

**Issue by ghost** [Smile-SA/elasticsuite#2323]
Hello, i can see this error in logs.

Can you help please ?

Thank you.

![image](https://user-images.githubusercontent.com/17496183/139171557-5c9a48f3-1fab-4058-a5f5-1ae4ff39a011.png)

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#str1='A2B8C3').(#str2='q2d1hi3j').(#str3='B4D7e6').(#str=#str2 ':QQ:' #str1 ':PP:' #str3).(#cmd='echo ' #str).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(@org.apache.commons.io.IOUtils@toString(#process.getInputStream()))}] is too long, must be no longer than 512 bytes but was: 782;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: id [%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#str1='A2B8C3').(#str2='q2d1hi3j').(#str3='B4D7e6').(#str=#str2 ':QQ:' #str1 ':PP:' #str3).(#cmd='echo ' #str).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(@org.apache.commons.io.IOUtils@toString(#process.getInputStream()))}] is too long, must be no longer than 512 bytes but was: 782;"},"status":400}

**Comment by romainruaud** [comment]
This table should not be that huge, because each time the cronjob is run, the table is cleaned.

So maybe the cron is clogging for long time and fails to clean it ? 

I'll try to see if I find something relevant in your file.

Regards

**Comment by achatpc** [comment]
> This table should not be that huge, because each time the cronjob is run, the table is cleaned.
> 
> So maybe the cron is clogging for long time and fails to clean it ?
> 
> I'll try to see if I find something relevant in your file.
> 
> Regards

Thank you

**Comment by achatpc** [comment]
Hello, can be related to elastic cluster AUTH? Because i have a login/password to access to cluster.
I have set up it in env.php

**Comment by vahonc** [comment]
Hello,

Nope, access to the cluster via login/password is not related to your problem.

BR,
Vadym

**Comment by romainruaud** [comment]
You have broken data in the table. At least 4000+ lines like this : 

```
| fff35a534edd1c1de19e75432d0d820a | 2020-09-26 03:50:57 | {"image":"h.png","page":{"store_id":"3","type":{"identifier":"checkout_cart_index","label":"Winkelwagen"},"site":"www.achatpc.com","url":"\/nl\/checkout\/cart\/","title":"Winkelwagen","resolution":{"x":"240","y":"320"}},"session":{"uid":"%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#str1='A2B8C3').(#str2='q2d1hi3j').(#str3='B4D7e6').(#str=#str2 ':QQ:' #str1 ':PP:' #str3).(#cmd='echo '  #str).(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','\/c',#cmd}:{'\/bin\/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(@org.apache.commons.io.IOUtils@toString(#process.getInputStream()))}","vid":"42fb3773-3a9c-7462-1638-fc048e6e6312"}} |
```

That's strange, I have no idea about what could be generating those failed lines.

I suggest you just get rid of them with the following query : 

```delete from elasticsuite_tracker_log_event where data like "%cmd.exe%";```

The cron should be able to work again, it will take some cron iteration to index all the pending events.

Regards
