### ISSUE TITLE
tracking_log_session index does not exist yet. Make sure everything is reindexed.

### ISSUE THREAD

**Issue by hkruit** [Smile-SA/elasticsuite#2324]
The Magento admin shows this message on the search usage analytics page. "tracking_log_session index does not exist yet. Make sure everything is reindexed."

### Preconditions
This is on a Magento Cloud PRO environment
Magento version 2.4.3
ElasticSuite Version : 2.10.7
Elasticsearch 7.9 
plugins 
            - analysis-icu
            - analysis-phonetic

Environment : Production mode

### Steps to reproduce
1. Enable tracker
2. Reindex everything
3. Open search usages analytics page

### Expected result
1. Search usage has been tracked

### Actual result
1. A message is shown "tracking_log_session index does not exist yet. Make sure everything is reindexed."
2. The indice magento2_default_tracking_log_session does not exist

Good to know on the staging and production environment we face this problem on multiple Magento cloud instances. On the integration / development instances the indice is available. Let me know if you need any more information we could also schedule a debug session on the magento cloud staging environment.

**Comment by JKingma** [comment]
Anyone?

**Comment by romainruaud** [comment]
Hello,

did you navigate on Front Office ? 

is the tracking enabled ? 

do you see "tracking*" indices in the Elasticsuite > Indices Management menu ?

**Comment by hkruit** [comment]
Hi @romainruaud 
Yes tracking is enabled, it is a live production environment so there are constantly customers on the frontend end.
There are no indices called tracking_log_session. The tracking_log_event indice is created and populated.

**Comment by romainruaud** [comment]
@hkruit are you able to provide me the frontend url of this environment if that's a running website ?

**Comment by hkruit** [comment]
Hi @romainruaud  yes that would be https://mostwantednl.nl/

**Comment by romainruaud** [comment]
The tracking seems to befiring properly in frontend.

Do you have data in the elasticsuite_tracker_log_event table ?

**Comment by hkruit** [comment]
Yes there is data in this table.
it is either
`{"image":"h.png"}
OR
{"page":{"store_id":xx,"cart":{"product_id":xxxxx}},"session":{"uid":"xxxxxxx","vid":"xxxxxxxxxxxx"}}`

**Comment by romainruaud** [comment]
@hkruit did you investigate more by your side ?

**Comment by hkruit** [comment]
@romainruaud  I'm currently in contact with Adobe support, they rerouted me to you :( however I believe there is something happening with either Magento Cloud architecture or Fastly. The issue was ranked P3 so I don't expect swift responses. I will update this when I have more info.

**Comment by romainruaud** [comment]
Hi @hkruit 

Did you have any progress on this one ? We are facing exactly the same issue for one of our customers, I'll go throught the Magento Cloud / Fastly journey as well but as you said, it might take some time, so I was wondering if you had anything new.

I'll update if I have some progress by my side.

Regards

**Comment by hkruit** [comment]
@romainruaud  Cloud support is stonewalling me, so I'd expect litte help from them :( 

I tried adding a "pass" for this request in the VCL but it didn't seem to help. 

Regards

**Comment by romainruaud** [comment]
@hkruit I now have the solution for this one.

Another customer of ours faced it recently, here is what he did to fix that : 

> The problem was not Faslty caching itself but the Fastly Image Optimization feature, as it detects h.png as an image and removes the parameters from the request.
> 
> The solution is to add a custom Fastly VCL pass removeing the faslty header.
> 
> This is the solution i came up with, it may help you with future customer:
> 
> if (req.url ~ "^/elasticsuite/tracker/hit/image(/.*)?$") { set req.http.X-Fastly-Imageopto-Api = "none"; return (pass); }

**Comment by romainruaud** [comment]
Added to the FAQ : https://github.com/Smile-SA/elasticsuite/wiki/FAQ#im-using-fastly-and-i-cant-see-anything-on-the-elasticsuite--search-usage-dashboard

I close !

**Comment by cdfrm** [comment]
I have this issue after removing them (tracking_log_session, tracking_log_event) from Elasticsearch by ES API. So it will not auto-recreate even if data in table and cron were running. I tried to change the Indies prefix, and that fixed the problem.
