### ISSUE TITLE
Disable search and autocomplete, use only category related tools. Is this possible?

### ISSUE THREAD

**Issue by ikslavok** [Smile-SA/elasticsuite#2325]
I am happy with our theme custom autocomplete so I don't need ElasticSuite one. But I need virtual category and category rule extensions. Can I somehow use ElasticSuite without its autocomplete solution? I could also use the ElasticSuite search engine but not autocomplete.

**Comment by romainruaud** [comment]
You could dismantle our autocomplete by layouting (remove the form.mini block or something like this).
