### ISSUE TITLE
Live search support

### ISSUE THREAD

**Issue by Vigneshmuthusamy** [Smile-SA/elasticsuite#2328]
Will there be support for livesearch using this module now or in the future?

**Comment by romainruaud** [comment]
I'm not sure to understand what would be the "support for livesearch". What would you expect ? 

Livesearch is a Saas solution which replaces everything related to the search engine in Magento, so for me actually, it's either you use Livesearch, or you use something else (Elasticsuite or legacy ES implementation or any other Saas solution).

**Comment by Vigneshmuthusamy** [comment]
Like product listing is powered in elasticsearch and
