### ISSUE TITLE
Virtual Categories Rule for New Products

### ISSUE THREAD

**Issue by henkvalk** [Smile-SA/elasticsuite#2337]
### Discussed in https://github.com/Smile-SA/elasticsuite/discussions/2332

<div type='discussions-op-text'>

<sup>Originally posted by **henkvalk** November  6, 2021</sup>
We love using Virtual Categories. We miss only the option _new products_ inside the rule. 

It would be great to add the rule _New Products_ and as option choose _days old_

Based on the create date of the product ID, you can match the given days old from current date. So it will automatically add new and delete products from the virtual category</div>

**Comment by romainruaud** [comment]
Hi @henkvalk 

I guess you are using Magento Open Source version ? Because most of time when using Magento Commerce, people are just using an "is_new" attribute and making it move with the staging mechanism.

**Comment by Nuranto** [comment]
If it can help, it is implemented here : https://github.com/Smile-SA/elasticsuite/wiki/Querying

**Comment by romainruaud** [comment]
We implemented rules like "creation dates in the last X days" in the rule engine. So I close this issue.

Regards
