### ISSUE TITLE
RFC : Product page views statistics from GA

### ISSUE THREAD

**Issue by flsabourin** [Smile-SA/elasticsuite#234]
In order to help the merchandiser organizing the shelf, add information about the product page viewed in the last "x days" directly in the grid
(information coming from Google Analytics)

**Comment by djenvert** [comment]
This feature would kick ass

**Comment by romainruaud** [comment]
But this will not come from GA :)

**Comment by djenvert** [comment]
Yes, I know. Will we have the equivalent not only of page views, but also of other GA metrics like click-through-rate for instance?

**Comment by djenvert** [comment]
"It’s the most simple feature **Tweakwise** offers. But the one I really like is that its connected to Google Analytics so its giving the best search results feeded by our GA account info.
The productname is connected with Google Analytics and google provides Tweakwise with pageviews and click through rate info. (Pageviews and ctr) This info helps only with the sorting options on the overview pages. "

**Comment by afoucret** [comment]
Closed in favor of #589 issue.

**Comment by romainruaud** [comment]
Will not be done via GA but implemented by #589 aka "Search analytics dashboard".

Regards
