### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by hbarza** [Smile-SA/elasticsuite#2343]
In case there is a virtual category with no virtual rule defined the following error will occur when opening the category in storefront.

```
Error filtering template: Warning: Invalid argument supplied for foreach() in .../vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php on line 101
```

### Preconditions

PHP Version: 7.4

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.8.1

Environment : developer

Third party modules :

### Steps to reproduce

1. Create a new category
2. Enable the "Virtual Category" option under "Products in Category" section
3. Select a category as root for the "Virtual Category Root" option
4. Set the "Virtual rule" option into "If **ALL**  of these conditions are **TRUE**"; BUT define no condition
5. Save the category and open it in the storefront

### Expected result

View products in the category/widget

### Actual result

```
Error filtering template: Warning: Invalid argument supplied for foreach() in .../vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php on line 101
```

**Comment by romainruaud** [comment]
I'll review PR #2344 

Thank you for contributin.

**Comment by romainruaud** [comment]
Fix has been merged and will be part of next minor release scheduled for january.

Regards
