### ISSUE TITLE
Search by custom-attribute/name - force order of words (no results by wrong order of words)

### ISSUE THREAD

**Issue by petiz** [Smile-SA/elasticsuite#2345]
Hello,

i'm integrating the search for a custom attribute.

Image a product has the value for this attribute: "word1 word2".

In this case i would like to find this product by "word1 word2" but NOT by "word2 word1".
Is it possible to ignore every wrong orders with my custom analyzer / filters? 

If yes, how can i achieve it?

Thanks for your help in advance :)

**Comment by romainruaud** [comment]
Hi @petiz , what is the use case behind this exactly ?

We already embed a "match phrase" mechanism that will favor results containing "word1 word2" against any other results containing the words in different orders.

Isn't it enough in your case ? 

If you really don't want products having "word2 word1" maybe you could dismantle the fulltext search query and keep only the "match phrase" part of it.

**Comment by petiz** [comment]
hi @romainruaud :


I want to integrate some kind of fulltext-search for a custom-attribute which is called part-number (not the sku!)

Lets say as an example an item has the part-nuber 838930, the item has te be found by 838 but also with 893,  but not by 983 (wrong order of the tokens).

So my plan is to convert the part-number from 838930 to 8 3 8 9 3 0 and set the min_ngram to 1 so that every digit is a single token.

This is already finished and seems to work, and now i have to make sure, that the order of the tokens / digits has to be correct.


I hope i'm not doing something completely wrong, but as far as i understand it right, it should work this way?



Thanks for your help in advance!

**Comment by romainruaud** [comment]
@petiz did you manage to achieve it ?
