### ISSUE TITLE
CMS Catalog widget - Sort product list

### ISSUE THREAD

**Issue by Coosos** [Smile-SA/elasticsuite#2356]
### Preconditions

Magento Version : 2.3.7-p2 (EE) / 2.4.3-p1 (EE)

ElasticSuite Version : 2.9.9.1 / 2.10.8.1

Environment : Developer

Third party modules : Fresh installation

### Steps to reproduce

1. Create product list in CMS page (I used page builder)
2. (in modal) Use select product by condition (with or no condition)
3. (in modal) Change "Sort by" to Price (low or high)
4. Save configuration / page

### Expected result
1. Products sorted by price

### Actual result
1. Products no sorted by price

##### Without elasticsuite : Admin

![WithoutES_Conf_CMS](https://user-images.githubusercontent.com/5632327/142770415-46004211-746f-457b-83e8-ceada4007075.png)

![WithoutES_CMS_View](https://user-images.githubusercontent.com/5632327/142770421-d1636960-f33f-425c-992b-6620e4232fa4.png)

##### Without elasticsuite : Front

![WithoutES_Front_View](https://user-images.githubusercontent.com/5632327/142770425-54feac07-10b7-4a7f-b06c-dbe57a163170.png)

##### With elasticsuite : Admin

![ES_Conf_CMS](https://user-images.githubusercontent.com/5632327/142770461-551f8f1f-3ec8-4f4e-b3b3-c2c5a56637ed.png)

![ES_CMS_View](https://user-images.githubusercontent.com/5632327/142770468-708349d6-0998-40cc-bf78-e5906938e812.png)

##### With elasticsuite : Front

![ES_Front_View](https://user-images.githubusercontent.com/5632327/142770463-ebe0f6b0-5c1d-4559-ab6a-9a07e668e214.png)

**Comment by Coosos** [comment]
_Tested with Select Product By Condition, SKU and Category_

After new tests, multiple sorting does not work on :

* Newest products first (magento sort by entity_id DESC)
* Oldest products first (magento sort by entity_id ASC)
* Stock: low stock first
* Stock: high stock first
* Price: high to low
* Price: low to high

For position, I don't know if the sort is good (when use Select Product By Category or SKU)

**Comment by Coosos** [comment]
I continued the analysis

**Stock filter**

Magento use "quantity_and_stock_status" attribute field to apply filter, but this data not exist in ES

![image](https://user-images.githubusercontent.com/5632327/142918988-719f56df-2518-4445-bfa7-ff81b15f621f.png)

For fix this, add `'quantity_and_stock_status' => 'stock.qty'` in `\Smile\ElasticsuiteCatalog\Model\Search\Request\Field\Mapper::$fieldNameMapping`

(**it is necessary to test if we display the products out of stock**)

**Comment by romainruaud** [comment]
Hi @Coosos thank you for digging more on this one.

I've merged a PR that should fix the problem for price #2361 

I'm blurry about the "quantity_and_stock_status". I'm not sure if legacy this is really using the "qty" (number of stock units) for sorting or rather using the status (1 or 0). 

We could map this to our `stock.qty` field of course, but this field is always `0` for composite products (configurable, bundles) as  it's like this in the legacy `cataloginventory_stock_status` table of Magento. So I'm not sure we should use this as a mapping but rather rely on `stock.is_in_stock`.

Regards

**Comment by Coosos** [comment]
Hi @romainruaud

> We could map this to our stock.qty field of course, but this field is always 0 for composite products (configurable, bundles) as it's like this in the legacy cataloginventory_stock_status table of Magento. So I'm not sure we should use this as a mapping but rather rely on stock.is_in_stock.

I didn't think about that :confused:

I have checked in a native magento how it works to sort by price.
And it's sorted by quantity (even if it's equal to 0 for configurable products) and entity_id.

Sql query to sort by High stock first :

```sql
SELECT DISTINCT  `e`.*, `at_visibility`.`value` AS `visibility`, `stock_status_index`.`stock_status` AS `is_salable`, IFNULL(position, ~0) AS `cat_index_position` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_entity_int` AS `at_visibility` ON (`at_visibility`.`row_id` = `e`.`row_id`) AND (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 0)
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id
 LEFT JOIN `catalog_category_product` AS `cat_pro` ON cat_pro.product_id=e.entity_id AND cat_pro.category_id = 25
 LEFT JOIN `cataloginventory_stock_item` AS `stock_item_table` ON e.entity_id=stock_item_table.product_id WHERE ((((at_visibility.value = '2') OR (at_visibility.value = '4'))) AND (((IFNULL(`e`.`entity_id`, 0) IN (SELECT `catalog_category_product`.`product_id` FROM `catalog_category_product` WHERE (category_id IN ('25')))) )) AND (stock_status_index.stock_status = 1)) AND (e.created_in <= 1) AND (e.updated_in > 1) ORDER BY `stock_item_table`.`qty` DESC, `e`.`entity_id` DESC
```

Sql query to sort by low stock first :

```sql
SELECT DISTINCT  `e`.*, `at_visibility`.`value` AS `visibility`, `stock_status_index`.`stock_status` AS `is_salable`, IFNULL(position, ~0) AS `cat_index_position` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_entity_int` AS `at_visibility` ON (`at_visibility`.`row_id` = `e`.`row_id`) AND (`at_visibility`.`attribute_id` = '99') AND (`at_visibility`.`store_id` = 0)
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id
 LEFT JOIN `catalog_category_product` AS `cat_pro` ON cat_pro.product_id=e.entity_id AND cat_pro.category_id = 25
 LEFT JOIN `cataloginventory_stock_item` AS `stock_item_table` ON e.entity_id=stock_item_table.product_id WHERE ((((at_visibility.value = '2') OR (at_visibility.value = '4'))) AND (((IFNULL(`e`.`entity_id`, 0) IN (SELECT `catalog_category_product`.`product_id` FROM `catalog_category_product` WHERE (category_id IN ('25')))) )) AND (stock_status_index.stock_status = 1)) AND (e.created_in <= 1) AND (e.updated_in > 1) ORDER BY `stock_item_table`.`qty` ASC, `e`.`entity_id` ASC
```

Only changes are `ORDER BY stock_item_table.qty DESC, e.entity_id DESC` or `ORDER BY stock_item_table.qty ASC, e.entity_id ASC`.

And magento use LEFT JOIN to get quantity, so allow item line not existing in table.
So magento seem sort product quantity even if quantity equal to 0.
However, I notice that magento sort by entity_id for all sort available.

Concerning whether it is in stock or not, magento add / remove `stock_status_index.stock_status = 1` from where condition (SQL).

**Comment by romainruaud** [comment]
Well, I double checked and configurable products does have "qty = 0" in the `cataloginventory_stock_item` table.

This means that, on a pure SQL basis, the code produced by Magento is not fancy at all, because it does not compute the "real" stock quantity for configurable, but rather consider only the `stock_item_table.qty`.

We'll do like Magento does, and rely on `stock.qty` field for building the ES query. Of course, it will suffer the same erroneous behavior than Magento SQL query when dealing with configurable products, but we'll be ISO-functional.

**Comment by romainruaud** [comment]
PR #2397 contains the implementation to deal with "low stock first" and "high stock first".

We'll publish a release containing this at the beginning of january.
