### ISSUE TITLE
Source Model Attribute filter is not working 

### ISSUE THREAD

**Issue by sandeepkawade** [Smile-SA/elasticsuite#2357]
I have created a product attribute with source model.
I have set the attribute used in search and filter.
When I try to call rest API with the filer I am getting empty result.

Below is my source model for attribute
`namespace Arise\CatalogImport\Model\Entity\Attribute\Source;

use Magento\Eav\Model\Entity\Attribute\Source\Boolean;

class Flag extends Boolean
{

    /**
     * Retrieve all attribute options
     *
     * @return array
     */
    public function getAllOptions()
    {
        if (!$this->_options) {
            $this->_options[] = [
                'label' => __('-- Select Option --'),
                'value' => '',
            ];
            $availableOptions = $this->getOptionArray();
            foreach ($availableOptions as $key => $value) {
                $this->_options[] = [
                    'label' => $value,
                    'value' => $key,
                ];
            }
        }

        return $this->_options;
    }//end getAllOptions()

    /**
     * Get getOptionArray
     *
     * @return array
     */
    public function getOptionArray()
    {
        return [
            0 => __('No'),
            1 => __('Yes'),
            2 => __('All'),
        ];
    }//end getOptionArray()

}//end class`

Rest API

`http://dev.local/rest/V4/products-list/?searchCriteria[currentPage]=1&searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=226&searchCriteria[filter_groups][1][filters][0][condition_type]=eq&searchCriteria[filter_groups][1][filters][0][field]=flag&searchCriteria[filter_groups][1][filters][0][value]=1&searchCriteria[PageSize]=2&searchCriteria[requestName]=catalog_view_container`

**Comment by vahonc** [comment]
Hello @sandeepkawade,

Are you sure that you added values for your attribute to some products?

BR,
Vadym

**Comment by sandeepkawade** [comment]
Yes I assign the attribute to product as well without flag filter the I am getting the response but after adding the filter getting empty response

**Comment by vahonc** [comment]
@sandeepkawade, to be able to reproduce your issue we need more details about your environment. 

So answering on these questions:

- Which version of the Magento and ElasticSuite module you are using?
- Have you assigned your products with your test attributes values to some real or virtual category?
- Have you multistore websites environment?

Also, provide the config (xml) files of your REST endpoint.

BR,
Vadym
