### ISSUE TITLE
Js error in optimizer-preview-type.js

### ISSUE THREAD

**Issue by Tahuna1** [Smile-SA/elasticsuite#2358]
we have made an update 2.10.8.1 and since then we are getting an js error in optimizer-preview-type.js when we try to create an new optimizer in the admin.

### Preconditions
local docker env. / abode magento cloud
Magento Version : EE 2.4.2
ElasticSuite Version: 2.10.8.1
Environment : both

### Steps to reproduce
1. go to optimizer
2. click on button new optimizer 

### Expected result
1. The Form should be loaded

### Actual result
Form is not loaded and the console shows this error:

(index):9 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at UiClass.onContainersUpdate (optimizer-preview-type.js:90)
    at UiClass.initialize (optimizer-preview-type.js:33)
    at UiClass.initialize (wrapper.js:109)
    at new UiClass (class.js:49)
    at Object.initComponent (layout.js:137)
    at fire (jquery.js:3238)
    at Object.fireWith [as resolveWith] (jquery.js:3368)
    at Object.deferred.<computed> (jquery.js:3467)
    at fire (jquery.js:3238)
    at Object.fireWith [as resolveWith] (jquery.js:3368)

btw:

it looks fine when i took out: this.onContainersUpdate

initialize: function () {
...
    //this.onContainersUpdate(this.searchContainers);
...
}

**Comment by Coosos** [comment]
Hi,

This bug is fixed on this MR : https://github.com/Smile-SA/elasticsuite/pull/2318
I think that you can apply patch with this modification to fix only JS error : https://github.com/Smile-SA/elasticsuite/pull/2318/files#diff-3d73c4318a74a5eca65f759be8ad8034fc756af2364848229fa06daba6a96dd9

This fix is in branch but is but not yet with a tag

**Comment by romainruaud** [comment]
Yes this has been already fixed/merged in all branches and will be delivered in the next minor release.

Regards

**Comment by romainruaud** [comment]
I close, stay tuned for next minor release in the beginning of january.
