### ISSUE TITLE
Rule "Only in stock products" in Optimizer does not work

### ISSUE THREAD

**Issue by Agent-003** [Smile-SA/elasticsuite#2366]
**Is your question related to a problem? Please describe.**
I have create an optimizer for "Only in stock products" (like here https://github.com/Smile-SA/elasticsuite/issues/704#issuecomment-359784903 )  It doesnt work. 

Magento Version : Magento CE 2.4.2
ElasticSuite Version : 2.10.8.1
ElasticSearch Version : 7.15.1

**Additional context**
I have create an optimizer for "Only in stock products" https://i.imgur.com/556QRq5.png . It doesnt work. 
And there are all produsts "out of stock" in "Category Product View" in Preview https://i.imgur.com/LpnlY55.png . But among these products there are products "in stock" .
Optimizer works for price , but doesn't work for "Only in stock products" .

Could you please suggest the right way how to fix these?

**Comment by romainruaud** [comment]
Please share a full capture of the boost configuration.

We are having issue on latest version with the boost weight that can be configured with a slider, sometimes just moving the slider is not enough to populate correctly the input containing the value, or at least to make Magento aware that the value is not 0.

Regards

**Comment by Agent-003** [comment]
https://prnt.sc/2181i1s
https://prnt.sc/2181jrk
I think my problem is not related to the optimizer settings....

Elasticsuint does not see that products are "in stock". Maybe Elasticsuite has a problem with a lot of products?

**Comment by romainruaud** [comment]
Nope, there is no problem with "a lot" of products. We have several customers with millions of products.

If the product appears as "out of stock", it's due to the fact that it's indexed in Elasticsearch "as is".

Can you show me some details about products that are displayed "out of stock" but that should not ? 

I mean : 

- screenshot of inventory configuration for these products
- corresponding lines in the stock index table for these products

Regards

**Comment by Agent-003** [comment]
An example of one of these products:
https://i.imgur.com/wMlJV05.png 
https://i.imgur.com/lXnyijV.png - advanced Inventory.
![image](https://user-images.githubusercontent.com/21066583/144245735-9408685a-647d-4055-b8ad-bacce9fe4b5f.png) 
![image](https://user-images.githubusercontent.com/21066583/144246151-1b1615be-5be7-4b48-baff-fa4958385581.png)

https://i.imgur.com/4knOVjv.png - but it is "Out Of Stock" in Optimizers ... :(

**Comment by vahonc** [comment]
@Agent-003 have you installed some third-party modules that could affect on the inventory of the products?

BR,
Vadym

**Comment by Agent-003** [comment]
Sorry. I had some kind of problem with inventory_stock_1 . Fixed by recreating the view. 

Thank you!
 
Best regards

**Comment by vahonc** [comment]
@Agent-003,

Did I understand you correctly, you found a solution to your problem and we can close this issue?

BR,
Vadym

**Comment by Agent-003** [comment]
@vahonc  
Yes. You can close this issue.
