### ISSUE TITLE
Cannot use 'match' as an identifier. It is a reserved keyword since PHP 8.0

### ISSUE THREAD

**Issue by FredericMartinez** [Smile-SA/elasticsuite#2368]
Hello folks!

Elasticsuite 2.10.8.1 is not compatible with PHP 8.0 (Magento 2.4.4-beta2)

### Preconditions

- PHP 8.0
- Magento Version : (ee) 2.4.4-beta2
- ElasticSuite Version : 2.10.8.1
- Magento Environment : Developer (same with Production mode)

### Steps to reproduce

```
composer create-project --repository-url=https://repo.magento.com/ magento/project-enterprise-edition=2.4.4-beta2 ee_244-beta2
composer require smile/elasticsuite ~2.10.0
php bin/magento setup:di:compile
```

### Expected result

Elasticsuite should be compiled in `generated` without errors

### Actual result

```
syntax error, unexpected token "match", expecting identifier#0 /var/www/html/vendor/composer/ClassLoader.php(429): Composer\Autoload\includeFile('/var/www/html/v...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Smile\\Elasticsu...')
```
My error is truncated, but it's:
- `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query\Builder\Match` class
- `Smile\ElasticsuiteCore\Search\Request\Query\Match` class
- `Smile\ElasticsuiteCore\Search\Request\Query\Common extends Match`
IDE Error: Cannot use 'match' as an identifier. It is a reserved keyword since PHP 8.0

**Comment by romainruaud** [comment]
Well it seems that we are not able actually to access the Magento2 beta releases ... that's weird, I'm contacting them.

By the way, I've added beta of Magento to our Github Actions pipeline (and allowed these versions to fail for now, I don't wait to block everything).

Vadym will follow the rabbit hole on this one and push fixes regarding Magento 2.4.4 beta as long as Magento team does update of the product.

Regards

**Comment by VkStyle** [comment]
magento "version": "2.4.3-p1" aslo has this error

**Comment by romainruaud** [comment]
@VkStyle are you sure ? I don't think that's the case. 

This bug is related to PHP >8.0 ("match" is a reserved word), Magento 2.4.3-p1 is not supposed to be run with PHP 8.0

**Comment by FredericMartinez** [comment]
Yes, 2.4.3-p1 will have this error because it's a PHP 8.0 issue.

But you shouldn't use PHP 8.0 with 2.4.3-p1, see the requirements https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

**Comment by FredericMartinez** [comment]
Awesome, thx!

**Comment by romainruaud** [comment]
I reopen, at least for now, because even if this issue has been resolved by the associated commit, the setup:upgrade is not working with magento 2.4.4 beta.

Is this something you also face @FredericMartinez ?

**Comment by FredericMartinez** [comment]
It's ok for me:

```
composer require smile/elasticsuite (dev-master#ac5d66918f5490bfa1c96aa6f22f92cee6b55fce)
php bin/magento setup:upgrade
php bin/magento setup:di:compile
```

No error found during setup:upgrade or di:compile

**Comment by vahonc** [comment]
I guess that there is could be some issues during running `setup:upgrade` command which are linked to deploying the sample data of the Magento. During this one I got errors, so I had to disable some Magento modules.

BR,
Vadym

**Comment by FredericMartinez** [comment]
```
bin/magento sampledata:deploy
```
On beta2/PHP8.0 works fine too.

I don't know why you have an issue on setup:upgrade

**Comment by romainruaud** [comment]
According to this run (as an example) https://github.com/Smile-SA/elasticsuite/runs/4507597050?check_suite_focus=true

The setup:upgrade is failing after I add the Venia sample data to the project.

So it's probably related to the Venia sample data. I'll dig on it.
