### ISSUE TITLE
Issue with "Show more+" button, content disapearing. 

### ISSUE THREAD

**Issue by oliverde8** [Smile-SA/elasticsuite#237]
Hello, 

If you configure an attribute with : 
* Use in Layered Navigation at "Filterable (with results)"
* Use in Search Results Layered Navigation at No

Then the Smile\ElasticsuiteCatalog\Controller\Navigation\Filter\Ajax returns empty results as it can't find the attribute in the filter list.

**Comment by afoucret** [comment]
The PR #241 fix this one.

**Comment by afoucret** [comment]
The PR is merged and the code is available on the 2.3.x branch for testing.
