### ISSUE TITLE
 Does optimizer work for graphQL queries ?

### ISSUE THREAD

**Issue by Agent-003** [Smile-SA/elasticsuite#2370]
**Preconditions**
Magento Version : Magento CE 2.4.2
ElasticSuite Version : 2.10.8.1
ElasticSearch Version : 7.15.1

I created an optimizer with the conditions "Only in stock products", it works great for the category page. All products with "out pf stock" at the end.
But that doesn't work for my graphQL query. 
Does optimizer work  for graphQL queries at all? Or maybe I am doing something wrong?

**Comment by vahonc** [comment]
@Agent-003, normally optimizers should work everywhere, so it is possible that something is wrong on your side.

Could you please provide us with an example of your graphQL queries and a screenshot of the configuration of your optimizer?

BR,
Vadym

**Comment by Agent-003** [comment]
@vahonc Maybe you're right.

I'm guessing the optimizer rules don't work if there is a different sort in the query?
https://prnt.sc/224uehp https://prnt.sc/224yd3v https://prnt.sc/224yhi1

**Comment by vahonc** [comment]
@Agent-003, optimizers are applied only when the default **Position** sort order is used in frontend. It will not working if sort order will be changed to **Price** or **Name**.

BR,
Vadym

**Comment by romainruaud** [comment]
@Agent-003 can we consider this question as answered ? 

Regards
