### ISSUE TITLE
Category Products gets empty

### ISSUE THREAD

**Issue by alam-ejaz** [Smile-SA/elasticsuite#2404]
### Preconditions

Magento Version :
2.4.1

ElasticSuite Version :
1.5.1

Environment :
production

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1. category products should be completely visible

### Actual result

![image](https://user-images.githubusercontent.com/72202738/147115300-fc4ea74b-6936-4c27-8795-70987629c7fc.png)
![image](https://user-images.githubusercontent.com/72202738/147115352-00e24c6a-a289-4183-a7bd-937d617b08c7.png)

1. [Screenshot, logs]

We actually don't know how to reproduce it but when it happens we simply run the elastic suit indexer and then everything works fin.

**Comment by vahonc** [comment]
Hello @alam-ejaz,

Could you please clarify what exactly version of ElasticSiute you are using? You write that you use the 1.5.1 version and it is a little bit strange cause we support 2.9.x and 2.10.x versions? 

BR,
Vadym
