### ISSUE TITLE
 Virtual Category conditions not working with multi stores

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#2405]
If we create Virtual Category and add Virtual rule with condition like Sku "Contains" , add some skus and then select another store from Scope drop down and add again different product skus then it's overwrite previously added other countries SKU's.

Magento Version : 2.4.1
ElasticSuite Version : 2.10.8.1
Environment : Production

Third party modules :
Aheadworks_Autorelated
Amasty_Storelocator
Amasty_ShopbyBrand
Amasty_Gdpr

# Steps to reproduce
1. setup default magento with multi stores, create Virtual category and add Virtual rule with condition like Sku "Contains"  and add some products sku's.
2. Select another store from Scope drop down for same category and add different sku's than step 1
3. it's overwrite previously added other countries SKU's.

# Expected result
1. both store's category should have to show different Sku as per virtual rule.

# Actual result
1. Both store's showing same Sku's as per added in above step 2 because its overwrite

Can you please let us know, Is it possible to add different Sku on same virtual category for different stores?

Thanks,
David Andersson

**Comment by vahonc** [comment]
Hello @davidandersson1.

Unfortunately, it doesn't work that way, especially when it comes to virtual categories and creating rules for them. Even if it's the same categories with the only difference in other SKU of products, you must follow the following steps:
- Select the required store/website from the scope drop-down list.
- Create a new virtual category.
- Set a rule for this category with a condition like `Sku "Contains"` and add some product SKU's.
- Save the category by clicking on the `Save` button.
- Choose another store/website.
- Create a new virtual category again.
- Set a rule for this category by adding other product SKU's.
- Save the category by clicking on the `Save` button.
- Clear and re-index all data.

BR,
Vadym

**Comment by davidandersson1** [comment]
Hello @vahonc thanks for your suggestion, we will try with it.

**Comment by romainruaud** [comment]
@davidandersson1 any update ?

**Comment by davidandersson1** [comment]
Hi @romainruaud,

Really sorry, I was forgot to reply here but its works fine according as per your suggested way.
