### ISSUE TITLE
How to get in touch

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#2409]
Hello,

a couple of days ago I tried to get in touch with your company to ask for a quote (custom development).
I did not get an answer and it seems the contact form I used is gone from your site?

A customer is in need of a feature so how can I get in touch with you if you are interested at all?

Thank you

**Comment by vahonc** [comment]
Hello @OvalMedia,

If you need additional (paid) support by our side, feel free to write an email to elasticsuite@smile.fr.

p.s. as I know my colleagues (Romain and Richard) are out on holidays and return to work on January 3rd. So please wait, I think on Monday they will answer your request. Happy New Year!!!

BR,
Vadym

**Comment by romainruaud** [comment]
Yes, you can write to us at elasticsuite@smile.fr

Regards
