### ISSUE TITLE
Attributes/Filters missing in category admin

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#2410]
On the category administration page under "Display Settings" I can configure the attributes being used in a particular category.
In a project of mine there seems to be an issue with the attributes since there are quite some attributes missing on that page and I have no way to configure them.

### Preconditions

Magento Version : 2.4.3-p1

ElasticSuite Version : 7

Environment : issue happens in both modes

Here you can see a list of configured attributes. Please don't get confused by multiple attributes with the same title. They are actually separate attributes with different attribute codes only with the same title.

![smile-cat-1](https://user-images.githubusercontent.com/1006378/147761836-204f55e0-6b6c-4ecb-a4cc-9ecdf040e3ea.png)

The goal here was to only have the manufacturer ("Hersteller") attribute shown in this category.
But in the frontend there are three more attributes which don't show up in the backend configuration:

![smile-cat-2](https://user-images.githubusercontent.com/1006378/147762030-bdaf6396-e9d0-4c03-a5a1-32df62f925dc.png)

I have no idea what is going on here or why they are missing on the admin page. 
All that data gets written to the table `smile_elasticsuitecatalog_category_filterable_attribute`. I added the missing attributes into this table manually after which they disappeared in the frontend as expected. But of course another save in the backend will always kill these lines again.

Are there any known limitations I might have crossed?
If this is a bug can you point me to the relevant parts of the code to debug?

Thank you

**Comment by vahonc** [comment]
Hello @OvalMedia,

Are you sure that your custom attributes are included in some existing Attribute Sets and assigned to some products with values? Because if they are not included in Attribute sets or don't have any values they could not be displayed in category settings.

Also according to your last screenshot, it looks like you are using some custom code or custom theme, so try to check the settings of this custom theme or analyze if any installed third-party modules can't affect it.

**Comment by OvalMedia** [comment]
Hi,

yes, the missing attributes are definitely assigned to attribute sets.

Regarding the screenshot: this is a custom theme. I posted it only to demonstrate that there are more attributes in that category than accessible in the backend.

One thing I found out though: all three attributes ("Hubgröße", "Flächengewicht" and "Verwendungszweck") only have one available option in that category with only one product. And it is always the same product which happens to be a bundle product. Once I remove that product from the category the attributes disappear in the frontend.

So I have to assume there is some bug related to bundle products?

**Comment by OvalMedia** [comment]
Update: the bundle product itself does not have these attributes. It's attribute set does not even have them. But the bundled (simple) products do and that's where the system must get the attributes and the options from.

**Comment by romainruaud** [comment]
It might come from this line : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php#L245

We filter on the attributes sets of products belonging to the current collection.

Maybe we should replace this by aggregating data on "indexed_attributes" and use them as filters, that would be more accurate.

We need to investigate a bit more on a fix for this one.

Regards

**Comment by romainruaud** [comment]
@vahonc if we go through the `getSize()` method of the collection : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L192

This should go through this method : https://github.com/Smile-SA/elasticsuite/blob/85069d8439f1600e2c5df4f82de35797df392609/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L558

If we don't go through "loadProductsCount" it might indicate that the collection has been loaded before, which should not be the case since we just create the collection before.

**Comment by romainruaud** [comment]
Hi @OvalMedia , can you check if the PR #2459 fixes your error ?

**Comment by OvalMedia** [comment]
How do I grab it? I assume a simple "composer update" does not suffice?
I updated to 2.10.9.1 but the error persists.

**Comment by vahonc** [comment]
Hello @OvalMedia,

You could try to add this content as a patch, just add this content to a patch file and if it's possible try to apply this patch to your environment:
<pre>
From 246a892728e336897ffab09acbbb7c05cf3065a8 Mon Sep 17 00:00:00 2001
From: Vadym Honcharuk <vadym.honcharuk@smile-ukraine.com>
Date: Thu, 24 Feb 2022 17:19:27 +0200
Subject: [PATCH 1/3] Fixes #2410, replace attributes collection by aggregating
 data of 'indexed_attributes'

---
 .../Ui/Category/Form/DataProviderPlugin.php     | 17 ++++++++---------
 .../etc/elasticsuite_search_request.xml         |  2 ++
 2 files changed, 10 insertions(+), 9 deletions(-)

diff --git a/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php b/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
index 42e3d3f5..cac1eff3 100644
--- a/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
+++ b/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
@@ -22,7 +22,6 @@ use Smile\ElasticsuiteCore\Search\Request\QueryInterface;
 use Smile\ElasticsuiteCore\Api\Search\ContextInterface;
 use Smile\ElasticsuiteCore\Search\Request\Query\Builder as QueryBuilder;
 use Smile\ElasticsuiteCatalog\Model\Category\Filter\Provider as CategoryFilterProvider;
-
 use Magento\Catalog\Model\Category\DataProvider as CategoryDataProvider;
 
 /**
@@ -62,11 +61,11 @@ class DataProviderPlugin
     /**
      * DataProviderPlugin constructor.
      *
-     * @param AttributeCollectionFactory $attributeCollectionFactory Attribute Collection Factory.
-     * @param FulltextCollectionFactory  $fulltextCollectionFactory  Fulltext Collection Factory.
-     * @param StoreManagerInterface      $storeManager               Store Manager.
-     * @param ContextInterface           $searchContext              Search context.
-     * @param CategoryFilterProvider     $categoryFilterProvider     Category Filter Provider.
+     * @param AttributeCollectionFactory          $attributeCollectionFactory Attribute Collection Factory.
+     * @param FulltextCollectionFactory           $fulltextCollectionFactory  Fulltext Collection Factory.
+     * @param StoreManagerInterface               $storeManager               Store Manager.
+     * @param ContextInterface                    $searchContext              Search context.
+     * @param CategoryFilterProvider              $categoryFilterProvider     Category Filter Provider.
      */
     public function __construct(
         AttributeCollectionFactory $attributeCollectionFactory,
@@ -242,9 +241,9 @@ class DataProviderPlugin
                 ->setPageSize(0)
                 ->addFieldToFilter('category_ids', $this->getCategoryFilterParam($category));
 
-            $attributeSetIds = array_keys($fulltextCollection->getFacetedData('attribute_set_id'));
-            if (!empty($attributeSetIds)) {
-                $collection->setAttributeSetFilter($attributeSetIds);
+            $indexedAttributes = array_keys($fulltextCollection->getFacetedData('indexed_attributes'));
+            if (!empty($indexedAttributes)) {
+                $collection->setCodeFilter($indexedAttributes);
             }
         }
 
diff --git a/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml b/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
index 5ce85f0e..9dbd5092 100644
--- a/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
+++ b/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml
@@ -27,6 +27,7 @@
         <aggregations>
             <provider name="filterableAttributesProvider">searchFilterableAttributesProvider</provider>
             <aggregation xsi:type="termBucket" name="attribute_set_id" field="attribute_set_id"/>
+            <aggregation xsi:type="termBucket" name="indexed_attributes" field="indexed_attributes"/>
         </aggregations>
     </request>
 
@@ -50,6 +51,7 @@
         <aggregations>
             <provider name="filterableAttributesProvider">categoryFilterableAttributesProvider</provider>
             <aggregation xsi:type="termBucket" name="attribute_set_id" field="attribute_set_id"/>
+            <aggregation xsi:type="termBucket" name="indexed_attributes" field="indexed_attributes"/>
         </aggregations>
     </request>
 
-- 
2.25.1


From 5fa026bcd2863a28fc42448c05d0c12c90c95ae8 Mon Sep 17 00:00:00 2001
From: Vadym Honcharuk <vadym.honcharuk@smile-ukraine.com>
Date: Thu, 24 Feb 2022 17:33:21 +0200
Subject: [PATCH 2/3] Fixes #2410, update phpdoc errors

---
 .../Plugin/Ui/Category/Form/DataProviderPlugin.php     | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

diff --git a/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php b/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
index cac1eff3..8345089d 100644
--- a/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
+++ b/src/module-elasticsuite-catalog/Plugin/Ui/Category/Form/DataProviderPlugin.php
@@ -61,11 +61,11 @@ class DataProviderPlugin
     /**
      * DataProviderPlugin constructor.
      *
-     * @param AttributeCollectionFactory          $attributeCollectionFactory Attribute Collection Factory.
-     * @param FulltextCollectionFactory           $fulltextCollectionFactory  Fulltext Collection Factory.
-     * @param StoreManagerInterface               $storeManager               Store Manager.
-     * @param ContextInterface                    $searchContext              Search context.
-     * @param CategoryFilterProvider              $categoryFilterProvider     Category Filter Provider.
+     * @param AttributeCollectionFactory $attributeCollectionFactory Attribute Collection Factory.
+     * @param FulltextCollectionFactory  $fulltextCollectionFactory  Fulltext Collection Factory.
+     * @param StoreManagerInterface      $storeManager               Store Manager.
+     * @param ContextInterface           $searchContext              Search context.
+     * @param CategoryFilterProvider     $categoryFilterProvider     Category Filter Provider.
      */
     public function __construct(
         AttributeCollectionFactory $attributeCollectionFactory,
-- 
2.25.1


From ee5a562645d2f42dfee6718a164ab0c27eb84c6e Mon Sep 17 00:00:00 2001
From: Vadym Honcharuk <vadym.honcharuk@smile-ukraine.com>
Date: Tue, 1 Mar 2022 14:33:24 +0200
Subject: [PATCH 3/3] Fixes #2410, resolve graphql error

---
 .../DataProvider/Product/LayeredNavigation/Builder/Attribute.php | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php b/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php
index 6c655eea..73742110 100644
--- a/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php
+++ b/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php
@@ -60,6 +60,7 @@ class Attribute implements LayerBuilderInterface
         Price::PRICE_BUCKET,
         Category::CATEGORY_BUCKET,
         'attribute_set_id',
+        'indexed_attributes',
     ];
 
     /**
-- 
2.25.1
</pre>

BR,
Vadym

**Comment by OvalMedia** [comment]
When I use that the patch process throws a bunch of errors. Even when I remove what seems to be mail headers?

**Comment by vahonc** [comment]
@OvalMedia,

In that case, if you want you can try to add my changes manually, there are not many, just follow my commits.

BR,
Vadym

**Comment by OvalMedia** [comment]
Now it seems to show ALL filterable attributes in the admin even attributes that are not used in that category.
But hiding attributes seems to work now.

**Comment by vahonc** [comment]
Hum... should be displayed only those attributes that are used in that category in other words that are assigned to some products which belong to this category.

Have you run a reindex?

BR,
Vadym

**Comment by OvalMedia** [comment]
Yes, does not make a difference.

**Comment by vahonc** [comment]
Could you please provide some screenshots?

BR,
Vadym

**Comment by OvalMedia** [comment]
Can I send them to you in private?

**Comment by vahonc** [comment]
Yes, please send them on my email: vahonc@smile.fr

BR,
Vadym
