### ISSUE TITLE
Telemetry causing admin errors

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#2413]
Magento Version : 2.4.3-p1 CE

ElasticSuite Version : 2.10.9

Environment : Developer

### Steps to reproduce

1. As part of our optimization/performance effort, we disable magento core modules that we don't use. Therefore, Magento_AdminAnalytics module is disabled
2. Upon admin login, we get an error that table `admin_analytics_usage_version_log` does not exist. We created the table manually so the admin will load.
3. I go to ES config settings and disable Telemetry
4. When I return to the dashboard, there is a console error for `Uncaught Error: Script error for: Magento_AdminAnalytics/js/modal/component`

### Expected result

1. Support should be added for when Magento_AdminAnalytics is not available

### Actual result

1. Currently, errors are given, even when ES Telemetry is disabled

**Comment by refueledinc** [comment]
When I enable `Magento_AdminAnalytics` but have CSP enabled, the console in admin shows:

```
The Content-Security-Policy directive 'frame-ancestors' does not support the source expression ''unsafe-inline''
```

for `{admin_path}/#smile_elasticsuite_tracker_telemetry-link`

**Comment by Morgy93** [comment]
Similar issue here, just that it seems the module does depend deeply on it now:
```
In ClassReader.php line 51:
Impossible to process constructor argument Parameter
#1 [ <required> Magento\AdminAnalytics\Model\Condition\CanViewNotification $canViewNotificationAnalytics ]
of Smile\ElasticsuiteTracker\ViewModel\Notification class

In ClassReader.php line 71:
Class Magento\AdminAnalytics\Model\Condition\CanViewNotification does not exist
```

https://github.com/Smile-SA/elasticsuite/blob/2.10.9/src/module-elasticsuite-tracker/etc/module.xml#L25

Even though it is not required in the composer.json for the 2.10.9
