### ISSUE TITLE
Double "type" attribute on script tag for tracking.js

### ISSUE THREAD

**Issue by Dam62** [Smile-SA/elasticsuite#242]
Hi.

It seems that our client has discovered a very small mistake in the calling of tracking.js in the tracker module.

https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-tracker/view/frontend/layout/default.xml

Apparently, no need to precise type="text/javascript" in the link declaration, because Magento doubles the type in the HTML (as you can see in your demo website : http://demo.magento-elastic-suite.io/ )

`<script  type="text/javascript"  type="text/javascript" src="http://demo.magento-elastic-suite.io/static/version1475056628/frontend/Magento/luma/en_US/Smile_ElasticsuiteTracker/js/tracking.min.js"></script>`

**Comment by afoucret** [comment]
PR #243 will fix this one.
Thx for reporting.

**Comment by afoucret** [comment]
PR have been merged into 2.3.x branch.
