### ISSUE TITLE
Manual sort not works with multi store

### ISSUE THREAD

**Issue by brmor-group-label** [Smile-SA/elasticsuite#2421]
Global Manual sort not works with multi Store we need to have sort on Store View

### Preconditions
Magento 2.4.1-p1
Magento Commerce Cloud

ElasticSuite Version : ES 2.10.4

Environment : Developer and Production mode

Third party modules : Amasty Import/Export

### Steps to reproduce

1. Use default position (on store view)
![image](https://user-images.githubusercontent.com/73245308/149279795-faf1c6ba-99ae-414c-a8f4-66ce57ddbc11.png)

2. Go on Category, stay at Global Scope
2. Sort manually products
3. Refresh the category on Frontend

### Expected result

1. Products position need to be the same as on BO (Global Scope) if we use default position (on store view)

### Actual result

1. Products position are no correct on frontend

**Comment by brmor-group-label** [comment]
Hi Vadym,

Check on my screen shot, on store view 1, I use default position.
![store_view_1_default_position](https://user-images.githubusercontent.com/73245308/149350695-3f67c9e1-887e-4820-be36-a136938f41bb.png)
On global scope, I use manual sort
![manual_sort_global](https://user-images.githubusercontent.com/73245308/149350694-e6937aea-9c67-4ca6-8a24-2d015d0702ff.png)

And you can see on frontend result after index and cache flush
![result_on_category](https://user-images.githubusercontent.com/73245308/149350687-4f79a4c6-91a3-4dcf-bf30-08bdeec5d0e1.png)

**Comment by vahonc** [comment]
@brmor-group-label, are you sure that products for which you set up manual sorting on Global Scope exist on Store View 1? Could you show a screenshot with Product List Preview and Sorting from Store View 1 after you set up manual sorting on Global Scope?

BR,
Vadym

**Comment by brmor-group-label** [comment]
Product Exist and is enable on store view 1
![image](https://user-images.githubusercontent.com/73245308/149357115-ae98348e-4a7a-4bcc-91c8-71c24f3ba96d.png)

But when I try to search it on store view 1 on Product List and Sorting I don't find it
![image](https://user-images.githubusercontent.com/73245308/149356810-1210cdc1-af95-4db4-9cfe-ae04c239cb32.png)

**Comment by vahonc** [comment]
@brmor-group-label, you should check the configuration of your products (like qty, price, visibility, etc) on each Store View. Or try to test it with some other products.

BR,
Vadym

**Comment by brmor-group-label** [comment]
Seems to be good on this product
![image](https://user-images.githubusercontent.com/73245308/149462767-fc767bc7-06d7-430a-83e7-01763287b7df.png)

**Comment by romainruaud** [comment]
@brmor-group-label if you have custom positions for "All store views" (and you saved them), and then switch into a particular store view, you should see your custom positions but "greyed out", like this : 

![image](https://user-images.githubusercontent.com/15340849/149782384-23c01c7d-8759-42d4-9119-09d1026b3fee.png)

I understand that's not the case according to your first screen.

**Comment by brmor-group-label** [comment]
Exactly, it's my issue
The All store view positions is not retrieve ;)

**Comment by romainruaud** [comment]
This one is very strange, since we do not reproduce it by our side, it might be due to your project specific configuration and/or code.

I don't think we can provide more "blind" support here. We can provide (paid) professional services however. If you are interested, you can contact us at elasticsuite@smile.fr

Regards
