### ISSUE TITLE
Price filter not considering max_price for configurable products

### ISSUE THREAD

**Issue by Bogardo** [Smile-SA/elasticsuite#2426]
When applying a price range filter in a category, only the minimal price for a (configurable) product is taken into consideration.

Magento Version: 2.4.2-p2
ElasticSuite Version: 2.10.8.1
Environment: Developer
Third party modules: N/A

### Steps to reproduce

I have a configurable product **Shirt** which has two configurations (simples).
1. White: price $10
2. Black: price $15

These prices seem to be properly indexed in Elasticsearch.
```
{
  "price": [
    {
      "price": 10,
      "original_price": 15,
      "is_discount": false,
      "customer_group_id": 0,
      "tax_class_id": 2,
      "final_price": 10,
      "min_price": 10,
      "max_price": 15
    }
  ]
}
```

Apply a price range filter on the category containing this configurable product:
```
{"min": 12, "max": 20}
```

### Expected result
The **Shirt** product should show up, as the `max_price` for the product is within range.

### Actual result
The product is not showing up.

---

It seems like the price filter is only considering the `price.price` field as can be seen here:
https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Price.php#L153

This `price.price` field always contains the minimum price for a configurable product. So searching for a product with a price range, targeting the `max_price` will likely yield no results.

Is this a bug, a known limitation, or a mistake on my end? I'm not sure, but at the moment I suspect it's a bug.

**Comment by romainruaud** [comment]
This is a known limitation, price.price will always contains minimal_price of a product, and that's the field that is used for filtering by price.

There is no improvement planned on this actually.

Regards

**Comment by romainruaud** [comment]
I close because nothing will happen with this issue as per my previous comment.

Regards
