### ISSUE TITLE
Filters - boolean (yesno) attribute

### ISSUE THREAD

**Issue by QbU** [Smile-SA/elasticsuite#2428]
It is not possible to filter on the false value of the boolean attribute.

Magento Version : 2.4.1 EE
ElasticSuite Version : 2.10.9
Environment : dev and prod

### Expected result
1. Filter by "No" value of the attribute.

#### Demo m2
![demo_m2](https://user-images.githubusercontent.com/4609003/150752859-892e3469-20e4-4dd2-88ba-245be3f3b22d.png)
listing: https://demo-magento-2.auroracreation.com/pl/women/tops-women.html
select filter boolean: https://demo-magento-2.auroracreation.com/pl/men/tops-men/hoodies-and-sweatshirts-men.html?erin_recommends=0

---

#### Demo Elastic Suite:
![demo_es](https://user-images.githubusercontent.com/4609003/150753196-064b3373-9e0b-442e-a70a-bbed3401f18a.png)
listing: http://demo.magento-elastic-suite.io/index.php/men/tops-men/hoodies-and-sweatshirts-men.html
crafted link (show all product): http://demo.magento-elastic-suite.io/index.php/men/tops-men/hoodies-and-sweatshirts-men.html?erin_recommends=0

**Comment by romainruaud** [comment]
Hi, you can inject your attribute code here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Boolean.php#L43

**Comment by QbU** [comment]
@romainruaud thank you
I saw this file. It's about the reverse. Now I can't see the NO value.

In the demo elasticSuite is also not visible. Is the demo on the latest version of elasticsuite?

**Comment by romainruaud** [comment]
FYI our demo is still on an old version : 2.10.5

**Comment by ArjenMiedema** [comment]
We're running into the same issue. Is there any news on this bug yet?

**Comment by vahonc** [comment]
Hi @ArjenMiedema,

We are working on it.

BR,
Vadym

**Comment by rbayet** [comment]
Hello @ArjenMiedeman,

This has been addressed by https://github.com/Smile-SA/elasticsuite/pull/2482 in the context of https://github.com/Smile-SA/elasticsuite/issues/2437

Regards,
