### ISSUE TITLE
Disabling Smile_ElasticsuiteVirtualCategory and using Magento_VisualMerchandiser results in "position = 0" not indexing 

### ISSUE THREAD

**Issue by jarcorreia** [Smile-SA/elasticsuite#2431]
Using Magento's Visual Merchandiser while having Smile_ElasticsuiteVirtualCategory module disabled, results in products that have "0" as their position being put to last on the category listing. On the index, the position property is being removed, and afterwards being attributed a random integer (for example: position = 9989787829) for sorting purposes.

### Preconditions

Magento Version : Magento 2.4.1 EE

ElasticSuite Version : 2.10.7

Environment : Production

### Steps to reproduce

1. Disable module Smile_ElasticsuiteVirtualCategory
2. Re-index catalog_category_product
3. Check indexed data on the search indexes for a product which holds position "0" on the Magento "Products in Category" section of the Categories tab. Check it against a product which holds any other position.

### Expected result

1. Position 0 should be indexed.

### Actual result

1. [Screenshot, logs]
<img width="332" alt="Screenshot 2022-01-26 at 13 05 10" src="https://user-images.githubusercontent.com/48832799/151168041-45705293-2bd3-41da-b301-fadbd4db7238.png">

I'm aware of the really good explanations by user @rbayet on [how it should work if you disable ElasticsuiteVirtualCategory](https://github.com/Smile-SA/elasticsuite/issues/1579#issuecomment-545964118). It should be reading information from the index table. I've checked my index table and it has position 0 on it. I've tried forcing all positions to 0`$categoryDataRow['position'] = 0;` (\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData::addData) as I wanted to be sure that the issue was with the indexing of the value "0" and not that the data for the position was not getting there.

**Comment by jarcorreia** [comment]
I've actually found the issue.
\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData::addData
`$indexData[$productId]['category'][] = array_filter($categoryDataRow);` filters array values of 0 because they're considered empty.

**Comment by romainruaud** [comment]
Hello @jarcorreia 

Can you give us some details ?

If I'm correct, products are indexed into Elasticsearch and therefore visible in frontend, right ?

It's just a matter that they do not have any "position" subfield in ES ?

Regards

**Comment by jarcorreia** [comment]
Hey Romain

Yes correct, the products that have "position = 0" are indexed without a position on ElasticSuite catalog product index. Later, if you debug the process of sorting by position on the product listing pages, it will create a "position = _______" (insert big random integer) which normally makes it so that the product is put to last on the listing and not to the correct position which should be the first product on the listing.

**Comment by romainruaud** [comment]
We should move the ```$indexData[$productId]['category'][] = array_filter($categoryDataRow);``` from ```\Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData::addData``` into another location in the virtual category module only.

I'm assigning this to @rbayet

**Comment by rbayet** [comment]
Hello @jarcorreia,

Pull request #2473 will alllow you to enable index 0 product position through DI injection.
I chose to keep filtering those 0 product position **even when Smile_ElasticsuiteVirtualCategory is disabled** because it could dramatically impact users in the same situation which dealt somehow with those 0 product position not being indexed.

Anyway, you will be able to filter out "0" product positions by adding this to the DI 
```
    <type name="Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData">
        <arguments>
            <argument name="filterZeroPositions" xsi:type="boolean">false</argument>
        </arguments>
    </type>
```
(the reverse is explicitely done in Smile_ElasticsuiteVirtualCategory)

Regards,
