### ISSUE TITLE
Issue with di.xml - How to treat it ?

### ISSUE THREAD

**Issue by vbidou** [Smile-SA/elasticsuite#2436]
Hello team
We have elasticsuite 2.10.8.1 installed on Magento 2.3-p1
Last weekend we installed an extension "Shop by brand" from Aheadworks.
During the configuration of the extension, we noticed a bug on the brand pages.
For example: https://ie.technostok.com/darantasia.html
Aheadworks propose us to correct the di.xml at path public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/etc
Their file is different from the native elasticuite file, and i created a Diff-Checker link which highlight those differences.
See here: https://www.diffchecker.com/9YLqEbz7

Question: Does this require to be reported as a bug in Elasticsuite git, or is the fix proposed by aheadworks legitimate to implement?
I'd like to have your opinion before proceeding the next steps.

Thanks in advance

![https___ie technostok com_darantasia html et 5 pages de plus - Personnel – Microsoft​ Edge 30_01_2022 10_57_08](https://user-images.githubusercontent.com/44623543/152211759-db6a1b25-ff13-4a30-955f-451fceee69f6.png)
![Elasticsuite   Aheadworks - di xml - Diff Checker et 3 pages de plus - Personnel – Microsoft​ Edge 02_02_2022 18_40_48](https://user-images.githubusercontent.com/44623543/152211790-b7c2b8dc-2a5c-42e5-baeb-04a0406ef889.png)
.

**Comment by romainruaud** [comment]
Hi,

Compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do for your issue. 

If the fix given by Aheadworks is fixing your issue, I suggest you continue using it. If that's not the case, you'll have to discuss with Aheadworks how the two extensions can live together.

That being said, "shop by brand" feature can be easily achieve with these two additional modules : 

https://github.com/Smile-SA/magento2-module-custom-entity
https://github.com/Smile-SA/magento2-module-custom-entity-product-link

Regards

**Comment by vbidou** [comment]
Merci Romain for all those details. All clear.
Thanks also for your proposal but we have just pruchased "Purchase by Brand" and will give a try to use it.
Maybe as well we will also update the Elasticsuite to the latest version.

But maybe I have one last advise to request from you. 
We see the following Disclaimer at the beginning of the file:
**_Do not edit or add to this file if you wish to upgrade Smile ElasticSuite to newer versions in the future._**

- If we increment the di.xml file with those elements of AheadWorks, will it be kept during future elasticsuite upgrades or will it be replaced by a new file (=need to reset the AheadWorks content) ?
- The Items provided by Aheadworks aren't worth in your opinion to use in ElasticSuite roadmap ?

Thanks for your feedbacks. François

**Comment by vbidou** [comment]
Dear Romain, quick update in order to inform you that the fix provided by aheadworks to the di.xml file is functional, and has resolved the problem. Do you confirm that this enhancement they provided is not required to be considered for ElasticSuite roadmap itself ?

**Comment by vbidou** [comment]
Dear Romain,
Aheadworks simply told me that they applied the fix documented in this thread that you closed in 2019: 
https://github.com/Smile-SA/elasticsuite/issues/1445

Not sure if the following fix needs to be reopened or not:
https://github.com/Smile-SA/elasticsuite/pull/1461

Thanks for your advise.
