### ISSUE TITLE
Have some respect for zeroooos! :D

### ISSUE THREAD

**Issue by sheepfy** [Smile-SA/elasticsuite#2437]
I have a decimal attribute, classic, normal one, people can edit it from admin, setting any numeric value on it. 
Create a product, and set value of 0.0000 on that attribute. Or update catalog_product_entity_decimal tabel and set 0.0000 value for a product on that attribute.

After fulltext indexer is reindexed, you should notice that the attribute value is not present in elasticsearch.
In my case, attribute_code = weight_factor

select * from catalog_product_entity_decimal where attribute_id = 309 and entity_id = 225405;
![image](https://user-images.githubusercontent.com/17467949/152351649-8da9edff-9fea-4b71-94bf-431c41103223.png)

vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php
$value = array_filter($value); <- this line doesn't like the zeros

PS:
full es json response:
```
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 0.0,
        "hits": [
            {
                "_index": "magento2_default_catalog_product_20220203_122828",
                "_type": "_doc",
                "_id": "225405",
                "_score": 0.0,
                "_source": {
                    "sku": "XXXXXX",
                    "entity_id": "225405",
                    "weight_factor_2": [
                        0.0
                    ]
                }
            }
        ]
    }
}

```

full es request body: 
```
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "entity_id": "225405"
                    }
                }
            ]
        }
    },
    "_source": ["entity_id", "sku", "weight_factor", "weight_factor_2"]
}
```

**Comment by vahonc** [comment]
Hello @sheepfy,

We will look into this as we have other requests that are related to a similar issue.

BR,
Vadym

**Comment by rbayet** [comment]
Hello @sheepfy,

This has been adressed by https://github.com/Smile-SA/elasticsuite/pull/2482 (https://github.com/Smile-SA/elasticsuite/issues/2437)

A new per-attribute setting "**Include zero or false values**" is available to enable indexing and filtering on 
- false/No value of boolean attributes 
- 0 for integer/decimal attributes 

![image](https://user-images.githubusercontent.com/2353374/158319803-0f6032e3-f23a-4d6e-867e-6a02eb88d7a2.png)

For a boolean attribute, if enabled and the facet sort order is set to Admin Sort, both Yes and No values will be shown, with Yes in first position :
![image](https://user-images.githubusercontent.com/2353374/158319940-1417dd92-ffc1-4b00-a0ec-92bbcafed052.png)

Regards,
