### ISSUE TITLE
Optimizer boost on attribute value of configurable product is based on lowest value of simple product 

### ISSUE THREAD

**Issue by Melleschepers** [Smile-SA/elasticsuite#2438]
### The problem
When setting-up an optimizer with model "boost on attribute value", the boost of configurable products is based on the lowest value of the simple products.. instead of the value of the configurable product itself.

### Some context
First of all. Thanks for all the work on this great module! Your Elasticsuite module is an absolut winner for every Magento store 🥇 !

We use optimizers for customizing product sorting in our categories. We have a large catalog with simple products, configurable products, and simple products part of configurable (not visible in storefront). Therefore all our products (simple and configurable) have an attribute "boost_score" with a value. The value of this attribute in a configurable and their child products (simple) can differ.

For example:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

sku | boost_score
-- | --
CP-PRODUCTX | 12464
S-PRODUCTX1 | 3213
S-PRODUCTX2 | 100
S-PRODUCTX3 | 4515
S-PRODUCTX4 | 3457
S-PRODUCTX5 | 1179

</body>
</html>

In elasticsearch it looks like this for the configurable product
![image](https://user-images.githubusercontent.com/13859086/152348101-68bcdd97-0af9-4ecd-8f6c-041117bbe710.png)

### Preconditions
Magento Version : 2.4.3-p1
ElasticSuite Version : 2.10.9
Environment : development
Third party modules : N/A

### Steps to reproduce

1. Add attribute boost_score and fill it in configurable and simple products with an value
2. Set up an optimizer with model "boost on attribute value" on catalog product view.. based on the boost_score attribute with boost impact 'high'.
3. Preview and check score CP-PRODUCTX (configurable product)

### Expected result

1. The boosting score of CP-PRODUCTX is based on the value of the product itself (CP-PRODUCTX) -> 12464

### Actual result

1. The boosting score of CP-PRODUCTX is based on the lowest value of the children(simple) products -> 100

![image](https://user-images.githubusercontent.com/13859086/152350217-a979c647-00aa-4aa3-ae33-19872d624dd6.png)

### Questions
1. Is this intended behavior for optimizers? (so maybe its not a bug)
2. What are the use-cases when boost based on the value of the product itself (CP-PRODUCTX) is not desirable. 
3. Would it be a good idea to make this some sort of a setting (so you can chose if you use the parent/config product value.. or the values of the children/simple products)? ( I saw some modes in https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Search/Request/Query/FunctionScore.php but don't know if its related)

### Temporary workaround
We will temporary empty/not fill the "boost_score" for simple products part/children of configurable product.. or we will fill it with the value of the configurable product.. to get our desired sorting.

**Comment by romainruaud** [comment]
Merging of child data occurs here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L69

Maybe in you case you just don't want to merge children data for this particular attribute.

**Comment by romainruaud** [comment]
I think we should not have the forbidden attributes hardcoded here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L34

This should be injected through di.xml in the constructor to allow extending/overriding it.

@vahonc can you propose a PR for this ?
