### ISSUE TITLE
Boost Scoring by Age,popularity ? Also integrating price file by LRU cached-JDBC Sql connection?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#244]
Take a look at this old document (slideshare):
http://www.slideshare.net/lucenerevolution/potter-timothy-boosting-documents-in-solr
or this article: https://jontai.me/blog/2013/01/advanced-scoring-in-elasticsearch/

They describe using RECIP with SOLR to boost the score of relevancy by the age of the Insertion of document! This is very important imo! As newer products tend to be more relevantly searched for than older products.

Plus a static external database to POPULARITY SCORE booster(or a child document?) that can be rapidly changed without affecting primary indexing load.

Stock/Price component to external LRU cached SQL (JDBC) source to not have to populate highly dynamic (price+stock+Popularity data) into static content. -- or place in sub-document that won't affect primary index load (1 mill+ products/documents!).

Are these possible to implement easily? 

They are pretty simple to do with SOLR but i'm not sure how external LRU Cached JDBC sourced would merge with elasticsearch design or if another method (sub-documents?) would be more appropriate.

**Comment by afoucret** [comment]
Hi @southerncomputer ,

I worked on the the SolR solution you are describing three years ago. It was working but without entering the details, they were several drawback with this solution. It is worst with ES which is distributed out of the box (how to shard the data coming from JDBC consistently with ES sharding, how to expires the cache, ...).

As you may have noticed we pushed an optimizer feature today on the branch 2.3.x. Currently you can only boost product that match a rule. If you assign a boost of 100% to all product being in stock, the score is multiplied by two. The optimizer are cumulated, so you can create several of them (they are multiplied).

It allows you to influence ranking of the product into the category view and into the fulltext search.

It is only the beginning of the bigger feature that will as we will include more optimizer in the future (popularity, scripted metrics and even machine learning based one) into the next release of ElasticSuite.
