### ISSUE TITLE
No products in the category pages or in the searches

### ISSUE THREAD

**Issue by NikodFr** [Smile-SA/elasticsuite#2440]
Over the past few days, we encountered a bug linked to ElasticSuit that we couldn’t fix.
When we activate ElasticSuit on the front office, products do not appear in categories.
On the Back Office, in the categories, we cannot use the merchandising option. An error message appears about the category that would be empty even if we can clearly see the products of the back office.

We upgraded the module’s software from 2.8.0  to 2.8.4 The problem remains… 

We installed an RGPD module a day before the bug but we deleted it since them and the problem remains. 

However, when we desactivate Elastic Suit, the products become instantly visible in front office in the categories.

**Preconditions**
Magento Version : 2.3.2
ElasticSuite Version : 2.8.4
Environment : Production
Third party modules : We installed an RGPD module a day before the bug but we deleted it since them and the problem remains. 

**Steps to reproduce**
Over the past few days, we encountered a bug linked to ElasticSuit that we couldn’t fix 
When we activate ElasticSuit on the front office, products do not appear in categories.
On the Back Office, in the categories, we cannot use the merchandising option. An error message appears about the category that would be empty even if we can clearly see the products of the back office.

We upgraded the module’s software from 2.8.0  to 2.8.4 but the problem remains… 

**Expected result**
1. have the elasticsuit module activated and the products visible in front
2. be able to use the elasticsuit merchandising functionality in BO for the categories

**Comment by romainruaud** [comment]
Hi @NikodFr 

Do you clear cache and reindex after enabling the extension ?

Is Elasticsuite selected as the default search engine in magento ?

**Comment by NikodFr** [comment]
@romainruaud 

Absolutely, we have clear cache and reindexed all indexers.
Elastic is well selected as a search engine.

**Comment by NikodFr** [comment]
Hello @Vadym,

I didn't notice any error during reindexing and I have already set the debug mode for elasticsuite.

Here is the system.log file >> https://drive.google.com/file/d/1TCqePNg25FjQUdLm8hLp09jT3PCLBvx8/view?usp=drive_web

Thank you for your help

**Comment by romainruaud** [comment]
Hi @NikodFr 

I just saw your message on twitter.

We do propose paid support, you can reach us at elasticsuite@smile.fr

**Comment by NikodFr** [comment]
Hi @romainruaud.

Perfect. I have just sent the email
Is it possible to have a quick response?
Thank you in advance.

**Comment by romainruaud** [comment]
@NikodFr considering the fact this issue was project-specific and the discussion was pursued offline as a commercial discussion, I'm closing this issue.

Regards
