### ISSUE TITLE
No results when searching for a term with uppercase letters mid string?

### ISSUE THREAD

**Issue by thehugh100** [Smile-SA/elasticsuite#2442]
I'm having trouble with searching for terms with mixed case:

'searchterm' returns the expected results,
'Searchterm' returns the expected results,
'SearchTerm' returns no results.

I've consulted and wiki and have looked at the module-elasticsuite-core/etc/elasticsuite_analysis.xml file but I don't see anything obvious.

I have no doubt I may be missing something simple but I can't seem to find the answer!

**Comment by thehugh100** [comment]
Hi @vahonc

We have DeWalt products on our site, they are listed as DEWALT - etc

searching for dewalt or DEWALT returns the products as expected. When we tested on mobile we found that autocorrect would correct 'dewalt' to DeWalt as it recognised the brand name.

The 'DeWalt' search returns no products at all.

After noticing this trend I searched for many variations of search terms that would previously return products with random capitalisation e.g. 'SearCh TerM' rather than 'Search term' and had an empty result set returned.

Is this expected behaviour? I switched back to the elasticsearch module as the search provider and the issue disappeared!

Is there a simple configuration setting I'm missing?

Thank you for you response.

**Comment by rbayet** [comment]
Hello @thehugh100,

Indeed this behaviour is unexpected.
In the  module-elasticsuite-core/etc/elasticsuite_analysis.xml file, the `world_delimiter` word/token filter logically ensures that we split a word according to a case change (so "DeWalt" becomes "De" + "Walt") **while preserving** the original word/token.
So searching for "dewalt" will search for "dewalt", but searching for "DeWalt" should search both for "dewalt" and "de walt".

Here in cerebro when checking the full `standard` analyzer (which includes a lowercase filter)
![image](https://user-images.githubusercontent.com/2353374/154978931-e5502ea9-5104-4944-9db9-52f97817ae7a.png)

This mechanism was specifically built in to avoid having to resort to thesaurus for the classic "StarWars" usecase.

Can you provide more information on your installation ?
- Version of Magento 2
- Version of Elasticsuite
- Version of Elasticsearch server 

Regards
