### ISSUE TITLE
Sort by custom condition

### ISSUE THREAD

**Issue by pvalium** [Smile-SA/elasticsuite#2449]
Hi all

I need to change price sortingin category view (and search view) by a custom condition: The price of products are calculated for each customer by third table by a serie of conditions. I don't use the native price of magento.
In mysql is not problem, I can join subquery and do work, ,but with elastic search is not running.
I think I must to index my third table in elastic search, but I don't know which steps I must follow for this feature.

Anybody can help me?

Thanks in advance

**Comment by romainruaud** [comment]
Hi, I think everything about indexing/querying additional content is covered in the developer's guide : https://github.com/Smile-SA/elasticsuite/wiki#developers-guide

Regards

**Comment by pvalium** [comment]
It's solved, thanks!

**Comment by romainruaud** [comment]
good to know :)

Best regards
