### ISSUE TITLE
Sorting of product is not proper

### ISSUE THREAD

**Issue by sumitgithub** [Smile-SA/elasticsuite#245]
I am getting all wrong sorting on the category list page.
If I select price as by default sorting options from magento admin. Its doesn't show expected results and if I disable smileelasticsuit modules sorting works properly.

**Comment by romainruaud** [comment]
Hello @sumitgithub and thank you for submitting this issue.

Could you precise which version of Magento and Elasticsuite you are using ?

I am not able to reproduce this one on the 2.3.x branch with Magento 2.1.2, maybe you are using an older release ?

Regards,

**Comment by romainruaud** [comment]
I am closing this one since we do not reproduce it on our side, and also due to inactivity.

@sumitgithub feel free to reopen it and to add more details if your are still facing the issue.

Best regards
