### ISSUE TITLE
Question: Limit results for virtual categories?

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#2453]
We're using the virtual category feature to create landing pages. Is there a way to limit the results? Say 200 products?

**Comment by vahonc** [comment]
Hello @refueledinc,

At the moment, it is not possible from out of the box to set any limits for results in Virtual Categories. This requires the implementation of custom code and it's not an easy task as it can affect the behavior of many aspects of our module.

BR,
Vadym

**Comment by romainruaud** [comment]
Hi @refueledinc 

if you want to limit the number of displayed products, you might have also issues with sort orders : if the page is capped to 200 products, you might not have the same products when sorted by price than with sorted by name.

Vadym is right, you have to go with custom code to achieve this, as this is not something we plan to integrate in our roadmap.

Regards
