### ISSUE TITLE
Custom attribute search

### ISSUE THREAD

**Issue by pvalium** [Smile-SA/elasticsuite#2454]
Soyy for my noob question, but I can't get results for a search with custom attribute 'barcode'.
I've created a custom attribute, and set can search in true. I've reindex.
When I type the barcode in search box, in autocomplete gets correct results, but when I type enter, and go to catalogsearch/result, there aren't any results.
I don't know If I need to follow any extra field.
![image](https://user-images.githubusercontent.com/20306610/154986131-af523330-cdbd-4987-9e1c-0f791be1a4fc.png)
![Sin-título-1](https://user-images.githubusercontent.com/20306610/154986487-3e62912c-d2df-4ddf-94b9-bdf03ed9ea11.png)

Thanks for help

**Comment by vahonc** [comment]
Hello @pvalium 

Firstly, we need more details about your environment, which versions of the Magento and ElasticSuite you are using, have you installed some third-party extensions, etc.

Are you able to see the product from autocomplete suggestion when you browse directly in the category to which belongs this product? Please provide configuration (screenshots) of this product from Magento BO.

P.S. If possible, switch the admin interface language to English when taking screenshots, this will help us understand your issue more clearly.

BR,
Vadym

**Comment by pvalium** [comment]
Solved. There was a third party module that was modifying collection.

Thanks
