### ISSUE TITLE
Optimized results are not reflected in the frontend

### ISSUE THREAD

**Issue by rowanfuchs** [Smile-SA/elasticsuite#2457]
I've created a few optimizers however they do not seem to come accross into the frontend. Out of stock products are pushed up into the results rather than down.

All set optimizers work very well and as expected in the backend:
![results](https://user-images.githubusercontent.com/48676736/155358893-413d1e6a-a99b-46ba-860e-6dd5d3174eb5.jpg)

**Comment by rowanfuchs** [comment]
Maybe I should ask the question a little different, where are the optimizers set for the frontend? I will start my debugging there.

**Comment by vahonc** [comment]
Hello @rowanfuchs,

Usually, everything should work as expected, maybe there is something wrong with your environment. 

Are you using some custom theme on the frontend? What is the sort order of the products (by Position, Product Name, or Price)?

Can you provide us with a screenshot of what the results look like on the frontend?

BR,
Vadym

**Comment by rowanfuchs** [comment]
Hi Vadym,

Thank you for taking the time to think about this with me.
I've obfuscated the results but they indeed aren't similair to the smile "Base Results" or "Optimized Results"
![results_frontend](https://user-images.githubusercontent.com/48676736/155515479-20277627-b33c-4c91-b879-3f408ced0f1e.png)

I can confirm that we use a custom theme based on Luma and i've disabled all custom modules, ran a setup:di:compile and disabled the caching.

Once I follow xdebug I see it passes smile but also the magento base search functionality. 

Could you point me in the direction where the Optimizers are applied I will try to debug further from there, any other idea's or suggestions are welcome.

With thanks,

**Comment by vahonc** [comment]
@rowanfuchs,

Can you provide us with a screenshot of what the results look like on the frontend?

BR,
Vadym

**Comment by rowanfuchs** [comment]
Attached the (redacted) final results on the autocomplete (quicksearch)

![stylized_results](https://user-images.githubusercontent.com/48676736/155519113-87cec328-1f60-4a6d-b607-7298d86fa737.jpg)

**Comment by vahonc** [comment]
Could you once again provide a screenshot with the configuration of your Optimizers, as it showed on my screenshot below?

![Screenshot from 2022-02-24 13-57-23](https://user-images.githubusercontent.com/67791361/155519964-924106df-7119-4f8a-81d7-c582cc3141da.png)

BR,
Vadym

**Comment by rowanfuchs** [comment]
![optimizer_view](https://user-images.githubusercontent.com/48676736/155522244-1b97089e-faad-40fe-ac23-5ce4e6bac0c1.jpg)

Note that I've also tested all other store views (there are exact copies of this rule).

**Comment by vahonc** [comment]
@rowanfuchs,

Try to make some tests with  **Boost value (%)** in diapason from -99 to 10000.

BR,
Vadym

**Comment by rowanfuchs** [comment]
While testing in the backend the results show as how we both would expect. But when I call the "search/ajax/suggest/?q=" endpoint 3 out of 5 results are out of stock. If I set up a "easier" result as in if the collection contains "SKU X" add 1000% the backend shows a top result with this sku but the frontend remains static without any boosts.

If i follow the call with xdebug I notice that the results pass the smile module however they seem to end up in Magento's search (Magento_Search) module before being displayed.

I'm torn as I absolutely believe this is my setup that's creating discrepancies, I just can't seem to  pinpoint the location where the results are distorted.

**Comment by vahonc** [comment]
@rowanfuchs,

It looks like smth are wrong with your environment, especially for the frontend part, maybe you are using some cache engine like Varnish or etc.

Also, you can try to continue your debugging from this [point](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-optimizer/Plugin/QueryRewrite.php#L69).

And if your environment is not in production mode you can try to enable logging ES queries in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode` and the queries will be logged into the `system.log`.

BR,
Vadym

**Comment by rowanfuchs** [comment]
Vadym,

Thank you very much from providing the point of debug, your initial guess on sorting seems to be right.

"Field _score does not exists in mapping"

the results seem to be sorted on ID rather than scoring fields.

**Comment by vahonc** [comment]
Hello @rowanfuchs,

If I understand correctly, you solved your problem and this ticket can be closed?

BR,
Vadym

**Comment by rowanfuchs** [comment]
Hi Vadym,

Sadly not yet, but I do have a direction in which I can debug. Once I find more i'll update this ticket.

With thanks,
Rowan

**Comment by rowanfuchs** [comment]
Once I debugged further into the issue I noticed that my other Optimizers did work except for the stock optimizer. Once I adjusted the stock optimizer from "Product in stock = false results in -99%" to "Product in stock results in +99%" it started to work.

Thank you very much for the pointers.
