### ISSUE TITLE
ElasticSuite not escaping forward slash aka special characters

### ISSUE THREAD

**Issue by IbrahimS2** [Smile-SA/elasticsuite#2458]
### Preconditions

Debian 11
Dockerised Elasticsearch 7.9.3 / icu & phonetic plugins

Magento Version : 2.4.3-p1

ElasticSuite Version : Latest

Environment : Production

Third party modules : Nothing relevant

### Steps to reproduce

1. add a product with a name that contains forward slash i.e _XYZ one two 6/4_
2. Search it

### Expected result

1. It escape the forward-slash and show the relevant results

### Actual result

1. Returns a 404

**Comment by vahonc** [comment]
Hello @IbrahimS2

I was not able to reproduce your issue on the fresh Magento EE 2.4.3 with default Sample Data.

I created two test products with names that contain a forward slash:

![Screenshot from 2022-02-25 13-28-58](https://user-images.githubusercontent.com/67791361/155708543-7ce2061d-063f-48d9-b050-7e3e941ccd97.png)

Then I tried to search it on frontend:

![Screenshot from 2022-02-25 13-23-59](https://user-images.githubusercontent.com/67791361/155708740-d402337f-3209-420e-aa22-331276cba639.png)

![Screenshot from 2022-02-25 13-24-16](https://user-images.githubusercontent.com/67791361/155708772-84f4ef58-7dd5-451a-8a25-88901238b248.png)

![Screenshot from 2022-02-25 13-26-24](https://user-images.githubusercontent.com/67791361/155708798-62f19782-9b58-40d3-9044-3d601365c36e.png)

![Screenshot from 2022-02-25 13-27-35](https://user-images.githubusercontent.com/67791361/155708824-b82afd59-8466-45f9-921c-08d4cc44769b.png)

So as you can see there are not any unexpected results or 404 errors.

The only difference, in my local environment I use **ElasticSearch 7.14**. Perhaps you are using some custom theme on your website? Please provide more details with screenshots about it.

Also please provide an extract of the queries that are being sent to ES when you are searching products. You can get it from the `system.log` file if you activate the **Debug mode** of Elasticsuite in: `Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`

BR,
Vadym

**Comment by IbrahimS2** [comment]
@vahonc I already checked and confirmed; it is irrelevant to ElasticSuite; it is due to Amasty SEO Toolkit ![image](https://user-images.githubusercontent.com/19901858/156073005-644e1884-92e7-44dd-b767-4dfaaeb1b6e9.png)
