### ISSUE TITLE
Product Widget Should Not Include Configurable (parent) Products

### ISSUE THREAD

**Issue by denis-zyk** [Smile-SA/elasticsuite#2466]
When the product widget is configured using **Select Products By** with a list of specific SKUs (all of which are simple products), the result includes configurable (parent) products as well.
![image](https://user-images.githubusercontent.com/44240055/156617336-adf92121-3c08-4343-b089-aed0a5785c46.png)

If I understand correctly this is now the default behaviour by design, because parent products also have child SKUs indexed, e.g.:
```...
"hits": [
      {
        "_index": "default_catalog_product_20220303_153058",
        "_type": "_doc",
        "_id": "7458",
        "_score": 1.0,
        "_source": {
          "entity_id": "7458",
          "attribute_set_id": "4",
          "type_id": "simple",
          "sku": "326582",
          "has_options": false,
          "required_options": false,
          "created_at": "2020-10-22 01:31:05",
          "updated_at": "2020-10-22 01:31:05",
          "row_id": "7458",
          "created_in": "1",
          "updated_in": "2147483647",
          "visibility": "4",
...
        },
        "sort": [
          1499.0,
          1.0,
          7458
        ]
      },
      {
        "_index": "default_catalog_product_20220303_153058",
        "_type": "_doc",
        "_id": "7457",
        "_score": 1.0,
        "_source": {
          "entity_id": "7457",
          "attribute_set_id": "4",
          "type_id": "configurable",
          "sku": [
            "bolton-spisestol",
            "326582",
            "326581"
          ],
...
```
### Preconditions

Magento Version : 2.4.3 EE

ElasticSuite Version : 2.10.9.1

Environment : Both

### Steps to reproduce

1. Add a Product widget to any CMS page
2. Configure product widget to **Select Products By**: SKU, with a list of simple products
3. Make sure some of those simple products are assigned to configurable product

### Expected result

1. Widget displays only products from the SKU list

### Actual result

1. Widget displays products from the SKU list including parent products (which do not strictly match any SKU from the list)

**Comment by vahonc** [comment]
Hello @denis-zyk,

> Widget displays products from the SKU list including parent products (which do not strictly match any SKU from the list)

This is currently the default behavior out of the box.

This could be solved by implement one or several rules (isSimple, isGrouped, isBundle, ...) according to existing "special attributes" https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-rule/etc/di.xml#L21

against the field `type_id`: https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L31

the data already exists in the index so this would require: 1) to add a specific attribute; 2) to contribute it systematically for all products.

The idea here is to create an additional attribute and then use that attribute in Select Products By Condition e.g. SKU + product_type (only simple products to select).

Another code approach is to take inspiration from https://github.com/Smile-SA/elasticsuite/blob/491eaa3ee89b35fa74a84d8686040371080ab613/src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php#L101 and create another plugin that would add the specific filter on `type_id`.

You can go with "no-code" way, if you already have a specific attribute that you know and which can be used to distinguish between product types (this could be the attribute_set for instance).

Most likely adding rules for product types to distinguish between product types will be added as an 'enhancement' ticket to the roadmap of the features for our module in the next releases.

BR,
Vadym

**Comment by davidandersson1** [comment]
Hello,

We have same issue in magento 2.4.3-p1 with smile/elasticsuite version 2.10.9.1 and i confirmed without smile/elasticsuite module its works fine with native magento.

If we add any child sku which is assigned to any bundle item then parent/bundle sku showing in Product Carousel in backend as well frontend!

Is there any solution here?

Thanks,
David Andersson
