### ISSUE TITLE
Autocomplete product attribute url not correct

### ISSUE THREAD

**Issue by murphy1484** [Smile-SA/elasticsuite#2469]
In the autocomplete the url of a product attribute contains the name of the attribute twice.

E.g /nl/catalogsearch/result/?brand=brand_name&q=brand_name
Shouldn't this be the original query parameter?
/nl/catalogsearch/result/?brand=brand_name&q=search+query"

**Comment by romainruaud** [comment]
That's by design, because "search query" could be partial (if the user did not finish to type a word), leading to a inacurrate result page.

If you want to change this behavior, you can override \Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Attribute\ItemFactory

Regards
