### ISSUE TITLE
Show "all" products is capped to 20 items

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#247]
When authorizing the users to apply "Show all" on the frontend pages, the results become irrelevant : pageSize gets capped to 20 items.

```
$size = $this->_pageSize ? $this->_pageSize : 20;
```

Probably the 'all' directive put by magento is not properly handled.

**Comment by afoucret** [comment]
I have modified your PR to remove the 1000 items capping and let developers the responsability of settings a limit if they want (great power ....).
