### ISSUE TITLE
All categories and search saying:  "We can't find products matching the selection" 

### ISSUE THREAD

**Issue by jesperbrejning** [Smile-SA/elasticsuite#2474]
HI, 

I have installed the module with no problem, but when i go to a category page or do a search i get "We can't find products matching the selection"

ex. https://dev.babygear.dk/legetoj/borneboger.html

I have reindexed couple of time, but still the same and No errors in log files. 
In Indices Status: I can see 5 indexes with status LIVE and size 2 MB to 86 MB

Magento Version : 2.4.3 CE
ElasticSuite Version : 2.10.9.1
Environment : Developer

Any Idea what is going wrong?

**Comment by jesperbrejning** [comment]
When I curl the elasticserver, I get the following reult.

babygear@ip-xxx-xx-xx-xx:~/www$ curl -X GET xxx.xx.xx.xx:9200/_cluster/health?pretty
{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 26,
  "active_shards" : 26,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 16,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 61.904761904761905

**Comment by jesperbrejning** [comment]
Also in Admin cateogries we get the following message: 

Your product selection is empty for the selected Store View. If you are running a multi-store setup, please check this [manual page](https://github.com/Smile-SA/elasticsuite/wiki/VirtualCategories#previewing-virtual-categories-on-a-multi-store-setup) for more informations.


![Skærmbillede (56)](https://user-images.githubusercontent.com/48727132/157396759-80974540-dafd-4a2e-b5ea-47239c6d0191.png)

**Comment by vahonc** [comment]
Hello @jesperbrejning,

For the moment it's hard to say what exactly could be causing your problem, more details are needed.

- Have you are using any third-party extension?

- Check if your ElasticSearch is installed and running: `curl -XGET 'http://localhost:9200' //or use your alias name`

- Check if all is good with indexes: `curl http://localhost:9200/_cat/indices?v`

- Check if cron works correctly in your environment

- Check if ElasticSuite is selected as main search engine via admin panel in the page:
`Stores -> Settings -> Configuration -> Catalog -> Catalog -> Catalog Search -> Search Engine`

You don't see a product listing for all categories or just for some in Admin? Are these real categories or virtual ones?

Have you are using a multi-store setup? If so, you must ensure to choose first the store you want to preview on the Store Switcher block. Then you will be able to preview the products of the virtual category correctly.

Also, you can check an extract of the queries that are being sent to ES when you are browsing categories. You can get it from the system.log file if you activate the Debug mode of Elasticsuite in:    
`Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`

BR,
Vadym

**Comment by jesperbrejning** [comment]
Hi, 

FYI: We are using the module EmbeddedERP from Boostmyshop and when we disable this module Smile Elasticsuite is working. So it must be a conflict between EmbeddedERP from Boostmyshop  and Smile Elasticsuite . 

Probably related to stock status

**Comment by romainruaud** [comment]
If your module is creating something called "stock", like an attribute, it might definitely cause conflicts with Elasticsuite.

As it's due to a third-party extension, I'm closing this issue.

Regards
