### ISSUE TITLE
The "Only Discounted products" virtual rule shows wrong configurable if there is an out of stock discounted variant but the available has no discount

### ISSUE THREAD

**Issue by hbarza** [Smile-SA/elasticsuite#2491]
A virtual category by only showing discounted products shows wrong configurable products if the available variants have no discount but there are some variants that are out of stock and having discounts.

### Preconditions

Magento Version: CE 2.4.3-p1

ElasticSuite Version: 2.10.8.1

Environment: Any mode (production, developer)

Third party modules :

### Steps to reproduce

1. Create a configurable product with at least two simple products in it
2. Set one of the simple products out of stock with no qty and define a special price for it
3. Set the other simple product in stock with qty but without any special price (has not any discount)
4. Create a virtual category to shows only discounted products (virtual rule: only discounted products)

### Expected result

1. The configurable product should not list as discounted product in the category

### Actual result

1. It shows the configurable product in the category storefront as discounted product with the original price
![Screenshot from 2022-03-16 10-57-17](https://user-images.githubusercontent.com/737761/158564567-0a2fee3f-9aba-49e2-9563-18eaec44ceb4.png)

**Comment by romainruaud** [comment]
Might it be related to #866 ?

**Comment by romainruaud** [comment]
Can you provide an extract of what is contained in the catalog_product_price_index table for this product ?

Regards
