### ISSUE TITLE
Getting error while upgrade elasticsuite

### ISSUE THREAD

**Issue by ia-gaurav** [Smile-SA/elasticsuite#2492]
In ServiceManager.php line 1129:

  An abstract factory could not create an instance of magentosetupconsolecommandconfigsetcommand(alias: Magento\Setup\Console\Command\ConfigSetCommand).

In ServiceManager.php line 940:

  An exception was raised while creating "Magento\Setup\Console\Command\ConfigSetCommand"; no instance returned

In AbstractFactory.php line 131:

  Type Error occurred when creating object: Smile\ElasticsuiteCore\Setup\ConfigOptionsList, Too few arguments to function Smile\ElasticsuiteCore\Setup\Con
  figOptionsList::__construct(), 1 passed in /vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 1
  21 and at least 2 expected

**Comment by romainruaud** [comment]
Please, when creating an issue, fill the details required (Magento + ElasticSuite version especially ...).

Otherwise we are blind and cannot dig into it.
