### ISSUE TITLE
Error with category view - Layered Navigation Filters

### ISSUE THREAD

**Issue by pawel86k** [Smile-SA/elasticsuite#2493]
Magento Version : 2.4.4-beta4
ElasticSuite Version : 7.9.3
module-elasticsuite-catalog: 1.6.2

The problem appeared after the magento upgrade. The problem is with displaying the data in the file
vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/adminhtml/web/template/category/filter-config/dynamic-rows.html line 36-42

[2022-03-18 02:58:22] [ERROR] Failed to load the "Smile_ElasticsuiteCatalog/category/filter-config/dynamic-rows" template requested by "category_form.category_form.display_settings.facet_config".

**Comment by romainruaud** [comment]
@pawel86k your Elasticsuite version (7.9.3) is probably the Elastic**search** version, not the Elasticsuite one.

Could you please precise the Elasticsuite version you are using ?

In any case, being compatible with Magento 2.4.4-beta4 (and 2.4.4 stable when it will be live) is on top of our priority, so we'll have a particular attention for this one.

Regards

**Comment by pawel86k** [comment]
Sory so exactly elasticsuite 1.6.2 but also tried on version 1.6.1

**Comment by romainruaud** [comment]
@pawel86k the Elasticsuite version is something like 2.9.x or 2.10.x

Please provide the output of "composer info | grep elasticsuite" at the root of your Magento2 directory

**Comment by pawel86k** [comment]
@romainruaud "smile/elasticsuite": "2.10.8.1",

**Comment by pawel86k** [comment]
@romainruaud fix
vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/adminhtml/web/template/category/filter-config/dynamic-rows.html
change line 29-44 

`<tbody>
                    <tr repeat="foreach: elems, item: '$record'"
                        class="data-row"
                        css="'_odd-row': $index % 2">
    
                        <td if="dndConfig.enabled && $record().isPinned()"
                            class="data-grid-draggable-row-cell"
                            template="name: dndConfig.template, data: dnd"></td>
    
                        <td if="dndConfig.enabled && !$record().isPinned()"></td>
                        
                        <td if="elem.template"
                            visible="elem.visible() && elem.formElement !== 'hidden'"
                            disable="elem.disabled"
                            css="$parent.setClasses(elem)"
                            template="elem.template"
                            attr="'data-index': index"></td>
                        
                    </tr>
                </tbody>`

**Comment by romainruaud** [comment]
This one is to be done as part of 2.4.4 compatibility.

Please try to propose something that keeps backward compatibility (maybe keep both ``data-grid-draggable-row-cell`` and ``col-draggable``)
