### ISSUE TITLE
Magento 2.4.4 compatibility

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2494]
Magento 2.4.4 will be live at the end of April.

Actually, we only "build" the 2.10.x branch against beta builds of Magento, and everything goes well.

However, we now need to enter the last stage of testing it, by going through all the Elasticsuite related screens in the back-office on a 2.4.4 version of Magento to check everything is operating normally.

@vahonc as soon as other priority tasks are done, you can engage some time on this one.

Regards

**Comment by vahonc** [comment]
It seems that on Magento 2.4.4 we are not able to create New Optimizers because this page is broken.

![Screenshot from 2022-04-07 10-18-40](https://user-images.githubusercontent.com/67791361/162152962-854025db-12f1-404c-b236-5e10ab1d7601.png)

We can't add any Rule conditions for Optimizer and Boost value (%) slider from the Boost & Bury section for Constant Model is also broken.

In Console I see errors: [ERROR] Failed to load the "..." component.

I'll try to dig into this.

**Comment by romainruaud** [comment]
![image](https://user-images.githubusercontent.com/15340849/162155950-c9510565-907c-4ce4-9f47-caf3b014b022.png)

This file was here on Magento 2.4.3 (and since the inception).

https://github.com/magento/magento2/blob/2.4.3/lib/web/MutationObserver.js

It's missing in 2.4.4 (probably they removed it ...) : 

https://github.com/magento/magento2/tree/2.4-develop/lib/web

**Comment by vahonc** [comment]
Yes, according to Magento 2.4.4 Release Notes the jQuery UI has been upgraded to the latest version (v1.13.0). And some jQuery components for the v1.10.0 version have been removed. Therefore many pages where we use these old components could be broken.

**Comment by romainruaud** [comment]
https://community.magento.com/t5/Magento-DevBlog/Technical-platform-changes-to-expect-in-Adobe-Commerce-2-4-4/ba-p/485506

Built-in JS libraries 

Upgrade of jQuery, TinyMCE, knockout and underscore library. 
**Removal of Modernizr, es6-collections, FormData.js & MutationObserver.js library** 

Thank you Adobe... once again, nice backward compatibility for a minor release.

**Comment by romainruaud** [comment]
I think we can re-add the MutationObserver.js library, probably in the ElasticsuiteCatalogRule module since it's used both by virtual categories and optimizers.

We should be able to use it then on this file : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-rule/view/adminhtml/web/js/component/catalog/product/form/rule.js

By replacing the 

```js
define([
    'Magento_Ui/js/form/components/html',
    'jquery',
    'MutationObserver'
], function (Component, $) {
``

by something like : 

```js
define([
    'Magento_Ui/js/form/components/html',
    'jquery',
    'Smile_ElasticsuiteCatalogRule/js/mutationObserver'
], function (Component, $, MutationObserver) {
``

**Comment by vahonc** [comment]
Yes, I agree with you.

I think we need to create a new branch like 2.11.x because it looks like we will need to change/fix a lot of things. And then create a new release with an indication to use Magento version >= 2.4.4.

**Comment by romainruaud** [comment]
I'm afraid we might have to do this, but for now I'd like to try to have something BC and avoid a 2.11.x.

Eg : this issue, if we introduce MutationObserver as a library of our module, should be still backward compatible.

I tend to think that #2493 could be fixed on a BC way also.

But I'm not sure for the other issues, especially the #2502 which seems to be related to jQuery update.

Let's dig a bit more and if there are too much things to fix,

**Comment by chris-brabender** [comment]
There's also now a distribution value in the client info from $this->client->info()['version']

There could be a check on distribution and version possibly?

`{
  ["distribution"]=>
  string(10) "opensearch"
  ["number"]=>
  string(5) "1.2.1"
  ["build_type"]=>
  string(3) "tar"
  ["build_hash"]=>
  string(40) "e3a44fa71b290fb265a94ef4297f044b9a63a762"
  ["build_date"]=>
  string(27) "2021-12-11T04:22:52.398139Z"
  ["build_snapshot"]=>
  bool(false)
  ["lucene_version"]=>
  string(6) "8.10.1"
  ["minimum_wire_compatibility_version"]=>
  string(5) "6.8.0"
  ["minimum_index_compatibility_version"]=>
  string(11) "6.0.0-beta1"
}`

**Comment by romainruaud** [comment]
can you check it and propose a PR for this one ?

**Comment by chris-brabender** [comment]
Yeah I can give it a look. Will get back to you in the next couple of days.

**Comment by romainruaud** [comment]
good catch, this one should be easy to fix, let me know

**Comment by mgeoffray-wide** [comment]
Thank you for the fix!   
It seems that the use is missing for this line: https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Plugin/Deprecation/Index/MappingPlugin.php#L60  

I cannot make a PR right now if someone wants to do it

**Comment by kpitn** [comment]
Hi, i just find another problem : 

Deprecated Functionality: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in XXXX/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/CustomerDataTrackingManager.php on line 55

There is not test to check if dob exist or not : 
```
    $customer = $this->customerSession->getCustomer();
    $shippingAddress = $customer->getDefaultShippingAddress();

    $dob = new DateTime($customer->getDob());
    $now = new DateTime();
```
