### ISSUE TITLE
Problem with button "Use Category Name in product search"

### ISSUE THREAD

**Issue by mnowakCode** [Smile-SA/elasticsuite#2501]
### Preconditions
I use PHP7.4, ElasticSearch v.7.16. 

Magento Version :
Magento 2.3.7-p1 CE
Magento 2.4.3-p1 EE

ElasticSuite Version :
Magento 2.3.7-p1 CE: 2.9.7
Magento 2.4.3-p1 EE: ~2.10.0

Environment :
Production mode/Developer mode

Third party modules :
Magento 2.3.7-p1 CE: yes, a few, but I can't write what these modules are
Magento 2.4.3-p1 EE: Ves_MegaMenu

### Steps to reproduce
1. I have over a dozen categories. I wanted to exclude one category from the search, so I used the button Use Category Name in the product search. 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/78545108/161228143-9e9862f8-e43f-4fce-812f-cd7af1baed8f.png">
2. After disabling it, I reindexed all indexes and went to the main page.

### Expected result
1. This category is not showing up in the search

### Actual result
1. I can see this category when searching
<img width="272" alt="image" src="https://user-images.githubusercontent.com/78545108/161228434-ce2e6a11-b9bc-40db-a2c2-0f46ba30999b.png">

The problem appeared in our main store. When a customer wanted to exclude one of the categories from the search. After turning it off, it still showed up after entering the name. I checked it on the development environment and the effect was the same.
I decided to install the latest Magento and use your module. After installation, the effect was the same.

**Comment by romainruaud** [comment]
Hi @mnowakCode 

with details it's now more clear.

The "use category name in product search" **does not affect the apperance of a category in the autocomplete**.

It's used to determine if the category name **is indexed in product content**.

Eg if you set it to "Yes" for the "Bottom" category, if you search for "bottom", you will see products belonging to the "bottom" category.

We should probably add another parameter that allows to make this category appear in the autocomplete results or not.

**Comment by mnowakCode** [comment]
@romainruaud Thank you for your answer. Yes, this function would be useful

**Comment by mnowakCode** [comment]
Hello @romainruaud, I saw you add a new function to the category editor "Display Category in Autocomplete". I thought that this function does what I mean in this ticket, but when I tested this function it doesn't work. 
What does this function do?

**Comment by romainruaud** [comment]
That's supposed to be what you meant in this ticket. You have to do a full reindex of "categories fulltext" index after upgrading the module, and that should be ok. If that's not the case, please open a new issue describing your problem.

Regards
