### ISSUE TITLE
this.element.find(...).slider is not a function with Magento 2.4.4

### ISSUE THREAD

**Issue by nwiegers01** [Smile-SA/elasticsuite#2502]
After upgrading Magento to version 2.4.4, I came to the conclusion that my price-slider is not working anymore. After I open the console, I can see the following warning: **_this.element.find(...).slider_**.
Currently this is breaking my slider filters, so this should be fixed before the official Magento 2.4.4 release.

### Preconditions
Magento Version : 2.4.4

ElasticSuite Version : 2.11.x-dev

Environment : Development

Third party modules :

### Steps to reproduce
1. Upgrade your project to Magento 2.4.4 ( Currently only available as Pre-Release ).
2. Go to any PLP ( Product Listing Page ).
3. The price slider is now broken and there is an error displayed in your console.

### Expected result
1. The price slider is working.

### Actual result
1. The price slider is broken and throws an error.

![2022-04-01_13-15](https://user-images.githubusercontent.com/92866914/161253019-c378297d-23b2-4c6b-ae4d-7d4a8ff8a2a9.png)
![2022-04-01_13-15_1](https://user-images.githubusercontent.com/92866914/161253025-7ee986a2-6764-433b-84c7-055391ef44ca.png)

**Comment by romainruaud** [comment]
This will be part of the compatibility fixes for Magento 2.4.4

Regards

**Comment by nwiegers01** [comment]
Hi @romainruaud ,

Great! Thank you for your reply. Do you know when the new version of Elasticsuite will be released?

**Comment by romainruaud** [comment]
@vahonc for this one maybe just re-adding the jquery Slider library as part of our module would be enough.

But I'm not sure we'll be able to add jqueryUI.slider on v1.11 if the main jQuery library is 1.13

**Comment by vahonc** [comment]
For this one, I already have a possible fix.

Just replacing in [src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js](https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js)

```
define([
    'jquery',
    'Magento_Catalog/js/price-utils',
    'mage/template',
    'jquery-ui-modules/slider',
    'Magento_Ui/js/modal/modal',
    'Smile_ElasticsuiteCatalog/js/jquery.ui.touch-punch.min'
], function ($, priceUtil, mageTemplate) {
```
by this
```
define([
    'jquery',
    'Magento_Catalog/js/price-utils',
    'mage/template',
    'jquery/ui',
    'jquery/ui-modules/widgets/slider',
    'Magento_Ui/js/modal/modal',
    'Smile_ElasticsuiteCatalog/js/jquery.ui.touch-punch.min'
], function ($, priceUtil, mageTemplate) {
```
With this, the price slider is working again but it could affect on BC.

**Comment by romainruaud** [comment]
okay, that's a good start, but you are right, maybe on lower versions of Magento "'jquery/ui-modules/widgets/slider'" is not there.

Maybe re-defining it on our module would allow to fix the fact that the same file is at two different locations across different Magento versions.
