### ISSUE TITLE
Facing error on reindexing after installation

### ISSUE THREAD

**Issue by asmitarane** [Smile-SA/elasticsuite#2506]
I have installed Smile Sa Elasticsuite extension. But I am facing the below error.

Please provide the solution for the same.

Catalog Search index process error during indexation process
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_catalog_product_testindices/acDKK2pQQseoc5nuMgylpw] already exists","index_uuid":"acDKK2pQQseoc5nuMgylpw","index":"test_default_catalog_product_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_catalog_product_testindices/acDKK2pQQseoc5nuMgylpw] already exists","index_uuid":"acDKK2pQQseoc5nuMgylpw","index":"test_default_catalog_product_testindices"},"status":400}

ElasticSuite Category Indexing index process error during indexation process:
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_catalog_category_testindices/pmM0SRzxTwC0fQWk-AClbg] already exists","index_uuid":"pmM0SRzxTwC0fQWk-AClbg","index":"test_default_catalog_category_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_catalog_category_testindices/pmM0SRzxTwC0fQWk-AClbg] already exists","index_uuid":"pmM0SRzxTwC0fQWk-AClbg","index":"test_default_catalog_category_testindices"},"status":400}

ElasticSuite Thesaurus Indexing index process error during indexation process:
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_thesaurus_testindices/5X1Btf4iTDi4wqvQ_r2TUw] already exists","index_uuid":"5X1Btf4iTDi4wqvQ_r2TUw","index":"test_default_thesaurus_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_thesaurus_testindices/5X1Btf4iTDi4wqvQ_r2TUw] already exists","index_uuid":"5X1Btf4iTDi4wqvQ_r2TUw","index":"test_default_thesaurus_testindices"},"status":400}

**Comment by romainruaud** [comment]
Hi @asmitarane 

if you want us to answer, please provide the required details when creating an issue. Otherwise we are not able to help you.

I close this issue, please create a new one and fill all the details. 

Regards.
