### ISSUE TITLE
Facing error on reindexing after installation Smile SA extension in magento 2 for search

### ISSUE THREAD

**Issue by asmitarane** [Smile-SA/elasticsuite#2507]
I have installed the extension Smile SA extension for Magento 2 search. After installation, I am trying to do reindexing but I am facing the below error.

Catalog Search index process error during indexation process
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_catalog_product_testindices/acDKK2pQQseoc5nuMgylpw] already exists","index_uuid":"acDKK2pQQseoc5nuMgylpw","index":"test_default_catalog_product_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_catalog_product_testindices/acDKK2pQQseoc5nuMgylpw] already exists","index_uuid":"acDKK2pQQseoc5nuMgylpw","index":"test_default_catalog_product_testindices"},"status":400}

ElasticSuite Category Indexing index process error during indexation process:
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_catalog_category_testindices/pmM0SRzxTwC0fQWk-AClbg] already exists","index_uuid":"pmM0SRzxTwC0fQWk-AClbg","index":"test_default_catalog_category_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_catalog_category_testindices/pmM0SRzxTwC0fQWk-AClbg] already exists","index_uuid":"pmM0SRzxTwC0fQWk-AClbg","index":"test_default_catalog_category_testindices"},"status":400}

ElasticSuite Thesaurus Indexing index process error during indexation process:
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [test_default_thesaurus_testindices/5X1Btf4iTDi4wqvQ_r2TUw] already exists","index_uuid":"5X1Btf4iTDi4wqvQ_r2TUw","index":"test_default_thesaurus_testindices"}],"type":"resource_already_exists_exception","reason":"index [test_default_thesaurus_testindices/5X1Btf4iTDi4wqvQ_r2TUw] already exists","index_uuid":"5X1Btf4iTDi4wqvQ_r2TUw","index":"test_default_thesaurus_testindices"},"status":400}

**Comment by romainruaud** [comment]
@asmitarane 

Please, make an effort, there is a template that you have to fill when creating an issue : 



### Preconditions



Magento Version :


ElasticSuite Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]

**Comment by asmitarane** [comment]
Please, make an effort, there is a template that you have to fill when creating an issue :

Preconditions
Magento Version: 2.4.3

ElasticSuite Version: 2.10.1

Environment : PHP 7.3 and MySQL

Third-party modules : Smile SA

Steps to reproduce
Expected result: list of products with images
Actual result: 
![image](https://user-images.githubusercontent.com/6649437/161939320-8418bc92-e78e-43d7-80fa-df5cd292aa3b.png)

**Comment by romainruaud** [comment]
@asmitarane 

how many websites and store view are enabled on your environment ? And how much products do you have ?

Regards
