### ISSUE TITLE
IE / Edge compatibility down

### ISSUE THREAD

**Issue by TdAmi** [Smile-SA/elasticsuite#2508]
Since ElasticSuite 2.10.9, IE and lowest versions of Edge doesn't work anymore because of defining "const" in "for" iteration (https://kangax.github.io/compat-table/es6/).
See this commit : https://github.com/Smile-SA/elasticsuite/commit/edf49391a2dd32f29914e43126b5fc472fd7d6b9

### Preconditions
Elasticsuite version 2.10.9.1
IE <= 11 / Edge < 14

Magento Version : 2.4.2

ElasticSuite Version : 2.10.9 / 2.10.9.1

Environment : Production

Third party modules : No

### Steps to reproduce
1. Navigate with IE or Edge < 14
2. See a blank page

### Expected result
1. Working website

### Actual result
1. White page with console error "SCRIPT1053: Const must be initialized"

**Comment by TdAmi** [comment]
Ok, thank you !
Of course Magento doesn't officialy support IE, but our website currently run on IE using Magento 2.4.2 and ElasticSuite 2.10.6.

**Comment by romainruaud** [comment]
Hi, we'll not implement this.

Regards
