### ISSUE TITLE
Virtual category "Category" rule not working

### ISSUE THREAD

**Issue by rensieeee** [Smile-SA/elasticsuite#2509]
When creating a virtual category, the rule "Category is one of" (or "is not one of") doesn't have a correct impact on the displayed products. Many products are included, not only the ones in the mentioned categories.

### Preconditions

Root category: Not virtual
Category A: Virtual category. Virtual root: Root category. Category rule: all products with "Category is one of A"
Product 1: Show in Category A
Product 2: Show in Category B

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.9.1

Environment: Production

Third party modules: -

### Steps to reproduce

1. Organise the products and categories as shown in the preconditions
2. Reindex the elastic server
3. View the category page of Category A

### Expected result

1. Only product 1 should be displayed

### Actual result

1. Both product 1 and product 2 are displayed

I'm working on debugging it as well, but I'm hoping you could help me with this. I also have another pull request ready to create for another issue.

**Comment by romainruaud** [comment]
Hi, this is a bit blurry for me. It seems to be 3 categories involved in your process : 

- Category A is your virtual category : where is it on the tree ? does it have childrens ?
- your virtual rule for this category is "Category is one of A" : is this another category or the category is targeting herself ???
- Category B : where is it on the tree, and what is his relationship with A ? does it have childrens ?

Regards

**Comment by rensieeee** [comment]
Hi @romainruaud,

- Category A and B are both direct children of the Root category. 
- The category is targeting herself in this instance (although this is not necessary, you can opt to target another category)
- Category B does not have a relation with category A. Both category A and B do not have children.

We've come up with a solution to mimic the categories in a separate product attribute. This way we can use the multiselect filter instead of the category filter. This does work as a workaround.

**Comment by romainruaud** [comment]
A category targeting herself will likely not work, so the resulting condition will be nothing, and only the root category will be taken into account. So what you describe seems to be normal.
