### ISSUE TITLE
Configurable Products not showing all available configurations 

### ISSUE THREAD

**Issue by harrigo** [Smile-SA/elasticsuite#2511]
With some of my configurable products underlying configurations are not available when they should be after updating to Magento 2.4.3-p2. Some configurations do show however not entirely sure on the pattern yet. Have noticed that adding a quantity on one occasion to an underlying simple product even though manage stock is set to no. Removing this module seems to fix the issue and all underlying configurations show.

I have not been able to provide exact reproduction steps at this point in time however am hoping I may be able to get a nudge in the right direction for what may be causing this behaviour, I will continue to try and trace at which point this goes wrong but have little to go on, there are no errors in logs, no console errors on page and no reason but the fact it works without this module.

### Preconditions
Magento Version : Magento CE 2.4.3-p2

ElasticSuite Version :~2.10.0

Environment : Developer

Third party modules :
	"magefan/module-blog": "^2.10",
        "ebizmarts/sagepaysuite": "^1.4",
        "magento/quality-patches": "^1.0",
        "amzn/amazon-pay-magento-2-module": "5.*",
        "wyomind/simplegoogleshopping": "^14.6",
        "mageplaza/module-abandoned-cart-email": "^4.2",
        "mageplaza/module-smtp": "^4.7",
        "swissup/module-marketplace": "^1.9",
        "swissup/firecheckout": "^1.28",
        "veriteworks/cookiefix": "^3.0",
        "amasty/base": "^1.13",
        "amasty/pgrid": "^1.10",
        "nordcomputer/showoutofstockprice": "^0.6.0"

### Steps to reproduce

Not entirely sure how to do provide these yet however will continue to look into the issue to provide exact steps.
1. Create a configurable product
2. Create underlying child configurations 
3. Navigate to product on frontend
4. Choose from available configurations

### Expected result

1. All underlying configurations show on the configurable product.

### Actual result

1. Not all configurations are available.

**Comment by romainruaud** [comment]
Hi @harrigo 

Do you have some frontend screenshots on the page zone that are not displaying child configurations ?

Elasticsuite is not involved on displaying child configurations, neither on listing page, nor on product detail page, that's why I'm doubtful of the impact of Elasticsuite here.

Regards

**Comment by harrigo** [comment]
Hello Romain, 

Hmm interesting, thanks for the quick response, close this I may be a little premature in posting here before investigating further.

This is the bit but It must be something else, I will keep investigating!

![image](https://user-images.githubusercontent.com/28608191/162172232-85fb494c-2119-4b44-a94e-8b5d47b70a11.png)

Thanks

**Comment by harrigo** [comment]
> Well this one is clearly not related to Elasticsuite :/

No worries thanks for letting me know! SORRY about that!
