### ISSUE TITLE
Correct result found in autocomplete but not in normal catalog search

### ISSUE THREAD

**Issue by WebWeave** [Smile-SA/elasticsuite#2513]
When creating a searchable product attribute it is not finding results in the catalog search but it is finding the correct result in the autocomplete.
### Preconditions

Magento Version : 2.3.5-p1

ElasticSuite Version : 2.9.3

Environment : Production

Third party modules :
        "honl/magento2-nl-nl": "^1.1",
        "dealer4dealer/xcore-magento2": "^2.0",
        "cweagans/composer-patches": "^1.6",
        "mageplaza/module-core": "^1.4",
        "mailchimp/mc-magento2": "^102.3",
        "smile/elasticsuite": "2.9.3",
        "picqer/exact-php-client": "^3.32",
        "mageplaza/module-ajax-layered-navigation": "^1.0",
        "mageplaza/magento-2-french-language-pack": "dev-master",
        "avada/module-proofo": "^1.0",
        "mageplaza/magento-2-german-language-pack": "dev-master",
        "amasty/module-customer-login": "^1.1",
        "amasty/module-store-locator": "^2.4",
        "kiwicommerce/module-cron-scheduler": "^1.0",
        "guzzlehttp/psr7": "1.7.0",
        "symfony/lock": "5.4.2"

### Steps to reproduce

1. Create a new product attribute that has the scope global, is a text field and is searchable
2. Fill in the product attribute in a product with the value 450012200
3. Search the product

### Expected result

1. Find the product, like it finds the product in the autocomplete :-).

### Actual result

2. We are getting a error that nothing could be found.

**Comment by rensieeee** [comment]
Hi @WebWeave,

We're having the same problem, but with partial search terms: the autocomplete query autocompletes the search terms before sending the query, while the non-autocomplete query does not. I think this is the cause of the issue, since we do get correct results on the results page when filling in the complete search terms.

I'm trying to figure out where to trigger the autcompletion of search terms before adding it in the search query.

**Comment by rensieeee** [comment]
Hi @WebWeave,

I've found a fix. I've tested in on Magento 2.4.3-p1, let me know if it works for you as well. I've created a Pull Request here to have it implemented in the module: [https://github.com/Smile-SA/elasticsuite/pull/2519](https://github.com/Smile-SA/elasticsuite/pull/2519)

In the meantime, you can apply the following patch to get the same result (applicable in the latest official release): [https://patches.experius.nl/patches/experius/fixes_integration_token_activate_for_get_requests_2.4.2_CE_COMPOSER.patch](https://patches.experius.nl/patches/experius/fixes_integration_token_activate_for_get_requests_2.4.2_CE_COMPOSER.patch)
