### ISSUE TITLE
search result not selected

### ISSUE THREAD

**Issue by amrit0209** [Smile-SA/elasticsuite#2530]
i have install the elasticsuite extension magento2. Search result not selected and not open the result

**Comment by vahonc** [comment]
@amrit0209,

Please, make an effort, there is a template that you have to fill when creating an issue : 



### Preconditions



Magento Version :


ElasticSuite Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]
