### ISSUE TITLE
Backward incompatible changes in patch update 2.10.9.1 to 2.10.10!!

### ISSUE THREAD

**Issue by Stepa4man** [Smile-SA/elasticsuite#2535]
Update from 2.10.9.1 to 2.10.10 caused BC break here: 
https://github.com/Smile-SA/elasticsuite/blob/635635a21ce73ccafccc129799403c1976794346/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php#L52

Details:
PHP Fatal error:  Access level to **_ProjectName\ElasticsuiteCatalog\Model\Layer\Filter\Category::$childrenCategories_** must be protected (as in class **_Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category_**) or weaker in _**app/code/ProjectName/ElasticsuiteCatalog/Model/Layer/Filter/Category.php**_ on line 167

**Comment by romainruaud** [comment]
Hi @Stepa4man 

We always try to be backward-compatible between versions, unfortunately we couldn't make this differently for this property due to the virtual categories subtree feature we introduced in 2.10.10.

However, this should be pretty straightforward to fix in your project code.

Regards

**Comment by Stepa4man** [comment]
Hi @romainruaud 
First of all my kudos for such a cool module. in fact, we use it in every project.

Regards to this issue.
there is definitely another backward-compatible way to solve such a problem. Of course, if you are motivated to keep backward compatibility. Running composer update nowadays is such a pain.

**Comment by romainruaud** [comment]
Hi @Stepa4man , can you propose a more better way to deal with this BC ?

Regards

**Comment by Stepa4man** [comment]
@romainruaud Depending on why did you actually change it from private to protected. I assume to be able to use it in a child class. If so I would recommend just adding the new property in a child class by injecting it through the constructor. And mark it as deprecated. After that, you can add a TODO comment to the class header which will remind me to make your changes when you do a major update of the module instead of a patch. 
If you changed for another reason, then just let me know, maybe I'll be able to recommend something else.

**Comment by romainruaud** [comment]
I close since 2.10.10 is out since april, so we'll not fix this.

Thank you for submitting this however, we'll try to be more conscious about BC on next releases.

Regards
