### ISSUE TITLE
Synonyms don't work on partial matches

### ISSUE THREAD

**Issue by Hexmage** [Smile-SA/elasticsuite#2538]
### Preconditions

Magento Version : 2.4.2 

ElasticSuite Version : 2.10.9.1

Environment : Production

### Steps to reproduce

1. Create a synonym for Blue to Bleu
2. Search for Bleu 
3. Search for Bleu Pants

### Expected result

1. First search returns all blue products
2. Second search returns all blue pants products.

### Actual result

1. First search returns all blue products
2. Second search does **not** return all blue pants products

**Comment by romainruaud** [comment]
Fixed by #2554 that will be part of next minor release.

Regards
