### ISSUE TITLE
Problem with layered navigation when using bucket price.price and offer.price

### ISSUE THREAD

**Issue by romainitofo** [Smile-SA/elasticsuite#2540]
https://github.com/Smile-SA/elasticsuite/blob/635635a21ce73ccafccc129799403c1976794346/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Response/AggregationFactory.php#L83

With the histogram aggregation, for the buckets price.price and offer.price the result of the last price is down rounded.
In example if the last result of one these buckets is 25,78  we will get 25.
And as we use this result for the layered navigation filter with the prices, we can  have this situation:
for example: 3 articles: 2€, 3,5€ and 4,67€.
our price filter with display from 2€ to 4€.

But we should have from 2€ to 5€.

If it's not clear do not hesitate to contact me.

Thanks.

**Comment by vahonc** [comment]
Hello @romainitofo,

Firstly, we need more details about your environment, like versions of Magento and ES, installed third-party modules. As I understand your environment is a little bit more specific than fresh Magento with default sample data.

As for getting `max_price` and preventing it from rounding down, we use a little trick. You can take inspiration from this [peace of code](https://github.com/Smile-SA/elasticsuite/blob/635635a21ce73ccafccc129799403c1976794346/src/module-elasticsuite-catalog/Block/Navigation/Renderer/PriceSlider.php#L92-L102).

I'm assuming you're using some custom theme on the fronted, I mean not the default Luma theme?

Are you using some headless / PWA approach or GraphQL requests for building layered navigation filter with the prices?

BR,
Vadym
