### ISSUE TITLE
Product sort by position, set by API

### ISSUE THREAD

**Issue by LaurensGoedel** [Smile-SA/elasticsuite#2546]
Magento 2.3.5-p1
ElasticSuite 2.9.0

We feed the webshop via the Rest API and set the product sort per category.  
After the synchronisation is done, i check in the database to see if the position is correctly, and it is.

However, when i check on the shop (frontend and backend) the ordering deviates. 

Maybe i overlook some settings, but i can't find any setting to manipulate this. I have tried manual sorting and automatic sorting. Buth both have the same result.

Anyone got a suggestion where to look?

**Comment by romainruaud** [comment]
Hi @LaurensGoedel 

could it be a duplicate of #1977 ?

**Comment by LaurensGoedel** [comment]
@romainruaud I'm sorry, you are correct! I thought i searched all the issues, but apparently i missed this one.
