### ISSUE TITLE
broken php 7.3 compatibility

### ISSUE THREAD

**Issue by misthero** [Smile-SA/elasticsuite#2547]
the file src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/SpecialAttribute/ProductType.php added recently broke php 7.3 compatibility

https://github.com/Smile-SA/elasticsuite/issues/2494, https://github.com/Smile-SA/elasticsuite/issues/2466

this file has been introduced withoud changing elasticsuite version or it's php requirements

this files uses [typed properties](https://wiki.php.net/rfc/typed_properties_v2) introduced in php 7.4

php 7.3 gives error _syntax error, unexpected 'QueryFactory' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)_

### Preconditions
magento 2.4.x php 7.3.x

Magento Version : CE

ElasticSuite Version : 2.10.10

Environment : Developer

### Steps to reproduce

1. composer require smile/elasticsuite
2. bin/magento setup:di:compile
3.

### Expected result
1. compilation should go to the end

### Actual result
1. syntax error, unexpected 'QueryFactory' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by romainruaud** [comment]
Hi @misthero 

We will merge the PR from Vadym but according to this page, you should not be using PHP 7.3 if you are using Magento > 2.4.0 : 

https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

And for Magento 2.4.0 the only available version of Elasticsuite is 2.10.1 as per stated in the README.

I think you are messing up with the versions of PHP/Magento/Elasticsuite you are working with.

Regards

**Comment by misthero** [comment]
> Hi @misthero
> 
> We will merge the PR from Vadym but according to this page, you should not be using PHP 7.3 if you are using Magento > 2.4.0 :
> 
> https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html
> 
> And for Magento 2.4.0 the only available version of Elasticsuite is 2.10.1 as per stated in the README.

Hello @romainruaud thank you for your answer.

The magento page you linked states that magento 2.4.0 supports php 7.3, 7.4. 

In magento 2.4.3 composer.json you can see:

`    "require": {
        "php": "~7.3.0||~7.4.0",
`
https://github.com/magento/magento2/blob/2.4.3/composer.json

I mistyped the Elasticsuite versione being the 2.10.1 the correct one we have.

We use composer to install and update packages, usually if a package require a specific PHP it is listed in it's composer.json, both magento and ElasticSuite installed flawlessly.

I agree with you anyway, we should upgrade PHP but sadly, that's not my decision...

Thank you for merging the pull request.

**Comment by dpobel** [comment]
Hi,

it would be nice to have 2.10.11 release with that fix, at the moment, installing the last 2.10 with 7.3 ends up with a broken Magento while this is fixed in the branch.

Thanks

**Comment by romainruaud** [comment]
Hi @dpobel 

We will release a 2.10.11 containing this fix, probably around the end of this month or beginning of next month.

In the meantime, you can use the 2.10.x branch when installing.

regards
