### ISSUE TITLE
Explain results: Words with accents not bold when matching

### ISSUE THREAD

**Issue by trfloSmile** [Smile-SA/elasticsuite#2548]
**In back office "explain results" section, I search for the term "Clé". In the results, "clé" is not bold but "cle" is.**

- Magento EE 2.4.2-p1
- "smile/elasticsuite: 2.10.7

```
        "smile/elasticsuite-for-retailer": "~2.2.0",
        "smile/module-elasticsuite-behavioral-autocomplete": "^2.10",
        "smile/module-elasticsuite-behavioral-optimizer": "^2.10",
        "smile/module-elasticsuite-catalog-optimizer-customer-segment": "^2.10",
        "smile/module-elasticsuite-explain": "^2.10",
        "smile/module-elasticsuite-facet-recommender": "^2.10",
        "smile/module-elasticsuite-instant-search": "^2.10",
        "smile/module-elasticsuite-virtual-attribute": "^2.10",
```

Environment : Developper & Production

### Steps to reproduce
1. Create products with "clé" in the name and others with "cle"
2. Go to Back office explain results
3. Search "Clé"
4. Click on a product and go to indexed content

### Expected result
1. "clé" and "cle" should be bold

### Actual result
1. "cle" is bold but not "clé"
![image](https://user-images.githubusercontent.com/102654190/165905190-3ec311d2-2acc-4821-9574-48f546727191.png)

**Comment by romainruaud** [comment]
Fixed in the 2.10.11 release of the explain module.

Regards
