### ISSUE TITLE
Widget Products page builder not works correctly

### ISSUE THREAD

**Issue by brmor-mistermenuiserie** [Smile-SA/elasticsuite#2551]
### Preconditions
Magento 2.4.1-p1
ElasticSuite Version : 2.10.9.1
Environment : Production

### Steps to reproduce

1. create a block cms page with Page builder Content and Products Element
2. select Product By Categories
3. save your cms Block
4. Call this block CMS on category page (Display Mode : Static Block Only)

### Expected result

1. We need to see selected product on Frontend

### Actual result

1. Any Products are visible on frontend.

Other condition (by sku for example) works correctly
We have any errors on elastic logs

**Comment by vahonc** [comment]
Hello @brmor-mistermenuiserie,

I was not able to reproduce this issue according to your preconditions on my test environment (fresh Magento EE 2.4.1-p1 with default sample data and ES 2.10.9.1)

Here are my steps:

1. Create a block with Page builder Content and Products Element
![Screenshot from 2022-05-06 18-25-24](https://user-images.githubusercontent.com/67791361/167164912-a3b00cf9-2299-4f02-a2ea-a9a0b5bcb57e.png)

2. Select Product By Categories

![Screenshot from 2022-05-06 18-24-49](https://user-images.githubusercontent.com/67791361/167164758-6fd1dcb6-6aed-4d69-9c5e-9e4716aa6f1b.png)

3. Call this block on category page (Display Mode : Static Block Only)
![Screenshot from 2022-05-06 18-25-54](https://user-images.githubusercontent.com/67791361/167165157-8ed22287-d342-4ee1-b5b4-21531fc5a67e.png)

After that, when I browsed my test category (Cat A) on the frontend, I saw only products from the selected category in my Test Block from Step 1.
![Screenshot from 2022-05-06 18-26-30](https://user-images.githubusercontent.com/67791361/167165606-57c280d3-c3df-44de-b62f-eb81c66c2482.png)

It seems that something is wrong with your configuration or environment. 
Therefore, please provide more details with screenshots about your block.

BR,
Vadym
