### ISSUE TITLE
Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/ClientConfiguration.php on line 54

### ISSUE THREAD

**Issue by mrrobotisback** [Smile-SA/elasticsuite#2556]
### Preconditions

Ubuntu 20.4
Php 8.1.5

Magento Version : 2.4.4

ElasticSuite Version : 2.10..10

Environment :developer

Third party modules : 

### Steps to reproduce

1. install frash magento 2.4.4
2. install fresh elastcsuite 2.10.10
3. run bin/magento setup:upgrade

### Expected result

1. setup:upgrade finish

### Actual result

1. setup:upgrade stop with this error: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/ClientConfiguration.php on line 54

**Comment by romainruaud** [comment]
Hi @mrrobotisback 

Full install is tested on Github actions and does not fail : 

https://github.com/Smile-SA/elasticsuite/runs/6307574732?check_suite_focus=true

Can you give us more details about your install commands ? And maybe the content of your app/etc/env.php file ?

Regards

**Comment by cmuench** [comment]
@romainruaud 
We have the same issue in our Gitlab CI. I think I was able to figure that out.
If `setup:install` is started with explicit set `.-elasticsearch-host` and `--elasticsearch-port` option (like in your Github action) then there is no issue.
If the options are not not set and Magento uses the defaults, then we have this issue.

**Comment by romainruaud** [comment]
@vahonc can you try to add some checks here ? 

https://github.com/Smile-SA/elasticsuite/blob/e6ac45c2112ec0a99b2373c85b1be97ad9b62bbc/src/module-elasticsuite-core/Client/ClientConfiguration.php#L54

Maybe something like (untested) : 

```php
    public function getServerList()
    {
        return $this->getElasticsearchClientConfigParam('servers') ? explode(',', $this->getElasticsearchClientConfigParam('servers')) : null ;
    }
```
