### ISSUE TITLE
Unable to fetch customattribute, it is a textarea at the category page

### ISSUE THREAD

**Issue by IbrahimS2** [Smile-SA/elasticsuite#2562]
Unable to fetch customattribute, it is a textarea at the category page, I have created a textarea attribute i.e "TEXTAREA" and I want to the items at the category page to return either 1 or 0 if it has a value, anyhow when using ElasticSuite it does not return anything but NULL, the moment we disabled ElasticSuite it worked as expected with the built-in integration with ES7

The code I am using to call this textarea attribute is:
` $_product->getCustomAttribute('textarea_attribute')`

Any clue why?

**Comment by vahonc** [comment]
Hello @IbrahimS2 

We need more details about your issue and environment.

Please, make an effort, there is a template that you have to fill when creating an issue : 



### Preconditions



Magento Version :


ElasticSuite Version :


Environment :


Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1.

### Actual result

1. [Screenshot, logs]



BR,
Vadym

**Comment by IbrahimS2** [comment]
@vahonc 

**Preconditions**
======================================
Magento Version : **2.4.3-p1**
ElasticSuite Version : **2.10.9.1**
Environment : **Nginx 1.20, PHP7.4, ElasticSearch 7.10.2**
Third party modules : **NA**

**Steps to reproduce**
======================================

- Create a Custom Product textarea attribute
- Assign it to the default attribute set and define a value
- Open the category and from template files inject this code ` $_product->getCustomAttribute('textarea_attribute')->getValue()` and try to fetch the textarea attribute
 
**Expected result**
======================================
I get the value that is defined/assigned to the textarea attribute

**Actual result**
======================================
I get null

**Comment by romainruaud** [comment]
Hi @IbrahimS2 

Elasticsuite is not responsible for loading product data in listing pages, since it only return matching product ids : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L517

Products are fetched by their entity_ids according to the engine response.

I don't know how is made your product collection, but you might probably need to add ```addAttributeToSelect('textarea_attribute')``` when building it.

Regards
