### ISSUE TITLE
Error when first index catalogsearch_fulltext

### ISSUE THREAD

**Issue by anethum** [Smile-SA/elasticsuite#257]
Hello,

I have the same failure as mentoined in #182 

put with following attributes like option_text_diameter or option_text_typ

The following Versions are used:
smile/elasticsuite 2.2.5
magento 2.1.1

**Comment by romainruaud** [comment]
Hello @anethum , and thank you for trying our module.

It seems that your attributes "diameter" and "typ" are misconfigured. Can you post a screenshot of how they are configured in the back office ?

Best regards,

**Comment by anethum** [comment]
Hello @romainruaud ,

after complete fresh installation and migration from 1.9 I get the same failure.

Please find the attached screens. 
[typ _ Product Attributes _ Attributes _ Stores _ Magento_1.pdf](https://github.com/Smile-SA/elasticsuite/files/664394/typ._.Product.Attributes._.Attributes._.Stores._.Magento_1.pdf)
[typ _ Product Attributes _ Attributes _ Stores _ Magento_2.pdf](https://github.com/Smile-SA/elasticsuite/files/664396/typ._.Product.Attributes._.Attributes._.Stores._.Magento_2.pdf)
[typ _ Product Attributes _ Attributes _ Stores _ Magento_3.pdf](https://github.com/Smile-SA/elasticsuite/files/664395/typ._.Product.Attributes._.Attributes._.Stores._.Magento_3.pdf)
![2016-12-20 18_49_03](https://cloud.githubusercontent.com/assets/1729737/21361624/0cbc24c4-c6e5-11e6-9b5b-85556d3eb27c.png)

**Comment by afoucret** [comment]
The reason of the bug is that your attribute is not used in search but used for sort by.

The configuration should not allow such a combination or the mapping generation should be more secure regarding it. 

We will release a patch in the early of January (2.3.0 release). You can make the attributes searchable waiting for this patch to be released as a workaround.

**Comment by anethum** [comment]
@afoucret thank you!

yeah that was the reason!

**Comment by afoucret** [comment]
@romainruaud  : See PR #277 and test it carefully.

**Comment by afoucret** [comment]
The patch is present on the 2.3.x branch and will be part of the next stable release 2.3.0.
You can test it now.

Thx for reporting.
