### ISSUE TITLE
Indexing Issues and Disk Space Floating related to indexes

### ISSUE THREAD

**Issue by FedericoAlessandroni** [Smile-SA/elasticsuite#2570]
### Preconditions

Magento Version : Magento Enterprise 2.4.3

ElasticSuite Version : 2.10.9.1

Environment : Production

Third party modules : MexBs, MageDelight, Wyomind, Monetate

### Steps to reproduce
1. Re-index
2. A lot of indexes are created 
3. A lot of disk space is consumed (38GB) 

### Expected result
1. All indexes should be created correctly AND IN CORRECT NUMBER

### Actual result
Magento has reviewed disk usage and found that the Elasticsuite is creating too many indexes.

```
55xmxnvctmh4m@i-04384d1b4e3019d60:~$ php bin/magento config:show catalog/search/engine
elasticsuite
 
```

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ curl http://localhost:9200/_cluster/health?pretty
{
...

  "active_primary_shards" : 165,
  "active_shards" : 489,
...
}
 
It was using 38GB at the time when checked by the team.

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ du -h --max-depth=1 /data/exports | sort -nr
124G    /data/exports
82G     /data/exports/shared
38G     /data/exports/elasticsearch
....
 
The indexes were reset and reindexed.

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ php bin/magento indexer:reset
Design Config Grid indexer has been invalidated.
Customer Grid indexer has been invalidated.
Category Products indexer has been invalidated.
Product Categories indexer has been invalidated.
Catalog Rule Product indexer has been invalidated.
Product EAV indexer has been invalidated.
Stock indexer has been invalidated.
Inventory indexer has been invalidated.
Catalog Product Rule indexer has been invalidated.
Product/Target Rule indexer has been invalidated.
Target Rule/Product indexer has been invalidated.
Product Price indexer has been invalidated.
Catalog Search indexer has been invalidated.
Sales Rule indexer has been invalidated.
Additional Promotion Action Product indexer has been invalidated.
Additional Promotion Action Product Rule indexer has been invalidated.
ElasticSuite Category Indexing indexer has been invalidated.
ElasticSuite Thesaurus Indexing indexer has been invalidated.

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ php bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:21
Category Products index has been rebuilt successfully in 00:01:37
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:02:01
Stock index has been rebuilt successfully in 00:00:07
Inventory index has been rebuilt successfully in 00:00:28
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product/Target Rule index has been rebuilt successfully in 00:00:54
Target Rule/Product index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:45
Catalog Search index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:01
Additional Promotion Action Product index has been rebuilt successfully in 00:00:00
Additional Promotion Action Product Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:14
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:06
 
Then disk usage was checked again:

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ du -h --max-depth=1 /data/exports | sort -nr
185M    /data/exports/elasticsearch
87G     /data/exports
82G     /data/exports/shared
....
 
 
 
When I checked a few hours ago, it was 13GB

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ du -sh /data/exports/elasticsearch/
13G /data/exports/elasticsearch/
 
And after a couple of hours later, 21GB, 8GB increase.

55xmxnvctmh4m@i-04384d1b4e3019d60:~$ du -sh /data/exports/elasticsearch/
21G /data/exports/elasticsearch/

**Comment by FedericoAlessandroni** [comment]
In addition to the already detailled information you provided, could you tell us the number

of active store views of your Magento installation: **18 storeviews**
a rough estimate of your products number per store view: **30k skus** 
a rough estimate of your number of categories: **230** 
a rough estimate of the number of thesaurus rules that you have: **0**
the number of Elasticsearch nodes on the cluster (but as you mentionned Magento, I guess you're using a Magento Cloud 3 nodes cluster as it is what they provide out of the box) **confirm**

**Comment by rbayet** [comment]
Thanks for the extra information @FedericoAlessandroni.

So basically, my recommendation would be to 
- set "Stores > Configuration > Elasticsuite > Base settings > Indices settings > Number of Shards per Index" to 1 : 30k skus, even with a lot of customer groups, should not generate a product index big enough to justify more than 1 shard, and this global configuration will also apply to the category index
- review the tracker related "Stores > Configuration > Elasticsuite > Tracking > Global Configuration > Retention Delay" setting to check the value in number of months
   - 12 is the default value
   - but if you already had Elasticsuite before version 2.10.7 it should be the previous value in days (default was 365) divided by 31
      - for instance "200" (days) should have become "7" (months)
 - before and/or after a full reindex, inspect the Indices dashboard to identify ghost or external indices that *could* be safely removed to free disk space/resources on your Elasticsearch cluster
 
Regards,
