### ISSUE TITLE
OpenSearch Compat

### ISSUE THREAD

**Issue by ssx** [Smile-SA/elasticsuite#2572]
Hi,

We currently use ES on a number of projects hosted via Magento Commerce cloud. They're clearly now favouring opensearch instead of elasticsearch.

How supported is this within ES? as far as I can tell Opensearch implement the same protocol as Elasticsearch so it should be a drop in replacement.

If it is compatible, may be worth adding something to the repo readme as I couldn't spot anything.

**Comment by romainruaud** [comment]
Yes, we are compatible with OpenSearch,

I'll try to emphasize more this point on the Readme.

regards

**Comment by romainruaud** [comment]
Added to the readme, I close

**Comment by ssx** [comment]
thanks @romainruaud :)

**Comment by richardechidna** [comment]
Hey @romainruaud 
I might be parking at the wrong tree, I couldn't see much info on OpenSearch Vs ElasticSuite in ReadMe other than the mention of it in 'Supported Elasticsearch Version' table.

If there is a detailed documentation could you point me to it?
