### ISSUE TITLE
error while s:up install

### ISSUE THREAD

**Issue by rimmeh** [Smile-SA/elasticsuite#2579]
### Preconditions

Magento Version : 2.4.2

ElasticSuite Version : 7.16.2

Environment : Dev

Third party modules :

### Steps to reproduce

1. composer require smile/elasticsuite ~2.10.0
2. s:up
3. {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}

### Expected result

1. no error while setup:upgrade

### Actual result

1. [Screenshot, logs]

**Comment by vahonc** [comment]
Hello @rimmeh,

Do you still have this error?

BR,
Vadym
