### ISSUE TITLE
Virtual categories functionality affects catalog search performance

### ISSUE THREAD

**Issue by abasanskii** [Smile-SA/elasticsuite#2581]
### Preconditions
Magento ver. 2.4.3-p1 EE
ElasticSuite Version : 2.10.9.1
Elastic Search Version: 7.10.2
Environment : Production

### Steps to reproduce
1. Setup several virtual categories.
1. Open storefront.
2. Run search.
3. Observe search performance.

### Expected result
Search speed should not be affected by Smile_ElasticsuiteVirtualCategory module actions.

### Actual result
Search speed is slow.
Analysis of the individual search request trace recorder in NewRelic shows that almost 3 sec of the entire request time of 4.8 sec were utilized by Smile_ElasticsuiteVirtualCategory module actions:
![image](https://user-images.githubusercontent.com/68284256/171372285-8daa5100-c4ac-45be-8fec-dff4d5a5fc58.png)

**Comment by cdcrothers** [comment]
I observed similar problems. Child virtual categories get their filters/conditions added to parent categories, which can compound problems for parent/root categories with lots of virtual children. I disabled inheritance of virtual categories via code change to fix this.

**Comment by romainruaud** [comment]
Hi @abasanskii 

how much virtual categories do you have ?
