### ISSUE TITLE
Search Result Page

### ISSUE THREAD

**Issue by rimmeh** [Smile-SA/elasticsuite#2583]
HI,

is there a way to categorize the search result page like the autocomplete?

The autocomplete have sections fpr "categories, terms, products, cms pages (cms search plugin)".

But on on the actual search result page i dont have those sections. Only products and cms pages from the cms search plugin.

How can i add categories and terms too? 

regards

rimmeh

**Comment by romainruaud** [comment]
I close since this has been answered.

regards
