### ISSUE TITLE
Version problem with composer installation

### ISSUE THREAD

**Issue by RomainCuzon** [Smile-SA/elasticsuite#2584]
When running "composer install", composer gets the wrong ElasticSuite version despite explicitly declaring the version in the composer.json.

### Preconditions

Magento Version : Magento Cloud 2.4.2 p2

ElasticSuite Version : ElasticSuite 2.10.6

Environment : production et staging

### Steps to reproduce
1. Declare ElasticSuite version 2.10.6 in composer.json
2. Execute composer install

### Expected result
1. the version in the composer.lock should be 2.10.6 and the reference should correspond to the commit sha of said version (4bc459e2e08e3f593d791f28903ff3a8bbbd6230)
2. ![2022-06-02 08_37_55-composer lock - comptoirdespros_ee  WSL _ Debian  - Visual Studio Code](https://user-images.githubusercontent.com/106688385/171568434-f57be999-32f8-47b8-9f3a-c8830f1db75a.png)

### Actual result
1. the version in the composer.lock is indeed 2.10.6 but the reference corresponds to the sha of the commit of 2.10.9.1 (e7b072306bbd2b1c7e70cf3ab40410afca8770b4)
2. 
![2022-06-02 08_42_19-● composer lock - comptoirdespros_ee  WSL _ Debian  - Visual Studio Code](https://user-images.githubusercontent.com/106688385/171569331-c49f6fe7-c9fa-4a85-b8f0-68458591dd8f.png)
3. The installed version is the wrong one, as shown by the appearance of menu items that do not exist on 2.10.6
4. 
![2022-06-02 08_46_17-Configuration _ Settings _ Stores _ Magento Admin](https://user-images.githubusercontent.com/106688385/171569688-765d9d7a-2700-4f1b-ba81-febd864c3556.png)

The problem was presented for the first time on Monday May 23 and it has since been reproduced on our Magento Cloud servers as well as on our development workstations.

**Comment by romainruaud** [comment]
Hi, this is strange, what do you have exactly in composer.json file ?

"~2.10.6" or "2.10.6" ? And in the .lock file prior installing, what do you have ? did you try to remove the lock file ?

Regards

**Comment by RomainCuzon** [comment]
Hi, 
we have been using version 2.10.6 for several months without any problems. And the latter happens randomly about one in four times.
Here is a copy of the composer.json
![2022-06-02 17_07_07-composer json - comptoirdespros_ee  WSL _ Debian  - Visual Studio Code](https://user-images.githubusercontent.com/106688385/171661361-ef5cf0ff-b1fe-484a-9bfe-1d796f5db2e4.png)

we have remove the lock file, and purge composer cache.
