### ISSUE TITLE
Search Relevance Need "OR" not AND

### ISSUE THREAD

**Issue by secaliskan** [Smile-SA/elasticsuite#2585]
Our client wnat make a phrase search for each word in phrase like below:
**yellow turtleneck short sleeve t-shirt**

And want search result:
All products with names consist of "yellow"
+ All products with names consist of "turtleneck"
+ All products with names consist of "short"
+ All products with names consist of "sleeve"
+ All products with names consist of "t-shirt"

They dont want exact phrase MATCH, but they want all words in phrase accumulate like "OR" search result.
Seacrh result --> yellow **OR** turtleneck **OR** short **OR** sleeve **OR** t-shirt

How we can do this. Many setting I made but I could not be successfull.

**Comment by vahonc** [comment]
Hello @secaliskan,

You can take some experience by reading our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/FulltextSearchEngineBasicConfiguration#fulltext-search-relevance-configuration) and trying to find the best value for the field `Fulltext base settings` -> `Minimum Should Match` that will satisfy your request. 

For example, you can set up this value like **50%** or **1** and check search results on your store. Please check the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html) for `Minimum Should Match` available values.

BR,
Vadym
