### ISSUE TITLE
Strange attribute behavior

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2589]
Hi guys,

Magento 2.4.4
ES 7.9.3
Smile Elasticsuite 2.10.10

I have a virtual category "News" with a custom rule "Is_product_new". I was wondering why I had some products that were there, since they are not new on that store.

The concerned product is a grouped product (ID: 179330) which as only one child (ID: 28392)

I checked the document 179330 on ES for store 7, and here is the strange data I saw (just after a reindex) : 

![Capture d’écran 2022-06-02 à 15 28 59](https://user-images.githubusercontent.com/1633463/171640334-bd4eb33d-acd8-4d15-adfb-2fe7c1a46242.png)

Here is the DB data : 
 
<img width="486" alt="Capture d’écran 2022-06-02 à 15 30 05" src="https://user-images.githubusercontent.com/1633463/171640545-049872c2-4a97-43c0-adfc-0b03b7aaae76.png">

93 : news_from_date
94: news_to_date

As you can see, news_from_date has a wrong value : It shows the default value instead of store 7 value which is NULL/empty

And even more strange, news_to_date has two wrong values : The default value of the grouped product AND the default value of the simple product.

Here are the attributes definition : 

```
INSERT INTO `eav_attribute` (`attribute_id`, `entity_type_id`, `attribute_code`, `attribute_model`, `backend_model`, `backend_type`, `backend_table`, `frontend_model`, `frontend_input`, `frontend_label`, `frontend_class`, `source_model`, `is_required`, `is_user_defined`, `default_value`, `is_unique`, `note`)
VALUES
	(93, 4, 'news_from_date', NULL, 'Magento\\Catalog\\Model\\Attribute\\Backend\\Startdate', 'datetime', NULL, 'Magento\\Eav\\Model\\Entity\\Attribute\\Frontend\\Datetime', 'date', 'Set Product as New from Date', NULL, NULL, 0, 0, NULL, 0, NULL),
	(94, 4, 'news_to_date', NULL, 'Magento\\Eav\\Model\\Entity\\Attribute\\Backend\\Datetime', 'datetime', NULL, 'Magento\\Eav\\Model\\Entity\\Attribute\\Frontend\\Datetime', 'date', 'Set Product as New to Date', NULL, NULL, 0, 0, NULL, 0, NULL);


INSERT INTO `catalog_eav_attribute` (`attribute_id`, `frontend_input_renderer`, `is_global`, `is_visible`, `is_searchable`, `is_filterable`, `is_comparable`, `is_visible_on_front`, `is_html_allowed_on_front`, `is_used_for_price_rules`, `is_filterable_in_search`, `used_in_product_listing`, `used_for_sort_by`, `apply_to`, `is_visible_in_advanced_search`, `position`, `is_wysiwyg_enabled`, `is_used_for_promo_rules`, `is_required_in_admin_store`, `is_used_in_grid`, `is_visible_in_grid`, `is_filterable_in_grid`, `search_weight`, `additional_data`, `attribute_suffix`, `attribute_range_algorithm`, `attribute_range_steps`, `hide_on_stores`, `attribute_use_slider`, `attribute_show_if_one`, `is_displayed_in_autocomplete`, `is_used_in_spellcheck`, `facet_min_coverage_rate`, `facet_max_size`, `facet_sort_order`, `facet_boolean_logic`, `is_display_rel_nofollow`, `display_pattern`, `display_precision`, `sort_order_asc_missing`, `sort_order_desc_missing`, `is_pagebuilder_enabled`, `include_zero_false_values`)
VALUES
	(93, NULL, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, NULL, 0, 0, 0, 1, 0, 1, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, 90, 10, '_count', 0, 0, NULL, 0, '_last', '_last', 0, 0),
	(94, NULL, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, NULL, 0, 0, 0, 1, 0, 1, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 1, 90, 10, '_count', 0, 0, NULL, 0, '_last', '_first', 0, 0);

```
The only difference I can see is that news_from_date is used for sort (`used_for_sort_by` = 1) and not news_to_date (`used_for_sort_by` = 0).

Am I missing something here, or is there a bug ?

**Comment by romainruaud** [comment]
Hi @Nuranto 

This is normal that values are merged from child product into the parent.

For scoped values, we take the first non-null that is found, with taking first the store-scoped value, and then the default.

We use non-null to allow the legacy magento of overriding the default value in the store-scoped one, so if you've placed "null" arbitrary on a store-scoped value, this will be fallbacked to the default one.

regards

**Comment by Nuranto** [comment]
I understand for child/parent.

For default value, it doesn't seems right though. If I understood you correctly, you're saying that if a store-scoped value is set to NULL (but value_id is not null), and the default one is '2022-06-08', then the default value will be indexed ? 

If so, that's a bug to me, we should use default value only if the store-scoped value is missing (value_id is null)

**Comment by Nuranto** [comment]
Hi,

I'm not sure it only make sense for dates, could cause problem for any text input I guess.

But ok, if I find some time, I'll work on a PR.

**Comment by romainruaud** [comment]
Your PR was merged, I close.
