### ISSUE TITLE
OpenSearch for M2.4.3?

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#2596]
@romainruaud 

I've reviewed the README and it seems OpenSearch is only available with ES2.10.10 and M2.4.4.

Can you confirm that OpenSearch compatibility and ES2.10.10 will not work with M2.4.3?

We can't yet update to M2.4.4, but we really need OpenSearch compatibility.

**Comment by refueledinc** [comment]
I see this in the release notes for ES2.10.10

> This release is also compatible with Magento 2.4.1, 2.4.2 and 2.4.3 so you do not need to upgrade your Magento instance to use it :)

Unless I'm reading the README wrong, seems there is a bit of a disconnect?

The README seems to indicate that you must use M2.4.4 and ES2.10.10 in order to have OpenSearch support.

**Comment by romainruaud** [comment]
This should be read as : 

- Only Elasticsuite 2.10.10 is compatible with Open Search.
- Magento 2.4.4 requires Elasticsuite 2.10.10
- **But Elasticsuite 2.10.10 is supposed to be compatible with prior 2.4.x versions**
