### ISSUE TITLE
Category Schedulled updates Preview

### ISSUE THREAD

**Issue by rqsakai** [Smile-SA/elasticsuite#2597]
### Preconditions
OS: Ubuntu server 20.04
Env: Magento 2 Cloud docker
Magento version: Adobe commerce loud 2.4.3
ElasticSuite Version : 
- smile/elasticsuite 2.10.9.1
- smile/module-elasticsuite-quick-order 2.10.1
- smile/module-elasticsuite-rating 2.3.2
- smile/module-elasticsuite-shared-catalog 2.10.3
- smile/module-elasticsuite-targetrule 1.4.1

Magento Environment: Developer mode

Third-party modules: None that touches ElasticSearch implementation

### Steps to reproduce
1. Disable some products
2. Create a scheduled update for those products
3. Preview Scheduled update
4. In the preview mode go to the product page [It works]
5. In the preview mode go to the category page and check for the product [**Does not work**]
6. In the preview mode search for the product and check for the product [**Does not work**]

### Expected result
1. should be able to see the product on the category page in preview mode
2. should be able to see the product in the search results in preview mode

### Actual result
1. Product is not indexed on the elasticsearch index
2. Products never show on Category or search while in the preview mode

**Comment by vahonc** [comment]
Hello @rqsakai,

It could be difficult to index products that have disabled status.

Have you tried to check this behavior with Magento and Elasticsearch7 legacy by removing our module?

BR,
Vadym
