### ISSUE TITLE
Get specific filter in separate block

### ISSUE THREAD

**Issue by murphy1484** [Smile-SA/elasticsuite#2598]
In one of our projects we have all the filters in a slide-out menu.
But I would need the color filter to be always visible above the product list.

I've created a block that extends `Smile\ElasticsuiteCatalog\Block\Navigation` .
Here I can loop through `$this->getDisplayedFilters()` and check the Filter instance and the requestVar to extract the color filter. The problem here is that all the filter instances are `Magento\Catalog\Model\Layer\Filter` instances instead of `Smile\ElasticsuiteCatalog\Model\Layer\Filter`.

How should I go about this?

**Comment by romainruaud** [comment]
You are probably missing those lines : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/frontend/di.xml#L74:L103

Beware, there are also similar DI modifications in the virtual category module.

You should probably reproduce the same thing for your particular block.

**Comment by murphy1484** [comment]
@romainruaud I've tried your suggestion without luck.
See my code below.

`frontend/di.xml`

<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">

    <virtualType name="categoryFilterList" type="Smile\ElasticsuiteCatalog\Model\Layer\FilterList">
        <arguments>
            <argument name="filterableAttributes" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Layer\Category\FilterableAttributeList</argument>
            <argument name="filters" xsi:type="array">
                <item name="attribute" xsi:type="string">Smile\ElasticsuiteCatalog\Model\Layer\Filter\Attribute</item>
                <item name="price" xsi:type="string">Smile\ElasticsuiteCatalog\Model\Layer\Filter\Price</item>
                <item name="decimal" xsi:type="string">Smile\ElasticsuiteCatalog\Model\Layer\Filter\Decimal</item>
                <item name="category" xsi:type="string">categoryFilterUsingRewrite</item>
                <item name="boolean" xsi:type="string">Smile\ElasticsuiteCatalog\Model\Layer\Filter\Boolean</item>
            </argument>
        </arguments>
    </virtualType>

    <virtualType name="categoryFilterUsingRewrite" type="Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category">
        <arguments>
            <argument name="useUrlRewrites" xsi:type="boolean">true</argument>
        </arguments>
    </virtualType>

    <virtualType name="GlueCustomColorFilter" type="Glue\CategoryAdditionals\Block\ColorFilter">
        <arguments>
            <argument name="filterList" xsi:type="object">categoryFilterList</argument>
        </arguments>
    </virtualType>
</config>

`ColorFilter.php`

```
<?php

namespace Glue\CategoryAdditionals\Block;

use Magento\Catalog\Model\Layer\AvailabilityFlagInterface;
use Magento\Catalog\Model\Layer\FilterList;
use Magento\Catalog\Model\Layer\Resolver;
use Magento\Framework\Module\Manager;
use Magento\Framework\ObjectManagerInterface;
use Magento\Framework\View\Element\Template\Context;
use Smile\ElasticsuiteCatalog\Block\Navigation;

class ColorFilter extends Navigation
{
    public function __construct(
        Context                      $context,
        Resolver                     $layerResolver,
        FilterList                   $filterList,
        AvailabilityFlagInterface    $visibilityFlag,
        ObjectManagerInterface       $objectManager,
        Manager                      $moduleManager,
        array                        $data = []
    )
    {
        parent::__construct($context,
            $layerResolver,
            $filterList,
            $visibilityFlag,
            $objectManager,
            $moduleManager,
            $data
        );
    }

    public function getColorFilter()
    {
        $displayedFilters = $this->getDisplayedFilters();
        dd($displayedFilters);
        // returns
        
        //  array:3 [▼
        //  0 => Magento\Catalog\Model\Layer\Filter\Category {#2331 ▶}
        //  1 => Magento\Catalog\Model\Layer\Filter\Attribute {#2335 ▶}
        //  2 => Magento\Catalog\Model\Layer\Filter\Price {#2330 ▶}
        //]

        dd($this->filterList);
        // returns
        
        // ^ Magento\Catalog\Model\Layer\FilterList {#3994 ▼
        // #objectManager: Magento\Framework\App\ObjectManager {#52 ▶}
        // #filterableAttributes: Magento\Catalog\Model\Layer\Category\FilterableAttributeList {#928 ▶}
        // #filterTypes: array:4 [▶]
        // #filters: array:6 [▼
        //     0 => Magento\Catalog\Model\Layer\Filter\Category {#3963 ▶}
        //     1 => Magento\Catalog\Model\Layer\Filter\Attribute {#3967 ▶}
        //     2 => Magento\Catalog\Model\Layer\Filter\Attribute {#3993 ▶}
        //     3 => Magento\Catalog\Model\Layer\Filter\Attribute {#3987 ▶}
        //     4 => Magento\Catalog\Model\Layer\Filter\Attribute {#4000 ▶}
        //     5 => Magento\Catalog\Model\Layer\Filter\Price {#4003 ▶}
        //     ]
        // -layerCategoryConfig: Magento\Catalog\Model\Config\LayerCategoryConfig {#2146 ▶}
        // }
    }
}
```

**Comment by romainruaud** [comment]
```
<virtualType name="GlueCustomColorFilter" type="Glue\CategoryAdditionals\Block\ColorFilter">
    <arguments>
        <argument name="filterList" xsi:type="object">categoryFilterList</argument>
    </arguments>
</virtualType>
```

You should not define a virtual type for your block if your block exists. In your case you should inject the proper parameters inside your block constructor.

Something like : 

```
<type name="Glue\CategoryAdditionals\Block\ColorFilter">
    <arguments>
        <argument name="filterList" xsi:type="object">categoryFilterList</argument>
    </arguments>
</virtualType>
```

**Comment by murphy1484** [comment]
@romainruaud now it works.
Thanks!
