### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by kovalevandrew** [Smile-SA/elasticsuite#260]
Hello, after enable modules i use command `bin/magento setup:di:compile`  and get this.

`  [ErrorException]
  Declaration of Smile\ElasticsuiteSwatches\Helper\Swatches::loadVariationByF
  allback(Magento\Catalog\Api\Data\ProductInterface $parentProduct, array $at
  tributes) should be compatible with Magento\Swatches\Helper\Data::loadVaria
  tionByFallback($parentProduct, array $attributes)
`

Can you help me?

**Comment by kovalevandrew** [comment]
Solved by commenting extend core helper dada (Magento\Swatches\Helper\Data) in Smile\ElasticsuiteSwatches\Helper\Swatches

**Comment by Koc** [comment]
@kovalevandrew what version of Magento do you using?

**Comment by kovalevandrew** [comment]
2.0.7
