### ISSUE TITLE
Plugin aroundQuery at Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter

### ISSUE THREAD

**Issue by profbruna** [Smile-SA/elasticsuite#2603]
### Discussed in https://github.com/Smile-SA/elasticsuite/discussions/2602

<div type='discussions-op-text'>

<sup>Originally posted by **profbruna** June 10, 2022</sup>
Hi

I need to create a plugin where I can change the sql script of the query when loading the screen. How could I perform this change in this class?

This is original plugin code for elasticsearch7 on Magento\Framework\Search\AdapterInterface. This works fine with elasticsearch7, but not with elasticsuite.

`namespace Vendor\Marketplace\Plugin\Elasticsearch7\SearchAdapter;

use Vendor\Marketplace\Helper\Data as MpHelper;
use Magento\Framework\Search\RequestInterface;
use Magento\Elasticsearch\SearchAdapter\Aggregation\Builder as AggregationBuilder;
use Magento\Elasticsearch\SearchAdapter\ConnectionManager;
use Magento\Elasticsearch\SearchAdapter\ResponseFactory;
use Magento\Elasticsearch7\SearchAdapter\Mapper;
use Magento\Elasticsearch\SearchAdapter\QueryContainerFactory;

class Adapter
{

    private $responseFactory;
    private $connectionManager;
    private $aggregationBuilder;
    protected $helper;
    private $mapper;
    private $queryContainerFactory;
    protected $request;
    protected $collection;
    private static $emptyRawResponse = [
        "hits" =>
            [
                "hits" => []
            ],
        "aggregations" =>
            [
                "price_bucket" => [],
                "category_bucket" =>
                    [
                        "buckets" => []

                    ]
            ]
    ];

    public function __construct(
        ConnectionManager $connectionManager,
        ResponseFactory $responseFactory,
        AggregationBuilder $aggregationBuilder,
        Mapper $mapper,
        QueryContainerFactory $queryContainerFactory,
        \Vendor\Marketplace\Helper\Data $helper,
        \Magento\Framework\App\RequestInterface $request,
        \Vendor\Marketplace\Model\ResourceModel\Product\Collection $collection
    ) {
        $this->connectionManager = $connectionManager;
        $this->responseFactory = $responseFactory;
        $this->aggregationBuilder = $aggregationBuilder;
        $this->mapper = $mapper;
        $this->queryContainerFactory = $queryContainerFactory;
        $this->helper = $helper;
        $this->request = $request;
        $this->collection = $collection;
    }
    public function aroundQuery(
        \Magento\Framework\Search\AdapterInterface $subject,
        callable $proceed,
        RequestInterface $request
    ) {
        if ($this->request->getFullActionName() == 'marketplace_seller_collection') {
            $marketplaceProduct = $this->collection->getTable('marketplace_product');
            $sellerId = $this->getProfileDetail()->getSellerId();
            $client = $this->connectionManager->getConnection();
            $aggregationBuilder = $this->aggregationBuilder;
            $updatedQuery = $this->mapper->buildQuery($request);
            $productIds = $this->helper->getSellerProducts($sellerId);
            $updatedQuery['body']['query']['bool']['filter'] = ['ids' => ['values' => $productIds]];
            $aggregationBuilder->setQuery($this->queryContainerFactory->create(['query' => $updatedQuery]));
            try {
                $rawResponse = $client->query($updatedQuery);
            } catch (\Exception $e) {
                $this->helper->logDataInLogger("Elasticsearch7_SearchAdapter_Adapter aroundQuery ".$e->getMessage());
                // return empty search result in case an exception is thrown from Elasticsearch
                $rawResponse = self::$emptyRawResponse;
            }

            $rawDocuments = $rawResponse['hits']['hits'] ?? [];
            $queryResponse = $this->responseFactory->create(
                [
                    'documents' => $rawDocuments,
                    'aggregations' => $aggregationBuilder->build($request, $rawResponse),
                    'total' => $rawResponse['hits']['total']['value'] ?? 0
                ]
            );
            return $queryResponse;
        }
        return $proceed($request);
    }

    public function getProfileDetail()
    {
        return $this->helper->getProfileDetail(MpHelper::URL_TYPE_COLLECTION);
    }
}`

Can anybody help me?</div>

**Comment by romainruaud** [comment]
Hi @profbruna 

If you want to do something like this, you should implement a filter like this : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml#L23

Then you just have to implement the filtering (by product id in your case) withing your filter implementation.

Regards

**Comment by profbruna** [comment]
I think I got it, so when I'm in the aroundQuery plugin I created for "Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter" should I add this list of Id's to that filter?

My question at that moment would be how to inform the Id's that I want to the filter. We can assume they were:

$ids = [1,2,3,4,5];

Where would I add the call to the filter by passing these Id's?

Thanks again
