### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2604]
![Capture d’écran 2022-06-11 à 10 07 02](https://user-images.githubusercontent.com/1633463/173179377-5b4510f1-c568-4720-9b2d-2a8d3278e4c5.png)

**Comment by romainruaud** [comment]
Are you having a null value for $alias ?

That's not supposed to be the case as per https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/config.xml#L29

Can you give us more details about what causes `$alias` being null in this case ?

Regards

**Comment by Nuranto** [comment]
I try to reproduce by launching the cron manually, but cannot reproduce it. It's probably context-dependant (indice states or something).

If I found more information, I'll let you know
