### ISSUE TITLE
Magento 2 Search Auto Complete Issue - Elastic suite module from Smile

### ISSUE THREAD

**Issue by OneClickCloud** [Smile-SA/elasticsuite#2607]
We have set up Smile Elasticsuite, but Search Autocomplete does not show the feature as mentioned in the demo, that Autocomplete load search result with the count.

https://github.com/Smile-SA/elasticsuite
http://demo.magento-elastic-suite.io/

### Preconditions

Magento Version : Magento CE 2.4.4

ElasticSuite Version : 2.10.10

Environment : Production

Third party modules : No, we have disabled all third-party modules which is used before setup Smile-Elasticsuite Module

### Steps to reproduce

1. Setup Elasticsuite Module at Magento CE 2.4.4
2. Once you search at the search bar, it just shows some relevant results inside autocomplete popup
3. but that autocomplete does not show results like relevant category, the search result with the link, a product with image and name

### Expected result

1. Autocomplete load following functionality
-> Category name and link based on Search terms
-> Search result with link
-> Product load with image, name, and link

![image](https://user-images.githubusercontent.com/103513214/173500624-b73a9263-27c2-4dc3-9e86-a2247b717f62.png)

### Actual result

1. [Screenshot, logs]
currently, it just shows matched search results with count
![image](https://user-images.githubusercontent.com/103513214/173500770-4a67bde5-be21-43f9-ac1b-e54a2261a638.png)

**Comment by romainruaud** [comment]
Hi @OneClickCloud 

Did you have a look at https://github.com/Smile-SA/elasticsuite/wiki/FAQ#the-autocomplete-box-is-not-showing-up--does-only-display-search-terms ?

Regards
