### ISSUE TITLE
Unable To Push certain products to the End using an Optimizer

### ISSUE THREAD

**Issue by achrafkh** [Smile-SA/elasticsuite#2610]
What i'm trying to achieve here is to push sold out product to the bottom in each product list page.
But it doesn't work and out of stock products change position but not toward the end.

### Preconditions
Magento Version : 2.4.2-p1

ElasticSuite Version : 2.10.9

Environment : PHP 7.4.11

Third party modules :

### Steps to reproduce

1. Have Few product in Category list page ( 3 or 4 ) with One product out of stock
2. Create Optimizer 
    Model: Constant 
    Request type: Select All 
    Condition : If ALL  of these conditions are FALSE : Only in stock products
    Boost value: -99
3. Apply / Reindex and check Product listing

### Expected result
1. Expected Result is for the Product to appear at the end of the Product list

### Actual result
1. ![image](https://user-images.githubusercontent.com/16535365/173711046-ca8b3fee-559e-47fc-b8eb-d3b237100ceb.png)

Is there something wrong here or is it just not something that an optimizer can achieve?

**Comment by vahonc** [comment]
Hello @achrafkh,

I was not able to reproduce your issue on my test environment (fresh Magento 2.4.2-p1 EE with default Sample data and ElasticSuite 2.10.9). In my case, after adding the optimizer all worked as I expected and out-of-stock products moved to the end of the product list.

Here're my steps with screenshots:

1. Have a few products in the category list with one product out-of-stock (name of the product: `Test Product 200672`)

![Screenshot from 2022-06-15 13-12-01](https://user-images.githubusercontent.com/67791361/173830018-237137fe-d835-437e-a489-1b00dfc560a5.png)

![Screenshot from 2022-06-15 13-15-27](https://user-images.githubusercontent.com/67791361/173830036-9bb80f1d-3f37-44aa-9482-715ae3838dea.png)

As you can see the `Test Product 200672` is on the top of the list.

2. Create a new Optimizer
Model: Constant
Request type: Select All
Condition: If ALL of these conditions are FALSE: Only in stock products
Boost value: -99

![Screenshot from 2022-06-15 13-16-33](https://user-images.githubusercontent.com/67791361/173830677-2bb20b89-3eb5-4fb2-b867-a81e032c1343.png)

3. Apply / Reindex and check the Product listing

![Screenshot from 2022-06-15 13-18-32](https://user-images.githubusercontent.com/67791361/173830829-680ff852-2cfd-4792-9c85-349e6ab4030c.png)

![Screenshot from 2022-06-15 13-20-22](https://user-images.githubusercontent.com/67791361/173830882-3d544748-ea64-401b-a8ba-ef0b4dbf410d.png)

So now my test product `Test Product 200672` is at the end of the list, which means that my Optimizer is working.

Are you sure that you enabled your optimizer and everything was cleaned (Magento & Varnish cache) and reindexed?

p.s. By the way, you can also try to create an optimizer for your purpose, and apply a positive boost to products that are In stock. In this case, all products that In-Stock will be moved to the top of the products list.

BR,
Vadym
