### ISSUE TITLE
Product widget with products selected by category and sort by position does not respect the products position in category

### ISSUE THREAD

**Issue by RyseSlade** [Smile-SA/elasticsuite#2612]
Product widgets like the products carousel used in the page builder do not respect the manual sort for products selected by category and sort by position.

### Preconditions
Docker, PHP 7.4

Magento Version : CE 2.4.4

ElasticSuite Version : 2.10.10

Environment : Developer

Third party modules : none

### Steps to reproduce
1. Install Magento with sample data
2. Install Elasticsuite
4. Create a new category "A" with five sample products
5. Create another new category "B" with the same five sample products but change one of the latter products to "manual sort" so it should display as the first product (and change the product order)
6. Create a new category "C". Use the categories content page builder to add a products carousel with "select products by" set to "category", select the "A" category (the one that does NOT have any products with manual sort enabled) and "sort by" set to "position"
7. Open the frontend and click the "C" category (the one with the products carousel)

### Expected result
1. The product carousel should display the products of the "A" category in the order displayed when you open the "A" category

### Actual result
1. The product carousel shows the products of the "A" category but the first product listed is the one that was set to "manual sort" in the "B" category.

Magento uses a plugin Magento\PageBuilder\Plugin\Catalog\Block\Product\ProductsListPlugin to apply the sorting. This does not work with elasticsuite. Actually there does not happen any filtering on the selected category id. This means the elastic query uses the position of ANY category id. This results in category "C" displaying the manul sort position that was set in category "B" even though category "A" is used for the product carousel.

Not sure this is a clean and 100% working solution but what seems to work with this specific issue is a plugin for that same class (Magento\CatalogWidget\Block\Product\ProductsList) that adds the sort filter parameters.

```
class ElasticsuiteCreateCollectionPlugin
{
    public function afterCreateCollection(ProductsList $subject, Collection $result)
    {
        if ($result instanceof \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection) {
            $conditionOption = $subject->getData('condition_option');
            $categoryId = $conditionOption === 'category_ids' ? $subject->getData('condition_option_value') : null;
            $sortOption = $subject->getData('sort_order');

            if ($conditionOption == 'category_ids' && $sortOption == 'position' && $categoryId) {
                $result->addSortFilterParameters('position', 'category.position', 'category', ['category.category_id' => $categoryId]);
            }
        }

        return $result;
    }
}
```

**Comment by romainruaud** [comment]
Probably this logic could be added into this file : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-virtual-category/Plugin/Widget/ProductsListPlugin.php#L108
