### ISSUE TITLE
Disbale only specific Modules

### ISSUE THREAD

**Issue by rimmeh** [Smile-SA/elasticsuite#2613]
Hi,

i have installed the Elastic suite but only realy need the Autocomplete, other Features are not compilant with my shop:
a) Catalog sorting via position is decending but it was ascending before ES install
b) Disabled Filters in Catalog when only products with same value exists. But i need them to show even if there are only results with same value. I have a very special Table like Layout an the filters work like tableheads, so i need them to stay.

Which Modules do i have to disable to disable a) and b) ?

modules:status gives:
Smile_ElasticsuiteAdminNotification
Smile_ElasticsuiteCore
Smile_ElasticsuiteCatalog
Smile_ElasticsuiteCatalogGraphQl
Smile_ElasticsuiteCatalogRule
Smile_ElasticsuiteCatalogOptimizer
Smile_ElasticsuiteCms
Smile_ElasticsuiteTracker
Smile_ElasticsuiteThesaurus
Smile_ElasticsuiteSwatches
Smile_ElasticsuiteIndices
Smile_ElasticsuiteAnalytics
Smile_ElasticsuiteVirtualCategory

Or is there another way to reactivate the normale behavior of MAgento with those 2 things?

regards,

rimmeh

**Comment by vahonc** [comment]
Hello @rimmeh,

>a) Catalog sorting via position is decending but it was ascending before ES install

You can try disabling Smile_ElasticsuiteVirtualCategory because this module may affect sorting by position.

>b) Disabled Filters in Catalog when only products with same value exists. But i need them to show even if there are only results with same value. I have a very special Table like Layout an the filters work like tableheads, so i need them to stay.

For the filter's configuration you can take some  experience from our Wiki:
- [Faceting configuration of the product attributes](https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration) 
- [Faceting configuration by category](https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration-by-category)

BR,
Vadym

**Comment by rimmeh** [comment]
Hi Vadym,

thanks for the reply.

a) I tried it. Disabling the Modul does not affect the Sorting. So not what i need.

b) I can configure the attribute in specific category option to "View Mode = always displayed". Thats what i needed. But i have over 300 Categories and 150 attributes and dont want to configure this 300x150 times. How can i set that option global? I cant find it in the options of the attribute.

reagards,

rimmeh

**Comment by vahonc** [comment]
Hi @rimmeh,

>b) I can configure the attribute in specific category option to "View Mode = always displayed". Thats what i needed. But i have over 300 Categories and 150 attributes and dont want to configure this 300x150 times. How can i set that option global? I cant find it in the options of the attribute.

Unfortunately, there is no such option for attributes from out of the box. Therefore, you will have to go through a custom solution. It can be a SQL request directly to the database with the insertion of the desired value for all the attributes that you want to update, or a composer patch with a fix directly in the code of the module.

BR,
Vadym
