### ISSUE TITLE
Catalog Search indexer process unknown error:

### ISSUE THREAD

**Issue by kovalevandrew** [Smile-SA/elasticsuite#262]
When i try to `bin/magento index:reindex catalogsearch_fulltext` i have receive :
`Catalog Search indexer process unknown error:
No handler found for uri [/magento2_default_catalog_product_20161222_125729] and method [POST]
`
it is problem with my elasticsearch server?

**Comment by afoucret** [comment]
Hi @kovalevandrew,

What version of ElasticSearch are you using.

It's looks like you are using ElasticSearch 5.x which is not yet supported as explained in the wiki : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

Do you confirm ?

**Comment by kovalevandrew** [comment]
Oh i dont notice that, what version of elastic do i need to use and when do you support version 5.x ???

**Comment by afoucret** [comment]
Hi @kovalevandrew

As explained in #211 : 

> ElasticSearch 5.x support is planned, but we have to work on the module compatibility. One of the most difficult part of the job is to update the ES PHP Client to the 5.x version. While it is not a huge problem for the community edition of Magento, the enterprise one requires a 2.x client. As we want provide support for Magento EE, we will need to find a way. We will have to work with Magento team in order to get this achieved.

You can use ElasticSearch 2.4.x and you should have a successfull install if you follow the wiki [Server Config Page](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig).

BR,
