### ISSUE TITLE
Per indices configuration

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2620]
**Is your feature request related to a problem? Please describe.**

Currently, many indices configurations (shard qty, replicas qty, batch_indexing_size) are managed globally. It would be great to have the possibility to configure each indexes separatly.

For example we may not want as many shards for category index and product index. Or if we need to add a custom indice that manage millions of small records, we may want to increase batch_indexing_size. etc..

**Describe the solution you'd like**

I see two solution : 
1. Managed in `system.xml` with a `Magento\Config\Block\System\Config\Form\Field\FieldArray\AbstractFieldArray` field
2. Managed in `elasticsuite_indices.xml` (and `elasticsuite_indices.xsd`) via extra attributes or nodes. (Probably easier and safer and fits most of the cases)

**Comment by romainruaud** [comment]
Hi @Nuranto 

That could be interesting. However, 99% of merchants don't need more than 1 shard, even for product indices.

You should consider using 2 shards when your index is greater than dozens of Gbs.

So for me this is really low priority actually.

**Comment by Nuranto** [comment]
Hi, we indeed created another huge index. So, yes, I understand this is low priority.

**Comment by Nuranto** [comment]
functionnality added by e5d7f872f891843bb685ffefcc172d1aba347fb5, thanks !
