### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by bangln** [Smile-SA/elasticsuite#2622]
I have an issue with search: 
when i search for swan, it have no exact ressults: https://sklep.yes2move.com/catalogsearch/result/?q=swan
but when i type 'swanson', it have 9 results: https://sklep.yes2move.com/catalogsearch/result/?q=swanson 
please help me!

**Comment by vahonc** [comment]
Duplicate of #2600

@bangln, take some experience from the initial issue.

BR,
Vadym

**Comment by bangln** [comment]
It's work! thanks very much!
Regard!

**Comment by vahonc** [comment]
In this case, I'm closing this issue.
