### ISSUE TITLE
.CRITICAL: Error: Call to a member function setRequestPath() on null

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2623]
Magento 2.4.4
Smile_ES 2.10.10

```
.CRITICAL: Error: Call to a member function setRequestPath() on null in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Url.php:222
Stack trace:
#0 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Router.php(159): Smile\ElasticsuiteVirtualCategory\Model\Url->getCategoryRewrite('vaccinium', '7')
```

**Comment by romainruaud** [comment]
Hi @Nuranto 

Can you please respect the issue template and give detailed steps about how to reproduce the issue ?

Otherwise it's unlikely someone of the team will have a look at it.

Regards

**Comment by Nuranto** [comment]
Error seems clear and easy to fix. Reproduce it can be complicated. 
But I get it, I'll patch it on my side.

**Comment by lumnn** [comment]
The way to reproduce an issue is to have 2+ stores. Accessing an url based on url-key from another store (that doesn't exist in current one) will result in $rewrite variable beeing empty and therefore call to setRequestPath throws error.

The suggested fix seems to be working, and that's what I added in PR submitted a moment ago
