### ISSUE TITLE
Exclude categories from autocomplete results

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2624]
I'd like to be able to exclude some categories from the autocomplete results.

For me, this should be done by following those steps : 

**1. Add an attribute to categories**

We should add an attribute name "Displayed in autocomplete" to all categories.

This attribute should be displayed after the "Use category name in product search" field of the form.

This attribute should have a default value of 1, and be applied to all existing categories with a setup script for existing installations of Elasticsuite.

To create an attribute : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Setup/CatalogSetup.php#L63

To set it to "1" for all existing categories : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Setup/CatalogSetup.php#L85

**2. Display this attribute in the back-office form**

This should be automatic since the attribute will be created in the proper attributes group.

**3. Use it to exclude categories in autocomplete requests**

This can be done here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/Autocomplete/Category/DataProvider.php#L181

We should add two things : 

```
$categoryCollection->addAttributeToSelect("is_displayed_in_autocomplete");
$categoryCollection->addFieldToFilter("is_displayed_in_autocomplete", 1);
```

**4 . If I set a category to be disabled for autocomplete, I should not be able to see it when I search for his name**

**Comment by romainruaud** [comment]
This has been released, I close.

**Comment by Tanu098** [comment]
Hi, I am using magento2.4.4 and php version8.1 
I have installed the elastic suite version2.10.10 but products are not listed on the category page.

**Comment by vahonc** [comment]
Hello @Tanu098,

If you want to use this feature you need to install ElasticSuite version 2.10.11.

Also please notice, that this feature is related to excluding categories from autocomplete results and not related to products listing.

BR,
Vadym
