### ISSUE TITLE
Can't Adjust/remove default sort order easily 

### ISSUE THREAD

**Issue by trunglv** [Smile-SA/elasticsuite#2629]
Hi team,
I just want to customize default orders for product collection. As I debugged, I need to have a way to write a plugin for the function addDefaultSortOrders. But now, it is private. I can't do anything now. I know that we rarely want to change it. But for my project, I really need to do it. So I just suggest we can move it to configuration, or apply any design pattern so a developer can modify and extend it easily. 

![image](https://user-images.githubusercontent.com/820411/178096259-459b5071-7b1f-48ac-9fe8-1b1c49b674d7.png)

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Search/Request/SortOrder/SortOrderBuilder.php

**Comment by romainruaud** [comment]
What we should do here is : 

- Create an Interface called "DefaultSortOrderProviderInterface" with a unique method "getDefaultSortOrders".
- Implement this interface with a class named "DefaultSortOrderProvider"
- This class will implement the getDefaultSortOrders method and return what we have legacy
- We will inject the DefaultSortOrderProviderInterface inside the private method of the SortOrderBuilder to retrieve default sort order

**Comment by trunglv** [comment]
Thanks @romainruaud so much!
