### ISSUE TITLE
How to implement filter block on the frontend?

### ISSUE THREAD

**Issue by qumuq-til** [Smile-SA/elasticsuite#2631]
I've installed Elasticsuite according to the instructions and it appears to work. However I cannot figure out how to enable the multiselect navigation, the block that allows, for example, specifying multiple product sizes in a certain category and filter the product list according to the selection.

I have enabled the Size attribute to be shown in Layered Navigation and that block did show on frontend even before I installed Elasticsuite, and I obviously couldn't select more than 1 option there. However after installing Elasticsuite the same block is still there and I can't figure out how to replace it with Elasticsuite's multiple select block, if it should be done automatically or manually. What should I do to enable it?
![1](https://user-images.githubusercontent.com/43707841/178259443-5017a596-2f8b-4bb6-a66e-2c88e047cd58.jpg)

**Comment by vahonc** [comment]
Hello @qumuq-til,

Looking at your screenshot, I can assume that you are probably using some kind of custom theme, or you are using some third-party module for filtering in Layered Navigation. Is that so?

You can see how it should look when the ElasticSuite is properly installed on our [demo site](http://demo.magento-elastic-suite.io/index.php/women/bottoms-women/pants-women.html)

BR,
Vadym

**Comment by qumuq-til** [comment]
I'm using a Koller theme https://themeforest.net/item/koller-multipurpose-sections-magento-2-theme/30180585, there are some modules included with it, listed below, but  there are no third-party modules that I myself have installed for Layered Navigation, nor any custom modifications were made to the navigation code.

```
MageWorx_Info
MageWorx_SearchSuiteAutocomplete
Magefan_Community
Magefan_Blog
Magefan_WysiwygAdvanced

Mageplaza_Core
Mageplaza_Smtp

Rokanthemes_AjaxSuite
Rokanthemes_Brand
Rokanthemes_CategoryTab
Rokanthemes_CustomMenu
Rokanthemes_Faq
Rokanthemes_ImageCmsPage
Rokanthemes_Instagram
Rokanthemes_LayeredAjax
Rokanthemes_OnePageCheckout
Rokanthemes_PriceCountdown
Rokanthemes_ProductTab
Rokanthemes_QuickView
Rokanthemes_RokanBase
Rokanthemes_SlideBanner
Rokanthemes_StoreLocator
Rokanthemes_Superdeals
Rokanthemes_Testimonial
Rokanthemes_Themeoption
Rokanthemes_VerticalMenu
Rokanthemes_WidgetSubCategory

Temando_ShippingRemover
```

I'm also having trouble with AJAX (live) search functionality:
```
main.ERROR: Catalog Layer has been already created [] []
main.CRITICAL: RuntimeException: Catalog Layer has been already created in /var/www/mag/vendor/magento/module-catalog/Model/Layer/Resolver.php:54
```

Not sure if the above is a generic error or theme-related.

Either way, could there be an easy way out, such as disabling some module, or overriding an xml file to get the filters to work?

**Comment by qumuq-til** [comment]
Also, I have three "base" extensions related to Layered Navigation and not sure if those should be enabled or disabled when Elasticsuite extensions are enabled. Those are Magento_LayeredNavigation, Magento_SwatchesLayeredNavigation and Magento_TwoFactorAuth. Disabling them however just removed the filter block entirely from the page.

**Comment by vahonc** [comment]
@qumuq-til,

There is no need to disable standard modules of the Magento because ElasticSuite is fully compatible with them. What can not be said about other third-party modules. From the list of modules you provided, I believe you should disable this module `Rokanthemes_LayeredAjax` first. You can also try switching to the default Magento (Luma) theme.

Also, please note that compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do for your issue. You'll have to make a choice, ask the support team of the Rokanthemes directly about your problem or resolve these conflicts by yourself.

BR,
Vadym
