### ISSUE TITLE
Issue Indexing

### ISSUE THREAD

**Issue by gusdemayo** [Smile-SA/elasticsuite#2632]
**Is your question related to a problem? Please describe.**
For some reason when I run a reindex it says it completes each step of the reindex in like 0-2 seconds, including for the catalogsearch_fulltext reindex, but no indices are actually created on my elasticsearch node. I have confirmed that it's actually connected to elasticsearch

**Additional context**
Elasticsuite 2.10.10
Magento 2.4.4
PHP 8.1

**Comment by vahonc** [comment]
Hello @gusdemayo,

I believe that it's something specific to your project. You should check the configuration of your store (indexes settings, assign products to the default store or stores, etc).

Are there any errors in logs (Magento or Elasticsearch)?

Also, could you provide an output of this command `curl http://localhost:9200/_cat/indices?v`

BR,
Vadym
