### ISSUE TITLE
Search Analytics page not working

### ISSUE THREAD

**Issue by Maxime-ClMb** [Smile-SA/elasticsuite#2633]
Hello, 

We are using Elasticsuite V2.10.6 on magento. when trying to access the Analytics page for search terms, we have an error. Everything is working fine in dev and staging environment but not in production. In production, we just have a brokken page with broken date filter. 

Backend configurations seems to be identical between our staging and production environnement. Indexes seems to be OK too.

More details below.

### Preconditions

Magento Version : Magento (cloud) EE 2.4.2-p2 in production mode

ElasticSuite Version : Elasticsuite 2.10.6

### Steps to reproduce

1. login in backend
2. Open Analytics page in Elasticsuite menu

### Expected result

We get a brokken page when we try to access the analytics page for search terms in backend.

### Actual result

![image](https://user-images.githubusercontent.com/109135209/178434880-81109ce7-502f-4196-b5b1-426fae643d05.png)

After checking the logs, here the trace:

[2022-07-06 08:32:10] report.CRITICAL: TypeError: DateTime::__construct() expects parameter 1 to be string, bool given in /app/bxrtuu45mq7zw/vendor/magento/framework/View/Element/AbstractBlock.php:827
Stack trace:
#0 /app/bxrtuu45mq7zw/vendor/magento/framework/View/Element/AbstractBlock.php(827): DateTime->__construct(false)
#1 /app/bxrtuu45mq7zw/vendor/smile/elasticsuite/src/module-elasticsuite-analytics/Block/Adminhtml/Report/DateRangeSwitcher.php(107): Magento\Framework\View\Element\AbstractBlock->formatDate(false, 3, false, 'UTC')
#2 /app/bxrtuu45mq7zw/vendor/smile/elasticsuite/src/module-elasticsuite-analytics/view/adminhtml/templates/report/date_range_switcher.phtml(58): Smile\ElasticsuiteAnalytics\Block\Adminhtml\Report\DateRangeSwitcher->getJsConfig()

Looking at the code more closely, the error seems to come from the function getIndicesDateBounds() who returns false.

**Comment by vahonc** [comment]
Hello @Maxime-ClMb,

It's could be linked to the date format or settings on your Magento Cloud instance.

BR,
Vadym
