### ISSUE TITLE
Plugin removeTrackTotalHitsPlugin misbehave with opensearch

### ISSUE THREAD

**Issue by menardavid** [Smile-SA/elasticsuite#2635]
The pager information section is fixed to 10000 even though there are more than 10000 that should be returned. The plugin removeTrackTotalHitsPlugin check if the search version if > 7 but we are now using Opensearch@1.2.4 with M2.4.4 so the test fails and the property track_total_hits is unset.

### Preconditions
Having opensearch as searchengine and have a category with more than 10000 items

Magento Version : 2.4.4

ElasticSuite Version : **Opensearch**: 1.2.4

Environment : Production

Third party modules : 

### Steps to reproduce

1. Access to a category with more than 10000 records

### Expected result
1. The real count should be returned on the collection->getSize()

### Actual result

1. Even though there are more than 10000 items, only 10000 is returned in the pager info. 

![Screen Shot 2022-07-12 at 15 43 28](https://user-images.githubusercontent.com/76953912/178580622-45c8ede7-5dae-4b77-a051-83beb29b82d0.png)

**Comment by romainruaud** [comment]
Good catch, so we should fix this piece of code : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Plugin/Deprecation/Search/Adapter/Elasticsuite/Request/MapperPlugin.php#L57

This should become something like : 

```php
        if (strcmp($this->serverVersion, "7") < 0
            && $this->serverDistribution == ClusterInfoInterface::DISTRO_ES
```

You can take some inspiration in https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Plugin/Deprecation/Index/MappingPlugin.php
