### ISSUE TITLE
Magento 2.4.4 Pagebuilder product widgets get automatic category filter on category page

### ISSUE THREAD

**Issue by d-korlach** [Smile-SA/elasticsuite#2636]
Hi,

I have a problem at a customers Magento installation. I added a CMS Block to a categories description that contains a pagebuilder product widget. In this product widget I filtered by SKU. 

![Bildschirmfoto 2022-07-13 um 20 43 28](https://user-images.githubusercontent.com/62059576/178807975-9684fd99-b4af-495d-8609-775c00ebb607.png)

One of those products (loaded by SKU) is included in the current category, the other is not. The one that's included is properly displayed the other is not. 

I believe it has to do with the current category filter that is applied here:

https://github.com/Smile-SA/elasticsuite/blob/635635a21ce73ccafccc129799403c1976794346/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml#L49

I found the category filter is automatically applied to the pagebuilders product widget. I could confirm that when I commented this filter out and flushed the cache, then reloaded the page. Now both products were visible (and of course all products of all categories were visibile in the default category product list).

When I deactivated all Smile Elasticsuite modules the widget also worked as intended and both products were visible.

This problem is also not reproducible on cms pages. There the product widget works as intended as well.

Is there any way to work around that or is it fixable by and configurations?

Elasticsearch 7.16

Magento Version :
Magento 2.4.4

ElasticSuite Version :
ElasticSuite Version 2.10.10

Environment :
Developer and Production

### Steps to reproduce
1. Add pagebuilders product widget to a cms block
2. Filter product widget by sku (one that is in the intended category, one that isn't)
3. Add cms block to a categories description

### Expected result
1. All products are always visible, no matter the current category you are viewing

### Actual result
1. Only the products that are in the currently viewed category are visible

**Comment by romainruaud** [comment]
To resolve this, if that's reproductible, I suggest we add another "search request" declaration that will be used for rendering widgets.

The declaration should be like this one : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/elasticsuite_search_request.xml#L45

But without the "currentCategory" declaration, and without the "filterProvider" in aggregations.

The new search request should be named "catalog_product_widget" and labelled with "Catalog Products Widgets".

It should be injected in the collection that is used for rendering widgets : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-virtual-category/etc/di.xml#L134

This collection should be replaced by a virtual type like this : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/etc/di.xml#L97

The newly created virtual type should use the "catalog_product_widget" request.

**Comment by vahonc** [comment]
Hello @d-korlach, 

Could you confirm that in your environment you are disabled **Display Category Filter**, in other words, set up this option to **No** as it's shown on the screenshot below:

![Screenshot from 2022-07-25 17-13-55](https://user-images.githubusercontent.com/67791361/180803741-1767e2aa-d575-464f-82f4-c507afa6e017.png)

BR,
Vadym

**Comment by d-korlach** [comment]
Hello @vahonc,
sorry for the late reply. I can indeed confirm that Display Category Filter is set to No:
![Bildschirmfoto 2022-08-03 um 10 34 21](https://user-images.githubusercontent.com/62059576/182563257-8bd87a18-cd63-4b2c-a041-af5046fdcf56.png)

**Comment by vahonc** [comment]
@d-korlach,

Could you test my fixes for this issue? This should work even if `Display Category Filter` is set to `No`.

BR,
Vadym

**Comment by d-korlach** [comment]
@vahonc,
Soonest I can test this is tomorrow. I will give feedback tomorrow.
Thanks for your quick work.

**Comment by d-korlach** [comment]
@vahonc,
Got to testing right now and everything seems to work fine! I tested the same scenarios as in my first test with the exact same products. Now both products are shown in the category even though one of them is not in the currently viewed category. The product widget still works fine on all pages it worked on before as well.

Many thanks for your very quick work!
