### ISSUE TITLE
Reindex error

### ISSUE THREAD

**Issue by kovalevandrew** [Smile-SA/elasticsuite#265]
As you say in: https://github.com/Smile-SA/elasticsuite/issues/264
I installed phonetic plugin of ElasticSearch and restart the elasticsearch and error still appear.

![elasctic phonetic](https://cloud.githubusercontent.com/assets/8459731/21500495/0fff0382-cc48-11e6-8c01-18f100e4ef8b.PNG)

This is address of my elasticsearch server : http://direct.ult1.ml:9200/_nodes/settings?pretty=true

**Comment by afoucret** [comment]
Are you sure the error message is exactly than previously the same during indexing ?
I look at your cluster setup and everything seems OK to me.

I suspect there is something else causing the error and that having the full error message would be helpful to understand what happen ...

One more thing ... Having your ElasticSearch server open on the Internet is a critical security threat. Someone could send a delete index query that will empty all indices by example or inject data in ElasticSearch. You should increase the security level of the cluster by : 

* Filtering IP of the servers allowed to access ElasticSearch server

* If using ElasticSuite > 2.3.x using HTTPs and user password authentication

BR,

**Comment by kovalevandrew** [comment]
![default](https://cloud.githubusercontent.com/assets/8459731/21547533/5a555dde-cdef-11e6-95fe-c1f70f22179e.PNG)
Thx for this advances but server that i create just for test, on live server of-course i do this stuff)

Issue is still open i cant find any information about this, logs say that we have problem with phonetic but it installed and elastic is restarted as we see in #264 screenshot.

**Comment by kovalevandrew** [comment]
> I suspect there is something else causing the error and that having the full error message would be helpful to understand what happen ...

Can you say where i can get full error message?

**Comment by kovalevandrew** [comment]
Install new magento verison and last ver. of module solve problem thx.
