### ISSUE TITLE
Problem with button "Display Category in Autocomplete"

### ISSUE THREAD

**Issue by mnowakCode** [Smile-SA/elasticsuite#2665]
As I mentioned in this ticket, after upgrading to a new version of your module, I still have a problem with excluding categories from the search. After changing the status to "0" and a full index, the category appears further.

### Preconditions
I use PHP 7.4, ElasticSearch v.7.16.3

Magento Version : 2.4.4

ElasticSuite Version : 2.10.11

Environment : Developer mode

### Steps to reproduce
1 I turned it off button "Display Category in Autocomplete"
<img width="760" alt="image" src="https://user-images.githubusercontent.com/78545108/181723756-7a102a03-273e-4a18-8c46-a9e3d66a8069.png">
2. I did full indexer

### Expected result
1. This category is not showing up in the search

### Actual result
1. I can see this category when searching
<img width="640" alt="image" src="https://user-images.githubusercontent.com/78545108/181724551-bc5a36e7-f161-401f-9638-58f2af1d94ea.png">

I think I found one of the reasons. In this method \Smile\ElasticsuiteCatalog\Model\Autocomplete\Category\DataProvider::getCategoryCollection you didn't add $categoryCollection->addAttributeToSelect("is_displayed_in_autocomplete");
I think this may be a problem, but when I added this, the function still searched get this category.

**Comment by rbayet** [comment]
Hello @mnowakCode,

In addition, to @vahonc's request, could you highlight on your screenshot where you see that category "E-bike Ladestationen" name ?
I only see it in the results block title "Suchbegriffe" which means, if I'm not mistaken "Search terms".
It looks like you don't actually show any Categories results in this autocomplete results screenshots.

Regards,

**Comment by mnowakCode** [comment]
I'm sorry today after again tests, I saw that it works. So we can close this issue
