### ISSUE TITLE
After last module upgrade version see error on log

### ISSUE THREAD

**Issue by achatpc** [Smile-SA/elasticsuite#2666]
### Preconditions

Magento 2.4.4
Php 7.4
Elsticsearch 7.17.5

Magento Version : 2.4.4 CE

ElasticSuite Version : 7.17.5

Environment : Production

Third party modules :

### Steps to reproduce

1. Check magento system.log and /var/log/report folder of Magento
2.
3.

### Expected result

1. No error about NODE

### Actual result

[2022-07-30T22:14:11.360563+00:00] main.CRITICAL: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:64
Stack trace:
#0 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(82): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(99): Elasticsearch\Transport->getConnection()
#2 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php(43): Elasticsearch\Transport->performRequest()
#3 /var/www/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(400): Elasticsearch\Namespaces\BooleanRequestWrapper::performRequest()
#4 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/Client.php(96): Elasticsearch\Namespaces\IndicesNamespace->exists()
#5 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/IndexOperation.php(103): Smile\ElasticsuiteCore\Client\Client->indexExists()
#6 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Index/IndexOperation.php(117): Smile\ElasticsuiteCore\Index\IndexOperation->indexExists()
#7 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php(176): Smile\ElasticsuiteCore\Index\IndexOperation->getIndexByName()
#8 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php(137): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList->getMapping()
#9 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(109): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\AttributeList->getAttributeCollection()
#10 /var/www/html/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(84): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product->loadAttributeOptions()
#11 /var/www/html/vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php(124): Magento\Rule\Model\Condition\AbstractCondition->__construct()
#12 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(88): Magento\Rule\Model\Condition\Product\AbstractProduct->__construct()
#13 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule/Condition/Product.php(79): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product->__construct()
#14 /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Smile\ElasticsuiteVirtualCategory\Model\Rule\Condition\Product->__construct()
#15 /var/www/html/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#16 /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create()
#17 /var/www/html/vendor/magento/module-rule/Model/ConditionFactory.php(55): Magento\Framework\ObjectManager\ObjectManager->create()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Rule\Model\ConditionFactory->create()
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Rule\Model\ConditionFactory\Interceptor->___callParent()
#20 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Rule\Model\ConditionFactory\Interceptor->Magento\Framework\Interception\{closure}()
#21 /var/www/html/generated/code/Magento/Rule/Model/ConditionFactory/Interceptor.php(23): Magento\Rule\Model\ConditionFactory\Interceptor->___callPlugins()
#22 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Combine.php(113): Magento\Rule\Model\ConditionFactory\Interceptor->create()
#23 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Category/Attribute/VirtualRule/ReadHandler.php(75): Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Combine->loadArray()
#24 /var/www/html/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php(48): Smile\ElasticsuiteVirtualCategory\Model\Category\Attribute\VirtualRule\ReadHandler->execute()
#25 /var/www/html/vendor/magento/framework/EntityManager/Operation/Read.php(112): Magento\Framework\EntityManager\Operation\Read\ReadExtensions->execute()
#26 /var/www/html/vendor/magento/framework/EntityManager/EntityManager.php(80): Magento\Framework\EntityManager\Operation\Read->execute()
#27 /var/www/html/vendor/magento/module-catalog/Model/ResourceModel/Category.php(1102): Magento\Framework\EntityManager\EntityManager->load()
#28 /var/www/html/vendor/magento/framework/Model/AbstractModel.php(543): Magento\Catalog\Model\ResourceModel\Category->load()
#29 /var/www/html/generated/code/Magento/Catalog/Model/Category/Interceptor.php(1040): Magento\Framework\Model\AbstractModel->load()
#30 /var/www/html/app/code/Smartwave/Megamenu/Block/Topmenu.php(48): Magento\Catalog\Model\Category\Interceptor->load()
#31 /var/www/html/app/code/Smartwave/Megamenu/Block/Topmenu.php(198): Smartwave\Megamenu\Block\Topmenu->getCategoryModel()
#32 /var/www/html/var/view_preprocessed/pub/static/app/design/frontend/Smartwave/porto/Smartwave_Megamenu/templates/topmenu.phtml(1): Smartwave\Megamenu\Block\Topmenu->getMegamenuHtml()
#33 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#36 /var/www/html/vendor/amasty/module-fpc-warmer/Plugin/Holepunch/TemplateRenderer.php(57): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#37 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Fpc\Plugin\Holepunch\TemplateRenderer->aroundRender()
#38 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#39 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#40 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#41 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#42 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#43 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#44 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#45 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#46 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#47 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#48 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout->renderElement()
#49 /var/www/html/var/view_preprocessed/pub/static/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(1): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#50 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#51 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#52 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#53 /var/www/html/vendor/amasty/module-fpc-warmer/Plugin/Holepunch/TemplateRenderer.php(57): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#54 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Fpc\Plugin\Holepunch\TemplateRenderer->aroundRender()
#55 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#56 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#57 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#58 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#59 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#60 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#61 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#62 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#63 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#64 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#65 /var/www/html/var/view_preprocessed/pub/static/vendor/magento/module-theme/view/frontend/templates/html/sections.phtml(1): Magento\Framework\View\Layout->renderElement()
#66 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#67 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#68 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#69 /var/www/html/vendor/amasty/module-fpc-warmer/Plugin/Holepunch/TemplateRenderer.php(57): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#70 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Fpc\Plugin\Holepunch\TemplateRenderer->aroundRender()
#71 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#72 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#73 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#74 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#75 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#76 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#77 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#78 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#79 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#80 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#81 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout->renderElement()
#82 [internal function]: Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#83 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(94): call_user_func_array()
#84 /var/www/html/var/view_preprocessed/pub/static/app/design/frontend/Emipro/achatpc/Smartwave_Porto/templates/html/header.phtml(1): Magento\Framework\View\TemplateEngine\Php->__call()
#85 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/var/www/html/v...')
#86 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#87 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#88 /var/www/html/vendor/amasty/module-fpc-warmer/Plugin/Holepunch/TemplateRenderer.php(57): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#89 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\Fpc\Plugin\Holepunch\TemplateRenderer->aroundRender()
#90 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#91 /var/www/html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#92 /var/www/html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#93 /var/www/html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#94 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#95 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#96 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#97 /var/www/html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#98 /var/www/html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#99 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#100 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#101 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#102 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#103 /var/www/html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement()
#104 /var/www/html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#105 /var/www/html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement()
#106 /var/www/html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement()
#107 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#108 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent()
#109 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#110 /var/www/html/generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins()
#111 /var/www/html/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#112 /var/www/html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#113 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#114 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent()
#115 /var/www/html/vendor/amasty/gdpr-cookie/Plugin/ProcessPageResult.php(59): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#116 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\GdprCookie\Plugin\ProcessPageResult->aroundRenderResult()
#117 /var/www/html/vendor/amasty/module-page-speed-tools/Plugin/ProcessPageResult.php(45): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#118 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Amasty\PageSpeedTools\Plugin\ProcessPageResult->aroundRenderResult()
#119 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#120 /var/www/html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins()
#121 /var/www/html/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult()
#122 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#123 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#124 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#125 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#126 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#127 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#128 {main} [] []
[2022-07-30T22:14:11.707569+00:00] main.ERROR: No alive nodes found in your cluster [] []
[2022-07-30T22:14:11.711842+00:00] main.ERROR: No alive nodes found in your cluster [] []
[2022-07-30T22:14:11.837720+00:00] main.ERROR: No alive nodes found in your cluster [] []
[2022-07-30T22:14:11.843065+00:00] main.ERROR: No alive nodes found in your cluster [] []
[2022-07-30T22:14:12.176866+00:00] main.ERROR: No alive nodes found in your cluster [] []
[2022-07-30T22:14:12.187295+00:00] main.ERROR: No alive nodes found in your cluster [] []

**Comment by Bashev** [comment]
Are you sure your elasticsearch is up and running?

**Comment by vahonc** [comment]
Hello @achatpc,

Are you sure the **Search Engine** is set to **ElasticSuite** in `Configuration -> Catalog -> Catalog -> Catalog Search -> Search Engine`?

BR,
Vadym

**Comment by achatpc** [comment]
> Hello @achatpc,
> 
> Are you sure the **Search Engine** is set to **ElasticSuite** in `Configuration -> Catalog -> Catalog -> Catalog Search -> Search Engine`?
> 
> BR, Vadym

Yes. And the strange think is that i can use all functions in frontend without issue. And this errors in logs is +/- 1 by hours

**Comment by romainruaud** [comment]
Hi @achatpc 

What is "module-fpc-warmer" ? Could it be possible that this module implies a bug where it would be using a corrupted version of configuration cache or something like that ?

**Comment by achatpc** [comment]
> Hi @achatpc
> 
> What is "module-fpc-warmer" ? Could it be possible that this module implies a bug where it would be using a corrupted version of configuration cache or something like that ?

This is this:

https://amasty.com/full-page-cache-warmer-for-magento-2.html

I can disable it and see if error persist.

**Comment by achatpc** [comment]
Hi, after disable Amasty Full Page Cache Warmer, i can not see any error on log.

I think that the conclusion is that we have now incompatibility between both modules.

Next step is to empty all the caches of this module and reactivate it in order to analyze its behavior.

**Comment by achatpc** [comment]
Hi, i can see on my appache logs that connections with elasticsearch have 70007 TImeout.

Exemple of url:

You can try it for example here (this will create that 70007 error but you need to wait until page loads [few minutes untile timeout is reached]), copy it all, including spaces:

https://www.achatpc.com/de/search/hp z2 g5 ddr4 sdram i7 10700k tower 10th gen intelr core i7 32 gb 1000 gb ssd windows 10 pro workstation black

I think this is related with my issue.

I can not see thir error type before 2.10.11 version of module

**Comment by achatpc** [comment]
Afer downgrade module to 2.10.10, no error in log.

I dont understand why i have this issue with 2.10.11 version.

**Comment by vahonc** [comment]
@achatpc,

I'm not sure, but the only one [PR](https://github.com/Smile-SA/elasticsuite/pull/2542), that was included in the new version of ElasticSuite adding some changes for system settings. Maybe you could try to make some tests.

BR,
Vadym
