### ISSUE TITLE
Mobile search bar is not opening on click

### ISSUE THREAD

**Issue by cartok** [Smile-SA/elasticsuite#2668]
The bug was introduced with https://github.com/Smile-SA/elasticsuite/pull/2566

**Comment by achatpc** [comment]
Same issue on my side. Testing the PR...

**Comment by rbayet** [comment]
Hello @achatpc,

Does the PR work on your side ?

Regards,

**Comment by rbayet** [comment]
OK, just saw the exchanges in https://github.com/Smile-SA/elasticsuite/pull/2566 ...

**Comment by achatpc** [comment]
> Hello @achatpc,
> 
> Does the PR work on your side ?
> 
> Regards,

Yes, working fine
