### ISSUE TITLE
Help with custom module for remote server

### ISSUE THREAD

**Issue by nikonratm** [Smile-SA/elasticsuite#267]
I'm trying to use a remote (AWS) ElasticSearch server. I tried following the wiki instructions at https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#optional--installing-the-module-when-using-a-custom-elasticsearch-server-location & used http://inchoo.net/magento-2/how-to-create-a-basic-module-in-magento-2/

I have a custom module installed (shows up in Admin → Stores → Configuration → Advanced → Advanced) as follows:

/app/code/MSWD/YFElasticSuite/etc/config.xml
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
    <default>
        <smile_elasticsuite_core_base_settings>
            <es_client>
                <servers> %server_endpoint_url% </servers>
            </es_client>
        </smile_elasticsuite_core_base_settings>
    </default>
</config>
```

/app/code/MSWD/YFElasticSuite/etc/module.xml
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MSWD_YFElasticSuite" setup_version="1.0.0">
    </module>
</config>
```

/app/code/MSWD/YFElasticSuite/registration.php
```
<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'MSWD_YFElasticSuite',
    __DIR__
);
```

However when I run bin/magento setup:upgrade I get error `No alive nodes found in your cluster`. When I manually edit the file /vendor/smile/elasticsuite/src/module-elasticsuite-core/etc/config.xml with my remote server URL it works just fine, so I think the issue is related to my custom module.

Thanks so much for any help, really grateful for this module, it works great!

**Comment by romainruaud** [comment]
Hello @nikonratm ,

I think that your module should depend on Smile_ElasticsuiteCore : 

Here is a modified version of how should your module.xml look alike : 

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="MSWD_YFElasticSuite" setup_version="1.0.0">
        <sequence>
            <module name="Smile_ElasticsuiteCore"/>
        </sequence>
</config>
```

We will have to add this specificity to the documentation to prevent this part to be confusing.

Let us know if this does resolve your issue.

Best regards,

**Comment by nikonratm** [comment]
Awesome—that did fix the issue!

Thanks for the module and the help.

**Comment by romainruaud** [comment]
I keep the issue open : 

- to help other peoples that may have the same question.
- as a reminder for us to update the documentation on january.

Best regards,

**Comment by afoucret** [comment]
Doc have been update. The issue can be closed now.
