### ISSUE TITLE
Virtual category subcategory filter

### ISSUE THREAD

**Issue by pvalium** [Smile-SA/elasticsuite#2682]
Hi, I want to know if is possible show category filter in virtual category view. 
Actually i have one virtual category:
![image](https://user-images.githubusercontent.com/20306610/184161879-df584698-945d-4343-8242-183bfaf2199b.png)
but in category view, only show attribute filters:
![image](https://user-images.githubusercontent.com/20306610/184161995-3247a983-dc02-4ae0-8fec-6581f54b7caa.png)

Is this possible?

**Comment by Bashev** [comment]
Try to use: Generate Virtaul Category Root Subtree:
![image](https://user-images.githubusercontent.com/1854269/184663340-d8ce60dd-b2d1-4738-abf1-ddc8e4b70ddc.png)

**Comment by pvalium** [comment]
This option not showing for me:

![image](https://user-images.githubusercontent.com/20306610/184678054-5bc33594-ec65-46ae-b1e2-69b3fe900353.png)

My version is 2.10, and magento 2.4.3

Maybe is in a new version?

**Comment by pvalium** [comment]
Ok, I can see that this is a feature of 2.10.10. I will upgrade module.
Thank you!

**Comment by rbayet** [comment]
Closing as answered by @Bashev

@pvalium feel free to reopen if needed !
