### ISSUE TITLE
Magento upgrade to 2.4.4 with opensearch creating issue with indexing

### ISSUE THREAD

**Issue by kuldipbrillio** [Smile-SA/elasticsuite#2695]
### Preconditions
Magento Version: Magento 2.4.4 EE Cloud

ElasticSuite Version: 2.10.10

Environment: Staging
Search Engine: Opensearch

### Steps to reproduce

1.Execute the reindex command using terminal

### Expected result
Reindex should run successful
### Actual result

1. 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/112680628/188068505-8fca7c63-fcc1-4ffd-8fde-d632e7c58370.png">

We are facing issue with indexing. While run reindex we are getting above error. It was working fine until we have request Adobe support to update elastic and from 2.4.4 onwards they are not supporting elasticsearch so they have enabled opensearch.

Below is the admin setting we have for the elasticsuite.
![Configuration _ Settings _ Stores _ Magento Admin (7)](https://user-images.githubusercontent.com/112680628/188067987-a22e378a-b5eb-4b60-b6cc-75265a43741c.png)

**Comment by romainruaud** [comment]
Hello,

this error is not inherent to Opensearch, you could have exactly the same with Elasticsearch.

Can you please check how much RAM is allocated to the Opensearch server ? You can ask the Magento Cloud team about that.

On a generic manner, to solve this one, you should either : 

- dedicate more RAM to Elasticsearch : let's start with that, if this was working with legacy ES before, there is no reason it won't be running with opensearch.
- reduce the request size when indexing : there is a way in Elasticsuite to do that, but let's stick to the RAM usage for now.

Regards

**Comment by kuldipbrillio** [comment]
Thanks @romainruaud I have increase Ram from my end from the service.yaml and also asked Adobe team to check for RAM. Meanwhile can you please suggest me other alternative way to check it? I have disable smile module and indexing is working fine.

**Comment by kuldipbrillio** [comment]
@romainruaud I have Retenation Delay value from 12 month to 2 month. let me know if is there any other way i can use to reduce request size. It's bit urgent so wanted to try it and check if that solved issue for the testing.

**Comment by romainruaud** [comment]
Hi @kuldipbrillio 

I'll need to know how much data you currently have in your Elasticsearch index.

Can you give us the output of "curl elasticsearch:9200/_cat/indices" ?
