### ISSUE TITLE
Fuzzy search not quite working

### ISSUE THREAD

**Issue by qumuq-til** [Smile-SA/elasticsuite#2701]
I have several products in the store that begin with "chec" or "chem". So, like "checkered" or "chemical". However, issuing a search for "check" never shows a product with "checkered" in the name, likewise, a search for "chem" never shows "chemical". Other products which may not even contain the word snippet are being shown instead. A search for "checkered" lands at the correct (single) product page, whilst a search for "chemical" shows all the relevant products with "chemical" in the name.

Question is, what parameters should I change in ElasticSuite in Magento admin so that the search for "chem" displays "chemical"s and a search for "che" or "chec" displays results including "checkered"?

**Comment by romainruaud** [comment]
Hi,

that's not fuzzy search. There is way too much distance between "che" and "checkered" for the fuzzy search to match.

Check #970
