### ISSUE TITLE
All products in all categories in front

### ISSUE THREAD

**Issue by TouchForDiffusion** [Smile-SA/elasticsuite#2705]
All products are displayed in all categories.

Magento Version : CE - 2.4.3-p1

ElasticSuite Version : 2.10.11

Environment : Production & developer

### Steps to reproduce

1. Setup and enable ElasticSuite 2.10.11

### Expected result

1. Before setup ElasticSuite, the categories had the right products in front.
2. Is OK in back.

### Actual result

In front (504 pages * 32 résultats = + de 16k results)
![image](https://user-images.githubusercontent.com/5040751/189666759-2d2cda4f-9e9a-422d-882f-a1050e6cb735.png)
![image](https://user-images.githubusercontent.com/5040751/189666820-432c5a19-7e68-403b-a7a6-54e1c2ea1684.png)

I disabled all custom preferences but no change.

In back it's ok : 
![image](https://user-images.githubusercontent.com/5040751/189668547-4677bb0d-30dd-49eb-b405-6491cdbd2524.png)

**Comment by Bashev** [comment]
Try with this: https://github.com/Smile-SA/elasticsuite/issues/2698#issuecomment-1238322659

**Comment by TouchForDiffusion** [comment]
Thanks @Bashev but I already checked.
Everything is 1 in the database for the is_anchor attribute.

**Comment by vahonc** [comment]
Hello @TouchForDiffusion,

Have you before installed the ElasticSuite module on your website or it was the first time?

If you have a staging environment, could you try switching to the default Magento theme Luma? Your issue could be linked to compatibility ES with 3rd party themes or modules.

BR,
Vadym

**Comment by TouchForDiffusion** [comment]
After investigation and numerous tests, it is the 
`<referenceBlock name="catalog.leftnav" remove="true"></referenceBlock>`
line that is the problem in my theme.

**Comment by TouchForDiffusion** [comment]
Thank you @vahonc @Bashev for your time.
