### ISSUE TITLE
Warning when there is too much ghost indices.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2711]
**User story :** 

I'd like to have a warning displayed in the Elasticsuite Back-Office when the following event is matched : 

- people have ghost indices.

If that's the case, a warning message should be displayed on top of the Back-Office to indicate them that their cluster is suffering from the presence of ghost indices.

**Technical implementation :**

To display a message in the back-office, you have to inject it like this : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/etc/adminhtml/di.xml#L21

And you have to implement a message class like this : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-core/Model/System/Message/NotificationAboutVersions.php

For the ```isDisplayed()``` it should return ```true``` if : 

- the number of existing ghost indices is > 1

To get the list of ghost indices, you can have a look in the "module-elasticsuite-indices" that is displaying the indices grid in Back-Office. You should find in this module some utility methods that are able to fetch the type of indices, and to know if they are "ghost" or not.

For the ```getIdentity()``` method we should generate an ID that is unique.

For the ```getSeverity()``` method this should be a warning.

For the ```getText()``` method we should return the following message : 

"You have X ghost indices. Ghost indices have a footprint on your Elasticsearch cluster health. You should consider removing them. You can go to the **indices screen** (and here we put a link to Elasticsuite Indices list) to take appropriate actions."

**Comment by vahonc** [comment]
Here you also need to add a translation at least into French.

![Screenshot from 2022-09-28 14-42-40](https://user-images.githubusercontent.com/67791361/192771728-dc26b951-e5d0-42c3-b4c1-a2932ee6eb44.png)

**Comment by romainruaud** [comment]
Merged, I close, will be part of next minor release.
