### ISSUE TITLE
Show out of stock products based on website scope

### ISSUE THREAD

**Issue by JoostWan** [Smile-SA/elasticsuite#2713]
We need to enable show out of stock products for one website view. This is working fine with some code changes. But when Smile ElasticSuite installed and cronjob Index process is running and complete the products are disappear. 

We made the code change in the function `addIsInStockFilterToCollection` based on this version https://magento.stackexchange.com/a/305220

Somebody running an Magento 2 store with Smile Elasticsuite and have show out of stock working for a different store then default.

**Comment by romainruaud** [comment]
Magento legacy parameter "Display out of stock products" is a **global** parameter : it cannot be switched per-store view or per-website.

We respect this parameter when retrieving products.

That being said, Elasticsuite is creating a dedicated index per store view, so this should be easy to do such behavior technically.

But it's unclear exactly what you want to achieve.

Regards

**Comment by JoostWan** [comment]
We want to show products that are out of stock on one website and not on other shops. So we needed the option "Display out of stock products" at website instead of global. For now we found other solution to show out of stock products at website level.

**Comment by romainruaud** [comment]
If you change the scope of the "Display out of stock products", this should work as you expect.

Regards
