### ISSUE TITLE
Search Form Template Override

### ISSUE THREAD

**Issue by nikonratm** [Smile-SA/elasticsuite#272]
Seems this module overrides the mini search form template from a separate theme I am using. I'm wondering how I can avoid this, ideally without modifying this module or the theme itself (but rather using my own code that is a hybrid of the two). How come this module takes precedence over the theme template? 

For now I had to directly edit `/vendor/smile/elasticsuite/src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml`.

Thanks for any help

**Comment by nikonratm** [comment]
Figured this one out =)
In my custom module:

`app/code/Vendor/ModuleName/view/frontend/layout/default.xml`:
```
<body>
    <referenceContainer name="header-wrapper">
        <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Vendor_Module::search/form.mini.phtml"/>
    </referenceContainer>
</body>
```

And then copy (and modify) the template `/vendor/smile/elasticsuite/src/module-elasticsuite-core/view/frontend/templates/search/form.mini.phtml` to `/app/code/Vendor/Module/view/frontend/templates/search/form.mini.phtml`

Also, to ensure loads in the right order, include in your 
`/app/code/Vendor/Module/etc/module.xml` file:
```
<module name="Vendor_Module" setup_version="1.0.0">
    <sequence>
        <module name="Smile_ElasticsuiteCore"/>\
    </sequence>
</module>
```

**Comment by webshopessentials** [comment]
@nikonratm, I suspect I have ran into a similar kind of problem as you described in this issue.
But with me the complete mini search form is not rendered at all.
The theme I am using is Ultimo by Infortis. It seems that they have moved many of the containers to another reference in `app/design/frontend/Infortis/base/Magento_Theme/layout/default.xml`:

```
<move element="header-wrapper"          destination="base-header-container" />
<move element="top.search"              destination="base-header-container" />
```
Would you please be so kind to tell me whether you have created your own separate custom module or have you included the code changes in the separate theme you are using?

**Comment by nikonratm** [comment]
I made my own custom module.

**Comment by webshopessentials** [comment]
@nikonratm, thank you for your swift reply. I tried the solution that worked out for you, but because of the theme setup it did not work out for me. I've submitted a new issue in case you are interested:
[https://github.com/Smile-SA/elasticsuite/issues/297](https://github.com/Smile-SA/elasticsuite/issues/297)

**Comment by tanolalano** [comment]
Hi, 
I'm able to display search form on Ultimo theme as suggesting @nikonratm with custom module.
The issue is that the search result only display search terms and are not clickable.
Any help to resolve?
Thank you

**Comment by mjamato714** [comment]
Hi @tanolalano,

I had the same issue recently when using Porto theme. My solution is described in this thread: https://github.com/Smile-SA/elasticsuite/issues/477 

The only difference for you may be your referenceContainer name depending on your theme/desired layout container. 

Hope this helps you!

**Comment by tanolalano** [comment]
@mjamato714 thanks for your support.
The issue solved by adding to my custom module some arguments that you add to your custom theme. 
So if someone has same issue is needed updating [FAQ](https://github.com/Smile-SA/elasticsuite/wiki/FAQ) for Ultimo theme.... 
in `app/code/Vendor/ModuleName/view/frontend/layout/default.xml` 
the full code to insert is:
````
<body>
    <referenceContainer name="header-wrapper">
        <block class="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete" name="top.search" as="topSearch" template="Davide_elasticpersonalizz::search/form.mini.phtml">
    	                   <arguments>
	                       <argument name="rendererList" xsi:type="array">
	                           <item name="term" xsi:type="array">
	                               <item name="title" xsi:type="string" translate="true">Search terms</item>
	                               <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
	                           </item>
	                       </argument>
	                   </arguments>
	   </block>
    </referenceContainer>
   		        <referenceBlock name="top.search">
		            <arguments>
		                <argument name="rendererList" xsi:type="array">
		                    <item name="product" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Products</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
		                    </item>
		                    <item name="category" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Categories</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
		                    </item>
		                    <item name="product_attribute" xsi:type="array">
		                        <item name="title" xsi:type="string" translate="true">Attributes</item>
		                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
		                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
		                    </item>
		                </argument>
		            </arguments>
		        </referenceBlock>
</body>
````
 So.. thank you another time @mjamato714

**Comment by mjamato714** [comment]
@tanolalano No problem! Glad this saved you some of the frustration I had with this problem. I agree that the FAQ should be updated in regards to including the search module on a custom theme. 

Enjoy elasticsuite, I am loving it!

**Comment by roman204** [comment]
dont forget to add the template to your custom layout and add the div="header-serach"
```
<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */

/**
 * Template for quick search mini form.
 * Overriden to manage template injection for the rendering of autocomplete results.
 *
 * @var $block \Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete
 */
?>

<?php
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */
                echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */
            echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */
                            echo __('Search'); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */
                               echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete",
                                "templates": <?php /* @noEscape */
                               echo $block->getJsonSuggestRenderers(); ?>,
                                "priceFormat" : <?php /* @noEscape */
                               echo $block->getJsonPriceFormat(); ?>}
                            }'
                               type="text"
                               name="<?php /* @escapeNotVerified */
                               echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */
                               echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */
                               echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               data-block="autocomplete-form"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */
                            echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
```

**Comment by deckside** [comment]
I have Magento 2.2 with Elasticsuite & Ultimo theme and I'm trying to get the search box to display while using both.

I have tried all the suggestions but I must be missing something.

I do not mind modifying the Ultimo theme, 

Any suggestions would be helpful.

**Comment by deckside** [comment]
Roman204 said 
dont forget to add the template to your custom layout and add the div="header-serach"

As Im new to Magento can someone let me know where this would be placed?

thank you

**Comment by ukomiljon** [comment]
Hello
We are facing the same issue. After installing Elasticsuite with Ultimo theme, the search box disappears. 
please, any suggestion.

**Comment by mjamato714** [comment]
@ukomiljon have you reviewed this thread along with the others relating to this issue? https://github.com/Smile-SA/elasticsuite/issues/477

**Comment by roman204** [comment]
maybe my [gist](https://gist.github.com/roman204/bce68bbf4be9db8538223559504f1f7d) would help some.
put that template file into: app/design/frontend/{cutom_theme_name}/Smile_ElasticsuiteCore/templates/search

**Comment by ukomiljon** [comment]
roman204. I tried this, it did not work.

**Comment by roman204** [comment]
this is also a change i did: [link](https://gist.github.com/roman204/557725b9aaf05986685959f4bd153c7b)
this file is here:
app/code/frontend/{custom_theme_vendor/{custom_theme_name}/Magento_Theme/layout/

**Comment by ukomiljon** [comment]
Hello

I did it also. Still there is no search box.

When it's deployed, it does not display custom theme.  it displays
Luma,  ultimo
themes.
It looks the custom theme is not deployed.
Is it anywhere i have to register to deploy the custom theme?

Bellow deployed results:

# bin/magento setup:static-content:deploy -f

Deploy using quick strategy
frontend/Magento/blank/en_US            0/2138
>-------------------frontend/Magento/blank/en_US            60/2138
     >-------------------frontend/Magento/blank/en_US            818/2138
          ==========>---------frontend/Magento/blank/en_US
1419/2138           ==================>-frontend/Magento/blank/en_US
    1599/2138           ====================frontend/Magento/blank/en_US
        2039/2138
 ====================frontend/Magento/blank/en_US            2041/2138
     ====================frontend/Magento/blank/en_US            2043/2138
         ====================frontend/Magento/blank/en_US
2044/2138           ====================frontend/Magento/blank/en_US
    2138/2138           ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/blank/en_US            2138/2138
 ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ====================frontend/Magento/blank/en_US            2138/2138
     ============================ 100% %  10 secs
adminhtml/Magento/backend/en_US         2140/2140
 ============================ 100% %  7 secs
frontend/Magento/luma/en_US             2154/2154
 ============================ 100% %  16 secs
frontend/Infortis/base/en_US            2259/2259
 ============================ 100% %  16 secs
frontend/Infortis/ultimo/en_US          2261/2261
 ============================ 100% %  6 secs

Execution time: 65.325731039047

**Comment by deckside** [comment]
Hi  ukomiljon

Did you run 

`
![image](https://user-images.githubusercontent.com/12390601/37991235-65726ed0-3254-11e8-937e-0c5a495c1dd3.png)
`

Before  

`
![image](https://user-images.githubusercontent.com/12390601/37991266-79f16f3c-3254-11e8-8ab2-46eb87dc1716.png)
`

**Comment by deckside** [comment]
Hi @roman204 

I have detailed everything I have tried at 
https://github.com/Smile-SA/elasticsuite/issues/477#issuecomment-376420735

If you have any ideas what I have done wrong it would be appreciated

Thanks

**Comment by deckside** [comment]
Solved:
Create file app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml

Paste content below:
```

<?php
/**
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
 * versions in the future.
 *
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCore
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
/**
 * Template for quick search mini form.
 * Overriden to manage template injection for the rendering of autocomplete results.
 *
 * @var $block \Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete
 * 
 * @modified by Darren Sutherland <darren@deckside.com> for use with Infortis Ultimo theme, only removed "Search" from echo as it did not fit well on screen.
 * Place this code in app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml
 *
 */
?>

<?php
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */
                echo __(''); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */
            echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?php /* @escapeNotVerified */
                            echo __(''); ?></span>
                    </label>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */
                               echo $block->getUrl('search/ajax/suggest'); ?>",
                                "destinationSelector":"#search_autocomplete",
                                "templates": <?php /* @noEscape */
                               echo $block->getJsonSuggestRenderers(); ?>,
                                "priceFormat" : <?php /* @noEscape */
                               echo $block->getJsonPriceFormat(); ?>}
                            }'
                               type="text"
                               name="<?php /* @escapeNotVerified */
                               echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */
                               echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Search entire store here...'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */
                               echo $helper->getMaxQueryLength(); ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               data-block="autocomplete-form"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */
                            echo __(''); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

```
Set permission for file, flush cache

**Comment by ukomiljon** [comment]
Hi guys, it works!.

After this:
Create file app/design/frontend/Infortis/base/Smile_ElasticsuiteCore/templates/search/form.mini.phtml
and paste the content. flush cache.

thank you very much to all. :)

**Comment by lasg125** [comment]
@deckside do you know if maybe this works with another theme? i am having the same issue with Etheme

**Comment by deckside** [comment]
I have no idea

if you have a test site you could give it a try.

But I would not try it on a live site

**Comment by ahsanaimer** [comment]
As per Magento documentation you need to put the layout file under "layout/override/base". Try this example ( tested on Magento ver. 2.3.5)

<theme_dir>/Smile_ElasticsuiteCatalog/layout/override/base/catalog_category_view_type_layered.xml

will override

vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/frontend/layout/catalog_category_view_type_layered.xml
