### ISSUE TITLE
Memory issue when a search suggest is executed

### ISSUE THREAD

**Issue by javimi93** [Smile-SA/elasticsuite#2723]
In our production environment, when a search/ajax/suggest/ call is placed, a memory issue is showed up.

### Preconditions
Magento Version : 2.4.5

ElasticSuite Version : 2.10.11

Environment : Magento cloud production environment
4G of PHP memory limit

### Steps to reproduce
1. Write on searcher search/ajax/suggest/ call is placed.

### Expected result
1. Getting suggest options and a 200 response

### Actual result
1. Getting no suggest options and a 500 response

This are the logs:
![image](https://user-images.githubusercontent.com/8806739/192791105-d8d4ef57-045c-4bdd-af57-0db1daf132eb.png)

**Comment by romainruaud** [comment]
Hi @javimi93 

Does this happen on every search query ? Do you have examples of a particular search query triggering this ?

How much synonyms do you have in the back-office ?

Regards

**Comment by javimi93** [comment]
Hi @romainruaud !

We have the error randomly on logs. Not always

Not so much: 7 thesaurus, with 10-15 synonyms each

**Comment by javimi93** [comment]
@romainruaud We tried to extend memory limit of php to 6GB but it doesn't work. 

We found that issue happened when we search a certain string.

We have also disabled synonyms and search expansions, (Both for avoiding to use getSynonymsRewrites function which is causing problem), and now memory issue is not there.

But no synonyms or search expansions working which is not a good final solution.

Could you give me a better one?

**Comment by romainruaud** [comment]
@javimi93 can you give us more details ? especially what is the "a certain string" ?

regards

**Comment by javimi93** [comment]
@romainruaud  I'm able to trigger the out of memory most of the time by search for "bre"

The word "breien" is the Dutch word for knitting so quite popular for our client.

I get a 503 for "bre" and "brei" but not for "br" and "breie"

**Comment by romainruaud** [comment]
Hello @javimi93 

is this word present in synonyms and thesaurus ? if yes, which ones ?

**Comment by javimi93** [comment]
@romainruaud I've look over the synonyms and the most similar are this ones:
![image](https://user-images.githubusercontent.com/8806739/195032503-057332a3-bd0a-41b3-bfac-76b0c8cd98af.png)

**Comment by romainruaud** [comment]
Hello @javimi93 

We've rewritten this part on the 2.10.x branch.

Are you able to test this branch locally ?

Regards

**Comment by romainruaud** [comment]
This has been fixed in 2.10.12.1 and confirmed working on live websites.

Regards
