### ISSUE TITLE
Cannot run ElasticSuite with Elastic Cloud

### ISSUE THREAD

**Issue by emogerov** [Smile-SA/elasticsuite#2725]
I have a problem running elastic suite.

I used composer require smile/elasticsuite ~2.10.0 on magento 2.4.2 instance with elasticsearch 7.13 version

I used [https://github.com/Smile-SA/elasticsuite/issues/1482](url) and setup everything but I still get the same error:

ElasticSuite Category Indexing index process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}

How can I fix this

**Comment by romainruaud** [comment]
the "analysis-phonetic" (and probably "analysis-icu") plugin is not installed on your Elasticsearch instance.

You need to install those plugins (and reboot the Elasticsearch server after).

Regards

**Comment by emogerov** [comment]
Here is image from my elastic cloud activity

![image](https://user-images.githubusercontent.com/27552933/193543296-4d867e33-768c-4402-996b-54b1a9fafd38.png)

and then i restarted the server:

![image](https://user-images.githubusercontent.com/27552933/193543472-9e179338-7281-40e8-b279-52883ed87b6e.png)
