### ISSUE TITLE
Hyvä Compatibility

### ISSUE THREAD

**Issue by maierb** [Smile-SA/elasticsuite#2728]
Are there plans to support Hyvä frontends with this module? Thanks!

**Comment by romainruaud** [comment]
There is no plan, we made it :)

https://hyva.io/blog/news/elasticsuite-hyva-partnership.html

> If you want to install ElasticSuite on your Hyvä Store, simply follow the [standard installation instructions for ElasticSuite](https://github.com/Smile-SA/elasticsuite). Then install the compatibility module (if you are an existing Hyvä customer) from composer (hyva-themes/magento2-smile-elasticsuite) or[ via our Gitlab](https://gitlab.hyva.io/hyva-themes/hyva-compat/magento2-smile-elasticsuite/).

Here is one of the first websites combining Hyvä and Elasticsuite : https://www.megadental.fr/

Regards
