### ISSUE TITLE
Missing "is one of" in virtual category rule ()

### ISSUE THREAD

**Issue by sheepfy** [Smile-SA/elasticsuite#2730]
So, I am forced to use "contains". (Smile 2.10.7 had "is one of" there)
Because of that, the elastic query is done in such way that brings me the similarities of the skus. 
Is intended to have a virtual category or widget with a specified list of skus that brings you more skus than you specified?

disabling these from ES virtual category module:
![image](https://user-images.githubusercontent.com/17467949/194272734-637182a6-2e5d-4933-aa32-e72ec45407dd.png)
will brings the "is one of" there and therefor, the skus in the virtual categories will be the exact ones that I have specified in the rule.

Steps:
Create 2 products with skus: TEST and TEST-2 (well in my case, SAW-ARI3-90Ni2-P-C, SAW-ARI3-90Ni2-CNP-P-C)
Create virtual category
Add rule "SKU contains "TEST" (in my case SAW-ARI3-90Ni2-P-C)

Expected result: Virtual category to have 1 product
Actual result: Virtual category have 2 products.

**Comment by romainruaud** [comment]
Hello @sheepfy 

Can you check that the fix in this PR solves your issue ? https://github.com/Smile-SA/elasticsuite/pull/2742

Regards
