### ISSUE TITLE
Maximum execution time of 360 seconds exceeded + 2.4.4 + PHP 8.1

### ISSUE THREAD

**Issue by davidandersson1** [Smile-SA/elasticsuite#2731]
Hello,

We are using magento versions 2.4.4 with [2.10.11] smile elasticsuite version with PHP 8.1 & MySQL 8.x.

We have noticed below error multiple time in php error log ( not magento error log) in server.

PHP Fatal error:  Maximum execution time of 360 seconds exceeded in vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Model/Index.php on line 377

We have around 400k products and 600+ categories with flat mode enabled. we are using some 3rd party Amasty modules as listed below
Amasty_ShopbyBrand
Amasty_SeoRichdata
Amasty_Gdpr
Amasty_SeoToolKit
Amasty_Meta
Amasty_Promo
Amasty_XmlSitemap

However sadly we do not know how to reproduce the error again.

So can you please guide us what we have to do here in order to investigate more or if you aware already with this issue then can you please help us here.

Thanks,
David Andersson

**Comment by vahonc** [comment]
Hello @davidandersson1,

How many thesaurus do you have?

BR,
Vadym

**Comment by davidandersson1** [comment]
HI @vahonc 

We are created 2 Thesaurus where one thesaurus with around 75~ Synonym terms and another one with only two Synonym terms. also we have 2 stores but these both Thesaurus for only main store.

Thanks,
David Andersson

**Comment by vahonc** [comment]
Hi @davidandersson1,

Have you changed smth in `ELASTICSUITE -> Search Relevance -> Thesaurus Configuration`? Can you provide the configuration as it's shown below screenshot?

![Screenshot from 2022-10-10 16-52-20](https://user-images.githubusercontent.com/67791361/194883419-5f484aa1-db4c-4f5d-b882-7d191b7c3bd6.png)

Also, if it's possible, please provide details or screenshots of one of your thesaurus (with around 75~ Synonym terms).

BR,
Vadym

**Comment by davidandersson1** [comment]
Hi @vahonc 

Please check attached both screenshot of configuration as you mentioned above.

![Screenshot from 2022-10-11 16-12-04](https://user-images.githubusercontent.com/49389320/195070731-30e92aad-a6c1-4468-b537-fa63ea15d219.png)
![Screenshot from 2022-10-11 16-17-01](https://user-images.githubusercontent.com/49389320/195070736-b2d54c05-c176-4a00-8670-ec622041f5a5.png)

Thanks,
David Andersson

**Comment by davidandersson1** [comment]
Hi @vahonc please let me know if any update for above issue.

**Comment by romainruaud** [comment]
Hi @davidandersson1 

we've refactored this part in the 2.10.x branch.

Can you give it a try (in local?) and tell me if this is better ?

Regards

**Comment by davidandersson1** [comment]
Hi @romainruaud thanks for your quick reply.

Can you please provide branch (2.10.x) URL or let me know how can I check 2.10.x branch?

Also as i informed above, yet we do not know how to reprouce the issue. if you aware then please provide some steps to reproduce.

**Comment by vahonc** [comment]
Hi @davidandersson1

> Can you please provide branch (2.10.x) URL or let me know how can I check 2.10.x branch?

To test this you can re-install the Elasticsuite with composer commands: `$ composer require smile/elasticsuite:2.10.x-dev`

Unfortunately, we were also not able to reproduce your problem exactly as you described, but we tried to take some steps that should help to avoid such problems.

BR,
Vadym

**Comment by romainruaud** [comment]
Btw this part has been revamped in 2.10.12, especially regarding performances.

Can you upgrade and give it a try ?

**Comment by davidandersson1** [comment]
Hi @romainruaud thanks for update, we will try and let you know the status.

**Comment by romainruaud** [comment]
I close, the revamp of thesaurus system has been tested successfully on live websites.

@davidandersson1 if you are still facing this issue, feel free to open a new bug report here.

Regards

**Comment by ankita-parashar-soni** [comment]
@davidandersson1 is this issue resolved for you.

**Comment by davidandersson1** [comment]
@ankita-parashar-soni atleast now issue is not appear in php error log after applied latest elasticusite version.
