### ISSUE TITLE
Disable quick lookup search box in layered navigation filters

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2732]
Hi,

I'm struggling several hours to remove the quick lookup search box in layered navigation filters.
Initially I thought this was by default in magento 2 but after a lot of hours searching I realized it's part of elasticsuite!
What I would like to have is the default behavior of magento2 where all the categories are shown at the same time. I don't need the search box and I don't need the show more / show less links.
So is this possible to configure it by an option in elasticsearch? I have spent several hours searching and trying without finding a solution!

**Comment by romainruaud** [comment]
https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration

The "facet max size" which is by default capped to 10 items will make appear the "Show more" for filters having more than 10 values.

If you don't want this, you can rise the "facet max size" of your attributes.

Regards

**Comment by cptX** [comment]
> https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration
> 
> The "facet max size" which is by default capped to 10 items will make appear the "Show more" for filters having more than 10 values.
> 
> If you don't want this, you can rise the "facet max size" of your attributes.
> 
> Regards

I had only 3 options in a category and still it was showing the search box and the show more. I'll check your suggestion.
