### ISSUE TITLE
Comma separated values for varchar Attributes with validate-numeric cannot be indexed

### ISSUE THREAD

**Issue by bosch-manuel** [Smile-SA/elasticsuite#2737]
It's stated in the documentation that a varchar attribute can be filtered using a slider, when it's input validation is set to validate-number (https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#using-sliders-for-custom-attributes).
This is true and working as expected.

"validate-numeric" allows to input comma separated values, not only dot separated. A german user might be tempted to place 200,51 instead of 200.51 into such an attribute. Saving works fine but when the catalog_product index gets updated,  a mapper_parsing_expection occurs. 
`[2022-10-11 12:50:27] main.ERROR: Bulk index operation failed 1 times in index magento2_default_catalog_product_20221011_115017 for type _doc. Error (mapper_parsing_exception) : failed to parse field [attr_413] of type [double] in document with id '49796'. Preview of field's value: '200,51'. Failed doc ids sample : 49796. [] []
`
This causes the affected products to be invisible in the storefront.

### Preconditions

Magento Version : Magento CE 2.4.3-p2

ElasticSuite Version : 2.10.11

Environment : production

Third party modules : -/-

### Steps to reproduce

1.Add varchar attrtibute with input validation "validate-number"
![attr_413](https://user-images.githubusercontent.com/3950460/195110593-be3cf2e8-09e5-42b9-839f-a0f79d403dbf.png)
2.Enter comma separated decimal value as attribute value for a product
![assignAttributeValue](https://user-images.githubusercontent.com/3950460/195111571-1cc524b6-b573-43bc-885c-936a33ccd636.png)
3. Reindex catalog_product index

### Expected result

Reindexing works fine and product can be found in storefront 

### Actual result

1. Reindexing the product fails, error in system.log
`[2022-10-11 12:50:27] main.ERROR: Bulk index operation failed 1 times in index magento2_default_catalog_product_20221011_115017 for type _doc. Error (mapper_parsing_exception) : failed to parse field [attr_413] of type [double] in document with id '49796'. Preview of field's value: '200,51'. Failed doc ids sample : 49796. [] []
`
2. Product cannot be found in storefront

**Comment by bosch-manuel** [comment]
Hi @vahonc,

sorry, I somehow messed up my log excerpts. I updated the issue.
It's about attr_413.

Here the remaining settings of the attribute:
![settings](https://user-images.githubusercontent.com/3950460/195527459-9fc37627-faff-4784-b70c-5be5bf2aee3d.png)
![settings2](https://user-images.githubusercontent.com/3950460/195527577-277f4442-d71c-42fb-a35e-91ab53d29a74.png)

**Comment by romainruaud** [comment]
As discussed, maybe we can add a test here : 

https://github.com/Smile-SA/elasticsuite/blob/d92bdf7275558bec2287932448154a5040955d1a/src/module-elasticsuite-catalog/Helper/AbstractAttribute.php#L349

something like `$this->getBackendType($attributeId) == 'decimal' || $this->getFrontendClass($attributeId) == 'validate-number'`

this means you'll have to implement a `getFrontendClass($attributeId)` method with caching mechanism, as for `getBackendType`

you'll also have to check what is the output of the floatval($value) when value is something like '250,52'. If this produces "250" that's acceptable but not perfect. If this produces an error or null, that will not make it.

Check what is indexed in Cerebro also after the process.

Regards

**Comment by bosch-manuel** [comment]
Hi @vahonc ,
sorry for my delayed response but I was on vacation.

I applied your commit in my local environment. Indexing the related product is working and it's also showing up in storefront.

Feels like an acceptable solution for this issue.

**Comment by romainruaud** [comment]
PR has been fixed, it will be part of next release, I close.
