### ISSUE TITLE
Catalogue Visibility not used in Autocomplete Results

### ISSUE THREAD

**Issue by paulpartington** [Smile-SA/elasticsuite#274]
**Pre Conditions**

Magento 2.1.3
Latest version of the ElasticSuite module from the 2.2.x branch
Autocomplete turned on

**Steps to Replicate**

* Set up a product with a visibility of 'Catalog'
* Type the product name

**Expected Results**

* The product should not be displayed in the autocomplete or the search results page

**Actual Results**

* The product is displayed in the autocomplete results but not on the search results page

 A quick fix seems to be possible by doing setVisibility(3, 4) in https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Autocomplete/Product/DataProvider.php#L126-L141

**Comment by afoucret** [comment]
The PR have been merged into the 2.3.x branch and the patch will be part of the upcoming 2.3.0 release.

Thx for reporting.
