### ISSUE TITLE
Difference in elasticsuite configuration interface

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2749]
I'm trying to solve a very important issue of elasticsearch not working when searching for a word without accents in Greek.
I have a test installation with sample data where elasticsearch gives the same results for accented and non accented words. This installation initially had this issue too and I was struggling for days to solve it. At some point it started working correctly, but unfortunately I don't know what solved the issue.
I now am creating the production site so I'm facing again the same issue with accented/non-accented. So I'm trying to copy all possible settings from the test implementation that works to the new production implementation. I don't know if this relates with the issue but the configuration interface of Elasticsuite is different in the two installations although both versions for magento and elasticsuite are the same! So can you please help me understand why there are these interface differences? If I understand this maybe it relates with the issue with the accents and I could solve this too!

this is from the working installation
![image](https://user-images.githubusercontent.com/9040042/196706729-af240c1e-6b0e-4333-9ed2-35c544ad876d.png)

and this from the non working installation (where the words without accents do not produce search results)
![image](https://user-images.githubusercontent.com/9040042/196707070-32ae7cfb-90be-47f6-a7a7-0f3a3ace7623.png)

I really am stuck, I cannot understand why they are different!

Magento ver. 2.4.5,  Elasticsuite ver. 2.10.11

**Comment by vahonc** [comment]
Hello @cptX

In the first screenshot, I notice some differences, looks like you are using some 3d party theme or modules **PORTO 4.0.3**, maybe you have some additional settings there. Also, I noticed under `ELASTICSUITE -> Autocomplete -> Product Autocomplete` additional fields like **Enable** and **Improve search** which as far as I know are not the legacy of our module.

You can also try to compare the settings of your catalog product indices, just go to `ELASTICSUITE -> Indices`, and on the `Action` column select **View settings** or provide them for us.

BR,
Vadym

**Comment by cptX** [comment]
> You can also try to compare the settings of your catalog product indices, just go to `ELASTICSUITE -> Indices`, and on the `Action` column select **View settings** or provide them for us.
> 
> BR, Vadym
Hi Vadym,

Where is ELASTICSUITE -> Indices, cannot find it!

**Comment by vahonc** [comment]
@cptX 

![Screenshot from 2022-10-21 13-02-21](https://user-images.githubusercontent.com/67791361/197171568-dd2a3818-49fe-4c9f-8d8c-b107e8304d2f.png)

![Screenshot from 2022-10-21 13-08-21](https://user-images.githubusercontent.com/67791361/197171577-77f181a0-79fa-4f1b-b8af-294086f2606f.png)

**Comment by cptX** [comment]
There is no such option in none of my setups!

![image](https://user-images.githubusercontent.com/9040042/197175009-20ba2931-5183-4833-8e7d-6edbe7f31be4.png)

**Comment by vahonc** [comment]
@cptX,

What version of ElasticSuite you are using?

Are you sure that ElasticSuite is properly installed and all modules are enabled?

BR,
Vadym

**Comment by cptX** [comment]
Hi @vahonc,
please check my versions:

curl localhost:9200
{
  "name" : "i7",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "nHqeqYFeQGmfwwScsY0hHg",
  "version" : {
    "number" : "7.17.6",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "f65e9d338dc1d07b642e14a27f338990148ee5b6",
    "build_date" : "2022-08-23T11:08:48.893373482Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

and in magento 

Magento ver. 2.4.5
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.12

According to your wiki looks like I have installed all the required plugins.

**Comment by cptX** [comment]
@vahonc

Tried to reinstall elasticsearch and elasticsuite. Followed all wikis for installing them in linux (linux mint 20.3)
Still none of my instances show the menu "Indices"

This what I get with your last curl command:

curl -X GET "localhost:9200/_cat/plugins?v=true&s=component&h=name,component,version,description&pretty"
name component         version description
i7   analysis-icu      7.17.6  The ICU Analysis plugin integrates the Lucene ICU module into Elasticsearch, adding ICU-related analysis components.
i7   analysis-phonetic 7.17.6  The Phonetic Analysis plugin integrates phonetic token filter analysis with elasticsearch.

**Comment by cptX** [comment]
@vahonc

I managed to make Indices available in menu. Module Smile_ElasticsuiteIndices was not enabled and in the wiki the instructions doesn't say to include it. In a production environment is it needed? What are the purpose of Indices? Is it only for debugging?

Can you please now guide me what can I check for finding the root cause of my problems is greek searching?

**Comment by romainruaud** [comment]
Can you post the index mapping and settings that you are able to fetch from the Indices module ?

Btw, this module is here to help for managing the Elasticsearch health, so it's definitely worth activating it in production as well.

Regards

**Comment by cptX** [comment]
A lot of strange things are happening with search at the moment in Greek!

Look this picture
![image](https://user-images.githubusercontent.com/9040042/197487296-cf23ac98-22fa-4403-849f-b0b326b868b3.png)

Autocomplete successfully finds the word "κόρνα" (with accent) but at the same moment seach can't find it , gives a message that "No exact results found for: 'κόρνα'." but still shows it succesfully in search results!

Now if I search for the word "κορνα" (without accent)
autosuggest give nothing at all!
search gives again the message "No exact results found for: 'κορνα'. The displayed items are the closest matches."
but shows the corresponding item!

![image](https://user-images.githubusercontent.com/9040042/197487840-a57cfa0a-a09c-45f9-b983-a1d78db970f2.png)

Really confusing situation and critical too!

**Comment by romainruaud** [comment]
I close this issue. I remain your other open here : https://github.com/Smile-SA/elasticsuite/issues/2762
