### ISSUE TITLE
Use of jQuery 3 deprecated event shorthands 

### ISSUE THREAD

**Issue by MartynasKasp** [Smile-SA/elasticsuite#2765]
### Preconditions
jQuery version: 3.6.0
Magento Version: 2.4.5-p1 OpenSource
ElasticSuite Version: latest (2.10.12.1)
Environment: Developer
Third party modules: -

### Steps to reproduce
Upgraded Magento version to 2.4.5-p1 which uses jQuery 3.6.0 (this version has some major changes and deprecations comparing to 1.12.4 which was used for previous Magento versions).
Opened category page on the storefront and got info log in console.

### Expected result
I expect this package not to use deprecated jQuery functions (therefore no errors in console).

### Actual result
![image](https://user-images.githubusercontent.com/33058459/198022742-ddd2fdf7-c6ff-4495-80f2-a7726216aab0.png)

This is not the only deprecated jQuery function still in use for this project! There are a lot more like: bind, isArray, focus, etc.

jQuery Migrate plugin warning messages doc: https://github.com/jquery/jquery-migrate/blob/main/warnings.md

**Comment by romainruaud** [comment]
Thank for signaling this @MartynasKasp 

That's something we'll fix in the future.

Regards

**Comment by smartexcan** [comment]
Just wanted to add on to this that jquery.touch-punch  should also be updated. Though the main repo isnt being updated anymore, there is a maintained fork available
https://github.com/RWAP/jquery-ui-touch-punch
