### ISSUE TITLE
2.4.5-p1 Search Slow - show_out_of_stock enabled

### ISSUE THREAD

**Issue by timpea** [Smile-SA/elasticsuite#2772]
When Show Out Of Stock products in enabled, search with ElasticSuite is very slow

### Preconditions
Magento Version : CE 2.4.5-p1
ElasticSuite Version : 2.10.12.1
Environment : Production

### Steps to reproduce

1. Configuration>Catalog>Inventory>Stock Options>Display Out Of Stock Products: YES
2. Slow search on front end

Same issue occurs using default ElasticSearch 7, the speed issue can be solved with this fix:
https://github.com/magento/magento2/issues/36375

With ElasticSuite enabled, the above fix does not affect the load speed and it is still extremely slow.

**Comment by vahonc** [comment]
Hello @timpea

How many products on your store?

BTW, displaying **Out Of Stock Products** it's a Magento native feature, therefore I'm not sure that the issue with slow search is ElasticSuite's fault. When we tested the compatibility of our module with Magento 2.4.5 we detected some problems with `Display Out Of Stock Products` when it was set to `YES`. And it looks like this issue occurred on the Magento side after implementing some breaking changes exactly in the 2.4.5 version.

On the GitHub of Magento, already exists a few issues are linked to this problem. For example, this [issue](https://github.com/magento/magento2/issues/36055). As you can see there are some fixes but they don't solve problems for all.

BR,
Vadym

**Comment by timpea** [comment]
Hi Vadym,

We have 17956 products, 11027 enabled.
2396 are out of stock.

Thank you, I have been following the Magento GitHub problems.   I was hoping you might have a clue for a temporary fix for the search speed.  I thought I had cracked it when I saw https://github.com/magento/magento2/issues/36375, but this didn't help with ElasticSuite.

The popup quick search is working fine.

Many Thanks
Tim

**Comment by romainruaud** [comment]
This is the original issue on Magento side : https://github.com/magento/magento2/issues/36055

And the associated fix : https://github.com/magento/magento2/pull/35986 (hello @Bashev !)

For me, this fix will not have an effect when using Elasticsuite.

There is also this issue that is still opened by their side : https://github.com/magento/inventory/issues/3360

I'll have a look about what we can do.

**Comment by timpea** [comment]
Perfect, just tested on our staging server and it has fixed the incorrect numbers of displayed products, and it has reduced the page load from 6sec to under 2sec.

**Comment by romainruaud** [comment]
Great, then I'll merge this, and maybe I'll tag a "minor minor" release because this bug is annoying for many people.

Regards
