### ISSUE TITLE
Support for Magento 2.4.5-p1 EE

### ISSUE THREAD

**Issue by rahulrj-eglobeits** [Smile-SA/elasticsuite#2776]
Hi Guys,
	One of our clients using the following Magento modules kindly go through the listed modules.
		
	ElasticsuiteAdminNotification	- 2.8.0 (Version)
	ElasticsuiteAnalytics		- 2.8.0 (Version)
	ElasticsuiteCatalog		        - 2.8.0 (Version)
	ElasticsuiteCatalogOptimizer	- 2.8.0 (Version)
	ElasticsuiteCatalogRule	        - 2.8.0 (Version)
	ElasticsuiteCore		        - 2.8.0 (Version)
	ElasticsuiteSwatches		- 2.8.0 (Version)
	ElasticsuiteThesaurus		- 2.8.0 (Version)
	ElasticsuiteTracker		        - 2.8.0 (Version)
	ElasticsuiteVirtualCategory	- 2.8.0 (Version)
	 
	 we are planning to upgrade the  "Magento 2.3.1 Enterprise Edition  " to " 2.4.5-p1 Enterprise Edition  ".  so, kindly let us know the compatibility of the above-listed modules with "Magento 2.4.5-p1 Enterprise Edition " .if not, guys do you  have any plan to release/develop a new version of the above modules or did you stop the updated version release for the above modules.

**Comment by vahonc** [comment]
Hello @rahulrj-eglobeits,

After upgrading Magento to the 2.4.5-p1 version you just need to upgrade/re-install ElasticSuite to the latest version (at this moment it's 2.10.12.1). This latest version is fully compatible with Magento 2.4.5-p1 version.

More info about which version should you use [here](https://github.com/Smile-SA/elasticsuite#%EF%B8%8F-magento-versions-compatibility-).

BR,
Vadym

**Comment by romainruaud** [comment]
Close as it's been answered.
