### ISSUE TITLE
Escaped <style> tags in JSON break the content on the page

### ISSUE THREAD

**Issue by zhovnirigor** [Smile-SA/elasticsuite#2777]
### Preconditions

Magento Version : 2.4.4, 2.4.5-p1

Third party modules : doesn't matter

### Steps to reproduce

These are the test steps fully equivalent to the real page content.
1. Enabled Breeze experience for the current theme.
2. In \Swissup\Breeze\Plugin\ViewResultPage::afterRenderResult before `$html = $this->filter->process($html);` assign the test content from the attached (bottom of the page) initial.html as a value to the `$html` variable.
3. Load any (since we have replaced the content) PDP/PLP/CMS page.

### Expected result

1. Take a look at the top of the `<head>` tag. Script tag is there. Look at the `<body>` - non-script content is properly rendered there. HTML tags for the test content are properly opened and closed (see expected.html)

### Actual result

1. Take a look at the top of the `<head>` tag. Some tags in the test content are incorrectly closed (see actual.html).

### Suggested solution:
In \Swissup\Breeze\Model\Filter::escapeNestedHtmlTags `$patterns` should be replaced by a single pattern `/<(style|script)\b[^>]*>(.*?)<\/\1>/is`; `$matches[1]` should be replaced by `$matches[2]`.

### Explanation
When the page content contains some JSON-escaped `<style>` or `<script>` tags, corresponding closing escaped `<\/style>` or `<\/script>` tag doesn't match the patterns from \Swissup\Breeze\Model\Filter::escapeNestedHtmlTags. It will match the nearest closing `</style>` or `</script>` which leads to the unexpected behavior and broken content.
[files.zip](https://github.com/Smile-SA/elasticsuite/files/9990854/files.zip)

**Comment by romainruaud** [comment]
Hi @zhovnirigor 

this is not Swissup\Breeze repository here :)

I don't understand how Elasticsuite could help you on that.

Regards

**Comment by zhovnirigor** [comment]
Oh god, I knew hundreds of tabs will mix me up one day! Sorry man :D
