### ISSUE TITLE
Wrong url when removing a filter when multiple filters are enabled on Catalog Search Page

### ISSUE THREAD

**Issue by alainvdzanden** [Smile-SA/elasticsuite#2780]
### Preconditions

Magento Version : 2.4.5-p1

ElasticSuite Version : 2.10.12.1

Environment : Developer & production mode

Third party modules : -

### Steps to reproduce
1. Go to a catalog search page with multiple filters enabled (example: https://www.sanidirect.nl/catalogsearch/result/index/?q=hoek&brand%5B0%5D=Saniselect&colorname%5B0%5D=Wit)
2. Try to remove one of the multiple filters (example: remove filter "Commerciële Kleurnaam: Wit")
<img width="879" alt="Screenshot 2022-11-13 at 20 53 10" src="https://user-images.githubusercontent.com/111735645/201541499-ec7b1e1b-1c75-46b5-af1d-e0bfd54b30a3.png">

### Expected result

1. Filter should be removed from the current filters (example expected url: https://www.sanidirect.nl/catalogsearch/result/index/?q=hoek&brand%5B0%5D=Saniselect)

### Actual result

1. New url is incorrect and redirects to previous page (example wrong url: https://www.sanidirect.nl/catalogsearch/result/index/?brand%5B0%5D=Saniselect&amp;q=hoek)

As you can see in the example, the url is generated incorrectly, which means you are redirected to the current page

**Comment by vahonc** [comment]
Hello @alainvdzanden 

I was not able to reproduce your issue on my test environment with fresh Magento 2.4.5-p1 (default sample data) and ElasticSuite 2.10.12.1.

Here's my scenario with screenshots:

So, I tried to search "watch" and after getting some results I added two filters **Activity** and **Gender**. As you can see I got three items.

![Screenshot from 2022-11-14 18-38-34](https://user-images.githubusercontent.com/67791361/201717269-9ed280d0-8efb-48d2-b8bb-f9071a6b4904.png)

Then I removed **Gender** filter and as result, I got 5 items. And all was as I expected and without any redirection to the current page.

![Screenshot from 2022-11-14 18-40-05](https://user-images.githubusercontent.com/67791361/201717690-88917616-5a6d-4e4a-b8c9-09f762d4bb0e.png)

What is also strange for me is that provide by you URL is different from what I have on my test environment

http://localhost:8086/catalogsearch/result/index/?activity=Athletic&gender=Men&q=watch

It looks like on your environment you have installed some 3rd party modules or made some additional customization or maybe your custom theme has some additional settings.

You can try to check your 3rd party modules and switch to the default Magento theme (Luma) on your developer env and check your issue again.

BR,
Vadym

**Comment by alainvdzanden** [comment]
Hi @vahonc ,

Thanks for your feedback!
I will do some more research/debugging and will update this issue asap.
