### ISSUE TITLE
Layered Navigation : Multiple filter selection of single attribute not showing products 

### ISSUE THREAD

**Issue by prernagupta85** [Smile-SA/elasticsuite#2782]
Hi,

Below are the details of the storefront
Elasticsuite Catalog 
Mageplaza Layered Navigation : 1.0.5
Magento2 : 2.4.3-p1

**Issue** : While selecting multiple filter from a single attribute "Product Brand" It is not showing the product collection on the listing page. 

**More Details** : As we came to know that Elasticsuite Catalog also provides its layered navigation, we were also using Mageplaza Layered Navigation. So there is a conflict between the two modules. Is there any fix that can be done so that we can continue using Mageplaza for its Layered Navigation. We cannot disable Elasticsuite Catalog but we can make changes to solve the conflicting behaviour. Please guide.

**Comment by vahonc** [comment]
Hello @prernagupta85

It's unlikely that our module and another one working on the same area (layered navigation) will function correctly. Compatibility with third-party modules is out of the scope of our Open Source support policy provided here, there is not much we can do for your issue. So, you'll have to make a choice, or resolve these conflicts by yourself (by coding).

If you are interested in dedicated (paid) support through professional services, please send a mail to elasticsuite@smile.fr

BR,
Vadym

**Comment by romainruaud** [comment]
@vahonc is right, this is out of the scope of our open source support policy.

I close therefore.
