### ISSUE TITLE
Optimizer based on attribute only work with special_price

### ISSUE THREAD

**Issue by supportA3WEB** [Smile-SA/elasticsuite#2792]
When we want to create an optimizer based on a specific attribute in our admin : price, we can't select attribute. Only one is loaded in the attribute list : special price

### Preconditions

Magento Version : 2.3.6-p1
ElasticSuite Version :2.9.13
Environment : Production Mode

### Steps to reproduce
1. Go to magento 2 admin
2. Select Elasticsuite > Optimizer > Add an optimizer
3. Go on the "model" field and select "Based on attribute value"
4. Open attributes list below 

### Expected result
1. Will show a lot of numeric attribute like cost, special price, tier price etc... 

### Actual result

1. Show only one attribute : special price. 
![image](https://user-images.githubusercontent.com/10046331/204554102-5b7c81da-9894-492c-adb4-47c27c481eeb.png)

**Comment by vahonc** [comment]
Hello @supportA3WEB,

If I'm not mistaken, in order to be able to select your attribute in the **Based on attribute value** select box in that attribute's configuration, the `Use for Promotion Rule Conditions` option needs to be set to `Yes`.

BR,
Vadym

**Comment by supportA3WEB** [comment]
Hello @vahonc,
Yes, I tried this, but for the "price" attribute it's not working.

**Comment by romainruaud** [comment]
This cannot work for price due to the fact it's a nested field in Elasticsearch.

Nested fields are explicitely removed here : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-optimizer/Model/ResourceModel/Optimizer/Config/Attributes/Collection.php#L116

Regards
