### ISSUE TITLE
Redirect error after changing number of product per page on the last page of a listing

### ISSUE THREAD

**Issue by Dam62** [Smile-SA/elasticsuite#280]
Hello,

Our client found a small error in the product listing 

1 - Go on a product listing
2 - Go on the last page with the pager
3 - Change the number of product to display with a higher number (for example 20 to 40)

With a native Magento, the user is redirected to the last page of the listing (the last page is not the same : there are more products per page so there are less pages).
With Elasticsuite, we stay on the same page with a notice indicating that no product can be displayed .

Thanks in advance

**Comment by romainruaud** [comment]
Hello @Dam62 and thank you for submitting this issue.

I tested it on my own, and you are right, a native Magento belongs as you said.

We'll look at this one,

thank you for reporting it.

**Comment by romainruaud** [comment]
Pr have been merged.

You can wait for the next stable release or use the 2.3.x branch for now if you cannot wait.

Feel free to reopen the issue if needed.

Best regards,
