### ISSUE TITLE
Enabling minification in production mode throws a javascript error in admin panel

### ISSUE THREAD

**Issue by passtet** [Smile-SA/elasticsuite#2805]
Enabling minification in production mode throws a javascript error in admin panel
```
Constr is not a constructor TypeError: Constr is not a consructor
```

### Preconditions

Enable minification at `dev/js/minify_files` and production mode

Magento Version : 2.4.5-p1

ElasticSuite Version : 2.10.12.1

Environment : production

Third party modules :

### Steps to reproduce

1. Open admin panel
2. Login
3. Open dev tools in browser

### Expected result

1. No error

### Actual result

1. 
![image](https://user-images.githubusercontent.com/5439132/208721015-2ae7d41a-8a5f-405e-8c0e-f47326530b63.png)

When blocking URL using chrome dev tools `/static/adminhtml/Magento/spectrum/en_US/Smile_ElasticsuiteTracker/js/modal/component.min.js` all works as expected
The strange content at the top of the JS appears with minification only:
![image](https://user-images.githubusercontent.com/5439132/208721784-e2dc4ec7-46bc-4f50-9e3f-60a242b400fc.png)

**Comment by vahonc** [comment]
Hello @passtet,

I was not able to reproduce your issue on my test environment with fresh Magento 2.4.5-p1 CE/EE (with default sample data) and ElasticSuite 2.10.12.1.

After enabling JS minification in Magento BO:

![Screenshot from 2022-12-23 18-56-40](https://user-images.githubusercontent.com/67791361/209535020-4ebc80bc-4c9f-49fd-a9e3-d315e233985b.png)

I switched my test environment to production mode and I didn't notice any errors in the dev tools of the browser that could be related to your issue.

![Screenshot from 2022-12-23 19-27-21](https://user-images.githubusercontent.com/67791361/209535043-2bb6d19e-f9ff-4bf3-980d-e4b3a18946db.png)

Therefore, please provide more details about where exactly you noticed this issue.

BR,
Vadym
