### ISSUE TITLE
Categories are not saving after enable Smile_ElasticsuiteVirtualCategory

### ISSUE THREAD

**Issue by manishgoswamig** [Smile-SA/elasticsuite#2806]
### Preconditions

Magento Version : Magento 2.4.4-p2 EE

ElasticSuite Version : 2.10.10

Environment : Developer mode

Third party modules : NO 

### Steps to reproduce

1. Please enable Smile_ElasticsuiteVirtualCategory 
2. Go to admin category and save any category and we will face the issue with below message 

Error Message :  

A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later.

![Screenshot from 2022-12-21 19-06-49](https://user-images.githubusercontent.com/46725562/208918192-5546ce7a-c828-48b7-8251-8aa4f1960544.png)

### Expected result

1. Category should save without any error.

**Comment by vahonc** [comment]
Hello @manishgoswamig

I was not able to reproduce your issue on my test environment with Magento 2.4.4-p2 EE and ElasticSuite 2.10.10. 
All categories are saving as expected without any errors.

By the way, on your screenshot I see a few warning messages, one of them about that you are using a Demo store. Is this mean that it's not a real environment or it has some restrictions? Have you tried to install ElasticSuite on the real or local environment?

Also, you should check Magento logs, maybe the is some error/explanation that occurs your issue.

BR,
Vadym
