### ISSUE TITLE
illegal_argument_exception OpenSearch  - Magento 2.4.5-p1 

### ISSUE THREAD

**Issue by BeardTech** [Smile-SA/elasticsuite#2808]
Open search error appear in log, about the type of stored datas.. Append for me for entity_id.

`{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [entity_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "magento2_mystore_catalog_category_20221221_031227",
        "node": "jFgagn_IQJKKNqXn7tJ8mA",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [entity_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [entity_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [entity_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    }
  },
  "status": 400
}`
### Preconditions
Magento Cloud

Magento Version : EE 2.4.5-p1 

OpenSearch : Version 1.2.4

ElasticSuite Version : Open Source ver. 2.10.x-dev

Environment : Production

### Steps to reproduce
1. Navigate to category
2. Error appear in logs

**Comment by vahonc** [comment]
Hello @BeardTech,

Could you add more details about what exactly you want to achieve and what data you tried to add to entity_id? It's a custom attribute or system attribute and you just want to add some additional data to the aggregation?

What about a stack trace on the frontend? Have you noticed some errors or behavior that you not expected to see?

Also, provide us with your category index mapping. 

BR,
Vadym

**Comment by kaplansin** [comment]
```
{
    "attribute": {
        ....
        "frontend_input": "text",
        "backend_type": "varchar",
        "is_filterable": true,
        "frontend_class": "validate-number"
        .....
    }
}

```

Create a filterable, text  attribute with frontend_class : "validate-number"
navigate to a category generated query will have following records in aggregations 

```
"aggregations": {
  ...
  ...
 
  "test_attribute": {
          "terms": {
                "field": "test_attribute",
                "size": 5,
                "order": {
                    "_count": "desc"
                }
            }
        },
       "other_attribute": {
            "terms": {
                "field": "other_attribute.untouched",
                "size": 5,
                "order": {
                    "_count": "desc"
                }
            }
        },
````
  
While running the query related exception will be thrown

**Comment by rbayet** [comment]
Hello @kaplansin,

Please open a distinct issue where you will be able to give us more context.

I'm pretty sure that your issue is slightly different since you're working with attributes while the initial author of this issue was trying to build an aggregation on a "static" index field.

Regards,
