### ISSUE TITLE
http://demo.magento-elastic-suite.io/ is down

### ISSUE THREAD

**Issue by yutv** [Smile-SA/elasticsuite#2813]
Go to http://demo.magento-elastic-suite.io/

**Actual Result:** 
![image](https://user-images.githubusercontent.com/1616522/210513011-0f6a3ce0-78c2-4087-b325-dc8258a7111b.png)

**Expected Result:** Default Magento + Elasticsuite.

**Comment by romainruaud** [comment]
Hi @yutv 

yes we are in the process of moving this server and are running into some internal issues. 

We're working on it.

Regards

**Comment by romainruaud** [comment]
Up and running again.

Regards
