### ISSUE TITLE
Category display all product instead of only affected

### ISSUE THREAD

**Issue by brmor-mistermenuiserie** [Smile-SA/elasticsuite#2817]
### Preconditions

Magento Version : 2.4.5-p1
ElasticSuite Version : 2.10.x-dev
Environment : Production

### Steps to reproduce

No idea for reproduce errors

### Expected result

Only display product affected to category

### Actual result

We have category with all parent category display

We don't understand this error, sometimes it works and sometimes not, we think than category page is cached with all products because clear cache and its good.
We encounter this error only on production environment

We check elasticsuite logs and Magento 2 logs we have only this error : 

![image](https://user-images.githubusercontent.com/103111614/211329219-334a4c67-7654-4ade-b506-fe12e4fcb7db.png)

Also we don't understand why the router (\Smile\ElasticsuiteVirtualCategory\Controller\Router::match) is called only for cms page, on categories and virtual categories it not called ?

**Comment by vahonc** [comment]
Hello @brmor-mistermenuiserie,

We didn't receive such reports from our clients, and in general everything should work as expected. So it's probably something specific to your environment.

Are you sure that you don't have any 3rd-party extensions or customization that could affect this issue?

>Also we don't understand why the router (\Smile\ElasticsuiteVirtualCategory\Controller\Router::match) is called only for cms page, on categories and virtual categories it not called ?

As for that, no, this router should be calling from everywhere. Why do you think it's not?

BR,
Vadym

**Comment by brmor-mistermenuiserie** [comment]
Hello @vahonc 

I reproduce this bug.
Indeed this bug seems to be due to crawler bingbot and also Display catalog Filter to No

![image](https://user-images.githubusercontent.com/103111614/212754153-eaf93637-c3b4-4bb4-92e5-ffad393f7d79.png)

I check access logs and I see than bingbot crawl any urls like : 
catalog/navigation_filter/ajax/id/XXX/?cat=XXX&d=&filterName=filtre_battant_forme (seems to be url for "show more" on filters)

When display catalog filter to no, categories is not filtered on search query so all products enable are retrieve.

Step to reproduce :
- flush cache: bin/magento cache:flush
- go to url like : 
catalog/navigation_filter/ajax/id/XXX/?cat=XXX&d=&filterName=filtre_battant_forme
- go to categorie url about id/XXX

I also find an error on function loadUsingCache (\Smile\ElasticsuiteVirtualCategory\Helper\Rule::loadUsingCache:74)
$data = $this->cache->load($cacheKey); return null.
So we can't passed in if ($data === false) line 74

**Comment by romainruaud** [comment]
Issue #2829 has been fixed. I close this one as well.

Feel free to open a new issue if that's still occuring.

regards
