### ISSUE TITLE
Magento 2.4.6 compatibility

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#2818]
Magento 2.4.6-beta1 is available for partners.

Let's make Elasticsuite compatible with it !

https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-6.html

https://developer-stage.adobe.com/commerce/php/development/backward-incompatible-changes/highlights/#246-beta

Notable changes : 

- Removal of "Zend_*" libraries
- Support of Elasticsearch 8 (and OpenSearch 2)

High probability to release a 2.11 branch considering all those backward incompatible changes.

**Comment by hostep** [comment]
Confirming that fixes are needed for Magento 2.4.6, tried Elasticsuite on 2.4.6-beta1 and the `indexer:reindex` command already gives following errors:

```
...
Catalog Search index process error during indexation process:
Class "Zend_Date" not found
ElasticSuite Category Indexing index process error during indexation process:
Class "Zend_Date" not found
Elasticsuite Cms Page Indexing index process error during indexation process:
Class "Zend_Date" not found
ElasticSuite Thesaurus Indexing index process error during indexation process:
Class "Zend_Date" not found
```


Thanks for the effort you guys put in here!

**Comment by justinconabree** [comment]
Hey @romainruaud ,

Is this in progress by anyone? I can jump onto it if needed.

Thanks!

**Comment by vahonc** [comment]
Hello @justinconabree,

Yes, we are working on it.

BR,
Vadym

**Comment by romainruaud** [comment]
Hi everybody, I confirm that @vahonc is taking care of this actually, we're investigating on the replacement of Zend_Date by legacy PHP Date object, which is not that easy because we rely on a pure "Zend" date pattern when naming our indices, so we also have to take car about backward-compatibility on this topic.

That being said, once we unlock this first step, there will probably be a lot more of other "Zend related" pieces of code to refactor, and probably many other Magento shenanigans that might be quite time consuming, so as we strongly believe in Open Source and have faith in our community, do not hesitate to also contribute on this @justinconabree .

Best regards

**Comment by romainruaud** [comment]
The master branch contains everything needed for Magento 2.4.6 : 

- PHP 8.2 compatibility
- Elasticsearch 8 compatibility
- Opensearch 2 compatibility

We are in the process of finalizing our tests on this by reviewing manually our test cases.

We will create a new 2.11.x branch and tag a 2.11.0 after the Magento release.

There will probably be some days of delays, however, because we know that the current 2.4.6 tag from Magento might be different of the final 2.4.6 tag. Yes I know this is bad practice from them but they did this for past releases... so we'll try to be cautious this time.

**Comment by romainruaud** [comment]
You can test the master branch if you want btw.

**Comment by ssx** [comment]
@romainruaud excellent, happy to be a test bunny for you 🙂

**Comment by hostep** [comment]
> ... because we know that the current 2.4.6 tag from Magento might be different of the final 2.4.6 tag. Yes I know this is bad practice from them but they did this for past releases... so we'll try to be cautious this time.

As far as I know this has never happened before, do you have some evidence to back up this statement? A tagged pre-release is always 100% the same as the final release. If a serious bug is still found in the pre-release, they tag a new version (this happened in the case of Magento 2.3.5 for example, where there was a 2.3.5-p1 with a bugfix at the same time when 2.3.5 was launched, see the second box on [this page](https://devdocs.magento.com/guides/v2.3/release-notes/release-notes-2-3-5-commerce.html))

**Comment by romainruaud** [comment]
Maybe I'm a bit peremptory, and you're right, I've no evidence of this, I just remember we had issues with a previous release that was available previously privately, but ended up being different once made public.

That being said, you can actually install a 2.4.6 open-source or commerce (as we did for testing), but the tag does not exists in there : https://github.com/magento/magento2/tags . It only exists on private packagist.

So question is : what will they tag on the release date, will they tag something on github, or sync the tag from some private repo where they did tag previously for the private packagist ? Will they overwrite the existing tag ?

In french we say "quand c'est flou, il y a un loup" (_when it's blurry there's a wolf_), so I prefer losing a bit of time to double-check :)

**Comment by hostep** [comment]
As far as I know, the tagged version on repo.magento.com that currently exists in pre-release will just remain the same one and opened up to all users. Instead of only the users with pre-release access.
As far as github goes, I would assume that they push the tag when the version is public for everyone and it should hopefully match what they published via repo.magento.com.

But take your time to double check if you want, no pressure from me, it was more meant as an informational message.

**Comment by leonhelmus** [comment]
@romainruaud  Thanks we'll be testing it as well. I will make sure that the results will be shared here :). Thank you for making it compatible!

**Comment by hostep** [comment]
It should be the same tag as what we had access to during pre-release indeed.

They don't push everything to github yet before GA because of the security fixes that are included, they don't want to publish these openly before GA as that would give info to the bad guys before the good guys are able to update their shops.

I agree it's a mess, but what can we do ... As long as we know that the tag in pre-release is the same one as the GA release I'm happy 🙂
