### ISSUE TITLE
500 Error/Timeout/Memory Limit On Update to 2.4.5 & Elasticsuite 2.10.12 From Magento 2.3.2 & Elasticsuite 2.8

### ISSUE THREAD

**Issue by gusdemayo** [Smile-SA/elasticsuite#2824]
**Is your question related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Ex :
We are updating from Magento 2.3.2 & Elasticsuite 2.8 to Magento 2.4.5 & Elasticsuite 2.10.2.1. We have a very large catalog - around 500,000 products - but things work fine on 2.3.2 and 2.8. When we update to 2.4.5 & 2.10.2.1, we see 500 errors relating to significantly increased memory usage, and timeouts. When we increase the PHP memory limit to like 3GB & remove the timeout limit, it takes around 5 minutes for the search to complete.

Our elasticsearch server has a heap max of 7.8GB

**Additional context**
Add any other context or screenshots about your question here.

**Comment by romainruaud** [comment]
Hi @gusdemayo 

500.000 products is large, but we have customers with millions of products and they do not face any issue.

Can you please give more details ?

Which page is slow ? The catalogsearch/result/index ? (ie the search result page)

If you enable Magento profiler, which line is causing the memory consumption ?

Regards

**Comment by gusdemayo** [comment]
It's the catalogsearch/result/index page, the profiler doesn't seem to show anything about specific lines.

**Comment by gusdemayo** [comment]
It appears we have 1 virtual category

**Comment by gusdemayo** [comment]
Doing a little troubleshooting I find that in vendor/magento/module-catalog-search/Controller/Result/Index.php the line around when the issue gets triggered is

```
$this->_view->loadLayout($handles);
```

I don't know if that at all narrows anything down

**Comment by romainruaud** [comment]
nope, because layout will then load anything.

Can you post your profiler table ?

**Comment by gusdemayo** [comment]
Yes, we got

cache_frontend_create,0.005668,0.002834,2,"68,800",0
cache_load,0.002866,0.000717,4,"1,072,960","2,097,152"
cache_save,0.005768,0.002884,2,-112,0
magento,5.472886,5.472886,1,"1,039,368","2,097,152"
magento->cache_frontend_create,0.000437,0.000219,2,"18,200",0
magento->cache_save,0.001114,0.001114,1,-16,0

**Comment by romainruaud** [comment]
Hi,

this is not a complete profiling, you're supposed to see a lot of things inside the "magento" call.

![image](https://user-images.githubusercontent.com/15340849/213112357-39757e60-701e-4139-96e1-c78f26fdab9e.png)

**Comment by gusdemayo** [comment]
It looks like the biggest memory use by far is here
![loadentities](https://user-images.githubusercontent.com/72032719/213224859-c1b005c6-ec2c-4bd9-9f36-bf101d25d6c9.png)

**Comment by gusdemayo** [comment]
I know our number of products isn't abnormal, but are there any tables or anything related to the catalog that could bog down loading?

**Comment by gusdemayo** [comment]
Upon some digging we see the 2 queries under the load_entities taking the most time & resources are

```
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier _price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_ index`.`max_price`, `price_index`.`tier_price`, IFNULL(review_summary.reviews_count, 0) AS `reviews_count`, IFNULL(review_summary.rating_summary, 0) AS `rating_summary`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e` INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index .website_id = '1' INNER JOIN `catalog_product_website` AS `product_website` ON product_website.product_id = e.entity_id AND product_website.website_id = 1 LEFT JOIN `review_entity_summary` AS `review_summary` ON e.entity_id = review_summary.entity_pk_value AND review_summary.store_id = 1 AND review_summa ry.entity_type = (SELECT `review_entity`.`entity_id` FROM `review_entity` WHERE (entity_code = 'product')) LEFT JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id WHERE ((e.entity_id IN (0))) AND (e.c reated_in <= 1) AND (e.updated_in > 1) ORDER BY FIELD(e.entity_id,0)
```

and

```
SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `stock_status_index`.`stock_status` AS `is_salable` F ROM `catalog_product_entity` AS `e` INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.category_ id=1243 LEFT JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id WHERE (e.created_in <= 1) AND (e.upda ted_in > 1)
```

**Comment by gusdemayo** [comment]
I upped our memory limit to 8GB & set my /etc/hosts to point directly to our testing server so as to get around a cloudflare timeout issue we have - and the search will eventually complete, it's just really slow.

In our profiler it showed 

this `vendor/smile/elasticsuite/src/module-elasticsuite-tracker/view/frontend/templates//variables/page.phtml`

taking the most time, but disabling the tracker module didn't change the issue happening, so that may be a red herring.

**Comment by romainruaud** [comment]
````WHERE ((e.entity_id IN (0)))````

You're likely loading nothing, or your whole catalog (I tend to think that's what happens there).

Can you enable Elasticsuite Debug Mode and check the Elasticsearch query in your system.log file ?

Also, can you check what do you have around there lines : 

https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php#L527

And please provide a list of third-party modules you are using on your project.

This issue is likely project-specific.

**Comment by gusdemayo** [comment]
The elasticsearch query one particular search gives us is

curl -XPOST 'http://elasticsearch-staging.midlandsci.com:80/magento2_default_catalog_product/_search?pretty=true' -H 'Content-Type: application/json' -d '{"size":10,"sort":[{"relevance":{"order":"asc","missing":"_last","unmapped_type":"keyword"}},{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"keyword"}}],"from":0,"query":{"function_score":{"score_mode":"multiply","boost_mode":"multiply","functions":[{"field_value_factor":{"field":"p21_times_sold","factor":0.001,"modifier":"none","missing":1000.0},"filter":{"bool":{"must":[{"terms":{"attribute_set_id":["4"],"boost":1}}],"must_not":[],"should":[],"boost":1}}},{"field_value_factor":{"field":"p21_times_sold","factor":0.0001,"modifier":"none","missing":10000.0},"filter":{"bool":{"must":[{"bool":{"must_not":[{"terms":{"attribute_set_id":["4"],"boost":1}}],"boost":1}}],"must_not":[],"should":[],"boost":1}}},{"weight":2.0,"filter":{"bool":{"must":[{"terms":{"attribute_set_id":["4"],"boost":1}}],"must_not":[],"should":[],"boost":1}}}],"query":{"bool":{"filter":{"bool":{"must":[{"terms":{"visibility":[3,4],"boost":1}},{"bool":{"must_not":[{"terms":{"sku":["492010","530946","492003","531685","492020","531711","532790","492031","492017","530947","492026","530948","565636","492016","531808","492023","531706","492021","531707","497383","530957","492029","531809","531710","492000","531812","492002","531708","531709","564306","492009","556570","506064","532791","526884","531834","497114","531814","530959","565641","566436","497379","530960","530987","582575","531777","581018","497380","530961","497381","492019","530963","497685","530964","492014","544583","552620","552612","551349","551353","583018","557086","557091","557093","575810","575812","576278","576279","560921","560995","560994","561141","561142","561148","561150","561513","564307","571108","572562","569913","569771","552730","552729","566637","565640","531807","530958","492022","497116","531813","492012","492007","497115","526878","492028","531684","531233","497382","510852","530962","530965"],"boost":1}}],"boost":1}},{"terms":{"visibility":[3,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"must":{"bool":{"must":[],"must_not":[],"should":[{"multi_match":{"query":"bobby","fields":["spelling.whitespace^10","keyword_category.whitespace^50000000","keyword_01.whitespace^80000","keyword_02.whitespace^80000","keyword_03.whitespace^80000","p21_item_id.whitespace^5000000","keyword_brand.whitespace^500"],"minimum_should_match":"100%","tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15,"fuzziness":"AUTO","prefix_length":1,"max_expansions":10}},{"multi_match":{"query":"bobby","fields":["spelling.phonetic^1"],"minimum_should_match":"100%","tie_breaker":1.0,"boost":1,"type":"best_fields","cutoff_frequency":0.15}}],"minimum_should_match":1,"boost":1}},"boost":1}}}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":100000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":100000,"order":{"_count":"desc"}}},"categories":{"filters":{"filters":{"1244":{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"bool":{"must_not":[{"term":{"category.is_virtual":{"value":true,"boost":1}}}],"boost":1}},{"terms":{"category.category_id":["1244"],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"5367":{"bool":{"must":[{"terms":{"deadstock":["1000"],"boost":1}},{"bool":{"must":[{"bool":{"must_not":[{"terms":{"attribute_set_id":["4"],"boost":1}}],"boost":1}}],"must_not":[],"should":[],"boost":1}}],"must_not":[],"should":[],"boost":1}}}}},"keyword_category":{"terms":{"field":"keyword_category.untouched","size":7,"order":{"_count":"desc"}}},"keyword_brand":{"terms":{"field":"keyword_brand.untouched","size":7,"order":{"_count":"desc"}}}},"track_total_hits":true}'

Which when I run that, it returns 102 hits, so nothing that looks out of the ordinary.

**Comment by gusdemayo** [comment]
It looks like on line 527 of that class the number of docIds is only a few IDs for particular search terms - it appears that the issue is with the actual loading of the collection

**Comment by KevinMace** [comment]
We're seeing the same issue on a project that was recently upgraded. Generic search terms which would return a large collection of products are causing an `Allowed memory size of xxx bytes exhausted`. Increasing the memory limit helps however the page load time is unacceptable (+30 seconds). 

- Adobe Commerce ver. 2.4.5
- ElasticSuite Open Source ver. 2.10.11
- Catalog contains in excess of 140k products.

I'll report back if/when I have further information after debugging the issue on a local test environment.

**Comment by ankita-parashar-soni** [comment]
@KevinMace did this issue resolve for you?

**Comment by Nuranto** [comment]
We have similar issues with : 
- Magento 2.4.5-p1
- ES 7.17.8
- ElasticSuite 2.10.13.3
- 40K products

We had to increase heap size too (4G was not enough oO).

And our search page `/catalogsearch/result/?q=any_term` gives a 500 (Allowed memory exhausted). Even a search on a sku that shoud return one result.

I tried to dump a trace when memory get high, and it's pointing at the `array_map` call in `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query\Builder\Boolean::buildQuery`

**Comment by webcreative24** [comment]
Same here. Magento 2.4.5-p1

**Comment by rob542** [comment]
we have the same problem.

we have only a catalog of 15k SKU's and meanwhile a heap size of 8 GB and still this is not enough.

and we have these problems only since the update from to Magento 2.4.5-P1 - with Magento 2.3.5 we had none.

The Adobe support, is also no help, they simply say, this is a problem with ElasticSuite and talk also otherwise only out, with flimsy excuses.

**Comment by Nuranto** [comment]
Got a ugly quick fix for the loop I describe above. If it can help some of you while it's getting fixed : 

in `src/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Search/Request/Product/Attribute/Aggregation/Category.php`

replace 
`if ($this->layerCategoryConfig->isCategoryFilterVisibleInLayerNavigation() === true) {`

with 
`if (false && $this->layerCategoryConfig->isCategoryFilterVisibleInLayerNavigation() === true) {`

to disable categories aggregation, which was triggering the issue in my case.

**Comment by Nuranto** [comment]
I have about 400 virtual categories, but I don't know about conditions that could loop though, it depends on users. I will check. Are your talking about root category id, or some category condition inside the rule ?
Thanks @romainruaud.

**Comment by romainruaud** [comment]
Closing because this is an old issue that was most probably project-specific.

Regards
