### ISSUE TITLE
Problem with different host of elastic

### ISSUE THREAD

**Issue by kovalevandrew** [Smile-SA/elasticsuite#283]
with localhost module works fine but with other host it not work at all.
I created module app/code/Mymodule/ElascticSuite 

**etc/config.xml**
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Store:etc/config.xsd">
<default>
    <smile_elasticsuite_core_base_settings>
        <es_client>
            <servers>10.42.236.26:9200</servers>  
        </es_client>
    </smile_elasticsuite_core_base_settings>
</default>
</config>`

**etc/module.xml**

`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
  <module name="Mymodule_ElasticSuite" setup_version="1.0.0">
    <sequence>
      <module name="Smile_ElasticsuiteCore"/>
    </sequence>
  </module>
</config>`

**registration.php**
```
<?php
\Magento\Framework\Component\ComponentRegistrar::register(
    \Magento\Framework\Component\ComponentRegistrar::MODULE,
    'Mymodule_ElasticSuite',
    __DIR__
);
```

Notice that in my magento2 server i do curl with this ip and get 
`{
  "name" : "Brass",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "xqsgAC7US8ahZWJXpTgNMg",
  "version" : {
    "number" : "2.4.3",
    "build_hash" : "d38a34e7b75af4e17ead16f156feffa432b22be3",
    "build_timestamp" : "2016-12-07T16:28:56Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}` 
I think it means server with elastic works fine

**Comment by romainruaud** [comment]
Hello @kovalevandrew 

Are you sure that you properly created your ```OpsWay_ElasticSuite``` module ?

It should appears on the Back-Office on **Stores > Configuration > Advanced > Advanced**

If your module does not appear here, this indicates it has not been properly created.

Additionnally, please ensure your file structure is correct. Your module should be somewhere like this : 

- app
-- code
--- OpsWay
---- ElasticSuite

Also ensure all is OK regarding lower/upper case letters in your module name.

Best regards,

**Comment by kovalevandrew** [comment]
Yes im sure that i created module properly, but elasticsuite take ip from config in admin
![default](https://cloud.githubusercontent.com/assets/8459731/21682470/63db9cf6-d35d-11e6-8a43-ce0753fd8485.PNG)

**Comment by Koc** [comment]
relates to #267, #233

**Comment by kovalevandrew** [comment]
im created module by documentation and still has problem, ip took from admin config.
