### ISSUE TITLE
Deprecated Functionality: Creation of dynamic property

### ISSUE THREAD

**Issue by Sharkozp** [Smile-SA/elasticsuite#2835]
Hello here,

### Preconditions

I am testing this module with PHP8.2 and Magento 2.4.6-beta2 before it will be released. 

Magento Version :
2.4.6-beta2

ElasticSuite Version :
2.10.13.1

Environment :
Developer

### Steps to reproduce

1. Install Magento 2.4.6-beta2 with PHP 8.2
2. Run bin/magento setup:upgrade

### Expected result
command setup:upgrade runs without exceptions

### Actual result
The directory '/var/www/html/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Deprecated Functionality: Creation of dynamic property Smile\ElasticsuiteCore\Setup\Validator::$client is deprecated in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Setup/Validator.php on line 37

**Comment by romainruaud** [comment]
Hi @Sharkozp 

our branch containing the Magento 2.4.6 compatibility is "feature-magento-246". 

We fixed your issue on this branch, can you check it's behaving properly ?

Regards

**Comment by rutgerrademaker** [comment]
@romainruaud I can verify setup:upgrade runs without issues after requiring the 246 branch (like @Sharkozp explained)
Seems search is working now

Please note that I found another issue in the admin panel

DateTime::sub(): Argument #1 ($interval) must be of type DateInterval, bool given

Exception in //vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatusProvider.php:158

it looks like the try-catch is not accepting the bool

I've now patched it locally by adding 

```
    private function isGhost($indexDate): bool
    {
        // Make sure to not even try if $indexDate is false
        if (false === $indexDate) {
            return false;
        }

        try {
            return (new DateTime())->sub($indexDate)->getTimestamp() / self::SECONDS_IN_DAY >= self::NUMBER_DAYS_AFTER_INDEX_IS_GHOST;
        } catch (Exception $e) {
            return false;
        }
    }
```

**Comment by romainruaud** [comment]
Initial issue has been fixed.

Issue with datetime is in #2869

**Comment by Sharkozp** [comment]
Hello @romainruaud,

I can confirm that this issue has been fixed for Magento 2.4.6 with PHP 8.2 in **feature-magento-246** branch. I will close this issue.

Thank you

**Comment by wilfriedwolf** [comment]
Hi @romainruaud 

Just found another deprecated error in release 2.11.0. If you want, I  can create a PR or just apply the attached patch.
Best regards,

Willi

--- a/src/module-elasticsuite-tracker/Model/IndexResolver.php
+++ b/src/module-elasticsuite-tracker/Model/IndexResolver.php
@@ -38,7 +38,11 @@
      */
     private $indexSettings;

-
+    /**
+     * @var \Smile\ElasticsuiteTracker\Model\IndexManager
+     */
+    private $indexManager;
+
     /**
      * Constructor.
      *

**Comment by wilfriedwolf** [comment]
Won't let me upload the patch file, although stated differently :(
