### ISSUE TITLE
Problem with ancestor categories and scope is All Store Views

### ISSUE THREAD

**Issue by msloboda-macopedia** [Smile-SA/elasticsuite#2841]
The problem seems  to be related with ancestor categories. If there is need to manually sort products on page with ancestor category and scope is **'All Store Views'** then to  table  `smile_virtualcategory_catalog_category_product_position` in column **'store_id' goes '0'.** 
I found that in this case store_id = 0, means admin store. 

![image](https://user-images.githubusercontent.com/114057111/217223944-e4cf9a50-61d6-4ab3-bde8-b70f85afc710.png)

So, if certain store view is selected, other then default, then products are visible on store front.

However it is misleading behaviour, maybe when All Store Views is selected, then multiple rows should be set up in `smile_virtualcategory_catalog_category_product_position` table, each for separate store?

version:  "smile/elasticsuite": "2.10.6"

_Originally posted by @msloboda-macopedia in https://github.com/Smile-SA/elasticsuite/issues/2768#issuecomment-1420591494_

**Comment by romainruaud** [comment]
Hi @msloboda-macopedia 

Your description of the issue is barely not understandable for us.

Please describe exactly what you want to achieve, and what's happening. With screenshot and examples of data.

To keep it short "store_id = 0, means admin store" => nope, "store_id = 0, means **all store views**".

That being said, an improvement has been made in version 2.10.13 on this part : https://github.com/Smile-SA/elasticsuite/pull/2793

So please also try to check if the latest version could fix what you are seeing.

Regards

**Comment by msloboda-macopedia** [comment]
Hi @romainruaud, 
OK, I try to clarify. Here is printscreen from `smile_virtualcategory_catalog_category_product_position` table
![Screenshot from 2023-02-20 11-40-15](https://user-images.githubusercontent.com/114057111/220083590-0c935d02-64c2-4c1f-8dca-d904aa8c0374.png)
In column store_id is 0. 
As You see that column is in relation with `store` table, where store_id = 0 means admin
![Screenshot from 2023-02-20 11-46-45](https://user-images.githubusercontent.com/114057111/220084072-6af7d8e2-6537-4338-b6e2-4bd9a19a3d8d.png)

**Comment by romainruaud** [comment]
@msloboda-macopedia 

1. As I said before, in the context of saving product positions "store = 0" means **all store views**, not "Admin". This means that these positions will be applied to all store views of your website in frontend. Except if you override these positions with a particular store view when contributing them.

2. As I asked last time, please describe exactly what you want to achieve, and what's happening. With screenshot and examples of data.

3. Please check if latest version solves your issue.


Without answers for point 2. and 3. we'll have to close your issue.

Thank you

**Comment by msloboda-macopedia** [comment]
At this point, after upgrade to version 2.10.13 it seams to be ok.
