### ISSUE TITLE
Search Usage Analytics: Data Inaccuracies 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#2846]
### Preconditions
Adobe Commerce,  2.10.12

Magento Version : 2.4.5-p1 

ElasticSuite Version : 2.10.12

Environment : Production 

Third party modules : ERP Integrations, and Klavio 

### Steps to reproduce

1. Create Product with SKU "804731"
2. Search Term "804731"
3. Product is found in Configurable and Simple Product 2 results 
4. Search Tool reports unknown "# Results (avg.)" value, in my case it's 17332, 17730 etc. 

### Expected result

1. Number of Search Results should be actual 

### Actual result

<img width="591" alt="Screenshot 2023-02-10 at 9 33 44 PM" src="https://user-images.githubusercontent.com/7387019/218237029-42a2e8d8-9680-466a-ae06-9005aa0e3a6c.png">

**Comment by vahonc** [comment]
Hello @duffner,

I was not able to reproduce your issue on my test environment with fresh Magento 2.4.5-p1 EE with default sample data and ElasticSuite 2.10.12.

I tried using different search terms and also your steps for reproducing.

Here're some screenshots from my test environment:

![Screenshot from 2023-02-14 13-03-12](https://user-images.githubusercontent.com/67791361/218784711-d0ffa4cf-31d1-4619-822b-06f0f1d7bdeb.png)

![Screenshot from 2023-02-14 13-03-44](https://user-images.githubusercontent.com/67791361/218782411-a94c1ff3-999f-47a4-992d-1050ff6a06de.png)

![Screenshot from 2023-02-14 13-09-33](https://user-images.githubusercontent.com/67791361/218782500-aa7de2d3-3ab7-4acd-9479-b03bcbafbdd7.png)

![Screenshot from 2023-02-14 16-30-26](https://user-images.githubusercontent.com/67791361/218782560-917c44df-de32-4f4f-aabd-50dfc5b46060.png)

As you can see the  "# Results (avg.)" values are normal and actual. Therefore it looks like smth wrong on your side or specific to your project. So we need more details about your environment.

Have you checked the logs (Magento and Elasticsearch)?

BR,
Vadym
