### ISSUE TITLE
Index Mapping

### ISSUE THREAD

**Issue by eBusinessAtlantique** [Smile-SA/elasticsuite#2850]
Hello

I am wondering why the default setup of the module is as follow for index mapping in the config:
Key
elasticsuite_categories_fulltext
Name of index
catalog_category

And (second line)

Key
elasticsuite_categories_fulltext
Name of index
catalog_product

Why does the key is the same for different indexes ?

I hope that someone have the answer.
BR
Max

**Comment by vahonc** [comment]
Hello @eBusinessAtlantique,

Is your question related to this [config](https://github.com/Smile-SA/elasticsuite/blob/e8e67b407f3f49a2bac16e3525173d19af9c0f7c/src/module-elasticsuite-indices/etc/config.xml#L22) 

BR,
Vadym

**Comment by eBusinessAtlantique** [comment]
Exactly !
