### ISSUE TITLE
Pagination, sorting and limit on virtual category tree

### ISSUE THREAD

**Issue by Bashev** [Smile-SA/elasticsuite#2856]
If Virtual Category tree is enabled you are not able do to sort, change the limit, or go to other pages.

Magento Version: 2.4.5

ElasticSuite Version: 2.10.12.1

Environment: Production

### Steps to reproduce

1. Make a virtual category.
2. Enable Category Tree
3. Navigate to storefront to category created in step 1. 
4. Open some of subcategories of this virtual category. 
5. Try to go to second page, sort or change limit of products per page.

### Expected result
Sort/limit/paginate only products which are in the respective category.
1.

### Actual result
Redirect you to original category outside of the virtual tree.

**Comment by romainruaud** [comment]
good catch, and good fix.

We just need to check if this is backward compatible. I guess that Magento changed how url-rewrites are working in 2.4.5.

Regards

**Comment by vahonc** [comment]
@romainruaud, I can confirm that this fix is backward compatible with previous versions of Magento. The UrlRewriteFinder object is present in all versions of Magento 2.4.x and even in 2.3.7-p2. I was able to reproduce this issue on M2.4.6-beta8 and also on M2.4.3 with ElasticSuite version 2.10.11. In both cases, this hotfix resolved the issue.

BR,
Vadym
