### ISSUE TITLE
Product Listing Widget - Sku condition - missing options

### ISSUE THREAD

**Issue by KrzysztofWisniewskiAcc** [Smile-SA/elasticsuite#2864]
Create a custom-page
In the content insert a widget (Catalog Product List) 
Conditions: 'in' or 'no_in' are missing.
More info in the 'steps to reproduce' section

### Preconditions
Any version of magento where you can install elastisuite
Magento Version :  >= 2.4
ElasticSuite Version : 2.10.*
Environment : Developer
Third party modules : -

### Steps to reproduce
In magento OOTB (tested on 2.4.2-p2 && 2.4.5-p1 )
1) Create a custom-page
2) Edit content, add row & add a text field into the row
3) Click on the text field, editor will appear, Click 'insert widget' from the editor menu
![image](https://user-images.githubusercontent.com/126663987/223463352-bf959b62-5b2a-4e2e-be27-c265593320a3.png)

4) Pick 'Catalog Product List'
5) Go to conditions section and pick 'sku' condition
![image](https://user-images.githubusercontent.com/126663987/223459989-5ab2718c-2de4-482b-9c70-13890445623b.png)

You can see the list of filters for 'sku' .

6) Now install elasticsuite & repeat all the steps and we recieve to following:
![image](https://user-images.githubusercontent.com/126663987/223469389-9e7b68fe-63da-4523-9b40-d16f16d5a94c.png)
You can see that (in my current version of elasticsuite 2.10.10) there are only 2 conditions filters.

I saw that in never version there are new additional conditions, but still the ones important for me are missing.

All takes action in this file:
https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php
```
public function getDefaultOperatorInputByType()
    {
        if (null === $this->_defaultOperatorInputByType) {
            $this->_defaultOperatorInputByType = [
                'string'      => ['{}', '!{}'],
                'numeric'     => ['==', '!=', '>=', '>', '<=', '<'],
                'date'        => ['==', '>=', '>', '<=', '<'],
                'select'      => ['==', '!='],
                'boolean'     => ['==', '!='],
                'multiselect' => ['()', '!()'],
                'grid'        => ['()', '!()'],
                'category'    => ['()', '!()'],
                'sku'         => ['()', '!()', '{}', '!{}'],
            ];
            $this->_arrayInputTypes            = ['multiselect', 'grid', 'category'];
        }

        return $this->_defaultOperatorInputByType;
    }

```

I even checked, if adding extra conditions to the 'sku' field('in' & 'not_in') and it looks like it's working, but I'm not sure if that's correct and what consequences it will have across other application.
` 'sku'         => ['==', '!=', '()', '!()', '{}', '!{}'],`

### Expected result
Condition 'in' & 'not_in' should be available to pick.

### Actual result
Most of conditions are missing, only few are available.
![image](https://user-images.githubusercontent.com/126663987/223469389-9e7b68fe-63da-4523-9b40-d16f16d5a94c.png)

**Comment by romainruaud** [comment]
That's very strange, considering it was exactly what this commit was aimed for : 

https://github.com/Smile-SA/elasticsuite/commit/e834e18d7bee05dad493a339e7eca982a0a42c69

_"Allow both "contains" and "is one of" for SKUs."_

**Comment by romainruaud** [comment]
But my commit was only integrated in 2.10.12, so if you're still on 2.10.10 you might be missing it.

Could you try to reproduce this on latest Elasticsuite version ? At least on a version >= 2.10.12.

Regards

**Comment by KrzysztofWisniewskiAcc** [comment]
Answering your question, I tested this on 2.10.12.1 and the options 'is one of' & 'is not one of' are present.

Could you tell me please if condition: 'is' === 'is one of' ?
As there were 2 different in the base version and it makes me wonder what's the difference.

Also I see that the the conditions 'equals or greater than' & 'equals of less than' are missing, but that at least makes sense in terms of sku field.

**Comment by romainruaud** [comment]
Hi @KrzysztofWisniewskiAcc 

yes, "is" = "is one of" for the SKU.

everything is wrapped under a "should" clause : https://github.com/Smile-SA/elasticsuite/blob/2.10.x/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/QueryBuilder.php#L139

so if your rule is "SKU is A,B,C", it will result in "SKU in [A,B,C]" as a result.

Regards
