### ISSUE TITLE
Lot of indices in REBUILDING status after changing the shard count

### ISSUE THREAD

**Issue by sweta-fcmoto** [Smile-SA/elasticsuite#2866]
We  recently downgraded our shard count from 3 to 1 on our Magento commerce cloud 2.4.5-p1 environment, based on the dashboard warning, re-run the catalogsearch fulltext reindex, indexing is successful but elasticsuite index status for lot of indices are in REBUILDING state. Is this normal or we have some issue?

![Indices-Status-Magento-Admin (3)](https://user-images.githubusercontent.com/77714241/223756400-2bb5e78c-92a4-46af-926c-c21b17ba91d8.png)

**Comment by romainruaud** [comment]
Hello,

according to the date-time pattern of those indices, they should be considered as "ghosts" and not as "rebuilding".

These indices are quite old, most of them are from 2022. Ghost indices are indices that were never finished to build by the engine and that could safely deleted.

We're working on a problem existing in detection of ghost indices wrongly displayed as "rebuilding".

Regards

**Comment by sweta-fcmoto** [comment]
Thanks Romain, let us delete these ghost indices then. 

cheers
Sweta

**Comment by romainruaud** [comment]
In any case, what's the version of Elasticsuite you are using ?

**Comment by sweta-fcmoto** [comment]
Hi Romain, 

SmileSuite : 2.10.12.1
Elastic Search: 7.7.1

Ideally we should be upgrading to opensearch as per Magento devdocs (that is in progress).
