### ISSUE TITLE
Version 2.11.0 not compatible with Hyva compatible module

### ISSUE THREAD

**Issue by anvanza** [Smile-SA/elasticsuite#2872]
### Preconditions
Magento Version : 2.4.6
ElasticSuite Version : 2.11.0
Environment : developer

Third party modules :

### Steps to reproduce

1.
2.
3.

### Expected result

1. 

### Actual result
Root composer.json requires hyva-themes/magento2-smile-elasticsuite ^1.1 -> satisfiable by hyva-themes/magento2-smile-elasticsuite[1.1.0, 1.1.1, 1.1.2].
    - hyva-themes/magento2-smile-elasticsuite[1.1.0, ..., 1.1.2] require smile/elasticsuite ~2.10.9 -> found smile/elasticsuite[2.10.9, ..., 2.10.14] but it conflicts with your root composer.json require (^2.11)

**Comment by romainruaud** [comment]
You're right, we should publish a new version of the Hyva compatibility package that requires Elasticsuite 2.11.0

Btw, is Hyva compatible with Magento 2.4.6 right now ?

Regards

**Comment by anvanza** [comment]
Hi @romainruaud ,

I seems to work fine on my environment. I'm still using PHP 8.1 and not 8.2.

Found this PR that has just been merged.
https://gitlab.hyva.io/hyva-themes/magento2-theme-module/-/merge_requests/309

**Comment by romainruaud** [comment]
I fixed this in the Hyva package and published a new version :)
