### ISSUE TITLE
Exception in admin panel with 2.11

### ISSUE THREAD

**Issue by justinconabree** [Smile-SA/elasticsuite#2873]
### Preconditions

Magento Version : 2.4.6

ElasticSuite Version : 2.11.0

Environment : Developer

Third party modules : many (shouldn't be related)

### Steps to reproduce

1. Access admin configuration section

### Expected result

1. No error message up top

### Actual result

1. Error message above content
```
DateTime::diff(): Argument #1 ($targetObject) must be of type DateTimeInterface, bool given
Exception in /app/vendor/smile/elasticsuite/src/module-elasticsuite-indices/Model/IndexStatusProvider.php:159
```
![image](https://user-images.githubusercontent.com/68294336/225051787-677a31bb-9ecd-4db1-b467-4b031bf4bfbe.png)

A few things
- There is a try/catch in isGhost, but it seems the exception thrown is \Throwable but not \Exception
- Issue comes from `getIndexUpdatedDateFromIndexName` returning a boolean
- Some debug info about the values I have in that function

```
$format: "YmdHis"
$date: "220230314141959"
$indexName: "_en_b2b_catalog_product_20230314_141959"
```

**Comment by romainruaud** [comment]
Hi @justinconabree and thank you for submitting this.

We did not see this in our final testing phase despite the fact we've done plenty of testing around this zone, considering that Zend_Date was replaced by DateTime.

Could you give me a bit more insights ? what is the "full" index name ? prior reaching to this function.

Would you mind sharing a screen of the Elasticsuite > Indices screen as well ? 

Regards

**Comment by romainruaud** [comment]
Ok I think I got it...

it's probably due to the fact that there is a "2" in your store code (in "en_b2b").

Everything is stripped except the number 2.

Then the date is **2**20230314141959 instead of **220230314141959**

**Comment by justinconabree** [comment]
Hi @romainruaud 

Elasticsuite > Indicies actually crashes with the same error

Wow yeah good catch! Our other store views have the same `catalog_product` index but don't crash. Only the b2b ones.

**Comment by justinconabree** [comment]
@romainruaud not sure about performance impact but changing the regex from `[^0-9]` to `[^0-9]|(?<=[a-zA-Z])[0-9]` did the trick for me (all non numbers or numbers preceded by a letter).

**Comment by mvenghaus** [comment]
i ran into the same issue .. my problem was that i had an old config value in "indices_pattern".
i changed it and now it works
old: {{YYYYMMdd}}_{{HHmmss}}
new: {{Ymd}}_{{His}}
