### ISSUE TITLE
addFiledToFilter wipes out most of items

### ISSUE THREAD

**Issue by KrzysztofWisniewskiAcc** [Smile-SA/elasticsuite#2874]
Elastisuite version 2.10.10
Magento 2.4.2-p2

1.  I created a catalog product list widget on custom page
![image](https://user-images.githubusercontent.com/126663987/225646294-98c080c3-1b98-4263-92ba-7ebaa536e962.png)

html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection::createCollection
2)
I have a method getProducts and it goes like this:

```
public function getProducts(): ?ProductCollection
    {

        if ($this->collection !== null) {
            return $this->collection;
        }

        $this->collection = $this->createCollection(); 
        // at this point getSize() is ~900 & getItems() on collection returns lots of products with different types
        $this->collection->addFieldToFilter(ProductInterface::TYPE_ID, ['eq' => Type::TYPE_SIMPLE]);
        //now getSize() 1 & getItems() 1 product
}
```

![image](https://user-images.githubusercontent.com/126663987/225651092-44615aed-876b-4d6d-bddf-ec34d342498e.png)

After runing addFieldToFilter I end up having 1 item in the collection, although I should have more as before using the filter I saw that there are many simple products in the collection.

Am I using this in a invalid way?

ProductInterface::TYPE_ID = 'type_id'
Type::TYPE_SIMPLE = 'simple'

**Comment by vahonc** [comment]
Hello @KrzysztofWisniewskiAcc,

At this point, it's hard to tell from the code that you provided why you have a such result. For a correct answer, here at least need to know whether the collection of products has already been loaded or not.

In the latest versions of our module, we slightly expanded the list of conditions that you can now use. For example, you can add the condition **Only simple products** or **Only grouped products**, etc. So now there is no need to add such filters directly in the code.

![Screenshot from 2023-03-20 17-06-23](https://user-images.githubusercontent.com/67791361/226403815-293705c0-cabc-45aa-b095-f2e54e0be65d.png)

So the safest thing for you is to update our module to the latest version (for now it's [2.10.14](https://github.com/Smile-SA/elasticsuite/releases/tag/2.10.14)).
Maybe this will solve your problem.

BR,
Vadym

**Comment by KrzysztofWisniewskiAcc** [comment]
I will give it a try on the newer version
For now I will close the issue
