### ISSUE TITLE
Extending Class / Type Error occurred when creating object

### ISSUE THREAD

**Issue by dennismetz** [Smile-SA/elasticsuite#2876]
### Preconditions
PHP8.1 / Linux / Apache Webserver

We overwrite the class "Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData" in its own module. 
We only add a "$select->join" in the "getRelationQuery" method, otherwise, except for the namespace, nothing is changed - the contents are exactly the same. The problem exists even if our extra code is not added and we overwrite the class without any customizations.
The whole module consists only of the overwritten class, the di.xml/module.xml and the composer.json/registration.php.

Magento Version : 2.4.5-p1 / CE (Open Source Edition)
ElasticSuite Version : 2.10.14
Environment : Developer
Third party modules : - 

### Steps to reproduce
Create a new extension under app\code\Vendor\Module

1. copy the whole file: Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData.php and paste it to the following location: Vendor\Module\Catalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData.php.
2. Change the namespace from Smile\ElasticsuiteCatalog to Vendor/Module
3. Create the etc\di.xml file with the following content:
`<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData"
                type="Vendor\Module\Catalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData"/>
</config>`
4. Otherwise still the etc\module.xml and the registration.php
5. Then activate the module in Magento: `bin/magento module:enable vendor_module
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento setup:static-content:deploy -f -j5
bin/magento c:f
bin/magento c:c`

### Expected result
Without any changes nothing should happen - the module should work without any error message because we didn't change anything in the code.

### Actual result
The module triggers the following error message:
`Exception #0 (Magento\Framework\Exception\RuntimeException): Type Error occurred when creating object: Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData, Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData::__construct(): 
Argument #2 ($attributeResourceModel) must be of type Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData, Vendor\Modulename\Catalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData given, called in vendor/magento/framework/ObjectManager/Factory/AbstractFactory. php on line 121`

**Comment by vahonc** [comment]
Hello @dennismetz,

Most likely you need to check if you are correctly extending from the original class. In my opinion, this is a typical Type Error in PHP. So carefully check the parameters in your constructor and classes that you declare in the Use section.

BR,
Vadym
