### ISSUE TITLE
Possibly missing changes from Magento 2.4.6?

### ISSUE THREAD

**Issue by hostep** [Smile-SA/elasticsuite#2877]
Hi there

### Preconditions
- Magento Version: OS 2.4.6
- ElasticSuite Version: 2.11.0
- Environment: N/A
- Third party modules: N/A

### Possible issue
I've used the [ampersand-magento2-upgrade-patch-helper](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper) package during an upgrade of a shop from 2.4.5-p2 to 2.4.6

And it alerted me about 3 files in the elasticsuite module which could potentially be affected by the Magento upgrade:
```
+-------+------------+----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| Level | Type       | File                                                                                               | To Check                                                                                      |
+-------+------------+----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
| WARN  | Plugin     | vendor/magento/module-catalog-inventory/Model/Indexer/Stock.php                                    | Smile\ElasticsuiteCatalog\Plugin\Indexer\Stock\ReindexProductsAfterStockUpdate::aroundExecute |
| WARN  | Preference | vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php | Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Category      |
| WARN  | Preference | vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Price.php    | Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Price         |
+-------+------------+----------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------+
```

The first one is not relevant, the change in there shouldn't cause issues.
But the other two might be relevant:

1. `Builder\Category`:
Magento 2.4.6 came with this change: https://github.com/magento/magento2/commit/e40bc76d938e61c0c27b1d44700f9fc9bd8de208
Unfortunately not a lot of info can be found in the commit message to explain what this is needed for.

_Update_, found some more info about this one, is being described in the release notes as:
> The product query now returns correct category data in aggregation. Previously, attribute_code.category_uid returned the value of category_id instead of category_uid.

And I've found the merge commit under ticket number [AC-5984](https://github.com/magento/magento2/commit/be5513fdbbdf644649ba535bdcdc9f5477190866)

I'm wondering if the same change needs to be applied to [the preference inside elasticuite](https://github.com/Smile-SA/elasticsuite/blob/ee0e14b32ba75b525bfc8e8feffa7eb999409f97/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Category.php#L163-L167)?

2. `Builder\Price`:
Magento 2.4.6 came with a change in scope of [ACP2E-1238: attributes from GraphQL not translated](https://github.com/magento/magento2/search?q=ACP2E-1238&type=commits) (see the [merge commit](https://github.com/magento/magento2/commit/18bdb6a8e85e5c6b125b19e2d5442dd4a7089cd4#diff-2f9f323d6ff713c8daa86618a1b8128bb1e2c6ed8e41a91b29c5a3abef7b94f4) of which only the changes in `app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Price.php` are relevant)
 
The fix is being described in [the 2.4.6 release notes](https://experienceleague.adobe.com/docs/commerce-operations/release/notes/magento-open-source/2-4-6.html?lang=en#translations-and-locales) as:
> The getOptions method now correctly fetches price attribute label values based on store view. Previously, the price attribute was translated during GraphQL operations for the incorrect store view.

Same question, do we need this fix as well in [the preference inside elasticsuite](https://github.com/Smile-SA/elasticsuite/blob/ee0e14b32ba75b525bfc8e8feffa7eb999409f97/src/module-elasticsuite-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Price.php#L81) ?

Thanks!

**Comment by vahonc** [comment]
Hello @hostep,

>Builder\Price:
Magento 2.4.6 came with a change in scope of [ACP2E-1238: attributes from GraphQL not translated](https://github.com/magento/magento2/search?q=ACP2E-1238&type=commits) (see the [merge commit](https://github.com/magento/magento2/commit/18bdb6a8e85e5c6b125b19e2d5442dd4a7089cd4#diff-2f9f323d6ff713c8daa86618a1b8128bb1e2c6ed8e41a91b29c5a3abef7b94f4) of which only the changes in app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/Builder/Price.php are relevant)

If I'm not mistaken we already added a fix for the translation of the attributes from GraphQL on our side.

> Builder\Category:
Magento 2.4.6 came with this change: https://github.com/magento/magento2/commit/e40bc76d938e61c0c27b1d44700f9fc9bd8de208

Yes, we know that Magento now uses `category_uid` instead of  `category_id`. It looks like they don't care if some customers use requests with `category_id`. We have a similar issue [here](https://github.com/Smile-SA/elasticsuite/issues/2862) and trying to find a solution to keep two of those aggregations in the GraphQl response for backward compatibility.

BR,
Vadym
