### ISSUE TITLE
Optimizers Not Working as Expected

### ISSUE THREAD

**Issue by lsmitley** [Smile-SA/elasticsuite#2878]
We have an optimizer set up based on our attribute call Rank. It should be applied to both search and category, but have a discrepancy with the search term prep table and when you navigate to prep tables.

https://www.centralrestaurant.com/refrigeration/commercial-prep-tables/sandwich-and-salad-prep-tables.html
https://www.centralrestaurant.com/catalogsearch/result/?q=prep+tables

Our highest ranking item showes up first through navigation, but I do not even see it when searching. 

### Preconditions

Magento Version : Magento ver. 2.4.4-p2

ElasticSuite Version : Open Source ver. 2.10.12.1

Environment :Production

Third party modules :
Mageants
Ameex
Powerrevieews
Magetop.com
Encora
Magefan Extensions
Firebear
Codazon
Elasticsuite
Magepal
Mageplaza Extensions
FlurryBox
Amasty Extensions
### Steps to reproduce

1. Set up Optimizer based on our Rank attribute
2. Searched "prep table" saw difference from navigating to the Sandwich and Salad Prep Tables category.
3.

### Expected result

1. The expected result would be to see SKU 69K-770 at or near the top of the results when searching "prep table" or "prep tables"

### Actual result

1. It is not in the top results. Have to go to several pages to see SKU 69K-770.
![image](https://user-images.githubusercontent.com/128414967/226733609-d2b05607-cadf-4c13-90be-2d7b2b48c66f.png)

**Comment by vahonc** [comment]
Hello @lsmitley,

It's hard to say what's wrong with your optimizer because we need more details. So please provide the configuration (with screenshots) of your optimizer.

BR,
Vadym
