### ISSUE TITLE
Impossible to disable Smile_ElasticsuiteCatalogGraphQl via composer by yireo tool

### ISSUE THREAD

**Issue by yutv** [Smile-SA/elasticsuite#2879]
On the projects which don't use any GraphQl functionality there is a good tool to disable all of them via composer https://github.com/yireo/magento2-replace-tools
```
composer require yireo/magento2-replace-graphql
php bin/mageno setup:upgrade
```

Unfortunately the Elasticsuite has no a separate GraphQl composer package so it's impossible to disable it that way.
```
php bin/mageno setup:di:compile
Interface "Magento\CatalogGraphQl\Model\Resolver\Products\Query\ProductQueryInterface" not found
```

**Describe the solution you'd like**

The `Smile_ElasticsuiteCatalogGraphQl` Magento module should be moved  to a separate composer package.

**Comment by romainruaud** [comment]
Hi, we will not do this.

Our experience has proven that separated packages are hard to maintain and often left-behind.

See https://github.com/Smile-SA/magento2-module-elasticsuite-cms-search or https://github.com/Smile-SA/magento2-module-elasticsuite-rating or https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order

They're not really up-to-date. It's also much painful to centralise any potential issues.

To be honest, I don't think there is a gain in disabling Magento2 graphql modules. There are a lot of junk modules that are worth to disable (optional core modules, bundled extensions like vertex, etc...), but the graphQl ones does not really have an impact.

Regards

**Comment by Stevie-Ray** [comment]
Having the same issue, trying to remove the unused GraphQL endpoints from Magento because they show a security risk while running the Acunetix vulnerability scanner.

```
php bin/mageno setup:di:compile
Interface "Magento\CatalogGraphQl\Model\Resolver\Products\Query\ProductQueryInterface" not found
```

But adding `"smile/module-elasticsuite-catalog-graph-ql": "*"` doesn't work.

**Comment by cptX** [comment]
I hope this will be reconsidered in the future!
