### ISSUE TITLE
Numerical synonyms issue

### ISSUE THREAD

**Issue by udovicic** [Smile-SA/elasticsuite#2891]
If you try to set up synonyms that contain only numerical values, the result will not work as expected as they will not be used.

This has been partially resolved with [this commit](https://github.com/Smile-SA/elasticsuite/commit/62497ec4e4199004ed1f9053ba335df4b1df8cdc), but not fully.

There is one more remaining `array_merge()` call that tempers with this functionality in [QueryRewrite.php](https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-thesaurus/Plugin/QueryRewrite.php#L129-L132).

**Comment by romainruaud** [comment]
Hi @udovicic 

can you describe a reproduction scenario ?

**Comment by udovicic** [comment]
The simplest scenario would be this:

Provided that project has a product with SKU `2097402` and the extension is configured with the following synonyms:
```
097402,2097402
```

Doing a search for query `097402` will not return any results.


__What is basically happening is the following:__

In the referenced code `array_merge()` causes keys to be numerated again and defined synonym array return by elastic:
```
[2097402 = 0.1]
```

becomes

```
[0 = 0.1]
```

That is why referenced commit has comments like this
```
// Use + instead of array_merge because keys can be purely numeric and would be casted to 0 by array_merge.
```
Same needs to be applied to `QueryRewrite` class for synonyms to work.

**Comment by romainruaud** [comment]
okay, understood.

Can you propose a PR for this ?

Regards

**Comment by udovicic** [comment]
Yes, I belive so. As soon as I test my local patch, I will make a PR for it.

**Comment by udovicic** [comment]
Hi @romainruaud Should I create separate PRs to fix multiple versions or is there a better way to achieve the same?

**Comment by romainruaud** [comment]
yep exactly, PR to 2.10.x and I will cascade it.

Regards

**Comment by romainruaud** [comment]
Merged, will be part of next minor releases.

Thank you for contributing.
