### ISSUE TITLE
A preview of the terms found is displayed. However, no articles are displayed on catalogsearch.

### ISSUE THREAD

**Issue by stradd** [Smile-SA/elasticsuite#2893]
Magento ver. 2.4.5-p1 CE
ElasticSuite) Open Source ver. 2.10.14
Production mode

First of all, everything works flawlessly.
After a few hours, a preview of the search terms found is displayed, but after confirming in the search field with Enter the following appears on the search page:
Your search returned no results. And no items are displayed.

Not all categories are affected, but always the same ones.
index:reindex catalog search_fulltext fixes the problem again for a few hours.
Before reindexing, the status of the index is ready
After that it occurs again.
When I disable Elasticsuite. the problem does not occur.

**Comment by stradd** [comment]
Hi vahonc,

I still use the Amasty Full Page Cache Warmer. However, this has been working flawlessly for years.
However, I have noticed the following.
If I deactivate the ElastiSuite, the system runs perfectly. If I activate it, the problem occurs again after a while.
I have now set a cronjob for index:reindex catalog search_fulltext.
This has fixed the problem so far, but is not a permanent solution.

I use a multi websites/store.
curl http://localhost:9200/_cat/indices?v
gives:

health status index                                        uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   magento2_de_tracking_log_event_202209        zH9NB0LETmS4RfCTPDeSjA   1   0         11            0     59.7kb         59.7kb
green  open   magento2_de_tracking_log_event_202208        IgueCw-fT5y9elzreHbljw   1   0         15            0     24.8kb         24.8kb
green  open   magento2_en_tracking_log_session_202211      50h-3BriRN6e91FyQsfHew   1   0         71            0     49.3kb         49.3kb
green  open   magento2_en_tracking_log_session_202212      DH7tbDwORESJ3jcPbcHYsw   1   0         71            0     53.4kb         53.4kb
green  open   magento2_de_tracking_log_event_202304        z7JZM3IPSLGHJ1h75imvWQ   1   0        942            0      1.1mb          1.1mb
green  open   magento2_de_tracking_log_event_202303        W7EzsgElTBCItT1nL4Sw-g   1   0       3568            0      3.4mb          3.4mb
green  open   magento2_de_tracking_log_session_202209      n2Uh6VZvQGulX8JB-etGlA   1   0          7            0     16.2kb         16.2kb
green  open   magento2_de_tracking_log_session_202208      fj_l27eKSNiD65VHKAOCvQ   1   0         14            0      9.6kb          9.6kb
green  open   magento2_de_tracking_log_event_202206        S_2mjugvQvKTWWE7pCzcEA   1   0         47            0     45.1kb         45.1kb
green  open   magento2_de_tracking_log_session_202206      YUl4tj9jR6KZ6L4IInZh_w   1   0          9            0      8.9kb          8.9kb
green  open   magento2_de_tracking_log_session_202304      g0nHM-mSTtSd1fvc3ivNMw   1   0        302            2    142.2kb        142.2kb
green  open   magento2_de_tracking_log_session_202303      Gv4yA5KHR9mEahnvA88Zew   1   0        709           13    274.3kb        274.3kb
green  open   magento2_de_tracking_log_session_202302      4SbNloCRT6C84YhbLfMDvw   1   0        761            6    288.4kb        288.4kb
green  open   magento2_de_tracking_log_session_202301      cR-YWcniTN-ILtqzZ-ku2A   1   0        643            4    269.3kb        269.3kb
green  open   magento2_en_tracking_log_session_202210      158Uw-mwSeafqwJjA0ZEPQ   1   0         21            1       35kb           35kb
yellow open   magento2_product_2_v543                      JkMadoFwS1K5pKEFUJ0e1Q   1   1       2344            0        2mb            2mb
green  open   .geoip_databases                             1bEU-sTKR-KxvbiSdpGB8A   1   0         42           42     40.6mb         40.6mb
green  open   magento2_en_tracking_log_event_202210        0wWjBIInTcuAjF1Xt3UqlA   1   0         40            0     99.1kb         99.1kb
green  open   magento2_en_tracking_log_event_202211        2tAOhkuQSRKX3TE8yKq34w   1   0        526            0      685kb          685kb
green  open   magento2_en_tracking_log_event_202212        sWLVQJNgRp2M-TBtdlnsLA   1   0        195            0    358.4kb        358.4kb
green  open   magento2_de_tracking_log_event_202302        Khx8qipDSZCEAkJwNvLiKg   1   0       2916            0      2.4mb          2.4mb
yellow open   shopprefix_product_1_v12                     co7oyy22QAqLhxOsGT764g   1   1          1            0      9.4kb          9.4kb
green  open   magento2_en_catalog_category_20230408_212346 Q2uJ40twTxOWpeDhIZUbng   1   0        433            0    759.4kb        759.4kb
green  open   magento2_de_tracking_log_event_202301        Bm-RkWlHTxCjBL4sOBdOcA   1   0       2227            0      1.6mb          1.6mb
green  open   magento2_en_thesaurus_20230408_212346        ZqDBVNs7TqyfZ2Qqt3F1bw   1   0          0            0       226b           226b
yellow open   shopprefix_product_2_v5                      q0d8RD1MT12wGdSV6b0dTQ   1   1          1            0      9.4kb          9.4kb
green  open   magento2_de_catalog_product_20230417_073008  2p_jCcFAStqJVDpp_sY7nw   1   0      28293            0     12.4mb         12.4mb
yellow open   magento2_product_1_v568                      uH0U64ozSaiFd6xRcv0A6w   1   1       2341            0      2.1mb          2.1mb
green  open   magento2_en_tracking_log_session_202301      YygMv2tnRrSAh_SJiAQK3A   1   0        130            2     67.7kb         67.7kb
green  open   magento2_en_tracking_log_session_202302      PgM93DvvR2K3K9ps4SePxA   1   0        174            0     96.1kb         96.1kb
green  open   magento2_en_tracking_log_session_202206      t4SkeApsRJWlWmFu-6sqDQ   1   0          1            0        5kb            5kb
green  open   magento2_en_tracking_log_session_202303      FkX4ukCKTHyJ4MfxB6VTJw   1   0        172            6     99.2kb         99.2kb
green  open   magento2_en_tracking_log_session_202304      bL4zjZE5ROSA8sI7rdMgJw   1   0         46            1     44.1kb         44.1kb
green  open   magento2_de_catalog_category_20230408_212345 r76DPpJOQZSYU5OJGr7gOw   1   0        430            0    780.3kb        780.3kb
green  open   magento2_de_tracking_log_session_202212      eE_LzUo2RoCCLpmW-yXu1w   1   0        717            6      286kb          286kb
green  open   magento2_de_thesaurus_20230408_212346        L6xrns6jR8-XtCn1arb_vA   1   0          0            0       226b           226b
green  open   magento2_de_tracking_log_session_202211      hZIT2Wv_SJeQU8d2cNm83A   1   0        795            3    289.4kb        289.4kb
green  open   magento2_de_tracking_log_session_202210      RQh3kwedSx--PIZP1PXx6Q   1   0        196           10    142.6kb        142.6kb
green  open   magento2_en_catalog_product_20230417_073020  hO0HFDs4TMWa7BfGfCW_eg   1   0      28293            0     11.7mb         11.7mb
green  open   magento2_en_tracking_log_event_202301        AN5ki6QnQEy6nKPDanr75Q   1   0        394            0    609.2kb        609.2kb
green  open   magento2_en_tracking_log_event_202302        7t87JBqJT4eyg9-qIxPcBw   1   0        521            0    561.3kb        561.3kb
green  open   magento2_de_tracking_log_event_202212        LKthFaGRTjmmE8p6PPJnCA   1   0       2239            0      2.3mb          2.3mb
green  open   magento2_en_tracking_log_event_202303        d45uF-O9RnaQZnoeoInTJQ   1   0        627            0    744.4kb        744.4kb
green  open   magento2_de_tracking_log_event_202211        XYw5pSHDRLmevPF4NjCuzg   1   0       4089            0      4.3mb          4.3mb
green  open   magento2_en_tracking_log_event_202304        hVfO_CQrTJKyvUi11TbImg   1   0        126            0    273.9kb        273.9kb
green  open   magento2_en_tracking_log_event_202206        fKF08dHiRj2HNEkeAAVmeA   1   0          4            0     13.3kb         13.3kb
green  open   magento2_de_tracking_log_event_202210        UrGCzz_rQ5iG0jOGAYdefg   1   0        696            0    867.6kb        867.6kb

**Comment by vahonc** [comment]
@stradd,

It is very strange that your problem does not appear on all categories, but only on some categories. It also seems to me that the problem you describe may consist of two separate problems. But it's hard to say anything specific right now.

You can try to enable Debug Mode for ElasticSuite and to analyze queries which send to Elasticsearch. You can get it from the `system.log` file if you activate the Debug mode of Elasticsuite in:
`Stores -> Configuration -> Elasticsuite -> Base settings -> Elasticsearch Client -> Enable Debug Mode`. Just looking for big JSON data. 

Also, please add more details about what you have before and after you added cronjob, and how exactly it solves your problem (maybe with screenshots).

BR,
Vadym
