### ISSUE TITLE
Product Search does not work for Quick Order B2B functionality. Magento EE 2.4.6 & Elasticsuite 2.11.0

### ISSUE THREAD

**Issue by dm-vasilenko** [Smile-SA/elasticsuite#2895]
The search on the quick order page does not work.

### Preconditions
Magento 2.4.6 EE
ElasticSuite Version : 2.11.0
Environment : Developer or Production, it does not work for any

Third party modules : no, clear magento

### Steps to reproduce
1. Install magento/extension-b2b
2. Enable Quick Order functionallity
3. Go to quick order page on FE
4. Try to find product by sku or name.

### Expected result
1. Search works correctly

### Actual result
1. `report.CRITICAL: TypeError: Smile\ElasticsuiteCore\Model\Search\RequestBuilder::getRequest(): Argument #1 ($searchCriteria) must be of type Smile\ElasticsuiteCore\Api\Search\SearchCriteriaInterface, Magento\Framework\Api\Search\SearchCriteria given, called in /var/www/src/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search.php on line 67 and defined in /var/www/src/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search/RequestBuilder.php:96`
2. 
![Screenshot from 2023-04-08 02-37-30](https://user-images.githubusercontent.com/51929620/230692464-ab75458b-96bc-4978-8edf-4bc6bff2b56e.png)

**Comment by romainruaud** [comment]
Hi, did you install 2.11.0 version of this module ? https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order

Regards

**Comment by dm-vasilenko** [comment]
Hi @romainruaud,
After trying to update the module via the composer, for some reason I can't load the latest version.
`Root composer.json requires smile/module-elasticsuite-quick-order ~2.11.0, found smile/module-elasticsuite-quick-order[dev-master, 1.0.0, 2.6.0, ..., 2.10.x-dev] but it does not match the constraint.`

I installed the latest version smile/module-elasticsuite-quick-order extension in app/code, the error is still reproduce.

**Comment by vimart-smile** [comment]
Hi to all. Any news?

**Comment by vahonc** [comment]
Hello @vimart-smile, @chre,

We are working on it.

BR,
Vadym

**Comment by romainruaud** [comment]
Fixed in the quick-order module, I'll publish a minor version asap : https://github.com/Smile-SA/magento2-module-elasticsuite-quick-order/commit/350c4d559830608259623e116d570cd4ecbff172
