### ISSUE TITLE
addAttributeToFilter('custom_attribute) is not working with store scopes

### ISSUE THREAD

**Issue by cctorres** [Smile-SA/elasticsuite#2896]
addAttributeToFilter is not working in store scope.

### Preconditions

I Want to apply a  filter to the collection products from a search query in the store. This filter depends on a custom attribute yes/no. This custom attribute has a store scope and can be difference between stores

Magento Version :
Magento EE 2.4.5-p1

ElasticSuite Version :
Elasticsearch: 7.16-0
ElastisSuite:  2.10.12.1

Environment :
Developer

Third party modules :

### Steps to reproduce

1. In Magento\Catalog\Model\Layer use a Plugin afterGetProductCollection
2. $result is a collection instance of Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection
3. Use $collection->addAttributeToFilter('custom_attribute, ['neq' => 1]);

### Expected result

1. Get the filtered $collection depends on store scope

### Actual result

1. I am getting the collection filtered by the last saving in the admin configuration (it does not matter which scope) and not the filtered collection related to the stores where I am searching.

**Comment by vahonc** [comment]
Hello @cctorres

Please specify which version of ElasticSuite you are using. Also, add more details about what you want to achieve and where you are trying to implement it because it's not entirely clear at the moment.

BR,
Vadym

**Comment by cctorres** [comment]
> Hello @cctorres
> 
> Please specify which version of ElasticSuite you are using. Also, add more details about what you want to achieve and where you are trying to implement it because it's not entirely clear at the moment.
> 
> BR, Vadym

Hi @vahonc , I Updated the main post. I hope to be clearer now, thanks!

**Comment by vahonc** [comment]
Hello @cctorres,

It looks like your problem may be related to the fact that your custom attribute is not indexed. Check the configuration of your attribute on the **Storefront properties** tab, especially if the flag `Use for Promo Rule Conditions` is set to `Yes`.

Also, check if your attribute is included in the product mapping, for this go to `Elasticsuite -> Indices` and view the mapping of your `*_catalog_product_*` index. 

>I am getting the collection filtered by the last saving in the admin configuration 

Not exactly understand what you mean by saying this.

Finally, I believe that instead of using `addAttributeToFilter` you should use `AddFieldToFilter`.

BR,
Vadym

**Comment by cctorres** [comment]
> Hello @cctorres,
> 
> It looks like your problem may be related to the fact that your custom attribute is not indexed. Check the configuration of your attribute on the **Storefront properties** tab, especially if the flag `Use for Promo Rule Conditions` is set to `Yes`.
> 
> Also, check if your attribute is included in the product mapping, for this go to `Elasticsuite -> Indices` and view the mapping of your `*_catalog_product_*` index.
> 
> > I am getting the collection filtered by the last saving in the admin configuration
> 
> Not exactly understand what you mean by saying this.
> 
> Finally, I believe that instead of using `addAttributeToFilter` you should use `AddFieldToFilter`.
> 
> BR, Vadym

Hi, Thanks for answering. I found why is happening. The custom attribute has static type and the column is in the 'Catalog_product_entity' table. So, I remove that attribute and drop the column in that table and create again the custom attribute with the store scope.
