### ISSUE TITLE
Error with magebees/module-layerednavigation

### ISSUE THREAD

**Issue by sb-ac** [Smile-SA/elasticsuite#2927]
We have a error with working two modules (smile/elasticsuite and magebees/module-layerednavigation):

`Error: Call to undefined method Magebees\Layerednavigation\Model\ResourceModel\Fulltext\Collection\Interceptor::addSortFilterParameters() in /home/user/project/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php:87`

Can you know how fix it?

Details:
* Magento 2.4.3
* ElasticSuite Open Source ver. 2.10.11
* Improved Layered Navigation For Magento 2 v 1.2.16 - https://www.magebees.com/improved-layered-navigation-pro-extension-for-magento-2.html

**Comment by romainruaud** [comment]
Looks like this : https://github.com/Smile-SA/elasticsuite/wiki/FAQ#i-have-a-php-fatal-error-on-catalogsearch-page-

However, support for third party extensions is out of the scope of this repository.

You should contact Magebees support.

Best regards
