### ISSUE TITLE
bin/magento index:reindex elasticsuite_categories_fulltext not indexing categpries

### ISSUE THREAD

**Issue by sunilnexialabs** [Smile-SA/elasticsuite#293]
I have installed latest elasticsuite and Magento 2 extension. Product indexing is working fine as expected but its not indexing categories.
http://localhost:9200/_all/category/_search
Response:
`{
"took": 4,
"timed_out": false,
"_shards": {
"total": 3,
"successful": 3,
"failed": 0
},
"hits": {
"total": 1,
"max_score": 1,
"hits": [
{
"_index": "magento2_default_catalog_category_20170116_123800",
"_type": "category",
"_id": "2",
"_score": 1,
"_source": {
"entity_id": "2",
"attribute_set_id": "3",
"parent_id": "1",
"created_at": "2016-09-25 11:29:26",
"updated_at": "2016-09-25 11:29:26",
"path": "1/2",
"position": "1",
"level": "1",
"children_count": "0"
}
}
]
}
}`
But I have 5 categories and sub-categories in system.

**Comment by afoucret** [comment]
Can you send us a screenshot of the category tree in order we take a look at this one ?

**Comment by sunilnexialabs** [comment]
@afoucret thanks for quick response. PFA
![step0002](https://cloud.githubusercontent.com/assets/24425752/21985342/2965260c-dc20-11e6-8c7c-9d251d753da8.png)

**Comment by afoucret** [comment]
Hi @sunilnexialabs,

The behavior is fully normal since your categories are not located under the root category of your website. So they are not browsable on your website (the default one). We are indexing only categories located under the root category.

If you place the categories under the default category (or the category configured as root of your website), they will be indexed.

As this behavior seems to be the expected one, I think the issue can be closed.

**Comment by sunilnexialabs** [comment]
@afoucret thanks for you guide. I added all categories into the default category, now its indexing. But why its not indexing categories name as its doing in case of product.
PFA
Category Structure:
![categories categories inventory products magento admin](https://cloud.githubusercontent.com/assets/24425752/22023593/cdbea9ea-dcec-11e6-990a-86c686eba7ed.png)

Indexed data:
![localhost 9200 _all category _search](https://cloud.githubusercontent.com/assets/24425752/22023619/e8af8f44-dcec-11e6-9a06-fefe37a92147.png)

**Comment by romainruaud** [comment]
Hello @sunilnexialabs , the index data you are showing are the ```*_default_*``` one. This is related to the "Default Store View". 

Are you sure your categories are existing for this default store view, and having values for their name on it ?

Regards,

**Comment by sunilnexialabs** [comment]
@romainruaud  thanks for your quick response. I don't have much idea on this. What I'm trying is to index categories and products into elastic search with their basic information like name, id etc.  @afoucret told me that categories are not indexing because they are not root category, so I added them into the default category which is right now my root category.
Its indexing but not indexing category name.
