### ISSUE TITLE
Is it necessary to run indexer:reindex manually for updating the carousels?

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2930]
I have a carousel in the home page, which displays the new products. In the carousel settings I have no conditions setup.
I have noticed that whenever I add new products this carousel doesn't display them unless I run manually from the command line
bin/magento indexer:reindex
bin/magento c:c

Is this the correct approach? I have cron running and I see that many indexing actions are scheduled, so I don't understand why I have to login to my terminal and run manual commands every time I add a product. It's counter productive. Is there any better way or at least a way to trigger the indexing without using terminal?

I'm using magento 2.4.6 and Elasticsuite 2.11.1

In index management I have all setup to "Update on save".

Any help will be much appreciated.

**Comment by romainruaud** [comment]
Hi @cptX 

you say that this carousel is supposed to display "new products", how is it configured to display the new products ?

Your index management should be on "Update on Schedule", and you should have your Magento cronjob running. That's the good practice and the Magento recommendation.

Starting from that, when you add a new product, it should be put and the index changelog, and then, reindexed by the cronjob.

Regards

**Comment by cptX** [comment]
Thanks @romainruaud I'll try it! In how many minutes with the default settings should be able to show in the carousel?

**Comment by cptX** [comment]
Thanks @romainruaud it works! My only fear now if for small amount of products as I have it is a big burdain for cron to check every minute for new products. Is this method for small number of products better than update on save? Also why update on save was not updating the carousels? Any idea?

**Comment by romainruaud** [comment]
It's not a problem that the crons run every minute. If it has nothing to do, it will just do nothing.

I don't know why the Update On Save mode was not dealing properly with the carousel, but it's probably more a Magento issue than an Elasticsuite issue.

Regards

**Comment by romainruaud** [comment]
I'm closing this as resolved.

Regards

**Comment by cptX** [comment]
Hi, please reopen this. According to your suggestions I changed the system to do indexing on schedule! But I noticed that the carousels with "Only discounted products" filter are still not updating automatically unless I run bin/magento i:rei manually.
First case: I had an discount rule. When the discount ended, the carousel was still showing the products that previously were on discount, even if there was no discount anymore.
Second case: I put a special price on a product but the carousel was not updated automatically
Cron is running correctly and indexing is configured to run on cron...
I still believe something is not correct in the automatic indexing of the elasticsuite "Only discounted products" filter...
