### ISSUE TITLE
Facet sort order issue on attributes with custom source model

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#2932]
### Preconditions

Magento Version : 2.4.6

ElasticSuite Version : 2.11.1 

Environment : production

### Steps to reproduce

1. Create a “month” attribute with custom source model, which returns month in calendar order : “January”, “February”, etc..
2. Set that attribute filterable.
3. Set facet sort order = Manual/admin

### Expected result

1. Month filter options are displayed in correct order : January, February, March, etc..

### Actual result

1. Month filter options are displayed in random order : March, December, October, etc..

### Comment

I guess that Admin sort is always relying on `sort_order` of `eav_attribute_option`, but that souldn’t be for source models other than `Magento\Eav\Model\Entity\Attribute\Source\Table`.

**Comment by romainruaud** [comment]
Hi @Nuranto 

yes maybe this is not working properly with source models returning an "hardcoded" list. We'll have to have a look.

That being said, why managing a list of month like this ? Having them created as options in the back-office would allow easy translation of the months labels.

Regards

**Comment by Nuranto** [comment]
It allows us to have the numeric month value (January = 1, ..., December = 12), which we then use - among other things - to display easily "From January to March and June to August" on product view, instead of "January,February,March,June,July,August" for example. 
The use of `__()` solves the translation issue.
Also, we have multiple attributes using that month source model, with, obviously, same static options.
It's quite similar to native attribute `country_of_manufacture` which is using a Country source model instead of basic options.

We have also another attribute which is actually fetching its options from database, in a way basic options cannot manage.
