### ISSUE TITLE
Unit Test is not Working. In Magento 2.4.5.p1

### ISSUE THREAD

**Issue by maheshmakwana-code** [Smile-SA/elasticsuite#2934]
When I run the unit test command for a core module I got the below error : 

![Screenshot from 2023-05-14 17-20-13 (1)](https://github.com/Smile-SA/elasticsuite/assets/57209161/e19719ca-dd56-4b77-b131-2b24eff298f0)

### Preconditions
Unit Testing command 

**./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist  vendor/smile/elasticsuite/src/module-elasticsuite-core/Test/Unit/**

Magento Version: 2.4.5.p-1  CE

ElasticSuite Version: 2.10.12.1

Environment: Developer

Third-party modules: No

### Steps to reproduce

1. Install Smile Module
2. Run setup:upgrade command
3. Then I run the Unit TEST command and it failed. 

### Expected result

1. Install Smile Module
2. Run setup:upgrade command
3. Then I run the Unit TEST command and it's a success.

### Actual result
1.  OutPut : 
![Screenshot from 2023-05-14 17-20-13 (2) (1)](https://github.com/Smile-SA/elasticsuite/assets/57209161/798cbfe1-3c12-49b9-89c9-d7b0f19b11d0)

**Comment by maheshmakwana-code** [comment]
I fixed Issue in this https://github.com/Smile-SA/elasticsuite/pull/2935

**Comment by romainruaud** [comment]
Hi @maheshmakwana-code 

we run all the Unit Tests as part of our "Integration" pipeline, and they do not fail with Magento 2.4.5-p1

What's your PHP version ?

**Comment by maheshmakwana-code** [comment]
PHP version 8.1 , Magento 2.4.5-p1 and Elasticsuite 2.11.x , I fixed this issue in  https://github.com/Smile-SA/elasticsuite/pull/2935

**Comment by bhashkarkaragthiya** [comment]
Magento 2.4.x not supporting setup script but module still having it. will you please convert into patch and db_schema file ?
