### ISSUE TITLE
Custom attribute created in module does not show up on layered navigation no matter what i do

### ISSUE THREAD

**Issue by glenelkinsdev** [Smile-SA/elasticsuite#2936]
I am using the elastic suite in magento 2.3.5 , elastic version 2.9.7 , my own module creates a custom attribute which is a product attribute as a multiselect, the options come from a custom source model:

```
$eavSetup->addAttribute(
            Product::ENTITY,
            'svgs',
            [
                'type' => 'varchar',
                'label' => 'Key Product Points',
                'input' => 'multiselect',
                'source' => 'MyVendor\MyModule\Model\Config\Attributes\SvgOptions',
                'backend'=> 'MyVendor\MyModule\Entity\Attribute\Backend\ArrayBackend',
                'frontend'=> 'MyVendor\MyModule\Model\Config\Attributes\SvgFrontendOptions',
                'required' => false,
                'sort_order' => 100,
                'global' => ScopedAttributeInterface::SCOPE_STORE,
                'group' => 'Key Product Points',
                'visible_on_front' => true,
                'used_in_product_listing' => true,
                'filterable'=>true,
                'searchable'=>true,
                'comparable'=>false,
                'user_defined'=>true,
                'apply_to' => 'simple,configurable,virtual,bundle,downloadable',
                'is_used_in_grid' => true,
                'is_visible_in_grid' => false,
                'is_filterable_in_grid' => true,
                'is_filterable_in_search'=>true
            ]
        );
```

The options show up on the product edit screen from my custom source model perfectly fine, and as you can see i use a slightly different model for the frontend as the options need to load in slightly different.

The issue is that no matter what i do my attribute will just not show up in the layered navigation when using elasticsuite. I have it set in admin to display on layered navigation. 

Really not sure what is going on, or what i may be missing?

**Comment by glenelkinsdev** [comment]
Conitnuing if i debug through Smile\ElasticsuiteCatalog\Model\Layer\Filter\Attribute.php in _getItemsData(), for example:

```
if($attribute->getAttributeCode() === 'svgs'){
            die("FOUND");
        }
```

And refresh the page, it does die out with FOUND on the screen, so the attribute is being picked up but just not being displayed?

**Comment by romainruaud** [comment]
Do you go through this line ? : 

https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php#L152

**Comment by glenelkinsdev** [comment]
> https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php#L152

Yes it gets through that line, but the $optionsFacetedData is empty so the foreach inside that if statement does nothing

**Comment by romainruaud** [comment]
Is your backend model for this attribute allowed to be indexed ? : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php#L65

**Comment by glenelkinsdev** [comment]
> Is your backend model for this attribute allowed to be indexed ? : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Eav/Indexer/Fulltext/Datasource/AbstractAttributeData.php#L65

> https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration

yes my backend model is Magento\Eav\Model\Entity\Attribute\Backend\ArrayBackend

![image](https://github.com/Smile-SA/elasticsuite/assets/99587729/d292a896-4533-4d49-9ada-0b8d9429118c)

**Comment by romainruaud** [comment]
Did you add some data to your products for this attribute ? 

What is the coverage rate of your attribute ? Maybe it does not cover enough products in your category.

**Comment by glenelkinsdev** [comment]
> Did you add some data to your products for this attribute ?
> 
> What is the coverage rate of your attribute ? Maybe it does not cover enough products in your category.

Yes i added options in the multiselect to a single test product, and the Facet coverage rate is set to 0 for the attribute in admin

**Comment by glenelkinsdev** [comment]
> Did you add some data to your products for this attribute ?
> 
> What is the coverage rate of your attribute ? Maybe it does not cover enough products in your category.

Conituing from my last reply, if i create a multi select in admin manually then it shows up on the filters, it's just my custom one using source models that doesn't, it's really odd that it's finding the options fine and the filter is recognised but somehow it won't display and i think it's something to do with $optionsFacetedData in _getItemsData()

**Comment by glenelkinsdev** [comment]
I have also looked a bit more into the getFacetedData() call on the Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection and it appears the bucket values are empty for my attribute

Could this be something wrong with my source model? I don't see how as it's building the options correctly but this bucket can't seem to see them

**Comment by romainruaud** [comment]
I close this one for being outdated. I don't know if you had any success implementing this in the end or not. Feel free to open another issue if you're still struggling.

Regards
