### ISSUE TITLE
Searching with keywords from all store views

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2940]
Is it possible during search on a store view to return results also for the keywords of another store view?
For example I have an eshop in greek and english. When in greek store view many people use english keywords to search items, for example the word "controller" which we use it also often in greek. Now the system will return zero results. Can I configure the system to search both store views with their corresponding keywords and then just return the specific products in the store view that is selected from the customer?

**Comment by vahonc** [comment]
Hello @cptX,

That's not possible, because we create each index per-store, due to the fact that data may be different per store (it can be due to the store locale, or just attribute scoped values that may differ, etc).

BR,
Vadym

**Comment by cptX** [comment]
That's a pity. I think there would be some benefits if combined.

**Comment by romainruaud** [comment]
Did you try to fix such behaviors by doing synonyms in mixed languages ? like "controller, ελεγκτής" ?

It would not be possible to search across all indices, because catalog structure might be completely different (categories, prices, etc...).

Regards

**Comment by romainruaud** [comment]
I close this one because question has been answered.

Regards
