### ISSUE TITLE
After installing Smile_Elasticsuits module "Sort category products" option is not showing in backend 

### ISSUE THREAD

**Issue by sanjaykesari28** [Smile-SA/elasticsuite#2951]
Hello Support,

We are using Smile_Elasticsuits module in our magento cloud project. After installing this extension, "Sort category products" option is not showing in backend on category page. As "Sort category products" is inbuilt feature of magento cloud version. Below is link to check "Sort category products"  functionality 
https://experienceleague.adobe.com/docs/commerce-admin/catalog/categories/products-in-category/category-products-sort.html?lang=en

We need to use "Sort category products"  feature. Please help to check how we can enable this with Smile_Elasticsuits extension.

Below are required details 
Magento Cloud Version - 2.4.5-p1
Website- https://www.lynaccs.com/en/

**Comment by vahonc** [comment]
Hello @sanjaykesari28,

Please refer to our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#manual-product-sorting-in-categories) about this.

BR,
Vadym

**Comment by vasinjirawutinunt0109** [comment]
Hi Vadym,

I have checked on the wiki but seems like the sort option does not match on our side. Can we disable the sort option from Elasticsuite and use the product sort from Magento itself?

Vasin

**Comment by vahonc** [comment]
Hi @vasinjirawutinunt0109,

Actually, it's not possible to use sorting for products in the categories previews, based on Magento legacy and ElasticSuite cause we use our own way for this. The drag-and-drop feature of the Smile_ElasticsuiteVirtualCategories module overrides that legacy behavior.

But if you really want to use the Magento sorting feature, you need to disable Smile_ElasticsuiteVirtualCategories module. However in this case you couldn't use the Virtual Categories feature.

BR,
Vadym
