### ISSUE TITLE
Automatic Related Products

### ISSUE THREAD

**Issue by suwubee** [Smile-SA/elasticsuite#2959]
Elasticsuite has powerful search and attribute analysis functions, why not use it for product association and related product recommendation?

Many plugins that do not use elasticsearch have poor performance and inaccurate product matching.

**Comment by suwubee** [comment]
> @suwubee that's exactly a feature of the Premium version.
> 
> Would you be interested ?
> 
> Regards

thanks, the price?

**Comment by romainruaud** [comment]
@suwubee you can write an email to elasticsuite@smile.fr and a salesguy will take care of you :)

Best regards
