### ISSUE TITLE
Category link in autocomplete not updated after change

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2960]
I have changed the url of a category but in autocomplete the suggested category is still displayed with the old url no matter what I do, cache clearing, reindexing etc...

### Preconditions

Magento Version : Magento 2.4.6 CE

ElasticSuite Version : 2.11.1

Environment : Production mode

Third party modules :

### Steps to reproduce

1. create a category with a specific url
2. reindex, clear caches etc, test in autocomplete the name of the category. If clicked should go successfully to the category page
3. change the url of the category
4. clear caches, reindex etc
5. test in autocomplete: click on the suggested category but now the page cannot be found!

### Expected result

1. The category url should be updated in elasticsuite autocomplete suggestions

### Actual result

1. [Screenshot, logs]
You can test it directly on my site.
Visit https://electrons.gr and write "Ανταλλακτικά για πατίνια" in the search field. The first category suggestion should be the wanted category but if you click it it returns the old url which was 
`https://electrons.gr/el/ilektrika-oximata/ilektrika-patinia/antallaktika`      and is not existing
instead of 
https://electrons.gr/el/ilektrika-oximata/ilektrika-patinia/antallaktika-axesouar which is the new one

URL should be updated in the elasticsuite system and not be based in url redirects to function...

**Comment by romainruaud** [comment]
@vahonc can you try to reproduce this one ?

It's just about changing a category URL and ensuring the new one is used in autocomplete.

Regards

**Comment by vahonc** [comment]
Hello @cptX,

I was not able to reproduce your issue on the fresh Magento environment.

Is this issue still relevant to you?

BR,
Vadym
