### ISSUE TITLE
Default value for 'display_pattern' causes issues with attribute sliders

### ISSUE THREAD

**Issue by bosch-manuel** [Smile-SA/elasticsuite#2965]
In Version 2.10.14 there was a fix for 
Add missing propertymapping for eav attribute creation/updates by @brosenberger in [https://github.com/Smile-SA/elasticsuite/pull/2804](https://github.com/Smile-SA/elasticsuite/pull/2804) 

This introduced a default value for the property display_pattern of EAV Attributes.
https://github.com/Smile-SA/elasticsuite/blob/39607f9e34103f587d5609a21cf1129612d391df/src/module-elasticsuite-catalog/Model/ResourceModel/Setup/PropertyMapper.php#L42 

This 'magic number' 10 destroys the <from> - <to> labels of all sliders in layered navigation, when they are created programmatically via EavSetup. This pop up after switching from 2.10.13 to 2.10.15 and running our custom attribute import, which makes use of the EAVSetup, to create/updates eav-attributes.

Creating attributes manually in backend does not lead to this issue.

### Preconditions
Magento Version 2.4.5-pre1
ElasticSuite Version: 2.10.15
Environment : production

### Steps to reproduce

1. Programmatically create new attribute via \Magento\Eav\Setup\EavSetup::addAttribute(...) without defining display_pattern
``` 
$eavSetup->addAttribute(
              "catalog_product",
              "test_decimal",
              [
                    'input' => "price",
                    'type' => "decimal",
                    'group' => "General",
                    'required' =>0,
                    'searchable' =>1,
                    'user_defined' => 1,
                    'visible_on_front' =>1,
                    'visible => 1,
                    'label'=> "Höhe (mm)"
                 ]
);
```
3. Assign it to some products
4.  Make sure it will be listed as a filter somewhere in the frontend

### Expected result
Attribute's <from> - <to> labels should have proper values
<img width="368" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/3950460/59e15d81-20a7-434b-99f6-4bad43dad206">

### Actual result
Attribute's <from> - <to> labels show 'magic number' 10
<img width="390" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/3950460/9ee5b161-bd51-4833-9200-321e59c1a135">

### Possible Fix
As far as I understand your code and the purpose of the 'display_pattern' property, it might be better to use 'null' as default value.

**Comment by vahonc** [comment]
Hello @bosch-manuel,

I was able to reproduce this issue, indeed when we try to create product attributes programmatically via EavSetup without defining `display_pattern` the "magic number" 10 destroys the labels of the sliders in layered navigation.

Can you test my fix for the newest custom attribute import? For the already existing attributes which were programmatically created you can update the default value for the `display_pattern` property in your DB. You will need to change '10' value to _NULL_ in the `catalog_eav_attribute` table.

BR,
Vadym

**Comment by bosch-manuel** [comment]
Hello @vahonc ,

your fix solves the issue. Thanks a lot!
