### ISSUE TITLE
Price filter not showing the price range

### ISSUE THREAD

**Issue by utsav-cinovic** [Smile-SA/elasticsuite#2966]
In the layered navigation the price filter is not showing the price range, it is showing static price values with a count.
### Preconditions

PWA studio (venia) as frontend
Magento 2.4.3 as Backend
PHP 7.4.19

Magento Version : Magento 2.4.3 CE

ElasticSuite Version : ~2.10.13 in composer version ([ElasticSuite] Open Source ver. 2.10.15.1 in admin)

Environment : Developer & Production both

Third party modules : 

### Steps to reproduce

1. after enabling the ES suite on the fronted, it shows static prices in layered navigation.
2.
3.

### Expected result

1. it should display the price range on PLP layered navigation as 0 -100(1), 101-200(4), etc. right now it's showing only static prices as 300(1), 500(4), etc.

### Actual result

1. [Screenshot, logs]
<img width="318" alt="Screenshot 2023-06-12 at 3 25 39 PM" src="https://github.com/Smile-SA/elasticsuite/assets/70888269/c615c8cd-55e9-4b85-8dae-2cd47775d531">

**Comment by vahonc** [comment]
Hello @utsav-cinovic,

Most likely you need to redesign your price filter template. My guess is that it uses checkboxes, which in turn causes this problem. You can provide us with some of the code related to this, perhaps it will help to better understand the problem.

BR,
Vadym

**Comment by utsav-cinovic** [comment]
Hii @vahonc ,

We are getting graphQL aggregation response like shown below screenshot, This response we are getting after adding the ElasticSuite module.

<img width="1154" alt="Screenshot 2023-06-14 at 3 52 54 PM" src="https://github.com/Smile-SA/elasticsuite/assets/70888269/5edd6ab8-7c29-41a6-8905-d9808dc32d47">

But what we need is a price range filter, the default magento2 graphQL from Elasticsearch provides a range filter. Can you please let me know how we can achieve this?

<img width="1175" alt="Screenshot 2023-06-14 at 3 56 35 PM" src="https://github.com/Smile-SA/elasticsuite/assets/70888269/e4f3fa03-c1fc-4ace-b173-9cedd2816703">

Also, if it is possible to achieve this price slider?

**Comment by romainruaud** [comment]
Hi @utsav-cinovic 

With Elasticsuite, you do not have price ranges, we're returning the results so that you can build a price slider (price histogram).

You can do the price slider by yourself in the Front-Office application.

We do this in Luma theme like this : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/view/frontend/web/js/range-slider-widget.js

Regards
