### ISSUE TITLE
How Do I Get Layered Navigation displayed on PLP for each category for REST API

### ISSUE THREAD

**Issue by kybanhmi** [Smile-SA/elasticsuite#2971]
I'm creating custom class for REST API to get layered navigation filter displayed on PLP by category id,

I tried classes below but it return wrong data

use Magento\Catalog\Model\Layer\Category\FilterableAttributeList;
use Magento\Catalog\Model\Layer\FilterListFactory;
use Magento\Catalog\Model\Layer\Resolver as layerResolver;

How can i get layered filter right as displayed

Ex: displayed color attribute in PLP: 5 colors
but rest api return empty array

![image](https://github.com/Smile-SA/elasticsuite/assets/99716823/4d473bc5-f53e-46fa-8cd7-758a82a31e40)

**Comment by vahonc** [comment]
Hello @kybanhmi,

First of all, please respect the issue template and give detailed steps about how to reproduce the issue or explain what exactly you want to achieve.

Otherwise, it's unlikely someone from the team will have a look at it. 

For me, it is not clear the purpose of creation and tasks.

BR,
Vadym

**Comment by romainruaud** [comment]
Hi @kybanhmi 

what do you have as result when you use the legacy REST api ?

The one located at `/V1/search` ? 

https://adobe-commerce.redoc.ly/2.4.6-guest/tag/search/#operation/GetV1Search

Do you have aggregations as well ?

Regards

**Comment by kybanhmi** [comment]
I mean i wanna get filters displayed on PLP for each category in my custom REST API

![image](https://github.com/Smile-SA/elasticsuite/assets/99716823/124c0dc7-187c-4393-aea3-263c2bab02ba)

**Comment by romainruaud** [comment]
I close, we do not provide support for custom code in this repository as part of our Open Source support policy.

Regards
