### ISSUE TITLE
"Only discounted products" filter doesn't update automatically on cron

### ISSUE THREAD

**Issue by cptX** [Smile-SA/elasticsuite#2972]
I changed my system to do indexing on schedule! But I noticed that the carousels with "Only discounted products" filter are still not updating automatically unless I run bin/magento i:rei manually.
First case: I had a discount rule. When the discount ended, the carousel was still showing the products that previously were on discount, even if there was no discount anymore.
Second case: I put a special price on a product but the carousel was not updated automatically, so it was not showing the product.
Cron is running correctly and indexing is configured to run on cron...

I believe something is not correct in the automatic indexing of the elasticsuite "Only discounted products" filter...
I really would like to avoid logging in terminal for indexing everytime I do a price change...

### Preconditions
Magento Version : CE
ElasticSuite Version : 2.11.1
Environment : 2.4.6

Third party modules :

### Steps to reproduce

1. Create a carousel with "Only discounted products" filter
2. Create a product with a special price. Wait some minutes for indexing to run on cron.
3. Check carousel. It is not showing the discounted product.
4. Now go to terminal and run bin/magento i:rei
5. Carousel now correctly shows the discounted product

### Expected result

1. "Only discounted products" filter on carousels should update automatically on cron

**Comment by vahonc** [comment]
@cptX,

I was not able to reproduce this issue on the fresh Magento environment, all works as we expected without reindexation.

Are you sure that you added your cronjob to the system crontab?

Also, please check if there is no cached data (Varnish, etc), it could depend on where exactly you tried to add your product carousel (page, widget, block).

BR,
Vadym
