### ISSUE TITLE
Error in compilation step with Magento2 2.4.7-beta1

### ISSUE THREAD

**Issue by brosenberger** [Smile-SA/elasticsuite#2973]
There is an error with the RelevanceConfig compilation step with the newes Magento2 (beta) version (2.4.7-beta1):

Compilation was started.
%message% 0/9 [>---------------------------]   0% < 1 sec 77.0 MiBProxies code generation... 0/9 [>------------------------]   0% < 1 sec 77.0 MiB
Proxies code generation... 1/9 [==>----------------------]  11% < 1 sec 81.0 MiB
Repositories code generation... 1/9 [==>-----------------]  11% < 1 sec 81.0 MiB
Fatal error: Declaration of Smile\ElasticsuiteCore\Model\ResourceModel\Search\Request\RelevanceConfig::_construct() must be compatible with Magento\Config\Model\ResourceModel\Config::_construct(?Magento\Framework\MessageQueue\PoisonPill\PoisonPillPutInterface $pillPut = null) in /builds/stage-m-demo/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php on line 98

there has been a new constructor argument been added in https://github.com/magento/magento2/commit/e6f90adbddc7775508a6770c874811d7ee34b2f9

### Preconditions

Magento Version : 2.4.7-beta1

ElasticSuite Version : latest

### Steps to reproduce

1. upgrade magento to 2.4.7-beta
2. call bin/magento setup:di:compile

### Expected result

1.

### Actual result

1. [Screenshot, logs]
Compilation was started.
%message% 0/9 [>---------------------------]   0% < 1 sec 77.0 MiBProxies code generation... 0/9 [>------------------------]   0% < 1 sec 77.0 MiB
Proxies code generation... 1/9 [==>----------------------]  11% < 1 sec 81.0 MiB
Repositories code generation... 1/9 [==>-----------------]  11% < 1 sec 81.0 MiB
Fatal error: Declaration of Smile\ElasticsuiteCore\Model\ResourceModel\Search\Request\RelevanceConfig::_construct() must be compatible with Magento\Config\Model\ResourceModel\Config::_construct(?Magento\Framework\MessageQueue\PoisonPill\PoisonPillPutInterface $pillPut = null) in /builds/stage-m-demo/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php on line 98

**Comment by romainruaud** [comment]
Hi @brosenberger 

we'll begin to test with Magento 2.4.7-beta1, thanks for reporting this.

That being said, 2.4.7-beta2 is scheduled for october, so the final release of 2.4.7 will probably be at the end of the year. 

We'll engage some time on it but it's not a priority actually because we're afraid that Magento changes everything between beta1 and beta2 :)

regards

**Comment by peterjaap** [comment]
I fixed the compilation issue with this;

```
diff --git a/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php b/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php
index 0e83b63..c208094 100644
--- a/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php
+++ b/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php
@@ -95,7 +95,7 @@ class RelevanceConfig extends \Magento\Config\Model\ResourceModel\Config
      *
      * @return void
      */
-    protected function _construct()
+    protected function _construct(?\Magento\Framework\MessageQueue\PoisonPill\PoisonPillPutInterface $pillPut = null)
     {
         $this->_init('smile_elasticsuite_relevance_config_data', 'config_id');
     }

```

**Comment by ProxiBlue** [comment]
Just as a note:

I had this same issue installing Mage-OS 1.0.1, which is (as far as I know) Magento 2.4.6.
Possible this issue comes with a 2.4.6 patch-set,  and is not only prevalent on the new 2.4.7 beta version.

The patch as supplied by @peterjaap worked to solve issue.
