### ISSUE TITLE
Want to search products by category

### ISSUE THREAD

**Issue by ia-Gaury** [Smile-SA/elasticsuite#2974]
### Preconditions
Magento 2.4.1

Magento Version : Magento CE

ElasticSuite Version : 3.0

Environment : Production

### Steps to reproduce

Create attribute name "Apparel" with values - Shirts , Trousers and Ties
![image](https://github.com/Smile-SA/elasticsuite/assets/79962372/7c718c6e-aae1-4ded-b587-097e6dab562b)

Create product with below names

Linen Shirts
Linen Trouser
Now search for "Linen Shirts"

### Expected result
it should show attribute base search. For eg. If we search "linen" it should show result like "Linen in Shirts", "Linen in Trousers", etc

### Actual result
its searching in product names first and showing result datewise(product uploaded date)

![image](https://github.com/Smile-SA/elasticsuite/assets/79962372/8eb5adf0-5cd0-474c-ae60-dfa8a40f79a5)

**Comment by romainruaud** [comment]
Hi @ia-Gaury 

I still don't get it.

If you search Linen, you will match "Linen". There is no "Linen in Shirts" or "Linen in Trousers" feature in Elasticsuite.

It's unclear what you want to achieve.

What do you have if you search for "Linen Shirts" ?
