### ISSUE TITLE
How DO I GET ATTRIBUTE FILTER ON PHP 

### ISSUE THREAD

**Issue by kybanhmi** [Smile-SA/elasticsuite#2976]
I WANT TO GET VALUE OF "THIS.ITEMS" VARIABLE ON FILE attribute-fiter.js IN MY CUSTOM PHP CLASS

![image](https://github.com/Smile-SA/elasticsuite/assets/99716823/8ac39f44-cf2d-47ff-a588-5cde29942360)

**Comment by romainruaud** [comment]
Not clear, no respect of the issue pattern, not answered.
