### ISSUE TITLE
Is elasticsuite support magento cloud 245 version ?

### ISSUE THREAD

**Issue by bhashkarkaragthiya** [Smile-SA/elasticsuite#2977]
I had tried to install https://github.com/Smile-SA/elasticsuite/tree/2.10.x/src on magento cloud integration environment but deployment process not able to execute UpgradeData.php, UpgradeSchema.php,InstallData.php and InstallSchema.php

Any idea how to resolve above issue ?

**Comment by romainruaud** [comment]
@bhashkarkaragthiya please provide details.

What's the error you're seeing when deploying ?

Regards

**Comment by bhashkarkaragthiya** [comment]
@romainruaud i am getting below error as it's having install script in setup folder. 

{"0":"Please upgrade your database: Run \"bin\/magento setup:upgrade\" from the Magento root directory.\nThe following modules are outdated:\nSmile_ElasticsuiteCatalog schema: current version - 1.6.3, required version - 1.7.0\nSmile_ElasticsuiteCatalog data: current version - 1.6.3, required version - 1.7.0","1":"

**Comment by vahonc** [comment]
Hello @bhashkarkaragthiya,

How do you install ElasticSuite via Composer or smth another way?

Have you run this command `bin/magento setup:upgrade` after installing ElasticSuite?  

BR,
Vadym

**Comment by bhashkarkaragthiya** [comment]
@vahonc i had install ElasticSuite via composer and during bin/magento setup:upgrade getting below error magento cloud integration environment.

Magento version : 2.4.5-p2

`{"0":"Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.\nThe following modules are outdated:\nSmile_ElasticsuiteCatalog schema: current version - 1.6.3, required version - 1.7.0\nSmile_ElasticsuiteCatalog data: current version - 1.6.3, required version - 1.7.0","1":"`

**Comment by romainruaud** [comment]
Hi @bhashkarkaragthiya 

so if you launch a setup:upgrade what's the results ? That's what Magento is asking you to do.

Regards
