### ISSUE TITLE
Attribute Export: Missing "Facet internal logic" in CSV

### ISSUE THREAD

**Issue by FadedOut** [Smile-SA/elasticsuite#2978]
### Preconditions
Magento Version : CE 2.4.6-p1
ElasticSuite Version : 2.11.2 (latest)
Environment : Developer mode
Third party modules :
The only module that "might" have an effect on this could be: Bss_CustomProductAttributeExport, but all other fields show properly when exporting the smile attribute values - so I don't believe this should be an issue.

### Steps to reproduce
1. Set up attributes along with smile values for said attributes
2. Export to CSV
3. Check CSV

### Expected result
1. The column named "facet_boolean_logic" should [I believe] have the logic chosen, OR/AND, showing. Unless that column/field does not relate to the option named "Facet internal logic"?

### Actual result

1. The column named "facet_boolean_logic" has nothing in it, all fields/values are empty.
2. ![magento-smile-boolean-logic-missing](https://github.com/Smile-SA/elasticsuite/assets/12685113/b1389499-d29b-4cce-8fcf-2583566a5918)

I attempted to place the following into the column fields but it didn't change the value to what I wanted (from OR to AND, vice versa).
or
and
_or
_and

**Comment by vahonc** [comment]
Hello @FadedOut,

Provide output or screenshot of what you have in the specified column in your DB by running this query:
`SELECT * FROM catalog_eav_attribute;`

BTW, normally this column should have **0** or **1** values, where 0 => OR, 1 => AND.

BR,
Vadym

**Comment by FadedOut** [comment]
Hi Vadym,

I have the SQL file and turned it into CSV as well so you can decipher using both. It appears that column is missing entirely in the DB, I think.

**Comment by FadedOut** [comment]
CSV:
[fadedout-smile-2-11-2-catalog_eav_attribute.csv](https://github.com/Smile-SA/elasticsuite/files/11839425/fadedout-smile-2-11-2-catalog_eav_attribute.csv)

SQL:
[fadedout-smile-2-11-2-catalog_eav_attribute.zip](https://github.com/Smile-SA/elasticsuite/files/11839445/fadedout-smile-2-11-2-catalog_eav_attribute.zip)

**Comment by vahonc** [comment]
@FadedOut,

Yeap, I don't see `facet_boolean_logic` column in your files. It's very strange and probably this is where you problem.

BR,
Vadym

**Comment by FadedOut** [comment]
Hm well this was a fresh install of 2.4.6-p1 that I added smile elasticsuite to. So possibly something up with the install scripts? 

Is there a way I can add the column so it that will function properly? Or is there a more in-depth process involved than simply adding the column.

TIA

**Comment by vahonc** [comment]
I will try to reproduce this on a fresh 2.4.6-p1 and elasticsuite.

BR,
Vadym
