### ISSUE TITLE
Attribute Option: Facet internal logic - Won't Change from OR to AND

### ISSUE THREAD

**Issue by FadedOut** [Smile-SA/elasticsuite#2979]
### Preconditions
Magento Version : CE 2.4.6-p1
ElasticSuite Version : 2.11.2 (latest)
Environment : Developer mode

### Steps to reproduce
1. Create attribute (dropdown or multiple select)
2. Add a few values
3. Change "Facet internal logic" from Logical OR -to- Logical AND
4. Save
5. Check field for change

### Expected result
1. It should change after saving

### Actual result
1. It does not change. It stays on "Logical OR (default)". It says it saved the changes successfully, so there are no errors or logs to report on. It just simply does not save the change. There is a debug log that I can post, not sure if it will help:

`main.DEBUG: cache_invalidate:  {"method":"POST","url":"/catalog/product_attribute/save/key/.../attribute_id/173/back/edit/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"}} []`

`main.DEBUG: cache_invalidate:  {"method":"POST","url":"/catalog/product_attribute/save/key/.../attribute_id/173/back/edit/","invalidateInfo":{"tags":["EAV","EAV_ATTRIBUTE"],"mode":"matchingAnyTag"}} []`

`main.DEBUG: cache_invalidate:  {"method":"POST","url":"/catalog/product_attribute/save/key/.../attribute_id/173/back/edit/","invalidateInfo":{"tags":["EAV_ATTRIBUTE"],"mode":"matchingAnyTag"}} []`

`main.DEBUG: cache_invalidate:  {"method":"POST","url":"/catalog/product_attribute/save/key/.../attribute_id/173/back/edit/","invalidateInfo":{"tags":["TRANSLATE"],"mode":"matchingTag"}} []`

**Comment by FadedOut** [comment]
These two might be related, maybe why the values won't show up in the exported file, because this value isn't working properly.

https://github.com/Smile-SA/elasticsuite/issues/2978

**Comment by romainruaud** [comment]
This column is not defined in the xml file : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/etc/db_schema.xml#L21

This may explain this issue.

**Comment by FadedOut** [comment]
Is there something you'd like me to test? I could probably attempt to add that column but I feel it probably wouldn't be done correctly.

**Comment by vahonc** [comment]
@FadedOut,

We have fixed this issue in the [#2978](https://github.com/Smile-SA/elasticsuite/issues/2978). And we planning a new release very soon.

So stay tuned!

BR,
Vadym

**Comment by FadedOut** [comment]
Excellent, much appreciate the fix. And it looks like a pretty nice update too :). Will report back if there are any issues. 

Thanks again!
