### ISSUE TITLE
Initialize mandatory selected attributes for Elasticsuite's Product\Fulltext\Collection for Virtual Categories

### ISSUE THREAD

**Issue by nige-one** [Smile-SA/elasticsuite#2983]
I was trying to use `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection` for some custom logic beside using the **Virtual Category** functionality. It did not work at the beginning and had different wrong outcomes. I am aware of the use of `\Magento\Catalog\Model\Layer` to mock FE behaviour, but this does not look clean to me.

A clean solution should be the use of `\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection` and using it like intended, w/o any hacks or special initialization in terms of **Virtual Categories**.

After adding these attributes to my collection instance everything worked as expected.
```
        $subCategories = $category->getCategories($category->getId(), 0, false, true, false);
        return $subCategories
            ...
            // ElasticSuite mandatory attributes
            ->addAttributeToSelect(['is_virtual_category', 'virtual_rule'])
            ...
```
These attributes are referenced in
https://github.com/Smile-SA/elasticsuite/blob/39607f9e34103f587d5609a21cf1129612d391df/src/module-elasticsuite-virtual-category/Plugin/Collection/AddVirtualCategoryQuery.php#L57
and
https://github.com/Smile-SA/elasticsuite/blob/39607f9e34103f587d5609a21cf1129612d391df/src/module-elasticsuite-virtual-category/Model/Category/Attribute/VirtualRule/ReadHandler.php#L61

when the collection is actually loaded.

It would be great and is also referenced in other issues if we could make the mandatory attributes loaded by default, so the collection works with **Virtual Categories** as expected.

If you follow my idea I will create a PR.

**Comment by romainruaud** [comment]
I'm not sure to completely understand what you'd like to achieve.

Maybe propose a PR with your changes, it would be probably more clear for me to understand.

Regards
