### ISSUE TITLE
Search Analytics : Exclude IP-address

### ISSUE THREAD

**Issue by gerrits-ecommerce** [Smile-SA/elasticsuite#2990]
When we are using the Search Analytics of Elastic suite, every session is tracked. This is normal behavior, but we would like to exclude some IP-addresses (including our own) to get a better overview of the actual search results of customers.

Is it possible to exclude certain IP-addresses from the search analytics?

**Comment by vahonc** [comment]
Hello @gerrits-ecommerce,

Unfortunately, excluding IP addresses is not possible out of the box. And this requires additional customization in the Back Office. 

Therefore, you need to look for other ways to solve this problem, for example, dropping IP requests at the Nginx, Varnish, or on the browser level using some additional plugins. I'm pretty sure that they exist.

BR,
Vadym
