### ISSUE TITLE
Options in category filter from variants (simple)

### ISSUE THREAD

**Issue by Thorug** [Smile-SA/elasticsuite#2994]
We have attribute with sizes for variants but i dont see this attribute in category filter. Everything in administration is set correctly.
Can elasticsuite show these values in category filter? or it show only values from configurable products?
https://www.wayfarer.sk/muzi/oblecenie

Thank you.

**Comment by vahonc** [comment]
Hi @Thorug,

First of all, please respect the issue template and give details about your environment and steps with screenshots on how to reproduce this issue.

Otherwise, it's unlikely someone from the team will have a look at it.

BR,
Vadym

**Comment by romainruaud** [comment]
Hello @Thorug 

According to this line : 

https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php#L152

The `$minCount < $productCollection->getSize()`

If you have a category, were all your products do have all the available values for the "Size" attribute, this filter will not be considered useful and not displayed.

In that case, to check it, you can try to set this filter to "Always visible" in this category edit screen. This will allow bypassing the rule described above.
