### ISSUE TITLE
Unknown column is_display_rel_no_follow

### ISSUE THREAD

**Issue by sheepfy** [Smile-SA/elasticsuite#3005]
Fresh install clean magento 2.4.6-p1 (or 2.4.5 i think, I tried on 2.4.6-p1)
Deploy sample data - not sure if relevant
Basic stack (es, redis, mysql8, php8.1 etc)
run setup upgrade, make sure clean magento works
composer require smile/elasticsuite ~2.11.0 (will install 2.11.3.X)
run setup upgrade

Expected result:
- setup upgrade works
Actual result:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_display_rel_no_follow' in 'field list', query was: UPDATE `catalog_eav_attribute` SET `is_display_rel_nofollow` = is_display_rel_no_follow

![image](https://github.com/Smile-SA/elasticsuite/assets/17467949/8311a36e-d816-47bc-9277-8066ee7a340c)

**Comment by romainruaud** [comment]
@vahonc can you try to reproduce this ? 

We should probably remove this line after all : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/etc/db_schema.xml#L81

**Comment by vahonc** [comment]
Ok, I will check it out.
