### ISSUE TITLE
Move out of stock product at the end of pages in catalog

### ISSUE THREAD

**Issue by felek000** [Smile-SA/elasticsuite#3006]
I would like to move out of stock product to the end of catalog.

I found that module responsible is `Smile_ElasticsuiteCatalog`  *setup_version="1.5.1"*

`\Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::prepareRequest`

In line *$sortOrders = $this->prepareSortOrders();* this i think is part that should be added changed.

But to move that product i require collection.  Example code that change this on collection.
It requires joins to get extra data.
```
$this->_productCollection->getSelect()  
->joinLeft(  
['cataloginventory_stock_item'],  
'cataloginventory_stock_item.product_id = e.entity_id',  
['qty']  
)  
->joinLeft(  
['cataloginventory_stock_status'],  
'cataloginventory_stock_status.product_id = e.entity_id',  
['stock_status']  
)  
->order('stock_status desc')
```
Thx for help.

**Comment by vahonc** [comment]
Hello @felek000,

There is no need for any additional code to do this.

Just take some inspiration from this [issue](https://github.com/Smile-SA/elasticsuite/issues/2142).

BR,
Vadym

**Comment by felek000** [comment]
@vahonc looks nice. But i don`t see any were in backed feature like this. Is this exist in version `1.5.1` or this requires additional module ?

**Comment by vahonc** [comment]
@felek000,

Which version of Magento and ElasticSuite you are using? 

For getting the version of ElasticSuite you can use this command: `composer info | grep elasticsuite`

BR,
Vadym

**Comment by felek000** [comment]
@vahonc i have installed this in app/code.
Module name `Smile_ElasticsuiteCatalog`  setup version is *1.5.1*

**Comment by vahonc** [comment]
@felek000,

We don't support "app/code" setup or from a zip archive, that's why in the Wiki is only speaking about installing through composer. You should install via composer as per the Magento good practices.

BR,
Vadym

**Comment by felek000** [comment]
@vahonc so based on installation type i have some features and some not ? That some think new for me. Module was added by template claue and was install like so. 
So to the original question is any way to programmatic add plugin to alter only that feature ?

**Comment by romainruaud** [comment]
Hi @felek000 

you should install Elasticsuite via composer, that's the only supported method, and the only good practice as per the Magento guidelines.

If you install the whole Elasticsuite package, you will have access to the Optimizer module, which allows you to create boost on "in stock products" as detailed in the linked issue.

I close because this is not an issue, what you want to achieve is definitely supported out of the box.

Regards
