### ISSUE TITLE
Problem after installing extension in Magento 2.4.6-p1

### ISSUE THREAD

**Issue by predragstojiljkovic** [Smile-SA/elasticsuite#3008]
- 

### Preconditions
Magento Version : 2.4.6-p1

ElasticSuite Version : 2.11

Elasticsearch version: 8.4.0

Environment : Production mode

Third party modules : Porto theme

### Steps to reproduce
1. Install the extension using composer require smile/elasticsuite ~2.11.0
2. Try to perform bin/magento setup:upgrade
3. Getting the following error:  There are no commands defined in the "setup" namespace.
4. Try to perform bin/magento setup:di:compile
5. Getting the following error:  There are no commands defined in the "setup:di" namespace.
6. Perform bin/magento list
7. Getting the following output: 
In ServiceManager.php line 649:
Service with name "Magento\Setup\Console\Command\ConfigSetCommand" could not be created. Reason: Impossible to process constructor argument Parameter #0 [ <required> Elasticsearch\ClientBuilder $clientBuilder ] of Smile\ElasticsuiteCore\Client\ClientBuilder class

In ClassReader.php line 57:
Impossible to process constructor argument Parameter #0 [ <required> Elasticsearch\ClientBuilder $clientBuilder ] of Smile\ElasticsuiteCore\Client\ClientBuilder class

In GetParameterClassTrait.php line 34:
Class "Elasticsearch\ClientBuilder" does not exist

### Expected result

1. Install the extension using composer require smile/elasticsuite ~2.11.0
2. Try to perform bin/magento setup:upgrade
3. Upgrade succeeds

### Actual result

1. After installation of extension I was unable to perform setup:upgrade nor setup:di:compile
2. After I removed the extension using composer remove smile/elasticsuite everything started working well again

**Comment by predragstojiljkovic** [comment]
Yes. I did `composer require magento/module-elasticsearch-8 --with-all-dependencies`.
Will `composer require elasticsearch/elasticsearch ~7.17.0` work with Elasticsearch 8.4.0 (since we can not change the version of Elasticsearch itself on that server and not allowed to install a different one)?

**Comment by romainruaud** [comment]
Yes, the 7.x client works well with the v8.x of Elasticsearch

**Comment by vahonc** [comment]
@predragstojiljkovic,

Have you solved your problem?

BR,
Vadym

**Comment by predragstojiljkovic** [comment]
No, not really. Removing magento/module-elasticsearch-8 and installing elasticsearch/elasticsearch ~7.17.0 and smile/elasticsuite ~2.11.0 caused many other problems. I tried fixing it one by one, but it took too long. So I reverted it all and gave up on installing smile/elasticsuite for now. I hope you will release a new version soon  that will work with magento/module-elasticsearch-8 :) I'll be patient until then...

**Comment by romainruaud** [comment]
@predragstojiljkovic we've plenty of projects running with Magento 2.4.6 and Elasticsuite 2.11.x with the Elasticsearch 7.17 client.

That's also the stack we test on our CI jobs.

Can you please give us more details regarding the issues you've had after removing magento/module-elasticsearch-8 and downgrading the PHP client ?

Regards
