### ISSUE TITLE
tracking_log_session index does not exist yet. Make sure everything is reindexed | Magento Cloud | 2.4.4-p2

### ISSUE THREAD

**Issue by mkkkashif** [Smile-SA/elasticsuite#3009]
Dear Support,
The Elasticsuite "**tracking**" feature is enabled. The "**Search Usage Analytics**" page is showing results but "**Popular search terms**" and "**search terms**" are empty.

A following message is appearing on the page top.
"tracking_log_session index does not exist yet. Make sure everything is reindexed."

A screenshot is attached. 
Please check and resolve.

**Instance:**
Adobe Commerce ver. 2.4.4-p2
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.17.1

Thanks,
![screenshot-www westlab com au-2023 07 17-23_31_49](https://github.com/Smile-SA/elasticsuite/assets/9351168/cf9ea251-a9c5-45dd-8413-c27a7cee7c2a)

**Comment by romainruaud** [comment]
Hi @mkkkashif is this a Magento Cloud ?

**Comment by mkkkashif** [comment]
> Hi @mkkkashif is this a Magento Cloud ?

Yes

**Comment by mkkkashif** [comment]
Issue resolved.

I submitted a ticket to the Magento Cloud support. I was getting a following error under "cron.log".

**report.ERROR: {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"cannot execute [inline] scripts"}},"status":400} [] []**

Above error was resolved after enabling "Inline" and "stored" scripts on the cluster Elasticsearch instance.
After above error resolving the "Elasticsuite" index message disappeared and  "Popular search terms" and "search terms" started appearing.

Thanks,
![screenshot-www westlab com au-2023 07 18-15_04_58](https://github.com/Smile-SA/elasticsuite/assets/9351168/8cb82b43-3a53-4852-be11-6030d43bfe25)

**Comment by mkkkashif** [comment]
Issue resolved.
Thanks,
