### ISSUE TITLE
Reindexing issue - this action would add [1] total shards, but the cluster currently has [1204]/[1000] maximum open shards

### ISSUE THREAD

**Issue by zsspoldzielnia** [Smile-SA/elasticsuite#3012]
### Preconditions

While reindexing, we are facing this error:

_this action would add [1] total shards, but the cluster currently has [1004]/[1000] maximum open shards_

It occurs for:

1. Catalog Search index
2. ElasticSuite Category Indexing
3. ElasticSuite Thesaurus Indexing

Magento Version : CE 2.4.5-p1

ElasticSuite Version : 2.10.14
Numer of shards set per index : 1

Environment : Production

Third party modules : none

### Steps to reproduce

1. Run php/bin magento indexer:reindex

### Expected result

1. Indexing all indices go through successfully.

### Actual result

1. For 3 indices listed above we get this error:  this action would add [1] total shards, but the cluster currently has [1004]/[1000] maximum open shards

![Zrzut ekranu 2023-07-25 o 10 58 03](https://github.com/Smile-SA/elasticsuite/assets/70642070/fb4a3f95-5a58-4efc-b5af-ff20fb34dab2)

**Comment by zsspoldzielnia** [comment]
Quite a lot!

![Zrzut ekranu 2023-07-25 o 11 23 19](https://github.com/Smile-SA/elasticsuite/assets/70642070/adfec951-2f7d-4b86-a38d-c51f10516862)

Why is it creating so many indicies?

**Comment by romainruaud** [comment]
Ghost indices are indices that were never finished to build by the engine and that could be safely deleted.

You can delete them manually if you want through the Indices screen.

Or you can consider using this third party module to do it automatically : https://github.com/stephanie-ehrling/elasticsuite-ghost-cleaner

**Comment by zsspoldzielnia** [comment]
Thank you for your help. 

We'll try the module suggested.

**Comment by zsspoldzielnia** [comment]
Go ahead with closing it, thanks.
