### ISSUE TITLE
Expanded facets number is not respected (all stay collapsed)

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3015]
No matter how many Facets I enter to be opened by default.
All will be closed (inactive) upon visiting the category.

### Preconditions

Magento Version :
Magento ver. 2.4.6

ElasticSuite Version :
Open Source ver. 2.11.3.1

Environment :
Developer

Third party modules :
BSS Fast Order
Yireo Next Gen Images
### Steps to reproduce

1. Keep the default value of opened facets
2. Blank Theme Child
3. Visit the category with 4 facets and 3 (default) opened.
4. All facets will be collapsed

### Expected result

1. I expect the facets to stay opened, respecting the number of the setting.

### Actual result

1. [Screenshot, logs]
All facets stay closed

**Comment by vahonc** [comment]
Hi @onepack,

Could you provide some screenshots from the fronted side of your store? 

What did you mean under "Blank Theme Child"?

Have you checked the console in the DevTools of your store, maybe there are some js error?

BR,
Vadym

**Comment by onepack** [comment]
Hi There Vadym,

I have the default facets opened at 3.
This is what it looks like:
![image](https://github.com/Smile-SA/elasticsuite/assets/475598/0c5828b5-07b1-4cd7-9a55-da35a04f1df4)

Selecting an option under Manufacturer collapses manufacturer after the choice was made:

![image](https://github.com/Smile-SA/elasticsuite/assets/475598/0891e6e6-c8d4-4598-8209-d57512e3c503)

No matter what I do, the facets collapse.

Here is the console output. zero errors:
![image](https://github.com/Smile-SA/elasticsuite/assets/475598/20114583-0e7b-47bc-a8b8-dadf337e2e1e)

**Comment by vahonc** [comment]
@onepack,

I"m not sure but maybe the accordion functionality not working in the Blank Theme by default.

Try to switch to the Luma theme if it's possible and check it out again.

BR,
Vadym

**Comment by onepack** [comment]
Hi Vadym,

I have two websites on one Magento install. I've tried the Blank and Luma theme on the first website.
The Child-theme based on the Blank theme in the second website has the same issue.

I'll try to figure out a bit more what the cause is and report back.

Greetings,

Mau

**Comment by onepack** [comment]
I found it.
I completely forgot that I have a custom module with a layer view file for an "In Stock" filter that I made before using this module.
That one was conflicting with the expanded facet status and kept them collapsed.

**Comment by onepack** [comment]
Thanks for your help Vadym!
