### ISSUE TITLE
How to filter product collection by category and custom attribute id?

### ISSUE THREAD

**Issue by webcreative24** [Smile-SA/elasticsuite#3022]
Hello. I'm trying to get a product collection with a custom product attribute filter but it always returns an empty result:
```
/** \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory $collection */
            $collection = $this->productCollectionFactory->create();
            $collection->addAttributeToSelect('*');
            $collection->setStoreId($this->storeManager->getStore());
            $collection->addAttributeToFilter('visibility', Visibility::VISIBILITY_BOTH);
            $collection->addAttributeToFilter('status', Status::STATUS_ENABLED);
            $collection->addCategoryFilter($category);
            $collection->addFieldToFilter('promotions', '1234');
            $productCount = $collection->getSize(); // == 0
```
The custom attribute is showing in the category filter and works well...
can you please help? What is missed?

**Comment by vahonc** [comment]
Hello @webcreative24,

Provide the configuration (with screenshots) of your custom attribute.

BR,
Vadym

**Comment by webcreative24** [comment]
@vahonc or maybe you can help me  to find how to get the number of items in the collection by applying a filter to it, as it would be on the frontend programmatically? for example, I have a link to a category with a filter parameter, I pass this link to a custom method and get the number of products filtered by parameters from the passed url

**Comment by webcreative24** [comment]
@vahonc this was my mistake. I have used attribute level as filter value instead of attribute value. thanks
