### ISSUE TITLE
Can the number of Facets opened in mobile view be different from Desktop?

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3034]
Is ElasticSuite able to set a number for facets to be open in Desktop view vs Mobile view?
Let's say: 5 open by default n Desktop and only 1 in Mobile view.

**Comment by vahonc** [comment]
Hello @onepack,

It's not possible from out of the box, so you need to look for other ways to implement it. Perhaps, you can try to do it with some hard coding in your mobile theme.

BR,
Vadym
