### ISSUE TITLE
Autocomplete Wiki redirect

### ISSUE THREAD

**Issue by deancodes** [Smile-SA/elasticsuite#3035]
Hi there, the Wiki for configuring autocomplete (https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteConfig) redirects with the error "You do not have permission to update this wiki."

It is incorrect on this page: https://github.com/Smile-SA/elasticsuite/wiki/Autocomplete

**Comment by rbayet** [comment]
Thanks a lot @deancodes 

That's fixed.
