### ISSUE TITLE
Query contains too many nested clauses (Adobe Commerce Cloud hosting)

### ISSUE THREAD

**Issue by MatthieuCardin** [Smile-SA/elasticsuite#3049]
Bonjour! Since upgrading to Magento 2.4.6 we've had this error which prevents certain categories from being displayed, such as a Smart category "Sales" based on special prices.

Adobe commerce Cloud
Magento Version : EE
ElasticSuite Version : 2.11.2
Environment : Production
Third party modules : No

### Steps to reproduce

1. Create a Smart category based on products that have a special price
2. Clear cache, reindex, etc
3. Go to this category PLP

### Expected result

1. The category should display all products with special price

### Actual result

PLP is empty

Error in logs:

`{"error":{"root_cause":[{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 10240"},{"type":"too_many_nested_clauses","reason":"too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 10240"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_en_ca_catalog_product_20230914_215508","node":"PxB1kjaBRHuTEOgdT6037g","reason":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 10240"}},{"shard":1,"index":"magento2_en_ca_catalog_product_20230914_215508","node":"uEpXNo49T1C9dT99S3uPbQ","reason":{"type":"too_many_nested_clauses","reason":"too_many_nested_clauses: Query contains too many nested clauses; maxClauseCount is set to 10240"}}],"caused_by":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 10240","caused_by":{"type":"too_many_nested_clauses","reason":"Query contains too many nested clauses; maxClauseCount is set to 10240"}}},"status":500} [] []`

### Adobe support comment:

"After a thorough investigation, we have determined that the issue occurs due to the Elasticsuite search engine.
Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\Query\Builder\Boolean::buildQuery is responcible for building big nested queries"

**Comment by MatthieuCardin** [comment]
Found something very interesting:

- It seems it is happening with Virtual Categories
- The search request in some cases is so huge it explodes. We found out that it contains a
`{"match":{"sku.reference":{"query":"0039901","minimum_should_match":"100%","boost":1}}}`
for every products in the catalog (In our case more thant 100k products)

The Virtual category that fails is at root level and has only on condition: Only products with Special price 
It has many nested virtual categories under it.

**Expected request**

`{"size":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"must":[{"range":{"special_price":{"gt":0,"boost":1}}}],"must_not":[],"should":[],"boost":1}},{"term":{"stock.is_in_stock":{"value":true,"boost":1}}},{"terms":{"visibility":[2,4],"boost":1}},{"bool":{"must_not":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"term":{"category.category_id":{"value":13280,"boost":1}}},{"term":{"category.is_blacklisted":{"value":true,"boost":1}}}],"must_not":[],"should":[],"boost":1}},"boost":1}}],"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"attribute_set_id":{"terms":{"field":"attribute_set_id","size":10000,"order":{"_count":"desc"}}},"indexed_attributes":{"terms":{"field":"indexed_attributes","size":10000,"order":{"_count":"desc"}}}},"track_total_hits":true}`

**Current request**

`{\"size\":0,\"query\":{\"constant_score\":{\"filter\":{\"bool\":{\"must\":[{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"range\":{\"special_price\":{\"gt\":0,\"boost\":1}}}],\"minimum_should_match\":1,\"boost\":1}},{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"range\":{\"special_price\":{\"gt\":0,\"boost\":1}}}],\"must_not\":[],\"should\":[],\"boost\":1}},{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"nested\":{\"path\":\"category\",\"score_mode\":\"none\",\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must_not\":[{\"term\":{\"category.is_virtual\":{\"value\":true,\"boost\":1}}}],\"boost\":1}},{\"terms\":{\"category.category_id\":[\"10993\"],\"boost\":1}}],\"must_not\":[],\"should\":[],\"boost\":1}},\"boost\":1}},{\"bool\":{\"must\":[{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"match\":{\"sku.reference\":{\"query\":\"0028444\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045905\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0043218\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044602\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045884\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045861\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045609\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045758\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045588\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045191\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044310\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0041759\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044673\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0036328\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045077\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0037064\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0042582\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0033947\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044370\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044356\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0027246\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0018747\",\"minimum_should_match\":\"100%\",\"boost\":1}}}],\"minimum_should_match\":1,\"boost\":1}}],\"minimum_should_match\":1,\"boost\":1}},{\"nested\":{\"path\":\"category\",\"score_mode\":\"none\",\"query\":{\"bool\":{\"must\":[{\"bool\":{\"must_not\":[{\"term\":{\"category.is_virtual\":{\"value\":true,\"boost\":1}}}],\"boost\":1}},{\"terms\":{\"category.category_id\":[\"11020\"],\"boost\":1}}],\"must_not\":[],\"should\":[],\"boost\":1}},\"boost\":1}}],\"must_not\":[],\"should\":[],\"boost\":1}},{\"bool\":{\"must\":[{\"bool\":{\"must\":[{\"bool\":{\"must\":[],\"must_not\":[],\"should\":[{\"match\":{\"sku.reference\":{\"query\":\"0028444\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045905\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0043218\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044602\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045884\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045861\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045609\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045758\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045588\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045191\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044310\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0041759\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044673\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0036328\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0045077\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0037064\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0042582\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0033947\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044370\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0044356\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0027246\",\"minimum_should_match\":\"100%\",\"boost\":1}}},{\"match\":{\"sku.reference\":{\"query\":\"0018747\",\"minimum_should_match\":\"100%\",\"boost\":1}}}],\"minimum_should_match\":1,\"boost\":1}}],...`

It his way more longer thant that. It makes crash my local environement with a Fatal error: Allowed memory exhausted

**Comment by rbayet** [comment]
Hello @MatthieuCardin,

This looks like you have a virtual category that has a "virtual category root" somewhere in your category tree that has a nasty virtual category descendent itself.

The exact query created for a virtual category consists of the clause for that query "product_type=car AND color=red" combined with the clause related to configured its virtual category root (if it is different than the root of your catalog tree).

Even if that virtual category root is a physical category, which would mean a simple clause like `{"term":{"category.category_id":{"value":13280,"boost":1}}}, [...]`, the resulting clause will be the combination of every virtual category under it.

So it could become quite fast "product_type=car AND color=red AND (category_id=13280 OR (sku=0033946 OR sku=0033947 OR sku=0033948 OR ....) AND (sku=0022121 OR sku=00221222 OR ....) AND (...)".
Hence Elasticsearch/OpenSearch complaining about way too many nested/boolean clauses.

In your case, it seems someone created way too many "SKU oriented" virtual categories, basically designing the category tree structure with virtual categories, which is a "no no".
Virtual categories are supposed to be used for limited, marketing oriented merchandising operations, but NOT to be used as the foundations for a catalog, precisely to avoid the situation you are facing.

Regards,

**Comment by MatthieuCardin** [comment]
@rbayet thanks for the anwser although I don't understand everything. Could this be due to a recent update, as our setup worked perfectly before the recent updates? (v. 2.10.x -> 2.11.2)

I will tell my client to change their virtual category tree and they will try to find a way around.

Thanks again!

**Comment by vahonc** [comment]
Hello @MatthieuCardin,

Could you clarify from which exactly version of 2.10.x you updated to the 2.11.2 version?

BR,
Vadym

**Comment by romainruaud** [comment]
> I still need to understand why root Smart categories are affected by nested children categories

As described in @rbayet note : 

> the resulting clause will be the combination of every virtual category under it.



I close the issue, regards
