### ISSUE TITLE
PHP version inconsistency when updating version < 2.4.6

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#3074]
When upgrading from 2.10.8.1 to 2.10.18.1 I found a PHP version inconsistency. I wanted to upgrade using the composer command `composer require smile/elasticsuite ~2.10.13`. This failed with a constraint error stating I need to use PHP 7.3 (I was on 7.4):

```
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/magento2-functional-testing-framework is locked to version 2.4.5 and an update of this package was not requested.
    - magento/magento2-functional-testing-framework 2.4.5 requires php 7.0.2||7.0.4||~7.0.6||~7.1.0||~7.2.0||~7.3.0 -> your php version (7.4.33) does not satisfy that requirement.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```
So I switched to 7.3 and the composer update went fine.
After `setup:upgrade` I triggered `setup:di:compile` which failed with a syntax error:
`MiBsyntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)#0 /www/vendor/composer/ClassLoader.php(428)`
This could only be circumvented by switching back to PHP 7.4

### Preconditions

Magento Version : 2.4.3-p1

ElasticSuite Version : 2.10.18.1

Environment : Dev

### Steps to reproduce

1. Use PHP 7.4
2. Update module via `composer require smile/elasticsuite ~2.10.13`

### Expected result

1. Composer should download the latest suitable version

### Actual result

1. Composer fails with error (see above)

It seems the composer package should either be updated to allow PHP 7.4 or the code should be fixed to be compatible with PHP 7.3 again. My usual error between those 2 versions are typecasts for class members which leads to syntax errors in PHP 7.3. Example:

`private \Magento\Framework\ObjectManagerInterface $objectManager`

**Comment by romainruaud** [comment]
Hi, Elasticsuite does not require a particular PHP version : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/composer.json

Most probably it's a mismatch in the global composer.json file of your project (the Magento composer.json).

Regards
