### ISSUE TITLE
Wrong breadcrumbs due to last visited category being virtual category

### ISSUE THREAD

**Issue by setura** [Smile-SA/elasticsuite#3082]
When we visit a virtual category page and then visit a product page of a product that doesn't belong to the last visited virtual category, we will see the virtual category page of the last category visited in the breadcrumbs instead of "home" -> "product name". When searching products we should not see categories on breadcrumbs.

### Preconditions

Replicable in every env. Using M1 chip with valet for PHP and Nginx and docker for redis, Open search, and database

Magento Version : 2.4.5-p3

ElasticSuite Version: smile/elasticsuite 2.10.13.3

But this issue also happens on smile/elasticsuite 2.10.18.1

Environment : Reproducible in both modes

Third party modules : None seem to impact this feature directly.

### Steps to reproduce

1. Create a virtual category with some products and visit it
2. Go to another product that doesn't belong to this virtual category 
3. Check the category of the breadcrumbs, it will show the virtual category as it was the last category visited.

### Expected result

1. When searching for products we should not see categories on breadcrumbs.

### Actual result

1. We see the Virtual category of this product

The is where the issue happens. Basically, since the last visited category is a virtual, this plugin will return true.
\Smile\ElasticsuiteVirtualCategory\Plugin\Catalog\ProductPlugin::aroundCanBeShowInCategory

<img width="1002" alt="Screenshot 2023-10-10 at 12 36 53" src="https://github.com/Smile-SA/elasticsuite/assets/43816552/08cea4c3-c615-49cd-ad82-6f7a4051f06f">

Then this line is evaluated to true vendor/magento/module-catalog/Helper/Product.php:446 which will set the categoryID to the virtual category.

Ultimately the this line sets the wrong product category to the product 

vendor/magento/module-catalog/Helper/Product.php:461

**Comment by setura** [comment]
Forgot to say, but this issue also happens on smile/elasticsuite 2.10.18.1

**Comment by setura** [comment]
My solution for this was an after plugin to Magento\CatalogSearch\Controller\Result\Index:afterExecute setting         
$this->catalogSession->setLastVisitedCategoryId(null);

\Magento\Catalog\Model\Session $catalogSession

**Comment by vahonc** [comment]
Hello @setura, thanks for your feedback.

Yes, it looks like the logic of `aroundCanBeShowInCategory` plugin is not up to date, so from out-of-the-box we don't have a fix for this issue now. 

Your fix is a little bit dirty, but in your case, it can fix your issue.

We will try to come back to this and fix it in the proper way in our feature releases.

BR,
Vadym

**Comment by setura** [comment]
Agreed @vahonc, it is a temporary solution for sure.

Best regards,
Pedro Amaro

**Comment by setura** [comment]
Hi @vahonc,
I noticed that this issue remains reproducible even after nearly a year. Could you provide an update on any development efforts or progress made to address this bug? Any additional details would be greatly appreciated.

Thank you for your attention.

Best regards,
Pedro Amaro

**Comment by romainruaud** [comment]
Hi @setura I'll be glad to review any PR you might submit to address this issue.

Best regards
