### ISSUE TITLE
Huge number of documents for the catalog_product index

### ISSUE THREAD

**Issue by Neos2007** [Smile-SA/elasticsuite#3086]
**Magento version:** 2.4.4-p3
**Elastic suite version:** 2.10.10
We have about 12000 products visible in the catalog/search.
And for these products, elasticsearch generates indexes with more than 2 million documents per index:
<img width="1578" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/17883826/822b8492-b634-4928-a3c4-7e73b92689d8">
I wanted to ask if this is the correct behavior.  Why does it produce so many documents? Or does this number include hidden nested documents?

**Comment by romainruaud** [comment]
This is normal : a document/record in a Elasticsearch is any document, including subdocuments.
For products, those sub-documents are the price and category data.

![image](https://github.com/Smile-SA/elasticsuite/assets/15340849/48bb238d-4628-45da-8920-7f8380db0d3e)

![image](https://github.com/Smile-SA/elasticsuite/assets/15340849/2502e6b3-7e2a-43db-9e24-e4f0d7f39331)


For instance, a single product located in 3 categories on a Magento instance with 4 customer groups will generate 8 documents in the catalog_product index : 1 for the global document, 3 sub-documents for category data and 4 sub-documents for the price data.

One possibility to reduce the total amount of documents per index, one simple solution, which is also beneficial for Magento price indexing performances, is to remove unused customer groups.

Regards,
