### ISSUE TITLE
Category product's position are not matching in the graphql

### ISSUE THREAD

**Issue by usergithubb** [Smile-SA/elasticsuite#3087]
Hi Team,

Category product's positions/sort orders are not matching in product graphql what we have set in the admin panel. 

Adobe Commerce ver. 2.4.4-p5
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.17.3
### Steps to reproduce
1. Add products to a category.
2.Set the order in Magento admin.
3.Product graphl is not returning in the same order

### Expected result
It should return the order what it is set in the admin panel

### Actual result
It is returning some randon order

**Comment by vahonc** [comment]
@usergithubb 

>3.Product graphl is not returning in the same order

Can you share the query that you use in the graphql?

BR,
Vadym
