### ISSUE TITLE
Product attribute autocomplete > Search terms

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#309]
- I type "black" in the search engine
- In product autocomplete, I click "black (62)"
- A page "search result for: black" is displayed, with 62 products
- In the filters, I click on "clear all"
- A page "search result for: black" is displayed, with 66 products

It's a bit difficult for the user to understand what happens, it's not very user-friendly.

This issue seems really minor to me... but, if it's possible to optimize...

I think a better solution (if technically possible) would be:
- I type "black" in the search engine
- In product autocomplete, I click "black (62)"
- A page "search result" is displayed, with 62 products (= no search query + filter on "color=black")
- In the filters, I click on "clear all"
- A page "search result" is displayed, with all products in the database (= no search query and no filter)

**Comment by romainruaud** [comment]
I am not sure it would be easy to perform a query without any search query (and just a filter applied). We may dig this option with @afoucret . 

We keep you in touch.

Regards

**Comment by romainruaud** [comment]
This one is obsolete due to the deletion of result number for attributes autocomplete.

Regards,
