### ISSUE TITLE
facet_max_size not used if facet_sort_order is _manual 

### ISSUE THREAD

**Issue by Nuranto** [Smile-SA/elasticsuite#3090]
### Preconditions

Magento Version : 2.4.6-p2

ElasticSuite Version : 2.11.4.1

Environment : Both

### Steps to reproduce

1. Configure an attribute with more than facet_max_size options
2. Configure that attribute with facet_sort_order = manual
3. Load frontend category that uses that attribute

### Expected result

1. Only facet_max_size options are displayed, with a "see more" button

### Actual result

1. All options are displayed, with a "see less" button

**Comment by vahonc** [comment]
Hello @Nuranto,

Could you provide the configuration of your attribute and what exactly you see on the frontend (screenshots are welcome)?

BR,
Vadym

**Comment by vahonc** [comment]
@Nuranto,

Is this issue still relevant to you?

If so, it will be useful if you provide the configuration of your attribute and what exactly you see on the frontend (screenshots are welcome)

Is there any chance that the `facet_max_size options` option of your attribute could be overridden by the `Display Settings` of your category?

![Screenshot from 2023-11-06 18-36-29](https://github.com/Smile-SA/elasticsuite/assets/67791361/101785c9-b7fb-436d-bb8e-42646e249dfd)

Are you sure that your theme is based on the Luma?

BR,
Vadym

**Comment by Nuranto** [comment]
Hi @vahonc,

No, you're right, our theme is based on hyva, and it was a theme issue indeed. Well, actually, that's debatable : If I understood correctly the issue that we had (I'm not in charge of frontend on this project), all the options are loaded on frontend when sort is custom. But your default templates deals with it, so for the end user it is transparent. Our theme did not, and was expecting the same behavior as other attributes (with non-custom sorting).

Anyway, I guess you can close this issue.
