### ISSUE TITLE
positions mixed up on categories

### ISSUE THREAD

**Issue by gtrocks** [Smile-SA/elasticsuite#3101]
when we try to drag and drop and reposition the products under a category it will mix up positions and not change the 
position of selected one but for many other items as well

### Preconditions

Magento Version : 2.4.4-p6

ElasticSuite Version : 
"smile/elasticsuite": "2.10.12.1"
        "smile/module-elasticsuite-cms-search": "2.2.8"
              "smile/module-elasticsuite-shared-catalog": "~2.10.0"

Environment : Production mode

Third party modules :
yes we are using 
### Steps to reproduce

1. goto -> catalog -> categories
2.scope -> all store view now open any category which have large numbers of items
3. now try to change the product position by drag and drop

### Expected result

1. it will only change the position of selected product 

### Actual result

1. [Screenshot, logs]
it was changing position of multiple other products and mix up everything. instead of just updating position for single item
![image](https://github.com/Smile-SA/elasticsuite/assets/25859719/3c121779-1ee0-43e3-b156-4d857017b792)
![image](https://github.com/Smile-SA/elasticsuite/assets/25859719/d7147496-8a0d-4e82-a285-1f7918bfb44e)

I have checked on smile_virtualcategory_catalog_category_product_position table on magento2 and found multiple entire occur with 
negative position and some products have position zero 

but not clear what was the issue ?
can you please help on this we facing this issue on most of the categories

**Comment by gtrocks** [comment]
@romainruaud can you please assign someone to look into it and help me on this

**Comment by romainruaud** [comment]
Hello @gtrocks 

how did you initialize the products positions ? Did you import something on the table ?

Or did you just move products manually and ended up with some having negative positions ?
