### ISSUE TITLE
Virtual Categories price rules not working correctly

### ISSUE THREAD

**Issue by glen-stanbridge-brightminded** [Smile-SA/elasticsuite#3103]
### Preconditions

Magento Version : EE2.4.4-p6

ElasticSuite Version : 2.10

Environment : Dev

Using price attribute to build virtual category rules yields unexpected products in the category.

Example I add price >= 14.98 and price <=15 I get products with a prices out of that range ie. 15.99

![virtual-categories-3](https://github.com/Smile-SA/elasticsuite/assets/133893327/c910c208-b6fe-48c1-9472-4125188466cc)

Another example
price <=14.98 & price >= 14.5 and still get products priced at 15.99

![virtual-categories-2](https://github.com/Smile-SA/elasticsuite/assets/133893327/1735e534-219c-489f-8c6d-d33f4453984c)

Any ideas as to why this could be happening?

**Comment by vahonc** [comment]
Hello @glen-stanbridge-brightminded,

Please specify which exact version of ElasticSuite you are using.

BR,
Vadym

**Comment by glen-stanbridge-brightminded** [comment]
Hi @vahonc 

It's 2.10.12.1

I can also confirm after much testing that it is only the price < and price <= that I am seeing this issue on

Thanks,
Glen

**Comment by vahonc** [comment]
@glen-stanbridge-brightminded,

Are you also getting products with prices out of that range when you browse your category on the frontend or it's only in category preview issue in Admin?

Is there something specific for the prices configuration of your product, maybe you a using different (special, regular, final) prices?

Have you tried to test this issue on simple products, in other words not configurable or bundle items?

Have you multiple currency setup for the default store?

BR,
Vadym

**Comment by glen-stanbridge-brightminded** [comment]
Hi @vahonc 

Yes, products which are out of price range are displayed on the frontend too, even price filters for the out of range prices are created.

There's nothing specific about pricing, occurs on bundle products and simple products. Interestingly there is a pattern, the threshold for a product being included is 90% of the price . eg a product is £11, it will show when a rule of less than £9.90 is applied, but not when a rule of less than £9.89 is applied. Tax rate is 20% so I don'r think that is a factor.

Doing some digging I can see that the rules are being correctly applied as filters to the collection.

Thanks,

Glen

**Comment by glen-stanbridge-brightminded** [comment]
I am closing this issue. Found that the price filter was behaving unexpectedly due to ElasticSuite Phrase Match Boost Value being set to 10, changing this to 1 so that no multiplier was applied produced expected results in price matching.

**Comment by glen-stanbridge-brightminded** [comment]
I am closing this issue. Found that the price filter was behaving unexpectedly due to ElasticSuite Phrase Match Boost Value being set to 10, changing this to 1 so that no multiplier was applied produced expected results in price matching.
