### ISSUE TITLE
Faulty search results

### ISSUE THREAD

**Issue by svdp24** [Smile-SA/elasticsuite#3108]
Problem: Customer is typing a full sku in the search bar, f.e. 1RG1
Expected result: Only 1 product should appear as result 
Result: 2 results are given: 1RG1 and 1RG6

Also, sometimes in search, only the wrong result is shown
Problem: 1RG5 was searches
Expected result: 1RG5 PDP
Result: PDP of the 1RG6

Extra info:

Fuzzyness is off
All thesaurus items are inactif

Working with Adobe Commerce version 2.4.5-p5
Elastic Suite OPen Source version 2.10.14

**Comment by rbayet** [comment]
Hello @svdp24,

Yes, by default, any attribute using the "reference" analyzer might be invisible to the pre-request analysis that determines if an exact matching or a fuzzy (fuzziness + phonetic search) request should be made.

We've introduced a couple of releases ago some experimental settings to adress that in Elasticsuite > Search Relevance.
I would switching to Yes those settings 
* "Elasticsuite > Search Relevance > Spellchecking Configuration > Term Vectors Configuration > [Experimental] Use reference analyzer in term vectors"
  * and possibly "[Experimental] Use all tokens from term vectors" just above (not required in your example but it may be if you have very long skus)
* "Elasticsuite > Search Relevance > Relevance Configuration > Exact Match Configuration > [Experimental] Use default analyzer in exact matching filter query"

Switching those settings to Yes does not require a full reindex but clearing caches might be required.

Regards,
