### ISSUE TITLE
Cannot Create Thesaurus via import

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3109]
### Preconditions

Magento Version :

Adobe Commerce ver. 2.4.4-p3
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.18.2

And

Magento ver. 2.4.5-p2
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.18.1

Environment :
Deverloper and Production mode

### Steps to reproduce

1. Create an import file via the Example document
2. Import check: Checked rows: 2, checked entities: 2, invalid rows: 0, total errors: 0
3. Import after check: Created: 0, Updated: 0, Deleted: 0, Import successfully done 
4. Check new Thesaurus, nothing imported

### Expected result

1. I should be able to import new Thesauruses via an import.
2. After import there should be new thesauruses added.

### Actual result

1. Nothing happens

A workaround is to create fake Thesauruses by hand and then run the import against them with the same ids/ thesaurus numbers
That will update the thesauruses.
But this can be time-consuming and kills the whole idea of an import via a file to win some time.

[thesaurus-import-test.csv](https://github.com/Smile-SA/elasticsuite/files/13317695/thesaurus-import-test.csv)

**Comment by rbayet** [comment]
Hello @onepack,

Yes, the sample file is a bit misleading.
To add new Thesaurus, simply remove the content of the thesaurus_id column.

Regards,

**Comment by vahonc** [comment]
Hello @onepack,

Which import behavior did you select when you tried to import thesaurus?

![Screenshot from 2023-11-10 14-58-13](https://github.com/Smile-SA/elasticsuite/assets/67791361/527fe435-7393-4038-ba0a-d9443f0163f7)

BR,
Vadym

**Comment by onepack** [comment]
@vahonc 
Add/Update

**Comment by rbayet** [comment]
Hello @onepack,

Did you try the solution I described in my comment above ?

Regards,

**Comment by onepack** [comment]
@rbayet Yes it worked! Thank you very much. It saved me 2400+ clicks.
