### ISSUE TITLE
Product attribute autocomplete > Settings

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#311]
It should be forbidden to set up a product attribute in the following configuration:

("Use in search = no" OR "Used in autocomplete = no")
AND
"Display in autocomplete = yes"

Today it's possible and the search result displayed are not correct (ex: a click on the product attribute "black" displays 27 products instead of 62 products).

**Comment by romainruaud** [comment]
This has been just fixed in release 2.3.1 :)
