### ISSUE TITLE
Redirect on specific search terms

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3113]
I'm trying to find a solution for the following.

When a customer searches for a brand name we don't want the customer to end up in a search-result page with 100 products but in some cases we want them to go to a brand or category landing page.

For instance a customer searches for Brand ABC.
Now they end up in a result of 1000 products.

Instead we want to create a redirect for this so when a client searches for ABC he will be send to Brand Page ABC or another page of our choice instead of the resultpage with 1000 products.

How to achieve this?

**Comment by romainruaud** [comment]
Hi, check this link, this is legacy Magento feature : https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/search/search-terms.html?

Search for "redirect".

Regards
