### ISSUE TITLE
Normalizer error on catalogsearch_fulltext reindex

### ISSUE THREAD

**Issue by enalettoWalit** [Smile-SA/elasticsuite#3116]
I am currently upgrading the Elasticsuite module from version 2.10.10 to version 2.10.18.2.
From the initial tests, everything seems to be working. But whenever I try to reindex the `catalogsearch_fulltext` index, it gives me the following error:
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"normalizer [untouched] not found for field [untouched]"}],"type":"mapper_parsing_exception","reason":"normalizer [untouched] not found for field [untouched]"},"status":400}
```
I've noticed that if I comment the row 420 of the `src/module-elasticsuite-core/Index/Mapping/Field.php` file, the reindex finishes correctly.

What could be causing this error?

I am currently experiencing the problem on a local environment, I haven't deployed the upgraded version to a live environment yet.

### Preconditions

Magento Version : 2.4.4-p4

ElasticSuite Version : 2.10.18.2

Environment : Developer

Elasticsearch version: 7.6.2 (I am using the docker container from [mark shust](https://github.com/markshust/docker-magento))

Third party modules :

### Steps to reproduce
1. Install version 2.10.18.2 of the Elasticsuite module
2. Launch the command `bin/magento indexer:reindex catalogsearch_fulltext`

### Expected result
1. The reindex should finish correctly

### Actual result

1. The reindex won't start and the following error is shown `{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"normalizer [untouched] not found for field [untouched]"}],"type":"mapper_parsing_exception","reason":"normalizer [untouched] not found for field [untouched]"},"status":400}`

**Comment by rbayet** [comment]
Hello @enalettoWalit,

I've done the following tests on environment already built where I just changed the Elasticsearch/OpenSearch image
* EE 2.4.6-p2 + ES 7.6.2 from mark shust (was legacy Elasticsearch) : OK.
* EE 2.4.3-p3 + ES 7.6.2 from mark shust (was OpenSearch) : OK.

Could you check that you didn't have a lingering composer patch applied on `[magento]/vendor/smile/elasticsuite/src/module-elasticsuite-core/etc/elasticsuite_analysis.xml` which would prevent it to contain the following at the bottom of the file ?
```
    <normalizers>
        <normalizer name="untouched" type="custom" language="default">
            <char_filters></char_filters>
        </normalizer>

        <!--
            If you want to have case insensitive layered navigation filters options matching,
            you can override the "untouched" normalizer above (which does nothing) by this one.
            Please note, though, that those filter options will now be displayed in lowercase
            in the layered navigation filters.
        <normalizer name="untouched" type="custom" language="default">
            <char_filters></char_filters>
            <filters>
                <filter ref="ascii_folding" />
                <filter ref="trim" />
                <filter ref="lowercase" />
            </filters>
        </normalizer>
        -->
    </normalizers>
```

That's where the definition of the "untouched" normalizer comes from.
Either this definition is missing or your (XML) configuration cache was not cleared, that's the only logical reason I see.

The code supporting "normalizers" in the elasticsuite_analysis.xml was [merged eons ago](https://github.com/Smile-SA/elasticsuite/commit/dd314ec60948e293279fdb31fce74738c4b7ab16) so I don't think it's the issue.

Regards,

**Comment by enalettoWalit** [comment]
Hi @rbayet 
thanks for the reply!
Indeed I found out that I had exactly that XML code commented, for some reason.

I'm closing the issue.
Thanks
