### ISSUE TITLE
Show Out Of Stock Products At Bottom (Elasticsuite 2.8.x)

### ISSUE THREAD

**Issue by ravitejaexinent** [Smile-SA/elasticsuite#3125]
We've created an optimizer to display out-of-stock products at the bottom of category pages. However, it seems that when products are selected for 'manual sort,' the optimizer doesn't function as intended.

### Preconditions
Magento Version CE : 2.3.4
ElasticSuite Version : 2.8.19

### Steps to reproduce
1. Created an optimizer to display out-of-stock products at the bottom.
2. Selected 'manual sort' for some out-of-stock products.

### Expected result

1. All out-of-stock products should display at the bottom.

### Actual result

1. Products with 'manual sort' selected are not displaying at the bottom.

**Comment by rbayet** [comment]
Hello @ravitejaexinent,

First, be advised that using an optimizer to move out-of-stock products at the bottom of category pages can work as long as you don't have other conflicting optimizers that also boost those products: the score boost (or penalty) of optimizers are combined.
So you could have a -99% penalty for out-of-stock products and a +400% bonus for discounted products : some of your out-of-stock and discounted products will still show in the first few rows of your category products.

That being said: yes, this is a limitation that has been addressed recently in Elasticsuite 2.10.x and 2.11.x, see the section "Ignore manual positions for out of stock products" in the release notes for [2.11.4.2](https://github.com/Smile-SA/elasticsuite/releases/tag/2.11.4.2).

Unfortunately, we do not support anymore Elasticsuite 2.8.x, so there is absolutely no plan to backport this enhancement there.
But you could probably try to backport yourself [the code](https://github.com/Smile-SA/elasticsuite/pull/3100) in your local project.

Regards,

**Comment by ravitejaexinent** [comment]
We attempted to sort the collection using the following code:

$this->_collection->getSelect()->order(array(new \Zend_Db_Expr("FIELD(e.sku, " . $skus . ")")));

This code was implemented in the file vendor\magento\module-catalog\Block\Product\ProductList\Toolbar.php. However, despite our efforts, we were unable to achieve the desired sorting. Could you provide guidance on the correct approach to accomplish this?

**Comment by rbayet** [comment]
Hello @ravitejaexinent,

I don't see the link between your original question and your last comment.
Please create different tickets if you have different questions.

Your approach using the SQL collection is dead wrong, this is not how Elasticsuite works: every filtering and sorting is to be performed at the Elasticsearch level, the native SQL-based collection is only there to "hydrate" the results against the database.

So if you want to sort an Elasticsuite-driven products collection by SKU, you should make the sku attribute sortable and use the "setOrder" method of the product collection.

I'm closing this ticket please feel free to reopen it to discuss the original issue.

Regards,
