### ISSUE TITLE
Is there a way to do a search query programatically with all relevant optimizers automatically applied?

### ISSUE THREAD

**Issue by gusdemayo** [Smile-SA/elasticsuite#3126]
Using the method

```
$searchRequest = $this->requestBuilder->create(
    $this->storeManager->getStore()->getId(),
    'catalog_view_container',
    0,
    25,
    $searchTerm
);

$queryResponse = $this->searchEngine->search($searchRequest);
```

It looks like I'm getting base results without optimizers applied, and the documents returned by $queryResponse->getIterator() have scores also matching the scores of the base results without optimizers appllied - is there a way to programatically get the results as they would show on the catalog search page with optimizers applied?

**Comment by romainruaud** [comment]
This should work, but maybe there's something wrong in your call, because a conjonction of "catalog_view_container" (ie : a category view) and having a $searchTerm (ie : a search result page) is not supposed to happen.

What do you have if you use "quick_search_container" instead ?

And btw, your boosts should be configured to be applied to the appropriate search requests (and store views).

Regards

**Comment by gusdemayo** [comment]
If I do quick_search_container it also shows results akin to the "base results" on the optimizer preview, rather than the results shown in the optimizer preview or on the catalog search page for the same terms -the boosts are configured to be applied to the current store

**Comment by gusdemayo** [comment]
I confirmed by logging the optimizers being applied in the `Smile\ElasticsuiteCatalogOptimizer\Plugin\QueryRewrite` class that on the catalog search several optimizers are applied, but none when I use the programatic query above for the same search terms.

**Comment by gusdemayo** [comment]
I should clarify I'm trying to build a query from an admin controller - the above query returns results with the correct optimizers applied when run from a frontend controller, but not on the admin side

**Comment by romainruaud** [comment]
Optimizers are attached to a store view.

In admin, I'm wondering what you'll obtain with "$this->storeManager->getStore()->getId()".

You should enforce this to the Store where your optimizers are applied.

Regards

**Comment by gusdemayo** [comment]
it appears the storeIds look to match - it's the default store view

**Comment by gusdemayo** [comment]
To test, in a script I put 

```
$state->setAreaCode('adminhtml');

$searchRequest = $builder->create(
    1,
    'quick_search_container',
    0,
    10000,
    <search term>
);
```

and then changed it to 

```
$state->setAreaCode('frontend');

$searchRequest = $builder->create(
    1,
    'quick_search_container',
    0,
    10000,
    <search term>
);
```

and it only applies the optimizers to the one with the frontend state set

**Comment by rbayet** [comment]
Hello @gusdemayo,

You probably lack the declaration of the search context.

Have a look at \Smile\ElasticsuiteCatalogOptimizer\Controller\Adminhtml\Optimizer\Preview :
```
/**
     * Update the search context using current store id, category or query text.
     *
     * @param integer           $storeId   Store id.
     * @param CategoryInterface $category  Category.
     * @param string            $queryText Fulltext query text.
     *
     * @return void
     */
    private function updateSearchContext($storeId, $category, $queryText)
    {
        $this->searchContext->setStoreId($storeId);

        if ((string) $queryText !== '') {
            try {
                $query = $this->queryFactory->create();
                $query->setStoreId($storeId);
                $query->loadByQueryText($queryText);

                if ($query->getId()) {
                    $this->searchContext->setCurrentSearchQuery($query);
                }
            } catch (\Magento\Framework\Exception\LocalizedException $exception) {
                // Do not break if we fail to retrieve the query.
            }
        } elseif ($category && $category->getId()) {
            $this->searchContext->setCurrentCategory($category);
        }
    }
```

When you set the area code to frontend, it probably makes it so that setting the store id in the context is not that necessary, but if you don't set up the "current query" or the "current category" then optimizers applicable only to some specific search terms or specific categories will not be applied.

Regards,
