### ISSUE TITLE
Advanced search broken when search on dropdown or mutiliselect attribute

### ISSUE THREAD

**Issue by zkliouel** [Smile-SA/elasticsuite#313]
Hi,
When a make an advanced search on dropdown attribute, I have the error bellow :
**_Exception #0 (Exception): Warning: array_filter() expects parameter 1 to be array, string given in .../vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Advanced/Collection.php on line 41_**
And when a make an advanced search on mutiliselect attribute, I have the error bellow : 
**_Exception #0 (Exception): Warning: strlen() expects parameter 1 to be string, array given in .../vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Advanced/Collection.php on line 41_**
Thank You
Zakaria

**Comment by romainruaud** [comment]
Fixed by PR #315

**Comment by afoucret** [comment]
PR have been merged

**Comment by afoucret** [comment]
@romainruaud : Please release a new 2.3.x version. I close the ticket.
