### ISSUE TITLE
How to configure the Autocomplete Result template

### ISSUE THREAD

**Issue by MatridTechnologies** [Smile-SA/elasticsuite#3130]
I am trying to configure the Autocomplete Result template so that it is shown like this

![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/5478dba8-d789-43cb-a0c6-3977c4b0312e)

I have followed Smile Elasticsuite Automcomplete wiki but could not make it work. This is the link I followed

https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteConfiguration

Screenshot from Stores > Configuration where I have enabled the options as asked in the wiki

![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/42ec455c-709b-4d46-ba58-bf5bed3b11a7)

This is how it is showing on the frontend

![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/9f7c0a48-fd5b-4686-9f77-cfba88e83f0d)

What changes do I need to make to get the desired result? 

Magento version - 2.4.6-p3
ElasticSuite Open Source Version - 2.11.4.1

**Edit**
I have changed to default theme as suggested by @vahonc and now the design is better but still **Search Terms** and **Categories** is not showing in Autocomplete box. 
I need to show these 2 section in this box.
Screenshot

![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/b32b669e-9903-460f-8300-af38ea58a6d6)

**Comment by vahonc** [comment]
Hello @MatridTechnologies 

It seems that you are using a custom theme that is not based on the default Magento theme like Luma. In this case, you should perform updating your autocomplete template and styles by yourself. 

BR,
Vadym

**Comment by MatridTechnologies** [comment]
@vahonc ok I am checking by applying the default theme. But if you see the content then you will find that it is not showing search Terms or Categories in the autoComplete template. It is only showing products.

**Comment by MatridTechnologies** [comment]
@vahonc I have updated my question according to your suggestions. You can see Search Terms and categories is still not showing. How I can add these 2 sections in the Autocomplete pop up?

**Comment by MatridTechnologies** [comment]
@vahonc 
I checked and found out that display category in Autocomplete is set to Yes. I randomly checked this for multiple categories.
![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/464252fa-25e9-4754-a953-89e79f7cd87d)

On Magento Dashboard I see the following search terms:
![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/3b9a3241-ac67-4b8d-81ad-3c83a17482f0)

I checked and saw that all Elasticsuite modules are enabled except 1.
Screenshot of the disabled module
![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/0d8e240b-af57-409b-9113-273ff0a8cfda)

Enabled Modules
![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/3eae8f3a-1fef-40df-8749-2e577e1301bd)

Also cron job is running fine.
![image](https://github.com/Smile-SA/elasticsuite/assets/121944110/ebac0085-4f03-4cbf-b36b-a290c5e0e562)

**Comment by vahonc** [comment]
@MatridTechnologies 

Yes, you need to have **Smile_ElasticsuiteTracker**. That's the module responsible for collecting data. In other cases, you will see only search terms that are collected from the search result page (what you see on the Magento dashboard), so not the partial ones that are typed in the autocomplete.

Have you tried to type in the search field some things that are related to your category (e.g. Hole, Bathroom, etc) to check if the search engine will suggest some result? 

BR,
Vadym

**Comment by vahonc** [comment]
@MatridTechnologies,

>I have a website where it is working fine, and there I saw that Smile_ElasticsuiteTracker module is disabled there too.

Great! So, it's a definitely configuration issue and you just need to compare these two websites (check layouts and templates, configurations in Admin Panel).

BR,
Vadym

**Comment by MatridTechnologies** [comment]
@vahonc 
yes sure, I am trying this and will let you know how it goes.

**Comment by vahonc** [comment]
Hello @MatridTechnologies,

Have you solved your issue?

BR,
Vadym

**Comment by MatridTechnologies** [comment]
@vahonc It is not 100% solved but I have moved forward with the solution. We had a customization in the custom theme for Magento_Search module. I have removed it and now the design is better but still I am not getting search Terms, and categories in the Auto complete pop up. Looking into that.
