### ISSUE TITLE
large number of indexes created after import full of 50 000 products

### ISSUE THREAD

**Issue by waelkensy** [Smile-SA/elasticsuite#3140]
Hello,

We have a catalog of 200K products with one store.
All our indexes are configured as "Update on schedule".

After execute a import of 50k products the Opensearch folder was abnormally big.

`192.168.5.5 23hwgstcguvig root@i-025bba12c6619afc0:~# du -h /data/exports/opensearch/ --max-depth=1
41G     /data/exports/opensearch/nodes
41G     /data/exports/opensearch/
`
And that is all index created : 

![image](https://github.com/Smile-SA/elasticsuite/assets/8972397/46db139f-1a67-48d9-bbc7-79266e54540a)

When i execute 
`bin/mangento indexer:reindex catalogsearch_fulltext`
An error occured : 

`{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [magento2_fr_catalog_product], an index exists with the same name as the alias","index":"magento2_fr_catalog_product","index_uuid":"lINo4GkGSDO3Xar16eGdPw"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [magento2_fr_catalog_product], an index exists with the same name as the alias","index":"magento2_fr_catalog_product","index_uuid":"lINo4GkGSDO3Xar16eGdPw"},"status":400}`

After delete all this index, disable cron and reindex manually everything is OK. 
But i don't know yet if this issue will occur on live condition, did you already encountered this situation ?

### Preconditions

Our configuration : 
![image](https://github.com/Smile-SA/elasticsuite/assets/8972397/e255524e-f5dc-4418-a3eb-db3aa66aa0f8)

Magento Version : 2.4.6-p3 on magento cloud environment

ElasticSuite Version : Open Source ver. 2.11.4.1

Environment : Production mode

### Steps to reproduce

1. Put magento indexe on update on schedule
2. Import ~more than 50 000 products. 

### Expected result

1. All products are imported and indexe created

### Actual result

1. ![image](https://github.com/Smile-SA/elasticsuite/assets/8972397/46db139f-1a67-48d9-bbc7-79266e54540a)

**Comment by rbayet** [comment]
Hello @waelkensy,

What was the method used to import the 50K products ?
The native Import/Export features ?
A third party PIM-related module ?

Regards,
