### ISSUE TITLE
Products that are filtered out by virtual rules are still visible in parent category

### ISSUE THREAD

**Issue by GioDeGruyter** [Smile-SA/elasticsuite#3142]
Hi,

We've currently set up a normal category which contains multiple virtual categories as children. These child virtual categories contain virtual rules to filter out specific products. The virtual rules do work for the virtual categories, so the products that need to be filtered out are indeed not available in the virtual categories anymore. But we do see that these products are still available in the parent category, which is not virtual, even though these specific products are not linked to this category. Now we had the following questions:
* Is this intended behaviour? Or should the products actually be filtered out from the parent category as well? 
* Is it perhaps a bug that has already been fixed in a later version? 
* If this isn't a bug is it perhaps a possibility this could be added as a feature? Or do we have to implement a custom solution to resolve this?

We're currently running version 2.10.12.1 of elasticsuite.

Kind regards

**Comment by vahonc** [comment]
Hello @GioDeGruyter,

>But we do see that these products are still available in the parent category, which is not virtual, even though these specific products are not linked to this category.

Are you sure that your products are not directly assigned to your parent category? 

I'm talking about this:

![Screenshot from 2023-12-27 16-19-34](https://github.com/Smile-SA/elasticsuite/assets/67791361/236ed272-435a-4faf-9de9-70ebd0ed0a4e)

Let's imagine that **Gear** is a real category and **Fitness Equipment** is a virtual. So if your product is attached to both categories you will see this in the children and parent categories on the fronted.

BR,
Vadym

**Comment by GioDeGruyter** [comment]
@vahonc,

No this is not the case.

Apologies for the late response.

**Comment by vahonc** [comment]
Hi @GioDeGruyter,

Is this issue still relevant for you?

If so, please provide more details about the configuration of your virtual and parent categories, especially the virtual rules that you are using for filtering out the products (screenshots are welcome). This will help me better understand your problem and try to reproduce it on my test environment.

BR,
Vadym
