### ISSUE TITLE
26186 returns 261872T00 but not 261860000, why?

### ISSUE THREAD

**Issue by stravanato** [Smile-SA/elasticsuite#3149]
I have this strange problem with search results.
I'm not talking about autocomplete results, which seem to work, but search results you get when you press enter.

Searching partial product code as **26186** I get:
2618**7**2T00, 2618**7**M250 and 2618**7**M500
But I don't get **26186**0000

I get 261860000 only if I type 2618600
I thought that an exact substring should be found first and then possible little changes.
Is there any configuration I should look at?

**Comment by rbayet** [comment]
Hello @stravanato,

There are quite a lot of parameters that can dictate how and why an EAN-like string would get matches.

First things first, please note that there is no notion of "substring" matching.
What can occur is the fuzziness doing its magic when an fuzzy query is performed.
A fuzzy query is performed when Elasticsuite determines that what the user searched is not present "exactly" in the search engine.

Secondly, what is present in the engine is determined by the (text) analyzer that you can configured on a per-attribute level.
The "standard" analyzer does a bit of "alphanumerical string splitting" and split strings along special characters.
So there is a pretty good chance that the following strings are generating "tokens" (search engine "words") like these : 
* 261872T00 : should generate "261872", "T", "00" but "261872T00" is probably preserved too
* 26187M250 : should generate "26187", "M", "250" but "26187M250" is probably preserved too
* 26187M500 : should generate "26187", "M", "500" but "26187M250" is probably preserved too
* 261860000 : should only generate "261860000"

You can check for yourself using the "Elasticsuite > Analysis" screen in your Magento admin.

The "reference" analyzer which we recommend using for "EAN-like" attributes (like `sku`) works a bit like that too.

But long story short, if your attribute is using the "standard" analyzer, when searching "26186", there will be no exact match amongst all the tokens I listed above.
So Elasticsuite enables the fuzziness which will allow up to 2 characters change per token to match the user request
* 261872T00 will match through the token "261872" (removal of terminal 2, changing the 7 by a 6)
* 26187M250 will match through the token "26187" (changing the 7 by a 6)
* same thing for 26187M500
* on the other hand there are too many changes to go from 261860000 to 26186 (4 removals of trailing "0")

Give a try to the "Elasticsuite > Analysis" to see if the "reference" analyzer would be able to generate from 261860000 a token "not too far" from 26186 (my guess is probably not).
**If that's the case,** I would encourage you to enable the following "experimental" settings in the "Elasticsuite > Search Relevance" configuration screen
* Relevance configuration > Exact Match Configuration > [Experimental] Use default analyzer in exact matching filter query
* Relevance configuration > Exact Match Configuration > [Experimental] Use reference analyzer in exact matching filter query
* Spellchecking configuration > Term Vectors Configuration > [Experimental] Use reference analyzer in term vectors
* Spellchecking configuration > Term Vectors Configuration > [Experimental] Use all tokens from term vectors

If that's not the case, you can try : 
* either to tweak the "reference" analyzer through the XML configuration to allow ignoring trailing 0, while keep the complete form, so "261860000" would be indexed as both "261860000" and "26186" (and "261872T00" as both "261872T00" and 261872T", and so on)
* or to assign to your attribute the "standard_edge_ngram" analyzer which adds (to the cost of index size and a bit of performance) the "standard" analyzer the ability to perform real autocompletion 
  * "261860000" will still be indexed as "261860000" but also "261", "2618", "26186", "261860", "2618600" and "26186000"
  * if you go this route, then enabling the following experimental settings in the "Elasticsuite > Search Relevance" menu will be mandatory too 
     * Relevance configuration > Exact Match Configuration > [Experimental] Use default analyzer in exact matching filter query
     * Spellchecking configuration > Term Vectors Configuration > [Experimental] Use all tokens from term vectors
     * Spellchecking configuration > Term Vectors Configuration > [Experimental] Use edge ngram analyzer in term vectors

Regards,
