### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by AndreaMastracchio** [Smile-SA/elasticsuite#3158]
After updating magento to version 2.4.6p2 on the smile/elasticsuite version I get this error when trying to filter in the listing

#0 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php(107): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->getFilterQuery()
#1 /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Category.php(129): Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category->applyCategoryFilterToCollection(Object(Magento\Catalog\Model\Category\Interceptor))
#2 /var/www/html/app/code/Vendor/ExponentialFilters/Plugin/Catalog/Model/WebApi/FilterService/GetProductCollection.php(119): Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category->apply(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Vendor\ExponentialFilters\Plugin\Catalog\Model\WebApi\FilterService\GetProductCollection->aroundGetProductCollection(Object(Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor), Object(Closure), 50, Array, 'https://magento...')
#4 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->Magento\Framework\Interception\{closure}(50, Array, 'https://magento...')
#5 /var/www/html/generated/code/Vendor/Catalog/Model/WebApi/Filter/Service/Interceptor.php(41): Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->___callPlugins('getProductColle...', Array, NULL)
#6 /var/www/html/app/code/Vendor/ExponentialFilters/Plugin/Catalog/Model/WebApi/FilterService/TotalProducts.php(49): Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->getProductCollection(50, Array, 'https://magento...')
#7 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Vendor\ExponentialFilters\Plugin\Catalog\Model\WebApi\FilterService\TotalProducts->aroundTotalProducts(Object(Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor), Object(Closure), 50, Array, 'https://magento...')
#8 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->Magento\Framework\Interception\{closure}(50, Array, 'https://magento...')
#9 /var/www/html/generated/code/Vendor/Catalog/Model/WebApi/Filter/Service/Interceptor.php(77): Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->___callPlugins('totalProducts', Array, NULL)
#10 [internal function]: Vendor\Catalog\Model\WebApi\Filter\Service\Interceptor->totalProducts(50, Array, 'https://magento...')
#11 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(202): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#13 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#15 /var/www/html/vendor/fastly/magento2/Model/FrontControllerPlugin.php(128): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Fastly\Cdn\Model\FrontControllerPlugin->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#17 /var/www/html/vendor/vladflonta/magento2-webapi-log/Plugin/Rest/Api.php(112): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): VladFlonta\WebApiLog\Plugin\Rest\Api->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor->___callParent('aroundDispatch', Array)
#20 /var/www/html/app/code/Vendor/WebApiLog/Plugin/Rest/Api.php(47): VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Vendor\WebApiLog\Plugin\Rest\Api->aroundAroundDispatch(Object(VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor), Object(Closure), Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /var/www/html/generated/code/VladFlonta/WebApiLog/Plugin/Rest/Api/Interceptor.php(23): VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor->___callPlugins('aroundDispatch', Array, NULL)
#24 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): VladFlonta\WebApiLog\Plugin\Rest\Api\Interceptor->aroundDispatch(Object(Magento\Webapi\Controller\Rest\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#27 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#29 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#30 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#31 {main}

Can anyone help me?

**Comment by vahonc** [comment]
Hello @AndreaMastracchio,

If I'm not mistaken, it seems that you have conflicts with third-party modules (e.g. ExponentialFilters, VladFlonta\WebApiLog).

But, we need more details, which version of Elasticsuite you are using, and where exactly do you get Error 500 (frontend/backend) 

Try to run these commands:

```
rm -rf var/cache/* var/page_cache/* generated/code/*
bin/magento setup:di:compile
```
Also, try to disable problematic modules. 

BR,
Vadym

**Comment by romainruaud** [comment]
@AndreaMastracchio can you give us the exact error message you have ?

Actually we have only the stack, and not the error message itself.
