### ISSUE TITLE
Error "illegal_argument_exception" occurred

### ISSUE THREAD

**Issue by Mohammed-Megahed** [Smile-SA/elasticsuite#3160]
Magento version 2.4.6 at the end of "setup:upgrade" command error occurred "{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}"

and error in the frontend

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.7.0
Smile_ElasticsuiteCatalogGraphQl data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.3.0
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteIndices data: current version - none, required version - 1.0.0
Smile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.5.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.7.0
Smile_ElasticsuiteCatalogGraphQl data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.2.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.3.0
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteIndices data: current version - none, required version - 1.0.0
Smile_ElasticsuiteAnalytics data: current version - none, required version - 0.0.1
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.5.0
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#2 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#3 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#4 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#5 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#6 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

**Comment by romainruaud** [comment]
You need the phonetic plugin (and most probably, the icu plugin).

Please refer to the wiki : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-7.x#installing-required-plugins

Regards

**Comment by Mohammed-Megahed** [comment]
Thanks
