### ISSUE TITLE
Sorting on Price works in Grid view but not in List view

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3163]
When I'm in Grid mode I can sort on all attributes without a problem but in List view however Price and a custom attribute don't work when used in sorting. The order stays the same.
### Preconditions

Magento Version :
Adobe Commerce ver. 2.4.4-p3

ElasticSuite Version :
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.10.19.1

Environment : Developer mode

Third party modules :

### Steps to reproduce

1. Sort on price in grid view and see the results
2. Now Sort on price in list view and see no difference in the sort.

![image](https://github.com/Smile-SA/elasticsuite/assets/475598/e34dbea7-475b-4403-95ef-1edcc05def44)
![image](https://github.com/Smile-SA/elasticsuite/assets/475598/e6510f74-b125-415b-bd3b-f213e4028c15)

**Comment by romainruaud** [comment]
Hi, not reproduced : https://demo.magento-elastic-suite.io/index.php/venia-dresses.html?product_list_mode=list&product_list_order=price

What's the URL you have for your page ? and the parameters ?

Regards

**Comment by onepack** [comment]
Thanks for the fast reply!
Indeed, I don't see it on this demo env.
The shop is behind a login as it is being developed.
I will test by disabling some modules and see what happens. I'll get back to you and let you know.

**Comment by onepack** [comment]
We have a Incl and Excl vat module.
Switching tax view before sorting seems to have fixed things.
Now that I did that I can sort on price again (with and without tax).
Maybe it was a cached query? Any ideas?

**Comment by vahonc** [comment]
Hello @onepack,

Is this issue still relevant for you or this is already fixed?

If it still not working as you expected provide more details about what you mean by saying:
>We have a Incl and Excl vat module.

Is this some custom (third-party extension) or native module of Magento?

BR,
Vadym

**Comment by onepack** [comment]
Hi Vadym,

Yes it's a third party module. It seems that it's working now.
The module must have been interfering with the sort query.
Thank you very much for your great support (as always).

I will close this ticket.
