### ISSUE TITLE
Removing extension breaks magento

### ISSUE THREAD

**Issue by peterhirn** [Smile-SA/elasticsuite#317]
Error after removing the extension:

    PHP message: PHP Fatal error:  Uncaught Error: Class 'Smile\ElasticsuiteVirtualCategory\Model\Category\Attribute\Backend\VirtualRule' not found in /data/magento/lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php:93

Hack to get it running again:

    DELETE FROM eav_attribute where attribute_code='virtual_rule';
    DELETE FROM eav_attribute where attribute_code='is_virtual_category';
    DELETE FROM eav_attribute where attribute_code='virtual_category_root';

I think a proper way to uninstall should be built-in (if possible) or at least documented in the wiki.

Edit: Duplicate #299 -> request for proper cleanup/documentation.

**Comment by afoucret** [comment]
@romainruaud : can you add an uninstall entry into the wiki ?

**Comment by romainruaud** [comment]
Added here : https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall

I close this issue

**Comment by PsmIndia** [comment]
Hello, i facing this issues, i remove module completely and deleted all files related to module
-------------------------------------------------
main.CRITICAL: exception 'Magento\Framework\Exception\LocalizedException' with message 'Something went wrong while saving the file(s).' in /var/www/demo5.litextension.com/public_html/customer/13173/vendor/magento/module-catalog/Model/ImageUploader.php:205
Stack trace:
#0 /var/www/demo5.litextension.com/public_html/customer/13173/vendor/magento/module-catalog/Model/Category/Attribute/Backend/Image.php(101): Magento\Catalog\Model\ImageUploader->moveFileFromTmp('Knives_and_Shar...')
#1 /var/www/demo5.litextension.com/public_html/customer/13173/var/generation/Magento/Catalog/Model/Category/Attribute/Backend/Image/Interceptor.php(24): Magento\Catalog\Model\Category\Attribute\Backend\Image->afterSave(Object(Magento\Catalog\Model\Category\Interceptor))
#2 [internal function]: Magento\Catalog\Model\Category\Attribute\Backend\Image\Interceptor->afterSave(Object(Magento\Catalog\Model\Category\Interceptor))
