### ISSUE TITLE
Product out of stock -> back in stock not updated in frontend grid

### ISSUE THREAD

**Issue by onepack** [Smile-SA/elasticsuite#3177]
### Preconditions

Magento Version :
Magento ver. 2.4.6-p3

ElasticSuite Version :
[ElasticSuite](https://elasticsuite.io/) Open Source ver. 2.11.4.2

Environment :
Production mode

Third party modules :

### Steps to reproduce

1. A product is out of stock + setting that an out of stock product is not visible on the frontend in the grid
2. That same product is back in stock after new stock is synced via REST.
3. The frontend will that there are 12 products but only 8 are visible.
4. An invalidate of the index in needed to get the missing products to show up.

### Expected result

1. A product should become visible after the qty is updated via the REST api.

**Comment by romainruaud** [comment]
Hi @onepack 

what's your index configuration ? Are they configured with "Update on Schedule" or "Update on Save" ?

Are you cronjobs running properly ?

Regards

**Comment by davidwindell** [comment]
We're seeing the same thing on Magento 2.4.6-p3 with 2.11.4.2, however in our case it is reproducible via taking a product out of stock and putting it back in stock manually via the admin. All indexes are set to "Update on Schedule", crons run correctly.

Running a manual/invalidate index of the catalogsearch index only after the changes makes the product show up again.

**Comment by davidwindell** [comment]
@onepack did you find a solution for this?

**Comment by ryanisn** [comment]
What might be potential cause of this?
We just found partial indexer is not picking up certain stock changes on a new site and we had to fix it with manual full reindex.
Not sure if this is related to magento or elasticsuite yet.
