### ISSUE TITLE
Attribute values of disabled children products are showing in filters

### ISSUE THREAD

**Issue by PerrineBlackbird** [Smile-SA/elasticsuite#3178]
### Preconditions

Magento Version : ver. 2.4.5-p5

ElasticSuite Version : ver. 2.10.19.1

Environment : both

Third party modules : -

### Steps to reproduce

1. Create a grouped product with multiple children, and disable some children
2. Go to the category page

### Expected result

1. The attribute values of the disabled products not appear in the filter panel

### Actual result

1. The attribute values of the disabled products appear in the filter panel

Hi,
I have a grouped product P, with 3 children : 
- A, red item, disabled
- B, green item, enabled
- C, blue item, enabled 
When I go to the category page, the color filter display 3 colors, instead of 2.

I've tried to update the module, reindex, without success.
Maybe I haven't see something in the configuration?

Thanks for your help!
Regards

**Comment by romainruaud** [comment]
Hi @PerrineBlackbird 

what do you have around this line when reindexing ? https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php#L98

This should prevent the data from the disabled children to be merged into the parent one.

Also, what do you have for the "color" attribute of the parent himself in the Magento Back Office ?

Regards

**Comment by PerrineBlackbird** [comment]
Hi @romainruaud 
I found the problem : the current products import only disable the product in one scope, instead of all...
Thanks for your quickly help :)
