### ISSUE TITLE
catalog_product index does not exist yet

### ISSUE THREAD

**Issue by rbostan** [Smile-SA/elasticsuite#318]
Hello,

Thank you for this great work.
We had a website with configurable swatches and simples mixed.
There are about 1 and half million products exists in database (both configurables, childrens and simples).

I have installed module via composer.

After install es and module. An exception thrown on frontend.
<pre>catalog_product index does not exist yet</pre>

But all indexes are seems ready and there is not any uncompleted database transaction or something like that.

<img width="1299" alt="screenshot at jan 28 16-44-40" src="https://cloud.githubusercontent.com/assets/4427628/22397036/b4b1ae7a-e570-11e6-8cf7-821831f6341a.png">

Also checked elasticsearch service by :
<pre>curl -i http://localhost:9200/?pretty=true
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 372

{
  "name" : "Sharon Friedlander",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mGwpLo8JRKOz7L1Z1OPg0A",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
</pre>

And healthcheck is : 
<pre>curl -i http://localhost:9200/_cluster/health?pretty=true
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 466

{
  "cluster_name" : "elasticsearch",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 6,
  "active_shards" : 6,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 4,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 60.0
}
</pre>

The exception is :
<pre>Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed
#0 /home/domain/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php(176):Smile\ElasticsuiteCore\Index\IndexOperation->getIndexByName('catalog_product', Object(Magento\Store\Model\Store\Interceptor))
</pre>

**Comment by romainruaud** [comment]
Hello @rbostan and thank you for testing our extension.

You may need to process a full reindex of the "catalogsearch_fulltext" indexer if you did a fresh install of Elasticsuite.

Could you give it a try and see if it fixes your problem ? Also, we are curious about the time it will take for your catalog to process the full reindex, so can you post here the time it took ?

We keep in touch,

Regards,

**Comment by rbostan** [comment]
@romainruaud I have already processed full reindex on all indexers.
I'll do a full reindex with timer and will inform you about this.

Another minor issue, autocomplete sytling not working. Result takes too long and after, a raw list appears on search input, but no styles or thumbnails etc. Fyi.

I'll try latest development branch (currently 2.4 i think).
Becuase we are using Magento 2.1.3 and latest commits may be fix our performance and other related issues.

We'll see.
;)

**Comment by rbostan** [comment]
The error has gone. I don't know why, but gone :)
Autocomplete issue continuing, no styles, seems like renderers can not be applied.
Dropdown just has multiple <pre>`<li class="" id="qs-option-1" role="option"><span class="qs-option-name"> Keyword</span><span aria-hidden="true" class="amount"></span></li>`</pre>

**Comment by romainruaud** [comment]
any update about this one @rbostan ? Are you still facing the issue ?

**Comment by rbostan** [comment]
@romainruaud 
Nope, styling issue is related with our current theme, not module. 
You may close this, thanks.

**Comment by richievalsalan** [comment]
Hi I am facing this issue in Magento2 EE


'Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed'

This is the error am getting. Even though all the index are indexed.
I have installed the 'ICU' and 'Phonetic' plugins also.

**Comment by truelogicapp** [comment]
catalog_product index does not exist yet. Make sure everything is reindexed

a:4:{i:0;s:75:"catalog_product index does not exist yet. Make sure everything is reindexed";i:1;s:8304:"#0 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCore/Search/Request/ContainerConfiguration.php(161): Smile\ElasticsuiteCore\Index\IndexOperation->getIndexByName('catalog_product', 1)
#1 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCore/Search/Request/ContainerConfiguration.php(94): Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration->getIndex()
#2 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCore/Search/Request/Builder.php(150): Smile\ElasticsuiteCore\Search\Request\ContainerConfiguration->getIndexName()
#3 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php(583): Smile\ElasticsuiteCore\Search\Request\Builder->create(1, 'catalog_view_co...', 0, 0, NULL, Array, Array, Array, Array)
#4 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php(189): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->loadProductCounts()
#5 /Applications/AMPPS/www/testsssports/var/generation/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(24): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->getSize()
#6 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Data/Collection.php(259): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getSize()
#7 /Applications/AMPPS/www/testsssports/var/generation/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(1610): Magento\Framework\Data\Collection->getLastPageNumber()
#8 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Data/Collection.php(245): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getLastPageNumber()
#9 /Applications/AMPPS/www/testsssports/var/generation/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(1597): Magento\Framework\Data\Collection->getCurPage(0)
#10 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php(484): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getCurPage()
#11 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php(393): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->prepareRequest()
#12 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Data/Collection/AbstractDb.php(338): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFiltersBefore()
#13 /Applications/AMPPS/www/testsssports/app/code/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection.php(430): Magento\Framework\Data\Collection\AbstractDb->_renderFilters()
#14 /Applications/AMPPS/www/testsssports/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(906): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFilters()
#15 /Applications/AMPPS/www/testsssports/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(727): Magento\Eav\Model\Entity\Collection\AbstractCollection->load(false, false)
#16 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Catalog\Model\ResourceModel\Product\Collection->load(false, false)
#17 /Applications/AMPPS/www/testsssports/var/generation/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(377): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->___callPlugins('load', Array, Array)
#18 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Data/Collection.php(820): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->load()
#19 /Applications/AMPPS/www/testsssports/var/generation/Smile/ElasticsuiteCatalog/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(1844): Magento\Framework\Data\Collection->getIterator()
#20 /Applications/AMPPS/www/testsssports/vendor/magento/module-catalog/Block/Product/ListProduct.php(321): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->getIterator()
#21 /Applications/AMPPS/www/testsssports/var/generation/Magento/Catalog/Block/Product/ListProduct/Interceptor.php(154): Magento\Catalog\Block\Product\ListProduct->getIdentities()
#22 /Applications/AMPPS/www/testsssports/vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php(71): Magento\Catalog\Block\Product\ListProduct\Interceptor->getIdentities()
#23 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Interceptor.php(152): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), ' <script>\n ...')
#24 /Applications/AMPPS/www/testsssports/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#25 /Applications/AMPPS/www/testsssports/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#26 /Applications/AMPPS/www/testsssports/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#27 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#28 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#29 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#30 /Applications/AMPPS/www/testsssports/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#31 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#32 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#33 /Applications/AMPPS/www/testsssports/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#34 /Applications/AMPPS/www/testsssports/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#35 /Applications/AMPPS/www/testsssports/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#36 /Applications/AMPPS/www/testsssports/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#37 /Applications/AMPPS/www/testsssports/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /Applications/AMPPS/www/testsssports/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}";s:3:"url";s:31:"/testsssports/men/tops-men.html";s:11:"script_name";s:23:"/testsssports/index.php";}

Can anyone help please.

ElasticSearch => 2.4.6
ElasticSuite => ElasticSuite 2.3.10
Magento EE => 2.1.x

Please reply ASAP

**Comment by farhadfrz** [comment]
Make sure that your catalog search engine is set to "ElasticSuite"

`bin/magento config:store:set catalog/search/engine elasticsuite
bin/magento cache:flush
bin/magento index:reindex`

**Comment by LiamKarlMitchell** [comment]
Same problem.

**Comment by catgento** [comment]
If this can help any of the people that asked here:
* In my case, the issue was related to a product attribute which was preventing one of the index to be indexed, even though the other ES indexes were being indexed correctly.
* This particular attribute was related to a module which we uninstalled but let the product attribute created in the database referencing to a model class that didn't exist anymore.
