### ISSUE TITLE
Sort categories by level in autocomplete results

### ISSUE THREAD

**Issue by Jackom9147** [Smile-SA/elasticsuite#3182]
I am trying to figure out how to be able to sort the categories that are shown in the search bar in div#autocomplete.
When the categories are shown I would like to be able to see the main categories first and then the subcategories after that.

How can I do this?

Thanks for any help!

**Comment by romainruaud** [comment]
Hi @Jackom9147 

Probably here : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Autocomplete/Category/DataProvider.php#L170

You could add a sort order on "level", this might require this field to be set as being sortable (by adding `<isUsedForSortBy>1</isUsedForSortBy>` under the "level" field, in the elasticsuite_indices.xml file under the category declaration : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/etc/elasticsuite_indices.xml#L89
