### ISSUE TITLE
Magento 2.4.7 compatibility

### ISSUE THREAD

**Issue by vahonc** [Smile-SA/elasticsuite#3188]
Magento 2.4.7 will land on April 9th.

Magento 2.4.7-beta2 is already available for partners and 2.4.7-beta3 will be available on March 12th.  

It's already been added to our integration test suite for branch 2.11.x. All tests are working actually which is a good start.

However, we need to check that all features are functioning as expected.

https://experienceleague.adobe.com/docs/commerce-operations/release/notes/adobe-commerce/2-4-7.html

https://developer-stage.adobe.com/commerce/php/development/backward-incompatible-changes/highlights/#247-beta2

So, let's make Elasticsuite compatible with it!

**Comment by Bashev** [comment]
Hi everyone,
i wants to notice one critical finding which is "[breaking change](https://github.com/magento/magento2/issues/36083)". Magento 2.4.7-beta3 have "silent" dependency of `psr/log` version `^2.0 || ^3.0` (I made a PR which will made it visible but will not solve the issue https://github.com/magento/magento2/pull/38524).

At the same time Magento requires `laminas-di` and accepts only `^1.0 || ^3.0`, this is fine until `opensearch-project/opensearch-php` dependency of *elasticsuite* accepts only version of `psr/log` ^1 || ^2`

**Comment by hostep** [comment]
Based on Magento 2.4.7-beta3, I've found with the help of the [ampersand upgrade tool](https://github.com/AmpersandHQ/ampersand-magento2-upgrade-patch-helper/) some preferences in this module on files in core Magento that changed between 2.4.6-p4 and 2.4.7-beta3:

```
+-------+------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Level | Type       | File                                                                                                | To Check                                                                                  |
+-------+------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| WARN  | Preference | vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php | Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Attribute |
| WARN  | Preference | vendor/magento/module-catalog-graph-ql/DataProvider/Product/SearchCriteriaBuilder.php               | Smile\ElasticsuiteCatalogGraphQl\DataProvider\Product\SearchCriteriaBuilder               |
| WARN  | Preference | vendor/magento/module-catalog-graph-ql/Model/Resolver/Aggregations.php                              | Smile\ElasticsuiteCatalogGraphQl\Model\Resolver\Aggregations                              |
+-------+------------+-----------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
```

After some digging in the git commits in core Magento, I've found following commits that contain changes:
- https://github.com/magento/magento2/commit/7ab48b08dc6cda2853c95033e44152fa98f89258 (Graphql Product visibility for search results)
- https://github.com/magento/magento2/commit/3674d12a1393c40468d8fe0411140518f8793c81 (GraphQL doesn't return attribute options with count 0(zero) when "Use in Layered Navigation" = "Filterable (no results)")
- https://github.com/magento/magento2/commit/563a8a53810ecfeac1bd238d36029b5d315fcb3c (emulate advanced search for graphql products filter match)
- https://github.com/magento/magento2/commit/24f0719817058e44f4f5bc5e804fada702a66b7b (Products query returns aggregations for products not assigned to a shared catalog)

No idea if any of these changes are important for this module, but maybe somebody should double check to make sure?

**Comment by ssx** [comment]
Considering this is out today - what's the current state of play?

Doesn't seem to be working as-is (v2.11.4.3) as an interface is mismatched:

```Fatal error: Declaration of Smile\ElasticsuiteCore\Model\ResourceModel\Search\Request\RelevanceConfig::_construct() must be compatible with Magento\Config\Model\ResourceModel\Config::_construct(?Magento\Framework\MessageQueue\PoisonPill\PoisonPillPutInterface $pillPut = null) in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php on line 98```

**Comment by Bashev** [comment]
@ssx this is fixed in v2.11.5.2

**Comment by vahonc** [comment]
Hello @ssx,

Did you install the ElasticSuite module using the `composer require smile/elasticsuite ~2.11.0` command?

BR,
Vadym

**Comment by vahonc** [comment]
@ssx,

A new release [2.11.6](https://github.com/Smile-SA/elasticsuite/releases/tag/2.11.6) is available.

BR,
Vadym

**Comment by vahonc** [comment]
I think that for now it is worth keeping this ticket open because the context of it is the general compatibility of our module with the latest version of Magento, including if our clients have any other issues.
