### ISSUE TITLE
Tracker url is down

### ISSUE THREAD

**Issue by yasser-moudouani** [Smile-SA/elasticsuite#3203]
The domain use to track seems down

### Preconditions
Use the search engine and check the error console

Magento Version : Magento commerce cloud 2.4.6-p4

ElasticSuite Version : 2.11.5.1

Environment : Production

### Steps to reproduce

1. Use internal search engine
2. check dev console 

### Expected result

1. No error related to https://t.elasticsuite.io/track

### Actual result

![image](https://github.com/Smile-SA/elasticsuite/assets/56895261/7a1d87b9-9f8b-453e-88f2-16cf4b170c6f)

**Comment by romainruaud** [comment]
Yes, this telemetry service has been disabled. This has no impact for you, it was just used by us to monitor our product usage.

You can disable the Telemetry by going to **Stores > Configuration > Elasticsuite > Tracking > Telemetry** and setting the Enable Telemetry parameter to No.

**Comment by yasser-moudouani** [comment]
Hi Romain, 
No problem I disable the feature on our website 
Regards, 
Yasser
