### ISSUE TITLE
Color attribute not showing in layered navigation

### ISSUE THREAD

**Issue by mcyrulik** [Smile-SA/elasticsuite#322]
We have our color attribute set up to be a visual swatch. Before we added ElasticSuite, the color attribute displayed and worked properly in the layered navigation. Now it does not even display. 

We have the storefront properties set to match what is noted in the wiki under "Attribute Configuration".

Looking in our elastic search index, the proper values for the color have been indexed, and the they are returned as attributes on the individual documents, but when I look at the response body for what seems like the aggregations, I see this for color:

"option_text_color":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]}

Looking at a custom attribute that is displaying properly in the layered navigation I see this:

"option_text_gw_specialty_length":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"None","doc_count":7324},{"key":"Petite","doc_count":1022},{"key":"Tall/Long","doc_count":115}]}

Thanks.
~Mark

**Comment by mcyrulik** [comment]
OK, after a little more digging, we have a custom source model on the color attribute. The model adds another array key to the toArray(), toOptionArray(), and getAllOptions(). It seems that this added array key is causing something to wither not index correctly, or not be returned correctly.

**Comment by romainruaud** [comment]
Hello @mcyrulik and thank you for submitting this issue.

I close it since it was due to a custom source model (and therefore not due to ElasticSuite) and you managed to fix it on you way.

Best regards,

**Comment by mcyrulik** [comment]
Agreed that it was not an ElasticSuite issue directly, but native Magento2 does not break with this type of custom source model. 

I do think that it would be nice if ElasticSuite didn't add in features that break things that Magento natively does not. 

call it a feature request, if you will.  :)
