### ISSUE TITLE
Magento 2.4.6-p3 and AWS opensearch 1.2 connection with smile elasticsuite

### ISSUE THREAD

**Issue by Mohammed-Megahed** [Smile-SA/elasticsuite#3254]
Hello,

Please I'm trying to connect AWS opensearch 1.2 with smile elasticsuite instead of local elastic search. How can I configure it with Magento 2.4.6-p3.

as all indexers are success except the 2 indexers of elasticsmile return No alive nodes

**Comment by romainruaud** [comment]
Hi @Mohammed-Megahed 

did you read the Wiki ? https://github.com/Smile-SA/elasticsuite/wiki
