### ISSUE TITLE
Is it possible to exclude graphql module dependency? Decouple gql 

### ISSUE THREAD

**Issue by ThisIsRuddy** [Smile-SA/elasticsuite#3255]
Hi,

Is there any way I can ignore/replace/not pull in the 'smile/src/module-elasticsuite-catalog-graph-ql' dependency?

This submodule has reliance on other Magento core gql modules which we have removed/replaced as we do not require them and therefore we cannot completely disable gql as a result

- magento/module-graph-ql
- magento/module-graph-ql-cache
- magento/module-graph-ql-resolver-cache
- magento/module-eav-graph-ql
- magento/module-catalog-graph-ql
- magento/module-customer-graph-ql
- magento/module-sales-graph-ql

I did attempt to add a replace entry in the magento projects root but unfortunately it causes a conflict due to the replace self.version  declaration in the elasticsuite module composer.json file.

I also tried patching the composer.json file but this didn't work either :(

**Comment by romainruaud** [comment]
Duplicate of #2043 

If you don't want the graphql modules, just disable them.

I don't get the point of removing them to be honest. They have no footprint on the legacy theme if you're not using GraphQl.

If you are worried about potential security flaws in the GraphQl entry point, just put a reverse proxy rule on the /graphql url.

Regards
