### ISSUE TITLE
How do I customize sort dynamically?

### ISSUE THREAD

**Issue by gustadev84** [Smile-SA/elasticsuite#3258]
Hi, 

I need to customize the sort dynamically using data from an external API.

Firstly I tried to create a plugin for Magento\Catalog\Block\Product\ProductList\Toolbar::setCollection trying to sort the order by the dynamic attribute, but it didn't work.

I tried to use \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection::setOrder, but it doesn't matter the order I set, Magento keeps listing the products sorted by Elasticsearch.

I'm even displaying the query used on the front end to be sure it's correct, but the list does not respect the query. Do you have an idea?

I want to add a new sort order item called "Points". When the category page or search page is ordered by "Points", Magento will call an API with the customer ID and the products and this API will return the Points to each product. This part of the call is already working. After this, I added an around plugin that set the collection's order by the Points. This part is not working, it keeps sorting by Elasticsearch order.

I'm using $collection->getSelect()->order('api_point ' . $direction) and api_point column is in the collection.

I can't index this data because it changes constantly.

Thanks

**Comment by romainruaud** [comment]
> I can't index this data because it changes constantly.

Then you'll not be able to make Elasticsearch sort on this data, unfortunately.

Elasticsearch is responsible for sorting : he will need a sortable field for doing so, with the proper data inside.

Regards

**Comment by gustadev84** [comment]
Hi @romainruaud 

Thanks for the reply. I found another solution.

Thanks
