### ISSUE TITLE
Error: php bin/magento setup:upgrade fails while trying to install elasticsuite 2.11.6.1 for magento 2.4.7 with elasticsearch 8

### ISSUE THREAD

**Issue by Playhf** [Smile-SA/elasticsuite#3273]
php bin/magento setup:upgrade failse with **No alive nodes found in your cluster** error while installing data from Smile_ElasticsuiteCatalog module.

Hello, I'm trying to install smile/elasticsuite:2.11.6.1 for magento magento/product-community-edition:2.4.7 and with magento/module-elasticsearch-8 installed. elasticsearch/elasticsearch module version is 8.5.3 (coming from magento/module-elasticsearch-8)

### Steps to reproduce
1. magento/product-community-edition:2.4.7 
2. composer require smile/elasticsuite ~2.11.0
3. php bin/magento setup:upgrade

### Expected result
Setup upgrade installs all things for elasticsuite module

### Actual result
<img width="471" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/30925570/f59819a7-cf90-4706-bdc8-83cd1170ce8c">

As you can see from the first screen issue is coming from \Smile\ElasticsuiteCatalog\Setup\InstallData::install (line 97)
After that module tries to create ElasticSuiteClient in \Smile\ElasticsuiteCore\Client\Client::getEsClient
as you can see here it always returns **\OpenSearch\Client for some reason.**
<img width="819" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/30925570/cc3a1f2a-f3bb-41b2-a569-4b575c835c27">

In \Smile\ElasticsuiteCore\Client\ClientBuilder::build it tries to build a client and on line 109 clientBuilder creates client object which must be an instance of \OpenSearch\Client
<img width="524" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/30925570/69cfc029-0c35-42e0-8b7c-aac6e7f41ef5">
<img width="568" alt="Screenshot 2024-05-09 at 15 39 49" src="https://github.com/Smile-SA/elasticsuite/assets/30925570/927984c9-7171-4a9c-affb-a68d2fdec15b">
After that attempting to make a test connection it fails because I don't have Open search installed. 

I can see a comment in \Smile\ElasticsuiteCore\Client\ClientBuilder::build it claims it must work with elasticsearch 8 but it doesn't
`We decided to use the OpenSearch client because he is versatile and can work with :
     * - Elasticsearch 7.x
     * - Elasticsearch 8.x
     * - Opensearch 1.x
     * - Opensearch 2.x`

Please assist. Thanks

**Comment by vahonc** [comment]
Hello @Playhf,

Yes, we know about it. For now, you can find a workaround here [#2880](https://github.com/Smile-SA/elasticsuite/issues/2880).

BR,
Vadym

**Comment by Playhf** [comment]
> Hello @Playhf,
> 
> Yes, we know about it. For now, you can find a workaround here [#2880](https://github.com/Smile-SA/elasticsuite/issues/2880).
> 
> BR, Vadym

@vahonc so what is the workaround? remove magento/module-elasticsearch-8 module and use elasticsearch/elasticsearch ~7.17.0 composer package?

Thanks

**Comment by vahonc** [comment]
@Playhf 

Yes, stay tuned, but keep using client v7 for now, while we work under refactoring.

BR,
Vadym

**Comment by Playhf** [comment]
@vahonc should i also downgrade smile/elasticsuite package version to any older? i removed magento/module-elasticsearch-8 package now have elasticsearch/elasticsearch:v7.12 but it still tries to execute OpenSearch since it is hardcoded in \Smile\ElasticsuiteCore\Client\ClientBuilder constructor.

Thanks

**Comment by vahonc** [comment]
@Playhf,

You don't need to downgrade `smile/elasticsuite` package version to any older, you just don't need to use the Elasticsearch8 Magento module.

Most probably, running `composer remove magento/module-elasticsearch-8` will make you rollback to `elasticsearch/elasticsearch` on version 7.x. 

If not, try doing:
```
$ composer remove magento/module-elasticsearch-8
$ composer require elasticsearch/elasticsearch ~7.17.0
```
Maybe you have an version issue: https://github.com/magento/magento2/blob/2.4.7/composer.json#L44

BR,
Vadym

**Comment by vahonc** [comment]
@Playhf 

As for this:
>i removed magento/module-elasticsearch-8 package now have elasticsearch/elasticsearch:v7.12 but it still tries to execute OpenSearch since it is hardcoded in \Smile\ElasticsuiteCore\Client\ClientBuilder constructor.

Are you sure that you select ElasticSuite as the default search engine?

![Screenshot from 2024-05-14 12-09-48](https://github.com/Smile-SA/elasticsuite/assets/67791361/2511d0b3-eebf-4459-beac-42180e243b7b)

Also, please check/provide the configuration of your Elasticsearch Client.

![Screenshot from 2024-05-14 12-11-04](https://github.com/Smile-SA/elasticsuite/assets/67791361/f954591c-b962-4c6f-acd3-c31671269718)

BR,
Vadym

**Comment by romainruaud** [comment]
@Playhf that's normal to have an OpenSearch client.

OpenSearch is just a fork of Elasticsearch (by Amazon). The OpenSearch PHP client is also a fork of the Elasticsearch PHP client v7.

Since the v8 of the Elasticsearch PHP client, there has been many changes in the code, making this client only reliable for connecting to ES 8 backend servers.

Since we have to support all the possible backend servers (Opensearch 1.x and 2.x, Elasticsearch 7.x and 8.x), we had to find the best possible option, which is to use the OpenSearch PHP client, because this client is able to connect to all the pre-listed flavors of Elasticsearch and Opensearch servers.

Please refer to Vadym's last post to ensure your search engine configuration is correct (Elasticsuite is selected as engine, and proper servers are configured).

Please also check the "Magento is already installed" chapter of our doc : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-already-installed-

You might have to run these commands (with proper config) : 

```
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/servers node-1:9200,node-2:9200
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/http_auth_user ""
bin/magento config:set -le smile_elasticsuite_core_base_settings/es_client/http_auth_pwd ""
bin/magento config:set -le catalog/search/engine elasticsuite
bin/magento app:config:import
```
