### ISSUE TITLE
Product widget preview

### ISSUE THREAD

**Issue by michdelzo** [Smile-SA/elasticsuite#3275]
Dear support,

we have problems viewing the preview of *Products* widget in the Magento BO when editing the description of a category for a specific store view.
Selecting a few conditions for which we know there are products that match them, the preview is collapsed (making it difficult to interact with the widget) and none of the products are showing.
It seems to us that elastic make use of the default index instead of using the index of that particular store view.
Some of the conditions we tested are:
* *Only products with image*
* *Only in stock products*

Could you support us with this problem?

Yours sincerely,
Michele

### Preconditions

Magento Version : 2.4.5-p6

ElasticSuite Version : 2.10.12.1

Environment : Production

Third party modules : none related to Elasticsuite

### Steps to reproduce

1. Access the BO
2. Edit a category (**Catalog > Inventory > Category**)
3. Change the scope to a specific store view
4. Edit the *Content > Description* of the category through Page Builder
5. Insert a *Products* widget (**Add Content > Products**)
6. Chose *Select Products By: Condition*
7. Insert one or more conditions such as *Only products with image*, *Only in stock products*
8. Save the widget
9. **PROBLEM**: The preview is collapsed and not showing products

### Expected result

The *Products* widget preview should show products as when you filter the product grid (**Catalog > Inventory > Products**) using the same conditions set.

### Actual result

The *Products* widget preview is collapsed (and difficult to interact with) and not showing products.

### Images
Conditions:
<kbd><img src="https://github.com/Smile-SA/elasticsuite/assets/169437869/c6347d18-5ef9-400b-9534-837a10ad447b" alt="conditions"/></kbd>

Preview:
<kbd><img src="https://github.com/Smile-SA/elasticsuite/assets/169437869/0bbada1b-517e-4b92-9e01-e7bf1dc2779e" alt="preview"/></kbd>

Products grid:
<kbd><img src="https://github.com/Smile-SA/elasticsuite/assets/169437869/3bc1f6a6-79ae-4799-893b-eba2c4010a26" alt="grid"/></kbd>

**Comment by romainruaud** [comment]
@michdelzo can you check that the PR #3315 is fixing your issue ?

It looks good to me and it's working locally but we're not having a really complex catalog for our testing purposes, a double check could be great.

Regards
