### ISSUE TITLE
Hyvä module

### ISSUE THREAD

**Issue by OvalMedia** [Smile-SA/elasticsuite#3279]
Hello,

I would like to point to some issues with the hyvä compatibility module posted in the private hyvä gitlab.
I know this is probably not the right place but it has been weeks without response. I also sent you a direct inquiry through a contact form on your website but nothing happened.

Is that module abandoned?

**Comment by romainruaud** [comment]
Nope, this module is still maintained but to be transparent it's not ideal for us that this module resides in the Hyvä gitlab, we're not checking it very often.

Regards

**Comment by OvalMedia** [comment]
So should I report here instead?

**Comment by romainruaud** [comment]
Hi, yes thanks for reporting the issue here.
