### ISSUE TITLE
Filtering Stock with Additional Product Attribute

### ISSUE THREAD

**Issue by artttj** [Smile-SA/elasticsuite#3294]
### Issue

I am trying to modify the stock filtering in the [Filter/Stock.php](https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-catalog/Model/Product/Search/Request/Container/Filter/Stock.php) file to consider an additional product attribute.

### Scenario
I have a boolean product attribute named `show_when_out_of_stock`.

### Goal
I want to filter products to display:

```
Products with `is_in_stock` set to `true` OR
Products with `is_in_stock` set to `false` AND `show_when_out_of_stock` set to true.
```

This means showing out-of-stock products only if they have the `show_when_out_of_stock` attribute set to `true`.

### Challenge
I attempted to add a nested query for this purpose. However, it seems that specifying a nested path is required, which does not exist by default in the stock data source. Additionally, I'm unsure how to incorporate the additional product attribute into the query.

Any advice or guidance on how to achieve this would be greatly appreciated. Thanks!

**Comment by vahonc** [comment]
Hello @artttj,

Could you elaborate on what exactly you want to achieve with the filtering?

BR,
Vadym

**Comment by artttj** [comment]
Hi @vahonc,

Thanks for your response!

We have globally enabled the display of out-of-stock products in Magento.

However, our requirement is to display only those out-of-stock products that have the "Display when out-of-stock" attribute set to true.

I hope it makes more sense.

**Comment by romainruaud** [comment]
Hi @artttj what you need is a BOOL query with multiple clauses : 

- is in stock
- OR :  "is not in stock" AND "is display out of stock".

Btw, the "is not in stock" clause can be removed as per boolean logic if I'm not wrong, so the resulting query would just be : 

- is in stock OR is display out of stock

You'll need to ensure that your "is_displayed_out_of_stock" attribute is set to "use for promo rules" and to maybe test either "1" or "true" for the value, depending the datatype you gave to it.

But something like (untested) should do the trick : 

```php
    public function getFilterQuery()
    {
        $isInStockQuery = $this->queryFactory->create(QueryInterface::TYPE_TERM, ['field' => 'stock.is_in_stock', 'value' => true]);
        $isDisplayOutOfStock = $this->queryFactory->create(QueryInterface::TYPE_TERM, ['field' => 'is_display_out_of_stock', 'value' => true]);

        $query = $this->queryFactory->create(QueryInterface::TYPE_BOOL, ['should' =>[$isInStockQuery , $isDisplayOutOfStock ]]);
        return $query;
    }
```

**Comment by artttj** [comment]
Hi @romainruaud 

This is exactly what we needed, and it works perfectly! Initially, I was attempting to use nested queries, but boolean logic and integer filtering did the trick.

Thanks so much for your help and detailed explanation!
