### ISSUE TITLE
elasticsuite_tracker_log_event data column has only image property

### ISSUE THREAD

**Issue by jenyatrishin** [Smile-SA/elasticsuite#3298]
A website works on the magento cloud. And there're a lot of records in the table 'elasticsuite_tracker_log_event' which are marked as invalid. Content in the column 'data' is only '{"image":"h.png"}'. What's possible reason of this problem and what's possible solution to resolve it? 
Magento 2.4.6, elasticsuite 2.11

**Comment by romainruaud** [comment]
https://elastic-suite.github.io/documentation/docs/ElasticSuite/Installing.html?qsdqsdqs#integration-with-magento-cloud-andor-fastly
