### ISSUE TITLE
Search returning no results after update to 2.11.7

### ISSUE THREAD

**Issue by JamesAllwood** [Smile-SA/elasticsuite#3304]
After updating ES to v2.11.7 from 2.11.6.1, search results have deteriorated, and in many situations, return no results at all

### Preconditions

Magento Version : 2.4.6-p6
ElasticSuite Version : 2.11.7
ElasticSearch Version :  7.16.3
Environment : Production
Third party modules : None (tested on a vanilla install with only Smile installed to confirm there are no 3rd party interferences)

### Steps to reproduce

1. Search for "Pico Downlight"

### Expected result

1. I expect to see 3 results

### Actual result

1. I get zero results

I used two vanilla installs, one with 2.11.6.1 installed and the other with 2.11.7 installed and repeated a test using the same database for the search term "Pico Downlight". I confirmed that on v2.11.6.1, three results were returned, but on v2.11.7 no results were shown

v2.11.6.1 results:

<img width="1273" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/5270957/92a63c74-9b88-4a88-8a62-4f7780ea28d6">

v2.11.7 results:

<img width="1280" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/5270957/367a4a4f-4065-41f2-b610-54907004d0b9">

I enabled debug mode to capture the request being sent between the different versions and found the following difference:

<img width="2304" alt="image" src="https://github.com/Smile-SA/elasticsuite/assets/5270957/a314db01-c07c-4d0f-973d-644722ee551a">

Is there any new configuration in v2.11.7 that needs to be adjusted in order to rectify this, or is this a bug?

**Comment by romainruaud** [comment]
Good catch @JamesAllwood 

The default configuration file for relevance has been deleted by mistake between 2.11.6.1 and 2.11.7 : 

https://github.com/Smile-SA/elasticsuite/blob/2.11.6.1/src/module-elasticsuite-core/etc/elasticsuite_relevance.xml
https://github.com/Smile-SA/elasticsuite/blob/2.11.7/src/module-elasticsuite-core/etc/elasticsuite_relevance.xml

**Comment by romainruaud** [comment]
2.11.7.1 fixed this.

Regards
