### ISSUE TITLE
Native behavior for optimizers on product listing

### ISSUE THREAD

**Issue by Thomsath** [Smile-SA/elasticsuite#3313]
Hi,

On our Magento 2 website, we have some optimizers configured (on brands, product type, etc.) for products listing. We are displaying 40 products per page. 
We have some optimizers that are not displaying, even if they are activated on the right store. For example, if we have a specific optimizer set on a specific brand (saved in table elasticsuite_optimizer row config) and if there is 0 product loaded in the 40 first products related to this brand, the optimizer will not display. 

### Question
Does the native behavior is supposed to be '**apply optimizers on the current loaded products collection**' (and so don't display a given optimizer if 0 product related to the optimizer config is find in the loaded collection), or should **the module load the product related to the optimizer separately**, if no optimizer is loaded in the collection ? Like if it plug a new product to the loaded collection (afterLoad ?)
I would like to be sure of the native behavior. 

Best regards,

**Comment by rbayet** [comment]
Hello @Thomsath,

I'm not 100% sure to understand your question, based on some sentences, like 
> We have some optimizers that are not displaying, even if they are activated on the right store.
and 
> should the module load the product related to the optimizer separately

Optimizers are never "displayed" in the frontend, they just impact your products collection if conditions (Request type, Condition rules, Request type Limitations) are satisfied.
The optimizers only affect a product **basic score** (which defaults to 1 in catalog navigation, and varies according to word matches in fulltext search), either making it bigger or lower.
The optimizers DO NOT decide if a product belongs or not to a collection (but of course, optimizers WILL decide if a product is shown in the first 40 or not).

The optimizers are applied at the search request level, so **not** on **a loaded** product collection but when the pre-load Elasticsearch request is performed.

Regards,
