### ISSUE TITLE
Products doesn't show in one of the store in multistore

### ISSUE THREAD

**Issue by mnowakCode** [Smile-SA/elasticsuite#3321]
After updating Elasticsuite from version 2.11.6.0 to 2.11.7, in one of the stores, products don't show. 

### Preconditions

Magento Version : Magento 2.4.6-p5 EE.

ElasticSuite Version : 2.11.7.0

Environment : The problem exists in both environment

### Steps to reproduce
1. Create a few stores (we have de_de, ch_de, fr_fr, ch_fr, b2b_de_de)
2. In version 2.11.6.0 all products are in all stores
3. After updating to version 2.11.7.0 products don't show in the b2b_de_de store. (only in the admin panel)

### Expected result
1. Products should be seen in all stores

### Actual result
1. <img width="1039" alt="image" src="https://github.com/user-attachments/assets/62ca33f2-0503-4adf-a77b-4ba785b395a8">

After a small investigation, I saw that a release 2.11.6.1 created the problem.

**Comment by vahonc** [comment]
Hello @mnowakCode,

>After a small investigation, I saw that a release 2.11.6.1 created the problem.

Not sure if I understood you correctly, is your problem still there or have you solved it?

BR,
Vadym

**Comment by vahonc** [comment]
@mnowakCode,

Have you tried to upgrade to the latest version of ElasticSuite?

Are you sure that all is configured correctly (ES is selected as the default search engine, etc), all data is reindexed and there are no any effects by 3rd party extensions?

Have you checked Elasticsearch and Magento logs?

BR,
Vadym

**Comment by mnowakCode** [comment]
@vahonc 
Yes, I checked everything. A few times switched versions and versions before version 2.11.6.1 works correctly. But after the version, it doesn't work.

**Comment by vahonc** [comment]
@mnowakCode,

>After updating to version 2.11.7.0 products don't show in the b2b_de_de store. (only in the admin panel)

So the problem is only with the displaying of products on the `b2b_de_de` store or are the products not displayed on other stores as well?

BR,
Vadym

**Comment by mnowakCode** [comment]
@vahonc 
The problem exists only in the b2b_de_de store

**Comment by vahonc** [comment]
@mnowakCode,

Probably something is wrong with the configuration of this store or with his index. 

Have you checked the status of the index in `ElasticSuite -> System -> Indices` (is this index a live) or use this command `curl http://localhost:9200/_cat/indices?v`?

Try to delete and then re-create this index.

BR,
Vadym

**Comment by mnowakCode** [comment]
@vahonc
Indices look good: 
![image](https://github.com/user-attachments/assets/5022bcb1-9d79-473f-a584-43cee8ea2668)

Please give me information on how to recreate Indices.

**Comment by mnowakCode** [comment]
@vahonc,
I didn't see the newest update from Friday. I updated the module now and it works.
I'm closing the issue.
