### ISSUE TITLE
Category Sort By Direction with Default Sort Direction Config

### ISSUE THREAD

**Issue by jesse-thomas** [Smile-SA/elasticsuite#3333]
The new category sort direction feature is awesome and definatly needed. 

We had implemented our own default sort direction (xml layout), since we default sort by a Most Popular metric, but we need it descending. So when I installed the new feature all our categories changed to sorting asc, or by least popular first. As is, we would have to go to each category and change the setting to desc (hundreds of categories). A quick patch flipped the behavior but now i'm stuck with a patch.

A more flexible solution would be to add a system config setting for Default Sort Direction under the Configuration > Catalog > Catalog > "Product Listing Sort by" setting. Then add a "Use Config Settings" check box on the category form. Then a default could be set and fewer categories would need be chaged to set the default. It could also allow for the system to default to allowing layout xml or some other method to still have an effect on sort direcion. 

Thanks for your consideration!

**Comment by romainruaud** [comment]
This was implemented in last releases.

Regards
