### ISSUE TITLE
Sort by Quantity is not working

### ISSUE THREAD

**Issue by nix0x00** [Smile-SA/elasticsuite#3341]
### Preconditions

Magento Version : 2.4.3-p3, via GraphQL

ElasticSuite Version : 2.10.3

Environment : Production & Developer

### Steps to reproduce

1. Enable sorting for quantity in stores > attributes > products > quantity_and_stock_status
2. reindex & clear cache
3. On PLP sort by Quantity, now the out of stock products should sorted however, they are not.

### Expected result

1. On the PLP when sorted by Quantity, products should be sorted by Out Of Stock status i.e. moved to end of page instead of having no affect and products are still sorted by position.

### Actual result

1. On the PLP when sorted by Quantity, products should be sorted by Out Of Stock status i.e. moved to end of page instead of having no affect and products are still sorted by position.

This was a bug which according to Magento was resolved in 2.4.3 release, however, when enabling this products are still not sorted. Perhaps elasticsuite is not sorting and saving by this type?

**Comment by vahonc** [comment]
Hello @nix0x00,

If I understand you correctly, you just need a solution to move out of stock products to the end of products on PLP?

If it's your case, then I suggest you create an optimizer to do this. Please refer to the our [Wiki](https://github.com/Smile-SA/elasticsuite/wiki/ProductSorting#using-the-search-optimizers), it's as simple as creating a positive boost and targeting **"Only in stock products"** in the rule section of the optimizer.

BR,
Vadym

**Comment by nix0x00** [comment]
Hello @vahonc,

Yes, I was able to achieve it via optimizer and I gave a positive boost of 2% to in stock products.

**Comment by vahonc** [comment]
@nix0x00,

So, your issue is solved and I can close this ticket?

BR,
Vadym
