### ISSUE TITLE
Request to porting the Elasticsuite Magento Extension to Manticoresuite Magento Extension

### ISSUE THREAD

**Issue by coresh** [Smile-SA/elasticsuite#3345]
Hello,

The [Elasticsuite](https://github.com/Smile-SA/elasticsuite) is a great solution. Thank you

But a great alternative:
[https://manticoresearch.com/](https://manticoresearch.com/)

**Is your feature request related to a problem? Please describe:**
**Describe the solution you'd like:**
Correct:  [The Performance](https://manticoresearch.com/blog/manticore-alternative-to-elasticsearch/)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered:
Manticoresearch:

[manticoresearch docs](https://manual.manticoresearch.com/Introduction)
[Manticoresearch - play](https://play.manticoresearch.com/)
[Manticoresearch - Elasticsearch-like requests](https://play.manticoresearch.com/elasticlike-requests/)
[Manticoresearch php-client](https://github.com/manticoresoftware/manticoresearch-php) and [HTTP JSON API](https://manual.manticoresearch.com/Searching/Full_text_matching/Basic_usage#HTTP-JSON)

**Additional context**
Would be great to porting the [Elasticsuite-Magento-Extension](https://github.com/Smile-SA/elasticsuite) to the e.g:
a new "Manticoresuite-Magento-Extension".

The reason: The Performance.

Thank you

**Comment by romainruaud** [comment]
Hi @coresh 

Thanks for suggesting this but I don't know how we'd be able to do this.

Manticoresearch and Elasticsearch are really different tools and doing this would be like restarting from scratch.

Regards

**Comment by coresh** [comment]
Hi @romainruaud 

Re: "this would be like restarting from scratch":

Correct.

It takes place to be.

The reason:

The performance: preferred.

Thank you
