### ISSUE TITLE
Product missing from the product listing page and category view in admin

### ISSUE THREAD

**Issue by abhisingh00** [Smile-SA/elasticsuite#3347]
After updating the ElasticSuite module from version 2.10.18 to 2.10.22.2, we encountered an issue where the top products from categories were missing. Additionally, new products added or enabled after the update are not appearing in the respective categories, even after reindexing.

### Preconditions

Magento Version : 2.4.5- p5

ElasticSuite Version : 2.10.22.2

Elasticsearch Version: 7.17.13

Environment : Developer or Production mode 

Third party modules :

### Steps to reproduce

1.Having simple products in various categories with similar properties and values.
2.Visiting the catalog pages / visiting categories section on adminhtml.
3.Having identical settings for all products.

### Expected result

1.All the products must have visible on the frontend and backend and must be searchable.
2. This should be the actual behaviour.
![image](https://github.com/user-attachments/assets/5837f421-52b1-4301-a6a2-896de39065f1)

### Actual result

1.Products which assigned to the category are showing on the table but not visible by Elastic 
![image](https://github.com/user-attachments/assets/f2d060f9-475c-4dc0-a675-f0a361bbb461)

2. Some products are products are not visible not searchable either including above.

**Comment by vahonc** [comment]
Hello @abhisingh00,

Are you sure that all data are re-indexed and there are no errors in Magento or Elasticsearch logs?

How exactly do you upgrade ElasticSuite (via composer or zip archive)?

BR,
Vadym
