### ISSUE TITLE
function score query returned an invalid score: NaN for doc

### ISSUE THREAD

**Issue by ryanisn** [Smile-SA/elasticsuite#3357]
### Preconditions

Magento Version : EE 2.4.6-p6

ElasticSuite Version :2.11.3.2

Environment :dev

Third party modules :

### Steps to reproduce

1.make sure there are some products exist in catalog
2.create a new product numeric attribute and flag it searchable
3, create a new search optimizer with model 'based on attribute value' that is based on this new attribute value
4, reindex
5, do a search on storefront

### Expected result

1. search works as normal and boosting rule applies

### Actual result

1. search returns no result
2. a elasticsearch exception is left in log: function score query returned an invalid score: NaN

the old products do not have a value on the new attribute, which causes this exception

**Comment by rbayet** [comment]
Hello @ryanisn,

Out of curiosity, does this happen whatever the "Boost impact" selected ?

Regards

**Comment by ryanisn** [comment]
@rbayet good question. we were using medium (sqrt)
now I see you provided `missing` parameter, it might be the negative values we have on products instead of missing values, does that make sense? 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html
> square root of a negative number is an illegal operation, and an exception will be thrown

**Comment by romainruaud** [comment]
Hi Ryan,

did you try to add a clause on the "Apply to Product" of your boost, a clause tht would say "My Attribute is greater than 0" ?

Regards

**Comment by ryanisn** [comment]
@romainruaud no we have negative values intentionally, I guess we just can't use medium boost
