### ISSUE TITLE
"Error: Call to a member function setName() on null" - on partial word search

### ISSUE THREAD

**Issue by mazurekiza** [Smile-SA/elasticsuite#3359]
### Preconditions
Magento Version : 2.4.7-p1

ElasticSuite Version : 2.11.8.3

Environment : developer and production mode

### Steps to reproduce
1. Set configuration for search fuzziness and phonetic to No.
![image](https://github.com/user-attachments/assets/820279dc-db02-44be-86ca-3f8666a0136b)
2. On search, try to search by part of the word. Example: full word is "jadalnia", part of word to search is "jada".
![image](https://github.com/user-attachments/assets/5552ac17-f160-4c8b-be61-0f4c8983bde6)

### Expected result
1. Search result page with info "No exact results found for: <b>'%1'</b>. The displayed items are the closest matches." should be rendered.

### Actual result
1. Error is displayed/logged into the file:
Error: Call to a member function setName() on null in /var/www/html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php:88

### Additional info
In class vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Fulltext/QueryBuilder.php:87 the $query variable is set as null because \Smile\ElasticsuiteCore\Search\Request\Query\Fulltext\QueryBuilder::getSpellcheckedQuery can and it returns null in case fuzzy and phonetic search are disabled.

**Comment by rbayet** [comment]
Thanks @mazurekiza for pointing out this bug and the detailed report.

This has been fixed in PR #3366 and merged on 2.11.x 
Will ship in the next release.

Regards
