### ISSUE TITLE
ElasticSuite Loses Connection to OpenSearch During Reindexing in Magento 2.4 Enterprise

### ISSUE THREAD

**Issue by diazrma** [Smile-SA/elasticsuite#3379]
**Preconditions**
Magento Version: Magento 2.4 (Enterprise)
ElasticSuite Version: ElasticSuite 2.10.22.2 (Open Source)
Environment: Production

**Steps to reproduce**
Run the reindex process in Magento.
Observe the behavior between ElasticSuite and OpenSearch.
Check the logs for connection issues between ElasticSuite and OpenSearch.

**Expected result**
Reindexing completes without losing the connection between ElasticSuite and OpenSearch.

**Actual result**
ElasticSuite sometimes loses connection with OpenSearch during reindexing.
![2024-09-12_08-13](https://github.com/user-attachments/assets/a33390b4-fa5d-483a-b0a8-cb2e013fb2f6)

**Comment by romainruaud** [comment]
hi @diazrma 

are you running on Adobe Commerce Cloud ? Who's your hosting provider ?

**Comment by diazrma** [comment]
Good affernoon, @romainruaud 
Yes is Adobe Commerce Cloud

**Comment by romainruaud** [comment]
well then the error you're seeing indicates that the Opensearch cluster was not reachable. This is not due to Elasticsuite. Did you ask Adobe Commerce Cloud team about this ?

Regards

**Comment by diazrma** [comment]
Good morning, yes we are going to open a ticket with them but they wanted to check with you first if you have ever had a similar case.
