### ISSUE TITLE
Price Filter show wrong Price number into the slider 

### ISSUE THREAD

**Issue by mahesh-makwana-web-vision** [Smile-SA/elasticsuite#3389]
In the category filter, the price filter shows a minimum price of €3.00, even though no products are listed with that price. There is a product priced at €3.90, which should be reflected in the filter.

### Preconditions
Magento ver. 2.4.5-p9
ElasticSuite Open Source ver. 2.10.15.1

Environment : Production

### Steps to reproduce
1. Add products to a category with prices ranging from €3 to €1000.
2. Ensure at least one product has a price of €3.90.
3. Run the reindexing and clear the cache.
4. Check the category filter.

### Expected result
1. The price filter should show the correct minimum price (e.g., €3.90) based on the actual product prices in the category.

### Actual result
1. The price filter shows a minimum price of €3.00, which does not match any product in the category.

![TEST](https://github.com/user-attachments/assets/7ba47285-7b32-4a2c-8a99-063d86286251)

**Comment by mahesh-makwana-web-vision** [comment]
Hello @romainruaud 

We are encountering an issue where the price filter is displaying incorrect values, including zero, even though no products have a zero price.

After reindexing, the issue is temporarily resolved, but it reappears after a few days.

What steps should I take to fix this issue?

Thanks.

**Comment by vahonc** [comment]
Hello @mahesh-makwana-web-vision,

Have you checked these two comments [#1](https://github.com/Smile-SA/elasticsuite/issues/3300#issuecomment-2311806550), [#2](https://github.com/Smile-SA/elasticsuite/issues/3300#issuecomment-2311572462)?

Are you able to test the wrong price number issue without the ElasticSuite module, cause there could be some bug in the core of Magento?

BR,
Vadym

**Comment by mahesh-makwana-web-vision** [comment]
Hello @vahonc 

In my case, the price is not showing as a negative number, but it's showing as zero, and the filter is displaying incorrect products as a result.

When I run the indexer, the issue is fixed, but after a few days, when I add or update products again, the issue reappears.

It seems that adding or updating products is causing something to go wrong with the indexer.

For your information, products are added and updated via an import script, so we do not use the Magento admin interface, and the indexer is set to scheduled mode.

Thanks.

**Comment by vahonc** [comment]
@mahesh-makwana-web-vision,

Could you enable the debug mode of Elasticsuite and give us the query it's generating?

Also, provide (if it's possible) a code of your import script.

BR,
Vadym
