### ISSUE TITLE
Categories: cannot manual sort out of stock products in back-end

### ISSUE THREAD

**Issue by tropilex** [Smile-SA/elasticsuite#3395]
Hello,

The out of stock products are not showed in the "Product List Preview and Sorting". So you cannot sort them manual. 

So the problem is that when you manual sort the products and then new stock comes for a product that product is not sorted and will be showed last.

**Magento setting**
Display Out of Stock Products = No

![Screenshot 2024-09-25 at 09 29 19](https://github.com/user-attachments/assets/bb55dd3e-c775-43ef-b46d-2b5a51f457d9)

Magento Version: 2.4.6-p7

ElasticSuite Version: 2.11.9 (but this is on older versions also)

Environment: Production

### Steps to reproduce
1. Go to Admin --> Catalog --> Category --> Select a category
2. Try to sort out of stocks manual 
3. You don't have the option to manual sort out of stock products

### Expected result
1. A full list of all products in the category so you can sort all products.

### Actual result

See the following screenshot. We have 9 products but only 3 available for manual sorting. 

![Screenshot 2024-09-24 at 21 56 15](https://github.com/user-attachments/assets/f2b56def-84e4-4447-aa41-2f84389ae69b)

**Comment by tropilex** [comment]
BTW: I tried this setting but that didn't help. It also says it's for a different 'problem' but you can always try. ;-)

![Screenshot 2024-09-25 at 09 43 42](https://github.com/user-attachments/assets/ab811b78-553f-42d6-9e9e-0443248ba752)

**Comment by rbayet** [comment]
The category preview shows you the list of products as they appeared in the currently selected or default store view.
If you chose to configure Magento to hide out-of-stock products in the frontend, yes, they will also be hidden in the category preview in the backend.

Indeed the second option "Ignore manual positions ..." is more for when you chose to **show** out-of-stock products but you don't want to have an "just been out-of-stock product" manually positioned in the frontend.
In that case only, the category preview is no longer "exactly what the frontend is showing".

Have you considered the following combination ?
* Showing out-of-stock products on your site
* But creating an optimizer to boost products that are in stock in catalog navigation: by default, your categories will first display in stock products and then out-of stock ones
* For specific categories, you will still have the ability to pin specific products at the first positions
* Depending on what you want to achieve you will be able to keep products pinned at their configuration position OR NOT depending on "Ignore manual positions of [...]"

Regards,

**Comment by tropilex** [comment]
Hello @rbayet ,

Thanks for your reply. It is much appreciated!

Unfortunately we don't want to show out of stock products. Then we get too many questions about when the product will be back in stock. 

I actually find it quite weird that you can only sort manually if you happen to have all products in stock at that specific moment. Otherwise the function is quite useless. This was also not necessary with the regular Position. 

The only solution I see is to set ‘Display Out Of Stock’ to Yes. Then manually rank the category and then set ‘Display Out Of Stock’ to No again. And then hope it saves the positions correctly, even in the event of any minor change.

Is there any way to get the native Magento Position back again? That it is a bit more visually appealing now and you then drag and drop is unnecessary for us.

Regards, Kees

**Comment by rbayet** [comment]
Hello @tropilex,

You can try the following : 
- disable the Smile_ElasticsuiteVirtualCategory module (you will lose the backend category preview and the Virtual Category feature, though)
- either patch \Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData or add the following definition somewhere to your DI to make sure the position "0" (the first in Magento 2 native positioning mechanism) is not ignored when indexing category data
```
    <type name="Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\CategoryData">
        <arguments>
            <argument name="filterZeroPositions" xsi:type="boolean">false</argument>
        </arguments>
    </type>
```
- if you want to get back the product positions you had already configured, you'll need to look for them in the custom DB table `smile_virtualcategory_catalog_category_product_position`

Regards,

**Comment by tropilex** [comment]
Thanks. We will look in to it if this is a good solution for us!
