### ISSUE TITLE
index error: Cannot delete indices that are being snapshotted

### ISSUE THREAD

**Issue by ryanisn** [Smile-SA/elasticsuite#3402]
### Preconditions

Magento Version :
EE 2.4.6-p4

ElasticSuite Version :
2.10.11

Environment :
production

Third party modules :

### Steps to reproduce

1.reindex all

### Expected result

1. index finishes succesfully

### Actual result

1. index exit with error
Catalog Search index has been rebuilt successfully in 00:07:16
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:01
ElasticSuite Thesaurus Indexing index process error during indexation process:
{"error":{"root_cause":[{"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[magento2_default_thesaurus_20241003_132033/9BlOPlftS8m9-jWL1QX0Kg]]. Try again after snapshot finishes or cancel the currently running snapshot."}],"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[magento2_default_thesaurus_20241003_132033/9BlOPlftS8m9-jWL1QX0Kg]]. Try again after snapshot finishes or cancel the currently running snapshot."},"status":400}

This is a very very case, but with indexer runs constantly on a prod server, we would observe this happens a few times a month.
Our opensearch is on AWS and has a hourly snapshot that is enforced.
related comment
https://github.com/wagtail/wagtail/issues/6100

**Comment by romainruaud** [comment]
Hello @ryanisn 

not much to tell about this one, if you have an AWS plan allowing you to reach their support to ask them to not proceed these hourly snapshots (which are useless for Elasticsuite), this is the way to go.

Best regards
