### ISSUE TITLE
Price slider JS breaks in Dutch shop (2.10.23+)

### ISSUE THREAD

**Issue by mdesplenter** [Smile-SA/elasticsuite#3405]
When updating a shop with nl_NL translation from es 2.10.22.3 to 2.10.23.x , the price slider breaks with a JS error.
![Screenshot 2024-10-07 at 15 43 11](https://github.com/user-attachments/assets/f564b9bc-ec6c-46ee-b52d-da68545f0871)

The variable is suddenly translated, this is the JS that's been generated:

`(function anonymous(obj,_
) {
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
with(obj||{}){
__p+=''+
((__t=( aantal ))==null?'':_.escape(__t))+
' producten';
}
return __p;
})`

### Things I tried
- Only updating this module, not the other modules to rule them out
- I also tried it a clean nl_NL instance, same result.
- Toggling the new Custom Stemmer to force English instead of Dutch, same result.
- Toggling the Custom Stemmer to use default

### Preconditions
Magento Version : 2.4.5-p8 and 2.4.5-p9

ElasticSuite Version : 2.10.22.3 (ok), 2.10.23.x generates the error

Environment : Dev and production

Third party modules :
"amasty/shippingtablerates": "^1.9",
"community-engineering/language-nl_nl": "^0.0.47",
"cweagans/composer-patches": "^1.6",
"experius/module-postcode": "^1.8",
"magento/product-community-edition": "2.4.5-p8",
"mollie/magento2": "^2.11",
"yireo/magento2-taxratesmanager2": "^1.2",
"yireo/magento2-webp2": "^0.13.0"

### Steps to reproduce
1. Update smile elasticsuite to 2.10.23.*
2. Open a category with the price slider
3. change the value

### Expected result
1. Filter with the slider value

### Actual result
1. Console error of screenshot

**Comment by vahonc** [comment]
Hello @mdesplenter,

There is a problem with translating a variable in the script. Try temporarily editing the file with the Dutch translation inspired by my commit until we publish a new release that will also include this fix.

BR,
Vadym
