### ISSUE TITLE
Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /datas/prod/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php on line 252

### ISSUE THREAD

**Issue by EA-SK** [Smile-SA/elasticsuite#3410]
Cron Job elasticsuite_index_log_event has an error: Deprecated Functionality: trim()

Exception: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /datas/prod/vendor/smile/elasticsuite/src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php on line 252

### Preconditions

Magento Version : 2.4.7-p2

ElasticSuite Version : 2.11.9

Environment : production

**Comment by romainruaud** [comment]
HI @EA-SK this has been fixed and will be part of an upcoming release quite soon : https://github.com/Smile-SA/elasticsuite/blob/2.11.x/src/module-elasticsuite-tracker/Model/ResourceModel/EventQueue.php#L252

Best regards

**Comment by rbayet** [comment]
Fixed in #3398 and available in 2.10.23.1 and 2.11.9.1
