### ISSUE TITLE
Disabling category sort

### ISSUE THREAD

**Issue by rbostan** [Smile-SA/elasticsuite#344]
Hello,

Can i use original product positions in categories instead of modules logic?
How can i disable that feature?

**Comment by rbostan** [comment]
@romainruaud @afoucret Any ide for this ?

**Comment by romainruaud** [comment]
Hello @rbostan ,

the original product positions sorting in the categories is still working. You can set product position and they will be used for sorting in Front Office.

We just added a more easy-to-use and ergonomical drag and drop feature, but did not disable the native feature.

Best regards,

**Comment by rbostan** [comment]
@romainruaud It is not working like that :)
After starting to use module, products listing in categories ordering most popular search results in that category.

For example, we set a 'chair' category position to top place.
After a few search about 'table', in category 'table' starts to shown in top place.
Double checked.

**Comment by romainruaud** [comment]
I am afraid but I know how is working our module ... We did not made such a feature like "autoboosting" (although it could be interesting).

Could you please tell me if you are using any third party modules ?

Also, to ensure I am understanding your issue properly, can you please attach screenshots where I can see how is configured you category in Back-Office, and also what is rendered in Front-Office ? Especially which sort order is applied.

Best regards,

**Comment by rbostan** [comment]
@romainruaud 
I didn't argue about your knowledge of module lifecycle.

But If it is not related this module, why it is working fine (as expected, sorted by position) after disabling elasticsuite?

I'll digg to deeper. If i found a clue, inform you.
See you.

**Comment by romainruaud** [comment]
Hello @rbostan ,

for us, the behavior you are describing (the "chair" product moving by itself on top of the list after a few search) is clearly not related to ElasticSuite.

But after looking back, it's in fact clear that we do not rely on the "position" field for sorting.

In fact, we are sorting products in front office the following way : 

- First comes the products which have been set to "Manual Sort" by the Drag and Drop feature

- Then the boosts (Catalog Optimizers) if some of them are applicable.

- If there are no boosts, then all products have the same score (which equals to 1).

- Finally, all products having the same score are sorted by their entity_id (desc).

But what is clear now, is that we have to remove the "position" column from this back-office grid to prevent any confusion for our users. That will be done in the next minor version of the module.

Best regards

**Comment by afoucret** [comment]
To avoid confusion the position column have been removed from admin when using ElasticSuite (PR #354).

BR

**Comment by cefrigo** [comment]
sorry  to add to this, but is there any plan to make sorting by position an option, i came across recently with an store, that has 50K+ products and TONS of categories, they used to use position and the sorting agent in this store, after the smile SA was installed the products in those categories lost the position because as it was said here you dont use position for sorting, maybe not a big release but can you point me to where should i look into to make a module customizing this to sort by position ?
