### ISSUE TITLE
After Upgrade to Magento 2.4.7., setup:upgrade throws "ElasticSuite : Unable to validate connection to Elasticsearch server : No alive nodes found in your cluster"

### ISSUE THREAD

**Issue by constancyGmbH** [Smile-SA/elasticsuite#3460]
We updated Magento from 2.4.6-p8 to 2.4.7-p3.
Now we get "ElasticSuite : Unable to validate connection to Elasticsearch server : No alive nodes found in your cluster" when we run setup:upgrade in the console. 

Magento Version : Magento 2.4.7-p3 CE

ElasticSuite Version : 2.11.9.2

Environment : Production Mode

### Steps to reproduce
1. Updated Codebase to Magento 2.4.7.
2. run bin/magento setup/upgrade

### Expected result
1. bin/magento setup/upgrade runs without an error

### Actual result
Updating modules:
ElasticSuite : Unable to validate connection to Elasticsearch server : No alive nodes found in your cluster

**Comment by constancyGmbH** [comment]
I have another instance (the live system) connected to the elastic search, so the Server is running and working. maybe there is a problem with the configuration in magento itself. Is there a way to test the connection with my access data from the DB to verify, that there is no config issue?

**Comment by vahonc** [comment]
@constancyGmbH,

Are you sure the **Search Engine** is set to **ElasticSuite** in `Configuration -> Catalog -> Catalog -> Catalog Search -> Search Engine`?

Have you checked Magento and Elasticsearch logs?

Which version of Elasticsearch and which Magento module (magento/module-elasticsearch-7 or magento/module-elasticsearch-8) you are using?

BR,
Vadym

**Comment by constancyGmbH** [comment]
Yes, it is set to ElasticSuite
![image](https://github.com/user-attachments/assets/aa934a11-efdc-40f4-81c2-d817756dfde4)

We use ES7 (magento/module-elasticsearch-7).

Server Version is 7.17.13

**Comment by vahonc** [comment]
@constancyGmbH,

Have you checked Magento and Elasticsearch logs?

What you have after running this query to DB: `SELECT * FROM core_config_data where path like '%elasticsuite%';`

BR,
Vadym

**Comment by constancyGmbH** [comment]
![image](https://github.com/user-attachments/assets/3d567450-1107-42bd-855b-aa875c27b3af)

**Comment by constancyGmbH** [comment]
I found the problem. I saw that the Server is missing in the configuration (database). I added the server an now it is working.
Thanks for the help and pointing me out to the missing conf.
