### ISSUE TITLE
Category Edit page don't work in Magento EE

### ISSUE THREAD

**Issue by nuzil** [Smile-SA/elasticsuite#347]
Hello We are using Magento EE.
In case if create backend user with Website restricted permissions, appear fatal error on Category Edit page in backend

Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function getId() on null in /Users/alexlyzun/Projects/code/aboshop3/www/vendor/magento/module-ui/Component/Wrapper/UiComponent.php on line 0

**Comment by romainruaud** [comment]
Hello @nuzil and thank you for submitting this issue.

I confirm I have the same problem on my EE instance after creating a new backend user with restricted permissions on a given website.

Thank you for submitting it, we'll look how to fix this one and provide a solution.

Best regards,

**Comment by afoucret** [comment]
This have been fixed on branches master, 2.3.x and 2.4.x.
Will be present in a coming bugfix release.

**Comment by nuzil** [comment]
Thanks a lot :)
