### ISSUE TITLE
Recoverable Error: Object of class Smile\ElasticsuiteVirtualCategory\Model\Rule could not be converted to string

### ISSUE THREAD

**Issue by rbostan** [Smile-SA/elasticsuite#357]
### Preconditions

Magento Version : 2.1.2

ElasticSuite Version : 2.4@dev

Environment :Developer and Production

Third party modules :

### Steps to reproduce

1. Install module by reading docs
2. Working fine for a while

### Expected result

1. Not affected to frontend

### Actual result

1. In cron_schedule table error logged

<pre>
In 'indexer_update_all_views' job:
Recoverable Error: Object of class Smile\ElasticsuiteVirtualCategory\Model\Rule could not be converted to string in
/home/domain/public_html/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228
<pre>

**Comment by romainruaud** [comment]
Hello @rbostan ,

did you update recently the module ? This has been fixed by this commit : https://github.com/Smile-SA/elasticsuite/blame/2.4.x/src/module-elasticsuite-virtual-category/Model/Rule.php (see implementation of the toString() method).

Regards,
