### ISSUE TITLE
elasticsuite Authentication error

### ISSUE THREAD

**Issue by anandukrishna-olt** [Smile-SA/elasticsuite#359]
I use fedora 23 with magento 2.1.3 CE

ElasticSuite Version : 2.3

Environment : Developer mode

Third party modules : PayUIndia, OpsWay

While giving composer require smile/elasticsuite, it asks for an authentication details.... which i dont know how to create or specify one... please help me...

I use elasticsearch V 2.1 in my magento development instance.

**Comment by afoucret** [comment]
The authentication is the Magento repository one : http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

Nothing special on our side.

**Comment by anandukrishna-olt** [comment]
Thanks For your Help..
