### ISSUE TITLE
Fatal error on Category View Page

### ISSUE THREAD

**Issue by nuzil** [Smile-SA/elasticsuite#360]
Got a strange error on Category View Page. But not sure to what is it related, because its appear only on  SOME category view pages. At the moment don't see any logic why.

In case somebody saw it already or have an idea:

Error is follows:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getFields() on null in /home/live/releases/6/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product/AttributeList.php:150\nStack trace:\n#0 /home/live/releases/6/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(85): Smile\\ElasticsuiteCatalogRule\\Model\\Rule\\Condition\\Product\\AttributeList->getAttributeCollection()\n#1 /home/live/releases/6/vendor/magento/module-rule/Model/Condition/AbstractCondition.php(83): Smile\\ElasticsuiteCatalogRule\\Model\\Rule\\Condition\\Product->loadAttributeOptions()\n#2 /home/live/releases/6/vendor/magento/module-rule/Model/Condition/Product/AbstractProduct.php(111): Magento\\Rule\\Model\\Condition\\AbstractCondition->__construct(Object(Magento\\Rule\\Model\\Condition\\Context), Array)\n#3 /home/live/releases/6/vendor/smile/elasticsuite/src/module-elasticsuite-catalog-rule/Model/Rule/Condition/Product.php(77):

**Comment by afoucret** [comment]
You should try to :

* Empty the cache `bin/magento cache:clean`

* Reindex all : `bin/magento indexer:reindex``

**Comment by romainruaud** [comment]
Hello @nuzil ,

did you update to latest 2.3.x branch ? I'm not sure you did because getFields() is not on line 150 anymore.

This must be related to your other issue regarding Website Restrictions, for which I had to fix this class, because it was not properly retrieving current store view (and therefore the associated mapping).

Regards

**Comment by romainruaud** [comment]
Since this should have been fixed since 2.3.3 I close the issue.

Feel free to reopen it if you still encounters.

Best regards,
