### ISSUE TITLE
Filtering without choosing category.

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#364]
Is it possible to use elastic filtration without choosing category (ex. filter all products only by price) ?

### Preconditions
OS: Linux debian-8 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
Magento Version: 2.1.4 CE
ElasticSuite Version: 2.3.3
Environment: developer

**Comment by romainruaud** [comment]
Hello @madonzy ,

I am not sure to understand what you plan to do ? Do you mean programatically ? Eg : retrieve a product collection and filter it ?

**Comment by southerncomputer** [comment]
If I select a filter before searching (first time search since login) then the filtered query will fail, manually searching for anything, then applying a filter works fine?

Any ideas on why this would be the case? I might want to select category or query with attribute from a menu?

**Comment by romainruaud** [comment]
@southerncomputer I'm not sure how your question is related to @madonzy issue ?

Please open a new issue if this is not related, or provide more explanation about how it is linked if you think this is the case.

Regards,

**Comment by romainruaud** [comment]
I close this one for following reasons : 

- unclear, and not enough details given. @madonzy please re-open the issue with more details if still needed.

- unclear if @southerncomputer issue is related to the original one : please create a new issue if this is not related.

Best regards
