### ISSUE TITLE
Error in Virtual Category since update to ElasticSuite 2.3.3

### ISSUE THREAD

**Issue by DogSports** [Smile-SA/elasticsuite#366]
### Preconditions
**OS**: Ubuntu 16.04.2 LTS
**Magento Version**: 2.1.4 CE
**Environment**: developer
**ElasticSuite Version**: 2.3.3

Error shown since update from ElasticSuite 2.3.2 to 2.3.3

### Steps to reproduce
1. Create a Virtual Category
2. Select a Virtual rule(s)
3. Save
4. Reindex all
![elasticsuite233-01](https://cloud.githubusercontent.com/assets/9626689/24239954/2f69daf2-0fb0-11e7-91b2-4bbfbd563bef.jpg)

### Expected result
1. All products are dislayed in the category

### Actual result
1. Only "manual sort" products are displayed.
![elasticsuite233-02](https://cloud.githubusercontent.com/assets/9626689/24239963/3625db84-0fb0-11e7-8113-64c8d670275b.jpg)

**Comment by romainruaud** [comment]
Fixed by PR #368 , please migrate to 2.3.4 version and process cache clean and compile.
