### ISSUE TITLE
Fresh Install fail : Data change made in Schema

### ISSUE THREAD

**Issue by MacFJA** [Smile-SA/elasticsuite#37]
In a **InstallSchema** Setup there are data that are changes. But on a fresh install there are no data at this time (see below).

The method that cause an installation failure is: [Smile\ElasticSuiteCatalog\Setup\InstallSchema::updateDefaultValues](https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Setup/InstallSchema.php#L161)

--
Magento run setup in this way:
 - Loop on each modules
   - Run `InstallSchema`
   - Run `UpdateSchema` (if available)
 - Loop on each modules
   - Run `InstallData`
   - Run `UpdateData` (if available)

**Comment by afoucret** [comment]
My bad. The issue #36 was closed by this not this one.

**Comment by afoucret** [comment]
Fixed by PR #47 

**Warning :** ES need to be started during initial install since Magento run a catalogsearch full reindex.
