### ISSUE TITLE
Error on installation: Indexer handler is not available: elasticsuite

### ISSUE THREAD

**Issue by adamj88** [Smile-SA/elasticsuite#372]
### Preconditions

When running `bin/magento setup:install` on an empty database with nothing but Magento CE v2.1.5 and elasticsuite installed the setup reaches the following stage and fails with the below error:

```
[Progress: 359 / 538]
Module 'Magento_CatalogSearch':
Installing data... 

                                                  
  [LogicException]                                
  Indexer handler is not available: elasticsuite
```                                                  

**Magento Version:** Magento 2.1.5 CE

**ElasticSuite Version:** 2.3.4

**Environment:** Developer

**Third party modules:** None

### Steps to reproduce

1. Start with blank project and empty database
2. Add `"magento/product-community-edition": "2.1.5",` and `"smile/elasticsuite": "2.3.4",` to composer.json
3. `composer install`
4. Run `bin/magento setup:install`, e.g.: 

```
bin/magento setup:install --db-name=magento2 --db-host=localhost --db-user=user --db-password=password --db-model=mysql4 --db-engine=innodb --db-init-statements=SET NAMES utf8; --cleanup-database --admin-user=admin --admin-password=paddword --admin-firstname=Admin --admin-lastname=User --admin-email=dummy@gmail.com --backend-frontname=admin --use-secure-admin=0 --admin-use-security-key=1 --base-url=http://localhost/ --base-url-secure=0 --use-rewrites=1 --session-save=files --currency=GBP --timezone=Europe/London --skip-db-validation --use-secure=0
```

### Expected result

1. `setup:install` successfully completes and installs the extension.

### Actual result

1. `setup:install` fails to install at the Magento_CatalogSearch stage with the following error:

```
[Progress: 359 / 538]
Module 'Magento_CatalogSearch':
Installing data... 

                                                  
  [LogicException]                                
  Indexer handler is not available: elasticsuite

```

**Comment by romainruaud** [comment]
Hello,

did you properly install ElasticSearch and all required modules ?

Can you check if elasticsearch is runnning with this command : ``` curl localhost:9200```. You should replace localhost by your elasticsearch instance location if you are running it on a separate server.

By the way, if you are running elasticsearch on an other server, ensure you follow this part of the wiki : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#optional--installing-the-module-when-using-a-custom-elasticsearch-server-location

Best regards,

**Comment by adamj88** [comment]
@romainruaud Thanks for the reply - the ElasticSearch modules are all installed using composer.

Given the above wiki section it says using a different server other than `localhost:9200` requires a modification to `etc/config.xml` I presume this way doesn't support installation via composer.

Would it be advisable to move this configuration to Magento 2's admin configuration allowing you to install it via composer and run `setup:install` successfully and worry about if elasticsearch is running at the point of enabling and configuring the module inside the admin?

**Comment by romainruaud** [comment]
Hello @adamj88 ,

the documentation does not imply to modify the elasticsuite etc/config.xml file but to create your own module that will contain your configuration for Elasticsuite.

This does not block you from installing the module via composer if you want.

regards,

**Comment by adamj88** [comment]
@romainruaud Sorry my mistake!
