### ISSUE TITLE
Class 'Magento\Catalog\Model\Layer\Filter\ItemFactory' not found 

### ISSUE THREAD

**Issue by rootindex** [Smile-SA/elasticsuite#38]
```bash
$ bin/magento dev:tests:run static
---- dev/tests/static> php ./vendor/phpunit/phpunit/phpunit

Fatal error: Class 'Magento\Catalog\Model\Layer\Filter\ItemFactory' not found in vendor/smile-sa/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Item/AttributeFactory.php on line 23

```

I know that class will exists after the Factory gets created automatically however for static testing fails each time.

**Comment by romainruaud** [comment]
Hello,

thank you for reporting this.

We will try to propose a better static-testing aware feature by moving these factories into Virtual Types if possible.

We'll keep in touch.

Regards,
