### ISSUE TITLE
Bring back the optimizer preview!

### ISSUE THREAD

**Issue by djenvert** [Smile-SA/elasticsuite#383]
The optimizers are back and it's a great news.
It would be even greater if we had the preview feature embedded in the back office screen just like the old days.

***what?***
A simple search box

two columns : 

- the results without the optimizer we're currently building, live update
- the results with the optimizer applied, live update, with fancy arrows indicating whereas the product was boosted or not

Extra features (I could create new tickets if needed but I note them here to avoid forgetting them)
- ability to memorize previously searched terms, for quick access
- extra third column or switch on the second column with only the current boost applied (and not the other existing ones)

**Comment by romainruaud** [comment]
Feature has been merged in 2.4.x branch.
