### ISSUE TITLE
Missing required argument $data of Smile\ElasticsuiteCatalog\Model\Category\Indexer\Fulltext.

### ISSUE THREAD

**Issue by robbanl** [Smile-SA/elasticsuite#384]
The table `cron_schedule` is filled with errors for the index `indexer_update_all_views`. The error message given is `Missing required argument $data of Smile\ElasticsuiteCatalog\Model\Category\Indexer\Fulltext.`.

### Preconditions
Magento Version : CE 2.1.5
ElasticSuite Version : ^2.3
Environment : both
Third party modules : None

**Comment by idsergiu** [comment]
workaround: 
<type name="Smile\ElasticsuiteCatalog\Model\Category\Indexer\Fulltext">
        <arguments>
            <argument name="data" xsi:type="array" />
        </arguments>
</type>

**Comment by romainruaud** [comment]
PR #388 will fix this issue.

Please wait for the next minor release,

thank your for submitting this issue.

Best regards,
