### ISSUE TITLE
Ergonomy of filters arrow

### ISSUE THREAD

**Issue by cldha** [Smile-SA/elasticsuite#385]
Hi there,

On Magento 2.1, on the category pages, the arrows next to the filters are adapted to the state of the filter: 

- Filter opened - arrow points upwards
- Filter closed - arrow point downwards  

However with the ElasticSuite module, the arrows always point downwards : http://demo.magento-elastic-suite.io/index.php/women/tops-women/tanks-women.html, as it does not take into account the state of the filter (open or closed)

From an ergonomy point of view, it would be best to adopt the native Magento behavior. 

Thank you in advance,

Kind regards,
Claire

**Comment by romainruaud** [comment]
Hello @cldha and thank you for submmiting this issue.

The PR #387 will fix it. Please wait for the next minor release or feel free to add it as a workaround on your stylesheet now.

Best regards,
