### ISSUE TITLE
Can't create optimizer for category view

### ISSUE THREAD

**Issue by Pigau** [Smile-SA/elasticsuite#392]
### Preconditions

Magento Version : EE 2.1.4
ElasticSuite Version : 2.3.4
Environment : Dev & Prod

### Steps to reproduce

1. Create an optimizer with "catalog_view_container" as request type
2. Check the category on front

### Expected result

1. The optimzer should be used for the category view request

### Actual result

1. The optimizer is ignored because the request type for the category view is "quick_search_container"

I personnaly correct this by changing the ItemCollectionProvider of the Layer\Category\Contex virtual type :
```
<virtualType name="Magento\CatalogSearch\Model\Layer\Category\Context" type="Magento\Catalog\Model\Layer\Category\Context">
  <arguments>
    <argument name="collectionProvider" xsi:type="object">Magento\CatalogSearch\Model\Layer\Category\ItemCollectionProvider</argument>
  </arguments>
</virtualType>
```

**Comment by romainruaud** [comment]
Fixed by PR #398 . Please wait for the next minor 2.3 release or feel free to use the 2.3.x branch while waiting for it.

Best regards,
