### ISSUE TITLE
500 internal server error while searching terms.

### ISSUE THREAD

**Issue by geek96** [Smile-SA/elasticsuite#401]
### Preconditions

Magento Version : 2.1.5

ElasticSuite Version : 2.3

Environment : Development

Third party modules : **no**

### Steps to reproduce

1.  Search any term i.e "gear"

### Expected result

1. Products should be display in auto complete list

### Actual result

![screenshot from 2017-04-23 16-01-12](https://cloud.githubusercontent.com/assets/26523208/25313383/c9195dae-2846-11e7-9651-005df8362655.png)

All products and categories are indexed in appropriate elasticsearch index so when I try to search any product or category got above error

Thanks

**Comment by romainruaud** [comment]
Hello @geek96 and thank you for submitting this issue.

Which version of Elasticsearch are you using ?

**Comment by romainruaud** [comment]
I close this one due to being inactive for one week.

Do not hesitate to reopen it and give us more details about the version of ElasticSearch (and Elasticsearch PHP client) as I asked previously.

Best regards,

**Comment by geek96** [comment]
I have tried with the following configuration.
Elasticsearch: 2.4.3, 2.4.4
PHP Elasticsearch Clint: 2.0
Thanks

**Comment by tukker01** [comment]
Same isseu here after installing Comwrap_ElasticsuiteBlog 
HTTP ERROR 500 error on every search query 
When disable Comwrap_ElasticsuiteBlog it works fine.
Same isseu with module CMS Search

**Comment by tukker01** [comment]
Same isseu here is there a solution?
