### ISSUE TITLE
I cannot navigate to product page in quick search (autocomplete). Page is reloaded instead.

### ISSUE THREAD

**Issue by NeosKnowledgeBasePluswerk** [Smile-SA/elasticsuite#403]
### Preconditions

Magento Version : 2.1.3

ElasticSuite Version : 2.3.0

Environment : both

Third party modules : Venustheme Brand Carousel, Payone

### Steps to reproduce

1. Insert query inside quick search input
2. Navigate with keyboard to product result
3. Press Enter

### Expected result

1. Page with selected product is loaded

### Actual result

1. Current page is reloaded

In _module-elasticsuite-core/view/frontend/web/js/form-mini.js_ in method __onKeyDown_ there is no event passed into __validateElement_ method

**Comment by romainruaud** [comment]
Confirmed.

I proposed the PR #405 to fix this one.

**Comment by afoucret** [comment]
Merged into 2.3.x, master and 2.4.x
