### ISSUE TITLE
Question: How to translate "Search terms" in autocomplete?

### ISSUE THREAD

**Issue by shazul** [Smile-SA/elasticsuite#409]
Magento Version : CE 2.1.6
ElasticSuite Version : 2.3.0
Environment : Developer and Production

This is actually a question, and probably not a bug:
I've been unsuccesfully trying to translate the block titles in the autocomplete results: **Search terms, Products, Categories**.

I have tried adding them to my theme csv translations file (dictionary.csv) which is where I think they should be. Just to try I also addes them to the js translation (No success). Please excuse me if I'm just doing something wrong, I just can't figure out how to translate those "words".

**Comment by romainruaud** [comment]
Hello,

I can confirm this one is a bug, I am not able to get the translations working properly in my testing environment either.

We will try to provide a fix soon. 

Best regards

**Comment by romainruaud** [comment]
The ```translate="true"``` node was missing into the DI for the "Search terms" title.

But the other have this tag and does not get translated properly either.

I think that the ```ŧranslate="true"``` into Magento DI has no effect : they are not using in the core.

I asked Magento how this is supposed to work : https://github.com/magento/magento2/issues/9411

But I guess we will have to refactor slightly this part. 

We keep you in touch

**Comment by afoucret** [comment]
PR merged
