### ISSUE TITLE
Fix various errors detected by static testing

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#41]
`bin/magento dev:tests:run static` detects some errors : 
- duplicate keys in DI
- layouts mistakes (especially in tracker module)
- cosmetics in composer.json files (essentially "no space after colon")

**Comment by afoucret** [comment]
The few remaining cases are not critcal and can be fixed in a later version

**Comment by afoucret** [comment]
Seems it can be closed
