### ISSUE TITLE
[Suggestion] Add is_new nested field for Virtual Category rules

### ISSUE THREAD

**Issue by metamasterplay** [Smile-SA/elasticsuite#410]
Hello,

I was wondering if it's possible to add a new field "is_new" for Virtual Categories so that it can be possible to create categories containing only new stuff. I think it will follow the same implementation as the two other nested fields except for the logic which will be more or less like this:
```php
	$now = date("Y-m-d");
	$newsFrom= substr($_product->getData('news_from_date'),0,10);
	$newsTo=  substr($_product->getData('news_to_date'),0,10);
	if ($newsTo != '' || $newsFrom != ''){
		if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == $
			$is_new=true;
		}
	}
```
PS: I can try and do a PR with the suggestion if that's permitted
### Preconditions

Magento Version : Magento CE 2.1.6

ElasticSuite Version : 2.4.x (dev-master)

Environment : Production

Third party modules : none relevant

**Comment by romainruaud** [comment]
See PR #595 which allow you to code it by yourself.

I included an example with "is_new" attribute so you can adapt it to your project.

Regards
