### ISSUE TITLE
Backend Category  not loading after install this module - loading spinner endlessely

### ISSUE THREAD

**Issue by kamendra** [Smile-SA/elasticsuite#411]
Not able to create or update any category in backend. spinner loading endlessly. Please help me. This is jquery error attached screen, 
### Preconditions

Magento Version : 2.1.5

ElasticSuite Version : 2.3.0

Environment : Development

Third party modules :

### Steps to reproduce

1.Product->categories
2.(index):1 Uncaught SyntaxError: Unexpected end of JSON input - Browser chrome and firefox

##Error Screen

![screenshot_2](https://cloud.githubusercontent.com/assets/1927007/25578257/7525abc2-2e8a-11e7-9169-0eb66bf87414.jpg)

**Comment by romainruaud** [comment]
Hello @kamendra ,

Are you sure about the version of Elasticsuite you are using ? 2.3.0 ? If it's the case, please switch to the latest version.

Let me know,

Regards

**Comment by romainruaud** [comment]
I close this one for being inactive/unanswered during two weeks.

Do not hesitate to reopen it and to give more details if you are still encountering the issue.

Regards
