### ISSUE TITLE
Can't install with "Can't update non dynamic settings" error

### ISSUE THREAD

**Issue by quickshiftin** [Smile-SA/elasticsuite#413]
When running `bin/magento setup:upgrade` Magento errors out with these types of messages:

>   [Elasticsearch\Common\Exceptions\BadRequest400Exception]                                                                                                                      
>   ElasticsearchIllegalArgumentException[Can't update non dynamic settings[[index.translog.durability]] for open indices [[magento2_default_catalog_category_20170503_144607]]]

### Preconditions

Magento Version : CE 2.1.6

ElasticSuite Version : 2.3

Elastic Search Version: 1.7.3

Environment : Production mode

Third party modules :

### Steps to reproduce

1. composer require smile/elasticsuite
2. bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker
3. bin/magento setup:upgrade

### Expected result

1. Module should be installed

### Actual result

1. Module fails to install

I installed the required plugins in Elasticsearch, (phonetic and icu). From what I've read this error results because configuration can't be read from while an index is open. Here's a thread discussing on Stackoverflow: http://stackoverflow.com/questions/19758335/error-when-trying-to-update-the-settings

Curious though, why I'm encountering this; I imagine someone would have reported it by now. So what might I be doing wrong?

**Comment by afoucret** [comment]
From requirements section of the wiki (https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) : 

> ElasticSearch 2.1 or higher 

So, ElasticSearch 1.7.3 is not supported. Please upgrade your config to ES 2.1.
The complete ElasticSearch install is documented there : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig

**Comment by quickshiftin** [comment]
Thank you for the quick response sir! Apologies, I knew it had to be something stupid like that.
