### ISSUE TITLE
Mass-adding products to category fails.

### ISSUE THREAD

**Issue by reviskar** [Smile-SA/elasticsuite#414]
Mass-adding products to category results in duplicate entry insert.

### Preconditions
Magento Version : CE 2.1.5 && CE 2.1.6
ElasticSuite Version : 2.3.4 && 2.3.5

Environment : Dev/Prod

Third party modules : -

### Steps to reproduce

1. Go to Products->Categories
2. Open tab "Products in Category"
3. Search for some products
4. Select all using "select all checkbox" in the top left corner of the table
5. Hit "Save"

### Expected result

1. All products saved to the category with no errors present

### Actual result

1. An error occurs: Something went wrong while saving the category.
2. Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails
3. PDO EXCEPTION:` INSERT INTO `catalog_category_product` (`category_id`,`product_id`,`position`) VALUES (?, ?, ?), (?, ?, ?)
`

What I think that happens is, that the "Select all" checkbox is treated as a product checkbox, so vendor/magento/module-catalog/Model/ResourceModel/Category.php:391 gets an element that is with the string 'on' as an array key. That translates into a product array element with `product_id => 0`. When trying to save that element an exception is thrown.
I've just re-validated this error with a fresh magento install and only "smile/elasticsuite" as a composer dependancy.

Thanks in advance.

**Comment by romainruaud** [comment]
Hello @reviskar and thank you for submitting this issue.

Does this occur only with ElasticSuite enabled ?

I will take a look on this one,

**Comment by reviskar** [comment]
Hi and thanks for the fast reaction!

Yeah. Just to be sure I installed fresh Magento CE 2.1.6, added a few products, did everything as mentioned in "Steps to reproduce" and confirmed everything worked in vanilla Magento2. Then used composer to require smile/elasticsearch and got the error described above.

At the moment, as a very, very messy hotfix, I've created a patch that adds a check to the Category Resource class.

**Comment by romainruaud** [comment]
Okay,

I reproduce your bug on my environment, I will try to provide a fix for this one.

Best regards,

**Comment by afoucret** [comment]
PR have been merged.

**Comment by vseager** [comment]
I have got this exact issue on Magento 2.4.1 and Elasticsuite 2.10.3

**Comment by OvalMedia** [comment]
2.10.5 / magento 2.4.2-p1: problem persists.
