### ISSUE TITLE
AutocompleteExtension

### ISSUE THREAD

**Issue by baokhoa1080** [Smile-SA/elasticsuite#415]
I want to install elasticsuite to magento 2.1. But I dont know "Adding an autocomplete provider" and "Adding an autocomplete renderer " by di.xml. Can anyone help me ? Tks so much.

**Comment by romainruaud** [comment]
Hello @baokhoa1080 

Is your request related to the wiki page ? https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteExtension

What do you want to do exactly ?

Best regards,

**Comment by baokhoa1080** [comment]
Tks.
exactly.
But I want to know about step by step to do it.
If i add 
 <type name="Magento\Search\Model\Autocomplete">
        <arguments>
            <argument name="dataProviders" xsi:type="array">
                <item name="20" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\DataProvider</item>
            </argument>
        </arguments>
    </type>
To Magento\Search\Model\Autocomplete. because magento folder on vender, when I update Magento so it clear.
Can you help me to do it?

**Comment by romainruaud** [comment]
Hello,

I am afraid but I do not understand what you want to do.

This part of the wiki is for **extending** the autocomplete with additional items. Are you sure you need to add items into the autocomplete ?

If you want to see an example, here is how we did on an other module to add CMS Pages into the autocomplete results : https://github.com/Smile-SA/module-elasticsuite-cms-search/blob/master/etc/frontend/di.xml#L24

**Comment by baokhoa1080** [comment]
Hi,
yes. I want to add items into the autocomplete. But I don't know how to do it. I see in this link "https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteExtension" but i don't know where I can add code?
Can you help me?
