### ISSUE TITLE
Improper display message about number of products in the list toolbar.

### ISSUE THREAD

**Issue by romantomchak** [Smile-SA/elasticsuite#416]
After installation of ElasticSuite module, message about count of products in category toolbar are showing incorrect.

### Preconditions

Magento Version : EE 2.1.5, EE 2.1.6
ElasticSuite Version : 2.3.4 
Environment : Developer, Default, Production

### Steps to reproduce

1. Create simple category
2. Add products to this category (number of products should be more than default count of products per page)

### Expected result
In case, when Magento category contains number of products which is more than default value per page, Magento shows message "Items 1-9 of 100500".

![a834138edb](https://cloud.githubusercontent.com/assets/2635104/25703991/83f8dc8e-30e0-11e7-9c08-0f45a8f86a21.jpg)

### Actual result
But after installation Magento shows: "Items 100500"

![b33f100dcf](https://cloud.githubusercontent.com/assets/2635104/25704086/cedcd138-30e0-11e7-97ac-65782b21f81a.jpg)

### Investigations
After some investigations I found the next:
To check which message need to show, Magento check if category has more than one page
`magento/module-catalog/view/frontend/templates/product/list/toolbar/amount.phtml`
```php
<?php if ($block->getLastPageNum() > 1): ?>
    <?php /* @escapeNotVerified */ echo __('Items %1-%2 of %3',
        '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
        '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
        '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
```
The product collection counts the number of products as follows way:
```php
public function getLastPageNumber()
{
    $collectionSize = (int)$this->getSize();
    if (0 === $collectionSize) {
        return 1;
    } elseif ($this->_pageSize) {
        return ceil($collectionSize / $this->_pageSize);
    } else {
        return 1;
    }
}
```

But you rewrite product collection and before load you set `_pageSize` to `false` (I don't know why) and `getLastPageNumber` always return 1.

class `Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext`
```php
protected function _renderFiltersBefore()
{
//...
    if (empty($docIds)) {
        $docIds[] = 0;
    }

    $this->getSelect()->where('e.entity_id IN (?)', ['in' => $docIds]);
    $this->_pageSize = false;
//...
}
```

**Comment by romainruaud** [comment]
Hello and thank you for submitting this one.

Thank you also for you great analysis which is totally exact.

I'll try to provide a fix for this one soon.

Best regards,

**Comment by romainruaud** [comment]
And by the way, the pageSize is set to "false" because the pagination is done previously by the engine itself, we got paginated results from ElasticSearch and then retrieve the products by their ids, so we have to reset the page size otherwise Magento would apply a LIMIT on the collection loading.

Best regards,

**Comment by romantomchak** [comment]
Hi @romainruaud ,

thanks for your explanation.

Best regards,

**Comment by afoucret** [comment]
PR has been merged
