### ISSUE TITLE
Behavioral Search Optimizations

### ISSUE THREAD

**Issue by cykirsch** [Smile-SA/elasticsuite#419]
In particular, the "boost the top sales products" is what I am looking for. I see that the readme states it's a feature that will be coming along this year, but I don't see an issue for it. I'm curious if you have a timeline for implementation? I could potentially help out with it, given some direction.

**Comment by romainruaud** [comment]
Hello,

Behavioral Search Optimizations is actually on the roadmap for this year, you are right.

For now, this part will need much work by our side especially for collecting and processing the data which are coming from the ElasticsuiteTracker module.

We do not have much precise timeline about when it will be released.

But you can ensure that we will keep all of our fellow users in touch when it will be the case.

Best regards,
