### ISSUE TITLE
Category Preview not accounting for Visibility

### ISSUE THREAD

**Issue by cykirsch** [Smile-SA/elasticsuite#424]
I don't think the Category Preview is taking the Visibility attribute into account. I would expect the preview to match up with whatever is seen on the frontend. But on the other hand, it shows Out of Stock products in the preview, and those may or may not display on the frontend. So perhaps the solution could be to show them in the preview, but have an identifier so you can quickly see that it doesn't match due to that product's visibility configuration.

Magento Version : 2.1.6

ElasticSuite Version : 2.3.5

Environment : Developer

**Comment by romainruaud** [comment]
That's true, visibility is not taken into account, as for the stock status.

I will let @afoucret decide on this one about how we are supposed to do.

Best regards,

**Comment by afoucret** [comment]
Fixed in branch 2.4.x by PR #581.

Will be part of ElasticSuite 2.4.0
