### ISSUE TITLE
"%1 is the only product matching your '%2' research." displays with a delay of one page load

### ISSUE THREAD

**Issue by TiEul** [Smile-SA/elasticsuite#426]
There's an observer that is triggered when only one product has been found which displays the message _"%1 is the only product matching your '%2' research."_, however, we have been experiencing the problem that it displays one page load too late.

### Preconditions

Magento Version :
2.1.6 EE

Environment :
Acceptance (Production-like)

### Steps to reproduce

1. Search using first search term of which you know it only returns one product result
2. Search using second search term of which you know it only returns one product result
3. Search using third search term of which you know it only returns one product result

### Expected result

1.  _"Product01 is the only product matching your 'Product01' research."_
2. _"Product02 is the only product matching your 'Product02' research."_
3. _"Product03 is the only product matching your 'Product03' research."_

### Actual result

1.  No message is shown
2. _"Product01 is the only product matching your 'Product01' research."_
3. _"Product02 is the only product matching your 'Product02' research."_

PS: The text should also have the term "research" changed to "search", probably was a slip-up when translating it from the French "recherche".

**Comment by maxinacube** [comment]
I'm also experiencing this bug with Magento 2.1.7 EE in developer mode, running version 2.3.0 of ElasticSuite.

**Comment by maxinacube** [comment]
Also worth noting that turning off "Redirect to product page if only one result" will prevent the page message from ever displaying - not ideal as it's a good feature, but the easiest temporary work around for the bug.

The setting can be found in the Magento admin through Stores > Configuration > Smile ElasticSuite > Catalog Search

**Comment by afoucret** [comment]
PR merged
