### ISSUE TITLE
Different results in autocomplete vs search results page

### ISSUE THREAD

**Issue by cykirsch** [Smile-SA/elasticsuite#427]
Unfortunately I couldn't come up with any search terms to reproduce this on the demo elasticsuite site. But I did some debugging and was able to verify where the ES queries differ.

On the site we are developing, there are a few search terms appropriate for our catalog where the top 5 results in the autocomplete do not match the top 5 on the search results page, and some products may not even be in the first 24 (page 1). I tracked it down to the popular search terms. When enabled (default of 3, https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteConfiguration), there is a difference for a few terms that we've identified. But when I change the popular search term config to 0, then the results are the same.

In the "steps to reproduce" below, I will identify for you where I debugged to prove that the query was being built including the popular search terms.

### Preconditions

Magento Version : 2.1.6

ElasticSuite Version : 2.3.5

Environment : Developer

### Steps to reproduce

1. `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Adapter::doSearch`
2. Add log `file_put_contents('path/to/file.log', print_r($searchRequest, true)."\n\n", FILE_APPEND);`
3. Add a search term to the box, let the autocomplete come up.
4. Change the configuration to show zero popular search terms, then repeat step 3.

### Expected result

1. In the log, I expect that under `body->query->function_score->query->filtered->query->bool`, it  it should be the same for the search in both step 3 and step 4.
2. I expect the results of the actual products to be exactly the same regardless of the popular search term configuration, which logically should be independent.

### Actual result

1.  In the log, I expect that under` body->query->function_score->query->filtered->query->bool`, you will find that it adds filters for the popular search terms in the search for step 3, and then does not include them in the search for step 4.
2. For certain search terms (wish i could figure one out for sample data!) the autocomplete results are different from the search results page when the popular search terms are enabled, but they are the same if the popular search terms are disabled.

**Comment by romainruaud** [comment]
Hello @cykirsch 

What you describe here seems normal for me. This is a functional design choice from our side.

When the user is typing something into the search bar, we propose search terms matching his query, and then run a query for all these search terms.

The scenario is the following : 

- The user begins to type. Let's say he types "ho" as a beginning of word.

- With a query as tiny as this, the engine would not be able to find matching products.

- This query match for popular search term "hoodie". This could also match other terms, let's say maybe "hologram" or everything beginning with "ho".

- We process a search query for all the search terms matched previously. We will then have matching for hoodies, hologram, and so on...

- The same process applies along the user is typing.

This is not applied on the Search Results page, where only the typed query is sent to the search engine.

So this can happens that autocomplete returns differents results compared to the search result page.

Could you provide more details, especially about the query you are typing and the suggested search terms which are getting used by the engine ?

Best regards

**Comment by southerncomputer** [comment]
@romainraud How come sku based searches are more precise on auto-complete than on regular search? Are they using different filters/analyzers?

**Comment by cykirsch** [comment]
@romainruaud I'm sorry, I wish I could come up with a specific public example for you to see the results. As I said, I tried several searches but couldn't get anything to be different with the sample data.

I understand why you would want to include results for incomplete words like "ho"->"hoodie". But I suppose a key detail would be that in our case it was full word searches. To illustrate:

- Search for "headphones" expecting to find various 
- Suggestions include terms like "headphones bluetooth"
- Autocomplete shows things like bluetooth mouse and keyboard when it should be clear that headphones are what I want

**Comment by afoucret** [comment]
Have you customized the `Smile ElasticSuite` > `Relevance Configuration` > `Fulltext Base Settings` > `Minimum Should Match` settings ?

The default value is 100%.

**Comment by afoucret** [comment]
Closed for being inactive since too long.
Feel free to reopen if you can provide additional information or feedback.
