### ISSUE TITLE
Try to install but getting error

### ISSUE THREAD

**Issue by bkjain** [Smile-SA/elasticsuite#430]
Hi there,
I am trying to install using composer but getting an error. see below screen shot,
![error](https://cloud.githubusercontent.com/assets/4090714/26519549/ae21b4c4-42e0-11e7-9ea2-de2e319f7e90.PNG)

**Comment by romainruaud** [comment]
Hello,

as it's said by the error message you are getting, you need to have a working version of Magento installed. 

Please refer to the Magento2 [documentation](http://devdocs.magento.com/guides/v2.1/install-gde/bk-install-guide.html) to know how to proceed.

Once you are done with Magento, you'll be able to install ElasticSuite by following our wiki.

Best regards,
