### ISSUE TITLE
Cannot access autocomplete.

### ISSUE THREAD

**Issue by baokhoa1080** [Smile-SA/elasticsuite#432]
I do it as guide. But I cannot access autocomplete in my site.
And in demo site too.
![screenshot from 2017-05-30 08-36-32](https://cloud.githubusercontent.com/assets/14296456/26565170/2567af28-4513-11e7-9152-4f04cc2ad87b.png)

**Comment by romainruaud** [comment]
Hello @baokhoa1080 

I am afraid but I still do not understand what you are trying to do.

Please do not hesitate to give us a detailed plan about what you are willing to do. For now this is impossible for anybody to understand what you are trying to process.

Best regards,

**Comment by romainruaud** [comment]
I close this one due to being inactive for too long.

Please feel free to reopen it if needed.

Best regards,
