### ISSUE TITLE
Many requests made for search autocomplete

### ISSUE THREAD

**Issue by dersam** [Smile-SA/elasticsuite#433]
### Preconditions

Magento Version : CE 2.1.5

ElasticSuite Version : 2.3.5

Environment : Developer

Third party modules : No

### Steps to reproduce

1. On a category page, with the browser developer console open to the Network panel.
2. Enter a search term

### Expected result

1. No requests should be made until typing is complete or a short pause has occurred.

### Actual result
A request is made for nearly every entered character. These requests are "cancelled" but the web server continues to process them. These additional requests slow down the response time of the final autocomplete.  

The slowdown is illustrated by the difference when a search term is pasted in. Only one request will be made, and the response will be noticeably faster.

Entry to this field should be debounced, so that the request isn't sent until a specified time has elapsed since the last character was entered. This would prevent the glut of requests being sent to the server.

This is likely exacerbated by the large catalog this particular site is working with (over 380k skus).

![motorcycle_helmets_canada_-_fortnine](https://cloud.githubusercontent.com/assets/475851/26594588/31f3d6cc-4536-11e7-999d-788b3a9a6a81.png)

**Comment by southerncomputer** [comment]
like this?
https://github.com/Smile-SA/elasticsuite/commit/a0bd260b55ee4dd15a5a7d8f0ec09c2839cfc8ed

**Comment by romainruaud** [comment]
Hello @dersam , you are 100% right about the symptoms.

Just to enlight a bit, the autocomplete is node made by us, this is the default one of Magento, that we did just improve a bit to display more content. I agree that adding a smooth delay could do better.

We will take a look on this one and on the PR submitted by @southerncomputer  (thank you for proposing this !).

Regards,

**Comment by cykirsch** [comment]
I'm also in favor of this change, including configurability. I made a customization in our site to delay it a bit (not configurable) and will be very happy to remove it in favor of your solution :)

**Comment by romainruaud** [comment]
PR #489 has been merged

Please use 2.3.x-dev branch to benefit from it, or wait for the next minor release.
