### ISSUE TITLE
Exception thrown in admin for Category page

### ISSUE THREAD

**Issue by JamesonNetworks** [Smile-SA/elasticsuite#435]
When viewing the categories in M2 admin, I'm getting an exception in trying to load a product list for categories. The exception comes from line 196 in Preview.php. I've added a PR (#434) with a potential fix

### Preconditions

Magento Version : 2.1.6 EE Cloud Edition

ElasticSuite Version : ^2.3

Environment : Developer/Production

### Steps to reproduce

1. Go to the Category edit page in the admin
2. See the eternal spinner of doom

### Expected result

1. Page loads normally

### Actual result

1. Eternal spinner of doom

**Comment by romainruaud** [comment]
Hello @JamesonNetworks 

A category should never have "null" as Virtual Rule, according to https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-virtual-category/Model/Category/Attribute/Backend/VirtualRule.php#L71

Could you please provide more details about your instance ?

Are you using flat categories ? What do you have in the database for the virtual_rule attribute for your categories ?

**Comment by JamesonNetworks** [comment]
Thanks for the heads up, will get some more info this morning

**Comment by JamesonNetworks** [comment]
@romainruaud I never hit the afterLoad for the VirtualRule when I'm going to the url "admin/catalog/category/index/". Do you know what part of di.xml is responsible for wiring up this particular plugin/observer?

**Comment by JamesonNetworks** [comment]
VirtualRule doesn't appear to exist inside of the category extension attributes...

**Comment by romainruaud** [comment]
It's not an extension attribute but an EAV one. Do you see it in the eav_attribute table ?

Regards,

**Comment by romainruaud** [comment]
I can confirm that on my side I have no exception, and I'm properly passing in the VirtualRule backend model when I navigate through categories.

Maybe something went wrong during the module install ? I notice you are on Magento Cloud environment, are you sure the install process and/or the setup:upgrade has ran properly ?

**Comment by JamesonNetworks** [comment]
You are correct @romainruaud , we had to remove the extension for a separate deployment problem we were having. When we did this, the admin stopped functioning because the backend model for the attribute was missing. We deleted the attribute to get around it at the time, and it doesn't exist now that we've reinstalled the module. Pretty sure this is just going to be a deficiency of uninstalling modules on M2 that is pretty difficult or impossible to get around without modifying the way core checks for those backend models for attributes. Thanks for the help @romainruaud !

**Comment by romainruaud** [comment]
You're welcome !

Did you resolve your deployment problem ? Was it linked with Elasticsuite ? We always appreciate to see that people is using our module on Magento Cloud Environment, but are lacking of feedbacks (except for projects we have ourselves on MECE at Smile).

Regards,

**Comment by JamesonNetworks** [comment]
They provided us with a deployment work around in order to get the module working again. It works, but we are unclear as to why:

We added the following code into a deploy hook in the .magento.app.yaml
    deploy: |
        php vendor/magento/magento-cloud-configuration/pre-deploy.php
        php bin/magento -vvv magento-cloud:deploy
        rm -Rf var/generation_copy
        cp -R init/var/generation var/generation_copy
        ln -s generation_copy var/generation_link
        mv -Tf var/generation_link var/generation
        php bin/magento cache:clean
        php bin/magento indexer:reindex
        php bin/magento cache:clean

Sometimes we also have to run these steps manually if the plugin breaks. It is pretty bizarre.

**Comment by romainruaud** [comment]
Kinda weird ... I do not understand why it could break, our module is not as different as an other. We did not have any issue with MECE deployment for our projects using ElasticSuite here.

Could you provide me the error you had ? I'll try to take a look if I see something.

Regards
