### ISSUE TITLE
No handler found for uri

### ISSUE THREAD

**Issue by hashsup** [Smile-SA/elasticsuite#439]
### Preconditions

Magento Version : Magento  2.1.1 CE

ElasticSuite Version : 5.0.1

Environment : Developer

Third party modules : only elasticsuite

### Steps to reproduce

I'm installing magento from scrath, I downloaded a fresh zip from magento and prior to run installer I installed elasticsuite via composer, after this I trying to setup but it fail with this error:

```
Module 'Magento_CatalogSearch':
Installing data... 
[ERROR] exception 'Elasticsearch\Common\Exceptions\BadRequest400Exception' with message 'No handler found for uri [/magento_default_catalog_product_20170601_213009] and method [POST]' in \home\magento\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php:683
```

Any idea what's happening?

### Actual result

1. [Screenshot, logs]

**Comment by romainruaud** [comment]
Hello,

What do you mean by "ElasticSuite version 5.0.1" ? I suppose you are talking about the Elasticsearch version and not the Elasticsuite module.

If your are using Elasticsearch 5.0.1 you need to use this specific branch of Elasticsuite : https://github.com/Smile-SA/elasticsuite/tree/feature-es-5-compat

Regards

**Comment by hashsup** [comment]
![capture](https://user-images.githubusercontent.com/19599187/26851200-8c5e7bbc-4ae0-11e7-9ea7-467d9a42ac92.JPG)

Sorry my fault, you right, I downgrade to elasticsearch 2.4.5 and works, unfortunatelly I want able to install 

>  https://github.com/Smile-SA/elasticsuite/tree/feature-es-5-compat

due an error in elasticsearch-php library there is a required version of ext-json that my system doesn't have.

Thank you.

**Comment by romainruaud** [comment]
Hello,

on which system are you installing ? And what is your PHP version ? I guess PHP7 ?

Which version of ext-json is actually included in your PHP version ?

Regards,

**Comment by hashsup** [comment]
I'm  installing on Windows 10, PHP is 5.6.30 and ext-json installed is 1.2.1.

Thank you.

**Comment by romainruaud** [comment]
Hello,

I am afraid that we cannot provide any support for such a custom install. Magento himself is not intended to be installed on Windows (see their [requirements](http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html)).

Please consider using virtualization tools like Virtualbox to emulate a supported Linux system (eg. : Debian).

Additionnally, for the feature-es-5-compat branch we are using the elasticsearch-php connector with their dev-master branch. According to their requirements, you need to use PHP 7.0 : See [here](https://github.com/elastic/elasticsearch-php/blob/master/composer.json#L13)

Please try to fix all of these points and see if it does work better.

Regards,

**Comment by romainruaud** [comment]
I closed this issue : 

- for being inactive more than a week
- since it's related to a non-standard installation of Elasticsuite.

Feel free to reopen it if you have any additional question, or if you updated your setup according to [my latest comment](https://github.com/Smile-SA/elasticsuite/issues/439#issuecomment-307113427)

**Comment by opiumated** [comment]
I'm having similar issue. Running Magento2 on Ubuntu 
[ERROR] Elasticsearch\Common\Exceptions\BadRequest400Exception: No handler found for uri [/magento2_default_catalog_product_20180221_105245] and method [POST] in /var/www/mage2/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:681
