### ISSUE TITLE
Sorting Result is not coming properly in Product Listing page

### ISSUE THREAD

**Issue by shekharS7** [Smile-SA/elasticsuite#440]
Attribute sorting result in product listing page of magento 2 is not correct. The result , i getting in random fashion for every attribute sort result for price and name etc. Suppose i choose to sort using price in ascending , Result will be like this Product 1 price -100, product 2 price 150, product 3 price 50, product 80. After disable elasticsuite module, the result of attribute sort is fine. 

Magento Version : 2.1.0 Magento CE
ElasticSuite Version : 2.3
Environment : developer mode
Third party modules :NO

**Comment by romainruaud** [comment]
Hello @shekharS7 .

Did you process a full reindex after installing the module ? And after setting the attributes as sortable ?

Also, which kind of products are you using ? Composites (bundles, grouped, and/or configurables) ?

Please provide more informations, even screenshots and details about your issue.

Best regards,

**Comment by shekharS7** [comment]
Hi @romainruaud ,
I got the solution for problem, through the listed  FAQ  of elasticsuite. 
Thanks for your response.
Best regards

**Comment by romainruaud** [comment]
Cool, glad to see the FAQ is useful for our users !

I close this issue then, do not hesitate to re-open this one, or to open a new one if you're still facing problems.

Regards,

**Comment by test4295** [comment]
Hi @shekharS7  
Can you give me a solution or FAQ link?

Thanks

**Comment by bangln** [comment]
@shekharS7
Hi bro, can you give me a solution or FAQ link?

Thanks
