### ISSUE TITLE
Problem of reindex for a categories that created via API

### ISSUE THREAD

**Issue by nuzil** [Smile-SA/elasticsuite#441]
Hello

We faced with a next problem.
For not default Website we created new Category by using Magento REST api. Category was successfully created, but when we are trying ti make a reindex or save any product in backend, we getting next error:

Notice: Undefined offset: 79 in /home/dev/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php on line 93

Just had a look at the code a little, and see that select query tries to get default names of the category:

`->where('default_value.store_id = ?', 0)
`
But for those categories default name is not existed in database.

Can you please check and fix that if possible

### Preconditions
Magento Version : 2.1.6
Elasticsuite version: 2.3.2.1
Environment : default mode

### Steps to reproduce

1. Create new category via API for NOT default Website
2. Try to save any product

### Expected result

1. Success message

### Actual result

1. Notice: Undefined offset: 79 in /home/dev/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Indexer/Fulltext/Datasource/CategoryData.php on line 93

**Comment by romainruaud** [comment]
Hello @nuzil ,

could you please provide an example of how you are creating the category ? Then I'll be able to reproduce your issue exactly.

Regards

**Comment by romainruaud** [comment]
Hello @nuzil 

Could you check the fix provided in PR https://github.com/Smile-SA/elasticsuite/pull/448 solves your issue ?

Best regards,

**Comment by paulbarker** [comment]
Not sure if this is related but I have API generated categories and I'm getting this when I try to reindex via the CLI:
```
# bin/magento index:reindex catalogsearch_fulltext
Catalog Search indexer process unknown error:
Warning: Invalid argument supplied for foreach() in /home/magento2/magento2/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/CategoryData.php on line 53
```
In the debugger I can see this loop:
```
foreach ($categoryData as &$categoryDataRow) {
   $categoryDataRow['name'] = $storeCategoryName[(int) $categoryDataRow['category_id']];
}
```
but `$categoryDataRow` contains only these keys:
```
$categoryDataRow = {array} [5]
    category_id = "2"
    product_id = "6060"
    is_parent = "1"
    is_virtual = "0"
    position = null
```
no 'name' index at all.

**Comment by afoucret** [comment]
PR Merged
