### ISSUE TITLE
Magento 2 "main.CRITICAL: The attribute model is not defined. [] []"

### ISSUE THREAD

**Issue by abovebar** [Smile-SA/elasticsuite#442]
I am seeing the following error in my system log in magento 2 CE:

main.CRITICAL: The attribute model is not defined. [] []main.CRITICAL: The attribute model is not defined. [] []

i believe that this is halting me from being able to update my site. please help

**Comment by romainruaud** [comment]
Hello @abovebar 

Please provide the required details if you want us to help : 

Magento version. (the exact one, including the minor version).

Elasticsuite version. (same, please specify the tag or the branch you are using).


Also, what do you mean by "halting me from being able to update my site" ?

Regards

**Comment by abovebar** [comment]
Romainruaud,

I am running Magento 2.1.4

not using Elasticsuite

my while using the web setup wizard my site will time out on the component manager page.

it seems that i have a null module getting recognized by the system, I am looking for instruction to track this down for removal.

Thank you!

**Comment by romainruaud** [comment]
Hello,

if you are not using ElasticSuite, this is not the proper place to submit an issue.

Please report your issue directly on the [Magento Issues](https://github.com/magento/magento2/issues)

I close this one since it's not related to ElasticSuite module.

**Comment by abovebar** [comment]
my apologizes, i am new to github
