### ISSUE TITLE
Multiselect Layered Navigation 

### ISSUE THREAD

**Issue by crantron** [Smile-SA/elasticsuite#449]
The select inputs are not appearing in layered navigation. Should this happen automatically, or is there a setting I'm missing? 

Magento 2.1.6 
Elasticsearch 2.4.5

**Comment by romainruaud** [comment]
Hello,

did you configure your attributes like this ?

![selection_314](https://user-images.githubusercontent.com/15340849/27033674-b51c470c-4f7a-11e7-88f3-772b42e14dc9.png)

Could you please provide more details about the expected result ? I'm not sure to understand what "the select inputs are not appearing" mean.

Regards

**Comment by crantron** [comment]
![screen shot 2017-06-12 at 10 41 05 am](https://user-images.githubusercontent.com/3859969/27047379-be506aa6-4f5c-11e7-8a4b-592ae164a015.png)

I would like to have each filterable layered nav item to have a checkbox next to it.

**Comment by romainruaud** [comment]
Hello @crantron 

The checkboxes should appear automatically.

Do you use a custom theme ? Or did you personalize the Luma one ?

If yes, you should ensure that your modifications does not collisionate with the ones made by Elasticsuite for the filter templates : 

https://github.com/Smile-SA/elasticsuite/tree/master/src/module-elasticsuite-catalog/view/frontend/templates/layer/filter

Let me know,

best regards,

**Comment by crantron** [comment]
Thank you for your response. This issue was due to an Magento_LayeredNavigation Layout override in our theme works like a charm now!

**Comment by romainruaud** [comment]
Fine, I close the issue then.

Feel free to reopen it if you need more informations,
