### ISSUE TITLE
Can we add custom sort ordering for product attribute option values ?

### ISSUE THREAD

**Issue by vipingarg12** [Smile-SA/elasticsuite#450]
Hi Support,

We need to add custom sort ordering in results. How we can do that ? Currently sorting working on attribute option id.

Magento version: 2.1.1
Elastic Version: 2.1.1
Elastic Suite Version: 1.2.0

Thanks,
Vipin

**Comment by romainruaud** [comment]
Hello @vipingarg12 

You just have to set any attribute you want to sort on, as "Used For Sorting in Product Listing".

![selection_315](https://user-images.githubusercontent.com/15340849/27033775-1895c858-4f7b-11e7-9427-7e16431a4a1a.png)


This is standard Magento's behavior and we are actually keeping it functional.

Best regards. I close the issue, do not hesitate to reopen it if you have any other question.

**Comment by vipingarg12** [comment]
We need to sort ordering on option values. for example Color is attribute and values are Red, Green, Blue then when we sort it should sort by alphabetically.  So Blue, Green, Red results should come.

I hope you understand the problem. Default magento sort gives results based on option id not alphabetically.

**Comment by romainruaud** [comment]
Sorry but I do not get it.

What do you want to sort ? The options inside the filter ? Or the products ?

**Comment by vipingarg12** [comment]
I wants to sort products collection on category page. Go to below page and sort by color

http://custom.pratikshajewelry.com/diamond.html

**Comment by romainruaud** [comment]
Ok I got it.

You are right, when using a select-based attribute for sort, the optionId is used, instead of the option label.

I reopen the issue, we will try to provide a fix for this one.

Regards

**Comment by mautz-et-tong** [comment]
We have the same Problem on Integer Attributes.
We have set up an attribute "alt_position" type integer and the frontend is sorted by value_id not by the value itself.
We use Magento 2.1.7
Smile 2.3.5
Elastic 2.4.5

**Comment by afoucret** [comment]
PR have been merged into branch 2.3.x

**Comment by andros89cy** [comment]
Hello vipingarg12,

Are you a magento developer?

Thanks

**Comment by jeremy-donson** [comment]
**  Has this customizable sorting issue been addressed?  **
I have great ideas, and want great options!  :D 
I can fix it solo, but would prefer to have this be a github enhancement for our planet.

**Comment by vishal-magento360** [comment]
@vipingarg12  did you get any solution for this ? I am also experiencing same issue.

**Comment by manishgoswamig** [comment]
@vipingarg12 have you got any solution because we are facing the same issue with custom sorting?

**Comment by manishgoswamig** [comment]
Hello @romainruaud ,

We want to apply the sorting with our custom table column value, but it is not working, do you have any reference so that we can archive it ?
