### ISSUE TITLE
Not all DB stuff deleted after doc uninstalling guide

### ISSUE THREAD

**Issue by icbrg** [Smile-SA/elasticsuite#451]
DELETE FROM eav_attribute where attribute_code='virtual_rule';
DELETE FROM eav_attribute where attribute_code='is_virtual_category';
DELETE FROM eav_attribute where attribute_code='virtual_category_root';
DELETE FROM smile_elasticsuite_optimizer;
DELETE FROM smile_elasticsuite_optimizer_search_container;

DROP TABLE smile_elasticsuite_optimizer_search_container;
DROP TABLE smile_elasticsuite_optimizer;
DROP TABLE smile_elasticsuite_relevance_config_data;
DROP TABLE smile_elasticsuite_thesaurus_expanded_terms;
DROP TABLE smile_elasticsuite_thesaurus_reference_terms;
DROP TABLE smile_elasticsuite_thesaurus_store;
DROP TABLE smile_elasticsuite_thesaurus;
DROP TABLE smile_virtualcategory_catalog_category_product_position;

With this all stuff was not deleted. I still had some columns in catalog_eav_attribute that I already deleted manually.

Please could you specify all? I'm facing some troubles with a specific attribute and I want to ensure that there's not any reindexing problem related with this uninstall.

**Comment by romainruaud** [comment]
Hello,

yes it may remains some columns in the catalog_eav_attribute table. You could remove it by doing this : 

ALTER TABLE catalog_eav_attribute DROP COLUMN is_displayed_in_autocomplete;
ALTER TABLE catalog_eav_attribute DROP COLUMN is_used_in_spellcheck;
ALTER TABLE catalog_eav_attribute DROP COLUMN facet_min_coverage_rate;
ALTER TABLE catalog_eav_attribute DROP COLUMN facet_max_size;
ALTER TABLE catalog_eav_attribute DROP COLUMN facet_sort_order;
ALTER TABLE catalog_eav_attribute DROP COLUMN display_pattern;
ALTER TABLE catalog_eav_attribute DROP COLUMN display_precision;

Which specific attribute is causing you trouble ?

**Comment by icbrg** [comment]
Color attribute

After changing **Catalog Input Type for Store Owner** from Dropdown to Text Swatch, I cannot revert it to Dropdown again.

I mean, I can, but frontend does not change. Tried to make a setup:upgrade, dicompile, reindex, flush cache .... but nothing, stills Text Swatch in frontend.

Are you sure that there are no more db stuff? I already droped those columns.

**Comment by romainruaud** [comment]
Hello, there is no more db stuff, and nothing which could prevent you from saving an attribute.

Did you try to change the attribute type with all Elasticsuite modules disabled ?

**Comment by icbrg** [comment]
Yes, actually they're all completely uninstalled, but I have to discard any kind of DB residue. I tried to disable any potential extension that could affect too.

**Comment by romainruaud** [comment]
@icbrg 

I'm pretty sure this is a standard Magento2 behavior (which can be called a bug) that is preventing to "revert" a swatch attribute to a dropdown one.

If you are still encountering issues with the Elasticsuite extension turned off, and after having cleaned the DB (which cannot be responsible for anything here), this bug is for sure not related to Elasticsuite extension.

I close the issue, feel free to reopen it if you have any additional elements.

I also updated the uninstall guide, btw.

Best regards,

**Comment by avenicus** [comment]
@sbernaldev It's been some time, but in case you need it. Your issue is Magento 2 core related and confirmed on this bug thread: https://github.com/magento/magento2/issues/12695
