### ISSUE TITLE
Undefined sessionConfig

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#457]
With minification, bundling and grouping enabled in we are experience a JS frontend error within the SmileTrackerImpl.

### Preconditions

MCE2.1.7
ES 2.3
Haproxy:80->Varnish->Nginx->PHP-FPM7 on Ubuntu 16.04

**Tracking is disabled by admin** 

### Issue
    Uncaught TypeError: Cannot read property 'sessionConfig' of undefined
    at SmileTrackerImpl.initSession (87824f0….min.js:213)
    at SmileTrackerImpl.getTrackerUrl (87824f0….min.js:204)
    at SmileTrackerImpl.sendTag (87824f0….min.js:208)

    initSession @ 87824f0….min.js:213
    getTrackerUrl @ 87824f0….min.js:204
    sendTag @ 87824f0….min.js:208

It looks like the JS does get included even if the tracking is disabled, this results in empty cookie/ no session.

Called at
https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-tracker/view/frontend/web/js/tracking.js#L182

Browse our frontend on https://www.makerdise.com/ with developer console enabled.

Regards
Jan

**Comment by romainruaud** [comment]
Confirmed.

Fix is in the PR #460

**Comment by gewaechshaus** [comment]
THX @romainruaud

**Comment by afoucret** [comment]
PR have been merged.
