### ISSUE TITLE
Category: getimagesize(): Filename cannot be empty 

### ISSUE THREAD

**Issue by winds1983** [Smile-SA/elasticsuite#461]
When view category, it still show loading, and get error from console:

https://test.magento.dev/hp_ols_admin/virtualcategory/category_virtual/preview/ajax/1/store/1/?isAjax=true

a:4:{i:0;s:158:"Warning: getimagesize(): Filename cannot be empty in /usr/share/nginx/html/test.magento.dev/vendor/magento/module-catalog/Model/Product/Image.php on line 922";i:1;s:9182:"#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(2, 'getimagesize():...', '/usr/share/ngin...', 922, Array)
#1 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-catalog/Model/Product/Image.php(922): getimagesize('')
#2 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-catalog/Helper/Image.php(535): Magento\Catalog\Model\Product\Image->getResizedImageInfo()
#3 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-catalog/Block/Product/ImageBuilder.php(132): Magento\Catalog\Helper\Image->getResizedImageInfo()
#4 /usr/share/nginx/html/test.magento.dev/app/code/HPOLS/Sales/Helper/Product.php(31): Magento\Catalog\Block\Product\ImageBuilder->create()
#5 /usr/share/nginx/html/test.magento.dev/app/code/HPOLS/Catalog/Plugin/Helper/Product.php(29): HPOLS\Sales\Helper\Product->getImage(Object(Aitoc\PreOrders\Model\Product\Interceptor), 'product_small_i...')
#6 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(142): HPOLS\Catalog\Plugin\Helper\Product->aroundGetSmallImageUrl(Object(Magento\Catalog\Helper\Product\Interceptor), Object(Closure), Object(Aitoc\PreOrders\Model\Product\Interceptor))
#7 /usr/share/nginx/html/test.magento.dev/var/generation/Magento/Catalog/Helper/Product/Interceptor.php(26): Magento\Catalog\Helper\Product\Interceptor->___callPlugins('getSmallImageUr...', Array, Array)
#8 /usr/share/nginx/html/test.magento.dev/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview/Item.php(65): Magento\Catalog\Helper\Product\Interceptor->getSmallImageUrl(Object(Aitoc\PreOrders\Model\Product\Interceptor))
#9 /usr/share/nginx/html/test.magento.dev/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(178): Smile\ElasticsuiteVirtualCategory\Model\Preview\Item->getData()
#10 /usr/share/nginx/html/test.magento.dev/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Preview.php(93): Smile\ElasticsuiteVirtualCategory\Model\Preview->preparePreviewItems(Array)
#11 /usr/share/nginx/html/test.magento.dev/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Controller/Adminhtml/Category/Virtual/Preview.php(71): Smile\ElasticsuiteVirtualCategory\Model\Preview->getData()
#12 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/App/Action/Action.php(102): Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview->execute()
#13 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#15 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor->___callParent('dispatch', Array)
#16 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Smile\\Elasticsu...', 'dispatch', Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Array, 'adminAuthentica...')
#17 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#18 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#19 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Smile\\Elasticsu...', 'dispatch', Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Array, 'log')
#20 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-logging/App/Action/Plugin/Log.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Logging\App\Action\Plugin\Log->aroundDispatch(Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#22 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Smile\\Elasticsu...', 'dispatch', Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Array, 'adminMassaction...')
#23 /usr/share/nginx/html/test.magento.dev/vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#24 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#25 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Smile\\Elasticsu...', 'dispatch', Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Array, 'mgtDeveloperToo...')
#26 /usr/share/nginx/html/test.magento.dev/vendor/mgtcommerce/module-mgtdevelopertoolbar/src/app/code/Mgt/DeveloperToolbar/Model/App/FrontController/ToolbarPlugin.php(64): Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(142): Mgt\DeveloperToolbar\Model\App\FrontController\ToolbarPlugin->aroundDispatch(Object(Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#28 /usr/share/nginx/html/test.magento.dev/var/generation/Smile/ElasticsuiteVirtualCategory/Controller/Adminhtml/Category/Virtual/Preview/Interceptor.php(26): Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor->___callPlugins('dispatch', Array, Array)
#29 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/App/FrontController.php(55): Smile\ElasticsuiteVirtualCategory\Controller\Adminhtml\Category\Virtual\Preview\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#30 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#32 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#33 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /usr/share/nginx/html/test.magento.dev/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /usr/share/nginx/html/test.magento.dev/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#38 /usr/share/nginx/html/test.magento.dev/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#39 {main}";s:3:"url";s:82:"/hp_ols_admin/virtualcategory/category_virtual/preview/ajax/1/store/1/?isAjax=true";s:11:"script_name";s:10:"/index.php";}

### Preconditions

Magento Version : CE

ElasticSuite Version : 2.3.5

Environment : Production

**Comment by romainruaud** [comment]
Hello,

one of your product has a problem (no image, or image with a path that does not exists).

Could you try to investigate a bit more and find which product is problematic, and then give me informations about how this product is configured ?

Regards

**Comment by romainruaud** [comment]
I close this issue for two reasons : 

- inactive / no answer for one week.
- I have a strong suspicion that something is wrong with your data (a product which has no image) and this would imply that this bug is not related to elasticsuite.


Feel free to reopen the issue if you have anything new to add.

Best regards,
