### ISSUE TITLE
Is elasticsuite safe to use in production site?

### ISSUE THREAD

**Issue by inelukipg** [Smile-SA/elasticsuite#462]
Hi,
This looks lika a great extension for Magento2!
Is it ready to use in a production site? 

Do you have any examples of sites using elasticsuite in a live store? Or is there any demo site where you also can login to backend?

**Comment by romainruaud** [comment]
Hello @inelukipg 

We are running ElasticSuite in production for most of the Magento2 websites we developed here at Smile-SA. We were four-times Europe Partner of the the Year (2010-2014),two-times Spirit of Excellence (2015-2016), and now one of the top 5 Global Elite Partner (2017)  awarded by Magento : https://magento.com/partners/portal/details/partner/id/266/

ElasticSuite is a standard for us now, for all the Magento2 websites we develop. Prior to this, we also used to deploy the Magento1 version of this module on most of our customer's websites.

But for confidentiality issues, I am not able to drop a list of the sites running ElasticSuite in production here. Trust us that there are many, from small ones to several websites with millions of products.

Do not hesitate if you need more informations.

I close the issue for now, but feel free to reopen it if needed.

Best regards,
