### ISSUE TITLE
Call to a member function getStoreGroupId() on null when open virtual category on frontend

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#464]
### Preconditions

Magento Version : 2.1.7

ElasticSuite Version : 2.3.6

Environment : php 7.0.x

Third party modules :

### Steps to reproduce

1. migrate from mage 1
2. set some category as virtual
3. open it on frontend

### Expected result

1. category with applyed filters

### Actual result

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getStoreGroupId() on null in /ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php:346
Stack trace:
#0 /ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(201): Smile\ElasticsuiteVirtualCategory\Model\Rule-&gt;getRootCategoryId(NULL)
#1 /ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(249): Smile\ElasticsuiteVirtualCategory\Model\Rule-&gt;getVirtualRootCategory(Object(Magento\Catalog\Model\Category\Interceptor))
#2 /ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(138): Smile\ElasticsuiteVirtualCategory\Model\Rule-&gt;getVirtualCategoryQuery(Object(Magento\Catalog\Model\Category\Interceptor), Array)
#3 /ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php(284): Smile\ElasticsuiteVirtual in <b>/ololo/vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Rule.php</b> on line <b>346</b><br />

```

removing `if (is_numeric($store) || is_string($store)) {` fixes the problem for me. Don't know why it occurs. Category preview in admin panel works ok.

**Comment by romainruaud** [comment]
Hello @Koc 

Could you tell me what is is the `$store` variable when entering the `getRootCategoryId` function ? (with a var_dump or by logging it with a print_r)

Is it an already loaded Store Entity ?

**Comment by Koc** [comment]
As I understand correctly - `null` (Call to a member function getStoreGroupId() on null )

> Is it an already loaded Store Entity ?
Don't know, maybe no. Where it should be loaded? Am I missing some important block on the page?

**Comment by romainruaud** [comment]
The store is retrieved line 192 : `$storeId = $this->getStoreId()`

So yes, it may be null.

But if its "null", how could it work by removing the "is_numeric" and "is_string" check ?

Could you please put this check back, and tell me what is in the $store variable **before** the is_numeric check ?

**Comment by Koc** [comment]
Hm, sorry, I'm lying previously :).

```php
    private function getRootCategoryId($store)
    {
		var_dump($store); exit;
```
prints `int(1)`.

I haven't any multistore configured.

**Comment by romainruaud** [comment]
Kinda strange ... 

And just after that, what does $store contains after it is set via $this->storeManager->getStore($store) ?

Could it means that there is no store with the id "1" ?

Or maybe you are using some Website restrictions ?

**Comment by Koc** [comment]
As I understand correctly - it depends on cache.

flush cache - store = 1, after loading store = object
cache populated - store = null and store not loading

**Comment by Koc** [comment]
Looks like `$rule->setStoreId()` not called when cache is populated

**Comment by romainruaud** [comment]
Hello,

I agree that it could explain the issue. But I did never face it, neither on our demo site, nor on all Smile projects.

Which caches are enabled on your site ? And what is the callstack of your exception ? Is it passing through custom pieces of code made on your own ?

Regards

**Comment by Koc** [comment]
All caches are enabled except FPC.

Also I cann't understand why stacktrace is so small?

```
    private function getRootCategoryId($store)
    {
        var_dump($store);
        //if (is_numeric($store) || is_string($store)) {
            $store = $this->storeManager->getStore($store);
        //}
```

after cache flush returns `int(1) int(1) int(1) NULL NULL NULL ` (6 calls)
next request `NULL NULL NULL ` (3 calls)

As I see from `VirtualRule::afterLoad`

```php
$rule->setStoreId($object->getStoreId());
```

maybe when cache are populated - afterLoad method not executes.

**Comment by romainruaud** [comment]
Any update on this one @Koc  ? 

I still cannot reproduce it

**Comment by Koc** [comment]
I can give you teamviewer access for my PC with reproducible issue (if you have time to debug).

**Comment by romainruaud** [comment]
@Koc sorry but I can't.

Can you rather post me the complete stack trace of the raised exception ?

Not only the first lines like you did on your first message, but the complete stack trace.

Regard

**Comment by Koc** [comment]
Of course I understand you. Also there is a problem: stacktrace is short like in first message in issue. See my comment above

> Also I cann't understand why stacktrace is so small?

**Comment by romainruaud** [comment]
That's strange, please try to add something like this : 

```
    private function getRootCategoryId($store)
    {
        $storeGroupId = 0;
        
        try {
            if (is_numeric($store) || is_string($store)) {
                $store = $this->storeManager->getStore($store);
            }

            $storeGroupId = $store->getStoreGroupId();

        } catch (\Exception $exception) {
            $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
            $logger = new \Zend\Log\Logger();
            $logger->addWriter($writer);
            $logger->info($exception->getMessage());
            $logger->info($exception->getTraceAsString());
        }

        return $this->storeManager->getGroup($storeGroupId)->getRootCategoryId();
    }

and check if you get the full stacktrace in the log file.

Let me know
```

**Comment by romainruaud** [comment]
Closed due to being inactive for too long, and probably too much linked with custom data (since it's not reproductible by our side).

Feel free to reopen with more informations and proper reproduction scenario if you still need help on this one.
