### ISSUE TITLE
Catalog search indexer process unknown error : SQLstate 42S22 Column not found 1054 unknown column error

### ISSUE THREAD

**Issue by sugapriyanavamani** [Smile-SA/elasticsuite#466]
Catalog search indexer process unknown error : SQLstate 42S22 Column not found 1054 unknown column error

### Preconditions

Magento CE 2.1.7

ElasticSuite Version : 2.3.0

Environment : Development mode

Third party modules : No

### Steps to reproduce

1. installed elastic search 2.4.5 and relevant plugins, started the server
2. installed elastic suite 2.3.0 
3. run reindexing 

### Expected result

1. reindexing should be successful

### Actual result

1.getting following error when reindexing

C:\wamp64\bin\php\php7.0.10>php C:\wamp64\www\magento1\bin\magento index:reindex

Design Config Grid index has been rebuilt successfully in 00:00:06
Customer Grid index has been rebuilt successfully in 00:00:06
Category Products index has been rebuilt successfully in 00:00:02
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:09
Product EAV index has been rebuilt successfully in 00:00:05
Catalog Search indexer process unknown error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'use_name_store_value.val
ue' in 'field list', query was: SELECT `cat`.`entity_id`, COALESCE(store_value.v
alue,default_value.value) AS `name`, COALESCE(use_name_store_value.value,use_nam
e_default_value.value,1) AS `use_name` FROM `catalog_category_entity` AS `cat`
 INNER JOIN `catalog_category_entity_varchar` AS `default_value` ON cat.entity_i
d = default_value.entity_id
 LEFT JOIN `catalog_category_entity` AS `use_name_default_value` ON default_valu
e.entity_id = use_name_default_value.entity_id AND use_name_default_value.attrib
ute_id = 0 AND use_name_default_value.store_id = 0
 LEFT JOIN `catalog_category_entity_varchar` AS `store_value` ON default_value.e
ntity_id = store_value.entity_id AND store_value.attribute_id = 45 AND store_val
ue.store_id = 1
 LEFT JOIN `catalog_category_entity` AS `use_name_store_value` ON default_value.
entity_id = use_name_store_value.entity_id AND use_name_store_value.attribute_id
 = 0 AND use_name_store_value.store_id = 1 WHERE (cat.entity_id != 2) AND (defau
lt_value.store_id = 0) AND (default_value.attribute_id = 45) AND (cat.entity_id
IN (2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24,
25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36))
Stock index has been rebuilt successfully in 00:00:03
Catalog Rule Product index has been rebuilt successfully in 00:00:04
Catalog Product Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing index has been rebuilt successfully in 00:00:01
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00

**Comment by romainruaud** [comment]
Hello,

it looks like you did not install the module properly.

Did you ran the "bin/magento setup:upgrade" command properly ?

Best regards.

**Comment by sugapriyanavamani** [comment]
Thank you so much for ur response...

yes done it.. installed elastic suite module using composer

<<<composer require smile/elasticsuite:2.3.0>>>

![image](https://user-images.githubusercontent.com/29648582/27953904-3493c73a-632b-11e7-8ac8-8a50e5ee54d1.png)

it did five installs and then it says package "fabpot/php-cs-fixer" is abandoned , use friendsofphp/php-cs-fixer.

I ran setup:upgrade then

then when i opened the admin console, i got the following error.

![image](https://user-images.githubusercontent.com/29648582/27954188-7bfa2456-632c-11e7-9ddd-73731c70b615.png)

opened setup_module table in db and changed the data_version same as schema_version

"update setup_module set data_version = schema_Version where module like 'Smile%'"

again ran setup:upgrade

Now, admin console is opening. set the search engine to "smile elastic"

ran again setup:upgrade and then reindexing.. same error as i told in previous message

**Comment by romainruaud** [comment]
You are doing it wrong ....

When it did show you that your modules did not have the proper versions, that was meaning you have to launch the setup:upgrade command.

By setting the values directly in the table you are saying to magento "everything is installed", which was obviously not the case, because he was saying you that he was needing you to run the setup:upgrade command....

Running the setup:upgrade command after having already hacked into the database has no effect, because since magento sees the proper version in the DB, he does not proceed to any installation at all.

Please restart from scratch and by following exactly what is written in the wiki : https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall

**Comment by sugapriyanavamani** [comment]
Thank you

Now i have done again from scratch

when running setup:upgrade.. it is done, but some write permission error on luma media files.. hope it is not an issue

![image](https://user-images.githubusercontent.com/29648582/27956736-b94fb6b6-6338-11e7-9b4e-f7463f4c8794.png)

when opening magento admin.. same dataversion error 

![image](https://user-images.githubusercontent.com/29648582/27956832-25949c38-6339-11e7-9783-fecbe74a97d6.png)

dont know how to proceed...

i ran setup:upgrade, but still the dataversoin error is coming

**Comment by sugapriyanavamani** [comment]
now done this also
 1) bin/magento setup:static-content:deploy

2) removed the read only permission for all files under magento folder

3) deleted smile related modules from setup_module table
<<delete from `setup_module` where module like 'Smile%'>>

4) bin/magento setup:upgrade --keep-generated

same version error in magento admin <<data: current version - none, required version - 0.0.1>>

**Comment by sugapriyanavamani** [comment]
Thank you. it is resolved now.. From the below blog i got that the file permission issue is not allowing the setup:upgrade to run completely..
https://github.com/mirasvit/module-blog/issues/44

Thankyou

**Comment by romainruaud** [comment]
Fine,

I close the issue then.

Do not hesitate to reopen it if needed.

Best regards
