### ISSUE TITLE
Creating a custom search suggestion list

### ISSUE THREAD

**Issue by ShirishRam** [Smile-SA/elasticsuite#468]
Is there any way to create a custom search suggestion list. For example, if I want to add 'Recent terms' as a section in the search autocomplete dropdown along with the other existing suggestion lists (terms, products, categories). Is there a way to do it through some configurations or by extending your module?

### Preconditions

Magento Version : Magento CE 2.1.6
ElasticSuite Version : 2.3.5
Environment : Developer mode
Third party modules : N/A

### Steps to reproduce
1. Need to know more about adding custom search suggestion list

### Expected result
1. Recent terms in the search autocomplete dropdown

**Comment by romainruaud** [comment]
Hello,

please check this part of the wiki : https://github.com/Smile-SA/elasticsuite/wiki/AutocompleteExtension

You are able to extend the module by this way to append new "providers" to the autocomplete.

Best regards,

I close the issue for now, do not hesitate to reopen it if you have more questions,

**Comment by ShirishRam** [comment]
Can I add the autocomplete rendered in the DI itself, rather than in the layout file? Will it work the same way?

Thanks!

**Comment by romainruaud** [comment]
I think it could work via the DI, but I would strongly recommend using the layout for now. Via the DI you will not be able to translate the title of the block.

Which version of Elasticsuite are you using ? This was done via the DI previously, but since version 2.3.6 this is done via the layouting, to fix the translations issues (see here : https://github.com/Smile-SA/elasticsuite/pull/437 )

**Comment by ShirishRam** [comment]
I am using version 2.3.5. I can update to version 2.3.6 and use layout. Thanks!

**Comment by ShirishRam** [comment]
Is there any way to remove an item from the render list? I want to remove terms from the search autocomplete.

**Comment by ShirishRam** [comment]
Got it! Never mind.

I configured popular term max size to 0 in the admin panel.
