### ISSUE TITLE
Provide example how to run arbitrary queries

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#469]
Please add some howto and describe how it possible reuse elastic index to run some queries like getting categories ids for filtered product collection. For now I'm using native Magento products collection api which triggers queries into mysql. Is it possible to reuse some other api for queryuing elasticsearch instead?

**Comment by romainruaud** [comment]
Hello Koc.

Could you give me a specific use case describing precisely what you are trying to do ? This way, I'll be able to help you with more details.

Regards

**Comment by Koc** [comment]
For example I want get all categories for products filtered by some attributes like manufacturer, colour, etc. For now I'am doing it using native product/category collections. But this collection works with mysql.

Is there way to retrieve this data from elasticsearch using some standatd magento api?

**Comment by romainruaud** [comment]
You can take a look on how the Preview of the optimizers is made in the 2.4.x branch.

Starting from this one : https://github.com/Smile-SA/elasticsuite/blob/2.4.x/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview.php

Then the Request Builder : https://github.com/Smile-SA/elasticsuite/blob/2.4.x/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/RequestBuilder.php

And the Results Builder (which is in fact running the search) : https://github.com/Smile-SA/elasticsuite/blob/2.4.x/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/ResultsBuilder.php

Here is a short example of building a simple query (visibility, and stock availability) : https://github.com/Smile-SA/elasticsuite/blob/2.4.x/src/module-elasticsuite-catalog-optimizer/Model/Optimizer/Preview/SearchQuery.php#L89

I know I am not providing many details here, I hope that you will manage to understand how this part is working and how you could do it on your own.

If it's not the case, do not hesitate to ask more questions,

Best regards

**Comment by Koc** [comment]
@romainruaud, oh, thanks.

**Comment by afoucret** [comment]
Closed since @romainruaud responded few times ago.
