### ISSUE TITLE
Filter in catalogsearch without query

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#476]
Feature request:
The q parameter is required, without it I either see a report page or a redirect to the homepage. I haven't found a wildcard character to simulate not passing a query.
Wouldn't it be nice if you could link to catalog search with a filter as parameter without the q parameter to find all red products in store? 
Example:
catalogsearch/result/index/?color=red

**Comment by afoucret** [comment]
This is a limitation of Magento.
The search queries issues by users are saved into the search query terms stats table and it can not be saved if the query is empty.

A workaround is to provide q equals to the searched filter in your example : catalogsearch/result/index/?color=red&q=red

No report should be raised. If so there is a bug there. On my instance I am redirected to the homepage if the query param is missing.

**Comment by rikwillems** [comment]
Thanks for the hint on the workaround, that would work. On my live instance I get a redirect to the homepage. On local development I saw a report.
