### ISSUE TITLE
Add support of adding custom orders (like optimizier)

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#478]
For now possible boost product by rules. But each optimiziers apply always for each request. It would be nice add option - apply optimizier when `product_list_order=XXX`, so we can create custom dynamic arbitrary orders.

**Comment by romainruaud** [comment]
Thank you for submitting this request, @Koc 

We'll have a look on it with @afoucret 

Best regards

**Comment by afoucret** [comment]
Hi @koc,

This was stallen since I was looking a way to implement it.
Sadly and it is by design there is no way to implement it.
