### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by maxmcee** [Smile-SA/elasticsuite#483]
### Preconditions

Magento Version : 2.1.7

ElasticSuite Version : 2.3.6

Environment: Ubuntu 16.04

Third party modules :

### Steps to reproduce

1. composer require smile/elasticsuite

### Expected result

1. Install ElasticSuite

### Actual result

1. 
composer require smile/elasticsuite
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^2.3 for smile/elasticsuite
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - smile/elasticsuite 2.3.6 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.5 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.4 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.3 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.2 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.1 requires magento/framework >=100.1.0 -> no matching package found.
    - smile/elasticsuite 2.3.0 requires magento/framework >=100.1.0 -> no matching package found.
    - Installation request for smile/elasticsuite ^2.3 -> satisfiable by smile/elasticsuite[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

**Comment by romainruaud** [comment]
Hello @maxmcee 

You have to run the `composer install` command at the root of your magento installation.

How did you install Magento ? What do you have in your composer.json file ?

**Comment by maxmcee** [comment]
Hello @romainruaud 
Thank you for the help

**Comment by romainruaud** [comment]
I close this one since it seems resolved.

Feel free to reopen it if you are still encountering issues.
