### ISSUE TITLE
VC Filtering on scoped-level attributes when no global value set

### ISSUE THREAD

**Issue by vo1** [Smile-SA/elasticsuite#497]
Issue on filtering virtual category on store/website scope attributes when no global fallback value present in database.

### Preconditions

Generic M 2.1.7 environment

Magento Version :
Magento CE 2.1.7

ElasticSuite Version :
2.3.0

Environment :
Development mode.

Third party modules :
None
### Steps to reproduce
1. Create a filterable attribute vcat, simple Boolean, store/website scope, assign it to attribute set.
2. Find existing product with attribute set containing vcat, select store/website scope and change attribute vcat to be yes.
3. Go to categories and select store view of product that was updated above.
4. Create virtual category on specific store, filter for this attribute, when vcat = yes, you will see no products in the list. Reindexing won't help.

### Expected result

Should show products which have vcat=yes on selected virtual category store

### Actual result

Not showing anything

To make product appear - go to product, select "All store views" and simply click save. The global value (regardless of its yes or no) will be pushed to DB and ES and product will be filtered now correctly.

**Comment by romainruaud** [comment]
Sorry for the delayed response but you are right.

Let's see the query which is ran during indexing : 

```
SELECT `entity`.`entity_id`, `t_default`.`attribute_id`, COALESCE(t_store.value, t_default.value) AS `value` 
FROM `catalog_product_entity` AS `entity`
 INNER JOIN `catalog_product_entity_varchar` AS `t_default` 
ON entity.entity_id = t_default.entity_id
 LEFT JOIN `catalog_product_entity_varchar` AS `t_store` 
ON t_default.entity_id = t_store.entity_id AND t_default.attribute_id = t_store.attribute_id AND t_store.store_id= 1 
WHERE (t_default.store_id=0) 
AND (t_default.attribute_id IN (134, 200, 140, 153, 151, 138, 139, 87, 136, 73, 152, 150, 210, 137, 135, 148, 149, 208)) 
AND (entity.entity_id IN (1))
```

We can see that it begins with an "INNER JOIN" on the attribute table, with the clause "store_id=0".

So if a product, for any reason, does not have any value for the default store for a given attribute, this attribute value will not be indexed, even if a value exists for store 1 (or store X).

**Comment by romainruaud** [comment]
For me, this is not something we will fix : 

- reasons of why a product would not have default value (store 0) for an attribute are quite unclear.
- I understand your scenario, but I find it quite unusual to happen on a running production website (creating attribute directly via the BO and contributing it into products by hand and only for a given store)
- fixing this one would require to revamp the indexing SQL query to something that would be, in any case, much slower compared to what we are doing now.


Do not hesitate to reopen the issue or to propose an elegant PR to fix this behavior if it is really annoying for you or your customer.

Regards
