### ISSUE TITLE
Missing Layered Navigation on Some Category Pages

### ISSUE THREAD

**Issue by espradley** [Smile-SA/elasticsuite#498]
In production mode, layered navigation dissapears for some categories.

### Preconditions
Attribute options as a drop down with a value of 0 AND with a sort of adminBackendSort

Magento Version :  2.x EE and CE

ElasticSuite Version : Tested on 2.0.0 and 2.1.6, but probably for most versions.

Environment :  Both

Third party modules : N/A

### Steps to reproduce

1.    Create a select attribute and make sure it's set to be filterable in layered navigation.  Also ensure that its sort is set to Admin Backend Sort
2.    Add a value of 0 as one of the options
3.    Set that value on a product and associate it to a category

### Expected result

1.    0 should show up in the layered navigation.

### Actual result

Production Mode:  Navigation disappears. 
Developer Mode:  
`Exception #0 (Exception): Notice: Undefined index: adminSortIndex in [magento_root]/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php on line 275`

###Fix
src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php

Change line 267 FROM:
`if ($optionLabel) && isset($items[$optionLabel])) {`

to 
`if (isset($optionLabel) && isset($items[$optionLabel])) {`

**Comment by espradley** [comment]
Pull request submitted.
https://github.com/Smile-SA/elasticsuite/pull/499

**Comment by afoucret** [comment]
PR #525 fix this one and have been merged in branch 2.3.x
