### ISSUE TITLE
Error when clicking on "New attribute" during product configuration creation

### ISSUE THREAD

**Issue by cldha** [Smile-SA/elasticsuite#500]
Hi there,

When creating configurations for configurable products, if on step 1 you click on Create New Attribute, an exception is displayed. Please find more information below : 

### Preconditions
Magento EE 2.1.5 or 2.1.7
ElasticSuite Version : 2.3.6
Environment : Development and Production mode

### Steps to reproduce
1. Go to the back-office, in Products > Catalog
2. Click on Add Product
3. Fill in all the mandatory fields
4. Click on Create configurations
5. On Step 1: Select Attributes, click on Create New Attribute

### Expected result
1. We should be able to create a new attribute

### Actual result
1. The following exception is displayed : 

![configurations-new-attribute-error](https://user-images.githubusercontent.com/27002605/29371112-c1cd5cce-82a7-11e7-8fbb-f5f5f6b40f60.png)

This has been reproduced on a fresh install of Magento + ElasticSuite. 

Kind regards,
Claire

**Comment by romainruaud** [comment]
Hello Claire,

do this work on a raw Magento install (without Elasticsuite) ? Since I do not see anything related to ElasticSuite in the stacktrace, I would be sure that it is not a Magento native bug.

Regards

**Comment by cldha** [comment]
Hi Romain, 

My developer tells me the problem is in the file vendor/smile/elasticsuite/src/module-elasticsuite-catalog/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml. In this file is used the layout "admin-2columns-left", but by default in Magento 2 it is "admin-1column". (This can be checked in the default M2 file vendor/magento/module-catalog/view/adminhtml/layout/catalog_product_attribute_edit_popup.xml.)

This results in the duplication of the block Magento\Catalog\Block\Adminhtml\Product\Attribute\Edit\Tab in "content" and in "left" container and on the second time, while the _prepareForm of the block is running, it triggers the error.

Hope this helps, 

Kind regards,
Claire

**Comment by afoucret** [comment]
PR have been mergerd in branch 2.3.x
