### ISSUE TITLE
Admin category view Product Preview and Sorting is not using the cached image

### ISSUE THREAD

**Issue by viiter** [Smile-SA/elasticsuite#504]
### Preconditions
Magento Version : CE 2.1.7
ElasticSuite Version : 2.3.6
Environment : Developer
Third party modules : none

### Steps to reproduce
1. Create a category for products
2. Create a product and upload a high definition image to it, attach it to previously created category
3. open the said category in admin Products > Categories
4. see that the section "Product Preview and Sorting" is using the thumbnail as the original image that is resized inline

### Expected result
1. the product thumbnail should use the media cached file instead ex: media/catalog/product/cache/small_image/240x300/beff4985b56e3afdbeabfc89641a4582/w/a/wallhaven-426396.png

### Actual result
1. The original uploaded image is linked as the source for the "thumbnail" ex: media/catalog/product//w/a/wallhaven-426396.png

the problem is that when i have n+1 amount of images that are all full hd and size is from 1MB to 10MB the amount of data needing to be downloaded for that "preview" area is enormous and with a slower computer, slower internet speed i need to download 100s of megabytes of data to rearrange my products ?!

![screen shot 2017-08-18 at 15 29 01](https://user-images.githubusercontent.com/1838955/29459353-e54fbf18-842b-11e7-945c-7100c7f7b7a3.png)

**Comment by afoucret** [comment]
PR have been merged in branch 2.3.x.

**Comment by afoucret** [comment]
Available in the 2.3.7 release.
I close the issue.
