### ISSUE TITLE
How would one include autocomplete product results in general search query?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#512]
I'd like to include the limited number of products  in autocomplete search - once you hit enter and   retrieve the general query results?

How would I  go a bout patching  the multi-match query to directly include the autocomplete query results?

**Comment by romainruaud** [comment]
Hello @southerncomputer 

I don't understand what you are meaning by "the limited number of products in autocomplete search" ?

Could you please detail a bit more what you are trying to obtain ?

regards

**Comment by southerncomputer** [comment]
When I search using autocomplete the results are generally more accurate than when you press enter on the search box and see the results, I would like to have the results of the autocomplete carry forth into the main search results. It is understandable they use a different method to locate the products but am not sure how to get the same results included and prioritized into the main results

**Comment by romainruaud** [comment]
Autocomplete Data provider for products is basically identical to what we are doing on the search result page : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Autocomplete/Product/DataProvider.php

The only difference here is the collection is filtered by "the search terms related to the current user input", as seen here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Model/Autocomplete/Product/Collection/Filter.php#L82

You could copy the use of the "TermDataProvider" on a plugin around the addSearchFilter method of the ElasticSuite collection, this may do what you want.

Regards
