### ISSUE TITLE
Add rule for virtual category - only new products

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#513]
### Preconditions

Magento Version : 2.1.8

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules : -

### Steps to reproduce

1. Switch category to virtual
2. Rename it to "new products"
3. Start adding filters

### Expected result

1. Expected add rule "only new products" (products which filters by standard magento attributes for new products: `now() beteween product.is_new_from and product.is_new_to` )

### Actual result

1. This rule is missing

**Comment by romainruaud** [comment]
Duplicate of #410 

I close this one.

Regards

**Comment by Koc** [comment]
oops, sorry for duplicate
