### ISSUE TITLE
Categories dependent on alive Elasicsearch connection

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#516]
We notice in our development project that category listings are dependent on an alive Elasicsearch server. When no connection is available the category listing shows an error report. 

We host a small Elasticsearch server on which Elasicsearch crashes from time to time which results in a missing connection. 

Can this dependency be remove? So we can see normal (Magento default) category listings when no connection is available? Virtual categories wouldn't work of course, but normal categories could.

**Comment by romainruaud** [comment]
Hello,

unfortunately, you can't.

We consider the Search Engine as vital as other parts of an Ecommerce website : would you tolerate a website where the MySQL crashes from time to time ? 

Please read my complete answer here : https://github.com/Smile-SA/elasticsuite/issues/509#issuecomment-324271074

I'm sorry but you should better get a fully working Elasticsearch server,

best regards

**Comment by rikwillems** [comment]
Hi Romain,

You are right, we need a 100% Elasticsearch server. But this issue appeared now so I thought I'd bring it up. Thank you for your answer, it is clear and understandable.

Cheers!
