### ISSUE TITLE
Synonyms in Elasticsuit

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#518]
How do you use ElasticSearch functionality: synonyms? How did you implement it?

**Comment by romainruaud** [comment]
Hello @madonzy 

if you are speaking about the "synonyms" filter of Elasticsearch, we are not totally relying on it. We build a Thesaurus system which is more useful. Please see the Wiki about it.

In fact, when you build a synonym/expansion list in the Magento Back office, we fill a new Elasticsearch index with these synonyms. They are then used when searching.

Regards,

**Comment by madonzy** [comment]
@romainruaud what do you mean "Magento Back office"? Where in Magento I can set such synonyms?

**Comment by romainruaud** [comment]
Please read the Wiki : https://github.com/Smile-SA/elasticsuite/wiki/Thesaurus and the User guide.
