### ISSUE TITLE
New Feature - delete products from a search page

### ISSUE THREAD

**Issue by FlorentGuilbard** [Smile-SA/elasticsuite#522]
### Preconditions
Magento Version : 2.0.x and 2.1.x
Magento CE and EE 

### The steps of functionality
Could we imagine deleting products from a search page?
For example : for the query "tee-shirt", I have 23 T-shirts that go up + 3 tee-shirts with long sleeves.

### Expected result
I wouldlike to have juste the 23 T-shirts
I don't have the ability to delete the 3 tee-shirts with long sleeves by hand, or create virtual categories. So I would like to delete them.

Do you think it's possible to create this feature ? 

Thank you

**Comment by afoucret** [comment]
The feature is merged and will be available in release 2.6.0.
