### ISSUE TITLE
Filter for configurable option delivers configurables with out of stock simples

### ISSUE THREAD

**Issue by sydekumf** [Smile-SA/elasticsuite#530]
We have a catalog of only configurables (shoes) visible in the frontend. On the category page we have a size filter. When you select one size it still displays configurables where the size is not in stock (is_in_stock = 0 and qty = 0).

I saw that `Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData::loadChildrens()` does not filter if a child is in stock or not. Also the search query on the category page with the corresponding filter does not respect out of stock products.

### Preconditions
- Configurables with simples as childs
- One Simple is out of stock (is_in_stock = 0 and qty = 0)
- Filter on the category page for the attributes which belong to the out of stock simple

Magento Version : EE 2.1.8

ElasticSuite Version : 2.4.4

Environment : Developer or Production (both reproducable)

Third party modules : n.a.

### Steps to reproduce
- Configurables with simples as childs
- One Simple is out of stock (is_in_stock = 0 and qty = 0)
- Filter on the category page for the attributes which belong to the out of stock simple

### Expected result
1. The configurable is not shown on the category page for the filter selection as the corresponding simple is out of stock

### Actual result
1. The configurable is shown on the category page

**Comment by afoucret** [comment]
This behavior is consistent with what Magento does out of-the-box and we do not plan to change it.

If you need such a behavior, you should try to have a look at \Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\AttributeData::loadChildrens. A plugin may be used there to filtered out children that are not in stock.
