### ISSUE TITLE
How to combine filterable attributes?

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#531]
How can I combine some filterable attributes to show them not in separate blocks, but all (I have three) in one block?

I mean that I want to combine view like this:
<img width="305" alt="screen shot 2017-09-14 at 11 30 16 am" src="https://user-images.githubusercontent.com/5281020/30422424-32525be4-9940-11e7-83a0-123868aa8265.png">
to view like this:
<img width="305" alt="screen shot 2017-09-14 at 11 31 17 am" src="https://user-images.githubusercontent.com/5281020/30422450-47fc1bf6-9940-11e7-81b9-45436810a004.png">

**Comment by afoucret** [comment]
You have to create a new attribute (a swatch attribute in your case this you are using image in filters) and merge the values into this attribute.

A piece of code like a product save plugin may be used to keep sync values between main attributes and the new one.

It is not directly related with ElasticSuite, so I close this one.
