### ISSUE TITLE
Slight product sorter UX improvements in admin

### ISSUE THREAD

**Issue by sambolek** [Smile-SA/elasticsuite#536]
### Preconditions

Magento Version : Magento CE 2.1.6

ElasticSuite Version : source - c273b232a8fb3e33344b9501e44f194370262d6f

Environment : Developer

Third party modules : not relevant

### Steps to reproduce

1. Open product sorter in admin
2. Assign large number of various products of similar names to category

### Expected result

1. Products are easily identified by SKU or product name, even if product name is long, by hovering over product name

### Actual result

1. Observe that there's no SKU identifier on products
2. Observe that there's no title on product name, so it's not possible to view entire product name, as the box that contains the product is smaller than whole product name

I'm submitting a pull request that adds a bit more info to product sorter.

**Comment by afoucret** [comment]
I will check the PR but 👍 for the feature proposal.

**Comment by afoucret** [comment]
Merged in branch 2.4.x

Thx for the contrib.
