### ISSUE TITLE
ReaderPoolInterface does not exist in Magento 2.2

### ISSUE THREAD

**Issue by roman204** [Smile-SA/elasticsuite#544]
### Preconditions

Install Magento 2.2
Install smile/elasticsuite:^2.3

Magento Version : 2.2.0

ElasticSuite Version : 2.3.7

Environment : developer|default|production

Third party modules : no

### Steps to reproduce

1.
2.
3.

### Expected result

1. it should work

### Actual result

1. [Screenshot, logs]
PHP Fatal error:  Interface 'Magento\Framework\App\Config\Scope\ReaderPoolInterface' not found in /var/www/htdocs/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/Search/Request/RelevanceConfig/ReaderPool.php on line 22

**Comment by afoucret** [comment]
Hi @roman204,

Magento 2.2.0 is not backward compatible with previous version.
The PR #543 fix this one. It will be merged very soon and be part of the 2.3.8 release which aims to bring Magento 2.2.0 compatibility to Elasticsuite.

Feel free to test the PR and give us a feedback.

**Comment by afoucret** [comment]
I close the issue by mistake. We will wait for the 2.3.8 release to close it.

**Comment by roman204** [comment]
Thanks for enlightenment

**Comment by afoucret** [comment]
2.3.8 version have been released.
I close the issue.

**Comment by Koc** [comment]
@romainruaud , @afoucret guys, you are the best!

**Comment by afoucret** [comment]
@Koc thx for being so supportive !!!
