### ISSUE TITLE
Newbie JRE installation question

### ISSUE THREAD

**Issue by inelukipg** [Smile-SA/elasticsuite#546]
Hi,
This is a really newbie question about JRE installation, sorry for that. But where should I install JRE?
Should I be in home directory or in Magento root when i run  _sudo yum install java-1.8.0-openjdk_?

**Comment by afoucret** [comment]
It does not matter.
yum install the package in your OS not in a particular directory.

I close since it is not related to ElasticSuite but a Java install question.
