### ISSUE TITLE
composer won't update  smile/elasticsuite[2.4.x-dev]

### ISSUE THREAD

**Issue by genyuk** [Smile-SA/elasticsuite#547]
### Preconditions
Magento 2.1.9 CE
Tried both Composer 1.2.1 and Composer 1.5.2

Magento Version :Magento 2.1.9 CE

ElasticSuite Version : 2.4.x-dev

Environment :Production

Third party modules :long list

### Steps to reproduce

1.composer update

### Expected result

1. successful update

### Actual result
1.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - smile/elasticsuite 2.4.x-dev requires magento/framework >=100.2.0 -> satisfiable by magento/framework[100.2.0-rc20, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 101.0.0].
    - smile/elasticsuite 2.4.x-dev requires magento/framework >=100.2.0 -> satisfiable by magento/framework[100.2.0-rc20, 101.0.0-rc21, 101.0.0-rc22, 101.0.0-rc23, 101.0.0-rc30, 101.0.0].
    - magento/framework 100.2.0-rc20 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc21 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc22 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc23 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0-rc30 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - magento/framework 101.0.0 requires composer/composer 1.4.1 -> satisfiable by composer/composer[1.4.1].
    - Conclusion: don't install composer/composer 1.4.1
    - Installation request for smile/elasticsuite 2.4.x-dev -> satisfiable by smile/elasticsuite[2.4.x-dev].

---
Did the last successful update a few days ago, but can't update composer since the last commit of the elasticsuite. Tried to roll back to  Composer 1.2.1 - same result.
Please advise how to fix it.

Thank you,

**Comment by afoucret** [comment]
Hi @genyuk,

2.4.x branch is not a stable branch.
When released this branch will be compatible with Magento >= 2.2.0.
We have updated phpunit and few dependencies today.

If you are using Magento 2.1.x you must use ElasticSuite 2.3.x branch.

**Comment by afoucret** [comment]
If you really need 2.4.x branch you should consider upgrading Magento.

**Comment by enridoku** [comment]
Hello! I am running Magento 2.2.1 CE, but I encounter a problem during the installation (sorry but I am an absolute beginner)...this is what I get:

> Problem 1
>     - The requested package magento/product-community-edition could not be found                                                                                                              in any version, there may be a typo in the package name.
>   Problem 2
>     - smile/elasticsuite 2.4.3 requires magento/framework >=101.0.0 -> no matchi                                                                                                             ng package found.
>     - smile/elasticsuite 2.4.2 requires magento/framework >=101.0.0 -> no matchi                                                                                                             ng package found.
>     - smile/elasticsuite 2.4.1 requires magento/framework >=101.0.0 -> no matchi                                                                                                             ng package found.
>     - smile/elasticsuite 2.4.0 requires magento/framework >=101.0.0 -> no matchi                                                                                                             ng package found.
>     - Installation request for smile/elasticsuite ^2.4 -> satisfiable by smile/e                                                                                                             lasticsuite[2.4.0, 2.4.1, 2.4.2, 2.4.3].
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your min                                                                                                             imum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det                                                                                                             ails.
>  - It's a private package and you forgot to add a custom repository to find it
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo                                                                                                             n problems.

What I do is: through FTP I copy the content of the src folder into public_html/vendor/magento (and so here I get those folders like module-elasticsuite-xxx and one folder called lib) then I login to the server and I run "composer require smile/elasticsuite"...but all I get is that error message.

I am 100% sure that I do something wrong, probably in the first step where I copy the folders into the server. I would really appreciate your help, and sorry again if it's a very basic question!
