### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by VictorSnow** [Smile-SA/elasticsuite#549]
### Preconditions
Magento Version : 2.2.0
ElasticSuite Version : 2.3.8
Environment : development
Third party modules : None
Elasticsearch: 5.6.2
os: ubuntu 16.04 php7.1.6nts

### Steps to reproduce
1. 
2.
3.

### Expected result
1. install success

### Actual result
1. failed to install with errors 
````
[ERROR] Elasticsearch\Common\Exceptions\BadRequest400Exception: No handler found for uri [/magento2_default_catalog_product_20170930_022743] and method [POST] in 
````

i tried a fresh install with elasticsuite, but keep showing this error

**Comment by afoucret** [comment]
Hi @VictorSnow,

ElasticSearch 5.x is not supported as explained in #375

**Comment by PingusPepan** [comment]
Hey,
is there a way how we can use it with ES5?. You said: 

> Actually we could add the ES 5.x support very quickly but it would make the module incompatible with Magento EE

is there a way for us to do it quickly ourselves?
Thank you!

**Comment by romainruaud** [comment]
@PingusPepan there is a branch called https://github.com/Smile-SA/elasticsuite/tree/feature-es-5-compat

But we may need to resync this branch with current master to ensure all fixes are properly merged to this one.

Regards
