### ISSUE TITLE
Price filter customization

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#557]
Hi, how can I edit the price filter to make it filter by price **with VAT**?

Elasticsuit: 2.3.8
Magento: 2.1.9

**Comment by romainruaud** [comment]
Hello @madonzy 

I dont understand your question. Please provide details about your prices and tax display configuration.

Regards

**Comment by madonzy** [comment]
@romainruaud lat's say that we have product A in the website DE, the price for the product A is $10 + 13% VAT ($11,30 total). In the website FR the price for the same product is $14 because of 40% of VAT. I want to filter in my layered navigation prices with VAT.

**Comment by romainruaud** [comment]
@madonzy I am not able to help you if I do not have full vision on what you are doing. Please provide an exhaustive copy of : 

- what you have configured in the Back-office under **Sales > Tax > Price Display Settings** (for each website if this does differ)
- the price which is set for your product, for each website (if the price differs across websites).
- the entry of the ```catalog_product_index_price``` table for your products.

Regards.

**Comment by romainruaud** [comment]
Closed due to being inactive/no-answers for 3 weeks.

Feel free to reopen it if you are able to provide more details.
