### ISSUE TITLE
Question: Layered navigation show categories from brand attribute

### ISSUE THREAD

**Issue by inelukipg** [Smile-SA/elasticsuite#558]
I'm using virtual categories for my brand attribute to show a list of brands in the top menu and list all products by a brand in the layered navigation.
 
Is it possible to show a list of categories in the left sidebar with the categories that are linked to those products?

The search result works this way when I search for a brand instead.

**Comment by romainruaud** [comment]
@inelukipg yes, you can try to add the "Default Category" (the root of your catalog) as "Virtual Category Root" of your virtual category.

it's possible to do this in the edit screen of your category in the back-office

**Comment by inelukipg** [comment]
@romainruaud Ok, thank you! I tried this, but no luck.
The virtual brand category (_Brand 1_) is on the 3rd level, is that a problem?
Like: 
-Default Category
--Brands (Normal Category)
---Brand 1 (Virtual Category)
---Brand 2 (Virtual Category)

If I navigate to the the 2:nd level category _Brands_ it shows categories in the left sidebar, but only the virtual brands categories.

**Comment by inelukipg** [comment]
Anyone got an idea or a solution about this?

**Comment by inelukipg** [comment]
Ok, I think my goal is not possible. 

Sub categories from virtual categories are fetched from sub categories from the virtual category itself.
I thought the sub categories were fetched from the Virtual Category Root..??

**Comment by romainruaud** [comment]
@inelukipg you are right, the automatic generation of a subtree has never been finished (see waiting PR #235 )

I'm sorry but you are right, your goal is not actually possible.

Please keep in touch with us to be informed when the feature goes live.

Regards

**Comment by inelukipg** [comment]
Hi,
ok, thanks! That would be a great feature!
