### ISSUE TITLE
Option to change "missing" option in "sort" clause.

### ISSUE THREAD

**Issue by lucacanella** [Smile-SA/elasticsuite#560]
We needed to reverse the "missing" option behaviour of the "sort" clause within a products query but there is no per attribute option to achieve this.

Probably related to https://github.com/Smile-SA/elasticsuite/issues/62, but not sure, so we opened a new Issue.

### Preconditions

We have a date attribute we use to sort catalog products which is optional so many products are missing a value. When we sort by descendant order on this attribute we get products with null value first but they should show last.
Current solution is to override buildSortOrder inside `Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Request\SortOrder\Builder`, changin this lines:
```
        $sortOrderConfig = [
            'order'         => $sortOrder->getDirection(),
            'missing'       => $sortOrder->getDirection() !== SortOrderInterface::SORT_ASC ? '_first' : '_last',
            'unmapped_type' => FieldInterface::FIELD_TYPE_STRING,
        ];
```
Please note that "**!==**" was originally a "==".

What we achieve was to show products with null attribute last, but it affected the catalog globally (on every attribute). What we preferred was to have a backend option to tune on a per attribute basis.

Magento Version : 2.1.7

ElasticSuite Version : 2.3.8

Environment : Developer and production mode.

### Steps to reproduce

1. Add an optional date catalog product attribute.
2. Set this value only on certain products.
3. Try to sort in DESCENDING order.

### Expected result

1. We expected to see products with attribute value first (obviously sorted in desc order) followed by products without a value on that attribute.

### Actual result

1. Products without a value for that attribute are shown first.

**Comment by romainruaud** [comment]
You are right, we should definitely address this point by allowing to configure it on the attribute level.

Btw, this has already been reported in #362 

Regards
