### ISSUE TITLE
Getting Blank page on search result page

### ISSUE THREAD

**Issue by amitsharma8891** [Smile-SA/elasticsuite#561]
Hello,

I just installed this package to my Magento 2.1.7 and followed all the instruction mentioned in the documentation and its working very fine but when I enter any word to the search box and hit the enter it directs to search page but there I am getting the blank page. I checked all log files but not getting any error.
Here is the link.
http://kosmetic.clu.pw/catalogsearch/result/?cat=&q=moist

### Preconditions

Magento Version :Magenot 2.1.7 (CE)

ElasticSuite Version : 2.3

Environment : Developer

Third party modules :

### Steps to reproduce

1. Click search button on the right corner of the page.
2.En.ter any keyword and hit enter
3.It will redirect to search page which is blank

### Expected result

1.Should show search result instead blank page.

### Actual result

1. Got blank page (couldn't find anything in log files)

please check this link.
http://kosmetic.clu.pw/catalogsearch/result/?cat=&q=moist

**Comment by afoucret** [comment]
Blank page usually means a php fatal error.
Without any error message there is nothing we can do for you.

I close the issue. If you have more detail to share with us, feel free to reopen.
