### ISSUE TITLE
Can not reindex after upgrading from 2.3.5 to 2.3.7/8

### ISSUE THREAD

**Issue by srenon** [Smile-SA/elasticsuite#565]
### Preconditions

Magento Version : 2.1.9 EE

ElasticSuite Version : 2.3.7

Environment : Both

Can not longer add or remove a product from category etc because of error in reindexing, after upgrading from Magento 2.1.7EE / ElasticSuite 2.3.5 to Magento 2.1.9EE / ElasticSuite 2.3.8 (or 2.3.7) with same exact product data.

> Catalog Search indexer process unknown error:
> Notice: Undefined index: status in vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php on line 51
> Product/Target Rule index has been rebuilt successfully in 00:00:00
> Target Rule/Product index has been rebuilt successfully in 00:00:00
> Sales Rule index has been rebuilt successfully in 00:00:01

##Possible solution
vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/AttributeData.php

            foreach ($childrenIndexData as $childrenId => $childrenData) {
                 //check if array key exist
                if(array_key_exists('status', $childrenData)){
                    $enabled = current($childrenData['status']) == 1;
                    if ($enabled === false) {
                        unset($childrenIndexData[$childrenId]);
                    }
                }
            }

Output of print_r($childrenData) in foreach loop

```
....
Array
(
    [product_size] => Array
        (
            [0] => 573
        )

    [option_text_product_size] => Array
        (
            [0] => L
        )

    [name] => Array
        (
            [0] => Product 1
        )

)

Array
(
    [product_size] => Array
        (
            [0] => 572
        )

    [option_text_product_size] => Array
        (
            [0] => M
        )

    [name] => Array
        (
            [0] => Product 2
        )

)
.....

```

**Comment by afoucret** [comment]
I don't see how it is possible to have products without the status attribute filled.
Maybe a corruption in your data ?

I will try to make the process of indexing more secure but you should check why simple product have no status attribute filled.

**Comment by Koc** [comment]
Have same issue after migrating from Magento 1.9.3.4 to 2.1.9. Looks like data-migrator tool bug.

**Comment by srenon** [comment]
@Koc ... we are using a third-party extension to add/update products/attributes but this was build from ground up on Magento 2.x (starting with 2.1.4), so no data-migrator tool was used.

**Comment by srenon** [comment]
@afoucret ... is it possible to make another release? I tested your fix and it does work for me

**Comment by afoucret** [comment]
Release 2.3.10 contains the fix.
