### ISSUE TITLE
Price scroll incorrect edge values

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#571]
The values on the price scroll are incorrect on init.

### Preconditions

Magento Version : 2.1.9

ElasticSuite Version : 2.3.8

Environment : Developer

Third party modules : -

### Steps to reproduce

1. Open catalog/search
2. See price scroll edge values

### Expected result

1. Edge value to be limited to the lowest and highest prices of filtered products

### Actual result

1. The down edge price is smaller then the price of the cheapest product (see brutto value)
2. The up edge price is higher then price of the most expensive product (not seen in screen)

**The products on screen are sorted by price from small to high.**
![screenshot-2](https://user-images.githubusercontent.com/5281020/31715837-a0e0c6a6-b405-11e7-94ab-45732b4bac45.png)

**Comment by afoucret** [comment]
Are you using tier pricing ?

**Comment by madonzy** [comment]
@afoucret no, normal pricing. The value I put in admin panel is "brutto" (ex. 699,00 for the first product)

**Comment by afoucret** [comment]
Are you applying some post-filtering after the collection is loaded (in order to hide some products by example) ?

**Comment by madonzy** [comment]
@afoucret no, I load all products that apply values of filters. There's no extra functionality

**Comment by romainruaud** [comment]
@madonzy if I understand well, you have products on the page which have a "brutto" price which is >993 ?

If yes, can you please post here the same elements as in #557: 

- what you have configured in the Back-office under **Sales > Tax > Price Display Settings** (for each website if this does differ)
- the price which is set for your product, for each website (if the price differs across websites).
- the entry of the ```catalog_product_index_price``` table for your products.

Regards

**Comment by romainruaud** [comment]
Closed due to being inactive/no-answers for 3 weeks.

Feel free to reopen it if you are able to provide more details.

**Comment by madonzy** [comment]
@romainruaud 
price display settings are: 
<img width="1012" alt="screen shot 2017-11-21 at 3 05 16 pm" src="https://user-images.githubusercontent.com/5281020/33077046-f468e068-cece-11e7-9322-9200772c2345.png">

For the first product (when listing is sorted from low to high price):
price is set the same for each store = 699

catalog_product_index_price for this product is:
<img width="1019" alt="screen shot 2017-11-21 at 3 14 56 pm" src="https://user-images.githubusercontent.com/5281020/33077166-54ed6a62-cecf-11e7-8a64-314e929efd87.png">

**Comment by nicobatty** [comment]
I feel into the same problem than @madonzy.

By looking at the indexing process, it seems like it does not consider the default tax destination at all.

Magento's `catalog_product_index_price` table prices does not contain the tax when the catalog admin price is set as `Excluding Tax` (which is the default and most sane way of setting a price).

So when the catalog product listing is set to show the price including tax based on the default tax destination, the price range is showing the price without the tax and the catalog the price with the tax.
