### ISSUE TITLE
Missing products from category after upgrade to 2.3.10

### ISSUE THREAD

**Issue by srenon** [Smile-SA/elasticsuite#572]
### Preconditions

Magento Version : 2.1.9

ElasticSuite Version : 2.3.10

Please take a look at my comment on https://github.com/Smile-SA/elasticsuite/pull/567

This code will remove any product that does not have a status. Before upgrading, I have 5 products after upgrading I have only one showing up.

          foreach ($childrenIndexData as $childrenId => $childrenData) {
                $enabled = isset($childrenData['status']) && current($childrenData['status']) == 1;
                if ($enabled === false) {
                    unset($childrenIndexData[$childrenId]);
                }
            }

**Comment by afoucret** [comment]
Since 2.3.8, we decided that all composite products with no active simple children should not be indexed.

Can you please check that the missing products : 
1. Are composite (configurable, grouped or bundle)
2. Have no active simple children (I suspect this happen because of one of your previous post)

In this case it does not make sense to display them and the behavior is expected.

**Comment by srenon** [comment]
I created a new product in our existing store and also an in a fresh test installation (same exact product setup and version)

Existing store print_r(childrenData)
```
Array
(
    [product_size] => Array
        (
            [0] => 573
        )

    [option_text_product_size] => Array
        (
            [0] => L
        )

    [name] => Array
        (
            [0] => Product 1
        )

)
```


fresh test installation store
```
Array
(
    [name] => Array
        (
            [0] => Test product-Gray
        )

    [color] => Array
        (
            [0] => 52
        )

    [option_text_color] => Array
        (
            [0] => Gray
        )

    [status] => Array
        (
            [0] => 1
        )

    [option_text_status] => Array
        (
            [0] => Enabled
        )

    [tax_class_id] => Array
        (
            [0] => 2
        )

    [option_text_tax_class_id] => Array
        (
            [0] => Taxable Goods
        )

)
```

**Comment by afoucret** [comment]
Your first example product does not have a status. For me it is equivalent to being disabled.
So I think the behavior is the expected one.

**Comment by srenon** [comment]
Since I'm at least the second person with this issue (https://github.com/Smile-SA/elasticsuite/issues/565), could we check to see if the key exist and if so do new the logic else do nothing?

**Comment by srenon** [comment]
I have zero configurable showing on the site after upgrading from 2.3.5  and they should be over 500+

**Comment by afoucret** [comment]
I think it would be better to fix the problem at source : status is a mandatory field for products. Having it missing can lead to other problems elsewhere in your Magento install or with other extensions.

**Comment by srenon** [comment]
@afoucret 

The issue is caused by someone changing the default "Use in Search" from "yes" to "no"

![image](https://user-images.githubusercontent.com/1415141/31787927-2b8e5f7c-b4db-11e7-98e9-e201bbf14694.png)


```
SELECT `main_table`.`entity_type_id`, `main_table`.`attribute_code`, `main_table`.`attribute_model`, `main_table`.`backend_model`, `main_table`.`backend_type`, `main_table`.`backend_table`, `main_table`.`frontend_model`, `main_table`.`frontend_input`, `main_table`.`frontend_label`, `main_table`.`frontend_class`, `main_table`.`source_model`, `main_table`.`is_required`, `main_table`.`is_user_defined`, `main_table`.`default_value`, `main_table`.`is_unique`, `main_table`.`note`, `additional_table`.* FROM `eav_attribute` AS `main_table`
 INNER JOIN `catalog_eav_attribute` AS `additional_table` ON additional_table.attribute_id = main_table.attribute_id WHERE (main_table.entity_type_id = 4) AND (is_searchable = 1 OR is_visible_in_advanced_search = 1 OR is_filterable > 0 OR is_filterable_in_search = 1 OR is_used_for_promo_rules = 1 OR used_for_sort_by = 1) AND (is_searchable = 1 OR is_visible_in_advanced_search = 1 OR is_filterable > 0 OR is_filterable_in_search = 1 OR is_used_for_promo_rules = 1 OR used_for_sort_by = 1) AND (is_searchable = 1 OR is_visible_in_advanced_search = 1 OR is_filterable > 0 OR is_filterable_in_search = 1 OR is_used_for_promo_rules = 1 OR used_for_sort_by = 1) AND (is_searchable = 1 OR is_visible_in_advanced_search = 1 OR is_filterable > 0 OR is_filterable_in_search = 1 OR is_used_for_promo_rules = 1 OR used_for_sort_by = 1)
```
