### ISSUE TITLE
Can't override category layer filter

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#573]
Why I'm not able to override category filter model **Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category** ?
Are there some special requirements? I was trying to use `<preference />` and:
```
<virtualType name="Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category" type="Test\ElasticsuiteCatalog\Model\Layer\Filter\Category">
    <arguments>
        <argument name="filterItemFactory" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Layer\Filter\Item\CategoryFactory</argument>
    </arguments>
</virtualType>
```
as well. But it still not loading...

### Preconditions

Magento Version : 2.1.9

ElasticSuite Version : 2.3.8

Environment : Developer

Third party modules : -

**Comment by afoucret** [comment]
If the virtual category module is enabled, this implementation is not used as you can see in `module-elasticsuite-virtual-category/etc/frontend/di.xml`  :

```
<virtualType name="searchFilterList" type="Smile\ElasticsuiteCatalog\Model\Layer\FilterList">
        <arguments>
            <argument name="filters" xsi:type="array">
                <item name="category" xsi:type="string">Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category</item>
            </argument>
        </arguments>
    </virtualType>
```

You can override by doing the same in your own module.
You should extends `Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category` instead of `Smile\ElasticsuiteCatalog\Model\Layer\Filter\Category` if you want to keep the virtual category feature working.

**Comment by madonzy** [comment]
@afoucret I did as you said:
1) Extend my own class from **\Smile\ElasticsuiteVirtualCategory\Model\Layer\Filter\Category**
2) di.xml:
```
<virtualType name="searchFilterList" type="Smile\ElasticsuiteCatalog\Model\Layer\FilterList">
    <arguments>
        <argument name="filters" xsi:type="array">
            <item name="category" xsi:type="string">Test\ElasticsuiteCatalog\Model\Layer\Filter\Category</item>
        </argument>
    </arguments>
</virtualType>
```

Still, doesn't work...
Module enabled, cache cleaned.

**Comment by madonzy** [comment]
Ok, I also override virtual type:
```
<virtualType name="categoryFilterUsingRewrite" type="Test\ElasticsuiteCatalog\Model\Layer\Filter\Category">
    <arguments>
        <argument name="useUrlRewrites" xsi:type="boolean">true</argument>
    </arguments>
</virtualType>
```
and now it works.

**Comment by sambolek** [comment]
Commenting on this closed issue for future reference:

you should be able to override virtualTypes with `<preference>` handle, but your module should be dependant on the module you're trying to override (i.e. having `<sequence>` defined correctly in your module.xml)
