### ISSUE TITLE
Is it possible to run 2-4 threads/forks for Catalogsearch_fulltext reindex?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#574]
I have many idle cores, is it possible to rig up a way to run multiple threads to index?  Perhaps a simple interface via CLI to split the jobs into begin-wait,part1,part2,part3,part-4 and end-last-wait partition of full index.

It seems full reindex of 2M+ parts takes almost 2 hours with much idle cpu,i/o left on the table.

Any thoughts on how to approach a CLI method to re-index faster?

**Comment by afoucret** [comment]
No plan for developing such a feature even if it would be very valuable for huge catalog.
You can propose a PR if interested.

**Comment by romainruaud** [comment]
This is not exactly what you want @southerncomputer , but since Magento 2.2.5 the catalogsearch_fulltext indexer can be run on parallel mode for store views : 

https://devdocs.magento.com/guides/v2.2/config-guide/cli/config-cli-subcommands-index.html#config-cli-subcommands-index-reindex-parallel

**Comment by afoucret** [comment]
As said, we do note plan such a feature.
Magento added some improvement that allow parrallel indexing for several store.

I close this issue.
