### ISSUE TITLE
No result with several stores

### ISSUE THREAD

**Issue by pravalitera** [Smile-SA/elasticsuite#575]
Magento Version : 2.1.7
ElasticSuite Version : 2.3
Environment : Both

### Steps to reproduce
1. Have multiple stores, with exactly the same datas on all products.
2. Do a search by sku

### Expected result
1. Same result on all stores

### Actual result

1. Result are ok store_id = 1 , but on others, sometimes, not the same result...
2. when i force the index name on the first store, it works.
3. there is exactly the same number of documents on each index...

Does anyone has a clue ?

**Comment by afoucret** [comment]
Can you please check the missing product are present in catalog_product_website for the current website ?

**Comment by pravalitera** [comment]
I have only one website.
It's clearly Elasticsearch that respond no documents: 
when i do a var_dump of $docIds in 
_Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection_ _renderFiltersBefore_ , there is 0 for my other stores.

I installed a gui on my elasticsearch server, as i said: exactly the same number of documents.

![2017-10-19 15_04_30-elasticsearch gui](https://user-images.githubusercontent.com/16425832/31772149-fb62e45e-b4de-11e7-9c6f-f6085528e1c1.png)


When i manually change the "index" in the doSearch function, forcing it to the one of store 1, it works.

So i don't know... maybe the the documents that are in Elastic are not good... But when i do a search by sky in the GUI, it works on all index...

**Comment by pravalitera** [comment]
Another weird things i noted: when i enter a SKU, sometimes, it does not find it... And the result proposed is _"No exact results found for: 'CBLT91391530'. The displayed items are the closest matches."_  :(

**Comment by romainruaud** [comment]
I close this one due to being inactive for too long, not reproductible (so probably strongly linked to user custom data), and also due to the fact we introduced better relevance for SKU search in 2.4.

Feel free to open a new issue if you are still facing this bug with 2.4 version.
