### ISSUE TITLE
Magento 2.2 Compatiblity

### ISSUE THREAD

**Issue by EliasKotlyar** [Smile-SA/elasticsuite#576]
### Preconditions
Have a working Magento 2.2 Installation . 

Magento Version : CE and EE

ElasticSuite Version : 2.3 / 2.4

Environment : Developer / Production

Third party modules : No

### Steps to reproduce
Install into Magento 2.2
Start compiling process using /bin/magento setup:di:compile

### Expected result
You can compile your di
                                                               

### Actual result
Proxies code generation... 1/7 [====>-----------------------]  14% 2 secs 70.0 MiB
Repositories code generation... 1/7 [====>-----------------------]  14% 2 secs 70.0 MiB
Repositories code generation... 2/7 [========>-------------------]  28% 48 secs 246.0 MiB
Service data attributes generation... 2/7 [========>-------------------]  28% 48 secs 246.0 MiB
Service data attributes generation... 3/7 [============>---------------]  42% 48 secs 246.0 MiB
Application code generator... 3/7 [============>---------------]  42% 48 secs 246.0 MiB
Application code generator... 4/7 [================>-----------]  57% 1 min 266.0 MiB
Interceptors generation... 4/7 [================>-----------]  57% 1 min 266.0 MiB
Interceptors generation... 5/7 [====================>-------]  71% 2 mins 304.0 MiB
Area configuration aggregation... 5/7 [====================>-------]  71% 2 mins 304.0 MiB
                                                               
  [ReflectionException]                                        
  Class Magento\Framework\App\Config\ScopePool does not exist

**Comment by afoucret** [comment]
The fix have been pushed on branches master, 2.3.x and 2.4.x.

Thx for reporting and PR.
