### ISSUE TITLE
Manage facets by category.

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#587]
New feature : ability to manage facets by category.

For each category, display a list of all filterable attributes (not filterable in search for now).

The list contains the following data for each attribute : 

- **Sort Order** (implicit, the list is drag-n-droppable)
- **Attribute Name** (just the label)
- **A selector** to choose between 3 display mode. It contains 3 values : 
    - **Auto** : let the engine do the job, via the "facet coverage"
    - **Yes** : the attribute is displayed in any case, even if facet coverage is not reached.
    - **No** : the attribute is never displayed for this category.

**Comment by afoucret** [comment]
Hi @romainruaud 

A prototype of the UI I want in : https://github.com/afoucret/elasticsuite/tree/facet-category-config

This code need a lot of cleaning and a proper management of the drag and drop and additional fields (coverage rate, sort order and facet size).

I let you finish the work based on this.

**Comment by romainruaud** [comment]
acknowledged @afoucret 

What about hide/show of the attributes considered as irrelevant ? This was nice for UX especially with a huge diversity of universes in the catalog.

**Comment by afoucret** [comment]
Start with implementing without this feature. It would be added after.

**Comment by afoucret** [comment]
Feature is now in the master branch and will be released with version 2.5.0
