### ISSUE TITLE
Manual sort order of products in search results

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#588]
For each "Search Term" in the Back-Office : 

Ability to : 
- **preview the results**
- **assign a sort order** to each product in the result list (probably via a **drag-n-drop**).

**Comment by afoucret** [comment]
Merged in master.
Will be released with 2.5.0.

Feature can be accessed in search term detail by clicking on the **Merchandiser** button in the toolbar : 

<img width="1544" alt="capture d ecran 2018-01-24 a 16 02 10" src="https://user-images.githubusercontent.com/529238/35339265-6f9e8412-0120-11e8-9154-82d6b204e57d.png">


In the future, this feature will be accessible from search usage report #589.
