### ISSUE TITLE
Wiki mistake (module enable command)

### ISSUE THREAD

**Issue by dubromev** [Smile-SA/elasticsuite#59]
Hi,
There's a mistake in the wiki, at page 'ModuleInstall'

Command line :
`bin/magento module:enable Smile_ElasticSuiteCore Smile_ElasticSuiteCatalog Smile_ElasticSuiteSwatches Smile_ElasticSuiteCatalogRule Smile_ElasticSuiteVirtualCategory Smile_ElasticSuiteThesaurus Smile_ElasticSuiteTracker`

must be :
`bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteTracker`

**Comment by afoucret** [comment]
You are right.

We will fix it ASAP.

Thx for reporting.

**Comment by romainruaud** [comment]
Done on my wiki fork. Please merge it @afoucret .

**Comment by afoucret** [comment]
Done. I close the issue.
