### ISSUE TITLE
Feature : Virtual Attributes

### ISSUE THREAD

**Issue by romainruaud** [Smile-SA/elasticsuite#590]
New feature, Virtual Attributes : 

for a given product attribute, being able to create **values based on rules**.

**Comment by romainruaud** [comment]
Discarded from Open Source version.

**Comment by torhoehn** [comment]
@romainruaud What does "Discarded from Open Source version" mean? Is there any other version to get this feature?

It was mentioned here, to get a nicer implementation for sorting by newest products: https://github.com/Smile-SA/elasticsuite/issues/1289#issuecomment-466418963
