### ISSUE TITLE
PHP version (5.6.32) does not satisfy that requirement

### ISSUE THREAD

**Issue by ashokdubariya** [Smile-SA/elasticsuite#596]
We have tried to install Smile Elastic Suite module on our dev site and we are getting below error.

`magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (5.6.32) does not satisfy that requirement.`

This error is related to PHP version does not satisfy, but we are using `PHP Version 7.0.25`

**Magento Version:** 2.2

**ElasticSuite Version:** 2.3

**Magento Environment:** Production mode

**Third party modules:** We are not using any third party modules.

Can you please let us know what is the solution for that error?

Thanks
Ashok Dubariya

**Comment by romainruaud** [comment]
Two things : 

- if composer says you are using php 5.6.32, you are probably. Please ensure which php version you run by typing ```php -v```

- you'd better use Elasticsuite 2.4.x branch with Magento 2.2.

Regards

**Comment by ashokdubariya** [comment]
Hi romainruaud

Thanks for your reply.

We have checked with command `php -v` and it's showing us PHP version 7.0.25. Please check below.

`ea-php-cli Copyright 2017 cPanel, Inc.`
`PHP 7.0.25 (cli) (built: Oct 30 2017 18:01:25) ( NTS )`
`Copyright (c) 1997-2017 The PHP Group`
`Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`

Also we have tried to install Elasticsuite 2.4.x branch with Magento 2.2 but it's generating same error like below.

`magento/framework 101.0.0 requires php 7.0.2|7.0.4|~7.0.6|~7.1.0 -> your PHP version (5.6.32) does not satisfy that requirement`

Thanks
Ashok Dubariya
