### ISSUE TITLE
Attribute faceting

### ISSUE THREAD

**Issue by delyriand** [Smile-SA/elasticsuite#60]
For example, we have a color attribute and a base color attribute. The configurable products are decline by color (& size). But for customer experience, we need to be able to filter based on "base" color.

But, the displayed base colors are from the configurable product (instead of simple product).
We use a visual swatch for color base attribute and we are obliged to select a color for configurable product. 

---- 

**MyConfigurable**
Color base - white

**MyFirstSimple**
Color - white
Color base - white

**MySecondSimple**
Color - crimson
Color base - Red

**MyThirdSimple**
Color - cherry red
Color base - Red

We have only **white** value in color base facet.

**Comment by afoucret** [comment]
The PR #64 has been rejected but the PR #65 fix this one and is merged into the master.

@delyriand can you test it from the master.

**Comment by delyriand** [comment]
@afoucret It's ok. Your fix works fine.
