### ISSUE TITLE
Possibility to search products by category name

### ISSUE THREAD

**Issue by reviskar** [Smile-SA/elasticsuite#603]
### Preconditions

Magento Version : 2.0.19 CE // EDIT: actual version is 2.1.9 CE

ElasticSuite Version : @latest

Environment : Prod/Dev

Third party modules : Endless amount but nothing in this regard

### Steps to reproduce

1. Enter a category name or a string %like% category name in the search tab
2. Hit search

### Expected result

1. List of products found that are assigned to categories that are found with the search query

### Actual result

1. Category name is not included in the search

For example I have products in the category "medicine", so when someone executes the search query (not autocomplete) for the string "medicine", it should show all the products in the category "medicine" in addition to the normal search results (i.e. "Medicine ball"). 

Sorry, if this is not in the most correct way for asking help, but I'm having massive trouble implementing this. We have n+1 products in n+1 categories that change n+1 times every day - so manually assigning let's say "category_cache" product attribute and listing available categories there as a csv is not really plausible. 

The way I can get it to work is to call the product search by category name in the search list phtml file and append the results to the `$productCollection` there, but this is basically just a nasty hack because no filters will be able to work correctly after this.

Could someone point me to the right direction where I could add my extra filters? Maybe create a virtual product_attribute while indexing? 

Thanks in advance!

**Comment by afoucret** [comment]
Hi @reviskar,

As you are using an old version of Magento (2.0.19), I do not think you are using the last version of ElasticSuite (which requires Magento > 2.1. To help us we really need the exact ElasticSuite version you are currently using.

The search in category name is a standard feature of ElasticSuite. BUT there is one exception, we can not search in the virtual categories name. Maybe your category is virtual.

BR,

**Comment by reviskar** [comment]
Hey, thanks for your response. 
I've indeed gotten the magento version mixed up a little. Magento version is 2.1.9, not 2.0.19 :).

**Comment by reviskar** [comment]
Ok, now I feel stupid now.
Yeah, as @afoucret pointed out, this already works out of the box. It was the way I tested it that made me think it's not working. Anyway, when I search for "medicin" term, the products in the "medicine" category do not show up. So I guess I'm now asking whether it's possible not to enforce an exact match here ("medicine" term when category is "Medic supplies and medicines" for example).  But yeah, this ticket in this form is probably not relevant any more.

**Comment by afoucret** [comment]
You should consider using a synonym though the thesaurus feature.

I close the issue.

**Comment by reviskar** [comment]
Yep, I'll try that. Thanks very much for the fast response!
