### ISSUE TITLE
Compile fails with 2.4 - Incompatible argument type

### ISSUE THREAD

**Issue by edmund** [Smile-SA/elasticsuite#614]
### Preconditions
Magento Version : 2.2.1 CE
ElasticSuite Version : 2.4.0
Environment : Developer
Third party modules : None (clean install)
OS: Ubuntu 17.10
PHP: PHP 7.1.8-1ubuntu1

### Steps to reproduce
1. Install Magento with composer - `composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ...`
2. Do a basic install - `bin/magento setup:install --base-url= ...`
3. Install ElasticSuite - `composer require smile/elasticsuite ^2.4.0`
4. `bin/magento setup:upgrade` - works fine
5. `bin/magento setup:di:compile` - boom!

### Expected result
Compile step should complete as normal and look like this:
```
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 12 secs 244.0 MiB
Generated code and dependency injection configuration successfully.
```
### Actual result
Compile step does this:
```
Compilation was started.
Interception cache generation... 6/7 [========================>---]  85% 11 secs 252.0 MiBErrors during compilation:
	Smile\ElasticsuiteCatalog\Helper\CategoryAttribute
		Incompatible argument type: Required type: string. Actual type: \Magento\Catalog\Model\ResourceModel\Category\Attribute\CollectionFactory; File: 
/var/www/test/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/CategoryAttribute.php

	Smile\ElasticsuiteCatalog\Helper\ProductAttribute
		Incompatible argument type: Required type: string. Actual type: \Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory; File: 
/var/www/test/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Helper/ProductAttribute.php

Total Errors Count: 2

                                           
  [Magento\Framework\Validator\Exception]  
  Error during compilation                                       
```

2.3.10 works perfectly.  Tried cleaning cache etc., no difference.

Probably not relevant, but I did notice a notice in the `bin\magento setup:upgrade` step:
```
Module 'Smile_ElasticsuiteCatalog':
Installing data... Notice: Undefined offset: 1 in /var/www/test/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/ClientFactory.php on line 95
```

**Comment by afoucret** [comment]
PR #615 will fix this one.

DI was working on Magento 2.2.0 and is broken in 2.2.1. The reason is : DI compilation now take care about comment in constructor. A bad type was specified in one of our comment.

Now DI is working.

I will merge this today and we will release a bugfix version of ElasticSuite (2.4.1).

Thx for reporting.

**Comment by afoucret** [comment]
PR have been merged.

**Comment by JVKeller** [comment]
I have a related issue. I just tried installing on Magento 2.2.

During setup:upgrade...

Notice: Undefined offset: 1 in /home/motoheaven/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/ClientFactory.php on line 95
