### ISSUE TITLE
Search pages or other models

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#617]
Hi,

I was looking for a way to also search through pages and other modes/tables. Is this supported by the module or otherwise optional to build.

**Comment by romainruaud** [comment]
@rikwillems please have a look into the "Indexing Content" part of the developer's guide.

This part of the documentation is still a work in progress but it might be helpful for you to extend the module to fit your needs.

https://github.com/Smile-SA/elasticsuite/wiki/Indexing

Obviously, this does require knowledge about Elasticsearch and of course Magento.

For specific CMS pages case, we already have this module : https://github.com/Smile-SA/magento2-module-elasticsuite-cms-search

Regards

**Comment by rikwillems** [comment]
Dear @romainruaud , thank you for pointing me to the CMS search module. That is exactly the example I need. I missed this in my own search.
