### ISSUE TITLE
Bad error message in facet values search

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#618]
See below : little problem with the error message.

![capture d ecran 2017-11-15 a 16 09 09](https://user-images.githubusercontent.com/20048184/32843217-7a91d14a-ca1f-11e7-8cda-1d27a4e98de0.png)

**Comment by afoucret** [comment]
PR have been merged in branches 2.4.x and master. It will be part of the next bugfix release (2.4.2).

Thx,
