### ISSUE TITLE
reverse sort order and "missing"

### ISSUE THREAD

**Issue by TonyDeplanque** [Smile-SA/elasticsuite#62]
It should be possible to reverse the sort order and the "missing" located in module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/SortOrder/Builder.php

**Comment by romainruaud** [comment]
Hello @TonyDeplanque and sorry for the delay, I'm not sure I'm understanding your issue properly.

What do you mean by "reversing" ?

Regards

**Comment by romainruaud** [comment]
I close the issue due to one week without any response.

@TonyDeplanque feel free to reopen it if needed.
