### ISSUE TITLE
Update to 2.3.11 (Magento 2.1.8)

### ISSUE THREAD

**Issue by inelukipg** [Smile-SA/elasticsuite#633]
Hi,
I'm not so familiar with composer:
But could I run: 
`composer update smile/elasticsuite ^2.3.0`

to update to the latest 2.3.x version?

Current insatlled version is 2.2.10.

**Comment by romainruaud** [comment]
You'd rather do `composer require smile/elasticsuite ^2.3.0` which should do what you need.

best regards

**Comment by inelukipg** [comment]
Ok thank you!
I meant current installed version is 2.3.10. 

But I usually do `composer update` when updating my modules. What's the different?

**Comment by romainruaud** [comment]
If you have a requirement to "^2.3.0" in your composer.json, and the currently installed version is 2.3.10, it will automatically detect there is a new 2.3.11 published when you run composer update.

If you want to use a 2.4.x version, just do a composer require ^2.4.0 and it will automatically install any of newly published 2.4.* version when you run composer update.

Please have a look to composer documentation about this : https://getcomposer.org/doc/01-basic-usage.md#package-version-constraints

**Comment by inelukipg** [comment]
Ok thanks! I think I understand.. :)
