### ISSUE TITLE
JavaScript error when hiting enter before autocomplete loads

### ISSUE THREAD

**Issue by krzksz** [Smile-SA/elasticsuite#634]
### Preconditions

Magento Version: 2.2.0 but all are probably affected.

ElasticSuite Version: 2.3.0 but all versions are probably affected.

Environment: All modes are affected.

### Steps to reproduce

1. Go to any shop with elasticsuite search extension installed e.g. on the demo: http://demo.magento-elastic-suite.io/. 
2. Type any search string into mini search form.
3. Quickly hit enter key before autosuggestion items appear.

### Expected result

1. User should be redirected to search results page for given query string.

### Actual result

1. `TypeError: this.responseList.selected is null` or similar depending on browser is thrown in the console originating from this line: https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/view/frontend/web/js/form-mini.js#L359

Above error is due to `this.responseList.selected` being null until autosuggestion results are loaded. The solution is to check if `this.responseList.selected` is truthy before accessing `.attr('href')` method.

I will create a pull request with fix for this in the nearest hours.

**Comment by romainruaud** [comment]
Hello @krzksz and thank you for submitting this issue.

We really appreciate your effort to publish a PR fixing this one.

Thank you again for the interest you are showing to our module.

Regards
