### ISSUE TITLE
Freeze click

### ISSUE THREAD

**Issue by digiwebpro** [Smile-SA/elasticsuite#643]
Hi there!
If i put text to search input and don't choose anything, when I click off it, it will not allow me to click in the search again, it freeze.
I can only refresh page..
How can i fix that?

**Comment by romainruaud** [comment]
Hello @digiwebpro 

I'm not sure I understand properly your issue.

I tried to replicate it on our demo server http://demo.magento-elastic-suite.io/ but I do not reproduce it.

Which web browser do you use ? And which version ? Do you see any error in console ?

Regards

**Comment by afoucret** [comment]
Closed for being inactive for too long and not reproduced.
Maybe related with #657.
