### ISSUE TITLE
Product List Widget Is Not Working

### ISSUE THREAD

**Issue by varun-jyothi** [Smile-SA/elasticsuite#644]
I have installed a landing page module [https://amasty.com/landing-pages-for-magento-2.html](url) to our Magento 2 web site. However when I access a landing page, it throws the exception "Index provider not configured"
### Preconditions

Magento Version : Magento CE 2.1.10

ElasticSuite Version : 2.3.11

Environment : Developer

Third party modules : Amasty Xlanding

### Steps to reproduce

1. Create a landing page in "Landing Page" section
2. Give some condition like "SKU is G200, G500" etc
3. Save and access this page in front-end

### Expected result

1. The page will load and we can see a listing page

### Actual result

1. [Screenshot, logs]
Throwing exception "Index provider not configured"

`a:4:{i:0;s:29:"Index provider not configured";i:1;s:7018:"#0 /var/www/youapparel.com/vendor/magento/framework/Search/Adapter/Mysql/Adapter.php(83): Magento\Framework\Search\Adapter\Mysql\Mapper->buildQuery(Object(Smile\ElasticsuiteCore\Search\Request)) #1 /var/www/youapparel.com/vendor/amasty/xlanding/Plugin/SearchEnginePlugin.php(52): Magento\Framework\Search\Adapter\Mysql\Adapter->query(Object(Smile\ElasticsuiteCore\Search\Request)) #2 /var/www/youapparel.com/vendor/magento/framework/Interception/Interceptor.php(142): Amasty\Xlanding\Plugin\SearchEnginePlugin->aroundSearch(Object(Magento\Search\Model\SearchEngine\Interceptor), Object(Closure), Object(Smile\ElasticsuiteCore\Search\Request)) #3 /var/www/youapparel.com/var/generation/Magento/Search/Model/SearchEngine/Interceptor.php(26): Magento\Search\Model\SearchEngine\Interceptor->___callPlugins('search', Array, Array) #4 /var/www/youapparel.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(586): Magento\Search\Model\SearchEngine\Interceptor->search(Object(Smile\ElasticsuiteCore\Search\Request)) #5 /var/www/youapparel.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(189): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->loadProductCounts() #6 /var/www/youapparel.com/vendor/magento/framework/Data/Collection.php(259): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->getSize() #7 /var/www/youapparel.com/vendor/magento/framework/Data/Collection.php(245): Magento\Framework\Data\Collection->getLastPageNumber() #8 /var/www/youapparel.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(484): Magento\Framework\Data\Collection->getCurPage() #9 /var/www/youapparel.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(393): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->prepareRequest() #10 /var/www/youapparel.com/vendor/magento/framework/Data/Collection/AbstractDb.php(338): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFiltersBefore() #11 /var/www/youapparel.com/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(430): Magento\Framework\Data\Collection\AbstractDb->_renderFilters() #12 /var/www/youapparel.com/vendor/magento/module-eav/Model/Entity/Collection/AbstractCollection.php(906): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFilters() #13 /var/www/youapparel.com/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php(727): Magento\Eav\Model\Entity\Collection\AbstractCollection->load(false, false) #14 /var/www/youapparel.com/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Catalog\Model\ResourceModel\Product\Collection->load(false, false) #15 /var/www/youapparel.com/var/generation/Faya/ElasticSearch/Model/ResourceModel/Product/Fulltext/Collection/Interceptor.php(26): Faya\ElasticSearch\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->___callPlugins('load', Array, Array) #16 /var/www/youapparel.com/vendor/magento/framework/Data/Collection.php(820): Faya\ElasticSearch\Model\ResourceModel\Product\Fulltext\Collection\Interceptor->load() #17 /var/www/youapparel.com/vendor/magento/module-catalog/Block/Product/ListProduct.php(321): Magento\Framework\Data\Collection->getIterator() #18 /var/www/youapparel.com/vendor/magento/module-page-cache/Model/Layout/LayoutPlugin.php(71): Magento\Catalog\Block\Product\ListProduct->getIdentities() #19 /var/www/youapparel.com/vendor/magento/framework/Interception/Interceptor.php(152): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), '`

**Comment by afoucret** [comment]
We do not provide support for third party module as part of our Open Source community support, especially if the module is a commercial one.

It can be part of our commercial support for ElasticSuite. You can send me an email at aurelien.foucret@smile.fr if interested in a commercial support on this one.

**Comment by ngtuan96lc** [comment]
Hi @afoucret 
I have the same problem. When switching back from elasticsearh to mysql -> go to Catalog Listing page. I recived an error : 
1 exception(s):
Exception #0 (LogicException): Index provider not configured
<pre>#1 Magento\Framework\Search\Adapter\Mysql\Adapter->query() called at [vendor/magento/module-search/Model/SearchEngine.php:42]
#2 Magento\Search\Model\SearchEngine->search() called at [vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Search/Request/Product/Coverage/Provider.php:106]
...
Please help me fix it. I am using magento 2.3 EE.
