### ISSUE TITLE
Duplicate searchresults 

### ISSUE THREAD

**Issue by shekharS7** [Smile-SA/elasticsuite#646]
### Preconditions

Magento Version :2.1.0

ElasticSuite Version :2.4.5

Environment : Developer

Third party modules : Emthemes

### Steps to reproduce

1.
2.
3.

### Expected result

1.Searchresults with individuals products

### Actual result

1. Searchresults with duplicates products: same product comming twice

**Comment by romainruaud** [comment]
Hello @shekharS7 

This one is not enough qualified for us.

Please provide a detailed scenario, and do not hesitate to include screenshots illustrating your issue.

Regards
