### ISSUE TITLE
How about enabling index.codec DEFLATE ?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#650]
index.codec
The default value compresses stored data with LZ4 compression, but this can be set to best_compression which uses DEFLATE for a higher compression ratio, at the expense of slower stored fields performance. If you are updating the compression type, the new one will be applied after segments are merged. Segment merging can be forced using force merge.

I wonder what kind of storage savings we'd see with this option?

https://www.elastic.co/blog/elasticsearch-storage-the-true-story-2.0

**Comment by afoucret** [comment]
We did not evaluate this option.
Do you have any speed (indexing and query) and index size benchmarks on your setup (I know it is a quite big catalog).

**Comment by southerncomputer** [comment]
15% saved - i have 48 cores and 128gb  of  ram - time to full reindex 2m products 1h:45m - 15% * 2 is  a good bit of SSD that costs a lot more than cpu/ram ..

**Comment by afoucret** [comment]
PR #663 use the best_compression for indices created with ElasticSuite.

Will be part of the next stable release (2.5.0).
