### ISSUE TITLE
Product name not suggesting in autocomplete

### ISSUE THREAD

**Issue by surajiiitm** [Smile-SA/elasticsuite#653]
<! Product suggestion not being shown as auto complete in search bar ->

### Preconditions
Magento Version : 2.1.7 CE

ElasticSuite Version : 2.4

Environment : Developer

Third party modules :  
Emthemes_Flyingcart
Emthemes_Blog
Mageplaza_Sociallogin 

### Steps to reproduce
1. Type in search bar any product name or brand or first word
2. displays nothing
3. but spelling mistakes will produce result

### Expected result
1. should give suggestions for correct spellings also

### Actual result
 1. No result diplayed for the correct object name typed
![screenshot from 2017-12-07 17-33-47](https://user-images.githubusercontent.com/13780601/33716699-22a2c9ac-db7d-11e7-9b30-34f35e0a3373.png)

![screenshot from 2017-12-07 17-34-07](https://user-images.githubusercontent.com/13780601/33716700-22dd4456-db7d-11e7-8a8e-267f4f98895e.png)

**Comment by surajiiitm** [comment]
But if we type products instead of product, it is displaying the result.

**Comment by romainruaud** [comment]
This one is kinda strange, is there any error on the Ajax request which is sent the first time, when you type just "plywood" ?

**Comment by surajiiitm** [comment]
plywood ajax response are:

0: {…}
--
title | Plywood
num_results | 75
type | term
1 | {…}
title | plywood mr 16mm
num_results | 2
type | term
2 | {…}
type | product
title | Promate Plywood 16MM MR 8 x 4
image | http://xyz.jpg
url | http://xyzmate-16mm-mr.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="11914">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-11914"                data-price-amount="1576"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹1,576.00</span>    </span>         </span>  </div>
3 | {…}
type | product
title | Kitply Plywood 16MM KIT 2000 MR 8 x 4
image | http://bfc89641a4582/8/1/811948029.jpg
url | http://plywood-16mm-kit-2000-mr-8-x-4.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="26925">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-26925"                data-price-amount="2639"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹2,639.00</span>    </span>         </span>  </div>
4 | {…}
type | product
title | Promate Plywood 6MM MR 8 x 4
image | http://beabfc89641a4582/m/r/mr_6mm.jpg
url | http://6mm-mr.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="11915">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-11915"                data-price-amount="956"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹956.00</span>    </span>         </span>  </div>
5 | {…}
type | category
title | Plywood
url | http://shop/boards/plywood.html

**plywoods (not exact matching word but right suggestions)**
Ajax response:\

0: {…}
--
type | product
title | Century Sainik Plywood 19MM BWR 8 x 4 Brown
image | http://2/8/1/811948212.jpg
url | http://plywood-19mm-bwr-8-x-4-brown.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="26949">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-26949"                data-price-amount="4033"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹4,033.00</span>    </span>         </span>  </div>
1 | {…}
type | product
title | Century Sainik Plywood 16MM BWR 8 x 4 Brown
image | http://45x45/beff4985b56e3afdbeabfc89641a4582/8/1/811948211.jpg
url | http://8-x-4-brown.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="26948">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-26948"                data-price-amount="3601"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹3,601.00</span>    </span>         </span>  </div>
2 | {…}
type | product
title | Century Sainik Plywood 12MM BWR 8 x 4 Brown
image | http://a4582/8/1/811948209.jpg
url | http://inik-plywood-12mm-bwr-8-x-4-brown.html
price | <div class="price-box price-final_price" data-role="priceBox" data-product-id="26947">       <span class="price-container price-final_price tax weee"         >         <span  id="product-price-26947"                data-price-amount="2845"         data-price-type="finalPrice"         class="price-wrapper "         >         <span class="price">₹2,845.00</span>    </span>         </span>  </div>
3 | {…}
type | category
title | Plywood
url | http://xsatyfdsas.boards/plywood.html

From the above Ajax request, we get difference between two response that where type term is not present in spell mistake keyword but displays the result but this doesn't happen in right keyword(plywood) as we got term in response and autocomplete result is not being displayed.

**Comment by shekharS7** [comment]
Required to change in following files..
1)elasticsuite-core/Model/Autocomplete/Terms/DataProvider.php
L105-L109
  $resultItem = $this->itemFactory->create([
                        'title' => $item->getQueryText(),
                        'num_results' => $item->getNumResults(),
                        'type'        => $this->getType(),
                    ]);
2)elasticsuite-core/etc/frontend/di.xml : add below code in config
<type name="Smile\ElasticsuiteCore\Block\Search\Form\Autocomplete">
        <arguments>
            <argument name="rendererList" xsi:type="array">
                <item name="term" xsi:type="array">
                    <item name="title" xsi:type="string" translate="true">Search Terms</item>
                <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item> 
                </item>
            </argument>
        </arguments>
    </type>

**Comment by afoucret** [comment]
Hi @shekharS7 

Can you please issue a PR and explain the reason of your change ?

It will be easier for us to figure what happens there.

**Comment by romainruaud** [comment]
@shekharS7 any update ?

**Comment by afoucret** [comment]
Closed for being inactive for too long
