### ISSUE TITLE
Duplicate element of 'search' with layered navigation autocomplete boxes

### ISSUE THREAD

**Issue by edmund** [Smile-SA/elasticsuite#657]
### Preconditions
Magento Version : 2.2.2 CE
ElasticSuite Version : 2.4.2
Environment : Developer
Third party modules : None (clean install)
OS: Ubuntu 17.10
PHP: 7.1.11-0ubuntu0.17.10.1

### Steps to reproduce
Go to a category with at least one attribute with enough values to bring up an autocomplete box (e.g. material on the sample data.)

### Expected result
There should not be any elements on the page with the same element id.

### Actual result
The layered navigation autocomplete inputs all have the id of 'search', as does the standard search box in the header.  This doesn't seem to cause any problems, but ids are supposed to be unique and Chrome 63 is now eager to remind you of this, logging a warning to the console on every catalogue page.

The id is defined in https://github.com/Smile-SA/elasticsuite/blob/8062b32f9c18fed164d3f47785588f35d765e580/src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html#L3

Everything seems to work without any id being defined, so maybe just remove it?

**Comment by romainruaud** [comment]
Thank you for submitting this one @edmund , and also for using our module.

Not a critical one but we will fix it to remain compliant with HTML standards, and also to prevent erratic behavior for someone willing to manipulate '#search' selector with JS libraries.

**Comment by afoucret** [comment]
PR #659 have been merged in branch 2.4.x and will be part of the next maintenance release (2.4.3)
