### ISSUE TITLE
RFC : Virtual categories : improve product page URL when using category path in product URL

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#66]
Initial conditions:
- In Store/Configuration > Catalog > Catalog, set "Use Categories Path for Product URLs" to "YES"
- Create a virtual category
- Click on a product

--> The URL of the product page is an URL not rewritten, example: https://www.xxxxxxx.eu/uk/catalog/product/view/id/13672/category/643

We would like to improve the URL in this case to have a "clean" URL like this:
http://base_url/virtual-category-name/product-name

**Comment by afoucret** [comment]
We will try to have this feature released in the 2.2.0 or 2.3.0 version.

Thx for reporting.

**Comment by afoucret** [comment]
Regarding the amount of work still remaining in the PR #227, postponing this one to 2.4.x should be considered to have a cleaner implementation ...

**Comment by Koc** [comment]
@afoucret any news on this issue?

**Comment by romainruaud** [comment]
@androshchuk please have a look on this one, probably my old (and unmerged) PR is a good start since it was nearly finished when I wrote it.

Regards

**Comment by romainruaud** [comment]
Closed by associated PR !
