### ISSUE TITLE
Proposal: add class to input or form when searching

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#669]
it would be useful to be able to have a class applied to the input or to the form when the search starts and obviously will be removed once completed, this would allow to assign a different style or an icon to improve the UX

**Comment by afoucret** [comment]
Hi @CRYX2 

I let you propose a PR on this one.

Thx,

**Comment by romainruaud** [comment]
Since you did not propose any PR, I made it by myself.

Regards
