### ISSUE TITLE
Installaton errors...

### ISSUE THREAD

**Issue by JVKeller** [Smile-SA/elasticsuite#672]
Errors during installation of Elastic Suite
### Preconditions 

Apache Version | 2.4.29
PHP Version | 7.0.26
MySQL Version | 10.2.11-MariaDB
Architecture | x86_64
Operating System | linux

Magento Version : 2.2.2 CE

ElasticSuite Version : ^2.4.0

Environment : Production Mode

Third party modules : Venus Theme

### Steps to reproduce

1. Install using composer require smile/elasticsuite ^2.4.0
2. run setup:upgrade
3. receive error 

### Expected result

1. It should install all related files

### Actual result

1. [Screenshot, logs]
During setup:upgrade...

Notice: Undefined offset: 1 in /home/motoheaven/public_html/vendor/smile/elasticsuite/src/module-elasticsuite-core/Client/ClientFactory.php on line 95

snippit:
```
 94        foreach ($clientConfiguration->getServerList() as $host) {
 95          list($hostname, $port) = explode(':', $host);
 96            $currentHostConfig = [
 97                'host'   => $hostname,
 98                'port'   => $port,
 99                'scheme' => $clientConfiguration->getScheme(),
100            ];
```

And during static content deploy:

```
Compilation from source: /home/motoheaven/public_html/vendor/magento/theme-frontend-blank/web/css/styles-m.less
variable @autocomplete-item__border is undefined in file /home/motoheaven/public_html/var/view_preprocessed/pub/static/frontend/Venustheme/freshmarket/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
28| border-bottom: 0;
29| }
30| .lib-css(border-top, @autocomplete-item__border);
31| cursor: default;
32| margin: 0;
33| padding: @indent__xs @indent__xl @indent__xs @indent__s;
Compilation from source: /home/motoheaven/public_html/vendor/magento/theme-frontend-blank/web/css/styles-l.less
variable @autocomplete-item__border is undefined in file /home/motoheaven/public_html/var/view_preprocessed/pub/static/frontend/Venustheme/freshmarket/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
28| border-bottom: 0;
29| }
```

di:compile was successful, but front end would not load.
I tried a few fixes I found in the issuse here with no luck...

Any ideas?!
Thank you.

**Comment by afoucret** [comment]
Hi @JVKeller 

There is 2 very different things here.

1. The problem you have encountered while running `setup:upgrade`.
   Possible reasons are :
   * Running the command without cleaning the caches before
   * Having an invalid ES server address configured. The pattern is "hostname:port"
  The message tends to indicate that you have missed the port in your configuration.

Feel free to reopen if this two indication does not solve your issue.

2. About the missing LESS variable.
    It is due to the fact that you are using a custom theme that did not declare this variable which is a native Magento one (present in blank and luma theme).
   We do not provide support for custom themes (especially commercial one) as part of our community support. You can join me by email  (aurelien.foucret@smile.fr), if interested by some paid support on this one.
