### ISSUE TITLE
smile_elasticsuite_thesaurus_store not updating

### ISSUE THREAD

**Issue by mdroidian** [Smile-SA/elasticsuite#674]
### Preconditions

Magento Version : 2.2.2 EE

ElasticSuite Version : 2.4

Environment : Dev

Third party modules :

### Steps to reproduce

1. Add Synonym or Expansion
2. ElasticSuite Thesaurus Indexing On Save or Schedule

### Expected result

1. smile_elasticsuite_thesaurus_store updates thesaurus_id, store_id
2. search for sysnonym on storefront

### Actual result

1. smile_elasticsuite_thesaurus_store remains blank

Anyone have this issue?  How could we debug it?
If we manually add the thesaurus_id, store_id to smile_elasticsuite_thesaurus_store and reindex ... works as expected.

**Comment by mdroidian** [comment]
Enable Synonyms Search: Yes

**Comment by mdroidian** [comment]
Single Store Mode: On

**Comment by cft-mike** [comment]
Smile\ElasticsuiteThesaurus\Model\ResourceModel\Thesaurus

 private function saveStoreRelation(\Magento\Framework\Model\AbstractModel $object)

$storeIds = $object->getStoreIds(); returns an empty array when single store mode is on
Setting the $storeIds[] = 0 when array is empty fixes this index issue.

Not sure if $storesIds is supposed to return a value when on single store mode, and is part of another issue?

**Comment by romainruaud** [comment]
Confirmed.

Store relation is not stored properly when using single store mode. Should be defaulted in this case.

I will provide a fix for this one to 2.4.x and master version.

Regards, and thank you for reporting it.

**Comment by afoucret** [comment]
PR #676 have been merged in branch 2.4.x.
Will ne part of the next bugfix release.
