### ISSUE TITLE
Unify rendering of facet filters: attributes, swatches

### ISSUE THREAD

**Issue by Koc** [Smile-SA/elasticsuite#675]
### Preconditions

Magento Version : 2.1.11

ElasticSuite Version : 2.3.x

Environment : PHP 7.0.21

Third party modules : -

### Steps to reproduce

1. Create attribute with type `text swatch`
2. Open category view
3.

### Expected result

1. It would be nice reuse existing `Smile_ElasticsuiteCatalog/templates/layer/filter/attribute.phtml` template for rendering swatch attributes

### Actual result

1. This not possible

The only differences that I see for now:

1. `Smile\ElasticsuiteSwatches\Block\Navigation\Renderer\Swatches` does not provide `getFilters()` method (property `filter` exists, but it not has getter
2. template for swatches hasn't `$filterItems` variable

**Comment by Koc** [comment]
The only differences that I see for now:

1. `Smile\ElasticsuiteSwatches\Block\Navigation\Renderer\Swatches` does not provide `getFilters()` method (property `filter` exists, but it not has getter
2. template for swatches hasn't `$filterItems` variable

**Comment by romainruaud** [comment]
Hello @Koc and thank you for this suggestion.

For me, "text swatches" are meant to be used "as is". You could create your attribute as a text attribute if you want it to be displayed with "standard" filters.

But feel free to propose a PR to achieve what you want. For me the PR should only allow to change the filter template by layouting so you could fit your need for text swatches.

Best regards

**Comment by Koc** [comment]
yes, will do it after return from vaccation.

We are using swatches on product view, but prefer checkboxes for facet navigation.

**Comment by afoucret** [comment]
@koc

> We are using swatches on product view, but prefer checkboxes for facet navigation.

Using swatches in facets is a standard in Magento. I don't think changing it in ElasticSuite is a good idea and IMHO, it is a per project decision.

I close this issue since I don't think it can be relevant for ElasticSuite and it is stalled since a while.
