### ISSUE TITLE
VirtualCategories seems to break category indexing

### ISSUE THREAD

**Issue by mtarld** [Smile-SA/elasticsuite#681]
### Preconditions

Magento Version : 2.2.2

ElasticSuite Version : master (2.4.x)

Environment : developer

Third party modules : - 

### Steps to reproduce

1. Install every Smile_Elasticsuite modules except Smile_ElasticsuiteVirtualCategory
2. Navigate on `/women/bottoms-women/shorts-women.html` -> Everything OK
3. Navigate on `/men/tops-men.html` -> Everything OK
4. Install VirtualCategory module `$ magento module:enable Smile_ElasticsuiteVirtualCategory` - `$ magento setup:upgrade`
5. Update `Women>Bottom>Short` category and set some manual sorting then save it
6. Reindex data : `$ magento indexer:reindex`
7. Return on front category pages

### Expected result

1. Categories should have their respective products

### Actual result

1. Each category contains exactly same products in the same order (187 products : every product that is in stock and visible)

Btw, after disabling VirtualCategories module again, each category still contains 187 products but with its "good" order

**Comment by afoucret** [comment]
Hi @mtarld 

I did not reproduce your bug on the latest master version.
But we had this kind of bug few weeks ago while we were refactoring filter display. Be sure you have the latest master deployed or even better the latest stable release (master is not intended to be used in production).

If an update does not solve your issue, I will need to have more information to understand what happen there :
* Store configuration (how many websites, how many store views, ...) ?
* Enable the ES debug mode and try to follow the logs. Maybe there is something inside.
* Describe virtual categories that are set up on your website

BR,

**Comment by mtarld** [comment]
Hi @afoucret 

Thank you for you fast response, I'll try to use the stable version today, I'll let you know !

**Comment by mtarld** [comment]
I've switched to the 2.4.0 version and it still the same.
Here is the body sent to elasticsearch when displaying a category (on front)
```json
{
   "from":0,
   "size":9,
   "sort":[
      {
         "category.position":{
            "order":"asc",
            "missing":"_last",
            "unmapped_type":"string",
            "nested_path":"category",
            "mode":"min",
            "nested_filter":{
               "terms":{
                  "category.category_id":[
                     "19"
                  ],
                  "boost":1
               }
            }
         }
      },
      {
         "_score":{
            "order":"desc",
            "missing":"_first",
            "unmapped_type":"string"
         }
      },
      {
         "entity_id":{
            "order":"desc",
            "missing":"_first",
            "unmapped_type":"string"
         }
      }
   ],
   "query":{
      "filtered":{
         "filter":{
            "bool":{
               "must":[
                  {
                     "terms":{
                        "stock.is_in_stock":[
                           true
                        ],
                        "boost":1
                     }
                  },
                  {
                     "terms":{
                        "visibility":[
                           2,
                           4
                        ],
                        "boost":1
                     }
                  }
               ],
               "must_not":[

               ],
               "should":[

               ],
               "minimum_should_match":1,
               "boost":1
            }
         },
         "boost":1
      }
   }
}
```
It seems like that products are just sorted by categories, and not filtered
In admin category configuration, the right products are displayed, so, it comes from the query generated by the front

I'm using the "single store mode" and I don't have any virtual category yet.
Btw, I'm using 2.2.2 version of Magento, maybe it comes from here. I'll give a try with 2.2 version

**Comment by afoucret** [comment]
@romainruaud 

Can you please test the following combination to see if the bug is reproduced : 
* Magento 2.2.2
* Single Store Mode set to ON.

Thx

**Comment by romainruaud** [comment]
@mtarld just to be sure, please try the latest version which is 2.4.3 and not 2.4.0.

I will also try to reproduce this one this afternoon.

We keep you in touch. Regards.

**Comment by mtarld** [comment]
@romainruaud 
I created a fresh install of Magento 2.2.2 and installed Elasticsuite 2.4.3
Everything seems to be ok... I don't know precisely how this bug appeared before.
Maybe it was the way that I've installed my sample data previous times

**Comment by afoucret** [comment]
Since the bug disappeared and have not been reproduced by us, it will be hard to find the cause and fix it.

I will close for now but feel free to reopen with more information if necessary.

**Comment by mtarld** [comment]
Sure !
Thanks again !

**Comment by mbernabeu** [comment]
same issue 

Preconditions

Magento Version : 2.2.2

ElasticSuite Version : 2.4.4

Environment : developer

Third party modules : -


When enable Smile_ElasticsuiteVirtualCategory the products disappear from the categories and 
when I activate it the products reappear
