### ISSUE TITLE
Special price doesn't show by autocomplete

### ISSUE THREAD

**Issue by redouanhajjari** [Smile-SA/elasticsuite#682]
### Preconditions
When you search for an product and it has an special price. the normale price wil showed in the dropdown screen.

i mean the top search balk in the header.
when you type your product. you see different products that the customer means. and the it didn't show an special price if the product has an special price.

Magento Version : 2.1.9
ElasticSuite Version : 2.3.0
Environment : production and development

**Comment by redouanhajjari** [comment]
Can somebody please give me feedback about this?

**Comment by sambolek** [comment]
Following this issue, as I'm seeing the same behaviour on one of our sites.

It seems that autocomplete box doesn't display special price for some products. Furthermore, the part that fetches the price (priceRenderer) seems pretty slow, so it sometimes takes a few seconds for autocomplete to show. 

Haven't investigated yet, but interested to see if someone else has the same problem(s).

**Comment by romainruaud** [comment]
I am able to reproduce the issue on my testing environment.

I set special price to a product and save it. Price index is OK, so does the ES index. But the autocomplete display the base price.

I will investigate this one to find what could cause this bug.

**Comment by afoucret** [comment]
PR have been merged.
Will be part of the next stable release.

**Comment by interequipment** [comment]
How can I hide product price from autocomplete list??
