### ISSUE TITLE
Filter option links changing to controller URL after clicking 'show more'

### ISSUE THREAD

**Issue by Tjitse-E** [Smile-SA/elasticsuite#686]
### Preconditions

Magento Version :
- Magento 2.2.2
- PHP7.1.13

ElasticSuite Version :
- smile/elasticsuite 2.4.3

Environment :
- Developer

### Steps to reproduce

1. Select one of the attributes (more than 10 values), set the facet max size on 10.
2. View a category page. Example:
![bevestigingsmateriaal___ijzerwaren](https://user-images.githubusercontent.com/14849044/34871149-d0273f42-f78c-11e7-8247-81a1db2fc8ec.png)

3. Validate the url's of the options. Example:
`http://site.url/category?manufacturer=QZ`

4. Click the show more button.

5. Click one of the URL's. Notice that they are different now, compared to step 3.

### Expected result

1. To see a normal category page, with the chosen filter applied.

### Actual result

1. You'll be redirected to the ajax result page. For example: http://site.url/catalog/navigation_filter/ajax/id/66/?_=1515753029191&cat=66&filterName=manufacturer&manufacturer=Kinzo
![staging_gereedschapbestellen_nl_catalog_navigation_filter_ajax_id_66____1515753029191_cat_66_filtername_manufacturer_manufacturer_kinzo_en_developer_tools_-_http___staging_gereedschapbestellen_nl_catalog_navigation_filter_ajax_id_66____1515](https://user-images.githubusercontent.com/14849044/34871250-37454fd4-f78d-11e7-8669-6442478f9055.png)

**Comment by afoucret** [comment]
Think you have a JS error somewhere.
Try to look at the dev console of your browser to give us more information.

**Comment by romainruaud** [comment]
Yes I am not able either to reproduce this one.

Maybe you have some JS plugged on filter links (maybe a tagging JS or something like this ?)

Regards

**Comment by afoucret** [comment]
@Tjitse-E ,

I confirm we can't reproduce your issue. I think the issue is related to custom developments in your project.

If you need some support that is specific to your project, we can provide you commercial support.
You can contact me directly at : aurelien.foucret@smile.fr

If you are able to give us more information on how to reproduce the issue, we will reconsider reopening this issue.

BR

**Comment by carloricci84** [comment]
I had the same problem, an other extension had an "afterGetUrl" function in a plugin here: vendor/mirasvit/module-seo/src/SeoFilter/Plugin/AttributeFilterPlugin.php .

**Comment by Tjitse-E** [comment]
Sorry for not responding earlier @afoucret , totally missed this topic. I've already bypassed this problem by disabling this feature.

@carloricci84 we also used the Mirasvit SEO module in this project, so it makes sense that this module is the cause of the error.

**Comment by inelukipg** [comment]
Hi,
I have the same problem and using Mirasvit Module Seo.
Is there any solution to this?

**Comment by inelukipg** [comment]
How did you bypass this problem @Tjitse-E?

**Comment by Tjitse-E** [comment]
@inelukipg , we've stopped using Mirasvit SEO actually. The module uses a lot of plugins, and is present on every page. So it was causing a lot of troubles, not only with elasticsuite.

But, if I remember correctly I think we disabled/modified the `afterGetUrl` in Mirasvit SEO, like @carloricci84  pointed out, using a patch file.

**Comment by inelukipg** [comment]
@Tjitse-E ok thanks! For others with the same problem I did the following as a quick fix.
(I know it's not a good solution to edit module core files, but it did the trick)

I think the best way is to create a new module instead to disable that plugin like described here:
https://magento.stackexchange.com/questions/148032/how-can-i-disable-a-plugin-in-a-module-from-another-module 


In `/vendor/mirasvit/module-seo-filter/src/SeoFilter/etc/frontend/di.xml`
add: `disabled="true"`
```
<type name="Magento\Catalog\Model\Layer\Filter\Item">
<plugin name="m-seofilter-catalog-layer-filter-item" type="Mirasvit\SeoFilter\Plugin\AttributeFilterPlugin" sortOrder="1000" disabled="true"/>
</type>
```
