### ISSUE TITLE
Practice of using private methods

### ISSUE THREAD

**Issue by reviskar** [Smile-SA/elasticsuite#687]
I'm sorry if this is not the correct place to discuss this matter, but why are nearly all the methods in every single class in your modules marked as `private`?

My patch folder is filled with patches of various Smile/Elasticsuite modules, because it is literally impossible to override/make plugins for any Smile/Elasticsuite items with correct DI or inheritance.

For example, by law I am not allowed to show some of the product images in autocomplete (This is just one example, there are far more primitive problems, are made impossible to solve without involving in core changes). If for example `\Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\ItemFactory::getImageUrl` would be a `public` method, this would be a simple 5 minute plugin, and leaving 100% upgrade-ability to newer versions. But as this method and everything else is `private`, I have literally no other way than to make a vendor patch to implement what I need, and this is just awful practice, IMO.

Even if you want to keep your visibility more strict (not everything `public`), why not keep everything  
`protected`? Making things `private` as a Magento module provider makes zero sense what so ever.

It makes sense only if you actually want end users not to be able to customize your module.

**Comment by afoucret** [comment]
Disagree with you.

In the case you are using as an example, it is only a very basic application of the "Open/Closed" principle (https://en.wikipedia.org/wiki/Open/closed_principle).

The class is closed for modification and all properties and util methods are private.

But you can still extends it by changing the default param in the constructor through :
* DI (in your case you can inject your own implementation of the Magento\Catalog\Helper\Image class in the ItemFactory)
* Through config if you want change the image dimension by overriding etc/view.xml

Our best practice includes :
* Application of the SOLID pattern as much as possible
* Favor composition over inheritance and allow to change behavior through DI
* Application of the Open / Closed principle
* Create inmutable objects as much as possible

It allow us to ensure the module is robust and more easy to maintain and test. Most experienced developers are able to extend the module if they don't consider inheritance as the only way to extend things.

Last but not least, the same principle are applied to Magento Core (all new classes are written in the same way we are writing ElasticSuite) and Magento is still very extensible for experienced developers.

**Comment by reviskar** [comment]
Hi afoucret!
Thank you for your response.
I appreciate the answer and also am fairly familiar with the solid principle. 
As to `Magento\Catalog\Helper\Image`, I'm afraid this does not help me much as I need this logic implemented only to autocomplete actions, not anywhere else in my case.

I appreciate all that you stand for, don't get me wrong, but I still think you are being slightly too aggressive with the closed principle, regarding magento as a platform. 

Let's take the same class in question. I agree to the `renderProductPrice` method being private, as you could override the renderer (but only assuming you want the same renderer for the entire app), but for example `addProductData` and `getImageUrl` would make sense to be classified as protected, as they are expected to be changed by different business logic.  Even if it is important for you to keep `addProductData` as private, then the submethods in that method could easily be less closed with strict return types. For example, you assume one always needs the `$product->getProductUrl()` as the url, but it may not be so simple for every user. 

You are doing an excellent job, and I don't want to sound so negative about the topic. Just some observations, I have come across while developing a pretty large site. As You said Magento does keep track of the Open / Closed principle, but I personally think you can't blindly private everything. Basically when I look at Smile / Elasticsuite modules, the majority of the protected methods are those overridden from magento2 core. Almost everything else is private. (This is just an illustrated example, probably not the best one, but the point is there, I think)

I've not had any issues so far with magento core nor with other modules.

Having said all that, I do not consider myself an expert in the field, but I thought would give some real-life feedback to an issue I and other members in my team have stumbled upon more than once. It's entirely up to you guys to decide whether this information is useful or not.

Keep up the good work!

**Comment by afoucret** [comment]
Hi @reviskar,

> As to Magento\Catalog\Helper\Image, I'm afraid this does not help me much as I need this logic implemented only to autocomplete actions, not anywhere else in my case.

And you can write your own helper and apply it only there.
By example by writing a class `\YourNamespace\Catalog\Helper\Product\CensoredImage` with a custom implementation of of the `getUrl` method.

Then you can inject it only in the `Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\ItemFactory` with :

```
<type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\ItemFactory">
     <arguments>
         <argument name="imageHelper" xsi:type="object">YourNamespace\Catalog\Helper\Product\CensoredImage</argument>
     </arguments>
</type>
```
From an architectural POV, I find this approach better than inheritance based on protected method because by doing this you will create a new reusable behavior (image censorship in your case) that can be applied elsewhere if you need. That is the kind of best practices that we encourage with an extensive usage of the private scope.

If you look ElasticSuite through this POV a l suspect you could realize it is a lot more extensible that what you were thinking. Not everything is perfect (the URL example is good), but most of the time we don't need protected methods but better to refactor the code using more composition (the image helper is a good example of how composition can give more flexibility). 

To finish I would encourage you to point us out specific extension difficulties you may have encoutered in new issues to help us to refactor the code to meet developer happiness. PR are also welcome !!!

**Comment by reviskar** [comment]
Hi @afoucret,
You are correct about the ImageHelper, can't belive how I missed that.
I guess there are habits (regardless of being good or bad) that are hard to look past...

> If you look ElasticSuite through this POV, l suspect you could realize it is a lot more extensible that what you were thinking. 

Yeah it would seem so. I get Your point and try to rework my issues.

Was very intresting to discuss this topic, I hope I did not waste your time too much.
Thanks a dozen!

**Comment by afoucret** [comment]
Hi @reviskar,

There is no waste of time in discussing with the community. It is a good opportunity for us to explain our way to do things and to spread what we believe to be best practices. It is also important if we want people to be aware and trained to our coding policy, so they can contribute to the module without having there contrib rejected for architectural or coding style concerns.

Even if we have good feedback from our internal usage of the module, we always listen for the community and even if the proposed solutions are not always relevant compared to our goals, it raises most of time some issues that need to be addressed.

Developper experience is important to us and we need to address difficulties you can meet in working with ElasticSuite. But as said in my eary posts, our decisions are here to ensure the module will be easy to maintain and upgrade.

Feel free to point us out area that are difficult to extend and explain us what you are trying to do and why. We are not shy with refactoring our code when needed to meet both our best practice and user satisfaction.

BR,
