### ISSUE TITLE
Catalog Rule not applied in virtual category

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#689]
When you create a Catalog Rule under Marketing, it's correcly displayed on frontend but is ignored in Virtual Categories.

Magento 2.2
ElasticSuite Version : master
Environment : Dev

### Steps to reproduce
1. Add some Configurable products with some simple products
2. Create a catalog rule under Marketing with a discount percent
3. Create a sale Virtual Category with discounted condition
4. Reindex

### Expected result
1. My virtual category has to show my configurable products discounted

### Actual result
No products.

**Comment by CRYX2** [comment]
Someone has verified my issue?

**Comment by afoucret** [comment]
Hi @CRYX2,

I planned to bring you a response today or tomorrow. 
It is a quite complicated one and it require time to see what we will do for this one.

BR,

**Comment by CRYX2** [comment]
Sorry but I really need this feature, can I do some tests on my environment to help you to resolve the bug?

**Comment by afoucret** [comment]
Does a fulltext reindex and cache cleaning solve the issue ?

If so, the bugfix may be quite easy.

**Comment by CRYX2** [comment]
I've investigated, and the problem is in the data returned method `loadPriceData($storeId, $productIds)` of class `Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Indexer\Fulltext\Datasource\PriceData`.

I've set a simple product with a special price manually, but when I reindex the `catalog_product_index_price` doens't get updated.

Any suggestions?

**Comment by afoucret** [comment]
By @CRYX2,

Can you propose the fix as a PR. It will be easier for us to investigate on a diff and publish a patch.

BR

**Comment by afoucret** [comment]
PR #714 have been merged and will be part of the next bugfix release (2.4.5).

Feel free to report if the fix does not solve the issue.

BR

**Comment by CRYX2** [comment]
Your patch is working very well even with catalog rules now, thanks dude

**Comment by CRYX2** [comment]
Sorry but I've encountered a problem with grouped products. I've some parent grouped products with 2 childs.
Each child has two different prices, one 9,02 € and another 1.000,00 €.
**No one of this child or parent product has rule or fixed discounted price.**
In magento index all prices are stored correcly, but in elasticsearch it's stored like:

`"price": [
{
"price": "9.0200",
"original_price": "1000.0000",
"is_discount": true,
"customer_group_id": "0"
}
,
{
"price": "9.0200",
"original_price": "1000.0000",
"is_discount": true,
"customer_group_id": "1"
}
,
{
"price": "9.0200",
"original_price": "1000.0000",
"is_discount": true,
"customer_group_id": "2"
}
,
{
"price": "9.0200",
"original_price": "1000.0000",
"is_discount": true,
"customer_group_id": "3"
}
],`

As you can see the min price is placed are discounted price (but is the price of one product), and the max price is placed as original_price, and it's set as "is_discount".
