### ISSUE TITLE
Setup:static-content:deploy less compilation error

### ISSUE THREAD

**Issue by bery** [Smile-SA/elasticsuite#69]
Hi,

with the newest Magento 2.1.0, static content deploy throws an error:

 ```
variable @autocomplete-item-border is undefined in file /home/httpd/www/_test-dev.test.summit.co.uk/var/view_preprocessed/css/frontend/Magento/blank/en_US/Smile_ElasticsuiteCore/css/source/_module.less in _module.less on line 30, column 34
  28|                 border-bottom: 0;
  29|             }
  30|             .lib-css(border-top, @autocomplete-item-border);
  31|             cursor: default;
  32|             margin: 0;
  33|             padding: @indent__xs @indent__xl @indent__xs @indent__s;
```

Fulltext search over the codebase suggests that the variable is not defined anywhere and I believe that the variable only has been renamed yet I am unable to find a fix for that.

Lukas

**Comment by afoucret** [comment]
What branch are you using ?

Only branch 2.2.x is currently compatible with Magento 2.1.0. It is a preview of our next release coming very soon.

**Comment by afoucret** [comment]
The commit that fixed it : 56cffc9bce9d1f57c4a3c6049a37f98f28f2a65c

Let me know if using 2.2.x branch solves the issue.

**Comment by bery** [comment]
Fix worked, many thanks!

**Comment by afoucret** [comment]
I close this issue since using the 2.2.x branch seems to solve it.

Thx for reporting.
