### ISSUE TITLE
Wrong search term count after applying filter in search result page

### ISSUE THREAD

**Issue by lokeshvnaik** [Smile-SA/elasticsuite#691]
Magento Version: 2.1.8 CE
ElasticSuite Version : 2.3.0
Environment: Developer mode
Third party modules: No

### Steps to reproduce
1. Enter any relevant keyword in the search box
2. In the suggestion box, Observe count for the search term
3. Click on search term
4. User is redirected to the search result page
5. Now apply any of the filters
6. Once filtered results are displayed, again search with the same keyword in the search box
7. Observe count in the suggestion box. Now the count for the same search term is not the same as before

### Expected result
1. Search term count in the suggestion should not change with the filtered search result. It should always show the total count of products for that search term.

### Actual result

![searchs01](https://user-images.githubusercontent.com/16201742/34987911-d0c9e798-fae2-11e7-91fb-a93dc2e0e99a.png)

![searchs02](https://user-images.githubusercontent.com/16201742/34987918-db81a176-fae2-11e7-9c31-fcc6caf2f03f.png)

![search03](https://user-images.githubusercontent.com/16201742/34987926-e2adfbc0-fae2-11e7-950a-62b440f4bd99.png)

One thing that I have observed is that the new count of the search term changes with no of products displayed on the search result page for that search term after the filter is applied.

For eg., If I search let say 'bed' and search term 'bedroom' shows count 13. Now on search result page for 'bedroom' when I apply a filter and now filtered result shows 3 products. So now if I search 'bed' in the search box, the search term count in the suggestion for 'bedroom' is showing 3 instead of 13.

**Comment by afoucret** [comment]
Tried here (http://demo.magento-elastic-suite.io/index.php/catalogsearch/result/index/?material=Fleece&q=men+shirt) and not able to reproduce.

Think you have a problem in your templating or in your JS.

**Comment by afoucret** [comment]
Hi @lokeshvnaik 

I confirm we can't reproduce your issue. I think the issue is related to custom developments in your project.

If you need some support that is specific to your project, we can provide you commercial support.
You can contact me directly at : aurelien.foucret@smile.fr

If you are able to give us more information on how to reproduce the issue, we will reconsider reopening this issue.

BR
