### ISSUE TITLE
Problem with sorting by polish characters

### ISSUE THREAD

**Issue by pawcioma** [Smile-SA/elasticsuite#694]
Wrond sorting result for product name with polish characters

Magento CE 2.1.7

ElasticSuite Version : "2.3.6

Environment : Production, but the same situation in developer mode

### Steps to reproduce
1. I added 4 products with names:
Łatwa naz
Latwa naz
Łatwa naa
Latwa naa

2. I search by "latwa" and sorting by "name" DESC

### Expected result
Łatwa naz
Łatwa naa
Latwa naz
Latwa naa

"Ł" should be before "L"

### Actual result
Łatwa naz
Latwa naz
Łatwa naa
Latwa naa

**Comment by afoucret** [comment]
To be fairly honest, we don't have support for polish yet.

There is a bunch of work to be done to achieve it : 
* Custom analyzer (including char filtering, collation, and so on)
* Custom plugin for ES as the polish language is not supported in ElasticSearch out of the box (no stemmer can handler the polish language) 

The main issue here : my team and me don't speak polish at all. 
My only notion of polish speaking are coming from the wikipedia readings I have after I read this issue !!!

But we can work together on this if you are interested in helping.

**Comment by pawcioma** [comment]
Ok. char_filter mappings work fine.

**Comment by afoucret** [comment]
Closed because you have find a solution using custom analyzer.
