### ISSUE TITLE
Price range does not change on currency change

### ISSUE THREAD

**Issue by prateekkarki** [Smile-SA/elasticsuite#696]
### Preconditions
Magento Version : 2.2 CE

ElasticSuite Version : 2.4

Environment : PHP 7.1 nginx on ubuntu

### Steps to reproduce

1. Set up a few different currencies from magento backend
2. Check any page with price filter with slider
3. Set a price range and hit OK to apply the filter
4. Change the currency of the store

### Expected result

1. The price ranges should change according to the new currency
2. If the price range is set for USD $10 to USD $100, upon change in the currency, the range should change to 1107.4 JPY to 11074 JPY, but it just stays on 10 JPY to 100 JPY

### Actual result

1. The values for price range should change according to the new currency
2. If the price range is set for USD $10 to USD $100, upon change in the currency, the range just stays on 10 JPY to 100 JPY

**Comment by afoucret** [comment]
Hi @prateekkarki,

We don't support multiple currencies. One quick workaround would be to disable price facet if using a currency that is different of the store view default currency. 
@romainruaud : can you patch it against 2.4.x branch ?

It is far from being perfect but at least it will allow to not display a wrong information.

We should be able to have multiple currencies support in a later version (2.5.x or 2.6.x).

BR,

**Comment by prateekkarki** [comment]
Hi @afoucret ,

Thanks for adding it to 2.4.5, I will disable the facet for now and will be waiting for the update. 

Meanwhile, if I can be of any help regarding the issue. Please feel free to tell me. With some explanation regarding the flow of price filter through the module, I'd be happy to contribute.

**Comment by afoucret** [comment]
@romainruaud : ping

**Comment by doanhchuong** [comment]
hi @prateekkarki and @afoucret   how to disable the price facet ? 
please help me . thanks
