### ISSUE TITLE
Display another product attribute in product sorter

### ISSUE THREAD

**Issue by VincentMarmiesse** [Smile-SA/elasticsuite#699]
Hello,

I would like to display another product attribute in the category product sorter.

I have rewrited files`Smile_ElasticsuiteCatalog/web/js/form/element/product-sorter/item.js` and `Smile_ElasticsuiteCatalog/web/template/form/element/product-sorter.html` in my own theme to add my custom attribute.

I saw the item data is supplied by `\Smile\ElasticsuiteVirtualCategory\Model\Preview\Item::getData` and wanted to create a plugin to add my own attribute but the `product` parameter of the class is `private` so I can't access it. Here is my code:

```
namespace Vendor\Module\Plugin\Elasticsuite\Preview;

class ItemPlugin
{
    public function afterGetData(\Smile\ElasticsuiteVirtualCategory\Model\Preview\Item $subject, $productItemData)
    {
        $productItemData['myattribute'] = $subject->product->getMyAttribute();

        return $productItemData;
    }
}
```

Can I retrieve `$subject->product` in some way?

I have the id and can use `\Magento\Catalog\Model\ResourceModel\Product::getAttributeRawValue()` but it could be easier if the class `\Smile\ElasticsuiteVirtualCategory\Model\Preview\Item` had a public method `getProduct()`.

What do you think about it?

**Comment by afoucret** [comment]
Hi @VincentMarmiesse,

I am currently refactoring this part of the code in order to implement a new feature (#588).
I will consider making this code easier to implement.

BR,

**Comment by afoucret** [comment]
The previous class `\Smile\ElasticsuiteVirtualCategory\Model\Preview\Item`have been replaced by `Smile\ElasticsuiteCatalog\Model\ProductSorter\ItemDataFactory`.

The code is easier to implement, since the product is now a param of the getData method.
It is part of a full rewrite of the product sorter preview.

I will merge this on master very soon and it will be part of release 2.5.0.
