### ISSUE TITLE
Fatal error: Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Response\QueryResponse

### ISSUE THREAD

**Issue by bery** [Smile-SA/elasticsuite#70]
When running on Magento 2.1.0

`setup:di:compile`

the output of Repositories code generation is a fatal error

`Fatal error:  Class Smile\ElasticsuiteCore\Search\Adapter\Elasticsuite\Response\QueryResponse cannot implement previously implemented interface IteratorAggregate in /home/httpd/www/_test-dev.test.summit.co.uk/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Response/QueryResponse.php on line 27`

**Comment by afoucret** [comment]
As explained in issue #70 you have to use branch 2.2.x with Magento 2.1.

**Comment by bery** [comment]
Sorry, I didn't know that. You have also referenced this issue and not the one you intended. Would it be possible to update readme with this information?

**Comment by afoucret** [comment]
No problem.

I fix the reference to the issue.

As it is already late here in France, I will fixed the readme tomorrow in the morning.
PRs are also welcome if you have the time to do it 😄

**Comment by afoucret** [comment]
Hi @bery,

I have updated the readme this morning.

I close the issue since using branch 2.2.x solves issues related to Magento 2.1.0

Thx for reporting
