### ISSUE TITLE
Dissabling facets instead of hiding them

### ISSUE THREAD

**Issue by krisdante** [Smile-SA/elasticsuite#701]
I am looking for a possibility to disable facets when a combination is not possible instead of hiding them (configuration option would be nice)

### Preconditions

Magento Version : 2.2 CE

ElasticSuite Version : 2, does not matter

Environment : does not matter

Third party modules : does not matter

### Steps to reproduce

1. Go to http://demo.magento-elastic-suite.io/index.php/women/tops-women/tanks-women.html
2. You can see ~10 options for Material
3. Select Black color
4. Now you have only 6 Materials

### Expected result

1. There shall be still ~10 materials, but those which do not offer black shall "disabled" and/or number of results indicator show (0)

### Actual result

1. Materials that do not offer black color were removed from the materials list
2. Users who come to a category page from a link like:  http://demo.magento-elastic-suite.io/index.php/women/tops-women/tanks-women.html?color=Black are not aware that more Materials will appear when they "unselect" black color. 

### Real life use-case

We have a customer who deep links to a category page with a preselected brand filter. 
This shop sells paints and then the color picker is reduced to colors offered only by preselected brand (in corner case only one color out of 20).
What we want to achieve is to show all the colors of paint in the shop to indicate that when a client will remove Brand filter more colors are available to choose.

**Comment by afoucret** [comment]
Hi @krisdante 

I take a look at this one and such a feature can not be implemented in ElasticSuite without big changes in the query building stack.
To be fairly honest it is very unlikely that someone in the core team will work on this since we have other priorities.

If you are really interested in such a feature, I would be very happy to review some code to merge for this.

**Comment by romainruaud** [comment]
We waited for community proposals on this once for two years, I think it's time to close it :) 

Regards
