### ISSUE TITLE
[FR translation] Enabled means "Activé"

### ISSUE THREAD

**Issue by VincentMarmiesse** [Smile-SA/elasticsuite#702]
Hello,

There is a mistake in the french translation of the `Smile_ElasticsuiteTracker` module.

Currently, `Enabled` is translated by `Activer`, it should be `Activé`.

Thanks!

**Comment by romainruaud** [comment]
Hello @VincentMarmiesse and thank you for reporting it.

May I let you propose a PR to fix this minor one ?

Regards

**Comment by VincentMarmiesse** [comment]
Pull request #703 created ;)

**Comment by afoucret** [comment]
Will be part of the upcoming 2.5.0 release.
Thx for contributing.
