### ISSUE TITLE
Sorting products by stock availability doesn't work

### ISSUE THREAD

**Issue by shirishShoptimize** [Smile-SA/elasticsuite#704]
On listing page, I have added a custom feature of automatically sorting the products based on their stock availability. It works fine without the Elasticsuite module. When the Elasticsuite module is turned on, the in-stock and out-of-stock products are shown together without following the ordering.

### Preconditions
Magento Version : Magento CE 2.1.10
ElasticSuite Version : 2.3.5
Environment : Developer and Production
Third party modules : No

### Steps to reproduce
1. Add plugin for Magento\Catalog\Model\Layer, below is the di.xml: 
```
<type name="Magento\Catalog\Model\Layer">
        <plugin name="CustomLayerPlugin" type="Vendor\Module\Model\Plugin\LayerPlugin"/>
</type>

```
2. Add beforePrepareProductCollection() method in the plugin:
```
public function beforePrepareProductCollection (
        \Magento\Catalog\Model\Layer $layer,
        \Magento\Catalog\Model\ResourceModel\Collection\AbstractCollection $collection)
    {

        try {
            $collection->getSelect()->resetJoinLeft();

            $collection->getSelect()->joinLeft(
                ['stock_status' => 'cataloginventory_stock_status'],
                "stock_status.product_id = e.entity_id",
                ['qty', 'stock_status']
            );

            $select = $collection->getSelect();
            $field = new \Zend_Db_Expr('IF(stock_status.qty > 0, 0, 1)');
            $field2 = new \Zend_Db_Expr('stock_status.stock_status DESC');

            $select->order($field)->order($field2);

            // move to the first position
            $orders = $select->getPart(\Zend_Db_Select::ORDER);
            if (count($orders) > 1) {
                $last = array_pop($orders);
                array_unshift($orders, $last);
                $select->setPart(\Zend_Db_Select::ORDER, $orders);
            }

        } catch (\Exception $e) {
            $this->logger->debug("Exception in plugin while sorting by stock status: ". $e->getMessage());
        }
    }
```
3. Go to listing page on storefront.

### Expected result
1. All out of stock products should be shown at the end of the result on the listing page. Please refer the screenshot below. This is the result when the Elasticsuite modules are disabled.

![screenshot from 2018-01-23 18 13 40](https://user-images.githubusercontent.com/28599721/35276567-cab5d948-0069-11e8-8539-d8ced4e97282.png)

### Actual result
1. Out of stock products appear along with in-stock products. Please find below the screenshot:

![screenshot from 2018-01-23 18 11 11](https://user-images.githubusercontent.com/28599721/35276577-d2b10c4e-0069-11e8-8f00-63cbc3c93887.png)

Could you please suggest the right way to add sort order for products collection in this case?

**Comment by afoucret** [comment]
The thing is : ElasticSuite is using ElasticSearch to achieve sorting.
You are doing it using the MySQL query instead and it can not work this way.

I would not advice to do it programmatically but that you should better rely on the search optimizer feature if you want to achieve such a feature (bonus : it will work without coding even one line).

The process is : 
- Create an optimizer (Smile ElasticSuite -> Optimizer)
- Choose the constant score model
- Choose store the optimizer should be applied on
- Choose if the optimizer applies to Fulltext search, category listing, ...
- In the apply to product section, you should have a rule that math "Only in stock products"
- Fill a quite high value in the boost value field (let's says 1000)

By doing so search result will be boosted for product with are in stock both in search result and in catalog product view.

![screencapture-localhost-8080-admin_1pewh6-smile_elasticsuite_catalog_optimizer-optimizer-create-key-7fb3cc0d87d524c2a4b578188ed51347d2b194fb26b813e1f6f25c23cdf87ca0-1516712594484](https://user-images.githubusercontent.com/529238/35277357-c89a2cfe-0046-11e8-9671-4a2e7b853628.png)

Hope it's help.

**Comment by shirishShoptimize** [comment]
Hi @afoucret ,

Thanks for the solution! It worked for me. The Optimizer is quite a powerful tool, I would be exploring this further :)

**Comment by abhisheksdckap** [comment]
I have tried this but still products are not sorting by inventory on category product view page.
Magento version : 2.4.1
Elasticsuite version : 2.10.0
