### ISSUE TITLE
"Did you mean ?" feature

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/elasticsuite#705]
Idea from [issue #84 ](https://github.com/Smile-SA/elasticsuite/issues/84)
It could be good to have a list of suggestions in the search results page in the query didn't match with any products.
For example: for q = "guital" .
Have a sentence 'We didn't find any result for 'guital'. Did you mean "guitar", ... ?' . With a link to the new search results page for the query 'guitar'.
Possibility to configure in the backend the number max of suggestions ?
Possibility to enable/disable this feature ?

### Preconditions
Magento Version : CE 2.1.11
ElasticSuite Version : 2.3.10

**Comment by afoucret** [comment]
This is definitely something we are considering.

Probably for 2.6.x release.

**Comment by romainruaud** [comment]
With https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-suggesters-phrase.html ?

**Comment by Melleschepers** [comment]
This feature would be great! Could be in the same style as the "related search terms" (http://demo.magento-elastic-suite.io/index.php/catalogsearch/result/?q=shirt)

**Comment by romainruaud** [comment]
Will be fixed by #3053 

![image](https://github.com/Smile-SA/elasticsuite/assets/15340849/7e2f7275-1d24-411f-9f5a-107711b5bf85)

**Comment by romainruaud** [comment]
Fixed by #3053
