### ISSUE TITLE
Layered navigation: products count should be displayed depending on config

### ISSUE THREAD

**Issue by VincentMarmiesse** [Smile-SA/elasticsuite#711]
Hello,

The products count should be displayed depending on the `catalog/layered_navigation/display_product_count`

### Preconditions
Magento Version : 2.1+
ElasticSuite Version : NA
Environment : NA
Third party modules : NA

### Steps to reproduce
1. Go in admin to Stores > Configuration > Catalog > Catalog > Layered Navigation and set Display Product Count to No.
2. Flush cache

### Expected result
1. Product count should not be displayed in layered navigation

### Actual result
1. Product count is displayed

**Comment by afoucret** [comment]
PR #713 fix this one and will be part of the next stable release (2.5.0).

Thx for reporting.
