### ISSUE TITLE
Magento 2.1, error sortParams

### ISSUE THREAD

**Issue by Fdec** [Smile-SA/elasticsuite#72]
we have an error on search 
Exception #0 (Exception): Notice: Undefined index: sortParams in /var/www/damartch/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection/ProductLimitation.php on line 45

Exception #0 (Exception): Notice: Undefined index: sortParams in /var/www/damartch/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection/ProductLimitation.php on line 45
#0 /var/www/damartch/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection/ProductLimitation.php(45): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/var/www/damart...', 45, Array)
#1 /var/www/damartch/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(504): Magento\Catalog\Model\ResourceModel\Product\Collection\ProductLimitation->offsetGet('sortParams')
#2 /var/www/damartch/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(475): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->prepareSortOrders()
#3 /var/www/damartch/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/ResourceModel/Product/Fulltext/Collection.php(383): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->prepareRequest()
#4 /var/www/damartch/vendor/magento/framework/Data/Collection/AbstractDb.php(338): Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Collection->_renderFiltersBefore()

**Comment by afoucret** [comment]
The issue has been fixed on the 2.2.x branch
