### ISSUE TITLE
PHP Fatal Error: ..\Aggregation\Bucket\Term::__construct()

### ISSUE THREAD

**Issue by alloylab** [Smile-SA/elasticsuite#723]
We have been running in production with same codebase for a couple weeks now... but today we started getting a php fatal error when any term is search... we were running ElasticSuite Version : 2.4.4 at the time ... but just upgrade to ElasticSuite Version : 2.4.5... and we are continuing to have the same issue...  

Any ideas? Thanks.

### Preconditions
Magento CE 2.2.1
ElasticSuite Version : 2.4.5
Environment : Production

### Steps to reproduce
1. Search any term

### Expected result
1. Return search results

### Actual result
`2018/02/02 23:26:48 [error] 6#6: *28412 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: Argument 3 passed to Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term::__construct() must be of the type array, null given, called in /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /var/www/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Aggregation/Bucket/Term.php:51
Stack trace:
#0 /var/www/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Smile\ElasticsuiteCore\Search\Request\Aggregation\Bucket\Term->__construct(NULL, NULL, NULL, NULL, NULL, NULL, 10, '_count')
#1 /var/www/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Smile\\Elasticsu...', Array)
#2 /var/www/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Smile\\Elasticsu...', Array)
#3 /var/www/generated/code/Smile/ElasticsuiteCo" while reading response header from upstream, client: 172.17.0.6, server: *.xx.com, request: "GET /catalogsearch/result/?q=work HTTP/1.1"`

I also discovered that when I enter a random term that provides no resutls, I get this message on a blank page "No exact results found for: 'ter'. The displayed items are the closest matches." instead of blank page when results are found

**Comment by romainruaud** [comment]
I'm pretty sure that someone changed an attribute configuration in the back-office.

Probably someone has set an attribute to being filterable, or searchable. When browsing, Elasticsuite is trying to build an aggregation for this attribute but the field (the Elasticsearch field) does not exist in the current mapping.

Could you try to process a full reindex of the Catalog Search index and tell us if it is working better ?

Not sure about how we could deal with this dynamic mapping update @afoucret , it could be easy for "new" fields to add into mapping, but that does not cover all cases.

Regards

**Comment by alloylab** [comment]
a full reindex of the Catalog Search index didn't fix the issue... interestingly enough i discovered the master branch/release 2.5.0 fixes the issue...

**Comment by afoucret** [comment]
If fixed in the latest release, I close the issue.

**Comment by leo-leung** [comment]
It is due to production mode problem, please run setup:di:compile and it returns to normal
