### ISSUE TITLE
Missing addOptionsData in filter options

### ISSUE THREAD

**Issue by Leone** [Smile-SA/elasticsuite#729]
When you change option label in the filter attribute in the admin panel, filter navigation on the frontend disappears.

### Preconditions

Magento Version : 2.1.10 CE

ElasticSuite Version : 2.3.0, but does not matter

Environment : does not matter

Third party modules : does not matter

### Steps to reproduce

1. edit attribute in the admin panel
2. change label in some option
3. save changes

### Expected result

1. Filters should be still visible on the frontend.

### Actual result

Filter nav (the whole block) on the frontend disappears.
We found in logs:

> main.CRITICAL: Notice: Undefined index: adminSortIndex in /*/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Layer/Filter/Attribute.php on line 277 [] []

The problem is that script doesn't set key adminSortIndex to all items in array $items and a few lines below the script tries to sort these array using this key.

### Possible solution

In class Smile\ElasticsuiteCatalog\Model\Layer\Filter\Attribute, method addOptionsData(),
change this:
```
usort($items, function ($item1, $item2) {
    return $item1['adminSortIndex'] <= $item2['adminSortIndex'] ? -1 : 1;
});
``` 
to this:
```
usort($items, function ($item1, $item2) {
    // check if key adminSortIndex exists
    if(!isset($item1['adminSortIndex']) or !isset($item2['adminSortIndex'])){
        return 0;
    }
    return $item1['adminSortIndex'] <= $item2['adminSortIndex'] ? -1 : 1;
});
```

**Comment by afoucret** [comment]
Hi @Leone 

I will try to look at your PR quickly now.

**Comment by afoucret** [comment]
PR have been merged and will be part of the next maintenance release (2.5.1).

Thx for contributing.
