### ISSUE TITLE
error when using table_prefixes

### ISSUE THREAD

**Issue by mnentwich** [Smile-SA/elasticsuite#73]
The module seems broken when table prefixes are configured.

error on setup:upgrade:

Base table or view not found: 1146 Table 'magento.catalog_category_entity' doesn't exist, query was: INSERT INTO `lei_catalog_category_entity_int` (`attribute_id`, `entity_id`, `value`) SELECT 131 as attrib
  ute_id, `catalog_category_entity`.`entity_id`, 1 as value FROM `catalog_category_entity` ON DUPLICATE KEY UPDATE `attribute_id` = VALUES(`attribute_id`), `entity_id` = VALUES(`entity_id`), `value` = VALUES(`value`)

I searched around and the problem occurs in updateAttributeDefaultValue (InstallData.php), where the insertFromSelect produces the illegal query.

**Comment by afoucret** [comment]
Fixed by PR #83
