### ISSUE TITLE
Small mistake in the help message of "Fuzziness Prefix Length"

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#74]
Open the menu "ElasticSuite > Search relevance"
Open the tab "spellchecking configuration"

The help message for the setting "Fuzziness Prefix Length" is:
"Allowed values "0", "1" or "AUTO". See doc here for more information"

This message should be:
"Allowed values "1", "2" or "AUTO". See doc here for more information"

Explanation:
- Value 0 doesn't make sense (you should disable fuzzy search).
- Value 2 is working and allows 2 wrong letters (I tested it) 

Same remark for the setting "Phonetic fuzziness value"

**Comment by afoucret** [comment]
I think the field should be turned into a select at the same time since values different than 0, 1 or AUTO can break the engine.

**Comment by PierrickOlivier** [comment]
Correction: "values different than 1, 2 or AUTO "

**Comment by afoucret** [comment]
This one have been fixed and will be part of the 2.2.0 release.
