### ISSUE TITLE
After installation Modules are outdated error 

### ISSUE THREAD

**Issue by surendiranganesan** [Smile-SA/elasticsuite#740]
Hi
I am new to Magento. After installation of elastic suite i am getting few modules are outdated.

### Preconditions

Magento Version :CE 

ElasticSuite Version :2.5.0

Environment :Developer

Third party modules :

### Steps to reproduce

1.Downloaded Magento 2.2.2 with sample data from https://github.com/magento-2/magento-2-community-sample-data/archive/master.tar.gz.
2. installed successfully in Wamp (Apache 2.4.27,php 7.1.9)
3. installed elastic suite 2.5.0 successfully  using composer

### Expected result

1. Front end and back end should open without errors

### Actual result

After installation when i try to open both front end and back end i am getting following issues.
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.4.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.0.1
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.1.0
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.1.0

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Smile_ElasticsuiteCatalog data: current version - none, required version - 1.4.0
Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.0.1
Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
Smile_ElasticsuiteTracker data: current version - none, required version - 1.1.0
Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.1.0
#0 E:\wamp64\www\magento\vendor\magento\framework\Interception\Interceptor.php(121): Magento\Framework\Module\Plugin\DbStatusValidator->beforeDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Magento\Framework\App\Request\Http))
#1 E:\wamp64\www\magento\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#2 E:\wamp64\www\magento\generated\code\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#3 E:\wamp64\www\magento\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 E:\wamp64\www\magento\generated\code\Magento\Framework\App\Http\Interceptor.php(24): Magento\Framework\App\Http->launch()
#5 E:\wamp64\www\magento\vendor\magento\framework\App\Bootstrap.php(256): Magento\Framework\App\Http\Interceptor->launch()
#6 E:\wamp64\www\magento\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#7 {main}
```

I tried Run "bin/magento setup:upgrade" but no success.

I found one more similar kind of issue (https://github.com/Smile-SA/elasticsuite/issues/698)  in the issue section, In the comment section another link  (https://github.com/Smile-SA/elasticsuite/issues/692)       was shared. As i am new to magento i don't know exactly what to do.kindly help me fix this issue.

**Comment by afoucret** [comment]
You should clean you cache and then run `the setup:upgrade` process :

``` 
bin/magento cache:clean && bin/magento setup:ugrade
```

Do not forget to reindex everything :

``` 
bin/magento indexer:reindex && bin/magento cache:clean
```

In the end, you should prefer installing Magento using `composer create-project` instead of using a tar as explained here (depending you are using community or enterprise) : http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_ce.html and http://devdocs.magento.com/guides/v2.0/install-gde/prereq/integrator_install_ee.html

I close because not related to ElasticSuite but to Magento modules management.

**Comment by OvalMedia** [comment]
I have the same issue with different versions though.
My magento installation was initially a 2.2.5 which I recently upgraded to 2.2.6. Very basic system so far (new project just started). 

I installed with `composer require smile/elasticsuite ^2.6.0` followed by a `bin/magento setup:upgrade` and `bin/magento setup:di:compile`. Also cleared the cache multiple times but no go:

> 1 exception(s):
> Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
> The following modules are outdated:
> Smile_ElasticsuiteCatalog data: current version - none, required version - 1.5.0
> Smile_ElasticsuiteCatalogRule data: current version - none, required version - 1.0.0
> Smile_ElasticsuiteCatalogOptimizer data: current version - none, required version - 1.1.0
> Smile_ElasticsuiteSwatches data: current version - none, required version - 0.0.1
> Smile_ElasticsuiteThesaurus data: current version - none, required version - 1.0.0
> Smile_ElasticsuiteTracker data: current version - none, required version - 1.2.0
> Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.3.0

**Comment by cctalma** [comment]
My data_version was also empty. I've corrected it with this query

update setup_module set data_version = schema_version where data_version is NULL;

**Comment by myselfhimself** [comment]
Same exception as https://github.com/Smile-SA/elasticsuite/issues/740#issuecomment-425408976 in front-end and back-end, [in the middle of post-install configuration steps](https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall#magento-is-already-installed-).

```
MariaDB [magento]> select * from setup_module;
+-------------------------------------+----------------+--------------+
| module                              | schema_version | data_version |
+-------------------------------------+----------------+--------------+
| Amazon_Core                         | 4.2.2          | 4.2.2        |
| Amazon_Login                        | 4.2.2          | 4.2.2        |
| Amazon_Payment                      | 4.2.2          | 4.2.2        |
| Dotdigitalgroup_Chat                | 1.5.0          | 1.5.0        |
| Dotdigitalgroup_Email               | 4.12.0         | 4.12.0       |
| Dotdigitalgroup_Sms                 | 1.1.1          | 1.1.1        |
| Klarna_Core                         | 6.2.4          | 6.2.4        |
| Klarna_Kp                           | 7.3.7          | 7.3.7        |
| Klarna_KpGraphQl                    | 0.9.7          | 0.9.7        |
| Klarna_Onsitemessaging              | 1.0.6          | 1.0.6        |
| Klarna_Ordermanagement              | 6.2.5          | 6.2.5        |
| Magento_GoogleShoppingAds           | 4.0.1          | 4.0.1        |
| Magento_Securitytxt                 | 1.0.0          | 1.0.0        |
| PayPal_Braintree                    | 4.0.3          | 4.0.3        |
| Smile_ElasticsuiteAdminNotification | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteAnalytics         | 0.0.1          | NULL         |
| Smile_ElasticsuiteCatalog           | 1.6.2          | NULL         |
| Smile_ElasticsuiteCatalogGraphQl    | 1.0.0          | NULL         |
| Smile_ElasticsuiteCatalogOptimizer  | 1.2.0          | NULL         |
| Smile_ElasticsuiteCatalogRule       | 1.0.0          | NULL         |
| Smile_ElasticsuiteCore              | 0.0.1          | 0.0.1        |
| Smile_ElasticsuiteIndices           | 1.0.0          | NULL         |
| Smile_ElasticsuiteSwatches          | 0.0.1          | NULL         |
| Smile_ElasticsuiteThesaurus         | 1.0.0          | NULL         |
| Smile_ElasticsuiteTracker           | 1.3.0          | NULL         |
| Smile_ElasticsuiteVirtualCategory   | 1.5.0          | NULL         |
| Snowdog_Menu                        | 0.2.5          | 0.2.5        |
| Vertex_AddressValidation            | 100.5.0        | 100.5.0      |
| Yotpo_Yotpo                         | 3.2.0          | 3.2.0        |
+-------------------------------------+----------------+--------------+

```

> My data_version was also empty. I've corrected it with this query
> 
> update setup_module set data_version = schema_version where data_version is NULL;

Had to do this too to fix.. we are in 2022, three years later.

For information, I have no alive nodes for now, will continue the configuring steps.
