### ISSUE TITLE
No alive nodes found in your cluster - magento setup:upgrade

### ISSUE THREAD

**Issue by deckside** [Smile-SA/elasticsuite#741]
I have installed ElasticSearch and have installed ElasticSuite via composer. 
When I run bin/magento setup:upgrade I get an error 

Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

### Preconditions

Magento Version : 2.2.2 CE

ElasticSuite Version 2.5

Magento Environment : Production mode 

Environment Ubuntu 16.04.3

Third party modules : Fooman Same Invoice, Fooman PDF attachments, M2ePro

### Steps to reproduce
**Install Elastic Search**
sudo apt-get install openjdk-8-jre
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
sudo apt-get update && sudo apt-get install elasticsearch
sudo service elasticsearch start

**Test**
curl localhost:9200
ubuntu@ip-172-31-19-232:~$ curl localhost:9200
{
  "name" : "JR6Ny5F",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "4mVwf5szTIe984wLFAY2Sg",
  "version" : {
    "number" : "5.6.7",
    "build_hash" : "4669214",
    "build_date" : "2018-01-25T21:14:50.776Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"

**Install Elastic suite**
cd /var/www/magento
sudo bash
composer require smile/elasticsuite

bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker

bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers node-1:9200,node-2:9200
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user "admin"
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd "Password123"
bin/magento app:config:import

php bin/magento setup:upgrade
During this step the error was found

Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

### Expected result
I would have expected setup:upgrade to complete without any errors

### Actual result
Module 'Smile_ElasticsuiteCatalog':
Installing data... No alive nodes found in your cluster

**Comment by afoucret** [comment]
Hi @deckside,

If your server is responding on localhost:9200 and auth is disabled, you don't have to do anything with the config (**optional if using default server location, http://localhost:9200** in the wiki).

You can fix by playing :

```
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers localhost:9200
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user ""
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd ""
bin/magento app:config:import
```

Then clean all caches and rerun the setup :

```
bin/magento cache:clean && bin/magento setup:upgrade
```

In the end reindex all :
``` 
bin/magento indexer:reindex 
```

Closed for being a misusage of the module.
