### ISSUE TITLE
Table not found : module doesn't manage table prefixes in 2.5.0 

### ISSUE THREAD

**Issue by shavounet** [Smile-SA/elasticsuite#743]
### Preconditions
Magento Version : 2.2
ElasticSuite Version : 2.5
Environment : dev

### Steps to reproduce
1. Install a basic Magento with table prefixes & sample data
2. Go on product list page
3. Try to reindex

### Actual result
1. For now (following stacks), I've seen 3 places where table prefixes where not correctly implemented
   * `src/module-elasticsuite-catalog/Model/ResourceModel/Product/Search/Position.php:64`
   * `src/module-elasticsuite-catalog/Model/ResourceModel/Product/FilterableAttribute/Category/Collection.php:129`
   * `src/module-elasticsuite-catalog/Model/ResourceModel/Product/FilterableAttribute/Category/Collection.php:170`
2. I've still an issue (showing twice) while reindexing : 
``` $ ./bin/magento indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:00
Category Products index has been rebuilt successfully in 00:00:00
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:06
Product EAV index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:03
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Stock index has been rebuilt successfully in 00:00:02
Catalog Search indexer process unknown error:
mapper_parsing_exception: No handler for type [keyword] declared on field [type_id]
Product/Target Rule index has been rebuilt successfully in 00:00:04
Target Rule/Product index has been rebuilt successfully in 00:00:00
Sales Rule index has been rebuilt successfully in 00:00:00
ElasticSuite Category Indexing indexer process unknown error:
mapper_parsing_exception: No handler for type [keyword] declared on field [path]
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00
```

**Comment by afoucret** [comment]
PR have been merged and will be part of the next maintenance release (2.5.1).
Thx for reporting and contributing.

**Comment by shavounet** [comment]
Note that there is another error that I haven't fixed (without knowing if normal or not).
I haven't done a full test either.

**Comment by afoucret** [comment]
For your reindexing issue, I suppose you are working on branch master and not on the 2.5.x branch.
I also suppose that you are still using ElasticSearch 2.x and have not migrated yet to 5.x.

The master branch contained the next major release (2.6.0). In version 2.6.0 we will drop the support for version 2.x of ElasticSearch and we will support only 5.x and 6.x.

Note : you should not use a branch until you are contributing and you should prefer using a stable release (2.5.0 currently).

BR,

**Comment by shavounet** [comment]
Indeed, after some cleanup, reindexing went ok. I'm now plugged on ES 5.2 (maximum available for my hosting platform...).
