### ISSUE TITLE
Frontend not working after install

### ISSUE THREAD

**Issue by deckside** [Smile-SA/elasticsuite#746]
After installing ElasticSuite front-end is not working.
Back-end is working, module is installed

### Preconditions

Magento Version : 2.2.2 CE

ElasticSuite Version 2.5

Magento Environment : Production mode

Environment Ubuntu 16.04.3

Third party modules : Fooman Same Invoice, Fooman PDF attachments, M2ePro, Ultimo Theme.

### Steps to reproduce
Install Elastic Search
sudo apt-get install openjdk-8-jre
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
sudo apt-get update && sudo apt-get install elasticsearch
sudo service elasticsearch start

**Test**
curl localhost:9200
ubuntu@ip-172-31-19-232:~$ curl localhost:9200
{
"name" : "JR6Ny5F",
"cluster_name" : "elasticsearch",
"cluster_uuid" : "4mVwf5szTIe984wLFAY2Sg",
"version" : {
"number" : "5.6.7",
"build_hash" : "4669214",
"build_date" : "2018-01-25T21:14:50.776Z",
"build_snapshot" : false,
"lucene_version" : "6.6.1"
},
"tagline" : "You Know, for Search"

**Tested frontend all good**

Install Elastic suite
cd /var/www/magento
sudo bash
composer require smile/elasticsuite

bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker

bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers localhost:9200
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user "admin"
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd "Password123"
bin/magento app:config:import

bin/magento cache:clean && bin/magento setup:upgrade

php bin/magento setup:di:compile

bin/magento indexer:reindex && bin/magento cache:clean

php bin/magento setup:static-content:deploy en_US en_AU -f
sudo php bin/magento cache:flush

### Expected result
Expected frontend to be working

### Actual result
Frontend (website home page) not working
Backend (Admin Console) working perfectly

**Comment by afoucret** [comment]
Hi @deckside,

Can you be more explicit about the meaning of : 

> Frontend (website home page) not working

Additionaly we had several issue with third party themes that modify the layout in a way that is not compatible with the standard Luma theme (espacially with Ultimo). Debugging commercial extensions is not part of our Open Source community support but we can help as part of our commercial support.

**Comment by romainruaud** [comment]
There are notorious issues with the Ultimo theme due to their wrong usage of catalog layer (especially on a block which is on the home page).

Check the first entry of our FAQ about this : https://github.com/Smile-SA/elasticsuite/wiki/FAQ

**Comment by deckside** [comment]
Just reinstalled on a new instance without Ultimo

Working well

Thank you

**Comment by afoucret** [comment]
So we close
