### ISSUE TITLE
Drag & Drop > Alignment problem

### ISSUE THREAD

**Issue by PierrickOlivier** [Smile-SA/elasticsuite#750]
![capture d ecran 2018-02-13 a 18 00 35](https://user-images.githubusercontent.com/20048184/36162925-1276cb28-10e8-11e8-9139-9d1b0dc5aa7f.png)

When I play with the drag & drop, the width of the product decreases and the layout is broken : a product from the 2nd line is moving to the 1st line. See screenshot enclosed.

### Preconditions

I'm using Chrome 63 for Mac OS X

Magento Version : 2.2.0 Open source

ElasticSuite Version : Latest (2.5)

### Steps to reproduce

Open the search terms, click the "merchandiser" button
Drag & drop several product.
After a few drag & drop the width of the products decreases.
Depending on the width of the browser, a product of the 2nd line may move to the 1st line.

**Comment by PierrickOlivier** [comment]
Another problem with the drag & drop: it's very easy to move a product towards the left, but it's much more difficult to move a product towards the right.

**Comment by afoucret** [comment]
Main problem confirmed.
After one hour spent debugging still no idea of how this can happen.

At the same time I had a try to improve a little bit the sorter with :
* More compact design (make easier to move the items)
* Better placeholder during while moving the product

Here is a screenshot :

<img width="841" alt="capture d ecran 2018-02-14 a 10 38 01" src="https://user-images.githubusercontent.com/529238/36197130-40fb8b56-1173-11e8-9193-54e40581eb09.png">

What do you think about this ?

I will try to dig to find out why this small offset appears after we move items.

**Comment by romainruaud** [comment]
Haha @afoucret while working on the blacklist feature UX, I ended up to exactly the same design : moving the product name inside the "black box" to gain some space on top (I plan to have the "eye" button on top right).

Please let me know if you merge this on master so we are not conflicting

**Comment by djenvert** [comment]
Happy Valentine's Day, @afoucret and @romainruaud!

**Comment by afoucret** [comment]
I will merge on 2.5.x and master today.
Wait for it.

**Comment by PierrickOlivier** [comment]
It looks good ^^
Aboot the small offset, when I look at the <li> object I see that the width doesn't change but the offsetLeft property is set to a wrong value: 587 instead of 591.
![capture d ecran 2018-02-14 a 10 48 29](https://user-images.githubusercontent.com/20048184/36197701-ca0239a8-1174-11e8-8385-b693816316c7.png)

**Comment by afoucret** [comment]
Fixed by PR #753 
Will be part of the next maintenance release (2.5.2)

**Comment by afoucret** [comment]
Merged in 2.5.x and master.
