### ISSUE TITLE
Show out of stock at last in category and search page

### ISSUE THREAD

**Issue by rahul-bhandary** [Smile-SA/elasticsuite#764]
Reference to https://github.com/Smile-SA/elasticsuite/issues/754

It is working fine when default sort is applied. The above method doesn't work when any other sort is applied in category toolbar.

I had overwrite the class \Magento\Catalog\Block\Product\ProductList\Toolbar and applied my custom sort logic under setcollection method .

Does this effect the optimizer logic for sorting . I want to apply the Out OF Stock at last for all the sorting .

**Comment by afoucret** [comment]
Hi @rahul-bhandary,

I close this one since it duplicate #754 and we will continue the discussion in the original issue in order to keep issue tracking clean.
