### ISSUE TITLE
Virtual category added to menu not rewritten

### ISSUE THREAD

**Issue by CRYX2** [Smile-SA/elasticsuite#765]
When you create a virtual category and flag Add to menu, it's added correcly but is url is not rewritten. However, if you try to access the rewritten url it works correcly.

Magento Version : 2.2.2
ElasticSuite Version : 2.5
Environment : dev

### Steps to reproduce
1. Create a new virtual category like "On sale"
2. Flag Add to menu
3. Reindex and clear cache
4. Go to the frontend

### Expected result
1. The menu should be diplayed and the url should be the same on the admin (like "onsale.html")

### Actual result
1. The url is like: catalog/category/view/s/in-sconto/id/207

**Comment by romainruaud** [comment]
Hello @CRYX2 

Our module has nothing to do with URL Rewrite feature of Magento. 

I am actually not able to reproduce this bug on my test instance (Magento CE 2.2.2 and Elasticsuite 2.5).

Is it working for you on non-virtual categories ?

**Comment by CRYX2** [comment]
Yes It's all working correctly. I've investigated a bit and the problem seems on the getUrl() method called in Magento menu when it generate the tree for the virtual category

**Comment by romainruaud** [comment]
Are you creating a virtual category under another virtual category ?

**Comment by CRYX2** [comment]
No, only under Default root category

**Comment by afoucret** [comment]
The same as @romainruaud for me.
Unable to reproduce the bug.

**Comment by CRYX2** [comment]
I will try to investigate better to reproduce the problem

**Comment by CRYX2** [comment]
ok I solved, I had to enter for each store outside the main and save with a different alias. 
however it's strange, who it has behaved ONLY for the virtual category

**Comment by afoucret** [comment]
I close since it is unclear if the bug is related to ElasticSuite.
Feel free to reopen if you can confirm the issue is related to ElasticSuite and give us more information.
