### ISSUE TITLE
Memory Exhaustion when Viewing Certain Categories

### ISSUE THREAD

**Issue by phronesis** [Smile-SA/elasticsuite#77]
For a certain category and it's sub categories, we are experiencing memory exhaustion. This is actually happening for 1 category(Home Appliances) and most of its sub categories. It does not have the most number of products but this still happens. Just to test, i have tried increasing the php allowed memory size to 1G just to test. 
When this happens, a blank page shows on the frontend. My Catalog size is 9k and I am running elastic search on 2 aws ec2 servers with 2G each.

**Comment by phronesis** [comment]
Error From Logs:
PHP Fatal error:  Allowed memory size of 1077936128 bytes exhausted (tried to allocate 37748736 bytes) in /var/www/releases/d-ZYPRQ8DEG/vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Response/AggregationFactory.php on line 58" while reading response header from upstream, client: 172.31.9.215, server: _, request: "GET /home-appliances.html HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:",...

**Comment by phronesis** [comment]
Taking a closer look at it shows that memory gets exhausted when carrying out price aggregations. It happens in my Home Appliances category because it has the highest prices ranges: between like 5k and 2million. My immediate need will be to disable price aggregation and price slider and instead stick with the price layering my custom theme provides.

**Comment by phronesis** [comment]
I found how to remove prices from layered navigation in product attributes. That solved it, temporarily. I think you should look into changing price steps in layered navigation, your implementation makes price step 1 and does not seem to take into consideration the settings in Back Office Catalog Layered Navigation settings.

**Comment by afoucret** [comment]
Hi @phronesis,

We will have a look at this one.
To be honest it is quite unusual to have such an high price range and we had not managed this case.

**Comment by phronesis** [comment]
Thanks @afoucret. I understand. We are in Africa where the exchange rate of the dollar or Euro is quite high.. lol. That's why we have such price ranges.

**Comment by afoucret** [comment]
I traveled in Africa few months ago and I had the feeling of being a millionaire with the change rate between CFA and Euros.

We will try to provide a fix.

**Comment by romainruaud** [comment]
Hello @phronesis , you can check the PR #111 which takes into account the fact that the config parameter "Price Navigation Step Calculation" is set to "Manual" and then apply the value of "Default Price Navigation Step" for the interval.

This should be merged into 2.2.x branch really soon, but you can already take a look at it.

Best regards,

**Comment by romainruaud** [comment]
As I said, this is fixed by PR #111 

I close the issue, feel free to reopen it if needed.

**Comment by southerncomputer** [comment]
In : vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Aggregation/Builder/Histogram.php

Add min_doc_count=>'1' to reduce stress on elasticsearch engine and php!

 public function buildBucket(BucketInterface $bucket)
    {
        return ['histogram' => ['field' => $bucket->getField(), 'interval' => $bucket->getInterval(),'min_doc_count'=>'1']];
    }
