### ISSUE TITLE
Elasticsuite Tracker does not properly support ampersand in categories title (and probably in product names, cms pages title, etc)

### ISSUE THREAD

**Issue by rbayet** [Smile-SA/elasticsuite#771]
### Preconditions

Magento Version : EE 2.2.2

ElasticSuite Version : 2.5.0

Environment : Developer mode

Third party modules : lots, none related to search 

### Steps to reproduce

1. Name a category with an ampersand (&) in the title, for instance "Baby & Child"
2. Place a product in that category 
3. Navigate in frontend on the home page, the "Baby & Child" category, the product page, perform a search to find that product

### Expected result

1. After the cron:run reindexing of tracker events, events document should be present in the Elasticsearch index with the correct page title (category page event), category label (product page event)

### Actual result

1. The ampersand generates additional request parameters/variables
2. The original parameters/variables contain partial value and those extra parameters are pushed "as is" as empty ES document fields
3. Those bogus document fields become part of the mapping

![category_hit_event](https://user-images.githubusercontent.com/2353374/36433093-065c9dd0-165c-11e8-800e-894b33563f4b.png)

![product_hit_event](https://user-images.githubusercontent.com/2353374/36433161-2a00fede-165c-11e8-9264-3edaebe7ed85.png)

![mapping](https://user-images.githubusercontent.com/2353374/36433178-32a46ae4-165c-11e8-98a5-4ff360eaef1d.png)

**Comment by afoucret** [comment]
Fixed by PR #773
