### ISSUE TITLE
Category view, product sorting in frontend

### ISSUE THREAD

**Issue by gewaechshaus** [Smile-SA/elasticsuite#787]
Hello,

after updating elasticsuite to 2.5.3 by composer and elasticsearch to 5.6.8 (from 2.x) the category lists product sorting in frontend doesn't work anymore. I think this could be related to the elasticsearch scripting module. However, the script flags mentioned in the 2.x wiki (https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-2.x) 

    script.inline: on
    script.indexed: on

seems to be replaced in elasticsearch 5? 

We did replace script.indexed as it throws out a java exception. Can somebody who is deeper into elastic demistify this?

Another thing we noticed in context, is an error in magentos system.log
     
    main.INFO: Request Success: {"method":"GET","uri":"http://xx.xxx.xxx.xxx:920/live_default_catalog_product   /product/_search","headers":{...] 
    main.CRITICAL: Unable to unserialize value. [] []

Possible related to
https://github.com/Smile-SA/elasticsuite/blob/e0d4e5ea8488bc460467ace8b0d0a9f880e1bd92/src/module-elasticsuite-virtual-category/Plugin/Catalog/Category/SaveProductsPositions.php#L77

**Comment by afoucret** [comment]
Hi @gewaechshaus,

The scripting configuration have change in ElasticSearch 5.x.
As it is not required anymore in the last version of ElasticSuite, you can safely remove these lines of configuration.

I suspect, your serialization problem is related to a low `max_input_vars` config value.
You should consider setting it too an higher value (> 5000).
It is a common error we have with Magento.

Please tell me if it solve your issue.

**Comment by gewaechshaus** [comment]
Hi  @afoucret ,
many thanks for clarifying this. 

I did enlarge the `max_input_vars` to 6000(from default 1000) and the nesting from 64 to 128. Still logging the unserialize error and got those sorting problems.

**Comment by afoucret** [comment]
Did you clean the cache and have you reindex everything after the update ?

**Comment by gewaechshaus** [comment]
For sure, I did a indexer:reindex, cache:clean, cache:flush. As I didn't had an effect, I also restarted all related services

**Comment by afoucret** [comment]
To be clear : are you talking about the manual product sorting ?

**Comment by gewaechshaus** [comment]
Yes, we did sort all categories manualy. This works in backend, but doesn't work in frontend.

**Comment by afoucret** [comment]
OK. Think I got it.

**Comment by gewaechshaus** [comment]
Flushed the redis-cli, no effect. Stumbled upon https://magento.stackexchange.com/questions/194010/magento-2-2-unable-to-unserialize-value

**Comment by afoucret** [comment]
PR #790 will fix this one.
Will be part of release 2.5.4.

Feel free to test it and give us a feedback.

BR

**Comment by gewaechshaus** [comment]
Does work! Fixed. Many many thanks!!

**Comment by gewaechshaus** [comment]
@afoucret - and btw, mad respect for the merchandiser, real awesome

**Comment by afoucret** [comment]
The 2.5.4 release is out and contains the patch
