### ISSUE TITLE
How to use custom entity attribute values for autocomplete

### ISSUE THREAD

**Issue by pkbhadkoliya** [Smile-SA/elasticsuite#789]
### Preconditions
Unix 16.04 16GB RAM (Web Server)
-- NGINX 1.10.3
-- PHP 7.0.25

Unix 16.04 16GB RAM (Elasticsearch Server)
-- openjdk8
-- Elasticsearch 5.6.8

MySQL 5.7.19 8GB RAM

Magento Version : Magento 2.2.2 CE

ElasticSuite Version : 5.6.8

Environment : Production

Third party modules : None

### Steps to reproduce
1. Create Custom Entity called "Operator" and their attribute tables
2. Create "select" type Product Attribute "operator_id" with source_model which passes (id, name) for options. Keep searchable, filterable and autocomplete = true.
3. Assign few products with operator.
4. Reindex Data

### Expected result
1. It should show operators (by names) in autocomplete like it is showing other attributes.

### Actual result
1. It doesn't show operators in autocomplete, although it is showing it in side filters on category as well as search results page.

Have I missed anything? Does it require any custom development?

**Comment by afoucret** [comment]
What inside the eav_attribute and catalog_eav_attribute tables for your custom attribute ?

**Comment by pkbhadkoliya** [comment]
It is working fine now.

**Comment by afoucret** [comment]
Can you explain us what was missing ?

**Comment by pkbhadkoliya** [comment]
Not sure, but I deleted old "operator_id" attribute and created new "operator_id" attribute, and imported products again.

After reindexing, it started working fine.
