### ISSUE TITLE
how to add apply filter button with multiple select filters

### ISSUE THREAD

**Issue by goudas** [Smile-SA/elasticsuite#795]
we are using magento CE-2.2 with smile elastic suite2.4.6

Magento Version :MAGENTO-CE-2.2

ElasticSuite Version :2.4.6

Environment :developer

Third party modules :NA

### Steps to reproduce

1.how to stop reloading by selecting filters
2.how to add apply filters button on filters

### Expected result

1.onclick filters should not load

### Actual result

1. on selecting filter will load page

**Comment by afoucret** [comment]
Hi @goudas,

This feature can be implemented in your project by overriding the following templates shipped with ElasticSuite  :
* module-elasticsuite-catalog/view/frontend/templates/layer/filter/attribute.phtml
* module-elasticsuite-catalog/view/frontend/web/js/attribute-filter.js
*module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html

This is not something we will add out-of-the-box in the module.

BR,
