### ISSUE TITLE
isInline is not returning expected value

### ISSUE THREAD

**Issue by mageho** [Smile-SA/elasticsuite#800]
Magento Version : 2.2.0
ElasticSuite Version : 2.5.0
Environment : Developer Mode

----------------------------------------
About #784 
Fix broken layered navigation when using 1 column layout.
----------------------------------------

Good afternoon,

When we change the category view layout in xml for 1column, block's function isInline return always false.
Function IsInline only take in account category admin configuration.

Could you take a look ?

Thank you,

Ilan

**Comment by afoucret** [comment]
Can you post the XML you have used please. Will be easier to debug with

**Comment by mageho** [comment]
Good morning @afoucret,

We just add an attribute layout in catalog_category_view.xml :   
`<page layout="1column" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">`

To correct it, I just modified block Navigation 
(vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Block/Navigation.php)

Line 76,
`$this->pageLayout         = $context->getPageConfig()->getPageLayout() ?: $this->getLayout()->getUpdate()->getPageLayout();`
instead of
`$this->pageLayout         = $context->getPageConfig()->getPageLayout();`

Test it, and tell me if I am doing wrong.

Cheers,

Ilan PARMENTIER

**Comment by afoucret** [comment]
Hi @mageho,

If you submit your fix as a PR, I will be happy to review it and add it to the next maintenance release (2.5.5).

BR,

**Comment by afoucret** [comment]
Hi @mageho,

Since I haven't seen any PR, I postpone to 2.5.6.

BR,

**Comment by romainruaud** [comment]
I reproduce both the issue and his solution.

Will provide a PR to fix this one asap.

**Comment by afoucret** [comment]
Part of release 2.5.6
