### ISSUE TITLE
Escaped Javascript breaking virtual rules in admin

### ISSUE THREAD

**Issue by NathMorgan** [Smile-SA/elasticsuite#806]
### Preconditions
Magento Version : CE 2.1.12
ElasticSuite Version : 2.3.11
Environment : Developer / Production
Third party modules : N/A

### Steps to reproduce
1. View admin category page
2. Under 'Products in Category' tab

### Expected result
1. JS should be loaded and virtual rule working

### Actual result
Javascript escaped causing the virtual rule to break

`<' + 'script> require([ "Magento_Rule/rules", "prototype" ], function(VarienRulesForm){ window.virtual_rule = new VarienRulesForm("virtual_rule", "https://xxxx.test/admin/catalog_search_rule/product_rule/conditions/form/virtual_rule/element_name/virtual_rule/key/xxxx/"); }); <' + '/script>`

Seems to be coming from this line https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-virtual-category/Block/Adminhtml/Catalog/Category/VirtualRule.php#L62 The form contains JS removing escapeJsQuote seems to fix this issue

**Comment by afoucret** [comment]
Hi @NathMorgan,

The version you are using is quite old and not maintained anymore.
Please upgrade to a newer version and tell us if the problem is still there.

BR,
