### ISSUE TITLE
"Failed to parse value [0] as only [true] or [false] are allowed.

### ISSUE THREAD

**Issue by devhero-tech** [Smile-SA/elasticsuite#807]
Indexer blow up on first indexing
### Preconditions

PHP 7.0.27 (cli) (built: Jan 20 2018 14:08:57) ( NTS )
Mac OS x

Magento Version : 2.2.3

ElasticSuite Version : 6.2.2

Environment : Developer

Third party modules :

   "magento/product-community-edition": "2.2.3",
        "composer/composer": "@alpha",
        "snowdog/frontools": "^1.5",
        "snowdog/theme-blank-sass": "*",
        "dlambauer/magento2-module-backend-widget-imageupload": "^1.0",
        "magento/magento-composer-installer": "^0.1.12",
        "olegkoval/magento2-regenerate-url-rewrites": "^1.0",
        "smile/elasticsuite": "^2.5.0",
        "magefan/module-blog": "^2.6",
        "magepal/magento2-gmailsmtpapp": "^1.5",
        "magepal/magento2-googletagmanager": "^2.0",
        "mageplaza/magento-2-seo-extension": "^2.0",
        "hellobrave/cookiecompliance": "^1.0"

### Steps to reproduce

1.  php n98-magerun2.phar indexer:reindex

### Expected result

1. Indexes should be rebuild

### Actual result

1.  php n98-magerun2.phar indexer:reindex
Design Config Grid index has been rebuilt successfully in 00:00:00
Customer Grid index has been rebuilt successfully in 00:00:12
Category Products index has been rebuilt successfully in 00:00:02
Product Categories index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:01
Product EAV index has been rebuilt successfully in 00:00:01
Stock index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:00
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Catalog Search indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [0] as only [true] or [false] are allowed."}],"type":"illegal_argument_exception","reason":"Failed to parse value [0] as only [true] or [false] are allowed."},"status":400}
ElasticSuite Category Indexing indexer process unknown error:
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Failed to parse value [0] as only [true] or [false] are allowed."}],"type":"illegal_argument_exception","reason":"Failed to parse value [0] as only [true] or [false] are allowed."},"status":400}
ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:00```

**Comment by afoucret** [comment]
Hi @devhero-tech,

This bug is caused by using ElasticSearch 6.x with ElasticSuite.
As explained in the wiki, we do not support ElasticSearch 6.x yet (https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall). Downgrade your ElasticSearch server to 5.x and everything should work fine (do not forget to install plugin as described here : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-5.x).

ElasticSearch 6.x support should come with the next major release of ElasticSuite (2.6.0).

BR,
