### ISSUE TITLE
Multiselect "AND" filter options

### ISSUE THREAD

**Issue by ghost** [Smile-SA/elasticsuite#819]
Unix 16.04 16GB RAM (Web Server)
-- NGINX 1.10.3
-- PHP 7.0.25

Unix 16.04 16GB RAM (Elasticsearch Server)
-- openjdk8
-- Elasticsearch 5.6.8

MySQL 5.7.19 8GB RAM

Magento Version : Magento 2.2.3 CE

ElasticSuite Version : 5.6.8

Environment : Production

Third party modules : None

Steps to reproduce
1. Create "multiselect" type Product Attribute, called tags. Keep it filterable.
2. Assign few products with multiple tags.
3. Reindex data.
4. Navigate to category page which has products added to it.
5. Apply tags filter with "tag 1" and "tag 2".

Expected result
It should show products which has "tag 1" AND "tag 2" assigned.

Actual result
It shows all products which has either "tag 1" OR "tag 2" assigned.

How can change "OR" behaviour to "AND".

**Feature Request:**
In Admin Panel, while adding/editing attribute, can we add 2 more options:
1) Selection Type: Checkbox / Radio
-- Selection Type will be used to display Radio UI or Checkbox UI on frontend filters section. If it is "radio" typed, only one option can be selected while applying filter.
2) Filter Type: AND / OR
-- Filter Type is only applicable when Selection Type is "Checkbox".

**Comment by afoucret** [comment]
Hi @pkbhadkoliya,

This is not a feature we have planned. If you are really interested in such a feature, I can invite you to contribute it and I will be happy to review some PR from you.

I let the issue open as a community poll. We could plan it if there is lot of people voting for it.

**Comment by pczerkas** [comment]
+1

**Comment by nsiebler-dm** [comment]
@pkbhadkoliya @afoucret 
The "AND / OR" feature would be really great on the roadmap. One thing to consider is how to present this visually if there are mixed types in use. It could be confusing for the visitor. So from the user perspective it would be even more flexible and feature rich to let the visitor intuitively choose which type he wants to apply.

We have a few clients which asked for this feature specifically.

**Comment by romainruaud** [comment]
Implement in 2.10.4 version (finally !) : https://github.com/Smile-SA/elasticsuite/releases/tag/2.10.4

I close
