### ISSUE TITLE
Slider filter does not work with negative values

### ISSUE THREAD

**Issue by fabio-coutinho** [Smile-SA/elasticsuite#821]
### Preconditions
NGINX 1.12.2
PHP 7.0.25
Elasticsearch 5.6.8

Magento Version : 2.2.2 CE
ElasticSuite Version : 2.4.0
Environment : Developer mode

### Steps to reproduce
1. Create a new attribute that enables slider filtering as defined in https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration
2. Set negative values in the attribute; in the example below I set 3 products with the following values -- Temperature=-10 Temperature=-15, Temperature=-25
3. Search for the products that the attribute was set
4. The Slider should show up just fine on the layered navigation, but if you filter it does not return any result 

### Expected result
1. The results should filter the negative values according to the slider

### Actual result
1. The filter is not performed correctly as shown below:

Before filtering:
![image](https://user-images.githubusercontent.com/36739803/37476050-e93c5642-2852-11e8-8b12-9d37f28338ed.png)

After changing filter:
![image](https://user-images.githubusercontent.com/36739803/37476066-f94a21c2-2852-11e8-84d8-f7987103128f.png)

After pressing OK:
![image](https://user-images.githubusercontent.com/36739803/37476090-0bfbbea2-2853-11e8-963e-037a9b1e550b.png)

It seems that since the filter uses the character "-" as the range separator, the engine is not able to parse numbers that have a minus signal on its values.

**Comment by afoucret** [comment]
PR #822 have been merged.
Will be part of the next bugfix release (2.5.6)

BR.
