### ISSUE TITLE
No search results for: '"thunderbolt 3" video'. We propose you approaching results.

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#84]
We propose you approaching results.

I'm not sure what happened here but this is not well versed english.

in the english and french i18 csv files!

Sorry to open a ticket but I could not find one that was appropriate to post to!

**Comment by rootindex** [comment]
I'm suggestion the following as it would have a greater impact : 

`We didn't find XYZ, perhaps you looked for <a href="%1">XYZZ</a>, <a href="%2">XYZY</a> or <a href="%3">XYZX</a>`

With the same search results shown as before.

**Comment by romainruaud** [comment]
@southerncomputer we plan to change it to "No exact results found for %s. The displayed items are the closest matches".

What do you think about it ?

@rootindex : we keep in mind the idea to implement a "Did you mean ?" feature according to your proposal. Thank you.
