### ISSUE TITLE
unable to install module facing the issue

### ISSUE THREAD

**Issue by ranu7455** [Smile-SA/elasticsuite#841]
unable to install module facing the issue as attached, 
 while running setup upgrade command following errors are happening
![capture](https://user-images.githubusercontent.com/36107844/38117490-ed3903ea-33d2-11e8-8468-8d3ee66bccac.JPG)

**Comment by romainruaud** [comment]
@ranu7455 you have to respect the issue template if you want us to provide efficient help.

I close this issue for now, please open a new one and fill all fields related to component versions (php, magento, etc...)
