### ISSUE TITLE
I am unable to uninstall this extension from magento 2.2.2?

### ISSUE THREAD

**Issue by bansalkapil** [Smile-SA/elasticsuite#843]
I am using magento 2.2.2 website. 

http://1.6.46.132/eurostyles/

I was installed Smile-SA/elasticsuite in my website. 
using this commend 
composer require smile/elasticsuite
after that I enable all module 
bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker

Now I want to uninstall all the module, But am only able disable the modules.
Please suggest what Should I need to do If I want to remove  Smile-SA/elasticsuite completely form my website.

Thanks in advance!

**Comment by romainruaud** [comment]
Hello,

please see the wiki for module uninstalling: https://github.com/Smile-SA/elasticsuite/wiki/ModuleUninstall

Regards
