### ISSUE TITLE
Blocking Integration Tests: Disable functionality via config option?

### ISSUE THREAD

**Issue by kdeubert** [Smile-SA/elasticsuite#845]
I'm working on a customer project which uses the smile/elasticsuite module. We are developing some other custom modules with Integration Tests, and some CI as a service platforms (i.e. bitbucket pipelines) do not have easy/cheap ways to include elasticsearch instances.

Without further changes to magento setup or module structure, I can't seem to find a good way to execute the integration tests without being blocked by missing elasticsearch node.

I found this very helpful article in the wiki (https://github.com/Smile-SA/elasticsuite/wiki/ModuleInstall) about installing and setting configuration options.

Maybe there is some (hidden?) setting that I can use in my case?
Or some boilerplate code for an elasticsearch test adapter?

I'm also not 100% sure if the module should support any of this, or if it is more of a magento issue (like magento setup:install call with a --skip-modules call), I'm open for any ideas.

Since the default integration test setup includes a setup:install call, and the generated sandbox is not present before, there is currently no way to just execute a module:disable before executing tests.

### Preconditions
- Magento 2.2 CE
- Elasticsuite ^2.5
- bitbucket pipelines (ubuntu 14, docker)
- magento integration tests execution

### Steps to reproduce
1. Have module present in composer.json
2. Have no elasticsearch instance available
3. Try to execute magento integration tests

### Expected result
1. Be able to test everything not related to elasticsuite

### Actual result

`+ ../../../bin/phpunit --log-junit ~/test-reports/junit-integration.xml --testsuite=CustomIntegration
Exception: Unable to connect ElasticSearch server : No alive nodes found in your cluster
SQLSTATE[HY000] [2002] No such file or directory

  [InvalidArgumentException]
  Parameter validation failed

Exception trace:
 () at /opt/atlassian/pipelines/agent/build/magento/setup/src/Magento/Setup/Console/Command/InstallCommand.php:189
 Magento\Setup\Console\Command\InstallCommand->initialize() at /opt/atlassian/pipelines/agent/build/magento/vendor/symfony/console/Command/Command.php:207
 Symfony\Component\Console\Command\Command->run() at /opt/atlassian/pipelines/agent/build/magento/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at /opt/atlassian/pipelines/agent/build/magento/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /opt/atlassian/pipelines/agent/build/magento/vendor/magento/framework/Console/Cli.php:104
 Magento\Framework\Console\Cli->doRun() at /opt/atlassian/pipelines/agent/build/magento/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /opt/atlassian/pipelines/agent/build/magento/bin/magento:23

setup:install [--backend-frontname BACKEND-FRONTNAME] [--es-hosts ES-HOSTS] [--es-enable-ssl] [--es-user ES-USER] [--es-pass ES-PASS] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user ADMIN-USER] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-firstname ADMIN-FIRSTNAME] [--admin-lastname ADMIN-LASTNAME] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [-i|--interactive] [--magento-init-params MAGENTO-INIT-PARAMS]

 in /opt/atlassian/pipelines/agent/build/magento/vendor/magento/framework/Shell.php:61
Stack trace:
#0 /opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/framework/Magento/TestFramework/Application.php(466): Magento\Framework\Shell->execute('/usr/local/bin/...', Array)
#1 /opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/framework/bootstrap.php(77): Magento\TestFramework\Application->install(false)
#2 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/Util/Fileloader.php(61): include_once('/opt/atlassian/...')
#3 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/Util/Fileloader.php(45): PHPUnit\Util\Fileloader::load('/opt/atlassian/...')
#4 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(915): PHPUnit\Util\Fileloader::checkAndLoad('/opt/atlassian/...')
#5 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(737): PHPUnit\TextUI\Command->handleBootstrap('/opt/atlassian/...')
#6 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(152): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#8 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#9 {main}

Next Magento\Framework\Exception\LocalizedException: Command returned non-zero exit code:

`/usr/local/bin/php -f '/opt/atlassian/pipelines/agent/build/magento/bin/magento' setup:install -vvv --db-host='localhost' --db-user='root' --db-password='123123q' --db-name='magento_integration_tests' --backend-frontname='backend' --admin-user='user' --admin-password='password1' --admin-email='admin@example.com' --admin-firstname='firstname' --admin-lastname='lastname' --magento-init-params='MAGE_DIRS[etc][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/etc&MAGE_DIRS[var][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var&MAGE_DIRS[media][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/pub/media&MAGE_DIRS[static][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/pub/static&MAGE_DIRS[view_preprocessed][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/view_preprocessed/pub/static&MAGE_DIRS[code][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/generated/code&MAGE_DIRS[cache][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/cache&MAGE_DIRS[log][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/log&MAGE_DIRS[session][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/session&MAGE_DIRS[tmp][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/tmp&MAGE_DIRS[upload][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/var/upload&MAGE_DIRS[pub][path]=/opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/tmp/sandbox-0-9cbea49b09ade00f1a2545a9d91a0f62/pub&MAGE_MODE=developer' 2>&1` 

in /opt/atlassian/pipelines/agent/build/magento/vendor/magento/framework/Shell.php:62
Stack trace:
#0 /opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/framework/Magento/TestFramework/Application.php(466): Magento\Framework\Shell->execute('/usr/local/bin/...', Array)
#1 /opt/atlassian/pipelines/agent/build/magento/dev/tests/integration/framework/bootstrap.php(77): Magento\TestFramework\Application->install(false)
#2 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/Util/Fileloader.php(61): include_once('/opt/atlassian/...')
#3 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/Util/Fileloader.php(45): PHPUnit\Util\Fileloader::load('/opt/atlassian/...')
#4 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(915): PHPUnit\Util\Fileloader::checkAndLoad('/opt/atlassian/...')
#5 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(737): PHPUnit\TextUI\Command->handleBootstrap('/opt/atlassian/...')
#6 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(152): PHPUnit\TextUI\Command->handleArguments(Array)
#7 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#8 /opt/atlassian/pipelines/agent/build/magento/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#9 {main}

=== Memory Usage System Stats ===
Memory usage (OS):	43.84M (219.22% of 20.00M reported by PHP)
Estimated memory leak:	23.84M (54.38% of used memory)`

**Comment by romainruaud** [comment]
Hello @kdeubert 

I do not know well the Bitbucket pipelines, but since you are running the Magento install process with your CI, I'm nearly sure you are using a MySQL service to test the install process, aren't you ?

If this is the case, do you have any option to add an Elasticsearch service to your pipeline ?

**Comment by kdeubert** [comment]
Hi @romainruaud

thank you for your reply. You are correct, I'm using a mysql service with bitbucket pipelines. MySQL is one of a few predefined bitbucket pipelines service templates.
The install process execution is part of the default magento2 integration test framework.

I already tried adding an Elasticsearch service to the environment, and there are two ways:

1) Try to install Elasticsearch to the container running the build.
I tried several approaches to this (adding custom repositories, using prebuilt packages) but all of them fail into some kind of D-Bus error, which seems to be related to bitbucket pipeline container restrictions.

`+ systemctl start elasticsearch
Failed to get D-Bus connection: Unknown error -1`

2) Add Elasticsearch as separate service Container.
This only works, and I also found some forum entries/related similar search results, when building and maintaining a custom docker image yourself. While it sounds like the right way, it seems like a lot of work. In our particular case, there would also be additional cost for a second service container we don't want to test against.

**Comment by romainruaud** [comment]
Well then I'm afraid we have no solution for the moment...

If you plan to test your entire application, you will need to have a running Elasticsearch server to ensure testability, since the search engine is imho as important as the DB on an e-commerce website. 

It would make irrelevant to test the application without any search engine, as it would be to test it without any MySQL running.

From what I've read about ES on Bitbucket pipelines, it seems that the best solution is to run it as a separate service container, you are right. The docker image is not as hard to built, since it only requires the installation of mandatory plugins (`analysis-phonetic` and `analysis-icu`) over a standard ES container.

I let the issue open for now to give us some times to think about it.

Best regards

**Comment by kdeubert** [comment]
I don't share your opinion on all listed points, but I understand and accept that solving my issue is not really related to just the elasticsuite module itself, but should be solved in the magento 2 integration testing setup.

Thank you for your time.

As a quick workaround, building and using a docker elasticsearch image as service container, including the mandatory plugins you listed, was not hard at all.

Dockerfile:
`FROM elasticsearch:2.4.6

RUN /usr/share/elasticsearch/bin/plugin install analysis-phonetic && \
    /usr/share/elasticsearch/bin/plugin install analysis-icu
`

**Comment by romainruaud** [comment]
In fact I am wondering about one point : when using legacy Magento2 Commerce (no Elasticsuite embedded) with Elasticsearch as search backend, do the integration test work ?

I'm not sure it's the case since the `Magento_CatalogSearch` module is also triggering a `reindexAll` when installing, so this may fail if no running Elasticsearch instance is found, even with legacy codebase.

Glad to see that you were able to solution your problem with using a custom docker image, please note that we plan to drop ES 2.x support in next Elasticsuite version, so you may have to switch to an ES 5.x based image to ensure everything continue to work.

By the way, thank you for testing our module and for contributing your thoughts here and raising this specific topic.

Best regards
