### ISSUE TITLE
Tracking code inside javascript, pinging back to t.smile.eu

### ISSUE THREAD

**Issue by HRR1337** [Smile-SA/elasticsuite#85]
Hello, 

Was wondering why the server is pinging back, and why/what is tracked:

// Send the tag to the remote server
    // Append a transparent pixel to the body
    function sendTag(forceCollect) {
        if (this.trackerSent === false || forceCollect === true) {
            var trackingUrl = getTrackerUrl.bind(this)();
            var bodyNode = document.getElementsByTagName('body')[0];
            var imgNode = document.createElement('img');
            imgNode.setAttribute('src', trackingUrl);
            setTrackerStyle(imgNode);
            bodyNode.appendChild(imgNode);
            this.trackerSent = true;
            this.vars = {};

            if (window.location.protocol === "http:") {
                var extImgNode = document.createElement('img');
                extImgNode.setAttribute('src', "http://t.smile.eu/h.png?magento2");
                setTrackerStyle(extImgNode);
                bodyNode.appendChild(extImgNode);
            }
        }
    }

Thanks.

**Comment by afoucret** [comment]
The module Smile_Tracker add this tracking transparent pixel.
It is used only to track the adoption of the module. 
The only usage of this is providing stats of the number of install of ElasticSuite and evaluating the community size.

The other purpose of this module is to generate data, that are not sent to Smile but are only present in your access log. Such data will be used in the future to generate improvement of the user experience using behavioral mechanisms (recommandations, better autocomplete, ranking improvements, ...). Here is an example on our demo website :
```
http://demo.magento-elastic-suite.io/static/version1468316817/frontend/Magento/luma/en_US/Smile_ElasticsuiteTracker/hit.png?page.store_id=1&page.type.identifier=catalog_category_view&page.type.label=Catalog%20Category&page.category.id=21&page.category.label=Tops&page.category.path=1/2/20/21&page.product_list.page_count=5&page.product_list.product_count=50&page.product_list.current_page=1&page.product_list.sort_order=position&page.product_list.sort_direction=asc&page.product_list.display_mode=grid&session.uid=0ba814d6-f160-d0ea-535c-e8c43f300a7d&session.vid=40d5f6bc-f7d9-a538-dfa2-d187904e168d&page.site=demo.magento-elastic-suite.io&page.url=/index.php/women/tops-women.html&page.title=Tops%2520-%2520Women&page.time=1468830133&page.referrer.domain=demo.magento-elastic-suite.io&page.referrer.page=/&page.resolution.X=1920&page.resolution.Y=1177```
