### ISSUE TITLE
Support sensitive / environment specific configuration

### ISSUE THREAD

**Issue by nicobatty** [Smile-SA/elasticsuite#850]
ElasticSuite servers, authentication type, user and password should be declared as sensitive / environment specific configurations.

http://devdocs.magento.com/guides/v2.2/extension-dev-guide/configuration/sensitive-and-environment-settings.html

**Comment by romainruaud** [comment]
Hello @nicobatty 

Thank you for pointing us this.

I think you are right.

Regards

**Comment by afoucret** [comment]
PR #857 has been merged and will be part of the next maintenance release (2.5.7).
