### ISSUE TITLE
Exception and no alive nodes found

### ISSUE THREAD

**Issue by DevXeni** [Smile-SA/elasticsuite#851]
Hi!
I'm trying to install smile/elasticsuite, I use amazon aws elasticsearch v5.5, 
I use endpoint AWS ES:

smile/smile_elasticsuite_core_base_settings/servers ***us-east-1.es.amazonaws.com

and

smile_elasticsuite_core_base_settings/es_client/enable_https_mode 1

because endpoind supports https.

All steps described in the documentation are passed, exept

> bin/magento setup:upgrade

On this step, after few minutes, I've got a message: "No alive nodes found in your cluster".

But I can connect to endpoint 

> curl -XGET 'https://***us-east-1.es.amazonaws.com 

and there is all plugins installed:

> curl -XGET 'https://***us-east-1.es.amazonaws.com/_cat/plugins?pretty'

pfp9Rkr analysis-icu 5.5.2
pfp9Rkr analysis-kuromoji 5.5.2
pfp9Rkr analysis-phonetic 5.5.2
pfp9Rkr analysis-seunjeon x.x.x.x
pfp9Rkr analysis-smartcn 5.5.2
pfp9Rkr analysis-stempel 5.5.2
pfp9Rkr analysis-ukrainian 5.5.2
pfp9Rkr discovery-ec2 5.5.2
pfp9Rkr elasticsearch-jetty 2.2.0
pfp9Rkr ingest-attachment 5.5.2
pfp9Rkr ingest-user-agent 5.5.2
pfp9Rkr mapper-attachments 5.5.2
pfp9Rkr mapper-murmur3 5.5.2
pfp9Rkr mapper-size 5.5.2
pfp9Rkr repository-s3 5.5.2
OwW3GjV analysis-icu 5.5.2
OwW3GjV analysis-kuromoji 5.5.2
OwW3GjV analysis-phonetic 5.5.2
OwW3GjV analysis-seunjeon x.x.x.x
OwW3GjV analysis-smartcn 5.5.2
OwW3GjV analysis-stempel 5.5.2
OwW3GjV analysis-ukrainian 5.5.2
OwW3GjV discovery-ec2 5.5.2
OwW3GjV elasticsearch-jetty 2.2.0
OwW3GjV ingest-attachment 5.5.2
OwW3GjV ingest-user-agent 5.5.2
OwW3GjV mapper-attachments 5.5.2
OwW3GjV mapper-murmur3 5.5.2
OwW3GjV mapper-size 5.5.2
OwW3GjV repository-s3 5.5.2

and AWS ES 5.5 supports

> /_termvectors (Index only)

Why I've got this message "No alive nodes found in your cluster"?

Additionally, in var/report files was found:

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. The following modules are outdated: Smile_ElasticsuiteThesaurus data: current version - none, reqrequired version - 1.1.0 Smile_ElasticsuiteVirtualCategory data: current version - none, required version - 1.1.0

Please, maybe you can provide explanation?
Thank you for your excellent work :)

**Comment by romainruaud** [comment]
I am actually able to reproduce your issue.

I have a working ES instance on an https host, reachable via cURL, but not by Elasticsuite.

I am investigating and will keep you in touch.

Regards

**Comment by DevXeni** [comment]
Hi, just now, I checked dependent module elasticsearch/elasticsearch and this problem caused because that module setup default port to 9200 if it was not specified. Therefore, I specify the port as mydomain.com:443 and all works fine. 
This issue not about smile/elasticsuite module at all. 
Thank you and have a nice day!
Closed.

**Comment by romainruaud** [comment]
Yep, 

I was about to answer that I went to the same conclusion, you have to specify the port 443 because having the scheme set to https is not enough.

Glad to see this one solved.

Regards
