### ISSUE TITLE
How to disable collapsing of facets?

### ISSUE THREAD

**Issue by DocOlson** [Smile-SA/elasticsuite#859]
How can I disable the collapsing of facets? I don't really need this feature. But my facets initially all show the first option only and expand on click to show the rest.

Thank you

**Comment by romainruaud** [comment]
Hello @DocOlson 

What do you mean by the "collapsing of facets" ? 

- If you are speaking about the number of expanded facets by default, this is configurable via **Store > Configuration > Smile Elasticsuite > Expanded facets**

- If you are speaking about the "show more / show less" which is displayed when a filter has more than X value, you can configure the "X" value for each attribute as stated here by changing the "Facet max. size" value : https://github.com/Smile-SA/elasticsuite/wiki/Attribute-configuration#faceting-configuration

Best regards

**Comment by DocOlson** [comment]
Thank you. That's a new option I was not aware of.
