### ISSUE TITLE
Anchor attribute in InstallData.php

### ISSUE THREAD

**Issue by micmeister59** [Smile-SA/elasticsuite#86]
Hi,

Between https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/Setup/InstallData.php and https://github.com/Smile-SA/elasticsuite/blob/2.2.x/src/module-elasticsuite-catalog/Setup/InstallData.php, there is a difference with "updateAttributeDefaultValue" method and "is_anchor" parameter: a new "excludedIds" parameter is added.

I have an issue with "is_anchor" attribute of "tree root id" category which is set to 1 because of master version, I guess. Indeed, I can't add category when I try to save a product.

Should we force "is_anchor" attribute of "tree root id" category to 0 in a update data setup?

Thanks,

**Comment by afoucret** [comment]
There is an update that fix a bug with Magento 2.1.

If you are using Magento 2.1, you must fix it manually. It will be part of the upgrade notice when we will finalize the next version.
