### ISSUE TITLE
Get products from virtual category by categoryID?

### ISSUE THREAD

**Issue by jellesiderius** [Smile-SA/elasticsuite#862]
Is it possible to get a product collection just by categoryID?

Preconditions
OS: Linux debian-8 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
Magento Version: 2.2.3 CE
ElasticSuite Version: 2.5
Environment: developer

**Comment by romainruaud** [comment]
Hello @jellesiderius 

Please detail a bit more what you are trying to do.

If you are planning to retrieve an Elasticsearch based collection filtered on a given category, you can instantiate the Fulltext product collection and use the `addCategoryFilter` method, like this : 


```
use Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\CollectionFactory as FulltextCollectionFactory;

$productCollection = $this->collectionFactory->create();
$productCollection->addCategoryFilter($categoryId);
```

Regards
```
