### ISSUE TITLE
Configurable products shown in virtual category as discounted products, when they are not

### ISSUE THREAD

**Issue by dverkade** [Smile-SA/elasticsuite#866]
Configurable products shown in virtual category as discounted products, when they are not

### Preconditions
Magento Version : 2.2.3
ElasticSuite Version : 2.5.4
Environment : Production mode

### Steps to reproduce
1. Create a configurable product with different sizes. The price needs to be different per simple product.
2. Create a virtual category where you have all products which are in stock & are discounted.

### Expected result
1. Configurable products where the simple price is different and which do not have a special price should not be shown in the virtual category. 

### Actual result
1. Products are shown in the virtual category. 

![image](https://user-images.githubusercontent.com/1058480/38754023-8d804f46-3f60-11e8-8e06-48843497a495.png)
![image](https://user-images.githubusercontent.com/1058480/38754047-9a36701c-3f60-11e8-911c-4e850c1793f8.png)

**Comment by afoucret** [comment]
Confirmed when simple price are not all equals.

**Comment by romainruaud** [comment]
Not sure how we could fix this one easily. 

For now we rely on the `catalog_product_index_price` table and this does not seem to be enough to differentiate these 2 cases : 

- product has many children of different prices. These children have no special price. => should NOT have `is_discounted`

- one of the children product has a special price. => product should have `is_discounted`

any advice @afoucret  ?

**Comment by moejoee91** [comment]
Hello, 
any fix planned for this? or any work around available for now ?

**Comment by afoucret** [comment]
Hi @moejoee91, 

I am currently braimstorming on this one. The technical part is quite easy but this bug highlight a functional issue I will explained later. Without a clean functional solution it will be useless to solve this issue.

**Comment by amenk** [comment]
We had this issues mentioned in #1140 and https://magento.stackexchange.com/questions/247097/price-filter-returns-wrong-results-price-ist-stored-as-0-insteal-of-null-and-i with the price index in 2.1.6 -- now we are on 2.1.8 and believe the price index is in a bit better shape

Simples work fine now, but configurables are wrongly tagged as is_discounted

* min_price and max_price seem to be right
* but price is now 0 in the index for configurables.

and  is_discounted becomes true, which it should not.

The question we are asking ourselves now is, what should be the price for configurables in the price index -- actually I think "0" is quite correct, because normally a configurable does not have a price. But how could the is_discounted indexing then work of elastic suite?

**Comment by amenk** [comment]
ping @romainruaud  ;-)

**Comment by amenk** [comment]
[ElasticSuite is assuming ](https://github.com/Smile-SA/elasticsuite/blob/2.8.x/src/module-elasticsuite-catalog/Model/Product/Indexer/Fulltext/Datasource/PriceData/PriceConfigurable.php) that the price (actual price) is in min_price in the index and original price is in max_price in the index.

I think this is a basic design problem: If I have a configurable T-Shirts where S cost 9 € and M costs 10€ of course min_price is 9 and max_price is 10 --> then elasticsuite is assuming we have a discounted product.

**Comment by amenk** [comment]
> I am currently braimstorming on this one. The technical part is quite easy but this bug highlight a functional issue I will explained later. Without a clean functional solution it will be useless to solve this issue.

@afoucret Was there any result of the brainstorming :-D

**Comment by amenk** [comment]
I am trying to tackle this but have problems to debug into 

     \Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\PriceData::addData

Does anybody have a hint to to write a test which triggers that one? Currently I am saving a product and run the cron which is super cumbersome.... Trying to write an integration test for that but have to understand the architecture more

**Comment by amenk** [comment]
@romainruaud @dverkade  I developed a patch for this https://github.com/Smile-SA/elasticsuite/pull/1411

**Comment by gkueny** [comment]
Hello @afoucret,

I'm currently facing this issue, and I saw that you mentioned braimstorming about the problem (https://github.com/Smile-SA/elasticsuite/issues/866#issuecomment-388730916)

It's a bit old, but do you remember the conclusion?

Have a good weekend,

**Comment by Mbertu** [comment]
Maybe a stupid question, but why you don't look inside the table catalogrule_product or catalogrule_product_price to get if a product has a catalog rule applied?

**Comment by Bashev** [comment]
Can someone reviewing my pull request? I think is better than previous one and for now works as expected on few production environments.
