### ISSUE TITLE
Search Result Page not displaying the products based off query

### ISSUE THREAD

**Issue by TenzinNKhando** [Smile-SA/elasticsuite#867]
Search Result Page is not showing the products which match the query. I noticed that the autocomplete shows better results than the result page and those same products don't appear on the search result until page 3 or 4.

Is there a configuration that I need to change to show the same type of results?

### Preconditions

Magento Version : CE 2.1.5
ElasticSuite Version : 2.3.0
Environment : Production

### Expected result

I expect to see products from the autocomplete and products on page 3 on the first page.

### Actual result

1. You can visit our website and do the same search.
     https://www.americanretailsupply.com
     https://www.americanretailsupply.com/catalogsearch/result/?q=display+case

![image](https://user-images.githubusercontent.com/13293090/38754717-c646f88c-3f17-11e8-8783-a2b039678fcf.png)

Different from the products shown in the autocomplete. Also shows closeable bags, hangers, labels, and other not relevant products.
![image](https://user-images.githubusercontent.com/13293090/38754762-eb9f0e58-3f17-11e8-904d-3adc8ed48d53.png)

Not until page 3 does it start to show the products that we want.
![image](https://user-images.githubusercontent.com/13293090/38754877-6a43eddc-3f18-11e8-970f-f7e662a9655f.png)

**Comment by afoucret** [comment]
Two things there : 

1. You are using an outdated version of ElasticSuite. I would advice to update to a newer version.

2. Relevance problem depends a lot on your catalog and the way relevance is tuned. We can not deliver valuable advice without having an audit of both your catalog and your setup. This kind of service is not part of our open source commitment but we can help through our commercial support of the extension.

BR,
