### ISSUE TITLE
Search Result Page can't find products by SKU 

### ISSUE THREAD

**Issue by TenzinNKhando** [Smile-SA/elasticsuite#868]
Can't find products by SKU on the Search Page even though the product is enabled and in stock. This isn't always the case, sometimes it does pull the right product and directs me to the product details page. Other times it finds the product on the search page but the warning still appears stating that the product isn't found.

How can I set it so that SKU is a parameter to search and remove the warning if it finds a match? The same way that **SKU that does work**

### Preconditions

Magento Version : CE 2.1.5
Environment : Production
ElasticSuite Version : 2.3.0

### Expected result

1. I search for a product by SKU
2. I should see the product in the autocomplete
3. No warning should appear unless the product has been disabled or not there

### Actual result

1. I search for a product by SKU

## **SKU that can't be found**
1. 703222
2. 6836EL

![image](https://user-images.githubusercontent.com/13293090/38755897-5644a2dc-3f1c-11e8-96e4-9be83ad1d191.png)

## **SKU that does work**
1. 701222
2. C73PT15B

![image](https://user-images.githubusercontent.com/13293090/38756368-2096e4e0-3f1e-11e8-9837-d11ed021b9ce.png)

## **SKU that does work but a warning appears**
1. 6834EL
2. 6837EL
3. 790402B

![image](https://user-images.githubusercontent.com/13293090/38755460-9fd492e2-3f1a-11e8-960e-cbf406e1e011.png)

**Comment by afoucret** [comment]
Hi @TenzinNKhando,

The search by SKU topic have been discussed in many issues that are now closed (#100, #829 , #759, #524 , #797). Most of them have been fixed in version 2.4.x and 2.5.x.

I would advice you to update to the latest stable version to get more accurate SKU search (some additional improvement are coming in version 2.6.x).

BR,
