### ISSUE TITLE
RFC : Advanced Search Support

### ISSUE THREAD

**Issue by haresh208** [Smile-SA/elasticsuite#88]
Hello,

I have installed this extension for my project and search and autocomplete is working fine. But when i am trying to search via advanced search then it shows the blank page.

I have already seen the same error on your demo site.

So can you please help to solve this error?

Thanks

**Comment by afoucret** [comment]
The advanced search is not yet implemented.
We will have a focus on it for version 2.3.

**Comment by southerncomputer** [comment]
btw, when is 2.2 going to be ready to use with magento 2.1 EE?

**Comment by afoucret** [comment]
PR #225 have been merged.

Two additional things to be done in order to close this issue :

* Restore the advanced search link into the header

* On range filters (eg price), you should be able to fill only one bound (eg. price >= 60 only). Currently you have an empty result if you fill only one.

**Comment by romainruaud** [comment]
@afoucret I do not see any advanced search link into the header of a raw Magento2 instance. There is a link in the footer but our extension did not disabled it previously.

I fixed the range filter and will PR this asap.

**Comment by afoucret** [comment]
OK for the link in header. It was only in Magento 1.x.
I merge the PR #226 
I close the issue then.
