### ISSUE TITLE
Nested filter error

### ISSUE THREAD

**Issue by vgrygor2** [Smile-SA/elasticsuite#881]
### Preconditions
Magento Version : EE 2.2.3
ElasticSuite Version : 2.5
Elasticsearch version : 2.4.5
Environment : developer

Third party modules : no

### Steps to reproduce
1. Go to category page on frontend

### Expected result
1. Products appeared 

### Actual result
1. No products matching the selection
2. Error present in log file:
[2018-04-18 10:22:16] report.ERROR: [500 Server Exception] illegal_state_exception: child query must only match non-parent docs, but parent docID=4 matched childScorer=class org.apache.lucene.search.ConjunctionScorer [] []

Request is the following:

`array(5) { ["http_method"]=> string(3) "GET" ["scheme"]=> string(4) "http" ["uri"]=> string(49) "/magento2_default_catalog_product/product/_search" ["body"]=> string(1316) "{"size":9,"sort":[{"category.position":{"order":"asc","missing":"_last","unmapped_type":"string","nested_path":"category","mode":"min","nested_filter":{"nested":{"path":"category","score_mode":"none","query":{"terms":{"category.category_id":["98"],"boost":1}},"boost":1}}}},{"_score":{"order":"desc"}},{"entity_id":{"order":"desc","missing":"_first","unmapped_type":"string"}}],"from":0,"query":{"constant_score":{"filter":{"bool":{"must":[{"nested":{"path":"category","score_mode":"none","query":{"bool":{"must":[{"bool":{"must_not":[{"term":{"category.is_virtual":{"value":true,"boost":1}}}],"boost":1}},{"terms":{"category.category_id":["98"],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},{"terms":{"visibility":[2,4],"boost":1}}],"must_not":[],"should":[],"boost":1}},"boost":1}},"aggregations":{"categories":{"filters":{"filters":[]}},"option_text_collection_product":{"terms":{"field":"option_text_collection_product","size":10,"order":{"_count":"desc"}}},"option_text_classification":{"terms":{"field":"option_text_classification.untouched","size":10,"order":{"_count":"desc"}}},"option_text_colorfamily":{"terms":{"field":"option_text_colorfamily","size":10,"order":{"_count":"desc"}}},"option_text_size_name":{"terms":{"field":"option_text_size_name","size":20,"order":{"_count":"desc"}}}}}" ["headers"]=> array(3) { ["Host"]=> array(1) { [0]=> string(14) "127.0.0.1:9200" } ["Content-Type"]=> array(1) { [0]=> string(16) "application/json" } ["Accept"]=> array(1) { [0]=> string(16) "application/json" } } } `;

**Comment by afoucret** [comment]
Hi @vgrygor2,

What exact 2.5.x version are you using ?

**Comment by vgrygor2** [comment]
Hi @afoucret , 
I using v5.3.2.

**Comment by afoucret** [comment]
Think you should try to update to the latest 2.5.x stable version (2.5.8) since we fix some issues related to nested filters since 2.5.3.

BR,

**Comment by vgrygor2** [comment]
Ok, I'll try and reply to you. Thanks.

**Comment by vgrygor2** [comment]
Updated, 2.5.8 version now, the same error: 
`[2018-04-18 13:24:44] report.ERROR: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"child query must only match non-parent docs, but parent docID=4 matched childScorer=class org.apache.lucene.search.ConjunctionScorer"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"magento2_default_catalog_product_20180418_131852","node":"J1mJzDM9Qmq8jb7ZnihK1w","reason":{"type":"illegal_state_exception","reason":"child query must only match non-parent docs, but parent docID=4 matched childScorer=class org.apache.lucene.search.ConjunctionScorer"}}]},"status":500} [] []`

**Comment by vgrygor2** [comment]
After investigation it seems that the issue is with sortOrder building: vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/SortOrder/Builder.php buildSortOrder function, but I have no idea how to fix it). As a temporary solution we commented the following lines:
`//            if ($sortOrder->getNestedFilter()) {
//                $sortOrderConfig['nested_filter'] = $this->queryBuilder->buildQuery($sortOrder->getNestedFilter());
//            }`  
and products collection has been appeared. But I'm not sure that functionality is works correct after that fix).  
@afoucret , please advise.

**Comment by afoucret** [comment]
Hi @vgrygor2,

Can you please paste the code of \Smile\ElasticsuiteCore\Search\Request\Query\Filter\QueryBuilder::isNestedField present in your current setup ?

**Comment by vgrygor2** [comment]
Sure, in mentioned file (vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Request/Query/Filter/QueryBuilder.php) we have the following:
```
/**
     * @param FieldInterface $field       Filter field.
     * @param string|null    $currentPath Current nested path or null.
     *
     * @return bool
     * @throws \LogicException
     */
    private function isNestedField(FieldInterface $field, $currentPath)
    {
        $isNested = $field->isNested();

        if ($currentPath !== null) {
            if ($field->isNested() && ($field->getNestedPath() !== $currentPath)) {
                throw new \LogicException("Can not filter nested field {$field->getName()} with nested path $currentPath");
            }
            if (!$field->isNested()) {
                 throw new \LogicException("Can not filter non nested field {$field->getName()} in nested context ($currentPath)");
            }

            $isNested = false;
        }

        return $isNested;
    }
```

**Comment by afoucret** [comment]
Hi @vgrygor2,

I will try to dig in tomorrow.

BR,

**Comment by vgrygor2** [comment]
Hi @afoucret , 
Thanks you, let me know if you'll find something.

**Comment by vgrygor2** [comment]
I have analyzed my query and it supposed to be 
`"nested_filter":{"terms":{"category.category_id":["98"]}}}}` 

instead of
  
`"nested_filter": {
"nested": {
"path": "category",
"score_mode": "none",
"query": {
"terms": {
"category.category_id": [
"98"
],
"boost": 1
}
},
"boost": 1
}
}`
As example provided here https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-sort.html#nested-sorting

**Comment by vgrygor2** [comment]
It seems I have found an issue. In the file vendor/smile/elasticsuite/src/module-elasticsuite-core/Search/Adapter/Elasticsuite/Request/Query/Builder/Nested.php we have buildQuery function, which apply to nested filter the query with all parameters even if we already have parent query with nested path specified and we got described error. If I add additional condition to check if it is a child query and return just
 `$queryParams = [
       'query' => $this->parentBuilder->buildQuery($query->getQuery())
   ];`
it works as expected. Maybe it will help in further investigation.

**Comment by afoucret** [comment]
Hi @vgrygor2,

I am sorry but I am unable to reproduce this one.
At the same time we had a problem with packagist last week.
It is possible that you were not able to deploy the last bugfix version correctly (2.5.8).

Can you try to update your ElasticSuite version and give us a feedback : 
```
composer require smile/elasticsuite:2.5.8
```

**Comment by afoucret** [comment]
Hi @vgrygor2,

Any feedback ?

**Comment by afoucret** [comment]
Hi @vgrygor2,

I will close because we were not able to reproduce your issue and we have no feedback from you.
Feel free to reopen if you can share more detail on this one.
