### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by efimov-ivan** [Smile-SA/elasticsuite#884]
### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : 2.5.8

Environment : development

### Steps to reproduce

1. Created folder app/code/Smile
2. Paste folders: module-elasticsuite-catalog and module-elasticsuite-core
3. Enabled modules: php bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog
4. Next command: php bin/magento setup:upgrade

### Expected result

1. I need install module correctly

### Actual result

1. Return me error "Source class "\Smile\ElasticsuiteCore\Search\Request\Query\Query" for "Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory" generation does not exist."

<img width="569" alt="screen shot 2018-04-19 at 16 44 01" src="https://user-images.githubusercontent.com/5754338/38987291-fb4a4038-43f0-11e8-8db4-d4e7911175ce.png">

**Comment by afoucret** [comment]
The way you are installing the module is not correct (copying file). 
You have to use composer instead. 
That's way all dependencies of the module (like the elasticsearch client) will be installed.

I close since the way you are installing is not correct.
