### ISSUE TITLE
2.5.8 : Error during setup:upgrade

### ISSUE THREAD

**Issue by kanduvisla** [Smile-SA/elasticsuite#891]
I'm getting the following error during `bin/magento setup:upgrade`:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}
```

I'm using:

- Magento 2.2.3
- ElasticSuite 2.5.8
- ElasticSearch 5.6

Anyone knows what might be causing this issue?

**Comment by afoucret** [comment]
Hi @kanduvisla,

You have missed to install the analysis-phonetic plugin (and probably not the analysis-icu one) for ElasticSearch as explained in the [doc](https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-5.x) . 
If installed, maybe you did not restart ElasticSearch in order the change to take effect.

**Comment by kanduvisla** [comment]
Woopsie! Sorry I didn't RTFM ;-)
