### ISSUE TITLE
Does it work with AWS or not?

### ISSUE THREAD

**Issue by blueflykeelo** [Smile-SA/elasticsuite#895]
I have an ES 5.5.2 cluster running on AWS, Magento 2.2.3 CE, and smile elasticsuite 2.5....I am not able to run the magento upgrade due to the "no alive servers" error. I can curl the endpoint from the same instance just fine. Does this work with AWS or not?

Magento Version : 2.2.3 CE

ElasticSuite Version : 2.5

Environment : dev

**Comment by lingwooc** [comment]
Have you run

```
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/servers node-1:9200,node-2:9200
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_https_mode 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/enable_http_auth 0
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_user ""
bin/magento config:set -l smile_elasticsuite_core_base_settings/es_client/http_auth_pwd ""
bin/magento app:config:import
```

**Comment by blueflykeelo** [comment]
Yes, but with my AWS endpoint in the server list.

**Comment by blueflykeelo** [comment]
For anybody who can't figure this out....make sure you don't set your server host with http, or https. That was my issue. Make sure it's just domain:port
