### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by blueflykeelo** [Smile-SA/elasticsuite#897]
Just installed the module and everything seems to be working so far, but when I navigate to the categories page in the back office I get the following error which keeps the page from fully loading. The spinner never stops.

Uncaught TypeError: Cannot read property 'map' of undefined
    at UiClass.onProductListLoad (product-sorter.js:97)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)

Magento Version : 2.2.3 CE

ElasticSuite Version : 2.5

Environment : Dev

**Comment by JamesAllwood** [comment]
@blueflykeelo how did you resolve this?

**Comment by uhallac** [comment]
@blueflykeelo did you manage to fix this problem?

**Comment by JamesAllwood** [comment]
@uhallac - I managed to resolve this. The issue I had was that I'd migrated data with an install that included elasticsuite. When categories had been migrated, the install scripts that are included within the extension were't actioned, so a number of database changes were missing in the migrated data. To resolve, I removed the record from the setup table and forced elasticsuite to install again.

**Comment by uhallac** [comment]
@JamesAllwood - thank you! I had the same case. I did the following as you suggested:
- Disabled 8 Smile_ElasticSuite modules (using bin/magento module:disable)
- Removed 8 Smile_ElasticSuite related rows from the setup_module table
- Enabled 8 modules (using bin/magento module:enable)
- Ran the upgrade command (bin/magento setup:upgrade)

**Comment by volanar** [comment]
I have the same mistake and it did not help. Magento2.3.1, elasticsuite 2.8.0. Are there other fixes available?
Uncaught TypeError: Cannot read property 'map' of undefined
    at UiClass.onProductListLoad (product-sorter.js:212)
    at fire (jquery.js:3232)
    at Object.fireWith [as resolveWith] (jquery.js:3362)
    at done (jquery.js:9840)
    at XMLHttpRequest.callback (jquery.js:10311)
