### ISSUE TITLE
Feature Request: Bestseller & New Product Sort

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#899]
Magento Version : 2.2.3 CE
ElasticSuite Version : 2.5.8

Any chance of getting bestseller and new product sort added to elasticsuite? We are trying to work with a third party provider who has a premium extension that offers such functionality (to magento default sort) but there is ongoing conflicts. It would be nice to have native support.

**Comment by refueledinc** [comment]
Any chance of getting this added to the ES2.6.X roadmap?

**Comment by martijnrmediact** [comment]
Any news if this feature will be implemented soon?

**Comment by rav-redchamps** [comment]
Just released an extension https://github.com/redchamps/extra-sorting-options. This will add an option to sort by new products and it is fully compatible with ElasticSuite. 

The bestseller and many other options will be added soon to the extension. If anyone likes to contribute, please feel free to do so :-)

**Comment by refueledinc** [comment]
This feature request is now available here: https://redchamps.com/extra-sorting-options-magento-2-extension.html 

Thanks @rav-redchamps for making this possible. I'm going to close this.

**Comment by lbajsarowicz** [comment]
@refueledinc Unfortunately Redchamps made that extension paid, so their comment became promotional (spam).
