### ISSUE TITLE
Could you not directly access pricing tables when using autocomplete?

### ISSUE THREAD

**Issue by southerncomputer** [Smile-SA/elasticsuite#90]
I have added plugin to surround AroundGetPRice .. to replace pricing engine method with my own cost+plus rules. 

Since I did this plugin -> I notice autocomplete no longer responds with correct price!! just 0 which is odd since the index shows a valid price but I am guessing my modification to AroundGetPrice plugin is messing up  this call? Perhaps since I use optional-attribute 'cost' which has to be scoped to display in product_listing or it does not function/retrieve any cost! 0 

Or perhaps AutoComplete does not access attribute GetCost ->getdata('cost') in scope and retrieves cost of 0/null and my routines use that pricing level as cost multiplier!?

Any thoughts why auto-complete would only be affected by this?

**Comment by romainruaud** [comment]
Hello @southerncomputer 

Since we are calling ->addPriceData() on the $productCollection used when building the autocomplete results, Magento should pick the values from the index tables.

Could you give us an example of your plugin so we would be able to reproduce similar behavior.

Regards

**Comment by southerncomputer** [comment]
I worked around this issue using different plugin method to directly access database cost field! Thanks Please close issue
