### ISSUE TITLE
Manually re-saving a product removes it from the magento2_default_catalog_product index

### ISSUE THREAD

**Issue by Judder** [Smile-SA/elasticsuite#901]
Hi Smile Team

A strange one for you!

Manually creating products adds them correctly to the product Elastic index, and then they show in our categories

If we re-save them manually in the admin, changing any attribute or not, then they appear to be being removed from the index and no longer show in the category

Re-indexing produces a fresh index, but the products still don't show in the category

I've done some tests looking at the Elastic index count through the steps, and wondered whether these would throw any light onto what might be happening here?

BTW it could be one of our own custom extensions monitoring the same observers as this a big and relatively complex site, but we can't see anything obvious at the moment

Thanks!

_Before_

green  open   magento2_default_catalog_product_20180503_145226   F4U4tkgKRg-VS7OaWXUHoA   1   0      **46942**            0     38.2mb         38.2mb

_New product Save [shows in category]_

green  open   magento2_default_catalog_product_20180503_145226   F4U4tkgKRg-VS7OaWXUHoA   1   0      **46949**            0     38.2mb         38.2mb

_Edit product and Save [drops out of category]_

green  open   magento2_default_catalog_product_20180503_145226   F4U4tkgKRg-VS7OaWXUHoA   1   0      **46942**            0     38.2mb         38.2mb

_Reindex [still not showing in category]_

green  open   magento2_default_catalog_product_20180503_151041   agDGxhCJRl61fLrgrU378g   1   0      **46943**            0     38.2mb         38.2mb

**Comment by Judder** [comment]
Here's a test directly looking at the magento2_default_catalog_product index in Elastic

First search is directly after saving a new Simple product

Search is after manually changing the quantity from 999 to 998 and saving the product in the Magento admin system

I have tried deleting the index after this happens, and reindexing all of the indexes, but the product still doesn't get included - very strange!

![screen shot 2018-05-03 at 17 51 46](https://user-images.githubusercontent.com/40323/39591188-e810f006-4efa-11e8-8b05-bfcf1bb258ac.png)

**Comment by afoucret** [comment]
Hi @Judder,

We were not able to reproduce your issue at least for 2.5.x branch. As you said, it may be related to custom dev or third party extension. The only way for us to be sure would be to have an audit of your setup (part of our commercial support of the extensions).

I close for being not reproduced but feel free to reopen if you can can share more detail on how we can reproduce this bug.

**Comment by Judder** [comment]
We actually have worked this out. We had added the created_at attribute to the admin front-end, which caused an issue where when a product was saved, the created_at date was incorrectly set to '0000-00-00 00:00:00'

Elastic then ignored the product due to this

The fix (for the record) was to remove the attribute from the admin front-end but still allow it to be searchable (we use it for filtering) and update the records

`update catalog_product_entity set created_at = '2018-05-03 03:27:44' where created_at = '0000-00-00 00:00:00';`

**Comment by Judder** [comment]
Thanks for looking into it too BTW

**Comment by afoucret** [comment]
Suppose your data have been migrated ...

Thank your for the feedback.

**Comment by Judder** [comment]
This is where the team debugged it just for reference

`vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/Indexer/Category/Save/ReindexProductsAfterSave.php`
line 42

`vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/Indexer/AbstractIndexerPlugin.php` line 61
