### ISSUE TITLE
Disable categories in layered navigation

### ISSUE THREAD

**Issue by rikwillems** [Smile-SA/elasticsuite#904]
I have a list of filters on the left of my catalog which is topped by a filter for category. The attributes can be enabled/disabled but I cannot find the category list to be disabled. Am I missing something or is this a fixed element?

Regards, Rik

**Comment by afoucret** [comment]
Hi @rikwillems,

The category filter is a default one and can not be hidden.
We have no plan to change that. 

If you need it to be configurable by category, you can develop it by your own. I will be happy to read some code and to merge it if you think your implementation can improve ElasticSuite.

**Comment by rikwillems** [comment]
@afoucret we have the category navigation in a seperate block above the filters so it needs to go for this project. I'll work it out and submit a PR.
