### ISSUE TITLE
Change order HTML Autocomplete

### ISSUE THREAD

**Issue by guilhermengler** [Smile-SA/elasticsuite#922]
### Preconditions

Magento Version : 2.2.4

ElasticSuite Version : 2.5.0

Environment : Developer

Third party modules : No

### Steps to reproduce

I need to change the order of autocompelte content, today's Search Items - Products - Category.
I would like to know how I can handle this order.

Code from my default.xml file of the Smile_ElasticsuiteCore module:

```
<referenceBlock name="top.search">
            <arguments>
                <argument name="rendererList" xsi:type="array">
                    <item name="term" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Search terms</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCore/autocomplete/term</item>
                    </item>
                    <item name="category" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Categories</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/category</item>
                    </item>
                    <item name="product_attribute" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Attributes</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product-attribute</item>
                        <item name="titleRenderer" xsi:type="string">Smile_ElasticsuiteCatalog/js/autocomplete/product-attribute</item>
                    </item>
                    <item name="product" xsi:type="array">
                        <item name="title" xsi:type="string" translate="true">Products</item>
                        <item name="template" xsi:type="string">Smile_ElasticsuiteCatalog/autocomplete/product</item>
                    </item>
                </argument>
            </arguments>
        </referenceBlock>
```

### Expected result

1. Can change the order of autocomplete content.

### Actual result

![image](https://user-images.githubusercontent.com/6594313/40323180-fe98c68c-5d0a-11e8-8947-93bc682cf8f0.png).

**Comment by romainruaud** [comment]
Hello @guilhermengler 

If you feel comfortable with it, you can propose us a PR to fix this one (Eg : by adding a ``sortOrder`` field in XML declaration of the autocomplete providers).

Otherwise, we will have a look on this one.

Regards

**Comment by romainruaud** [comment]
I was actually looking how I could provide a PR for this one, but it seems actually doable just by defining the proper DI to ```Magento\Search\Model\Autocomplete``` like this (will display "Products", "Terms", "Category" then "Attributes") : 

```
    <type name="Magento\Search\Model\Autocomplete">
        <arguments>
            <argument name="dataProviders" xsi:type="array">
                <item name="20" xsi:type="object">Smile\ElasticsuiteCore\Model\Autocomplete\Terms\DataProvider</item>
                <item name="10" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\DataProvider</item>
                <item name="40" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Attribute\DataProvider</item>
                <item name="30" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Category\DataProvider</item>
            </argument>
        </arguments>
    </type>
```

Actually it's more a workaround than a proper fix since you must use the 10,20,30, and 40 keys that are already defined by Elasticsuite DI to override them and prevent duplicates. This is due to the legacy implementation of ```Magento\Search\Model\Autocomplete``` which is basically sorting the providers by their name and not checking if an object is defined twice.

Regards

**Comment by guilhermengler** [comment]
Hi @romainruaud!

Thanks for this solution, it suits what I need to do! :)

Regards.

**Comment by artmediastudio** [comment]
I tried it but without success
I want to put in autocomplete in second  position the Attribute autocomplete results.

This is my code
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
<type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig">
    <arguments>
            <argument name="additionalSelectedAttributes" xsi:type="array">
                <item name="artista" xsi:type="string">artista</item>
                <item name="formato" xsi:type="string">formato</item>
            </argument>
    </arguments>
</type>
  <type name="Magento\Search\Model\Autocomplete">
        <arguments>
            <argument name="dataProviders" xsi:type="array">
                <item name="20" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Attribute\DataProvider</item>
                 <item name="30" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Category\DataProvider</item>
                <item name="40" xsi:type="object">Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\DataProvider</item>
               
            </argument>
        </arguments>
    </type>
</config>
