### ISSUE TITLE
Virtual category based on rule shows parent and child products

### ISSUE THREAD

**Issue by romantomchak** [Smile-SA/elasticsuite#923]
Hi,

I have strange behavior with virtual category. 
I have 2 products: simple (sku product1) and bundle (with sku product2). Bundle product is a parent for simple product. All products have visibility catalog/search.
I have created virtual category based on rule: _SKU is one of product1, product20, product100500_ (as was described above product1 is sku of simple product). It means, that I want to show category only with one product (simple), but on frontend, on this category, both products (simple and bundle) are shown.
After some investigations, I found out that problem come from product sku value in ES. In ES bundle product document contains a list of skus (bundle sku + skus of all children products).
As bundle product contains all skus both products are matched by this rule and what's why both products are displayed in category. 

Could someone explain me the reason of adding all children products skus to the parent document?
This logic done in Smile\ElasticsuiteCatalog\Model\Product\Indexer\Fulltext\Datasource\AttributeData.

### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : 2.5.6

Environment : All

Third party modules :

### Steps to reproduce

1. Create simple product with sku product1
2. Create bundle product with sku product2 and add simple product product1 as child.
3. Create virtual category based on rule: _SKU is one of product1_

### Expected result

1. Only product1 is shown on category page.

### Actual result

1. Both, bundle and simple product are shown on category page.

**Comment by romainruaud** [comment]
Hello @romantomchak 

> Could someone explain me the reason of adding all children products skus to the parent document?

This allow to find parent products by typing a children SKU in search (could be useful for grouped or bundle products, more than for configurables).

Could you explain the reason of building a virtual category on an SKU condition ? If you plan to have a given list of products inside a category, you can just use the Magento legacy behavior and assign those products into the category by picking them in the grid.

Regards

**Comment by afoucret** [comment]
As explained by @romainruaud, it by design and A lot people ask us to ad children SKUs in order to improve search relevance (find by child SKU). 

We do not plan nothing to change this and you will have to workaround the default behavior (by example by adding a filter on the product type to get only configurable).

A explained by @romainruaud, if you are selecting individual SKU, using a normal category (not a virtual one) can also be the best option.

BR

**Comment by romantomchak** [comment]
Hi @romainruaud and @afoucret ,

thanks you for your detailed explanation. The case which I described in description  it is only simple example for better understanding.
I'm not saying that it is a bug, I just wanted to know if this is an additional feature or whether it is necessary for the some internal logic.

Your answers have fully explained the situation, thank you again.

Regards,
Roman
