### ISSUE TITLE
Issue with Elasticsuite tracking pixel 

### ISSUE THREAD

**Issue by duffner** [Smile-SA/elasticsuite#926]
### Preconditions

Public Server Setup:

- Varnish 5
- Ngnix
- PHP 7.1
- No CDN

Magento Version : 2.2.4 OpenSource (CE) 

ElasticSuite Version : 2.5

Environment : Production 

Third party modules : None now

### Steps to reproduce

1. Install Elastic Suite
2. Look at JS Console 

### Expected result

1. No 404 found on tracking pixel 

### Actual result

1. 404 on the following assest /elasticsuite/tracker/hit/image/h.png?page[store_id]=1&page[cms][identifier]=home&page[cms][title]=WitsEnd%20Mosaic&page[type][identifier]=cms_index_index&page[type][label]=CMS%20Home%20Page&session[uid]=bf4e4040-13ab-4d51-ffe9-ac6c05fa4f03&session[vid]=cbf30e97-f528-e5c2-893a-6546573d64dd&page[site]=dev.witsendmosaic.com&page[url]=%2F&page[title]=WitsEnd%20Mosaic&page[referrer][domain]=dev.witsendmosaic.com&page[referrer][page]=%2Fceramic-porcelain.html&page[resolution][x]=1440&page[resolution][y]=877

Added Later: 
After review, I found that this issue does not occur on my local environment with the follow specifications.  

- Apache 
- Nginx
- PHP 7.1 

<img width="1440" alt="screen shot 2018-05-24 at 9 14 39 pm" src="https://user-images.githubusercontent.com/7387019/40522643-84e5a974-5f97-11e8-9b88-229502293e35.png">

**Comment by romainruaud** [comment]
Hello @duffner 

This one is kinda strange, did you follow all installation step and properly clean up the cache ? (maybe the module route is not up to date).

Could you also give me some details, especially if you are using Varnish or any CDN in front of your magento instance ?

Regards

**Comment by duffner** [comment]
Thanks for the quick response!  @romainruaud, I followed all installation steps after a quick review it's definitely environment related.  

Server Setup: 

- Varnish 5 
- Ngnix 
- PHP 7.1 
- No CDN

**Comment by romainruaud** [comment]
Hmm... from what I am able to see from here, I guess the setup is the following : 

User query a page -> Nginx (serving https) -> Varnish (for caching) -> Nginx (will pass the request to PHP app).

If I try to access directly https://dev.witsendmosaic.com/elasticsuite/tracker/hit/image/h.png?page[store_id]=1&page[cms][identifier]=home&page[cms][title]=WitsEnd%20Mosaic&page[type][identifier]=cms_index_index&page[type][label]=CMS%20Home%20Page&session[uid]=bf4e4040-13ab-4d51-ffe9-ac6c05fa4f03&session[vid]=cbf30e97-f528-e5c2-893a-6546573d64dd&page[site]=dev.witsendmosaic.com&page[url]=%2F&page[title]=WitsEnd%20Mosaic&page[referrer][domain]=dev.witsendmosaic.com&page[referrer][page]=%2Fceramic-porcelain.html&page[resolution][x]=1440&page[resolution][y]=877 

I obtain a 404 error given directly by Nginx (not a nice Magento 404 error), so I tend to think the HTTP request does not hit neither Varnish nor Magento. 

This is probably something related to your nginx configuration (maybe something to handle *.png ?)

Could you try to check what differs between your dev.* environment and your local environment ?

**Comment by duffner** [comment]
@romainruaud, thanks for the advice - there's quite a bit different... But I think you're on to something. I'll follow up with my findings.

**Comment by afoucret** [comment]
Any update on this one ?

**Comment by duffner** [comment]
@afoucret, not yet.  I'll be jumping back into this project later today/ tomorrow

**Comment by romainruaud** [comment]
I close this one for being inactive for too long / too specific to your project.

Do not hesitate to open a new issue if you have any clues about this one.

Regards

**Comment by LiamKarlMitchell** [comment]
@powelles Thank you for the Nginx rewrite.
I could not seem to get it to work for some reason suspect Cloud Flare may have cached.

Should I add something like this and flush cloudflare?
```
        add_header Cache-Control "no-store";
        add_header X-Frame-Options "SAMEORIGIN";
        expires    off;
```
