### ISSUE TITLE
Extending classes and trying to plugin issue

### ISSUE THREAD

**Issue by Kershrew** [Smile-SA/elasticsuite#927]
### Preconditions
Magento Version : 2.2.4
ElasticSuite Version : 2.5.0
Environment : Production

### Steps to reproduce
1. Try to extend class from your code base, specify module to override and die()

### Expected result
1.  The script should die()

### Actual result
1. Nothing is effected, nothing dies

## Comment
Hello, I am trying to use Magento 2 with your plugin to extend a public method in a class in order to add an extra filter to the autocomplete quicksearch in the header.

I have found a suitable class which will enable me to do what I want:
Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Filter

in which I am attempting to override: prepareCollection() to add a filter for categories.

I have created a module which will succsessfully extend any class from the Magento core I throw at it and even classes from other extensions but whenever I extend one of yours it has literally no effect.
Even when I add a die(); it doesn't take effect.

So to try and get around that I have created a plugin to action before prepareCollection() and add the filter I want, this module again works with everything else I throw at it but when I try and extend this of your classes I am met with a 500 error.
I have added all the details of the plugin to this magento stackexchange question: https://magento.stackexchange.com/questions/227422/filter-interceptor-getting-added-to-end-of-argument-class-in-plugin

Do you guys have something in place that stops people from being able to use a plugin or preference with your code or am I missing something simple?

**Comment by romainruaud** [comment]
Hello @Kershrew 

According to the code example you provide in your stackexchange ticket, you are missing something.

Please have a look on official documentation about plugins : https://devdocs.magento.com/guides/v2.2/extension-dev-guide/plugins.html

The `before` plugin you wanna write should have 2 arguments : 

- the first being the "subject" of the Plugin : an instance of `Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Filter`
- the second argument should be the collection. 

But however, **there is no need to use a plugin to achieve what you want.**

ElasticSuite is accepting several objects for the Autocomplete collection provider, as you can see here : https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-catalog/etc/frontend/di.xml#L130

There are already 3 processors defined, feel free to add another one via the DI of one of your modules to achieve what you want.

Regards

**Comment by Kershrew** [comment]
My apologies, it was something small I was missing from that then!

I read the docs and from that example I thought the subject was the title of what was getting set, what a fool I am. Adding the necessary argument literally made it work perfectly. Thank you!

I saw mention of your proposed solution in your documents but I'm not sure how to achieve it, do I create a module with just a di.xml matching the same syntax as in the one you linked me and a Model?How do I pass the filter from the Model into the collection I want?

Your documentation on this process on the wiki tab is a bit lacking.

I very much appreciate your helpful comment thus far though!

**Comment by romainruaud** [comment]
Well actually you could have a DI like this : 

```xml
    <type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\Provider" shared="true">
        <arguments>
            <argument name="collectionProcessors" xsi:type="array">
                <item name="kershrew_filter" xsi:type="object">Kershrew\Module\Model\Autocomplete\Product\Collection\Filter</item>
            </argument>
        </arguments>
</type>
```

and then the PHP class could look like this : 

```php
class Filter implements Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\Collection\PreProcessorInterface
{
   
    /**
     * Append filters to the product list 
     *
     * @param ProductCollection $collection Product collection.
     *
     * @return ProductCollection
     */
    public function prepareCollection(ProductCollection $collection)
    {
        // Do what you want

        return $collection;
    }
}
```

**Comment by Kershrew** [comment]
Can I use a __construct() in that class to inject extra dependencies?

This is awesome, you've helped me out a lot thank you.

**Comment by romainruaud** [comment]
Yes sure you can inject dependency into this class, this is a class like any other in your Magento project !

I'm glad if I did help you, thank you for giving our module a try !

**Comment by Kershrew** [comment]
Thank you very much, this has just made my day :)

Your module is awesome, makes Magento so much better 👍
