### ISSUE TITLE
Error after magento 2.0.9 update

### ISSUE THREAD

**Issue by Fdec** [Smile-SA/elasticsuite#93]
Fatal error: Class 'Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Select' not found in /var/www/damartch/src/vendor/magento/framework/Code/Generator/EntityAbstract.php on line 331

**Comment by romainruaud** [comment]
Hello @Fdec . Issue should have been fixed by attached commit. Please ensure you are set to use dev-master and update. 

I close the issue.

Regards.
