### ISSUE TITLE
Unknown filter type [phonetic] for [phonetic]

### ISSUE THREAD

**Issue by wintermute-84** [Smile-SA/elasticsuite#944]
### Preconditions

Magento Version : CE 2.2.4

ElasticSuite Version : 5.4

Environment : production

### Steps to reproduce
1. Require "smile/elasticsuite": "^2.5"
2. Run setup:upgrade

### Actual result

 `{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [phonetic]"},"status":400}
`

I'm using elastic deployed via cloudways

**Comment by romainruaud** [comment]
Hello @wintermute-84 , you are missing the required plugins (phonetic and analysis-icu). Please refer to the documentation : https://github.com/Smile-SA/elasticsuite/wiki/ServerConfig-5.x#installing-required-plugins

You will have to ask your hosting provider if he is able to add these plugins to your elasticsearch instance.

Regards

**Comment by m9iqbal** [comment]
I'm also getting the same error and I'm pretty sure that I've both the plugins installed. Below is the out put of my `sudo bin/plugin list` command:

```
Installed plugins in /usr/share/elasticsearch/plugins:
    - analysis-icu
    - analysis-phonetic
```

I'm running ElasticSuite Version 2.3.5 with Magento EE 2.1.3

**Comment by lewisje** [comment]
You might need to kill and restart Java, if killing and restarting processes named `elasticsearch` doesn't work to load in the plugins.

**Comment by proffrink** [comment]
Sorry for the necro post but if anyone else Googles this in the future and finds it: The solution - on Cloudways at least - is restarting your Elasticsearch service.

**Comment by johnorourke** [comment]
Docker image which includes these plugins: https://hub.docker.com/r/getjohn/elasticsearch-docker

**Comment by tidypol** [comment]
if you are using opensearch you can relay on the warden docker images
https://hub.docker.com/r/wardenenv/opensearch/tags with those plugins https://github.com/wardenenv/images/commit/459cf3e9e63f85a4106b065f10e488cb4aa613c9

**Comment by romainruaud** [comment]
Or just use the Magento official image since they embed these plugins : magento/magento-cloud-docker-opensearch:2.4-1.3.5

**Comment by BergMedia** [comment]
Or go to: /usr/share/opensearch
`bin/opensearch-plugin install -b analysis-icu && bin/opensearch-plugin install -b analysis-phonetic`
