### ISSUE TITLE
Typo error in knockout template

### ISSUE THREAD

**Issue by mageho** [Smile-SA/elasticsuite#948]
Good afternoon,

I would like to notice you about a duplicate attribute at this line :
https://github.com/Smile-SA/elasticsuite/blob/79931eb7e32c8ef52f9812a4843cea12f5e71961/src/module-elasticsuite-catalog/view/frontend/web/template/attribute-filter.html#L29

Have a nice day,

Ilan PARMENTIER

**Comment by afoucret** [comment]
Hi @mageho,

Could you please try to provide us a PR on this one.
I would be glad to merge it.

BR,

**Comment by mageho** [comment]
Hello @afoucret,

I am not familiar with github for this point, but I did it anyway.

I am closing this issue.

Ilan PARMENTIER
