### ISSUE TITLE
Showing all products in specific category page when use sort by name or price 

### ISSUE THREAD

**Issue by Alizeinalzadeh** [Smile-SA/elasticsuite#949]
Showing all products in category page when use sort by name or price 

Magento Version : Magento CE, Version 2.2.2

ElasticSuite Version: 2.5.10

Environment : Developer mode

Third party modules: Magento Codazon fastest Theme

### Expected result
1. after you sort products by price or name in the specific category, products should load with ajax and show in the page.

### Actual result
1. Page has been refreshed and all site products (from all categories) shown in page after sort.

**Comment by afoucret** [comment]
Hi @Alizeinalzadeh,

Sorry but I was not able to reproduce the issue.
I suspect your custom theme to cause the bug and we do not provide support for third party themes as part of our community support commitment.

You should also try updating to 2.5.11.

Feel free to reopen if you can reproduce the issue using the luma theme.
