### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object

### ISSUE THREAD

**Issue by Hesoy** [Smile-SA/elasticsuite#951]
### Preconditions

Magento Version : 2.2.1

ElasticSuite Version : 2.5.11

Environment : developer

Third party modules : No

### Steps to reproduce

1. Open category catalog page

### Expected result

1. Category catalog page

### Actual result

1 exception(s):
Exception #0 (Exception): Warning: call_user_func_array() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in ../vendor/smile/elasticsuite/src/module-elasticsuite-virtual-category/Model/Layer/Filter/Category.php on line 153

I tried to use setup:upgrade, setup:di:compile, cache:flush but it's useless. I'm not using flat categories.

**Comment by afoucret** [comment]
In most case the bug is caused by a non running ES server.

**Comment by Hesoy** [comment]
@afoucret ES server is working

It's a response from ES
> {
>   "name" : "xI2VRPR",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "sb5XlIifQo-oh4Jj-Q75Cg",
>   "version" : {
>     "number" : "5.6.9",
>     "build_hash" : "877a590",
>     "build_date" : "2018-04-12T16:25:14.838Z",
>     "build_snapshot" : false,
>     "lucene_version" : "6.6.1"
>   },
>   "tagline" : "You Know, for Search"
> }

**Comment by afoucret** [comment]
By not running it can be misconfigured in Magento.

* Is all reindexed ?
* Do you have any indices and docs ?

You should also try to empty caches and code generated

**Comment by Hesoy** [comment]
Ok, I have found problem. It was my mistake, I had deleted attributes from `eav_attribute` table in MySql.
