### ISSUE TITLE
less @media-common: true issue

### ISSUE THREAD

**Issue by mageho** [Smile-SA/elasticsuite#952]
Good afternoon, 

Magento use one variable declared or not in styles-l / styles-m less stylesheet.
@media-common one.

This is a mandatory if your theme inherit from blank or luma theme from magento core.

If you do not check the boolean value for this variable, this is will output all stylesheet in styles-l and styles-m stylesheet, so for a standard magento website, or a theme which inherit blank or luma theme, the consequence is to have the css twice declared.

This is normal in your distribution ?

Ilan PARMENTIER

**Comment by afoucret** [comment]
PR #958 fix this behavior.
It will be merged in the master branch and release with version 2.6.0.

Thx for reporting.

BR
