### ISSUE TITLE
Can't add short_description in autocomplete results

### ISSUE THREAD

**Issue by mokadev** [Smile-SA/elasticsuite#953]
### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : 2.5

Environment : Developer

Third party modules :

### Steps to reproduce

1. Go to Attributes config form for "short_description"
2. Look for "is_displayed_in_autocomplete" field

### Expected result

1. Possibility to add this attribute to additionnals attributes that can be shown in the autocomplete template with the "is_displayed_in_autocomplete" field

### Actual result

1. the field "is_displayed_in_autocomplete" is not visible because it depends on the field "is_filterable_in_search" wish is a strange behavior. 

Did I missed something?

**Comment by afoucret** [comment]
Fear that you don't really undestand the purpose of this settings.

It allow to suggest attribute valuesin autocomplete.
In the following screenshot attribute material and color have been set to "is_displayed_in_autocomplete" : 

<img width="283" alt="capture d ecran 2018-06-15 a 10 01 30" src="https://user-images.githubusercontent.com/529238/41457232-48eed858-7083-11e8-9142-3533ba024f5f.png">

Having the short description suggested this way is a non sense and it seems that you want to be able to use short_description in the product template instead.

To do it you should add the short description to the Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig.
You can do it by creating a etc/frontend/di.xml file in your own module / namespace with the following content :

```xml
<type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig">
    <arguments>
            <argument name="additionalSelectedAttributes" xsi:type="array">
                <item name="short_description">short_description</item>
            </argument>
    </arguments>
</type>
```

**Comment by afoucret** [comment]
Think this issue can be closed because of the above response.

**Comment by mokadev** [comment]
Great!

You have an error in the code snippe , I had to add xsi:type="string" on the item tag (otherwise it will throw an error)

```xml
<type name="Smile\ElasticsuiteCatalog\Model\Autocomplete\Product\AttributeConfig">
    <arguments>
            <argument name="additionalSelectedAttributes" xsi:type="array">
                <item name="short_description" xsi:type="string">short_description</item>
            </argument>
    </arguments>
</type>`

Thank you!
