### ISSUE TITLE
 Class 'Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Select' not found

### ISSUE THREAD

**Issue by JohnnyXiang** [Smile-SA/elasticsuite#96]
Hi

I was trying to install the module but got class not found error. 

Fatal error: Class 'Smile\ElasticsuiteCatalog\Model\ResourceModel\Product\Fulltext\Select' not found in vendor/magento/framework/Code/Generator/EntityAbstract.php on line 331

please advise

Thanks

**Comment by romainruaud** [comment]
Hello @JohnnyXiang .

This seems to be a duplicate of #93 which occurs on Magento 2.0.9 only.

I am currently investigating on this one. Could you give me more precision about the version of Magento you are using ? Please also remember that if you are using Magento 2.1 you should not use dev-master of this module but the 2.2.x branch.

Regards.

**Comment by JohnnyXiang** [comment]
thank you for the prompt reply. yes, i am use Magento 2.0.9 and Elasticsuite 2.1.0

**Comment by romainruaud** [comment]
This has been fixed by the attached commit. Please move to dev-master to benefit the fix. I close the issue.

**Comment by JohnnyXiang** [comment]
thx
