### ISSUE TITLE
Display mode "Auto" in category layered navigation filters

### ISSUE THREAD

**Issue by VincentMarmiesse** [Smile-SA/elasticsuite#961]
Hello,

I'm not sure the Auto mode in category layered navigation filters is working as it should.

### Preconditions
Here is my setup:
* A category with 43 configurable products
* A filter named "Model" with 3 possibilites: Model 1, Model 2, Model 3
* 19 products are Model 1
* 15 products are Model 2
* 9 products are Model 3

In Layered Navigation Filters section, if I don't change anyting about the filters display mode, the filter is not displayed in front.
If I set it to "Always displayed", it works as intended.

Magento Version : CE 2.2.3

ElasticSuite Version : 2.5.11

Environment : Production mode

### Steps to reproduce

1. After having the same setup, just go on the category page

### Expected result

1. Filter "Model" should be displayed

### Actual result

1. Filter "Model" is not displayed

Is this the correct behavior? I check the documentation and it says

> The filter will be displayed according to its coverage rate. This is the standard behavior and will automatically hide filter if it's not really relevant (not covering enough products) for the category.

In my case, the filter covers 100% of the products.

Thanks for your help.

**Comment by afoucret** [comment]
Are you sure your category does not retrieve products from children category and these product does have the required attribute ?

**Comment by VincentMarmiesse** [comment]
Hi @afoucret,

I'm not sure I understand your question, but my products are in the category i'm currently on, not in a children one.
The products have the required attribute and I'm sure of it because when I set the filter to "Always displayed", all is working fine.

**Comment by afoucret** [comment]
Does you category have child categories and does these categories contain any product that does not have the required attribute ?

**Comment by VincentMarmiesse** [comment]
No, the category I'm on does not have any child.

**Comment by afoucret** [comment]
Can you please attach a screenshot of the category facet  config.

**Comment by bartek9007** [comment]
I have the same issue

**Comment by romainruaud** [comment]
We decided to dig a bit more on this one to dispell any doubts. I am not able to reproduce this issue, if I create a new attribute with "Used in Spellcheck=No", it appears properly on layered navigation with Auto mode. Same thing with "Used in Spellcheck=Yes".

I just spotted one thing that may explain the problem : when creating a new attribute, the attribute is not automatically added to the Elasticsearch mapping, so it does not appear on frontend.

Maybe we should invalidate the search index when creating a new attribute (or when modifying search related properties of an existing one).

Any thoughts @afoucret  ?

**Comment by romainruaud** [comment]
I close this one since it's resolved/inactive.

**Comment by bartoszkubicki** [comment]
I had same issue, but it turned out that this was configuration issue - I think I had a facet coverage on default level 90% and category products didn't reach that level. All works as expected.

**Comment by davinanaya** [comment]
@bartoszkubicki thanks! it worked, I was facing the same problem, I just changed the facet coverage because most of my products do not have the attribute set
