### ISSUE TITLE
Ability to install modules with external ES, or without ES

### ISSUE THREAD

**Issue by wintermute-84** [Smile-SA/elasticsuite#971]
Hi,
This is not exactly an issue. Suite works great when ES is installed before installing M2 modules on the same server.
However installing and running setup:upgrade without ES results in "No alive nodes found in your cluster"

1. Shouldn't it be possible to run suite with ES SaaS server?
2. For some instances it would be great to have other features, like virtual categories to be used on a site that does not need/have ES installed. Is it possible to install these features separately or at least without preconfigured ES?

thank you for any feedback.

**Comment by afoucret** [comment]
This have been responded multiple times.

All ElasticSuite modules are built on ElasticSearch features (eg : virtual categories are pure ElasticSearch queries, tracking data are indexed into ElasticSearch, ...) So installing is not possible without having a running ElasticSearch server.

You can configure it during magento install or using `bin/magento setup:config:set` command.
It allows to use any ElasticSearch server.

Hope it is more clear for you now.
