### ISSUE TITLE
Geo_shape mapping issue

### ISSUE THREAD

**Issue by alakhdeveloper** [Smile-SA/elasticsuite#972]
when i try to map geo_shape it showing me error message : mapper_parsing_exception: Mapping definition for [coordinates] has unsupported parameters:  [norms : {enabled=false}] [doc_values : true]
### Preconditions
I am using elasticsweet 2.3 and magento 2.1

Magento Version : CE Version 2.1

ElasticSuite Version :2.3

Environment : Developer

Third party modules :

my code in xml elasticsuite_indices.xml: 
field name="hyperlocal.sellerid" type="integer" nestedPath="hyperlocal" /
field name="hyperlocal.coordinates" type="geo_shape" nestedPath="hyperlocal" /

When i try to index it throwing error message: 
mapper_parsing_exception: Mapping definition for [coordinates] has unsupported parameters: [norms : {enabled=false}] [doc_values : true]

what i am missing in mapping xml code? Please help

### Expected result
I am trying to mapping like:
"hyperlocal" : {
"type" : "nested",
"properties" : {
"location" : {
"type" : "geo_shape"
},
"sellerid" : {
"type" : "integer"
}
}
}

### Actual result

1. [Screenshot, logs]

**Comment by afoucret** [comment]
Hi @alakhdeveloper,

`geo_shape` is not a type that is officially supoorted by ElasticSuite.
Indeed, your problem should not be present in newer version of ElasticSuite (from 2.5.0).

As your current version (2.3.x) is outdated, we don't provide community support for it. Please try to use a newer version of ElasticSuite for this issue.

**Comment by alakhdeveloper** [comment]
Thanks for your reply.

I have created new queryFactory for geo_shape.

That working fine. I am getting other issue is:
We need to combine two nested query EX:
stock.status =1 and visibility = 2
and ( geo_shape filterquery or geo_point filterquery)

right now all query working with "must". I need to use "should" with two query rest will work with "must".
Current query is :
Array
(
    [from] => 0
    [size] => 0
    [sort] => Array
        (
            [0] => Array
                (
                    [_score] => Array
                        (
                            [order] => desc
                            [missing] => _first
                            [unmapped_type] => string
                        )

                )

            [1] => Array
                (
                    [entity_id] => Array
                        (
                            [order] => desc
                            [missing] => _first
                            [unmapped_type] => string
                        )

                )

        )

    [query] => Array
        (
            [filtered] => Array
                (
                    [filter] => Array
                        (
                            [bool] => Array
                                (
                                    [must] => Array
                                        (
                                            [0] => Array
                                                (
                                                    [nested] => Array
                                                        (
                                                            [path] => category
                                                            [score_mode] => none
                                                            [query] => Array
                                                                (
                                                                    [bool] => Array
                                                                        (
                                                                            [must] => Array
                                                                                (
                                                                                    [0] => Array
                                                                                        (
                                                                                            [bool] => Array
                                                                                                (
                                                                                                    [must_not] => Array
                                                                                                        (
                                                                                                            [0] => Array
                                                                                                                (
                                                                                                                    [term] => Array
                                                                                                                        (
                                                                                                                            [category.is_virtual] => 1
                                                                                                                        )

                                                                                                                )

                                                                                                        )

                                                                                                )

                                                                                        )

                                                                                    [1] => Array
                                                                                        (
                                                                                            [terms] => Array
                                                                                                (
                                                                                                    [category.category_id] => Array
                                                                                                        (
                                                                                                            [0] => 42
                                                                                                        )

                                                                                                )

                                                                                        )

                                                                                )

                                                                            [must_not] => Array
                                                                                (
                                                                                )

                                                                            [should] => Array
                                                                                (
                                                                                )

                                                                            [minimum_should_match] => 1
                                                                            [boost] => 1
                                                                        )

                                                                )

                                                            [boost] => 1
                                                        )

                                                )

                                            [1] => Array
                                                (
                                                    [terms] => Array
                                                        (
                                                            [stock.is_in_stock] => Array
                                                                (
                                                                    [0] => 1
                                                                )

                                                        )

                                                )

                                            [2] => Array
                                                (
                                                    [terms] => Array
                                                        (
                                                            [visibility] => Array
                                                                (
                                                                    [0] => 2
                                                                    [1] => 4
                                                                )

                                                        )

                                                )

                                            [3] => Array
                                                (
                                                    [nested] => Array
                                                        (
                                                            [path] => hyperlocal
                                                            [score_mode] => none
                                                            [query] => Array
                                                                (
                                                                    [geo_shape] => Array
                                                                        (
                                                                            [hyperlocal.location] => Array
                                                                                (
                                                                                    [shape] => Array
                                                                                        (
                                                                                            [type] => point
                                                                                            [coordinates] => Array
                                                                                                (
                                                                                                    [0] => -118.37833469999998
                                                                                                    [1] => 34.09316029999999
                                                                                                )

                                                                                        )

                                                                                )

                                                                        )

                                                                )

                                                            [boost] => 1
                                                        )

                                                )

                                            [4] => Array
                                                (
                                                    [nested] => Array
                                                        (
                                                            [path] => storepickup
                                                            [score_mode] => none
                                                            [query] => Array
                                                                (
                                                                    [geo_distance] => Array
                                                                        (
                                                                            [distance] => 100mi
                                                                            [storepickup.location] => Array
                                                                                (
                                                                                    [lat] => 34.09316029999999
                                                                                    [lon] => -118.37833469999998
                                                                                )

                                                                        )

                                                                )

                                                            [boost] => 1
                                                        )

                                                )

                                        )

                                    [must_not] => Array
                                        (
                                        )

                                    [should] => Array
                                        (
                                        )

                                    [minimum_should_match] => 1
                                    [boost] => 1
                                )

                        )

                    [boost] => 1
                )

        )

    [aggregations] => Array
        (
            [attribute_set_id] => Array
                (
                    [terms] => Array
                        (
                            [field] => attribute_set_id
                            [size] => 0
                            [order] => Array
                                (
                                    [_count] => desc
                                )

                        )

                )

        )

)

The hyperlocal and storepickup query need to use with "should" instead of "must". How can i do this. Please help.

Thanks

**Comment by alakhdeveloper** [comment]
I get success to add the conditon mush and should both. 
 $filterQuery = $this->queryFactory->create(QueryInterface::TYPE_BOOL, ['must' => $queries,'should'=>$queriesGeo]);

Thats work..!!


Thanks
