### ISSUE TITLE
Loading problem on demo instance 

### ISSUE THREAD

**Issue by vipra93** [Smile-SA/elasticsuite#978]
### Preconditions

Magento Version :  demo instance http://demo.magento-elastic-suite.io

ElasticSuite Version :

Environment :

Third party modules :

### Steps to reproduce

1. Go to search terms
2. select "watch" term
3.go to "merchandiser"

### Expected result

1. Show drag and drop tool

### Actual result

1.infinite loading

**Comment by afoucret** [comment]
@romainruaud 

Think this have been fixed by the release 2.5.10.
Can you check the demo env is up to date.

**Comment by romainruaud** [comment]
Demo was still on 2.5.9

I updated it. The bug is now gone.

Regards
