### ISSUE TITLE
Layered Navigation Including Out Of Stock Products

### ISSUE THREAD

**Issue by JamesAllwood** [Smile-SA/elasticsuite#979]
Out of stock child products are included in the options available in the layered navigation

### Preconditions

Magento Version : 2.2.4 Open Source

ElasticSuite Version : 2.5.11

Environment : Production

Third party modules : Vanilla Installation

### Steps to reproduce

1. Create a config product with 3 size options (Small, Medium, Large)
2. Set "Small" variant to be in stock
3. Set "Medium" variant to be in stock
4. Set "Large" variant to be in **out of stock**
5. Assign product to category
6. Set size attribute to be filterable on the frontend

### Expected result

1. View the category on the frontend
2. Check layered navigation
3. "Large" should not be visible

### Actual result

1. View the category on the frontend
2. Check layered navigation
3. "Large" should is visible
4. I can filter on "Large"
5. Filtered results include parent with "Large" assigned
6. I visit that filtered product and see that "Large" is not a visible option

**Comment by JamesAllwood** [comment]
Possible relation to https://github.com/Smile-SA/elasticsuite/issues/809

**Comment by afoucret** [comment]
As explained in issue #809, this behavior is consistent with what Magento does out of the box.
@koc proposed a workaround that can fix your issue during indexing but we do not plan to integrate this in future, because it would be a backward compatibility issue and the behavior would change on existing websites.

I close since, this behavior is expected and consistent with Magento + there is a possible workaround.

**Comment by adamj88** [comment]
@afoucret just to address the BC issue - would it not be better to add configuration to enable/disable showing of out of stock products in the layered navigation and default to the current behaviour to avoid it? I believe @Koc requested this as well.

It seems as though it's a commonly requested feature which improves the out the box functionality as currently customers of the store are presented options in the filters which they're ultimately unable to purchase.

**Comment by afoucret** [comment]
@adamj88 

To be honest we have a lot of work with on other features of the project and we do not have much time to get this done.

I would be please to read some PR indeed.
