### ISSUE TITLE
Autocomplete : Special character rendering for Product Attribute

### ISSUE THREAD

**Issue by PierreLeMaguer** [Smile-SA/elasticsuite#981]
### Preconditions

Magento Version : 2.1.12

ElasticSuite Version : 2.3.11

Environment : Developer and Production

### Steps to reproduce

1. Create a product attribute and display it on autocomplete search.

### Expected result

1. The value is decoded and we have a correct rendering of special characters like '&'.

### Actual result

1. The value is not decoded and we can't show &. We actually show &amp;

This problem looks like #179 but the merged request does not correct the problem for product attributes. Maybe it is deliberate ?
If not, just add a html_entity_decode on vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Model/Autocomplete/Product/Attribute/ItemFactory.php l51 could be sufficient.

**Comment by afoucret** [comment]
Actually a templating issue.
Fixed by #982

**Comment by afoucret** [comment]
@romainruaud can you check the PR and merge it if everything is OK for you
