### ISSUE TITLE
Error No handler for type [text] declared on field [search]

### ISSUE THREAD

**Issue by juporag** [Smile-SA/elasticsuite#985]
### Preconditions

Magento Version : 2.2.4

ElasticSuite Version :2.4.6

Environment :

Third party modules :smile/elasticsuite 2.6

### Steps to reproduce

1. php bin/magento setup:upgrade 

### Expected result

1. Install ok

### Actual result
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"}],"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [search]"},"status":400}

1. curl -XGET 'localhost:9200'     

> {
>   "name" : "Mortimer Toynbee",
>   "cluster_name" : "elasticsearchr",
>   "cluster_uuid" : "ufenbBN8S969ElX-f0Hd6g",
>   "version" : {
>     "number" : "2.4.6",
>     "build_hash" : "5376dca9f70f3abef96a77f4bb22720ace8240fd",
>     "build_timestamp" : "2017-07-18T12:17:44Z",
>     "build_snapshot" : false,
>     "lucene_version" : "5.5.4"
>   },
>   "tagline" : "You Know, for Search"
> }
> 
2 . curl "localhost:9200/_nodes/settings?pretty=true"

> {
>   "cluster_name" : "elasticsearch_jporter",
>   "nodes" : {
>     "_5mE2wWcRq-6-1OqTnI6ZA" : {
>       "name" : "Mortimer Toynbee",
>       "transport_address" : "127.0.0.1:9300",
>       "host" : "127.0.0.1",
>       "ip" : "127.0.0.1",
>       "version" : "2.4.6",
>       "build" : "5376dca",
>       "http_address" : "127.0.0.1:9200",
>       "settings" : {
>         "name" : "Mortimer Toynbee",
>         "client" : {
>           "type" : "node"
>         },
>         "cluster" : {
>           "name" : "elasticsearch_jporter"
>         },
>         "path" : {
>           "data" : "/usr/local/var/lib/elasticsearch/",
>           "logs" : "/usr/local/var/log/elasticsearch",
>           "home" : "/usr/local/Cellar/elasticsearch@2.4/2.4.6_1/libexec"
>         },
>         "config" : {
>           "ignore_system_properties" : "true"
>         },
>         "script" : {
>           "inline" : "on",
>           "indexed" : "on"
>         }
>       }
>     }
>   }
> }
> 

3.log/elasticsearch_xxx.log

> [2018-06-26 19:57:09,514][WARN ][cluster.routing.allocation.decider] [Mortimer Toynbee] high disk watermark [90%] exceeded on [_5mE2wWcRq-6-1OqTnI6ZA][Mortimer Toynbee][/usr/local/var/lib/elasticsearch/elasticsearch_jporter/nodes/0] free: 17.5gb[7.5%], shards will be relocated away from this node
> [2018-06-26 19:57:09,520][INFO ][cluster.routing.allocation.decider] [Mortimer Toynbee] rerouting shards: [high disk watermark exceeded on one or more nodes]
> 

4.system.log

>  report.WARNING: Response ["{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"No handler for type [text] declared on field [search]\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"No handler for type [text] declared on field [search]\"},\"status\":400}"] []

^C

**Comment by juporag** [comment]
It is necessary to update the version of elasticsearch. 

> {
>   "name" : "wOtsEpy",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "K025Zp3nRzqQvtaS3ugWlg",
>   "version" : {
>     "number" : "6.2.4",
>     "build_hash" : "ccec39f",
>     "build_date" : "2018-04-12T20:37:28.497551Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.2.1",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }
> 

It works

**Comment by afoucret** [comment]
Be cautious. Version 2.6.x is not yet released and not considered as stable. Use it at your own risk.

Your right next version will drop support for elasticsuite 2.x
