### ISSUE TITLE
Not correct product search results

### ISSUE THREAD

**Issue by Neos2007** [Smile-SA/elasticsuite#995]
Sometimes in search suggestions block and search results displayed wrong/not correct results.
For example I type in search input first 2 letters of product name - in suggestion block I see correct products, then I type third letter and see in suggestion one product which doesn't has in his attributes letters combination that I type (and I do not see previous correct products ), type few more letters and see again correct suggestion results. 
In other cases  I start to type in search  input product name and do not see any results (or wrong results) until  almost completely entered the word of product name.
If click on search button during typing in search input  got same (not correct) results.

### Preconditions

Magento Version : 2.2.4

ElasticSuite Version : 2.4.3 (also tasted on 2.5.* version)

Environment : Developer, Production.

### Expected result

1. Search request "Fuß" must show in suggestion product with name Fußmatte "Hereinspaziert"
2. Search request "Land" must show in suggestion product with name Landlust - Kilcarra-Tweed-Knäuel

### Actual result

1.
![image](https://user-images.githubusercontent.com/17883826/42094626-0d0fbe88-7bb9-11e8-9e84-d8e19556ba3d.png)
![image](https://user-images.githubusercontent.com/17883826/42094679-3144a278-7bb9-11e8-95d9-19154a94743b.png)
![image](https://user-images.githubusercontent.com/17883826/42094703-41eeb4e2-7bb9-11e8-8b80-4f2a2b29482b.png)
![image](https://user-images.githubusercontent.com/17883826/42094726-5348398e-7bb9-11e8-824c-2ef4e6b1ef3b.png)

2. 
![image](https://user-images.githubusercontent.com/17883826/42094848-aeb75b2e-7bb9-11e8-97d3-31147e6c0acc.png)
![image](https://user-images.githubusercontent.com/17883826/42094922-d6613adc-7bb9-11e8-819d-33f6adb5e034.png)
![image](https://user-images.githubusercontent.com/17883826/42094941-e48b64b6-7bb9-11e8-832a-737a4456b718.png)

**Comment by afoucret** [comment]
From what I see you have disabled the popular searches suggestion.
The current implementation of both product and category suggestion relies on search suggestion. It should explain why you have results that seems not accurate.

We plan to refactor the implementation for better result in the future.

**Comment by romainruaud** [comment]
I'm closing this one since it's unclear/outdated.

Feel free to open a new issue with more details if you still want any help on this one.

Regards
