### ISSUE TITLE
Undefined class ScopeConfigInterface

### ISSUE THREAD

**Issue by DmitryFursMagecom** [Smile-SA/elasticsuite#996]
`use` operator missed in class [RelevanceConfig.php](https://github.com/Smile-SA/elasticsuite/blob/master/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php#L34)
You need to add the following `use Magento\Framework\App\Config\ScopeConfigInterface;`
Thanks!

**Comment by romainruaud** [comment]
Fixed by PR #1006 

Included in latest 2.5.14 release.

Thank you for reporting it.
