### ISSUE TITLE
"Catalog Search" indexer not working after upgrade elastic search to 2.5.13

### ISSUE THREAD

**Issue by pankajpragma** [Smile-SA/elasticsuite#997]
### Preconditions

Magento Version : 2.2.2

ElasticSuite Version : 2.5.13

Environment : Developer

Third party modules : No

### Steps to reproduce

1. I have upgrade elastic search version form 2.5.9 to 2.5.13.
2. After the upgrade, I have run the full indexing.
3. But "Catalog Search" indexer produces the error.

### Expected result

1. "Catalog Search" indexer should be working as like others.

### Actual result

1. https://screenpresso.com/=5EVCb

**Comment by moejoee91** [comment]
Same here, magento 2.2.4 with the same issue

**Comment by romainruaud** [comment]
Please @pankajpragma  and @moejoee91 if you are using Magento < 2.2.5, rollback to Elasticsuite 2.5.12.

Elasticsuite 2.5.13 is here only to bring compatibility with latest Magento version and has been shipped fastly to ensure we were not preventing our customers to update their Magento website.

If you are still using a lower version of Magento, there is no need for you to rush on the latest elasticsuite version.

We'll try to publish soon another minor version bringing support of Magento 2.2.5 AND backward compatibility.

Regards

**Comment by romainruaud** [comment]
We added backward-compatibility to the latest 2.5.14 version of Elasticsuite.

You can switch to this version that is compatible both with Magento 2.2.5 and also with prior 2.2.x versions.

Regards
