### ISSUE TITLE
Unable to deploy elasticsuite to Magento Cloud environment

### ISSUE THREAD

**Issue by akilirw** [Smile-SA/elasticsuite#999]
### Preconditions
Attempting to install Elasticsuite on Magento Cloud environment.

Magento 2.1.7 EE
ElasticSuite 2.3.11
Elasticsearch 2.4
Environment : Production mode

### Steps to reproduce
1. Add `"smile/elasticsuite": "^2.3.0"` to composer.json file. (`composer require smile/elasticsuite`)
2. Follow the instructions from these documentation pages:
    - https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall
    - https://devdocs.magento.com/guides/v2.1/cloud/project/project-conf-files_services-elastic.html
3. Commit changes and push to cloud branch or staging environment.

### Expected result
1. Elasticsuite is installed

### Actual result
1. Elasticsuite fails to install. 

When **setup:upgrade** gets to **Smile_ElasticsuiteCatalog** it attempts a reindex during install data in **vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Setup/InstallData.php** line 107:
`$this->getIndexer('elasticsuite_categories_fulltext')->reindexAll();`

and it also tries to reindex when it gets to:
**vendor/smile/elasticsuite/src/module-elasticsuite-thesaurus/Setup/InstallData.php** line 57:
`$this->getIndexer('elasticsuite_thesaurus')->reindexAll();` 
Which causes the deployment to fail. I thought maybe it was due to the var/generation folder permissions but that isn't everything that is happening.

Elasticsearch is installing properly and the necessary plugins are installed on the integration branches. If I patch the elasticsuite module and comment out:
`$this->getIndexer('elasticsuite_categories_fulltext')->reindexAll();` 
and 
`$this->getIndexer('elasticsuite_thesaurus')->reindexAll();` the modules install to the database correctly. 

When I go back to reindex, `elasticsuite_categories_fulltext` and `elasticsuite_thesaurus` still fail and I get the following error:
```
ElasticSuite Thesaurus Indexing indexer process unknown error:
No alive nodes found in your cluster
```

Which usually means that the elasticsearch service isn't running, but that isn't true:
```
$ curl -i elasticsearch.internal:9200/_cluster/health?pretty=true
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 466

{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 9,
  "active_shards" : 9,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

Obviously all the indices aren't present here because it needs to be reindexed:
```
$ curl -i elasticsearch.internal:9200/_cat/recovery
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 945

magento2_product_7_v1 0 68  store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_8_v1 0 80  store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_9_v1 0 164 store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_3_v1 0 95  store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_4_v1 0 113 store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_6_v1 0 148 store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_5_v1 0 97  store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_2_v1 0 57  store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0 
magento2_product_1_v1 0 297 store done 248.0.129.143 248.0.129.143 n/a n/a 0 0.0% 0 0.0% 0 0 0 100.0% 0
```

The plugins are installed:
```
$ curl -i elasticsearch.internal:9200/_cat/plugins
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 112

Nth Man: the Ultimate Ninja analysis-icu      2.4.6 j  
Nth Man: the Ultimate Ninja analysis-phonetic 2.4.6 j 
```

And if it's set to elasticsearch instead of elasticsuite and I test the connection in the admin, I get the success message.

I was also getting this error on categories on the frontend:
```
The specified "/app/var/generation/Smile/ElasticsuiteCore/Search/Request/Query/BooleanFactory.php.794" file could not be written Warning!file_put_contents(/app/var/generation/Smile/ElasticsuiteCore/Search/Request/Query/BooleanFactory.php.794): failed to open stream: Read-only file system
```

I tried adding the `GENERATED_CODE_SYMLINK = disabled` environment variable but it didn't make a difference when I deploy. Now I just get the `No alive nodes found in your cluster` error on the frontend on categories.

Also I've set the `SEARCH_CONFIGURATION` variable to elasticsuite but it still sets it to elasticsearch in the config.php when I deploy.

I'm not really sure where to go from here. I was easily able to setup the extension on my local Vagrant machine and also on an AWS EC2 instance but I can't figure out how to deploy to the cloud branches. Deploying to cloud staging environment is a whole other problem too. I think in that case it's because the analysis plugins aren't installing during deployment and I can't get rid of the read-only problems with var/generation the same way on staging. If I remove the var/generation folder and then reindex, I get:
```
ElasticSuite Category Indexing indexer process unknown error:
RemoteTransportException[[Morgan Le Fay][inet[/192.168.7.7:9300]][indices:admin/create]]; nested: IndexCreationException[[magento2_default_catalog_category_20180703_205200] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find token filter type [phonetic] for [phonetic]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [phonetic]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.phonetic.PhoneticTokenFilterFactory]; 
```
because the plugins are not installed. And the other index actually _does_ reindex:
`ElasticSuite Thesaurus Indexing index has been rebuilt successfully in 00:00:02`

I've read through a few other issues on here and none of them helped me to solve my problem. Are there more steps missing from the documentation in the links posted above that I'm not doing?

**Comment by romainruaud** [comment]
Hello @akilirw 

since you are using old versions of Magento and Elasticsuite, please try to use the "deprecated" version of MECE configuration as described here : https://github.com/Smile-SA/elasticsuite/wiki/MeceInstall#deprecated-solution--by-using-a-module-embedding-the-configuration

You should also ensure that the search engine which is selected in your Magento configuration is "Smile Elasticsuite", because seeing indexes named "magento2_product_v**" is telling me that the standard Magento Elasticsearch implementation is building these indexes. Elasticsuite indexes are named with an horodated timestamp.

Let me know,

Regards

**Comment by akilirw** [comment]
Yea I tried adding the configuration via a custom module already with no luck. 

There actually aren't any indices being created on the integration branch because I'm unable to reindex.

On our staging environment I am able to reindex elasticsuite_thesaurus but not elasticsuite_categories_fulltext. So I do see the correctly named magento2_default_thesaurus_20180703_205207 index there. I think the problem there has to do with the elasticsearch plugins not being installed so I'm working with Magento support to install them on our staging and production environments.
